### ISSUE TITLE
Constraint tasks on name?

### ISSUE THREAD

**Issue by isabellaalstrom** [grocy/grocy#1001]
```
"error_message": "SQLSTATE[23000]: Integrity constraint violation: 19 UNIQUE constraint failed: tasks.name"
```
I understand from this error message that tasks has to have unique names. I would suggest that to be true only if the task is not yet marked as done - or if one tries to make a task with the same name as another task that already exists, it should overwrite that task with the new one. It's very often that a task name is not unique for all eternity, I think. Couldn't find any information or another issue about the same thing.

**Comment by berrnd** [comment]
The UNIQUE CONSTRAINT is now removed, so multiple tasks can have the same name now.
