### ISSUE TITLE
Migration 0103 fails if products have been deleted but exist at stock_log (NOT NULL constraint failed)

### ISSUE THREAD

**Issue by afv** [grocy/grocy#1002]
When there are rows at `stock_log` with a product ID that does not exist at `products` (product deleted), the migration 0103 fails:

> **Type:** PDOException
> **Code:** 23000
> **Message:** SQLSTATE[23000]: Integrity constraint violation: 19 NOT NULL constraint failed: stock_log.qu_factor_purchase_to_stock
> **File:** /srv/grocy/grocy/services/DatabaseService.php
> **Line:** 35

It happens at line 10:

```sql
UPDATE stock_log 
SET qu_factor_purchase_to_stock = (SELECT qu_factor_purchase_to_stock FROM products WHERE product_id = id);
```

And at the next run, it will fail with

> **Message:** SQLSTATE[HY000]: General error: 1 duplicate column name: qu_factor_purchase_to_stock

as it already added the columns.

***

Suggested fix (add `where` clause with `exists` condition):

```sql
UPDATE stock_log
SET qu_factor_purchase_to_stock = (SELECT qu_factor_purchase_to_stock FROM products WHERE product_id = id);
WHERE EXISTS (SELECT qu_factor_purchase_to_stock FROM products WHERE product_id = id);
```

Or maybe the problem is that those `stock_log` rows should have been deleted when the products were deleted?

Thanks!

**Comment by afv** [comment]
Got another constraint violation, at `INSERT INTO product_barcodes`:

> Abort due to constraint violation (UNIQUE constraint failed: product_barcodes.barcode)

Somehow I had two products with the same barcode. :sweat_smile:

**Comment by berrnd** [comment]
Products can be archive instead of being deleted since #565.

So I think it's ok to delete all `stock_log` rows for not existing products in that migration - will add that.
