### ISSUE TITLE
Bug (?): Custom conversion becomes 0

### ISSUE THREAD

**Issue by darkspirit510** [grocy/grocy#1003]
I'm not sure if this is a bug or misusing, so I'll just post it here and see if someone can help me. The following case can be reproduced using the demo.
 
- Create two quantity units (piece and gram)
- Create a product (cucumber) with default unit (piece) and a custom conversion (let's say 100 gram)
- Create a recipy using the product and use an amount of the custom conversion below one piece (50 gram)

Actual: The product is stored (even with the custom value if you edit it) but the displayed amount is 0 pieces/0 gram. The 0 pieces is also used for stock.
Expected: The ingredients list shows and uses the correct value for stock

Edit: Additional information: Running grocy 2.7.1 [linuxserver/grocy](https://hub.docker.com/r/linuxserver/grocy) with docker

**Comment by berrnd** [comment]
Is reproducible on the current stable demo, but already works on current master (see the [pre-release demo](https://en.demo-prerelease.grocy.info)).

Most probably fixed by #801.
