### ISSUE TITLE
Move supplies to another location?

### ISSUE THREAD

**Issue by Saturo78** [grocy/grocy#1004]
How can I move some of the supplies units to another storage location?

**Comment by berrnd** [comment]
The better place for generic questions is the [subreddit](https://github.com/grocy/grocy#questions--help--bug-reporting--feature-requests), as [mentioned in README](https://github.com/grocy/grocy#questions--help--bug-reporting--feature-requests).

That's what the "Transfer" page is for (left menu): https://demo.grocy.info/transfer

Or just edit the corresponding stock entry: https://demo.grocy.info/stockentries
