### ISSUE TITLE
Feature Request: 

### ISSUE THREAD

**Issue by LexPagani** [grocy/grocy#1006]
Hy Bernd,
Bin vor kurzem auf dein Projekt gestoßen und bin sehr begeistert von deiner Idee und dem aktuellen Projektstand.
Kurz zum Hintergrund des Feature-Requests: Da eines meiner Hobbys Prepping (ja das kann man auch als Hobby betreiben) ist, hab ich in den letzten Jahren auch einen sehr großen Vorrat an Lebensmitteln angehäuft (zZ ca. ein 2-Jahres-Vorat) den ich auch „pflegen“ muss. Hierbei kommt auch ein Rotationsprinzip zur Anwendung, mit dem ich dich nicht langweilen möchte, um die am frühesten ablaufenden Lebensmittel am weitesten vorne zu lagern um sie auch als erste verbrauchen zu können (nennt sich First-In/First-out oder FIFO; kannst du gerne bei Bedarf auch nachlesen, ist interessant).
Und so habe ich auch mit deinem Projekt Freundschaft geschlossen. Da ich jedoch trotzdem auch eine „analoge“ Liste auf meinen Lagerboxen mitführt, ist hier ein entscheidender Punkt, der mir hier fehlt. Es ist möglich eine Bestandsliste auszudrucken die auch Platz für Notizen und „konsumierte“ Artikel bietet. Jedoch wäre es hierbei auch interessant wenn man auch das Mindesthaltbarkeitsdatum bzw. andere „Tags“ auf dieser Liste mitdrucken könnte.
Wäre toll, wenn dieses Feature irgendwann in der Zukunft auch erscheint.
Bis dahin,
Alles Gute!

**Comment by berrnd** [comment]
Hier ist sicher Englisch besser, damit jeder mitlesen kann - aber es geht ja an sich nur um eine Frage, also belasse ich es auch mal bei Deutsch:

_(It's only about a question, so I'll continue in German for now.)_

> um die am frühesten ablaufenden Lebensmittel am weitesten vorne zu lagern um sie auch als erste verbrauchen zu können (nennt sich First-In/First-out oder FIFO; kannst du gerne bei Bedarf auch nachlesen, ist interessant).

Ja, find ich auch interessant, von daher macht das grocy per Default genau so, sofern beim Verbrauch kein abweichender Bestandseintrag manuell ausgewählt wird.

![grafik](https://user-images.githubusercontent.com/2161815/93773126-fdc5b600-fc1f-11ea-91db-18cc67e09ad4.png)

https://github.com/grocy/grocy/blob/4b5b7bcb19a149b4ff5aaed136ed766ca978f5e9/services/StockService.php#L591-L594

> Es ist möglich eine Bestandsliste auszudrucken die auch Platz für Notizen und „konsumierte“ Artikel bietet. Jedoch wäre es hierbei auch interessant wenn man auch das Mindesthaltbarkeitsdatum bzw. andere „Tags“ auf dieser Liste mitdrucken könnte.

Ist bereits in #622 vermerkt, ergänze gerne dort, wenn noch was fehlt.

**Comment by LexPagani** [comment]
Thanks for fast respond!
I‘m sorry, I‘m not familiar with this (actually my first issue/request on GitHub/ever).
#622 is exactly what im looking for. Thanks. Looking foward to this feature!
