### ISSUE TITLE
Android Phone cannot Connect to server keeps saying API Key Not working.

### ISSUE THREAD

**Issue by nsamuel76** [grocy/grocy#1007]
I cannot get to connect to my Android keeps saying API key is not working.  I have tried making new Keys copy paste and cannot get it to work. 
I also cannot figure out how to configure it to connect by https I have it installed on a QNAP TS-431P

**Comment by berrnd** [comment]
This is the repository of grocy itself, which provides only a web UI, no API keys needed - so you probably use one of the grocy companion apps.

So please post this at the right place, maybe best on the [subreddit](https://www.reddit.com/r/grocy/), as this is most probably not an issue.
