### ISSUE TITLE
Port Change and HTTPS not working

### ISSUE THREAD

**Issue by nsamuel76** [grocy/grocy#1008]
How can I reconfigure it to use a different port and I cannot figure out how to get it to work by HTTPS I have it installed on a QNAP TS-431P

**Comment by berrnd** [comment]
Please use the [subreddit](https://www.reddit.com/r/grocy/) for general questions as [mentioned in README](https://github.com/grocy/grocy#questions--help--bug-reporting--feature-requests), thanks.
