### ISSUE TITLE
Installation Error

### ISSUE THREAD

**Issue by Saturo78** [grocy/grocy#1009]
I get the following error message: 

Unable to run grocy: config-dist.php not found. Please do not remove this file.

And yes there is no config-dist-php because i have renamed it to config.php
What could i do to resolve this issue?

**Comment by Saturo78** [comment]
ah okay, it has to be placed in the grocy folder.
Now i get the following error message:

`Slim\Exception\HttpNotFoundException
Code: 404
Message: Not found.
File: /home/web3jijjr/html/Grocy/vendor/slim/slim/Slim/Middleware/RoutingMiddleware.php
Line: 93`

**Comment by berrnd** [comment]
As mentioned yesterday in #1004 and still [mentioned in README](https://github.com/grocy/grocy#questions--help--bug-reporting--feature-requests), please use the [subreddit](https://www.reddit.com/r/grocy/) for general questions, this is most probably not an issue and this is the issue tracker, thanks.

I would also recommend to check the (simple) instruction, also [mentioned in README](https://github.com/grocy/grocy#how-to-install), first - nobody said you should rename `config-dist.php`, but more copy the file to `data/config.php` and edit to your needs.

Everybody recommends using the Docker containers, if the manual installation is too complex for you.

For that specific error (404), please also first search the issues here, the subreddit or check [grocy.info/links](https://grocy.info/links), this comes up maybe the second time...

https://github.com/grocy/grocy/issues/694#issuecomment-609079721

https://github.com/grocy/grocy/issues/694#issue-592850273

https://www.reddit.com/r/grocy/comments/g17lbo/trying_to_run_grocy_from_a_subdirectory/

**Comment by Saturo78** [comment]
Sorry, i read all the threads and tried this for hours but i could not find a solution.
Also the instructions in the readme are not very helpful.

**Comment by berrnd** [comment]
Then please provide more information and I'm sure someone picks this up immediately on the subreddit to help you.

Most probably you run this in a (webserver) subdirectory. What webserver? Is URL rewriting enabled? What's the root path?
Nobody can guess this by the error message you provided...

**Comment by Festeazy** [comment]
send me a PM on Reddit and I can help

u/festeazy
