### ISSUE TITLE
Docker Hub

### ISSUE THREAD

**Issue by pixelyo** [grocy/grocy#101]
for updates it would be convenient to just pull the images from the docker hub :)

**Comment by berrnd** [comment]
"Forwarding" this to @talmai (he did the Docker things).

@talmai would it be maybe better to separate the grocy Docker integration into a separate repository? There is also already [grocy-desktop](https://github.com/berrnd/grocy-desktop), so maybe it's time to create a organization for grocy and place these repository under that organization then - let me know if you would like to maintain such a "grocy-docker" repo, would be great. :)

**Comment by talmai** [comment]
yep, I could help with that. We can make it so that it is an automated build when things are merged to master. Reminder: you'd have to create org here on GitHub, and also one on docker hub.

**Comment by berrnd** [comment]
Ok, Docker Hub org and repo is also ready and you should have received an invitation.
https://hub.docker.com/r/grocy/grocy-docker

The `master` branch is currently the development branch, I consider stable the latest tagged commit. If you need a branch and cannot use the latest tag automatically, we could also add a `stable` (or other name) branch which will be merged from master on every release in the future.

**Comment by talmai** [comment]
https://github.com/grocy/grocy-docker tested and updated. Instructions there.

@berrnd can you remove all docker stuff from this repo and point there?

/docker_nginx folder
.dockerignore
docker-compose.yml
Dockerfile-grocy
Dockerfile-grocy-nginx

And update the README.md?

**Comment by berrnd** [comment]
Great, thanks! :)

> can you remove all docker stuff from this repo and point there?

WIll do this, then this can be closed.
