### ISSUE TITLE
Recipe picture upload does not work

### ISSUE THREAD

**Issue by renarena** [grocy/grocy#1010]
after adding image does not exist: https://en.demo-prerelease.grocy.info/recipe/7

**Comment by berrnd** [comment]
Recipe picture image upload seems to be broken in general for pre-release / current master.

If you have problems with Umlaute only, check your browser (see #916).

**Comment by renarena** [comment]
I use grocy 2.7.1 on linux FF 68 with several privacy addons, not sure, what to do (beside renaming images)
