### ISSUE TITLE
Is “purchase quantity unit” still necessary with v3.0

### ISSUE THREAD

**Issue by Festeazy** [grocy/grocy#1011]
I'm looking at the prerelease and am wondering if the PQU is still needed now that the purchase conversion is now handled via the barcodes?

I'm seeing many cases the PQU and SQU would be the same unit

**Comment by berrnd** [comment]
> I'm seeing many cases the PQU and SQU would be the same unit

Sure, most probably that's true for most cases.

It's just displayed there for info.
#947 is still open to also make it possible to pick any (for the product configured) QU on purchase.
And not everybody picks products by scanning barcodes...
