### ISSUE TITLE
parent item when child items are purchased

### ISSUE THREAD

**Issue by Festeazy** [grocy/grocy#1014]
Let's say I have a parent product in a shopping list for "paper towel"
I think if I purchase any of its child-products (paper towers brand A), it should remove the parent products from the shopping list.

Actually any item that is purchased should be removed from the shopping list if it's on there

**Comment by berrnd** [comment]
That's already done when you add the item directly from the shopping list, that button:

![grafik](https://user-images.githubusercontent.com/2161815/94195609-88721380-feb3-11ea-9771-a326122fcb52.png)

Also possible with all items (one after another, but without having to click through each single item) with the button "Add all items to stock" in the header.

**Comment by berrnd** [comment]
> Actually any item that is purchased should be removed from the shopping list if it's on there

That doesn't really make sense since grocy has multiple shopping lists.

Closing this, the button(s) mentioned above to add a single or all shopping list entries to stock still work.
