### ISSUE TITLE
purchase/inventory/consume in QU conversion unit.

### ISSUE THREAD

**Issue by Festeazy** [grocy/grocy#1015]
Hello. I'd like to start off by saying thank you. Genuinely I mean that.

Feature Request/Improvement:

I think it could be very efficient to be able to purchase/consume/inventory in all available QU Conversions for that product.

My library is set up a little different than yours where my stock units are set to the lowest unit. This mean OZ for me in the states.

For barcodes, it would be easy to simply apply the correct conversion rate and scan the barcode, but you mentioned in another ticket that a lot of people also do it manually.
I think people would benefit from being able to set item specific conversion units and then use them when interacting with them.

for stock unit 1L milk is equal to 1Bottle milk and then be able to purchase/consume/inventory in those bottles. 

Since 1L is set as the stock unit, we keep all the default metadata stock units conversions in the products while still being able to interact with other familiar units.

**Comment by berrnd** [comment]
> Hello. I'd like to start off by saying thank you. Genuinely I mean that.

My pleasure, thanks also for your "Intro" writing and the rest on the subbredit, great. :)

It's planned to make it possible to use any product-related QU at any place in the UI (currently already and only possible when adding recipe ingredients, but there is already a UI-component `productamountpicker` for it, so it's only to use that "everywhere").

Already started in #947, I found no corresponding issue, so I'll link that one here.

**Comment by tcjdesign** [comment]
I'm super glad to see this is being worked on. I just discovered Grocy, and to see the one issue I had setting it up already on its way to be resolved is awesome.

**Comment by Festeazy** [comment]
so happy!
