### ISSUE TITLE
feature request: printable journals

### ISSUE THREAD

**Issue by Festeazy** [grocy/grocy#1016]
not much to explain here, not even that big of a deal. 
printable chore and stock journals could be useful and may be easy to add. 
I'm imagining something similar to the "Location Content Sheet"

**Comment by berrnd** [comment]
Or maybe a generic approach to make any page printable (probably doable with just some CSS stuff).

**Comment by berrnd** [comment]
Unless where it could be really useful (like the shopping list or the location content sheet), I don't think we need to optimize _everything_ to be printed, because why does a journal need to be printed...

So closing this for now.
