### ISSUE TITLE
undefined variable on product page (when FEATURE_FLAG_STOCK_PRICE_TRACKING is disabled)

### ISSUE THREAD

**Issue by darkspirit510** [grocy/grocy#1017]
I'm using master state from grocy. I can't delete custom conversions for products. Sadly this is not reproducible in prerelease demo (or at least I don't know what I did to break it 😅)  The following error occurs on load.

```
Uncaught TypeError: i is undefined
    jQuery 15
    <anonymous> http://server/viewjs/productform.js?v=2.7.1:395
jquery.dataTables.min.js:24:465
```

Clicking on the delete icon does not do anything. I can delete conversions using postman, so it's not the API. Any idea about this?

**Comment by berrnd** [comment]
The master branch is not considered "stable", so far in general the basics always worked, but since the last release a lot has changed which still needs some detail-polish...

However, I just tried that on the pre-release demo and deleting a conversion on the product edit page worked. Also on the referenced line (`productform.js:395`) I find no variable named `i`... (?)

**Comment by berrnd** [comment]
As mentioned by @fipwmaqzufheoxq92ebc in #1018 this happens when `FEATURE_FLAG_STOCK_PRICE_TRACKING` is disabled.
@darkspirit510 do you have that disabled?

**Comment by darkspirit510** [comment]
```
# Sub feature flags
Setting('FEATURE_FLAG_STOCK_PRICE_TRACKING', false);
Setting('FEATURE_FLAG_STOCK_LOCATION_TRACKING', false);
Setting('FEATURE_FLAG_STOCK_BEST_BEFORE_DATE_TRACKING', false);
Setting('FEATURE_FLAG_STOCK_PRODUCT_OPENED_TRACKING', false);
Setting('FEATURE_FLAG_STOCK_PRODUCT_FREEZING', false);
Setting('FEATURE_FLAG_STOCK_BEST_BEFORE_DATE_FIELD_NUMBER_PAD', true); // Activate the number pad in best-before-date fields on (supported) mobile browsers
Setting('FEATURE_FLAG_SHOPPINGLIST_MULTIPLE_LISTS', true);
Setting('FEATURE_FLAG_CHORES_ASSIGNMENTS', true);
```

Indeed!
