### ISSUE TITLE
Barcode Scanner not working on Galaxy S20 Ultra chrome. 

### ISSUE THREAD

**Issue by 89jd** [grocy/grocy#1023]
Hi all,

Getting an issue on grocy, that it "could not start video source".

I think it is something to do with the camera setup.

I know this is a seperate library, but I reckon it is related.

Maybe something to do with the multiple cameras?

**Comment by berrnd** [comment]
Do you serve grocy via a secure (https) connection?
No major browser allows using the camera on unsecure connections...

Multiple cameras will result in a dropdown menu where you can select which one should be used.

Try the QuaggaJS (although we use Quagga2, but makes no difference for the basics) demo: https://serratus.github.io/quaggaJS/examples/live_w_locator.html

**Comment by 89jd** [comment]
1. It works on all other devices (I am on https).
2. That page doesnt work either. No camera options appear. I think it must be related to this below (forgot to attach it before, whoops):

https://github.com/zxing-js/ngx-scanner/issues/329

**Comment by berrnd** [comment]
> That page doesnt work either. No camera options appear. 

Then it's definitely with the library ([Quagga2](https://github.com/ericblade/quagga2)) itself.
Would be interessing what error pops up in the browser console (don't know how to access it on Chrome Mobile...).

**Comment by 89jd** [comment]
> > That page doesnt work either. No camera options appear.
> 
> Then it's definitely with the library ([Quagga2](https://github.com/ericblade/quagga2)) itself.
> Would be interessing what error pops up in the browser console (don't know how to access it on Chrome Mobile...).

I will have to do remote debugging. Might get chance to try it tonight.

Leave it with me.

Thanks for quick replies :+1:

**Comment by ericblade** [comment]
Keep me in the loop please.  Also, if anyone's reporting issues with iOS 14, i've got an issue logged on my repo for that (camera display not correct), but I don't have the ability to attempt to diagnose it, lacking hardware .. so i'm curious if it's working over here, i'd love to figure out why so i can make it work everywhere :)

It could be possible that there's something off with the browser implementation of camera on that device, too.  I am trying to decipher the linked post from zxing, and I can't tell if some people found success by specifying the camera to use first, or not.

**Comment by berrnd** [comment]
So since this is not a problem in grocy's scope, closing this here for now.
