### ISSUE TITLE
Duplicate ingredients since migration 104

### ISSUE THREAD

**Issue by m-byte** [grocy/grocy#1024]
Migration 104 introduces a change to `recipes_pos_resolved` that causes some of the ingredients from the demo database to be listed multiple times in recipes.

**Comment by berrnd** [comment]
Thanks for finding that, just to note here:
Migration 104 is not yet part of a release, so only affects master.

**Comment by m-byte** [comment]
Yes, no release is affected by this.

**Comment by berrnd** [comment]
Fixed in https://github.com/grocy/grocy/commit/e91bc0b01b804bde496a9812733e87583aeab679.
