### ISSUE TITLE
Feature Request: Repeated Meal Plan items + "Auto Consume"

### ISSUE THREAD

**Issue by Festeazy** [grocy/grocy#1028]
low priority feature request here. 
a option to have an mean plan item repeated month/weekly/daily.

possibly also an option to have an item auto consumed on the meal plan.

Uses: 
1) if a family has a taco Tuesday or pancake Fridays every week, they wouldn't need to interact with grocy at all to consume that.  
2) my morning coffee could be automated, for 4 years I've made the same amount of coffee every morning.

**Comment by berrnd** [comment]
Similar to #310.

**Comment by berrnd** [comment]
Merged into #310.
