### ISSUE TITLE
How to add custom method to API (405 not allowed)

### ISSUE THREAD

**Issue by donk7413** [grocy/grocy#1030]
For specifics reasons, I have write a method to get all the ingredients for a recipe_id because i have too many recipes and ingredients in db so i can't load all of it in one time. 

I essentially work with api and Android app, to my home automation system.

`public function SearchObjectsRecipePos(\Psr\Http\Message\ServerRequestInterface $request, \Psr\Http\Message\ResponseInterface $response, array $args)
	{
		if ($this->IsValidEntity($args['entity']) && !$this->IsEntityWithPreventedListing($args['entity']))
		{
			try
			{
				return $this->FilteredApiResponse($response, $this->getDatabase()->{$args['entity']}
					()->where('recipe_id == '. $args['searchString']), $request->getQueryParams());
			}
			catch (\PDOException $ex)
			{
				throw new HttpBadRequestException($request, $ex->getMessage(), $ex);
				//return $this->GenericErrorResponse($response, 'The given entity has no field "name"', $ex);
			}
		}
		else
		{
			return $this->GenericErrorResponse($response, 'Entity does not exist or is not exposed');
		}
	}`

in grocy/controllers/GenericEntityApiController.php

I also add a route in 
`$group->get('/objects/{entity}/searchRecipePos/{searchString:.*}', '\Grocy\Controllers\GenericEntityApiController:SearchObjectsRecipePos');`
in route.php just under the GenericEntityApiController:SearchObjects

And i add 
`"/objects/{entity}/searchRecipePos/{searchString}": {
			"get": {
				"summary": "Returns all objects of the given entity where the field \"name\" contains the search string (so only works for entities which have that field)",
				"tags": [
					"Generic entity interactions"
				],
				"parameters": [
					{
						"in": "path",
						"name": "entity",
						"required": true,
						"description": "A valid entity name",
						"schema": {
							"$ref": "#/components/internalSchemas/ExposedEntity"
						}
					},
					{
						"in": "path",
						"name": "searchString",
						"required": true,
						"description": "The search string",
						"schema": {
							"type": "string"
						}
					}
				],
				"responses": {
					"200": {
						"description": "An entity object",
						"content": {
							"application/json": {
								"schema": {
									"type": "array",
									"items": {
										"oneOf": [
											{
												"$ref": "#/components/schemas/Product"
											},
											{
												"$ref": "#/components/schemas/Chore"
											},
											{
												"$ref": "#/components/schemas/Battery"
											},
											{
												"$ref": "#/components/schemas/Location"
											},
											{
												"$ref": "#/components/schemas/QuantityUnit"
											},
											{
												"$ref": "#/components/schemas/ShoppingListItem"
											},
											{
												"$ref": "#/components/schemas/StockEntry"
											}
										]
									}
								}
							}
						}
					},
					"400": {
						"description": "The operation was not successful",
						"content": {
							"application/json": {
								"schema": {
									"$ref": "#/components/schemas/GenericErrorResponse"
								}
							}
						}
					}
				}
			}
		},`
in grocy.openapi.json

now i have two errors : 
when i call => https://XXX/api/objects/recipes_pos/search/aaa
i have error : Call to undefined method Grocy\Controllers\GenericEntityApiController::FilteredApiResponse()

when i call => https://XXX/api/objects/recipes_pos/searchRecipePos/1
i have error : Call to undefined method Grocy\Controllers\GenericEntityApiController::FilteredApiResponse()

I know the code or name can be dirty, it's just a first try, not a final version.

Someone know where is the problem ?

**Comment by berrnd** [comment]
Please try to format your code above so that it can be read.

And why not just use what #985 added (as already mentioned twice)?
Either by waiting for the next or applying the changes manually if you want to have it now or just using the master branch.

**Comment by berrnd** [comment]
Maybe you tried to copy & paste something from the master branch, but using the last release where of course the function `FilteredApiResponse` not yet exists?

**Comment by donk7413** [comment]
Yes, I copied it from the master branches. Just forget that the filter function is already implemented in the master branche. thanks, i will look into using directly the master branche in my dev environnement.
