### ISSUE TITLE
Recipe unit conversion leads to amount of 0 in list of ingredients

### ISSUE THREAD

**Issue by v411e** [grocy/grocy#1034]
I am experiencing a bug where the amount in the list of ingredients switches to zero.

Steps to reproduce:
- Create an item with unit "Kilogramm"
- Create unit conversion from Kilogramm to Gramm and from Gramm to Kilogramm
- Create a recipe
- Add the item as ingredient with 125 Gramm
- Save the list of ingredients and see "0 Gramm" in list of ingredients of the recipe

Thank you for your help!

**Comment by berrnd** [comment]
Already reported and fixed in #1003 (works on the current [pre-release demo](https://demo-prerelease.grocy.info)).
