### ISSUE TITLE
Can't use shopping list when stock is disabled

### ISSUE THREAD

**Issue by Rudloff** [grocy/grocy#1036]
Hello,

I am using grocy 2.7.1.

I would need a shopping list but don't need stock management so I added this in my config file:
```php
Setting('FEATURE_FLAG_STOCK', false);
Setting('FEATURE_FLAG_SHOPPINGLIST', true);
```
However, I can't add anything to the shopping list because it first asks me to create a product and points me to `/product/new`, which is a disabled route.

**Comment by berrnd** [comment]
A shopping list item requires either a product or a note or both. So with disabled `FEATURE_FLAG_STOCK` you can only use the note field for shopping list items. Products are part of the stock feature, I doubt that grocy is more useful than a simple note if you want to have a shopping list without (managed) products...

**Comment by Rudloff** [comment]
Well, it would still be useful to me to have my shopping lists, chores and tasks self-hosted in the same place, but I get your point.
(And the fact that a button linked me to a 404 error made it look like a bug.)

**Comment by berrnd** [comment]
Let's add to hide the product field on the shopping list item edit page, when `FEATURE_FLAG_STOCK` is disabled to make it more clear.
