### ISSUE TITLE
Icons / Pictograms for products

### ISSUE THREAD

**Issue by FX7** [grocy/grocy#1037]
In my opinion it would make all item lists (stock, shopping list ...) more accessable, if i can define an icon which is displayed instead / in addition to the the product name.

Maybe this can be acomplished by mark an picture already defined for a product as "display as icon" or somethink linke that?

**Comment by berrnd** [comment]
I think we had that request before, but I don't find it...

I doubt that the product picture at the size to fit into tables is really recognizable. On the stock overview page you can already click the product name to show the productcard, which includes the product picture in an appropriate size...

**Comment by FX7** [comment]
I also searched the issues before opening this new one, but also didnt find something.

You are right, that the pictures would be really small to be displayed in the table. Maybe this might be the wrong place for this issue, because I think it would be very helpful in a mobile view / the android app / maybe the desktop app. But in my opinion it should be managed by the server.

**Comment by FX7** [comment]
Just opened a issue for the android app. https://github.com/patzly/grocy-android/issues/138
As said before: Think the server should somehow manage the icons, but in the end the app should display it.

**Comment by berrnd** [comment]
We now have a new Userfield type "File" and also "Image".
Add such a field to products and you can upload any picture which also renders in tables, if enabled for the Userfield.
