### ISSUE TITLE
Recipe Ingredients list - alternative quantity unit below 1 peace buggy

### ISSUE THREAD

**Issue by MoD01** [grocy/grocy#1038]
I've discovered a bug with the calculation of alternative quantity units. I am using Version 2.7.1.

How to Reproduce the failure: 
- Create a Product with:
```
name=test
quantity unit purchase=Piece
quantity unit stock=Piece
QU conversion=100:Subpieces
````

- Create new recipe 'test recipe' with ingredients list:
- Product=test
- Amount=99
- Quantity unit=Subpieces
- Save()
==> Error: The amount in the ingredients list is displayed as 0. If you edit the ingredient there is also 0. 

I discovered that if the Amount is higher than 1 piece (e.g. 100 Subpieces or 200) it works. It seems the code does somehow require to have complete pieces. Amounts lower 1 piece (1-99 Subpieces) are somehow buggy.

**Comment by berrnd** [comment]
Already reported and fixed in #1003 (not yet released, feel free to verify it on the current [pre-release demo](https://demo-prerelease.grocy.info)).

**Comment by MoD01** [comment]
Thanks for the quick reply. I've tested it on your pre release demo. 
what works is the coversion to quantities of the original piece size (0,x pieces).

But there's still a strange behavior of the edit menu of an ingredients.  
Try to make a new recipe, add Cheese, 5 Slices, Save.
Now edit it again, it jumps from Slices to Pieces automatically in the dropdown, save.
Now edit it again, now it has 0,x Pieces of Cheese but the field validation marks it as invalid beause 0,x pieces is not valid. 

desired behaviour:
Notwithstandig how often you hit edit on the ingredients, the type of subpiece (here a slice of cheese) should stay selected in the dropdown.

**Comment by berrnd** [comment]
Thanks for testing, created #1060 to track that.
