### ISSUE TITLE
parse Error

### ISSUE THREAD

**Issue by ThomasKujawa** [grocy/grocy#1039]
Ich habe die letzte Version heruntergeladen und im Verzeichnis /grocy entpackt.
grocy sollte aufgerufen werden unter https://meinfamilienfreund.de/grocy/public/

Config-Datei liegt in /www/htdocs/w0174798/rechnung/grocy/data/config.php
Domain zeigt auf /www/htdocs/w0174798/rechnung/

Parse error: syntax error, unexpected '?', expecting variable (T_VARIABLE) in /www/htdocs/w0174798/rechnung/grocy/vendor/slim/slim/Slim/Factory/AppFactory.php on line 84

Liegt es an den fehlerhaften Einträgen in der config.php oder etwas anderem?

aus der config.php
Setting('BASE_PATH', '/rechnung/grocy');
Setting('BASE_URL', '/');

Kann mir jemand helfen, was ich falsch gemacht habe? Oder wo ich 'weiter' suchen kann?

**Comment by berrnd** [comment]
Bitte benutze das [subreddit](https://github.com/grocy/grocy#questions--help--bug-reporting--feature-requests) für allgemeine Fragen (wie in der [README geschrieben](https://github.com/grocy/grocy#questions--help--bug-reporting--feature-requests)), das hier ist der Issue Tracker (und hier ist auch Englisch besser, damit jeder mitlesen kann).

Ersetze halt einfach nochmal die `config.php` mit dem default (`config-dist.php`) um zu prüfen, ob da nix kaputt gegangen ist.

Und vermutlich sollte `BASE_PATH` auch eher nur `/grocy` sein, wenn deine Domain im root auf `/www/htdocs/w0174798/rechnung` served (hat aber sicher nix mit dem Fehler hier zu tun).

**Comment by berrnd** [comment]
Vielleicht auch mal die PHP Version checken, grocy ist nur mit PHP 7.4 getestet (steht auch in der README).

**Comment by ThomasKujawa** [comment]
Sorry, @Bernd. There I did not read attentively.

Will ask again in subbreddit.

First of all I have set php 7.4. An error remains nevertheless.
