### ISSUE TITLE
receipt uploads

### ISSUE THREAD

**Issue by Festeazy** [grocy/grocy#1040]
Hello again. 

Just an idea and a question. Receipt uploads, for times that we don't want to do the purchases just then and there. 

I created a user entity called receipts which is just links to files in the storage folder /config/storage/receipts
my only current issue is that I cant add more userfeilds to that userentity via API. 
my plan was to API PUT links into the receipt fields with the BASE64 encoded file name in the link, but that wont show the links in the Receipts Entity without it being manually entered.
below is an example with my URL replaced, if I try userfields/userentity-Receipts/### it wont show up. only when the # was created manually can I replace it. 

am i missing something here?

curl -X PUT https://demo.grocy.info/api/userfields/userentity-Receipts/2 -H accept: */* -H Content-Type: application/json -d {"Receipt":"https://demo.grocy.info/api/files/receipts/MTkzMi5qcGVn}

**Comment by berrnd** [comment]
The endpoint `PUT /userfields/{entity}/{objectId}` is only supposed to edit userfields of _existing_ objects.

If you want to create a _new_ one, use `POST /objects/{entity}`, the `entity` (also the database table) for all objects of user defined entities is `userobjects`.

(The UI also uses the API for everyhting, so to find out how something is done, a good way is to just check that out - can easily be done via the browser developer tools.)
