### ISSUE TITLE
mealplan and recipes 502 Bad Gateway at Docker

### ISSUE THREAD

**Issue by poltrian** [grocy/grocy#1042]
I tried to add a new recipes, but i got an 502 Error. How can i fix it?

**Comment by berrnd** [comment]
This is not the [grocy-docker repo](https://github.com/grocy/grocy-docker/), also general questions better fit on the [subreddit](https://www.reddit.com/r/grocy/) as [mentioned in README](https://github.com/grocy/grocy/#questions--help--bug-reporting--feature-requests), this is the issue tracker.

502 most probably is just a timeout error. So do you maybe have a lot of recipes? Also try to check the webserver and/or PHP error logs (don't know how to access them in a Docker environment).

**Comment by jayaddison** [comment]
Just adding a note that I've discovered this after looking for related issues from https://github.com/grocy/grocy-docker/issues/118.  I'll try to do a bit more investigation soon to understand what causes these HTTP 502 results to occur.
