### ISSUE TITLE
Userfields for shopping list

### ISSUE THREAD

**Issue by kriddles** [grocy/grocy#1052]
I noticed I can add userfields for shopping_list and shopping_list but I do not see them anywhere in the UI?

I'm not sure where to even suggest seeing the information or edit the userfields it, perhaps when adding a new shopping list the popup could include the field? Then add a "edit shopping list" button?

**Comment by berrnd** [comment]
Yes, seems that they are currently not rendered anywhere - the shopping list explicitly renders the product userfields.

So I think we should add, just to make it complete:
- Render `shopping_lists` userfields on the shopping list edit page
- Render `shopping_list` userfields on the shopping list item edit page and on the shopping list item table, there additionally to the product userfields (as of now)

**Comment by Festeazy** [comment]
Same goes for Userfields on Product Barcodes in prerelease. i added "price" but dont see it anywhere. 

havent noticed any others
