### ISSUE TITLE
Make it possible to hide columns

### ISSUE THREAD

**Issue by berrnd** [grocy/grocy#1058]
As not everyone wants every column to be visible, especially on the overview pages, make it possible to hide columns generically on all tables. Maybe there is a DataTables plugin for that.

**Comment by kriddles** [comment]
https://datatables.net/examples/api/show_hide.html for reference

**Comment by Festeazy** [comment]
would it be possible to include a calories column in the Master Data Products page, it could even be hidden by default.
calories are a big part of my grocy use.

**Comment by berrnd** [comment]
If we have an option to individually select which columns should be displayed, it would make of course sense to add all available ones by default "everywhere"...

**Comment by berrnd** [comment]
@Festeazy the calories per product are now also on the stock overview page. 🙂

Or have you thought of the summarized / total current stock calories per line?

![grafik](https://user-images.githubusercontent.com/2161815/98864768-b4992200-246a-11eb-843a-3808f2c98b54.png)

**Comment by Festeazy** [comment]
not a big deal but QU conversions has a "eye" but nothing pops up.

**Comment by berrnd** [comment]
> what do you mean "Or have you thought of the summarized / total current stock calories per line?"

Currently it's just the number from product master data.
So if Paprika has `10` calories per stock QU, `10` is displayed on the stock overview page, regardless if the amount in stock.
Is that what you thought of or should the calories on the stock overview consider the stock amount, so `20` calories there if 2 Paprikas are in stock?

**Comment by Festeazy** [comment]
i think in stock overview, since the value is also done by stock_amount that calories should also be multiplied by stock_amount
but in products, it should stay per QU

**Comment by berrnd** [comment]
> not a big deal but QU conversions has a "eye" but nothing pops up.

Thanks for your quick test, fixed that in https://github.com/grocy/grocy/commit/0a600d3277547a76e20a7f7e025a3e9a2240d1dc.

**Comment by berrnd** [comment]
So because we can now hide columns, I just added them both 🙂 - "Calories" is the one `multiplied by stock_amount`.

![grafik](https://user-images.githubusercontent.com/2161815/98867136-5c641f00-246e-11eb-94da-d8b550d1ef76.png)

**Comment by Festeazy** [comment]
Column Idea (hidden by default):

Overall: userfeilds wherever possible

Stock Overview:
last_purchased 
last_price

Products:
shopping_location name

Barcodes:
last_price (more of a dev column but could be useful)

**Comment by berrnd** [comment]
I've added all the mentioned columns. :)

**Comment by berrnd** [comment]
Just to add:

> Overall: userfeilds wherever possible

For Userfields nothing has changed, they still have there own setting "Show as column in tables" (and can then again also be hidden again by the new "Table options" - makes maybe not so much sense, but technically possible that way...).
