### ISSUE TITLE
Blank page 

### ISSUE THREAD

**Issue by marc700** [grocy/grocy#1059]
I've followed the #694 steps to install on Ubuntu 16 server but get a blank page when accessing the URL. I've read through lots of posts and cannot figure out how to fix this. 
The log file shows 
`[Thu Oct 15 19:27:55.407931 2020] [:error] [pid 2121] [client 192.168.15.20:45988] PHP Parse error: syntax error, unexpected '?', expecting variable (T_VARIABLE) in /var/www/html/grocy/vendor/slim/slim/Slim/Factory/AppFactory.php on line 84`

**Comment by berrnd** [comment]
Already answered in https://github.com/grocy/grocy/issues/152#issuecomment-709847828, double posting is not necessary.

Also please use the [subreddit](https://www.reddit.com/r/grocy) for questions and help requestes, as [mentioned in README](https://github.com/grocy/grocy#questions--help--bug-reporting--feature-requests), this is the issue tracker.
