### ISSUE TITLE
Workflow for purchase, group purchase transactions

### ISSUE THREAD

**Issue by white-gecko** [grocy/grocy#1061]
I just went shopping, and

- bought the things on the list (using grocy-android) and some extra stuff

When I came home 
- my wife took the phone to scan everything (grocy-android app) while I put it in the locations
- during that we add all of the new products (grocy-android app) using the batch mode
- afterwards I went through the batch list to add the missing unit sizes and expiry dates (grocy-android app)

- now I wanted to use the grocy web interface to add the prices of the purchase but I can't find a way to edit the transactions
- also I wanted to check if all of the added quantities were tracked correctly, as I have just scanned one bottle for each case.

(The only option I see at the moment to get the prices in and check the quantities is to do an inventory, which does not seem right.)

Am I doing something wrong in my purchase workflow?

My idea would be to group all of the transactions for one shopping event so I can go thorough it after scanning the products and add the price information. Also this would allow to compare the total of the purchase and maybe later attach a photo/scan of the receipt to the purchase event.

Sorry, this is a report of my first experiences mixes with a question and a not so simple feature request.

**Comment by berrnd** [comment]
> (The only option I see at the moment to get the prices in and check the quantities is to do an inventory, which does not seem right.)

You can also edit each existing stock entry, without inventory, on [`/stockentries`](https://demo.grocy.info/stockentries) (button at the top of the stock overview page).
If you order that table by purchased date descending, you would have the latest bought products at the top.

Without the app (which has it's [own repo](https://github.com/patzly/grocy-android) and also is not maintained by me), the easiest way would be using the button "Add all items to stock" on the shopping list page, which just goes through all items on the shopping list / opens the purchase page while all information (amount, default best before date and so on) is already prefilled.

Stock transactions which belong to the same "action" (so for example when using the "Add all items to stock"-button) are already grouped together by an id, we currently do nothing with it (maybe would be something for the stock entries page), don't know if the app also handles this "correctly".

I personally do the scanning at home, put everything on the table and use a wireless laser barcode scanner while just using the normal purchase page, afterwards I put the things where they belong to. But I personally don't care about price tracking...

**Comment by white-gecko** [comment]
Thank you very much.

For the issue the feature request to **group transactions as a purchase** is left over. Maybe this can be implemented using the id that you mention, but I'm not sure if this would do the trick already because a purchase would can be split in multiple transactions if I scan part of the products with my phone and my wife uses her phone to scan the other half.

Also a batch edit mode like requested in #1020 would help on the `/stockentries` page to now add the store for all of the entries. Or in the future add the items as a batch to a common purchase transaction.

Also the `/stockentries` page is quite coarse for identifying a purchase event based on the time as it only shows the year-month-day without the hour and minute. (I have added a separate issue for that #1063)

**Comment by berrnd** [comment]
So displaying stock entries on the stock overview page will be tracked in #1064.

If you have a specific idea what to do with the by transaction id grouped actions on the stock journal page, please open a separate issue for that.

**Comment by MrJohnZoidberg** [comment]
Hi, I just saw that issue and I want to ask you @berrnd how it is possible in the [add request](https://en.demo-prerelease.grocy.info/api#/Stock/post_stock_products__productId__add) to group stock entries together by an id like you said above?
I think currently with "Add all list items to stock" in our app, every `add` transaction will have another id...

**Comment by berrnd** [comment]
Just checked that again and I was wrong above, when using the add "Add all items to stock"-button on the shopping list page not all the stock transactions will have the same id.

- Each stock entry (table `stock`), has an `stock_id`, this id is generated when the entry was first added (normally via purchase)
- Stock entries can get split, this `stock_id` remains the same and groups rows in the `stock` table together
- Stock journal entries (table `stock_log`) have also that `stock_id` and
  - a column `transaction_id` to group all used stock entries by one transaction together (e. g. when you consume an amount of 5 and this transaction used 5 different rows/entries of the `stock` table)
  - a column `correlation_id` to group journal entries together which are dependent on each other (currently only used when editing stock entries, there is one journal entry for the values before and one for the values after the edit action)

So when we need this (?), this would be maybe more a "action_id". If using the normal purchase page, the question would be also when such an action starts and when does it end...

**Comment by white-gecko** [comment]
I think per default everything is an individual action, i.e. the transactions are not part of any action (`null`). For actions like "add all items to stock" it could be possible to group the transaction automatically. But in other cases an action has to be initiated and finished manually. Also it should be possible to manually associate transactions with an action, or remove transactions from the action.

**Comment by berrnd** [comment]
Ok, let's add such an `action_id` - I created #1100 to track that.

What should be possible by that id (on the stock journal page) is also open for discussion...
