### ISSUE TITLE
Error when adding "by-barcode"

### ISSUE THREAD

**Issue by Festeazy** [grocy/grocy#1068]
Im getting the following error while trying to add a product "by-barcode" through the api for the pre-release. 

 **"error_message": "SQLSTATE[23000]: Integrity constraint violation: 19 NOT NULL constraint failed: stock_log.qu_factor_purchase_to_stock"**

![image](https://user-images.githubusercontent.com/65983438/96360565-e32e1200-10e3-11eb-8ad0-81d0426a892d.png)

![image](https://user-images.githubusercontent.com/65983438/96360530-a530ee00-10e3-11eb-869d-18aaf594e200.png)

![image](https://user-images.githubusercontent.com/65983438/96360582-12448380-10e4-11eb-9d35-21961604b11d.png)

**Comment by berrnd** [comment]
Only affects master, works on the latest release - so maybe the same as #1055.
