### ISSUE TITLE
Creating new products redirect adds url to redirected page twice

### ISSUE THREAD

**Issue by jaranta** [grocy/grocy#1070]
Version 2.7.1
PHP Version 7.4.11
SQLite Version 3.11.0 

After creating new products, grocy redirects the browser to a new page with the url

    https://grocy.url/https:/grocy.url/inventory?createdproduct=ProductName

It seems that the base url is added twice to the redicted url.

I don't encounter this behavior on any other pages, so I assume that this is not a problem with my specific server redirects, but with how grocy handles this specific action.

There is one exception where this does not happen when adding new products: if products are added from the Manage master data - Products section, the redirect completes succesfully.

**Comment by berrnd** [comment]
Cannot be reproduced on current [stable](https://demo-prerelease.grocy.info) and [pre-release demo](https://en.demo-prerelease.grocy.info).

Please double check your `BASE_URL` setting, most probably an issue with that one, redirection back from the product edit page happens here: https://github.com/grocy/grocy/blob/80cf68aeaab7a6827344041ff0d6f4be7a044880/public/viewjs/productform.js#L9

**Comment by berrnd** [comment]
Your `BASE_URL` setting should be simply `https://grocy.url`.

**Comment by jaranta** [comment]
Seems to have fixed it. Thanks!

I had the `BASE_URL` set to `'/'`, since I have grocy running at the root of a subdomain, and the description says

    # The base url of your installation,
    # should be just "/" when running directly under the root of a (sub)domain
    # or for example "https://example.com/grocy" when using a subdirectory

Maybe those comments should be updated?

**Comment by berrnd** [comment]
The comment is still correct, it's also just `/` for alle demo instances, which also run at the root of a subdomain, and works.

Here's the function which populates the URL:
https://github.com/grocy/grocy/blob/9115645e193d7bbdafbb028d9d182fe0c48cf9d3/public/js/grocy.js#L251-L254

`Grocy.BaseUrl` contains what's provided in `BASE_URL`.

So would need further investigation what's the problem at your side there, it's also the same for the purchase page, so should be at least also a problem when creating a product from there...
