### ISSUE TITLE
More details on recipe calculation

### ISSUE THREAD

**Issue by basxto** [grocy/grocy#1072]
It would be helpful if you could see how much kcal and cost each product contributes to the recipe.
Especially for tracking down wrongly entered data:
![2020-10-19_04:25_777x653](https://user-images.githubusercontent.com/1314450/96394780-227f6000-11c3-11eb-9c90-dc124406cfed.png)

**Comment by berrnd** [comment]
Looks now like that:

![grafik](https://user-images.githubusercontent.com/2161815/101394290-90452f80-38c8-11eb-907f-7ce159991b4a.png)
