### ISSUE TITLE
[Feature?] Support deleting stock entries

### ISSUE THREAD

**Issue by heinrich-ulbricht** [grocy/grocy#1075]
I wrongly added a stock entry that I now want to remove. Undo it. It should never have been added in the first place. This doesn't seem to be possible?

I expected the three-dot-menu of the inventory item to contain a "Delete" entry, but there is none:
![image](https://user-images.githubusercontent.com/3469970/96421589-3a70d700-11f7-11eb-9aaf-e91d551c9d5d.png)

I don't want to "consume" this item since it would be wrong. I did not consume it. It never existed and is just there because I wrongly added it. (I even tried to set the amount to "0" to maybe trigger a "secret" delete dialog. But 0 isn't allowed to be entered.)

Is there a way to solve this cleanly? Maybe via API or direct DB manipulation? I'm open for everything. Or I didn't find it yet. If this functionality is not there I'd like to propose this as a new feature.

Any insight is appreciated.

**Comment by berrnd** [comment]
You can undo any stock transaction:
- There is an undo button directly in the success popup after each transaction
- Or on the stock journal page ([`/stockjournal`](https://demo.grocy.info/stockjournal), button in the header of the stock overview page) where you can undo each transaction

![grafik](https://user-images.githubusercontent.com/2161815/96422943-fa125880-11f8-11eb-87b4-d4c69f0081c1.png)

Deleting the journal itself is not possible, I think that's against the sense of an journal.
(And would be the source of if we ever will have my personal biggest feature request #64 done.)

> (I even tried to set the amount to "0" to maybe trigger a "secret" delete dialog. But 0 isn't allowed to be entered.)

Also possible, on the [`/inventory`](https://demo.grocy.info/inventory) (Inventur) page.
The difference between inventory and consume is that the amount entered on the inventory page is the new total stock amount for the selected product (so use it when you want to correct an invalid stock amount).

The purchase/consume/inventory page can also be opened from the context menu of the item on the stock overview or stock entries page.

And just for further clarification if it's maybe not 100 % clear:
- The stock overview page displays _one_ line per product (summarized amount)
- The stock entries page is the "raw" stock content, there can be multiple lines per product, doesn't matter if there are 5 lines with an amount of 1 each or 1 line with an amount of 5, would mean the same, lines there get maybe splitted on several stock transaction
- The stock journal page is just the log for any happened stock transaction

**Comment by heinrich-ulbricht** [comment]
Perfect thank you. Didn't know how to use the journal until now. It fits my purpose.
