### ISSUE TITLE
Stock filter: Expiring items don't contain items which expire today

### ISSUE THREAD

**Issue by MrJohnZoidberg** [grocy/grocy#1080]
Hi!

On a demo instance, purchase one Yogurt which expires today. Then filter it

With grocy version 2.7.1 if you filter for expiring items, Yogurt is displayed there.
With grocy current master version if you filter for expiring items, Yogurt is not displayed there, but it is in "already expired". So there is an orange item between red ones, that doesn't seem right.

In the API volatile response, Yogurt is included in "expiring_products".

**Comment by berrnd** [comment]
Great bug, just the fourth time we have it... 😂

#1050, #936, #87
