### ISSUE TITLE
PreRelease bug Number Picker

### ISSUE THREAD

**Issue by kriddles** [grocy/grocy#1083]
I've not identified yet but there is an issue with the number picker and decimals if you could take a look.

On the prerelease if you create a userfield using decimals then it is invalid with and entry of 0. 
This is also occurring for the Energy(kcal) entry.

![image](https://user-images.githubusercontent.com/54413450/96735298-0a553f80-1381-11eb-9c73-8022b69b783d.png)

**Comment by berrnd** [comment]
Thanks for testing, fixed in https://github.com/grocy/grocy/commit/be18d59735f06e78747b0d361afafcee344fd7b3 - more or less just a copy & paste typo... 😂
