### ISSUE TITLE
Alpha sort case-sensitivity on Location Content Sheets

### ISSUE THREAD

**Issue by Cordelya** [grocy/grocy#1086]
The Location Content Sheets currently sort case-sensitive.

This isn't a problem for organized people who entered all of their product names with uniform first-letter casing.

I am not one of those people. 

If there's no use case for case-sensitive sorting, may I suggest adjusting the printable sheets generator to i-sort the products?

**Comment by berrnd** [comment]
The sort happens here, just an `ORDER BY` directly in corresponding the SQL statement.

https://github.com/grocy/grocy/blob/be18d59735f06e78747b0d361afafcee344fd7b3/controllers/StockController.php#L44

So seems that SQLite sorts case-sensitive by default, have no problem to change that (`ORDER BY name COLLATE NOCASE ASC`) (maybe then on other related places too).

**Comment by Cordelya** [comment]
I suspected this one would be an easy fix! Thanks for the quick response.

I've already gone through my products and harmonized my capitalization, but I know that others will appreciate this enhancement in the future.

**Comment by Cordelya** [comment]
Another spot where this occurs is QU pick lists on Master Product entry/change forms
