### ISSUE TITLE
Inventory setting stock to 10 counts as 0

### ISSUE THREAD

**Issue by hasmaneuroda** [grocy/grocy#1087]
You are in the inventory-menu. You have 0 items and want to change the new amount to 10 items. (unit is pieces)
Grocy says the amount may not be <= 0 .

If you add any multiple of ten it works as expected.

Means you can add 11 or 9 but not exactly 10 at least when you're starting from 0

**Comment by berrnd** [comment]
Strange, can you reproduce this on the demo?
https://demo.grocy.info/inventory

I just tried it and it works...

**Comment by hasmaneuroda** [comment]
No, I can't reproduce it on the demo. (Sorry, should have tested that first).

Hm. Okay, tried another browser with my installation and there it works. (Sorry again, should have tested that first.)

Please excuse my overhasty posting.

**Comment by berrnd** [comment]
Absolutely no problem. :)

Which browser does not work?
Just default browser form validation features are used to do the form checks which should be widely supported...
https://caniuse.com/form-validation
