### ISSUE TITLE
xx below min. stock amount inconsistency

### ISSUE THREAD

**Issue by donk7413** [grocy/grocy#1088]
from the android App github : [https://github.com/patzly/grocy-android/issues/119](https://github.com/patzly/grocy-android/issues/119)

I figured out that if you have a Item 1 with 0 amount that have a children Item 2 with 0 amount that have a children Item 3 that have 1 amount, the grocy API will return Item 1 as missing item that is incorrect because Item 3 have a amount (
as well as Item 2 have 1 amount aggredated).

Item 1 (amount : 0, amount aggredated : 0) => missing Item (not correct)
- Item 2 (amount : 0, amount aggredated : 1) => Not missing (correct)
--Item 3 (amount : 1, amount aggredated : 1) => Not missing (correct)

This case can happens if you sub product with not exactly the same percent of ingredient
example :
- Dark chocolate
-      - NESTLE Dark Chocolate
-             - Nestle Dark Chocolate 90% Cocoa
-             - Nestle Dark Chocolate 70% Cocoa
-             - Nestle Dark Chocolate 60% Cocoa

**Comment by berrnd** [comment]
So you have 3 levels?
- Item1
  - Item2 (child of Item1)
    - Item3 (child of Item2)

**Comment by donk7413** [comment]
yes

**Comment by berrnd** [comment]
And how have you configured this?
The UI doesn't allow this (Item2 cannot be selected as a parent product on Item3 when it's already a child of Item1).

The parent product feature currently only allows one level, excerpt from the changelog where this was introduced (v2.5.0):
> - Products can now have variations (nested products)
>
>    - Define the parent product for a product on the product edit page (only one level is possible, means a product which is used as a parent product in another product, cannot have a parent product itself)
> ...

**Comment by donk7413** [comment]
I have do it in the product page. I will figured out how it's possible to bypass it.

**Comment by donk7413** [comment]
Ok, i have reproduce the bug. I have a huge list of product (more than 10000, imported, merged and processed from open food fact) so I can set quickly the parent when the page load (before the listbox become grey) because my interface is slow. The problem shouldn't affect normal user. (who doesn't have a huge database like me)
