### ISSUE TITLE
Prerelease demo: language always English

### ISSUE THREAD

**Issue by MrJohnZoidberg** [grocy/grocy#1094]
Hi, when I change language in the prerelease demo, Subdomain and Currency changes but the selected language remains English and all UI strings are still in English.

**Comment by berrnd** [comment]
Because of the new automatic/preference based language handling (#976), this should be disabled for the demo instances...

**Comment by sleeplessnight2** [comment]
The automatic/preference ignore the given setting at config.php too. If set "de" the UI remain at english.

**Comment by berrnd** [comment]
> The automatic/preference ignore the given setting at config.php too. If set "de" the UI remain at english.

When `MODE` = `production`:

- `DEFAULT_LOCALE` = `en`, user setting never changed, German browser => `de` localization is used
- `DEFAULT_LOCALE` = `de`, user setting never changed, English browser => `en` localization is used
- `DEFAULT_LOCALE` = `en`, user setting changed to "de", English browser => `de` localization is used

Looks good to me...
So which case does not work for you?

**Comment by sleeplessnight2** [comment]
I'm sorry, it's my fault. In my case, i used Firefox with english as language... Never checked before the Browser Language...
Please ignore my comment

**Comment by berrnd** [comment]
Turns out that the problem about the pre-release demo was a webserver configuration issue on my side, is now fixed.
