### ISSUE TITLE
Barcode linking on phone without an action

### ISSUE THREAD

**Issue by L0ric0** [grocy/grocy#1098]
wenn trying to link a barcode to a product with a phone it is impossible to do this without doing something with the object. 

Also adding the action to do inventory of the object woul be nice.

**Comment by berrnd** [comment]
> impossible to do this without doing something with the object.

If you don't want to do something, just edit the product (master data) and enter the barcode there.

If you enter something unknown into the product input on the [/inventory page](https://demo.grocy.info/inventory) there is the same "Create or assign product" popup as on the purchase and consume page... (?)
