### ISSUE TITLE
Confused translations in German shopping list

### ISSUE THREAD

**Issue by basxto** [grocy/grocy#1104]
`Diesen Eintrag löschen` (delete) and `Diesen Eintrag bearbeiten` (edit) are confused
![2020-10-28_02:43_298x44](https://user-images.githubusercontent.com/1314450/97380580-9e666000-18c7-11eb-9a84-38b7df1a6f3d.png)

Grocy version: 2.7.1

**Comment by berrnd** [comment]
It's about the shopping list page.

**Comment by berrnd** [comment]
Not reproducible anymore, maybe was fixed by #1103.
