### ISSUE TITLE
Doubt about "real" self-hosting

### ISSUE THREAD

**Issue by Porrumentzio** [grocy/grocy#1105]
I'm looking about Grocy after knowing about it with Grocy Android.

It is supposed that it's thought for self-hosting it for each home, but the reality is that very little people can self-host it due to lack of knowledge, but there's also another problem: almost all people has **dynamic IP** internet connection.

So it's not so easy to have a real self hosted instance of Grocy.

Or maybe am I wrong? Is it needed an URL to use the instance?

Also, maybe not each people can self host an instance for their house, but managing an instance among many people can be viable. So my question is whether it's possible to use a unic instance for more than a house.

Thanks for the project!

**Comment by berrnd** [comment]
Please use the [subreddit](https://www.reddit.com/r/grocy/) for general questions as [mentioned in README](https://github.com/grocy/grocy#questions--help--bug-reporting--feature-requests), this is the issue tracker.

Dynamic IPs are not a problem, search "Dynamic DNS".
There are also companies were you can rent whole servers, virtual servers (VPS) or shared webshosting, grocy is just a pretty normal PHP web application, so more or less runs everywhere...
There are [Docker images](https://github.com/grocy/grocy#how-to-run-using-docker) or [grocy-desktop](https://github.com/grocy/grocy-desktop) if you're not so familiar with hosting things yourself.

grocy is meant to manage one household.
So multiple househoulds currently means having multiple instances (which is also not a real problem).
In the next version the `data` path is customizable (see #939), so multiple instance will be kind of easier to set up.
For more about that there is #644.
