### ISSUE TITLE
Bug: Error 500. missing table

### ISSUE THREAD

**Issue by sleeplessnight2** [grocy/grocy#1113]
It's unable to load the site with a "old-stable" database.

Seems a missing table:
`PHP Fatal error:  Uncaught PDOException: SQLSTATE[HY000]: General error: 1 no such table: uihelper_user_permissions in /opt/grocy-test/vendor/morris/lessql/src/LessQL/Database.php:108\nStack trace:\n#0 /opt/grocy-test/vendor/morris/lessql/src/LessQL/Database.php(108):`

**Comment by berrnd** [comment]
This is a view which will be create in [migration 111](https://github.com/grocy/grocy/blob/master/migrations/0111.sql).
As already mentioned elsewhere, I already care that database migrations work between release, we have no release where this migration is included, you maybe need to take care of all migrations manually when running the master branch.

And just again: The master branch is not supported, thanks for testing, but of course anything can be broken (which is not a bug).

**Comment by sleeplessnight2** [comment]
Sorry, I didn't know that the import of existing databases will probably only be dealt with at the end. I won't report anything more so as not to be annoying.
