### ISSUE TITLE
Bug: Recipe unit conversion fails

### ISSUE THREAD

**Issue by matthiakl** [grocy/grocy#1117]
I use grocy in German, where a comma is used as decimal point. This causes an error, when a recipe uses unit conversion. 

![Bildschirmfoto vom 2020-11-03 18-35-39](https://user-images.githubusercontent.com/23122583/98020551-6ef1af00-1e03-11eb-9b18-7621a5a2b74a.png)

When I input this in the recipe ingredient window, the resulting amount, shown in the recipe is 0. And the following message is printed to the log:
```
NOTICE: PHP message: PHP Notice:  A non well formed numeric value encountered in /media/data/grocy/data/viewcache/2ef305327ea0009be49d2ca87c0f512168c71426.php on line 152
```
Corresponding file:
```
$product = FindObjectInArrayByPropertyValue($products, 'id', $recipePosition->product_id);
$productQuConversions = FindAllObjectsInArrayByPropertyValue($quantityUnitConversionsResolved, 'product_id', $product->id);
$productQuConversions = FindAllObjectsInArrayByPropertyValue($productQuConversions, 'from_qu_id', $product->qu_id_stock);
$productQuConversion = FindObjectInArrayByPropertyValue($productQuConversions, 'to_qu_id', $recipePosition->qu_id);
if ($productQuConversion)
{
         $recipePosition->amount = $recipePosition->amount * $productQuConversion->factor;
                                                      ^
}
```
`$recipePosition->amount` is `0,25` like in the picture, but `0.25` is expected.

grocy Version 2.7.1
PHP Version 7.4.11
SQLite Version 3.32.3

**Comment by berrnd** [comment]
Already reported and fixed in #1003 (not yet released).
