### ISSUE TITLE
Feature request: Automatic transfer workflow

### ISSUE THREAD

**Issue by matthiakl** [grocy/grocy#1119]
It would be nice to have an automatic transfer option for a product, when it is opened.
Say for example, I open a bottle of juice and then put it into the fridge. 
Or the pasta is stored in the basement, but when I open a pack I leave it in the kitchen.

**Comment by berrnd** [comment]
Merged into #830.

**Comment by berrnd** [comment]
This is now done in combination with #1365 (new product option "Default consume location") - changelog excerpt:

> - New product option "Move on open" (defaults to disabled)
>    - When enabled, on marking the product as opened, the corresponding amount will be moved to the products default consume location
