### ISSUE TITLE
Feature Request: UI Search field

### ISSUE THREAD

**Issue by BlizzWave** [grocy/grocy#112]
What do people think of the current placement of the search field?
In my opinion it should be on the left because its closer to all the main categories.

I have attached a super simple suggestion.

![natural](https://user-images.githubusercontent.com/6298655/48970161-6bdfc880-f009-11e8-9206-7f81ef541228.jpg)

**Comment by berrnd** [comment]
I think nothing speaks against this, so did this (for all pages) in https://github.com/grocy/grocy/commit/a3617cffb863711e7afd89a10565b11890597241.
