### ISSUE TITLE
Feature request: Floating ingredients panel

### ISSUE THREAD

**Issue by AllesMeins** [grocy/grocy#1121]
One thing I would find very useful would be a (optional) "floating ingredients panel" while displaying recipes on larger screens. I'm a bit absentminded and often forget the exact quantities of an ingredient. So on longer recipes I have to scroll back and forth. 

Separating ingredients and preperation into two tabs as in the pre-release demo doesn't help much either because I'd have to scoll all the way up to change the tab, check how much sugar I need, change tab back and then scroll back down again. So it would be very useful to me to have the ingredients alongside the preperation-text.

**Comment by AllesMeins** [comment]
Okay, that was easier than expected and surprisingly I managed to realize this feature with my limited scripting-skills. I add the two files I had to edit in case anybody else would like a floating ingredients panel, likes to build upon it or likes to do it properly :-) I marked all changes I did with a comment "MENUEDIT START"

[menuedit.zip](https://github.com/grocy/grocy/files/5504032/menuedit.zip)

I tried it out while cooking dinner tonight and it was a vast improvement for me.

**Comment by gismo2006** [comment]
Hi, 
I haver try this at version 3. But it didn´t work. Is there an other option to use floating ingredients?

Greets gismo

**Comment by berrnd** [comment]
>  I haver try this at version 3. But it didn´t work. Is there an other option to use floating ingredients?

This here is an OPEN feature request, so not yet done, so not a real suprise that not yet implement things don't yet work (also applies to any other open request, just in case you wonder ;D).

**Comment by berrnd** [comment]
Merged into / replaced by #2051.
