### ISSUE TITLE
Feature request: Shopping List: Adding temporary Items

### ISSUE THREAD

**Issue by sleeplessnight2** [grocy/grocy#1124]
An idea from practice: It would be helpful to allow items in the shopping list that do not have to exist as products. More like a "note".

I am currently not using this function, as you can only add items that previously existed as a product.

For some things it makes no sense and more work than use to record them in the database.
e.g. a broom. You buy this once, but not every time.
Nevertheless, I would like to have this on my shopping list only for today, but not add it as a product.
There are innumerable such cases.

So just a temporary entry that is only allowed in the shopping list.

**Comment by berrnd** [comment]
Already possible, just leave the product field empty (not required) and only use the note field.
