### ISSUE TITLE
Bug: Can't select Parent product

### ISSUE THREAD

**Issue by sleeplessnight2** [grocy/grocy#1125]
Today it's not possible to pick any parent Product.

I used a fresh database, a fresh web-dir (copy git-master-project via git clone)

The Server Logs say this:

```
Trying to get property 'id' of non-object in /opt/grocy-test/data/viewcache/3198e37e0de070caa317e0878aeefa4626461fe4.php on line 481

PHP Notice:  Undefined variable: product in /opt/grocy-test/data/viewcache/3198e37e0de070caa317e0878aeefa4626461fe4.php on line 574 

PHP Notice:  Trying to get property 'picture_file_name' of non-object in /opt/grocy-test/data/viewcache/3198e37e0de070caa317e0878aeefa4626461fe4.php on line 574
```

Here the Video what happening: https://www.dropbox.com/s/ufvw5bzezgldc8i/Bildschirmvideo%20aufnehmen%202020-11-12%20um%2012.20.44.mov?dl=0

If I was too quick to report, the problem was already known, then close the case.

**Comment by berrnd** [comment]
Thanks for testing.

I cannot reproduce this specific problem here and on the pre-release demo, but I have fixed the undefined variable warnings on the product edit page in https://github.com/grocy/grocy/commit/ea9722bfa4931220aa758c427a21a15361ff6585.

**Comment by sleeplessnight2** [comment]
Can we figured out, why this is happening?

What's the difference between your system and mine? (I assume that you always delete everything and install freshly for testing ...)
My System:
```
PHP 7.4.3
Ubuntu 20.04 standard install
apache2
```

but on `yarn install` it's given me warnings:
```
[3/4] Linking dependencies...
warning " > bootstrap@4.5.2" has unmet peer dependency "popper.js@^1.16.1".
warning "startbootstrap-sb-admin > bootstrap@4.0.0" has unmet peer dependency "popper.js@^1.12.9".
warning " > tempusdominus-bootstrap-4@5.1.2" has unmet peer dependency "popper.js@^1.14.3".
warning " > tempusdominus-bootstrap-4@5.1.2" has unmet peer dependency "moment-timezone@^0.5.11".
warning " > tempusdominus-bootstrap-4@5.1.2" has unmet peer dependency "tempusdominus-core@5.0.3".
[4/4] Building fresh packages...
warning Ignored scripts due to flag.
```

`composer install` say that i have something to install, if some of the functions is needed...
Is something from below neccessary?
```
gettext/gettext suggests installing symfony/yaml (Is necessary if you want to use the Yaml extractor/generator)
gettext/gettext suggests installing twig/extensions (Is necessary if you want to use the Twig extractor)
gettext/gettext suggests installing twig/twig (Is necessary if you want to use the Twig extractor)
symfony/translation suggests installing psr/log-implementation (To use logging capability in translator)
symfony/translation suggests installing symfony/config
symfony/translation suggests installing symfony/yaml
illuminate/support suggests installing moontoast/math (Required to use ordered UUIDs (^1.1).)
illuminate/support suggests installing ramsey/uuid (Required to use Str::uuid() (^3.7).)
illuminate/support suggests installing symfony/process (Required to use the composer class (^4.2).)
illuminate/support suggests installing symfony/var-dumper (Required to use the dd function (^4.2).)
illuminate/support suggests installing vlucas/phpdotenv (Required to use the env helper (^3.3).)
illuminate/filesystem suggests installing league/flysystem (Required to use the Flysystem local and FTP drivers (^1.0).)
illuminate/filesystem suggests installing league/flysystem-aws-s3-v3 (Required to use the Flysystem S3 driver (^1.0).)
illuminate/filesystem suggests installing league/flysystem-cached-adapter (Required to use the Flysystem cache (^1.0).)
illuminate/filesystem suggests installing league/flysystem-rackspace (Required to use the Flysystem Rackspace driver (^1.0).)
illuminate/filesystem suggests installing league/flysystem-sftp (Required to use the Flysystem SFTP driver (^1.0).)
php-di/php-di suggests installing doctrine/annotations (Install it if you want to use annotations (version ~1.2))
php-di/php-di suggests installing ocramius/proxy-manager (Install it if you want to use lazy injection (version ~2.0))
```

**Comment by berrnd** [comment]
The composer and yarn warnings/suggestions have nothing todo with the problem and can be ignored.

If you have PHP warnings and/or notices in the HTML markup, this of course only occurs if enabled in `php.ini` (I think the default value for production setups is to not show them, I have `E_ALL` enabled).

So just check what's wrong with the rendered HTML markup of the parent product dropdown on the product edit page - just via the browser developer tools.

I develop on Windows with always the latest PHP stable version and I not always start completely fresh, but of course from time to time to test migration paths.

**Comment by sleeplessnight2** [comment]
It seems, that a function or code isn't executed or something similar. If something is still at code missing it don't produced in any case a error.

What i have recognized, that's a little code missing, that's on the Purchase Product Picker are present:
The rendered HTML contains there following code:
```
<select class="form-control product-combobox barcodescanner-input" id="product_id" required="" data-target="@productpicker" style="display: none;" barcode="null">
		<option value=""></option>
						<option data-additional-searchdata="," value="3">cf</option>
						<option data-additional-searchdata="," value="2">g</option>
						<option data-additional-searchdata="," value="1">test</option>
			</select>
```

The same Lines at the new Product page:
```
<select class="form-control product-combobox barcodescanner-input" id="product_id" data-target="@productpicker" style="display: none;" barcode="null">
		<option value=""></option>
			</select>
```
Where are the `data-additional-searchdata`, wich contains the actually products?

Can you try this with a fresh installation please?
I have setup E_ALL and nothing on errors found at the browser development or server logs.

**Comment by berrnd** [comment]
`data-additional-searchdata` contains the products barcodes, the value of the `option` is the product id, the text the product name.

> Can you try this with a fresh installation please?

The pre-release demos get completely recreated 10 minutes past every hour (deletes everything, clones the master branch, installs composer and yarn dependencies, pulls the recent translations from Transifex), so that's always a fresh installation to test.

The HTML markup doesn't seem to be broken.
The difference for the product picker on the product page is of course that there only products without a parent product and not the current product itself get displayed (and only active products).

https://github.com/grocy/grocy/blob/71f6b38cb28e0e4094b884556bb922cef730078c/controllers/StockController.php#L162

**Comment by sleeplessnight2** [comment]
Which line (s) are responsible for the Parent Product Picker to work?

What I don't understand is that it worked fine before the Nov 10 commits. Also that all other search lists work in other input fields. Only this one not (anymore).

This certainly has nothing to do with headers, does it? I always have the following message: Error with Feature-Policy header: Unrecognized feature: 'speaker'.

Can an Apache configuration also be responsible for this? (Strange but that I didn't change anything between working and not)

**Comment by berrnd** [comment]
> Which line (s) are responsible for the Parent Product Picker to work?

Exactly the line I mentioned before:
https://github.com/grocy/grocy/blob/71f6b38cb28e0e4094b884556bb922cef730078c/controllers/StockController.php#L162

Which results basically in the query:
```sql
SELECT *
FROM products
WHERE id != <TheIdOfTheProductYouCurrentlyEditing>
  AND parent_product_id IS NULL
  AND active = 1
```

As it seems in your example that you only have 3 products:
- Are all of them active?
- Do both other products (beside the one you currently edit) don't have a parent product?
=> If not, it's correct that no parent product is available to be selected

**Comment by sleeplessnight2** [comment]
I think, i have found the Problem. Seems, that's just a database error. It's trying for searching a null object.
And it's **not** working on your demo too.

Create a product and call this for eg "test". Then just finish with saving. Try now to make this earlier created Product as a Parent on a new one - you won't find this earlier created Product.

If you don't believe me, switch the mode to `production` instead of `demo` and create two fresh products in an empty database.
I bet you will experience the same as in my video...

Just as a nice tip:
You should always run a test with an empty database - not one that is already pre-loaded.
Because with a new installation you start with an empty one and not with the demo - and errors are much more apparent if you have to go through the processes yourself from the beginning ...

**Comment by berrnd** [comment]
> Create a product and call this for eg "test". Then just finish with saving. Try now to make this earlier created Product as a Parent on a new one - you won't find this earlier created Product.

Now we have it reproducible, thanks for testing. Will be tracked in #1128.

> Just as a nice tip:
> You should always run a test with an empty database - not one that is already pre-loaded.

Sure, if I do this before every commit, I maybe need 400 % more time, so no, just try to do tests before releasing a new version. So also just a nice tip: We still have no new release. But thanks again for testing.
