### ISSUE TITLE
Bug: Sorting is opposite in recipes 

### ISSUE THREAD

**Issue by BlizzWave** [grocy/grocy#113]
When you sort the recipes by "Requirementd fulfilled", it's opposite. Recipes that you have everything for (green check mark) and then it starts with recipes that missing the most. 

![capture](https://user-images.githubusercontent.com/6298655/48971620-6e97e900-f01c-11e8-98d8-0e6f58b4326c.JPG)

**Comment by berrnd** [comment]
That's the default sorting thing from DataTables which does a alphabetically ordering, but it seems to be [possible](https://datatables.net/reference/option/columns.orderData) to sort by different values than visible, will try that...

**Comment by BlizzWave** [comment]
That actually made it worse. haha

![grocy_issue8](https://user-images.githubusercontent.com/6298655/48979275-ad7b7c80-f0b8-11e8-8ceb-0d92fcb64a2e.gif)

**Comment by berrnd** [comment]
Ah, you of course wanted it to be sorted by the amount of missing products, makes sense - I just changed that
Green = 1
Yellow = 2
Red = 3
and sorted it by that value...

**Comment by BlizzWave** [comment]
Correct! Haha
