### ISSUE TITLE
Bug: apply last_price & last_purchased to barcodes in API

### ISSUE THREAD

**Issue by Festeazy** [grocy/grocy#1130]
Please describe the bug as detailed as possible, provide the steps how to reproduce it and maybe attach screenshots where useful.

when I run GET $grocy/api/stock/products/by-barcode/1234 I would like to see the last price of the last time the $barcode was purchased, not the last time the $product_id was purchased. 

that being said, I also expect $grocy/api/stock/products/$product_id to STILL give me the price of the last time the $product_id was purchased. 

does that make sense? I'm not sure if its a bug or an "enhancement" because I don't know if it was intentional

**Comment by berrnd** [comment]
> when I run GET $grocy/api/stock/products/by-barcode/1234 I would like to see the last price of the last time the $barcode was purchased, not the last time the $product_id was purchased.

We don't track which barcode was used to add a product to stock, the barcode is only used to lookup the product.
I I don't think this is what we should add - if the different barcode is a completely other product, then you should create separate product.

> that being said, I also expect $grocy/api/stock/products/$product_id to STILL give me the price of the last time the $product_id was purchased.

That's the case.

**Comment by berrnd** [comment]
If you want to get the last price from a specific store the product was purchased, the next version will have a separate endpoint for the stock journal + filter capabilities, see the [pre-release API doc](https://demo-prerelease.grocy.info/api#/Stock/get_stock_journal).

**Comment by Festeazy** [comment]
my main concern was when you try to purchase the same product(cookies) using two different barcodes (12pack/16pack), the workflow of the purchases becomes a little more difficult with the current pre-release method. 

if the product_barcodes had a last_price field, it could be directly applied to the total price with the barcode stock conversion during purchases, I agree the product should have a average price and a last price of its own because as its useful for "data", but I think its very important for the barcode itself to be looked at first when looking for prices as that's how things are naturally purchased.

I do truly believe this as an issue that deserves another round of consideration and could be a inconvenience for users when more get on V3

**Comment by berrnd** [comment]
That sounds reasonable, thanks.

So I think there is now other way then to track which barcode was used on purchase (if any).
=> I created the follow up issue #1131 to track that.

**Comment by berrnd** [comment]
And just that we mean the same thing:

If there is a way to get the last price for the used barcode, you want of course that this price is prefilled on the purchase page (?) + also that "Total price" is automatically selected, right?

**Comment by Festeazy** [comment]
Yeah, I feel like that would streamline the process.

IF you feel like it, we could even make that a column in the barcode products section
