### ISSUE TITLE
Track which barcode was used on purchase + use it for price suggestion

### ISSUE THREAD

**Issue by berrnd** [grocy/grocy#1131]
Follow up for #1130 by @Festeazy.

It should be tracked which barcode was used on purchase, if any - then use this for the price suggestion when using that barcode again.

> if the product_barcodes had a last_price field, it could be directly applied to the total price with the barcode stock conversion during purchases, I agree the product should have a average price and a last price of its own because as its useful for "data", but I think its very important for the barcode itself to be looked at first when looking for prices as that's how things are naturally purchased.

**Comment by berrnd** [comment]
@Festeazy this is now done:
- Just a new field `last_price` on the `product_barcodes` table
- Will be updated on purchase when the barcode was used
- If not empty, prefills the price field + auto selects "Total price" on next purchase with that barcode

**Comment by Festeazy** [comment]
this isn't working right, I'm seeing null for last_price in product_barcodes after purchases.

for my testing i created two barcodes for cookies 12 for a 12pack and 16 for a 16 pack, after purchasing one of each, i still see null when testing the API.


![image](https://user-images.githubusercontent.com/65983438/99444744-42996080-28e2-11eb-8051-a3c335e82cb5.png)

**Comment by berrnd** [comment]
I've just tried it with the `16` barcode and it worked...

Have you really used the barcode or manually selected the product?
(Entering the barcode is ok, when a barcode is resolved to a product it remembers that barcode when submitting the transaction.)
Of course it only get's updated when the barcode was used, happens here - can't see anything completely wrong with it:
https://github.com/grocy/grocy/blob/2b4d8a7cc56b7df1c42d5c814f1d81fff7d978d1/public/viewjs/purchase.js#L58-L66

**Comment by Festeazy** [comment]
when I enter just "16" for a purchase in the UI, it resolves cookies and the correct amount but it looks like its still pulling the product `last_price `and not the `product_barcodes last_price`

after carefully purchasing it by barcode in the UI, it still shows up as '`null`' in `product_barcodes `in API

**Comment by Festeazy** [comment]
After looking at the Chrome Dev Tools, it looks like it may be putting the unit price **and not the total price** into the last_price field in  "api/objects/product_barcodes/2" 

![image](https://user-images.githubusercontent.com/65983438/99448393-16331380-28e5-11eb-93ad-633d3a466650.png)

**Comment by berrnd** [comment]
> After looking at the Chrome Dev Tools, it looks like it may be putting the unit price and not the total price into the last_price field in "api/objects/product_barcodes/2"

That's right, fixed in https://github.com/grocy/grocy/commit/bbdc372dcf26a23c5add540f09097d1d113f7b30.

The normal product price is still used as a fallback (technically prefilled before - on the normal "product selected" event, the barcode's `last_price` get prefilled afterwards, if not empty.

**Comment by Festeazy** [comment]
awesome, tested and works correctly. did i also see your making changes on how often the pre-release updates?

**Comment by berrnd** [comment]
No, it still get recreated 10 minutes past every hour.

Just mentioned in https://github.com/grocy/grocy/issues/1134#issuecomment-729180332 that i'll have a look at #395 in the next days to make pre-release testing easier.

**Comment by Festeazy** [comment]
sorry to keep being a bother, but it doesn't look like the last_price is being applied via an API purchase(add)
I tested by making purchases via API and via UI but only via UI did it update. 
Im not sure where to start looking into for troubleshooting

**Comment by berrnd** [comment]
Only the UI does it, `/stock/products/{productId}/add` does not have a way to provide the used barcode, but of course `/stock/products/by-barcode/{barcode}/add` - so let's roopen this and close it again once that's done.

You can also update the used barcode manually by PUT `/objects/{entity}/{objectId}`.

**Comment by berrnd** [comment]
Have not thought my last comment to the end:
Will not be possible for `/stock/products/by-barcode/{barcode}/add`, because (as for all endpoints) the price and amount provided there needs to be related to the stock QU and also the purchase QU is not part of the request - so no way around doing that manually (like the UI) currently.

**Comment by Festeazy** [comment]
would you be able to add the barcode_id to the` /stock/products/by-barcode/{barcode}/add` response for easier PUT's

**Comment by berrnd** [comment]
Doesn't really fit, as the response is just the create stock booking (`StockLogEntry`).
(Internally it just looks up the product id by the given barcode and then calls `/stock/products/{productId}/add`.)
