### ISSUE TITLE
Feature request: Show/Print barcode

### ISSUE THREAD

**Issue by sotiris-bos** [grocy/grocy#1133]
Hey! Thanks so much for your work!

Some of the shops in my area have e-shops with companion smartphone apps where you can scan a barcode and add it to your order.

I wish grocy could present on screen and/or print in the shopping list the barcodes of products so we can use this functionality.

I think it would be trivial to implement, possibly only need to implement a barcode generator and some UI changes.

**Comment by berrnd** [comment]
So you mean just to display the barcodes of the product as a barcode?

That should be easy to add, just the barcode type to use would be interesting here (in Germany) I think the default barcode type used on consumer products is "EAN-13" ("GTIN-13").

**Comment by sotiris-bos** [comment]
Exactly! Just display the barcode as a barcode so we can scan it with scan-to-order apps.

Wow, I did a quick google search, I did not know there are so many types of barcodes

**Comment by berrnd** [comment]
That's now done - a new (hidden by default) column for the table on the shopping list page, looks like that:

![grafik](https://user-images.githubusercontent.com/2161815/102721308-3f86fb00-42fa-11eb-8085-de62d374b571.png)

Still unsure about the barcode type to use, currently hardcoded it to "EAN-8", maybe this is compatible with most used barcodes...

(The barcode-image is generated client-side by the JS library [bwip-js](https://github.com/metafloor/bwip-js).)
