### ISSUE TITLE
Bug: cant highlight (to copy) API KEY in prerelease

### ISSUE THREAD

**Issue by Festeazy** [grocy/grocy#1135]
Please describe the bug as detailed as possible, provide the steps how to reproduce it and maybe attach screenshots where useful.

pretty self explanatory, I created an API-KEY on my computer and cant highlight it to copy it. 

https://demo-prerelease.grocy.info/manageapikeys

DOESNT NOT WORK when tested on a Windows 10 Chrome, Edge, IE

WORKS on Android Tablet Chrome, and IOS Chrome/Safari

**Comment by berrnd** [comment]
This is caused by that tables are now horizontally scrollable, also by dragging anywhere on the table body (references #1115).
