### ISSUE TITLE
Bug: Schaltflächenbeschriftung vertauscht im Einkaufzettel

### ISSUE THREAD

**Issue by Dtrieb** [grocy/grocy#1137]
In der Demo ist im Einkaufzettel ist die Schaltflächenbeschriftung vertauscht.
Löschen mit Editieren 
![chrome_2020-11-18_19-42-21](https://user-images.githubusercontent.com/3650284/99574752-119b5780-29d8-11eb-85a9-48c22518cb0e.png)

**Comment by berrnd** [comment]
Duplicate of #1104, already fixed, not yet released.

Please always try to reproduce bugs on the [pre-release demo](https://demo-prerelease.grocy.info) first, thanks.
