### ISSUE TITLE
UI Bug: Stock Entry modal card covers tool-tips

### ISSUE THREAD

**Issue by Cordelya** [grocy/grocy#1138]
Using 2.7.1 on Linux (no Docker).

To reproduce: View a product's stock entry detail card. Hover mouse over either of the two icons in the upper right corner of the card. Tool-tips pop up, but they're obscured by the card (you may be able to see the tool-tip container edges peeking out).

**Comment by berrnd** [comment]
Duplicate of #1065, already fixed, not yet released.

Please always try to reproduce bugs on the [pre-release demo](https://demo-prerelease.grocy.info) first, thanks.
