### ISSUE TITLE
Feature request: Change "Scan-Modus Button" Text - wrong association

### ISSUE THREAD

**Issue by sleeplessnight2** [grocy/grocy#1141]
With the scan mode button it is unclear whether the mode is already "on" or whether it is only "turned on" by pressing it.

Now it is so that the button shows the current status. This is confusing because as a user you never associate the current status with a button, but rather the action on it.

For example: An "OK" button does not suggest that everything is ok, but what I trigger by pressing the button - in this case a confirmation.

**Comment by berrnd** [comment]
It's a toggle button, and toggle buttons show the current state of the thing they toggle.
An ok button is not a toggle button.

So what's your proposal of what to change in detail?

**Comment by sleeplessnight2** [comment]
It should be clear what happens when you press a button.  This is currently not the case.  A button that shows a status does not exist - I have never come across such a button in any program.

The toggle button mentioned is currently incorrectly labeled.  For example a playback control: A play button only plays the music after it has been pressed.  Then it shows the pause symbol and not the play symbol.

**Comment by berrnd** [comment]
> I have never come across such a button in any program.

Ok, so you probably never used any mobile OS, most probably the most used type of control for (setting) menus there.

It's a common pattern: https://getbootstrap.com/docs/4.1/components/buttons/#toggle-states
I've just modified to use the green and red colors instead of the "active border".

However, such things depend on personal preference, this is definetly not "wrong" in terms of common UI controls - so feel free to tweak it by using [custom CSS/JS](https://github.com/grocy/grocy#adding-your-own-css-or-js-without-to-have-to-modify-the-application-itself) for example if that bothers you that much.

**Comment by sleeplessnight2** [comment]
It's not about what's right / wrong.  It's about what the unsuspecting user expects.  A suggestion would be that the button conveys the current status through the color, but the text suggests the following action.  Unfortunately the text cannot be changed via custom css or I just don't know how.  I didn't know how to act myself at the beginning and never knew whether the mode was active or not.  I don't want to think of those who are happy if they even get the browser open ...

**Comment by berrnd** [comment]
Green + text "Scan mode on" = Scan mode is on
Red + text "Scan mode off" = Scan mode is off
=> Click = the mode is toggled, that's what a toggle button does, it toggles its state.

So assuming green means "on" and red "off", then:

> A suggestion would be that the button conveys the current status through the color

Is already the case.

>  the text suggests the following action

Is not true, the text states the _current_ state, in addition to the color.

If that's the most important and most confusing thing about grocy, there would have been complaints over and over, that's not the case.

>  Unfortunately the text cannot be changed via custom css or I just don't know how.

Here an example script (for `data/custom_js.html`) which removes the button color and makes the text hopefully super clear for you.

```html
<script>

if (Grocy.CurrentUrlRelative == "/purchase" || Grocy.CurrentUrlRelative == "/consume")
{
	new MutationObserver(function(mutations)
	{
		mutations.forEach(function(mutation)
		{
			if (mutation.type == "attributes" && (mutation.attributeName == "class"))
			{
				var button = $("#scan-mode-button");
				
				if (button.hasClass("btn-danger"))
				{
					// Scan mode is off
					// Original button color = red
					// Original button text = "Scan mode off"
					button.text("Scan mode is currently off, please press this button to enable it");
				}
				else if (button.hasClass("btn-success"))
				{
					// Scan mode is on
					// Original button color = green
					// Original button text = "Scan mode on"
					button.text("Scan mode is currently on, please press this button to disable it");
				}
			}
		});
	}).observe($("#scan-mode-button")[0], {
		attributes: true
	});
}
$("#scan-mode-button").addClass("btn-light");

</script>

```

**Comment by berrnd** [comment]
Here are examples for toggle buttons for maybe the biggest 3 platforms (Web/Android/iOS):
https://www.w3schools.com/howto/howto_css_switch.asp
https://developer.apple.com/design/human-interface-guidelines/ios/controls/switches/
https://developer.android.com/guide/topics/ui/controls/togglebutton

All have in common:
The current state is represented via color + text (if they have text).

Exactly how the scan mode button here works.
So seems that then all others do it wrong or they confuse their users by intention, we should immediately change that.
