### ISSUE TITLE
Bug: change user permissions

### ISSUE THREAD

**Issue by jdmarshall90** [grocy/grocy#1142]
When viewing the users list, I don't see any way to change the permission set per user, neither in the edit user nor the user list view. I am using the default config.php.

Is there a setting I need to toggle somewhere?

**Comment by berrnd** [comment]
The permission feature is not yet part of any release.
If you use the master branch (unstable, only use it if you can handle database migrations and stuff manually), there is a "lock icon" per user row, see the pre-release demo: https://demo-prerelease.grocy.info/users

**Comment by jdmarshall90** [comment]
ETA on prod release containing this?

**Comment by berrnd** [comment]
Because I do this only as my hobby, I never promise anything, but see: https://www.reddit.com/r/grocy/comments/jvphp8
