### ISSUE TITLE
Bug: Can't create quantity unit conversions

### ISSUE THREAD

**Issue by sbleblanc** [grocy/grocy#1144]
When managing _Quantity units_, I am unable to add conversions. When I go to edit a quantity unit and add a conversion, the **Quantity unit from** is greyed out, but not filled with the source unit as it should be. This happens with the latest release and the current master version. When I look at the logs for nginx, this is what I get:

```
[error] 829#829: *1473 FastCGI sent in stderr: "PHP message: PHP Notice:  Trying to get property 'name' of non-object in /srv/www/grocy/data/viewcache/1
6a47b27a561475ca360f45d6ef2ee38862fac64.php on line 18" while reading response header from upstream, client: 192.168.1.12, server: my.domain.com, request: "GET /quantityunitconversion/new?embedded&qu-unit=3 HT
TP/2.0", upstream: "fastcgi://unix:/run/php-fpm/php-fpm.sock:", host: "my.domain.com", referrer: "https://my.domain.com/quantityunit/3"
```
Im on Arch :

- PHP Version 7.4.13
- SQLite Version 3.33.0

**Comment by berrnd** [comment]
This is reproducible when you try for example use an invalid QU id for the `quantityunitconversion` form.
Example: https://demo.grocy.info/quantityunitconversion/new?qu-unit=xxxx

So I think the query parameter `qu-unit` doesn't hit the PHP runtime / is filtered out before (do you use a reverse proxy or something?).

Please use the [subreddit](https://www.reddit.com/r/grocy) for general help, unless it's a reproducible bug (try it on the demo instances before) as [mentioned in README](https://github.com/grocy/grocy#questions--help--bug-reporting--feature-requests), thanks.

**Comment by sbleblanc** [comment]
Thank you for looking into this.... I realised I made a typo in my nginx configuration. I wrote ?is_args instead of $is_args........
