### ISSUE TITLE
Feature request: On Purchase - prefill the Amount or/and Standard Amount per Produkt

### ISSUE THREAD

**Issue by sleeplessnight2** [grocy/grocy#1148]
It makes sense to fill in the consumption amount with the Quick Consume Amount instead of a standard amount.

A _global_ standard amount make really no sense... in 90% the usecases i changed this, because the consumption is individual or it ignores "the factor purchase to stock quantity" unit when consuming. 

For Example: 
The Factor is: 1 Piece is 500gr. But when I consume it, I have to manually enter the factor (i.e. 500), otherwise the 1gr will be booked out. The Quick Consume Amount is a solution for this - but the process is not complete finished yet.

A suggestion:
Rename at the Product Page the Field "Quick Consume Amount" into "Standard Consume Amount" and use that accordingly throughout the program.

It saves a lot of your time dealing with grocy.

**Comment by berrnd** [comment]
The easiest thing is that the default consume amount is 1 (QU stock) for all products, so depends on how you organize your products and of course never works for something like Flour tracked in grams - I personally do it like that.

But of course this is a valid feature request to also use the "Quick consume amount" also as a default on the consume page.
