### ISSUE TITLE
Feature request: Tax

### ISSUE THREAD

**Issue by Festeazy** [grocy/grocy#1153]
Please describe what you would find useful and please also check (by searching open requests here) if that was maybe already requested.

Have you ever considered adding tax information?

I'd image it would be a percentage per item (default settings) and also have the option to edit per item as in US some foods aren't taxed and some items are taxed differently. 

Then each price listing would be redone as "subtotal/tax/total" with the appropriate calculations

this is a after V3 feature request

**Comment by berrnd** [comment]
grocy is a software intended to manage your home, not your business.

As a consumer, I have to pay the total (gross) value - so what would be benefit of knowing the net value?

**Comment by Festeazy** [comment]
I guess that depends on if you enter the net or gross of items per purchase.
I can see how it adds complexity for only a tiny bit of additional info

**Comment by berrnd** [comment]
And why should I enter the net value when I have to pay the gross value?

I think we don't add this.

**Comment by thystra** [comment]
In the US, sales tax is not added to the price of items.  Most food is not taxable, however some items are (e.g. sodas, junk food, and other non-food household goods).  Users should be able to define sales tax rates for their localities (can change based on county/where purchased) and then check a box as item is taxable.  

Receipts show items and their pre-tax price, and a tag that they are taxable, and then the tax is added up for all items, not broken down individually at the bottom of the receipt.  

If you don't want to implement taxable/non-taxable status, then enable "math" in the price field so one could type in price*sales tax, e.g. 10.99*1.075 to get the final price.

**Comment by berrnd** [comment]
Consider using [custom JS](https://github.com/grocy/grocy#adding-your-own-css-or-js-without-to-have-to-modify-the-application-itself) for that - example snippet (for `data/custom_js.html`) to add quick "+%"-buttons next to the price input on [/purchase](https://demo-prerelease.grocy.info/purchase):

```html
<script>
if (Grocy.ActiveNav == "purchase")
{
	// Define your tax rates
	const taxRates = [7.5, 12, 15];

	taxRates.forEach(rate =>
		$("#price").parent().append('<div class="input-group-append"><div class="btn btn-primary price-tax-buton" data-tax="' + rate + '">' + rate + '%</div></div>')
	);

	$(document).on("click", ".price-tax-buton", function()
	{
		var rate = Number.parseFloat($(this).attr("data-tax"));
		var price = Number.parseFloat($("#price").val());

		$("#price").val(price + (price / 100 * rate));
		
		RefreshLocaleNumberInput("#group-price");
	});
}
</script>
```

Will look like that:

https://user-images.githubusercontent.com/2161815/226470527-ae501ea8-0fef-44da-88eb-b177a35d39c2.mp4
