### ISSUE TITLE
Feature request: Stores Additional Data

### ISSUE THREAD

**Issue by Protektor-Desura** [grocy/grocy#1154]
It would be nice if you could put the address in the store in case you are new to an area or sending someone to the store for you that you could give them the address of store. In the android app you could then send the address to MAPS for directions to the store as well.

It would also be nice to put in the store hours so if you can't remember when they close it would know that you only have 20 minutes until they close or that they aren't open today or whatever.

Also might be nice to have the phone number and then android app could dial directly from the app to the store.

**Comment by berrnd** [comment]
Duplicate-question of #982.

It's already possible to add any field to any entity (products, locations, stores, ...) - have a look at Userfields (#176).

It don't know if grocy-android handles/shows Userfields...
