### ISSUE TITLE
Move a Grocy installation with all Data to ProxMox

### ISSUE THREAD

**Issue by witzker** [grocy/grocy#1155]
Hi I'm new with all this server stuff
but trying to learn.

I Somme-how managed a time ago to get Grocy running on my Synology DS 418 NAS
and entered a lot of data.

Now I have set up ProxMox on a Lenovo
ThinkCenter M93P

Can You pls help to move this installation with all data to a server in ProxMox?

What should I set up in ProxMox
I thought about a LXC Ubuntu
![image](https://user-images.githubusercontent.com/4120266/101245158-23d10180-370b-11eb-9f72-fdf728038dae.png)
What do you think?

Or is there a better way?
----------------------------------------
I downloaded the package from here
extracted it and uploaded it to Synology web Folder 

![image](https://user-images.githubusercontent.com/4120266/101245505-a955b100-370d-11eb-814d-3bec51b17caa.png)

Then set up a virtual Host in Synology

![image](https://user-images.githubusercontent.com/4120266/101245569-179a7380-370e-11eb-82e8-ecb2a07dd140.png)

When I call the "synology IP:port" it worked
By the way this could be an installation guide for Synology
---------------------------
How can I transfair this to ProxMox?

PL Help

**Comment by berrnd** [comment]
Please use the [subreddit](https://www.reddit.com/r/grocy/) for general questions as [mentioned in README](https://github.com/grocy/grocy#questions--help--bug-reporting--feature-requests), this is the issue tracker.

You probably opened already the same topic there: https://www.reddit.com/r/grocy/comments/k66aso

Proxmox / LXC container are not that much different than any normal Linux server, so I would maybe try any of the guides linked on https://grocy.info/links.

Everyone who is not so familiar with setting up webservers and stuff IMHO uses the Docker images.

About data moving: Everything grocy uses is in the `data` folder.

**Comment by witzker** [comment]
THX

So I will try to set up a new Grocy on Proxmox and then replace the whole data folder with that one from Synology
Right?

**Comment by berrnd** [comment]
Yes, as I said, **everything is in the `data` folder, so moving that moves everything**.

**Comment by witzker** [comment]
THX
SOLVED
