### ISSUE TITLE
Feature request: user Avatar/Image

### ISSUE THREAD

**Issue by Festeazy** [grocy/grocy#1158]
user images/avatars that appears near the username.

in V3 I will add pictures to all users but it would be nice if it appears at the top of the page at each grocy terminal. 

in selfhosted, ive seen both an image file being uploaded or an avatar link in the db

**Comment by Festeazy** [comment]
just noticed that there isn't userfeids for users, is that also a possibility?

**Comment by berrnd** [comment]
> just noticed that there isn't userfeids for users, is that also a possibility?

Sure, but please keep it to one topic per request - everything else is hard to track...
