### ISSUE TITLE
When adding a product that's default location is set to a freezer, it pulls the default expiry time of a non freezer location

### ISSUE THREAD

**Issue by maglite4cell** [grocy/grocy#1160]
I purchase alot of meat to freeze and have it default location as a freezer location.  When I add it to my inventory, it tells me that it will expire in a week, instead of what I would expect it to be of what I set it as the frozen location.  Is this by design?  What is the best way to handle converting multiple items to the Freezer?

**Comment by berrnd** [comment]
> Is this by design?

Currently yes, as also the hint next to the option indicates - only on moving, so when using the [/transfer page](https://demo.grocy.info/transfer):

> **On moving** this product to a freezer location (so when freezing it), the best before date will be replaced by today + this amount of days

Of course we can (optionally) also apply this always, let's track that in this issue.

**Comment by B1ue-W01f** [comment]
IMO, this should be the default. Im not sure how it compares for everyone else, but 99% of items I put in the freezer go from shop to freezer. Arbitrarily adding them to the fridge and then transferring them is inefficient for me.

Purchase -> Freezer means frozen from purchase.
