### ISSUE TITLE
Adding ingredient to recipie, press save, window stays open

### ISSUE THREAD

**Issue by Wall-em** [grocy/grocy#1162]
Hi, 

I'm beginning to fill out as much as I can for this lovley app. 
When I add ingredients to a recipe, the window stays open. I can press cancel to close it and the ingredient shows up after I save the entire recipe.
This also happens when I use the Inventory via Stock overview. But here I have to reopen the Stock overview to do it again.

**Comment by berrnd** [comment]
When it's a reproducible problem:
Please provide screenshots, a screenvideo or error messages from the browser console and try to reproduce it on [the demo](https://demo-prerelease.grocy.info/).

Most probably this is a browser problem, so double check first that you don't use any addons or something which interfere with that.

Please also the [subreddit](https://www.reddit.com/r/grocy/) for general questions/help as [mentioned in README](https://github.com/grocy/grocy#questions--help--bug-reporting--feature-requests), this is the issue tracker.
