### ISSUE TITLE
Bug: Changing password for admin not possible

### ISSUE THREAD

**Issue by IeP4nieF** [grocy/grocy#1164]
Today I installed grocy two ways on debian buster: With the docker images an "by hand" with apache2. With both installations it is not possible to change the password for admin. After login I clicked on "Passwort ändern" (perhaps "Change Password" in english) and filled out a new password. But clicking on "Speicher" (Safe) doesn't make anything. Nothing happens. Checked with firefox and chrome.

Please make it possible to change password. admin admin isn't good. ;-)

**Comment by IeP4nieF** [comment]
Sorry! I tried for hours and right after filling the bug report, I found the problem:

I pasted the new password into the password fields. This way I can't click on "Safe". But changing on sign manually, makes it possible to safe.

Perhaps there should be a warning, that it is not possible to paste the password.

**Comment by berrnd** [comment]
That's most probably a browser issue (do you use any addons?). Nothing special is done about paste handling. I never write passwords by hand and never noticed that myself.

Please try to reproduce bugs on the demo instances first before reporting and provide error logs (webserver and/or browser console). Not reproducible reports are impossible to solve.
