### ISSUE TITLE
Feature request: [API] current user details endpoint

### ISSUE THREAD

**Issue by Festeazy** [grocy/grocy#1165]
Please describe what you would find useful and please also check (by searching open requests here) if that was maybe already requested.

An API endpoint that would return details of only the current user

https://demo-prerelease.grocy.info/api/users/current

{
    "id": "1",
    "username": "Demo User",
    "first_name": null,
    "last_name": null,
    "row_created_timestamp": "2020-12-09 17:11:53",
    "display_name": "Demo User"
  }

**Comment by berrnd** [comment]
Is now simply `/user`.

=> https://demo-prerelease.grocy.info/api/user
