### ISSUE TITLE
Feature request: Userfield "date" default to current

### ISSUE THREAD

**Issue by Festeazy** [grocy/grocy#1166]
Please describe what you would find useful and please also check (by searching open requests here) if that was maybe already requested.

I was wondering if we could get the "date" userfeild to default to current date

**Comment by berrnd** [comment]
That's now possible for Userfields of type "Date & time" and "Date (without time)" - new option "Default value":

![grafik](https://user-images.githubusercontent.com/2161815/161428264-32e1bee2-4631-4f4c-88c8-4d3b667d9491.png)
