### ISSUE TITLE
Feature request: reverse order in API

### ISSUE THREAD

**Issue by Festeazy** [grocy/grocy#1167]
Please describe what you would find useful and please also check (by searching open requests here) if that was maybe already requested.

just like the order query but reversed, this would be useful to grab the most recent of an item based on date or id

https://demo-prerelease.grocy.info/api/objects/stock_log?order=id

**Comment by berrnd** [comment]
Can now be utilized by the same query parameter (`order`):

> A valid field name by which the response should be ordered, use the separator `:` to specify the sort order (`asc` or `desc`, defaults to `asc` when omitted)

=> https://demo-prerelease.grocy.info/api/objects/stock_log?order=id:desc
