### ISSUE TITLE
Language?

### ISSUE THREAD

**Issue by filoor** [grocy/grocy#117]
I like to see it in Dutch.
Can i help you with translate it to dutch :D

**Comment by berrnd** [comment]
Sure, you're very welcome - as mentioned [here](https://github.com/grocy/grocy#localization), translations are managed with Transifex and I saw you already requested the language there. If you want to help, you can join "the NL team" here: https://www.transifex.com/grocy/teams/93189/nl

**Comment by filoor** [comment]
Hi,

Im getting this Notification 
"This organization has too many words and has been temporarily disabled. To resume using Transifex, please have an organization administrator upgrade to another plan."

on "https://www.transifex.com/grocy/grocy/"

**Comment by berrnd** [comment]
Hm, I don't see this message and accepted your team join request - can you now access the project on Transifex? grocy uses the free plan provided by Transifex for Open Source projects, which doesn't have any word count limitations (as far I can see from the description)...

**Comment by filoor** [comment]
It works Thanks
