### ISSUE TITLE
Bug: On Stockoverview Summary Count of overdue and expired are wrong

### ISSUE THREAD

**Issue by sleeplessnight2** [grocy/grocy#1170]
The Summary-Number inside the Filter Button count the Parent Products too, but the List show's without them.

Here is what i mean:
![Unbenannt](https://user-images.githubusercontent.com/8561601/101800226-5749cc80-3b0d-11eb-8cb0-907ea1a6d634.jpg)

what I expect is that the summary number is the same as the table rows...

**Comment by berrnd** [comment]
Someone created a product "test" on that demo with the new option "Show on stock overview page" checked. So the product is hidden from the table, but still part of the summary numbers

Depends on interpretation, but I would say this is ok - the idea about that new option was mainly to hide parent products you never buy itself (#906).

(Personally I don't need/use that - the stock overview page is about to see what's in stock, so I want to see everything in stock. The final solution about parent/child product display is #449).

**Comment by sleeplessnight2** [comment]
It's just confusing that there is a number, that don't fit the rows.

That's all. There is no place for a interpretation - it's confusing. the showed text is a lie...

It's like the German Rail - It borders on miracles when the time corresponds to the arrival of the train

But ok, I give up

**Comment by berrnd** [comment]
> it's confusing. the showed text is a lie

The number is correct, the product is hidden, because you said you don't what to see it, But it's still overdue.

The new option to hide products on the overview page is just a filter, search for a string that doesn't match any product and also click the "x products are overdue" button - you will not see any product. Confusing in the same way? Then better remove the filter-buttons, and the search field...

![grafik](https://user-images.githubusercontent.com/2161815/101831892-e3bcb500-3b36-11eb-8baf-00f8cd787ede.png)

Don't use (uncheck) the new "Show on stock overview page" product option and you will not have the problem. I will do the same, because, as said, for me this makes no sense. However, I implement things that don't make sense for me, and not for you, but probably for someone else, at least the one who requested it.

**Comment by sleeplessnight2** [comment]
I think, you think different. 
For example:

At a price comparison portal like idealo.de etc:

If I say "show me all 200 Laptops", then expect I 200 products in the list. 
Set I a additional filter "show me all laptops under 500€", then won't tell me the summary again "200" and the list shows 80 Products. The summary say "80" - Even if there are still 200.
But I don't care about the other 120.  I filter them consciously.

It's still math. 10 -1 = 9 and not 10.

If I use a filter, the summary must be filtered too. 

This is the usual way of using filters on the web and its not a special wish from me.

https://de.m.wikipedia.org/wiki/Filter_(Software)

**Comment by sleeplessnight2** [comment]
Or in short words: The new filter isn't completed...

**Comment by berrnd** [comment]
There is no new filter in general, we have all the filter inputs/dropdowns above the table since ever - the numbers in the "shortcut-fiilter-info-buttons" never changed based on the selected filter. I find that ok, nobody else complained about that so far.

> At a price comparison portal like idealo.de etc:

That's not the same, this is a "shortcut" to populate the filters below, not a refinment-filter like you have in mind.

However, I'll also give up, too much time wasting.
If I do it just wrong in your opinion, that's also ok.
When so much things obviously are confusing or just wrong in grocy for you, my advise would be to not use it.

**Comment by sleeplessnight2** [comment]
Können wir das freche von mir vergessen?... Weiß der Geier, was mich da geritten hat.
Ich hoffe, das du mir das nicht nachträgst...

Ich möchte für _mich selbst_ wissen, wie ich das verhalten der Filter für alle 4 angleichen kann. Ich meine damit, keine Step-für Step anleitung, lediglich, wo die Filterung der angezeigten Spalten umgesetzt wurde.

Lass mich das erklären, was ich für mich vorhab, damit du mich überhaupt verstehst. (Ziehe dabei die Bilder aus diesem "Report" mit zu rate)
  - Zur Zeit ist es so, das der Status-Filter `x-Produkte unter Mindestbestand ` auch Oberprodukte anzeigt.
  - Die anderen 3 Filter (bald überfällig, ist überfällig, abgelaufen) Zeigen keine Oberprodukte an. Jedoch zählt die  Zahl in dem Button das Oberprodukt mit.
  
Ich würde gerne entweder das Oberprodukt mit anzeigen lassen - also genauso wie der `unter Mindesbestand` die Stock-Rows in der Tabelle filtert - oder die Gesamtzahl entsprechend ohne Oberprodukte.

Wie die Zahl gebildet ist, hab ich schon ermittelt: Das ist einfach die Länge des Arrays. Dort ist natürlich auch das Oberprodukt mit aufgelistet.
Angezeigt wird jedoch alles außer die Oberprodukte.

Wie wird das gefiltert? Also, wo werden die Oberprodukte für die Table-Rows herausgefiltert?
Es macht Sinn, diese herauszufiltern, da es ja keine "echten" Produkte sind, die ablaufen würden.
Lässt sich dieser Filter evtl. auch auf die Gesamtzahl legen?

**Comment by berrnd** [comment]
Alles ok, vermutlich war ja das meiste ja auch nur wegen falsch verstanden wegen Englisch - von daher, mach dir kein Kopf, wirklich alles gut... 🙂

Funktioniert bei allen Seiten mit diesen "Filter shortcut buttons" gleich, hier als Beispiel mal versucht aufzuschreiben für die Bestandsübersicht:

Der Shortcut-Button setzt eigtl. erstmal nur das "Status" Dropdown:
https://github.com/grocy/grocy/blob/694b78f72a1f8d79c3358be28264c623d83a4823/public/viewjs/stockoverview.js#L74-L79

Das Status-Dorpdown macht wiederum einfach eine simple Spaltensuche:
https://github.com/grocy/grocy/blob/694b78f72a1f8d79c3358be28264c623d83a4823/public/viewjs/stockoverview.js#L71

Dafür wird (serverseitig) in eine versteckte Spalte der entsprechende Status der Zeile geschrieben:
https://github.com/grocy/grocy/blob/694b78f72a1f8d79c3358be28264c623d83a4823/views/stockoverview.blade.php#L349-L366

Das steuert auch gleichzeitig die farbliche Hervorhebung:
https://github.com/grocy/grocy/blob/694b78f72a1f8d79c3358be28264c623d83a4823/views/stockoverview.blade.php#L182

Vielleicht hilft das ja weiter...

Noch allgemein:
Die Bestandsübersicht zeigt generell nur Produkte im Bestand (unabhängig von der neuen Option "Zeige Produkt auf Bestandsliste", weil das halt bisher so war, evtl. wirds ja mal noch geändert)
Außer ein Produkt ist nicht im Bestand, aber unter Mindestbestand.
Gleichzeitig gibts für Parent-Produkte ja noch die Option "Mindestbestände von untergeordneten Produkten aufsummieren", was entsprechend hier mit reinspielt.
Diese Steuerung ist dann abgebildet in der SQL view `stock_current` ([code ref](https://github.com/grocy/grocy/blob/694b78f72a1f8d79c3358be28264c623d83a4823/migrations/0108.sql#L2-L51)), die quasi die Basis für die Bestandsübersicht-Seite ist.

**Comment by berrnd** [comment]
Ich habe aus gegebenem Anlass die neue Option nochmal quasi "umgedreht", ich denke, das ist so vielleicht logischer - siehe https://github.com/grocy/grocy/commit/c1ac9e8a45f0b3771f9d6ea098d1afe006d8eead.

![grafik](https://user-images.githubusercontent.com/2161815/102815791-3e72ce00-43cd-11eb-8b2e-de5652ac418e.png)

**Comment by sleeplessnight2** [comment]
> Vielleicht hilft das ja weiter...

Sehr sogar, danke.
Auch das umdrehen macht deutlich mehr Sinn.

Aus welchen API-Variabeln bildest du den ab, welches Product ein "Parent Product" ist? Weil ich bisher nirgendswo solch eine gefunden hab. Ich bilde mir dies bisher aus einer "und-Verknüpfung" von `cumulate_min_stock_amount_of_sub_products == false && amount > 0` - und das funktioniert halt nur, solange die beiden Erfüllt sind....

**Comment by berrnd** [comment]
Wenns um den [`/stock/volatile`](https://demo-prerelease.grocy.info/api/stock/volatile) endpoint geht (Properties `due_products` und `overdue_products` reichts `amount` und `amount_aggregated` zu betrachten.

`amount` ist die Menge des Produkts selbst, `amount_aggregated` die inkl. der Child-Produkte - sind die beiden nicht gleich, kanns entsprechend nur ein Parent-Produkt sein.

Ansonsten gibts keinen Endpoint aktuell der irgendwie die Hierarchie ausgibt oder ähnliches, aber da es ja aktuell nur 1 Level geben kann, reicht es ja [alle Produkte](https://demo-prerelease.grocy.info/api/objects/products) zu holen und ein Produkt ist dann ein Parent-Produkt, wenn dessen `id` in `parent_product_id` eines anderen Produktes steht.

**Comment by berrnd** [comment]
Vergessen:
`is_aggregated_amount` gibts ja noch als Eigenschaft, auf der Productcard wird das benutzt um den aufsummierten Wert (Menge inkl. die der Childproduct) anzuzeigen oder nicht...

https://github.com/grocy/grocy/blob/2e3c237648aec73d04f0810b4525550eb0c4be55/public/viewjs/components/productcard.js#L26-L45
