### ISSUE TITLE
Question/Enchancement: API Filter

### ISSUE THREAD

**Issue by Festeazy** [grocy/grocy#1173]
Please describe what you would find useful and please also check (by searching open requests here) if that was maybe already requested.

Is there a way to filter by "null"?

I tried != !> and more but nothing works

**Comment by berrnd** [comment]
No - the filters are directly translated into a SQL query and `null` is not a value...

So let's extend the filter options somehow to make that possible.

**Comment by berrnd** [comment]
I've added some special handling for `null` values in https://github.com/grocy/grocy/commit/51a95814e095069f9c6874d74dc693350e159bff - so it now "just works" by using the value `null` for the API `query[]` parameter (and only for the the operators `=` and `!=`).

Example (once the pre-release demo is updated):
All products which don't have a picture:
https://demo-prerelease.grocy.info/api/objects/products?query[]=picture_file_name=null
