### ISSUE TITLE
Feature request: API Query Filter Request: OR

### ISSUE THREAD

**Issue by Festeazy** [grocy/grocy#1174]
Please describe what you would find useful and please also check (by searching open requests here) if that was maybe already requested.

when searching for items using a query, be able to use multiple querys linked by an OR 

"https://demo-prerelease.grocy.info/api/objects/products?query[]=name=milk **OR** name=yogurt"

**Comment by berrnd** [comment]
There is now a new option to filter by a regular expression (operator `§`).

Example to get the product `Milk` or `Yogurt` (`name` matches exactly `Milk` or `Yogurt`):
https://demo-prerelease.grocy.info/api/objects/products?query[]=name§^Milk$|^Yogurt$

https://demo-prerelease.grocy.info/api/objects/products?query[]=name§Milk|Yogurt would mean a contains search, so will return any product where name contains `Milk` or `Yogurt`.
