### ISSUE TITLE
Bug: Cannot save products because of missing barcode column

### ISSUE THREAD

**Issue by darkspirit510** [grocy/grocy#1176]
Saving products fail with:

`"{\"error_message\":\"SQLSTATE[HY000]: General error: 1 no such column: barcode\"}"`

I don't want to use barcode scanning (for now), so my config is like:

```
Setting('STOCK_BARCODE_LOOKUP_PLUGIN', 'DemoBarcodeLookupPlugin');
Setting('DISABLE_BROWSER_BARCODE_CAMERA_SCANNING', true);
```

Any hint how to fix this? Currently, my workaround is to delete the barcode input field in the form every time I add/edit a product.

**Comment by berrnd** [comment]
If database tables/columns exist or not doesn't depend on settings or feature flags, the database schema is always the same.

This column was created in the [very first migration](https://github.com/grocy/grocy/blob/bfbaa7e9d5ee5af3d9d35079dda50f59f0a8fcb6/migrations/0001.sql#L9).
Database migrations run on the root route ([README ref](https://github.com/grocy/grocy#database-migrations)).

So if the `products` table is there but without the `barcode` column, I have no idea how this can happen (unless you use the `master` branch, where everything about barcodes has changed completely).

However, when you run the latest release and this column is definitely missing, manually executing the SQL command `ALTER TABLE products ADD barcode TEXT` would fix it.

**Comment by darkspirit510** [comment]
Hi berrnd,
thank you for the reply. I can't tell you which version I'm running, it's the tag latest from linuxserver/grocy image.
Your SQL statement fixed the issue, I can store products.
Thank you!

**Comment by berrnd** [comment]
👍

> I can't tell you which version I'm running

Is visible on the about page (top right corner settings menu -> "About grocy").

**Comment by darkspirit510** [comment]
I'm using 2.7.1, but I can't tell if I'm running 2.7.1 release or HEAD from master (didn't check the Dockerfile from linuxserver). But, nevermind. it's working now 🥳
