### ISSUE TITLE
Bug: Copy product function uses defaults instead of copy-from products values 

### ISSUE THREAD

**Issue by Festeazy** [grocy/grocy#1179]
Please describe the bug as detailed as possible, provide the steps how to reproduce it and maybe attach screenshots where useful.

when copying a product, looks like the page will use the system defaults for location and such instead of the originals values 

https://demo-prerelease.grocy.info/product/new?copy-of=1

**Comment by Festeazy** [comment]
works now for some reason?

**Comment by berrnd** [comment]
Can be improved, the stock-setting-defaults are set first, then the API call to `objects/products/{productId}` is done, when that finishes, the values from the "copy-of" product are set - so a potential timing problem, let's improve that.
