### ISSUE TITLE
Feature request: Self Produced Products have configurable Quantity stock unit produced from recipe

### ISSUE THREAD

**Issue by mlb-** [grocy/grocy#1181]
Thanks for the software, I find the concept of kitchen/house ERP software very enticing, and a clear step above many spreadsheets 😄 

My user story:
- I buy bags of rice from the store (available in multiples of 5 pounds). I enjoy I can track this quantity and have a "minimum stock amount" help remind me when to buy more.
- I cook rice using a recipe which measures rice in cups, a volumetric measurement. I can use the "Product overrides" QU conversions to convert from weight to volume (as that conversion is specific to the density of the product). The Recipe even manages the conversion to consume the correct amount of rice (albeit, with a few decimals of rounding error), and produce a "cooked rice" product, with "best before" set in the future!

However, while I can mark the recipe for 6 servings, the "cooked rice" produced via the recipe only allocates a single "Quality unit stock", even if "Factor purchase to stock quantity unit" is set greater than 1. Having an accurate track of cooked rice helps in planning meals where rice is a side, or in successive recipes (e.g., making rice balls).

I've tested this on https://en.demo.grocy.info/, but there appears to be an automated reset, periodically clearing the sandbox.

I've searched Reddit and checked the tutorials, but I can't find an option/feature that would allow me to create "cooked rice" from the recipe without having to edit the "cooked rice" stock amount after. Can there be:
- A target unit for recipe output? This would be useful to plan meals with a Product override conversion from a "pot of" unit, to a "servings" unit, and further recipes tracking cups/ounces, etc. but would require a transitive unit conversion feature, possibly bi-directional unit conversions on pairs of units, and defining product unit conversions not based on the Product's "Quantity unit stock" unit. Transitive unit conversions would also simplify my Product override unit conversion as I track the density conversion from pounds to cups, instead of the slightly more intuitive cups to ounces.
- Or a "Quantity unit produced", along with a "Factor produced to stock quantity unit" in the recipe?
- Or, have the recipe "Servings" count used as the Quantity stocked.
- All assuming this isn't a bug, and the intended behaviour is for a recipe to produce a Quantity purchased, following the same rules as Purchasing a product and a Quantity stocked stored is multiplied by the "Factor purchase to stock quantity unit". In which case, I suppose this is a bug report, and I can submit a feature request about bi-directional, transitive unit conversions later 😉 

Thanks again!

**Comment by berrnd** [comment]
> Or, have the recipe "Servings" count used as the Quantity stocked.

That's already the case, the "Desired servings" you select on the "main recipe page" are used for how many of the "Produces product" product will be added to stock.

In the current release version, this relates to the products purchase unit, will be changed to be related to products stock unit in the next release.

![grafik](https://user-images.githubusercontent.com/2161815/102052842-0e349980-3de7-11eb-855f-7f5a4c737315.png)

> I've tested this on https://en.demo.grocy.info/, but there appears to be an automated reset, periodically clearing the sandbox.

Yes, that's the case.
The pre-release demo has an option to create a "private demo instance": https://www.reddit.com/r/grocy/comments/jwnk9b

**Comment by mlb-** [comment]
Awesome! And the "Desired servings" appears to be persistent as well! Thanks for explaining the feature that I somehow missed, despite being in big letters under the button I've been clicking this whole time :smile:
