### ISSUE TITLE
Feature Request: Consume opened products first

### ISSUE THREAD

**Issue by sleeplessnight2** [grocy/grocy#1183]
If a product is in stock and both have the same MHD date, it consumes whichever is seen first from the API array and not which has the DB entry "open = 1".

In that case, an entry other than the one marked as open is consumed and the opened product remains untouched in the stock.

A solution would be to always give an entry with the DB entry "open = 1" priority over all others when consuming. This would ensure that exactly the opened entry is consumed and not an unopened entry.

Don't ask me now, why I still report at all... It's probably my own laziness to reverse engineer everything and that's why you can be much more effective than me.
You don't need to explain anything, just close the case if it's not a bug. And then just leave me the line(s) number responsible for selecting the date. Or rather the ones that decide which stock entry gets deleted.

Edit:
You can try it out:

Purchase 3 or more times a product with the same best before date. Then mark one as open.
After that consume it. With a little "bad luck" one is booked out and the opened remains.
I tried it on your demo version with the cheese. Went wrong at the first go.

**Comment by berrnd** [comment]
Consuming picks (since ever) the item to consume on the (not configurable rule) "First due first, then first in first out" unless you pick a specific stock entry, which is always possible.

That's also mentioned in the hint next to that option on the consume page:

![grafik](https://user-images.githubusercontent.com/2161815/102126925-0ce98800-3e4c-11eb-87d5-578e22ccc9fe.png)

It happens basically here:
https://github.com/grocy/grocy/blob/54e4d3217cd45cd5e51b919190f3cd14232ffd9c/services/StockService.php#L677-L701

So that's not a bug, but a feature request - I've changed the title accordingly.

**Comment by sleeplessnight2** [comment]
Thank you :) 

Just for food for thought, which is why I mention: 

The same thing happens with stock overview quick consume. It would be 3 more steps to select the opened product.

Based on reality, it is less likely that you will mark a product as consumed that is still unopened than one that has already been opened. For the first one, there is then the function you mentioned to consume a special entry.

For the more common case - based on practice - the opened one should be consumed first.

More frequently it is therefore, since one has more open products in the household, than which are planned to consume immediately. The latter is often the case in cooking, the former in the daily use of things - for example, cold cuts, breakfast, etc..

**Comment by berrnd** [comment]
Of course makes sense, so simply changing the default rule into "First opened first, then first due first, then first in first out" should be enough and also reality-wise ok I think...

**Comment by sleeplessnight2** [comment]
Okay, the Rule thing is easy.
I just had to insert `->orderBy('open', 'DESC')` - that's it.

In the course of this I noticed something else: The undo principle does not work as expected.
If I undo the transaction, it posts back the formerly opened one as not opened.
That wouldn't really be considered an "undo", but a change.

I'm assuming this happens in the `public function UndoBooking` @ Stockservice.php ?
If so, is then `elseif ... TRANSACTION_TYPE_CONSUME` the responsible area ?
If also yes, how can I include the old entry `open` again ? Because the last column is `opened_date`....

If you think that this is indeed not correct, I will open a new case for it. Otherwise, I would be grateful for the small explanation help that I can do this for me.

**Comment by berrnd** [comment]
>  If I undo the transaction, it posts back the formerly opened one as not opened.

Undoing a transaction is exactly this - I opened a specific stock item with an specific amount (regardless if it was picked by the default rule or manually), undoing should exactly undo that, so what you said:
>  If I undo the transaction, it posts back the formerly opened one as not opened.


It happens here:
https://github.com/grocy/grocy/blob/54e4d3217cd45cd5e51b919190f3cd14232ffd9c/services/StockService.php#L1245-L1259

**Comment by sleeplessnight2** [comment]
Attention: Possible waste of time.

Yes, from the point of view it is correct as it is. But that is not the expected action that the text on the pop-up bubble conveys.

A non-web designer/programmer always sees the word "Undo" as referring to the action just taken, not to a transaction.

Let's face it, Ctrl+Z or "Edit - Undo" in the menu of any program always undoes the exact action previously taken - it neither adds anything nor changes the past action in the process.

If a "Ctrl+z" in MS Visual Studio code or PHP-Storm would not undo exactly what you just typed, but somewhere else in the code additionally changed something: I don't think anyone would agree with that....

Then the text that comes from the message would have to be changed.
Because there it says "removed from xxx " "undo".
The "undo" is related to the action. It goes without saying that the action just performed is undone.
In this case the text message would have to be changed, in which it is clearly to be recognized that with "undo" not the before transacted action is meant, but a transaction.
Or: One changes the function in such a way, as the text suggests it at present.

But well - I wanted to change it for me. So that it works the way a non-programmer understands the world of the web.

**Comment by sleeplessnight2** [comment]
We have misunderstood each other.

I have this behavior when I _**consume**_ a product already opened.
After that, it books it back into inventory as unopened.

Try it on yourself:
Mark an **already** opened product as consumed. Undo the step again. After that it is no longer opened, but unopened in the inventory.

I didn't realize this misunderstanding until I saw the lines you mentioned. They are not needed in the operation process I meant, but the "consume" condition. (Line 1158-1176)

**Comment by berrnd** [comment]
Ich versteh dich mal wieder nicht, nicht mal über was wir genau sprechen, dachte "öffnen", aber anscheinend ja auch "verbrauchen" oder wir vermischen da mal wieder was wegen Englisch...

Verbrauchen:
Ich verbrauche "1 Packung xy", in der Benachrichtigung steht "Removed xy from stock", der "Undo" Button dort macht genau das rückgängig (also fügt xy wieder im Lager hinzu). Der Undo-Button im Journal macht dasselbe.

Öffnen:
Genau das selbe, nur das natürlich nix hinzugefügt wird beim Rückgängig machen, weil wurde ja auch nix entfernt vorher - es geht nur um die "Geöffnet" Eigenschaft, die wird entsprechend beim Öffnen gesetzt, beim Rückgängig machen zurückgesetzt.

Und dein Vergleich hinkt auch hier wieder, grocy ist kein simpler Texteditor - du verbrauchst xy Stück von irgendwas, das hat evtl. nicht nur eine Aktion ausgelöst, sondern mehrere, weil verschiedene Bestandseinträge betroffen waren, deswegen wird das auch in einer Transaktion zusammengefasst, beim Undo werden entsprechend alle Aktionen der Transaktion rückgängig gemacht, sodass danach alles ist wie vor der Transaktion - also im Ergebnis dann wie im Texteditor.

Ich verstehe also vor allem nicht was 
> If I undo the transaction, it posts back the formerly opened one as not opened.
> That wouldn't really be considered an "undo", but a change.

heißen soll. Nach dem Undo ist alles wie vorher, natürlich ist dabei was geändert und "zurück geändert" worden. Im Lager (technisch die Tabelle `stock` ist vorher/nachher kein Unterschied, aber natürlich ist das im Journal (Tabelle `stock_log`) protokolliert, weil warum nicht - eine Änderung ohne Protokoll ist immer weniger nachvollziehbar, ich hab nix gegen Nachvollziehbarkeit.

Ich benutze übrigens grocy auch täglich, so als Anwender, und mach dieses Lagersoftwarezeug von der Art her sogar beruflich, jetzt nicht für den Kühlschrank, eher in größeren Dimensionen und für unsere Industrie. Einige deiner Requests machen defintiv einfach keinen Sinn. Du denkst anders, ist ja ok, aber bitte dann nicht immer alles als rießen Bug melden der jedes mal das Grundprinzip als komplett bescheuert darstellt mit teilweise abwegigen Vergleichen. Wäre es anders, würden wir hier das ständig hören. grocy gibts nun seit über 3 Jahren, guck dich hier oder auf reddit um - natürlich gabs/gibts Logikfehler, aber anscheinend passt die grundlegende Logik für alle, was geschätzt auf alle Fälle 10K Leute sein müssen.

EDIT:
Deine letzte Nachricht hier hab ich erst gesehen nachdem ich das hier geschrieben habe - schau ich an und verschiebs in einen neuen Issue damits trackbar bleibt - lasse trotzdem das hier mal so stehen...

**Comment by sleeplessnight2** [comment]
Gibt's auf Github nicht eine PM funktion?... hmmm

Sorry,
ich sollte wohl eher lernen, richtig zu reporten. Wenn ich es gleich vollständig beschrieben hätte, wäre der Käse nicht passiert. Ich mach mir zukünftig mal ein Plan, damit ich immer alles aufschreibe, was gemeint ist. Ich hab irgendwie nur die Hälfte erzählt und daraus sollst du das Problem verstehen. Das kann nur schiefgehen und bei mir so ankommen, als wenn du der Meinung bist, das der nun verstandene Fehler korrekt ist.
Sorry nochmals. Werde zukünftig ein kurzen, deutlichen Report schreiben, ansonsten bitte kommentarlos löschen, wenn ich mal wieder nur die Hälfte erzähle.
