### ISSUE TITLE
Bug: Calendar doesn't display when `Setting('FEATURE_FLAG_RECIPES', false);`

### ISSUE THREAD

**Issue by jceloria** [grocy/grocy#1184]
```
{
    "Version": "2.7.1",
    "ReleaseDate": "2020-04-17"
}
```

![Screen Shot 2020-12-14 at 12 55 55 PM](https://user-images.githubusercontent.com/1354592/102122954-dee45380-3e0b-11eb-9ee4-1364f7d45ce0.png)
![Screen Shot 2020-12-14 at 12 56 37 PM](https://user-images.githubusercontent.com/1354592/102122997-ec99d900-3e0b-11eb-8939-e7b11b48776e.png)

**Comment by berrnd** [comment]
Is reproducible with v2.7.1, but not in current master - so probably already fixed, but can't find an issue or commit explicitly for that problem...
