### ISSUE TITLE
Feature request: Add barcode field as userfield

### ISSUE THREAD

**Issue by daviewales** [grocy/grocy#1186]
Userfields and userentities open up a lot of possibilities.
However, it would be great if barcodes could be added as userfields.

**Comment by berrnd** [comment]
A barcode is techincally just a string (text) - so basically a "Text (single line)"-type Userfield.

Or do you want to to able to pick/scan a Userobject by the attached barcode then?
That's already requested in a generic approach for all objects in #221.

**Comment by daviewales** [comment]
I was hoping to be able to scan barcodes to perform actions on userentities.
e.g. If I made a userentity for tracking DVDs, then I would hope to be able to add the DVD barcode by scanning it, and perhaps be able to scan the barcode and select an action such as 'loan' or 'return' or 'watch'.
 
If that's already in #221, perhaps this is a duplicate?

**Comment by berrnd** [comment]
#221 is only about the possibilty to select an object in a dropdown by scanning a barcode, just like for products, but for any object.

> If I made a userentity for tracking DVDs, then I would hope to be able to add the DVD barcode by scanning it, and perhaps be able to scan the barcode and select an action such as 'loan' or 'return' or 'watch'.

Sounds like you want to pick the DVD by scanning its barcode, then yes, this is part of #221.
"Loan/Return/Watch" is probably then just a "Select list" Userfield, scanning the barcode would simply open the Userobjects edit page (just like when you click the edit button manually).

**Comment by beetle442002** [comment]
@daviewales 
> I was hoping to be able to scan barcodes to perform actions on userentities.
> e.g. If I made a userentity for###  tracking DVDs, then I would hope to be able to add the DVD barcode by scanning it, and perhaps be able to scan the barcode and select an action such as 'loan' or 'return' or 'watch'.
> 
> If that's already in #221, perhaps this is a duplicate?

Not to detour from grocy but check out Readerware I have been using them for over a decade.  You can scan and catalog dvds by the barcode and it will get alot of information on it (normally), actors, directors, genre, thumbnail and it has a "loan" tracking feature.
[https://www.readerware.com/index.php/products/details/video](https://www.readerware.com/index.php/products/details/video)

**Comment by daviewales** [comment]
Thanks @beetle442002! That's pretty much exactly what I was looking for. I was just hoping to find a way to do it within Grocy. But I may consider it as an alternative.
