### ISSUE TITLE
Feature request: Add option to use kilojoules (kJ) as unit of energy instead of kcal

### ISSUE THREAD

**Issue by daviewales** [grocy/grocy#1187]
Currently, the energy of a given product may be specified in kilocalories (kcal). It would be good if there was a setting to change this to kilojoules (kJ).

<img width="587" alt="Screen Shot 2020-12-15 at 9 23 57 pm" src="https://user-images.githubusercontent.com/2499066/102202959-16dabc00-3f1c-11eb-8168-e67efe243f37.png">

**Comment by berrnd** [comment]
If you want to have a separate field:
Use Userfields (see #176).
Summarizing numeric Userfields on recipes/meal plan/etc. is tracked in #413.

If it's only about how this field is named, a solution would be maybe to create a separate localization where you just change this string or use [custom JS](https://github.com/grocy/grocy#adding-your-own-css-or-js-without-to-have-to-modify-the-application-itself) for that - I can help build an example if you want.

**Comment by daviewales** [comment]
Thanks @berrnd. I'm not sure if that's quite what I'm looking for.

It's a unit conversion thing.
1 kcal = 4.184 kJ
https://en.wikipedia.org/wiki/Calorie

In Australia, the primary unit of measure for food energy is the kilojoule (kJ), rather than the kilocalorie (kcal).

I was hoping to be able to enter kilojoules rather than kilocalories for products, which would require some unit conversion code, and a setting option perhaps?

**Comment by berrnd** [comment]
> I was hoping to be able to enter kilojoules rather than kilocalories for products

Ok - so why not use the existing field and just enter the kJ there and maybe change the field label as mentioned above?
It's just a number, if you always enter kJ there, nothing needs to be converted...
I would simply do it like that.

The ultimate solution to add any field named however you like and also summarize it at any place is #413.

**Comment by daviewales** [comment]
Thanks. I'll wait for #413.

> why not use the existing field and just enter the kJ there and maybe change the field label

I was hoping to be able to convert back and forth between kJ and kcal.
