### ISSUE TITLE
Feature Request: "Inventory checked list"

### ISSUE THREAD

**Issue by liffez** [grocy/grocy#1188]
When checking up on a larger number of inventory items it would make the process more effective if there could be an “Inventory overview list” that shows all the active inventory items 
The list could have a “Check this is done” button (as in the shopping list) to easily see which items has been checked. There could then be a button at the top of the list to” release” the checked items when you start a new bigger inventory checkup.
And of cause a button for open the inventory change window.

**Comment by berrnd** [comment]
Merged into #1988.
