### ISSUE TITLE
Feature request: Swagger configuration file

### ISSUE THREAD

**Issue by Gerw88** [grocy/grocy#1193]
Hi
I just noticed this Node-Red plugin:
[https://www.npmjs.com/package/openapi-red](https://www.npmjs.com/package/openapi-red)

For API's that use Swagger, it makes a neat job of making requests from Node Red.

However, it requires a swagger configuration file (possibly `swagger.json` or `swagger.yaml`). Which I'm guessing exists somewhere, but if it's here in the repo, I wasn't able to find it. (Excuse my lack of github skills!) Could you see if it's possible to expose this file in a way that it could be used for the plugin?

**Comment by Gerw88** [comment]
I started using Grocy as a Hassio plugin... Hence why the Node Red plugin, but I guess there's also a [swagger-js](https://github.com/swagger-api/swagger-js) library that would use it too?

**Comment by berrnd** [comment]
grocy has a valid OpenAPI 3 Specification file: [grocy.openapi.json](https://github.com/grocy/grocy/blob/master/grocy.openapi.json)

This file is served at [`/api/openapi/specification`](https://demo.grocy.info/api/openapi/specification) and also populates the integrated Swagger UI instance at [`/api`](https://demo.grocy.info/api).
