### ISSUE TITLE
Feature request: feature to 'Harvest' food, to keep a 'Growing' table?

### ISSUE THREAD

**Issue by Gerw88** [grocy/grocy#1195]
Blue-sky idea...
I've been testing an idea with a custom `userentities` object I called 'Growing', which is a table of crops and their details.
I've a few `userfields` set up, with the species of the crop/plant, months that the crop is productive (start date and end date), growing_location, produces_which_product_id
And I was thinking a modal-type form in the interface, like the Consume and Purchase forms that would allow you to record your yield and add the produce to your inventory. Maybe there's value in tracking your yield as well.

I've added our own stuff, but we only have a small greenhouse and some herbs in window boxes.
Might be of interest, might promote us nerdy data-entry-masochists to do a bit more gardening maybe? :)

**Comment by berrnd** [comment]
Duplicate (when I got what you mean) of #179.

**Comment by Gerw88** [comment]
Thanks @berrnd. Very interesting to read #179.
