### ISSUE TITLE
Bug: Cannot set property '_DT_CellIndex' of undefined

### ISSUE THREAD

**Issue by sleeplessnight2** [grocy/grocy#1202]
I'll try my best to speak intelligibly clear time :D
And should this be known - then just delete this without comment.

An error results if you set the setting "FEATURE_FLAG_STOCK_PRICE_TRACKING" to false in the config.php.

Please reproduce the following steps:
1. set the named setting to "false".
2. edit a product.
2a. If the product already has a barcode stored, it will not appear.
3. add a barcode. This will fail.

Likewise, the product cannot then be determined at consumption based on the barcode.

The console will throw the following error:
`Uncaught TypeError: Cannot set property '_DT_CellIndex' of undefined`

Unfortunately I didn't have the time today to find out the error myself. Up to now I could find out so much, that I can report here reconstructable. (I always use a new git-clone to isolate my errors).

**Comment by sleeplessnight2** [comment]
One thing remains and I don't know if it's just me or in general:

I get an `Uncaught TypeError: Cannot read property 'SetId' of undefined` in the console when purchasing something and entering this via the barcode.
The error somehow doesn't seem to affect the process though.

The error no longer comes when the named setting at config.php is set to `true`.

A bit more details:
Same as above:
1. set the variable to false.
2. use a product barcode when purchasing.

Everything works, but the console throws me the error named above.
It points to line 319 in purchase.js : `SetId(barcode.shopping_location_id);
`
Can you reproduce this?

**Comment by berrnd** [comment]
Is also fixed, thanks for testing.

However, Browser Console errors/warnings that don't break anything are IMHO not really worth looking into them - there is much more console spam from the third party components used (which I can't fix, unless doing it upstream)...
