### ISSUE TITLE
Bug: Can't delete API Keys 

### ISSUE THREAD

**Issue by sleeplessnight2** [grocy/grocy#1203]
API Keys are not removable.

Steps to reproduce it:
1. create an API Key for the user
2. click on Delete.
3. confirm the query with "yes".

There is an API error here. Console-Details:
```
response:"{"error_message": "Invalid entity"}"
responseURL: "https://en.demo-prerelease.grocy.info/api/objects/api_keys/1"
status: 400
@ manageapikeys.js Line 63
```

Sorry I find something again :(

**Comment by berrnd** [comment]
> Sorry I find something again :(

Gar kein Problem, im Gegenteil - vielen Dank fürs Testen! 🙂

Ich bin ja eher der, der alles immer kaputt macht... 😂
