### ISSUE TITLE
Bug: Recipes and Meal plan: Cannot set Row "clean" without id

### ISSUE THREAD

**Issue by afv** [grocy/grocy#1204]
Hi there :)

I'm getting this error on Recipes and Meal plan pages.

Not sure if it has something to do with my database structure: I'm having some trouble keeping up with the master branch (that I use to get access to the newest features and to be able to test/report bugs) as multiple migrations that were created/ran months ago are being changed, and I have to keep looking at the commits to change the database manually instead of them being a new migration on top of the older ones :disappointed: 
Doesn't look like a good idea to edit existing migrations! :sweat_smile:

Error source:
```
/srv/grocy/grocy/vendor/morris/lessql/src/LessQL/Row.php:478
```

Error message:
```
Cannot set Row "clean" without id
```

Stack trace:
```
#0 /srv/grocy/grocy/vendor/morris/lessql/src/LessQL/Result.php(158): LessQL\Row->setClean()
#1 /srv/grocy/grocy/vendor/morris/lessql/src/LessQL/Result.php(649): LessQL\Result->execute()
#2 /srv/grocy/grocy/helpers/extensions.php(5): LessQL\Result->getIterator()
#3 /srv/grocy/grocy/controllers/RecipesController.php(81): FindObjectInArrayByPropertyValue()
#4 /srv/grocy/grocy/vendor/slim/slim/Slim/Handlers/Strategies/RequestResponse.php(43): Grocy\Controllers\RecipesController->Overview()
#5 /srv/grocy/grocy/vendor/slim/slim/Slim/Routing/Route.php(384): Slim\Handlers\Strategies\RequestResponse->__invoke()
#6 /srv/grocy/grocy/vendor/slim/slim/Slim/MiddlewareDispatcher.php(81): Slim\Routing\Route->handle()
#7 /srv/grocy/grocy/vendor/slim/slim/Slim/MiddlewareDispatcher.php(81): Slim\MiddlewareDispatcher->handle()
#8 /srv/grocy/grocy/vendor/slim/slim/Slim/Routing/Route.php(341): Slim\MiddlewareDispatcher->handle()
#9 /srv/grocy/grocy/vendor/slim/slim/Slim/Routing/RouteRunner.php(84): Slim\Routing\Route->run()
#10 /srv/grocy/grocy/middleware/LocaleMiddleware.php(16): Slim\Routing\RouteRunner->handle()
#11 /srv/grocy/grocy/vendor/slim/slim/Slim/MiddlewareDispatcher.php(313): Grocy\Middleware\LocaleMiddleware->__invoke()
#12 /srv/grocy/grocy/middleware/AuthMiddleware.php(76): class@anonymous->handle()
#13 /srv/grocy/grocy/vendor/slim/slim/Slim/MiddlewareDispatcher.php(313): Grocy\Middleware\AuthMiddleware->__invoke()
#14 /srv/grocy/grocy/vendor/slim/slim/Slim/Middleware/RoutingMiddleware.php(59): class@anonymous->handle()
#15 /srv/grocy/grocy/vendor/slim/slim/Slim/MiddlewareDispatcher.php(147): Slim\Middleware\RoutingMiddleware->process()
#16 /srv/grocy/grocy/vendor/slim/slim/Slim/Middleware/ErrorMiddleware.php(107): class@anonymous->handle()
#17 /srv/grocy/grocy/vendor/slim/slim/Slim/MiddlewareDispatcher.php(147): Slim\Middleware\ErrorMiddleware->process()
#18 /srv/grocy/grocy/middleware/CorsMiddleware.php(30): class@anonymous->handle()
#19 /srv/grocy/grocy/vendor/slim/slim/Slim/MiddlewareDispatcher.php(313): Grocy\Middleware\CorsMiddleware->__invoke()
#20 /srv/grocy/grocy/vendor/slim/slim/Slim/MiddlewareDispatcher.php(81): class@anonymous->handle()
#21 /srv/grocy/grocy/vendor/slim/slim/Slim/App.php(215): Slim\MiddlewareDispatcher->handle()
#22 /srv/grocy/grocy/vendor/slim/slim/Slim/App.php(199): Slim\App->handle()
#23 /srv/grocy/grocy/app.php(77): Slim\App->run()
#24 /srv/grocy/grocy/public/index.php(45): require_once('/srv/grocy/groc...')
#25 {main}
```

**Comment by berrnd** [comment]
Migrations are supposed to work between releases, not between every commit - since the beginning of grocy.
Using the master branch is ok if you can and want to handle every possible error yourself (my private grocy instance uses the release branch).

This is not reproducible when starting from scratch on the master branch or when upgrading from v2.7.1.

Most probably it's about a view, but can't see which one from the error message - so you maybe have to check every view manually created/changed since the last release...

**Comment by berrnd** [comment]
>  Doesn't look like a good idea to edit existing migrations! 😅

And that's simply because for example since the nearly 400 commits from v2.7.1 to now (the next version will be released tomorrow), we would maybe have 50 or so more migrations, which is not a problem in general, but more to do and not really necessary.

The master branch is the development version, anything can be broken or can be changed anytime.

**Comment by afv** [comment]
Thanks and congrats for the release! 🎉

Solved! Just checked/executed every statement (one by one) from the migrations since the previous release (0102 to 0125) 😅 but the problem was even before that (the view recipes_resolved from 0095), as I'm using the dev version since January.
