### ISSUE TITLE
Bug: Release 3.0.0 not working

### ISSUE THREAD

**Issue by JuergenLeber** [grocy/grocy#1209]
I just downloaded and installed release 3.0.0 but after modifying config.php and opening the application in /public I get an error "SQLSTATE[HY000]: General error: 1 SELECTs to the left and right of UNION do not have the same number of result columns". So I tried it again by downloading again but no luck. Next try was release 2.7.1 and it worked flawlessly. So I tried an upgrade to release 3.0.0 but same error again. I think there's something wrong with the database structure in the packed  release zip file. 

Error source:
```
/var/www/services/DatabaseService.php:33
```

Error message:
```
SQLSTATE[HY000]: General error: 1 SELECTs to the left and right of UNION do not have the same number of result columns
```

Stack trace:
```
#0 /var/www/services/DatabaseService.php(33): PDO->exec()
#1 /var/www/services/DatabaseMigrationService.php(56): Grocy\Services\DatabaseService->ExecuteDbStatement()
#2 /var/www/services/DatabaseMigrationService.php(30): Grocy\Services\DatabaseMigrationService->ExecuteSqlMigrationWhenNeeded()
#3 /var/www/controllers/SystemController.php(27): Grocy\Services\DatabaseMigrationService->MigrateDatabase()
#4 /var/www/vendor/slim/slim/Slim/Handlers/Strategies/RequestResponse.php(43): Grocy\Controllers\SystemController->Root()
#5 /var/www/vendor/slim/slim/Slim/Routing/Route.php(384): Slim\Handlers\Strategies\RequestResponse->__invoke()
#6 /var/www/vendor/slim/slim/Slim/MiddlewareDispatcher.php(81): Slim\Routing\Route->handle()
#7 /var/www/vendor/slim/slim/Slim/MiddlewareDispatcher.php(81): Slim\MiddlewareDispatcher->handle()
#8 /var/www/vendor/slim/slim/Slim/Routing/Route.php(341): Slim\MiddlewareDispatcher->handle()
#9 /var/www/vendor/slim/slim/Slim/Routing/RouteRunner.php(84): Slim\Routing\Route->run()
#10 /var/www/middleware/LocaleMiddleware.php(16): Slim\Routing\RouteRunner->handle()
#11 /var/www/vendor/slim/slim/Slim/MiddlewareDispatcher.php(313): Grocy\Middleware\LocaleMiddleware->__invoke()
#12 /var/www/middleware/AuthMiddleware.php(31): class@anonymous->handle()
#13 /var/www/vendor/slim/slim/Slim/MiddlewareDispatcher.php(313): Grocy\Middleware\AuthMiddleware->__invoke()
#14 /var/www/vendor/slim/slim/Slim/Middleware/RoutingMiddleware.php(59): class@anonymous->handle()
#15 /var/www/vendor/slim/slim/Slim/MiddlewareDispatcher.php(147): Slim\Middleware\RoutingMiddleware->process()
#16 /var/www/vendor/slim/slim/Slim/Middleware/ErrorMiddleware.php(107): class@anonymous->handle()
#17 /var/www/vendor/slim/slim/Slim/MiddlewareDispatcher.php(147): Slim\Middleware\ErrorMiddleware->process()
#18 /var/www/middleware/CorsMiddleware.php(30): class@anonymous->handle()
#19 /var/www/vendor/slim/slim/Slim/MiddlewareDispatcher.php(313): Grocy\Middleware\CorsMiddleware->__invoke()
#20 /var/www/vendor/slim/slim/Slim/MiddlewareDispatcher.php(81): class@anonymous->handle()
#21 /var/www/vendor/slim/slim/Slim/App.php(215): Slim\MiddlewareDispatcher->handle()
#22 /var/www/vendor/slim/slim/Slim/App.php(199): Slim\App->handle()
#23 /var/www/app.php(77): Slim\App->run()
#24 /var/www/public/index.php(45): require_once('/var/www/vhosts...')
#25 {main}
```

If you need more information please let me know!

**Comment by berrnd** [comment]
Are you sure that used a _released_ version before and _not_ the master branch (anytime inbetween)?

The same was recently reported here: https://www.reddit.com/r/grocy/comments/jogh32/slim_application_error_selects_to_the_left_and/gcjscc4

**Comment by JuergenLeber** [comment]
Yes, downloaded https://github.com/grocy/grocy/releases/download/v3.0.0/grocy_3.0.0.zip. Tried it twice as a fresh install and once as an update from 2.7.1.

**Comment by berrnd** [comment]
Starting from scratch definitely works, the demo instances do that hourly without an issue.

Upgrading at least worked for a couple of users and my private instance, so I doubt there is a general problem - unfortunately your error message doesn't say which migration fails...

Next thing to check: The used SQLite version needs to be >= 3.8.3 (not a new requirement).

Otherwise, as always, I can offer that you can send me your v2.7.1 database file (`data/grocy.db`), if that's ok for you, and I will look into.

**Comment by JuergenLeber** [comment]
That's strange. The 2.7.1 database file is also an empty one, just installed 2.7.1 from scratch so there's no valuable data in it. But the 2.7.1 worked without any problems. Here the queries that are being executed until the problem appears: 

`CREATE TABLE IF NOT EXISTS migrations (migration INTEGER NOT NULL PRIMARY KEY UNIQUE, execution_time_timestamp DATETIME DEFAULT (datetime('now', 'localtime')))
SELECT COUNT(*) FROM migrations WHERE migration = 1
SELECT COUNT(*) FROM migrations WHERE migration = 2
SELECT COUNT(*) FROM migrations WHERE migration = 3
SELECT COUNT(*) FROM migrations WHERE migration = 4
SELECT COUNT(*) FROM migrations WHERE migration = 5
SELECT COUNT(*) FROM migrations WHERE migration = 6
SELECT COUNT(*) FROM migrations WHERE migration = 7
SELECT COUNT(*) FROM migrations WHERE migration = 8
SELECT COUNT(*) FROM migrations WHERE migration = 9
SELECT COUNT(*) FROM migrations WHERE migration = 10
SELECT COUNT(*) FROM migrations WHERE migration = 11
SELECT COUNT(*) FROM migrations WHERE migration = 12
SELECT COUNT(*) FROM migrations WHERE migration = 13
SELECT COUNT(*) FROM migrations WHERE migration = 14
SELECT COUNT(*) FROM migrations WHERE migration = 15
SELECT COUNT(*) FROM migrations WHERE migration = 16
SELECT COUNT(*) FROM migrations WHERE migration = 17
SELECT COUNT(*) FROM migrations WHERE migration = 18
SELECT COUNT(*) FROM migrations WHERE migration = 19
SELECT COUNT(*) FROM migrations WHERE migration = 20
SELECT COUNT(*) FROM migrations WHERE migration = 21
SELECT COUNT(*) FROM migrations WHERE migration = 22
SELECT COUNT(*) FROM migrations WHERE migration = 23
SELECT COUNT(*) FROM migrations WHERE migration = 24
SELECT COUNT(*) FROM migrations WHERE migration = 25
SELECT COUNT(*) FROM migrations WHERE migration = 26
SELECT COUNT(*) FROM migrations WHERE migration = 27
SELECT COUNT(*) FROM migrations WHERE migration = 28
SELECT COUNT(*) FROM migrations WHERE migration = 29
SELECT COUNT(*) FROM migrations WHERE migration = 30
SELECT COUNT(*) FROM migrations WHERE migration = 31
SELECT COUNT(*) FROM migrations WHERE migration = 32
SELECT COUNT(*) FROM migrations WHERE migration = 33
SELECT COUNT(*) FROM migrations WHERE migration = 34
SELECT COUNT(*) FROM migrations WHERE migration = 35
SELECT COUNT(*) FROM migrations WHERE migration = 36
SELECT COUNT(*) FROM migrations WHERE migration = 37
SELECT COUNT(*) FROM migrations WHERE migration = 38
SELECT COUNT(*) FROM migrations WHERE migration = 39
SELECT COUNT(*) FROM migrations WHERE migration = 40
SELECT COUNT(*) FROM migrations WHERE migration = 41
SELECT COUNT(*) FROM migrations WHERE migration = 42
SELECT COUNT(*) FROM migrations WHERE migration = 43
SELECT COUNT(*) FROM migrations WHERE migration = 44
SELECT COUNT(*) FROM migrations WHERE migration = 45
SELECT COUNT(*) FROM migrations WHERE migration = 46
SELECT COUNT(*) FROM migrations WHERE migration = 47
SELECT COUNT(*) FROM migrations WHERE migration = 48
SELECT COUNT(*) FROM migrations WHERE migration = 49
SELECT COUNT(*) FROM migrations WHERE migration = 50
SELECT COUNT(*) FROM migrations WHERE migration = 51
SELECT COUNT(*) FROM migrations WHERE migration = 52
SELECT COUNT(*) FROM migrations WHERE migration = 53
SELECT COUNT(*) FROM migrations WHERE migration = 54
SELECT COUNT(*) FROM migrations WHERE migration = 55
SELECT COUNT(*) FROM migrations WHERE migration = 56
SELECT COUNT(*) FROM migrations WHERE migration = 57
SELECT COUNT(*) FROM migrations WHERE migration = 58
SELECT COUNT(*) FROM migrations WHERE migration = 59
SELECT COUNT(*) FROM migrations WHERE migration = 60
SELECT COUNT(*) FROM migrations WHERE migration = 61
SELECT COUNT(*) FROM migrations WHERE migration = 62
SELECT COUNT(*) FROM migrations WHERE migration = 63
SELECT COUNT(*) FROM migrations WHERE migration = 64
SELECT COUNT(*) FROM migrations WHERE migration = 65
SELECT COUNT(*) FROM migrations WHERE migration = 66
SELECT COUNT(*) FROM migrations WHERE migration = 67
SELECT COUNT(*) FROM migrations WHERE migration = 68
SELECT COUNT(*) FROM migrations WHERE migration = 69
SELECT COUNT(*) FROM migrations WHERE migration = 70
SELECT COUNT(*) FROM migrations WHERE migration = 71
SELECT COUNT(*) FROM migrations WHERE migration = 72
SELECT COUNT(*) FROM migrations WHERE migration = 73
SELECT COUNT(*) FROM migrations WHERE migration = 74
SELECT COUNT(*) FROM migrations WHERE migration = 75
SELECT COUNT(*) FROM migrations WHERE migration = 76
SELECT COUNT(*) FROM migrations WHERE migration = 77
SELECT COUNT(*) FROM migrations WHERE migration = 78
SELECT COUNT(*) FROM migrations WHERE migration = 79
SELECT COUNT(*) FROM migrations WHERE migration = 80
SELECT COUNT(*) FROM migrations WHERE migration = 81
SELECT COUNT(*) FROM migrations WHERE migration = 82
SELECT COUNT(*) FROM migrations WHERE migration = 83
SELECT COUNT(*) FROM migrations WHERE migration = 84
SELECT COUNT(*) FROM migrations WHERE migration = 85
SELECT COUNT(*) FROM migrations WHERE migration = 86
SELECT COUNT(*) FROM migrations WHERE migration = 87
SELECT COUNT(*) FROM migrations WHERE migration = 88
SELECT COUNT(*) FROM migrations WHERE migration = 89
SELECT COUNT(*) FROM migrations WHERE migration = 90
SELECT COUNT(*) FROM migrations WHERE migration = 91
SELECT COUNT(*) FROM migrations WHERE migration = 92
SELECT COUNT(*) FROM migrations WHERE migration = 93
SELECT COUNT(*) FROM migrations WHERE migration = 94
SELECT COUNT(*) FROM migrations WHERE migration = 95
SELECT COUNT(*) FROM migrations WHERE migration = 96
SELECT COUNT(*) FROM migrations WHERE migration = 97
SELECT COUNT(*) FROM migrations WHERE migration = 98
SELECT COUNT(*) FROM migrations WHERE migration = 99
SELECT COUNT(*) FROM migrations WHERE migration = 100
SELECT COUNT(*) FROM migrations WHERE migration = 101
SELECT COUNT(*) FROM migrations WHERE migration = 102
SELECT COUNT(*) FROM migrations WHERE migration = 103
SELECT COUNT(*) FROM migrations WHERE migration = 104
SELECT COUNT(*) FROM migrations WHERE migration = 105
CREATE VIEW uihelper_stock_current_overview_including_opened AS SELECT p.id, sc.amount_opened AS amount_opened, p.tare_weight AS tare_weight, p.enable_tare_weight_handling AS enable_tare_weight_handling, sc.amount AS amount, sc.value as value, sc.product_id AS product_id, sc.best_before_date AS best_before_date, EXISTS(SELECT id FROM stock_missing_products_including_opened WHERE id = sc.product_id) AS product_missing, (SELECT name FROM quantity_units WHERE quantity_units.id = p.qu_id_stock) AS qu_unit_name, (SELECT name_plural FROM quantity_units WHERE quantity_units.id = p.qu_id_stock) AS qu_unit_name_plural, p.name AS product_name, (SELECT name FROM product_groups WHERE product_groups.id = product_group_id) AS product_group_name, EXISTS(SELECT * FROM shopping_list WHERE shopping_list.product_id = sc.product_id) AS on_shopping_list, (SELECT name FROM quantity_units WHERE quantity_units.id = p.qu_id_purchase) AS qu_purchase_unit_name, (SELECT name_plural FROM quantity_units WHERE quantity_units.id = p.qu_id_purchase) AS qu_purchase_unit_name_plural, sc.is_aggregated_amount, sc.amount_opened_aggregated, sc.amount_aggregated, p.calories AS product_calories, sc.amount * p.calories AS calories, sc.amount_aggregated * p.calories AS calories_aggregated, p.quick_consume_amount, p.due_type FROM ( SELECT * FROM stock_current WHERE best_before_date IS NOT NULL UNION SELECT m.id, 0, 0, 0, null, 0, 0, 0, p.due_type FROM stock_missing_products_including_opened m JOIN products p ON m.id = p.id WHERE m.id NOT IN (SELECT product_id FROM stock_current) ) sc LEFT JOIN products p ON sc.product_id = p.id WHERE p.hide_on_stock_overview = 0; CREATE VIEW uihelper_stock_current_overview AS SELECT p.id, sc.amount_opened AS amount_opened, p.tare_weight AS tare_weight, p.enable_tare_weight_handling AS enable_tare_weight_handling, sc.amount AS amount, sc.value as value, sc.product_id AS product_id, sc.best_before_date AS best_before_date, EXISTS(SELECT id FROM stock_missing_products WHERE id = sc.product_id) AS product_missing, (SELECT name FROM quantity_units WHERE quantity_units.id = p.qu_id_stock) AS qu_unit_name, (SELECT name_plural FROM quantity_units WHERE quantity_units.id = p.qu_id_stock) AS qu_unit_name_plural, p.name AS product_name, (SELECT name FROM product_groups WHERE product_groups.id = product_group_id) AS product_group_name, EXISTS(SELECT * FROM shopping_list WHERE shopping_list.product_id = sc.product_id) AS on_shopping_list, (SELECT name FROM quantity_units WHERE quantity_units.id = p.qu_id_purchase) AS qu_purchase_unit_name, (SELECT name_plural FROM quantity_units WHERE quantity_units.id = p.qu_id_purchase) AS qu_purchase_unit_name_plural, sc.is_aggregated_amount, sc.amount_opened_aggregated, sc.amount_aggregated, p.calories AS product_calories, sc.amount * p.calories AS calories, sc.amount_aggregated * p.calories AS calories_aggregated, p.quick_consume_amount, p.due_type FROM ( SELECT * FROM stock_current WHERE best_before_date IS NOT NULL UNION SELECT m.id, 0, 0, 0, null, 0, 0, 0, p.due_type FROM stock_missing_products m JOIN products p ON m.id = p.id WHERE m.id NOT IN (SELECT product_id FROM stock_current) ) sc LEFT JOIN products p ON sc.product_id = p.id WHERE p.hide_on_stock_overview = 0; `

The used SQLite version is 3.8.11 and I'll send you the grocy.db file but as said it's from scratch.

**Comment by berrnd** [comment]
As I assumed above, this problem is about that the database file in question was not one from a released version.

Database migrations only work between releases (since ever and as [mentioned in README](https://github.com/grocy/grocy#database-migrations)).

**Comment by JuergenLeber** [comment]
Sorry to bother you again but I did never use the master branch and I also don't have composer on that machine it's running. I started completely from scratch and the DB file is the one that gets created by the release. The one I sent was created by the 2.7.1 release and also new ones get created by 3.0.0 but that is then not working and throwing the error. I also deleted the file and started again and then it just gets created again.

**Comment by berrnd** [comment]
You sent me a database where migrations have run up to [`0104.sql`](https://github.com/grocy/grocy/blob/master/migrations/0104.sql).

When a migration has been executed, the migration number is inserted into the `migrations` table.

This is the output of `SELECT * FROM migrations ORDER BY migration DESC LIMIT 5` executed against your sent database:

![grafik](https://user-images.githubusercontent.com/2161815/102926420-3d0cd880-4495-11eb-9bdc-7ac8d04dc805.png)

In contrast, v2.7.1 only includes migrations up to `0101.sql`.

The v2.7.1 tag tree proves this: https://github.com/grocy/grocy/tree/v2.7.1/migrations

The v2.7.1 release ZIP proves this: https://releases.grocy.info/v?2.7.1

Running `SELECT * FROM migrations ORDER BY migration DESC LIMIT 5` against a database created by the v2.7.1 release shows this:

![grafik](https://user-images.githubusercontent.com/2161815/102926778-ebb11900-4495-11eb-86eb-5aebe85e4963.png)

I have no explanation how your database got those migrations > 101, but it's not possible that you used a released version to get this.

As written by mail, each created/changed view since migration 102 would need to be checked manually if you want to fix this - running an unreleased version is up to you as [mentioned in README](https://github.com/grocy/grocy#database-migrations).

> I also deleted the file and started again and then it just gets created again.

Have you downloaded the release ZIP from [here](https://releases.grocy.info/v?2.7.1) or [here](https://github.com/grocy/grocy/releases/download/v2.7.1/grocy_2.7.1.zip) (the only "official" sources)? It's simply impossible that the database you sent me was populated by those release as explained above...

**Comment by JuergenLeber** [comment]
The database was from a 2.7.1 which I updated to 3.0.0 - and then the error came again. I'll make a fresh install (without DB) of 3.0.0 now and send you the DB file that gets created by default.

**Comment by berrnd** [comment]
Turns out to be a changed SQLite behavour since [SQLite 3.9.0](https://www.sqlite.org/releaselog/3_9_0.html), means this affects you if running grocy v3.0.0 with SQLite > 3.8.3 < 3.9.0.

Fix/Workaround for now:
Replace the file `migrations/0105.sql` with [that one](https://raw.githubusercontent.com/grocy/grocy/5f09d4def194624003e22c37ed6093cdbf263cbb/migrations/0105.sql).

Will raise the minimum required/tested SQLite version for the next release as this was not the first time this was the cause and I'm really tired caring about those ancient stuff - really can't understand why people use such old runtimes...

**Comment by JuergenLeber** [comment]
Just tried a fresh install with the replaced 0105.sql file but same error appears. Of course I replaced the file before running and before the grocy.db was created. The application is hosted with the Plesk control panel and they bundled SQLite 3.8.11 with their PHP 7.4 package. So there is no chance to easily change the old SQLite there :-(

**Comment by berrnd** [comment]
Sorry, missed the same thing in the second view created in the same migration...

Could you try again with [this file](https://raw.githubusercontent.com/grocy/grocy/97b95803b865d4cf2b06834b8377f8b0765a958a/migrations/0105.sql) (also replaced the link above)?

> they bundled SQLite 3.8.11 with their PHP 7.4 package

Please blame your hoster (hard) for that, bundling a PHP release from late 2019 with a SQLite version from mid 2015 is at the best chance just stupid... 🙄😅

**Comment by JuergenLeber** [comment]
Now it seems there is a typo somewhere in the file:

Error message:
```
SQLSTATE[HY000]: General error: 1 near "CASE": syntax error
```

BTW: It's not the hoster to blame, it's unfortunately Plesk who packages this old version of SQLite. I'll request an updated version!

**Comment by berrnd** [comment]
Can you somehow see if it's probably about another migration script? Because in `0105.sql` no `CASE` is used...

Unfortunately I have no way to quickly setup such an old SQLite version here to reproduce this fully...

**Comment by JuergenLeber** [comment]
Now it stops at 0106.sql:

`CREATE INDEX ix_products_performance1 ON products ( parent_product_id ); CREATE INDEX ix_products_performance2 ON products ( CASE WHEN parent_product_id IS NULL THEN id ELSE parent_product_id END, active ); CREATE INDEX ix_stock_performance1 ON stock ( product_id, open, best_before_date, amount ); DROP VIEW products_resolved; CREATE VIEW products_resolved AS SELECT CASE WHEN p.parent_product_id IS NULL THEN p.id ELSE p.parent_product_id END AS parent_product_id, p.id as sub_product_id FROM products p WHERE p.active = 1; DROP VIEW stock_missing_products_including_opened; CREATE VIEW stock_missing_products_including_opened AS /* This is basically the same view as stock_missing_products, but the column "amount_missing" includes opened amounts */ -- Products WITHOUT sub products where the amount of the sub products SHOULD NOT be cumulated SELECT p.id, MAX(p.name) AS name, p.min_stock_amount - (IFNULL(SUM(s.amount), 0) - IFNULL(SUM(s.amount_opened), 0)) AS amount_missing, CASE WHEN IFNULL(SUM(s.amount), 0) > 0 THEN 1 ELSE 0 END AS is_partly_in_stock FROM products_view p LEFT JOIN stock_current s ON p.id = s.product_id WHERE p.min_stock_amount != 0 AND p.cumulate_min_stock_amount_of_sub_products = 0 AND p.has_sub_products = 0 AND p.parent_product_id IS NULL GROUP BY p.id HAVING IFNULL(SUM(s.amount), 0) - IFNULL(SUM(s.amount_opened), 0) < p.min_stock_amount UNION -- Parent products WITH sub products where the amount of the sub products SHOULD be cumulated SELECT p.id, MAX(p.name) AS name, SUM(sub_p.min_stock_amount) - (IFNULL(SUM(s.amount_aggregated), 0) - IFNULL(SUM(s.amount_opened_aggregated), 0)) AS amount_missing, CASE WHEN IFNULL(SUM(s.amount), 0) > 0 THEN 1 ELSE 0 END AS is_partly_in_stock FROM products_view p JOIN products_resolved pr ON p.id = pr.parent_product_id JOIN products sub_p ON pr.sub_product_id = sub_p.id LEFT JOIN stock_current s ON pr.sub_product_id = s.product_id WHERE sub_p.min_stock_amount != 0 AND p.cumulate_min_stock_amount_of_sub_products = 1 GROUP BY p.id HAVING IFNULL(SUM(s.amount_aggregated), 0) - IFNULL(SUM(s.amount_opened_aggregated), 0) < SUM(sub_p.min_stock_amount) UNION -- Sub products where the amount SHOULD NOT be cumulated into the parent product SELECT sub_p.id, MAX(sub_p.name) AS name, SUM(sub_p.min_stock_amount) - (IFNULL(SUM(s.amount), 0) - IFNULL(SUM(s.amount_opened), 0)) AS amount_missing, CASE WHEN IFNULL(SUM(s.amount), 0) > 0 THEN 1 ELSE 0 END AS is_partly_in_stock FROM products p JOIN products_resolved pr ON p.id = pr.parent_product_id JOIN products sub_p ON pr.sub_product_id = sub_p.id LEFT JOIN stock_current s ON pr.sub_product_id = s.product_id WHERE sub_p.min_stock_amount != 0 AND p.cumulate_min_stock_amount_of_sub_products = 0 GROUP BY sub_p.id HAVING IFNULL(SUM(s.amount), 0) - IFNULL(SUM(s.amount_opened), 0) < sub_p.min_stock_amount; `

**Comment by sleeplessnight2** [comment]
Since this change, it's only now blowing up in my face. Before that it ran perfectly.

Can it be that I am a little confused, or is the current sqliteversion 3 lower than this 3.9?

https://sqlite.org/changes.html

The 3.9.0 is a release from 2015?
But the 3.31 ran through perfectly before - only now by changing the 105.sql it crashes with the above error....
I mean, everywhere is installed by default as latest stable 3.3xx....

So if I'm not wrong, then you tinker here on outdated versions

**Comment by berrnd** [comment]
Sorry, can't see any syntax error in `0106.sql`...

Only way is to narrow it down which command is the cause ... run each `SELECT` of the migration manually to see if it works, maybe remove the `CREATE INDEX` command at the top (those are just nice to have, not necessary)...

**Comment by berrnd** [comment]
Oh @sleeplessnight2... 🙄
Nobody said you should try this workaround (which seems to not really work anyway so far) when you're not affected, and your definitely not affected when you run a pretty up to date SQLite version.

And yes, as everyone can see on the linked page, 3.9.0 is from late 2015, so IMHO to worth to be supported anymore, but of course I'll try my best to help to get it to work also there, if possible...

And the most recent release 3.34.0, which is of course > 3.9.0, unless we don't use different mathematics...

**Comment by sleeplessnight2** [comment]
Well, look at it this way:
That I (as one on the latest version) report, testifies to the fact that the changes fix an old version and crash the current...

Do not know now why this becomes personal

**Comment by berrnd** [comment]
> the changes fix an old version and crash the current...

That's not the case, as always, a good reference are the demo instances, which of course run a pretty up to date SQLite version.

Otherwise, please provide the concrete error message.
I also of course tested this once and it works...

> Do not know now why this becomes personal

Just because it's not the first time with use, spamming threads without added information brings nothing as time wasting noise...

**Comment by sleeplessnight2** [comment]
Hmm, then the search starts for me?! (and with that I am quiet)

Drop View and Add this new view generates this error message:

Error source:
```
/opt/grocy-test/vendor/morris/lessql/src/LessQL/Database.php:108
```

Error message:
```
SQLSTATE[HY000]: General error: 1 SELECTs to the left and right of UNION do not have the same number of result columns (View: /opt/grocy-test/views/stockoverview.blade.php)
```

Stack trace:
```
#0 /opt/grocy-test/vendor/illuminate/view/Engines/PhpEngine.php(45): Illuminate\View\Engines\CompilerEngine->handleViewException()
#1 /opt/grocy-test/vendor/illuminate/view/Engines/CompilerEngine.php(59): Illuminate\View\Engines\PhpEngine->evaluatePath()
#2 /opt/grocy-test/vendor/illuminate/view/View.php(142): Illuminate\View\Engines\CompilerEngine->get()
#3 /opt/grocy-test/vendor/illuminate/view/View.php(125): Illuminate\View\View->getContents()
#4 /opt/grocy-test/vendor/illuminate/view/View.php(90): Illuminate\View\View->renderContents()
#5 /opt/grocy-test/vendor/rubellum/slim-blade-view/src/Blade.php(173): Illuminate\View\View->render()
#6 /opt/grocy-test/vendor/rubellum/slim-blade-view/src/Blade.php(65): Slim\Views\Blade->fetch()
#7 /opt/grocy-test/controllers/BaseController.php(162): Slim\Views\Blade->render()
#8 /opt/grocy-test/controllers/BaseController.php(186): Grocy\Controllers\BaseController->render()
#9 /opt/grocy-test/controllers/StockController.php(96): Grocy\Controllers\BaseController->renderPage()
#10 /opt/grocy-test/vendor/slim/slim/Slim/Handlers/Strategies/RequestResponse.php(43): Grocy\Controllers\StockController->Overview()
#11 /opt/grocy-test/vendor/slim/slim/Slim/Routing/Route.php(384): Slim\Handlers\Strategies\RequestResponse->__invoke()
#12 /opt/grocy-test/vendor/slim/slim/Slim/MiddlewareDispatcher.php(81): Slim\Routing\Route->handle()
#13 /opt/grocy-test/vendor/slim/slim/Slim/MiddlewareDispatcher.php(81): Slim\MiddlewareDispatcher->handle()
#14 /opt/grocy-test/vendor/slim/slim/Slim/Routing/Route.php(341): Slim\MiddlewareDispatcher->handle()
#15 /opt/grocy-test/vendor/slim/slim/Slim/Routing/RouteRunner.php(84): Slim\Routing\Route->run()
#16 /opt/grocy-test/middleware/LocaleMiddleware.php(16): Slim\Routing\RouteRunner->handle()
#17 /opt/grocy-test/vendor/slim/slim/Slim/MiddlewareDispatcher.php(313): Grocy\Middleware\LocaleMiddleware->__invoke()
#18 /opt/grocy-test/middleware/AuthMiddleware.php(76): class@anonymous->handle()
#19 /opt/grocy-test/vendor/slim/slim/Slim/MiddlewareDispatcher.php(313): Grocy\Middleware\AuthMiddleware->__invoke()
#20 /opt/grocy-test/vendor/slim/slim/Slim/Middleware/RoutingMiddleware.php(59): class@anonymous->handle()
#21 /opt/grocy-test/vendor/slim/slim/Slim/MiddlewareDispatcher.php(147): Slim\Middleware\RoutingMiddleware->process()
#22 /opt/grocy-test/vendor/slim/slim/Slim/Middleware/ErrorMiddleware.php(107): class@anonymous->handle()
#23 /opt/grocy-test/vendor/slim/slim/Slim/MiddlewareDispatcher.php(147): Slim\Middleware\ErrorMiddleware->process()
#24 /opt/grocy-test/middleware/CorsMiddleware.php(30): class@anonymous->handle()
#25 /opt/grocy-test/vendor/slim/slim/Slim/MiddlewareDispatcher.php(313): Grocy\Middleware\CorsMiddleware->__invoke()
#26 /opt/grocy-test/vendor/slim/slim/Slim/MiddlewareDispatcher.php(81): class@anonymous->handle()
#27 /opt/grocy-test/vendor/slim/slim/Slim/App.php(215): Slim\MiddlewareDispatcher->handle()
#28 /opt/grocy-test/vendor/slim/slim/Slim/App.php(199): Slim\App->handle()
#29 /opt/grocy-test/app.php(77): Slim\App->run()
#30 /opt/grocy-test/public/index.php(45): require_once('/opt/grocy-test...')
#31 {main}
```

**Comment by berrnd** [comment]
@JuergenLeber I've now used an (very) old version of [SQLite Browser](https://sqlitebrowser.org/) and could reproduce the `Syntax error near CASE` in migration `0106.sql` - it's about the second index which get created in this migration, "index on expressions" is also something new in SQLite 3.9.0...

If you want to try this once again, I've provided an updated `0106.sql` (just without that index, as not really necessary) above: https://github.com/grocy/grocy/issues/1209#issuecomment-749760765

The rest of the migrations also run successfully on SQLite 3.8.10.2 - so hopefully this is the final workaround for this...

**Comment by berrnd** [comment]
@sleeplessnight2

Please move this to another thread, if really reproducible.

> Drop View and Add this new view generates this error message:

If you try to run this on an already to grocy v3.0.0 updated database, then of course this will be the problem.
Migrations run only forward, not backwards, and only between releases.
So make sure you try to apply this on a grocy v2.7.1 database.

**Comment by JuergenLeber** [comment]
Yay - Now it works, thank you!

**Comment by berrnd** [comment]
Great - thanks a lot for testing!

**Comment by afv** [comment]
Hi @berrnd,

The `uihelper_stock_current_overview_including_opened` view (https://github.com/grocy/grocy/blob/master/migrations/0105.sql) has two `UNION`s with 8 columns after the last commits that removed the `p.due_type` from the `SELECT` from `stock_current` view (https://github.com/grocy/grocy/blob/master/migrations/0108.sql), which has 9 columns, giving me the `[SQLITE_ERROR] SQL error or missing database (SELECTs to the left and right of UNION do not have the same number of result columns)`.

Am I missing something or is this a bug?

Thanks!

**Comment by berrnd** [comment]
Yes, you miss something:

Migrations run ordered.
At the point of migration 105, the view `stock_current` has 8 columns, created/changed in [migration 103](https://github.com/grocy/grocy/blob/200964edff92648408f479ffd8fed199e9494e17/migrations/0103.sql#L127-171).

The 9th column on `stock_current` was then added in [migration 108 ](https://github.com/grocy/grocy/blob/200964edff92648408f479ffd8fed199e9494e17/migrations/0108.sql#L2-L51)(as you noticed), the view `uihelper_stock_current_overview` was updated in [migration 122](https://github.com/grocy/grocy/blob/master/migrations/0122.sql) again.

So when updating from any release before to v3.0.0, the state of the views `uihelper_stock_current_overview*` from migration 105 were just temporary, because never used, the "UNION SELECT" part was practically wrong, but you don't notice that either when using a pretty up to date SQLite runtime, cause since [SQLite 3.9.0](https://www.sqlite.org/releaselog/3_9_0.html), view SELECTs are checked only on query time, not on definition time - this issue was about that, you are not affected when running any SQLite version > 3.9.0 as mentioned above.

**Comment by afv** [comment]
Ah, it was updated in migration 122! That's what I was missing. Thanks!
