### ISSUE TITLE
Getting grocy to work on apache2

### ISSUE THREAD

**Issue by jimbolaya** [grocy/grocy#121]
As I haven't seen any documentation on this here, I thought I should add some documentation for folks attempting to do the same thing I am. I'm running apache2 on Debian 8 with quite a few things in other subdirectories. Here's how I set up my grocy instance:

In `/etc/apache2/sites-available/default-ssl.conf`, I set up the directory:

`                Alias /grocy /var/www/grocy/public`

Set up rewrite of various things, .htaccess file wasn't working because I only selectively AllowOverride in apahce2:
```
        <Directory /var/www/grocy/public/>
                RewriteEngine On
                RewriteBase /grocy/
                RewriteCond %{REQUEST_FILENAME} !-d
                RewriteCond %{REQUEST_FILENAME} !-f
                RewriteRule ^ index.php [QSA,L]
        </Directory>
```

Then in config.php, I have `Setting('BASE_URL', '/grocy/');`. I found if I don't do that none of the nice formatting works.

One last thing I did that might help future upgrades and improve backups is I made a directory `/home/grocy`and moved my data directory there. Then I made a link from `/var/www/grocy/data` to `/home/grocy/data`
`ln -s /home/grocy/data /var/www/grocy/data`

**Comment by berrnd** [comment]
Thanks! But I still think grocy is a pretty normal PHP application like most of the other ones out there, so a lot of different ways to setup the details. Also where the data directory lives is up to personal preferences. So will come back to this anytime problems regarding this will come up.

According to the Docker Hub pull statistics, I would say most of the grocy users are "installing" it using Docker at this time.

Also when using the `update.sh` script for updates a backup is done in the `<data>/backup` directory.

**Comment by GitHub0202** [comment]
Is this documentation still working?
I was so happy to found it, but now it didn't work for me.
@jimbolaya 
-----------
I did:
`unzip grocy_2.4.2.zip -d /var/www/grocy`
`cp /var/www/grocy/config-dist.php /var/www/grocy/data/config.php`
. . .

**Comment by GitHub0202** [comment]
Now it worked!
I did:
`sudo chown -R www-data:www-data /var/www/grocy/`
`sudo chmod -R 755 /var/www/grocy`
