### ISSUE TITLE
Bug: Adding product barcodes not possible via browser camera barcode scanning

### ISSUE THREAD

**Issue by fnordson** [grocy/grocy#1210]
I wanted to add a barcode to a new product through the /products menu for the product. 
It would recognize the barcode (it does also in the /purchase menu) but won't display it afterwards in the appropriate field so I could save it. 

-------------

A related feature request to this: 
As it happens a lot, it would be nice if when I scan a product in purchase and want to add it as new, it could copy it automatically to barcodes and just let me enter a new name. 
What it does now is, it copies the barcode to the name field. 
Maybe this could be done by checking if what has been entered is just a number value.

**Comment by berrnd** [comment]
Please provide the steps, error messages (Browser Console and/or webserver logs), screenshot or something similar - otherwise it's impossible to help.

Also please try to reproduce things on the demo instances first. If it works there, it's most probably not a bug, but a problem with your installation where the better place for getting help is then the [subreddit](https://www.reddit.com/r/grocy), as [mentioned in README](https://github.com/grocy/grocy#questions--help--bug-reporting--feature-requests).

**Comment by berrnd** [comment]
Also multiple topics in one request are hard to track, but...

> As it happens a lot, it would be nice if when I scan a product in purchase and want to add it as new, it could copy it automatically to barcodes and just let me enter a new name.
>  What it does now is, it copies the barcode to the name field.

It does this when you pick "Add as new product" (**1** in the screenshot below) in the product picker workflow dialog, use "Add as new product and prefill barcode" (**2** in the screenshot below) and it works like

> it would be nice if when I scan a product in purchase and want to add it as new, it could copy it automatically to barcodes and just let me enter a new name.

![grafik](https://user-images.githubusercontent.com/2161815/102916278-91a75800-4483-11eb-8788-b8e016dd7149.png)

**Comment by fnordson** [comment]
Here is the step by step process (tested on demo instance):

- Manage master data
- Products
- Select & edit Product
- Barcodes - Add
- Scan Barcode

No Barcode appears.

**Comment by berrnd** [comment]
So further guessing you use browser camera barcode scanning...

Is reproducible, will be tracked in this issue.

**Comment by fnordson** [comment]
Yes I use browser barcode scanning but just to clarify again:
it only doesn't work there. 

It does work properly in the /purchase menu.

**Comment by berrnd** [comment]
For those who want to have this now:

- Replace the file `views/productbarcodeform.blade.php` with [that one](https://raw.githubusercontent.com/grocy/grocy/937bd6b702717e275cb71e0a20ce82a558ca5794/views/productbarcodeform.blade.php)
- Replace the file `public/viewjs/productbarcodeform.js` with [that one](https://raw.githubusercontent.com/grocy/grocy/937bd6b702717e275cb71e0a20ce82a558ca5794/public/viewjs/productbarcodeform.js)
