### ISSUE TITLE
UI-Bug: Broken success-message when FEATURE_FLAG_STOCK_PRICE_TRACKING on purchase

### ISSUE THREAD

**Issue by berrnd** [grocy/grocy#1214]
On purchase the amount on the success-message is `undefined` when `FEATURE_FLAG_STOCK_PRICE_TRACKING` is disabled.

**Comment by sleeplessnight2** [comment]
Seems that have spawn another Bug?

What's happening now:
![2020-12-23_15-34-46](https://user-images.githubusercontent.com/8561601/103008070-d2ab7500-4534-11eb-9b5f-f19009bab664.jpg)

**Comment by berrnd** [comment]
Thanks. Is also fixed.
