### ISSUE TITLE
Bug: Indirect quantity unit conversion do not work as expected

### ISSUE THREAD

**Issue by berrnd** [grocy/grocy#1217]
_Originally reported in https://www.reddit.com/r/grocy/comments/kj37t0_

> For example a bottle of olive oil - converts to 750 ml - ml converts to teaspoons. Which could be useful in recipe usage.

**Comment by Michael-Linz** [comment]
Unfortunately, still doesn't work yet.

This is how the error accures:
1. I create a product "red wine", unit: bottles, conversion override: 1 bottle = 0.75 l
2. 1 l = 1,000 ml in the general conversion table
3. I create a recipe with an ingredient of 125 ml "red wine"
4. Endet up for 125 ml converted to 166,667 bottles of "red wine"

So I guess this should still be fixed.

**Comment by berrnd** [comment]
Moved to #1264.

This was about to indirect units were not selectable, not about that the used factor is wrong.
