### ISSUE TITLE
Bug: Barcodes cannot be added anymore in the "Create Product" page

### ISSUE THREAD

**Issue by Forceu** [grocy/grocy#1221]
Since Grocy 3.0 barcodes cannot be added anymore when creating a product in the "Create Product" page.

This would be expected behaviour when

- Clicking on "Add as new product and prefill barcode" in Purchase / Consume menu
- Opening `/product/new` with the GET parameter `prefillbarcode`

**Comment by berrnd** [comment]
I guess you call this externally, I don't see a problem when using this ("normally") through the UI.

Yes, there is no GET parameter `perfillbybarcode` anymore for the product edit page.

The product picker workflow `Add as new product and prefill barcode` is now basically done by just passing through the barcode to the product edit page, then jumping back to the purchase/consume page and doing the same as the new product would have been scanned by the (new, at that point still unknown) barcode + the workflow `Add as barcode to existing product` gets started.

I don't consider any frontend features as being part of the API.

**Comment by Forceu** [comment]
Ah I see, I just created the product and saw that the barcode was not added once it was created, but I did not actually click on "Purchase" after the creation.
Thank you for the clarification.
