### ISSUE TITLE
Bug: no Quantity unit in shoppinglist item

### ISSUE THREAD

**Issue by liffez** [grocy/grocy#1222]
When "creating  shoppinglist item" from the stockoverview the "shoppinglistitem" window popup but there is no "Quantity unit" available. 
The item will be added to the shopping list, but the amount you enter in the "creating  shoppinglist item" will not be the same that is stated  in the shoppinglist

**Comment by berrnd** [comment]
Seems to be just some loading/initialization problems - when you re-select the product the unit dropdown will be loaded...

**Comment by liffez** [comment]
that is right :-)
The arrows in the amount picker does not work though, but you can enter the amount and it will get parsed to the shopping list. 
I dont know if ther should be a confirmation when it is done.

**Comment by liffez** [comment]
Thanks, implementer and it works great.
