### ISSUE TITLE
Bug: Updated to 3.0.0 but some pages are inaccessible

### ISSUE THREAD

**Issue by BeaglySmeagly** [grocy/grocy#1224]
Using Grocy in docker on Unraid.

Recipes and Mealplan dont work anymore. Can't see anything in the log.

502 Bad Gateway from the outside and The connection has timed out from the inside.

Checked the ISO 4217 code of the currency, looks good.

Anybody any idea what I can do to troubleshoot?

**Comment by berrnd** [comment]
This is not the right place for help requests, please use the [subreddit](https://www.reddit.com/r/grocy/) as [mentioned in README](https://github.com/grocy/grocy#questions--help--bug-reporting--feature-requests) (which you probably [already did](https://www.reddit.com/r/grocy/comments/kk1pht), so double posting brings nothing than noise...).

Or if you think this is a bug maybe the issue tracker of the Docker Image you are using (which one would be probably a helpful information) - I personally have unfortunately absolutely no expierence with Docker.

**Comment by jayaddison** [comment]
Just adding a note that I've discovered this after looking for related issues from https://github.com/grocy/grocy-docker/issues/118.  I'll try to do a bit more investigation soon to understand what causes these HTTP 502 results to occur.

**Comment by BeaglySmeagly** [comment]
Glad you found something! I’ve already migrated my stuff to another recipe/household application. Hope you can fix it for others

Kind regards
