### ISSUE TITLE
UI-Bug: Images in equipment descriptions

### ISSUE THREAD

**Issue by Gerw88** [grocy/grocy#1228]
In v3.0.
Images added to equipment notes are not saved.
Just tried this on the demo ( https://demo-prerelease.grocy.info ) and seems to be the same.

**Comment by berrnd** [comment]
Unrelated to to equipment notes, seems to be the same for any editor instance. Most probably related to the new filtering stuff due to #996.

**Comment by Gerw88** [comment]
Yes - Editor seems to break other html tags too (just checked with an unordered list in existing product notes).
Adding html using the api is still good.
