### ISSUE TITLE
UI-Bug: Amount-Picker: Keyboard UpArrow and DownArrow change 0.001 fractions

### ISSUE THREAD

**Issue by gersilex** [grocy/grocy#1232]
https://en.demo.grocy.info/consume

When using the keyboards arrow up and down keys to increase or decrease the *Amount*, the changes are in 0.001 steps, instead of full numbers.

Expected: Using the keyboard's UpArrow and DownArrow keys yield the same result as the clickable/touchable up/down buttons

**Comment by gersilex** [comment]
Now **every** input with this feature changes when using the keys.

Expected: Only the input with focus changes.

**Comment by berrnd** [comment]
Of course, thanks for all your testing! :)
