### ISSUE TITLE
Bug: image orientation from photos taken on iOS devices may be incorrect

### ISSUE THREAD

**Issue by jeauxlb** [grocy/grocy#1238]
> Please describe the bug as detailed as possible, provide the steps how to reproduce it and maybe attach screenshots where useful.

When I upload images that were captured on a device running iOS, the orientation may be rotated 90º or 180º when these images are displayed on Grocy. This is likely due to well-known problems with the non-standard way iOS devices can sometimes encode metadata around picture orientation.

I have ascertained that the original uploads are shown correctly, and only the 'downscaled' images are rotated for me. The relevant code is in services/FilesService.php, and in particular makes reference to `\Gumlet\ImageResize` which seems to do the heavy lifting for resizing. Something like [this](https://stackoverflow.com/questions/14649645/resize-image-in-php) is likely to be a solution/work-around, short of raising a bug with Gumlet if that is indeed where the problem is.

**Comment by jeauxlb** [comment]
Solution found: I am running the docker container from https://github.com/grocy/grocy-docker, and it is missing the PHP dependency for EXIF data. I will add a pull request for this later, but for now, the missing line is in Dockerfile-grocy, and should show:
```# Install system dependencies
RUN     apk add --no-cache \
            php7-ctype \
            php7-fpm \
            php7-fileinfo \
            php7-iconv \
            php7-json \
            php7-gd \
            php7-pdo_sqlite \
            php7-simplexml \
            php7-tokenizer \
            php7-exif
```

(Additionally with the new LDAP support in v3.0.0, I have found this file is also missing `php7-ldap`)

**Comment by berrnd** [comment]
Great, thanks - and yes, please report that or open a pull request at [grocy/grocy-docker](https://github.com/grocy/grocy-docker).
