### ISSUE TITLE
Allow inline setting of stock place

### ISSUE THREAD

**Issue by Braintelligence** [grocy/grocy#124]
When entering new stock I want to be able to determine the stock location inline.

Example use-case: You have one fridge in the kitchen and one deep freezer in the cellar. Sometimes I would put the same product in the fridge freezing department and other times I would put it in the deep freezer in the cellar.

EDIT: Obviously it seems that for this we would need something else that is drastically needed (IMHO): product variants ...

**Comment by berrnd** [comment]
Sorry, was not notified about your EDIT - please open a new issue for this if appropriate.
