### ISSUE TITLE
Bug: recipe consumption of products with mixed quantity units in parent/child relationship results in failed consumption

### ISSUE THREAD

**Issue by jeauxlb** [grocy/grocy#1240]
> Please describe the bug as detailed as possible, provide the steps how to reproduce it and maybe attach screenshots where useful.

Hi,

I am using Grocy in the following way:
1. Entering specific products e.g. "Beef Mince Lean 500g", and I add these with the unit 'packs'. These products are given conversions from packs to grams/kilograms.
2. Having a parent product for "Beef mince", that sums up how much of all beef mince I have, for recipes where the kind of mince is neither here nor there (e.g. lean/regular). This product only knows about grams/kilograms (not "packs", as this would not make sense).
3. Having recipes that call upon this parent product and specify the amount in grams of beef mince to be used.

The Stock Overview page shows the correct totals for me, for all mince products. In addition, the recipe front page shows that correct stock levels with reference to the recipe requirements. However, when I go to consume all items on a recipe, I receive an error: "Not all ingredients of recipe "Mince night" are in stock, nothing removed".

Demo available: https://test-h82i9vi0vbatu91onfkbm8.demo.grocy.info/recipes?recipe=7  and press "consume all ingredients needed by this recipe" on the "Mince night" recipe. This has only one ingredient, set up in the manner described above.

**Additionally** I have discovered some related/consequential bugs:
1. Although the stock levels shown on the recipe page are correct, calorie information is not passed through from child products. The recipe will always show "0.0 calories"
2. Even though the warning message says "nothing removed", in checking my stock levels and reading the journal, sometimes the stock levels of some products — usually just one or two products from the recipe — are removed and the user must manually roll back to make sure all levels are correct. It was not readily apparently to me which ingredients were chosen and why this was only a bug that occurred sometimes.

**Comment by berrnd** [comment]
Thanks for finding that.

> 2. Even though the warning message says "nothing removed", in checking my stock levels and reading the journal, sometimes the stock levels of some products — usually just one or two products from the recipe — are removed and the user must manually roll back to make sure all levels are correct.

Before consuming, the stock level is checked for the given amount and the API does nothing if that amount is > the current in-stock amount. But this check happens per product, not for the whole recipe (recipe consumption is just a "normal consume" per recipe ingredient). The base problem seems to be this "in-stock check" for parent product here. Recipe consumption is only possible if the recipe fulfillment check says "Everything is in stock" and then this should never be a real problem...

**Comment by jeauxlb** [comment]
That makes sense. However I think to better structure the process, and in case something does go wrong, the recipe ingredients should be removed from stock within a transaction that can be rolled back, as the action of removing all ingredients from stock here is (or should be considered) an atomic action.

**Comment by berrnd** [comment]
Recipe consumption for that example works now.

> Although the stock levels shown on the recipe page are correct, calorie information is not passed through from child products. The recipe will always show "0.0 calories"

I've moved this into #1241 and consider that more an enhancement.
Child/Parent products are currently about "exchanging amounts", aggregating everything else of course would also make sense - but it's potentially not only about calories, more all/most other fields too...

**Comment by notEvil** [comment]
Hi,

I think @jeauxlb s last point is still valid. When you consume a recipe, it should either succeed and the corresponding ingredients are consumed or it should fail and nothing is consumed.

The loop around

https://github.com/grocy/grocy/blob/84476ad093cb9120ec6f26f24e2dce31cc70bda6/services/RecipesService.php#L84

isn't within a transaction so every `ConsumeProduct` will commit immediately and if any call in later iterations fails, part of the recipes ingredients stay consumed. This creates inconsistencies that are easily avoided with a transaction.

Amazing project btw!

**Comment by berrnd** [comment]
>  When you consume a recipe, it should either succeed and the corresponding ingredients are consumed or it should fail and nothing is consumed.

Wasn't the topic here, multi-topic issues are untrackable - feel free to open another feature request with a reproducible example if that's important for you / want to have it tracked.

> This creates inconsistencies that are easily avoided with a transaction.

At the mentioned code reference transactions are technically not so "easy" possible. But feel free to just add it if you believe it's just that there.
