### ISSUE TITLE
Bug: saturday and sunday cannot be selected when adding a weekly chore

### ISSUE THREAD

**Issue by tkunzfeld** [grocy/grocy#1242]
When adding or editing a chore and selecting the period type "weekly", the checkboxes for Saturday and Sunday both toggle the box for friday only, the boxes for Saturday and Sunday stay deselected. 

Steps to reproduce:
- Click on "Manage master data" -> "Chores"
- Click "Add"
- Select "Period type" = "weekly"
- Try to check the checkboxes for Saturday and Sunday that appear below

Tested version: 3.0.0

I suspect at least part of the issue in the file grocy/views/choreform.blade.php in lines 142 and 150 (Commit 2e3c237):

`<label class="form-check-label custom-control-label"
						for="friday">{{ $__t('Saturday') }}</label>`
`<label class="form-check-label custom-control-label"
						for="friday">{{ $__t('Sunday') }}</label>`

Should these be `for="saturday"` and `for="sunday"` respectively?

**Comment by berrnd** [comment]
> Should these be `for="saturday"` and `for="sunday"` respectively?

Of course, thanks.
