### ISSUE TITLE
Feature request: Using Responsive Datatables for a alternativ mobile view

### ISSUE THREAD

**Issue by sleeplessnight2** [grocy/grocy#1243]
As a "small" design suggestion: I have noticed that in the mobile view you can find your way around much better if you see everything at once, instead of imagining the tables completely in your head.

Of course, this is all a preference - some like the view as it is so far (table is moved and you always have to imagine the whole table...).

But what I find a pity is that the product name is cut off and all the buttons in the first column look slightly "messy" because of the different quantities.

![01-01-_2021_17-39-24](https://user-images.githubusercontent.com/8561601/103442989-0e43ee80-4c5b-11eb-9fa9-453980ad441b.jpg)

Fortunately you already use datatables.net - and they offer a very nice plugin Names Responsive. [https://datatables.net/extensions/responsive/examples/](https://datatables.net/extensions/responsive/examples/)

I've included this just to illustrate how it would look in mobile view only:

![01-01-_2021_17-47-27](https://user-images.githubusercontent.com/8561601/103442996-1c920a80-4c5b-11eb-83d5-d9081ffaa125.jpg)

I have the feeling that it is a bit clearer on the touchscreens.

Would that be something? Perhaps a few more say something about it - design is rather something individual.

If it is not implemented for this project: May I get a little help to convert the whole thing so for me?
You would have to rebuild the table design a bit, because the Responsive Plugin always takes the first column as "reference" and rebuilds the rest of the table.
It's your decision of course - I understand if you refuse.

**Comment by berrnd** [comment]
We had exactly that with exactly that DataTables plugin before, related issues (including old screenshots): #522, #205, #1115

A lot complained about that collapsing columns is bad, horizontally scrollable tables are better.
I personally don't really care, but at the end I also find the scrollable variant better.

> design is rather something individual.

That's true, so this will stay as it is for now.

> Would that be something? Perhaps a few more say something about it - design is rather something individual.

Just look at the old code or what has been changed in #1115.
