### ISSUE TITLE
Bug: Ampersand (&) in name field is converted to HTML entity

### ISSUE THREAD

**Issue by josephbadow** [grocy/grocy#1247]
Creating a Product group with the ampersand character "`&`" in the name converts it to "`&amp;`". If you [create a new product group](https://github.com/grocy/grocy/pull/793), for example `Fleisch- & Wurstwaren`, it will display as `Fleisch- &amp; Wurstwaren`.

I am running grocy 3.0.0 in Docker and was able to reproduce this in the stable demo instance. Oh, and I just checked and found this to be a problem with Products and Locations as well. Could there be a relation to https://github.com/grocy/grocy/pull/793?

**Comment by berrnd** [comment]
> Could there be a relation to #793?

No, it's more because of the filtering stuff due to #996.

**Comment by josephbadow** [comment]
I am amazed how fast you resolved this regardless of the complexity. Thank you!

**Comment by berrnd** [comment]
Thanks - though replacing `&amp;` with `&` again after filtering is maybe not the best approach for "solving" this, but works - for grocy I don't care too much about "code elgance", more about the outcome, so this could be done better (and most probably affects more special characters, but mabye not all are really need/common for names and other fields)...

🥳🙃
