### ISSUE TITLE
Optional ingredients for recipes

### ISSUE THREAD

**Issue by Braintelligence** [grocy/grocy#125]
Use-case: Soup with optional toppings. A group whose ingredients are optional, preferrably with a checkmark that can be ticked before adding everything to the grocery list, so you don't have to create recipes for each and every variant.

**Comment by berrnd** [comment]
So it's only about what to put on the shopping list? There is already the checkbox "Disable stock fulfillment checking for this ingredient" per recipe ingredient to not check stock for the specified ingredient.

So maybe just list all ingredients again in the popup which asks if you are really sure to put everything on the shopping list with a checkbox left to it, defaults to all checked...

**Comment by Braintelligence** [comment]
The latter sounds reasonable

**Comment by berrnd** [comment]
This is now done. :)

In the "confirm to put everything on the shopping list"-popup there are now all missing products listed, all checked by default, when unchecked the product is not put on the shopping list.

If you want, you can play around with it in the already updated [pre-release demo](https://demo-prerelease.grocy.info/recipes). Let me know if this is not what you thought of.
