### ISSUE TITLE
Bug: Quantity in included recipes are not correct

### ISSUE THREAD

**Issue by erobert-c** [grocy/grocy#1252]
Hello,

Sorry if I missed something, but it seems there is a bug in the quantity for included recipes.
Version used: 3.0.0 (running in docker; linuxserver)
How to reproduce:

1. Create a recipe named sub-recipe
2. Specify that the ingredients listed are for 2 servings
3. Add some ingredients (e.g. 10cl of water) and save
4. Create a new recipe named parent
5. Add an "included recipe", referencing the sub-recipe, and indicates that it is for 4 servings
6. Save and go back to the recipes list

**Expected result**
When viewing the ingredients list in the "Sub-recipe" section of the "Parent" recipe, the quantity for the ingredient should be the double of what was specified in the "sub-recipe", in our example 20cl of water. Also when updating the desired servings for the "Parent", the ingredient of the Sub recipe included should be updated accordingly.

**Actual result**
The quantity corresponds to the quantity needed for the sub-recipe for 1 portion, in our example 5cl  of water. This actually matches to the "Desired servings" of the recipes list, instead of the one configured in the "Included recipe" section.

Don't hesitate if it's not clear enough, I can try to add more details.
Cheers

**Comment by berrnd** [comment]
I've created a demo of what you described, because then it's much easier to understand it...

=> https://test-pba868lxoapuphus7ig1.demo-prerelease.grocy.info/recipes?recipe=8

**Comment by erobert-c** [comment]
That was quick, thanks a lot :smile:

**Comment by erobert-c** [comment]
Hi @berrnd and thanks again for the quick release! 

I don't know if I need to open a new ticket or if we can reuse this one, but issue is still not fixed I believe.

I created two new recipes in this test instance: https://test-pba868lxoapuphus7ig1.demo-prerelease.grocy.info/recipes?recipe=9:

- Dough, with the ingredients to make 8 servings
- Stuff bread with eggs, which include the dough recipe. The ingredients are also for 8 servings, so I need 8 servings of dough.
- In the recipe list, I select the Stuff bread with eggs recipes, and want to prepare 4 servings
   => quantity for the included dough are still not correct (it shows 76.8g of flour while it should be 150, same for water)

Don't hesitate to tell me if you prefer to have a new ticket instead of recycling this one.
Cheers

**Comment by berrnd** [comment]
Sorry, the difference to the first example seems to be the "included recipe service amount" (8 here instead of 1 in the first example) - so probably that's still missing to be also considered, will have a look again (and we can track that here).

**Comment by berrnd** [comment]
Another example originally reported by @B1ue-W01f in #1439
https://test-h8311tny5enov5s4irujg8.demo-prerelease.grocy.info/recipes?recipe=7

Changing the parents recipe servings doesn't have an effect for the ingredient amounts of the included recipe (Pizza) - seem that it always takes the serving of the included recipe itself into account...

**Comment by berrnd** [comment]
Another example originally reported by @13hannes11 in #1489:

>     1. Create a recipe for 4 people
>     2. Select as subrecipe another recipe with 4 people.
>     3. The quantities are way too high.
> 
> 
> https://test-1pqe9lg5bfraye4cmd1js6.demo-prerelease.grocy.info/recipes?recipe=10
> 
> ![image](https://user-images.githubusercontent.com/9381167/119394714-cd647900-bcd2-11eb-9990-dab84123b00c.png)
