### ISSUE TITLE
Bug: purchase with "scan mode"on, the stored amounts per barcode are not used

### ISSUE THREAD

**Issue by rainman19121979** [grocy/grocy#1253]
When purchase with "scan mode"on, the stored amounts per barcode are not used.
With "scan mode" off the correct amount is used.
See example Spülmaschinentabs
https://test-ysz48e21sk99007n8w4g3n.demo.grocy.info/purchase?

Sorry for bad English

Holger

**Comment by sleeplessnight2** [comment]
I was just about to write something similar.

But I expand this:
The quantity stored in the barcode is not used at all when consuming.
Here simply the two values are taken (Quick-Consume or default value from the user settings).

My suggestion: Per barcode another "Quick-Consume-Amount" possibility - then you don't need to change too much in the code.

**Comment by berrnd** [comment]
@sleeplessnight2 IMHO also in 2021 it's good to keep it to one topic per request, this is a ui-bug, what you mentioned is an enhancement (barcode amounts and so on were clearly added for purchase, ref changelog) - I've moved this into #1254.
