### ISSUE TITLE
Bug: API keys passed in the clear 🔐

### ISSUE THREAD

**Issue by aihngel** [grocy/grocy#1257]
API keys are passed in the clear so anyone who sniffs it can view your database.  They're literally appended into the URLs.

**Comment by berrnd** [comment]
> They're literally appended into the URLs.

Where?

As [`/api`](https://demo-prerelease.grocy.info/api) mentions, API keys should be passed via a HTTP header named `GROCY-API-KEY`. By user requests, this was extended at some point to also allow a same named query parameter, which of course could get into server logs or similar. I would never do that, but for some use cases it's maybe impossible to send custom headers.

> API keys are passed in the clear so anyone who sniffs

If you use a proper TLS secured connection, would be interesting who you achieve that.
Would then also apply for your username+password combination.

Passing API keys via HTTP headers is common practice.

If you know how to do this better, let me know.
(Just saying something is bad while not providing why is, sorry to be direct, ugly.)

**Comment by aihngel** [comment]
I can go to a computer that's not logged in.

Https://grocy.myurl.com/stockoverviewAPI:blah and here's an XML of all my
data.  So you're saying I shouldn't be able to do that right?

**Comment by berrnd** [comment]
Of course not.

`/stockoverviewAPI:blah` is not a valid route.
grocy serves nowhere XML data (the API is JSON based, the base route is `/api`), nor are API keys accepted in that way (assuming `blah` should be an API key).

I can't say what you're doing, please provide examples, log and configuration files if this is reproducible and you need help.

Authentication is disabled on the demo instances, but https://demo.grocy.info/stockoverviewAPI:blah clearly serves a 404 error as it's supposed to do for non existent frontend routes.

**Comment by aihngel** [comment]
Sorry I was mobile and had to make some of the URL up.  Here we go. 

This test was done logged out in incognito mode (nothing cached)

https://my.url.com/api/stock/volatile?GROCY-API-KEY=RlHnuHnmiOqkq8ojrwXJau0k3OsHWUSZfH2DfGkKhRZKZ8z6Ha&expiring_days=5

And I get back this:

{"expiring_products":[],"expired_products":[],"missing_products":[]}

If there are categories in those sections they show up of course.

**Comment by highaltidude** [comment]
your api key is the credential. that is how api keys work. Transmission from your computer to grocy would be encrypted, just like your username/password

**Comment by aihngel** [comment]
That's exactly my point though.  No disrespect btw, I'm just concerned.

I'm using HTTPS and yet my API (which in this case IS my credential) is sent clear text in the URL.  I get that the API is sent in the URL by design, but if anyone can see it then why am I using it at all.  It seems to defeat security at that point.

For now I've just deleted my API keys because I don't feel like my grocy DB is anyone elses business.

**Comment by aihngel** [comment]
Ok update: I checked it with Wireshark.  Everything is wrapped in TLS...  For some reason my nginx server wasn't reflecting any of that.  Clearly an ID10T issue. 

Thanks for being patient!

**Comment by berrnd** [comment]
> I get that the API is sent in the URL 

The normal way is to use the `GROCY-API-KEY` header, it's not really different, but "more hidden" and doesn't get into webserver logs, that's why commonly API keys are sent in headers, the query parameter way is just an alternative where this is not possible, as mentioned above.

You must have the same conerns for any other API you're using.
And still: If you know how to do this better, let me (and the whole world), know.

**Comment by aihngel** [comment]
That's fine, but for some reason my logs weren't reflecting the correct use of TLS in NGINX.  Which is of course my issue not yours.  Wireshark showed none of that, so it is definitely being wrapped in TLS. (like you said and of like it should be)

> You must have the same concerns for any other API you're using.

Of course, everyone should!  Thanks for explaining.  I need to reformat the information in my logs now.
