### ISSUE TITLE
Cannot upload equipment manual

### ISSUE THREAD

**Issue by daviewales** [grocy/grocy#1258]
## Update

I solved this while creating the GitHub issue.
I'm posting and closing for future reference, in case it's helpful to others.

---

## Original Issue

I'm having trouble uploading equipment instruction manuals in Grocy 2.7.1.
I get the following error:

![Error while saving, probably this item already exists.](https://user-images.githubusercontent.com/2499066/103614249-41002680-4f7c-11eb-8f74-3d858a484feb.png)

```
Error while saving, probably this item already exists.
```

When I click to view details, I see:

![Error details
"\r\n\r\n\r\n
413 Request Entity Too Large
\r\n
nginx/1.14.2
\r\n\r\n\r\n"](https://user-images.githubusercontent.com/2499066/103614573-02b73700-4f7d-11eb-9e4e-1873d55fd0ad.png)

```
Error details
"\r\n\r\n\r\n
413 Request Entity Too Large
\r\n
nginx/1.14.2
\r\n\r\n\r\n"
```

This happens for every PDF I've tried to upload. The filesize of the most recent one is 1.7 MB, so it doesn't make sense to me that the filesize is too large.

I've tested on the Grocy 3.0.0 demo, and it works there.
I'm not sure if this is a bug in 2.7.1, or if I just don't have my permissions set up correctly.

## Installation details

**OS**: Debian 10 (buster)

Process details:
```
$ ps aux | grep "nginx\|php" | grep -v grep
root       342  0.0  2.0 200244  4748 ?        Ss   Jan04   0:17 php-fpm: master process (/etc/php/7.3/fpm/php-fpm.conf)
root       367  0.0  0.5  50364  1180 ?        Ss   Jan04   0:00 nginx: master process /usr/sbin/nginx -g daemon on; master_process on;
www-data   368  0.0  1.9  50992  4596 ?        S    Jan04   0:14 nginx: worker process
www-data 26240  0.4  6.1 201032 14220 ?        S    13:00   1:13 php-fpm: pool www
www-data 27013  0.4  6.2 201096 14376 ?        S    13:37   1:02 php-fpm: pool www
www-data 32525  0.5  6.3 200952 14760 ?        S    17:38   0:03 php-fpm: pool www
```

Directory permissions:
```
/var/www/grocy/data $ ls -l
total 464
-rw-r--r-- 1 www-data www-data   7838 Dec 13 15:55 config.php
-rw-r--r-- 1 www-data www-data 450560 Jan  5 17:38 grocy.db
drwxr-xr-x 2 www-data www-data   4096 Apr  4  2020 plugins
drwxr-xr-x 3 www-data www-data   4096 Dec 29 16:18 storage
drwxr-xr-x 2 www-data www-data   4096 Dec 29 16:00 viewcache
```

```
/var/www/grocy/data/storage $ ls -l
total 4
drwxr-xr-x 2 www-data www-data 4096 Dec 29 16:18 equipmentmanuals
```

**Comment by daviewales** [comment]
## Solution

The default upload size in Nginx is 1 MB.
To increase the upload size to 10 MB, add the following lines to the http section of `/etc/nginx/nginx.conf`:

``` nginx
# Maximum upload size
client_max_body_size 10M;
```

**Comment by creuzerm** [comment]
I ran into this today myself.  I have a 16GB max size, but a manual which is just larger than that.

"Maximum request body size 16777216 exceeded, actual body size 16782042"


I am struggling finding where to make the change. I am running Grocy inside Home Assistant running as a Proxmox Virtual Machine.   I expect I need to make the change inside a docker container that I don't know how to get to, but then the next time I get a Grocy update from Home Assistant, my change will be overwritten.
