### ISSUE TITLE
Create User API Not passing in function

### ISSUE THREAD

**Issue by gen2fish** [grocy/grocy#126]
Problem

When using Create User API, error received, does not appear to parse body.

Version

Version 1.22.0

Environment

Docker on Ubuntu 18.10 Host

Command;
```
curl -X POST "https://grocy.fish.local/api/users/create" -H "GROCY-API-KEY: SecretKey" -H "accept: application/json" -H "Content-Type: application/json" -d "{"id":5,"username":"string12","first_name":"string12","last_name":"string12","password":"string2","row_created_timestamp":"2018-12-30T21:30:39.906Z"}"
```

Error:
```
\/www\/controllers\/UsersApiController.php(35): Grocy\\Services\\UsersService->CreateUser(NULL, NULL, NULL, NULL)"
```

If I change the function to;
```
public function CreateUser(\Slim\Http\Request $request, \Slim\Http\Response $response, array $args)
        {
                $requestBody = $request->getParsedBody();

                try
                {
                        $this->UsersService->CreateUser('username','first','last','pass');
                        return $this->ApiResponse(array('success' => true));
                }
                catch (\Exception $ex)
                {
                        return $this->VoidApiActionResponse($response, false, 400, $ex->getMessage());
                }
        }
```

It creates the user matching the test variables, however I couldn't get it to work trying to parse $request. I tried to match from the ChoreTrackExecution with

`$request->getQueryParams()['username']`

But it seems the `$request` variable isn't populating correctly.

**Comment by gen2fish** [comment]
Upgraded to 1.24 with the same issue

**Comment by berrnd** [comment]
Tried that and found no problem in the request parsing part...

Was the `curl` request above done on Windows?
Then you have to escape the quotes inside the "JSON string", example with the same data as above:
~~~
curl -X POST "https://grocy.fish.local/api/users/create" -H "GROCY-API-KEY: SecretKey" -H "accept: application/json" -H "Content-Type: application/json" -d "{\"id\":5,\"username\":\"string12\",\"first_name\":\"string12\",\"last_name\":\"string12\",\"password\":\"string2\",\"row_created_timestamp\":\"2018-12-30T21:30:39.906Z\"}"
~~~

When you explore the API in the integrated Swagger UI on [/api](https://demo-en.grocy.info/api), it generates also an example `curl` call with requesting if you're on Windows or not...

(Also `id` and `row_created_timestamp` is not required and will also be ignored.)

**Comment by gen2fish** [comment]
Request was not done on Windows.  If I copy the Swagger UI in /api I get the same issue.

**Comment by gen2fish** [comment]
Executing from curl or via powershell wrapper I get the same issue;

```pwsh
$params = @{
    body =  @{
      "username" = $UserName
      "first_name" = $FirstName
      "last_name" = $LastName
      "password" = $Passwd
    }
      uri = "$URI/api/users/create"
      headers = @{
      "accept" = "application/json"
      "Content-Type" = "application/json"
      "GROCY-API-KEY" = $global:grocyGlobal.APIKEY
      }
      method = "Post"
    }

    $params.body
    $result = Invoke-WebRequest @params -SkipCertificateCheck
```

My function parses my body correctly
```
👉😎👉:cforkner> New-GrocyUser -UserName test -FirstName test -LastName test -Passwd test

Name                           Value
----                           -----
username                       test
last_name                      test
first_name                     test
password                       test
```

The Error persists
```
Invoke-WebRequest : {
    "message": "Slim Application Error",
    "error": [
        {
            "type": "TypeError",
            "code": 0,
            "message": "Argument 1 passed to Grocy\\Services\\UsersService::CreateUser() must be of the type string, null given, called in \/www\/controllers\/UsersApiController.php on line 35",
            "file": "\/www\/services\/UsersService.php",
            "line": 7,
            "trace": [
                "#0 \/www\/controllers\/UsersApiController.php(35): Grocy\\Services\\UsersService->CreateUser(NULL, NULL, NULL, NULL)",
                "#1 [internal function]: Grocy\\Controllers\\UsersApiController->CreateUser(Object(Slim\\Http\\Request), Object(Slim\\Http\\Response), Array)",
                "#2 \/www\/vendor\/slim\/slim\/Slim\/Handlers\/Strategies\/RequestResponse.php(41): call_user_func(Array, Object(Slim\\Http\\Request), Object(Slim\\Http\\Response), Array)",
```

**Comment by gen2fish** [comment]
I get the same error when I try from the Swagger;

```
{
  "username": "test",
  "first_name": "test",
  "last_name": "test",
  "password": "test",
}
```

```
{
  "message": "Slim Application Error",
  "error": [
    {
      "type": "TypeError",
      "code": 0,
      "message": "Argument 1 passed to Grocy\\Services\\UsersService::CreateUser() must be of the type string, null given, called in /www/controllers/UsersApiController.php on line 35",
      "file": "/www/services/UsersService.php",
      "line": 7,
      "trace": [
        "#0 /www/controllers/UsersApiController.php(35): Grocy\\Services\\UsersService->CreateUser(NULL, NULL, NULL, NULL)",
```

**Comment by gen2fish** [comment]
Interestingly, though.  When I use this;

```
{
  "id": 0,
  "username": "string",
  "first_name": "string",
  "last_name": "string",
  "password": "string",
  "row_created_timestamp": "2018-12-31T17:39:08.770Z"
}
```

It creates the user successfully via Swagger.

**Comment by berrnd** [comment]
Kind of strange, do you have any reverse proxy or something inbetween which maybe changes the request content type? I think Slim Framework only cannot parse the body when the content type is not `application/json`...

I can try to add some debugging info around/before `$request->getParsedBody();`...

The problem with the request
~~~
{
  "username": "test",
  "first_name": "test",
  "last_name": "test",
  "password": "test",
}
~~~
through swagger is the trailing comma (after password), this is not valid JSON, so this is also not parsed by Slim...

**Comment by gen2fish** [comment]
I am using HAProxy to forward the requests into the container, let me try the Swagger without the trailing comma and also I'll try direct without the proxy.

**Comment by gen2fish** [comment]
So the Swagger worked when I fixed the trailing comma that you pointed out.

I also believe I fixed my issue. Powershell was not passing the body of the request as JSON and so it wasn't getting accepted.  Once I adjusted my script to convert to JSON as so;

```
$params = @{
    body =  @{
      "id" = 0
      "username" = $UserName
      "first_name" = $FirstName
      "last_name" = $LastName
      "password" = $Passwd
      "row_created_timestamp"= $Execute
    } | ConvertTo-Json -Depth 5
      uri = "$URI/api/users/create"
      headers = @{
        "accept" = "application/json"
        "Content-Type" = "application/json"
        "GROCY-API-KEY" = $global:grocyGlobal.APIKEY
      }
      method = "Post"
  }
```

It worked as expected.

Thank you for the responses and the great app.

**Comment by berrnd** [comment]
Great, and thanks!

Maybe you're the first who uses the API with [gen2fish/grocy-posh](https://github.com/gen2fish/grocy-posh), at least the first project that I saw - so hope the API covers everything needed...

If you think this is something "everyone" could need, feel free to request it to be added under the [github.com/grocy](https://github.com/grocy) organziation.

Happy new year! 🎆 🥂
