### ISSUE TITLE
Wrong factor for indirect unit conversions

### ISSUE THREAD

**Issue by berrnd** [grocy/grocy#1264]
_Originally posted by @Michael-Linz in https://github.com/grocy/grocy/issues/1217#issuecomment-757325302_

> This is how the error accures:
> 1. I create a product "red wine", unit: bottles, conversion override: 1 bottle = 0.75 l
> 2. 1 l = 1,000 ml in the general conversion table
> 3. I create a recipe with an ingredient of 125 ml "red wine"
> 4. Endet up for 125 ml converted to 166,667 bottles of "red wine"

Demo instance to reproduce that: https://test-x53zb70t1hb1qd9tutqrrt.demo-prerelease.grocy.info/recipes?recipe=7

**Comment by berrnd** [comment]
_Another example originally reported by @InToSSH in https://github.com/grocy/grocy/issues/1307#issue-804465378_

> 
> 
> Assuming we have two QU master data: Litre and Millilitre - which specify conversions on QU level 1L=1000ml (and inverse).
> 
> Demo instance: https://test-jgwoz1wt3ssrzwh6mu11.demo-prerelease.grocy.info/
> 
> Products: [Kofola](https://test-jgwoz1wt3ssrzwh6mu11.demo-prerelease.grocy.info/product/27), [Kofola 1.5L](https://test-jgwoz1wt3ssrzwh6mu11.demo-prerelease.grocy.info/product/28)
> 
> Steps to reproduce:
> 
>     1. Create parent product with unit Litres
> 
>     2. Create child product with unit Bottles
> 
>     3. Set product level QU conversion: 1 Bottle = 1.5L
> 
>     4. Also set product level QU conversion: 1 Bottle = 1500ml
> 
>     5. Purchase 3 bottles of child product.
> 
>     6. Stock overview shows that we have **4 500 004,5 Litres in stock**.
> 
> 
> Screenshots:
> ![2021-02-09_12-28-12](https://user-images.githubusercontent.com/6452373/107357415-4fd57e00-6ad2-11eb-946b-08a338a0f585.png)
> 
> ![2021-02-09_12-27-22](https://user-images.githubusercontent.com/6452373/107357437-58c64f80-6ad2-11eb-8eaf-be69d489997e.png)
> 
> ![2021-02-09_12-27-46](https://user-images.githubusercontent.com/6452373/107357442-59f77c80-6ad2-11eb-93d7-6dbe3278d053.png)

**Comment by lepouletfou2** [comment]
This fixed it for me. https://github.com/lepouletfou2/grocy/commit/98ff7b2ea309b4eb603ccbc1c738b6f697309f3a

But I found out yesterday that this brings a **really big** performance loss.

To get this under control, the query can certainly be optimized and at the same time also eliminate the duplicate queries in the javascripts.

I'm still trying to find a solution for the performance, but would also appreciate help - either in slimming down the concurrent calls or in the SQL query.

**Comment by lepouletfou2** [comment]
@berrnd : Whats about the idea? This fixed the Problem with the wrong amount at the amount_opened_aggregated.
 
If there one could "simplify" the SQL query a bit, which at the same time is less CPU-heavy, would solve at least one problem acceptably...

**Comment by berrnd** [comment]
Thanks for the idea, have not looked into it yet, currently don't work on grocy - any progress is always tracked in the corresponding issue, so if I have checked or fixed it, I will note it here.

**Comment by berrnd** [comment]
Another example originally reported on https://www.reddit.com/r/grocy/comments/nk2cuv where **all conversions are product overrides**:

> When converting units, the callory count gets screwed up:
> 
> https://test-1pqe9lg5bfraye4cmd1js6.demo-prerelease.grocy.info/recipes?recipe=8
> 
> ![grafik](https://user-images.githubusercontent.com/2161815/119384421-f847d080-bcc4-11eb-9d72-6ade1adeedc3.png)

**Comment by berrnd** [comment]
> 
> 
> Another example originally reported on https://www.reddit.com/r/grocy/comments/nk2cuv where **all conversions are product overrides**:
> 
> > When converting units, the callory count gets screwed up:
> > https://test-1pqe9lg5bfraye4cmd1js6.demo-prerelease.grocy.info/recipes?recipe=8
> > ![grafik](https://user-images.githubusercontent.com/2161815/119384421-f847d080-bcc4-11eb-9d72-6ade1adeedc3.png)

This is subject to #1360.
