### ISSUE TITLE
Feature request: certain items are added to the shopping list when they reach the minimum amount

### ISSUE THREAD

**Issue by Mills79** [grocy/grocy#1266]
If their could be an option so that when certain items reach the minimum level they are added to the shopping list

**Comment by berrnd** [comment]
There is this button on the shopping list page which does exactly that:

![grafik](https://user-images.githubusercontent.com/2161815/104293822-bdd05a80-54be-11eb-9327-a1ce649fcd30.png)

So do want that this happens automatically?

**Comment by lyz-code** [comment]
It's just a click, but yes, it would be nice that it was automatic

**Comment by berrnd** [comment]
There is now this new shopping list setting for that (top right corner settings menu):

![grafik](https://user-images.githubusercontent.com/2161815/161424558-36001c17-f17e-406c-93c5-76672b13d056.png)
