### ISSUE TITLE
How about scalable recipes?

### ISSUE THREAD

**Issue by teamtmedia** [grocy/grocy#127]
Just looking through this solution (nearly perfect for my needs) but note that a recipe is not scalable.  It is useful to be able to define the amount of servings that a recipe creates then be able to cook a different amount and have the software make all the calculations.  This is also useful for shopping.

Example:
x+y+z = 4 portions of Bolognese
therefore (don't know where that symbol is)
8 portions = 2x + 2y + 2z

**Comment by berrnd** [comment]
Great idea, so I think we need:

- A field per recipe to define for how much portions the recipe is
- A field to change the defined portions when displaying the recipe, doing the calculations on change
  - The same in the popup when putting everything on the shopping list

**Comment by teamtmedia** [comment]
Sounds perfect.  I'll keep an eye on your release notes :)

**Comment by berrnd** [comment]
This is now done. :)

- A new field in the recipe edit form to define for how much servings the recipe is
- A field to change the desired servings when the recipe is displayed, changes here will scale the ingredient amount accordingly

If you want, you can play around in the already updated [pre-release demo](https://demo-prerelease.grocy.info/recipes) to check if this is what you thoguht of.

The thing about the popup before putting everything on the shopping list will be tracked in #125.
Currently the amount for the shopping list is the scaled amount (I think this is ok, no need for an additional "desired servings"-input in the popup then).

**Comment by simongavris** [comment]
Yes this is exactly what I needed, thanks :+1: 
two things I noticed though:

1. You can now have the requirement to have 0.5 Packs (for example), If you have 0 of ProductA in Stock but need 0.5 of ProductA for RecipeA then RecipeA will say "everything in stock"
2. It would be good to include servings for sub-recipes: 1 serving of ice cream needs 2 servings of chocolate sauce.

**Comment by berrnd** [comment]
Thanks for testing.

1. Seems to be a rounding problem, can be reproduced with [this](https://demo-prerelease.grocy.info/recipes?recipe=7) and [that](https://demo-prerelease.grocy.info/recipes?recipe=8) recipe => will be tracked in #164

2. Great idea, will be tracked in #163
