### ISSUE TITLE
Bug: Tasks page: Group by categories: Duplicated groups

### ISSUE THREAD

**Issue by ilakast** [grocy/grocy#1274]
I created two Task categories (Home and Car) and then proceeded to start creating Tasks.
Initially the tasks were grouped fine but after adding a few more, the categories started duplicating and thus they are not grouped any more as per screenshot:

![Screenshot from 2021-01-16 19-39-09](https://user-images.githubusercontent.com/1414477/104821288-aed90780-5832-11eb-8f4e-302910f31d37.png)

Version 3.0.1
Released on 2021-01-05 12 days ago

PHP Version 7.3.26
SQLite Version 3.32.1

**Comment by berrnd** [comment]
Please try to reproduce that on the demo instance: https://demo.grocy.info

Or double check that those are really different categories, maybe provide the output of [`/api/objects/tasks`](https://demo.grocy.info/api/objects/tasks) and [`/api/objects/task_categories`](https://demo.grocy.info/api/objects/task_categories).

Or maybe just try to reset the table options (left upper table edge eye icon -> Reset).

**Comment by ilakast** [comment]
Thank you for the suggestions. I tried 2 out of 3 to no avail:

1. Same happens on the demo instance
2. Trying to reset the table options, did not fix it (thanks for that because I was not aware of that option)

I am not sure how to provide the output of `api`
