### ISSUE TITLE
Feature request: Return to products when pressing enter while editing a product

### ISSUE THREAD

**Issue by lyz-code** [grocy/grocy#1276]
When editing a product from the manage master data, after the details have been modified, if I press enter I get redirected to the same page, I understand it's to add the unity conversions. 

It would be nice if we had a configuration option or something that will return to the products list when pressing enter.

Another option is that if we press enter and nothing has changed, it returns to the products page. This can happen after pressing once enter and get redirected to the product, if you press enter again, it brings you to the products list

**Comment by berrnd** [comment]
There are two buttons to submit the form, `ENTER` is just a shorthand to use the default button (so here the green one, most of the time the first (so left) one).

If there are two buttons or not also depends if you came from another page/flow, that's maybe what you mean with
> _Another option is that if we press enter and nothing has changed, it returns to the products page. This can happen after pressing once enter and get redirected to the product, if you press enter again, it brings you to the products list_

I don't know if a option for this makes so much sense, maybe consider using [custom JS](https://github.com/grocy/grocy#adding-your-own-css-or-js-without-to-have-to-modify-the-application-itself) to customize every detail to fit your needs.

**Comment by lyz-code** [comment]
At least for me it makes sense because now I have to use the mouse to edit a product instead of just using the keyboard, which slows me down a little bit. But I fully understand that it can be a corner case that is not worth the development time.

Maybe another solution could be to bind `Shift + Enter` to the second button?

Anyway, if you feel it's an isolated case, I'm fine with closing the issue.

And as always, thanks for developing grocy, it's a kickass tool :)

**Comment by berrnd** [comment]
After having another look on that:

`Save & continue` makes sense to be the default when
- coming from another page (=> then redirects back to the origin)
- creating a new product (=> then says on the same page, to add QU conversions and barcodes)
_=> both is already the case_

`Save & return to products` makes sense to be the default when
- editing an existing product and coming from the product list page
- after creating a new product once `Save & continue` was used
**=> That's not already the case will change that.**

When I understand it correctly, that's what you wanted.

**Comment by lyz-code** [comment]
Your scenarios makes sense to me and describes better what I meant. With the annotation that the first case you described under  `Save & return to products`,  `editing an existing product and coming from the product list page` doesn't work for me either, and could be changed too.
