### ISSUE TITLE
Feature request: disable chores

### ISSUE THREAD

**Issue by Festeazy** [grocy/grocy#1278]
Hey, been a while since I put in a ticket

I was hoping to see the option to disable Chores just like Products

This is mainly for seasonal chores, like snow shoveling and mowing the lawn which aren't applicable all year round.

**Comment by berrnd** [comment]
If you want to disable chores completely, there is a feature flag (config.php) for that.

If you want to disable a single chore, products/chores/batteries have a "Active" flag since v3.0.0.
