### ISSUE TITLE
Cost of recipe

### ISSUE THREAD

**Issue by teamtmedia** [grocy/grocy#128]
Could it be possible to have the cost of the recipe calculated from the ingredients (after scaling, if applied) in stock?  I can see that this might be a bit fluid due to pricing fluctuations but even based off the most recent price should give a good indicator as to how much a recipe costs.

**Comment by teamtmedia** [comment]
Ooh, Happy New Year :)

**Comment by hovingadesign** [comment]
This feature would be great, and to build on it to see how much was spent within a time period based on items consumed would be great!

**Comment by berrnd** [comment]
This is now done. :)

The total cost is display in the header of the recipe, based on the last purchase price per product.
Recipe scaling (#127) was also added today, so this will of course also respect this.

![firefox_2019-03-03_16-38-17](https://user-images.githubusercontent.com/2161815/53697568-c8a20a80-3dd2-11e9-8f84-730fa77fae39.png)

You can play around in the already updated [pre-release demo](https://demo-prerelease.grocy.info/recipes) with it, if you want.

@hovingadesign "Analytics things" will be part of #64 (not yet done).
