### ISSUE TITLE
Bug: Unit conversion weird behavior in recipies

### ISSUE THREAD

**Issue by teitrand** [grocy/grocy#1281]
Conversion of units in recipies are a bit odd. 

Trying to add one table spoon (spiseskje) of butter (smør) 

Seems like it multiplies the stock unit by the number insted of converting it from kilos to grams and then to table spoons (1 table spoon is 15 grams) 

This results in 1 table spoon becoming 15 kilos. 

When I go back to edit the amount is 1,0000000000000049 of some unknown reason. 

The overview of the recipe says that I have added 15 table spoons

This seems to happen when I add more than one unit conversion override for the same product. 

Running grocy 3.0.1

![Screenshot_20210122_095551_com android chrome](https://user-images.githubusercontent.com/16181644/105469152-1e6a4f00-5c98-11eb-9499-aec2be1cabe4.jpg)

![Screenshot_20210122_094738_com android chrome](https://user-images.githubusercontent.com/16181644/105468322-2675bf00-5c97-11eb-833d-eea9654fd6fe.jpg)
![Screenshot_20210122_094720_com android chrome](https://user-images.githubusercontent.com/16181644/105468327-27a6ec00-5c97-11eb-8698-50442fa7aca1.jpg)
![Screenshot_20210122_094651_com android chrome](https://user-images.githubusercontent.com/16181644/105468328-283f8280-5c97-11eb-877c-51bc0bab1afa.jpg)

**Comment by berrnd** [comment]
Please try to reproduce such problems on the demo (use a [private demo instance](https://www.reddit.com/r/grocy/comments/jwnk9b)), by that it's much easier to understand it.

All amounts are stored internally related to the products (and thereforce are converted from/to) stock unit.

Based on your "Decimal places allowed for amounts"-setting and the factor, this can lead into rounding problems at some point.
Only solvable by calculating with "real" fractions (tracked in #389), which is a kind of a whole other world...

**Comment by teitrand** [comment]
I have created a demo here: https://test-at7agzfe3c97t7kw5rc8wg.demo.grocy.info/quantityunits

Created product butter, added conversion and added 1 tablespoon of butter to the pancakes recipe. That is all that is needed to create the error.

Skaff deg Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by berrnd** [comment]
You store "Butter" in Kilos, buy it in Packs have a product specific conversion between Grams and Tabelspoons - how should grocy know how to get Tablespoons from Kilos? That's the problem since the base is always the products stock unit.

So either store it in Grams or also define a corresponding conversion, then it will work.
Please also note #1264.
