### ISSUE TITLE
Bug: Cannot upload image from mobile device

### ISSUE THREAD

**Issue by ahmadsyamim** [grocy/grocy#1282]
Please describe the bug as detailed as possible, provide the steps how to reproduce it and maybe attach screenshots where useful.

Please also check if your bug was maybe already fixed by searching closed issues here or by trying to reproduce your problem on the [pre-release demo](https://demo-prerelease.grocy.info/) (use a *private demo instance* if you want to make your example persistent).

**Comment by berrnd** [comment]
What's the error message, what's in your webserver log - how do you think someone should help without providing any detail?

Please also try to reproduce problems on the demo instance first, if it works there, it's most probably not a bug, but more a problem with your installation.
