### ISSUE TITLE
Feature request: Show product image stock overview

### ISSUE THREAD

**Issue by JamesDAdams** [grocy/grocy#1283]
Hi, 

it's possible to add a possibility to show image product on list like that ?

Thanks for the response :)

![Capture](https://user-images.githubusercontent.com/20860324/105557445-92ded580-5d0c-11eb-93e4-1aa323ac9435.PNG)

**Comment by berrnd** [comment]
Not yet, otherwise the column would be visible on the table options dialog (eye icon top left table corner - but seems you use an old version which also doesn't have that).

**Comment by JamesDAdams** [comment]
> Not yet, otherwise the column would be visible on the table options dialog (eye icon top left table corner - but seems you use an old version which also doesn't have that).

I not use the last version because is not compatible with the mobil app

**Comment by berrnd** [comment]
The product picture is now available as a (hidden by default) column, just like the others - looks like that:

![grafik](https://user-images.githubusercontent.com/2161815/125500151-7162756a-e5e1-4ed3-a2b4-00b0559401f7.png)

(The picture is currently max 64x64 px in size.)
