### ISSUE TITLE
Bug: Your Composer dependencies require a PHP version ">= 7.4.0

### ISSUE THREAD

**Issue by BaumiCoder** [grocy/grocy#1285]
### Situation
I try to install grocy on virtual machine with virtualbox. The virtual machine runs this software:

- Debian Buster 10.7 (Package source: http://ftp.de.debian.org/debian/)
- nginx 1.14.2
- PHP 7.3.19
- sqlite3 3.27.2
- grocy 3.0.1

I configure like it is described in the README.md. Only differences I have to make are the following:

1. I change in the default language to german in the data/config.php.
2. I change in the default currency to EUR in the data/config.php.
3. Instead of `try_files $uri /index.php$is_args$query_string;` (copy of the README.md) I write`try_files $uri /app.php$is_args$query_string;` in nginx configuration
4. Instead of `index index.php` (a typical default for php applications)  I write `index app.php` in nginx configuration.

The reason for changes 3 and 4 are the fact that there isn't any index.php in the the latest release of grocy. (Is that maybe also a little bug in the README.md?)

### Error

When I browse to this local grocy server, I get the following error.

- In the title of the browser tab `403 Forbidden`
- In the content area: `Composer detected issues in your platform: Your Composer dependencies require a PHP version ">= 7.4.0". `

Why PHP 7.3 isn't enough? (It is stil a [supported version](https://www.php.net/supported-versions.php).) The README.md says something different then the error.

> Based on user reports, the minmimum required/working runtime is PHP 7.2 with SQLite 3.9.0
> However, I don't really care about supporting old runtime stuff, currently everything is only tested against (means 100 % works with) PHP 7.4 with SQLite 3.27.2

**Comment by berrnd** [comment]
This is the issue tracker, this is obviously not a bug, so please use the [subreddit](https://www.reddit.com/r/grocy/) for general help as [mentioned in README](https://github.com/grocy/grocy#questions--help--bug-reporting--feature-requests).

The whole application gets bootstraped in `index.php`, so of course it will not work when you use `app.php` as the main/index file (don't know where it's written that you should do that).

> Instead of `index index.php` (a typical default for php applications)

A typical default is also to have a `public` directory were all exposed things are wrapped in, and voila - there you also find that `index.php` file: https://github.com/grocy/grocy/blob/master/public/index.php

> Why PHP 7.3 isn't enough?

Some users reported that also 7.2 is fine, as written in README - I also test with the versions mentioned there (PHP 7.4 with SQLite 3.27.2). PHP 7.4 was released over a year ago, I never require bleeding edge things, but cannot understand why sticking to old runtime stuff is prefered by a lot of people...

**Comment by daviewales** [comment]
@berrnd, I'm very happy to update to the latest packages, but PHP 7.3 is the latest version of PHP available in the latest version of Debian Buster. I have a pretty standard install of grocy on nginx, and I got the same error as @BaumiCoder after running `./update.sh`:

    Composer detected issues in your platform: Your Composer dependencies require a PHP version ">= 7.4.0".

I notice that [composer.json](https://github.com/grocy/grocy/blob/f1efd08bc692968856c0446f27cc9284c0200579/composer.json) requires `"php": ">=7.4"`. However, I can't see a way to change this on my server. (`composer.json` doesn't appear to exist.)

I assume I would need to clone the repository, reduce the dependency to 7.3, and rebuild with Composer and Yarn to see if it works with 7.3? It would be nice to keep the default requirements of grocy compatable with the latest version of Debian at least.

**Comment by berrnd** [comment]
> after running `./update.sh`

Can't be true, [`update.sh`](https://github.com/grocy/grocy/blob/master/update.sh) simply unpacks the release ZIP and never runs `composer`.

Having `composer` and `yarn` installed is not a required when using the release ZIP, everything needed is included, and therefore `composer.json` is also not part of it as not required.

Feel free to use PHP 7.3, with the requirement mentioned in `composer.json` I just want to say that nothing else get tested (and again, when using the release you will never see Composer errors).

**Comment by Forceu** [comment]
It happened to me as well after upgrading with the update.sh. There is a check that is autoloaded with composer that disallows running the instance with any PHP version below 7.4

**Comment by daviewales** [comment]
Hi @berrnd, I'm not saying that update.sh runs composer. Rather, I assume that the release ZIP contains artefacts from when the project was built, and the [composer.json](https://github.com/grocy/grocy/blob/f1efd08bc692968856c0446f27cc9284c0200579/composer.json) requirement for `php>=7.4` appears to prevent the release zip from working on PHP 7.3.

I did not have composer installed on my system when I updated to grocy 3, but when try to load grocy in my browser, I instead get the error message:

    Composer detected issues in your platform: Your Composer dependencies require a PHP version ">= 7.4.0".

I have cloned the repository and reduced the requirement to `php>=7.3`, and am currently rebuilding with Composer and Yarn, to see if that fixes the issue.

**Comment by berrnd** [comment]
Ok, didn't know that Composer does that check at runtime, I've added "platform-check: false" in https://github.com/grocy/grocy/commit/3d82c9abbd4f17d130c39a5774c26f109584dec8 to disabled that check.

(Btw. I also like and use Debian and it's no problem to use an up to date PHP release there.)

**Comment by daviewales** [comment]
Thanks @berrnd! Regarding Debian, are you installing newer versions of PHP via PPA? Or are you running a testing version of Debian? The [latest PHP](https://packages.debian.org/buster/php) I can see in the repos for Debian Buster (10) is PHP 7.3.

**Comment by berrnd** [comment]
I run Debian stable and use [deb.sury.org](https://deb.sury.org/) for PHP packages (and https://nginx.org/packages/mainline/debian/ for nginx, since I just don't want to wait years to be able to use new features...).
