### ISSUE TITLE
Feature request: NFC tag support

### ISSUE THREAD

**Issue by hansidampf** [grocy/grocy#1287]
Please add support for NFC tags. Idea is to scan an NFC tag on a product to transfer or to consume it directly by just scanning the NFC tag.

**Comment by berrnd** [comment]
That's not different than barcodes - your NFC reader would need to act as a keyboard (like all barcode readers do, most of the time called "HID emulation").

There is no native browser / web platform support yet, ref:

https://developer.mozilla.org/en-US/docs/Web/API/Web_NFC_API

https://caniuse.com/webnfc
