### ISSUE TITLE
Bug: When editing a shopping list entry, it cannot be saved without entering a note or reselecting the item

### ISSUE THREAD

**Issue by Forceu** [grocy/grocy#1289]
To reproduce:

1. Add entry to shopping list
2. Click on edit entry
3. It cannot be saved and the message "A product or a note is required" is shown

**Comment by berrnd** [comment]
Most probably caused by the same which affects #1261.

**Comment by Forceu** [comment]
Ah thanks, I did not see that issue

**Comment by berrnd** [comment]
There were changes lately for v3.0.1 that either a product or a note should be required for shopping list items (no field was required before), references https://github.com/grocy/grocy/commit/9f1692e31f996bf75407354a5ac150284203571c and #1226.
