### ISSUE TITLE
Feature request: Connect more than one pdf-document to equipment entries

### ISSUE THREAD

**Issue by baschdl78** [grocy/grocy#1290]
It would be very nice to get the abililty to connect more than only one pdf to an equipment entry. if so you could connect scanned invoices etc.
Thank you very much for the great software! I love using it!

Greatings from Karlsruhe, Germany

Sebastian

**Comment by berrnd** [comment]
You can already add any field to any entity/object by using Userfields, see #683 and #176.

Rendering Userfields of type "File" for equipment as tabs is already tracked in #978.

**Comment by baschdl78** [comment]
Okay, i tried this and it's fine... how can i display this useerfield-files in the overview on the right side in the equipment view... i found how to show the links to this userfield-files in the listing, but not in the "quick-view"

**Comment by berrnd** [comment]
Cross-referencing #978 here - it's now possible to add multiple files / PDFs to each equipment by using Userfields, changelog excerpt:

> - It's now possible to add multiple files (PDFs / manuals) to each equipment
>    - Define as many Userfields for the entity `equipment` and use the type `File`
>    - => Each of those File-Userfields will be shown as a separate tab on the equipment page
