### ISSUE TITLE
Bug: with Scan-Mode on it's not possible to consume something

### ISSUE THREAD

**Issue by sleeplessnight2** [grocy/grocy#1292]
Problem: The automatic booking (scan mode) does not wait until other script-functions has processed all fields.

This leads to the error message: "Scan mode is on but not all required fields could be populated automatically".

Steps to reproduce:
Just try on the demo to consume an article with scan mode on.

As an idea: Either protect the function by a lock from a early execution or asynchronous processing of the JS code.

**Comment by sleeplessnight2** [comment]
I have noticed due to a delay that these lines 

https://github.com/grocy/grocy/blob/5ecd3a585ecc34828a793bf49e2cf873bc58ddf6/public/viewjs/consume.js#L650-L653

then change the previously correctly filled amount back to "1".

What are these lines for?

If I delete these simply, then the correct quantity is consumed - otherwise always only 1.

**Comment by berrnd** [comment]
What are these lines for?

When the scanned barcode has no amount defined, `1` is used (existing behaviour since Scan Mode exists, please don't restart the discussion about this, it's never used when the barcode has an amount, this here is generally a timing problem).

**Comment by sleeplessnight2** [comment]
ok, thanks.
Then the code relic becomes a problem later. Because it seems to always overwrite the Quick & Standard Consume Amount....

For me, however, the problem is already solved with the removal of the lines - this inflates somehow infinitely when the amount is changed 100 times by functions in the script.

Thanks again for the explanation
