### ISSUE TITLE
Feature request: Automatic testing (initially focus on lint + styling)

### ISSUE THREAD

**Issue by mountainsandcode** [grocy/grocy#1293]
First of all, thanks for the hard work on this @berrnd - think it’s a brilliant tool already!

In order to facilitate development, I was thinking it might be helpful to add:
- Automatic code linting to check for errors, typos, etc, which could also be used to enforce the style guide (this could help prevent things like #1260)
- Potentially, in the future, doing some automated testing, though I think this is less of a priority

Happy to try to help on setting this up - if you think it’s helpful. If you do, and you have some ideas, happy to try to consider those in a possible PR!

**Comment by berrnd** [comment]
Thanks for the suggestion.

See https://github.com/grocy/grocy/issues/1114#issuecomment-720150440 and the there referenced other issues/comments about "dev topics".

I aready use (PHP) code linting, the changes which caused #1260 were not done by me. In general those things maybe cause 0.001 % of the reported bugs, all other things are UI glitches or simply logic errors. Both is hard to tackle by automatic tests, at least it's a lot of work, probably more then building/fixing the feature/problem itself - so out of scope for grocy for me.
