### ISSUE TITLE
API error requesting product search in Cyrillic Bug: 

### ISSUE THREAD

**Issue by vring0** [grocy/grocy#1296]
Version 3.0.1
PHP Version 7.4.14
SQLite Version 3.34.1

I get an error when I search for a product with a Russian name. If the product is named with an English name, the request succeeds.

![image](https://user-images.githubusercontent.com/34909289/106243288-ec726300-622a-11eb-9ffa-3887d3e27f56.png)

![image](https://user-images.githubusercontent.com/34909289/106243072-808ffa80-622a-11eb-94ae-87f383e8adf6.png)

**Comment by berrnd** [comment]
Example call: https://ru.demo-prerelease.grocy.info/api/objects/products?query%5B%5D=name%3D%D0%9F%D0%BE%D0%BC%D0%B8%D0%B4%D0%BE%D1%80
(Product "Помидор")

**Comment by vring0** [comment]
> Example API request: https://ru.demo-prerelease.grocy.info/api/objects/products?query%5B%5D=name%3D%D0%9F%D0%BE%D0%BC%D0%B8%D0%B4%D0%BE%D1%80
> (Product "Помидор")

What mistake am I making?

**Comment by vring0** [comment]
![image](https://user-images.githubusercontent.com/34909289/106248232-8558ac80-6232-11eb-89a0-bbeaff12e030.png)

example of a product search query in Latin. It succeeds and I get the code 200 in response.

**Comment by berrnd** [comment]
> What mistake am I making?

You make no mistake, click the link - it results in the same error message, so this is of course a bug.

I just wanted to provide a demo instance link for reference.
