### ISSUE TITLE
Mobile Add All Items

### ISSUE THREAD

**Issue by kwilliams147** [grocy/grocy#130]
When you click "Add all list Items to stock" on mobile the skip and close button are not accessible and the only way to get out is to go back a page.

**Comment by berrnd** [comment]
Are you sure that they are not visible at all? Can just reproduce that there is a maybe to big whitespace, which can be improved, but the buttons are there when scrolling down...

**Comment by kwilliams147** [comment]
I've repoduced this on an iPhone using chrome several times now. I am not able to scroll down and see the buttons it is just blank white. I can take pics if needed.

**Comment by berrnd** [comment]
Ok, I don't have an iPhone to reproduce, but I will improve the unneeded whitespace, maybe then this is solved...

**Comment by BlizzWave** [comment]
I'm using Chrome on Android. I need to scroll far down to see the buttons, but they are there.
Maybe look into making grocy more mobile friendly?

**Comment by kwilliams147** [comment]
Here is a video that might make more sense to you. It also looks like the date picker derps out too. 

https://imgur.com/a/Q0C6yKF

**Comment by berrnd** [comment]
This should now work better, if you want, you can do a quick test in the already updated [pre-release demo](https://demo-prerelease.grocy.info/shoppinglist).
