### ISSUE TITLE
Feature request: Meal / Recipe planner : Add teh possibility to select product

### ISSUE THREAD

**Issue by ztec** [grocy/grocy#1300]
On the Meal / Recipe planner, I like to schedule my week (and the next one). I cook often (thanks CoVid-19 😬 ) but not all the time.
 I would love to **be able to add simple product** like a Pizza, a pre-made meal I bought, instead of a cooking recipe . This would help building the shoping for the week.

**Comment by berrnd** [comment]
Already possible, recipes, products and notes can be added (like also showcased on the [demo](https://demo.grocy.info/mealplan)):

![grafik](https://user-images.githubusercontent.com/2161815/106865174-1ca67f80-66cb-11eb-9e87-1f2499664382.png)
