### ISSUE TITLE
Feature request: Feature Flag for calorie tracking

### ISSUE THREAD

**Issue by fridtjof** [grocy/grocy#1301]
We are not really interested in tracking/planning calories using grocy - so a feature flag to declutter some forms and views would be nice!

**Comment by berrnd** [comment]
Calories are not "tracked", they are just defined per product and then displayed for recipes and the meal plan.

When we add a feature flag for every single product property there will be a lot of them at the end, but well, let's leave this open...

Consider simply using [custom CSS](https://github.com/grocy/grocy#adding-your-own-css-or-js-without-to-have-to-modify-the-application-itself) to hide everything you don't need, here is a snippet for `data/custom_css.html` about this topic:
```html
<style>
#selectedRecipeCard .card-body .col-6:first-child,
#selectedRecipeCard .float-right:last-child,
#group-calories {
	display: none;
}
</style>
```

**Comment by fridtjof** [comment]
I think that's a perfectly reasonable solution for what I'm trying to do!

Thank you for even preparing the correct selectors, much appreciated.

I'm fine if you'd want to close this issue, I consider the problem solved using your solution :)

**Comment by berrnd** [comment]
Closing this, individual not needed/wanted details can be hidden by using custom CSS/JS as mentioned above.
