### ISSUE TITLE
Feature request: Products without barcode prices

### ISSUE THREAD

**Issue by cmora111** [grocy/grocy#1308]
I'd like to be able to add unit prices to products without a barcode, such as produce.

**Comment by berrnd** [comment]
Please describe a little more want you want in detail, I didn't get it.

A price attached to a barcode is just the default which get perfilled for purchase.
Regardless of that, you can enter any price on the purchase page manually for any product.

**Comment by cmora111** [comment]
Thank you
 
Is there a way to get a running tally of items either on a list or already
checked off the list?

thanks
Carlos

**Comment by cmora111** [comment]
One of the issues I found was that the system requires a barcode field to be present. When I go to the grocery store items such as produce don't have barcode data and I'm having to fill in the field with junk to get it to accept. Thanks CarlosSent from my Verizon, Samsung Galaxy smartphone
-------- Original message --------From: Bernd Bestel <notifications@github.com> Date: 2/10/21  1:45 AM  (GMT-05:00) To: grocy/grocy <grocy@noreply.github.com> Cc: cmora111 <mora@spectrix.com>, Author <author@noreply.github.com> Subject: Re: [grocy/grocy] Feature request: Products without barcode prices (#1308) 
Please describe a little more want you want in detail, I didn't get it.
A price attached to a barcode is just the default which get prefilled for purchase.
Regardless of that, you can enter any price on the purchase page manually for any product.

**Comment by berrnd** [comment]
> Is there a way to get a running tally of items either on a list or already checked off the list?

I don't know what you mean by that.
When it's about exporting things, check the API.
When it's about the shopping list, there is a "check" icon/button per line to mark an line as "done".

> One of the issues I found was that the system requires a barcode field to be present.

Where is that?
Check any of the demo products, most of them have no single barcode: https://demo.grocy.info/product/25
When you select a product manually on purchase, because it has no barcode, the last price is prefilled and you are able to change the prefilled one, as said above.
Prices are not bound to barcodes in any way, if a barcode has a price und you select a product by that barcode on the purchase page, that price get prefilled - that's all.

**Comment by cmora111** [comment]
A running total of money spentSent from my Verizon, Samsung Galaxy smartphone
-------- Original message --------From: Bernd Bestel <notifications@github.com> Date: 2/10/21  10:11 AM  (GMT-05:00) To: grocy/grocy <grocy@noreply.github.com> Cc: cmora111 <mora@spectrix.com>, Author <author@noreply.github.com> Subject: Re: [grocy/grocy] Feature request: Products without barcode prices (#1308) 

Is there a way to get a running tally of items either on a list or already checked off the list?

I don't know what you mean by that.
When it's about exporting things, check the API.
When it's about the shopping list, there is a "check" icon/button per line to mark an line as "done".

One of the issues I found was that the system requires a barcode field to be present.

Where is that?
Check any of the demo products, most of them have no single barcode: https://demo.grocy.info/product/25
When you select a product manually on purchase, because it has no barcode, the last price is prefilled and you are able to change the prefilled one, as said above.
Prices are not bound to barcodes in any way, if a barcode has a price und you select a product by that barcode on the purchase page, that price get prefilled - that's all.

**Comment by berrnd** [comment]
There is the productcard on all pages where you can select a product on the right side or when you click on the product name on the stock overview page which shows for example the price history or the average price.

![grafik](https://user-images.githubusercontent.com/2161815/107531223-e7af9680-6bbc-11eb-91b5-ecb7ece28e09.png)

Any other analysis things are tracked in #64, feel free to add your thoughts, for not already mentioned things, there.

**Comment by cmora111** [comment]
Ok thanks Sent from my Verizon, Samsung Galaxy smartphone
-------- Original message --------From: Bernd Bestel <notifications@github.com> Date: 2/10/21  10:29 AM  (GMT-05:00) To: grocy/grocy <grocy@noreply.github.com> Cc: cmora111 <mora@spectrix.com>, Author <author@noreply.github.com> Subject: Re: [grocy/grocy] Feature request: Products without barcode prices (#1308) 
There is the productcard on all pages where you can select a product on the right side or when you click on the product name on the stock overview page which shows for example the price history or the average price.

Any other analysis things are tracked in #64, feel free to add your thoughts, for not already mentioned things, there.
