### ISSUE TITLE
Bug: Adding missing products to shopping list from recipe not using the QU factor.

### ISSUE THREAD

**Issue by Comrade3** [grocy/grocy#131]
I am having a problem when adding missing products of a recipe to the shopping list. Instead of saying buy 1 pack for 4 eggs it says to buy 4 packs. I have replicated it on the demo site here [https://demo.grocy.info](https://demo.grocy.info) so you can try it yourself.

Just makes sure there are no eggs in the stock or the shopping list. Then add the missing products to shopping list from the "just a lot of eggs" recipe. It should add 1 pack(10 pieces) but adds 9 packs(90 pieces).

**Comment by berrnd** [comment]
I noticed that also when comparing recipe ingredients to shopping list items the QU factor was not considered, this is now also fixed.

If you want you can do a short test on the already updated pre-release demo:
https://demo-prerelease.grocy.info
