### ISSUE TITLE
Bug: when i click on the option to add all items on the shopping list to stock it freezes

### ISSUE THREAD

**Issue by Mills79** [grocy/grocy#1310]
When I click on the option on the shopping list page to add all the items on the shopping list to stock it takes me to the first item on the list. All the fields are correct so i click O.K. . The O.K. button dims but nothing else happens. the skip button doesn't do anything and the item isn't enter to stock. the close button works though and returns me back to the shopping list.

I have Grocy installed as an addon to home assistant

**Comment by berrnd** [comment]
Works on the demo instance, so most probably not a bug, but more a problem on your installation - please always try to reproduce bugs, as mentioned on the issue template.

Please provide logs (browser console, webserver, etc.), like also mentioned on the issue template - without that I don't know how to help.
