### ISSUE TITLE
Consuming QU

### ISSUE THREAD

**Issue by Saturo78** [grocy/grocy#1313]
In my opinion, there is a conflict here between consuming small amounts in grams or liters e.g.  via recipe and booking somthing out when a container is empty. 
For some products I would like to know the exact amount for a recipe.  But I would also like to  consume transfer the whole package and not grams.
So the best thing would be stock in grams and purchase and consume as packs.

**Comment by berrnd** [comment]
Since v3.0.0 it's possible to use any product related quantity unit anywhere, so you already can purchase or consume a product in packs and grams, if both units are respectively attached to the product.

If something does not work, please provide the things mentioned in the issue template.
If you need help, the better place is the [subreddit](https://www.reddit.com/r/grocy/) as [mentioned in README](https://github.com/grocy/grocy#questions--help--bug-reporting--feature-requests).

**Comment by Saturo78** [comment]
Hallo Bernd, 

ich schreibe jetzt mal ganz frech auf deutsch weil ich glaube mein Problem so besser erklären zu können. Wenn das nicht okay ist, kannst du die Mail ja einfach löschen.

Ich kaufe Hirse in 500g und 1000g Packungen. Im Produkt muss ich mich jedoch für eine Umrechnung zwischen Einkauf und Lager entscheiden. 
Hier wähle ich 500 g. Wenn ich nun die Mengen zu den Barcodes eingebe, ergibt die 1000g Packung 2 Stück. 

Wenn ich nun 3 1000g Packung umlagern möchte muss ich 6 Stück eingeben. Gebe ich 3 Stück ein, werden 1500 g umgelagert, was ja aber falsch ist. Das ist nicht logisch und führt zu Fehlern.

So wie ich es sehe kann es nur funktionieren, wenn ich jeweils ein eigenes Produkt anlege. Das möchte ich aber eigentlich vermeiden.

Aus meiner Sicht müsste die Umrechnung zwischen Stück und Menge individuell pro angelegtem Barcode eingegeben werden.

Viele Grüße
Christian

Am 11. Februar 2021 20:21:35 MEZ schrieb Bernd Bestel <notifications@github.com>:

**Comment by berrnd** [comment]
Wenn du unbedingt die 500g und 1000g Packung verschieden behandeln willst, dann wäre die Lösung ein Parent-Produkt "Hirse" (in stock QU g) und die 500g/1000g Packung Produkte als Subproducts - zumindest machen das die meisten anderen, die diese Genauigkeit brauchen, wohl so.

Ich weiß nicht was das mit Barcodes zu tun haben soll, ein Barcode ist erstmal nur dafür da, ein Produkt bequem auswählen zu können, also eine Alternative zur manuell Suche, mehr nicht.

Ich persönlich bevorzuge es simpel, heißt hier würde ich sicher generell Hirse nicht in Gramm verwalten, sondern nur in Packungen. Umso mehr Details man tracken will, umso komplizierter - wir (oder zumindest ich) verwalten aber mit grocy kein Business, sondern nur einen Kühlschrank. Ich habe dort gern die Übersicht, aber nicht im Milligramm Bereich... ;D

**Comment by berrnd** [comment]
> Wenn ich nun 3 1000g Packung umlagern möchte muss ich 6 Stück eingeben. Gebe ich 3 Stück ein, werden 1500 g umgelagert, was ja aber falsch ist.

Nochmal dazu: Du kannst an jeder Stelle eine Menge + Mengeneinheit angeben, sofern für das Produkt entsprechend vorhanden. Was für den Barcode eingetragen ist, wird bei Benutzung auch nur entsprechend vorbelegt, mehr nicht. Also konkret: Gib halt einfach die Gramm ein.

Wenn es wieder um die verschiedenen Packungrößen geht, die für dich anscheinend eher verschiedene Produkte sind, dann musst die wohl auch eher als verschiedene Produkte anlegen, wie eben beschrieben - wie solls auch anders gehen...

Für meine Küche wär mir das zu kompliziert...
