### ISSUE TITLE
Bug: When multiple shoppinglists feature is disabled, dialog is malformed

### ISSUE THREAD

**Issue by Forceu** [grocy/grocy#1315]
When disabling the feature to have multiple shopping lists, the dialog when clicking on "Clear" is malformed:

![image](https://user-images.githubusercontent.com/1593467/107769780-bf4ca700-6d38-11eb-959d-a3303bce8f33.png)

**Comment by berrnd** [comment]
Seems to work in the meantime, don't know by which commit it got fixed...

**Comment by Forceu** [comment]
The bug seems to be still present in 3.1.0 unfortunately.
