### ISSUE TITLE
Bug: API is returning "no column named barcode" for POST /objects/products

### ISSUE THREAD

**Issue by majso** [grocy/grocy#1316]
Hi everyone,

I've installed Grocy with docker, version 3.0.1.

On API for POST ​/objects​/products I am getting:

{
  "error_message": "SQLSTATE[HY000]: General error: 1 table products has no column named barcode"
}

Also on frontend, I am not able to add new Product with barcode. I can add barcode only for existing Product.

Thanks for the reply.

**Comment by berrnd** [comment]
>  "error_message": "SQLSTATE[HY000]: General error: 1 table products has no column named barcode"

This column has been removed in v3.0.0, there is now a separate table `product_barcodes` to store them - the UI of course reflects that, check the [changelog](https://grocy.info/changelog#v3.0.0) notes before upgrading.

> Also on frontend

The something went definitely wrong during upgrade, empty your browser cache, empty your `data/viewcache` folder.

Please always try to reproduce problems on the [demo](https://demo.grocy.info/) first before reporting, as also mentioned on the issue template - if it works there and not on your installation, it's most probably not a bug.
