### ISSUE TITLE
Feature Request: use partnums.com for new products

### ISSUE THREAD

**Issue by sund** [grocy/grocy#1318]
Use https://partnums.com/ for populating new products.

**Comment by berrnd** [comment]
More or less a duplicate of #158.

It's already possible to implement that yourself using a [BarcodeLookupPlugin](https://github.com/grocy/grocy#barcode-lookup-via-external-services).

Maybe have a look at Barcode Buddy: https://github.com/Forceu/barcodebuddy

**Comment by sund** [comment]
My search didn't show this as an existing request.
