### ISSUE TITLE
Tare Weight

### ISSUE THREAD

**Issue by oakbrad** [grocy/grocy#132]
Thank you for this great software :).

My use case is I would like to track the bulk items in my pantry by weight, like flour, dry beans, etc. I store these in various standard sized mason jars. It would be useful if the tare weight of the container were stored in Grocy - maybe as an attribute of the Quantity Units? Then I could create a unit for each jar size and have the weight for each readily available.

This would be useful info to show in the 'Product Overview' when consuming/purchasing/etc. And if I could pull the tare weight from the API, I am thinking I could use a Pi type device with scanner & scale to automate updating stock levels.

**Comment by berrnd** [comment]
Maybe a special use case, but grocy is here to fit them all... :D

So when this is an attribute per quantity unit, the tare weight defined there should be subtracted once per product to get the net weight per product? What if you have maybe multiple containers of flour?

Is it maybe better to have this as an attribute per location or product?

And on the consume/purchase/inventory page there has to be maybe a radio button to select if the entered amount is net or gross then...

**Comment by oakbrad** [comment]
Yes I think you are right, it makes more sense per product. Then I could put a barcode on each jar to scan products in and have a tare weight associated with each. This would be great for tracking spices as well.

And yes if Grocy could perform the calculation that would be wonderful, an option for net/gross if the tare weight has been entered for that product.

**Comment by berrnd** [comment]
I started implementing this, but I'm not 100% sure about if subtracting the tare weight is enough for all cases...

Imagine:
- A new field "Enable tare weight handling" per product
- A new field "tare weight" per product (the weight of the jar, needs to be in the same quantity unit as the stock qu-unit, so only makes sense for e. g. gramms, etc.)
  - Product "Flour" has this enabled, quantity unit gramms, tare weight = 600 gramms
  - I do a purchase booking for 1600 gramms, say the amount is "gross" (inlcuding the jar weight) => 1600 - 600 gramms = 1000 gramms will be added to stock => ok
  - I do a consume booking, say again the amount is "gross", the current weight is 1000 gramm, in stock there are 800 gramms => so for this it means 400 gramms need to be removed from stock (`(800 in stock + 600 tare weight) - (1000 new gross amount - 600 tare weight)`)
  - For inventory it's the same based on if the new amount results in an reduction or an addition of the stock volume

Hope this is what you thought of... (?) :)
(So maybe just a reminder what to do for myself...)

**Comment by berrnd** [comment]
This is now finished in the following way:

A new option per product to enable this and to define the tare weight (weight of the container):
 
![grafik](https://user-images.githubusercontent.com/2161815/53833589-309a5180-3f89-11e9-9d68-4654748c761f.png)

On purchase/consume/inventory for such a product the amount needs to be supplied including the container weight - means you always weigh the whole jar, what needs to be added/removed from stock will be calculated based on the difference and the defined tare weight. This also applies for the API, a product which has enabled "tare weight handling" also needs the gross amount on every action.
 
![grafik](https://user-images.githubusercontent.com/2161815/53833820-bfa76980-3f89-11e9-8c9f-673bdfcbfabd.png)

Hope this fits your use case, let me know if you have further ideas. :)

Would be great if you can do some testing in the pre-release demo, demo product for this is "Flour":
https://demo-prerelease.grocy.info
