### ISSUE TITLE
Feature request: Marking that a product shouldn't be frozen

### ISSUE THREAD

**Issue by RubenKelevra** [grocy/grocy#1320]
There are certain products that should never be frozen, like non-alcoholic drinks, eggs, tins...

When a product like this is destined to be frozen or moved to a freezer a warning might be helpful to catch accidental movements of products into the wrong location or warn the user that this product shouldn't be frozen.

In both cases, we could prevent an 'oopsie', so a 'can be frozen?' yes/no/unset-field would be nice

**Comment by Uatschitchun** [comment]
All those things **_can_** be frozen. Things is, if they **_should_** be frozen

**Comment by RubenKelevra** [comment]
Okay, in this case we might want to rename the field "should never be frozen" :)

**Comment by berrnd** [comment]
There is now a new product option:

![grafik](https://user-images.githubusercontent.com/2161815/125330569-3c5f6500-e347-11eb-944f-284bc0e9d778.png)

And when freezing such a product, a warning will be shown (you can simply undo the transfer action by using the undo button of the success-notification as usual):

![grafik](https://user-images.githubusercontent.com/2161815/125330969-aed04500-e347-11eb-98ae-1087efd80e01.png)
