### ISSUE TITLE
Bug: Filtering stock by location shows the grand total of each item rather than the total in that location

### ISSUE THREAD

**Issue by samnewman86** [grocy/grocy#1323]
Please describe the bug as detailed as possible, provide the steps how to reproduce it and maybe attach screenshots where useful.

When a product is stored in more than one location, for example a fridge and a freezer. Filtering the stock by fridge shows the total amount including those in the freezer rather than just the amount in the fridge.
This is unexpected.

Please also check if your bug was maybe already fixed by searching closed issues here or by trying to reproduce your problem on the [pre-release demo](https://demo-prerelease.grocy.info/) (use a *private demo instance* if you want to make your example persistent).

**Comment by berrnd** [comment]
Duplicate-question of #1170, please check existing issues before reporting.

**Comment by samnewman86** [comment]
I don't think it's the same issue as 1170
What is the purpose of filtering by location if it's not to see what is actually in that location?

**Comment by berrnd** [comment]
I explained there that those filters are just filters regarding which products are shown, not refinment-filters like in the comparison regarding shopping sites mentioned there - and that's the same not not only for the stock overview page, but for all pages with tables and filters. However, we don't need to restart that discussion here, everything about that was said in #1170.

See also: #682
