### ISSUE TITLE
Bug: adding a barcode, 

### ISSUE THREAD

**Issue by samnewman86** [grocy/grocy#1324]
Adding a barcode to a product in the master data section. Pressing save results in an endless loading icon.
Also in this page pressing up arrow does not increment the quantity value from zero to 1

Please describe the bug as detailed as possible, provide the steps how to reproduce it and maybe attach screenshots where useful.

Please also check if your bug was maybe already fixed by searching closed issues here or by trying to reproduce your problem on the [pre-release demo](https://demo-prerelease.grocy.info/) (use a *private demo instance* if you want to make your example persistent).

**Comment by berrnd** [comment]
Please always try to reproduce problems first on the demo instance. If it works there and not on your installation, it's most probably not a bug. If you need help, please provide logs (browser console, webserver, etc.) and/or screenshots or steps to reproduce the problem.

Both is mentioned on the issue template and I really have no clue how to help without that...
