### ISSUE TITLE
Feature request: Giant database of product barcodes

### ISSUE THREAD

**Issue by KTibow** [grocy/grocy#1325]
For most products, when you Google their barcode, there's a result. It would be nice to have a "pull from web/database" option, so when you scan a barcode, it could auto-create a product with a pre-filled barcode and name.

**Comment by RubenKelevra** [comment]
I don't think Googling is a good solution, but maybe requesting the data from openfoodfacts.org is an option? :)

**Comment by berrnd** [comment]
More or less a duplicate of #158.

It's already possible to implement that yourself using a [BarcodeLookupPlugin](https://github.com/grocy/grocy#barcode-lookup-via-external-services).

Maybe have a look at Barcode Buddy: https://github.com/Forceu/barcodebuddy
