### ISSUE TITLE
Feature request: Ability to change the stock quantity unit for a product

### ISSUE THREAD

**Issue by Ape** [grocy/grocy#1326]
Currently it is not possible to change the stock quantity unit for a product once it has been added. I'd like to have a feature for doing that. It would probably need a conversion factor.

Also, here is the current error message in case someone else is also searching for this issue:

```
Integrity constraint violation: 19 qu_id_stock cannot be changed when the product was once added to stock
```

**Comment by berrnd** [comment]
This is intentionally, [changelog excerpt of v3.0.0](https://grocy.info/changelog#v3.0.0):

> ### New feature: Use any product related quantity unit anywhere
> [...]
> - Because the stock quantity unit is now the base for everything, it cannot be changed after the product was once added to stock (for now, maybe there will be a possibilty to change it in a future release)

> Also, here is the current error message:

The UI simply doesn't allow to change the QU stock (the dropdown is disabled when the product was once used), so this can only happen when you use the API and there this error is simply correct for now.

**Comment by Ape** [comment]
For me the drop down wasn't disabled and I got that error log message. I think it is only disabled on the first purchase and not with the inventory action. I'm using version 3.0.1 so this may be something that is already fixed in master.

Is there any way to change the stock QU other than deleting the product and adding everything back with a brand new fixed product? I find that my first decision for the QU wasn't always the correct one.

**Comment by berrnd** [comment]
> Is there any way to change the stock QU other than deleting the product and adding everything back with a brand new fixed product?

As mentioned in the changelog, currently not via the UI and not via the API, so maybe only by manually editing the database (where you of course also need to take care about unit conversions manually, all amounts stored anywhere in the database are related to the products QU stock).

**Comment by williamd1k0** [comment]
I started using grocy recently and have made some mistakes in product registration as I am still figuring things out.
If I understand correctly, since you can create QU conversions, it would be possible to allow the stock QU to be changed, right?

**Comment by berrnd** [comment]
> it would be possible to allow the stock QU to be changed, right?

That's exactly what would be needed to be implemented to turn this request into reality.

**Comment by berrnd** [comment]
This is now done.

- When the product was NOT yet added to stock, any stock QU can be selected (like before)
- When the product was once added to stock, there needs to exist a corresponding unit conversion for the new QU
  - => All stock amounts are converted accordingly based on that factor
  - => The UI only allows to select QUs for "QU stock" where a corresponding conversion exists
  - => The API enforces/checks that a corresponding conversion exists
