### ISSUE TITLE
Feature request: Feature flag for meal plans

### ISSUE THREAD

**Issue by Ape** [grocy/grocy#1327]
I'd like to disable meal planning with a feature flag since I am not interested in that.

**Comment by berrnd** [comment]
The meal plan is part of `FEATURE_FLAG_RECIPES`.

Consider using [custom JS/CSS](https://github.com/grocy/grocy#adding-your-own-css-or-js-without-to-have-to-modify-the-application-itself) to customize everything to your likings - here is a snippet for `data/custom_css.html` to simply hide the sidebar menu entry:
```html
<style>
.nav-item[data-nav-for-page="mealplan"] {
  display: none !important;
}
</style>
```
