### ISSUE TITLE
Error in migration 0046 for new installs

### ISSUE THREAD

**Issue by jinks** [grocy/grocy#133]
This is more or less a duplicate of #122 

I ran into the same issue and then went and did each migration by hand, the problem lies with
https://github.com/grocy/grocy/blob/b9f0470d7621bd67479515bd5bc8efd790fb9a3c/migrations/0046.sql#L16-L17

the trigger in the db for products reads as follows at that point:

```sql
CREATE TRIGGER cascade_change_qu_id_stock AFTER UPDATE ON products
BEGIN
        UPDATE "recipes_pos_old"
        SET qu_id = (SELECT qu_id_stock FROM products WHERE id = NEW.id)
        WHERE product_id IN (SELECT id FROM products WHERE id = NEW.id)
                AND only_check_single_unit_in_stock = 0;
END;
```
with `UPDATE "recipes_pos_old"` probably caused by
https://github.com/grocy/grocy/blob/b9f0470d7621bd67479515bd5bc8efd790fb9a3c/migrations/0045.sql#L1

So I guess the trigger on products has to be dropped and re-created in migration 45. But I don't know why other users are not affected. I'm also using Arch Linux like @fallenczar, the relevant versions I'm at are:

- PHP and php-sqlite: 7.2.10
- sqlite: 3.25.2

**Comment by jinks** [comment]
Adding the following block to migration 45 after the existing DROP/CREATE TRIGGER block lets me indeed install grocy from an empty db:
```sql
DROP TRIGGER cascade_change_qu_id_stock;
CREATE TRIGGER cascade_change_qu_id_stock AFTER UPDATE ON products
BEGIN
        UPDATE recipes_pos
        SET qu_id = (SELECT qu_id_stock FROM products WHERE id = NEW.id)
        WHERE product_id IN (SELECT id FROM products WHERE id = NEW.id)
                AND only_check_single_unit_in_stock = 0;
END;

```

**Comment by berrnd** [comment]
Thanks a lot for finding that!

I tested initially against SQLite 3.20.1.
Seems that there was a [change](https://www.sqlite.org/changes.html) in SQLite 3.25.2 which added that references in bodies of triggers are renamed when renaming a table ([ref](https://www.sqlite.org/pragma.html#pragma_legacy_alter_table)) - that would be why I and maybe most of other users didn't notice that...

Will take care of this in the future and will figure something out to correct this for both existing and new installs through migrations.

**Comment by jinks** [comment]
I'd guess the simplest approach is amending migration 45 (so 46 gets applied correctly an new installs) and then duplicating the same block as a new migration.

That would unnecessarily re-create the trigger twice on new installs or updates from old versions but that doesn't hurt much.

The only edge case I can think of is if someone got exactly to migration 45 on a new enough sqlite and didn't upgrade since then. (You could amend 0046 instead to cover that, too.)
