### ISSUE TITLE
Feature request: Automatic dark mode

### ISSUE THREAD

**Issue by KTibow** [grocy/grocy#1334]
Using the `prefers-color-scheme` media query, dark mode could be auto-applied if the user has it turned on for their OS. Implementation:
First, change the night mode checkbox to a select, with 3 options:
- Off
- Auto (default)
- On

Then, update [public/js/grocy_nightmode.js](https://github.com/grocy/grocy/blob/master/public/js/grocy_nightmode.js). It needs to support the select. Also, update this section:
https://github.com/grocy/grocy/blob/779ac31ffe97e57518505d733f31ba748d7ebf4f/public/js/grocy_nightmode.js#L71-L110
Use `window.matchMedia("(prefers-color-scheme: dark)").matches` if the user has it set to auto.
And finally update the backend to support the new select.

**Comment by berrnd** [comment]
This is now done, these are the new settings (and "Use system setting" is the new default):

![grafik](https://user-images.githubusercontent.com/2161815/161394337-3f53aa41-27ad-4dd1-bc98-befca150c696.png)
