### ISSUE TITLE
Bug: ical calendar link gives 401 / needs logon

### ISSUE THREAD

**Issue by annegerben** [grocy/grocy#1335]
When open the ical calendar link it gives me an error 401 (when I'm not logged on).
Too rule out reserve proxy issues I've also tried my internal ip, but the issue persists.
When I set "Setting('DISABLE_AUTH', true);" I have no issue. (but would cause other issues ;-) )

I tried to reproduce the issue on a demo instance, but I cannot change the demo user password, so no logon is needed.

I'm running version 3.0.1 with PHP Version 7.3.26 and SQLite Version 3.32.1 on docker (https://github.com/linuxserver/docker-grocy)

**Comment by berrnd** [comment]
Can't reproduce this.

If you use a reverse proxy setup (or the docker container uses maybe one), double check that query parameters hit the backend, this could be the problem since the API key is passed via the query parameter `secret`.

**Comment by berrnd** [comment]
I would say, [linuxserver/docker-grocy](https://github.com/linuxserver/docker-grocy) is missing to pass the required `?` when there are query parameters [here](https://github.com/linuxserver/docker-grocy/blob/24cddde97340ef099323338229aed7f131ab42c4/root/defaults/default#L15):

[README ref](https://github.com/grocy/grocy#how-to-install)

[grocy/grocy-docker ref](https://github.com/grocy/grocy-docker/blob/38d1f52b1e23ab9f6b2c6e890de841b1a2ba6cb9/docker_nginx/common.conf#L4)

[Server Fault ref](https://serverfault.com/a/642558)

**Comment by annegerben** [comment]
Thanks for your help, I've also setup https://github.com/grocy/grocy-docker and now I don't have the issue.
So it must be https://github.com/linuxserver/docker-grocy

**Comment by annegerben** [comment]
I did some additional testing and found the "issue".
I deleted the default admin because of security reasons.

But when I checked in the DB I noticed that the "used_id" for the "special-purpose-calendar-ical" api_key was still "1" instead of using the new admin user_id. After changing the user_id to a valid account the  issue was solved.

**Comment by berrnd** [comment]
Kind of ok that an API key get invalidated when you delete the corresponding user I would say...

**Comment by annegerben** [comment]
> 
> 
> Kind of ok that an API key get invalidated when you delete the corresponding user I would say...
indeed, but the confusing part was that active user session/cookie the api was working
