### ISSUE TITLE
Bug: Check if any amount is in stock requires > 0.9

### ISSUE THREAD

**Issue by Saturo78** [grocy/grocy#1337]
Only check if any amount is in stock expects min. 1 Unit in Stock. 0,9 Pack is not enough.

**Comment by Saturo78** [comment]
In this case also the amount of calories is calculated in packs even when you select grams.

**Comment by berrnd** [comment]
Unrelated to this problem, moved to #1338 - please keep it to one topic per request, everything else is untrackable.

**Comment by berrnd** [comment]
Fixed in https://github.com/grocy/grocy/commit/e4c8f6b0239681849986067e9d720d668caf8f7e.

**Comment by berrnd** [comment]
> In this case also the amount of calories is calculated in packs even when you select grams.

Is now also fixed in https://github.com/grocy/grocy/commit/fbb006450505f063b17e1192383450601a6aca4c.
