### ISSUE TITLE
Feature Request: Userfield with requirement

### ISSUE THREAD

**Issue by horphi0815** [grocy/grocy#1339]
Hi guys and thanks for this great great Tool!!! Absolutely awesome!

Is it possible, to add an additional field option "text input repuired"?

Best regards,

Phil

![Bildschirmfoto von 2021-02-15 18-13-25](https://user-images.githubusercontent.com/39962016/107976235-8707cb80-6fb9-11eb-8cf9-facf1ef5b809.png)

**Comment by berrnd** [comment]
Of course that's technically possible, also related to #586.

**Comment by horphi0815** [comment]
ohhh thx, didnt saw , that req already exist.
BR

Phil

**Comment by berrnd** [comment]
The Userfield form has now exactly that new option like you mocked up in the screenshot above... :)

=> https://de.demo-prerelease.grocy.info/userfield/1

**Comment by horphi0815** [comment]
Great improvement. Thank you very much. :-) looking forward to the next stable release 
Many greetings,

Phil
