### ISSUE TITLE
Purchase items from Shopping list page

### ISSUE THREAD

**Issue by oakbrad** [grocy/grocy#134]
When using the Shopping List, can there also be a 'Purchase' button alongside the edit/remove buttons?

Ideally this would launch a purchase form pre-filled with the quantity from the shopping list and fields for other metadata. Confirming the purchase should then update the shopping list and the inventory.

This would allow for 'checking off' the items on the list while shopping at the store in one step. As it is now I delete from the shopping list then have to re-enter it later on the Purchase page (unless I am missing something?).

Thank you!!

**Comment by berrnd** [comment]
We have exactly that since version 1.23.0 - one button in each line and one button to do it for all items.

![2019-01-05_08-56-14](https://user-images.githubusercontent.com/2161815/50721939-efd8a600-10c7-11e9-81d9-dfd081e708b6.png)

**Comment by oakbrad** [comment]
Ah I see, the Docker container is on 0.22.0! Thank you for the explanation look forward to using this.
