### ISSUE TITLE
Feature request: Sum up / "compact" stock entries

### ISSUE THREAD

**Issue by Saturo78** [grocy/grocy#1343]
I have 5 pack on stock. Now i transfer 1 pack to another Location and back to  the original Location an new stock entry is created, even when all Dates are the same. 
This also happens when i undo a Transaction.

I think when next due date and shopping date are the same, it should not create a new stock entry.

**Comment by berrnd** [comment]
The stock entries ([/stockentries](https://demo.grocy.info/stockentries) page) are the "raw" stock entries (so how they are stored in the database), normally not really needed to do something on this page. Possibly only when you want to correct a for example a wrong entered due date.

Stock entries can get split at any time when partial amounts are consumed/transfered/whatever.

**Comment by Saturo78** [comment]
In my eyes this realy is a problem.

I have 2 packs with different due date.
I consume 0,75 pack from due date 1 by error and undo the transaction.
Now i have 0,75 pack and 0,25 pack.

When i want to transfer the pack with due date 1 to another location and i want to do this by "Use a specific stock item", i have to transfer first 0,75 pack an than 0,25 pack. I can't do this by one transaction.

I also have tried to edit the stock entry with 0,75 pack to one and to delete the stock entry with 0,25 pack but it seems that these changes did't have any effect.

So in my opinion the only way to undo the transaction would be reseting the pack to 1 instad of creating  a new stock entry with 0,25.

**Comment by berrnd** [comment]
This is now done - changes technically nothing, but if you work manually with stock entries it should be now better.

Stock entries get automatically "compacted" (per product on any transaction and once all products during the update/migration).

**Comment by tsbertalan** [comment]
Is it possible to disable the automatic compaction? I'd like to keep stock items as they are with less magic so I can easily refer to specific ones.
