### ISSUE TITLE
Bug: Setting Show a month-view calendar can not be undone

### ISSUE THREAD

**Issue by Saturo78** [grocy/grocy#1344]
Shopping List Setting
Show a month-view calendar 

The Setting is not set after i have it activated. 
So the calender can not be disabled.

**Comment by berrnd** [comment]
Works on the demo - please always try to reproduce problems on the demo instance first as also mentioned on the issue template. If it works there and not on your installation, it's most probably not a bug.

The please provide logs (browser console, webserver, etc.), without that I have no clue how to help.

**Comment by Saturo78** [comment]
I have tested with demo and preview version. It does not work on both.

If you don´t believe me, live with the mistake. Its your software.

Am 16. Februar 2021 12:19:50 MEZ schrieb Bernd Bestel <notifications@github.com>:

**Comment by berrnd** [comment]
> I have tested with demo and preview version. It does not work on both.

Then let me know what how it doesn't work, since, as I said, it works (here):


https://user-images.githubusercontent.com/2161815/108059032-32199300-7055-11eb-872e-31129ff337c3.mp4


> If you don´t believe me, live with the mistake. Its your software.

Will be hard, since that's most probably the biggest problem for me, my life, and grocy we ever had... ;D

**Comment by Saturo78** [comment]
activate "show a month-view calender" ->okay
-> shopping list = calender is shown
go back to shopping list settings
option "show a month-view calender" is not activated

Have tested with Edge and IE.


Am 16. Februar 2021 12:48:54 MEZ schrieb Bernd Bestel <notifications@github.com>:

**Comment by berrnd** [comment]
> activate "show a month-view calender" ->okay
> -> shopping list = calender is shown
> go back to shopping list settings
> option "show a month-view calender" is not activated

Now we have a reproducible way.
