### ISSUE TITLE
Feature request: set decimal point automaticly

### ISSUE THREAD

**Issue by Saturo78** [grocy/grocy#1345]
When entering Prices it would be good if the decimal Point is inserted automaticly.

Input: 109 -> 1.09

**Comment by berrnd** [comment]
When I enter `109`, how should grocy guess if you meant `109` or `1.09`?

Only possible if you always enter the value including the decimals (also depends on the decimal places setting) and I doubt that's faster/more convenient than just entering the decimal separator (use the numeric keypad).

**Comment by Saturo78** [comment]
Das ist an jeder Supermarktkasse so.
Die letzten beiden Eingaben werden zu den Nachkommastellen.
Wenn du 109 möchtest, gibst du 10900 ein. 
Sinn des ganzen ist sich den Punkt zu sparen, der mit dem Ziffernfeld der Tastatur nicht eingegeben werden kann.

Am 16. Februar 2021 12:24:07 MEZ schrieb Bernd Bestel <notifications@github.com>:

**Comment by berrnd** [comment]
Dann lassen wir das halt offen.

> der mit dem Ziffernfeld der Tastatur nicht eingegeben werden kann.

Mein Ziffernblock hat so ein Komma (US Layout hat vermutlich sehr sicher einen Punkt)...

**Comment by Saturo78** [comment]
When entering Prices "," as separator is not accepted. Only "." works for me.
Bug or hidden Setting?

**Comment by berrnd** [comment]
It's a standard number input, your browser is responsible for that and most probably uses whatever your prefered browser and/or system locale defines as the decimal separator. When I use a German Firefox, a comma is expected. When I use an English Firefox in my dev environmet, a point is expected. Other Browser maybe behave differently.

**Comment by berrnd** [comment]
There is now this new stock setting:

![grafik](https://user-images.githubusercontent.com/2161815/125499426-2c292f5e-1da9-4fca-88fc-a71b791167eb.png)

When enabled, it then just happens accordingly (on leaving any price input field):


https://user-images.githubusercontent.com/2161815/125499730-e8745fbc-d2b7-4e4f-bc97-113045c3018b.mp4

**Comment by Saturo78** [comment]
When activated the price field is cleared when i leave it.
I could not get it to work.

**Comment by berrnd** [comment]
Still works (here, in Firefox and Chrome, current demo) like on the video above.

If it's reproducible, I'm happy to help.

**Comment by Saturo78** [comment]
On my mobil it did not work with chrome.
It works with firefox but not as i mentioned.

In my opinion the right behavier would be:

9 -> 0.09
90 -> 0.90
900 -> 9.00

In the case of 0.09 you spare to clicks.

**Comment by berrnd** [comment]
"900 -> 9.00" is the only case that works, since that's was described in the tooltip of the setting and what you requested above:

> Die letzten beiden Eingaben werden zu den Nachkommastellen.
> Wenn du 109 möchtest, gibst du 10900 ein.

So
009 -> 0.09
090 -> 0.90
also works.

So maybe the rule what you have in mind is additionally "prefix with zeros if length < desired decimal places", then the rest like it already does...

Sorry, I'm not using Supermarktkassen anywhere, so I was unable to guess the rest and just did what was mentioned here...

Can everything be done, but there is still that decimal separator available, even on most virtual keyboards, I personally just use it - and the current state also works on Chrome mobile here:


https://user-images.githubusercontent.com/2161815/126013162-3d71f48a-174a-4c28-9643-c039a2e9c71e.mp4

**Comment by berrnd** [comment]
> So maybe the rule what you have in mind is additionally "prefix with zeros if length < desired decimal places", then the rest like it already does...

I added that (ref https://github.com/grocy/grocy/commit/5478bec2c74cb9adc53a5261b5aa37be2d9042d4).

So all of your mentioned examples work now:
> 9 -> 0.09
> 90 -> 0.90
> 900 -> 9.00

Replace the file `public/viewjs/components/numberpicker.js` with [that one](https://raw.githubusercontent.com/grocy/grocy/5478bec2c74cb9adc53a5261b5aa37be2d9042d4/public/viewjs/components/numberpicker.js) if you want to have this now.
