### ISSUE TITLE
Feature request: Add default location + parent product to stock overview table

### ISSUE THREAD

**Issue by horphi0815** [grocy/grocy#1351]
It would be great to add columns to the stock overview like price, parent product, default location. :-D

Best regards,

Phil

**Comment by berrnd** [comment]
The last price and also the current stock value is already there, check the little eye icon in the top left corner of each table.

![grafik](https://user-images.githubusercontent.com/2161815/108324843-b6405780-71c8-11eb-8752-c3b7722dfd3e.png)

**Comment by horphi0815** [comment]
Great, thank you very much :-)

**Comment by Ape** [comment]
Can I also request the *current* location.
