### ISSUE TITLE
Bug: QU Conversation Plural

### ISSUE THREAD

**Issue by Saturo78** [grocy/grocy#1352]
Manage Masterdata 
Products
Milk

Add QU conversation 1 Bottle -> 0.5 Liter
"This means 1 Liter is the same as 2 Bottle "
"Das bedeutet 1 l entspricht 2 Flasche" 

Plural of "Bottle" is defined as "Bottles".

**Comment by berrnd** [comment]
Just to note that here: It's about the fourth column in the "QU conversions" table where this is wrong:

![grafik](https://user-images.githubusercontent.com/2161815/108373186-e2c39600-71ff-11eb-9f7c-1cfbc16ae626.png)
