### ISSUE TITLE
Feature request: Better "add" button handling on mobile

### ISSUE THREAD

**Issue by KTibow** [grocy/grocy#1358]
I couldn't find any already existing issues from my glance at the "add" and "add button" searches.
On mobile, the "add" button is hidden behind a 3 dot menu.
![image](https://user-images.githubusercontent.com/10727862/108448912-6e94ec80-7217-11eb-91b0-62a425286511.png)
![image](https://user-images.githubusercontent.com/10727862/108448921-7359a080-7217-11eb-8400-396f19cb2b2a.png)
Given that it's the only thing there, it doesn't really make sense for it to be hidden.

**Comment by berrnd** [comment]
That's the same layout as on all pages and I doubt that this page is so important to be often used on mobile - so I don't think we need an exception/unique handling here.

**Comment by KTibow** [comment]
It applies on the product page too; I just had the API key page hanging around.
