### ISSUE TITLE
Bug: Meal plan shows calories per number of base servings and not per serving as stated

### ISSUE THREAD

**Issue by organismen** [grocy/grocy#1359]
**EDIT by @berrnd:
TODO for this issue:**
Show the kcal on the recipe page and the meal plan always per 1 serving.

---

I've noticed that "kcal per servings" are not showing correct in the meal plan "recipe card", it always displays calories per number of base servings from recipe. This would not affect demo data in demo environment since all the recipes have 1 as base servings. its easy to produce this error in the demo environment just by doubling the base servings for one recipe as shown below. Screenshots are taken from prelease out of `Version pre-release-3d82c9a`

![image](https://user-images.githubusercontent.com/3727297/108527819-06a3dc00-72d3-11eb-8f63-bfb221fb3a7b.png)

Meal plan shows 984 kcal per servings. Should in this case be 492 since we are only planing to make 1 serving

![image](https://user-images.githubusercontent.com/3727297/108527908-20ddba00-72d3-11eb-82b5-f9164641ae65.png)

Recipe shows 984 kcal for 2 desired servings which is correct. (I think it would be more useful to show kcal per 1 serving here as well but that's besides the point in this ticket)

![image](https://user-images.githubusercontent.com/3727297/108528306-921d6d00-72d3-11eb-9f6e-20d287db448e.png)

Recipe shows 492 kcal for 1 desired servings which is correct

**Comment by berrnd** [comment]
The problem is most probably that the meal plan uses the "desired servings" (from the recipe page) instead of the recipes base serving amount to get the calories...

**Comment by organismen** [comment]
That seams correct, what is the technical difference between desired servings and "meal plan servings"?

**Comment by berrnd** [comment]
> what is the technical difference between desired servings and "meal plan servings"?

Desired servings = the amount of servings you choose on the recipe page to calculate the ingredients/kcal/etc. accordingly.
Meal plan servings = the amount of servings of the recipe you have added to the meal plan on a specific day.

**Comment by organismen** [comment]
> The problem is most probably that the meal plan uses the "desired servings" (from the recipe page) instead of the recipes base serving amount to get the calories...

Recipe base serving isn't probably what we want since most recipes has a base of four or so.

Shouldn't it be kcals per one serving? I guess most people want to know how much energy per person and not energy per family?

**Comment by berrnd** [comment]
Yes, maybe it would be best to display always (recipe page + meal plan) the kcal per 1 serving - let's change that.
