### ISSUE TITLE
Feature request: Add product description to stock overview

### ISSUE THREAD

**Issue by Saturo78** [grocy/grocy#1362]
In stockoverview the searchfunction should also include the field product description.

**Comment by berrnd** [comment]
The search function simply searches the table, the same on all pages, so the only way would be to add the product description as a column, this is a multiline field, so I doubt this really looks good add the end - but of course is possible.

**Comment by berrnd** [comment]
The product description is now added as (hidden by default) column on the stock overview page.

Also without displaying the column, the general search field searches hidden columns (so maybe like you would have expected it; same behaviour like on all pages).
