### ISSUE TITLE
Feature request: create product hide descriptionp

### ISSUE THREAD

**Issue by Saturo78** [grocy/grocy#1363]
The description field in the create product page takes much space on mobile devises.
I don´t need it all the time and would have the possibility to hide it.

**Comment by berrnd** [comment]
Please consider using [custom JS/CSS](https://github.com/grocy/grocy#adding-your-own-css-or-js-without-to-have-to-modify-the-application-itself) for such individual customizations, adding an option for every little detail someone wants is really not the way to go...

Here is a snippet for `data/custom_css.html` to hide the description field on the product edit page on mobile:
```html
<style>
@media (max-width: 576px) {
	#product-form label[for="description"],
	#product-form .note-editor {
		display: none !important;
	}
}
</style>

```
