### ISSUE TITLE
Feature request: standard consumption location

### ISSUE THREAD

**Issue by Saturo78** [grocy/grocy#1365]
Purchased Milk goes to the pantry. One pack gets transfered the the fridge and there it will be consumed.
It would be nice if i could specify a consumption location the same way a the standard storage location.

**Comment by berrnd** [comment]
This is now done, there is this new optional product option for that:

![grafik](https://user-images.githubusercontent.com/2161815/161444172-7a300407-d6c7-4358-8d5d-c1d0cc2bd320.png)

Long explanation - changelog excerpt:

> - New product option "Default consume location" (not mandatory, defaults to not set / empty)
>     - When set, stock entries at that location will be consumed first
>     - => This will be automatically taken into account when consuming from the stock overview page and all other places where no specific location can be selected
>     - => On the consume page the location is preselected in the following order:
>         - 1. The new default consume location, if the product currently has any stock there, otherwise
>         - 2. The products default location, if the product currently has any stock there, otherwise
 >        - 3. The first location where the product currently has any stock

**Comment by berrnd** [comment]
Cross referencing [#830](https://github.com/grocy/grocy/issues/830#issuecomment-1101549050) here - stock entries can now also be automatically moved to the products default consume location on opening them:

> - New product option "Move on open" (defaults to disabled)
>    - When enabled, on marking the product as opened, the corresponding amount will be moved to the products default consume location
