### ISSUE TITLE
Bug:  A barcode can be assigned to multiple products

### ISSUE THREAD

**Issue by sleeplessnight2** [grocy/grocy#1369]
I don't know if this is intentional, but I doubt it and that's why I'm reporting it.

As the title says, a barcode can be assigned to several products.

steps to reproduce it:
Create 2 products and add for example 1234 as barcode.

What is expected:
When assigning a barcode that is already used, a corresponding error message should come and of course not be entered in the db.

For my information: Does such a check already exist? If yes, in which lines can it be found?

**Comment by berrnd** [comment]
There is and will be no check for that.

Hence it makes not so much sense to assign the same barcode to more than one product, barcodes are not world wide unique.

**Comment by sleeplessnight2** [comment]
Völlig falscher Ansatz. In einem Lagersystem sind Barcodes unique. Das ist Fakt. Und überall üblich. Und ein muss.
Ich möchte das Gesicht der Kunden an der Kasse sehen, wenn man bei Aldi für eine Zahnpasta 20€ bezahlen soll, weil der Barcode ebenfalls der Apple-Store Karte zugeordnet ist.

Aber ja, sie sind nicht weltweit einzigartig. Ich hab bei Aldi noch nie eine Zahnpasta aus Indien kaufen können... (die zufällig weise den gleichen Barcode trägt). 
Und selbst wenn es so wäre und die Indische Zahnpaste denselben Barcode tragen würde -  Aldi würde dann dem Hersteller die  Vorgabe machen, den Barcode entsprechend anzupassen.

Also nein: Der erwähnte  Grund wird bei niemanden der Fall sein. Niemals. 
Wie kommt man überhaupt darauf, in einem Lagersystem alle jemals existierenden Barcodes zu verwalten, so dass dieser Gedanke valide wäre?

Ernüchternd ist es, das solch eine Grundfunktion aufgrund solches falsches Denken nicht zu diesem Lagersystem gehört(e) oder gehören soll.

BTW:
Ich hab gestern überlegt, ob ich das hier einstelle, damit da vielleicht mehrere von Profitieren oder ob ich mich gleich (weiter) ans Revers Engineering mache. Ich hätte es lassen sollen. Wie schon weitere x-male zuvor und hab dadurch eine menge Zeit erspart.

**Comment by berrnd** [comment]
Ich weiß doch inzwischen, dass ich ein Idiot bin, überhaupt keine Ahnung von irgendwas habe, grundsätzlich alles falsch mache und grocy einfach von vorne bis ins letzte Detail hinten ein einziger Haufen Müll ist.

Mich wundert es von daher vor allem, dass du dich immer noch damit beschäftigst und nicht schon längst dein eigens Projekt gestartet hast, dass einfach alles richtig macht.
