### ISSUE TITLE
404 New Install

### ISSUE THREAD

**Issue by kwilliams147** [grocy/grocy#137]
SQLite 3.22.0 PHP 7.2.10

Getting 404 Not Found when trying to load the main page. I have my apache config set to the public folder as the root and when I hit the IP I get redirected to IP/stockoverview which is a 404 Not Found. I have no errors in my apache logs.

**Comment by berrnd** [comment]
Maybe URL rewriting is not enabled try `http(s)://<ip>/index.php/stockoverview`, URL rewriting can be disabled also in `config.php` (setting `DISABLE_URL_REWRITING`).

**Comment by berrnd** [comment]
Maybe just `a2enmod rewrite` and then restarting Apache, the rewrite conditions are already there in the `.htaccess` file in the `public` directory...

**Comment by kwilliams147** [comment]
I had to enable `a2enmod rewrite` aswell as add `AllowOverride All` to my apache config in the directory block. Thank you for your help.
