### ISSUE TITLE
Feature request: Idea for partial consumption

### ISSUE THREAD

**Issue by funnym0nk3y** [grocy/grocy#1375]
This is just a issue to put the idea into the system. 

There are a lot of things that get used up by fractions e.g. milk, cereals, etc.

Instead of having to guess how much was consumed a scale could be connected. In combination with a barcode scanner the workflow could be as follows:
When buying groceries (stock mode), scan the item and put it on the scale. It gets registered with weight and amount. 
In consume mode, scan the item and put it on the scale. This value gets saved as well. 
If the product is empty, scan it, put it in the scale and choose an option like empty container. Now the rough weight of that empty container gets stored and all values could be corrected by that oder converted to percentages. 
For the next new full product you stock partial consumption can be calculated more accurately.

**Comment by berrnd** [comment]
grocy can already handle products in containers (means you, or here the scale, enters/scans the "gross" weight on purchase/consume (including the container). The amount to be posted is then automatically calculated.

Check the product option "Tare weight handling" ([demo](https://demo.grocy.info) product for that is "Flour"):
![grafik](https://user-images.githubusercontent.com/2161815/108636084-60e39f00-7483-11eb-8a72-451e3089d344.png)

![grafik](https://user-images.githubusercontent.com/2161815/108636108-87a1d580-7483-11eb-9f72-0f4a1ae7495a.png)

**Comment by berrnd** [comment]
And if I remember correctly, somebody already build something about a "scale integration" - cannot find were this was, maybe here or on the [subreddit](https://www.reddit.com/r/grocy/) (which is also the better place to discuss such integrations).
