### ISSUE TITLE
Feature request: Flag delete product after consumption

### ISSUE THREAD

**Issue by Saturo78** [grocy/grocy#1377]
I have a lot of one shot products. It would be good if i could set a flag in the product masterdata that the product should be deleted automaticly when the amount is consumed.

**Comment by berrnd** [comment]
What's a practical example for this?

Maybe any item only tracked once is not worth to be a own product, but more a generic one...

**Comment by Saturo78** [comment]
The main use case are presents i get, mostly from family members.
I want to store them with the exact name but will probably not buy them anymore.

**Comment by Ape** [comment]
Could this be solved by marking the product "not active" while there is still some in the stock. It could be still shown in the stock listing while there are units left, but it could be immediately removed from the product list that is used for adding items to shopping lists etc.

**Comment by Saturo78** [comment]
This could work. Also it would be sufficient to set the not active flag when the amount is consumed.
I could regulary check the "not active" products and delete those i don´t need anymore.

**Comment by 13hannes11** [comment]
By now can this not be solved by using Notes?
