### ISSUE TITLE
Userfields (Mahlzeit, Kategorie) in receipts are not saved at first klick on Safe & return to recipes

### ISSUE THREAD

**Issue by witzker** [grocy/grocy#1378]
When I have saved a recipe and then from recipe view press Add
The Userfields ( Mahlzeit & Kategorie) are prefilled ( which is good and useful)
I have only to fill in the name & preparation

![image](https://user-images.githubusercontent.com/4120266/108725815-10be1880-7527-11eb-819b-0431708a7778.png)

When I press Save & return to recipes

![image](https://user-images.githubusercontent.com/4120266/108726039-46630180-7527-11eb-9c3f-da83338c06ce.png)

The Userfields (Mahlzeit, Kategorie) are not saved!
When I open It again the fields are empty and has to be set again.

Only then the fields will stay saved!

When I have saved the recipe and then from recipe view press Add
the same behaviour start again as described ……..
What’s wrong?

**Comment by berrnd** [comment]
The same problem as #1302.

This will be merged into #1302.
