### ISSUE TITLE
Bug: Add a new product with Picture problem

### ISSUE THREAD

**Issue by witzker** [grocy/grocy#1379]
When I go to 
Manage Masterdata -> Products -> ADD

There is no possibility like in former version to add a Product Picture
![image](https://user-images.githubusercontent.com/4120266/108766182-1b8fa200-7555-11eb-931f-60157a532746.png)

When I save the product without a Picture an afterwards go to edit product

A window to add product Picture is displayed on the right side of the product details

![image](https://user-images.githubusercontent.com/4120266/108766233-2ea27200-7555-11eb-9d55-bbbc10279095.png)

When I click Save & continue
![image](https://user-images.githubusercontent.com/4120266/108766319-4b3eaa00-7555-11eb-8e6b-febcb5ca5c28.png)

This error pops up
![image](https://user-images.githubusercontent.com/4120266/108766361-5abdf300-7555-11eb-92a6-bbaacecadd5c.png)

`Errorcode:
"{\"error_message\":\"Method not allowed. Must be one of: OPTIONS\",\"error_details\":{\"stack_trace\":\"#0 \\/volume1\\/web\\/Grocy\\/vendor\\/slim\\/slim\\/Slim\\/Middleware\\/RoutingMiddleware.php(58): Slim\\\\Middleware\\\\RoutingMiddleware->performRouting(Object(Slim\\\\Http\\\\ServerRequest))\\n#1 \\/volume1\\/web\\/Grocy\\/vendor\\/slim\\/slim\\/Slim\\/MiddlewareDispatcher.php(147): Slim\\\\Middleware\\\\RoutingMiddleware->process(Object(Slim\\\\Http\\\\ServerRequest), Object(class@anonymous))\\n#2 \\/volume1\\/web\\/Grocy\\/vendor\\/slim\\/slim\\/Slim\\/Middleware\\/ErrorMiddleware.php(107): class@anonymous->handle(Object(Slim\\\\Http\\\\ServerRequest))\\n#3 \\/volume1\\/web\\/Grocy\\/vendor\\/slim\\/slim\\/Slim\\/MiddlewareDispatcher.php(147): Slim\\\\Middleware\\\\ErrorMiddleware->process(Object(Slim\\\\Http\\\\ServerRequest), Object(class@anonymous))\\n#4 \\/volume1\\/web\\/Grocy\\/middleware\\/CorsMiddleware.php(30): class@anonymous->handle(Object(Slim\\\\Http\\\\ServerRequest))\\n#5 \\/volume1\\/web\\/Grocy\\/vendor\\/slim\\/slim\\/Slim\\/MiddlewareDispatcher.php(313): Grocy\\\\Middleware\\\\CorsMiddleware->__invoke(Object(Slim\\\\Http\\\\ServerRequest), Object(class@anonymous))\\n#6 \\/volume1\\/web\\/Grocy\\/vendor\\/slim\\/slim\\/Slim\\/MiddlewareDispatcher.php(81): class@anonymous->handle(Object(Slim\\\\Http\\\\ServerRequest))\\n#7 \\/volume1\\/web\\/Grocy\\/vendor\\/slim\\/slim\\/Slim\\/App.php(215): Slim\\\\MiddlewareDispatcher->handle(Object(Slim\\\\Http\\\\ServerRequest))\\n#8 \\/volume1\\/web\\/Grocy\\/vendor\\/slim\\/slim\\/Slim\\/App.php(199): Slim\\\\App->handle(Object(Slim\\\\Http\\\\ServerRequest))\\n#9 \\/volume1\\/web\\/Grocy\\/app.php(94): Slim\\\\App->run()\\n#10 \\/volume1\\/web\\/Grocy\\/public\\/index.php(45): require_once('\\/volume1\\/web\\/Gr...')\\n#11 {main}\",\"file\":\"\\/volume1\\/web\\/Grocy\\/vendor\\/slim\\/slim\\/Slim\\/Middleware\\/RoutingMiddleware.php\",\"line\":94}}"
`
What’s wrong?

**Comment by berrnd** [comment]
Please try to reproduce problems on the demo instance first, like also mentioned on the issue template - if it works there and not on your installation, it's most probably not a bug.

> There is no possibility like in former version to add a Product Picture

That's intentional, everything on the right side of the product edit page is only available after once saving a new product.

I tried to upload pictures on the demo just now, everything works - and sorry, can't say from the error message what's wrong on your side. Please use the [subreddit](https://www.reddit.com/r/grocy/) for generic help requests like [mentioned in README](https://github.com/grocy/grocy#questions--help--bug-reporting--feature-requests).

**Comment by witzker** [comment]
@ That's intentional, everything on the right side of the product edit page is only available after once saving a new product.

But that's very uncomfortable! Why to open a product 2 times for adding a picture??

The error says 
![image](https://user-images.githubusercontent.com/4120266/108771373-dd49b100-755b-11eb-9b36-35eed5a9d462.png)

Product exists?  Yes sure! I'm editing an existing Product!

PLS THINK about in giving back the possibility to ADD a product in 1 Step 
Not That complicated - I want to use the Program productive not to play around with it!

What do you think?

**Comment by berrnd** [comment]
> Why to open a product 2 times for adding a picture??

It's not about the picture particularly, it's the same for any dependent object and therefore behaves the same for barcodes and QU conversion overrides (and default QU conversions and recipe ingredients/pictures/included recipes). A technical thing (the id of the parent object need to be known for any dependent object, but that id is only created after a product was once saved).

The error is most probably unrelated to an existing/duplicate product, needs more investigation (use the browser developer tools for example to check what requests to the API are made / which fail). It works, you can verify that by testing this on the demo instance, so this is not a bug and this not the right place to discuss this further - as both mentioned before. If you have a reproducible way to get this error, feel free to report that and I'm happy to fix it.

**Comment by berrnd** [comment]
Just to note that also here:

Being able to add pictures directly on product creation was now done via #1620 (still not a bug).
