### ISSUE TITLE
Bug: Product picture upload with Umlaute in file name not working

### ISSUE THREAD

**Issue by witzker** [grocy/grocy#1382]
Pls reopen this issue again It has to be discussed.
I notice when there is no Ü in the picture name there is no error !!

**Comment by berrnd** [comment]
Please follow what is mentioned in the issue template for reporting bugs.

I mentioned in #1379 that adding pictures is the same like for any dependent objects and currently there is a kind of technical limitation to do this in one go. This is clearly not a bug, if then an enhancement request. Feel free to add one for that or simply implement it yourself.

**Comment by berrnd** [comment]
>  I notice when there is no Ü in the picture name there is no error !!

Is reproducible, will be tracked here.

**Comment by berrnd** [comment]
Turns out that this only happens when grocy is hosted on Linux, but the file upload (client) happens from Windows.

Tried to figured it out, didn't find the root cause, but applied a workaround (Umlaute will be stripped off the file name before uploading).
