### ISSUE TITLE
Bug: Checkbox not clickable

### ISSUE THREAD

**Issue by wrybind** [grocy/grocy#1383]
When adding missing products for a recipe to the shopping list, there is a list displayed where you can uncheck ingredients. 
 
Problem: You cannot uncheck a checkbox by clicking on it. You need to click anywhere in the ingredient field except the checkbox to get a reaction. Especially on mobile this is confusing.

**Comment by ORippler** [comment]
Does deselecting actually prevent the items from being added to the shopping list? At least for me it does not (3.0.1). Also tested on the demo server

**Comment by berrnd** [comment]
> Does deselecting actually prevent the items from being added to the shopping list? At least for me it does not (3.0.1). Also tested on the demo server

Not the topic of this issue, moved to #1407.
