### ISSUE TITLE
Bug: Transfer not possible when "use a specific stock item"

### ISSUE THREAD

**Issue by Saturo78** [grocy/grocy#1386]
Demo

Transfer
Milk
use a specific stock item

The okay button is grayed out.

**Comment by berrnd** [comment]
Needs (again) more exact steps to reproduce this, works here:

https://user-images.githubusercontent.com/2161815/109187504-431f7e00-7792-11eb-923a-74960111b53c.mp4

**Comment by Saturo78** [comment]
Seems to be an issue with an outdated edge browser on my second test computer. Sorry for any inconvenience!
