### ISSUE TITLE
Feature request: Inventory per location

### ISSUE THREAD

**Issue by Saturo78** [grocy/grocy#1387]
I would like to limit the inventory taking to one location.
Example 1 x milk in the fridge 4 x milk in the cellar. When I enter the stock in the fridge, I want to enter 1 x milk because thats the correct amount in the fridge.

It would also be important that it is possible to enter the correct amount. The purpose of the inventory is to record the available quantity. In this case no correction is necessary.

**Comment by berrnd** [comment]
So a "desired stock" option per product per location and if this is not met a notification or something? And what should happen when you try the purchase Milk, there is already 1 in the fridge - also a notification, or disallow it?

(Pretty much everything is technically possible, but some things sound a little bit like fridge over engineering to me... ;D)

**Comment by Saturo78** [comment]
Not sure if i explained it rigth. I refer to the menu entry inventory. (Inventur)
Nothing to do with desired stocks idea.

1 in Location 
Inventory 1 -okay
Inventory 2 correction +1 in location
Inventdry 0 correction -1 in location
Stocks in other locations are not relevant.

**Comment by Saturo78** [comment]
Nice side effect of this: when it is possible to enter the correct amount via "Inventory" it can be also used to assign a barcode to a product.

**Comment by Saturo78** [comment]
Thinking about this i came to the result that allowing to invent a single stock entriy maybe would be the best solution.

**Comment by berrnd** [comment]
Merged into #1988.
