### ISSUE TITLE
Feature request: Masterdata Filter Product on stock

### ISSUE THREAD

**Issue by Saturo78** [grocy/grocy#1388]
It would be very nice if the could be implemented a filter to see in product masterdata if a product is on stock.
This could prevent deleting a product which is still on stock.

**Comment by Saturo78** [comment]
My scope would be delete products which have no transactions, are not on stock and are not used in recipes.

Maybe there should better be a check of these three criterias?

**Comment by berrnd** [comment]
I would personally never delete once used products (needed for example for things like my personal biggest feature request #64) and also don't see the benefit. That's also why the "Active" checkbox was added to hide products not longer needed while not deleting them.

**Comment by Saturo78** [comment]
I totaly agree with you. But especially in the beginning time with grocy theres goes something wrong and some decisions are revised.
The activate checkbox is okay for me.
I hope the garbage products don´t need to much storage. ;o)

Am 2. März 2021 08:56:59 MEZ schrieb Bernd Bestel <notifications@github.com>:
