### ISSUE TITLE
API - A bit more RESTful

### ISSUE THREAD

**Issue by MrTarantula** [grocy/grocy#139]
GET requests should not be able to modify or delete data. The correct verb should be used, according to [this article](https://restfulapi.net/idempotent-rest-apis/). Additionally, some routes can be made more RESTful. For example the Stock API can have a starting point for a product of `/api/stock/{productId}` and each function can be its own route. On the left are original routes and on the right are the RESTful routes:

```
GET /api/stock/add-product/{productId}/{amount} => POST/PUT /api/stock/{productId}/add
GET /api/stock/consume-product/{productId}/{amount} => POST/PUT /api/stock/{productId}/consume
GET /api/stock/open-product/{productId}/{amount} => POST/PUT /api/stock/{productId}/open
GET /api/stock/inventory-product/{productId}/{newAmount} => POST /api/stock/{productId}/inventory
GET /api/stock/get-product-details/{productId} => GET /api/stock{productId}/details OR /stock/{productId}
GET /api/stock/get-product-price-history/{productId} => GET /api/stock/{productId}/pricehistory
GET /api/stock/get-product-stock-entries/{productId} => GET /api/stock/{productId}/entries
```

I can come up with a complete list from the routes file. I could potentially make the required changes to the code to go from GET to POST but it might take me longer, as my PHP is a bit rusty.

**Comment by berrnd** [comment]
Sounds good, and yes - the only place where I "followed the rules" was the `/api/file` group, however...

Feel free to provide the complete list, the API is used in various places in [/public/viewjs](https://github.com/grocy/grocy/tree/master/public/viewjs), so this needs also to be changed. And we need to increase the major version after that, or leave the old routes (maybe with redirects) to not confuse someone who is maybe already using the API for something...

**Comment by berrnd** [comment]
I kind of completed this now - the Swagger UI now also reflects the current state, you can have a look at the already updated pre-release demo:
=> https://demo-prerelease.grocy.info/api

I also did some additional changes, e. g. grouped all stock-product-routes together under `/stock/products` and changed the response code to 204 when there is no response body.

I'm still unsure about some things:
- Use plural or singular for naming routes which return a single object - `/users/{userId}` vs. `/user/{userId}`
  - Currently the plural form is more used, so the `/file` routes should probably be changed too
- Is it good to have `/chores/{choreId}/execute` and `/chores/{executionId}/undo` - same scheme, but in the former the id is a chore id and in the later it is an id of an execution - maybe change the later to `/chores/executions/{executionId}/undo`?

It would be great and help a lot if you can also play around a bit in the pre-release demo if I covered everything in the frontend JS - there were a lot of places to change...

Let me know what you think. :)

//CC @gen2fish

**Comment by MrTarantula** [comment]
I'll take a look soon and mess with the API. For your questions:

1. I consider plural as the right way, but I know there are differing opinions.
2. I think it is ambiguous having both executionId and choreId following `chores/`. `chores/executions/{executionId}/...` makes more sense. I would also consider adding the route `chores/{choreId}/executions/{executionId}/...`. That's only a personal preference and the other route can be left in as well.

**Comment by berrnd** [comment]
I think I'll close this for now, feel free to open another issue if there is anything else which can be improved...

And thanks again! :)
