### ISSUE TITLE
Bug: Meal plan recipe servings not used for stock fulfillment checking

### ISSUE THREAD

**Issue by liffez** [grocy/grocy#1391]
When adding a recipe to the meal plan the servings specified are not pushed down to recipe servings.
This means that the stock counts (Requirements fulfilled ) for the meal plan will be wrong at the first glance and if you use the mealplan to update the inventory then the update will be wrong as well.
The same happens if you change the number of servings in a Meal plan 
But if you press on the “view recipe” (the eye) and then update the browser, the servings will be updated and the inventory count will be right

**Comment by berrnd** [comment]
Related to #1359.

For fulfillment checking of a recipe added to the meal plan nothing of the recipe (desired servings) should be changed. That's only needed for viewing the recipe (the mentioned eye icon on the meal plan page).

**Comment by liffez** [comment]
ok i see, then the new title describes the issue better. Thanks for your quick reply
