### ISSUE TITLE
Feature request: Purchase/ Inventory - set "Never Overdue" as pre selected

### ISSUE THREAD

**Issue by horphi0815** [grocy/grocy#1392]
Hi,

It would be very nice, to create a option as pre set, that the CheckBox "Never Overdue" can be already pre selected.

Best regards,

Phil

**Comment by berrnd** [comment]
Already possible, check the product option "Default due days":

![grafik](https://user-images.githubusercontent.com/2161815/109557477-75094b00-7ad8-11eb-8d0f-cd89f0399a6c.png)

**Comment by horphi0815** [comment]
Damned, thats perfect!!!
