### ISSUE TITLE
Feature request: Stockoverview table options extension

### ISSUE THREAD

**Issue by horphi0815** [grocy/grocy#1393]
Hello togehter,

it would be great, to get the default location visualized on stockoverview.

![grafik](https://user-images.githubusercontent.com/39962016/109562683-febc1700-7ade-11eb-9a91-6650fd9f1558.png)

Best regards,

Phil

**Comment by berrnd** [comment]
Duplicate of #1351 - please check existing requests before opening new ones.

**Comment by berrnd** [comment]
> please check existing requests before opening new ones

Even more important when it's your own request... ;D

**Comment by horphi0815** [comment]
embarrassing.....please ignore me in  the future... :-P
