### ISSUE TITLE
Group of items as meal 

### ISSUE THREAD

**Issue by deliantwo** [grocy/grocy#1394]
I've add some recipes to grocy but, sometimes, my meal can be some "simple" food like smoked salmon, cheese and bread.
I find not practical to add it as a recipe but i find useful to "mark" that I will eat those items that day, considering, for example, they will expire soon.
The idea is to add a "meal" as a mere composition of items (think of it as an "anonymous recipe", translating it from a programming context), with the "consume" option.

**Comment by berrnd** [comment]
- Recipes can contain other recipes
- Products can be directly added to the meal plan

The aformentioned is already possible, so you probably mean that single products should be possible to be grouped together on the meal plan. However, creating a recipe of salmon/cheese/bread is most probably not really different than creating a group for them at the end (with the difference that you always need to pick the 3 products again vs picking single recipe).

**Comment by deliantwo** [comment]
Even if is an adding of one product, without grouping, I did completely miss that feature, my bad.
In addition, the #370 with the "newly discovered feature of adding a product to the meal plan" will probably solve my need.
Thank you again for pointing it out and shame on me for missing it :smile:
