### ISSUE TITLE
Bug: Location filter on stock overview: Contains search instead of exact match

### ISSUE THREAD

**Issue by Saturo78** [grocy/grocy#1399]
When setting up the location structure like this:

Kitchen
Kitchen\Shelf 1
Kitchen\Shelf 2
...

Filtering  to location Kitchen shows also  entrys in Kitchen\Shelf 1 and 2.
I think it shows everything begining with Kitchen.
Renaming Kitchen to Kitchen\General 
solves the issue.

Don´t know if this is bug or a feature.

**Comment by berrnd** [comment]
Seems to work in the meantime, don't know by which commit it got fixed...
