### ISSUE TITLE
Tables: Custom sorting for grouped column

### ISSUE THREAD

**Issue by Saturo78** [grocy/grocy#1402]
When grouped last purchased in stock overview sorting is always oldest entrys first.
It´s not possible to change the sort order via the column last purchased.

![grafik](https://user-images.githubusercontent.com/71584438/110463786-a5517a80-80d2-11eb-966d-95533751955d.png)

![grafik](https://user-images.githubusercontent.com/71584438/110463934-cd40de00-80d2-11eb-987e-ea64054ab800.png)

**Comment by berrnd** [comment]
I found no side effects and therefore just removed the restriction that grouped columns have a fixed order.

**Comment by berrnd** [comment]
> I found no side effects

I was wrong, this causes duplicate groups.
Ref: https://github.com/grocy/grocy/issues/1534#issuecomment-892766487
