### ISSUE TITLE
Bug: This page does not exist after installing.

### ISSUE THREAD

**Issue by p00rt** [grocy/grocy#1404]
grocy version: latest (3.0.1)
apache2 version 2.4.38
php version 7.4
debian 10

I've been trying to install grocy on a VPS. I unpacked it, changed the permissions and edited the config.php. This is what I'm getting:
![2021-03-11-125537_1364x767_scrot](https://user-images.githubusercontent.com/10347432/110783817-35292d00-8269-11eb-806f-fdfcf0025d29.png)

 I created 2 configs for apache:
```
<VirtualHost *:80>
	ServerName	my.tld
	RewriteEngine on
	RewriteCond %{SERVER_NAME} =*.my.tld [OR]
	RewriteCond %{SERVER_NAME} =my.tld
	RewriteRule ^ https://%{SERVER_NAME}%{REQUEST_URI} [END,NE,R=permanent]

	LogLevel warn 
	ErrorLog ${APACHE_LOG_DIR}/grocy-error.log
	CustomLog ${APACHE_LOG_DIR}/grocy-access.log combined
</VirtualHost>
```
```

<VirtualHost *:443>
	ServerName my.tld

	DocumentRoot /var/www/my.tld/public
	
	<Directory /var/www/grocy/public>
		Options Indexes FollowSymLinks MultiViews
		AllowOverride All
		Order allow,deny
		allow from all
	</Directory>

	LogLevel warn ssl:warn
	ErrorLog /var/log/apache2/grocy-error.log
	CustomLog /var/log/apache2/grocy-custom.log combined

	Include /etc/letsencrypt/options-ssl-apache.conf
	SSLCertificateFile /etc/letsencrypt/live/my.tld/fullchain.pem
	SSLCertificateKeyFile /etc/letsencrypt/live/my.tld/privkey.pem
</VirtualHost>

```
And here are the important parts from config:
```
 Setting('BASE_PATH', '/index.php');
Setting('BASE_URL', '/');
Setting('DISABLE_URL_REWRITING', false);
```

**Comment by berrnd** [comment]
This here is the issue tracker, this is more than obviously not a bug - please use the [subreddit](https://www.reddit.com/r/grocy/) for general questions/help as also [mentioned in README](https://github.com/grocy/grocy#questions--help--bug-reporting--feature-requests) and on the issue template.

Most probably a problem about `BASE_PATH` - there are a lot of things about that here and on the subreddit.
