### ISSUE TITLE
Clarify shopping list group by print option

### ISSUE THREAD

**Issue by Saturo78** [grocy/grocy#1405]
Settings:

![image](https://user-images.githubusercontent.com/71584438/110936173-c2838480-8330-11eb-921b-f27f383aaae3.png)

Result:
![image](https://user-images.githubusercontent.com/71584438/110936223-d6c78180-8330-11eb-9c19-c79055e18510.png)

Would expect something like this, with headlines
![image](https://user-images.githubusercontent.com/71584438/110936267-e8a92480-8330-11eb-9382-0cc7a1c3c571.png)

Funny thing, in this case everything is listed twice with this setting:
![image](https://user-images.githubusercontent.com/71584438/110936874-d4b1f280-8331-11eb-9272-6cd195cef1fb.png)

**Comment by berrnd** [comment]
"Group by" only works with layout type "Table" - can be of course clarified that this is the case..
