### ISSUE TITLE
Feature Request: Calendar Export

### ISSUE THREAD

**Issue by piersonjarvis** [grocy/grocy#141]
I was wondering if there was a way to export the calendar via iCalc or the like, that way you could attach it to your everyday calendar to know when you need to go shopping.

**Comment by berrnd** [comment]
This is now done. :)

The current calendar is export as-is in iCal format - new button in the header on the calendar page - hard work done by [eluceo/ical](https://github.com/markuspoerschke/iCal).

The iCal file is always the current calendar, not a snapshot of the time of link creation and the link is also served without authentication (I think this is needed to use it in any software/app - done with a special new API key type, can also be revoked in "Manage API keys" and the key cannot be used for anything else).

Check the already updated [pre-release demo](https://demo-prerelease.grocy.info/calendar) to play around with it, if you want.

**Comment by piersonjarvis** [comment]
I’m sorry but I do not see an option for an iCal in the calendar tab.

**Comment by berrnd** [comment]
![firefox_2019-03-04_19-56-13](https://user-images.githubusercontent.com/2161815/53755775-aafaa100-3eb7-11e9-9037-069a66fbd368.png)

:)

**Comment by piersonjarvis** [comment]
This is what I see, I’m running 1.24.1 through docker.

**Comment by berrnd** [comment]
It's not yet part of a release, that's what I meant with **pre-release** demo...

So currently only available there or when your install directly from master branch (not recommended)...
https://demo-prerelease.grocy.info/calendar

Just wanted to test out if this is what you thought of...

**Comment by piersonjarvis** [comment]
Oh My mistake I missed that part! Yes that is exactly what I was thinking of!
