### ISSUE TITLE
Translations: french translations problems

### ISSUE THREAD

**Issue by AngeloFrangione** [grocy/grocy#1410]
Hi, I'm french and use grocy in french, and there is a translations that i don't really agree with, the units one is translated to 'formats' but the real translation would be 'unités' you can see on [wordreference the translations](https://www.wordreference.com/enfr/unit)

If you want to add me on the transifex team I'm glad to help !

**Comment by berrnd** [comment]
Everyone can translate everything on Transifex: https://www.transifex.com/grocy/grocy

No invitation or approval from my side is necessary.
