### ISSUE TITLE
Bug: Nginx+Grocy new docker install error 502 after login

### ISSUE THREAD

**Issue by stefanorossiti** [grocy/grocy#1411]
I installed the grocy image gromlinuxserver.io
i use all container without ssl because there is an nginx reverse proxy, it works for all the services i have. 

But grocy is failing with both: 
 - my domain name with nginx through https 
 - local ip with http
the service itself works because i reach the login page, it seems its going through the login and the url goes to /stockoverview but it prints a blank page with the 502 Bad Gateway error. 
The container logs shows nothing, it remain at the [services.d] done. line showing no errors

**Comment by berrnd** [comment]
This here is the issue tracker, this is more than obviously not a bug of grocy itself, nor the repo of the Docker image you mentioned to use.

So please use the [subreddit](https://www.reddit.com/r/grocy/) for general help (also [mentioned in README](https://github.com/grocy/grocy#questions--help--bug-reporting--feature-requests)) or the issue tracker of the corresponding repo ([linuxserver/docker-grocy](https://github.com/linuxserver/docker-grocy)).
