### ISSUE TITLE
More setting

### ISSUE THREAD

**Issue by undergroundoyo** [grocy/grocy#1414]
Hello,

I think it would be interesting (when we add product in the database for products such the flour, the sugar or more) to be able to specify the kg/m3. Thanks to that when we creat a recipe with a an ingredient list we will be able to define a weight unit or volume unit define in the format list. And if a volume unit was chosen from the ingredients list, the software could be count the weight used in the stocks.

**Comment by berrnd** [comment]
Already answered in https://github.com/grocy/grocy/issues/1413#issuecomment-798956444, have a look at (product specific) quantity unit conversions.

No need for double posting your requests.
And the better place for general questions/help is the [subreddit](https://www.reddit.com/r/grocy/) like also [mentioned in README](https://github.com/grocy/grocy#questions--help--bug-reporting--feature-requests).
