### ISSUE TITLE
Fatal error: Uncaught TypeError: count(): Argument #1 ($var) must be of type Countable|array, null given in C

### ISSUE THREAD

**Issue by Asgwani** [grocy/grocy#1417]
Please describe the bug as detailed as possible, provide the steps how to reproduce it and maybe attach screenshots where useful.

Please also check if your bug was maybe already fixed by searching closed issues here or by trying to reproduce your problem on the [pre-release demo](https://demo-prerelease.grocy.info/) (use a *private demo instance* if you want to make your example persistent).

**Comment by berrnd** [comment]
This is the issue tracker, so for (reproducible) bugs - please use the [subreddit](https://www.reddit.com/r/grocy) for general help as also [mentioned in README](https://github.com/grocy/grocy#questions--help--bug-reporting--feature-requests).

In any case, please provide more information (webserver logs, browser console output, environment information, etc.) if you want to get help - I really have no clue how to help if you just throw a random part of a random error message in the headline of an issue...
