### ISSUE TITLE
Bug: Stock entries goup by purchase date

### ISSUE THREAD

**Issue by Saturo78** [grocy/grocy#1419]
Grouping stock entries by purchase date did not work:

![grafik](https://user-images.githubusercontent.com/71584438/111830565-787d3e80-88ee-11eb-8818-cfe36489e283.png)

Demo Instance:
https://test-tbzh9z4bu5ryt2iz3pke.demo.grocy.info/stockentries

**Comment by berrnd** [comment]
Same as #1274.
