### ISSUE TITLE
Feature request: allow changing the sqlite file location to ease app dockerization

### ISSUE THREAD

**Issue by mathieupotier** [grocy/grocy#1422]
In order to allow DB persistence in a docker environment, it would be great to allow to override the sqlite file location.
For the moment, it's under the `./data` directory, next to `config.php`, it's not easy to mount a volume only for this file.

I suggest such a change in the data directory structure in order to ease the persistance with docker.
```
/data
  -> config.php
  -> db/grocy.db
  -> storage/
```

In a docker environment, we can avoid editing the `config.php` and deal only with env var `GROCY_*` to setup things.
This could also be specified by a dedicated env var to keep retrocompat.

**Comment by berrnd** [comment]
Already possible, [changelog v3.0.0 excerpt](https://grocy.info/changelog#v3.0.0):

> - The data path (previously fixed to the data folder) is now configurable, making it possible to run multiple grocy instances from the same directory (with different config.php files / different database, etc.) (thanks @fgrsnau)
>   - Via an environment variable GROCY_DATAPATH (higher priority)
>   - Via an FastCGI parameter GROCY_DATAPATH (lower priority)

**Comment by berrnd** [comment]
grocy's data is not only the `config.php` and the database file, but everything in the `data` directory (currently mostly the `storage` subfolder which contains all uploaded pictures/files). So don't really see the point about having a separate config option only for the database file...
