### ISSUE TITLE
Feature request: (Inventory Correction) allow to be 0

### ISSUE THREAD

**Issue by TypeVII** [grocy/grocy#1427]
Is there a purpose for inventory correction not allow to be 0 and must be greater than 1? If there isn't any stocks available I believe this should be allow to be 0

**Comment by berrnd** [comment]
Please always try to reproduce problems on the [demo instance](https://demo.grocy.info) first and provide a reproducible way if something does not work.

Of course setting the amount to 0 on [/inventory](https://demo.grocy.info/inventory) is already possible:

https://user-images.githubusercontent.com/2161815/112713678-bb36ac00-8ed6-11eb-9e38-036925bd42bc.mp4

**Comment by TypeVII** [comment]
`XMLHttpRequest
​
mozAnon: false
​
mozSystem: false
​
onabort: null
​
onerror: null
​
onload: null
​
onloadend: null
​
onloadstart: null
​
onprogress: null
​
onreadystatechange: function onreadystatechange()
​
ontimeout: null
​
readyState: 4
​
response: "{\"error_message\":\"Argument 2 passed to Grocy\\\\Services\\\\StockService::InventoryProduct() must be of the type float, string given, called in \\/var\\/www\\/html\\/controllers\\/StockApiController.php on line 471\",\"error_details\":{\"stack_trace\":\"#0 \\/var\\/www\\/html\\/controllers\\/StockApiController.php(471): Grocy\\\\Services\\\\StockService->InventoryProduct(9, '', NULL, '30', '0.00', NULL, NULL)\\n#1 \\/var\\/www\\/html\\/vendor\\/slim\\/slim\\/Slim\\/Handlers\\/Strategies\\/RequestResponse.php(43): Grocy\\\\Controllers\\\\StockApiController->InventoryProduct(Object(Slim\\\\Http\\\\ServerRequest), Object(Slim\\\\Http\\\\Response), Array)\\n#2 \\/var\\/www\\/html\\/vendor\\/slim\\/slim\\/Slim\\/Routing\\/Route.php(384): Slim\\\\Handlers\\\\Strategies\\\\RequestResponse->__invoke(Array, Object(Slim\\\\Http\\\\ServerRequest), Object(Slim\\\\Http\\\\Response), Array)\\n#3 \\/var\\/www\\/html\\/vendor\\/slim\\/slim\\/Slim\\/MiddlewareDispatcher.php(81): Slim\\\\Routing\\\\Route->handle(Object(Slim\\\\Http\\\\ServerRequest))\\n#4 \\/var\\/www\\/html\\/middleware\\/JsonMiddleware.php(13): Slim\\\\MiddlewareDispatcher->handle(Object(Slim\\\\Http\\\\ServerRequest))\\n#5 \\/var\\/www\\/html\\/vendor\\/slim\\/slim\\/Slim\\/MiddlewareDispatcher.php(209): Grocy\\\\Middleware\\\\JsonMiddleware->__invoke(Object(Slim\\\\Http\\\\ServerRequest), Object(Slim\\\\MiddlewareDispatcher))\\n#6 \\/var\\/www\\/html\\/vendor\\/slim\\/slim\\/Slim\\/MiddlewareDispatcher.php(81): class@anonymous->handle(Object(Slim\\\\Http\\\\ServerRequest))\\n#7 \\/var\\/www\\/html\\/vendor\\/slim\\/slim\\/Slim\\/Routing\\/Route.php(341): Slim\\\\MiddlewareDispatcher->handle(Object(Slim\\\\Http\\\\ServerRequest))\\n#8 \\/var\\/www\\/html\\/vendor\\/slim\\/slim\\/Slim\\/Routing\\/RouteRunner.php(84): Slim\\\\Routing\\\\Route->run(Object(Slim\\\\Http\\\\ServerRequest))\\n#9 \\/var\\/www\\/html\\/middleware\\/LocaleMiddleware.php(16): Slim\\\\Routing\\\\RouteRunner->handle(Object(Slim\\\\Http\\\\ServerRequest))\\n#10 \\/var\\/www\\/html\\/vendor\\/slim\\/slim\\/Slim\\/MiddlewareDispatcher.php(313): Grocy\\\\Middleware\\\\LocaleMiddleware->__invoke(Object(Slim\\\\Http\\\\ServerRequest), Object(Slim\\\\Routing\\\\RouteRunner))\\n#11 \\/var\\/www\\/html\\/middleware\\/AuthMiddleware.php(76): class@anonymous->handle(Object(Slim\\\\Http\\\\ServerRequest))\\n#12 \\/var\\/www\\/html\\/vendor\\/slim\\/slim\\/Slim\\/MiddlewareDispatcher.php(313): Grocy\\\\Middleware\\\\AuthMiddleware->__invoke(Object(Slim\\\\Http\\\\ServerRequest), Object(class@anonymous))\\n#13 \\/var\\/www\\/html\\/vendor\\/slim\\/slim\\/Slim\\/Middleware\\/RoutingMiddleware.php(59): class@anonymous->handle(Object(Slim\\\\Http\\\\ServerRequest))\\n#14 \\/var\\/www\\/html\\/vendor\\/slim\\/slim\\/Slim\\/MiddlewareDispatcher.php(147): Slim\\\\Middleware\\\\RoutingMiddleware->process(Object(Slim\\\\Http\\\\ServerRequest), Object(class@anonymous))\\n#15 \\/var\\/www\\/html\\/vendor\\/slim\\/slim\\/Slim\\/Middleware\\/ErrorMiddleware.php(107): class@anonymous->handle(Object(Slim\\\\Http\\\\ServerRequest))\\n#16 \\/var\\/www\\/html\\/vendor\\/slim\\/slim\\/Slim\\/MiddlewareDispatcher.php(147): Slim\\\\Middleware\\\\ErrorMiddleware->process(Object(Slim\\\\Http\\\\ServerRequest), Object(class@anonymous))\\n#17 \\/var\\/www\\/html\\/middleware\\/CorsMiddleware.php(30): class@anonymous->handle(Object(Slim\\\\Http\\\\ServerRequest))\\n#18 \\/var\\/www\\/html\\/vendor\\/slim\\/slim\\/Slim\\/MiddlewareDispatcher.php(313): Grocy\\\\Middleware\\\\CorsMiddleware->__invoke(Object(Slim\\\\Http\\\\ServerRequest), Object(class@anonymous))\\n#19 \\/var\\/www\\/html\\/vendor\\/slim\\/slim\\/Slim\\/MiddlewareDispatcher.php(81): class@anonymous->handle(Object(Slim\\\\Http\\\\ServerRequest))\\n#20 \\/var\\/www\\/html\\/vendor\\/slim\\/slim\\/Slim\\/App.php(215): Slim\\\\MiddlewareDispatcher->handle(Object(Slim\\\\Http\\\\ServerRequest))\\n#21 \\/var\\/www\\/html\\/vendor\\/slim\\/slim\\/Slim\\/App.php(199): Slim\\\\App->handle(Object(Slim\\\\Http\\\\ServerRequest))\\n#22 \\/var\\/www\\/html\\/app.php(94): Slim\\\\App->run()\\n#23 \\/var\\/www\\/html\\/public\\/index.php(45): require_once('\\/var\\/www\\/html\\/a...')\\n#24 {main}\",\"file\":\"\\/var\\/www\\/html\\/services\\/StockService.php\",\"line\":723}}"
​
responseText: "{\"error_message\":\"Argument 2 passed to Grocy\\\\Services\\\\StockService::InventoryProduct() must be of the type float, string given, called in \\/var\\/www\\/html\\/controllers\\/StockApiController.php on line 471\",\"error_details\":{\"stack_trace\":\"#0 \\/var\\/www\\/html\\/controllers\\/StockApiController.php(471): Grocy\\\\Services\\\\StockService->InventoryProduct(9, '', NULL, '30', '0.00', NULL, NULL)\\n#1 \\/var\\/www\\/html\\/vendor\\/slim\\/slim\\/Slim\\/Handlers\\/Strategies\\/RequestResponse.php(43): Grocy\\\\Controllers\\\\StockApiController->InventoryProduct(Object(Slim\\\\Http\\\\ServerRequest), Object(Slim\\\\Http\\\\Response), Array)\\n#2 \\/var\\/www\\/html\\/vendor\\/slim\\/slim\\/Slim\\/Routing\\/Route.php(384): Slim\\\\Handlers\\\\Strategies\\\\RequestResponse->__invoke(Array, Object(Slim\\\\Http\\\\ServerRequest), Object(Slim\\\\Http\\\\Response), Array)\\n#3 \\/var\\/www\\/html\\/vendor\\/slim\\/slim\\/Slim\\/MiddlewareDispatcher.php(81): Slim\\\\Routing\\\\Route->handle(Object(Slim\\\\Http\\\\ServerRequest))\\n#4 \\/var\\/www\\/html\\/middleware\\/JsonMiddleware.php(13): Slim\\\\MiddlewareDispatcher->handle(Object(Slim\\\\Http\\\\ServerRequest))\\n#5 \\/var\\/www\\/html\\/vendor\\/slim\\/slim\\/Slim\\/MiddlewareDispatcher.php(209): Grocy\\\\Middleware\\\\JsonMiddleware->__invoke(Object(Slim\\\\Http\\\\ServerRequest), Object(Slim\\\\MiddlewareDispatcher))\\n#6 \\/var\\/www\\/html\\/vendor\\/slim\\/slim\\/Slim\\/MiddlewareDispatcher.php(81): class@anonymous->handle(Object(Slim\\\\Http\\\\ServerRequest))\\n#7 \\/var\\/www\\/html\\/vendor\\/slim\\/slim\\/Slim\\/Routing\\/Route.php(341): Slim\\\\MiddlewareDispatcher->handle(Object(Slim\\\\Http\\\\ServerRequest))\\n#8 \\/var\\/www\\/html\\/vendor\\/slim\\/slim\\/Slim\\/Routing\\/RouteRunner.php(84): Slim\\\\Routing\\\\Route->run(Object(Slim\\\\Http\\\\ServerRequest))\\n#9 \\/var\\/www\\/html\\/middleware\\/LocaleMiddleware.php(16): Slim\\\\Routing\\\\RouteRunner->handle(Object(Slim\\\\Http\\\\ServerRequest))\\n#10 \\/var\\/www\\/html\\/vendor\\/slim\\/slim\\/Slim\\/MiddlewareDispatcher.php(313): Grocy\\\\Middleware\\\\LocaleMiddleware->__invoke(Object(Slim\\\\Http\\\\ServerRequest), Object(Slim\\\\Routing\\\\RouteRunner))\\n#11 \\/var\\/www\\/html\\/middleware\\/AuthMiddleware.php(76): class@anonymous->handle(Object(Slim\\\\Http\\\\ServerRequest))\\n#12 \\/var\\/www\\/html\\/vendor\\/slim\\/slim\\/Slim\\/MiddlewareDispatcher.php(313): Grocy\\\\Middleware\\\\AuthMiddleware->__invoke(Object(Slim\\\\Http\\\\ServerRequest), Object(class@anonymous))\\n#13 \\/var\\/www\\/html\\/vendor\\/slim\\/slim\\/Slim\\/Middleware\\/RoutingMiddleware.php(59): class@anonymous->handle(Object(Slim\\\\Http\\\\ServerRequest))\\n#14 \\/var\\/www\\/html\\/vendor\\/slim\\/slim\\/Slim\\/MiddlewareDispatcher.php(147): Slim\\\\Middleware\\\\RoutingMiddleware->process(Object(Slim\\\\Http\\\\ServerRequest), Object(class@anonymous))\\n#15 \\/var\\/www\\/html\\/vendor\\/slim\\/slim\\/Slim\\/Middleware\\/ErrorMiddleware.php(107): class@anonymous->handle(Object(Slim\\\\Http\\\\ServerRequest))\\n#16 \\/var\\/www\\/html\\/vendor\\/slim\\/slim\\/Slim\\/MiddlewareDispatcher.php(147): Slim\\\\Middleware\\\\ErrorMiddleware->process(Object(Slim\\\\Http\\\\ServerRequest), Object(class@anonymous))\\n#17 \\/var\\/www\\/html\\/middleware\\/CorsMiddleware.php(30): class@anonymous->handle(Object(Slim\\\\Http\\\\ServerRequest))\\n#18 \\/var\\/www\\/html\\/vendor\\/slim\\/slim\\/Slim\\/MiddlewareDispatcher.php(313): Grocy\\\\Middleware\\\\CorsMiddleware->__invoke(Object(Slim\\\\Http\\\\ServerRequest), Object(class@anonymous))\\n#19 \\/var\\/www\\/html\\/vendor\\/slim\\/slim\\/Slim\\/MiddlewareDispatcher.php(81): class@anonymous->handle(Object(Slim\\\\Http\\\\ServerRequest))\\n#20 \\/var\\/www\\/html\\/vendor\\/slim\\/slim\\/Slim\\/App.php(215): Slim\\\\MiddlewareDispatcher->handle(Object(Slim\\\\Http\\\\ServerRequest))\\n#21 \\/var\\/www\\/html\\/vendor\\/slim\\/slim\\/Slim\\/App.php(199): Slim\\\\App->handle(Object(Slim\\\\Http\\\\ServerRequest))\\n#22 \\/var\\/www\\/html\\/app.php(94): Slim\\\\App->run()\\n#23 \\/var\\/www\\/html\\/public\\/index.php(45): require_once('\\/var\\/www\\/html\\/a...')\\n#24 {main}\",\"file\":\"\\/var\\/www\\/html\\/services\\/StockService.php\",\"line\":723}}"
​
responseType: ""
​
responseURL: "https://localhost/api/stock/products/9/inventory"
​
responseXML: null
​
status: 500
​
statusText: "Internal Server Error"
​
timeout: 0
​
upload: XMLHttpRequestUpload { onloadstart: null, onprogress: null, onabort: null, … }
​
withCredentials: false
​
<prototype>: XMLHttpRequestPrototype { open: open(), setRequestHeader: setRequestHeader(), send: send(), … }`


Doesn't work for me, this is the console error.

**Comment by berrnd** [comment]
Unless it's reproducible on the demo instance, I can't help and it's most probably not a bug, more a problem on your side (browser, server, whatever).

From the stack trace above it can be clearly seen that not `0` is passed as an amount, but `''` (empty string) - that's not possible via the UI, maybe double check if maybe your browser is interfering here.

When I manually do such an API request with an empty amount field I can get exactly this error:

```
POST https://demo-prerelease.grocy.info/api/stock/products/13/inventory
{"new_amount":"","best_before_date":"2021-04-03","shopping_location_id":"1","location_id":"2","price":"2.30"}
```
