### ISSUE TITLE
Bug: Product group headers text corrupted

### ISSUE THREAD

**Issue by pieterjandebruyne** [grocy/grocy#1434]
Hi,

I just started setting up grocy, I added a recipe for spaghetti bolognaise and played around with recipe producing the sauce product in portion of 10. and then a spaghetti recipe which uses the other recipe and pasta. I might have also created the product Bolognaise sauce. I then added stock rules to require at least 2 portions.. Then some cart items got auto removed I think and some data got corrupted. Not sure if all these steps were accurate but can't remember the exact flow. 

The main thing I see now is that my shopping list groups have the name overwritten (but not in other places, only in this view) 

<img width="1259" alt="Screenshot 2021-03-30 at 21 44 07" src="https://user-images.githubusercontent.com/9568274/113047608-cd983a80-91a1-11eb-8192-c7010602e87d.png">

**Comment by berrnd** [comment]
Reset the table options (eye icon on the top right corner of each table).

This is the issue tracker, so supposed for reproducible bugs, feel free to repoen this if you can provide the extact steps to get this or better: Reproduce this on a private/persistent demo instance (like mentioned on the issue template).
Please use the [subreddit](https://www.reddit.com/r/grocy/) for general like also [mentioned in README](https://github.com/grocy/grocy#questions--help--bug-reporting--feature-requests) and on the issue template.
