### ISSUE TITLE
Feature request: Allow recipes to produce multiple products

### ISSUE THREAD

**Issue by ChristianLieven** [grocy/grocy#1437]
I like to make my own oat milk for which I've added a recipe in grocy. However, the process not only yields oat milk but also oat pulp which is a great ingredient in other recipes i.e. hummus, granola, mueslibars. 

Would it be possible to extend the "Produziertes Product" (produced product) section to allow a list of produced products?

The only mention I could find is the original request for products (#374). However, maybe there is another way of allowing two products that I have not found?

Any help is appreciated! Also, kudos to you @berrnd, grocy is fantastic!

**Comment by berrnd** [comment]
As of now only one "Produces product" is possible, sorry.

Closing this in favor of #1053 as it's about the same.
