### ISSUE TITLE
Bug: Editing shopping list items doesn't let you save without adding a note

### ISSUE THREAD

**Issue by lambda1103** [grocy/grocy#1438]
When you try to edit an item on the shopping list the save button is a lighter shade of green and isn't clickable until you have added a note to the entry

**Comment by berrnd** [comment]
Already covered in #1289, already fixed, not yet released.

Can also be easily verified by trying it on the [pre-release demo](https://demo-prerelease.grocy.info/) like mentioned on the issue template.
