### ISSUE TITLE
Bug: Sub Recipe Quantity Broken

### ISSUE THREAD

**Issue by B1ue-W01f** [grocy/grocy#1439]
The calculation of ingredient requirements when including a sub recipe in a main recipe unfortunately is just wildly broken.

Issue 1: 
Changing the servings (Not Desired Servings) of a parent recipe has no effect on the ingredients required by its sub recipe. A parent recipe that produces 8 servings and one that produces 1 serving have different parent ingredient requirements but the same sub recipe ingredient requirements.

Issue 2: 
When the sub recipe is reviewed on its own, the ingredient quantities match exactly the serving numbers. 
750g of potatoes makes 8 servings of mashed potato.

However, when adding the recipe to a roast dinner, you would expect to choose 4 servings of mashed potato for a 4 serving (serving doesn't matter as above issue) roast dinner. 

This would then result in a requirement of 375g of potatoes (half the mashed potato recipe). Instead it requires 24,000 Grams on the pre-release demo. Reducing the serving requirements of the sub recipe in the main recipe, still results in a requirement for 6,000g potatoes, which is  a factor of 16 times wrong.

Apologies, I cant rap my head around how the math is so far off.

**Comment by berrnd** [comment]
Yes, sub recipe amounts are currently unfortunately not correct, but that's already covered by #1252.
