### ISSUE TITLE
Feature request: Add aliases to products (and maybe all other types)

### ISSUE THREAD

**Issue by ska-grocy** [grocy/grocy#1441]
Some products are usually known by more than one name.

It would be nice to add aliases to a product, that are searched in appropriate search boxes. The product itself is displayed with its configured name and not with the searched alias.

pineapple <-- main & display name

aliases:
ananas

So, whereever one can search for a product, both "pineapple" and "ananas" find the product "pineapple" and display in lists as pineapple

**Comment by berrnd** [comment]
That's already request/tracked in #1066, so closing this.
