### ISSUE TITLE
Add to shopping list always adds to default list

### ISSUE THREAD

**Issue by barcoboy** [grocy/grocy#1442]
I have several shopping lists defined, but whenever I try to "Add to shopping list" to one of them, even though the popup says the item was added to the list I selected in the dialog, the item always appears in the default "Shopping List", and I have to move it.

Also, is there a way to delete the default list "Shopping List"?  It seems the "Edit Shopping List" and "Delete Shopping List" buttons are greyed out whenever this list is selected in the drop down box.

Running the latest GitHub development version updated with the latest commits from March 31st, 2021.

**Comment by berrnd** [comment]
> Also, is there a way to delete the default list "Shopping List"?

Currently not, at least since "add missing ingredients to the shopping list" and related actions for example always take this default shopping list because there is no option to select which list should be used there.

> but whenever I try to "Add to shopping list" to one of them, even though the popup says the item was added to the list I selected in the dialog, the item always appears in the default "Shopping List", and I have to move it.

This will be tracked here.

**Comment by barcoboy** [comment]
Just noticed something tonight... this bug only seems to occur when adding an item from the Stock Overview page.  If you add an item using the "Add Item" button on the Shopping List page, it gets added to the correct list.
