### ISSUE TITLE
Feature request: set product flag open automaticly

### ISSUE THREAD

**Issue by Saturo78** [grocy/grocy#1445]
Setting option: "open stock entry when first consumed" = yes

When i consume from a product it is set as open.

Alternative:
Checkbox in the consume menu "open entry" to consume and open in one step.

Actually i enter the product and transfer it. Then i enter the product and click open and finally i enter the product and consume. That is not really efficient.

**Comment by Saturo78** [comment]
I would also suggest making the opening of a stockpile independent of the quantities. What sense does it make to open 0.5 packs from one pack?

**Comment by berrnd** [comment]
> Then i enter the product and click open and finally i enter the product and consume. That is not really efficient.

This needs clarification.

It's generally already possible to consume and open products, both is done via the consume page or any other place that's linked.

So when start using / opening a new bottle of milk today, "opened 1 bottle" is tracked.
When the bottle is used up tomorrow, "consumed" of the same bottle is tracked.
When the whole bottle was used today, why not simply only track "consumed" of that bottle?

And just that we speak UI wise about the same, so basically just another button "Mark as opened and consume" on the [/consume](https://demo.grocy.info/consume) page to practically track "opened" and "consumed" in one step?

**Comment by berrnd** [comment]
Sorry, but I don't really get the practical use case for that and we also mix a lot of things again...

So when I get it right, you want to automatically open the next item on consuming, right?

But what if you consume 2. Do you want then also to open the next 2 or only 1?

And when you always have one open by definition then, is it really worth to track it? I personally wouldn't do it and also don't see the practical sense in that case...

So let's try that on a practical example, pretending the /consume page has that new "open checkbox":

![grafik](https://user-images.githubusercontent.com/2161815/161611229-3fef2609-d644-4a86-a6bb-8e62f4ec2c98.png)

1 Pack should be consumed and 1 opened?

Next example situation:

![grafik](https://user-images.githubusercontent.com/2161815/161611351-51a51fc1-3f94-43c8-b18b-ededc8b1d94f.png)

3 Packs should be consumed and 3 opened?
Or 3 Packs should be consumed and 1 opened?

**Comment by Saturo78** [comment]
This behavior only makes sense when consuming less than 1 pack.
I have one pack with 500g.
I consume 100g and check "open"
As result now i have a pack with 400g which is open. When cosuming the whole pack nothing should be opened.

This maybe could be done automaticly.

When i want to open a stock without consuming (consum only when empty)
I could use the transfer dialog. 

This is not a big thing. If you don´t think it will be helpful feel free just to close this issue.

I ´m just following the developement of Grocy for fun and i´m not using it as productive system at the moment.

**Comment by renarena** [comment]
If you have Stock in grams and you try to open a pack, you open 1 gram rather the pack (in case of different pack sizes there shoulb be a selection, wich size to open). 
This may be not important on sugar, but on groceries which spoil soon.

**Comment by Saturo78** [comment]
Maybe define in the QU Masterdata which QU can be opened and disable the function for the other ones?

In the actual state i always have todo 2 transactions.

1. Open one pack
2. Consume 0.5 pack

I would prefer cosume and open in just one step.

**Comment by berrnd** [comment]
> I would prefer cosume and open in just one step.

Quoting yourself from the [first comment above](https://github.com/grocy/grocy/issues/1445#issue-850559469):
> Alternative:
> Checkbox in the consume menu "open entry" to consume and open in one step.

So this adds (once again) nothing new here.
