### ISSUE TITLE
Feature Request: Ability to select which features of Grocy are shown in the sidebar

### ISSUE THREAD

**Issue by bak3r** [grocy/grocy#1446]
Example: 
A user does not want to see Recipes, Meal plan, Tasks and Batteries in the sidebar. He should have the option to unselect those features of Grocy and they won't be shown to him during his use.

**Comment by berrnd** [comment]
Already possible, have a look at the "Feature flags" section in `config.php`:

https://github.com/grocy/grocy/blob/d23fda245e7a1974c354213f9a228995f2fd583f/config-dist.php#L162-L174
