### ISSUE TITLE
Bug: 

### ISSUE THREAD

**Issue by Saturo78** [grocy/grocy#1447]
If you use another recipe in a recipe, the portions are not calculated correctly and too many required ingredients are displayed.

4 portions
![image](https://user-images.githubusercontent.com/71584438/114030689-efb54b00-987a-11eb-837b-281e618801b3.png)

Pizzateig as Subrecipe 1 portion
![image](https://user-images.githubusercontent.com/71584438/114030777-0196ee00-987b-11eb-9ea2-6e1568043c4d.png)

Pizzateig as Subrecipe 4 portions
![image](https://user-images.githubusercontent.com/71584438/114031046-43279900-987b-11eb-82a9-a16b1c181ab5.png)

**Comment by berrnd** [comment]
Thanks, but that's already tracked in #1252 (and was also reported in #1439).
