### ISSUE TITLE
Error 500 (Synology Web Station)

### ISSUE THREAD

**Issue by Phoara** [grocy/grocy#145]
I tried to install grocy on my Synology NAS. Due to it only having supported PHP 7.0, I blamed the Synology for the 500 error I got. However, Synology has released PHP 7.2 and updated the WebStation yesterday. I tried running grocy again and I still get a php 500 error. Safari only shows a blank page.

I installed the latest grocy version under /web/grocy and try to launch it via MYIP/grocy/public and MY-DDNS/grocy/public. Nothing works. 

Can anybody help me?

**Comment by berrnd** [comment]
Just "500" can mean everything, please check the webserver / PHP logs (but I cannot say where to find them in Synology Web Station), also please ensure that you have create/copied `/data/config.php`...

**Comment by berrnd** [comment]
The `index.php` is located in `/public`, on which the webserver root should point to as mentioned in [README](https://github.com/grocy/grocy#how-to-install)...

**Comment by Phoara** [comment]
The config.php looks like this. When I access this URL in my browser, I am confronted with a 403. If I add /public oder /public/index.php I get the error 500.

> Setting('BASE_URL', 'https://XXX.XXX.XX/grocy');

**Comment by berrnd** [comment]
Your webserver base directory should point the subfolder `/public` of the grocy directory, it will not work when you point it to the main directory and add `/public` to the URL...

When your NAS also supports Docker, maybe have a look at https://github.com/grocy/grocy-docker for easier installation...

**Comment by Phoara** [comment]
Ah, I get it. The problem is, that the webserver has its own sub-directory, namely "web". In it I got folders like Nextcloud, Wordpress, etc. that I can open via https://XXX.XXX.XX/Nextcloud or /Wordpress. So that won't work with Grocy?

I tried Docker as well. I configured quite a lot of docker containers already. However, I can't access grocy when I type in https://XXX.XXX.XX:PORT or via the local IP. 

It's crazy that some github (docker) projects are very easy to configure, whereas some other projects (like Paperless or Bookstack) for me are too much of a challenge.

**Comment by berrnd** [comment]
When you only have one root directory for the webserver and only subdirectories there to use, maybe it also works then when you disable URL rewriting (config option `DISABLE_URL_REWRITING`) and access it via `https://<host>/grocy/public/index.php/stockoverview` (for the main page), while setting the `BASE_URL` in the config to `https://<host>/grocy/public`...

**Comment by Phoara** [comment]
Still getting the same error. Sorry for bothering you with this. :-/

**Comment by berrnd** [comment]
No problem, but sorry - I think I cannot help more without the exact error message, which has to be in any log or somewhere...

**Comment by berrnd** [comment]
Closing this for now, feel free to reopen it if there is anything else I can help with...
