### ISSUE TITLE
shopping_list_id missing in grocy.openapi.json

### ISSUE THREAD

**Issue by idittansikte** [grocy/grocy#1451]
First of all, thanks for all the work put into this.

I have some problems using the OpenAPI definition, one of the problems is that 'shopping_list_id' is missing in the checked-in grocy.openapi.json. And this feels strange, isn't grocy generating code from this? Are there more unsynced stuff?

Another problem/inconvenience is (and this is only a suggested improvement) the usage of oneOf in the /objects/{entity} function. Would be much easier and clear to use if each function was explicitly declared (e.g.  /objects/shopping_list,  /objects/batteries) so you could also declare explicit return types. Now it is a mess to use this since I must first run the API to get what fields that are actually returned for each particular entity-type and then figure out how to call the functions using the generated API (so much for generated code). Feels like /objects/{entity} doesn't fully use the power of swagger.

**Comment by berrnd** [comment]
> And this feels strange, isn't grocy generating code from this? Are there more unsynced stuff?

[`grocy.openapi.json`](https://github.com/grocy/grocy/blob/master/grocy.openapi.json) is currently entirely hand crafted, so probably there are more "not in sync things", but this doesn't change anything regarding API functionality.

I personally would call the [/api](https://demo.grocy.info/api) page only a general overview of the API, nothing that needs to work in every detail...

> 'shopping_list_id' is missing

Will be tracked here (it's about the schema `ShoppingListItem`).

> oneOf in the /objects/{entity} function

It's a generic (kind of "low level") endpoint, so a generic response definition - I will personally change nothing about this general concept. Despite that - feel free to improve anything you find useful, much appreciated.

**Comment by idittansikte** [comment]
Aha, that explains a lot, thanks for the information. I started using grocy.openapi.json to auto-generate a python client for a little custom shopping list integration and was really smooth apart from the things already mention. I was hoping/thinking it was THE API definition which I could rely on.

Is there any future plan to generate the server-side in grocy using the openapi.json?

**Comment by berrnd** [comment]
> Is there any future plan to generate the server-side in grocy using the openapi.json?

Definitely not from my side. If someone suggests a way how to do it without writing all the definitions just at another place, I'm open for everything.
