### ISSUE TITLE
edit inventory fails with a 400 request error when the inventory "opened" checkbox is unchecked on grocy 3.0.1 (docker)

### ISSUE THREAD

**Issue by dvelayos** [grocy/grocy#1452]
Edit an inventory line. If you don't check the "opened" checkbox, the request fails always with this error message:

"SQLSTATE[23000]: Integrity constraint violation: 19 CHECK constraint failed: open IN (0, 1)"

it seems that the default value for not open (false) is not correct (should be 0)

video with the bug: 

https://user-images.githubusercontent.com/11618681/115118322-eb87dc80-9fa2-11eb-9a2e-e4a7e46d059d.mp4

**Comment by berrnd** [comment]
Thanks for reporting, but that's already tracked in #1268 (and was also reported in #1284, and #1373, and #1390, and #1418, and #1423) - also already fixed, but not yet released - can be easily verified by trying to reproduce this before on the [pre-release demo](https://demo-prerelease.grocy.info/) like also mentioned on the issue template.

**Comment by dvelayos** [comment]
Sorry, I looked for the bug, but I couldn't find it (oh my, 6 duplicates, I looked for really bad :-))

it's a trivial one, i fixed it on my docker container. Thanks for your work!
