### ISSUE TITLE
Feature request: Group Products in Chores

### ISSUE THREAD

**Issue by CommittotheIndian** [grocy/grocy#1453]
It would be nice if you could use group products in a chore. For example, I have medications in a group under medications. The chore is taking the medications and the system could then change my stock based on completing that chore.

**Comment by berrnd** [comment]
If you use a parent product and that's not in stock, any of the child products is consumed (first expiring first, then first in first out) - so you want that but instead it should pick the next product of a product group?

If it's just about consuming multiple products on chore execution, that's already tracked in #860.

**Comment by CommittotheIndian** [comment]
Sorry I didn't see the reference in that other entry. I did search chores, just missed it. 

So are you saying make a "Name's Meds", place the meds in that group but never put the Name's Meds in stock/inventory? How would I calculate quantity etc (the required fields)?

**Comment by berrnd** [comment]
Sorry, seems I don't get what you try to accomplish - could you please provide a concrete example?

You have a chore "Take meds" and that should consume "Pill1" and "Pill2" or any of the product group "Pills" - or something else?

**Comment by CommittotheIndian** [comment]
Yes, chore "Take meds". Meds is a group product which includes pill 1 & pill 2. So everyday you take meds (and clear the chore) it consumes a pill 1 & 2 in the stock. Which can then keep track of how many pills (1 &2) are in stock and need replenished.

**Comment by berrnd** [comment]
Ok, thanks - so let's close this since adding the ability to consume multiple products on chore execution is already tracked in #860 as mentioned above.
