### ISSUE TITLE
Bug: selecting a recipe resets filter

### ISSUE THREAD

**Issue by Saturo78** [grocy/grocy#1455]
Recipe Tab
Filter recipes 
When selecting a recipe to show it on the right side the filter gets reset and shows all recipes again.
The expected behavior would be show the filter results till i hit the button "clear filter"

**Comment by berrnd** [comment]
It's the same behaviour on all pages, filters are not persistent - so reset on a page reload...

Can be easily "fixed" for the recipe page, more todo for a generic solution for everywhere...
