### ISSUE TITLE
Bug: Userfield of "stock" is missing in edit views of "stock"

### ISSUE THREAD

**Issue by ska-grocy** [grocy/grocy#1456]
Hi,

I have created an userfield for entitiy "stock".

It looks like, this field is neither present in "Purchase" view nor in the "stock" table nor in "stock" edit view.

**Comment by berrnd** [comment]
The general concept of Userfields unfortunately doesn't fit for stock transactions, that's why that's currently not really possible.

Please see #443 for this.
