### ISSUE TITLE
Video links in WYSIWYG editor are filtered out

### ISSUE THREAD

**Issue by undergroundoyo** [grocy/grocy#1461]
Hi,

The video of the URL inserted when creating a recipe does not work..

Thank

**Comment by berrnd** [comment]
Sorry, I really can't guess what you mean exactly.

Maybe you're referring to the https://grocy.info website, then that's also the wrong repo (but the website has no single video, just some GIFs):
=> [grocy/grocy-website](https://github.com/grocy/grocy-website)

So describing a little better what you mean would be great.

**Comment by undergroundoyo** [comment]
Yes it is true that by rereading it is not very clear. In fact when you create a recipe there is the possibility of putting the URL link to a video (youtube for example). But once saved, the video is not visible in the recipe.

**Comment by berrnd** [comment]
That's then related to #1298, let's leave this open to specifically track handling of the needed things, to not filter out video links in the editor, here.

**Comment by Saturo78** [comment]
I think this relates not only to video links but to all links inserted to a recipe description via html.
