### ISSUE TITLE
Bug: Missing Manage users when using Reverse Proxy Authentication

### ISSUE THREAD

**Issue by Alexsaphir** [grocy/grocy#1462]
I'm using the reverse proxy authentication. 
```
Setting('AUTH_CLASS', 'Grocy\Middleware\ReverseProxyAuthMiddleware');
```

The settings `Manage users` is not available but manually going to `/users` allow to manage users.

**Comment by berrnd** [comment]
That was already started in #1277, so let's link this issue to that pull request...

**Comment by Alexsaphir** [comment]
Sorry, don't know how I missed it.
