### ISSUE TITLE
Feature request: REST API: add a way to get the shopping list 

### ISSUE THREAD

**Issue by BlueBeerRunner** [grocy/grocy#1465]
Hi, I looked for REST API that I can get the shopping list. 
It would be easier to connect with other code.

**Comment by berrnd** [comment]
Of course already possible, please have a look at: https://www.reddit.com/r/grocy/comments/n4njsr

**Comment by berrnd** [comment]
So after a second look, seems that it was also you on reddit (?), then I maybe just don't understand the question/request here...
