### ISSUE TITLE
Bug: Cannot change stock entry unless I set the item as opened

### ISSUE THREAD

**Issue by jloffredo** [grocy/grocy#1466]
I'm trying to update the price (or store or any value) on a product and it doesn't work unless y check the open checkbox. 
If it's unchecked or I uncheck it I get this error in the JS console:

`error_message\":\"SQLSTATE[23000]: Integrity constraint violation: 19 CHECK constraint failed: open IN (0, 1)`

I'm using 
Version 3.0.1
PHP Version 7.4.15
SQLite Version 3.34.1

in the home assistant plugin version (Grocy current version: 0.13.0 ).

**Comment by berrnd** [comment]
Thanks for reporting, but that's already tracked in #1268 (and was also reported in #1284, and #1373, and #1390, and #1418, and #1423, #1452) - also already fixed, but not yet released - can be easily verified by trying to reproduce this before on the [pre-release demo](https://demo-prerelease.grocy.info/) like also mentioned on the issue template.

**Comment by jloffredo** [comment]
Oh, sorry. I searched but didn't find them. Any idea more or less on when will that fix be released? 
Thanks!!!

**Comment by berrnd** [comment]
In general I don't plan anything about grocy and currently (obviously) don't work on it.

The fix can also be applied manually, just replace the two files changed by commit bfa3347a20c764b8e3c8dc75e917affcfa7108bd:
https://raw.githubusercontent.com/grocy/grocy/bfa3347a20c764b8e3c8dc75e917affcfa7108bd/services/StockService.php
https://raw.githubusercontent.com/grocy/grocy/bfa3347a20c764b8e3c8dc75e917affcfa7108bd/helpers/extensions.php

**Comment by jloffredo** [comment]
Got it. thanks!
