### ISSUE TITLE
Bug: (Help-)Tooltips not available on touch devices

### ISSUE THREAD

**Issue by RubenKelevra** [grocy/grocy#1468]
I'm using the latest brave browser (which is basically Chrome) on Android 11.

I noticed that the question mark helps are not available, neither with a single tap nor with a long press.

https://user-images.githubusercontent.com/614929/117463566-1afd8980-af50-11eb-94a9-31f4d29034f2.mp4

**Comment by berrnd** [comment]
That's unrelated to a specific browser, it's about that [Bootstrap Tooltips](https://getbootstrap.com/docs/4.6/components/tooltips/) are triggered by the `hover` event by default and that's not available on touch enabled devices...

**Comment by RubenKelevra** [comment]
Can't we just add a click event for the question mark? 🤔
