### ISSUE TITLE
Bug: creating a task keeps the pop-up open + no refresh

### ISSUE THREAD

**Issue by RubenKelevra** [grocy/grocy#1469]
Creating a new task will open a pop-up window. Saving a task won't close the pop-up but instead just grey out all of the input fields. 

Since there's no "trigger" which now notifies Grocy that data has been changed, the "Close" button will close the dialog, but the list is the same as before. 

https://user-images.githubusercontent.com/614929/117463818-5c8e3480-af50-11eb-927a-09a95f083684.mp4

**Comment by berrnd** [comment]
Thanks for reporting, but please try to reproduce problems first on the demo instance (like also mentioned on the issue template).
If it works there and not on your side, it's most probably not a bug (maybe try to check the Browser Console for errors, or your webserver logs, etc.).

Tried it, can't reproduce it:
https://user-images.githubusercontent.com/2161815/117468026-919c8600-af54-11eb-8f67-0a493c4c326d.mp4

If that's reproducible somehow, feel free to reopen this.
 
> Since there's no "trigger" which now notifies Grocy that data has been changed

Not so true, at least the code proofs something else:

Here is the trigger:
https://github.com/grocy/grocy/blob/d23fda245e7a1974c354213f9a228995f2fd583f/public/viewjs/taskform.js#L27

Here is the receiver:
https://github.com/grocy/grocy/blob/d23fda245e7a1974c354213f9a228995f2fd583f/public/js/grocy.js#L907-L915
