### ISSUE TITLE
[Feature Request] Recipie image (grid overview)

### ISSUE THREAD

**Issue by shadowtor** [grocy/grocy#147]
Would be nice to see a grid overview of recipes with a head image of each dish so it is easy to pick what looks good.

**Comment by berrnd** [comment]
References #136

**Comment by berrnd** [comment]
I tried now something like that. :)

You can check it out in the already updated pre-release demo if you want:
https://demo-prerelease.grocy.info/recipes?tab=gallery

The selected tab is remembered (in the browsers local storage), so when you prefer the gallery view, it will be always used by default, if you never switch back to the list view tab.

Let me know if this is what you thought of or if you have further ideas on this.
