### ISSUE TITLE
Feature request: Recipe show calories per serving

### ISSUE THREAD

**Issue by Saturo78** [grocy/grocy#1470]
I think a recipe should show  calories per serving instead of total calories for the whole recipe.

**Comment by berrnd** [comment]
Of course, like the Tooltip implies - was unfortunately a bug, already tracked in #1359, already fixed, not yet released.

Execute this [SQL statement](https://raw.githubusercontent.com/grocy/grocy/c483c345981be5c49353c50cea6befffe3d66e2e/migrations/0129.sql) on your database manually if you want to have this now.
