### ISSUE TITLE
Bug: Tables are not horizontally scrollable unless one column completely doesn't fit

### ISSUE THREAD

**Issue by RubenKelevra** [grocy/grocy#1476]
The QU conversions table when editing a product is cut off on vertical mobile devices. 

Usually tables are horizontal scrollable in Grocy, but this one is not. 

There might be more than this one, but I noticed this one first. 

https://user-images.githubusercontent.com/614929/117893735-43241a00-b2bb-11eb-94d8-6bb9578efcbf.mp4

**Comment by berrnd** [comment]
It's nothing special about that table, all tables are technically the same.

Seems that the scrollbar only appears if at least one column completely doesn't fit the viewport width (not the case here, the last column is partly visible).

Don't know how to improve that, but let's leave this open, maybe someone else has an idea, don't think that's a really big problem...
