### ISSUE TITLE
Bug:  Can't edit Due Date for unopened products

### ISSUE THREAD

**Issue by Zottelchen** [grocy/grocy#1477]
**Steps:**
1. Create product sugar without setting a default due date.
2. Add 1 sugar
3. Try to change due date (e.g. to never expire) ➡ ❌ it doesn't work
4. Open 1 sugar
5. Try to change due date (e.g. to never expire) ➡✔it works
6. Try to un-open the sugar ➡ ❌ it doesn't work

**Comment by berrnd** [comment]
Thanks for reporting, but that's unrelated to editing the due date - editing stock entries in general is currently unfortunately broken and that's already tracked in #1268 (and was also reported in #1284, and #1373, and #1390, and #1418, and #1423, and #1452, and #1466) - also already fixed, but not yet released - can be easily verified by trying to reproduce this before on the [pre-release demo](https://demo-prerelease.grocy.info/) like also mentioned on the issue template and [here](https://github.com/grocy/grocy/issues/1466#issuecomment-834272075) is how to apply the fix manually if you want to have this now.
