### ISSUE TITLE
Improve mobile (touch) date time input picker/keyboard handling

### ISSUE THREAD

**Issue by RubenKelevra** [grocy/grocy#1478]
If you're entering a date and a time on the chores execution page, the keyboard pops up on every tap, blocking the view on the dialog. 

Additionally the button on the left seems to do nothing. 

https://user-images.githubusercontent.com/614929/118086312-0b54c980-b3c4-11eb-91ea-61ea53ad80d8.mp4

The best solution for such a dialog would actually be to let the browser open the native dialogs for entering a date and a time.

**Comment by berrnd** [comment]
That's a standard text input field, the picker component attached is [berrnd/tempusdominus-bootstrap-4](https://github.com/berrnd/tempusdominus-bootstrap-4) (the fork includes some fixes the original project didn't had).

Additionally, a lot of shorthands are available: https://github.com/grocy/grocy#input-shorthands-for-date-fields
I personally every only use them to enter any date...

> The best solution for such a dialog would actually be to let the browser open the native dialogs for entering a date and a time.

In a perfect world where every browser supports every "standard" and if, implements everything in the same way then I would agree: https://caniuse.com/input-datetime

Feel free to tweak/improve that, if the native approach _really_ works on at least all major browsers/devices, then I'm also open for that.

**Comment by RubenKelevra** [comment]
> > The best solution for such a dialog would actually be to let the browser open the native dialogs for entering a date and a time.
> 
> In a perfect world where every browser supports every "standard" and if, implements everything in the same way then I would agree: https://caniuse.com/input-datetime
> 
> Feel free to tweak/improve that, if the native approach _really_ works on at least all major browsers/devices, then I'm also open for that.

They do work with all major browsers:

![Screenshot_20210515-003800290](https://user-images.githubusercontent.com/614929/118338220-e1132100-b515-11eb-9200-46d5b630813e.jpg)
[_date_](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/date)

![Screenshot_20210515-003702129](https://user-images.githubusercontent.com/614929/118338164-b88b2700-b515-11eb-928c-b63b725dcdf0.jpg)
[_time_](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/time)

**Comment by berrnd** [comment]
Have you tried it? That it's stated on canisue.com doesn't necessarly mean it really behaves in the same (means without having browser specific quirks on grocy side at the end) way everywhere...

grocy has some options about dates/calendars, like showing week numbers or not, and the shorthands - can this also be integrated?

Anyways, thanks for your sugestions, as said, feel free to implement that, I'm open to everything, a native approach is of course better, but only if everything which should work, works - I will personally probably nothing do about that unless the current picker is broken.

**Comment by RubenKelevra** [comment]
> Have you tried it? That it's stated on canisue.com doesn't necessarly mean it really behaves in the same (means without having browser specific quirks on grocy side at the end) way everywhere...

There's a link below the pictures which loads the documentation from Mozilla. 

You can see how it looks like on each platform and test it in your current browser. 


> grocy has some options about dates/calendars, like showing week numbers or not, and the shorthands - can this also be integrated?

Well the native approach follows the locale setting in the operating system. So for example which day of the week is the start and if 12 or 24 system hours is used. 

So special settings will become superficial. 


> Anyways, thanks for your sugestions, as said, feel free to implement that, I'm open to everything, a native approach is of course better, but only if everything which should work, works - I will personally probably nothing do about that unless the current picker is broken.

You're welcome. 

I know that is super low priority, but I just wanted to point the bug in convince out. If someone is searching for a small task in this project he/she can tackle this. :)

**Comment by berrnd** [comment]
> If you're entering a date and a time on the chores execution page, the keyboard pops up on every tap, blocking the view on the dialog.

This is not a problem anymore:

https://user-images.githubusercontent.com/2161815/161446936-889d2edf-01c3-433a-80d6-8df95be095d3.mp4

&nbsp;
> Additionally the button on the left seems to do nothing.

That's related to when a max-datetime is set, the button will now be hidden when that's the case.
