### ISSUE TITLE
Feature Request: Medication cabinet management

### ISSUE THREAD

**Issue by MarcALE** [grocy/grocy#1479]
It would be great to have a base to manage our medicine cabinet :

- Photo of the box
- Barcode
- Name
- Expiry date
- Family member
- Prescription purpose
- When to take (morning / midday / evening / x-times a day...)
- How long to take
- First take

... and I have pollen allergies, so tracking things would be great 👍 : 

- Day
- Symptom (eye / throat / nose...) and intensity
- Medication taken (if any)

Thanks in advance !

**Comment by berrnd** [comment]
You can already define any entity with any properties to create any list you want.

Like mentioned on the homepage on showcased by this example Userentity: https://demo.grocy.info/userobjects/exampleuserentity

I personally simply track medicine just like any other stock item in a separate product category, a lot of others do the same - for questions / usage help the better place is the [subreddit](https://www.reddit.com/r/grocy) like [mentioned in README](https://github.com/grocy/grocy#questions--help--bug-reporting--feature-requests).
