### ISSUE TITLE
Feature request: Batteries for toys

### ISSUE THREAD

**Issue by MarcALE** [grocy/grocy#1480]
I'd like to be able to manage batteries in my kids' toys :

- Photo fo toy
- Name of toy
- Location
- Type of batteries
- Number of batteries
- Date of change
... and then generate a reminder based either on : 

- expiry date of battery
- average time to replace battery (better option)

**Comment by berrnd** [comment]
The same as already answered in https://github.com/grocy/grocy/issues/1479#issuecomment-841486692.

Custom properties are not limited to own entities, every built-in entity can also be extended, have also a look at #176 and the linked issues there.
