### ISSUE TITLE
Feature request: Shopping list thermal printer support

### ISSUE THREAD

**Issue by accessiblepixel** [grocy/grocy#1482]
Hi!

I really love the grocy software, and my partner had an idea for how we could make it better with a cheap thermal receipt printer (from our old ePOS setup). I'm not that familiar in how github works so if I have done this wrong, please move it to the right place :)

It would be really cool if there were a way to customise the printouts of the shopping lists and have it print on a thermal receipt printer.

It would be an awesome idea because the lists would then fit in his phone case in those "credit card" slots, and it would save us having to write them down or print them on a piece of A4.

It's just an idea, and it might be something I can do by changing the CSS of the print page, but I'm not sure where to start as I am not very familiar with the grocy codebase.

Many thanks for taking the time to write and share this software. It's useful to us because I am a disabled person, and so far we've been making lists of what food we have in every time my carers ask me what I would like making. This would let me program the recipes in and see what we have in stock without having to get to the kitchen (I can't at the moment as we haven't got anywhere near sorted after moving house). A really grateful user here!

Kind regards,
Jessica

**Comment by berrnd** [comment]
My pleasure that grocy is useful for you. :)

Have a look at #1273 where @Forceu already started something about this - already finished (most probably), but not yet merged.
Will link this ticket to that pull request.

I'm personally not familiar with thermal printers but it seems that they don't work like "normal" printer at all, so CSS customizations won't work here...

**Comment by accessiblepixel** [comment]
> 
> 
> My pleasure that grocy is useful for you. :)
> 
> Have a look at #1273 where @Forceu already started something about this - already finished (most probably), but not yet merged.
> Will link this ticket to that pull request.
> 
> I'm personally not familiar with thermal printers but it seems that they don't work like "normal" printer at all, so CSS customizations won't work here...

Thank you for your reply! That thread looks very interesting, thank you for linking it!

Thermal printers only usually support text output, but I know on Windows they can appear as a "Generic Text Printer" (and be shared on the network that way too). I've just built a "thin client" as a grocy station for the kitchen so it would be awesome could I get my generic thermal printer working with that thin client too.

Dunno how to attach an image here, but here's a gallery of the v2 client (without the thermal printer/barcode scanner... webcam is for QR code scanning!) and a background I made with some CC artwork and the grocy logo 

https://i.lowrex.com/a/6h2

Amazing so far though, thank you! :)

**Comment by berrnd** [comment]
When the printer is reachable just like any printer (so also from client/browser side), I would say the current shopping list print options "list and no header" already produce a pretty clear/simple list which then may fit...

![grafik](https://user-images.githubusercontent.com/2161815/119236787-9d35a280-bb39-11eb-8b1f-2565626dc2c5.png)

![grafik](https://user-images.githubusercontent.com/2161815/119236789-a161c000-bb39-11eb-8016-1e30944a5cb0.png)

**Comment by accessiblepixel** [comment]
@berrnd - Thank you for your reply! I'll give it some testing once we've found the power lead for the receipt printer and report back. I'll also post the model details and if I manage to get it working without using an API or whatever that's needed from the other thread so it can maybe help others out too who wanna do the same... :) Thank you!
