### ISSUE TITLE
Bug: QR Code Server URL not complete when installed in subdirectory

### ISSUE THREAD

**Issue by supergeorg** [grocy/grocy#1483]
This problem only seems to happen when Grocy is installed in a subdirectory, e.g. https://server.address/grocy/public
When you generate the QR code with the API key, only the subfolder is included, which makes the QR code content look like this: "/grocy/public/api|<APIKEY>". This cannot be used to connect to the server, so users have to enter the URL and Code manually.
This cannot be tested with the Demo server, since it doesn't use subdirectories.

**Comment by berrnd** [comment]
Double check the `config.php` setting `BASE_URL`.

All URLs are generated via the exact same function, so if this is a problem, I doubt that the frontend works at all since it also uses the API and therefore the same (wrong in that case) API URL...

**Comment by supergeorg** [comment]
Thank you, that fixed the problem for me.
