### ISSUE TITLE
Feature request: Add button to manually skip chores 

### ISSUE THREAD

**Issue by RubenKelevra** [grocy/grocy#1486]
I got many tasks which need to be regularly checked, but often it's not necessary. We currently just let them be overdue, but it would be nice to just skip them in the configured interval instead. 

This way it's clear that it was checker (not just "forgotten" to check today) and it disappears from the overdue list. 

Else different people in the household might check it more than one time a day, since it is showed as overdue. 

Marking them as "done" is kind of unfair as well, since you really didn't have to do something. 

It would be nice to have a log entry like 'task x was skipped one interval' or 'task x was skipped x days' in the journal. 

@berrnd hope this clears it up :) 
_This is a successor to #1322_

**Comment by berrnd** [comment]
That's now done:

New button on the /choresoverview page:

![grafik](https://user-images.githubusercontent.com/2161815/153039120-a2f37705-909b-4171-8c66-74d3661dd826.png)

New button on the /choretracking page:

![grafik](https://user-images.githubusercontent.com/2161815/153039229-68612d0e-5b58-475c-8c85-65d1b5ccea82.png)

Corresponding highlighting (italic) on the /choresjournal page:

![grafik](https://user-images.githubusercontent.com/2161815/153039669-ca447002-c3a7-42d4-9604-e8af7c3b1b81.png)

Skipping is not possible for chores with period type `manually`.

**Comment by RubenKelevra** [comment]
@berrnd just got the update via HA add-on and noticed a minor issue with that:

I had a task which I was "not doing" for a while and couldn't skip. If I now skip the task it is moved forward by the regular interval, but that's like weeks in the past. So it's still not "checked and not necessary" but overdue.

So my question is if this could be changed to having it "completed" and the due date is moved in the regular interval in the future. :)

**Comment by berrnd** [comment]
> I had a task which I was "not doing" for a while and couldn't skip. If I now skip the task it is moved forward by the regular interval, but that's like weeks in the past. So it's still not "checked and not necessary" but overdue.
> 
> So my question is if this could be changed to having it "completed" and the due date is moved in the regular interval in the future. :)

Moved to #1830.
