### ISSUE TITLE
Feature Request: App/HA integration

### ISSUE THREAD

**Issue by Griever102** [grocy/grocy#1487]
I just installed this on my Home Assistant and I couldn't find a way to integrate the app I downloaded on my phone with the instance running on my HA. The reason why this would be nice, is on HA Grocy is only in the side bar and only admins can access it. But if you can have the two linked together, then it would be a great work around. But only if you can access it from anywhere too. I am using the HA cloud so that might be a feature to use? Just tossing something out there. But if it's already possible and I just couldn't find the answer than that's great. But from playing around with Grocy, it seems really amazing and I'm excited to use it. 

Oh and another feature, with in the calendar, would it be possible to either add a Google calendar or to input things directly. For example I'm hoping to use HA and Grocy at our family cabin, so our whole family can see what food we have up there, and the manuals for all the equipment, ect ect.. but if we could add in who's going to be up there and when, it would be really nice to be able to see that. 

Great work on it and I am excited to see all the different features that are added and to dive into it more and use it for my personal use and family use.

**Comment by berrnd** [comment]
This here is the issue tracker, please the [subreddit](https://www.reddit.com/r/grocy/) for general questions/help like also [mentioned in README](https://github.com/grocy/grocy#questions--help--bug-reporting--feature-requests).

Or probably even better for this: The Home Assistant Community Forum: https://community.home-assistant.io/t/home-assistant-community-add-on-grocy/112422

Personally not using HA, but I'm sure it's possible to access it, so also grocy, externally.

Adding to the possibility to use external calendars is already tracked in #626.
