### ISSUE TITLE
Feature request: Coupon Scraping Feed w/ Inventory Tagging, Notification Platform, and REST Integration

### ISSUE THREAD

**Issue by iotemylabs** [grocy/grocy#1488]
Please describe what you would find useful and please also check (by searching open requests here) if that was maybe already requested.

Hi!

I had this idea where we can have a tab in Grocy to see available coupons to clip, even have tags that can notify you if an item in your Products master database matches a certain coupon, and can fire off a REST API Notification when it is available.

Also, my thought is that there can be a print coupon option if you want to take advantage of it.

I thought I might try to make a base of it (and learn more advanced python while I'm at it :) )

https://github.com/iotemylabs/appdaemon-grocy-walmart-coupons

**Comment by berrnd** [comment]
Thanks a lot for the idea, but seems not really to be a feature request, more about an integration of a community contribution - thanks for creating that!

Feel free to share that on the [subreddit](https://www.reddit.com/r/grocy), that's most probably the best place to reach most grocy users, or add it to the website which also has it's own repo ([grocy/grocy-website](https://github.com/grocy/grocy-website)) if you think that's ready to be shared.

Integrating something like that into the frontend is also already possible via [custom JS ](https://github.com/grocy/grocy#adding-your-own-css-or-js-without-to-have-to-modify-the-application-itself)(if any web UI or web API is available).
