### ISSUE TITLE
Bug: Subrecipe with wrong quantities

### ISSUE THREAD

**Issue by 13hannes11** [grocy/grocy#1489]
1. Create a recipe for 4 people
2. Select as subrecipe another recipe with 4 people.
3. The quantities are way too high.

https://test-1pqe9lg5bfraye4cmd1js6.demo-prerelease.grocy.info/recipes?recipe=10

![image](https://user-images.githubusercontent.com/9381167/119394714-cd647900-bcd2-11eb-9990-dab84123b00c.png)

**Comment by berrnd** [comment]
Thanks for reporting, but that's already tracked in #1252.
