### ISSUE TITLE
Item count in shopping list incorrect when below min stock

### ISSUE THREAD

**Issue by Forceu** [grocy/grocy#149]
If an item is added to the shopping list because it is below minimum stock, the item count is incorrect when editing it:
The value from the minimum stock is added to the entered value for the shopping list.
I attached a video for reproducing the bug:

https://imgur.com/IGBhRWH

I'm using version 1.23.1

**Comment by berrnd** [comment]
The idea was, that the amount which was automatically added by "Add products that are below defined min. stock amount" always applies in addtion to the user-entered amount.

There was a message below the amount field "1 units were automatically added and will apply in addition to the amount entered here" (for your example). This message somehow got lost which is of course a ui-bug...

**Comment by Forceu** [comment]
Thanks for the quick response! Isn't that a little bit counter-intuitive? If it is already on the shopping list and I  click on the "edit" button, shouldn't it rather let me edit the final item count?

**Comment by berrnd** [comment]
Yes, maybe.

I think we remove this better and compare with the visible/normal amount...
