### ISSUE TITLE
Feature request: Please make a new release from master 3.0.2

### ISSUE THREAD

**Issue by rolfberkenbosch** [grocy/grocy#1491]
I see that you have fixed alot of bugs in the master repo. Can you trigger a new release, for example 3.0.2 ?

**Comment by berrnd** [comment]
And I see a lot of new bugs, partly introduced by other bug fixes - releasing a state with currently 39 known open problems is at least a bad idea...

I currently don't work on grocy, but this is Open Source where everything is done publicly, so everyone is able to use the current master branch (if this is what you really want) or simply apply the fixes for already fixed things manually (on many issues there is, beside the commit references, also a short hint what to change/replace).

**Comment by Saturo78** [comment]
Whats the thing when i use the masterbranch?
You mentioned some issues with the update of the next official release?

**Comment by berrnd** [comment]
I only care that database migrations work between releases, so you would have to check that manually.

**Comment by Saturo78** [comment]
I can not assess the risk involved and how to check it. Therefore, I will have to wait for the next release. Maybe in 2022.
