### ISSUE TITLE
Feature request: Manually Assign Chore to Specific User

### ISSUE THREAD

**Issue by mahl3r** [grocy/grocy#1492]
Hi! I just started using Grocy and I'm looking for a way to start assigning chores to people in my household, but I was hoping this feature would be a part of the service. 

Maybe from the chores overview tab, click a button (maybe the three dots) that has a tab that says "Manually Assign Chore", and when you click it you can choose which user to manually assign that chore to for that time.

Please let me know what you think, and if there already is this feature please let me know!

Thanks!

**Comment by berrnd** [comment]
That's now done as part of #1830 - changelog excerpt:

> - It's now possible to manually reschedule / assign chores
>    - New entry "Reschedule next execution" in the context/more menu on the chores overview page
>    - If you have rescheduled a chore and want to continue the normal schedule/assignment instead, use the "Clear" button in the dialog
>    - Rescheduled/reassigned chores will be highlighted with an corresponding icon next to the "Next estimated tracking date" / "Assigned to"

![grafik](https://user-images.githubusercontent.com/2161815/161426871-0a45ab10-eefc-45ba-a7b2-142aff647612.png)

![grafik](https://user-images.githubusercontent.com/2161815/161426880-4acabf69-b8d9-4c45-98f9-1327afe9d0c4.png)
