### ISSUE TITLE
Bug: `ezyang/htmlpurifier` attempts to write in `/vendor` directory

### ISSUE THREAD

**Issue by gauravjuvekar** [grocy/grocy#1497]
vendor/ezyang/htmlpurifier/ tries to write in the installation directory. 

grocy should configure htmlpurifier cache directory to a path within grocy's own data directory / any other cache directory location.

See
https://github.com/ezyang/htmlpurifier/blob/master/INSTALL#L297

> May 31 03:23:04 [REDACTED] nginx[472]: 2021/05/31 03:23:04 [error] 472#472: *733 FastCGI sent in stderr: "PHP message: PHP Warning:  Directory /usr/share/webapps/grocy/vendor/ezyang/htmlpurifier/library/HTMLPurifier/DefinitionCache/Serializer not writable, please chmod to 777 in /usr/share/webapps/grocy/vendor/ezyang/htmlpurifier/library/HTMLPurifier/DefinitionCache/Serializer.php on line 297PHP message: PHP Warning:  Directory /usr/share/webapps/grocy/vendor/ezyang/htmlpurifier/library/HTMLPurifier/DefinitionCache/Serializer not writable, please chmod to 777 in /usr/share/webapps/grocy/vendor/ezyang/htmlpurifier/library/HTMLPurifier/DefinitionCache/Serializer.php on line 297PHP message: PHP Warning:  Directory /usr/share/webapps/grocy/vendor/ezyang/htmlpurifier/library/HTMLPurifier/DefinitionCache/Serializer not writable, please chmod to 777 in /usr/share/webapps/grocy/vendor/ezyang/htmlpurifier/library/HTMLPurifier/DefinitionCache/Serializer.php on line 297" while reading response header from upstream, client: 127.0.0.1, server: localhost, request: "PUT /api/user/settings/datatables_state_stock-overview-table HTTP/1.0", upstream: "fastcgi://unix:/run/php-fpm7/php-fpm.sock:", host: "127.0.0.1:8802", referrer: [REDACTED]

**Comment by berrnd** [comment]
Thanks, interesting that this wasn't noticed so far and if I check my private + the demo instances no cache files are generated in the mentioned directory...
