### ISSUE TITLE
404 Page Not Found

### ISSUE THREAD

**Issue by vroomhenderson** [grocy/grocy#150]
I've been wrestling with this for about a day now, thinking it's my own installation, but even on a fresh Apache installation, I'm receiving a 404 error.

The setup I have going is that on my base domain, I have an Nginx server running. When example.com/grocy/ is typed in, it'll reverse proxy it from an Apache server hosted with Grocy installed in the root web directory at http://123.123.1.123/.

Typing in https://example.com/grocy does correctly proxy, and automatically takes me to https://example.com/grocy/index.php/stockoverview (when URL rewriting is disabled in the config), but I'm given a "404 page not found" error issued by the Grocy server.

Apache Version: 2.0
PHP Version: 7.3

Let me know what log files I should include.

**Comment by berrnd** [comment]
Assuming your webserver root directory is `/var/www` and the grocy directory is then `/var/www/grocy`, a working URL should be `https://example.com/grocy/public/index.php/stockoverview` when URL rewriting is disabled and `BASE_URL` is set to `https://example.com/grocy/public`.

Or set the web root directly to `/var/www/grocy/public`.

These are my spontaneous ideas for this...

**Comment by vroomhenderson** [comment]
Sorry, I should've clarified on that a bit more. Grocy was extracted to `/var/www/html/`, and the web root is set to `/var/www/html/public`. I'm able to verify that it's accessing the correct directory both via logs, and by creating a 'test.html' document in the public folder.

Here's the Apache access log:
```
10.138.176.78 - - [04/Feb/2019:04:23:55 +0000] "GET // HTTP/1.0" 302 229 "-" "Mozilla/5.0 (X11; CrOS aarch64 11316.112.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/72.0.3626.85 Safari/537.36"
10.138.176.78 - - [04/Feb/2019:04:23:55 +0000] "GET //stockoverview HTTP/1.0" 404 471 "-" "Mozilla/5.0 (X11; CrOS aarch64 11316.112.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/72.0.3626.85 Safari/537.36"
```
Typing in `https://example.com/grocy` automatically redirects me to `https://example.com/grocy/index.php/stockoverview` without any input from the user, but does send the 404 error.

**Comment by vroomhenderson** [comment]
The above log is with rewriting enabled. Below is with rewriting disabled:
```
10.138.176.78 - - [04/Feb/2019:04:25:42 +0000] "GET // HTTP/1.0" 302 239 "-" "Mozilla/5.0 (X11; CrOS aarch64 11316.112.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/72.0.3626.85 Safari/537.36"
10.138.176.78 - - [04/Feb/2019:04:25:42 +0000] "GET //index.php/stockoverview HTTP/1.0" 404 1053 "-" "Mozilla/5.0 (X11; CrOS aarch64 11316.112.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/72.0.3626.85 Safari/537.36"
```

**Comment by berrnd** [comment]
Thanks! :)
And great that it works for you now.

**Comment by DoctorOctagonapus** [comment]
Hey, I'm having the same 404 error but apparently for a different reason. I've got my document root set directly to /var/www/grocy/public, and DNS port binding set so I can browse to http://grocy/. When I try and do it however, it returns a 404.

Access.log entry:
`"GET / HTTP/1.1" 302 251 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/75.0.3770.100 Safari/537.36"`
`"GET /stockoverview HTTP/1.1" 404 504 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/75.0.3770.100 Safari/537.36"`

php -v:
`PHP 7.3.6-1+0~20190531112735.39+stretch~1.gbp6131b7 (cli) (built: May 31 2019 11:27:35) ( NTS )`
`Copyright (c) 1997-2018 The PHP Group`
`Zend Engine v3.3.6, Copyright (c) 1998-2018 Zend Technologies`
`    with Zend OPcache v7.3.6-1+0~20190531112735.39+stretch~1.gbp6131b7, Copyright (c) 1999-2018, by Zend Technologies`

Any thoughts? I'm using the latest version.
