### ISSUE TITLE
Feature request: slowly move to vue.js for frontend javascript

### ISSUE THREAD

**Issue by mistressofjellyfish** [grocy/grocy#1501]
I do realize that this is far fetched and heavily opinionated, but my main goal is to start a discussion, *not* to get down to business.

As I'm working on #1500, I'm digging through code like [this](https://github.com/grocy/grocy/blob/master/public/viewjs/components/productcard.js) and its associated [view file](https://github.com/grocy/grocy/blob/master/views/components/productcard.blade.php), which does nothing but data binding, in an incredibly cumbersome, complicated and error-prone way.

As I like simplicity when hacking on stuff, I wondered if there is a better way. Having worked with vue.js in the past, it's data binding capabilities have always intrigued me.

Now, I realize the introduction of a whole javascript framework is a huge deal. I'm not married to vue, but I think anything that solves the databinding problem reduces the amount of code for UI problems.

Specifically, if you're open to try vue, this would by no means be a "do it now for everything" scenario. Instead, most of the code could be kept as-is while slowly introducing vue into the areas which benefit most (i.e. everything that is dynamically databound first).

I'll probably hack some prototype together once I finish up on #1500.

**Comment by berrnd** [comment]
Has been already mentioned on many other places...

The main point is still simple: I'm unfortunately currently not into any JS frontend framework (still one of the things I want to do/learn, but time...) but at the same time the one who does and maintains ~99% of what you see in grocy (well, the last couple of months not really, but again, time...).

I would more start a complete rewrite of the frontend, without server side code (I think that's also what a JS frontend framework is for), the API should already provide everything needed.

**Comment by mistressofjellyfish** [comment]
I see your point completely, and that's why I don't want to have this as a "omg we need x! now! do something!" issue but more of a discussion on what to do / centralize the discussion. I've seen people complaining in other issues, but that is precisely not what I want this to be about.

In the end, it's your call where to go. From my experience, especially in OSS, complete rewrites rarely happen (successfully). I would *much* rather prefer an incremental approach, and this would include moving all of the templates out of the server side. This would also enable us to build grocy as an electron app if needed or wanted.

Now; as far as I see it there two popular choices around, react and vue. Personally, my distaste for facebook things makes me use vue, but I'm fine either way. I don't want to put pressure on you in any way – I'm fine either way, and we can always continue that discussion once I figured out how this and the transition could work.

**Comment by berrnd** [comment]
> electron app if needed or wanted

There is already something similiar there (includes the backend/server part, so not just a website reframed into an application, but currently not cross-platform): https://github.com/grocy/grocy-desktop

**Comment by mistressofjellyfish** [comment]
Yes, but that's Windows-only AFAICT, electron works cross-plattform on windows / macOS / Linux. Electron can also better speak to Label- and Thermoprinters, without needing webhooks or server-side code. For example, this is the approach taken by the POS system ready2order for communication with printers and cash drawers.

For me personally the appeal would be in some sort of DIY kitchen appliance running Linux without a full browser. But that is certainly not a priority.

**Comment by mistressofjellyfish** [comment]
I think the biggest challenge is not a grocy-related technical one but is probably how to manage translations. There is https://github.com/Polyconseil/easygettext which can parse vue files and compile them back for consumation. Extraction should probably work as-is with vue3, however vue-gettext is, as far as I can tell, vue2 only right now.

vue-i18n unfortunately relys on a key-value approach to localisation, react-i18next has a Trans-Component; neither of which are as elegant as the gettext approach. While it probably needs some glue code to make it work, I think for the prototype I'll use vue-gettext ported to vue3.

Complete page reloads on my DIY kitchen appliance are unfortunately extremly costly, and the UI performance of the inventory/consume/purchase pages suffers from javascript initialization a lot. Improving performance (and reducing page reloads) has become a problem for me, so I'll probably start on those pages and do a PR once I have a MWE.

**Comment by berrnd** [comment]
Closing this as out of scope for this project.
