### ISSUE TITLE
Feature request: Show child items under parent item stock overview

### ISSUE THREAD

**Issue by aqws3** [grocy/grocy#1508]
I would find it very useful if in the parent stock overview view it showed all the stock of child items.

For example, I have recorded many kinds of shampoos, so if I rebuy one their data is individually recorded. Also I have a Parent Product generically called Shampoos, which I show in the Stock overview window and hide all the children to not clutter it all, but now I lost access to manipulate each individual item in case I have consumed it or something else.  They do appear in Stock entries but that is a linear list and not grouped. 

![image](https://user-images.githubusercontent.com/595095/122335999-c4497f00-cf01-11eb-96dd-21718093c371.png)
![image](https://user-images.githubusercontent.com/595095/122336023-cd3a5080-cf01-11eb-8222-b697721e5d47.png)
![image](https://user-images.githubusercontent.com/595095/122336062-dc210300-cf01-11eb-87b8-ed0d578b80ec.png)

**Comment by berrnd** [comment]
Thanks, but that's already requested/tracked in #449.
