### ISSUE TITLE
Product picker popper.js javascript error (only in console, no practical problem)

### ISSUE THREAD

**Issue by mistressofjellyfish** [grocy/grocy#1509]
I came across this as I'm currently working to modularize & modernize the current javascript a bit (which caused a lot of errors out of my own failure). This "bug" however is reproducible with the current implementation. It doesn't seem to have any real impact, but FWIW I'll note it here, even if the sole purpose is that I don't forget this.

Steps to reproduce:

Open Meal Plan -> Add Product -> open dropdown, then this gets logged to console:

```
popper.js:1211 Uncaught TypeError: Cannot read property 'setAttribute' of null
    at Object.onLoad (popper.js:1211)
    at popper.js:2521
    at Array.forEach (<anonymous>)
    at new t (popper.js:2519)
    at t.e.show (dropdown.js:176)
    at t.e.toggle (dropdown.js:126)
    at HTMLSpanElement.<anonymous> (dropdown.js:367)
    at Function.each (jquery.min.js?v=pre-release-fe59fac:2)
    at S.fn.init.each (jquery.min.js?v=pre-release-fe59fac:2)
    at S.fn.init.t._jQueryInterface [as dropdown] (dropdown.js:353)
onLoad @ popper.js:1211
(anonymous) @ popper.js:2521
t @ popper.js:2519
e.show @ dropdown.js:176
e.toggle @ dropdown.js:126
(anonymous) @ dropdown.js:367
each @ jquery.min.js?v=pre-release-fe59fac:2
each @ jquery.min.js?v=pre-release-fe59fac:2
t._jQueryInterface @ dropdown.js:353
(anonymous) @ dropdown.js:519
dispatch @ jquery.min.js?v=pre-release-fe59fac:2
v.handle @ jquery.min.js?v=pre-release-fe59fac:2
```

**Comment by berrnd** [comment]
That's there since ever (as you also noticed, doesn't has any impact) and entirely caused (from what's debuggable) by third party dependencies.

Seems also to happen not only for grocy if you search for this, don't think tracking third party "errors" here is worth it, I personally simply ignore such things (that's not the only one)...

**Comment by mistressofjellyfish** [comment]
Yes, that's what I figured as well. If you want, you can close this; this is more a thing because I'm knee deep in the javascript right now and need to keep track of errors I did not cause.
