### ISSUE TITLE
Repeatable tasks/chores?

### ISSUE THREAD

**Issue by Anroxo** [grocy/grocy#151]
Hi
Is there a way to set tasks/chores to a specific date then repeat every month on the same day? For example every fifth day of the month.

**Comment by berrnd** [comment]
Currently not - there is only the "Period type" "Dynamic regular", which means that the next execution is "scheduled" x days after the last execution.

But can be done added, of course.

**Comment by Anroxo** [comment]
Thank you!

**Comment by ajahart** [comment]
+1 here for trash/recycle day.  happens every monday whether i take it out on sunday, monday or forget

**Comment by berrnd** [comment]
Daily/Weekly/Monthly repetitions are now possible.

Can be tested on the already updated pre-release demo if you want:
https://demo-prerelease.grocy.info/choresoverview
