### ISSUE TITLE
Bug: adding a product to the shopping list from stock overview requires a note

### ISSUE THREAD

**Issue by hannahswain** [grocy/grocy#1514]
When adding an item to a shopping list, a note is required.

![image](https://user-images.githubusercontent.com/17844465/122671325-508bc880-d1c6-11eb-8b98-430abf8b7a5c.png)

On the Stock overview page: after selecting `add product to shopping list`, adding a product to any shopping list requires a note

On the Shopping list page, you can add any product to any list without a note required.

**Comment by berrnd** [comment]
Thanks, but that's already reported in #1289 (and #1438), also already fixed, but not yet released.

Can also be easily verified by trying it on the [pre-release demo](https://demo-prerelease.grocy.info/) like mentioned on the issue template.

**Comment by hannahswain** [comment]
Whoops, sorry about that!
