### ISSUE TITLE
Bug: add product to shopping list > amount disappears

### ISSUE THREAD

**Issue by hannahswain** [grocy/grocy#1515]
When adding a new product to the shopping list (both via Stock overview > Add to shopping list and directly on the shopping list page), the amount is preloaded and then disappears. 

To reproduce on stock overview

1. Open Stock overview
2. In the product dropdown, select "Add to shopping list". 
3. Note that the product is preselected, the amount shows "1" on load, and then disappears. No fields are focused.

To reproduce on shopping list:

1. Open Shopping list page
2. Click "add item", note that "amount" is set to "1"
3. Select a product
4. Cursor / field focus jumps to "amount", which is now empty

Expected behavior: the field is selected with the default amount intact, i.e. 1.

**Comment by berrnd** [comment]
Also that's not the current behaviour when trying this on the [pre-release demo](https://demo-prerelease.grocy.info/).

No related issue, https://github.com/grocy/grocy/commit/791a17fcad8264e8cebdd421993c6f439ceec271 is the related commit, also mentioned on the [preview-changelog](https://grocy.info/changelog#preview).
