### ISSUE TITLE
Feature request: Sum of ingredients in recipes 

### ISSUE THREAD

**Issue by RandomBlue2121** [grocy/grocy#1517]
If all ingredients are in g have the option to total the amount. A further function could be to convert tsp/tbsp/cups etc. to g and give a total number. Would be very helpful for making pre-mixes of flour and weighing the correct amounts into baking tins etc.

**Comment by berrnd** [comment]
Thanks, but that's already requested/tracked in #1132.

**Comment by RandomBlue2121** [comment]
#1132 only asks for part of what I was referring to ie. converting
everything to grams. What I am looking for is a function that would give a
total weight for the whole recipe assuming the whole recipe is now in g. So
if I have a recipe with 100g flour, 50g of milk and 10g of sugar I would be
able to see the total which would be 160g in this case.

**Comment by berrnd** [comment]
> if I have a recipe with 100g flour, 50g of milk and 10g of sugar I would be able to see the total which would be 160g in this case.

And what's the practical useful point about that? Can't remember that I have seen something like that anywhere so far - maybe cooking (or whatever the recipe requires to do with the ingredients) adds or reduces the weight additionally...
