### ISSUE TITLE
Decimal seperators are not consitent

### ISSUE THREAD

**Issue by RandomBlue2121** [grocy/grocy#1518]
The price for recipes has a comma decimal separator whereas the price when purchasing a product uses a period.

**Comment by berrnd** [comment]
Number display is entirely browser locale dependent.

Would be great if you can provide reproducible examples by using the demo instances (like also mentioned on the demo instance).

I took the time to reproduce it and can't see a problem:

[English demo](https://en.demo-prerelease.grocy.info) and English browser (they use dots as the decimal separator):

![grafik](https://user-images.githubusercontent.com/2161815/122886508-51e10080-d340-11eb-8945-31b1f49c867c.png)
![grafik](https://user-images.githubusercontent.com/2161815/122886571-5e655900-d340-11eb-9629-79624a166799.png)

[German demo](https://de.demo-prerelease.grocy.info) and German browser (they use commas as the decimal separator):

![grafik](https://user-images.githubusercontent.com/2161815/122886951-b1d7a700-d340-11eb-9db0-4434d5e4ef73.png)
![grafik](https://user-images.githubusercontent.com/2161815/122886854-9f5d6d80-d340-11eb-9438-d1aa04a277bb.png)

**Comment by RandomBlue2121** [comment]
Thanks for such a quick response. I have just checked in Chrome and it is
correct, it seems like it is a Firefox browser issue.
