### ISSUE TITLE
Bug: All items have no location

### ISSUE THREAD

**Issue by SupremeSports** [grocy/grocy#1525]
After update to 0.13.x, all pre-existing items has no location assigned and I'm unable to set one or to transfer them to a location.
I should at least be able to set one while transferring or changing the inventory
Error message saying "A location is required" and unable to do anything with the item, there's no choices in the drop-down menus

Tried to update to 0.14.0, still same issue

![Location Issue](https://user-images.githubusercontent.com/13887820/123498956-1aed4200-d601-11eb-824f-b662e8a7f992.jpg)

**Comment by berrnd** [comment]
I don't know which version you're refering to, the latest release is v3.0.1...

I can't really imagine that locations get dropped during any update - however please provide reproducible examples, or error logs (browser console, webserver, etc. - like also mentioned on the issue template) - or how should anyone guess what's going on by only having that screenshot? Im at least unable to help by that...
