### ISSUE TITLE
Bug: Unable to consume more than 1 at a time

### ISSUE THREAD

**Issue by SupremeSports** [grocy/grocy#1526]
After update to 0.13.x, unable to consume more than 1 at a time.
In the consume tab, we should be able to consume multiple of the same item (example, used 3 eggs so I consume 3)
Getting the message "This must between 0.0001 and 1 and needs to be a valid number with max. 4 decimal places"

Tried to update to 0.14.0, still same issue

![Consume Issue](https://user-images.githubusercontent.com/13887820/123498997-8cc58b80-d601-11eb-9196-a3c5cb51b1b9.jpg)

**Comment by berrnd** [comment]
Like already said in https://github.com/grocy/grocy/issues/1525#issuecomment-868957951 - don't know what this version should be (maybe the Home Assistant Addon?) and please provide reproducible examples, error logs (like still mentioned on the issue template), etc. if you want to get help.

This is not reproducible on the current [demo](https://demo-prerelease.grocy.info/), this here is the issue tracker - the better place for general help is the [subreddit](https://www.reddit.com/r/grocy) (like [mentioned in README](https://github.com/grocy/grocy#questions--help--bug-reporting--feature-requests)) or for Home Assistant Addon related problems maybe even better their community forum...
