### ISSUE TITLE
Bug: Adding a recipe ingredient via the api with non-stock qu results in wrong amount

### ISSUE THREAD

**Issue by TomRomeo** [grocy/grocy#1528]
I wanted to add an ingredient to a recipe using the Rest API.
In my example this ingredient was sugar but it also worked with other ingredients.

I have two QU conversions:
- 1 Gramm -> 0.001 Kilogramm
- 1 Kilogramm -> 1000 Gramm

For sugar, the _Quantity unit stock_ and _Default quantity unit purchase_ are Kilogramm
I now wanted to add 1 Gramm Sugar to a recipe with a post request to `/api/objects/recipe_pos` and the following json body:
```json
{
  "recipe_id":50,
  "product_id":15,
  "amount":1,
  "qu_id":4
}
```
4 is the qu_id of Gramm so I expected the outcome to be: 1 Gramm in the recipe ingredient section,
however Grocy seems to add the given amount in the default _stock-_ or _purchase unit_ and then visualize it with the qu_id  given.
This results in 1Kg of Sugar being added to the recipe and 1000 Gramm being shown.

![image](https://user-images.githubusercontent.com/60541979/124294798-64d1ad00-db58-11eb-8a73-c809d39d4ac7.png)

Now I am not sure if this is the expected behaviour or if I maybe didn't add the correct parameter to the post body.
I think it would be very practical if one could add an ingredient in a specific QU and the grocy server would convert it if possible.

Did I miss something? Is this a bug or the expected behaviour?

(Also, out of curiousity: What exactly does recipe_pos stand for anyways?)

**Comment by berrnd** [comment]
That's expected, the API does currently no quantity unit conversions anywhere, all amounts are internally (and therefore also for the API) related to products stock QU.

When there is a `qu_id`, that's only used for displaying the amount at the corresponding place.

So all QU conversions need to be currently done client side (the frontend also uses the API for everything and does that, just as a reference if needed),

Also noted in the [v3.0.0 changelog](https://grocy.info/changelog#v3.0.0) (API section at the end).

> (Also, out of curiousity: What exactly does recipe_pos stand for anyways?)

Speaking technically ERP, there is most of the time a document (recipe) which has positions / a position table (recipe ingredients).
