### ISSUE TITLE
Bug: API QR code does not provide enough contrast for scanning in dark mode

### ISSUE THREAD

**Issue by Mearman** [grocy/grocy#1529]
When in built-in dark mode or using an inverter such as Dark Reader, the QR does not maintain a background with enough contrast for scanning.

**Comment by berrnd** [comment]
Right, but also partly depends on your scanner/camera.

And was also already fixed/improved - can be easily verified by trying it on the [pre-release demo](https://demo-prerelease.grocy.info/manageapikeys) like mentioned on the issue template.

**Comment by Mearman** [comment]
Ah perfect. I'll have a look. Thank you
