### ISSUE TITLE
Feature request: Allow stock modifications from the location content sheet page

### ISSUE THREAD

**Issue by lyz-code** [grocy/grocy#1532]
I use the location content sheet to check that the inventory is correct. When I find some product whose quantity is wrong, I have to:

* Switch to the stock overview/consume/inventory tab
* Select the product
* Change the amount
* Switch back to the content sheet tab
* Find where I was

Instead, it would be awesome to be able to change the quantity directly in the location content sheet page. Maybe with an interface similar to the stock overview with the quick consume, with an optional quick addition.

I've tried using the stock overview itself, filtering by the location, but the problem comes when a product has two locations. Then you see the total amount of all locations instead of just the ones in the selected one.

An alternative solution could be that only the products of that location are shown in the stock overview, and that whenever you quick consume, you do so from that location without taking into account the first in, first out rule of general consuming.

**Comment by berrnd** [comment]
The location content sheet is optimized to be printed, so buttons and things not really fit there...

I think your request is already covered in #682, and/or #1387 and/or #1188 - feel free to add more ideas there.

**Comment by lyz-code** [comment]
Yes, those three features will solve my case. Sorry for not being able to realize it with the issue search I did

**Comment by berrnd** [comment]
> Sorry for not being able to realize it with the issue search I did

Absolutely no problem... :)
