### ISSUE TITLE
Feature request: Scanning / importing shopping receipts 

### ISSUE THREAD

**Issue by gohlin** [grocy/grocy#1533]
It would be great to be able to scan paper receipts (or import e receipts) from the grocery store which is then used to update the inventory. I imagine this isn’t super easy, but there are some great tools out there. Maybe a cooperation/integration  would be an option. 
this is the best I have used so far, in terms of recognizing and categorizing items: https://apocha.de/

**Comment by berrnd** [comment]
Thanks, but that already requested in #404 - please check existing requests before opening new ones.
