### ISSUE TITLE
Bug: iPhone: Grocy interrupts Music

### ISSUE THREAD

**Issue by michaelschramel** [grocy/grocy#1536]
Hello,
when I go shopping: 
 - I listen to music on an iphone 
 - I open my grocy instance on a vpn
 - my music stops
Is there a way to stop this from happening? 
Thanks

**Comment by berrnd** [comment]
grocy is a web application, so therefore runs in your browser and is therefore very limited (to available browser APIs what to do with your device - and there is definitely nothing "about music" what grocy does...

If you maybe use any of the companion apps, this is the wrong repo.

**Comment by QGgWW2WhH** [comment]
fYI: I still notice this behaviour with safari and grocy website- no app
