### ISSUE TITLE
Detailed Manual

### ISSUE THREAD

**Issue by smellsox** [grocy/grocy#1538]
Hello. Can you please write/create a detailed manual for installing Grocy on raspberry Pi? i know theres a version on an external site, but there are old PHP versions for example..

Just a noob friendly manual.

Thx

**Comment by berrnd** [comment]
Please use the [subreddit](https://www.reddit.com/r/grocy) for general help as [mentioned in README](https://github.com/grocy/grocy#questions--help--bug-reporting--feature-requests).

See [grocy.info/links](https://grocy.info/links) or [grocy/docs](https://github.com/grocy/docs) or https://www.reddit.com/r/grocy/comments/ka1hy5.

All of that is not maintained by me.
I would highly recommend using something like the [Docker Images](https://github.com/grocy/grocy#how-to-run-using-docker), [grocy-desktop](https://github.com/grocy/grocy-desktop) or the [Home Assistant integration](https://github.com/hassio-addons/addon-grocy), if you're not so familiar with setting up webservers. grocy is definitely technically a pretty simple PHP application, so any tutorial for setting up those will basically fit. Nothing has changed (beside the package names) between PHP 7 and 8.
