### ISSUE TITLE
Updating to 3.1.0

### ISSUE THREAD

**Issue by smellsox** [grocy/grocy#1539]
Hello. I have a problem after updating a well working version from 3.0.1 to 3.1.0 with the update.sh.

After installing, when i want to open my webserver with ip adress, i get the following error: 

Unable to run grocy: PHP module 'intl' not installed, but required.

Tried to update to PHP8 and Installing the Intl module, but still not working

**Comment by berrnd** [comment]
This is the issue tracker, so (again) please use the [subreddit](https://www.reddit.com/r/grocy) for general help like mentioned on the issue template and [in README](https://github.com/grocy/grocy#questions--help--bug-reporting--feature-requests).

The [v3.1.0 changelog](https://grocy.info/changelog#v3.1.0) clearly mentiones that there are additionally required PHP extensions (like `intl` as mentioned in your error message) for that release, so no real suprise that it doesn't run without having those installed...
