### ISSUE TITLE
Put missing products on shopping list, bug?

### ISSUE THREAD

**Issue by vitogit** [grocy/grocy#154]
In the recipe page when I "Put missing products on shopping list" I want to add all ingredients even if they already are on the shopping list, but currently if they are in the shopping list it will not be added.

Example: I have 2 recipes that uses 500g meat each, when I enter both recipes to the shopping list, then the shopping list should show 1000g, but currently is showing 500g.

Not sure if bug or I have to configure something.
version 1.24.1 docker image.

**Comment by berrnd** [comment]
Yes, currently only the difference (the amount which is not already on the shopping list) is added. 

https://github.com/grocy/grocy/issues/125#issuecomment-450545748 will be a working solution also for this, I think.

**Comment by vitogit** [comment]
Thanks for the workaround. I think by default it shouldn't check agains the shopping list when adding a recipe, just check the stock. But maybe I'm missing some special case. In that case another option:
- A setting to not check against the shopping list when adding a recipe. 
- Or A checkbox per recipe to not check against the shopping list

**Comment by berrnd** [comment]
I added now an option per recipe to not check the missing amount against the shopping list.

If you want, you can test this out on the already updated [pre-release demo](https://demo-prerelease.grocy.info/recipes), if this works for you that way.

Let me know if you have further ideas on this. :)
