### ISSUE TITLE
Feature request: Packlist for travelling

### ISSUE THREAD

**Issue by akemper** [grocy/grocy#1545]
In addition to the shopping list it would be nice to also have a packing list for traveling integrated / available on web and mobile. Initially I tried to reuse a newly created shopping list for this, but this seems to be overall too complex / not adequate in terms of e.g.

* Items can't be easily created
* No special pool for these items exists
* Not sure if it could separate individual and common items (for a family trip)

Are there any plans to add something like this in the (near) future or any hints on how to "reuse" existing shopping lists for this?

Thx
Andreas

**Comment by berrnd** [comment]
Please have a look at Userobjects and Userfields (ref #176 and #242 or [website](https://grocy.info/#user-defined-fields)) - you can already define any custom lists with any custom fields/columns you want.

Demo: https://demo.grocy.info/userobjects/exampleuserentity
