### ISSUE TITLE
Bug: Two errors in en_GB translation

### ISSUE THREAD

**Issue by wralb** [grocy/grocy#1549]
**Note:** I have created a Transifex account and made changes to fix this issue there, my changes work when I manually incorporated the translation file in to my Grocy instance. 

**Reproduction:**

1. Set Grocy language to en_GB
2. Pull up a product overview
3. See screenshot below and note two pairs of incorrect, confusing, duplicate labels.

![image](https://user-images.githubusercontent.com/47241942/126970989-4cd2eaec-b361-46f7-aa35-dc44fde10c15.png)

**Cause:**
I found issues in https://github.com/grocy/grocy/blob/master/localization/en_GB/strings.po

At line 1796:

Incorrect:

msgid "Stock value"
msgstr "Stock amount"

Should be:

msgid "Stock value"
msgstr "Stock value"

At line 1799:

Incorrect:

msgid "Average price"
msgstr "Average shelf life"

Should be:

msgid "Average price"
msgstr "Average price"

**Comment by berrnd** [comment]
Thanks, but translations are not maintained here, they are entirely managed via Transifex like [mentioned in README](https://github.com/grocy/grocy#localization). Everyone can translate/fix everything there.

I've updated those two mentioned strings.
https://www.transifex.com/grocy/grocy/translate/#en_GB/strings/297977892

**Comment by berrnd** [comment]
> Note: I have created a Transifex account and made changes to fix this issue there, my changes work when I manually incorporated the translation file in to my Grocy instance.

Sorry, missed that - so every is already done, no need to raise a bug for that here, all translations are included/updated in the next release.
