### ISSUE TITLE
Feature Request: Maintence log for equipment

### ISSUE THREAD

**Issue by scubieman** [grocy/grocy#155]
Could you do some kind of maintence log for equipment?

Like Fridge change water filter in 3 months.

or Change furnance filter in 6 months

Clean disher washer etc ?

**Comment by berrnd** [comment]
Maybe just use Chores or Tasks for this?

**Comment by berrnd** [comment]
Closing this for now, feel free to reopen it if Chores or Tasks are not enough for your use case.
