### ISSUE TITLE
Bug: Openldap authentication 

### ISSUE THREAD

**Issue by politas** [grocy/grocy#1551]
I was very pleased to discover that OpenLDAP support has just recently been added, just as I come to install Grocy. I have Grocy 3.1.0 running in a docker container, using the linuxserver.io image, and if I run with the DefaultAuthMiddleware setting, it is working fine. Unfortunately, when I switch the config over to LdapAuthMiddleware, I can't authenticate any accounts, even my original Admin account.

Here's the relevant parts of my config.php file:
```
Setting('AUTH_CLASS', 'Grocy\Middleware\LdapAuthMiddleware');
 
// LDAP options when using LdapAuthMiddleware
Setting('LDAP_ADDRESS', 'ldap://domain.tld:389');
Setting('LDAP_BASE_DN', 'dc=domain,dc=tld');
Setting('LDAP_BIND_DN', 'cn=readonly,dc=domain,dc=tld');
Setting('LDAP_BIND_PW', 'password that has been tested and works');
Setting('LDAP_USER_FILTER', 'ou=People');
Setting('LDAP_UID_ATTR', 'uid');
```
I have also tried with a blank `LDAP_USER_FILTER`, with no change. 

I've tested that I can connect to the OpenLDAP service from within a docker container, and I've also tried to use the grocy-docker image, setting the LDAP configuration in the env file, with no success.

Checking my openldap logs, I don't see any attempt to connect from grocy at all.

**Comment by berrnd** [comment]
@tank0226 added that in #1380, maybe he can help for that.

Personally don't run an OpenLDAP server anywhere so would need to create a test environment first to be able to verify/debug that at all...

**Comment by politas** [comment]
I have discovered that enabling unauthenticated searching on my OpenLDAP server and removing the BIND settings works.

**Comment by politas** [comment]
I think what's needed at the very least is to capture the error message from the LDAP_BIND attempt and log it if the connections fails to error.log?

**Comment by Gsyltc** [comment]
Problem for me too 👍 

```
// Either "Grocy\Middleware\DefaultAuthMiddleware", "Grocy\Middleware\ReverseProxyAuthMiddleware"
// or any class that implements Grocy\Middleware\AuthMiddleware
Setting('AUTH_CLASS', 'Grocy\Middleware\LdapAuthMiddleware');

// When using LdapAuthMiddleware
Setting('LDAP_DOMAIN', '');
Setting('LDAP_ADDRESS', 'ldap://my_open_ldap_server:389'); 
#Setting('LDAP_BASE_DN', '');
Setting('LDAP_BASE_DN', 'ou=users,dc=my-domain,dc=com');
Setting('LDAP_BIND_DN', 'cn=MyBinderUser,dc=my-domain,dc=com');
Setting('LDAP_BIND_PW', '**********************');
Setting('LDAP_USER_FILTER', '');
Setting('LDAP_UID_ATTR', 'uid');
```

This configuration is use for other services without problem.

Error log on openldap
```
61072682 conn=1272 fd=12 ACCEPT from IP=10.0.3.30:53994 (IP=0.0.0.0:389)
61072682 conn=1272 op=0 do_bind: invalid dn (\myuser)
61072682 conn=1272 op=0 RESULT tag=97 err=34 text=invalid DN
61072682 conn=1272 op=1 UNBIND
```

Thanks

**Comment by daufinsyd** [comment]
Hi @politas 
I justed deployed the latest linuxserver's image yesterday and it works fine (with openldap/univention).
```
Setting('AUTH_CLASS', 'Grocy\Middleware\LdapAuthMiddleware');
                       
Setting('REVERSE_PROXY_AUTH_HEADER', 'REMOTE_USER');

// When using LdapAuthMiddleware
Setting('LDAP_ADDRESS', 'ldap://<server>:7389'); // Example value "ldap://vm-dc2019.local.berrnd.net"                                  
Setting('LDAP_BASE_DN', 'my DC'); // Example value "OU=OU_Users,DC=local,DC=berrnd,DC=net"                                
Setting('LDAP_BIND_DN', 'DN of the SA'); // Example value "CN=grocy_bind_account,OU=service_accounts,DC=local,DC=berrnd,DC=net"
Setting('LDAP_BIND_PW', 'PWD'); // Password for the above account                                         
Setting('LDAP_USER_FILTER', ''); // Example value "(OU=grocy_users)"
Setting('LDAP_UID_ATTR', 'uid'); // Windows AD: "sAMAccountName", OpenLDAP: "uid", GLAuth: "cn"
```
Works also behind a proxy.
I hope it can help.

**Comment by politas** [comment]
> Hi @politas
> I justed deployed the latest linuxserver's image yesterday and it works fine (with openldap/univention).

Yeah, seems they've fixed it somehow. @Gsyltc, are you using the linuxserver.io image, too?

**Comment by Gsyltc** [comment]
Hello, 
Yes, I use the linuxserver.io image. But I haven't tested the new image yet.
Maybe tomorrow or at the end of the week.

I will update after my tests

**Comment by Gsyltc** [comment]
Hello, 
I have a problem with the linuxserver container version 3.1.0 (I was using 3.0.1 until yesterday).
The database seems to be correct (MariaDB), I have all my data. But no data on stock pages. No recipe lists but I have the details of the first recipe in the site.

Has the structure of the database changed? Is it a bug on my side?
If I go back to version 3.0.1, everything is ok

I am looking at the problem. As soon as it is solved, I will test the ReverseProxy.

thanks

**Comment by berrnd** [comment]
Please keep it to one topic per request, everything else is unhandable.

This here is about that LDAP authentication / OpenLDAP seems to have (probably) problems which I will personally verify before closing this.

> Has the structure of the database changed?

Of course the database schema changes from release to release, that what [migrations](https://github.com/grocy/grocy/tree/master/migrations) are for. No manual steps are required and of course this should not result in broken pages. If you've found another reproducible problem, please open a separate request.

> The database seems to be correct (MariaDB)

I doubt it, grocy exclusively uses SQLite and is not capable of using any different database system at the moment.

**Comment by Gsyltc** [comment]
> Hi @politas
> I justed deployed the latest linuxserver's image yesterday and it works fine (with openldap/univention).
> 
> ```
> Setting('AUTH_CLASS', 'Grocy\Middleware\LdapAuthMiddleware');
>                        
> Setting('REVERSE_PROXY_AUTH_HEADER', 'REMOTE_USER');
> 
> // When using LdapAuthMiddleware
> Setting('LDAP_ADDRESS', 'ldap://<server>:7389'); // Example value "ldap://vm-dc2019.local.berrnd.net"                                  
> Setting('LDAP_BASE_DN', 'my DC'); // Example value "OU=OU_Users,DC=local,DC=berrnd,DC=net"                                
> Setting('LDAP_BIND_DN', 'DN of the SA'); // Example value "CN=grocy_bind_account,OU=service_accounts,DC=local,DC=berrnd,DC=net"
> Setting('LDAP_BIND_PW', 'PWD'); // Password for the above account                                         
> Setting('LDAP_USER_FILTER', ''); // Example value "(OU=grocy_users)"
> Setting('LDAP_UID_ATTR', 'uid'); // Windows AD: "sAMAccountName", OpenLDAP: "uid", GLAuth: "cn"
> ```
> 
> Works also behind a proxy.
> I hope it can help.

Works fine with LDAP now.
But unable to connect with ReverseProxy/SSO (Authelia). [#1563 ](https://github.com/grocy/grocy/issues/1563#issue-961424248)

**Comment by politas** [comment]
Ok, it's a downstream issue, then. Closing Issue.
