### ISSUE TITLE
Feature request: Make the default best before date configurable

### ISSUE THREAD

**Issue by dkruzic** [grocy/grocy#1552]
It would be nice to configure the default best before time shown on the "New Product" page. E.g. you could set the default to 1 year or to "never expires" depending what's most common and adjust it only when needed.

**Comment by berrnd** [comment]
Is there really a "most common" due date which _really_ makes sense between minced meat and any tin can? I doubt it, but ok, let's at that to ["Presets for new products"](https://demo-prerelease.grocy.info/stocksettings#productpresets).

**Comment by corbolais** [comment]
Second that. Most products we use are best before a year later (or even more) in most cases anyway (preppers need this kind of stuff too ;-). When applicable, I'll modify that date.
