### ISSUE TITLE
Feature request: Barcode for Recipes

### ISSUE THREAD

**Issue by antontrummer** [grocy/grocy#1562]
is it possible to add a barcode to Recipes, so that i can search by barcode?

Example: I have a Recipe  for more Units (like 10 glasses of Marmelade…) . And if i would make the recipe later again, i can scan the barcode of the last glass, and i get the recipe.

Or is there a existing way ?

**Comment by berrnd** [comment]
> Or is there a existing way ?

Not yet, everything is technically possible to be added.

**Comment by antontrummer** [comment]
> > Or is there a existing way ?
> 
> Not yet, everything is technically possible to be added.

Thank you. 

I will look „deeper“ , cause i will it not use for Food and cooking recipes, but for Cosmetics raw materials and (nature)cosmetics recipes.   But its almost the same :-) 

So it will be fine, if i get an empty jar from my mom back, what i made her a time before, if i can scan the code and so i have the recipe fast for refill it for her .
