### ISSUE TITLE
Bug: External barcode lookup does not add product

### ISSUE THREAD

**Issue by orestismers** [grocy/grocy#1568]
Api call to api/stock/barcodes/external-lookup/{barcode}?add=true returns error 
"SQLSTATE[HY000]: General error: 1 table products has no column named barcode"

After manually adding column 'barcode' to the table, products can be added however no barcode appears under 'Barcodes'

**Comment by berrnd** [comment]
External barcode lookup happens only via plugins, no plugin is shipped with grocy ([README ref](https://github.com/grocy/grocy#barcode-lookup-via-external-services)).

However, adding the barcode (via the `add=true` query parameter) is not up to the plugin, so is of course a bug which will be fixed.

How barcodes are stored has recently changed, they are now stored in a separate table `product_barcodes`.
[v3.0.0 changelog](https://grocy.info/changelog#v3.0.0) excerpt:
> ### API improvements/fixes
> - ⚠️ **Breaking changes**:
>   - The product object no longer has a field barcodes with a comma separated barcode list, instead barcodes are now stored in a separate table/entity `product_barcodes` (use the existing "Generic entity interactions" endpoints to access them)

&nbsp;

> After manually adding column 'barcode' to the table, products can be added however no barcode appears under 'Barcodes'

So you add random column to a table and expect working functionality? Interesting idea...

**Comment by orestismers** [comment]
Thanks for adding it.
Of course wasn't expecting it to work! Was just curious what would happen if the request went through...
