### ISSUE TITLE
some kind of export

### ISSUE THREAD

**Issue by mbattistini** [grocy/grocy#1571]
Please add some kind of export readable offline, csv, pdf, text file, the database backup is one thing, a printable and immediately readable offline backup is another!

Thanks

**Comment by berrnd** [comment]
Duplicate of #129 - checking existing requests before opening new ones (like mentioned on the feature request template) would be great.

**Comment by mbattistini** [comment]
seen, but I think it is right to reiterate the concept again.

thanks.
