### ISSUE TITLE
Bug: Userfields in /api/objects/products incorrect

### ISSUE THREAD

**Issue by D3v01dZA** [grocy/grocy#1572]
When using multiple userfields on a product and querying the API endpoints the /api/objects/products and /api/objects/products/{id} return different values. It seems that the first userfield is duplicated in all subsequent userfields in the aggregate API.

The setup for these two userfields (if it matters) is that TestOne is a multi-line text field and TestTwo is a single-line text field.

Note on this API TestOne and TestTwo have the same value of TestOne in both cases (the TestTwo value should be TestTwo)
![Aggregate API](https://user-images.githubusercontent.com/10627822/128903539-d4c88293-2c1f-4874-afc2-cfc2e50d84d4.png)

This API returns the correct values
![Single API](https://user-images.githubusercontent.com/10627822/128903531-09217dac-61a9-4216-b9de-173399340829.png)

**Comment by berrnd** [comment]
Demo instance for easier reproducibility (like also mentioned on the issue template): https://test-hed1lfgoyabd9ugw1ziy6b.demo-prerelease.grocy.info

Single object `GET`s:
[`/api/objects/products/1`](https://test-hed1lfgoyabd9ugw1ziy6b.demo-prerelease.grocy.info/api/objects/products/1)
[`/api/objects/products/2`](https://test-hed1lfgoyabd9ugw1ziy6b.demo-prerelease.grocy.info/api/objects/products/2)

Multiple objects `GET`:
[`/api/objects/products?query[]=name~DEBUG`](https://test-hed1lfgoyabd9ugw1ziy6b.demo-prerelease.grocy.info/api/objects/products?query%5B%5D=name~DEBUG)

So far not reproducible there by the given details.
Feel free to tweak that demo instance to be able to reproduce it.

**Comment by berrnd** [comment]
> So far not reproducible there by the given details.

Sorry, seems that I was blind - is reproducible, the _first Userfield per object_ seems to be duplicated in the multiple objects `GET`.

**Comment by D3v01dZA** [comment]
My apologies, I clearly skimmed the bug submission incorrectly. I see you reproduced it and this is exactly what I was referring to, where each object has the same field value repeated for all keys, for completeness here is a reproduction on my side as well!

https://test-kxm3y25wbbjsie94gkjtd.demo-prerelease.grocy.info/api/objects/products
https://test-kxm3y25wbbjsie94gkjtd.demo-prerelease.grocy.info/api/objects/products/27
