### ISSUE TITLE
Bug: When logging seeing stock overview page

### ISSUE THREAD

**Issue by nandantumu** [grocy/grocy#1574]
Please describe the bug as detailed as possible, provide the steps how to reproduce it and maybe attach screenshots where useful.
When loading stock overview on login to grocy, I get an error message in the top right that expands to this:
```
"{\"error_message\":\"SQLSTATE[23000]: Integrity constraint violation: 19 UNIQUE constraint failed: user_settings.user_id, user_settings.key\"}"
```
Please also check if your bug was maybe already fixed by searching closed issues here or by trying to reproduce your problem on the [pre-release demo](https://demo-prerelease.grocy.info/) (use a *private demo instance* if you want to make your example persistent).

**Comment by heinrich-ulbricht** [comment]
I upgraded from Grocy <3 to 3.1.0 via the update.sh and got said error as well on clicking "Chores overview".
```
"{\"error_message\":\"SQLSTATE[23000]: Integrity constraint violation: 19 UNIQUE constraint failed: user_settings.user_id, user_settings.key\"}"
```

**Comment by berrnd** [comment]
So unless it's reproducible (on a (private) demo instance, like mentioned on the issue template) I really don't know how to debug that or how to help.

Most probably not a real problem - a duplicate user setting was tried to be added/saved, it was not saved at the end, should not hurt in any case.
