### ISSUE TITLE
Calendar event with section from mealplan

### ISSUE THREAD

**Issue by tikismoke** [grocy/grocy#1582]
Great work for all this.

Due to section add in the mealplan i would propose you to add section name in the calendar event.

I create 4 section for each meal (matin/midi/gouter/diner) (sorry for french...)
I think it would be nice to see those section in the ics calendar event (actually event are for the whole day).

Eventually event should be time related (maybe add in the section too!) but it's another story.

**Comment by berrnd** [comment]
Thanks for the idea, that's now done, including the time part for the calendar:

New optional meal plan section option "Time":

![grafik](https://user-images.githubusercontent.com/2161815/153040014-d332b74b-fe72-4a31-9240-a2f14c7cdc54.png)

That time is then display on the meal plan:

![grafik](https://user-images.githubusercontent.com/2161815/153040117-4d22b67d-d019-4938-8920-1f232a7a9d5f.png)

And is also used for the calendar event time:

![grafik](https://user-images.githubusercontent.com/2161815/153040432-345942db-bac1-473e-a8e3-ffac8b90d91b.png)

**Comment by tikismoke** [comment]
Whouah so nice
