### ISSUE TITLE
Bug: Environment Variables not overriding config.php

### ISSUE THREAD

**Issue by Germs2004** [grocy/grocy#1586]
Grocy 3.1.0
LinuxServer/Grocy docker image - latest as of 8/17/21

When I add "GROCY_FEATURE_FLAG_BATTERIES" as an environment variable in my docker-compose file, it fails to actually hide the batteries features inside Grocy.

If I change the "FEATURE_FLAG_BATTERIES" setting in config.php from true to false, then the batteries features are hidden.  The comments in the config.php file say that the environment variable should work as a higher priority than the config.php, but it doesn't seem to be working.  I tried setting GROCY_FEATURE_FLAG_BATTERIES to "false" with and without quotes, and "0", but none of the 3 values had an effect.  I ran "env" inside the docker container and confirmed that my environment variables appear in the list.

**Comment by berrnd** [comment]
Haven't tried it myself lately (will do it of course before closing this), however, the code ref below clearly takes care of handling environment variables as a precedence:

https://github.com/grocy/grocy/blob/61a58ddef0378c0493ead07c03279151d73cd3e5/helpers/extensions.php#L176-L180

Personally don't have that much experience with Docker at all (too much magic and too much restrictions for me most of the time), but starting a process (the webserver/PHP runtime) doesn't necessarily mean it inherits (any or) the current environment.

Have a look at linuxserver/docker-grocy#12, especially at https://github.com/linuxserver/docker-grocy/issues/12#issuecomment-768858965 which seems to be about exactly what I have mentioned before.

**Comment by Forceu** [comment]
Yes, by default Nginx clears all environment variables, therefore Grocy is unable to parse them. As berrnd said, you could change the nginx configuration to add `clear_env = no` in oder to have them parsed.

**Comment by Germs2004** [comment]
Good find, sorry I missed that.  I tried the `clear_env = no` fix, and it worked perfectly after restarting the docker container.  It sounds like LinuxServer is responsible for that file since nginx is part of their docker image, so I'll add an Issue over there suggesting they include the fix by default.  Thank you.
