### ISSUE TITLE
Purchase price rounds to 0

### ISSUE THREAD

**Issue by samdowrick** [grocy/grocy#1588]
When i "purchase" a product on Grocy it will change the price to 0 if i put in a value less than 1. I.E. 0.50 changes to 0.00 when addedd. Can anyone help me?

**Comment by berrnd** [comment]
Would be great if you can provide a reproducible example (so the exact steps, private [demo](https://demo.grocy.info) instances are the best way to do this).

Just tried to reproduce it, works there (current [pre-release demo](https://demo-prerelease.grocy.info) instance):

https://user-images.githubusercontent.com/2161815/129932144-27d2f186-6787-455e-9537-fa87c8640acd.mp4

This here is the issue tracker (so for reproducible bugs or feature request), the better place for general help is the [subreddit](https://www.reddit.com/r/grocy) like [mentioned in README](https://github.com/grocy/grocy#questions--help--bug-reporting--feature-requests). [Seems](https://www.reddit.com/r/grocy/comments/p6tkbf) that you already did that, don't really get what double posting brings...

**Comment by samdowrick** [comment]
Sorry for the double post, I thought I would try developers and the local community. It's a fresh install with no changes to ant of the configuration files. I've attached a video of the issue. Not sure whys this is happening.
 https://user-images.githubusercontent.com/5497143/129970332-8585cacf-c017-4178-80f2-ba3b8bcd85b8.mp4

**Comment by berrnd** [comment]
Sorry, again: Can't really help without all the details (there is more, the product, the quantity units, and so on), private demo instances are exactly for that an easy way to share those scenarios - however, some guessing in the dark:

Prices are tracked per stock quantity unit.
- Product "Carrot Battons" has a stock QU "Gram"
- You purchase 1 Pack
- The QU conversion is 1 Pack = 300 Grams
- 1 Pack costs 0.50
- => 1 Gram costs 0.50 / 300 = 0.0016666666666667
- => Your "Decimal places allowed for prices" [stocksetting](https://demo-prerelease.grocy.info/stocksettings) is set to 2 (default)
- => 0.0016666666666667 is rounded to those 2 decimal places = 0.00

That's only solvable by having a reasonable amount of decimal places (change the stocksetting if needed) if you really need that detail.
