### ISSUE TITLE
[Feature Request] iOS Webicon

### ISSUE THREAD

**Issue by aptonline** [grocy/grocy#159]
When saving the Grocy page as a bookmark on iOS the following icon is used (webview)
![784470e6-96be-4658-995a-6344d9fc680d](https://user-images.githubusercontent.com/190136/53658838-dda36000-3c51-11e9-9e39-49de016aba1b.jpeg)

The best solution would be to show an app icon using the code on the following page.

https://developer.apple.com/library/archive/documentation/AppleApplications/Reference/SafariWebContent/ConfiguringWebApplications/ConfiguringWebApplications.html

**Comment by berrnd** [comment]
Should be no problem, the only problem is maybe the icon itself - we currently only have [those two](https://github.com/grocy/grocy/tree/master/public/img) which maybe will not look that good in a rounded square...

**Comment by aptonline** [comment]
I’d be happy to provide an iOS compatible version. iOS auto adds the rounded corners.

**Comment by berrnd** [comment]
You're very welcome. :)

Feel free to add it just here or create a pull request.

**Comment by berrnd** [comment]
I just added the tag with the existing icon, maybe you can do a quick check with already updated [pre-release demo](https://demo-prerelease.grocy.info) to see how it looks...

**Comment by aptonline** [comment]
Not showing when adding the pre-release Demi to homescreen.

**Comment by aptonline** [comment]
Here’s 2 alternatives. They need to be added as png.

![68edb45f-6bdd-49c8-a235-d50d7aecbe50](https://user-images.githubusercontent.com/190136/53671910-51586380-3c78-11e9-8265-01328d56434a.png)
![ed1ac89f-1e18-4ffc-952c-c241c5cee5cd](https://user-images.githubusercontent.com/190136/53671911-51f0fa00-3c78-11e9-9bbd-78abab8d3929.png)

**Comment by berrnd** [comment]
Thank you.

I now used [realfavicongenerator.net](https://realfavicongenerator.net/) to hopefully cover them all, not only iOS/Safari.

If you want, you can do a quick test with the [pre-release demo](https://demo-prerelease.grocy.info) again.
