### ISSUE TITLE
Bug: sub product of accumulated parents can have non-zero minimum stocks

### ISSUE THREAD

**Issue by Kritzefitz** [grocy/grocy#1595]
Given the correct steps, it is possible to create two products — one parent product with one sub product — where the sub product has a non-zero minimum stock amount even though “Accumulate sub products min. stock amount” is checked on the patent product. The steps are as follows:

1. Create the product “sub”
    1. set the minimum stock amount to some non-zero value (e.g. 3)
2. Create the product “parent”
    1. Set the minimum stock amount to some non-zero value (e.g. 5)
    2. Check “Accumulate sub products min. stock amount”
3. Go back to the definition of “sub” and set “parent” as the parent product

Now “sub” will still have its original minimum amount set. This has some strange side effects on the shopping list. If you add products below minimum stock to the shopping list when the stock is empty, the sum of both minimum amounts will be added (so in the example above 8). If stocks are present, the amount added to the shopping list depends on the type of the present stocks. Each unit of “parent“ will be counted once against the minimum stock while each unit of “sub” will count both against its own minimum stock and against that of the parent, so it is counted twice against the total minimum stock. To extend the example above, if you have 1 “sub” and 1 “parent” in stock, 5 units will be added to the shopping list.

I'm not entirely sure if this is really a bug. But the behavior is at least very unintuitive. Also the fact that the input field for minimum stock amount is disabled when you add a parent with accumulation really suggests that such products aren't supposed to have a non-zero minimum stock amount.

I prepared this situation in [this demo instance](https://test-yhm84ryitch5qmjwl2hnlg.demo-prerelease.grocy.info/stockoverview)

**Comment by berrnd** [comment]
Reference about how it's upposed to work: https://github.com/grocy/grocy/issues/1409#issuecomment-873613515

So the solution for this would be to simply set the childs `Minimum stock amount` to 0 when `Accumulate sub products min. stock amount` on the parent is set.

...however intuitiv such a pretty deep-detail thing could be, if you need something like that, you need to take care of your data/definitions, UI sugar may help (like disabling the min. stock amount field on childs recently), but generally most of the things are always based on the good old EDV Prinzip "scheiße rein, scheiße raus" at the end...
