### ISSUE TITLE
Bug: Add all list items to stock workflow breaks midway.

### ISSUE THREAD

**Issue by tjhowse** [grocy/grocy#1596]
Probably related to #1248 and #1310. Reproduced on my local instance and on the demo instance.

Repro:
Add things to shopping list - at least 6.
Click "Add all list items to stock".
Complete the form and click "OK" for each stock item.
Clicking OK greys out the fields, adds the items to stock and shows a green message in the top right of the window confirming the addition. It will then proceed to the next item on the list.
After a few (3-5) items, clicking OK will grey out the fields, add the item to stock and show a green message in the top right, but it will not proceed to the next item in the list. Clicking "Skip" or "OK" again has no visible effect. Reloading the page is required to resume adding shopping list items to stock.

Console error thrown after clicking "OK" and triggering this bug.:
```
Uncaught TypeError: $(...)[(Grocy.ShoppingListToStockWorkflowCurrent - 1)] is undefined
    <anonymous> https://grocy.tjhowse.com/viewjs/shoppinglist.js?v=3.1.1:306
    jQuery 2
        dispatch
        handle
shoppinglist.js:306:6
    <anonymous> https://grocy.tjhowse.com/viewjs/shoppinglist.js?v=3.1.1:306
    jQuery 2
        dispatch
        handle
```

This can happen with or without grouping enabled on the shopping list.

Browser: Firefox 91.0.2 on Windows 10.

My local instance (v3.1.1, running in docker, image: ghcr.io/linuxserver/grocy):
![image](https://user-images.githubusercontent.com/1008081/131602939-e52d2d55-00f2-49b2-b362-376675885e24.png)

Demo instance:
![image](https://user-images.githubusercontent.com/1008081/131603400-19c2b5d5-2970-42e5-8439-43b4e926997f.png)

**Comment by berrnd** [comment]
Fixed by #1599.
