### ISSUE TITLE
Unable to connect icalshare

### ISSUE THREAD

**Issue by ITguy3118** [grocy/grocy#1603]
Getting the error below via the ical share link 

Issue seems to be similar to #1569. I am using php 8.0. I started out on version 3.1.0 (didn't work there either) and updated via the update.sh script to 3.1.1. I am able to add the calendar via the demo. I am able to add the calendar, just simply no entries populate. 

{"error_message":"Call to undefined function Eluceo\\iCal\\Presentation\\mb_strcut()","error_details":{"stack_trace":"#0 [internal function]: Eluceo\\iCal\\Presentation\\ContentLine->__toString()\n#1 \/var\/www\/html\/shreddergrocy\/vendor\/eluceo\/ical\/src\/Presentation\/Component.php(55): implode()\n#2 \/var\/www\/html\/shreddergrocy\/vendor\/slim\/http\/src\/Response.php(357): Eluceo\\iCal\\Presentation\\Component->__toString()\n#3 \/var\/www\/html\/shreddergrocy\/controllers\/CalendarApiController.php(52): Slim\\Http\\Response->write()\n#4 \/var\/www\/html\/shreddergrocy\/vendor\/slim\/slim\/Slim\/Handlers\/Strategies\/RequestResponse.php(43): Grocy\\Controllers\\CalendarApiController->Ical()\n#5 \/var\/www\/html\/shreddergrocy\/vendor\/slim\/slim\/Slim\/Routing\/Route.php(384): Slim\\Handlers\\Strategies\\RequestResponse->__invoke()\n#6 \/var\/www\/html\/shreddergrocy\/vendor\/slim\/slim\/Slim\/MiddlewareDispatcher.php(81): Slim\\Routing\\Route->handle()\n#7 \/var\/www\/html\/shreddergrocy\/middleware\/JsonMiddleware.php(13): Slim\\MiddlewareDispatcher->handle()\n#8 \/var\/www\/html\/shreddergrocy\/vendor\/slim\/slim\/Slim\/MiddlewareDispatcher.php(209): Grocy\\Middleware\\JsonMiddleware->__invoke()\n#9 \/var\/www\/html\/shreddergrocy\/vendor\/slim\/slim\/Slim\/MiddlewareDispatcher.php(81): Psr\\Http\\Server\\RequestHandlerInterface@anonymous->handle()\n#10 \/var\/www\/html\/shreddergrocy\/vendor\/slim\/slim\/Slim\/Routing\/Route.php(341): Slim\\MiddlewareDispatcher->handle()\n#11 \/var\/www\/html\/shreddergrocy\/vendor\/slim\/slim\/Slim\/Routing\/RouteRunner.php(84): Slim\\Routing\\Route->run()\n#12 \/var\/www\/html\/shreddergrocy\/middleware\/LocaleMiddleware.php(16): Slim\\Routing\\RouteRunner->handle()\n#13 \/var\/www\/html\/shreddergrocy\/vendor\/slim\/slim\/Slim\/MiddlewareDispatcher.php(313): Grocy\\Middleware\\LocaleMiddleware->__invoke()\n#14 \/var\/www\/html\/shreddergrocy\/middleware\/AuthMiddleware.php(76): Psr\\Http\\Server\\RequestHandlerInterface@anonymous->handle()\n#15 \/var\/www\/html\/shreddergrocy\/vendor\/slim\/slim\/Slim\/MiddlewareDispatcher.php(313): Grocy\\Middleware\\AuthMiddleware->__invoke()\n#16 \/var\/www\/html\/shreddergrocy\/vendor\/slim\/slim\/Slim\/Middleware\/RoutingMiddleware.php(59): Psr\\Http\\Server\\RequestHandlerInterface@anonymous->handle()\n#17 \/var\/www\/html\/shreddergrocy\/vendor\/slim\/slim\/Slim\/MiddlewareDispatcher.php(147): Slim\\Middleware\\RoutingMiddleware->process()\n#18 \/var\/www\/html\/shreddergrocy\/vendor\/slim\/slim\/Slim\/Middleware\/ErrorMiddleware.php(107): Psr\\Http\\Server\\RequestHandlerInterface@anonymous->handle()\n#19 \/var\/www\/html\/shreddergrocy\/vendor\/slim\/slim\/Slim\/MiddlewareDispatcher.php(147): Slim\\Middleware\\ErrorMiddleware->process()\n#20 \/var\/www\/html\/shreddergrocy\/middleware\/CorsMiddleware.php(30): Psr\\Http\\Server\\RequestHandlerInterface@anonymous->handle()\n#21 \/var\/www\/html\/shreddergrocy\/vendor\/slim\/slim\/Slim\/MiddlewareDispatcher.php(313): Grocy\\Middleware\\CorsMiddleware->__invoke()\n#22 \/var\/www\/html\/shreddergrocy\/vendor\/slim\/slim\/Slim\/MiddlewareDispatcher.php(81): Psr\\Http\\Server\\RequestHandlerInterface@anonymous->handle()\n#23 \/var\/www\/html\/shreddergrocy\/vendor\/slim\/slim\/Slim\/App.php(215): Slim\\MiddlewareDispatcher->handle()\n#24 \/var\/www\/html\/shreddergrocy\/vendor\/slim\/slim\/Slim\/App.php(199): Slim\\App->handle()\n#25 \/var\/www\/html\/shreddergrocy\/app.php(106): Slim\\App->run()\n#26 \/var\/www\/html\/shreddergrocy\/public\/index.php(45): require_once('...')\n#27 {main}","file":"\/var\/www\/html\/shreddergrocy\/vendor\/eluceo\/ical\/src\/Presentation\/ContentLine.php","line":31}}

**Comment by berrnd** [comment]
Please provide a reproducible way (steps to get this, recreated the situation on a private demo instance, or, if all fails, feel free to send me your database) like mentioned on the issue template. I'm happy to help but I'm really unable to guess all the things.

However, I have briefly asked my sphere glass (aka checked the first search result for `PHP mb_strcut missing`):
`mb_strcut` is part of the [`mbstring` extension](https://www.php.net/manual/en/book.mbstring.php), so most likely that's missing on your system.

**Comment by ITguy3118** [comment]
The steps I am taking is...
Going to Calendar
Selecting the Share/Integrate claendar (iCal) button
Copying the link 
then going to my outlook.com e-mail address  ( i am not able to add it on my outlook client, which is fine since i can add it to the outlook.com address and sync it with the client just the same), the calendar is added successfully, but no entries populate. 

If i go to the address that is provided via the share/integrate calendar (Ical) button, i get the error mentioned previously. 

I am not able to reproduce this from the demo as previously mentioned, it works fine there, just not on my instance.

**Comment by berrnd** [comment]
I quote myself from my last comment above:

> However, I have briefly asked my sphere glass (aka checked the first search result for `PHP mb_strcut missing`):
`mb_strcut` is part of the [`mbstring` extension](https://www.php.net/manual/en/book.mbstring.php), so most likely that's missing on your system.

### So have you checked that?

&nbsp;
> Question, It looks like you made have made a code adjustment. If i run the update.sh script, will i be able to receive the change you made to be able to test if this is working now?

I can't install things on your machine, the added thing (like mentioned on the commit message) was to check also for the `mbstring` extension before running the application.

> If i run the update.sh script, will i be able to receive the change you made to be able to test if this is working now?

Of course not before before a new release drops. And without checking why `mbstring` is missing on your system, this would just result in slightly different error message...

**Comment by ITguy3118** [comment]
```
I quote myself from my last comment above:

However, I have briefly asked my sphere glass (aka checked the first search result for PHP mb_strcut missing):
mb_strcut is part of the mbstring extension, so most likely that's missing on your system.

So have you checked that?
```

Provide steps on how to check

**Comment by ITguy3118** [comment]
nevermind, I figured it out. You didn't give me the answer, but gave me a clue.
