### ISSUE TITLE
Check boxes for ingredients

### ISSUE THREAD

**Issue by RandomBlue2121** [grocy/grocy#1606]
I find that following online recipes is always easier with check boxes next to the ingredients so that I don't miss adding anything.

**Comment by berrnd** [comment]
So something like the checkmark on the shopping list where the line/item get then striked through?

![grafik](https://user-images.githubusercontent.com/2161815/132868460-63c87040-64c3-46a7-be15-f9232d65099c.png)

And when should this be reset?
Or maybe not saving that so it can only be used as long as the page is open?

**Comment by RandomBlue2121** [comment]
Yes something like that, it could be reset when the "consume" button has
been clicked on for the recipe.

**Comment by berrnd** [comment]
There is now this new recipes setting (defaults to disabled):

![grafik](https://user-images.githubusercontent.com/2161815/161338799-f8f3ee77-aaf6-4ec4-9a23-fc9fcf73034d.png)

When enabled, a little checkbox is shown next to each ingredient and when clicked, the ingredient will be crossed out.

![grafik](https://user-images.githubusercontent.com/2161815/161338961-f2ce1fbd-9221-4f87-b4d7-45e71c1dc90f.png)

This is not saved (means reset on page reload).

Hope that fits.
