### ISSUE TITLE
Feature Request: Ability to add locations on demand

### ISSUE THREAD

**Issue by horphi0815** [grocy/grocy#1607]
It would be great, to get a dropdownlist, where you can add instant new values, if the available are not met your expectations.
This new added value will be stored in the dropdown selection and can also be removed by changing the master dropdown settings.

Dropdown:
 - blue
 - red
 - [add additonal value]

**Comment by berrnd** [comment]
And for what/where exactly?

We already have this for products (enter something unknown on purchase/transfer/consume/shoppinglist and there will be a popup with several options) - techincally not so super easy, and I doubt all other master data objects are needed to be added so often...

Related to #584.

**Comment by horphi0815** [comment]
For instance in the Productmanagement.
We make inventory check, then the guy scan the products in the storage racks. We have sometimes new racks and new drawer. Then he choul easily scan the rack or drawer to assign the product.

**Comment by berrnd** [comment]
Sorry, ich verstehs nicht ganz - am einfachsten wäre es, wenn bitte einfach ein konkretes Beispiel beschreibst wo (auf welcher Seite) was passieren soll...

Also auf der [/intenvory Seite](https://de.demo.grocy.info/inventory) nicht nur einen Standort auswählen, sondern direkt neue hinzufügen können?

**Comment by horphi0815** [comment]
> Sorry, ich verstehs nicht ganz - am einfachsten wäre es, wenn bitte einfach ein konkretes Beispiel beschreibst wo (auf welcher Seite) was passieren soll...
> 
> Also auf der [/inventory Seite](https://de.demo.grocy.info/inventory) nicht nur einen Standort auswählen, sondern direkt neue hinzufügen können?

Genau, ich habe im Dropdown die Angelegten Lagerfächer (Boxen) P-1-1, P-1-2, P-1-3, P-2-1, P-2-2 ....
Wenn jetzt einer im Lager Inventur macht, oder neue Ware hnizupackt und dabei neue Fächer anlegt (P-1-4, P-2-3 usw...), welche vorher nicht da waren, dann würde es helfen, die einfach direkt einzugeben/barcode zu scannen. 
Aber alternativ könnte man das Feld Standort einfach als Freitextfeld machen, da alle Fächer Barcode haben und irekt gescannt werden. Ginge das?

**Comment by berrnd** [comment]
Ok, danke - also genauso wie #584, nur für Standorte.

Technisch ist sowas meistens ein bisschen aufwändiger (wie bei Products), denn es ist ja eben kein Freitext, sondern ein "Master Data Objekt" dahinter - natürlich könnte man wahrscheinlich irgendwie Freitext zulassen und dann den Standort halt einfach mal mit dem eingegebenen Text anlegen im Hintergrund...

Hört sich auch eher nach Business use case an, grocy ist für daheim ausgelegt - dort ändern sich, würde ich mal behaupten, die Standorte/Schubladen/Whatever nicht so wirklich häufig, zumindest wüsste ich nicht, wann ich selbst zuletzt einen angelegt hätte in meiner grocy Instanz...

**Comment by berrnd** [comment]
grocy targets home usage.

A product location is a cupboard, a shelf, a shelf compartment, a fridge or whatever you define it to be.
In any case, those definitions don't change day by day.

The above provided examples clearly target a business use case, which is out of scope for this project.
