### ISSUE TITLE
Bug: Consume/Transfer context menu items on stock overview are greyed out when stock amount < 1

### ISSUE THREAD

**Issue by berrnd** [grocy/grocy#1609]
_Originally reported here: https://www.reddit.com/r/grocy/comments/plmlvj_

Example: https://test-3latwexy7k6bpjxlsyl6.demo-prerelease.grocy.info (product "Eggs")

**Comment by lepouletfou2** [comment]
why you delete the spoiled Option?
Or did that happen by mistake?

**Comment by berrnd** [comment]
> why you delete the spoiled Option?

Because it messes up the menu (how it was there / including the product name) and was fixed to consume `1` and I don't think this is needed (or should be needed) very often. And least that's based on my personal daily use of grocy. You can still simply use `Consume` from the context menu and set the `Spoiled` checkbox there.

**Comment by lepouletfou2** [comment]
My why was more on a technical level: whether removing this option has anything to do with the bug closed here.

Thereby I know now, that here 2 completely different things were mixed with each other.
