### ISSUE TITLE
Support languages with more than 2 plural forms

### ISSUE THREAD

**Issue by ASMfreaK** [grocy/grocy#161]
I'm translating grocy to russian ATM.
There are string that can't be translated into russian cleanly. 

Example:
```
1 Pack
2,3,4... Packs
```
can't be translated using only two plural forms as in english, as russian has 3 different plural forms.
It **should** be translated like this:
```
1,21,31,41,n1 Упаковка
2,3,4,22,23,24,32,33,34,n2,n3,n4 Упаковки
5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,25,26,27,28,29,n5,n6,n7,n8,n9 Упаковок
```
Otherwise it looks awful:
```
1 Упаковка
1 Упаков(ки/ок)
```

Please use [ngettext](http://php.net/manual/en/function.ngettext.php) from gettext or other translation frameworks that uses this function.

**Comment by berrnd** [comment]
We have no need for pluralization of the translation strings.
Except for demo data, which your example with Pack/Packs is from.

The only place where pluralization is handled is for quantity units, which is not part of the translation strings, but is defined by the user in master data configuration ([see an example](https://demo-prerelease.grocy.info/quantityunit/3)). So there needs the third plural form to be added and then handled accordingly.

**Comment by berrnd** [comment]
Hm, have never worked with `gettext` in PHP so far, but I cannot see how to use without `PO` files...

As said, we would only need it for properly displaying quantity units (amounts of products).

Also there seem to be languages with even more than 2 plural forms, `ngettext` only handles 2 (or I have missed something).

If you know a (PHP) library or any other way how to handle this properly, let me know.

**Comment by ASMfreaK** [comment]
The counterexample is:
```
#1 products expiring within the next #2 days
```
Here days can be in at least two plural forms.

**Comment by berrnd** [comment]
Your right, but that (the "header bars" on the overview pages) and quantity units are the only places where plularization is needed (so far). Because quantity units are always user defined (and therefore saved in the database), I think `ngettext` enough...

Oh, almost forgot: Thank you! for translating grocy into russian! :)

**Comment by ASMfreaK** [comment]
> Also there seem to be languages with even more than 2 plural forms, ngettext only handles 2 (or I have missed something).

`ngettext` is defined in terms of *default English language* i.e. with 2 plural forms. Other forms are defined in po files.

Example (copied from [ngettext doc](http://php.net/manual/en/function.ngettext.php))
file.po:
```po
...
"Plural-Forms: nplurals=3; plural=n%10==1 && n%100!=11 ? 0 : n%10>=2 && n%10<=4 && (n%100<10 || n%100>=20) ? 1 : 2;\n"
...
msgid "File"
msgid_plural "Files"
msgstr[0] "Файл"
msgstr[1] "Файла"
msgstr[2] "Файлов"
...
```

file.php
```php
...
echo ngettext("File", "Files", $number);
...
```

There is a certain pipeline in using gettext. There are tools (`xgettext`, `msginit`, `msgmerge`, `msgfmt`) to search for gettext and ngettext invocations, create, update and compile po files. The very significant downside of gettext is that it requires a compiled binary format to work AFAIK.
I solve this in my python projects by storing binary mo files alongside the non-compiled po [example](https://github.com/ASMfreaK/habitipy/tree/master/habitipy/i18n/ru/LC_MESSAGES), which is not ideal, but makes it portable, I hope.
You can see the pipeline in the [makefile](https://github.com/ASMfreaK/habitipy/blob/master/Makefile)

**Comment by ASMfreaK** [comment]
As far as I can see, there is a [nice framework](oscarotero/Gettext) for that in php

**Comment by ASMfreaK** [comment]
Another example of a place in need of an ngettext:
```
This means it is estimated that a new execution of this chore is tracked #1 days after the last was tracked
```
`days` can be both plural and not.

**Comment by berrnd** [comment]
Thanks for the input.

I see the advantages of gettext and the tools around it, so let's do this anytime soon.
Also the support on Transifex seems to be better and that translations in PO files can have comments looks nice.

We need to convert the currently used [PHP-Array-files](https://github.com/grocy/grocy/tree/8020f92d6b18a720823e47e7cc2dc6daba551807/localization) to PO files (maybe can also be done with the help of [oscarotero/Gettext](https://github.com/oscarotero/Gettext)). I would prefer to use the library to load PO files directly without having to install the gettext extension, to keep system dependencies small ([seems to be possible](https://github.com/oscarotero/Gettext#translator)).

Should be doable, all localization functionality is already implemented in a single class [LocalizationService.php](https://github.com/grocy/grocy/blob/8020f92d6b18a720823e47e7cc2dc6daba551807/services/LocalizationService.php) - so hopefully the only place which will need changes for this.

**Comment by berrnd** [comment]
This is now mostly done. :)

I migrated everything to use gettext, both server and client side.
Including migrating all current translations on Transifex.
Hopefully not everything is now broken and no translations got lost...
(There is a backup of all translations and the alorithm used for the migration in https://github.com/grocy/grocy/commit/6ceb6e3643f6d8ec4e306ea332fbf50ed5ac5360 and https://github.com/grocy/grocy/commit/40b5afe9269a333db6e69348db69c3aeaf70c2e3.)

The next step is to change/combine the translation strings for proper pluralizations via gettext.
Found no way to do this automatically with the current translations, so need to be done by hand and will involve some retranslations, but shouldn't be that much strings...

**Comment by ASMfreaK** [comment]
Ping me, when there'll be a version on Transifex, I'll try to help with russian and other european languages.

**Comment by berrnd** [comment]
It's now finished! :)

I combined all strings which need pluralization, results in about 20 strings (excluding demo data) which need to be (re)translated for all languages on Transifex.

There is one special thing:
Quantity units are not part of translation files (only for the demo), but defined by the user. This is now handled internally also as a PO file. So there is a new field on the quantity unit edit page and the fields map to PO fields like in the annotated screenshot below:

![grafik](https://user-images.githubusercontent.com/2161815/57097675-a1a37e80-6d18-11e9-9691-bdfc8b08368c.png)


Feel free to report any problems about this, or if there any plural strings missing, here.

**Comment by Maczuga** [comment]
With all the translations changed - we now lost a possibility to rearrange the order of input values (previously `#1 #2 #3` etc.). In Polish language - some translations must have those params in different order. Without that those would just sound bad.

Example:
![image](https://user-images.githubusercontent.com/544349/57189669-8cde0b00-6f11-11e9-81aa-6a2829c63965.png)

**Comment by berrnd** [comment]
Sure, sorry, it's the first time I used gettext, so seems to be possible, like [that](https://stackoverflow.com/a/7674084).

I reopen this issue to track this.

**Comment by berrnd** [comment]
All strings with more than 1 placeholde now have named placeholders.
