### ISSUE TITLE
Bug: If a barcode QU is empty no bookings possible

### ISSUE THREAD

**Issue by lepouletfou2** [grocy/grocy#1619]
Hi,

If a barcode does not contain a unit of quantity, this "empty" unit of quantity will be applied when booking.

This will make the unit of quantity field invalid and nothing can be booked.

I have found the cause myself: Since this release the barcode column "qu_id" in the SQL table is no longer "null" but empty.
This would fix it (or you create the "null" in the SQL column again).

https://github.com/grocy/grocy/blob/5563e7ed4c714a3121e0f922badb28bfd6d8784c/public/viewjs/purchase.js#L352-L353

change the Line 352 to:

`if (barcode.qu_id != null && !barcode.qu_id.isEmpty())`

Have a nice day ;)

**Comment by berrnd** [comment]
The mentioned extended check doesn't hurt, however:

> Since this release the barcode column "qu_id" in the SQL table is no longer "null" but empty

This situation can't be produced by using the frontend, there are two ways to add barcodes:
- Product edit page
  => A quantity unit is enforced
- "Add as barcode to existing product" productpicker workflow: 
  => The `qu_id` column is `null`

**Comment by lepouletfou2** [comment]
> This situation can't be produced by using the frontend, there are two ways to add barcodes:

I am talking about the barcode assigned units of quantity.

Just go to the product edit page and add a barcode. You don't have to add a unit of quantity to this barcode then.

In the past "null" was used in the SQL. Since this release the row in the column is empty. (Column `qu_id` in the `Product_Barcodes` Table)
