### ISSUE TITLE
Make it possible to specify a recipe: for how many people it is

### ISSUE THREAD

**Issue by simongavris** [grocy/grocy#162]
As a grocy user I want to be able to add products for a recipes for x people to the shopping list if they are not in storage. 
For this i would need to:
- specify for how many people one recipes is
- enter for how many people I want to cook the recipe

**Comment by berrnd** [comment]
I think this should be covered by https://github.com/grocy/grocy/issues/127#issuecomment-469018469.

The changes from there are not yet released, maybe check it out on the pre-release demo, if this fits your needs:
https://demo-prerelease.grocy.info/recipes

**Comment by simongavris** [comment]
thanks thats exatcly it! My bad for not checking closed issues. I found one bug with the feature though (see comment on original Issue)

**Comment by berrnd** [comment]
You're welcome - absolutely no problem. :)

...and thanks for testing!
