### ISSUE TITLE
Feature request: Return Add Picture at Product Creation

### ISSUE THREAD

**Issue by cryptodendrum** [grocy/grocy#1620]
First off, I've been using grocy since the nearly the start of CoronaTimes in 2020.  I was journeying down the Excel spreadsheet approach & came across your story of something similar before you backed up and rebooted your effort as Grocy.  I've been super please and loved nearly every revision / version update since then.  And we have thousands of food products entered into our DB now, and routinely add 5-20 new products with almost every trip to the grocery stores.

However, I think with the migration from 2.7 to 3 at the start of the year, I noticed an important feature to our workflow disappeared - the ability to add a picture at the Product Creation (either via BarcodeBuddy or direct in Grocy).  At first, I thought it was a bug and just lived with it, assuming it would be fixed.   And we've been working around with editing the product after creation, and adding the picture there.   

But to keep this up to date, it takes extra effort and time, and we've not been so good about doing this always.  I just came upstairs to my desktop (because as an extra step, it's faster to do on a desktop than an iPad which we have in the kitchen) and saw we had accumulated over 100 backlog of edits I have to go make just from the last few weeks.

I read the reason (in another post filed as a Bug) that it has to do with the ID of the parent object and understand this technical reason, but is there a way to work around this restriction - maybe with a Temp ID that gets replaced with the Parent ID upon and after the saving of the product record?   

We'd really welcome having our original one-step workflow of creating product records, if at all possible.

Thanks in advance, and thanks for everything you've done so far!

**Comment by cryptodendrum** [comment]
Just a further thought about your comment to the bugfix that was filed for this same feature (copying and pasting your comment here just for reference) and a possible work around that could be applied in the code.

> It's not about the picture particularly, it's the same for any dependent object and therefore behaves the same for barcodes  and QU conversion overrides (and default QU conversions and recipe ingredients/pictures/included recipes). A technical thing (the id of the parent object need to be known for any dependent object, but that id is only created after a product was once saved).

What if behind the scenes when the user presses the button to ADD Product (or via BcodeBuddy's Create Product) this actually goes ahead and creates and saves a new record stub and Parent ID right away and starts a 15 minute timer.
Once the user has populated all the data in the Add Product form & a new picture, this instead just updates the record as an edit and kills the timer.    However, if the user clicks Cancel, the new record stub gets deleted, and kills the timer.  But if the user hits the BACK button in the browser or navigates away from the New Product form, then after 15 minute timer expires, the record will automatically be deleted by the timer expiring. 

I'm not a php coder (but I do code) so was thinking this spitball idea might be feasible in php to do.

**Comment by berrnd** [comment]
This references #1379, I already basically said there that I won't change that due to keep it technically rather simple.

Of course technically everything is doable somehow, so let's leave this open - everyone can work on it - this is Open Source, doesn't have to be me (however, the idea about a dummy product for every /new page load + a timer is a really bad one, sorry).

> But to keep this up to date, it takes extra effort and time

It's one extra click on `Save & continue` before adding the picture, so this click must take a lot of time...

**Comment by cryptodendrum** [comment]
> Of course technically everything is doable somehow, so let's leave this open - everyone can work on it - this is Open Source, doesn't have to be me (however, the idea about a dummy product for every /new page load + a timer is a really bad one, sorry).

Was a spitball idea of a possible solution; figured it was better to postulate on possible solutions / workarounds than nothing at all.

How did it work before up to 2.7?

>  It's one extra click on Save & continue before adding the picture, so this click must take a lot of time...

Well actually, when we try to do this on our Kitchen iPad (an older generation model - we only use it for grocy now) through BarcodeBuddy, the Save & Continue closes the window, and takes us back to BarCodeBuddy.  So then we have to go hunt down the same product in Products view, open that up, add picture, save and close and switch back to BarCode buddy.   On our first Gen iPadAir in the kitchen, this takes an additional approx 3+ minutes. Times that against 5-15 new products my wife comes home with on every shopping trip, yeah, it adds up.

But, okay - there we go, maybe it's possible to add a SAVE & REFRESH button next to the SAVE & CONTINUE button?  So to prevent it from closing the window & returning to BcodeBuddy?

**Comment by berrnd** [comment]
I had a look into this just now - done in https://github.com/grocy/grocy/commit/7aa9e5748ed01a9d77a961bbf2dfe8733c99f351.
&nbsp;

> How did it work before up to 2.7?

Just like now, the code is here and the reference (more or less only the file name is saved in a field of the the product object).

> So to prevent it from closing the window & returning to BcodeBuddy?

I don't know what Barcode Buddy does...

> On our first Gen iPadAir in the kitchen, this takes an additional approx 3+ minutes

So loading the /products page + (maybe) searching + editing a product takes 3 minutes? Wow, I just don't understand why people are happy to use such slow devices... ;D

**Comment by cryptodendrum** [comment]
> Wow, I just don't understand why people are happy to use such slow devices... ;D
*raises fist to sky* "Curse you Apple updates & planned obsolesce!"

Thanks for sorting that! And again, thanks for the great project!
