### ISSUE TITLE
Feature request: Ingredients are not correctly transferred to the shopping list if they are already on it

### ISSUE THREAD

**Issue by Lacsap93** [grocy/grocy#1621]
Hello I am new here and must immediately apologize for my non-existent knowledge of English. For the translation of this text, the Internet has helped me. Therefore I have added the German version of the text below.

Suppose I need 1 carrot for a recipe and I add it to the shopping list. Then I need another carrot for another recipe and I add it to the shopping list as well, then at the end there is only one carrot on the shopping list instead of two. Is it possible to change this in the settings or is there a trick? The "problem" can also be reproduced in the demo version by adding the Bolognese sauce twice to the shopping list, but at the end there is only one package instead of two on the shopping list.

*DEUTSCH*
Angenommen ich benötige 1 Karotte für ein Rezept und ich füge diese der Einkaufsliste hinzu. Dann benötige eine weitere Karotte für ein anders Rezept und füge diese auch dem Einkaufszettel hinzu, dann steht am Schluss auf dem Einkaufszettel nur eine Karotte anstelle von zwei. Kann man das in den Einstellungen ändern oder gibt es da einen Trick? Das "Problem" kann man auch in der Demoversion nachvollziehen, indem man zweimal die Sauce Bolognese zum Einkaufszettel hinzufügt, am Schluss aber nur eine Packung anstelle von zwei auf dem Einkaufszettel stehen.

Greetings Lacsap93

**Comment by berrnd** [comment]
Recipe stock fulfillment checking currently happens only on per recipe level - already tracked in #840 to enhance that (and also related to #925 and #1122). Please check existing requests before opening new ones.

//

Bestandsprüfungen laufen bis jetzt ausschließlich pro Rezept - ist bereits in #840 aufgeschrieben, das irgendwie zu erweitern (siehe auch #925 und #1122). Bitte schau über die bereits vorhandenen Anfragen bevor neue aufmachst.
