### ISSUE TITLE
Chore does not automatically change assignment after its done

### ISSUE THREAD

**Issue by mracreep** [grocy/grocy#1630]
I can set Chore Assignment Type to alphabetic or who did it the least times, but when i execute the Chore it doesnt change the Assigned Person to the next one... 
Is this a bug or just not implemented yet? :)
I checked open issues but i only saw ones complaining about not having this feature at all, they seem to be outdated now?

**Comment by berrnd** [comment]
The assignment type `Who least did first` would of course assign the same person again and again, if this one is still the one who have the least executions tracked (exactly how it's described).

Would be great if you can provide a reproducible example (like also mentioned on the issue template which you obviously kind of ignored...).

I did that, here is demo instance: https://test-u42ukcb0pv4iathlugnx8.demo.grocy.info/choresoverview
And I can't see a problem there...

**Comment by mracreep** [comment]
Ah ok, your example helped me how to setup the chores correctly, thanks :)
Now it works for me too.

Sry for ignoring the issue template, it honestly didnt show up to me, who knows what i did wrong there...
