### ISSUE TITLE
Feature Request: Include timezone in iCal events (Outlook compatibility)

### ISSUE THREAD

**Issue by ITguy3118** [grocy/grocy#1637]
Getting this error message regarding the battery section when connecting grocy to outlook...the rest of the calendar seems to update fine. 

![10-03-2021 -  14_54_00 - Grocy - Internet Calendars - Outlook](https://user-images.githubusercontent.com/90217713/135769491-d5633f01-93d0-49f9-8a76-efdb9eb4d754.png)

**Comment by ITguy3118** [comment]
Looks like it still populates the entry...just gives an error during the update/sync
![10-03-2021 -  15_17_07 - Grocy - Internet Calendars - Outlook](https://user-images.githubusercontent.com/90217713/135770144-2cf3c93a-61a9-47b8-a5ec-03723a418775.png)

**Comment by berrnd** [comment]
Sorry, but this here is not the Outlook issue tracker and I guess Outlook is also not the reference regarding the definition of the iCalendar format...

This "error" probably means the start and end date (`DTSTART`, `DTEND`) does not include a timezone. The iCal standard definition ([ref](https://datatracker.ietf.org/doc/html/rfc5545#page-33)) allows that, grocy currently doesn't handle timezone information anywhere (related to #214).

So if, then more an enhancement to include the (server) timezone in the rendered iCal file.

**Comment by berrnd** [comment]
And ok, let's track here to make it Outlook compatible...

**Comment by berrnd** [comment]
Fun fact:
The [icalendar.org Validato](https://icalendar.org/validator.html)r doesn't complain:

https://icalendar.org/validator.html?url=https://demo-prerelease.grocy.info/api/calendar/ical

![grafik](https://user-images.githubusercontent.com/2161815/136076644-7ab1f5c5-ea84-48cc-9e43-a32f6d53cb12.png)
