### ISSUE TITLE
Feature request: Ability to use tab / shift + tab to (un)indent list

### ISSUE THREAD

**Issue by matejdro** [grocy/grocy#1638]
Currently, grocy uses a bit unusual `Ctrl + [`, `Ctrl + ]` shortcuts to indent/unindent the list item.

Could we have a way to remap this to `Tab` to indent and `Shift + Tab` to unindent, which is standard in most text editors?

**Comment by berrnd** [comment]
Guessing your refering to the WYSIWYG editor (for example on the [recipe page](https://demo.grocy.info/recipe/1) for "Preparation" or the "Description" on the [product edit page](https://demo.grocy.info/product/1):

The component used for that editor is [Summernote](https://summernote.org/) - so mabye request that there: https://github.com/summernote/summernote

**Comment by matejdro** [comment]
Made an issue: https://github.com/summernote/summernote/issues/4157
