### ISSUE TITLE
Feature Request: Camera barcode scanning: Support Samsung S20+ camera selection

### ISSUE THREAD

**Issue by StevenJonSmith** [grocy/grocy#1642]
When trying to scan a product barcode using a Samsung S20+ the app loads the main wide angle camera, I assume due to distrotion, this camera is unable to read any barcodes.

When I try to change the active camera, the dropdown menu shows 4 avaliable, but they all return the same error when selected. See the screenshots below.
[Avaliable cameras](https://photos.app.goo.gl/wa7LQCHHzF93LYVs7)
[Initial error notifications](https://photos.app.goo.gl/sGHeKYxG6oTh5ytP6)
[Error from "More details"](https://photos.app.goo.gl/xwuJmDJfoTydGuge7)

I am using the Chrome browser on the device, but I tried the Tor browser (a secured Firefox) however this doesn't show any avaliable cameras (I think due to the extra security). I have given access to cameras in Chrome, and Grocy is served via Nginx with SSL.

I tried the Quagga [test page](https://serratus.github.io/quaggaJS/examples/live_w_locator.html) on the same device and it has the sameissue with the wide camera, but does allow me to change camera which then reads barcodes without issue.

**Comment by berrnd** [comment]
Reporting the same thing twice (#1634) brings out exactly what? 🙄

> I tried the Quagga [test page](https://serratus.github.io/quaggaJS/examples/live_w_locator.html) 

QuaggaJS is not [quagga2](https://github.com/ericblade/quagga2).

&nbsp;

However, if it makes you happy, let's leave this open.
grocy does nothing specific for a Samsung S20+, neither for any other device.
In fact, it doesn't handle the barcode scanning part itself, it's the component used.

So still not really the right place and most probably only solvable/debuggable by someone having that device, so that won't be me.

**Comment by berrnd** [comment]
I've searched a little bit for you and found ericblade/quagga2#351 with exactly that specific problem and suggesting to remove the `facingMode` constraints.

So to try this out, simply remove or comment out line 71 of `public/viewjs/components/barcodescanner.js` ([that one](https://github.com/grocy/grocy/blob/master/public/viewjs/components/barcodescanner.js#L71), and double check that your browser isn't caching it after modifying it).

**Comment by StevenJonSmith** [comment]
> Reporting the same thing twice (#1634) brings out exactly what? 🙄

Sorry didn't realise I could still reply to the first bug, I assumed as it was closed I couldn't update it.

> QuaggaJS is not [quagga2](https://github.com/ericblade/quagga2).

I will look at this, as I didn't realise.

> I've searched a little bit for you and found ericblade/quagga2#351 with exactly that specific problem and suggesting to remove the facingMode constraint.

Thanks you beat me to it, I will give that a go and report back.

**Comment by StevenJonSmith** [comment]
> So to try this out, simply remove or comment out line 71 of `public/viewjs/components/barcodescanner.js` ([that one](https://github.com/grocy/grocy/blob/master/public/viewjs/components/barcodescanner.js#L71), and double check that your browser isn't caching it after modifying it).

Unfortunately this didn't work. I'll have a look and see if I can work anything out.

**Comment by berrnd** [comment]
`window.localStorage.getItem('cameraId')` holds the last used camera (id) and uses that again the next time.

So the only real change about that all is the first point about line 71 (like already mentioned before and in the referenced upstream issue), which clearly does that - allowing/showing any camera. In contrast, `facingMode: "environment" ` requests (or should request) the default back camera ([Web API ref](https://developer.mozilla.org/en-US/docs/Web/API/MediaTrackConstraints/facingMode), [caniuse ref](https://caniuse.com/mdn-api_mediatrackconstraints_facingmode)).

However, that's pretty clear still either an upstream issue, or (rather) a specific issue with that device. So closing that here, feel free to share that also on the [subreddit](https://www.reddit.com/r/grocy).
