### ISSUE TITLE
Case sensitivity issue with node modules

### ISSUE THREAD

**Issue by ioangogo** [grocy/grocy#165]
I just had a issue(and fixed it) where the UI was looking for `/node_modules/tagmanager/tagmanager.js` but couldnt find it because the path on the file system was `/node_modules/TagManager/tagmanager.js`

I fixed it by renaming the file, but that is a tempory fix

this is the errors that appear in the console in firefox when visiting the demo page
```
Loading failed for the <script> with source “https://demo-en.grocy.info/node_modules/moment/locale/x.js?v=2.0.0”. stockoverview:1274:1
Loading failed for the <script> with source “https://demo-en.grocy.info/node_modules/tagmanager/tagmanager.js?v=2.0.0”. stockoverview:1286:1 
```

**Comment by berrnd** [comment]
Thanks, will correct this.

The other issue about `https://demo-en.grocy.info/node_modules/moment/locale/x.js?v=2.0.0` is that here Moment.js needs no translation file for English, the untranslated string is `x` - so not a real problem, but also not beautiful - will also fix that...
