### ISSUE TITLE
Please state the minimum required PHP version

### ISSUE THREAD

**Issue by ASMfreaK** [grocy/grocy#166]
I can confirm grocy does **not** work with PHP 7.0 because of some dependencies, namely `Tuupola\Middleware\CorsMiddleware` which requires at least 7.1 see ([ this comment ](https://github.com/tuupola/cors-middleware/issues/21#issuecomment-412864168) )

**Comment by berrnd** [comment]
Right, we also had this in #8 and #53.

It's stated in README that currently everything is only tested against PHP 7.2:
https://github.com/grocy/grocy#how-to-install

I personally don't see a problem with this and don't want to "optimize" anything by not using never PHP features - having multiple versions of PHP on the same machine is not a real problem, when needed, in my opinion. Also I would say the larger number of users are running grocy with [grocy-docker](https://github.com/grocy/grocy-docker) (me **not** included), which uses PHP 7.2 anyway...
