### ISSUE TITLE
Bug: Black text labels on the context/more-menus in dark mode

### ISSUE THREAD

**Issue by barbax7** [grocy/grocy#1662]
In dark mode some text labels are black, so they are a bit unreadable.
![image](https://user-images.githubusercontent.com/66796758/140070914-a0c340ac-4b93-4f2f-b549-6b360eb50679.png)

**Comment by berrnd** [comment]
Most probably something about your browser, looks like that on Chrome and Firefox:

![grafik](https://user-images.githubusercontent.com/2161815/140094479-b1eb76e5-4d05-4425-8c3f-82ad95e1e47e.png)

(Or you're using an old version, there were some general night mode improvements in v3.1.0.)

**Comment by barbax7** [comment]
I'm using 3.1.2 version, installed with grocy-docker, and i'm talking about menù opened pressing the three dots on a product, not about the left side menù

![image](https://user-images.githubusercontent.com/66796758/140095961-0b3dbe49-41cf-4b3a-8c64-1b25f5d524e1.png)

Maybe now is more clear

**Comment by berrnd** [comment]
Sorry, missed that without any further notice from the screenshot...

**Comment by barbax7** [comment]
Don't  worry, my fault. I thought that the icons in the previous screenshot were enough to understand which menu I was talking about

**Comment by corbolais** [comment]
Have a look at https://github.com/grocy/grocy/pull/1664 :)
Haven't seen this issue before PR'ing, what a lucky one..

**Comment by barbax7** [comment]
> Have a look at https://github.com/grocy/grocy/pull/1664 :)
> Haven't seen this issue before PR'ing, what a lucky one..

oh, funny ahahah
