### ISSUE TITLE
Feature Request: Unique grocycodes for "Label per unit"

### ISSUE THREAD

**Issue by anwright** [grocy/grocy#1676]
_**EDIT by @berrnd, TODO for this request:**_
_Create unique grocycode stock item labels when "Label per unit" is selected (on purchase)._

---

Hello,

I'm very new to Grocy (mostly playing with the demo instance and API), and my goal is to be able to do all adding, transferring, consuming, and inventory with only a barcode reader and (probably) a custom python script.  Due to physical constraints, I won't have a "usual" or default location for a lot of things.  I'll have a number of shelves that have "back stock" of any particular item, and when I consume some, I'll have to tell Grocy which location I got it from.

The problem with using only a UPC when scanning a product to be consumed or transferred is: Grocy doesn't know which location it came from, or what the expiration date of that particular item is.  I'd like it to be able to warn me (or have my custom Python script warn me) if the product I happened to see on the shelf is not the one that expired the soonest.  If there's an older one at the back of the shelf, I'd like an automated "are you sure you don't want the older one?" type message to be possible.

The problem I see with the existing Grocycode is: it seems to be generated from product + location + expiration; if I move it from one location to another, the Grocycode changes, and I would have to print a new physical label to put on it, which I'd rather not do.

If Grocy could assign a unique ID to each and every product that I add to my inventory (meaning if I add 6 cans of green beans to my inventory, I'd print 6 labels each with its own unique ID), then Grocy could keep track of location, expiration, and any other information in the database, without having to reprint any labels.  In my case, I'd probably apply the new barcode label over top of the original UPC, and only use the custom label once the item is added to my inventory.

This would let me consume an item with a single barcode scan, ensuring that it is "removed" from the location where I actually removed it, and with the correct expiration date, as opposed the oldest one in Grocy's database.  It would let me move items between locations by scanning just the new location barcode, and the barcodes for whatever items I'm adding to that location.  Again, without having to worry about telling Grocy which location I'm pulling from, or indeed allow me to move items from multiple sources to a new destination, ensuring that the expiration dates are tracked correctly through the moves.

I'd be happy to contribute to this, but I'm not at all familiar with php, and I haven't had the time yet to dig into the code base and even find basic things like the database schema.

Thank you for writing, maintaining, and open-sourcing Grocy; it's definitely going to save me a whole lot of time and money!

**Comment by berrnd** [comment]
> The problem I see with the existing Grocycode is: it seems to be generated from product + location + expiration; if I move it from one location to another, the Grocycode changes

That's wrong, don't know where you got this information from. Each stock item has technically a "stock_id" which is generated when the item is added (through purchase or inventory). This id is basically the item-grocycode and it keeps the seem, regardless of what happens / how often an item is transferred between locations during its lifecycle.

> If Grocy could assign a unique ID to each and every product that I add to my inventory (meaning if I add 6 cans of green beans to my inventory, I'd print 6 labels each with its own unique ID)

Exactly this is how the stock item grocycode works, as mentioned before ([code ref](https://github.com/grocy/grocy/blob/787c885ccf876c1f11b6108af6412efb223da5ff/controllers/StockApiController.php#L657-L685)).

> This would let me consume an item with a single barcode scan, ensuring that it is "removed" from the location where I actually removed it, and with the correct expiration date

Again exactly what a stock item grocycode does, it removes that stock item, nothing else. Maybe you have mixed products grocycodes and stock item grocycodes?

So far I see nothing which isn't already possible by utilizing (stock item) grocycodes, so closing this.

**Comment by anwright** [comment]
@berrnd, thank you for the very quick response!

I just did a test on a private demo instance, and although it doesn't work quite the way I thought it did, it doesn't do what I was imagining from your description, either.  The demo instance I used is: https://test-tkeqhmbtq9e0rfz5984757q.demo.grocy.info .

I created two new locations, "Shelf A" and "Shelf B".  I then purchased 6 Cookies in a single transaction, setting the location to "Shelf A".  Think of this like buying a case that contains 6 sleeves of cookies, which will be consumed one at a time, and which may not always be stored together once the case is opened.

Then I transferred 3 of them to "Shelf B".  When I "Open stock entry label in new window" for each of the two entries, I do get two different stock entries (`/stockentry/76/label` and `/stockentry/77/label`).  However, the barcode in both of them is the same: `grcy:p:1:6189a73b26391`.  If I go to "Consume" and scan the barcode, it defaults to "Shelf B" as the location, which may or may not actually be where I got the item from, since there were 3 in each location in the inventory.  This means I can't just scan a single barcode and have Grocy definitely remove it from the correct location; I have to scan the product barcode and also a location barcode to indicate where I removed it from.

I think if I "Purchased" every single item separately (so every stock entry was quantity: 1), this would actually work exactly the way I want it to, but that's less than ideal when buying e.g. a case of a given item that may have 6 or 12 or 36 items, and I want to be able to move each of those items around independently once I've opened the case.

**Comment by berrnd** [comment]
> I think if I "Purchased" every single item separately (so every stock entry was quantity: 1), this would actually work exactly the way I want it to

That's the case currently, now I got what you mean.

So let's track here / TODO:
Create unique grocycode stock item labels when "Label per unit" is selected (on purchase).

**Comment by anwright** [comment]
Hello again,

I'm happy to open a separate issue for this, but I just noticed what I believe is a bug related to stock item grocycode generation.  I have grocy running locally now (via grocy-docker) and am using a webhook to print labels to a Brother QL printer.  I'm calling the webhook server-side.  I have a custom python script adding products via the `/api/stock/products/{}/add` endpoint, with `print_stock_label: 1` in the request body.

My goal was to add every item to inventory individually, as described in my previous reply, so that I'd end up with every stock entry having quantity: 1.  However, when I do that, instead of creating separate stock entries, the API appears to  just be incrementing the count of the existing stock entry since all of the data I'm providing (purchase date, expiration date, location) are the same.  That's logical, if undesired for my particular use case.

The problem is: the labels are printed with unique grocycodes containing `stock_entry_id`s, but only the first one is saved in the database.  If I add 10 of the same item (with the same location and expiration date), then I end up with 1 stock item grocycode in the database, with quantity 10, and 9 labels with stock item grocycodes that can't be found.

My guess is that although a [stockId is generated](https://github.com/grocy/grocy/blob/release/services/StockService.php#L168) in the stock service prior to database insert and subsequent label printing, something in the database layer is throwing that stockId away and using the existing one.  Since I'm not normally a PHPer I'm having some difficulty understanding exactly how that database call is happening, so I haven't been able to confirm.  The API response always has the (single, correct) stock entry ID in the response.

I did discover while writing this comment that if I add a unique price to each purchase, I do get the result that I'm looking for: unique stock entries per item, with unique labels.  I'm not currently using price tracking, but if I decide to in the future, I'll just make sure to increment the price by something in the thousandth-of-a-cent range to give the uniqueness I'm looking for.

**Comment by berrnd** [comment]
That's basically all what this feature request is about and what need to be handled when implementing/improving this...

> the API appears to just be incrementing the count of the existing stock entry since all of the data I'm providing (purchase date, expiration date, location) are the same. That's logical, if undesired for my particular use case.

Since v3.1.0 (ref #1343) this happens automatically ([here](https://github.com/grocy/grocy/blob/beae32ef234eed8cf992e769416e2c30d65e29ef/services/StockService.php#L1547-L1593)), since, you said it, it's kind of logical and natural - a stock entry is identified by `Product + Due date + Purchased date + Price + Opened/Not Opened + Location + Store where you bought it`, duplicate entries get combined.

Maybe disabling that somehow automatically or optionally manually is the solution for this feature request.

**Comment by berrnd** [comment]
When thinking about this again, this was more a bug and is now fixed.

On purchase and when selecting `Label per unit` (`stock_label_type: 2` for the `/stock/products/{productId}/add` API endpoint), unique stock entries are now generated (so technically a stock entry per unit with a different `stock_id`).
