### ISSUE TITLE
Feature Request: Mealplan toggle 1 day view

### ISSUE THREAD

**Issue by liffez** [grocy/grocy#1678]
If you have several recipies on the same day it would be nice to be able only to view the content that day. 
On the Phone it automaticaly do that since it is a small mobile device, but maybe ther could be a buttom toggeling between day/week view.

**Comment by berrnd** [comment]
On bigger screens there is now a week/day button on the top right corner of the meal plan to switch between the views:

![grafik](https://user-images.githubusercontent.com/2161815/153040692-28c76ddb-9ed3-42d1-8759-22811954379e.png)
