### ISSUE TITLE
nginx support

### ISSUE THREAD

**Issue by LogoiLab** [grocy/grocy#168]
Can this be used with nginx instead of an AMP stack? I'd assume so. Please pardon the issue I figured it would be better to not email directly.

**Comment by berrnd** [comment]
Sure, is also mentioned in the ["How to install"-section in README](https://github.com/grocy/grocy#how-to-install):
> If you use nginx as your webserver, please include `try_files $uri /index.php;` in your location block.

All of my instances, including all the demos, and also [grocy-docker](https://github.com/grocy/grocy-docker) run grocy with nginx, so absolutely no issue there. grocy uses the Slim Framework, so maybe check [their doc about webserver configuration](http://www.slimframework.com/docs/v3/start/web-servers.html) if you have any problems.
