### ISSUE TITLE
Bug: Product#location_id is returned as string instead of an integer

### ISSUE THREAD

**Issue by SebRut** [grocy/grocy#1683]
An [issue](https://github.com/SebRut/pygrocy/issues/203) reported for pygrocy uncovered that the `location_id` field in the `product` field in `CurrentStockResponse` is returned as a string instead of an integer as defined in the [API docs
](https://github.com/grocy/grocy/blob/master/grocy.openapi.json#L4262).

**Comment by berrnd** [comment]
That's the case not only for this integer field, but for all - see https://github.com/grocy/grocy/issues/1564#issuecomment-893562298 and https://github.com/grocy/grocy/issues/1564#issuecomment-902907708.

[v3.1.1 changelog](https://grocy.info/changelog#v3.1.1) excerpt:
> ### API
> > ❗ The release before (v3.1.0) introduced that "numbers are now returned as numbers": **This was reverted** since it had unintended side effects (so all fields are technically strings now again, just like before - sorry for that)

**Comment by SebRut** [comment]
Ah, I forgot about that. But then the API docs should probably be updated or are they getting generated?

**Comment by berrnd** [comment]
[`grocy.openapi.json`](https://github.com/grocy/grocy/blob/master/grocy.openapi.json) is entirely handrafted, was also never different there (all fields were in all versions returned as strings, only not in v3.1.0) - the underlying database type is mentioned, don't know what's better...

**Comment by SebRut** [comment]
I'll change the pygrocy implementation, because of [these lines](https://github.com/grocy/grocy/blob/beae32ef234eed8cf992e769416e2c30d65e29ef/grocy.openapi.json#L4262) in `grocy.openapi.json` declaring `location_id` as `integer`
