### ISSUE TITLE
Bug: Reordering columns on stock overview breaks filters

### ISSUE THREAD

**Issue by anwright** [grocy/grocy#1684]
Hello,

I've discovered what appears to be a bug on the stock overview page.  Once triggered, the only fix I've found is to `DELETE /user/settings/datatables_state_stock-overview-table`.

Reproduction steps:
- Visit stock overview page
- Click `table options` button
- Add any column (I've tested `min. stock amount` and `calories`)
- Drag the new column to the immediate left of `next due date`
- Apply any filter

In this scenario, applying any filter returns no results, and the only fix seems to be to delete the state via the API.  Hiding the column again via the UI has no effect, nor does restoring the original column order or hiding the column.

I was not able to test this on the pre-release demo, beacuse the stock overview does not load correctly there.

**Comment by berrnd** [comment]
Is reproducible on the [stable demo](https://demo.grocy.info/) (the general search field still works, only the filter-dropdowns seem to be the problem).

> the only fix seems to be to delete the state via the API

This can also be done on the UI:
Table options (eye icon) -> red "Reset" button at the bottom.

**Comment by anwright** [comment]
> This can also be done on the UI
Good to know, thank you.  I didn't even occur to me to try that, because I assumed it would behave like a "cancel" button on the dialog, rather than truly resetting the state of the table.
