### ISSUE TITLE
Feature Request: Add cooking/resting times to recipes in order to help with meal planning

### ISSUE THREAD

**Issue by proffalken** [grocy/grocy#1689]
I've started using Grocy to plan out my Christmas Dinner and related shopping lists, and it's looking really good so far!

One thing I end up doing every year about three days before Christmas is sitting down with all my recipe books and working out all the timings for when stuff has to go into the oven/on the hob/under the grill etc. and then working backwards from the target serving time to the point at which I have to start prepping/cooking.

For example, a joint of beef might take 2hrs to cook and then need to rest for 15 - 30 minutes, so at the absolute latest that needs to be in the oven at 1030hrs in order to serve up at 1300hrs.

The roast potatoes might take 1hr 15 minutes, so they need to go in at 1145hrs at the latest

Carrots take about 20 minutes, yorkshire puddings about 30 minutes, cabbage or sprouts could take an hour depending on how they're cooked.

I end up with a timeline for the day that looks a bit like this:
```
1300hrs - Serve Up

1240hrs - Carrots

1230hrs - Yorkshires

1200hrs cabbage & sprouts

1145hrs - Potatoes

1030 - Beef
```
It would be great to be able to add three *optional* fields to each recipe:

   1. Prep Time
   2. Cooking Time
   3. Resting Time

And then be able to use these fields to calculate the timeline for the day as above simply by selecting what you're cooking on a given day and stating the "serving up time".

**Comment by berrnd** [comment]
> It would be great to be able to add three optional fields to each recipe:

You can already add any field you want, not only to recipes - have a look at Userfields (ref #176).

Beside that, the purpose of the meal plan is more to structure the meals throughout a day/week, not about to organizing cooking times of a big dinner. Also something like that (generic rules to generate a meal plan) is already requested in #553, so feel free to add your ideas there.
