### ISSUE TITLE
Feature Request: Factor purchase to stock quantity unit in purchase page

### ISSUE THREAD

**Issue by BlizzWave** [grocy/grocy#169]
Would be very nice to see Factor purchase to stock quantity unit  when adding item in the purchase page.

**Comment by berrnd** [comment]
Will now be displayed like that and only when purchase/stock units are different:

![grafik](https://user-images.githubusercontent.com/2161815/54073985-9fc7bc80-428d-11e9-8a69-f5195b352dec.png)
