### ISSUE TITLE
Feature Request: custom tags + filtration for recipe module

### ISSUE THREAD

**Issue by Rafurus** [grocy/grocy#1690]
I would find tag system with filtration usefull for recipe module. 
Right now if you have 100+ recipes and you want to find "this one" recipe without remembering name it's time consuming. 
With custom tags we could do something like:

- meal type like soup, appetizer etc. 
- time of meal like breakfast, lunch etc.
- food practice like veganism, vegetarianism etc. 
- favorite recipes
- recipes for holidays
- recipes gluten-free,  low protein etc. 
- even our diet name like 2000 kcal

Some of them could be predefined like meal type or time of meal (for users who don't have time for creating ones).

This info should be view in recipe and in columns for recipe index. Best if columns where configurable if to show/not show them and which ones. 

Filtration for tags would be a thing for fast search for recipes. 
Cost and kcal that existing now would be usefull in filtration too. 

Hope you would find this feature usefull.

**Comment by berrnd** [comment]
> Best if columns where configurable if to show/not show them and which ones.

Already doable, not only for recipes - have a look at Userfields (ref #176).
