### ISSUE TITLE
Feature Request: Recipe Tags

### ISSUE THREAD

**Issue by arnediehm** [grocy/grocy#1692]
I would find it very helpful if I could assign tags to recipes and search for them, just as I can search for recipes containing a specific product. For example "Starter", "Main course", "Dessert", "Cake", "Soup", "Vegetarian", "Sweet"...  I've entered all of my recipes in Grocy and it gets a bit cluttered with recipes that don't fit when trying to decide what to cook.

**Comment by berrnd** [comment]
Already possible, not only for recipes - have a look at Userfields (ref #176).

Has also already been asked just yesterday in #1690 or also before in #324 or #896 - doing some search here before would be great.
