### ISSUE TITLE
Bug: Can't select Amount-QU or the checkbox above @ Add Recipe ingredient

### ISSUE THREAD

**Issue by lepouletfou2** [grocy/grocy#1697]
https://test-lav22nqnalkvhz6c47mune.demo.grocy.info/recipe/5

I cannot select the unit of amount AFTER selecting "cheese" as Product and also after entering a amount.

The dropdown is reset immediately after the mouse click and the control field above "quantity" can also only be operated randomly.

Seems something @recipeposform is broken.

**Comment by berrnd** [comment]
Can't see any problem by what you described - latest Firefox (latest Chrome behaves the same):


https://user-images.githubusercontent.com/2161815/143700187-eab4c9e5-bda0-48cb-8e9c-55f3976d8c57.mp4

**Comment by lepouletfou2** [comment]
you're crazy.

Just the same. Latest chrome, cache disabled and this happend:

https://user-images.githubusercontent.com/83538985/143705262-67dcc06c-54e2-429a-93d2-46b9666e819d.mp4

**Comment by berrnd** [comment]
> you're crazy.

You're welcome.

https://user-images.githubusercontent.com/2161815/143716838-9a74479f-1479-4e74-bf09-f9e39fe8fef6.mp4

Testing things without any enabled add-on (especially those which block things) is kind of a golden rule - most probably it's that...

**Comment by berrnd** [comment]
> Testing things without any enabled add-on (especially those which block things) is kind of a golden rule - most probably it's that...

![grafik](https://user-images.githubusercontent.com/2161815/143719182-018244ec-44ff-4f68-9735-165ab8f9619e.png)

https://github.com/hassio-addons/addon-grocy/issues/255#issuecomment-978097502

> I am using the "Enpass" extension as password manager. A recent update of the extension added icons within textfields to directly access the Enpass app. After deactivating the Enpass extension, the dropdown opened.
