### ISSUE TITLE
Setup - Docker, DynDNS, PathPrefix... Cannot find a working combination

### ISSUE THREAD

**Issue by anthraxn8b** [grocy/grocy#1698]
Hi!
First of all: GREAT APP! THX for providing it OpenSource!

Maybe this is more of a support question...
I currently struggle a bit getting my config up and running.

I have a DDNS domain that is forwarding HTTPS requests to my home router forwarding it to my raspberry forwarding it to the TRAEFIK-ReverseProxy-HTTPS-Endpoint (a docker container) which then applies some rules and forwards the request to the target docker container.
This is working fine for many installations - but I do not get grocy integrated.

Grocy should be made available via an URL like this: https://my.ddns.net/grocy
HTTPS is handled by TRAEFIK - so the communication from TRAEFIK to the GROCY container is HTTP.
Now there are two options: Either the URL is left as is and forwarded to GROCY or TRAEFIK can remove the path prefix "/grocy".

The used docker image (lscr.io/linuxserver/grocy) provides grocy on the root path on port 80.
So first of all stripping the prefix should be fine to reach the targets of the original inbound requests.

Because the initially loaded data (webapp) tries to load additional data like JS, CSS and reach its backend, it will have to know the URL to its resources which now require to be loaded from below the URL "https://my.ddns.net/grocy/...".
This requires the APP to understand the circumstance that the URL includes a sub path (like grocy) but the installation on the host (docker container image) is on the root path.

The GROCY config now allows me to set :
- BASE_PATH (which should be the URLs path prefix that is required to reach the root directory of the content - from the perspective of the container image only(?))
- BASE_URL (which should be the URL that is required to reach the root content of the application from a client - webapp running on a browser)

So my configuration is:
- BASE_PATH (unchanged - because the containers installation provides the content on the root path - http://IPorNAME/): "/"
- BASE_URL (which I understand as the URL required to reach the content from the outer world): "https://my.ddns.net/grocy"

This would now require the app logic running in the webbrowser to point every resource request (JS, CSS, backend,...) to the BASE_URL. Because TRAEFIK removes the prefix the request does not need to be internally remapped onto another path.

But that does not work.
I also cannot find any error hints. Not in the docker logs and not in the NGINX and PHP8 error logs in the container.

Ideas? :-)

**Comment by berrnd** [comment]
> Maybe this is more of a support question...

I guess that too and [README mentions](https://github.com/grocy/grocy#questions--help--bug-reporting--feature-requests) that this is the place for bug reports and feature requests, not for help requests.

**Comment by anthraxn8b** [comment]
However - it is not a bug. Whoever is interested what I did wrong: reading helps.
I accidently left BASE_PATH set to "/" instead of "".
