### ISSUE TITLE
Feature Request: Send mail if product is out of stock/under minimum

### ISSUE THREAD

**Issue by stphnmttldrf** [grocy/grocy#1699]
I don't use the Grocy Shoppinglist, because i do not put all things i buy into grocy. ;-)

The idea is, that grocy sends a mail (one per day/hour/...) with all products that are below stock minimum, out of stock or the due date is over. Would be a nice feature!

Bye the way: Many thanks for the development of grocy. Love it!

**Comment by berrnd** [comment]
Maybe have a look at grocy-alerts:

https://github.com/Typositoire/grocy-alerts

https://www.reddit.com/r/grocy/comments/qfk65p

**Comment by berrnd** [comment]
Merged into #156.
