### ISSUE TITLE
Consume all button breaks with partial units

### ISSUE THREAD

**Issue by matejdro** [grocy/grocy#170]
Just found small bug:

1. Create product with partial units enabled (for example milk - liters)
2. Set your inventory of Milk to 0.5 liters
3. Press consume all button on Stock page
4. Consume all will consume whole liter, resulting in stock page saying you have -0.5 liters of milk in stock. 

This is with grocy 2.1.0

**Comment by berrnd** [comment]
Thanks.

But fortunately only seems to be a display bug - there is already a safety check in the API to newer consume more that is in stock.

Also the "consume 1" button should be disabled when the stock amount is < 1 - currently the API response is not handled correctly, so no stock booking happens but also the displayed amount is wrong then...
