### ISSUE TITLE
Bug: iCal shared calendar times are off

### ISSUE THREAD

**Issue by brantg** [grocy/grocy#1700]
Entry in Grocy:

![Screenshot_20211129_071254](https://user-images.githubusercontent.com/10169603/143874371-0c708e89-5bcd-47c9-ac18-68ec7f4fc1f8.png)

Entry in calendar client:

![Screenshot_20211129_071423](https://user-images.githubusercontent.com/10169603/143874487-553c8f61-ab53-43eb-9840-a605b47866c8.png)

Works awesome otherwise, but this would be more useful if the times were correct.

**Comment by berrnd** [comment]
Double check your timezone settings. Timezones are currently not handled, therefore, your server (PHP and system/OS setting) and your client should all use the same timezone (ref #214).

**Comment by brantg** [comment]
Will do, thank you!
