### ISSUE TITLE
Need help with ldap error 

### ISSUE THREAD

**Issue by Gamechiefx** [grocy/grocy#1702]
Hello I have a Server 2019 AD server and when I set up the appropriate LDAP config inside of my config.php and attempt to log in I get an error of resource that should be expected but it appears that a bool was received instead.

Config is as follows:

// LDAP options when using LdapAuthMiddleware
Setting('LDAP_ADDRESS', 'ldap://10.70.70.250:389'); // Example value "ldap://vm-dc2019.local.berrnd.net"
Setting('LDAP_BASE_DN', 'OU=hill.online,DC=ad,DC=hillweb,DC=online'); // Example value "DC=local,DC=berrnd,DC=net"
Setting('LDAP_BIND_DN', 'CN=grocy,OU=Functional Accounts,OU=hill.online,DC=hill,DC=online'); // Example value "CN=grocy_bind_account,OU=service_accounts,DC=local,>
Setting('LDAP_BIND_PW', 'abc123'); // Password for the above account
Setting('LDAP_USER_FILTER', 'OU=Users,DC=hill,DC=online'); // Example value "(OU=grocy_users)"
Setting('LDAP_UID_ATTR', 'sAMAccountName'); // Windows AD: "sAMAccountName", OpenLDAP: "uid", GLAuth: "cn"

please see below technical data:

Error source:
```
/app/grocy/middleware/LdapAuthMiddleware.php:45
```

Error message:
```
ldap_get_entries(): Argument #2 ($result) must be of type resource, bool given
```

Stack trace:
```
#0 /app/grocy/middleware/LdapAuthMiddleware.php(45): ldap_get_entries()
#1 /app/grocy/controllers/LoginController.php(23): Grocy\Middleware\LdapAuthMiddleware::ProcessLogin()
#2 /app/grocy/vendor/slim/slim/Slim/Handlers/Strategies/RequestResponse.php(43): Grocy\Controllers\LoginController->ProcessLogin()
#3 /app/grocy/vendor/slim/slim/Slim/Routing/Route.php(384): Slim\Handlers\Strategies\RequestResponse->__invoke()
#4 /app/grocy/vendor/slim/slim/Slim/MiddlewareDispatcher.php(81): Slim\Routing\Route->handle()
#5 /app/grocy/vendor/slim/slim/Slim/MiddlewareDispatcher.php(81): Slim\MiddlewareDispatcher->handle()
#6 /app/grocy/vendor/slim/slim/Slim/Routing/Route.php(341): Slim\MiddlewareDispatcher->handle()
#7 /app/grocy/vendor/slim/slim/Slim/Routing/RouteRunner.php(84): Slim\Routing\Route->run()
#8 /app/grocy/middleware/LocaleMiddleware.php(16): Slim\Routing\RouteRunner->handle()
#9 /app/grocy/vendor/slim/slim/Slim/MiddlewareDispatcher.php(313): Grocy\Middleware\LocaleMiddleware->__invoke()
#10 /app/grocy/middleware/AuthMiddleware.php(36): Psr\Http\Server\RequestHandlerInterface@anonymous->handle()
#11 /app/grocy/vendor/slim/slim/Slim/MiddlewareDispatcher.php(313): Grocy\Middleware\AuthMiddleware->__invoke()
#12 /app/grocy/vendor/slim/slim/Slim/Middleware/RoutingMiddleware.php(59): Psr\Http\Server\RequestHandlerInterface@anonymous->handle()
#13 /app/grocy/vendor/slim/slim/Slim/MiddlewareDispatcher.php(147): Slim\Middleware\RoutingMiddleware->process()
#14 /app/grocy/vendor/slim/slim/Slim/Middleware/ErrorMiddleware.php(107): Psr\Http\Server\RequestHandlerInterface@anonymous->handle()
#15 /app/grocy/vendor/slim/slim/Slim/MiddlewareDispatcher.php(147): Slim\Middleware\ErrorMiddleware->process()
#16 /app/grocy/middleware/CorsMiddleware.php(30): Psr\Http\Server\RequestHandlerInterface@anonymous->handle()
#17 /app/grocy/vendor/slim/slim/Slim/MiddlewareDispatcher.php(313): Grocy\Middleware\CorsMiddleware->__invoke()
#18 /app/grocy/vendor/slim/slim/Slim/MiddlewareDispatcher.php(81): Psr\Http\Server\RequestHandlerInterface@anonymous->handle()
#19 /app/grocy/vendor/slim/slim/Slim/App.php(215): Slim\MiddlewareDispatcher->handle()
#20 /app/grocy/vendor/slim/slim/Slim/App.php(199): Slim\App->handle()
#21 /app/grocy/app.php(106): Slim\App->run()
#22 /app/grocy/public/index.php(45): require_once('...')
#23 {main}
```

System info:
```
{
    "grocy_version": {
        "Version": "3.1.3",
        "ReleaseDate": "2021-11-14"
    },
    "php_version": "8.0.13",
    "sqlite_version": "3.35.5",
    "os": "Linux 5.4.0-74-generic #83-Ubuntu SMP Sat May 8 02:35:39 UTC 2021 x86_64",
    "client": "Mozilla\/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit\/537.36 (KHTML, like Gecko) Chrome\/96.0.4664.45 Safari\/537.36"
}
```

**Comment by berrnd** [comment]
[README mentions](https://github.com/grocy/grocy#questions--help--bug-reporting--feature-requests) that this is the place for bug reports or feature requests, not the one for questions, for which we have the [r/grocy subreddit](https://www.reddit.com/r/grocy) for. So closing this as invalid.

[`ldap_get_entries`](https://www.php.net/manual/en/function.ldap-get-entries.php) returns a bool value / `false` when there is an error connecting to / getting entries from the LDAP server. So I would start by for example trying to query it manually by using [ldapsearch](https://docs.ldap.com/ldap-sdk/docs/tool-usages/ldapsearch.html) or something.

> I have a Server 2019 AD
> `Setting('LDAP_ADDRESS', 'ldap://10.70.70.250:389');`

Double check that unencrypted port 389 connections are still enabled on your DC, since that's [not the default since last year or so](https://techcommunity.microsoft.com/t5/core-infrastructure-and-security/ldap-channel-binding-and-ldap-signing-requirements-march-2020/ba-p/921536).

> `Setting('LDAP_BASE_DN', 'OU=hill.online,DC=ad,DC=hillweb,DC=online');`

Typically a base DN specifies the root of the domain, not an OU.
