### ISSUE TITLE
Bug: QU named matching a localization string displays that string instead of the QU name

### ISSUE THREAD

**Issue by Dahu88** [grocy/grocy#1705]
version: 3.1.2

I'm french and I created a unit called 'cs' standing for 'Cuillère à soupe' or table spoon in english. When in singular form in a recipe it is displayed as 'tch' instead of 'cs'.

I looked in the source and found the tch string in the translation file **localization/fr/locales.po** for the Czech
```
# Czech
msgid "cs"
msgstr "tch"
```

I think the translation should not occur on units.

I don't have the problem with the plural form which I also set as 'cs'

**Comment by berrnd** [comment]
Is reproducible and of course translations should not apply on quantity units.
&nbsp;

> I don't have the problem with the plural form which I also set as 'cs'

Because that example localization string doesn't have a plural form.
