### ISSUE TITLE
Feature Request: grocycode bulk download

### ISSUE THREAD

**Issue by yorocoboy1** [grocy/grocy#1707]
Please describe what you would find useful and please also check (by searching open requests here) if that was maybe already requested.

**Comment by berrnd** [comment]
Would be kind of great if you could explain a little bit of what you think of.

There is already an API endpoint to retrieve grocycodes.

For the frontend, grocycodes are meant to be printed on label printers which is done via a WebHook request on purchase.

**Comment by yorocoboy1** [comment]
Can you explain me how to download all the grocycode in one pdf file so I can print it out easily

**Comment by yorocoboy1** [comment]
Actually I am using on homeassistant

**Comment by yorocoboy1** [comment]
And can you add support for 3.1.0 in android ??

**Comment by berrnd** [comment]
> Can you explain me how to download all the grocycode in one pdf file so I can print it out easily

Nothing is in grocy / the frontend to do that currently, the current implementation is meant to work with label printers and they commonly need single labels, not a big page of multiple ones.

Of course something like that can be added, then please explain what you think of. We have grocycodes for products, stock entries, chores and batteries. I doubt a big PDF of just all makes so much sense.

> And can you add support for 3.1.0 in android ??

grocy is a web application, therefore runs everywhere a web browser is available. This is not the repository of any of the community contributed native mobile apps.

**Comment by yorocoboy1** [comment]
> > Can you explain me how to download all the grocycode in one pdf file so I can print it out easily
> 
> Nothing is in grocy / the frontend to do that currently, the current implementation is meant to work with label printers and they commonly need single labels, not a big page of multiple ones.
> 
> Of course something like that can be added, then please explain what you think of. We have grocycodes for products, stock entries, chores and batteries. I doubt a big PDF of just all makes so much sense.
> 
> > And can you add support for 3.1.0 in android ??
> 
> grocy is a web application, therefore runs everywhere a web browser is available. This is not the repository of any of the community contributed native mobile apps.

Like I am a home user and I or most of home user don't have label printer so what can I do is put all the grocycode with product name and email it to the printing shop they print labels in A4 size of paper and send it to me and also there are pre cut so I can easily peel of and can put labels on my product easily! Thank you sir🙂🙂

**Comment by yorocoboy1** [comment]
Like for the update I am asking for the barcode , when I try to enter a product in master data, so there is one option for barcode and it is telling that we are implementing it feature will be available soon that the only reason that i am asking for the update, thank you sir you are so great person I ever met, that reply so fast and you are a great creater keep it up!!

**Comment by berrnd** [comment]
Mailing grocycodes to a copy shop? Most probably the craziest thing I've heard so far, but whatever someone prefers. I would simply buy a label printer if I want to utilize (product and/or stock entry) grocycodes in my home, at the end also cheaper I would say...

> When I try to enter a product in master data, so there is one option for barcode and it is telling that we are implementing it feature will be available soon that the only reason that i am asking for the update

Whatever, sorry, I don't really understand what you mean. grocycodes can be automatically printed, printing happens via WebHooks (already mentioned before). How it works is explained [there](https://github.com/grocy/grocy/blob/master/docs/label-printing.md).

If you have a concrete feature request, please open a separate ticket for that and please explain in short but detailed words what you think of. I still doubt that a big sheet of just all grocycodes is so useful and really what you want, at least that's what I understood, but this here is also not the place for general usage discussions like [mentioned in README](https://github.com/grocy/grocy#questions--help--bug-reporting--feature-requests).

And I don't think we've ever met, but I'm glad when grocy is useful for you.
