### ISSUE TITLE
Bug: No Logout for LDAP Authentification

### ISSUE THREAD

**Issue by FloSet** [grocy/grocy#1709]
Hi there,
I'm not sure if that's supposed to be the case (if so, I don't know why), but the logout button for externally managed users is missing. I use LDAP for authenticating users and the logout flow seems to work fine, but it is through the missing link unusable. I don't have any problems (except updates) if I activate it again in the `default.blade.php` file.

**Comment by zombielinux** [comment]
I can confirm the same bug here.
