### ISSUE TITLE
buying convertion in webui

### ISSUE THREAD

**Issue by Zac5teeve** [grocy/grocy#1711]
Bug: on webui when buying a product that converts to an other unit the conversion (1x to 3y) occurs but the stock quantity shows “0y (sigma symbol E) 3y”

**Comment by berrnd** [comment]
Sorry, I really don't know what you mean by those few words - please provide a real example by using a [persistent demo instance](https://www.reddit.com/r/grocy/comments/jwnk9b) and the exact steps of what you did, which is also mentioned on the issue template.

Referring to "sigma symbol" you probably mean a parent/child product relation. If so, please double check related unit conversions and also keep in mind that currently only 1 level of unit conversion hierarchy is supported (ref #1360).
