### ISSUE TITLE
Bug: Cannot change price of stock entry

### ISSUE THREAD

**Issue by Lykos153** [grocy/grocy#1712]
Steps to reproduce:
* Add product via purchase, don't enter a price
* Open stock entry via stock overview and enter price
* Click OK => UI flashes
* Click Close and check price => It's still 0,00

Interesting: Stock journal shows a transaction `Stock entry edited (old values)`

Use case:
When I put the products from the shopping bag to the storage location, I use the scanner to add them to grocy and enter the best before date which is on the package. The price, however, is on the receipt, and searching each product on it while emptying the shopping bag would be very time consuming. I'd rather add all the prices later on using a PC with all items already present in grocy.

EDIT: Turns out I'm using quite an old version (provided by the k8s-at-home helm chart). I'm going to check if it's fixed in the current version.

```
 Version 3.0.1
Released on 2021-01-05 11 months ago

PHP Version 7.4.21
SQLite Version 3.34.1 
```

**Comment by berrnd** [comment]
Exactly that was a problem of v3.0.1 - [changelog excerpt of v3.1.0](https://grocy.info/changelog#v3.1.0):

> ### Stock improvements/fixes
> - Fixed that editing stock entries was not possible

Would be great if you can try to reproduce problems on the demo / latest version first, that's also mentioned on the issue template - referring to a version which already has 3 newer releases really makes not so much sense in general...

**Comment by Lykos153** [comment]
You're right. I kind of trusted the helm chart to be up-to-date, so I didn't even think about checking the version until mere seconds after I had created the issue.
