### ISSUE TITLE
Feature Request: Print stock entry labels also on inventory

### ISSUE THREAD

**Issue by andreheuer** [grocy/grocy#1713]
I´m using Grocy 3.1.3 (docker by Linuxserver) and ql_web for label printing.

Thereby, I am wondering on the type of label that is printed/triggered by specific screens:

- Inventory: when I create a new inventory item (which create a stock item), a product label is printed automatically. I would have expected that a stock item label incl. due date (what I have recently typed in during inventory) is printed.
- Shopping: when I was shopping and adding a product (also entering the due date), I also would have expected that a stock item label incl. due date would be printed.

Might I have forgotten to set a specific setting?

**Comment by berrnd** [comment]
[Changelog v3.1.0](https://grocy.info/changelog#v3.1.0) excerpt:

> ### New feature: grocycode / label printer support
> #### (Own) Product/stock entry/chores/batteries labels/barcodes
> - Can be printed (or downloaded) via 
>   - _**Automatically on purchase (new option on the purchase page, defaults can be configured per product) for stock entries**_

So, as mentioned there, the label is currently only printed (resp. the WebHook called/executed) on the [/purchase page](https://demo.grocy.info/purchase), nowhere else. Can be of course added and sounds useful, but it's definetly not a bug when not implemented things are not yet implemented.

Since the the "Add this item to stock"-button on the shopping list page also just shows the /purchase page prefilled, it's not differently there and should work. Or you mean something else.

What's printed on the label is entirely up to your WebHook receiver implementation, no receiver is shipped with grocy.

**Comment by andreheuer** [comment]
I made now some tests on this and used the inventory extensively. I realized that labels are printed after doing inventory via [/inventory](https://demo.grocy.info/inventory) page. However, this seems to be not configurable, i.e. if a label is printed or not - like on the purchase page. I think this would be worth an enhancement.

For sure, the label design is on the receivers implementation.

**Comment by berrnd** [comment]
> I made now some tests on this and used the inventory extensively. I realized that labels are printed after doing inventory via [/inventory](https://demo.grocy.info/inventory) page.

Also just tested that. If, then only when items are added during inventory. I'm unable to get that result and also the code (as of now) explicitly doesn't print stock labels when adding products on inventory:

https://github.com/grocy/grocy/blob/3e20c2cc3d251884f4137e6bf51c4ea4cc6a98a9/services/StockService.php#L905

Parameter `$stockLabelType` of [`StockService->AddProduct`](https://github.com/grocy/grocy/blob/3e20c2cc3d251884f4137e6bf51c4ea4cc6a98a9/services/StockService.php#L117-L179) is omitted, hence the default is used which is `0` = `No label`.

**Comment by andreheuer** [comment]
FYI: I now found the reason, why my label was printed. Everything you wrote above is valid. However, in version 3.1.3 the [if condition in line 271](https://github.com/grocy/grocy/blob/3e20c2cc3d251884f4137e6bf51c4ea4cc6a98a9/services/StockService.php#L271) does not include the check for `$stockLabelType == 1`. That´s why a label is printed even with lavel type 0.

Anyhow, thank you for the extension!
