### ISSUE TITLE
Bug: Selected stock quantity unit not used for pricing on inventory page

### ISSUE THREAD

**Issue by tinyoverflow** [grocy/grocy#1715]
Hello,

I'm new to grocy but I've noticed something while I wanted to bring my existing stock into grocy.
I've noticed, that when selecting a stock quantity unit other than the default unit on the inventory page, that it is still using the default stock unit for pricing.

Example:
I have oil and milliliter is the default stock unit, but the shopping unit is bottle with a factor of 750 (so 1 bottle = 750ml). When I now go to the inventory page and enter that I have 1 bottle for 4€, it calculates my stock value to be 3000€, as per 1ml = 4€. Everything works fine on the shopping page, though.

This also happens on the current unstable demo.

**Comment by berrnd** [comment]
Well, the little help text for that input field exactly mentions that - so not a bug.

![grafik](https://user-images.githubusercontent.com/2161815/145815360-605634ef-ed0c-4207-a3ac-7a50267176e2.png)


Beside that, it's already tracked in #1346 to extend that.
