### ISSUE TITLE
Bug: Check for "unround" recipe ingredient amounts in shopping list fails 

### ISSUE THREAD

**Issue by heinrich-ulbricht** [grocy/grocy#1717]
**Description of what I want to do, as simplified repro case**

* have 0 piece of zucchini in stock
* create a new recipe for 3 servings that has 1 zucchini as ingredient
* set desired servings for the recipe to 4 (=1.333 zucchini) and add it to the shopping list

**What do I expect to see on the recipe page?**

I expect a yellow exclamation mark saying something like _"Not enough in stock (not included in costs), 1 missing, 1 already on shopping list"_.

**What do I see instead?**

I see a red cross and _"Not enough in stock (not included in costs), 1.33 missing, 1.33 already on shopping list"_. Which makes no sense. Here's a screenshot from the prerelease demo for the described repro case:

![image](https://user-images.githubusercontent.com/3469970/146090124-dfda3ff9-24c1-4462-b5a4-2b6bcb446125.png)

Is this a rounding issue?

**Comment by berrnd** [comment]
Persistent demo instance to reproduce that:
https://test-u6z1bml8q3yil8lc5huaj.demo-prerelease.grocy.info/recipes?recipe=7

- On ingredient level the icon seems to be wrong, the text is correct
- On recipe level both (icon and text) is wrong

And yes, most probably something about rounding at any place where stock fulfillment checking happens. So technically in the [SQL view `recipes_resolved`](https://github.com/grocy/grocy/blob/d23fda245e7a1974c354213f9a228995f2fd583f/migrations/0095.sql#L51-L64) + the dependent ones.

**Comment by bababash** [comment]
I'm not sure this is a bug - in order to make 4 serves you need 1.33 zucchinis. Rounding down to 1 will mean that you can't make this dish. If anything, the shopping list should give you an option to round up. 

I'm concerned about my baking recipes - if it was cups of flour removing the remainder will break your recipe!

**Comment by heinrich-ulbricht** [comment]
It was not about the rounding but about the message being of wrong type, not recognizing the shopping list amount.

(My sample could have been better chosen.)

**Comment by berrnd** [comment]
> I'm not sure this is a bug - in order to make 4 serves you need 1.33 zucchinis. Rounding down to 1 will mean that you can't make this dish. If anything, the shopping list should give you an option to round up.

This here was about stock fulfillment checking regarding shopping list amount comparision when having recipe ingredients with decimal amounts. So don't know why you mention that there, it's more than off-topic at this place and if you think it's a bug, it's untrackable in that way.

However:
When not having any unit conversion, of course and for that example, 1.33 zucchinis will land on the shopping list.

So when I stay in the supermarket and see "1.33 zucchinis" on my grocy shopping list, from my personal practical live experience it's not too hard to simply pick two instead. Or maybe also only 1, if I think that's enough that time.

**Comment by bababash** [comment]
Apologies for the misunderstanding, I see it now. Thank you both for following up!
