### ISSUE TITLE
Purchase > Best Before date to today or earlier

### ISSUE THREAD

**Issue by hannahswain** [grocy/grocy#172]
The Purchase > Best Before date is currently limited to tomorrow or further in the future:
https://github.com/grocy/grocy/blob/master/views/purchase.blade.php#L25

Given that the best before date could be today, or even earlier, one of these scenarios would be a good solution:

* Allow best before date start from today, rather than tomorrow
* Allow past dates

**Comment by berrnd** [comment]
I agree to allow the current day - but are you really buying already expired products? Well, they are maybe still good anyways... :)

There is no enforcing of the best before date in the API, only in the UI - so maybe we remove that also there and just display a little hint if it's <= today... (?)

**Comment by berrnd** [comment]
I did this now like mentioned before - can now be also today or earlier, but when < than today, a hint is displayed - hope this works for you. :)

![grafik](https://user-images.githubusercontent.com/2161815/54086905-280d9680-434e-11e9-9213-55ca9c4152f6.png)

**Comment by hannahswain** [comment]
That is a beautiful solution, and exactly what I was hoping for! :) Thank you!
