### ISSUE TITLE
Feature Request: default Price / Product

### ISSUE THREAD

**Issue by devdracon** [grocy/grocy#1720]
Hello, from my point of view, it would be useful if I could specify a standard price for a product. this way, the price does not have to be entered each time a purchase is made, but only when it changes.

I have tried to implement this using a user field, but I cannot establish a relationship with the purchase form.

**Comment by berrnd** [comment]
On the [/purchase page](https://demo.grocy.info/purchase) the last price get already prefilled.

In my reality, prices change from time to time and it makes much more sense to prefill the last one. When it changes, the next time the changed price get prefilled without having to manually change a products default price. That's even additionally tracked/prefilled per barcode, if a product has different ones attached.

Consider using [custom JS](https://github.com/grocy/grocy#adding-your-own-css-or-js-without-to-have-to-modify-the-application-itself) for such detail-specific use cases. Here is a snippet (for `data/custom_js.html`) which prefills the price of a Userfield named `defaultprice` on [/purchase](https://demo.grocy.info/purchase):
```html
<script>
if (Grocy.ActiveNav == "purchase")
{
	Grocy.Components.ProductPicker.GetPicker().on('change', function(e)
	{
		var productId = $(e.target).val();
		if (productId)
		{

			Grocy.Api.Get('objects/products/' + productId,
				function(product)
				{
					$('#price').val(parseFloat(product.userfields.defaultprice / $("#qu_id option:selected").attr("data-qu-factor")));
				},
				function(xhr)
				{
					console.error(xhr);
				}
			);
		}
	});
}
</script>
```

**Comment by devdracon** [comment]
bernd, thanks for the clarification, it was much appreciated. i made a wrong assumption, so your explanation is very helpful. thanks also for the script and your explanation.
