### ISSUE TITLE
Bug: Multiple QU conversions with same QU from name breaks stock entry

### ISSUE THREAD

**Issue by blue-hound** [grocy/grocy#1722]
This is occuring in version 3.1.3. I

1. Create a stock entry as usual.
2. Add two QU conversions with the same "Quantity unit from" name with different "Quanity unit to" values.
3. Purchase the product with the QU from value.
4. Stock appears as a journal entry but doesn't appear in the list of goods.

![image](https://user-images.githubusercontent.com/15952047/146659505-318380b4-4758-4b04-8742-ff3d8b2e9c7b.png)
![image](https://user-images.githubusercontent.com/15952047/146659513-034e3d59-7a3f-4e0e-bb2f-f21f379b67a5.png)
![image](https://user-images.githubusercontent.com/15952047/146659529-39cae38e-9e23-4aae-825f-b47cf60eb454.png)
![image](https://user-images.githubusercontent.com/15952047/146659536-f4948e8d-08d9-4f2b-beea-cb8d2ceb9eab.png)
![image](https://user-images.githubusercontent.com/15952047/146659556-2449ac35-4d38-48d4-bd1a-2fce3dd7a938.png)
![image](https://user-images.githubusercontent.com/15952047/146659562-2a0cf7c9-bcd0-4341-ba13-50e5f68b6ca2.png)
![image](https://user-images.githubusercontent.com/15952047/146659572-62dde41d-c1ff-4b55-b13a-63131a1c223d.png)

**Comment by berrnd** [comment]
Would be great if you can recreate such complexer scenarios on a [persistent demo instance](https://www.reddit.com/r/grocy/comments/jwnk9b), which is also mentioned on the issue template - most of the time there are much more details around than you described above.

I took the time and recreated everything what I see above:
https://test-xx6ja2ieucate6feawqyzs.demo-prerelease.grocy.info
([Product](https://test-xx6ja2ieucate6feawqyzs.demo-prerelease.grocy.info/product/27?returnto=%2Fstockoverview), [Stock entries](https://test-xx6ja2ieucate6feawqyzs.demo-prerelease.grocy.info/stockentries?product=27), [Stock journal](https://test-xx6ja2ieucate6feawqyzs.demo-prerelease.grocy.info/stockjournal?product=27), [Stock overview](https://test-xx6ja2ieucate6feawqyzs.demo-prerelease.grocy.info/stockoverview))

And I can't see a problem.
