### ISSUE TITLE
Bug: Barcode unit conversions not functioning on purchases on iOS

### ISSUE THREAD

**Issue by tamburra** [grocy/grocy#1723]
When scanning purchases into grocy from the iOS app, barcode unit conversions don't seem to be functioning correctly.  They work fine when scanned into the web app.  

For example i have eggs:
Quantity unit stock: piece
Default quantity unit purchase: piece
Factor purchase to stock quantity unit: 1
----- This means 1 Pack purchased will be converted into 1 Piece in stock

Barcode: 4099100278804
Amount: 12
Quantity unit: piece

On the web app I go to purchase and scan 4099100278804, it will enter 12 pieces into eggs.
On iOS I go to quick scan, tap purchase tab at top, scan barcode 4099100278804, it will enter 1 piece into eggs.

**Comment by berrnd** [comment]
This is not the repository of any community contributed app.

**Comment by tamburra** [comment]
Sorry. Found the swift repository.
