### ISSUE TITLE
Bug: It doesn't save prices

### ISSUE THREAD

**Issue by barbax7** [grocy/grocy#1724]
I'm trying to understand why and in what conditions, but sometimes it doesn't store the price of purchased products.
This issue is only in my installation, not in demo. I hope that somebody had the same issue...

https://user-images.githubusercontent.com/66796758/146831590-77a1db9f-289a-4b3c-b35d-9cddebd7d333.mp4

**Comment by berrnd** [comment]
> This issue is only in my installation

This is the place for reproducible bugs as [mentioned in README](https://github.com/grocy/grocy#questions--help--bug-reporting--feature-requests).

**Comment by berrnd** [comment]
Seems also to be [grocy-desktop](https://github.com/grocy/grocy-desktop). Maybe a browser related issue, grocy-desktop uses Chrome/Chromium/[CefSharp](https://github.com/cefsharp/CefSharp).

Maybe involved unit conversion are the problem. But not only that I can't see from the screenvideo above and the only thing would be to recreate the scenario on a [persistent demo instance](https://www.reddit.com/r/grocy/comments/jwnk9b) (also mentioned on the issue template) to maybe help by any chance.
