### ISSUE TITLE
Feature Request: Add https://www.ean-search.org as product-lookup option

### ISSUE THREAD

**Issue by Heinrich-F** [grocy/grocy#1728]
Open Food Facts (OFF) works decent for most food-related items for me so far. But not so much for other items (as they are not always edibles, and as such out of the scope of OFF). ean-search.org works very well for the few things I've tested so far.

ean-search does general household items, food-adjacent items (if we want to call them that) and even books/media. And it also does food. Whough OFF generally provides more information that information isn't used in grocy, and isn't really any reason to think OFF is better for grocy than ean-search is. Some example are at the end of this FR.

There seems to be one big downside. It is rate limited, and higher rates are behind paid account tiers. With this in mind, an option to use it only if OFF does not find anything might be good.

I would propose to add an opt-in switch for this lookup, as it is done for OFF right now.
How I'd like multiple sources of product data to work is as follows (describing from the perspective of inventory taking in the android app):
* Tap the barcode-scan button
* scan barcode
* if there is only one source, or all sources provide the same name, or only one source "knows" about the product (in other words, if the name is unambiguous)
  * prefill the product name with that
* if multiple sources are enabled, and provide different names for the scanned product
  * show all different options, tap to choose one, prefill the product name with that

Examples
* Media: book
  * https://www.ean-search.org/?q=9783453319554
* Media: music CD
  * https://www.ean-search.org/?q=5060001275413
* Media: Blu-ray
  * https://www.ean-search.org/?q=4041658191616
* "Food adjacent item": distilled water
  * https://www.ean-search.org/?q=4002832001053
* General household item: dowel
  * https://www.ean-search.org/?q=4048962238952
* Food stuff: juice
  * https://www.ean-search.org/?q=4005517016007

**Comment by berrnd** [comment]
grocy doesn't provide a Open Food Facts integration as of now ([Barcode Buddy](https://github.com/Forceu/barcodebuddy) does) and also the android app is not maintained here - so maybe you hit the wrong place.

External barcode lookups are currently possible via the API + implementing a lookup plugin ([README ref](https://github.com/grocy/grocy#barcode-lookup-via-external-services)).

Integrating this "API only way" somehow into the UI (and maybe ship some Plugins for popular lookup services; which one is "better" is highly personal preference and location dependent) is already tracked in #158.

More than 2 years after [my popular comment about that topic there](https://github.com/grocy/grocy/issues/158#issuecomment-468709713), I personally still see no real benefit. The only really useful information you would get from such services is the product name. Everything else need to be matched or changed (e.g. quantity units) or need to be added manually anyways - so well, I just don't get why this is so often requested. After 4 years daily using grocy I don't know when I had to add my last new product and if, that's done right in the purchase workflow and maybe takes 10 seconds.

However, all who need that are using [Barcode Buddy](https://github.com/Forceu/barcodebuddy) for looking up barcodes, so maybe consider adding this datasource there, should be no big thing to do...
