### ISSUE TITLE
Feature Request: Integration with 3rd party auth provider

### ISSUE THREAD

**Issue by CodingSpiderFox** [grocy/grocy#1729]
I'd like to use keycloak or auth0 for my infrastructure to reduce amount of accounts to manage so I'd like to use a centralized auth service

**Comment by berrnd** [comment]
LDAP and reverse proxy auth is built-in, any other system/provide can be added by implementing a middleware (class) which extends [`AuthMiddleware`](https://github.com/grocy/grocy/blob/master/middleware/AuthMiddleware.php).

Was already discussed a couple of times regarding Authelia which seems to work by the reverse-proxy-way.
