### ISSUE TITLE
Bug: 'No transaction was found by the given transaction id' error message in the REST API

### ISSUE THREAD

**Issue by jake404** [grocy/grocy#1731]
I'm trying to consume a parent product through the REST API, but I get the error message 'No transaction was found by the given transaction id'. It works fine with a regular product.

The URL for the POST request I'm using is:
http://192.168.1.5:9283/api/stock/products/42/consume

The JSON body is:
{
    "amount": 1,
    "transaction_type": "consume",
    "spoiled": false
}

When I consume the parent product in the WebUI, it works fine. It seems to be a problem with the REST API.

**Comment by berrnd** [comment]
This is the place for _reproducible_ bug reports which can be reproduced on the demo instance, not for general usage questions - both is [mentioned in README](https://github.com/grocy/grocy#questions--help--bug-reporting--feature-requests) and on the issue template.

The [`/stock/products/{productId}/consume`](https://demo.grocy.info/api#/Stock/post_stock_products__productId__consume) endpoint has an optional request body parameter `allow_subproduct_substitution`:
&nbsp;
![grafik](https://user-images.githubusercontent.com/2161815/147953760-7bd0a8c3-c6fa-4735-9b8d-0b7e65ccef5c.png)

The UI uses the API for everything, so a simple way to find things out, which work on the UI but not for your manual API requests, is to simply check by using e.g. your browsers developer tools to check what it does.
