### ISSUE TITLE
Feature Request: Expose `products_last_purchased` to API objects endpoint

### ISSUE THREAD

**Issue by MrJohnZoidberg** [grocy/grocy#1732]
I don't know whether this would be the best way to access the last price of all products at once.

But currently I only see a way with the `product details` stock request (which I would have to make for every product) or the `stock_log` objects request (this table can be very long and thus the request can be time consuming).

I need this for grocy-android to display a column on stock overview page or shopping list page with the last price and/or sort it.

The same issue would apply to the `products_average_price` table...

**Comment by berrnd** [comment]
Both views are now exposed via the "Generic entity interactions"-endpoints (read only, so only on `GET /objects/{entity}` and `GET /objects/{entity}/{objectId}`).

https://demo-prerelease.grocy.info/api/objects/products_last_purchased

https://demo-prerelease.grocy.info/api/objects/products_average_price
