### ISSUE TITLE
Product groups > show product count + link to products

### ISSUE THREAD

**Issue by hannahswain** [grocy/grocy#174]
It would be great to see a count for the number of products in a product group, as well as a link to the products, filtered by the product group. 

![product_group_columns](https://user-images.githubusercontent.com/17844465/54087419-fcd97600-4352-11e9-8461-f97d164a5cb9.png)

This would speed up navigation between the different types of master data.

**Comment by berrnd** [comment]
Thanks for your ideas! :)

So a column with the product count per group - thats clear.
For the products itself - maybe a list in a popup when clicking that count number. (?)

When using the search field on the master data/products page, it would also already search for product groups (the search field always searches all fields of the table) - so maybe this also already helps to list all products of a product group...

**Comment by hannahswain** [comment]
> For the products itself - maybe a list in a popup when clicking that count number. (?)

That could work, but I was thinking of linking to the Master data > Products, so that view could be re-used instead of creating a new pop-up.  That also puts you in the right place to edit any products as needed. 

> When using the search field on the master data/products page, it would also already search for product groups (the search field always searches all columns of the table)

That's true, and you can access the same information in this way. It would be nice to be able to see it from the Product Groups perspective, rather than needing to move over to the Products to access it.

**Comment by berrnd** [comment]
> That could work, but I was thinking of linking to the Master data > Products, so that view could be re-used instead of creating a new pop-up. That also puts you in the right place to edit any products as needed.

The only issue I see is how to display 20 products per product group in one row? That's why I thought of a popup...

Or maybe using "child rows", so the product group row can be expanded to show the products.
Example: https://datatables.net/examples/api/row_details.html

**Comment by hannahswain** [comment]
Neat ideas!  I can see you want to stay on that same screen - what's wrong with going to the product master section, and leaving behind the product groups? At that point, I'd like to be able to both view and edit the products.

**Comment by berrnd** [comment]
Ok, so maybe we simply add (on the product groups page):

- A column with the product count per group
- A link or button next to it which opens the products page filtered by the current product group

**Comment by hannahswain** [comment]
That would be perfect!

**Comment by berrnd** [comment]
Done, hope this helps. :)

![grafik](https://user-images.githubusercontent.com/2161815/55651785-02a76780-57ea-11e9-94c0-3cb3df95aea5.png)


https://demo-prerelease.grocy.info/productgroups
