### ISSUE TITLE
Feature Request: Make chores due "today" a different color than next 5 days 

### ISSUE THREAD

**Issue by ITguy3118** [grocy/grocy#1740]
I understand that showing chores due today was showing in red and was just fixed, I understand that that would technically be incorrect but it did serve as a human trigger that the chore was then due today for it to be in a different color than being due within the next 5 days. 

It would be nice if chores due "today" were in a different color altogether, this would serve as a visual queue to the user to differentiate between past due chores and chores due in the future. As it stands now, the current chores blend in with future chores. 

I suggest the color 'green ', like a 'mint green' if possible so as not to blend in with the forest green "mark completed" button 

![01-09-2022 -  11_21_13 - Chores overview _ grocy - Vivaldi](https://user-images.githubusercontent.com/90217713/148693208-06a882af-b0b9-4926-8a6a-f7ed9eb9ccaa.png)

**Comment by berrnd** [comment]
👍, good idea - also related to #1485.

Not sure about the color yet.
So far (most) colors are oriented on [default bootstrap colors](https://getbootstrap.com/docs/4.6/utilities/colors/#background-color), but the only other already used table background color would be gray (overdue stock items on /stockoverview), but grey is also not the best one since all tables are striped...
Maybe darker yellow or orange + bold text?

**Comment by ITguy3118** [comment]
Based on the choices of the default bootstrap colors, I would vote for either 
.bg-primary (blue) or .bg-info if possible ...green means success, but also means "go" ...but that would blend in too well with the button. 
.bg-primary would be a nice contrasting color from the green "completed" button and could also queue users in the affirmative to carry out the chore that day. 
bg-info (blueish-green) is more closer to what i was thinking as a shade of green....more of a blueish-green, but would still be contrastive enough to not blend with the "completed" button. 
I'm not aware of what the table dependencies are so i'm not sure if this is a a programmatic stretch or a simple change. 

I like the bold text idea, please include that in combination with an additional color if possible.
Thank you for considering this.

**Comment by berrnd** [comment]
That's now done - in the same way for all 3 pages (chores/tasks/batteries) and uses blue as the color for items due today:

![Screen Shot 2022-01-23 at 17 44 13](https://user-images.githubusercontent.com/2161815/150688743-bf3bf3f2-ebd1-4798-937a-46218306e44b.png)

**Comment by ITguy3118** [comment]
just pulled down the latest update.....soooooooooooooooooooooooooooo much nicer, good work sir
