### ISSUE TITLE
Bug: stock overview, label "product due" in French

### ISSUE THREAD

**Issue by chpego** [grocy/grocy#1742]
Something is wrong (a space missing), in the label "products are due within the next 5 days" on French translations, on other it's okay.

Tested on the last released, and preview released :
![image](https://user-images.githubusercontent.com/38792705/148739966-72aae05d-fb31-4441-8628-d5ecdcc66c52.png)

I looked in the translations on Transiflex, but I didn't find anything wrong

**Comment by berrnd** [comment]
Translations are managed via [Transifex](https://www.transifex.com/grocy/grocy/) as [mentioned in README](https://github.com/grocy/grocy#localization), not here - feel free to change it there.

**Comment by chpego** [comment]
Thanks for your message @berrnd , i found in Transifex the wrong translation .

**Comment by berrnd** [comment]
👍

Also already not longer reproducible on the pre-release demo: https://fr.demo-prerelease.grocy.info/stockoverview
(It's updated 10 minutes past every hour as also [mentioned in README](https://github.com/grocy/grocy#localization).)

**Comment by chpego** [comment]
Work's like a cham :)
