### ISSUE TITLE
Bug: 19 UNIQUE constraint failed (on saving user settings)

### ISSUE THREAD

**Issue by ivannunyadambiz** [grocy/grocy#1747]
switching tabs more often than not leads to:
"{\"error_message\":\"SQLSTATE[23000]: Integrity constraint violation: 19 UNIQUE constraint failed: user_settings.user_id, user_settings.key\"}"

**Comment by berrnd** [comment]
> switching tabs more often than not leads to:

Did that, can't reproduce it:


https://user-images.githubusercontent.com/2161815/149468918-60f838ac-13e2-4526-9a1f-6184af82d5e5.mp4

**Comment by ivannunyadambiz** [comment]
i'm not even the only one experiencing the issue
https://issueexplorer.com/issue/hassio-addons/addon-grocy/178

**Comment by berrnd** [comment]
More examples are in #1748.

Quoting myself from https://github.com/grocy/grocy/issues/1748#issuecomment-1012904026:
> it's at the end not a problem, just the error message is wrong.
