### ISSUE TITLE
Bug: "{\"error_message\":\"SQLSTATE[23000]: Integrity constraint violation: 19 UNIQUE constraint failed: user_settings.user_id, user_settings.key\"}"

### ISSUE THREAD

**Issue by ivannunyadambiz** [grocy/grocy#1748]
- deleted database
- logged in as admin
- clicked on "Rezepte"
got "{\"error_message\":\"SQLSTATE[23000]: Integrity constraint violation: 19 UNIQUE constraint failed: user_settings.user_id, user_settings.key\"}"

**Comment by ivannunyadambiz** [comment]
i then provoked it again with a click on "Batterien", but clicking on "Rezepte" does not cause it anymore

**Comment by ivannunyadambiz** [comment]
again, clicking on anything else, and then on "Batterien" again does not cause it a second time

**Comment by ivannunyadambiz** [comment]
deleted database again, logged in as admin, clicked on "Einkaufszettel". got the error. doesn't appear on rezepte or batterien now.

**Comment by berrnd** [comment]
I've also tried multiple things just in the last couple of minutes and got it once - it's at the end not a problem, just the error message is wrong.

Providing examples at first would have been too easy I guess, but thanks anyways.

Merging this into your other issue #1747 since multiple issues for the same problem also brings nothing than noise.

**Comment by ivannunyadambiz** [comment]
> I've also tried multiple things just in the last couple of minutes and got it once - it's at the end not a problem, just the error message is wrong.
> 
> Providing examples at first would have been too easy I guess, but thanks anyways.
> 
> Merging this into your other issue #1747 since multiple issues for the same problem also brings nothing than noise.

steamrolling a possibly not yet fully described issue within minutes as "not a bug" just seems like a dick move, but whatever.
glad i could help

**Comment by berrnd** [comment]
> just seems like a dick move

Your project, your rules (described for example on the issue template, and I really don't care what other think about me - happy to be a dick, if that's what it seems to be for you).
