### ISSUE TITLE
Make "products expiring in 5 days" variable rather than 5 days

### ISSUE THREAD

**Issue by hannahswain** [grocy/grocy#175]
This is very low priority, but I wanted to log it in case anyone else thinks of it. 

The "products expiring in 5 days" seems a bit arbitrary, and it would be useful to choose your own number of days:

![expiring_in_x_days](https://user-images.githubusercontent.com/17844465/54087548-39f23800-4354-11e9-8f9a-ab9d7eabf86f.png)

There may be a moment when I'd be traveling for 10 days and want to clean out everything that would expire. Or I'm meal planning for the next 7 days and want to know what needs to be used up. 

Maybe make the number of days clickable, and then show a simple entry field to choose the number of days?

**Comment by berrnd** [comment]
This is now done and can be configured for alle overview pages in the corresponding settings page:

![grafik](https://user-images.githubusercontent.com/2161815/56457905-8a13df80-6381-11e9-932c-c9a2dd205bcd.png)
