### ISSUE TITLE
Feature Request: recipes performance optimization

### ISSUE THREAD

**Issue by Hoffelhas** [grocy/grocy#1750]
When working with recipes, it takes about 10 seconds to load. This is for both:

- Going to the recipes page -> grocyserver/recipes
- Loading a different recipe -> grocyserver/recipes?recipe=NUM

Currently we only have around 100 recipes, but we are still in the process of adding more. However, currently the system is quite bothersome to use due to the loading times when e.g. adding new recipes and switching between recipes.

Could a solution be found to increase the performance of recipes?

Edit: A thing I noticed is that if I add 100 recipes to the on-line demo version, it feels faster than our own. However we have many more ingredients per recipe, could this also be an important factor?

**Comment by berrnd** [comment]
Related to #695.

The recipes page is definitely the most complex one, due to the data involved - so there is also most probably room for improvements.

> A thing I noticed is that if I add 100 recipes to the on-line demo version, it feels faster than our own. 

Server (view generation) and client performance (rendering, mostly the DOM sourced DataTable) is also a big factor, so maybe that's then that.

**Comment by berrnd** [comment]
For future comparison, new demo instance with a bigger number of recipes:
=> https://test-y8p74fcapkzc171wmxy4i.demo.grocy.info/recipes

- 441 normal recipes
- 1509 meal plan entries (meal plan entries also generate internal not visible recipes per day and week)
- => 1520 total recipes
- => /recipes loads here currently here in about 12.5 seconds

**Comment by berrnd** [comment]
I've optimized some things, comparison pre-relase demo instance (same data):
=> https://test-yn582ebblwcl7dvnctq75.demo-prerelease.grocy.info/recipes

==> /recipes loads here about 10 times faster

Should be ok I think, closing this.

//CC @Saturo78
