### ISSUE TITLE
Feature Request: Per item count open as out of stock

### ISSUE THREAD

**Issue by blue-hound** [grocy/grocy#1753]
In the config we can set opened items to be counted as out of stock or not. It would be nice to be able to set this on a per item basis. For example, smaller items could be listed as low stock, counting their open status if selected on the item, while bigger items that last much longer once opened wouldn't be counted, if the count as open status was not selected.

**Comment by berrnd** [comment]
That makes sense and is now done:

New product option:

![grafik](https://user-images.githubusercontent.com/2161815/152847200-6f4a75ac-dedb-4eb0-95cb-5c27bf03c2f7.png)

And a corresponding new "Presets for new products" setting:

![grafik](https://user-images.githubusercontent.com/2161815/152847261-9a9bd414-8f56-42eb-b6fc-3a2ff6c2b532.png)

Both, the product option for existing products as well as the preset, will be set to what `FEATURE_SETTING_STOCK_COUNT_OPENED_PRODUCTS_AGAINST_MINIMUM_STOCK_AMOUNT` was set before during migration.
