### ISSUE TITLE
Bug: Meal plan multiplies calories by serving amount although statet otherwise

### ISSUE THREAD

**Issue by berrnd** [grocy/grocy#1757]
_Originally reported in https://www.reddit.com/r/grocy/comments/sa6rax:_

The meal plan (for both recipes and products) should display the calories per single serving / QU (as the suffix for recipe entries already implies). Currently the calories are multiplied by the serving amount

**Comment by kyrious** [comment]
Hey there,

here is a screenshot of the problem.
![image](https://user-images.githubusercontent.com/16724955/150678466-230e5356-656c-4cea-85f5-4f50edbd7398.png)

In addition the green "eat the meal button" is greyed out. This is to consume the ingredients i presume?

**Comment by berrnd** [comment]
> In addition the green "eat the meal button" is greyed out. This is to consume the ingredients i presume?

That's not the topic here, but yes - as the tooltip and the icon implies:

![grafik](https://user-images.githubusercontent.com/2161815/150678814-ae6dee16-10ae-44be-b9fe-a21918eeb58e.png)

When nothing is in stock, nothing can be consumed, hence the button is disabled.
