### ISSUE TITLE
Bug: Media embeds (video/image) get cut off on Recipe Preparation on mobile devices

### ISSUE THREAD

**Issue by RaitaroH** [grocy/grocy#1758]
### Description
A youtube video embed/iframe or an image inside a recipe preparation, gets cutoff on mobile devices so it is not possible to see most of the image or video.
A minimum width seems to be enforced and going lower manually will be overwritten upon recipe save.

[Demo here.](https://test-i8vj4f6xyurs3rv5vqqcl.demo-prerelease.grocy.info/recipes?recipe=4)

### Steps to reproduce video
1. go to a recipe, edit it and add a video embed by clicking the "video" button and pasting a link
<img src="https://user-images.githubusercontent.com/19552720/150685145-ea5f35a0-6129-4a10-a8c5-7724276ce43d.png" width=50% height=50%></img>
2. either resize the browser or use the Developer Tools to emulate a phone like aspect ratio
3. notice how the video gets cut off and is impossible to scroll to the right to access the controls
<img src="https://user-images.githubusercontent.com/19552720/150685724-27a305db-a6ac-472e-97a7-d1c98cb98161.png" width=50% height=50%></img>

A possible solution I considered was to manually edit the iframe code, but the lowest width I can set is 560px. Any lower value will be reset to 560 upon saving the recipe (as seen in the raw code). Not sure if this is intended feature or not. Furthermore, there is no way to allow the video to go to fullscreen either; adding that to the iframe will get removed upon save too.

### Steps to reproduce image
As above, but add an image instead. I used the thumnail url of the same video.
If you simply paste a URL without using the "resize" features, the image can be too huge. For example the default pancake image associated with the recipe.

Image resized to 25%, seems too small in the preview:
<img src="https://user-images.githubusercontent.com/19552720/150686197-56e4fdb6-0810-4a1d-90c9-2696af9be7ac.png" width=50% height=50%></img>
After saving the recipe, the image minimum size has been reset... which exceeds the available space and get's cut off:
<img src="https://user-images.githubusercontent.com/19552720/150686218-f49571ca-19a0-4c79-a6cb-7d7bb3c7580e.png" width=50% height=50%></img>

### Expected results
The embeded item should be as wide as the grocy page and fit on mobile devices. User specified size (or shown by preview) needs to be respected.
I can open another issue for "allow fullscreen in embedded videos" too if you want.

**Comment by berrnd** [comment]
Nothing of that is handled by grocy, the WYSIWYG editor component used is Summernote:
https://github.com/summernote/summernote

So basically an issue there.

However, I've added workarounds in the commit referenced above to make your examples work.

>  I can open another issue for "allow fullscreen in embedded videos" too if you want.

I'll definitely won't add more workarounds regarding embed options of arbitrary video sites.

**Comment by RaitaroH** [comment]
Thank you for the workarounds. Much appreciated.
