### ISSUE TITLE
Feature Request: Show description in chore overview

### ISSUE THREAD

**Issue by zmingee** [grocy/grocy#1759]
Currently when you view the Chores Overview, and then select a chore from the list, the resultant window "Chore Overview" does not show the description. For some chores with multiple steps (like what to clean for "Clean living room"), having the description available would be very useful.

<img width="541" alt="image" src="https://user-images.githubusercontent.com/6311084/150693102-a3e52366-94d6-4498-b58e-7a674179016a.png">

**Comment by zmingee** [comment]
Out of curiosity, does this mean the feature is already implemented for vNEXT? I was actually looking at the source to see if I could submit a PR for it.

**Comment by zmingee** [comment]
Ah, yes, answered my own question

https://github.com/grocy/grocy/blob/master/public/viewjs/components/chorecard.js#L9

**Comment by berrnd** [comment]
This issue was closed by this commit (referenced above) which implements what you requested - that's how things are done...

**Comment by zmingee** [comment]
Ah, sorry, I overlooked the commit. Thank you for the attention, I wasn't expecting it to be done so quickly.
