### ISSUE TITLE
Feature request: User-defined attributes

### ISSUE THREAD

**Issue by ASMfreaK** [grocy/grocy#176]
There is task tracking software called taskwarrior for bash. It's coded in C++, but it's very extensible using so-called [User-Defined Attributes (UDA)](https://webcache.googleusercontent.com/search?q=cache:oxjhobwdh0kJ:https://taskwarrior.org/docs/udas.html+&cd=3&hl=ru&ct=clnk&gl=ru&client=firefox-b-d) and on-add and on-modify hooks.
I think, that it's not hard to add UDA's to grocy. We can store all UDA's in a VARCHAR field alongside products, serialized in JSON or JSON-like serializer BSON, msgpack, etc. On frontend, we could just pack and unpack them using user-defined plugins, generating ui on frontend.
The most successful UDA's could then be turned into plugins with their own tables/fields.

**Comment by berrnd** [comment]
Sounds good, but we would also need not only the functionality to attach the fields (to products, locations, or any other model), I think I would also except that I can filter/search for them e. g. on the stock overview page then...

**Comment by ASMfreaK** [comment]
Yes, in fact in taskwarrior filtering and sorting using UDAs is one of the killer features.

**Comment by berrnd** [comment]
This is now (nearly complete) done. :)

- Fields can be attached to any entity, new button "Configure userfields" at the top of each master data page
- Fields have types (text, number, datetime, etc.)
- There is an option per field if it should show up as an column in tables (fields configured e. g. for products will also show up on the stock overview page, if set)
- Input editors will be rendered based on the field type on bottom of the corresponding object edit page
- New API endpoints to get and set fields for an object (`GET/PUT ​/userfields​/{entity}​/{objectId}`)

Only implementing all editor types in [userfieldsform.blade.php](https://github.com/grocy/grocy/blob/master/views/components/userfieldsform.blade.php) is missing, will finish this the next days.

Any help for testing this is appreciated, feel free to use the [pre-release demo](https://demo-prerelease.grocy.info). I'm sure there will be bugs.

Screenshots:

A field configured like:
![grafik](https://user-images.githubusercontent.com/2161815/56527448-fb07f280-654d-11e9-9ba7-7430f9499a83.png)

Will be rendered like this on the edit/create page of products:
![grafik](https://user-images.githubusercontent.com/2161815/56527547-1b37b180-654e-11e9-83e8-26b0c05fec36.png)

And like that in any products related table:
![grafik](https://user-images.githubusercontent.com/2161815/56527671-4a4e2300-654e-11e9-9ec4-7e1e14e12b07.png)

**Comment by berrnd** [comment]
This is now ready.

There is also a new menu link below "Master data" to see/configure userfields for all entities.
Would be cool if you can play around a little bit with it before we release it (maybe in two weeks or so).

https://demo-prerelease.grocy.info/userfields

**Comment by ytilis** [comment]
Would it be possible to add a preset list to the userfield Type? So the user can provide a comma separated list or something similarly simple, which would display as a select dropdown on the entity form.

**Comment by ytilis** [comment]
Also, an additional question which might require its own ticket: 
Would it be possible to optionally associate userfields with a particular Product Groups? This would allow more granular data for certain types of products. 

A hypothetical example would be types of Tea (Black, Green, Herbal, Oolong, etc) or Coffee (Dark Roast, Light Roast, Decaf) so you can better track a more detailed breakdown of your products. These are obviously inapplicable to other types of products, so would benefit from only displaying when you select a particular product group.

**Comment by berrnd** [comment]
I moved this to separate issues - #239 and #240.

Userfields can also be attached to product groups, but that would not be enough to have them show up in the product edit page (and at the end the value should be attached to the product, not the product group). So makes sense, but would need a special handling here...

**Comment by fabiencharrasse** [comment]
> I think I would also except that I can filter/search for them

Hello @berrnd. Is there anything new for this feature? I have some custom fields for my recipes (season, type of cooking, etc) which would be very useful for me to be able to filter.

**Comment by berrnd** [comment]
> Is there anything new for this feature?

What do you expect to be new about it? This here is done since more than 3 years, that's why it's closed and not still open, and include since [v2.4.0](https://grocy.info/changelog#v2.4.0). So I don't get what you mean.

**Comment by fabiencharrasse** [comment]
In the quote I took from your first answer you were talking about being able to filter/search by custom attribute. I feel like this part of the functionality has been forgotten.

On the /recipes page I would like to be able to filter by custom attribute, is this currently possible? I feel like no.

**Comment by berrnd** [comment]
> I feel like this part of the functionality has been forgotten.

Not forgotten, not yet done, not tracked here - see #1850. Feel free to start it, if that's important for you.

&nbsp;
> On the /recipes page I would like to be able to filter by custom attribute, is this currently possible? I feel like no.

I don't feel it, but I know that searching via the generic search field above each table also searches in Userfields - since it searches in all visible table columns (since ever).
