### ISSUE TITLE
Bug: application closes after scanning barcode and rotating the phone twice

### ISSUE THREAD

**Issue by aldem** [grocy/grocy#1762]
I tried to scan a barcode and had to rotate the phone to landscape mode, but once scan is completed application closes when I rotate it back to portrait mode. Actually it looks like that any double rotation after successful scan leads to this issue.

This problem is reproducible on two different phones - Samsung Galaxy Note 8 (Android 9) and Pixel 6 (Android 12), app version 2.1.0 - thus I believe it is not device or OS related.

### Steps to reproduce:

- Choose "Purchase"
- Activate barcode scanner
- Scan something
- Rotate phone and make sure orientation changes
- Rotate it back

**Comment by berrnd** [comment]
This is not the repository of any of the community contributed mobile apps.
