### ISSUE TITLE
Bug: Consume form just decrements by 1

### ISSUE THREAD

**Issue by tony451** [grocy/grocy#1763]
Since upgrade to 3.1.3 the "Consume" page decrements stock by 1 as soon as the Product is chosen.
There is no opportunity to select the number of items or change any of the flag fields etc.. 
The stock number drops by 1, the change is committed and the empty form is returned, as if "Ok" had been pressed.

**Comment by berrnd** [comment]
> The stock number drops by 1, the change is committed and the empty form is returned, as if "Ok" had been pressed.

Exactly that is what "Scan mode" (as implied by the tooltip) is supposed to do - disable it and your "bug" will be resolved.

![grafik](https://user-images.githubusercontent.com/2161815/151146770-23513e09-3e93-4d52-95e6-9acba14d6bf5.png)

This is the place for reproducible issues. The better place for general help / usage questions is the r/grocy subreddit. All that is [mentioned in README](https://www.reddit.com/r/grocy) and on the issue template, which you obviously ignored both.
