### ISSUE TITLE
Feature Request: More structure for the recipes

### ISSUE THREAD

**Issue by God-of-Games2k** [grocy/grocy#1768]
Ich habe im Internet durch Zufall eine Vorstellung von tandoor.dev gefunden. Was mir hier sehr gut gefällt ist, das man die Rezepte zu Kochbüchern zusammenfassen und auch mit Tags versehen kann.
Durch die Kochbuch-Funktion kann ich ein bestimmtes Kochbuch auswählen und sehe die darin enthaltenen Rezepte, die meist thematisch zusammenpassen.
Durch die Tags ist es möglich nach Kuchen, Torten, Gebäck, Hauptspeisen oder anderem zu filtern.
Eine Bewertungsfunktion würde das Ganze noch komplettieren.

I found an introduction to tandoor.dev on the Internet by chance. What I like very much here is that you can combine the recipes into cookbooks and also tag them.
Through the cookbook function, I can select a particular cookbook and see the recipes contained therein, which usually fit together thematically.
Through the tags it is possible to filter by cakes, pies, pastries, main dishes or other.
A rating function would complete the whole thing.

Website: https://tandoor.dev/
Demo: https://app.tandoor.dev/accounts/login/?demo

**Comment by berrnd** [comment]
> combine the recipes into cookbooks and also tag them

Already possible by using Userfields (ref #176).
Also a question-duplicate of #1126 and #324.

Create a Userfield "Kochbuch", the same for "tags", group by "Kochbuch" on the recipes page, use the general search field to search for tags.

Demo instance to showcase that: https://test-oxp5huopvax85usrlhgab.demo.grocy.info/recipes
&nbsp;
![grafik](https://user-images.githubusercontent.com/2161815/152009539-5ba12986-f43f-43eb-9ff5-8607a37382e8.png)
&nbsp;
![grafik](https://user-images.githubusercontent.com/2161815/152010421-1d74a19d-07aa-4fc3-bdd3-f28b125d180c.png)

&nbsp;
>  A rating function would complete the whole thing.

Duplicate of #1150.

**Comment by God-of-Games2k** [comment]
Thank you for the detailed explanation.
This is exactly what I was looking for.
