### ISSUE TITLE
Feature Request: Date input shorthands: Extend by relative dates

### ISSUE THREAD

**Issue by fhold** [grocy/grocy#1773]
I would appreciate if the expiring date could be inputed in a notation like this: 6 month from now as: "+6m" and of course accordingly also for days and years.

I know the quick input via shift up/down for month but this is still less precise and much more keys to press.

**Comment by berrnd** [comment]
Well, commonly due/expiration dates on products don't say "in six months", but state a fix date.

There are more input shorthands ([README ref](https://github.com/grocy/grocy#input-shorthands-for-date-fields)) to input dates by only numbers (and therefore by the number pad) quickly.

Additionally, there is the product option `Default due days` which prefills the due date relative to today (I personally use this mostly for fresh products, to give them just a suitable due date):
&nbsp;
![grafik](https://user-images.githubusercontent.com/2161815/152675169-ec1fa922-a8a6-4e96-af96-01e22ab4de5f.png)

The same goes for the prodcut options `Default due days after opened`, `-freezing`, `-thawing`.

So I doubt this practically makes so much sense.

However, grocy is able to fit anyone - consider using [custom JS](https://github.com/grocy/grocy#adding-your-own-css-or-js-without-to-have-to-modify-the-application-itself) for such customizations.
Here is a snippet (for `data/custom_js.html`) which will provide that something like `+6d/m/y` in any date input field will be converted to the corresponding relative date:
```html
<script>
if (Grocy.Components.DateTimePicker)
{
	Grocy.Components.DateTimePicker.GetInputElement().on("keyup", function(e)
	{
		var inputElement = $(e.currentTarget);
		var format = inputElement.data("format");
		var value = inputElement.val();
		var lastCharacter = value.slice(-1);

		if (value.startsWith("+") && (lastCharacter == "d" || lastCharacter == "m" || lastCharacter == "y"))
		{
			var n = parseInt(value.substring(1, value.length - 1));

			if (lastCharacter == "d")
			{
				Grocy.Components.DateTimePicker.SetValue(moment().add(n, "days").format(format));
			}
			else if (lastCharacter == "m")
			{
				Grocy.Components.DateTimePicker.SetValue(moment().add(n, "months").format(format));
			}
			else if (lastCharacter == "y")
			{
				Grocy.Components.DateTimePicker.SetValue(moment().add(n, "years").format(format));
			}
		}
	});
}
</script>
```


https://user-images.githubusercontent.com/2161815/152675806-6a628e85-fd35-486d-8d8a-05db20f9f788.mp4

**Comment by berrnd** [comment]
It will not hurt when basically extending the current shorthands by the snippet above - set let's do that.

And let's also localize it, so that for example for German `+6t/m/j` will also work.

**Comment by fhold** [comment]
Wow you are freaking awesome!!! Thank you very much!

**Comment by berrnd** [comment]
It's now added, but I decided to not localize the d/m/y abbreviation, since the others are also not.

> - `[+/-]n[d/m/y]` gets expanded to a date relative to today, while adding `+` or subtracting `-` the number of days/months/years, in proper notation
>    - Example: `+1m` will be converted to the same day next month
