### ISSUE TITLE
Hide Completed Chores Each Day

### ISSUE THREAD

**Issue by jonnes86** [grocy/grocy#1777]
Hello, I am loving Grocy so far, so many features and uses.

I was wondering if there is/could be a way to view only the chores that are due on the current day, and then when they are tracked as executed they disappear from the list/filter for the rest of that day. My son finds it a bit confusing that when he marks it, it still shows on the list.

**Comment by berrnd** [comment]
There is the status filter (dropdown or just click the colored buttons) to filter chores:

![grafik](https://user-images.githubusercontent.com/2161815/153143324-ae5212e4-5a59-4750-afa3-7f88bfefc793.png)

The status "Due today" not part of the current release, but the next version (ref #1740).

The better place for general usage questions is the [subreddit](https://www.reddit.com/r/grocy) as [mentioned in README](https://github.com/grocy/grocy#questions--help--bug-reporting--feature-requests). This here is the issue tracker and the place for feature requests.
