### ISSUE TITLE
Model attribute(s) for Equipment listings

### ISSUE THREAD

**Issue by Thndr** [grocy/grocy#178]
For tracking equipment it would be useful not only to organize it by the names I give them, but also Model Name and Model #. This way if a person has multiple of the same product they can list what Model it is and even the model# while having a unique name for each item.

EG:
Kitchen Coffeemaker , FlossTech Supreme dual shot , FT#123456
Commons Coffeemachine , FlossTech Supreme dual shot , FT#123456

Or even with computer equipment
SmartFridge Brain , Raspberry Pi 2 B , RPi2B v1.2
SmartBrain Smarts , Raspberry Pi 3 B+ , RPi3B+ v1
SmartGarage Brain , Raspberry Pi 3 B+ , RPi3B+ v1

**Comment by berrnd** [comment]
Relates to #176 - it would be best / more flexible to have custom fields for any database object (products, equipment, locations, ...) - but would be of course more to do than just add some fixed fields...

**Comment by Thndr** [comment]
Yeah that request would solve my issue and also be more fully featured than what I have suggested.

**Comment by berrnd** [comment]
#176 (generic user defined fields for any entity) is more or less ready.

So closing this now, please follow #176 for any updates.
