### ISSUE TITLE
Bug: Prevent to consume a recipe when not all ingredients are in stock (was the case some time ago)

### ISSUE THREAD

**Issue by notEvil** [grocy/grocy#1781]
Hi,

this is easy to reproduce:

1. create a recipe with 2 ingredients
2. make sure the 'first' ingredient is in stock and the 'second' is not ('what first' and 'second' is, might not correspond to the order they are shown)
3. consume recipe

This will give you an error message saying that there isn't enough in stock and nothing was consumed. However, the 'first' ingredient is actually consumed.

As I have pointed out in https://github.com/grocy/grocy/issues/1240 the issue is that there is a loop consuming each ingredient iteration by iteration outside a transaction. I've modified the code to execute SAVEPOINT, RELEASE and ROLLBACK TO statements around the loop and this solves the issue. However I'd like to raise a more general question.

I've looked at the code and didn't find (with 2 or 3 exceptions) any transactions at all. Why is that? Imo this is rather curious because in case there's a bug leading to an exception anywhere in the code, the database might be in an inconsistent state (from the users perspective). If simple operations with single statement per operation is all grocy is about, this is fine. In general however it is advisable to use transactions by default to avoid such data inconsistencies.

I'd suggest to add savepoint,release,rollback to all routes and gladly prepare a PR. What do you think?

**Comment by berrnd** [comment]
The bug is that consuming a recipe with not all ingredients in-stock is possible (was not possible since ever, don't know right now when this changed). This will also result in what you think of: Consume all or nothing.

This will be tracked here, one topic per request. Whether that's done by transactions you obviously love, or by preventing to consume anything / restoring the old state, doesn't matter.

> I've looked at the code and didn't find (with 2 or 3 exceptions) any transactions at all. Why is that? Imo this is rather curious because in case there's a bug leading to an exception anywhere in the code, the database might be in an inconsistent state (from the users perspective). If simple operations with single statement per operation is all grocy is about, this is fine. In general however it is advisable to use transactions by default to avoid such data inconsistencies.

> I'd suggest to add savepoint,release,rollback to all routes and gladly prepare a PR. What do you think?

It's simply because non of that caused any problems so far. I only care about practical problems for grocy, not theoretical ones.

**Comment by berrnd** [comment]
> (was not possible since ever, don't know right now when this changed)

The check is in fact still there:
https://github.com/grocy/grocy/blob/8e3a9d6c049429b0f6a619a21584151a83156d6f/views/recipes.blade.php#L298

It just doesn't really disables the corresponding buttons since the big settings page redesign of #795.
