### ISSUE TITLE
Stocklist Table Options

### ISSUE THREAD

**Issue by lpott6** [grocy/grocy#1782]
Is it possible to have the Stocklist Table Options "Stick" after they are selected? Right now, I have to go into the settings and change them every time I open Grocy.
Thanks.
Larry O

**Comment by berrnd** [comment]
[README](https://github.com/grocy/grocy#questions--help--bug-reports--feature-requests) and the issue templates (which you successfully ignored) mentions that this is the place for Bug Reports and Feature Requests - sounds like neither of both.

Hidden/Shown/Grouped columns sorting/grouping is saved per table per user. If that doesn't work, please provide a reproducible example.
