### ISSUE TITLE
Bug: Product produced by recipe uses ingredient price instead of total recipe price

### ISSUE THREAD

**Issue by bababash** [grocy/grocy#1791]
Hi grocy team,
Thanks for bringing this fantastic project to life!
I am not sure if I am using this wrong but after trying all options and reading the docs I think this is an open bug.

Demo instance here:
https://test-w153cm118wkorb4tn7rws.demo.grocy.info

I have a recipe to produce 900 mL of chicken oil that needs 3.95 kg of chicken skin. I will want to vary the amount of oil produced as it is a sub-recipe. I created a recipe called Chicken Oil with 1 serving (mL) and iit calls for 0.0043 kg chicken (3.95kg/900mL).

Chicken Oil and Chicken Skin have both been added as products into grocy. 

Once I consume all ingredients needed by the recipe, Chicken Oil appears in my inventory but the price is wrong! It uses the recipe cost ($11 for 900mL and multiplies this by 900 servings). Grocy should be using the unit cost instead of the recipe cost when adding to inventory.

Is there any way around this?

![grocy_recipes](https://user-images.githubusercontent.com/10411294/154784883-72e1fa7b-24d8-439c-b615-63eee2965f79.png)

![grocy_inventory](https://user-images.githubusercontent.com/10411294/154784882-91ceed50-d3d1-4c21-9aa7-919bb8b3aec6.png)

**Comment by berrnd** [comment]
> Is there any way around this?

Is reprodocuble, thanks for finding that, so the way around is to fix it - of course the recipe costs should not be multiplied by the serving amount when adding the "Produces product" item to stock, like you mentioned.

**Comment by berrnd** [comment]
Here is a pre-release demo instance of your example:
https://test-gx99uycc8reb8xx4nhxii.demo-prerelease.grocy.info

![grafik](https://user-images.githubusercontent.com/2161815/154792664-3f556c6f-d7cd-4c77-ab44-6190d6dcc65b.png)

**Comment by bababash** [comment]
Thank you very much @berrnd!!

Do you have any advice on how to merge this in to my current installation? I am running the docker image and am not sure how to pull this commit. Any help would be greatly appreciated :)

**Comment by berrnd** [comment]
The changed files can be seen in the [above referenced commit](https://github.com/grocy/grocy/commit/e220b3e9f3b857036e8baa5c5cdcd871819eefe2). I don't have any experience with Docker, so can't help with that.
