### ISSUE TITLE
Feature Request: Add Quarterly option to period type in chores - Solved

### ISSUE THREAD

**Issue by mingw128** [grocy/grocy#1792]
Hi,
I think it would be great if there was a quarterly option in the chore tracker as some things are on that interval. I suppose a reoccurence option would knock out all potential interval options for folks (similar to what Outlook has for meeting reoccurence), but that might be a bunch more work. I'm thinking adding a quarterly option that is +120 days would suffice for most folks. Thanks.

**Comment by mingw128** [comment]
Daily option +120 works well enough, no need to add a quarterly option.

**Comment by berrnd** [comment]
Or use `Monthly` with a period interval of `3` to have it on the same day each 3 months:

![grafik](https://user-images.githubusercontent.com/2161815/154811107-0e697a99-41fb-46cd-a67b-0e55771836c0.png)
