### ISSUE TITLE
Bug: Purchase validation issue with product tare weight / purchase factor

### ISSUE THREAD

**Issue by blue-hound** [grocy/grocy#1795]
Private Demo: https://test-rt54hdmt6jpg63sfdc31v.demo-prerelease.grocy.info/

Using product flour.

Steps to reproduce: 

1. Create a product with tare weight handling enabled.
2. Enter a tare weight, in this case I used the tare weight from the instance (500g).
3. Change the default QU (I chose pack).
4. Change Factor (I used 500).
5. Save.
6. Go to Purchase and choose flour.
7. The validation text says 'This cannot be lower than 250,000 and needs to be a valid number with max. 4 decimal places'. This equals the tare weight * the factor (if anything is currectly in stock that is also added [tare * factor + in-stock]).

![image](https://user-images.githubusercontent.com/15952047/154855236-72ec0669-9220-4c2e-b79b-bd7a0ecc85e0.png)

**Comment by berrnd** [comment]
Tare weight handling is supposed for: 
> This is useful e.g. for flour in jars - on purchase/consume/inventory you always weigh the whole jar, the amount to be posted is then automatically calculated based on what is in stock and the tare weight defined below"

So it doesn't make sense with different units. It only makes sense when you always weigh the whole container. Probably related to #320.

Don't know if it's worth doing something for that, generally grocy is based on [GIGO](https://en.wikipedia.org/wiki/Garbage_in,_garbage_out)...

**Comment by blue-hound** [comment]
Hi, yeah, perhaps a UI change to disable the QU purchase factor when tare weight is enabled. I was just adding another comment. It makes it difficult to buy multiple units. I just purchased a second bag of coffee for example. I changed my setup expecting you to say just that. I change both to grams and added a QU override so a bag equals 907g (the amount in one bag). I now get this:
![image](https://user-images.githubusercontent.com/15952047/154856421-604f18fb-33df-4447-9e63-bdde55a07b85.png)

I just tried to edit the entry to change 907 to 935 to see what happens and the edit modal doesn't edit the right entry.

**Comment by blue-hound** [comment]
Just some more screen shots:
![image](https://user-images.githubusercontent.com/15952047/154856590-e0d756be-4f55-4157-aa44-15296bf9e551.png)
935g validates, but on submission nothing happens.
![image](https://user-images.githubusercontent.com/15952047/154856617-0c0b1b5a-0f9a-4ccd-97df-5ae2dc15524d.png)
As seen in the stock journal.
![image](https://user-images.githubusercontent.com/15952047/154856636-ac01a719-7e5b-4a1c-865e-83cd21788308.png)
I'll see if I can find an error in the logs, but I think my logging is turned way down or off. I'll try to turn it up and try again to reproduce and see if there is anything useful in there.

**Comment by berrnd** [comment]
Again: Tare weight handling is supposed to work **only when you weigh the whole container _all the time_**. That's mentioned in the tooltip.

And also again: This means that there is only one QU (the stock QU) for a tare weight handling enabled product.

So all that just sounds like what is already requested in #320.

**Comment by berrnd** [comment]
> I'll see if I can find an error in the logs

grocy has no logs (beside any default webserver logs). Check the browser console, the error there will be this one:
https://github.com/grocy/grocy/blob/777fcbae77388b399b95df6da4e5b577bb386545/services/StockService.php#L138
