### ISSUE TITLE
Feature Request: Transitive unit conversions

### ISSUE THREAD

**Issue by winterscar** [grocy/grocy#1801]
With the ability to define default conversions for units, we create an implicit graph of conversions. Consider for example:
1 tsp -> 5ml
1 l -> 1000 ml

Grocy should be able to infer from the above two 'facts' that 1 tsp is also 1/200th of a liter and update the liter and tsp units accordingly. 

Perhaps to avoid unexpected conversions, grocy could present users with a list of computed conversions whenever a new conversion is added in, and allow the user to also add in all newly converted conversions too.

**Comment by winterscar** [comment]
Another example where this would be useful:
- 1 tbsp -> 3 tsp
- 20g baking powder -> 1tbsp

Grocy might then infer that 6.6g baking powder -> 1tsp

**Comment by winterscar** [comment]
Huh, as I am creating a recipe, It seems like grocy does actually already do this. Is that the case?

**Comment by berrnd** [comment]
> Huh, as I am creating a recipe, It seems like grocy does actually already do this. Is that the case?

Of course. Unit conversion hierarchy is only limited to 1 level currently, it's also already tracked in #1360 to extend that.

See [here](https://github.com/grocy/grocy/issues/1663#issuecomment-961299603) or [there](https://github.com/grocy/grocy/issues/1727#issuecomment-1002435787) for an practical example what "1 level" is about.
