### ISSUE TITLE
Bug: Bestand pro Lagerort

### ISSUE THREAD

**Issue by Matt77CHE** [grocy/grocy#1809]
Wenn ein Artikel an mehreren Standorten gelagert wird, ist dies nicht als solches ersichtlich - es wird die Gesamt-Menge angezeigt.
Wenn ich einen Standort auswähle, werden mir nicht die Artikel von diesem Standort angezeigt, sondern der Gesamtbestand der jeweiligen Artikel.

**Comment by berrnd** [comment]
_Damit das alle verstehen, schreibe ich hier ausschließlich auf Englisch._

Not a bug, related to #449 and #682, duplicate of #1323 and #1259.

Would be great if you can check existing request first, like also mentioned on the issue template.

**Comment by berrnd** [comment]
> Wenn ein Artikel an mehreren Standorten gelagert wird, ist dies nicht als solches ersichtlich

Practical example: https://test-c8awo4r4pebfo1xfhzah4n.demo.grocy.info

5 Tomatoes are in stock, each single one in a different location, and that's visible when having a look at the [product stock entries](https://test-c8awo4r4pebfo1xfhzah4n.demo.grocy.info/stockentries?product=15), the [location content sheet](https://test-c8awo4r4pebfo1xfhzah4n.demo.grocy.info/locationcontentsheet) and also via the location dropdown on the [/consume](https://test-c8awo4r4pebfo1xfhzah4n.demo.grocy.info/consume) and [/transfer](https://test-c8awo4r4pebfo1xfhzah4n.demo.grocy.info/transfer) page.
