### ISSUE TITLE
Variable amount of ingredients

### ISSUE THREAD

**Issue by OmgImAlexis** [grocy/grocy#181]
Some of my recipes list 1 - 2 cups.

**Comment by berrnd** [comment]
Ok, and which amount should then be used to check against the stock amount? Or maybe should this only be possible when also using "Disable stock fulfillment checking for this ingredient" at the same time?

**Comment by OmgImAlexis** [comment]
I would say maybe have a multiselect for match top/middle/bottom. Some recipes you can lean towards a larger variance others you can’t. 🤔

Just thinking of how I have everything currently on paper.

**Comment by berrnd** [comment]
I just did this now by adding a new (text) field for recipe positions, when not empty, this is used to replace the displayed amount, the original amount is still used for stock fulfillment checking (if enabled), looks like this:

![grafik](https://user-images.githubusercontent.com/2161815/57179204-784f3380-6e7b-11e9-927a-73180691301b.png)
