### ISSUE TITLE
Feature Request: Absolute amount of packages of a product X in my pantry

### ISSUE THREAD

**Issue by kasperikoski** [grocy/grocy#1810]
Let's say I have the following products in my pantry:

7 x Tomato sauce (400 grams)
2 x Tomato sauce (250 grams)
10 x Tomato sauce (1 kg)

I simply can add 'Tomato sauce' as a product and set the storage unit as kg and the purchase unit in grams. Then I make the purchase. Everything plays well as I purchase (7 x 400) + (2 x 250) + (10 x 1000) = 13300 = 13,3 kg of tomato sauce.

As a prepper I still would be the most interested to be able to know the exact amount of the cans in my pantry as this is a product that has to be used after it is opened. In this example it would be a total of 19 cans (7+2+10). I can do this by changing the storage unit for "cans" but then I will miss the total storage value in kilos/grams.

As I make a purchase, I would like to be able to scan a barcode of the Tomato sauce (400 gram) and then tell the Grocy that I bought 7 cans of it. The barcode would automatically know that it is this 400 gram version of the Tomaro sauce but it would be up to me to tell to the Grocy how many cans did I bought. It would then add 2800 grams of it into the stock and also add a running number of 7 into a column of "amount of containers" or what ever I want it to be.

The whole Idea of this is that I then would not have to create a different product for every can size. Then I'd also would be able to know the absolute amount of cans in my pantry.

The other way of doing this is the ability to create a master products that would just be used to tell the combined info of the subproduct X, like cans in this instance.

**Comment by berrnd** [comment]
Exactly that is what parent/child products are made for.

If you want to see grams, or kg, or cans is up to how you configure units and unit conversions.

I took the time and created a practical example out of what you mentioned above: https://test-w6rsdze88q9bis9x1b58m.demo.grocy.info

I would say it's pretty much immediately visible that you have 13.300 Grams of "Tomato sauce" (parent product) and 19 Cans of the specific ones (child products).

![grafik](https://user-images.githubusercontent.com/2161815/156914890-de41bb88-6583-4daf-8016-68d82d23978d.png)

Also related to #1704.

The better place for general help / questions is the [r/grocy subreddit](https://www.reddit.com/r/grocy) as [mentioned in README](https://github.com/grocy/grocy#questions--help--bug-reports--feature-requests).

**Comment by berrnd** [comment]
Continuing the example: 

> as this is a product that has to be used after it is opened

When consuming "Tomato sauce" (parent product) and when only 1 of the child products is opened, exactly that will be consumed, since the default consume rule is (mentioned on multiple places) `Opened first, then first due first, then first in first out`.

> As I make a purchase, I would like to be able to scan a barcode of the Tomato sauce (400 gram) and then tell the Grocy that I bought 7 cans of it

Each of the child products can have its own barcode, like any products.
