### ISSUE TITLE
Feature Request: Sort recipe by product expiration/due date

### ISSUE THREAD

**Issue by Kryptortio** [grocy/grocy#1813]
I think it could be useful to have the option to sort recipes according to the closest expiration date for everything in it that you have in stock (or some kind of score so that two items expiring is worth more than one but less than something expired). Might give you a quicker overview for what you should be making instead of having to go to stock overview and having to search for each item individually (sometimes there can be several expiring soon).

Another way to do it would be if you could search for expiration status in recipes but then you can't check multiple statuses at the same time. Another possibility would be to be able to search for a list of products (OR search operator?). Sorry if this is already covered I just found this project.

**Comment by berrnd** [comment]
That's a good idea.

So maybe just a column which shows the number of due soon/overdue/expired products (based on the ingredients) per recipe.

Or such a column which displays a score (would need a fancy name :D) - maybe:
- 1 point per due soon ingredient
- 2 points per overdue ingredient
- 3 points per expired ingredient

So more points would mean "cook this now to not waste things".

Such a number is needed anyway to make that column properly sortable.

**Comment by Kryptortio** [comment]
Sure, although I would probably pick something a bit higher for expired things or things expiring today to make sure they get listed first (or make it a setting if you think people are likely to have different opinions). 

Depending on how the data/columns work I guess it might be possible to have both score and quantity if you want e.g. "[score] ([quantity]x)". Maybe you could even include an asterisk or a color when one of the items are expired or expiring today. 

As for a fancy name, I guess something short would be best since there is already a scroll bar and the value will also be short (if needed maybe a detailed explanation could be added as a title attribute). E.g. Due/Expire/Use/⌛ #/score/calc/sort/order/rank/grade/⍰ (font awesome \f059)

**Comment by berrnd** [comment]
This is now done - changelog excerpt:

> ### New feature: Recipes "Due score"
> 
> - A number (new column on the recipes page) which represents a score which is higher the more ingredients, of the corresponding recipe, currently in stock are due soon, overdue or already expired
>   - Or in other words: A score to see which recipes to cook to not waste already due/expired or due soon products
> - The score is in detail based on:
>   - 1 point for each due soon ingredient (based on the stock setting "Due soon days")
>   - 10 points per overdue ingredient
>   - 20 points per expired ingredient
>   - (or else 0)

Can be tested (in an hour or so) on the pre-release demo if you want: https://demo-prerelease.grocy.info

Hope that fits, if you have additionally ideas on that - always welcome.

**Comment by Kryptortio** [comment]
Nice, thanks!

**Comment by berrnd** [comment]
> Maybe you could even include an asterisk or a color when one of the items are expired or expiring today.

That's now also added, the ingredients / product names are highlighted in the corresponding color (red/yellow/grey, the same as used on the stock overview page):

![2022-03-31_14-36-17](https://user-images.githubusercontent.com/2161815/161147463-6aab77ab-5e40-4d8d-8d47-a47c2fe3d3e3.png)
