### ISSUE TITLE
Feature Request: Meal plan in the app

### ISSUE THREAD

**Issue by JMProjectsHub** [grocy/grocy#1815]
Hi! first of all, thank you very much for your hard work making this awesome self-hosted scheduler. I've been using it a few days and here is what I miss: I'm using the grocy-android app and it would be nice to see the meal plan in it instead of going to the website. In general, being able to see all the features (tasks, batteries overview, equipment...) in the app would be convenient, but the meal plan is the most one that I miss.

I hope it is easy to implement. Thank you!

**Comment by berrnd** [comment]
This is not the repository of any of the community contributed mobile apps.
