### ISSUE TITLE
Bug: cannot add entries to userentity

### ISSUE THREAD

**Issue by CrysoK** [grocy/grocy#1817]
Steps to reproduce it:
1. Go to Userentities and add:
    - Name: `notes`
    - Caption: `Notes`
    - Show in sidebar menu
    - Icon CSS Class: `fas fa-book`
2. Click "Configure fields" and add:
    - Name: `title`
    - Caption: `Title`
    - Type: `Text (single line)`

    And:
    - Name: `content`
    - Caption: `Content`
    - Type: `Text (multi line)`
3. Go to Notes and add one.
4. Nothing appears.

Example: https://test-bfrx33i0c2cvguf1nt7blq.demo-prerelease.grocy.info/userobjects/notes

**Comment by berrnd** [comment]
All your defined fields for that userentity don't have `Show as column in tables` enabled - and then it does exactly that, doesn't show any column...

Set that at least for one field and it will work:

![grafik](https://user-images.githubusercontent.com/2161815/158130429-e8edbc46-d8a7-4119-a4d2-e9b43229ec7d.png)
