### ISSUE TITLE
Make "Disable stock fulfillment checking for this ingredient" (recipe ingredients) a default option per product

### ISSUE THREAD

**Issue by OmgImAlexis** [grocy/grocy#182]
Both water and herbs in my garden can be considered in stock at all times. I'd like to still list the amount in the recipe.

**Comment by berrnd** [comment]
Just check "Disable stock fulfillment checking for this ingredient" on the recipe ingredient edit page. You can still enter an amount, but it is considered always as "enough in stock".

**Comment by OmgImAlexis** [comment]
Could we get a `Disable stock fulfillment checking for this ingredient` for the product itself? I'd like to set them so I don't need to for each recipe.

**Comment by berrnd** [comment]
Sure, I changed the title, will be tracked in this issue.

So you can set a default per product, this is then the default when adding a recipe ingredient, it would be still possible to change it in the recipe.
