### ISSUE TITLE
Bug: Hide Recipes Chores and Menuplan

### ISSUE THREAD

**Issue by Shaewen-Chronicles** [grocy/grocy#1822]
Even I have Disabled the functions in the config.php it is still showing in the Menu bar

![image](https://user-images.githubusercontent.com/3136108/158599597-730ca94b-7d82-469c-b722-f508dfde6921.png)

![image](https://user-images.githubusercontent.com/3136108/158599664-6d218c5d-e4d3-405a-b03a-5053c99b43bd.png)

**Comment by berrnd** [comment]
Can't be the case, not reproducible, example code ref:

https://github.com/grocy/grocy/blob/790368cdf42d9565427be8f07bf898d1445a4cd9/views/layout/default.blade.php#L172-L197

I guess:
- Wrong config file edited (the only place is `data/config.php`)
- Caching problem (empty your `data/viewcache` directory, should be not a problem, but some webserver might behave differently)
- Restart the PHP runtime if you use OPcache and haven't done that yet
