### ISSUE TITLE
A server error occured while processing your request

### ISSUE THREAD

**Issue by Matt77CHE** [grocy/grocy#1823]
I got this error mesage today when I tried to open Grocy website on my Laptop (homeserver):

Error source
/var/www/html/vendor/morris/lessql/src/LessQL/Database.php:723

Error message
SQLSTATE[HY000]: General error: 8 attempt to write a readonly database

> Stack trace
#0 /var/www/html/vendor/morris/lessql/src/LessQL/Database.php(723): PDOStatement->execute()
#1 /var/www/html/vendor/morris/lessql/src/LessQL/Result.php(381): LessQL\Database->update()
#2 /var/www/html/vendor/morris/lessql/src/LessQL/Row.php(256): LessQL\Result->update()
#3 /var/www/html/vendor/morris/lessql/src/LessQL/Row.php(296): LessQL\Row->save()
#4 /var/www/html/vendor/morris/lessql/src/LessQL/Row.php(415): LessQL\Row->save()
#5 /var/www/html/services/SessionService.php(67): LessQL\Row->update()
#6 /var/www/html/middleware/SessionAuthMiddleware.php(20): Grocy\Services\SessionService->IsValidSession()
#7 /var/www/html/middleware/DefaultAuthMiddleware.php(24): Grocy\Middleware\SessionAuthMiddleware->authenticate()
#8 /var/www/html/middleware/AuthMiddleware.php(52): Grocy\Middleware\DefaultAuthMiddleware->authenticate()
#9 /var/www/html/vendor/slim/slim/Slim/MiddlewareDispatcher.php(313): Grocy\Middleware\AuthMiddleware->__invoke()
#10 /var/www/html/vendor/slim/slim/Slim/Middleware/RoutingMiddleware.php(59): class@anonymous->handle()
#11 /var/www/html/vendor/slim/slim/Slim/MiddlewareDispatcher.php(147): Slim\Middleware\RoutingMiddleware->process()
#12 /var/www/html/vendor/slim/slim/Slim/Middleware/ErrorMiddleware.php(107): class@anonymous->handle()
#13 /var/www/html/vendor/slim/slim/Slim/MiddlewareDispatcher.php(147): Slim\Middleware\ErrorMiddleware->process()
#14 /var/www/html/middleware/CorsMiddleware.php(30): class@anonymous->handle()
#15 /var/www/html/vendor/slim/slim/Slim/MiddlewareDispatcher.php(313): Grocy\Middleware\CorsMiddleware->__invoke()
#16 /var/www/html/vendor/slim/slim/Slim/MiddlewareDispatcher.php(81): class@anonymous->handle()
#17 /var/www/html/vendor/slim/slim/Slim/App.php(215): Slim\MiddlewareDispatcher->handle()
#18 /var/www/html/vendor/slim/slim/Slim/App.php(199): Slim\App->handle()
#19 /var/www/html/app.php(106): Slim\App->run()
#20 /var/www/html/public/index.php(45): require_once('/var/www/html/a...')
#21 {main} <

Error source:
```
/var/www/html/vendor/morris/lessql/src/LessQL/Database.php:723
```

Error message:
```
SQLSTATE[HY000]: General error: 8 attempt to write a readonly database
```

Stack trace:
```
#0 /var/www/html/vendor/morris/lessql/src/LessQL/Database.php(723): PDOStatement->execute()
#1 /var/www/html/vendor/morris/lessql/src/LessQL/Result.php(381): LessQL\Database->update()
#2 /var/www/html/vendor/morris/lessql/src/LessQL/Row.php(256): LessQL\Result->update()
#3 /var/www/html/vendor/morris/lessql/src/LessQL/Row.php(296): LessQL\Row->save()
#4 /var/www/html/vendor/morris/lessql/src/LessQL/Row.php(415): LessQL\Row->save()
#5 /var/www/html/services/SessionService.php(67): LessQL\Row->update()
#6 /var/www/html/middleware/SessionAuthMiddleware.php(20): Grocy\Services\SessionService->IsValidSession()
#7 /var/www/html/middleware/DefaultAuthMiddleware.php(24): Grocy\Middleware\SessionAuthMiddleware->authenticate()
#8 /var/www/html/middleware/AuthMiddleware.php(52): Grocy\Middleware\DefaultAuthMiddleware->authenticate()
#9 /var/www/html/vendor/slim/slim/Slim/MiddlewareDispatcher.php(313): Grocy\Middleware\AuthMiddleware->__invoke()
#10 /var/www/html/vendor/slim/slim/Slim/Middleware/RoutingMiddleware.php(59): class@anonymous->handle()
#11 /var/www/html/vendor/slim/slim/Slim/MiddlewareDispatcher.php(147): Slim\Middleware\RoutingMiddleware->process()
#12 /var/www/html/vendor/slim/slim/Slim/Middleware/ErrorMiddleware.php(107): class@anonymous->handle()
#13 /var/www/html/vendor/slim/slim/Slim/MiddlewareDispatcher.php(147): Slim\Middleware\ErrorMiddleware->process()
#14 /var/www/html/middleware/CorsMiddleware.php(30): class@anonymous->handle()
#15 /var/www/html/vendor/slim/slim/Slim/MiddlewareDispatcher.php(313): Grocy\Middleware\CorsMiddleware->__invoke()
#16 /var/www/html/vendor/slim/slim/Slim/MiddlewareDispatcher.php(81): class@anonymous->handle()
#17 /var/www/html/vendor/slim/slim/Slim/App.php(215): Slim\MiddlewareDispatcher->handle()
#18 /var/www/html/vendor/slim/slim/Slim/App.php(199): Slim\App->handle()
#19 /var/www/html/app.php(106): Slim\App->run()
#20 /var/www/html/public/index.php(45): require_once('/var/www/html/a...')
#21 {main}
```

> System info:
```
{
    "grocy_version": {
        "Version": "3.2.0",
        "ReleaseDate": "2022-02-11"
    },
    "php_version": "7.4.28",
    "sqlite_version": "3.34.1",
    "os": "Linux 5.13.19-3-pve #1 SMP PVE 5.13.19-7 (Thu, 20 Jan 2022 16:37:56 +0100) x86_64",
    "client": "Mozilla\/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit\/537.36 (KHTML, like Gecko) Chrome\/99.0.4844.51 Safari\/537.36"
}
``` <

**Comment by Matt77CHE** [comment]
I noticed "attempt to write a readonly database" ....

What does it mean? - Why that? It was working yesterday....

**Comment by Matt77CHE** [comment]
I noticed, that the LXC on Proxmox seamed to have crashed ....

**Comment by berrnd** [comment]
This is the place for feature requests and reproducible bugs, that's [mentioned in README](https://github.com/grocy/grocy#questions--help--bug-reports--feature-requests) and on the issue template, would be super cool to not ignore that, which you just did.

This is more than clearly not a bug, just a configuration problem.

**Comment by berrnd** [comment]
5 cm mehr überlegen, obs überhaupt ein Bug sein kann oder nicht wär halt geil, ich werd die Leute nie verstehen, die einfach alles und jeden eigenen Konfigurationsscheiß erstmal als hochoffiziellen Bug aufschreiben müssen. 🙄

Noch mehr liebe ich nur die, die wegen sowas hier anrufen.
