### ISSUE TITLE
Feature Request: API call to create a task. 

### ISSUE THREAD

**Issue by karwosts** [grocy/grocy#1824]
I'm trying to track something like paying a monthly bill, in either chores or tasks. 

Monthly chore doesn't seem to cover the case well because I can't easily track it as complete in the prior month. E.g. if I have a bill due on 2nd of the month, I can't "track" the April 2nd bill as complete on March 30th of the prior month, because it will just keep rescheduling the chore in April until I track it in April. I could maybe workaround this by manually changing the tracking time to the next month every time I complete the chore, but I would rather not remember to have to do that. 

If there's no builtin way to easily track this kind of task, a workaround could be the ability to create a new task via an API call, so that I can have a monthly cron job that creates a task for that item each month for the next month. 

Other ideas for solving this would be a different type of monthly chore that doesn't just schedule the next execution for the next month, but rather schedules it one or two months ahead based on the day of the month. (So that if I track my chore on March 30, instead of scheduling the next execution for April 2nd, it schedules it for May 2nd. (But if I track the chore on April 1, it would still schedule the next one for May 2nd, because the current day of the month is earlier than the due day of the month). Though this solution is also a little problematic, since if I forget to pay my April bill until after it is overdue, if I track the chore on April 3rd and it is overdue, I wouldn't want it to skip my May payment. 

So the task creation via API seems like maybe the best solution for me, but I'm not sure which of these two approaches would be preferred. 

Other ideas welcome, thank you.

**Comment by berrnd** [comment]
Anything what the UI does is possible via the API, because the UI uses the API for everything. Beside checking [/api](https://demo.grocy.info/api), a very easy way to find out which endpoints are used for that is to use e.g. your browsers developer tools and just have a look at what happens.

Use the endpoint `POST /objects/{entity}`.

Example:
```
POST https://demo.grocy.info/api/objects/tasks

{
  "name": "x1",
  "due_date": "2022-03-22"
}
```
