### ISSUE TITLE
Bug: Maximum consumable amount is zero when `FEATURE_FLAG_STOCK_LOCATION_TRACKING` is disabled

### ISSUE THREAD

**Issue by JHthe4** [grocy/grocy#1829]
Hi,

I'm on the latest version of the linuxserver docker container, and I'm running into a bug where I can't consume any stock via the "consume" interface. I've tested and confirmed that consuming via both the quick access button in the stock overview and via the API work without a problem, and API calls return the correct amount in stock as well. 

I have set the max decimal places to zero, so I'm only looking at whole items. As you can see, the amount I can consume must be between 1 and 0, so I believe there's something wrong with the client-sided JS input validation or the backend API call / DB access here that's incorrectly returning 0 as the amount in stock. You can see the error in the following screenshot.

![image](https://user-images.githubusercontent.com/9847839/159672399-288d8bd2-b39c-45dd-afff-ca0ab0bd2416.png)

Settings I've changed in config.php are the following:
```Setting('DEFAULT_LOCALE', 'de');
Setting('CURRENCY', 'EUR');
Setting('BASE_URL', 'http://xxxxx.fritz.box/grocy');
Setting('DISABLE_AUTH', true);
Setting('FEATURE_FLAG_SHOPPINGLIST', false);
Setting('FEATURE_FLAG_RECIPES', false);
Setting('FEATURE_FLAG_CHORES', false);
Setting('FEATURE_FLAG_TASKS', false);
Setting('FEATURE_FLAG_BATTERIES', false);
Setting('FEATURE_FLAG_EQUIPMENT', false);
Setting('FEATURE_FLAG_CALENDAR', false);
Setting('FEATURE_FLAG_LABEL_PRINTER', false);
Setting('FEATURE_FLAG_STOCK_PRICE_TRACKING', false);
Setting('FEATURE_FLAG_STOCK_LOCATION_TRACKING', false);
Setting('FEATURE_FLAG_STOCK_BEST_BEFORE_DATE_TRACKING', false);
Setting('FEATURE_FLAG_STOCK_PRODUCT_OPENED_TRACKING', false);
Setting('FEATURE_FLAG_STOCK_PRODUCT_FREEZING', false);
Setting('FEATURE_FLAG_STOCK_BEST_BEFORE_DATE_FIELD_NUMBER_PAD', false);
```

As you can see, I've disabled a bunch of stuff since I just need the actual stock tracking, and I strongly suspect that the error is being created somewhere there, maybe a certain field is unpopulated or missing?

Has anyone run into this issue before and could give me some pointers?

Thanks!

**Comment by berrnd** [comment]
I took the time and tracked down step by step which of your multiple changed options leads to that:

Is reproducible when `FEATURE_FLAG_STOCK_LOCATION_TRACKING` is disabled.

All other changed options are not relevant for this problem.

**Comment by JHthe4** [comment]
Wow that was quick, thanks so much!
