### ISSUE TITLE
Different location for added products during inventory

### ISSUE THREAD

**Issue by OmgImAlexis** [grocy/grocy#183]
I store some of my meat in my deep freeze and some in my main fridge/freezer. It'd be great to know which one I put the meat in after shopping.

**Comment by berrnd** [comment]
On the purchase page you can pick a different location, it is prefilled with the products default location. The different locations are currently only considered when using "Filter by location" on the stock overview page.

Let me know if you have an idea/need where to show/use this better...

**Comment by OmgImAlexis** [comment]
Ah I don’t think I saw the dropdown on the inventory page when I was trying to add existing stock.

**Comment by berrnd** [comment]
Ok, so I think it would be of course good that inventory behaves the same - so let's add also add the location field there, would also only apply to added products (the same as for the best before date).
