### ISSUE TITLE
Feature Request: Manually reschedule chores

### ISSUE THREAD

**Issue by berrnd** [grocy/grocy#1830]
_Originally requested by @RubenKelevra in https://github.com/grocy/grocy/issues/1486#issuecomment-1076291866_

> I had a task which I was "not doing" for a while and couldn't skip. If I now skip the task it is moved forward by the regular interval, but that's like weeks in the past. So it's still not "checked and not necessary" but overdue.
>
> So my question is if this could be changed to having it "completed" and the due date is moved in the regular interval in the future. :)

Maybe simply provide an option to set the "next estimated tracking"-date entirely manually.

**Comment by RubenKelevra** [comment]
Actually that would be a great feature as well, but as an additional button.

It would solve issues like "put the trash bin at the street"  but it's a holiday, so the dates changed. So you could hit the button and select a new date on a calendar-popup.

But I feel like that's not the default case. The default would probably be something like "remind me tomorrow", "remind me in the default interval".

So maybe having dedicated buttons for more streamlined use would be neat.

Anyway, just moving it up to one interval in the future which is in the past isn't a thing which would be used by me. Can't really think of a use case for this either. :)

**Comment by RubenKelevra** [comment]
> Actually that would be a great feature as well, but as an additional button.
> 
> So maybe having dedicated buttons for more streamlined use would be neat.

Sorry, to be clear:

One button in the overview to skip and a calendar popup which also has "remind me tomorrow" and "skip one default interval", to avoid that the user has to look at the calendar and parse it for a simple skip. :)

**Comment by berrnd** [comment]
First change regarding that:

> - Optimized that when skipping chores via the chore tracking page, the given time is used as the "skipped time", not the scheduled next estimated tracking time of the corresponding chore (essentially making it possible to skip more then one schedule at once)

This should already be the solution for https://github.com/grocy/grocy/issues/1486#issuecomment-1076291866.

Example of such a "not done for a while chore": https://test-kmte4uquyabpfd6fjmeob.demo-prerelease.grocy.info/choresjournal?chore=7

**Comment by berrnd** [comment]
That's now done:

> - It's now possible to manually reschedule chores
>    - New entry "Reschedule next execution" in the context/more menu on the chores overview page
>    - If you have rescheduled a chore and want to continue the normal schedule instead, use the "Clear" button in the dialog
>    - Rescheduled chores will be highlighted with an corresponding icon next to the "next estiamted tracking date"

**Comment by berrnd** [comment]
Additionally to that it's now also possible to reassign chores - see https://github.com/grocy/grocy/issues/1492#issuecomment-1086850566.

**Comment by RubenKelevra** [comment]
Thanks! Awesome work, can't wait to see it in my installation :)
