### ISSUE TITLE
Equipment: Provide somewhere a baseUrl or a custom global constant 

### ISSUE THREAD

**Issue by hklages** [grocy/grocy#1832]
**Feature Request** 
An editable baseUrl or constant, what can be used in the equipment, notes, edit link dialog. Usage similiar to relative url.
That would enable users to change the source (NAS, document server) without editing all links.

**Use case**
I would like to define a document for each relevant equipment. Example see in Demo, stable version, Equipment, Kaffeemaschine or the attached picture. The document contains several links to my NAS, where different kind of data (invoices, manuals) are kept (raid 0, backup to glacier).  

My prototype works already fine. It uses a docker based static file http server, mounting the NAS data. The document links are resolved by the http server (read only access to the NAS shared folder). Unfortunately in case of a new http address I would have to edit every link in every document. Thats not practicable. 

**Example** 
![equ](https://user-images.githubusercontent.com/17273119/159763712-7674d5f1-1c8f-4f6b-b8bb-146fb6c0d902.jpg)

**Comment by berrnd** [comment]
> Unfortunately in case of a new http address I would have to edit every link in every document. Thats not practicable.

And if not only the base URL is not the same, but also something after that (e.g. used a plain file system before, now switching to object storage), this would also not fit.

Why not use an alias hostname or something like that to make the system changeable without having to change all references, probably not only in grocy (I would personally always prefer to do it like that).

This could also be solved by simply using [custom JS](https://github.com/grocy/grocy#adding-your-own-css-or-js-without-to-have-to-modify-the-application-itself) or using [the API](https://demo.grocy.info/api) or editing the database directly (all with much more flexibility in the most likely rare case this will ever be needed).

**Comment by berrnd** [comment]
And in fact, why not uploading the documents to grocy, when using grocy...

It's already possible to define custom fields, custom fields can also be files.

#978 is about to render them better for equipment.

Here is an example [custom JS](https://github.com/grocy/grocy#adding-your-own-css-or-js-without-to-have-to-modify-the-application-itself) snippet (for `data/custom_js.html`) which makes it possible to use a placeholder `{xyBaseUrl}` which then will be replaced in any link used in equipment notes on rendering:
```html
<script>
const XY_BASE_URL = "http://hhnas.fritz.box:8080";

if (Grocy.ActiveNav == "equipment")
{
	$("#description-tab-content").on("DOMSubtreeModified", function()
	{
		$("#description-tab-content a").each(function()
		{
			$(this).attr("href", decodeURI($(this).attr("href")).replace("{xyBaseUrl}", XY_BASE_URL));
		})
	});
}
</script>
```

**Comment by hklages** [comment]
Thanks, I will check it. 
Files in userfields look promising. I did not know that they show up as tabs.

**Comment by berrnd** [comment]
> I did not know that they show up as tabs.

They don't, #978 is exactly about adding that.

**Comment by hklages** [comment]
... userfield "link with title" works for me. I 
- dont have to upload any files (no redundancy)
- can use my standard backup procedure (Glacier incremental backup)
- could modify the links (if needed) with sql (hopefully) or your great api

**Comment by berrnd** [comment]
Cross-referencing #978 here - it's now possible to add multiple files / PDFs to each equipment by using Userfields, changelog excerpt:

> - It's now possible to add multiple files (PDFs / manuals) to each equipment
>    - Define as many Userfields for the entity `equipment` and use the type `File`
>    - => Each of those File-Userfields will be shown as a separate tab on the equipment page
