### ISSUE TITLE
Feature request: UX - Form Validation - consider not disabling submit controls, relying on html5 validations

### ISSUE THREAD

**Issue by CloCkWeRX** [grocy/grocy#1836]
Scenario: New Recipe
Omit name
Try to interact with the submit control

![image](https://user-images.githubusercontent.com/365751/160230451-94cb8a50-42e6-4bb8-abd2-a4c468df9c7f.png)

At this point, 

- you realise the submit button is disabled; but it is not clear _why_ if your locus of attention has moved to the bottom of the form; and don't look up. Most people use a pattern of scanning where they move top to bottom. There is no tooltip on the disabled control, etc, only a slight fading and cursor: pointer instead of cursor: hand
- it can be visually difficult to realise the submit control is disabled until you view it in the active state
- if you have scrolled below the page fold, you can no longer see the required indicators on the invalid field

![image](https://user-images.githubusercontent.com/365751/160230611-a1017aed-07b4-43fa-8e45-a4cd3e882f3f.png)

On mobile, this is easy to trigger:
![image](https://user-images.githubusercontent.com/365751/160230638-ac2ca49f-3049-40f7-91f1-fa18bb9525eb.png)

## Proposed alternative

Either:
- Remove the novalidate behaviour from the forms, allowing the native browser behaviour to show the invalid field; and scroll the viewport to the correct area or
- Fire `reportValidity()` on form submit?

Example:
https://getbootstrap.com/docs/5.0/forms/validation/

_Before validity checked_
![image](https://user-images.githubusercontent.com/365751/160230758-aaeed959-cde7-49b4-986a-4943b6280bf0.png)

_After_
![image](https://user-images.githubusercontent.com/365751/160230785-6fa142d4-8142-4a28-9489-0d881fa5d848.png)

* Browser has scrolled to invalid fields
* It is a lot more obvious what I have missed or need to correct.

Not sure if Bootstrap itself will improve this in a later release

**Comment by berrnd** [comment]
> Example:
> https://getbootstrap.com/docs/5.0/forms/validation/

Wrong assumption: grocy doesn't use Bootstrap 5 (it uses v4).

Naming it "Feature request" and labeling it "bug"? Cool..

**Comment by CloCkWeRX** [comment]
@berrnd 

1. I started filing a different UX bug
2. I decided the bug language wasn't right
3. I took the time to try to make a meaningful contribution in good faith

Is it really necessary to respond in the way you have? It's very discouraging for possible new contributors.

**Comment by berrnd** [comment]
> Is it really necessary to respond in the way you have? It's very discouraging for possible new contributors.

If you don't like how I respond to things, that's how it is then, I am who I am and I don't use overly flowery words for everything. I like facts. And I just clarified two things, without flowers.

This is a good suggestion, I just fiddled with it and it will be also already finished shortly.
