### ISSUE TITLE
Notifications don't have count

### ISSUE THREAD

**Issue by OmgImAlexis** [grocy/grocy#184]
I received this notification after adding 3 jars via the inventory page.

```
Stock amount of Mayver's Smooth Peanut Butter + Hemp Seed is now null jars
```

**Comment by berrnd** [comment]
Can you reproduce this?
(How is the product configured, what amount is currently in stock, etc.)...

**Comment by OmgImAlexis** [comment]
I'll try and workout how to reproduce this. I've had a similar error a few times now.

**Comment by berrnd** [comment]
Have you found a way to reproduce this?

**Comment by OmgImAlexis** [comment]
Still have no clue how I did this and it’s not happening any more since I updated. Here’s hoping it was just a random fluke. 💁‍♀️

**Comment by berrnd** [comment]
Ok, thanks - then I'll close this for now...
