### ISSUE TITLE
Bug: Factor for purchase not applied when stock and purchase units are the same

### ISSUE THREAD

**Issue by PulsarFX** [grocy/grocy#1841]
I've added a new product "_water":
https://test-zqzys59f5wl6ie3nwiunse.demo.grocy.info/product/27
- Quantity unit stock: Liter
- Default quantity unit purchase: Liter
- Factor purchase to stock quantity unit: 12

On the purchase page I bought 1 _water, which ended up in 1 Liter in stock. I'd expect to have the factor applied and got 12 in stock.
This works, when "Default quantity unit purchase" is something else than "Quantity unit stock".

**Comment by berrnd** [comment]
> On the purchase page I bought 1 _water, which ended up in 1 Liter in stock. I'd expect to have the factor applied and got 12 in stock.

You buy 1 **Liter** and expect to have 12 **Liters** in stock? Crazy.

And yes, based on the definition this should happen. In practice it doesn't happen because it's basically bullshit. Don't know yet if  fixing something which produces practical bullshit is the way to got, generally that's not the case for grocy.

**Comment by PulsarFX** [comment]
So how would I have to purchase this _water, to get the defined "Factor purchase to stock quantity unit: 12"  applied? I can't select anything else in the purchase form to make the factor be applied or not 🤔
If this is expected, that means, I'd have to add another unit, which resembles, that it is a unit of 12 liters?

**Comment by berrnd** [comment]
A conversion factor of 1 is enforced when the purchase and stock unit is the same.

Please just look at this in a real life manner:

You don't buy *1 Liter* and then have *12 Liters*  at home.
If that's really possible in your world, I'm really interested where that is (especially when it's not about water, thinking about buying only 100 grams of the best steak and getting then 1.2 kg, sounds really interesting 😜).

Is it not more likely that you buy *1 Pack* (or however you call multiple liters/bottles) and then have *12 Liters* in reality?

&nbsp;
> I can't select anything else in the purchase form to make the factor be applied or not 🤔
If this is expected, that means, I'd have to add another unit, which resembles, that it is a unit of 12 liters?

Exactly that, use "Pack" for example as the purchase unit and it will work, if adjusted your example demo instance above accordingly (product "_water2").

![grafik](https://user-images.githubusercontent.com/2161815/161633805-155de02b-2ae2-4c09-9859-5c4cfc7b0b27.png)

At any place, any related unit (means any unit the product directly or indirectly has a conversion for) is selectable.

**Comment by PulsarFX** [comment]
argh, I was just about to edit my last comment. Now put here:

edit:
the product edit page also states for the factor: 
"This means 1 Liter purchased will be converted into 12 Liters in stock"

So either the purchase page has a problem or the product edit page ;)

I want to prevent to litter the QUs with all sorts of Wasserkisten there are for sale: "12*0,7"  "9*1l"  "12*1l" ... 
The same goes for various other thingies, like eggs (6 or 10), flour (1kg, 2kg, 5kg ...), toilet paper (8 pack, 10 pack, 16 ...what ever is on sale ) and so on.

**Comment by berrnd** [comment]
> the product edit page also states for the factor:
> "This means 1 Liter purchased will be converted into 12 Liters in stock"

Yes, wrong hint there, doesn't change anything about that "buying 1 LIter = 12 Liter in stock" is just nonsense.

&nbsp;
> I want to prevent to litter the QUs with all sorts of Wasserkisten there are for sale: "12x0,7" "9x1l" "12x1l" ...

If you really want/need to track the detail of each "Wasserkisten size", then that's the way to go - creating a unit for each Kisten size. ("Buying 1 water and having x water in stock" makes even less sense when the "1 water" is 1l this time and 0.7l the other time - don't know how grocy should guess that).

Just having water as bottles in grocy and tracking 12 when I buy 12 and 9 when I buy 9 is what I personally do at home. But I also like things simple, not overly complicated.

A lot of other grocy users like to have a parent product "Water" and then each different bottle size as sub products. So you can track each individual bottle and still have the total amount at the parent product level.

Example demo instance for that:
https://test-sj8bl1i4wgdg833lku50gv.demo.grocy.info

**Comment by PulsarFX** [comment]
Good to know, that "Bottle"s can be product specific sizes this way ;-)

**Comment by berrnd** [comment]
> > the product edit page also states for the factor:
> > "This means 1 Liter purchased will be converted into 12 Liters in stock"
> 
> Yes, wrong hint there, doesn't change anything about that "buying 1 LIter = 12 Liter in stock" is just nonsense.

Just added in https://github.com/grocy/grocy/commit/4d4ae9812b21941a2dd0265992cd7f4a89d25091 to make this more clear:
"Factor purchase to stock quantity unit" is disabled when stock unit = purchase unit and no conversion info is shown in that case

&nbsp;
> "Bottle"s can be product specific sizes this way

Any unit, when related to another is unit, is defined by its factor - as that's naturally the case - grocy needs to know if it's a 1l or 0.7l or 0.5l or whatever bottle, that's the factor, it can't be guessed.

**Comment by PulsarFX** [comment]
Thanks, I've fallen for this just again, when I restructured the various juice types and the hint suggested 6 bottles will be added when I set the purchase factor to 6 😅

 So, good change.
