### ISSUE TITLE
Feature Request: Automatically handle (create/update/delete) related QU conversions

### ISSUE THREAD

**Issue by luisneto** [grocy/grocy#1844]
It is possible to create contradicting/inconsistent quantity unit conversions.

Example:
- Open the form to create a new product
- Specify 'Quantity unit stock' as Gram and 'Default quantity unit purchase' as Pack
- Specify 'Factor purchase to stock quantity unit' as 500, so that 1 pack is the equivalent of 500 grams. This also means that a Gram is the equivalent of 0.002 packs.
- Click 'Save & continue'
- In 'QU conversions' click 'Add'
- Select from 'Gram' to 'Pack', specify a factor different than 0.002 (which is the only correct value) and click 'Save'.

Result: the app allows this conversion to be saved. 
This means we now have rules that establish that converting from unit A to the unit B is not consistent with converting from unit B to unit A.
For example, that one pack is the equivalent of 500 grams and simultaneously that a gram is the equivalent of 250 packs.

Suggestions: 

1.  When specifying the 'Quantity unit stock' and 'Default quantity unit purchase' of the product, automatically create two 'QU conversion' records: one with the value 'Factor purchase to stock quantity unit', and the other with the value inferred from that (`1 divided by 'Factor purchase to stock quantity unit'`). A few rules should exist regarding actions on these records:
  - It should not be possible to delete them.
  - Either a) it should not be possible to modify them, or b) it could be possible to modify them and doing that would update the 'Factor purchase to stock quantity unit' of the product.
2. Remove the 'Create inverse QU conversion' check-box from the UI and always create the 'inverse QU conversion' when specifying a QU conversion. If one is updated, the other should be updated accordingly, and if one is deleted, the other should be deleted.

**Comment by berrnd** [comment]
I don't know how you come to the conclusion that that's a bug. You put bullshit in, you get bullshit out ([GIGO](https://en.wikipedia.org/wiki/Garbage_in,_garbage_out), grocy is generally based on that principal).

Of course what you said - creating/updating/deleting related conversions always automatically - makes sense and could be improved.

&nbsp;
> When specifying the 'Quantity unit stock' and 'Default quantity unit purchase' of the product, automatically create two 'QU conversion' records: one with the value 'Factor purchase to stock quantity unit', and the other with the value inferred from that (1 divided by 'Factor purchase to stock quantity unit'). A few rules should exist regarding actions on these records:

That `Default quantity unit purchase` and `Factor purchase to stock quantity unit` exists as a product option has historic reasons. A longer time ago that was the only conversion possible, multiple conversions came later. Internally it is just an automatic conversion (which also always get the inverse "updated" accordingly, [code ref](https://github.com/grocy/grocy/blob/af4dd446aba409001f0b6aee77d7293883b7d6d4/migrations/0152.sql#L8-L42)).

Those two product options could also be removed and replaced by just using "normal" QU conversions (those on the right side on the product edit page), internally, as said, that's already just the same.

**Comment by berrnd** [comment]
> Example:
> 
>     * Open the form to create a new product
> 
>     * Specify 'Quantity unit stock' as Gram and 'Default quantity unit purchase' as Pack
> 
>     * Specify 'Factor purchase to stock quantity unit' as 500, so that 1 pack is the equivalent of 500 grams. This also means that a Gram is the equivalent of 0.002 packs.
> 
>     * Click 'Save & continue'
> 
>     * In 'QU conversions' click 'Add'
> 
>     * Select from 'Gram' to 'Pack', specify a factor different than 0.002 (which is the only correct value) and click 'Save'.

For that example it is indeed possible to create the Gram -> Pack conversion with a wrong factor, but this has no effect and is no problem, since the `Factor purchase to stock quantity unit` product option is in that case for the same QU conversion and takes higher precedence in the "QU conversion hierarchy".

**Comment by luisneto** [comment]
> I don't know how you come to the conclusion that that's a bug. You put bullshit in, you get bullshit out

I didn't raise this strongly convinced it is a bug. I was between bug and feature request. I ended up raising as bug because grocy is allowing creating something that in the real-world does not make sense, but I didn't know if it's by design or a bug because I don't know the decisions that you made as the developer.

Thanks for the explanations about this and for being open to improving this.

>  it is currently indeed possible to create the Gram -> Pack conversion with a wrong factor, but this has no effect and is no problem, since the `Factor purchase to stock quantity unit` product option is in that case for the same QU conversion and takes higher precedence in the "QU conversion hierarchy".
To make sure we're on the same page: please note the `Factor purchase to stock quantity unit` product option is not the same conversion (Gram -> Pack). It is the inverse: Pack -> Gram.
I see it is not possible to manually add a Pack -> Gram conversion, because there is a validation to prevent that. But there is no validation to prevent adding the Gram -> Pack.
I think this would also be improved with the implementation of the suggested changes.

**Comment by berrnd** [comment]
> To make sure we're on the same page: please note the `Factor purchase to stock quantity unit` product option is not the same conversion (Gram -> Pack). It is the inverse: Pack -> Gram.

It is possible to create it, but it has no effect, because it wil not be used aynwhere, because the conversion based on `Factor purchase to stock quantity unit` (which includes the inverse one) has the highest precedence when evaluating the QU conversion hierarchy, as mentioned above. Can easily be prooved by simply using the conversion anywhere. Book a purchase, use it in a recipe, whatever - the manaully wrongly entered conversion will not be used anywhere.

**Comment by berrnd** [comment]
The following is changed about that:
- It's not possible to create a conversion which is already defined by the products `Factor purchase to stock quantity unit` anymore (any existing manually created conversion will be removed during migration)
- The `Create inverse QU conversion` checkbox was removed from the QU conversion edit form
- => Instead the corresponding inverse conversion is now always created/updated/deleted automatically

Feel free to play around with that on the [pre-release demo](https://demo-prerelease.grocy.info) if you want (will be updated in an hour or so).

**Comment by luisneto** [comment]
I experimented with it and it's definitely an improvement. Thank you, @berrnd.
