### ISSUE TITLE
Feature Request: Add default quantity unit for consumption

### ISSUE THREAD

**Issue by luisneto** [grocy/grocy#1845]
I think it would be useful to introduce a new field in Product configuration for specifying the default quantity unit of consumption. 
Stock management involves the following 3 different aspects:
1. Purchase: the input action
2. Stock viewing
3. Consume: the output action

It's already possible to define the quantity units for the stock input (1) and for viewing the stock (2). 
Introducing the 'Default quantity unit of consumption' would allow more flexibility by decoupling the units used for stock "viewing" from the units used for consumption.
It would eliminate the need to enter numbers and selecting a different unit when consuming a product. 

An example: a product that is bought in Grams, its stock is visualised in Grams, but consumed in cups or spoons.

**Comment by luisneto** [comment]
@berrnd : Any update on the implementation of this? Thanks in advance.

**Comment by berrnd** [comment]
> Any update on the implementation of this?

[README excerpt](https://github.com/grocy/grocy#roadmap):
_Roadmap: There is none. The progress of a specific bug/enhancement is always tracked in the corresponding issue, at least by commit comment references._

Nothing has been posted or referenced here above - conclusion: Nobody has done anything about it so far.

**Comment by berrnd** [comment]
Changelog excerpt for this:

> - New product option "Default quantity unit consume"
>    - Will be used/selected as the default quantity unit on the consume page
>    - The product's "Quick consume amount" is now displayed related to this quantity unit ("quick consume/open buttons" on the stock overview page)
>    - Defaults to the product's "Quantity unit stock" (so no changed behavior when not configured)

**Comment by luisneto** [comment]
Thanks very much for implementing this, @berrnd.
 
I'm trying this out in a pre-release instance, and I see that  the 'Quick Consume Amount' has to be expressed in terms of the Quantity Unit of stock. 
It would make more sense to express it in terms of the new 'Default quantity unit of consumption'.

Was this done intentionally so it didn't cause problems when the Default quantity unit of consumption is not set, you say [here](https://github.com/grocy/grocy/commit/0585e80c704871c2fc3185b85773f3a14c2c2b84#diff-bd021cd47359d31c1ecb76af714d638fa2b01ac8c66e27fc1e6b4c4dd55b7596R20)?

Additionally, the tooltip of the 'Quick Consume Field' still says 'Related to quantity unit stock'.

**Comment by berrnd** [comment]
> I'm trying this out in a pre-release instance, and I see that the 'Quick Consume Amount' has to be expressed in terms of the Quantity Unit of stock.
> It would make more sense to express it in terms of the new 'Default quantity unit of consumption'

The change was about _displaying_ the "Quick consume amount" (stock overview and consume page), not when defining it. Also, as always, it's kind of personal preference what "makes more sense" - at least when changing the definition to be based on qu_consume, it leads to potential confusion on the product edit page - change qu_consume multiple times, don't have a factor for the new QU pair, and so on. For me that wouldn't change anything, but I try to minimize the places where users could easily define bullshit - lessons learned in more than 5 years grocy and so on...

&nbsp;
> Was this done intentionally so it didn't cause problems when the Default quantity unit of consumption is not set, as you say [here](https://github.com/grocy/grocy/commit/0585e80c704871c2fc3185b85773f3a14c2c2b84#diff-bd021cd47359d31c1ecb76af714d638fa2b01ac8c66e27fc1e6b4c4dd55b7596R20)?

It will cause problems when not set, therefore it's technically prevented that it is unset and initialized by qu_stock during the update.

&nbsp;
> Additionally, the tooltip of the 'Quick Consume Field' still says 'Related to quantity unit stock'.

Because that's the case.
