### ISSUE TITLE
Bug: Equipment manual HTTP 401 Unauthorized when accessed, but download works

### ISSUE THREAD

**Issue by dadosch** [grocy/grocy#1847]
Trying to look at a equipment manual leads to a 401 Unathorized error, while downloading with the download button works.

A look at the failing request reveals that the auth cookie session is missing. Clearing the view cache didn't resolve it.

**Comment by berrnd** [comment]
Please provide the exact steps to reproduce a problem, as mentioned on the issue template.

I can't reproduce it:

https://user-images.githubusercontent.com/2161815/162573716-af4883f4-b467-4554-86dd-81865fd42cc3.mp4

![grafik](https://user-images.githubusercontent.com/2161815/162573719-761de191-15a7-4eaf-83cc-0a08c50cff9a.png)

> A look at the failing request reveals that the auth cookie session is missing.

Your browser sends cookies, grocy runs on the server and can't change anything about when your browser doesn't do that, for whatever reason.
