### ISSUE TITLE
Equipment location and owner

### ISSUE THREAD

**Issue by OmgImAlexis** [grocy/grocy#185]
As title states. I collect gaming consoles as well as games and I'd like to have more than just their manuals and a notes field as it'd make searching way easier.

**Comment by berrnd** [comment]
Sounds logical.

But I'm not sure if we should add these fields (which would be a simple thing) or if we should go for #176 (which is of course more complex, hence will maybe take a little bit longer to be added)...

**Comment by berrnd** [comment]
#176 (generic user defined fields for any entity) is more or less ready.

So closing this now, please follow #176 for any updates.
