### ISSUE TITLE
Bug: Recipe-API Fulfillment Id always 1

### ISSUE THREAD

**Issue by Tim-Otte** [grocy/grocy#1855]
Here a few items fetched via [/api/recipes/fulfillment](https://de.demo-prerelease.grocy.info/api/recipes/fulfillment):
```json
[
  {
    "id": "1",
    "recipe_id": "-96",
    "need_fulfilled": "0",
    "need_fulfilled_with_shopping_list": "0",
    "missing_products_count": "6",
    "costs": "68.06",
    "costs_per_serving": "68.06",
    "calories": "5693.6",
    "due_score": "20",
    "product_names_comma_separated": "Passierte Tomaten,Passierte Tomaten,Pizzateig,Salami,Eier,Hackfleisch,Mehl,Zucker,Käse,Zartbitterschokolade,Aufschnitt,Joghurt,Nudeln,Käse,Käse"
  },
  {
    "id": "1",
    "recipe_id": "-95",
    "need_fulfilled": "0",
    "need_fulfilled_with_shopping_list": "0",
    "missing_products_count": "3",
    "costs": "6.2325",
    "costs_per_serving": "6.2325",
    "calories": "492.0",
    "due_score": "0",
    "product_names_comma_separated": "Pizzateig,Salami,Passierte Tomaten,Käse"
  },
  {
    "id": "1",
    "recipe_id": "-87",
    "need_fulfilled": "1",
    "need_fulfilled_with_shopping_list": "1",
    "missing_products_count": "0",
    "costs": "5.6065",
    "costs_per_serving": "5.6065",
    "calories": "270.6",
    "due_score": "0",
    "product_names_comma_separated": "Käse,Zartbitterschokolade,Aufschnitt"
  },
  {
    "id": "1",
    "recipe_id": "-81",
    "need_fulfilled": "0",
    "need_fulfilled_with_shopping_list": "0",
    "missing_products_count": "3",
    "costs": "9.0",
    "costs_per_serving": "9.0",
    "calories": "615.0",
    "due_score": "0",
    "product_names_comma_separated": "Pizzateig,Salami,Passierte Tomaten,Joghurt,Käse"
  },...
]
```

**Comment by berrnd** [comment]
What do you expect the `id` to represent?

It's a dummy field (technically needed, [code ref](https://github.com/grocy/grocy/blob/c0a727fcfc72976facb58277d3d02bbb4b064dac/migrations/0181.sql#L180)), ignore it.

**Comment by Tim-Otte** [comment]
Why send an id if its not required? Any why splitting the recipe data and the fulfillment data into separate api calls?

I need it to store the data in the db of the grocy app and if it is always 1 only the last dataset is saved to the database. So I need to use the recipe id as the primary key to store the data in the database? That feels not right...

**Comment by berrnd** [comment]
> Why send an id if its not required?

Mentioning myself from 8 minutes ago:
It's a dummy field (technically needed, [code ref](https://github.com/grocy/grocy/blob/c0a727fcfc72976facb58277d3d02bbb4b064dac/migrations/0181.sql#L180)).

&nbsp;
> Any why splitting the recipe data and the fulfillment data into separate api calls?

When you look at the other API routes, static object data and computed data is generally separated.

&nbsp;
> So I need to use the recipe id as the primary key to store the data in the database?

Since [`/recipes/fulfillment`](https://demo.grocy.info/api#/Recipes/get_recipes_fulfillment) returns exactly one object per recipe, of course the `recipe_id` is unique there, even though your feelings may say something else.

**Comment by Tim-Otte** [comment]
Okay, then I will use the `recipe_id` as the primary key. Thank you for your help.
