### ISSUE TITLE
Bug: No such table: products_current_price

### ISSUE THREAD

**Issue by bielej** [grocy/grocy#1856]
#### Expected Behavior:
- Item is added to Shopping list and the _Create shopping list item_ windows disappears 
#### Actual Behavior
- The item gets added to the Shopping list, but the _Create shopping list item_ window does not disappear. Refreshing the page helps.
- A XHR requests is being send to `https://example.com/api/stock/products/160` resulting in a 400 response code with 
```{"error_message":"SQLSTATE[HY000]: General error: 1 no such table: products_current_price"}```

#### Steps to reproduce:
- Add a product to the Shopping list 

![image](https://user-images.githubusercontent.com/11682584/163112608-8e176360-3ea9-4e7c-b7dc-bee745fe2d77.png)

#### Versions:
- Version 3.3.0
- PHP Version 8.1.2
- SQLite Version 3.34.1
I have always used the `update.sh` script to update Grocy.

**Comment by berrnd** [comment]
You upgraded from a previous version and haven't applied database migrations. This is automatically done when visiting the root route - [README excerpt](https://github.com/grocy/grocy#database-migrations): 

> Database schema migration is automatically done when visiting the root (`/`) route (click on the logo in the left upper edge).

So simply do that and this "bug" will be resolved.

**Comment by berrnd** [comment]
Just saw that you reported exactly the same two years ago: #807

Maybe update your bookmark you use to access grocy to `/`, instead of any sub page directly, and this will never be a problem anymore.

**Comment by bielej** [comment]
Yeah, I'll have to update my bookmark :)
