### ISSUE TITLE
Bug: transaction_type not set correctly when adding stock

### ISSUE THREAD

**Issue by supergeorg** [grocy/grocy#1860]
The transaction_type is not set when adding stock via "/stock/products/{productId}/add". It always defaults to "purchase"

E.g.
`{
  "amount": 1,
  "best_before_date": "2019-01-19",
  "transaction_type": "self-production",
  "price": "1.99"
}`

leads to 

`[
  {
    "id": "439",
    "product_id": "1",
    "amount": "1",
    "best_before_date": "2019-01-19",
    "purchased_date": "2022-04-15",
    "used_date": null,
    "spoiled": "0",
    "stock_id": "62596f7263051",
    "transaction_type": "purchase",
    "price": "1.99",
    "undone": "0",
    "undone_timestamp": null,
    "opened_date": null,
    "location_id": "2",
    "recipe_id": null,
    "correlation_id": null,
    "transaction_id": "62596f7263045",
    "stock_row_id": null,
    "shopping_location_id": null,
    "user_id": "1",
    "row_created_timestamp": "2022-04-15 15:13:22",
    "note": null
  }
]`

Do I use it correctly or is this feature not intended this way?

**Comment by berrnd** [comment]
Just as a side note:
The only way a "Self-production" stock transaction can be made from within the web frontend is by consuming a recipe which has a "Produces product" set.
