### ISSUE TITLE
Bug: Error when saving products in Master Data

### ISSUE THREAD

**Issue by ITguy3118** [grocy/grocy#1861]
I get this error message when trying to save or copy a product from the master data, this started when i updated to version 3.3.0 from 3.2.0. it is reproduceable on the demo instance below 
https://test-xull8l9vdaaeqce0o2pj87.demo-prerelease.grocy.info/product/new

i updated in the normal way by using the update.sh script on my linux instance

It is NOT reproducable on the public demo instances 

steps, simply add a new product and fill out required fields and attempt to save, this will produce the error message 

![2022-15-04-10_44_18-Create product _ grocy - Vivaldi](https://user-images.githubusercontent.com/90217713/163591856-e640e508-30f9-4e49-afaa-51cc8e241af8.png)

**Comment by berrnd** [comment]
See #1858 or #1856 or #1852 or simply have a look at [the README](https://github.com/grocy/grocy#database-migrations).

**Comment by ITguy3118** [comment]
Thank you!!!
