### ISSUE TITLE
Bug: Quantity saved incorrectly when adding to a recipe 

### ISSUE THREAD

**Issue by aidenmitchell** [grocy/grocy#1862]
I have no idea why this is happening...

https://user-images.githubusercontent.com/30846409/163728491-454ca183-53d8-4b10-be53-88c88dc0025c.mov

**Comment by aidenmitchell** [comment]
It looks like it used this value even it it's greyed out (this is after I fixed it back to 1, it was 0.0667 before)

![Screen Shot 2022-04-17 at 11 57 36 AM](https://user-images.githubusercontent.com/30846409/163728591-9722e507-2fe8-42d0-8245-05b4b0b669e2.png)

**Comment by berrnd** [comment]
> I have no idea why this is happening

I also not, since I can't look behind screenvideos - most probably some weird unit conversion factors. Provide a reproducible example (like also mentioned on the issue template which you bypassed) and I'm happy to look into it.

**Comment by berrnd** [comment]
> It looks like it used this value even if it's greyed out (this is after I fixed it back to 1, it was 0.0667 before)

When you entered that, then switched the QUs or whatever, the value of course stays - also correct that (as you have already figured out) and everything works. Bullshit in = bullshit out, also known as [GIGO](https://en.wikipedia.org/wiki/Garbage_in,_garbage_out) - most parts of grocy are based on that principal.

**Comment by aidenmitchell** [comment]
Reproduced here: https://test-31v6vmkr7y27ypx5jsoze.demo-prerelease.grocy.info/recipe/7

If the value is grey, it should mean that it's doesn't affect anything, which in this case, it does. Why is the factor even used when the QU and default QU match?

**Comment by berrnd** [comment]
> Why is the factor even used when the QU and default QU match?

You entered that before, grocy can't guess that it's not longer valid for your new choice of units for the product.

**Comment by aidenmitchell** [comment]
Ok, but if the QU and default QU match, shouldn't it set back to 1, because they're the same? There's no reason to keep the incorrect value.

**Comment by aidenmitchell** [comment]
Also, there's a mismatch between the overview and the actual recipe.
![image](https://user-images.githubusercontent.com/30846409/163728984-9a7a235c-b8f3-4115-8be4-95faad1e65fe.png)
![image](https://user-images.githubusercontent.com/30846409/163728987-38b6848e-4efb-42f5-90fb-0b234422a91f.png)

**Comment by berrnd** [comment]
> Ok, but if the QU and default QU match, shouldn't it set back to 1, because they're the same? 

Could be done, or you could simply correct it. Many parts of grocy rely on that, not every single possible user input bullshit is checked.

&nbsp;
> ~Also, there's a mismatch between the overview and the actual recipe.~
> NVM, that's my bad (the serving was different on the overview page)

Since you obviously haven't read the issue template, just again: This here is the place for reproducible bugs, not the place for individual usage questions - please use the [r/grocy subreddit](https://www.reddit.com/r/grocy) for that.

**Comment by berrnd** [comment]
> https://github.com/grocy/grocy/commit/00ac935367e6940bc9d81b26341b5bfd4f084105

When QU stock/purchase is the same, the given factor is now ignored / 1 is enforced when conversion factors are resolved, so this will not be a "problem" anymore.
