### ISSUE TITLE
Bug: Error if wrong LDAP filter used

### ISSUE THREAD

**Issue by lomion0815** [grocy/grocy#1865]
**Problem:** When using LDAP authentication and entering an incorrect user filter (in my case I missed to put it into brackets "(...)") one will get an error page.

**Solution:** Throw an exception in /middleware/LdapAuthMiddleware.php line 45:
```
  $search = ldap_search($connect, GROCY_LDAP_BASE_DN, $filter);
+  if ($search == false)
+  {
+    throw new \Exception('LdapAuthMiddleware: ' . GROCY_LDAP_USER_FILTER . ' env variable is invalid'); 
+  }
  $result = ldap_get_entries($connect, $search);`
```
Did not test this so far. Might get around to it on weekend.

**Comment by berrnd** [comment]
Throwing a different error when there is already an error due to providing an invalid configuration value? I don't really get the point. Just provide a valid `LDAP_USER_FILTER`, [the example](https://github.com/grocy/grocy/blob/900a49a36a8120d7dc1b150c5939a4039a262bdb/config-dist.php#L90) contains those brackets.

This will behave the same for kind of any configuration option value in `data/config.php` - when providing an invalid value, something will most likely be broken.

**Comment by lomion0815** [comment]
There is no error message in the current code. The code snippet above is my suggestion for it.
But you are right, if the correct LDAP_USER_FILTER is provided, then there is no need for any error message ...

**Comment by berrnd** [comment]
> There is no error message in the current code.

Don't know how you tested that, I clearly get an error when providing an invalid `LDAP_USER_FILTER` value:

```
ldap_get_entries(): Argument #2 ($result) must be of type resource, bool given
```

grocy is generally based around the principal that when you put bullshit in, you get bullshit out.

When it makes you happy, I've added (own) error handling when doing LDAP searches (in a more generic way, not only the `LDAP_USER_FILTER` could be wrong, more each and every single provided option value - see https://github.com/grocy/grocy/commit/6ad761e067e991254f561d6877dc8fa675b5e9cc).

When providing an invalid value for `LDAP_USER_FILTER` the error message is now:
```
LDAP error: Bad search filter
```

**Comment by lomion0815** [comment]
Okay, there is "some" error message ... it did not crash or something ...
In fact it makes me happy ;-) Other fools like me might now find their bullshit more easily and can enjoy the great software you provided us a bit earlier.
Thanks for this improvement!
