### ISSUE TITLE
Either ingredient

### ISSUE THREAD

**Issue by OmgImAlexis** [grocy/grocy#187]
I have a few recipes that suggest sweet or white potatoes.

Hard coding one or the other doesn't really work and the `"Disable stock fulfillment checking for this ingredient"` would mean it wouldn't check for either when we need at least one.

**Comment by berrnd** [comment]
I think this can now be achived with #196.

Create a product "Potatoes" with the sub-products "Sweet potatoes" and "White potatoes" and use the "master" product "Patotoes" in the recipe...
