### ISSUE TITLE
Bug: Change quantity unit of existing products with(out) stock

### ISSUE THREAD

**Issue by ManniDerLibero** [grocy/grocy#1871]
At the beginning of my new "grocy" life, I added products like "package of 10 eggs" as pack instead of unit.
I tried to change those existing products, but it doesn't work.
I am using version 3.3.0 and I also tested this problem in the demo (https://demo-prerelease.grocy.info/products) See product "Change quantity unit of existing products with(out) stock""

I also found this comment: https://github.com/grocy/grocy/issues/1326#issuecomment-1066133315

How to reproduce:

Create new product: 
Name: "Change quantity unit of existing products with(out) stock"
Quantity unit stock: Pack
Default quantity unit purchase: Pack

Add Stock: 1 Pack

Manage master data -> products -> choose this product
First question: 
Dropdown list of "Quantity unit stock" only shows "Pack".
But "Default quantity unit purchase" list shows all units in system.
I want to change the "Quantity unit stock" to piece..

How to show "Piece" entry in "Quantity unit stock" list:
Change
Default quantity unit purchase: Piece

After clicking the save button:
"Quantity unit stock" shows "Pack" and "Piece".

If I choose
Quantity unit stock: Piece
Default quantity unit purchase: Pack

Save button doesn't work. Looks like an error which is not visible in frontend.

If I remove the stock, the same problem still exists.

**Comment by berrnd** [comment]
> I also found this comment: https://github.com/grocy/grocy/issues/1326#issuecomment-1066133315

Have you also read it?

> When the product was once added to stock, **there needs to exist a corresponding unit conversion for the new QU**

Create a corresponding unit conversion and everything will work.

How should grocy think how much Pieces 1 Pack is without having a conversion?
