### ISSUE TITLE
Bug: Shopping list to stock workflow setting not working

### ISSUE THREAD

**Issue by oisaak** [grocy/grocy#1875]
The shopping list setting in "Shopping list to stock workflow" to automatically do the booking cannot be reliably toggled.

Whatever I do, I cannot turn this setting off in my installation (the config-dist entry is set to false).
In the public demo I've noticed, that the workflow only works when the Product is in stock (even though price & std expiration date are set).

Whatever is set, the checkbox always remains unchecked when the settings page is loaded.

**Comment by berrnd** [comment]
> Whatever is set, the checkbox always remains unchecked when the settings page is loaded.

That's indeed the case, but the setting is properly saved regardless of that - so everything based on that works.
