### ISSUE TITLE
Feature Request: Unit Administration: Plural form of units not displayed in unit list

### ISSUE THREAD

**Issue by schnillerman** [grocy/grocy#1878]
The plural form as a list column would greatly help in identifiying which units do not yet have a plural form.

Background: I noticed that on the shopping list, units are not displayed for items with qty.  >1 which do not have a plural form for their unit defined.

Another solution option would be to use the singular form of the unit if the plural form is not defined. This is actually how I though it would work (e.g. for "g" (grams), "kg" (kilograms) - I wouldn't want to enter the same form twice in those cases).

**Comment by berrnd** [comment]
Both suggestions can be done.

However, that's just one of those you-are-too-lazy-and-then-get-bullshit-out things, so very very low priority for me.

Going once through your QUs and add the missing plural form(s) is most probably a 5 seconds or 5 minutes one time action, depending on how much units you have. Just filling in everything needed when creating is even easier.

**Comment by schnillerman** [comment]
Hi, thanks for getting back so quickly, and no, I'm not too lazy, I just figured that it would work differently. Stating the same text for singular and plural is redundant, in my eyes, and singular should be displayed if plural is left empty.

But, of course, this is just my view and I mean in no way to offend or trigger anyone with it.

Cheers.
