### ISSUE TITLE
Feature Request: Get back the Dynamic regular period for chores

### ISSUE THREAD

**Issue by maniackcrudelis** [grocy/grocy#1879]
Hi

First, thanks for your app that I'm discovering and enjoying so far.

I've started with 3.1.3 (YunoHost package) a few days ago and just upgraded to 3.3.0 that afternoon to discover that you removed the Dynamic regular period that I especially wanted to use for chores.

The Dynamic regular was saying: "This means the next execution of this chore is scheduled %s days after the last execution" while the Daily one is saying "This means the next execution of this chore is scheduled at the same time (based on the start date) every %s days"

For different reasons (including laziness of course) I may not do a chore on the due day, and sometimes, often because I'm out of home for work, I may not do it for several days or weeks. To be able to use Dynamic regular instead of a Daily with Due date rollover is really convenient for me, because first it does reassign the chore for x days after it's done, and not when it was supposed to be done, and second because I could see when I was supposed to do it and so adjust my priorities.

For now, I moved to the hourly period (done automatically when migrating) and it works, but for chores that are due every multiple months or years, hours aren't really easy to read.

Best would be actually to have for every type of period a setting that can be toggled to reschedule the task from the done date instead of the start date. So depending of the chore and the period we could have either a regular rescheduling based on the start date, or on the done date.

**Comment by berrnd** [comment]
Despite what the description says, please just try it.

There is no difference between the former "Dynamic regular" and current "Daily" period type, except that the time part of the next execution is based on the start date. Again, just to not miss the relevant detail: Only the time part, not the day.

This is the code ref where "Daily" chores get calculated:
https://github.com/grocy/grocy/blob/9c1fd176c01fcbe20c4e1cf6845b807828c9d42e/migrations/0185.sql#L44

This is the code ref where former "Dynamic regular" chores were get calculated:
https://github.com/grocy/grocy/blob/9c1fd176c01fcbe20c4e1cf6845b807828c9d42e/migrations/0164.sql#L68

No difference also technically, except for the time part.

**Comment by maniackcrudelis** [comment]
Hi @berrnd

Thanks for your quick answer.
I'm not familiar with SQL requests, but I trust you anyway.
As I've started using the app a few days ago, I didn't yet encounter a real rescheduling of my chores to realize that.

Still, would it be possible to have a period that reschedule from the done date instead of the start date ? That's really what I'm looking for.

**Comment by berrnd** [comment]
All period types are based on the last done/tracked date, the start date is only used for the very first scheduling (so when the chore was not yet done).

The TIME (not the DATE) is taken from the start date for Daily chores.
If you track dates only (`Track date only` chore option), that even doesn't matter at all.

Please just try things out and provide a concrete example ([persistent demo instances](https://www.reddit.com/r/grocy/comments/jwnk9b) are there for that) if something doesn't work.

By the chore period type reorganization in the last two releases nothing was removed, just reorganized.

**Comment by maniackcrudelis** [comment]
OK, I really didn't understood what the help was saying then !
Sorry for the noise.

I'll continue using the app and see how it works. Thanks for your time.
