### ISSUE TITLE
Equipment accessories (sub-equipment)

### ISSUE THREAD

**Issue by OmgImAlexis** [grocy/grocy#188]
I have accessories for my equipment which have manuals themselves.

**Comment by bigwoof** [comment]
Just chiming in here - this would be a useful addition, perhaps have the option to allow more than 1 attachment with a custom label, then you can have each manual as well as receipts etc.

**Comment by bigwoof** [comment]
Never Mind - it looks like it can be done with userfeilds:
https://github.com/grocy/grocy/issues/176

**Comment by berrnd** [comment]
Merged into #335 (means create a Userfield to reference that sub-equipment, once linking/re-using existing objects as Userfields is possible).
