### ISSUE TITLE
Feature Request: Enable continuous update also in "normal" shopping list mode

### ISSUE THREAD

**Issue by schnillerman** [grocy/grocy#1881]
It seems that **continuous updates / sync** with the server are only activated with _shopping mode_ active inside _shopping list view_.

In my personal opinion, it makes sense also without _shopping mode_ active since shopping lists might be processed (during shopping) by someone else even while administrating the list.

Also, adding items to the list while someone else should be synchronized immediately (but this is already implemented I think).

**Comment by berrnd** [comment]
I guess you're refering to any of the community contributed companion apps.

At least I don't know what you mean related to what we have in grocy.

**Comment by schnillerman** [comment]
Oh shoot - of course, you're right, my bad. Sorry.
