### ISSUE TITLE
Bug: 

### ISSUE THREAD

**Issue by RedAlan92** [grocy/grocy#1882]
Hi,

since two days, when I try to input a purchase, I have the price set as 0. I tried both format "." and "," : not working
How can I repair it ? I'm running a docker instance of grocy on my Synology NAS 

Version 3.3.0
Date de sortie 2022-04-08 il y a un mois

PHP Version 8.0.13
SQLite Version 3.35.5
OS Linux 3.10.105 #25556 SMP Sat Aug 28 02:15:10 CST 2021 x86_64
Client Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/15.4 Safari/605.1.15

![2](https://user-images.githubusercontent.com/86835185/167014761-38196be6-5017-4149-b2d7-e6a4b7558456.jpg)
![1](https://user-images.githubusercontent.com/86835185/167014770-53aefd94-f1a0-4446-9db6-74a2c88c0d69.jpeg)

Is there a way to edit price after a bad purchase ?

Regards

**Comment by berrnd** [comment]
I don't know how you come to the conclusion that this is a bug.

General usage questions fit better on the [r/grocy subreddit](https://www.reddit.com/r/grocy) as [mentioned in README](https://github.com/grocy/grocy#questions--help--bug-reports--feature-requests) and on the issue template.

The decimal separator is browser locale dependent. Everything works on the demo instance. So not reproducible. And there was no new release in the last two days, so also unrelated to the time when this should have been broken.

> Is there a way to edit price after a bad purchase ?

Of course, simple edit the corresponding stock entry.

**Comment by RedAlan92** [comment]
Ok, I check the subreddit. Strange, all my last entries in purchased are at 0 and when I edit the price, it return to 0

**Comment by RedAlan92** [comment]
After some tests, it not work using safari browser on macOS but work fine in chrome.

**Comment by berrnd** [comment]
> it not work using safari browser on macOS

Also that's not reproducible, just tried it:

https://user-images.githubusercontent.com/2161815/167077866-fb606fff-a7e7-4cd3-98ef-d65c51d1fe25.mp4

Maybe try disabling any installed extension, more than often some of them causes weird problems like that, not only for grocy.

**Comment by RedAlan92** [comment]
Strange, my safari browser have no extension. My safari version 15.4 (17613.1.17.1.13) on apple silicon macOS version 12.3.1, I use chrome at this moment for grocy

**Comment by RedAlan92** [comment]
https://user-images.githubusercontent.com/86835185/167262658-1f403b73-535b-408d-88d3-8325f6153deb.mp4

Today not working on chrome !

**Comment by berrnd** [comment]
I'm happy to look into each and every problem when having it reproducible. I can't help without having something reproducible.

When you say it doesn't work since 2 (or now probably 4 days), I guess it has worked before. So what have you changed? grocy wasn't modified in that time span regarding anything related to number inputs.

**Comment by berrnd** [comment]
Does it work with the same browser when trying to reproduce it on the demo instances? If so, just another sign that just something was changed and broken on your side...

**Comment by RedAlan92** [comment]
I've made no changed. This morning I input some new products : working fine, and at a moment it became impossible to enter prices, I don't know how I can identify the root cause !

My current process 
- Scan the new product on iPhone (with the last version) and try to identify it with open food facts
- complete informations and save
- scan the product and complete quantity, date and price (when I check in stock overview the price is not set)

I try changing price on computer, but it not work (tried on chrome and safari). There is a way to enable some logs ?

**Comment by berrnd** [comment]
> There is a way to enable some logs ?

grocy doesn't have any logs, I even don't know what should be logged regarding a problem like that.

Mabye have a look at the browser console / developer, probably somethings pops up there.

If you can't reproduce the scenario on a demo instance, I'm still unable to help and can just guess around (which I also end here, since brings nothing).

**Comment by RedAlan92** [comment]
Thanks for your time, if I retrieve a way to reproduce exactly I tell you
