### ISSUE TITLE
Unable to log into UnFollowSpy.com

### ISSUE THREAD

**Issue by kitchen5203** [grocy/grocy#1883]
I receive this message: Composer detected issues in your platform: Your Composer dependencies require a PHP version ">= 7.4.0".

**Comment by berrnd** [comment]
[README excerpt](https://github.com/grocy/grocy#how-to-install):

> Currently everything is only tested against (means 100 % works with) **PHP 8.0** with SQLite 3.27.2

So I can only guess you run a PHP version < 7.4. Update it, it's 2022.
