### ISSUE TITLE
Bug: When I change language to greek the shopping list view breaks

### ISSUE THREAD

**Issue by emmker** [grocy/grocy#1885]
When I change language to greek the shopping list view breaks
I have tried to reproduce the problem on demo but there is no change in greek there. 
All the other categories and tabs work fine except shopping list

<img width="1444" alt="Screenshot 2022-05-09 at 2 34 19 PM" src="https://user-images.githubusercontent.com/28418595/167401697-2fb9bb16-699e-49a8-878e-c9033190724b.png">

**Comment by berrnd** [comment]
Translations are managed via Transifex and maintained by the community, not here ([README ref](https://github.com/grocy/grocy#localization)).

The Greek localization is generally kind of outdated / incomplete: https://www.transifex.com/grocy/grocy/translate/#el_GR

And someone made just translations errors: This particular string breaks the /stockoverview page:
https://www.transifex.com/grocy/grocy/translate/#el_GR/strings/171921723

Feel free to fix/complete the Greek translations on Transifex.

**Comment by berrnd** [comment]
>  I have tried to reproduce the problem on demo but there is no change in greek there.

Each and every included language has its own demo:

Greek stable demo: https://el.demo.grocy.info

Greek pre-release demo: https://el.demo-prerelease.grocy.info

**Comment by berrnd** [comment]
> The transifex links give 404 errors

Sorry, Transifex is also not maintained by me - the both links above work (you have to login there of course).

> And the Greek demo has the same problem

Not a surprise, the Greek translation is broken by at least that string just also mentioned above. Fix it and the pre-release demo will instantly (in about an hour according to what's [mentioned in README](https://github.com/grocy/grocy#localization)) reflect the change.

The demo doesn't use any other translations that are provided by what's on Transifex / shipped in releases.

**Comment by berrnd** [comment]
I've just fixed most of the technically broken Greek strings by best-guess, the Greek pre-release demo basically works again: https://el.demo-prerelease.grocy.info

Due to not speaking Greek, I can't say if it's good or bad content-wise. The Greek translations also has > 200 untranslated strings currently...
