### ISSUE TITLE
Can anyone confirm if barcode scanning works / does not work with iPhone 12 Max Pro? 

### ISSUE THREAD

**Issue by ericblade** [grocy/grocy#1887]
Hi all!  Apologies if there's a better more suitable place for this, but I figured this might be the best place, among developers who might be able to help nail down if and what a problem might be -- 

I maintain the Quagga2 library that is used for Grocy's barcode scanning, and I'm receiving new reports that iPhone 12 Max Pro devices are specifically failing to initialize the camera scanner library, so they never return any result.  https://github.com/ericblade/quagga2/issues/419

I don't have access to that specific device to try and debug what is going on, so I'm hoping that users of the largest product that I know of that uses quagga2 can help me identify if there is in fact a problem, and what that problem might be? 

So I'd really appreciate it if anyone who has a iPhone 12 Max Pro can try out the barcode scanner, and see if it works?  

Thank you!
-Eric

**Comment by berrnd** [comment]
You reach definitely more grocy users when using the [r/grocy subreddit](https://github.com/grocy/grocy#questions--help--bug-reports--feature-requests).

**Comment by ericblade** [comment]
will do, thanks
