### ISSUE TITLE
Feature Request: allow entering prices with greater precision than they are being displayed

### ISSUE THREAD

**Issue by klaernie** [grocy/grocy#1893]
A few of the products I track using Grocy are the the ingredients for my vaping liquid. These make sense to track in millilitres, but are usually purchased in 100ml bottles. This means the typical bottle price of 32.95€ converts to 0.3295€/ml.

Entering this price is impossible while the stock setting "decimal places allowed for prices" is set to its default `2`.
But increasing this setting to the value `4` needed to enter the price correctly has an unexpected consequence: prices are now generally shown with 4 digits of precision.

In my mind this setting would need to be two different settings:
- one setting "decimal places allowed"
- one setting "decimal places shown"

Honestly, in my mind the input validation on prices is too strict there, the only limit that should be enforced is the one the database allows to store (just to prevent the user from entering values that would be corrupted silently by the database).
Now when I take a look at the database's understanding of that column I see the definition `DECIMAL(15, 2)`.

But as SQLite is the only supported database there are some further rules at play: the database does not enforce this type, else the setting would be pointless. So the actual limits enforced are dictated by the storage class in use, which would be `REAL` - ["stored as an 8-byte IEEE floating point number"](https://www.sqlite.org/datatype3.html).
Applying this I'd choose an input validation of "greater than 0 and matches `/\d*\.\d*/`" - roughly a "floating point number greater 0".

**Comment by berrnd** [comment]
You can enter the price per bottle (means per any product related QU) on [/purchase](https://demo.grocy.info/purchase) and [/inventory](https://demo.grocy.info/inventory).

#1859 is about to make this also possible when editing a stock entry.

&nbsp;
> Applying this I'd choose an input validation of "greater than 0 and matches `/\d*\.\d*/`" - roughly a "floating point number greater 0".

Consider using[ custom JS](https://github.com/grocy/grocy#adding-your-own-css-or-js-without-to-have-to-modify-the-application-itself) to customize anything to the very end and how you personally like it. Example snippet (for `/data/custom_js.html`) which makes exactly that possible:
```html
<script>
$(".locale-number-currency").keyup(function(event)
{
	// Always allow 10 decimal places
	$(this).attr("data-decimals", "10");
	$(this).attr("step", ".0000000001");
});
</script>
```

**Comment by klaernie** [comment]
> > Entering this price is impossible while the stock setting "decimal places allowed for prices" is set to its default `2`.
> 
> Well, no - you can enter the price per bottle (means per any product related QU) on [/purchase](https://demo.grocy.info/purchase) and [/inventory](https://demo.grocy.info/inventory).
> 
> #1859 is about to make this also possible when editing a stock entry.

Thanks, this makes now clear how I totally missed it - since I was editing the stock entries I created while away from the last invoices.

But reading the helptext on the Inventory page's Price field puzzles me a bit, since it says that the price is only applied to added products. It also lacks the clarity of "to which unit does the price apply" that the purchase page has.
Am I correct in my assumption, that only the stock entry edit screen allows you to adjust pricing after the initial purchase?

I'll definitely go with the `custom_js.html` path in general, since it allows me exactly the flexibility I'd expect.

**Comment by berrnd** [comment]
> But reading the helptext on the Inventory page's Price field puzzles me a bit, since it says that the price is only applied to added products.

Inventory ("Inventur") is about to correct the products stock amount.
Current stock 5, new stock 6 => 1 will be added and the entered price will be set for this 1 added item.
Curent stock 5, new stock 3 => 2 will be removed, the entered price (if any) won't be used.

&nbsp;
> Am I correct in my assumption, that only the stock entry edit screen allows you to adjust pricing after the initial purchase?

You can edit existing stock entries. Stock entries can only be created via [/purchase](https://demo.grocy.info/purchase) or [/inventory](https://demo.grocy.info/inventory).

**Comment by klaernie** [comment]
Sorry, I was probably still not enough caffeinated so I skipped over the thought, that of cause altering prices for existing stock doesn't make sense in an Inventory process.

But there is still the point, that the inventory page does have a price field, which after thinking for it longer must be "price per stock unit", but the page doesn't say so explicitly. 



> > Am I correct in my assumption, that only the stock entry edit screen allows you to adjust pricing after the initial purchase?
> 
> You can edit existing stock entries. Stock entries can only be created via [/purchase](https://demo.grocy.info/purchase) or [/inventory](https://demo.grocy.info/inventory).

I'm aware that I can edit stock entries there - but the question was rather a "is this the only place where I can edit stock entries?". 

But nevertheless a huge thanks for answering that quickly!

**Comment by berrnd** [comment]
> But there is still the point, that the inventory page does have a price field, which after thinking for it longer must be "price per stock unit", but the page doesn't say so explicitly.

The price was explicitly related to the products stock unit on /inventory before [v3.3.0](https://grocy.info/changelog#v3.3.0) (ref #1346). The conclusion was, that it makes more sense to relate the price to the selected unit (which still defaults to products stock unit on /inventory, but you can select any other product related QU and the amount and price is then based on that selected unit).

&nbsp;
Your original request here (separate input and display decimal places settings) is IMHO still valid, if you need/want that, feel free to reopen this.

**Comment by klaernie** [comment]
> Your original request here (separate input and display decimal places settings) is IMHO still valid, if you need/want that, feel free to reopen this.

I probably misunderstood your immediate jump to "use the custom javascript to implement this" as a "not useful to a broader audience". But of cause I'd be happy to see this as two separate settings, sparing me to frickle the custom javascript into the k8s-deployed container ;)

**Comment by berrnd** [comment]
The stock setting "Decimal places allowed for prices" is now splitted into two separate settings:

![grafik](https://user-images.githubusercontent.com/2161815/171998328-8facbc96-507b-4188-94ac-246424c9234b.png)

**Comment by klaernie** [comment]
Thanks a lot! Time for me to update!
