### ISSUE TITLE
Feature Request: Randomize Mealplans

### ISSUE THREAD

**Issue by PaganRedCat** [grocy/grocy#1894]
grocy on windows

I am a terrible undesive person if it comes to "what to eat". 
My idea would be that i can toggle a button in the meal planner and grocy just fills some recepies for dinner for a week in so i dont have to think again. Also nice if grocy will fill it in with the dishes i didnt eat for a period of time. 
If it was mentioned somewhere else i am sorry, merge then.

**Comment by berrnd** [comment]
Duplicate of #553 and #1028.
