### ISSUE TITLE
iOS Shopping List Showing Inventory Quantity # with Purchase Quantity Units

### ISSUE THREAD

**Issue by peterETA** [grocy/grocy#1896]
On demo
Added 1 pack of eggs to shopping list
on iOS shopping list, shows Eggs: 10 pieces (correctly, but can we show 1 Pack instead of 10 pieces?)
Clicking on Eggs, in detailed view, Amounts shows 10. Unit shows PACKS (incorrect -- should be 1 PACK or 10 pieces).

**Comment by berrnd** [comment]
This is not the repository of any of the community contributed mobile apps.
