### ISSUE TITLE
Feature Request: Chores overdue tracking / time display

### ISSUE THREAD

**Issue by SerinitySW** [grocy/grocy#1898]
Thanks so much for this app, I greatly appreciate it and it works fantastic. A feature my household is missing is the ability to have overdue chores highlighted in red, and displaying the times for chores that have due times. Both would be greatly beneficial in getting my roommates to do their chores on time.

**Comment by berrnd** [comment]
On [/choresoverview](https://demo-prerelease.grocy.info/choresoverview):
- Overdue chores are highlighted in red
- Chores due today are highlighted in blue
- Due soon (based on the ["Due soon days" setting](https://demo-prerelease.grocy.info/choressettings)) chores are highlighted in yellow

For each and every line of course the "Next estimated tracking time" is displayed.

![grafik](https://user-images.githubusercontent.com/2161815/170096009-ce8fdb3c-7bb7-4ed6-9126-1bfd206c5edc.png)

So sorry, but I don't get what your referring to.
