### ISSUE TITLE
Multiple/named shopping lists

### ISSUE THREAD

**Issue by OmgImAlexis** [grocy/grocy#190]
Easter is coming up so I'd like to have Hot Cross Buns scheduled to be on my shopping list but yet I don't need them to actually be in stock.

**Comment by berrnd** [comment]
You can add anything to the shopping list and just delete it when bought without adding it to stock...

Or maybe I did not get the point what you mean... (?) :)

**Comment by OmgImAlexis** [comment]
So another example would be a Roast we have once a month. I don't want items just hanging around as some of them may go off in that time but I'd like to have the certain items in my shopping list in time for the date.

Hopefully that helps clear it up.

**Comment by berrnd** [comment]
So what about multiple/named shopping lists, would that help?

**Comment by OmgImAlexis** [comment]
That would also work. 👍

**Comment by Altheran88** [comment]
In relation to https://github.com/grocy/grocy/issues/158#issuecomment-476576212

Split shopping lists by stores.

**Comment by d4kn** [comment]
I would also like this feature. Preferably the ability to manually create and name shopping lists and then specify certain items to automatically go to certain lists when added. Whether by store, by recipe or by other criteria.

**Comment by berrnd** [comment]
Thanks for all the ideas, but please create separate issues for different topics. Also maybe #146 is related to what you want.

This issue will cover to be able to create multiple/named shopping lists.

**Comment by berrnd** [comment]
This is now done, feel free to play around with it in the already updated [pre-release demo ](https://demo-prerelease.grocy.info/shoppinglist)and let me know when you have further ideas on this or when you notice any problems.
