### ISSUE TITLE
Shopping List viewing bug

### ISSUE THREAD

**Issue by espiney** [grocy/grocy#1900]
I have discovered a bug (I think) with in the viewing the shopping list.

**Error Output**
Error source:
```
/config/data/viewcache/89f9a234123b13e6abc7c4f03ea8471d32bbf1d1.php:250
```

Error message:
```
Unsupported operand types: string * string (View: /app/grocy/views/shoppinglist.blade.php)
```

Stack trace:
```
#0 /app/grocy/vendor/illuminate/view/Engines/PhpEngine.php(60): Illuminate\View\Engines\CompilerEngine->handleViewException()
#1 /app/grocy/vendor/illuminate/view/Engines/CompilerEngine.php(61): Illuminate\View\Engines\PhpEngine->evaluatePath()
#2 /app/grocy/vendor/illuminate/view/View.php(139): Illuminate\View\Engines\CompilerEngine->get()
#3 /app/grocy/vendor/illuminate/view/View.php(122): Illuminate\View\View->getContents()
#4 /app/grocy/vendor/illuminate/view/View.php(91): Illuminate\View\View->renderContents()
#5 /app/grocy/vendor/berrnd/slim-blade-view/src/Blade.php(173): Illuminate\View\View->render()
#6 /app/grocy/vendor/berrnd/slim-blade-view/src/Blade.php(65): Slim\Views\Blade->fetch()
#7 /app/grocy/controllers/BaseController.php(180): Slim\Views\Blade->render()
#8 /app/grocy/controllers/BaseController.php(203): Grocy\Controllers\BaseController->render()
#9 /app/grocy/controllers/StockController.php(374): Grocy\Controllers\BaseController->renderPage()
#10 /app/grocy/vendor/slim/slim/Slim/Handlers/Strategies/RequestResponse.php(43): Grocy\Controllers\StockController->ShoppingList()
#11 /app/grocy/vendor/slim/slim/Slim/Routing/Route.php(384): Slim\Handlers\Strategies\RequestResponse->__invoke()
#12 /app/grocy/vendor/slim/slim/Slim/MiddlewareDispatcher.php(81): Slim\Routing\Route->handle()
#13 /app/grocy/vendor/slim/slim/Slim/MiddlewareDispatcher.php(81): Slim\MiddlewareDispatcher->handle()
#14 /app/grocy/vendor/slim/slim/Slim/Routing/Route.php(341): Slim\MiddlewareDispatcher->handle()
#15 /app/grocy/vendor/slim/slim/Slim/Routing/RouteRunner.php(84): Slim\Routing\Route->run()
#16 /app/grocy/middleware/LocaleMiddleware.php(16): Slim\Routing\RouteRunner->handle()
#17 /app/grocy/vendor/slim/slim/Slim/MiddlewareDispatcher.php(313): Grocy\Middleware\LocaleMiddleware->__invoke()
#18 /app/grocy/middleware/AuthMiddleware.php(76): Psr\Http\Server\RequestHandlerInterface@anonymous->handle()
#19 /app/grocy/vendor/slim/slim/Slim/MiddlewareDispatcher.php(313): Grocy\Middleware\AuthMiddleware->__invoke()
#20 /app/grocy/vendor/slim/slim/Slim/Middleware/RoutingMiddleware.php(59): Psr\Http\Server\RequestHandlerInterface@anonymous->handle()
#21 /app/grocy/vendor/slim/slim/Slim/MiddlewareDispatcher.php(147): Slim\Middleware\RoutingMiddleware->process()
#22 /app/grocy/vendor/slim/slim/Slim/Middleware/ErrorMiddleware.php(107): Psr\Http\Server\RequestHandlerInterface@anonymous->handle()
#23 /app/grocy/vendor/slim/slim/Slim/MiddlewareDispatcher.php(147): Slim\Middleware\ErrorMiddleware->process()
#24 /app/grocy/middleware/CorsMiddleware.php(30): Psr\Http\Server\RequestHandlerInterface@anonymous->handle()
#25 /app/grocy/vendor/slim/slim/Slim/MiddlewareDispatcher.php(313): Grocy\Middleware\CorsMiddleware->__invoke()
#26 /app/grocy/vendor/slim/slim/Slim/MiddlewareDispatcher.php(81): Psr\Http\Server\RequestHandlerInterface@anonymous->handle()
#27 /app/grocy/vendor/slim/slim/Slim/App.php(215): Slim\MiddlewareDispatcher->handle()
#28 /app/grocy/vendor/slim/slim/Slim/App.php(199): Slim\App->handle()
#29 /app/grocy/app.php(106): Slim\App->run()
#30 /app/grocy/public/index.php(45): require_once('...')
#31 {main}
```

System info:
```
{
    "grocy_version": {
        "Version": "3.3.0",
        "ReleaseDate": "2022-04-08"
    },
    "php_version": "8.0.13",
    "sqlite_version": "3.35.5",
    "os": "Linux 4.4.180+ #42218 SMP Mon Oct 18 19:17:56 CST 2021 x86_64",
    "client": "Mozilla\/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit\/537.36 (KHTML, like Gecko) Chrome\/101.0.4951.67 Safari\/537.36"
}
```

This is probably covered somewhere, but I haven't been able to find it.

**Comment by berrnd** [comment]
> This is probably covered somewhere, but I haven't been able to find it.

Please see #1884 which is essentially about the same.

From the error message you most likely have a string where a number is expected, I doubt that's possible to get via the web frontend. Maybe you have inputted some bullshit via the API or whatever.

**Comment by sjaeckel** [comment]
I've entered some products through the web UI with mostly default values, some which are packs.

I played around with the "Factor purchase to stock quantity unit" value, changed it to something and then deleted what's in the field, switched the "Quantity unit stock" type so the "Factor purchase to stock quantity unit" value gets grayed out again and saved the article.

Adding the article to a shopping list reproduces the crash.

> Maybe you have inputted some bullshit via the API or whatever.

Maybe you shouldn't be so rude and throw words at people if in the end your input checks might not be completely fault tolerant ...

**Comment by berrnd** [comment]
> I played around with the "Factor purchase to stock quantity unit" value, changed it to something and then deleted what's in the field, switched the "Quantity unit stock" type so the "Factor purchase to stock quantity unit" value gets grayed out again and saved the article.

I'm unable to reproduce this particular problem by that.
Private demo instance: https://test-xkdug6jgi3bfi20ez233i6.demo-prerelease.grocy.info
Product ["Test1"](https://test-xkdug6jgi3bfi20ez233i6.demo-prerelease.grocy.info/product/27) has that empty "Factor purchase to stock quantity unit" and it's no problem there adding it to the [shopping list](https://test-xkdug6jgi3bfi20ez233i6.demo-prerelease.grocy.info/shoppinglist).

I'm happy to fix any problem and did that kind of immediately since 5 years or so for grocy, but without having a problem reproducible, I can't help.

&nbsp;
> Maybe you shouldn't be so rude and throw words at people if in the end your input checks might not be completely fault tolerant ...

I personally don't have a problem with taking care of what I input. If that's a problem for you, feel free to improve any input validation checks, this is Open Source. Alternatively, or if you obviously don't like how I respond to things on the internet (which in fact doesn't affect anything in grocy), please just don't use grocy. It most likely doesn't fit your needs then.

Btw: Internally at every place a unit conversion is needed, an empty factor is treated as `1`. So sorry for being a complete idiot and not taking care of anything, just producing bullshit software.

**Comment by sjaeckel** [comment]
> I'm unable to reproduce this particular problem by that.
> Private demo instance: https://test-xkdug6jgi3bfi20ez233i6.demo-prerelease.grocy.info
> Product ["Test1"](https://test-xkdug6jgi3bfi20ez233i6.demo-prerelease.grocy.info/product/27) has that empty "Factor purchase to stock quantity unit" and it's no problem there adding it to the [shopping list](https://test-xkdug6jgi3bfi20ez233i6.demo-prerelease.grocy.info/shoppinglist).

Indeed on this demo instance the error is gone.
I've just tried on https://en.demo.grocy.info/shoppinglist?list=1 and there it breaks.
I'm also using 3.3.0

> feel free to improve any input validation checks, this is Open Source

I would've looked into it, if it wouldn't be fixed already.

**Comment by berrnd** [comment]
> Indeed on this demo instance the error is gone.

Fixed by me in https://github.com/grocy/grocy/commit/00ac935367e6940bc9d81b26341b5bfd4f084105 (not yet released). Sorry for taking care.

**Comment by berrnd** [comment]
I've added #2657 which tracks to finally prevent this old mystery obviously not solvable at the origin source (since years).
