### ISSUE TITLE
Feature Request: Add toggle assignment for chores

### ISSUE THREAD

**Issue by dinki** [grocy/grocy#1901]
Howdy.  Just found Grocy and wanting to use it for chore tracking only.  I am currently using Tody and one feature I'd like to see add to Grocy is the ability to reassign tasks.  One possible way is to add a toggle button which would cycle through each eligible user for that chore.  The reason that this is most desired right now is that while setting things up I am choosing alphabetical and this is causing an overload on certain people in the household.

Perhaps this is already available as an option and I have not seen it, but if not, please do consider adding it.

**Comment by berrnd** [comment]
> Perhaps this is already available as an option

It is - [changelog v3.3.0](https://grocy.info/changelog#v3.3.0) excerpt:

> - It's now possible to manually reschedule / assign chores
>   - New entry "Reschedule next execution" in the context/more menu on the chores overview page
>   - If you have rescheduled a chore and want to continue the normal schedule/assignment instead, use the "Clear" button in the same dialog
>   - Rescheduled/reassigned chores will be highlighted with an corresponding icon next to the "Next estimated tracking date" / "Assigned to"
