### ISSUE TITLE
Bug: Grocy Hassio setup API key auth doesn't work 

### ISSUE THREAD

**Issue by iamkarlson** [grocy/grocy#1902]
Hi, 
I have Grocy set up as a hassio addon. I added an API key and tried to use postman to import some basic data. However, I can get even GET  working as it's failing with 401 errors. 

curl command: 
```

curl --location --request GET 'https://my_hassio_url.ui.nabu.casa/api/hassio_ingress/grocy_hassio_ingress/api/objects/quantity_units' --header 'Accept: application/json' --header 'GROCY-API-KEY: my_valid_api_key'
```

Neither header nor query param works for me. Cookie auth works though. Is there any special setting in Grocy I have to turn on to let API be queried via postman?

**Comment by berrnd** [comment]
This is not the repository / issue tracker of the Home Assistant Add-on or any other community contributed app / integration.

grocy's API takes an API key via the header `GROCY-API-KEY` or the query parameter `GROCY-API-KEY` - [/api](https://demo.grocy.info/api) excerpt:

> Authentication is done via API keys (header GROCY-API-KEY or same named query parameter), which you can manage [here](https://demo.grocy.info/manageapikeys).
> Additionally requests from within the frontend are also valid (via session cookie).

Any webserver / reverse-proxy / whatever inbetween can maybe interfere both.

Seems to be not so an uncommon problem for the HA integration ([ref](https://github.com/hassio-addons/addon-grocy/issues?q=is%3Aissue+%22api+key%22), but they decide to use such a fancy bot to close not fixed problems 1 month after nothing was done - very interesting way of fixing things).
