### ISSUE TITLE
Bug: Incorrect recipe costs/calories when using a substituted ingredient and when unit conversions are involved

### ISSUE THREAD

**Issue by htpcent** [grocy/grocy#1903]
First hello from my site and sorry for my bad english.

I had a problem with the calculation in the unit "grams". In my case i would like to have a main flour that show me all kind of flour in the unit "grams". The sub flour type have the unit "pack".

My Settings in the Main Flour:

Quantity unit stock: Gram
Default quantity unit purchase: Gram
QU conversions: gram-kg 0,001 and kg to gram 1.000

My Settings in the Sub Flour:

Quantity unit stock: Pack
Default quantity unit purchase: Pack
QU conversions: gram to pack 0,001 and pack to gramm 1.000

In the Stock overview it works fine. I purchase 1 Pack Sub Flour and it shows me 1 Pack with 0,99$ per Pack. And the Main Flour shows correct 1000grams in stock.

Also it works with the Main Flour in kilograms.

But in the calculation for the recipes it shows me:

Main Flour in kilograms show correctly: 400 Calories and 0.10$. --> its correct
Main Flour in grams show incorrect: 400.000 Calories and 99,00$ --> its a wrong calculation

Here is my Private Demo link: https://test-9j280nkt3idy4jmxhi0v5l.demo-prerelease.grocy.info/stockoverview

I hope you can understand my problem. I think its a calculation bug to grams. I try many options but nothing shows me correct calculations. Maybe i have a wrong Setting in a product that a overlooked?

thanks for your helps.

Dear max

**Comment by berrnd** [comment]
Taking the costs and calories from the "current effective substituted product" was a new thing of v3.3.0.

Unit conversions weren't considered for that yet, I've just added that, because it of course makes sense - your second example also works now.

That your first example already worked was just due to that it used the conversion between `Gram` and `kg` of the parent product itself, which is the same as between `Gram` and `Pack` of your second example.

**Comment by htpcent** [comment]
hy

thanks for your fast answer. the stock unit in grams now worked perfekt. but i have the next problem :). in many recipes  the unit is tablespoon, teaspoon or prize. i set the conversions to the units.

if i have no "main flour" and no "sub flour" in stock ->calculation is correct.
if i have 1000 gams "main flour" and 1 pack "sub flour" in stock -> calculation is correct.

if i have no "main flour" flour in stock, but 1 pack "sub flour" in stock -> calculation is wrong.

in my case i need the "main flour" to show me the summary of flour in stock. also the "main flour" is for the recipes ingredients, to have only one kind of flour in recipes. this "main flour" never has anything in stock.

in the privat demo you can see two recipes. one is with "Main flour" and the other ist with "sub flour". In stock is 1000grams "main flour" and 1 pack "sub flour". if you consume the 1000grams of "main flour" you will see that the calculation of the recipe with the "main flour" is wrong.

https://test-9j280nkt3idy4jmxhi0v5l.demo-prerelease.grocy.info/recipes?recipe=8

dear and thanks a lot for your work
max

**Comment by berrnd** [comment]
What you just mentioned is a duplicate of #1360 - there needs to be a direct unit conversion available to make work things correctly currently (for any place unit conversions are used, not only for recipe ingredients).

The products stock QUs are always the base, when not using a products stock QU for the recipe ingredient, at least 3 conversion would be needed - that's what's currently not possible and #1360 is about.

**Comment by htpcent** [comment]
hy

ok thanks for your time und fast answers. i understand. but i have a last question ;) .

The main flour in unit grams work fine. but in the reciped shoppinglist calculation is a bug that i dont understand. in the privat demo you can see the bug. there are two "main flour products", here the settings

First "main flour" is set by the Default quantity unit purchase:
Quantity unit stock: g
Default quantity unit purchase: Pack
Factor purchase to stock quantity unit: 1000

Second "main flour" is set by the QU conversions:
Quantity unit stock: g
Default quantity unit purchase: g
Factor purchase to stock quantity unit: 1
QU conversions: g to pack 0.001 and pack to gramm 1000


in the recipes there are two recipe with the two "main flour". i add the missing 100g flour from each recipe to the shopping list.

recipe withe the main flour and default quantity unit purchase shows me: _"Not enough in stock, 100 missing, **100000** already on shopping list -> it's wrong calculation"_

recipe withe the main flour and quantity unit purchase shows me: _"Not enough in stock, 100 missing, 100 already on shopping list -> it's correct calculation"_

https://test-9j280nkt3idy4jmxhi0v5l.demo-prerelease.grocy.info/recipes?recipe=8

thanks for your time and great work
dear
max

**Comment by htpcent** [comment]
is this fix now available?

in the demo it's incorrect. it shows still "100000". 

now also the problem at consume. if i consume "sub flour unit Pack for default qu" in unit grams. it shows me:
 " This must between 0,0001 and 1 and needs to be a valid number with max. 4 decimal places ".

i can't consume 100g flour. before your update it was possible. anything goes wrong?if it not possible to change this converting at default qu,  it was no problem. then you can roll back to the last version and i convert the pack to grams always at the QU conversions.

dear 
max
