### ISSUE TITLE
Product picture 

### ISSUE THREAD

**Issue by DevEDVColin** [grocy/grocy#1906]
I Usw the newest version of Grocy.

I have a problem. I upload a Product Picture, and it dossend show on Stock... Not even on the Product info page..

Pls help

**Comment by berrnd** [comment]
Not mentioning this the first time. 🙄

Please provide a reproducible example or at least some concrete error messages. How do you think it's possible to help for anything by "something somewhere doesn't work"? I don't know how, sorry.
