### ISSUE TITLE
Moving products between locations, i.e. freezer to fridge

### ISSUE THREAD

**Issue by hannahswain** [grocy/grocy#191]
What's the best way to handle this scenario? You go to the butcher and buy a chunk of meat that's planned for in a few weeks. It initially goes into the freezer with a long expiry date. However, when you pull it out to defrost, it moves to the fridge and the expiry date needs to change. 

You can choose the location of a product when you purchase it. However, that location and the expiration date are then uneditable.  Could the fix be as simple as making the product editable?

**Comment by berrnd** [comment]
Also already thought of this...

I thought of a list which lists all single stock entries per product, maybe when clicking the amount on the stock overview page. In this list the best before, location, etc. can be changed. This will not edit the entry directly, rather creates a new one while marking the former one as obsolete (to have the history in the stock journal).

For your example:
Maybe you could mark the product as "opened". There is an option "Default best before days after opened" per product which then changes the best before date automatically when marking it as opened.

**Comment by hannahswain** [comment]
> I thought of a list which lists all single stock entries per product, maybe when clicking the amount on the stock overview page. In this list the best before, location, etc. can be changed. This will not edit the entry directly, rather creates a new one while marking the former one as obsolete (to have the history in the stock journal).

That would be awesome!

> Maybe you could mark the product as "opened". There is an option "Default best before days after opened" per product which then changes the best before date automatically when marking it as opened.

That would work as well, and would be a good short-term fix! And to track the different expiration dates (i.e. that a pot roast is good in the fridge for 3 days and in the freezer for 30), I've added that info to the product description. If we can see that in the product info pop-up, that would make things easier to figure out - you do need a bit of thinking to make sure you've added the correct date.
https://github.com/grocy/grocy/issues/173#issuecomment-473294152

**Comment by blubbel42** [comment]
This one would be really useful, also for Products which are distributed to more than one storage. They wouldn't need too change expiration-date, (unless opened, but that ist already taken care of), but everybody would know where to search for it.
Like: Move quantity n from storage to kitchen-cupboard

I also use kind of temp storages: Some food ist stored in the caravan (for it ist used spontaneously all year round), I would love to see which items are already there, an which need to be added from other storages before departure. For this it could also be useful to exclude this storage from the shopping list:
I want to have 3 packs of noodles in the storage and 1 in the caravan, but that one is only needed when i want to use the caravan. So normally i wouldn't shop for it.
