### ISSUE TITLE
Feature Request: Purchase-View change <TAB>-Jump Order

### ISSUE THREAD

**Issue by dabenzel** [grocy/grocy#1915]
Hello,
when in Purchase View, it's really complicated to handle input in my opinion.

I scan a barcode and then it jumps into the Amount-Field. That's okay.

Then I press TAB and I enter the expire-by-date - also okay. Then I press TAB and it focuses the "not expiring"-Field (maybe we can change it, that it jumps directly into the price-field).

Also, when I enter the price and press TAB to proceed to enter the next field, it clears the Price-Field. Thats really annoying, please change this!

Maybe you can make it optional via Settings to just jump through the input fields with <TAB> or to jump like in normal html-forms (as it is now), because I think some people would be annoyed the other way around.

Here's what I mean:

![msedge_kghXwuIWyK](https://user-images.githubusercontent.com/2480235/173183446-7aa3ecb2-94b6-4636-8d94-0ec40055981b.gif)

I'm not sure, if you understand, what I mean. If not, just ask ;)

Thanks

**Comment by berrnd** [comment]
> Then I press TAB and I enter the expire-by-date - also okay. Then I press TAB and it focuses the "not expiring"-Field (maybe we can change it, that it jumps directly into the price-field).

Nothing special is done about tab handling, that's just default browser behaviour - works on any website just like that, it jumps to the *next* input. Since there is the `x` [shorthand](https://github.com/grocy/grocy#input-shorthands-for-date-fields) available to essentially "press" "Never expires", it makes maybe sense to somehow introduce special tab handling there.

&nbsp;
> Also, when I enter the price and press TAB to proceed to enter the next field, it clears the Price-Field. Thats really annoying, please change this!

Of course nowhere an input field is cleared by `TAB`, also don't know what the practical sense about that would be - not reproducible on the current demo:

https://user-images.githubusercontent.com/2161815/173184154-1464dd7a-d2e0-427f-8839-e8241faa0add.mp4

**Comment by dabenzel** [comment]
Interestingly, I can't reproduce it in the demo either, but on my system.

Using Grocy 3.3.1 on Docker (image: [linuxserver/grocy](https://hub.docker.com/r/linuxserver/grocy/) ).

If I input e.g 1,99 in the Price-Field and press tab, I get the following JS-Error:
![image](https://user-images.githubusercontent.com/2480235/173184333-c8d5059e-5f9b-4ca2-8012-ed1df23ab166.png)

```
The specified value "1,00" cannot be parsed, or is out of range.

  | (anonym) | @ | jquery.min.js?v=3.3.1:2
-- | -- | -- | --
  | each | @ | jquery.min.js?v=3.3.1:2
  | each | @ | jquery.min.js?v=3.3.1:2
  | val | @ | jquery.min.js?v=3.3.1:2
  | (anonym) | @ | numberpicker.js?v=3.3.1:109
  | dispatch | @ | jquery.min.js?v=3.3.1:2
  | v.handle | @ | jquery.min.js?v=3.3.1:2

```

**Comment by berrnd** [comment]
> Then I press TAB and I enter the expire-by-date - also okay. Then I press TAB and it focuses the "not expiring"-Field (maybe we can change it, that it jumps directly into the price-field).

Just another note on that: When you use any of the [shorthands](https://github.com/grocy/grocy#input-shorthands-for-date-fields) (just like in my screenvideo above), it already jumps to the price field.

**Comment by dabenzel** [comment]
> > Then I press TAB and I enter the expire-by-date - also okay. Then I press TAB and it focuses the "not expiring"-Field (maybe we can change it, that it jumps directly into the price-field).
> 
> Just another note on that: When you use any of the [shorthands](https://github.com/grocy/grocy#input-shorthands-for-date-fields) (just like in my screenvideo above), it already jumps to the price field.

Thanks, I'll try it. I entered it like this the last times `YYYY-MM-DD` or `2022-10-02` - but not like described in the shorthands

**Comment by berrnd** [comment]
> Interestingly, I can't reproduce it in the demo either, but on my system.
> If I input e.g 1,99 in the Price-Field and press tab, I get the following JS-Error:

In either way a reproducible example is needed, I don't know how to fix things without that (and please open a separate request then for that - one topic per request as mentioned on the issue template(s), everything else is untrackable - this here will be about improving the tab order thing).

**Comment by berrnd** [comment]
These input elements are no excluded when using `TAB`:

![grafik](https://user-images.githubusercontent.com/2161815/173184672-3a5960bc-5cfa-4491-b90a-bb3fc997830b.png)
