### ISSUE TITLE
Feature Request: Userfields multiple links

### ISSUE THREAD

**Issue by Floflobel** [grocy/grocy#1919]
Hello,

I am looking to automate the purchase of my products directly through a store. To do this I wanted to use the API to retrieve my shopping list of missing products, then retrieve a "Userfields", type "link" to allow my script to know where to fetch the product.

In case a product is not available in my store I would like it to look in a second link if this product is available. 

My request is quite simple on the paper I would like to know if it is possible to add a "Userfields" "Multiple links" that would allow to put several links and retrieve them via the API.

I think I can manage with "Text multi line".

Thanks.

**Comment by berrnd** [comment]
> I think I can manage with "Text multi line".

That. Or just multiple Userfields.
