### ISSUE TITLE
Bug: Error 12 AM/PM in calendar

### ISSUE THREAD

**Issue by blaiselcq** [grocy/grocy#1922]
The 12 PM and 12 AM seems to be inverted : see the attached screenshot.
My locale in configured to english in both the browser and in config.php.
![Screenshot from 2022-06-23 10-45-28](https://user-images.githubusercontent.com/70012135/175257679-acb2f388-a6eb-4055-b74e-d69b7128d848.png)

**Comment by berrnd** [comment]
Well, what is wrong exactly?

Definition of a day starting at midnight:

<html><body>


12-hour am-pm clock | 24-hour military time
-- | --
12:00 am | 00:00
1:00 am | 01:00
2:00 am | 02:00
3:00 am | 03:00
4:00 am | 04:00
5:00 am | 05:00
6:00 am | 06:00
7:00 am | 07:00
8:00 am | 08:00
9:00 am | 09:00
10:00 am | 10:00
11:00 am | 11:00
12:00 pm | 12:00
1:00 pm | 13:00
2:00 pm | 14:00
3:00 pm | 15:00
4:00 pm | 16:00
5:00 pm | 17:00
6:00 pm | 18:00
7:00 pm | 19:00
8:00 pm | 20:00
9:00 pm | 21:00
10:00 pm | 22:00
11:00 pm | 23:00


</body>
</html>

grocy 12 hour clock calendar day view:

![grafik](https://user-images.githubusercontent.com/2161815/175260570-506d281e-c875-4a2d-9e9e-c04c4989edc5.png)

grocy 24 hour clock calendar day view:

![grafik](https://user-images.githubusercontent.com/2161815/175260701-6e21a2e8-1ae4-45de-b1e3-b93c2426d7e9.png)

**Comment by berrnd** [comment]
The calendar component used is FullCalendar: https://github.com/fullcalendar/fullcalendar

So please report that problem there, if you really think something is wrong regarding that.

**Comment by blaiselcq** [comment]
Ok, I would have guessed 12 AM would be noon, ind 12 PM midnight, but apparently it is the other way around : [https://en.wikipedia.org/wiki/12-hour_clock#Confusion_at_noon_and_midnight](https://en.wikipedia.org/wiki/12-hour_clock#Confusion_at_noon_and_midnight).
