### ISSUE TITLE
Feature Request: Additional fields for products depending on their storage location

### ISSUE THREAD

**Issue by Steffen75** [grocy/grocy#1923]
Let's say I want to organise 3 different locations with Grocy:

- Pantry 
- Wine cellar
- Scottish single malt whisky bar

Now it would be nice if you could define additional fields for some of the storage locations of the product. Let's say for example:

Wine cellar: Country, type of wine, type of grapes, vintage, sweetness and so on.
Scottish single malt whisky bar: Region, specified age, alcohol by volume and so on.

And when you add a purchase and select the wine cellar as the location these user defined fields show up for filling them out.

And as a second step when choosing the storage location under stock overview these fields get shown automatically.

This would make Grocy a much better tool for also managing things like your wine cellar.

**Comment by berrnd** [comment]
That's called "Userfields" in grocy and everything mentioned (adding fields, showing them on /purchase, showing them on /stockoverview) is already possible by that (ref #176).

**Comment by berrnd** [comment]
Maybe also have a look at https://www.reddit.com/r/grocy/comments/u07y1p.
