### ISSUE TITLE
Feature Request: Sale Price Checkbox

### ISSUE THREAD

**Issue by tonytonyistony** [grocy/grocy#1925]
I think it would be useful to add a sale price flag for purchase prices. When looking at pricing trends it would be useful to see when sales hit and how it effects total costs.

![image](https://user-images.githubusercontent.com/53504611/176354005-78313897-1173-42d6-81cc-a94c7fd97219.png)

**Comment by berrnd** [comment]
You can add any field anywhere by using Userfields (ref. #176).

Anything related data analysis is tracked in #64.
