### ISSUE TITLE
Bug: Duplicate barcode error

### ISSUE THREAD

**Issue by tonytonyistony** [grocy/grocy#1927]
While I was messing around with the app I decided to delete an previously input item so I could change the "Quantity Unit Stock" value. After recreating the item and rescanning the barcode, I get the following error.

Error while saving, probably this item already exists
"{\"error_message\":\"SQLSTATE[23000]: Integrity constraint violation: 19 UNIQUE constraint failed: product_barcodes.barcode\"}"

**Comment by berrnd** [comment]
Barcodes need to be unique across all products, that's what the error message says.

When that's not the case, please describe exactly how to reproduce this problem (also mentioned on the issue template), then this can be reopened and fixed.

**Comment by berrnd** [comment]
>I decided to delete an previously input item so I could change the "Quantity Unit Stock" value

Side note for that: Since v3.3.0 it's possible to change a products QU stock when a corresponding unit conversions exists, so that's not needed and/or you probably use an outdated version.
