### ISSUE TITLE
Bug: Quantity unit 

### ISSUE THREAD

**Issue by bob5731** [grocy/grocy#1929]
Quantity unit  is blank on inputting Inventory the list is blank.
How do I fix it? So I can use windows to do my Inventory.

**Comment by berrnd** [comment]
Please provide steps how to reproduce a problem, then I'm happy to look into - that's also mentioned on the issue template.

"Something somewhere doesn't work" is not enough for me to fix things, sorry.

**Comment by berrnd** [comment]
And yes, the [r/grocy subrreddit](https://www.reddit.com/r/grocy) is the better place for such questions: https://www.reddit.com/r/grocy/comments/vnwcph

But why the heck then double post also here without any reproduction steps? 🙄
