### ISSUE TITLE
Feature Request: Categories for recipes

### ISSUE THREAD

**Issue by szerencl** [grocy/grocy#1930]
It would be nice to be able to assign a category to a recipe e.g.: Soup, Main Course, Side Dish, Dessert etc.
Recipes could be shown grouped and filtered by category like in the stock or shopping list views.

**Comment by berrnd** [comment]
Question-duplicate of #324 and #1126, see https://github.com/grocy/grocy/issues/324#issuecomment-513479539 and have a look at Userfields.

**Comment by szerencl** [comment]
But is it possible somehow to filter based on this user field?
Currently I can only filter based on availability.

**Comment by berrnd** [comment]
> But is it possible somehow to filter based on this user field?

Partly already possible, the generic search field above any table searches in all columns - for the rest a duplicate of #1850.
