### ISSUE TITLE
Bug: Adding an API key always adds 2 keys

### ISSUE THREAD

**Issue by MrNavaStar** [grocy/grocy#1931]
When on the manage API keys menu and you click add, it always adds 2 keys. This seems to happen on the demo site as well.

**Comment by berrnd** [comment]
> This seems to happen on the demo site as well.

No:

https://user-images.githubusercontent.com/2161815/177027463-34a4ab62-fe12-4f2a-883e-c7c8ac7b2d5f.mp4

So needs a reproducible way first, then it can be reopened and fixed.
