### ISSUE TITLE
Feature Request: Option to skip overdue chores automatically on next due date

### ISSUE THREAD

**Issue by Aasikki** [grocy/grocy#1933]
Would be useful to have an option for skipping overdue chores automatically, on the next due date, as many (most?) chores can only be done once per day anyway.

This would solve the problem, of having two or more of the same task, shown on the same day (overdue ones + thw current one), and having to manually skip them, when it's already obvious, that it was skipped without pressing the skip button.

**Comment by berrnd** [comment]
Maybe try the chore option "Due date rollover":

![grafik](https://user-images.githubusercontent.com/2161815/177041383-f4d1a257-f987-4989-8a5e-3f8c85ed0dfa.png)

Similar to that, you really want that overdue chores are ignored / automatically tracked as skipped?

**Comment by Aasikki** [comment]
> 

Would that show as having the same task multiple times on same day when it overlaps with the regular next due date? Sorry for posting if that option is exactly what I need.

I don't want _all_ overdue tasks to be automatically skipped, I want to see them as overdue, but this way when the next due date comes I have the same task duplicated. This is really only a problem for daily or frfrequent tasks though. For monthly or weekly ones you'd already be done with the task before even if you completed it a couple day's after the due date.

**Comment by berrnd** [comment]
Maybe it would be great to first clarify if it's about chores or tasks - you talk about seeing multiple next due dates (when I get it right) - a chore can only have exactly ONE next due date.

Please create a practical example on a [private demo instance](https://www.reddit.com/r/grocy/comments/jwnk9b), so much easier to talk about stuff by that.

> I don't want all overdue tasks to be automatically skipped

Any chore option of course only affects the corresponding chore, no all - since it's an option for that specific chore.

**Comment by Aasikki** [comment]
> Maybe it would be great to first clarify if it's about chores or tasks - you talk about seeing multiple next due dates (when I get it right) - a chore can only have exactly ONE next due date.
> 
> Please create a practical example on a [private demo instance](https://www.reddit.com/r/grocy/comments/jwnk9b), so much easier to talk about stuff by that.
> 
>  
> 
> > I don't want all overdue tasks to be automatically skipped
> 
> Any chore option of course only affects the corresponding chore, not all - since it's an option for that specific chore.

I'm talks about chores as I stated in the title.
I now created an example chore here:
https://test-hpi6fjdtundkotglz1zyqf.demo-prerelease.grocy.info/choresoverview

I set an example chore and set thw start day two days in the past.

If you skip or track the example chore, the due date moves forward by one day and you have to skip a couple times before you get to the present day. The tasks don't show as multiples or have multiple due dates shown at one time, sorry for being unclear about that, English isn't my first language so maybe there's a misunderstanding heh.

I also should have given the rolling due date a try before submitting, sorry for that as well.

**Comment by berrnd** [comment]
The "next estimated tracking"-date is based on the last execution date.

&nbsp;
> If you skip or track the example chore, the due date moves forward by one day and you have to skip a couple times before you get to the present day.

Tracking/skipping in [/choresoverview](https://test-hpi6fjdtundkotglz1zyqf.demo-prerelease.grocy.info/choresoverview) is done for exactly this "next estimated tracking"-date, on [/choretracking](https://test-hpi6fjdtundkotglz1zyqf.demo-prerelease.grocy.info/choretracking) you can set a date/time manually, which is essentially skipping multiple schedules of a daily chore when it was not done multiple days - so do that in such cases.

There is also an option to reschedule a chore manually (ref #1830).

If you don't care about a chore being overdue, "Due date rollover" is what you're looking for - as mentioned before.

I don't see that anything of what you wanted is not already possible.

**Comment by Aasikki** [comment]
> The "next estimated tracking"-date is based on the last execution date.
> 
>  
> 
> > If you skip or track the example chore, the due date moves forward by one day and you have to skip a couple times before you get to the present day.
> 
> Tracking/skipping on [/choresoverview](https://test-hpi6fjdtundkotglz1zyqf.demo-prerelease.grocy.info/choresoverview) is done for exactly this "next estimated tracking"-date, on [/choretracking](https://test-hpi6fjdtundkotglz1zyqf.demo-prerelease.grocy.info/choretracking) you can set a date/time manually, which is essentially skipping multiple schedules of a daily chore when it was not done multiple days - so maybe use that in such cases.
> 
> There is also an option to reschedule a chore manually (ref #1830).
> 
> If you don't care about a chore being overdue, "Due date rollover" is what you're looking for - as mentioned before.
> 
> I don't see that anything of what you wanted which is not already possible.

Totally right, should have researched better, will do that in the future before opening a request!
