### ISSUE TITLE
Feature Request: Recipe Catagories #560 

### ISSUE THREAD

**Issue by nuovo10** [grocy/grocy#1936]
hello!
Will this proposal be implemented?
thanks

New Feature Recipe Catagories #560

**Comment by berrnd** [comment]
This is the wrong place for such questions, please use the [r/grocy subreddit](https://www.reddit.com/r/grocy) for general qustions as [mentioned in README](https://github.com/grocy/grocy#questions--help--bug-reports--feature-requests).

Having categories or any field for recipes is already possible by utilizing Userfields (ref #176).

Als already asked in #324 and #1126 and #1930.
