### ISSUE TITLE
Feature Request: Set purchase date myself

### ISSUE THREAD

**Issue by wurmmehl** [grocy/grocy#1937]
Hello,

I would find it very useful if you could set the purchase date myself. 
I do not get to enter the purchases directly every day, which has shown me a few problems.
First, the expiration date is set based on the purchase date, which thus then does not always fit.
On the other hand, the price history is consumed, because I enter the item with 2 different price on the same day.

I would be very happy about the possibility to set that date myself.

Thanks in advance

**Comment by berrnd** [comment]
Duplicate-question of #1631 - setting the purchased date is of course already possible, quoting myself:

> Already possible, check the stock setting `Show purchased date on purchase and inventory page (otherwise the purchased date defaults to today)`:
> 
> https://demo.grocy.info/stocksettings#show_purchased_date_on_purchase
> 
> ![grafik](https://user-images.githubusercontent.com/2161815/135244031-3e9ad727-58e2-4b8b-ba92-a7d6a586bedd.png)

&nbsp;
>  First, the expiration date is set based on the purchase date, which thus then does not always fit.

The due date is only automatically populated based on the corresponding products `Default due days` setting, not on the purchased date.
