### ISSUE TITLE
Bug: Cannot reschedule next execution

### ISSUE THREAD

**Issue by scrambled2k3** [grocy/grocy#1938]
I am unable to reschedule the next execution.  When I click the link in the context menu of a chore from the Chores Overview page, I get the below error.

```
TypeError: choreDetails.chore.next_execution_assigned_to_user_id.isEmpty is not a function
    at choresoverview.js?v=3.3.1:310:127
    at xhr.onreadystatechange (grocy.js?v=3.3.1:17:7)
```

This is my current install info:
```
Version 3.3.1
Released on 2022-06-10 a month ago

PHP Version 8.1.7
SQLite Version 3.31.1
OS Linux 5.4.0-121-generic #137-Ubuntu SMP Wed Jun 15 13:33:07 UTC 2022 x86_64
Client Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/103.0.0.0 Safari/537.36
```

**Comment by berrnd** [comment]
Not reproducible on the demo:

https://user-images.githubusercontent.com/2161815/178095247-35fd127f-69e3-4360-b73f-b9a029387f84.mp4

However, I've fixed the theoretical problem based on the error message above in b57ba59243aa667114d6cb67ff43ff5cb175cacc.
