### ISSUE TITLE
Feature Request: Amazon Prime Pantry And Subscribe and Save Integration

### ISSUE THREAD

**Issue by ajahart** [grocy/grocy#194]
Integrate with Amazon's Prime Pantry and/or Subscribe and Save to automatically add products upon amazon order confirmation.

**Comment by winterscar** [comment]
I feel like what would be cool here is some kind of plugin system where you can export a shopping list to a plugin, and that plugin would handle ordering said list though a provided shop/service. 

This means that we're not stuck adding support for prime/wallmart/whatever, but instead users can implement their own plugins that work with a unified api.

**Comment by hllhll** [comment]
How is this not the 1st thing developed right after the shopping list itself?
Does someone now a standard interface for such function? instead that we would re-invent the wheel? Something like IGroceriesProvider; 
If grocery had such feature, I Already would start implement for a local provider:)

**Comment by hllhll** [comment]
If someone from the devs could suggest a direction for implementing this, I'll might think about implementing this.

Does anyone know other platform for managing shopping-list with such extensible Interface (which one would probably need to implement locally)?

**Comment by PhilippCh** [comment]
You could try either the Amazon API (doesn't necessarily have to be Pantry, could also be regular Amazon for e.g. scotch tape or regular household items) or some ToDo List APIs. I personally use Microsoft ToDo, which has an extensive app, but others probably use ToDoist or others as well.

**Comment by berrnd** [comment]
Merged into #905.
