### ISSUE TITLE
Bug: QU conversion does not work when the "Decimal places allowed for amounts" is 0

### ISSUE THREAD

**Issue by Gnoupi** [grocy/grocy#1943]
Because I never deal with decimal amounts (and because the grocy iOS app is not super user friendly in such case), I thought it would be best to set the "Decimal places allowed for amounts" to 0.

Unfortunately, doing so breaks the quantity unit conversion, which inputs wrong values in stock (most likely I suppose because at some point we store in the opposite unit, needing decimal places? I haven't found the place for it in the code at first glance).

This can be reproduced on the demo server:
- Set the "Decimal places allowed for amounts" to zero.
- Attempt to purchase a pack of eggs
![image](https://user-images.githubusercontent.com/1322945/178786294-f494dd46-4c42-4e13-8ead-a11f8fd6b691.png)
- Notice the amount in the popup
![image](https://user-images.githubusercontent.com/1322945/178786350-f8b99f7a-041e-4722-970f-a1751a45e069.png)
- Confirm with the stock entry
![image](https://user-images.githubusercontent.com/1322945/178786609-b439c4f6-0527-418a-9577-7368dbab8c86.png)

**Comment by Gnoupi** [comment]
I'm not sure I understand. 

If a product is stocked by his QU, then in case of eggs, it's per single egg, and you purchase by packs of 10. Where does the conversion cause a partial amount? I'd expect the purchase unit and conversion to be a simple multiplier in this direction.

Unless it would be stored by "partial amounts of purchase units", in which case it would play a role. But from what I see in DB, it doesn't seem to be the case?

**Comment by Gnoupi** [comment]
Ok, I think I found the issue, it's the regex after the toFixed(). 
When the amount of decimal is 0, toFixed() takes away the decimal point, and the regex eats away the trailing zeros from the non-decimal part.

Easy way to confirm that is to change the eggs for a dozen per pack:
![image](https://user-images.githubusercontent.com/1322945/178859573-739f3325-63a8-4ab4-a781-68a359100e46.png)
![image](https://user-images.githubusercontent.com/1322945/178859579-0143f869-5bdc-4a84-bf54-2c185c85fdee.png)

Now it's the middle of the night so I don't have a proper regex alternative to suggest that would account for that 😄 , but I suppose that worst case you can condition the regex to be applied only when the amount of decimal is > 0.

**Comment by berrnd** [comment]
> When the amount of decimal is 0, toFixed() takes away the decimal point, and the regex eats away the trailing zeros from the non-decimal part.

You're right, thanks for the pointer.
