### ISSUE TITLE
Feature Request: Allow to attach follow-up tasks to every task

### ISSUE THREAD

**Issue by CodingSpiderFox** [grocy/grocy#1945]
As a user I want to automatically add follow-up tasks to tasks so that certain steps are not forgotten.

Example: 
* wash clothes should automatically assign a follow up task "put clothes into cabinet"

**Comment by berrnd** [comment]
Guess you mean [chores](https://demo.grocy.info/choresoverview), not [tasks](https://demo.grocy.info/tasks) - then a duplicate of #339.
