### ISSUE TITLE
Feature Request: Allow to add tasks that need to be done by multiple persons as a team

### ISSUE THREAD

**Issue by CodingSpiderFox** [grocy/grocy#1946]
When creating a task, I want to have an option that allows me to assign multiple people to a task

**Comment by berrnd** [comment]
Duplicate of #1935 when you mean maybe chores also here.

When really about tasks, then merged into #1935 since it's technically about the same.

**Comment by CodingSpiderFox** [comment]
I meant both ;)

Sorry for the waiting, I'm very busy at the moment
