### ISSUE TITLE
The menu is clipping behind the table

### ISSUE THREAD

**Issue by OmgImAlexis** [grocy/grocy#195]
On pages with only a single row the menu gets clipped behind the table, the screenshot isn't cut off.

![Screen Shot 2019-03-17 at 10 43 22 am](https://user-images.githubusercontent.com/6525926/54483353-8df3a400-48a1-11e9-8d60-88c489a1d1fd.png)

**Comment by berrnd** [comment]
Any idea how to fix this?

CSS is still not so my thing, tried different things for half an hour but had no luck so far...

**Comment by OmgImAlexis** [comment]
You’d likely need to look at the z-index from what I can tell. 

If you can link me to which file handles that popup menu I should be able to get a PR sorted.

**Comment by berrnd** [comment]
For the chores overview page it's defined here: https://github.com/grocy/grocy/blob/b6e80580edce3db54322cec7ae02a26f6831cd8f/views/choresoverview.blade.php#L60-L75

Bootstrap reference: https://getbootstrap.com/docs/4.1/components/dropdowns/

**Comment by berrnd** [comment]
I found a working way... :)

https://github.com/grocy/grocy/blob/45ae386005e58ec65cd0c96e8f2283177ba7489e/public/css/grocy.css#L202-L204
