### ISSUE TITLE
Bug: Equipment - Some data (brand, model, ..) not shown on detail page, edit mode

### ISSUE THREAD

**Issue by hklages** [grocy/grocy#1953]
Hi - I use the equipment functionality with 10 additional fields for purchase/warranty date, brand, model, serial, etc. 
Browser is the newest edge on windows 11
Grocy in version 3.3.1 is served on Synology NAS, image from linuxserver.io 

When opening the overview page all data is shown (brand, model, ...) but in the edit view only the first are shown. The others such as model, brand, seiral are missing. 
Any idea how to solve that issue? 

![overview-page](https://user-images.githubusercontent.com/17273119/180449337-d3dd10c1-1a06-4335-bf21-b2105d278478.jpg)

![Details](https://user-images.githubusercontent.com/17273119/180449383-c0d988b2-66f1-4f44-aa55-dd24595933b5.jpg)

**Comment by hklages** [comment]
Inspecting the page shows 2 error: 
```
autofill.js:9631 
        
       Uncaught TypeError: Cannot read properties of undefined (reading 'encrypt')
    at 41 (autofill.js:9631:33)
    at o (autofill.js:1:265)
    at autofill.js:1:316
    at 40../captureDdgGlobals (autofill.js:9479:49)
    at o (autofill.js:1:265)
    at autofill.js:1:316
    at 9.../UI/HTMLTooltip (autofill.js:2531:25)
    at o (autofill.js:1:265)
    at autofill.js:1:316
    at 7../DeviceInterface/AndroidInterface (autofill.js:2373:29)

Uncaught TypeError: Cannot read properties of null (reading 'isEmpty')
    at userfieldsform.js?v=3.3.1:181:18
    at Function.each (jquery.min.js?v=3.3.1:2:3053)
    at userfieldsform.js?v=3.3.1:136:7
    at xhr.onreadystatechange (grocy.js?v=3.3.1:17:7)
```

**Comment by hklages** [comment]
userfields are here: 

![userfields](https://user-images.githubusercontent.com/17273119/180451941-ffc5fd11-b28d-4f1e-9cef-eff018f64b3a.jpg)

**Comment by berrnd** [comment]
> Any idea how to solve that issue?

Yes. Provide a reproducible example on [persistent demo instance](https://www.reddit.com/r/grocy/comments/jwnk9b) as mentioned on the issue template and I will fix it, just like any problem since grocy exists. Sorry, but I'm unable to look behind screenshots.

**Comment by hklages** [comment]
See example equipment l, car on your demo page.
Field location does not show garage in the edit view but in overview

**Comment by berrnd** [comment]
Any public demo instance is reseted multiple times a day and especially the default instance (stable, english) is used by a lot of people simultaneously - so it's kind of the worst place to create reproducible examples there. Mentioned the better place on the issue template and less than half an hour just here above...

However, I copied to current stable english demo instance to this **persistent** demo instance: https://test-du6vk2so2ijsrkznkfblho.demo-prerelease.grocy.info/equipment

It's reproducible there.

**Comment by hklages** [comment]
You are lightning fast. Thanks.
