### ISSUE TITLE
Feature Request: Transfer Database to an new Grocy

### ISSUE THREAD

**Issue by redpepper1979** [grocy/grocy#1954]
I want to transfer all Data from an old Grocy Installation to an new Server. My problem is how to do this

**Comment by berrnd** [comment]
You've bypassed what's mentioned on the issue template and [in README](https://github.com/grocy/grocy#questions--help--bug-reports--feature-requests):
This is not the right place for general usage questions, please use the [r/grocy subreddit](https://www.reddit.com/r/grocy).

Everything is stored in the `data` directory (the database file is `grocy.db`) in that folder. Copy/backup/transfer the whole folder and everything is save.
