### ISSUE TITLE
Feature Request: Desktop application

### ISSUE THREAD

**Issue by Deedikjupijn** [grocy/grocy#1955]
Hey, I would like an executable for windows (if possible aswell for ubuntu and other linux distro) that works a bit like the android app. You can connect to the server whitout using a web browser, this could also look a bit better and be more intuative just like the app.

**Comment by berrnd** [comment]
Have a look at grocy-desktop: https://github.com/grocy/grocy-desktop

Beside that I don't know what's bad on a web UI, works on desktop, mobile and everywhere else.

I will not create anything "that works a bit like the android app". In any case, it would be a separate project - feel free to start it.
