### ISSUE TITLE
Unable to view products

### ISSUE THREAD

**Issue by OneThatWalks** [grocy/grocy#1957]
When trying to go to the products overview it shows up as blank, but there are certainly products.

![image](https://user-images.githubusercontent.com/644628/180658118-174d5563-fe6d-4591-944c-3505e3bb3374.png)

Version info
```plaintext
Grocy Version 3.3.1

PHP Version 8.0.13
SQLite Version 3.35.5
OS Linux 5.10.17-v7l+ #1403 SMP Mon Feb 22 11:33:35 GMT 2021 armv7l
Client Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:102.0) Gecko/20100101 Firefox/102.0 
```

Browser error
```plaintext
Uncaught TypeError: e is undefined
    jQuery 15
        fb
        ia
        La
        map
        map
        map
        La
        f
        tb
        hc
        u
        each
        each
        u
        DataTable
    <anonymous> https://***REDACTED***/viewjs/products.js?v=3.3.1:1
jquery.dataTables.min.js:38:29
    jQuery 15
    <anonymous> https://***REDACTED***/viewjs/products.js?v=3.3.1:1

```

**Comment by berrnd** [comment]
The issue template mentions to provide a reproducible example on a [persistent demo instance](https://www.reddit.com/r/grocy/comments/jwnk9b). Do that I'm happy to look into it.

**Comment by OneThatWalks** [comment]
This was my fault, and if anyone ever finds this as a result of some google search.  I just had to follow the update guidance in the README, importantly the deletion of the viewcache.
