### ISSUE TITLE
Bug: Documentation confusing

### ISSUE THREAD

**Issue by RickSanchezC136** [grocy/grocy#1958]
Using Grocy app for android..  created API key and scanned QR code. Next screen says: 

"You're using the grocy Home Assistant add-on.  Create a long-lived access token in your Home Assistant profile settings (last section).  Below the token field, click on Generate QR code and scan it here.

"in your home assistant profile settings (last section)" <-- sorry but this makes no sense. There aren't any steps explaining where to go, I can't find anything matching a description that makes sense to this wording.   The documentation and app basically say the same thing but provide no instruction how to actually do this or where to find this.

**Comment by berrnd** [comment]
This is not the repository / issue tracker of the Home Assistant Add-on or any other community contributed app / integration.
