### ISSUE TITLE
Bug: getting 500 Internal Server Error after installation

### ISSUE THREAD

**Issue by cwerner1** [grocy/grocy#1964]
1. Installed grocy  v3.3.1 on an uberspace.de account
2. Setup an subdomain      sub.domain.com
3. the subdomain was symlinked to the grocy-public folder
4. Recieving an 500 error when opening https://sub.domain.com

I had to edit the 
.htaccess to get it working on the subdomain
`RewriteBase /` was missing

`RewriteEngine On
RewriteBase /

 
RewriteCond %{REQUEST_FILENAME} !-f
RewriteCond %{REQUEST_FILENAME} !-d
RewriteRule ^ index.php [QSA,L]
`

**Comment by berrnd** [comment]
The is the tracker for reproducible bugs and feature requests, not the place for general help/support requests ([README ref](https://github.com/grocy/grocy#questions--help--bug-reports--feature-requests)).

"500 error" is an internal server error, your webserver logs most likely conains more hints about the actual problem - I would start checking there. At least it's impossible to help by the information provided above.
