### ISSUE TITLE
Feature Request: 

### ISSUE THREAD

**Issue by xiaoyuesansui** [grocy/grocy#1966]
hey Gents and developer 

appreciate for the brilliant working at first 

may I know if I can add products bss total amount rather than unit price 

for example ,it is easy to add stock when I spend 10 bucks bought 10 apples but can drive me crazy when I buy 5 bottoms of milk at 12.47 bucks 

pls advise how can I deal with later case without a calculator around me ?

thanks

**Comment by berrnd** [comment]
This here is the tracker for reproducible bugs and feature request, not the place for general help requests ([README ref](https://github.com/grocy/grocy#questions--help--bug-reports--feature-requests)).

On [/purchase](https://demo.grocy.info/purchase) the single price or the total price can be entered, not need to use a calculator.

![grafik](https://user-images.githubusercontent.com/2161815/184478721-8b9c7f31-3488-4672-9f4f-2cebe8964baf.png)
