### ISSUE TITLE
New userfields for already existing stock entries can't be updated

### ISSUE THREAD

**Issue by Andrei-Paul** [grocy/grocy#1969]
Steps to reproduce:

1. Purchase 1 "Cheese"
2. Create user field "Brand" for "Stock" entity
3. Go to "Stock entries" and edit "Cheese"
4. Set "Brand" to "Stinky" and click "OK"

Expectations:
"Brand" is now set to "Stinky".

Reality:
"Brand" is empty.

Workaround:
Use "Inventory", set to amount to 0.99 (would be nice to be able to set to 1 😅) and set "Brand" to "Stinky". Then edit the stock entry to set amount back to 1, correcting price if necessary.

Tested in latest instance.

**Comment by berrnd** [comment]
> Tested in latest instance.

Please use the [pre-release demo](https://demo-prerelease.grocy.info) for verifying things as mentioned on the issue template and provide a [private demo instance](https://www.reddit.com/r/grocy/comments/jwnk9b) for the problem, as also mentioned there.

Took the time and did that for you: https://test-1xk8sgprvis4u3ng2v7p54.demo-prerelease.grocy.info

Can't reproduce it:

https://user-images.githubusercontent.com/2161815/185443496-6b329c0c-1ac7-47b0-892a-9dddbf3ac4c5.mp4

Maybe releated to #1953, already fixed, not yet released.

**Comment by Andrei-Paul** [comment]
Reproduced here:
https://test-omkxx5heq3kekwd7shdc7s.demo-prerelease.grocy.info/stockentries

https://user-images.githubusercontent.com/5116046/185458282-f682552f-3146-4c79-84ff-723313357ce3.mp4
