### ISSUE TITLE
Feature Request: Quantity conversion factors for barcodes

### ISSUE THREAD

**Issue by kleinerChemiker** [grocy/grocy#1970]
It would be great if we could define quantity conversion factors on barcode level. Some products come in different package sizes. I buy them per package, but I would like to track e.g. how many servings I have. So I have one product, with several different barcodes and each barcode is one package but a different amount of servings.

**Comment by berrnd** [comment]
> So I have one product, with several different barcodes and each barcode is one package but a different amount of servings.

The amount field of each barcode is exactly made for that:

![grafik](https://user-images.githubusercontent.com/2161815/185635984-3ad0a4e6-5d10-4559-a071-6929601b08fe.png)


Possible since v3.0.0, [changelog](https://grocy.info/changelog#v3.0.0) excerpt:

> ### New feature: Prefill purchase data by barcodes
> - Imagine you buy for example eggs in different pack sizes and they have different barcodes
> - Each product barcode can be assigned an amount, quantity unit and store (on the product edit page), which is then automatically prefilled on the purchase page
> - Additionally, the last price per barcode will be tracked and prefilled as a "Total price" on purchase

**Comment by KD0BPV** [comment]
I don't think this is quite what @kleinerChemiker was looking for, nor is it what I am looking for. I adding "Factor purchase to stock quantity unit" to Barcode, and changing it in Product to be "Default Factor purchase to stock quantity unit".

Different barcodes might have different conversion factors. For example, I have Product A that I stock in Pieces, but buy in Packs, and has 3 barcodes. Barcode 1 is from Store A, and comes as 1 Pack containing 10 Pieces; Barcode 2 is a "value pack" from Store B, and comes as 1 Pack of 15 Pieces; Barcode 3 is a "bulk buy" from Store C that comes as 2 Packs, each containing 10 Pieces. 

I want to be able to set something like:
Barcode 1: Amount = 1, Quantity unit = Pack, Conversion factor = 10, Store = Store A
Barcode 2: Amount = 1, Quantity unit = Pack, Conversion factor = 15, Store = Store B
Barcode 3: Amount = 2, Quantity unit = Pack, Conversion factor = 10, Store = Store C
Then, on the Purchase page, when a barcode is entered, the "Amount" field should be how many of the particular barcode I'm buying, and the "Quantity unit" field can be hidden, or disabled, or set to "Barcode", or some other sensible handling. 

Now, let's say I'm at Store C, and I decide to get 2 of Barcode 3 at $5.99 each. On the purchase page, I can just enter: Product = Barcode 3, Amount =  2, Price = 5.99, Barcode price, Store = Store C. Once I submit this, the server can take all this information and calculate how many Pieces (40) to add to stock, the price per Piece ($0.30 [Rounded to nearest cent]), etc. 

Then let's say a couple months pass and I'm at Store B and decide to pick up 1 of Barcode 2 for $4.83. I enter: Product = Barcode 2, Amount = 1, Price = 4.83, Barcode price, Store = Store B. Again, with all this information, the server can calculate everything it needs, and I don't need to do any manual or mental math like we do currently.

What happens with Barcode 1 is pretty straight forward from here, I think. As for if no barcode is scanned/entered, and only Product A is selected, then Amount and Quantity unit can behave as current, and if the defined "Default purchase quantity unit" is selected, a new field can be shown/enabled and pre-populated with the value from "Default factor purchase to stock quantity unit".  This way, we retain the ability to handle unusual or custom purchase amounts, or things that are priced by weight, such as produce, where barcodes don't work well.

**Comment by berrnd** [comment]
I don't know why talking about a "conversion factor for barcodes", there is none, and there is no need for one. A conversion factor is to convert between different quantity units, not between different barcodes. A barcode is related to an amount `x` of QU `y` and that's what you can define per barcode.

&nbsp;
> Different barcodes might have different conversion factors. For example, I have Product A that I stock in Pieces, but buy in Packs, and has 3 barcodes. Barcode 1 is from Store A, and comes as 1 Pack containing 10 Pieces; Barcode 2 is a "value pack" from Store B, and comes as 1 Pack of 15 Pieces; Barcode 3 is a "bulk buy" from Store C that comes as 2 Packs, each containing 10 Pieces.

You store it in Pieces, there are Packs with different sizes - so a proper conversion between Pack and Pieces can't be directly established. A workaround would be to create QUs like "10 Pack" and "15 Pack", some users do that (more than a lot examples are around here and on the [r/grocy subreddit](https://www.reddit.com/r/grocy)). Or just simply create the practically related barcodes for the product:
- Barcode 1 Store A 10 Pieces
- Barcode 2 Store B 15 Pieces
- Barcode 3 Store C 20 Pieces

Reality check / practical example: https://test-heyjxztdxsrbyuw6nlp0v.demo.grocy.info

https://user-images.githubusercontent.com/2161815/185779340-008d958b-295c-447d-b9a2-e2db3b631834.mp4

&nbsp;
> Now, let's say I'm at Store C, and I decide to get 2 of Barcode 3 at $5.99 each. On the purchase page, I can just enter: Product = Barcode 3, Amount = 2, Price = 5.99, Barcode price, Store = Store C. Once I submit this, the server can take all this information and calculate how many Pieces (40) to add to stock, the price per Piece ($0.30 [Rounded to nearest cent]), etc.

When buying "multiple barcodes" and when scanning them, you would simply scan it two times - that's what the cashier in the store most of the time also does. About being able to properly enter different Pack size prices: That would fit better with the QUs like "10 Pack" and "15 Pack" as mentioned above. Or having parent/child products with the related QU conversion - also that's what commonly most grocy users do. And just again: You decided to track the product per Piece, there needs to be a QU conversion relationship to that QU, barcodes are not QUs.

Let's do another reality check, specific "Pack QUs" example: https://test-sruiexaxy6kf4wz7rwc4.demo.grocy.info

https://user-images.githubusercontent.com/2161815/185780609-632abd0f-2165-463c-8945-ef293c52ebbc.mp4

And another one, parent/child product example: https://test-hbsc8o8zty5gy7vx8z8q9.demo.grocy.info

https://user-images.githubusercontent.com/2161815/185780326-45dd7077-24d8-40c7-a6fb-d50742841add.mp4

I personally prefer that approach for those examples.

&nbsp;

Then let's say a couple months pass and I'm at Store B and decide to pick up 1 of Barcode 2 for $4.83. I enter: Product = Barcode 2, Amount = 1, Price = 4.83, Barcode price, Store = Store B. Again, with all this information, the server can calculate everything it needs, and I don't need to do any manual or mental math like we do currently.

By using one of the approaches of the last two examples above, there is no need to use a calculator manually.
