### ISSUE TITLE
Bug: When changing the stock QU, the item amount at the barcode is changed wrong.

### ISSUE THREAD

**Issue by kleinerChemiker** [grocy/grocy#1976]
I changed the stock QU and the item amount at the bar code was changed too. But the barcode QU and the stock QU were different. It seems that when the bar code amount is changed, the barcode QU is considered to be the same as the stock QU, i.e. the same factor is applied.

**Comment by berrnd** [comment]
Please provide a reproducible example on persistent pre-release demo instance as mentioned on the issue template.

When changing the products stock QU, all amount values in the entire database are changed by the very same conversion factor ([code ref](https://github.com/grocy/grocy/blob/58c6b72d772bd6b14137de6e32d48bd92868402b/migrations/0197.sql#L23-L54)).

**Comment by berrnd** [comment]
> When changing the products stock QU, all amount values in the entire database are changed using the very same conversion factor ([code ref](https://github.com/grocy/grocy/blob/58c6b72d772bd6b14137de6e32d48bd92868402b/migrations/0197.sql#L23-L54)).

While that's correct, you're right that barcode amounts don't need to be changed when the products stock QU is changed. Will be fixed.
