### ISSUE TITLE
Feature Request: When editing a unit conversion, also change the "QU from" and "QU to" of the corresponding reverse conversion

### ISSUE THREAD

**Issue by kleinerChemiker** [grocy/grocy#1977]
When creating a conversion from A to B, the conversion B to A is automatically created. If I change the conversion unit from A->B to e.g. C->B, then B->A is not altered. If the conversion factor is changed, then the change alters A->B and B->A.

**Comment by berrnd** [comment]
Not a bug.

The inverse _factor_ of the corresponding other conversion is automatically changed, nothing else. When you change the "QU from" or "QU to", they no longer build up a pair.

**Comment by kleinerChemiker** [comment]
But it doesn't make much sense to break up the pair instead of changing the QU in the corresponding conversion too.

**Comment by berrnd** [comment]
You reported this as a bug, which it is definitely not. Everything is possible to be improved. I'll convert this into a Feature Request.
