### ISSUE TITLE
Differences in highlighting for expiring/expired items in header vs table

### ISSUE THREAD

**Issue by navirom** [grocy/grocy#198]
The stock overview appears to use different rules for color highlighting exipiring/expired items in the header vs the table. The button in the header is for items expiring within five days, but rows in the table are highlighted out to longer than that.

![image](https://user-images.githubusercontent.com/16004771/54575079-06488b00-49b0-11e9-89be-264cd40c69dc.png)

![image](https://user-images.githubusercontent.com/16004771/54575114-18c2c480-49b0-11e9-976a-038a53e3beab.png)

**Comment by berrnd** [comment]
Maybe a regression bug, we already had that in #87...
