### ISSUE TITLE
Bug: Recipe with parent/child will not consume multiple Desired Servings

### ISSUE THREAD

**Issue by sniporbob** [grocy/grocy#1981]
This bug makes it impossible to consume multiple servings of a recipe.

Test environment: https://test-1onvlp7yay26m3q7ibwuf3.demo-prerelease.grocy.info/recipes?recipe=7
Offending recipe: Hot Dog - Meal
Offending ingredient: Yellow Mustard

Setup:
A parent ingredient with no stock named Yellow Mustard was created. It is configured to use units of Ounce. A child ingredient was created named Yellow Mustard - Signature Select Large 20oz. It is configured to use units of Bottle. A QU conversion was added to the child with 1 bottle = 20 ounce.

0.875 bottle of Yellow Mustard - Signature Select Large 20oz was added via the inventory menu. The hot dog and hot dog buns were configured according to #1979.

Yellow Mustard (the parent ingredient) was added to the Hot Dog - Meal recipe.

Result: the recipe reports that all ingredients are present. It is possible to successfully consume 1 serving of Hot Dog - Meal. This is good. Setting the number of desired servings to 4 will update all of the ingredient requirement totals appropriately, and they all report in stock as they should, however attempting to consume the 4 servings will generate an error that "some ingredients are missing and nothing was consumed". It actually **will** consume the hot dogs and hot dog buns but not the mustard. If other items are added to Condiment, they will not be consumed either. This creates a partial consumption condition and necessitates going to the Journal and reversing the consumption entries. I can set up an additional Condiment if desired, in case you are worried about this bug occurring elsewhere, but I think resolving the main source of error here will eliminate the partial consumption.

If the number of servings is set to 1, the consume button can be clicked 4 times to consume a total of 4 Hot Dog - Meal. The error only occurs when servings are >1.

**Comment by sniporbob** [comment]
I see the description of the fix mentions correcting the partial consuming of partially fulfilled recipes. In the provided test environment, this recipe is fully fulfilled for 4 servings but was incorrectly reporting that it could not be fulfilled upon clicking the consume button. Can you confirm that this behavior was also fixed?

**Comment by berrnd** [comment]
> Can you confirm that this behavior was also fixed?

Since all demo instances are public, everyone can verify things. And no, what you mentioned is (still) not correct there.

But another topic, hence another ticket to track that: => #1982
