### ISSUE TITLE
Bug: Redirected to login page after succesful login in iframe

### ISSUE THREAD

**Issue by szerencl** [grocy/grocy#1992]
**My Setup:**
I have Grocy reverse proxied with nginx and I'm embedding the HTTPS page in a Home Assistant webpage block.
This worked until now as I had Home Assistant use SSL from it's configuration, but because of some other issues I decided to also use nginx for Home Assistant. I wan't to use the HTTP version of HA when I'm at home and the HTTPS when I'm not home.

**The Issue:**
Now when I'm serving HA from the HTTP domain and log in to Grocy in the iframe in HA I get redirected to the login page again. I tried in chrome and samsung internet and it's the same, however for some strange reason it works with firefox.
When serving HA from HTTPS it works in all browsers.
I'm guessing it's some security issue with the cookies.

**What I tried:**
I had a similar issue with grafana but there adding cookie_secure = true to the config solved the issue. So I tried the same for grocy by adding the following directives in different combinations to php-local.ini:
```
session.cookie_secure = 1/0
session.cookie_samesite = None/Lax/Strict
session.cookie_secure = 1/0
session.cookie_domain = https://<mynginxdomain>:<port>
```
but the issue remains.
I found similar issues: #12, [Login successful but loop back to login (reddit)](https://www.reddit.com/r/grocy/comments/nyno1n/login_successful_but_loop_back_to_login/ ), but there was no solution for it.

**Versions:**
Grocy: 3.3.0 (docker)
HA: 2022.8.0 (docker)
nginx: 1.14.2

**Comment by berrnd** [comment]
grocy doesn't know and therefore does anything special if it's served via HTTP or HTTPS or in an iframe or not.

I can only gues that something about the [`BASE_URL` setting](https://github.com/grocy/grocy/blob/ff056f8d81fbd1e696abf46599e965bffe04ad48/config-dist.php#L58) is wrong. If I remember correctly from other posts, the HA integration does something special about that setting or at least handles it somehow differently due to whatever. Can't say more, have never used HA. But that's definitely not a problem to be tracked here.

**Comment by szerencl** [comment]
I still think it's a cookie issue, because it's working with Firefox. If it was a base url issue wouldn't it be wrong with all browsers?
Anyway I tried adding that code snippet to default.blade.php and restarting Grocy, but the issue persists.
Does Grocy perhaps keep logs of logins somewhere?

**Comment by berrnd** [comment]
>  Does Grocy perhaps keep logs of logins somewhere?

No.

> If it was a base url issue wouldn't it be wrong with all browsers?

When it's not the same behavior in all browsers, obviously not all browsers do things in the same manner.

&nbsp;
I personally prefer things to be simple. grocy in a Docker image run by HA, in an iframe, served via HTTPS and HTTP ... more complexity IMHO pretty naturally arise more problems to solve.
