### ISSUE TITLE
Cannot change admin password or add users behind haproxy

### ISSUE THREAD

**Issue by hexadecagram** [grocy/grocy#1993]
Both are Docker containers (linuxserver for grocy, and the official haproxy image). When I try to do either of these things, I get no confirmation and the change is not recorded.

/config/data is 777 and grocy.db is 666.

I have tried to serve the grocy application from a BASE_PATH of / (or more precisely ''). When I do so, I uncomment the commented-out portion of `backend grocy`. I cannot even get the URLs to map correctly so I must use the commented-out version and keep BASE_PATH set to /grocy.

My relevent haproxy configuration is here:

```
defaults
    log global
    mode http
    option redispatch
    option dontlognull
    option forwardfor except 127.0.0.0/8
    option httplog
    timeout check 5s
    timeout client 30s
    timeout connect 5s
    timeout server 30s

frontend https-termination
    bind *:443 ssl crt apps/haproxy.pem ca-file letsencrypt.pem
    http-request redirect prefix https://%[hdr(Host),regsub(^www\.,,i)] code 301 if { hdr_beg(Host) -i www. }
    http-request del-header X-Forwarded -m beg
    http-request del-header Forwarded -m beg
    http-request set-header X-Forwarded-Port %[dst_port]
    http-request set-header X-Forwarded-Proto https
    http-request set-header X-Real-IP %[src]
    acl is_grocy                   path_beg         /grocy
    use_backend grocy             if is_grocy             is_localnet

backend grocy
    option httpchk OPTIONS /grocy/
    http-check send hdr Host localhost
    http-request redirect prefix / drop-query append-slash if { path /grocy }
    # http-request replace-path /grocy/(.*) /\1
    # http-response replace-header Location ^(https?://[^/]+)?(/.*)$ \1/grocy\2
    # http-response replace-header Set-Cookie ^(.*[Dd]omain)=([^;]+)(.*)$ \1=example.com\3
    # http-response replace-header Set-Cookie ^(.*[Pp]ath)=([^;]+)(.*)$ \1=/grocy\3
     server grocy grocy_internal:80 check resolvers default
```

The only thing I've changed in grocy's config.php is here:

```
Setting('BASE_PATH', '/grocy');
Setting('BASE_URL', 'https://example.com/grocy');
```

**Comment by berrnd** [comment]
Changing a users password or adding a user is just a regular API call, like most of everything else. So if that doesn't work, nothing will work.

However, most likely a configuration problem, hence not something to track as a bug here (this is not repository if any of the community contributed Docker images).
