### ISSUE TITLE
Feature Request: Add a Add to Shopping List button to stock overview

### ISSUE THREAD

**Issue by jimmymasaru** [grocy/grocy#1997]
- It gives users a convenient functionality to add an item to the shopping list
- Currently I have to click on the menu and choose Add to Shopping List and complete the form, or I can go to the shopping list and find the item from the dropdown list.

Acceptance Criteria
- A button shows on the right side of "Mark this item as open"
- The button shows a shopping list icon
- When clicking, 1 amount of "Default quantity unit purchase" is added to the first shopping list

I understand the first shopping list might not be what the user prefers, so probably there could be an extra select in Shopping list settings that's similar to `shopping_list_auto_add_below_min_stock_amount_list_id`. And the button can add the item into this shopping list.

**Comment by jimmymasaru** [comment]
If you think this is useful I can work on that.

**Comment by berrnd** [comment]
We had something like that some time before. The conclusion was, less buttons, less clutter - all not often needed ones are in the "more menu".

Of course this depends also on personal preferences, use [custom JS](https://github.com/grocy/grocy#adding-your-own-css-or-js-without-to-have-to-modify-the-application-itself) to customize everything to the very end.

Manually adding things to the shoppping list should not be needed often, when having properly defined minimum stock amounts and when using recipes. At least that's what grocy is designed for.
