### ISSUE TITLE
Feature Request: Grocy assistant

### ISSUE THREAD

**Issue by jgherruzo** [grocy/grocy#1998]
Hi!

I'm not sure if this is the correct thread. I would like to make you know i recently develop a grocy assistant that help you to manage grocy througth telegram bot. 

Feel free to share this as an grocy setup example or remove if this is a wrong place to communicate it.

If it is of interest, here all info:

https://github.com/jgherruzo/JGH_GrocyAssistant

**Comment by berrnd** [comment]
Thanks, but no, it's not the right place - this here is for tracking Feature Requests and reproducible Bugs ([README ref](https://github.com/grocy/grocy#questions--help--bug-reports--feature-requests)).

Share it on the [r/grocy subreddit](https://www.reddit.com/r/grocy), add it to [grocy.info/addons](https://grocy.info/addons) (if it's ready to be used by the average grocy user). The website has its own repo: https://github.com/grocy/grocy-website
