### ISSUE TITLE
Bug: API for recipe ingredients is using Quantity unit stock for amount instead of selected quantity unit

### ISSUE THREAD

**Issue by DarkShortie** [grocy/grocy#2000]
I'm trying to export my recipes using the API. For getting the ingredients and amount I'm using an API call like this: /api/objects/recipes_pos?query[]=recipe_id=5

One ingredient is using Bottle for purchase unit, ml for stock unit and table spoon in the recipe. For this ingredient I've conversion from bottle to ml (1 bottle = 700ml) and from ml to table spoon (1 table spoon = 15ml) in place.

In the web ui everything is fine and the ingredient is displayed with 4 table spoon.

In the API the correct quantity unit is referenced (table spoon), but it delivers the quantity of the stock unit (60 in this case, since 4 table spoon equals 60ml). This will resolve in 60 table spoon instead of 4 table spoon.

I've replicated this in the demo instance with Milk and Choclate Sauce: https://test-t67k5bdj4zjta9yvdeq2bi.demo-prerelease.grocy.info

https://test-t67k5bdj4zjta9yvdeq2bi.demo-prerelease.grocy.info/recipe/5
This shows 4 table spoon like expected

https://test-t67k5bdj4zjta9yvdeq2bi.demo-prerelease.grocy.info/api/objects/recipes_pos?query[]=recipe_id=5
This gives 60 as amount and 13 for qu_id. While 13 is the correct quantity id (https://test-t67k5bdj4zjta9yvdeq2bi.demo-prerelease.grocy.info/api/objects/quantity_units) it should deliver an amount of 4 instead of 60 like the web ui does.

**Comment by berrnd** [comment]
Any amount (and price) on any API endpoint is always related to the products QU stock (since ever).

**Comment by DarkShortie** [comment]
Where can I find this information on the API? The recipe ingredients gives me the selected unit for this recipe, like it's also displayed in the web ui, but the amount of the stock unit.
If I have the selected unit, stock unit and amount of stock unit available I would be able to do the conversions.

**Comment by berrnd** [comment]
> Where can I find this information on the API?

Just like kind of everything, via the very same [`GET /objects/{entity}` endpoint](https://demo.grocy.info/api#/Generic%20entity%20interactions/get_objects__entity_).

See also there for another example: https://github.com/grocy/grocy/issues/1877#issuecomment-1114283883
