### ISSUE TITLE
Feature Request: Add recipe to meal plan from recipe list

### ISSUE THREAD

**Issue by undergroundoyo** [grocy/grocy#2003]
Hello,
I searched but I can't find an answer to my questions in the issues and yet I think that someone must have asked the question. Is it possible to save a recipe in the meal plan of the week from the recipe page. Indeed my recipe list is starting to be long...I think it would be interesting to be able to choose a recipe using filters or other attributes that we would have created in the recipe section and then send it to the meal plan.

Thanks

**Comment by berrnd** [comment]
There is now an option in the context/more menu on the recipes page to do that:

![grafik](https://user-images.githubusercontent.com/2161815/209553744-ff051e71-d80d-4873-b068-920bd2e2595d.png)
