### ISSUE TITLE
Bug: recipe ingredient

### ISSUE THREAD

**Issue by undergroundoyo** [grocy/grocy#2004]
Good morning,

I registered in the product database a product specifying that a coresspond unit has 200g. In my recipe when I indicate 80g of product and I save it only displays 8g.

Thanks

**Comment by berrnd** [comment]
Please provide a reproducible example on a [persistent/private demo instance](https://www.reddit.com/r/grocy/comments/jwnk9b) as mentioned on the issue template.

It's impossible to solve anything by guessing each and every detail of the specific scenario.

**Comment by undergroundoyo** [comment]
I just did the exact same thing in the demo and it works. Below are screenshots of my bug....

***@***.***
***@***.***

***@***.***

***@***.***

***@***.***














Envoyé à partir de Courrier<https://go.microsoft.com/fwlink/?LinkId=550986> pour Windows

De : Bernd ***@***.***>
Envoyé le :samedi 24 septembre 2022 22:55
À : ***@***.***>
Cc : ***@***.***>; ***@***.***>
Objet :Re: [grocy/grocy] Bug: recipe ingredient (Issue #2004)


Please provide a reproducible example on a persistent/private demo instance<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fwww.reddit.com%2Fr%2Fgrocy%2Fcomments%2Fjwnk9b&data=05%7C01%7C%7Ca0e23025a9c04a90330308da9e6f21e1%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637996497383293142%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=WBqY5XIlQiSRdkoVnkVG%2FvlYou9EWpVP5rJdXWPfQ7Q%3D&reserved=0> as mentioned on the issue template.

It's impossible to solve anything by guessing each and every detail of the specific scenario.

**Comment by berrnd** [comment]
I don't see any screenshots in your message above, but when it works on the demo, it's not a bug - the better place for general usage/help questions is the [r/grocy subreddit](https://www.reddit.com/r/grocy) as [mentioned in README](https://github.com/grocy/grocy#questions--help--bug-reports--feature-requests).
