### ISSUE TITLE
Bug: should forbid delete already refered quantity unit? or at least give a warning?

### ISSUE THREAD

**Issue by flintt** [grocy/grocy#2010]
after delete unit "pack", as shown below, every item has used "pack" became uneditable (this apply to purchase, consume, transfer and inventory).

![image](https://user-images.githubusercontent.com/3394691/192428092-6c56fcf5-f7cd-449e-a781-e5342812c900.png)

https://test-ow6mhsd3v4d3snofpa0rf9.demo-prerelease.grocy.info

**Comment by berrnd** [comment]
Duplicate-question of #1770, see https://github.com/grocy/grocy/issues/1770#issuecomment-1027869454.
