### ISSUE TITLE
Feature Request (API): Prevent adding an ingredient with a unit for which no conversion path exists

### ISSUE THREAD

**Issue by Lykos153** [grocy/grocy#2013]
Steps to reproduce:
* Create a product (eg. "lentils") and set storage unit to eg. "pack"
* Add 1 pack of lentils to the stock
* Create a recipe (eg. "lentil soup")
* Add lentils as ingredient and set the amount to eg. "100 grams". <== This is forbidden in the web UI, but not in the API and neither in the Android app
* Save the recipe
* => The recipe overview now shows `100 Grams lentils x Not enough in stock, 99 missing, 0 already on shopping list ` which suggests that the required amount is somehow tied to the storage unit
* Add a unit conversion from pack to grams (eg. 1 pack = 500 grams)
* => The recipe overview now shows `50,000 Grams lentils x Not enough in stock, 99 missing, 0 already on shopping list`

I reproduced this in a test instance using the API browser: https://test-kjh5swlhcwcf0tzqhqosb6.demo.grocy.info/recipes?recipe=7

I'm not entirely sure where how this can happen. It appears to me that grocy somehow didn't store "100 grams of lentils" but "100 packs of lentils" but still remembered to show it in grams, but I don't know why it should do that.

I know your stance on GIGO and of course this wouldn't have happened if the conversion had existed prior to creating the recipe. However, I provided grocy with all the information it needs, just not in the order it wants, so I wouldn't consider the input garbage here.

Thus, these two fixes come to my mind:
* Fix the underlying issue (if my hypothesis is correct: store the required amount in the unit that was given)
* Forbid adding an ingredient with a unit for which no conversion path exists in the API
* (Of course the 3rd way would be to just tell the Android devs to forbid this in their UI, too. Making them aware of the issue is probably a good idea anyway, but in the end, the API should be decisive and not the UI. (Because what if someone now wants to write a new client app for grocy who doesn't know this issue...))

**Comment by berrnd** [comment]
> I'm not entirely sure where how this can happen. It appears to me that grocy somehow didn't store "100 grams of lentils" but "100 packs of lentils" but still remembered to show it in grams, but I don't know why it should do that.

Throughout the whole database, all amounts and prices are stored releated to the products stock QU. The selected QU at the desired place (here: recipe ingredient) is just used to display the amount; conversion happens only for displaying.

&nbsp;
> store the required amount in the unit that was given

This makes absolutely no sense, think of changing QU conversion factors...

&nbsp;
> this wouldn't have happened if the conversion had existed prior to creating the recipe

That's not true, the order doesn't matter. You can delete and create the corresponding conversion at any time (also reproducible on your example demo instance). Deleting it is just the same bullshit, not prevented, but, as you said, GIGO.

&nbsp;
If it makes you happy, let's add to prevent that saving a recipe ingredient with an invalid "display QU" is not possible (via the API; the web frontend also uses the API for everything). But that's an enhancement, not a bug.

**Comment by Lykos153** [comment]
> That's not true, the order doesn't matter. You can delete and create the corresponding conversion at any time (also reproducible on your example demo instance). Deleting it is just the same bullshit, not prevented, but, as you said, GIGO.

In the linked test instance, I just 
* Created a product ("beans") and set storage unit to "pack"
* Added 1 pack of beans to the stock
* Added a unit conversion from pack to grams (1 pack = 500 grams)
* Created a recipe ("bean soup")
* Added beans as ingredient and set the amount to eg. "100 grams".
* Saved the recipe
=> The recipe correctly shows "100 grams of beans".

Those are the exact same steps as before, just that I added the unit conversion _before_ adding the ingredient. So the order does matter. (I think I know now that this happens because there is an implicit "1 pack = 1 gram" conversion before an actual rule is added. But this is not something everybody would expect when interacting with grocy)

> This makes absolutely no sense, think of changing QU conversion factors...
Actually that's the reason why it makes perfect sense. The recipe will forever need 100 grams of lentils. It doesn't care in the slightest in which unit I store my lentils and neither does it care about how big my packs are. It's extremely surprising that changing the pack size will silently corrupt my recipes. Grocy is violating POLA here.

To illustrate what I mean:
* I have set up everything (product, conversion, recipe and ingredients as in the beans example above) and all is good
* After some months I start to buy my beans somewhere else where they sell 300 gram packs
* I change the unit conversion to 1 pack = 300 grams
* A few weeks later I cook the recipe and realize that it tastes really weird because the ratios are messed up

I can't think of any circumstance in which I would _want_ my recipe to change when I change unit conversions. IMO recipes should store the required amount in the unit that was given. This way, they maintain their integrity no matter how other data changes. The only thing that should "break" if there is no valid conversion is the UI. However, even this could be mitigated by a message like "100 Grams lentils x Can't calculate if in stock: Missing unit conversion`.

**Comment by berrnd** [comment]
> I can't think of any circumstance in which I would want my recipe to change when I change unit conversions.

Ask all the people who fucked up their unit conversions at first, then corrected them, then reported here that the recipe ingredient amounts are still wrong.

&nbsp;
> IMO recipes should store the required amount in the unit that was given. This way, they maintain their integrity no matter how other data changes.

If you break the corresponding unit conversion, the amount is always useless, no matter related to which unit it was stored. When two units are needed, a conversion is needed. The only way to maintain integrity for every sinlge possible user input bullshit error would be to store the current state of all related unit conversions per ingredient and stock entry. And also that would not prevent to just add an invalid conversion factor, which is the practical problem most of the time.

&nbsp;
> Grocy is violating POLA here.

Just my advice as always: If grocy makes so much which doesn't fit you, just don't use it and all those problems are gone.

Whatever, let's just add what I said above: Prevent that saving a recipe ingredient with an invalid "display QU" is not possible.

**Comment by berrnd** [comment]
> To illustrate what I mean:
> * I have set up everything (product, conversion, recipe and ingredients as in the beans example above) and all is good
> * After some months I start to buy my beans somewhere else where they sell 300 gram packs
> * I change the unit conversion to 1 pack = 300 grams
> * A few weeks later I cook the recipe and realize that it tastes really weird because the ratios are messed up

"QU stock = Pack" makes no sense when you want to track/store the product per Grams. Use Grams as the products QU stock and this is not a problem. Let me know if you know how to magically guess and prevent that.

**Comment by Lykos153** [comment]
First of all, thanks for your responsiveness and for adding a guard to the API to address this user error!

> Just my advice as always: If grocy makes so much which doesn't fit you, just don't use it and all those problems are gone.

Up until e8f76e5, Grocy did exactly one thing that didn't "fit" me. To be crystal clear: I think Grocy is a great piece of software that helps me immensely in organizing my household by addressing so many pain points all in one and doing so with a very appealing UI on top.

And while I have challenged some design decisions in this issue (and I might have done so out of a lack of understanding), we don't need to agree on every one of them for my last statement to remain true.

Thank you for providing Grocy to the world!
