### ISSUE TITLE
Feature Request: Add a page for products barcodes

### ISSUE THREAD

**Issue by fuhraih** [grocy/grocy#2014]
It might ne usefull to have a page where all the products name and barcodes are displayed. So we can display it on a screen or print it for easily scan products for filling the shopping list or inventory.
We could choose which product group display. By default, the products are grouped by category and sort by names.

**Comment by berrnd** [comment]
> It might ne usefull to have a page where all the products name and barcodes are displayed.

That page already exists, it's the [master data / products list](https://demo-prerelease.grocy.info/products), the grocycode column is hidden by default, just show it via table options.

![grafik](https://user-images.githubusercontent.com/2161815/193650869-7367363d-4d0c-4781-9202-0134b3380a04.png)

![grafik](https://user-images.githubusercontent.com/2161815/193651009-1958bd27-1e9c-4cff-a54e-1e2c73ebbfe9.png)

&nbsp;
> We could choose which product group display. By default, the products are grouped by category and sort by names.

The very same page already has a separate filter for `Product group`. Beside that the generic search field above each table searches in all visible columns and you can sort any table by any column by clicking on the column header.
