### ISSUE TITLE
Feature Request: Get different entry pages by user

### ISSUE THREAD

**Issue by fuhraih** [grocy/grocy#2016]
It is possible to define an entry page in the config.php file, but the users can have different needs.
The different users have different usages. We can define some authorizations, it might be usefull to also define an entry page per user.
For example, I could set the chores or calendar page for my children, while my wife entry page is the shopping list and mine is the stock overview.
We can keep the entry page in teh config file and then in user parameters define if we use the default or another entry page with a combobox.

**Comment by berrnd** [comment]
Simply use different bookmarks in your browser for that.
