### ISSUE TITLE
Missing vendor directory

### ISSUE THREAD

**Issue by dillwishlist** [grocy/grocy#202]
Hello,

I'm trying to get this up and running.  I seem to be missing the "vendor" directory, specifically the autoload.php file.  How do you suggest I remedy?

PHP Fatal error:  require_once(): Failed opening required '/var/www/grocy/vendor/autoload.php' (include_path='.:/usr/share/php') in /var/www/grocy/app.php on line 37

Thanks,
Alexander

**Comment by berrnd** [comment]
When you use the [release ZIP file](https://releases.grocy.info/latest), everything is included, when you cloned the repository, Composer and Yarn dependencies need to be installed manually, as also [stated in README](https://github.com/grocy/grocy#how-to-install).
