### ISSUE TITLE
Bug: Chores scheduling for once a day do not appear to be scheduled every day

### ISSUE THREAD

**Issue by dinki** [grocy/grocy#2026]
I posted this on Reddit for help but did not get any responses.  Writing here to see if someone can help:

Hi all. Been running Grocy for chore tracking for a good while now but I am seeing some oddities where a chore that I want to run every day is not being scheduled that way. It very could be that I don't understand how to do this so I'll share my settings here in the hopes that someone can help be get this straight:

Name: Kitchen - Wipe Counters

Active: checked

Period type: Hourly (have tried daily previously)

Period interval: 12 (have tried set to 24 as well previously and 1 day when using daily)

Start date: 2022-05-28 14:38:55

Assignment type: In alphabetical order

Assign to: Bob, Mary, Jane, Sue

Track date only: checked

Due date rollover: check

Can someone tell me where I am going wrong? I have the docker container set to auto update every morning at 1am so I am always running the latest version.

Side note: We have been running this since late May and it has made a terrific difference in getting things done in our home and has generally made things much nicer.

**Comment by berrnd** [comment]
> I posted this on Reddit for help but did not get any responses. Writing here to see if someone can help:

And I've just [replied to your post](https://www.reddit.com/r/grocy/comments/y6dwyq/comment/istf5we/?context=3) there, maybe just wait a little longer than 24 hours, which is IMHO a pretty ok response time for a free open source hobby "product".

This is the tracker for reproducible bugs and feature requests (please note what's [mentioned in README](https://github.com/grocy/grocy#questions--help--bug-reports--feature-requests)), so far this is not reproducible.
