### ISSUE TITLE
Bug: Different QU stock & purchase results in QU conversion error

### ISSUE THREAD

**Issue by ITensEI** [grocy/grocy#2028]
When adding a new product QU stock & unit purchase have to be set to the same value. After the product is saved you can switch the Stock value to something different and set up unit conversion but it will not be respected when adding product to inventory or shopping list. If you set them to different values during creation trying to setup conversion will result in the following error:
`"{\"error_message\":\"SQLSTATE[23000]: Integrity constraint violation: 19 QU conversion already exists\"}"`

After it is setup and the unit conversion is saved when you try to add the item to inventory or shopping list, even though the Default QU purchase is set to a different unit it tries to use the stock QU.

**To reproduce:**
Add Milk 2% to Products master data.
Set Stock & Purchase QU to Pack
Save
Go back and edit Stock QU to Litre
Create QU Conversion -> 1 Pack = 2 Litre
Add Milk 2% to shopping list 
Pack (purchase QU) is selected by default, but entering 1 Pack shows 

![image](https://user-images.githubusercontent.com/9561099/197062776-682b84f1-cd83-4ae9-9e7a-930545f3d06b.png)
![image](https://user-images.githubusercontent.com/9561099/197063518-a7f8969a-edf6-4f60-b65e-7f6d44da76f6.png)

Tested on [latest pre-release](https://demo-prerelease.grocy.info/)

**Comment by berrnd** [comment]
> When adding a new product QU stock & unit purchase have to be set to the same value.

Not true, you can of course also initially set a QU stock different to the default QU purchase.

&nbsp;
> If you set them to different values during creation trying to setup conversion will result in the following error:
`"{\"error_message\":\"SQLSTATE[23000]: Integrity constraint violation: 19 QU conversion already exists\"}"`

I'm unable to reproduce that:

https://user-images.githubusercontent.com/2161815/197124598-9b053ff6-3658-4bf8-95ac-822534dbaa91.mp4

&nbsp;
> After it is setup and the unit conversion is saved when you try to add the item to inventory or shopping list, even though the Default QU purchase is set to a different unit it tries to use the stock QU.

The issue template mentions to reproduce problems on a [private/persistent demo instance](https://www.reddit.com/r/grocy/comments/jwnk9b) (the public ones get reseted multiple times a day), most of the time there is more around than visible on a single screenshot or a brief description.

I took the time and did that for you, based on what you mentioned above: https://test-jwedvnfk4ar4tiru0wd4.demo-prerelease.grocy.info/product/27

And I can't reproduce your mentioned problem:

![grafik](https://user-images.githubusercontent.com/2161815/197125388-7cc0d894-163f-44bb-8a16-1f636a7d7b62.png)
