### ISSUE TITLE
Allow partial units for minimum stock

### ISSUE THREAD

**Issue by Wdavery** [grocy/grocy#203]
Take something like condiments, a bottle of ketchup or something. I will periodically update the on-hand quantity as it depletes. 3/4 bottle, 1/2 bottle, 1/4 bottle.

I'd love to be able to set a minimum stock amount to something like 0.25 and not have "a full bottle" until I have none left.

**Comment by berrnd** [comment]
(Only when the product option "Allow partial units in stock" is enabled.)
