### ISSUE TITLE
Feature Request: Firefly-III integration

### ISSUE THREAD

**Issue by Letouane** [grocy/grocy#2030]
Hello and thank you for developing and sharing Grocy,
I'm new to Grocy and I wonder if it's possible to connect Grocy to Firefly-III.
I would love to be able to export the total cost of my groceries as well as the store directly into Firefly-III. It will save me a double entry and I find these two tools complementary.
I already saw that both apps have APIs but I don't think I'll be able some day to achieve that kind of link between those.

On the other hand, I had trouble getting Grocy to work behind Traefik and I would also like to share the method I used, which may not be ideal but functional. How can I publish it in the best way?

**Comment by berrnd** [comment]
This is nothing that will be integrated into grocy, I personally even don't use Firefly III.

Adding a general import/export functionality is tracked in #129 and as you mentioned, you can access everything using the API, so technically everything needed is already there to make an export possible.

&nbsp;
> On the other hand, I had trouble getting Grocy to work behind Traefik and I would also like to share the method I used, which may not be ideal but functional. How can I publish it in the best way?

I have no personal preference, whatever you like. If you meant adding it to [grocy.info/links](https://grocy.info/links), also possible - the website has [it's own repo](https://github.com/grocy/grocy-website) and you can add it yourself by opening a pull request there.
