### ISSUE TITLE
Feature Request: Accounts/bartabs

### ISSUE THREAD

**Issue by Tahtk3v** [grocy/grocy#2034]
A intergration so that users (linked to OpenLDAP) can have a bar tab/account with money on it so that they can buy foodstuffs(or other items)

**Comment by berrnd** [comment]
Please explain more detailed what this should be, really can't get what you want from this short description.

LDAP authentication is already possible ([config options ref](https://github.com/grocy/grocy/blob/30704485559c13c5cf1add73d011da488823ad3e/config-dist.php#L85)-L91).

And please remember that grocy is and will be about managing your fridge/food/home, nothing else.
