### ISSUE TITLE
Bug: v3.3.2: 500 Internal Server Error + no more HTML headers

### ISSUE THREAD

**Issue by matttbe** [grocy/grocy#2038]
Hello,

Thank you for this great web app!

I just upgraded from v3.3.1 to v3.3.2 and I now get a 500 error with HTML content but not having HTML headers, starting with:

```html





<div class="row">
	<div class="col">
		<div class="title-related-links">
			<h2 class="title mr-2 order-0">
				Stock overview			</h2>
```

ending with:

```html

</div>

<div class="modal fade"
	id="stockoverview-productcard-modal"
	tabindex="-1">
	<div class="modal-dialog">
		<div class="modal-content text-center">
			<div class="modal-body">
```

It is installed on an old server with PHP 7.4.

Is there anything else I can share?

**Comment by berrnd** [comment]
This here is the tracker for reproducible bugs and feature requests as [mentioned in README](https://github.com/grocy/grocy#questions--help--bug-reports--feature-requests), this here sounds more like a setup problem, the better place for that is the [r/grocy subreddit](https://www.reddit.com/r/grocy) (as also mentioned at the same place in README).

Check your webserver logs for more detailed errors, triple check you have cleared the `data/viewcache` directory during the update (as [mentioned in README](https://github.com/grocy/grocy#how-to-update)).

&nbsp;
> It is installed on an old server with PHP 7.4.

Currently anything is only tested against PHP 8.0 (as also [mentioned in README](https://github.com/grocy/grocy#how-to-install)).

**Comment by matttbe** [comment]
Thank you for the reply, I'm sorry for having reported the bug. I'm not a reddit user and I thought it was a regression.

I forgot to mention I used the `update.sh` script.

Sadly I cannot upgrade php on this server. I will rollback to the previous version then.

Thanks for the support.

**Comment by berrnd** [comment]
When there is a internal server error, more about that will be in your webserver and/or PHP error logs. Where you find them exactly is of course up to your configuration. I would personally simply have a look there instead of guessing about the cause.

**Comment by matttbe** [comment]
Thank you for this note.
I just received the Apache logs (accessible by root only):

```
[Sat Nov 12 19:09:09.841902 2022] [php7:error] [pid 16439] [client <IP>:<port>] PHP Fatal error:  Declaration of Ramsey\\Uuid\\Uuid::unserialize(string $data): void must be compatible with Serializable::unserialize($serialized) in /var/www/grocy/vendor/ramsey/uuid/src/Uuid.php on line 312
```

I did a rollback to v3.3.0 and everything is back. I will stay on this version until I'm able to move to another server with more control or up to date.

**Comment by berrnd** [comment]
I've took the time: Yes, is reproducible when running the current v3.3.2 release with PHP 7.4.

Not a bug, not a regression, since aynthing PHP <> 8.0 is currently and since [v3.1.0](https://grocy.info/changelog#v3.1.0) (so since nearly 1.5 years) unsupported.

**Comment by matttbe** [comment]
thank you for having taken the time.

**Comment by fnordson** [comment]
@matttbe FYI: I can confirm switching server to PHP8 made it work again with the current version.
