### ISSUE TITLE
Updating from 3.3.1 to 3.3.2 fails 

### ISSUE THREAD

**Issue by phellarv** [grocy/grocy#2040]
When I use the update.sh script to update from 3.3.1 to 3.3.2 I loose all the CSS. 
After restoring the backup, allt the CSS is back.

Sorry about the vague description.

**Comment by berrnd** [comment]
This here is the tracker for reproducible bugs and feature requests as [mentioned in README](https://github.com/grocy/grocy#questions--help--bug-reports--feature-requests), that here sounds more like a setup problem and the better place for those things is the [r/grocy subreddit](https://www.reddit.com/r/grocy) (as also mentioned at the same place in README).

&nbsp;
> Sorry about the vague description.

Right, I don't have the slightest idea what it could be by that, I guess something went wrong.

**Comment by phellarv** [comment]
OK. Here goes:
Grocy before upgrade:
![before_upgrade](https://user-images.githubusercontent.com/822762/201861957-dfd803e2-852c-4140-8608-abe5570f5962.png)

Upgrade successful:
![Upgrade_successful](https://user-images.githubusercontent.com/822762/201862034-2f5c5a85-5732-4690-8e26-95c5205895a0.png)

Grocy after Upgrade:
![after_upgrade](https://user-images.githubusercontent.com/822762/201862182-7b22ee53-34f8-431d-bda5-02e05607a4cd.png)

Relevant loglines from apachelog:
[Tue Nov 15 08:55:28.121019 2022] [mpm_prefork:notice] [pid 25757] AH00170: caught SIGWINCH, shutting down gracefully
[Tue Nov 15 08:55:28.223948 2022] [mpm_prefork:notice] [pid 83040] AH00163: Apache/2.4.54 (Debian) configured -- resuming normal operations
[Tue Nov 15 08:55:28.224007 2022] [core:notice] [pid 83040] AH00094: Command line: '/usr/sbin/apache2'
[Tue Nov 15 08:55:47.810815 2022] [php7:error] [pid 83045] [client 10.1.30.11:42472] PHP Fatal error:  Declaration of Ramsey\\Uuid\\Uuid::unserialize(string $data): void must be compatible with Serializable::unserialize($serialized) in /var/www/html/vendor/ramsey/uuid/src/Uuid.php on line 312, referer: http://grocy.home.arpa/stockoverview
[Tue Nov 15 08:55:48.547208 2022] [php7:error] [pid 83043] [client 10.1.30.11:42500] PHP Fatal error:  Declaration of Ramsey\\Uuid\\Uuid::unserialize(string $data): void must be compatible with Serializable::unserialize($serialized) in /var/www/html/vendor/ramsey/uuid/src/Uuid.php on line 312, referer: http://grocy.home.arpa/stockoverview
[Tue Nov 15 08:55:49.246988 2022] [php7:error] [pid 83041] [client 10.1.30.11:42530] PHP Fatal error:  Declaration of Ramsey\\Uuid\\Uuid::unserialize(string $data): void must be compatible with Serializable::unserialize($serialized) in /var/www/html/vendor/ramsey/uuid/src/Uuid.php on line 312, referer: http://grocy.home.arpa/stockoverview
[Tue Nov 15 08:55:50.079966 2022] [php7:error] [pid 83054] [client 10.1.30.11:42552] PHP Fatal error:  Declaration of Ramsey\\Uuid\\Uuid::unserialize(string $data): void must be compatible with Serializable::unserialize($serialized) in /var/www/html/vendor/ramsey/uuid/src/Uuid.php on line 312, referer: http://grocy.home.arpa/stockoverview
[Tue Nov 15 08:55:50.747996 2022] [php7:error] [pid 83043] [client 10.1.30.11:42570] PHP Fatal error:  Declaration of Ramsey\\Uuid\\Uuid::unserialize(string $data): void must be compatible with Serializable::unserialize($serialized) in /var/www/html/vendor/ramsey/uuid/src/Uuid.php on line 312, referer: http://grocy.home.arpa/stockoverview

Nothing done except running update.sh, and the restarted apache.

**Comment by phellarv** [comment]
And I have reproduced the problem this morning, so it's not an one-off.

**Comment by phellarv** [comment]
Having THIS kind of attitude, reminds me why some areas in the opensource community are to be avoided. You could easily have pointed out that PHP7 is not supported anymore without using capital letters. You could easily asked me for more info without fended me off with a "reddit is for nagging".
I've been deeply into opensource both as a developer and as a system administrator for the last 26 years, and still I find attitudes like this. I gravely regret even thinking about opening an issue, and will in the future fix bugs on my own, and contributing is pretty much off the table. I don't care for harassment if I might be a bit vague, or do not do things the way the owner of this project has decided how things should be done.
So have a fine day, and smile a bit more.
