### ISSUE TITLE
Feature Request: Manually Reschedule/Reassign Chores via REST API

### ISSUE THREAD

**Issue by shbatm** [grocy/grocy#2042]
The following issues added the ability to manually reschedule and reassign chores, but doesn't appear to include the ability to do this from the API, at least not a method that is documented or available in the REST API browser.

https://github.com/grocy/grocy/issues/1830
https://github.com/grocy/grocy/issues/1486

I would like to be able to use condition-based chore assignments from my home automation, but this requires the ability to set the due dates via REST. For example: I have a chore for backflushing my pool filter every 8 weeks; I have a pressure transmitter on the filter so I can set a chore due date based on if the pressure is too high, rather than just time based.

**Comment by berrnd** [comment]
> but doesn't appear to include the ability to do this from the API

Can't be the case for just like anything, since the web frontend uses the API for everything. A very simple way to find out how things work is to use the UI, while also having a look at your favorite browsers developer tools and see what actually happens.

Example request to reschedule and reassing a chore:
```
curl -X 'PUT' \
  'https://demo-prerelease.grocy.info/api/objects/chores/1' \
  -H 'accept: */*' \
  -H 'Content-Type: application/json' \
  -d '{
  "rescheduled_date": "2025-01-05",
  "rescheduled_next_execution_assigned_to_user_id": "2"
}'

**Comment by shbatm** [comment]
Thanks, just found this digging through the code myself.
