### ISSUE TITLE
Can’t scroll tables on mobile

### ISSUE THREAD

**Issue by OmgImAlexis** [grocy/grocy#205]
Is it possible to enable scrolling horizontally in tables?

Trying to use any tables in portrait mode just doesn’t work as you can only see the first one or two columns.
![B6C537BF-90E9-43E7-84AE-53CE059025C6](https://user-images.githubusercontent.com/6525926/55662966-62405a00-5860-11e9-9dbe-e962565a2529.png)

https://demo-prerelease.grocy.info/productgroups

Switching my phone to landscape mode does help but I’d love for portait mode to be supported too. 🙏

**Comment by berrnd** [comment]
Maybe somehow a "min width" can be defined...

The component used for all tables is [DataTables](https://datatables.net/) with the [Responsive extension](https://datatables.net/extensions/responsive/).

**Comment by berrnd** [comment]
I also checked this more detailed ... the idea of DataTables Responsive is to collapse columns when the viewport is too narrow - they can be shown with the blue plus symbol in front of each row.

So changing this into to a table which scrolls horizontally would mean to remove the DataTables Responsive extension - don't know what is better...

**Comment by berrnd** [comment]
I think we'll leave it as it is - that's the idea of DataTables Responsive - to collapse columns which not fit the viewport into a expandable section to always fit the screen...
