### ISSUE TITLE
Bug: When running the inventory, the browser window hangs

### ISSUE THREAD

**Issue by slimline33** [grocy/grocy#2050]
I cannot change the current inventory via the web interface. Here, for example, the article "Dishwasher salt" by KG.
I have tried with . and , as decimal separators. Nothing is added. The mouse pointer stays on hourglass.

Tested with chrome and edge.

![image](https://user-images.githubusercontent.com/3323812/203777434-d19b9912-7490-472a-a473-25570bc6449b.png)

Grocy 3.3.2 runs in a LXC container for me.

**Comment by berrnd** [comment]
There are so much things involved on that specific process, some of them:
- The product (any product option)
- The quantity unit (any QU option)
- (Maybe) quantity unit conversion factors
- Config settings
- User settings

I'm unable to help without having something reproducible (don't know how to guess all that details), means the exact steps to get that are needed (every detail). Easiest way: Create a reproducible example on a [private/persistent demo instance](https://www.reddit.com/r/grocy/comments/jwnk9b) (all of that is mentioned on the issue template).
