### ISSUE TITLE
Feature Request: Recipe fullscreen ingredients and preparation both visible

### ISSUE THREAD

**Issue by mx03** [grocy/grocy#2051]
In recipe fullscreen mode, it would be great if the ingredients and the prepation are both visible if the width of the site is large enough.

Not sure if its only me, but its a way better cooking experience on tablet, if i can see the amount and the ingredients beside the preparation, without switching all the time between these two tabs.

As an example
https://codepen.io/0x03x/pen/KKeRwje

**Comment by berrnd** [comment]
Something for that was started by @adamschmalhofer in #1628 about a year ago, but not finished so far.

Feel free to catch up on that, most likely "only" CSS fiddling...

**Comment by adamschmalhofer** [comment]
Yeah, I lost interest in upstreaming the changes. I've been using the changes ever since and it works without merge conflicts with current grocy (v3.3.2 as of writing). The change is rather small and only touches one css file.

**Comment by Dehalion** [comment]
@berrnd @adamschmalhofer What would be necessary to get it into upstream?
Should this be a system-wide setting or a per-view choice (e.g. button in the recipe view)?

**Comment by berrnd** [comment]
> What would be necessary to get it into upstream?

To fix the UI glitches mentioned in https://github.com/grocy/grocy/pull/1628#pullrequestreview-771759543.

&nbsp;
> Should this be a system-wide setting or a per-view choice (e.g. button in the recipe view)?

What was started so far in #1628 was not not to make this optional / introduce a new setting somewhere - but feel free to start also implementing that, if you think it's useful and/or necessary.

**Comment by Dehalion** [comment]
My bad, I just looked at the changes, not at the issues mentioned below.
I'll look into it.

**Comment by adamschmalhofer** [comment]
Just tested it. Works great! Thank you.
