### ISSUE TITLE
Feature Request: Filter iCal event types

### ISSUE THREAD

**Issue by bitte-ein-bit** [grocy/grocy#2059]
While I like to use e.g. due date tracking, I'm not interested in having those types show up in my iCal feed. I'd like to be able to filter by types. i.e. only show chores. I'm fine with manually appending a filter on the iCal URL. Something like https://grocy.example.com/api/calendar/ical?secret=BbwCzii3NzVFqiIJVhRCefUwftsXisI953ztO0BdGcLehPzbgB&select=chores would be good enough.

**Comment by berrnd** [comment]
Duplicate of #1984 - please check existing requests first.

**Comment by bitte-ein-bit** [comment]
hmm. I did check the existing requests. Looks like my keywords were wrong. Sorry
