### ISSUE TITLE
FreeBSD install?

### ISSUE THREAD

**Issue by Naesstrom** [grocy/grocy#206]
Anyone know of a guide how to install this in a FreeBSD install. I have a FreeNas system running 24/7 and would be lovely to get this into a jail there!

**Comment by berrnd** [comment]
I think having nginx or Apache on FreeBSD should not be that different as on any other Linux distribution...

If FreeNAS supports Docker, maybe try using https://github.com/grocy/grocy-docker...

**Comment by Naesstrom** [comment]
Thanks for the really fast reply. I've installed nginx, php and sqlite3. unrared the grocy folder to `usr\local\www\grocy` etc.

Server block in nginx config looks like this:
```
    server {
        access_log /var/log/nginx/example.com.access.log;
        error_log /var/log/nginx/example.com.error.log;
        listen       80;
        server_name  192.168.1.220;

        location / {
            try_files $uri /index.php;
            root   /usr/local/www/grocy/public;
            index  index.html index.htm;
        }
    }
```
When I reload nginx and go to the IP the browser just downloads a file that contains:
```
<?php

require_once __DIR__ . '/../app.php';
```

**Comment by berrnd** [comment]
Sure, because you need to tell nginx that `.php` files need to be executed/send to the PHP interpreter...

Assuming you have installed PHP-FPM 7.2 which uses sockets (instead of TCP/IP) by default:

```
    server {
        access_log /var/log/nginx/example.com.access.log;
        error_log /var/log/nginx/example.com.error.log;
        listen       80;
        server_name  192.168.1.220;

        location / {
            try_files $uri /index.php;
            root   /usr/local/www/grocy/public;
            include php.conf;
        }
    }
```

Where `php.conf` looks like:
```
location ~* \.(php|inc)$ {
	include fastcgi.conf;
	
	fastcgi_pass unix:/run/php/php7.2-fpm.sock;
	fastcgi_index index.php;
	fastcgi_intercept_errors on;
	fastcgi_buffer_size 16k;
	fastcgi_buffers 4 16k;
}
```

And `fastcgi.conf` looks like:
```
fastcgi_param  SCRIPT_FILENAME    $document_root$fastcgi_script_name;
fastcgi_param  PATH_INFO          $fastcgi_script_name;
fastcgi_param  QUERY_STRING       $query_string;
fastcgi_param  REQUEST_METHOD     $request_method;
fastcgi_param  CONTENT_TYPE       $content_type;
fastcgi_param  CONTENT_LENGTH     $content_length;

fastcgi_param  SCRIPT_NAME        $fastcgi_script_name;
fastcgi_param  REQUEST_URI        $request_uri;
fastcgi_param  DOCUMENT_URI       $document_uri;
fastcgi_param  DOCUMENT_ROOT      $document_root;
fastcgi_param  SERVER_PROTOCOL    $server_protocol;
fastcgi_param  HTTPS              $https if_not_empty;

fastcgi_param  GATEWAY_INTERFACE  CGI/1.1;
fastcgi_param  SERVER_SOFTWARE    nginx/$nginx_version;

fastcgi_param  REMOTE_ADDR        $remote_addr;
fastcgi_param  REMOTE_PORT        $remote_port;
fastcgi_param  SERVER_ADDR        $server_addr;
fastcgi_param  SERVER_PORT        $server_port;
fastcgi_param  SERVER_NAME        $server_name;
```

Maybe that helps...

**Comment by Naesstrom** [comment]
Sorry for being so stupid about all of this... should php.conf and fastcgi.conf be in the nginx folder _(ie. same place as nginx.conf)_, in grocy/public or just in plain **usr/local/etc** _(where I already have a huge php.info)_

**Comment by berrnd** [comment]
No problem, and yes - all included files need to be int the same folder as `nginx.conf`...

**Comment by berrnd** [comment]
Closing this for now, feel free to reopen it if anything still does not work.
