### ISSUE TITLE
Feature Request: On a stock entry with a quantity>1, only consume one not all quantity

### ISSUE THREAD

**Issue by bertrandgodefroy** [grocy/grocy#2060]
Currently, the consumption button consumes all the quantity of one stock entry.
Only consume one entry or select the amount to consume.

**Comment by berrnd** [comment]
> Currently, the consumption button consumes all the quantity of one stock entry.

One Button does that, there is at least another button and of course the normal way to consume any amount you define:

On [/stockoverview](https://demo-prerelease.grocy.info/stockoverview) this button per line consume everything in stock of the corresponding product:

![grafik](https://user-images.githubusercontent.com/2161815/206872702-a5fbac23-59f2-42ff-947f-2c277a82a424.png)

On [/stockoverview](https://demo-prerelease.grocy.info/stockoverview) this button per line consume the amount you define by the [product option `Quick consume amount`](https://demo-prerelease.grocy.info/product/12#quick_consume_amount) (defaults to `1`):

![grafik](https://user-images.githubusercontent.com/2161815/206872714-91539cf5-eb84-493a-a342-77eee59cc1bc.png)

On [/consume](https://demo-prerelease.grocy.info/consume), you can define any amount you want to consume (the decimals are up to the [stock setting `Decimal places allowed for amounts`](https://demo-prerelease.grocy.info/stocksettings#group-stock_decimal_places_amounts) (defaults to `4`).

There are a couple of more ways to consume things ([/stockentries](https://demo-prerelease.grocy.info/stockentries), context/more menu on the stock overview or stock entries page, ...).

So sorry, but I don't get what's not possible in that manner. Mabye describe a little bit more detailed what you really want to have added. The better place for general usage question would be the [r/grocy subreddit](https://www.reddit.com/r/grocy) as [mentioned in README](https://github.com/grocy/grocy#questions--help--bug-reports--feature-requests).
