### ISSUE TITLE
Bug: quantity unit stock has no values to choose

### ISSUE THREAD

**Issue by bitte-ein-bit** [grocy/grocy#2063]
The iOS Grocy app managed to create products with no default purchase unit. This renders a given product unchangeable, as only the purchase unit Dropdown has any values to choose. Since both are mandatory fields, the product can’t be updated/fixed.

I was able to populate the Dropdown by creating a dummy conversation. The save was allowed but after a refresh, the issue reappeared. The PUT request is logged with status code 400. PHP error log is quiet, even though if set the level to debug for php-fpm.

since I don’t know how the app managed to create it in the first place, I can’t fully reproduce either.

this is one of the affected products retrieved via the API
```
{
  "product": {
    "id": "112",
    "name": "Speisezwiebeln",
    "description": "",
    "product_group_id": "-1",
    "active": "1",
    "location_id": "3",
    "shopping_location_id": "1",
    "qu_id_purchase": "-1",
    "qu_id_stock": "-1",
    "qu_factor_purchase_to_stock": "1.0",
    "min_stock_amount": "0",
    "default_best_before_days": "180",
    "default_best_before_days_after_open": "0",
    "default_best_before_days_after_freezing": "0",
    "default_best_before_days_after_thawing": "0",
    "picture_file_name": "",
    "enable_tare_weight_handling": "0",
    "tare_weight": "0.0",
    "not_check_stock_fulfillment_for_recipes": "0",
    "parent_product_id": null,
    "calories": "0",
    "cumulate_min_stock_amount_of_sub_products": "0",
    "due_type": "2",
    "quick_consume_amount": "1.0",
    "hide_on_stock_overview": "0",
    "default_stock_label_type": "0",
    "should_not_be_frozen": "0",
    "row_created_timestamp": "2022-12-12T16:54:15.533Z",
    "treat_opened_as_out_of_stock": "0",
    "no_own_stock": "0",
    "default_consume_location_id": "",
    "move_on_open": "0"
  },
  "product_barcodes": [
    {
      "id": "135",
      "product_id": "112",
      "barcode": "4000874739200",
      "qu_id": "-1",
      "amount": null,
      "shopping_location_id": null,
      "last_price": null,
      "row_created_timestamp": "2022-12-12T16:54:15.750Z",
      "note": null
    }
  ],
  "last_purchased": "2022-12-12",
  "last_used": null,
  "stock_amount": "1",
  "stock_value": "1.99",
  "stock_amount_opened": "0",
  "stock_amount_aggregated": "1.0",
  "stock_amount_opened_aggregated": "0",
  "default_quantity_unit_purchase": null,
  "quantity_unit_stock": null,
  "last_price": "1.99",
  "avg_price": "1.99",
  "oldest_price": "1.99",
  "current_price": "1.99",
  "last_shopping_location_id": null,
  "default_shopping_location_id": "1",
  "next_due_date": "2023-06-10",
  "location": {
    "id": "3",
    "name": "Keller",
    "description": "",
    "row_created_timestamp": "2022-12-01 20:45:29",
    "is_freezer": "0"
  },
  "average_shelf_life_days": 180,
  "spoil_rate_percent": 0,
  "is_aggregated_amount": "0",
  "has_childs": false,
  "default_consume_location": null
}
```

**Comment by berrnd** [comment]
A product always needs to have a `Default quantity unit purchase`, so creating one (however) without one or maybe delete the selected unit afterwards leads to bullshit without real surprise.

grocy is generally based around [GIGO](https://en.wikipedia.org/wiki/Garbage_in,_garbage_out), so not a "bug".

**Comment by berrnd** [comment]
I've invested a couple of minutes to reproduce the mentioned example, here is a private demo instance: https://test-b304b3as1z8esoc3s4r0qd.demo.grocy.info

Having `qu_id_purchase` and `qu_id_stock` set to `-1` (negative id = never a valid object reference) is really crazy bullshit, what should be the working result for anything by that? 🙄

Whatever, creating that product (via the API) of course renders that product invalid, but it's totally possible to just select a valid unit on the product edit page:

https://user-images.githubusercontent.com/2161815/207155741-5c10a687-fa8d-4b38-bd3a-b8de32917fb7.mp4

Here is the same product unedited if you want to reproduce it practically yourself: https://test-b304b3as1z8esoc3s4r0qd.demo.grocy.info/product/28

Would be cool if you can create really reproducible examples for future "bug" reports.

**Comment by bitte-ein-bit** [comment]
Well, for a newcomer it’s really hard to meet the quality bar…

https://test-b304b3as1z8esoc3s4r0qd.demo.grocy.info/product/29 is the state I’m in for an unknown amount of products. I tried creating a conversation from unit -1 to unit 2. It shows up, but doesn’t look like it solves it.

```
{
  "error_message": "SQLSTATE[23000]: Integrity constraint violation: 19 qu_id_stock can only be changed when a corresponding QU conversion (old QU => new QU) exists when the product was once added to stock"
}
``` 

thanks for the effort on this “unqualified” bug report though.

**Comment by berrnd** [comment]
To clean up this mess:
- Create a quantity unit with id `-1` (via the API; not possible via the web frontend)
- Create a unit conversion between a valid unit and that one (because you've already added that product without any unit to stock, crazy again)
- Change the products stock QU to that unit (will also fix anything in-stock)
- => I've did that for https://test-b304b3as1z8esoc3s4r0qd.demo.grocy.info/product/29

I would recommend hourly backups and a test environment before doing garbage in "production".

**Comment by bitte-ein-bit** [comment]
thanks. that worked to get the mess cleaned up
