### ISSUE TITLE
Bug: 

### ISSUE THREAD

**Issue by master-kw** [grocy/grocy#2064]
Hi,

first of all, thank you for this fantastical app. It makes my 'daily shopping experience' so much easier. ;-)

The issue: 
If I add an item via (confirmed) QR-code I can't select any quantity unit. There's only a checkmark to choose although I have already created them.

The same in manual adding everything's fine.

![add item](https://user-images.githubusercontent.com/104136223/207870106-e8e09291-d106-45a0-9e8a-67d818061f38.jpg)

Regards,
Oliver

**Comment by berrnd** [comment]
This is not the repository of any of the community contributed mobile apps.
