### ISSUE TITLE
Bug: Wrong unit conversation

### ISSUE THREAD

**Issue by Saturo78** [grocy/grocy#2066]
Steps to reproduce:
Product Flour
Quantity unit stock: pack

QU conversions:
1 Pack = 1000 g
1 Table Spoon = 15 g

When i use Table Spoon in a recipe Grocy reports "this equals 25 packs"
When i set the Quantity unit stock to grams its seems to work okay.

**Comment by berrnd** [comment]
Please provide a reproducible example, as always and as mentioned on the issue template - [private/persistent demo instances](https://www.reddit.com/r/grocy/comments/jwnk9b) are still there for that.

I did that for you:
Product: https://test-4op2cjwo1r4euvf8ddqxhf.demo-prerelease.grocy.info/product/27
Recipe: https://test-4op2cjwo1r4euvf8ddqxhf.demo-prerelease.grocy.info/recipe/7

![grafik](https://user-images.githubusercontent.com/2161815/208257858-3c4aa727-9bed-47c2-9e2d-1658c27f828b.png)

Searching as also a very good approach when having problems - doing that leads to:
- #2039 describes exactly this problem.
- #1360 is the corresponding Feature Request and is also already done, but not yet released.
