### ISSUE TITLE
Feature Request: Track shopping location without price tracking

### ISSUE THREAD

**Issue by Saturo78** [grocy/grocy#2068]
I would like to disable the price tracking but would still like to track the shopping location of my purchases in the stock entries.
Could this feature easily turned on or did i have to do this via a userfield?

I use the grocy android app an like the posibility to enter new shopping locations in the masterdata section.
This would not be possible wenn i use a custom userfield.

**Comment by berrnd** [comment]
Don't disable `FEATURE_FLAG_STOCK_PRICE_TRACKING` if you want to use stores (the ones defined in master data) - those are part of that feature.

Of course replacing that with an Userfield is possible - including loosing the products "Default store" functionality and so on.

Consider using [custom CSS](https://github.com/grocy/grocy#adding-your-own-css-or-js-without-to-have-to-modify-the-application-itself) to hide price related fields, if that was the main reason to disable the price tracking feature.

**Comment by Saturo78** [comment]
Yes, hiding the price input field is mainly that what i want. Unfortunately i do not have the skills to do this on my own.
Maybe there are other users who are also interested in this idea.

**Comment by berrnd** [comment]
The most simplest option is to simply ignore those fields, they are not mandatory anywhere - is that really the biggest problem of all to have a field and just don't enter something?

Well, then let's better solve this most important problem right away - here is a snippet for `data/custom_css.html` to hide price inputs on the purchase and inventory page (standard CSS stuff, can also be easily googled):
```html
<style>
	#group-price {
		display: none !important;
	}
</style>
```

**Comment by Saturo78** [comment]
Of course i can ignore the fields. But the cursor still jumps in and i have to press tab once additionally.
So thank you very much for the solution!

**Comment by Saturo78** [comment]
Is the any documentation to find the relevant #tags to do such things?

**Comment by berrnd** [comment]
> Is the any documentation to find the relevant #tags to do such things?

Basically in your preferred Browser - again: Standard HTML/CSS stuff which can be easily googled, nothing grocy specific:

https://user-images.githubusercontent.com/2161815/208316288-842bbbd3-e4de-4897-b400-e0a8ae88ae8e.mp4
