### ISSUE TITLE
Feature Request: Show userfield in shopping list

### ISSUE THREAD

**Issue by Saturo78** [grocy/grocy#2069]
I want to order the products in the shoppinglist according to the order in the supermarket without loosing the ability to order the product groups in my own way by using leading numbers. (01-Fruits etc.).

Therefore i have created a userfield "order" for the product group and put in there the order for the supermarket.
No i have the issue that this userfield is not shown in the shopping list.

So i would like to ask if its posible to show a personal userfield in shopping lists.

**Comment by berrnd** [comment]
The shopping list already shows Userfields for the entity `products` and `shopping_list` - of course it's technically possible to also show `product_group` Userfields there.
