### ISSUE TITLE
Feature Request: External Authentication Source

### ISSUE THREAD

**Issue by davmin** [grocy/grocy#207]
I'd like to be able to authenticate my grocy users against an external source.  The method/protocol chosen isn't super important IMO as most people who have central authentication can support any of them with a bit of effort. LDAP(S), OIDC, and SAML are options.

Additionally some user management in the form of groups and permissions would be nice. For instance I may want a subset of users to be able to access the chores but not anything recipe related. Or I may want a subset of users to be able to add recipes to the cart but not edit recipes or ingredients.

**Comment by berrnd** [comment]
Let's split the permisson part into the new request #263 and keep this about adding external authentication source support.

If anyone wants to propose which roles/groups with which permissions would be needed, feel free to do so in #263.

**Comment by berrnd** [comment]
#921 is now merged, which also brings that the authentication class is now abstracts.

Means, any class that implements [`Grocy\Middleware\AuthMiddleware`](https://github.com/grocy/grocy/blob/master/middleware/AuthMiddleware.php) can now be used for (custom) authentication.

https://github.com/grocy/grocy/blob/31c412a28c44ab28ac1183f88a539c42af92c21c/config-dist.php#L69-L71

Permission things are still open and will be tracked in #263, as mentioned above.
