### ISSUE TITLE
Bug: QU conversation did not work when Parent Product is substituted

### ISSUE THREAD

**Issue by Saturo78** [grocy/grocy#2075]
Here is my test scenario:
https://test-4ku6qf0owshqxd9ohh4tt.demo-prerelease.grocy.info/recipes

Parent Product:
![grafik](https://user-images.githubusercontent.com/71584438/208899156-3c2c9f19-000a-4ee7-ada4-fcb00feb051f.png)
Stock QU = Milliliter
1ml = 1 kcal
Conversation: 
15 ml = 1 Piece

Child Product:
![grafik](https://user-images.githubusercontent.com/71584438/208899497-77dde873-0323-4464-869d-ada62b87c519.png)
Stock QU Bottle
1 Bottle = 150 ml
1 ml = 1 kcal
Conversations:
1 Bottle = 150 ml
1 Piece = 15 ml

Result:
![grafik](https://user-images.githubusercontent.com/71584438/208899761-89dfcbdd-2e92-4d72-9d93-cc59eeb9a7ed.png)
Expectet Calories: 15 Calculated Calories 225 = 225 ml = 1,5 Bottles

Second Try:
Child Product
![grafik](https://user-images.githubusercontent.com/71584438/208900045-65d3f714-fa30-4ef9-b32f-05e6806b9879.png)

I have deleted the conversation between Piece and ml and set a new directly between Bottle and Piece.
Result:
![grafik](https://user-images.githubusercontent.com/71584438/208900287-e8ba64b6-d9ad-4138-bf33-64c817450307.png)
Exactly the same.

What i'm doing wrong?

**Comment by berrnd** [comment]
> What i'm doing wrong?

Based on what I see on a first glance, nothing is wrong regarding definitions.

For parent/child product substitution any QU conversions (the needed one is between "Parent QU stock" and "Child QU stock" need to be defined on the child product, which is the case - that one:

![grafik](https://user-images.githubusercontent.com/2161815/208904261-04429808-a409-4642-8982-a8db8a0f1a8a.png)
Probably related to #1995.

**Comment by berrnd** [comment]
Btw: The costs are also not correct:

![grafik](https://user-images.githubusercontent.com/2161815/208982794-2eaa13f7-7efb-4c99-a1b0-675be95359fc.png)

1 Bottle of "Soja 150 ml" = 3.99 => 1 ml = 3.99/150 = 0.0266 => 15 ml = 0.399.

This is now also fixed (a wrong conversion factor was taken when a product substitution was involved):

![grafik](https://user-images.githubusercontent.com/2161815/208983218-6dd67d52-1eda-44f9-95d8-6dfa0b8abd49.png)

Double check: When the parent product "Soja*" itself is in stock, it's still correct:

![grafik](https://user-images.githubusercontent.com/2161815/208984614-5eb937d1-a78b-4d91-86cb-53adbf376964.png)

I bought 150 ml of "Soja*" for 5.99 => 1 ml = 5.99/150 = 0.03993 => 15 ml = 0,59895
