### ISSUE TITLE
Feature Request: 

### ISSUE THREAD

**Issue by loovanloon** [grocy/grocy#2077]
Please add the following functionality to the Shopping list:

Store / Shop: where you buy your grocery item
Department/ Route: the department (eg Fresh vegetables , Meat, Dairy, Frozen, Cookies) in a store where you can find the item on your shopping list. This can simply be a integer or a string ( that starts with a number : 01 Vegies, 02 Bread, 03 Soups & Herbs etc)
As a user I want to group and sort my shopping list items by Store and within the Store by Department because it will make my shopping far more efficient: It will give an efficient route for my shopping.

As a user I want be able to set the order of the Shops and Department as a setting, e.g.
Shops: 01 supermarket A, 02 Butcher, 03 Bakery,
Departments: 01 Vegies, 02 Bread, 03 Soups & Herbs

As a user I want to be able to have my shopping list presented grouped by and order by shop and department.

As a user I want to be able to assign a default shop and department to each common stock item so that I do not have to input this info every time I put a stock item on my shopping list.

As a user I want to be able to override the default store and department when I put a stock item on my shopping list.

**Comment by berrnd** [comment]
Userfields (ref #176) can be used to add any field you want to any entity (= a product, a shopping list item, etc.) you want - so everything of that is kind of already possible. And in any table rows can be grouped by any shown field/column (top left corner table options).

Please keep it to one topic per request (everything else is untrackable) and please also search existing requests before opening new ones - both is also mentioned on the request template.

&nbsp;
> Department/ Route: the department (eg Fresh vegetables , Meat, Dairy, Frozen, Cookies) in a store where you can find the item on your shopping list. This can simply be a integer or a string ( that starts with a number : 01 Vegies, 02 Bread, 03 Soups & Herbs etc)
> As a user I want to group and sort my shopping list items by Store and within the Store by Department because it will make my shopping far more efficient: It will give an efficient route for my shopping.

The default demo data already showcases that by using the built-in product group field + grouping by that: https://demo-prerelease.grocy.info/shoppinglist
![grafik](https://user-images.githubusercontent.com/2161815/209294383-60509b85-d8b9-45d9-9208-b5cc032f8264.png)

&nbsp;
>As a user I want be able to set the order of the Shops and Department as a setting, e.g.
>Shops: 01 supermarket A, 02 Butcher, 03 Bakery,
> Departments: 01 Vegies, 02 Bread, 03 Soups & Herbs

Use Userfields for that, related example: #2069

&nbsp;
> As a user I want to be able to have my shopping list presented grouped by and order by shop and department.

As mentioned above: In any table rows can be grouped by any shown field/column (top left corner table options).

&nbsp;
> As a user I want to be able to assign a default shop and department to each common stock item so that I do not have to input this info every time I put a stock item on my shopping list.

There is already a product option "Default store", use a Userfield for the "department" if you need that per product (I guess it makes more sense per product+store) - related / duplicate Feature Requests: #662, #1719, #1357

**Comment by loovanloon** [comment]
Dear Bernt,Thank you for your detailed reply. I am Vert pleased with it. Met vriendelijke groet,Ton van LoonOp 23 dec. 2022 om 08:52 heeft Bernd Bestel ***@***.***> het volgende geschreven:﻿
Closed #2077 as completed.

**Comment by arcanefoam** [comment]
Sorry for commenting on a closed issue, but I am also looking at this functionality and the user fields don't cover all the cases, in particular when you shop in 2 or 3 different stores and the product is at a different aisle/location in each store.

I already looked at the source code, but could not find where the data models are defined (i.e. the db structure) . If you point me in the right direction I might be able to make a PR for this feature.

**Comment by berrnd** [comment]
> when you shop in 2 or 3 different stores and the product is at a different aisle/location in each store.

Duplicate of #1719 - please check existing requests before opening new or spamming existing ones.

&nbsp;
> could not find where the data models are defined (i.e. the db structure)

The entire database is populated by running all migrations found in the [`/migrations`](https://github.com/grocy/grocy/tree/master/migrations) folder.
