### ISSUE TITLE
Calendar starts week on incorrect day

### ISSUE THREAD

**Issue by unikitty37** [grocy/grocy#208]
The calendar shows the week as being from Sunday to Saturday. This is correct only for some cultures, such as the US.

I need it to show from Monday to Sunday, but I cannot find a configuration option for this.

Please could this be added? Ideally, it would be per-user, but a `config.php` system-wide setting would probably do for most cases…

Thanks

**Comment by berrnd** [comment]
For me, living in Germany, the first day of the week is also monday - that already works (see the [German demo](https://demo-de.grocy.info) for example) like that:

The component used for the datepicker is [tempusdominus-bootstrap-4](https://tempusdominus.github.io/bootstrap-4/), the "big" calendar is based on [FullCalendar](https://fullcalendar.io/). Both come with their own localizations, but the datepicker just uses [Moment.js](https://momentjs.com/) for this. Which component translations to use is "translated" in `component_translations.php` ([link to German file](https://github.com/grocy/grocy/blob/41988aa1eee1d8fe255dec0b9e4352b7874c2e2e/localization/de/component_translations.php#L6)).

The translations are managed on Transifex (see README). So when this should work for the UK, a new translation for `en_GB` would be needed, probably with no real translations, only `component_translations.php`. Feel free to add this, or I can also do this later if you want...

**Comment by berrnd** [comment]
I've now added the `en_GB` localization, will be part of the next release. Nothing is really translated, except the `component_translations` as mentioned above.

Drop the folder in the attached ZIP into `/localization` and set the appropriate `/data/config.php` setting (`Setting('CULTURE', 'en_GB');`), if you want to use it right away.

[en_GB.zip](https://github.com/grocy/grocy/files/3108337/en_GB.zip)
