### ISSUE TITLE
Bug: Variable Amount displayed poorly in recipe

### ISSUE THREAD

**Issue by NathanSalapat** [grocy/grocy#2080]
I have a recipe that calls for 1 Tbsp of Lemon Juice, but I track lemon juice in tsp, so I set the amount to 3 tsp and then in the Variable amount field set 1 Tbsp. When viewing the recipe it shows, '1 Tbsp Tsp Lemon Juice' 

The popup with information about the Variable amount field makes it sound like what you enter there will be used for the recipe, which is why I'm reporting this as a bug rather than a feature request.

![unit conversion](https://user-images.githubusercontent.com/8930456/209415801-6f97e8af-7592-4536-a85e-358917f60aea.png)

**Comment by berrnd** [comment]
Please reread the help-tooltip, it's about the amount to be replaced by the "Variable amount" when set, not the quantity unit.

**Comment by berrnd** [comment]
Well, but it makes sense to also replace the unit - guess changing that doesn't hurt anyone, so let's do that.
