### ISSUE TITLE
Feature Request: Chores locations

### ISSUE THREAD

**Issue by gabt92** [grocy/grocy#2086]
It would be great to be able to assign a location to chores because there is not much way of filtering them this way. Yes, from Grocy a userfield could be created, but those are not exposed through the API.

In Home Assistant, more and more peolple are using the Grocy add-on & component, but the only way of filtering is by users of by the name of the chore and since the chore names needs to be unique, it's not possible to create simple chores like: 
- Vacuum _(for the Kitchen)_
- Vacuum (for the bedroom)
- etc...

The only way, as of today, seems to be to create chores with the location in the name like: 
- Kitchen: Vacuum
- Bedroom: Vaccum

And then, from HA, filter then by the content of their names.

I just think that adding a location to chore and expose those in the API would help side projects like this one : https://github.com/isabellaalstrom/lovelace-grocy-chores-card

It would usually help to better personalize the dashboards in Home Assistant and have, for example, different todo list of chores based on their location: 
![image](https://user-images.githubusercontent.com/38195308/210142760-349e99cb-4b3f-43f3-b152-e48817f2f563.png)

**Comment by berrnd** [comment]
Userfields are there for exactly such use cases, it's impossible and pointless to add any field someone can think of a an built-in field.

To be able to reuse existing objects (here: locations) as Userfields is tracked in #335.

Rendering separate table filters on the web frontend per Userfields is tracked in #1850 (the generic search field above each table already works, it searches in all visible columns).

&nbsp;
> a userfield could be created, but those are not exposed through the API

Not true.

https://demo-prerelease.grocy.info/api#/System

![grafik](https://user-images.githubusercontent.com/2161815/210145172-18bc364b-bae4-462f-a0da-5e2cbb1fb923.png)
