### ISSUE TITLE
Feature Request: More Information on Setup

### ISSUE THREAD

**Issue by SparkyMark66** [grocy/grocy#209]
Hi 
I Love the look of your project and want to have a copy running on my Raspberry Pi but I am struggling getting the it running. I have followed the instructions on Github but the only result I get is a blank web page. 
Any pointers would be much appreciated.

Regards

**Comment by berrnd** [comment]
I maybe repeat myself - it's just a pretty normal/basis PHP application, nothing special to setup.

Just check the webserver and PHP logs (or post them here, I'm happy to help), then the problem should be clear.

All the problems with blank pages in the past had to do with a wrong root directory (it should point to `/public`) or wrong PHP/SQlite versions (PHP 7.2 or higher is required, SQLite 3.8.3 or higher is required). All this is mentioned in README.

If you are not so familiar with maintaining a webserver, maybe [grocy-docker](https://github.com/grocy/grocy-docker) or [grocy-desktop](https://github.com/grocy/grocy-desktop) works better for you.

**Comment by berrnd** [comment]
Closing this for now, let me know if there's anything I can help with.
