### ISSUE TITLE
Feature Request: The label prints automatically after changing the expiration date

### ISSUE THREAD

**Issue by marcineqpol** [grocy/grocy#2092]
Hi,
I want to suggest a feature that allows you to automatically print a stock label when changing the expiration date of a stock entry. Changing the expiration date in Grocy occurs when we open something, move it to the freezer or defrost it.

I suggest adding a field in the product form called "Print label when EXP is change". When checkbox is active - Grocy prints the stock label after each operation that changes the date of a given stock entry.

**Comment by berrnd** [comment]
I've added this now like that - changelog excerpt:
- _Added a new option "Reprint stock entry label" on the stock entry edit page (will print the correspondind stock entry label on save)_
  - _This option will be automatically set when on changing the due date_

![grafik](https://user-images.githubusercontent.com/2161815/210840918-8aceb7c5-da8b-4345-a2b4-5c9a783a8892.png)

**Comment by berrnd** [comment]
Printing the label when the due date is changed automatically is not yet done - reopening this.

**Comment by berrnd** [comment]
Update changelog excerpt for this:

> - New product option "Auto reprint stock entry label"
>    - When enabled, auto-changing the due date of a stock entry (by opening/freezing/thawing and having corresponding default due days set) will reprint its label (only server side label printer WebHooks are supported)
>    - Defaults to disabled, so no changed behavior when not configured
>- Added a new option "Reprint stock entry label" on the stock entry edit page (will print the correspondind stock entry label on save)
>    - This option will be automatically set on changing the entry's due date
