### ISSUE TITLE
Feature Request: Group chore assignments

### ISSUE THREAD

**Issue by LastElf** [grocy/grocy#2095]
I have separate tasks set up for things in the same room (Clean Shower/Clean Toilet for example) that I would like to assign to many people but have the different chores linked to the same person for that week's assignment so that a room is done by one person.

To throw a spanner in the works, I don't know how this would work if chores have different schedules (All mine are daily interval x cause it needs to be done x after it was last done). This might be able to be tied into #339?

**Comment by berrnd** [comment]
The ability to assign multiple users to a single chore execution + everyone assigned needs to do it is tracked in #1415, if you mean that.

#1935 is about kind of the same, but the chore execution is done when anyone assigned did it.

#339 is about that Chore2 is only due after Chore1 is done, as mentioned there.

Beside that, grouping by a field (you can also add own fields by utilizing Userfields, ref #176) is possible in every table (top left corner table options), if it's maybe just about that.

Closing this as a duplicate.

**Comment by berrnd** [comment]
> If I have chore 1 and core 2 and I set them both to "assign to least done" they can get out of sync where two people can be assigned to two chores. I want them to stay synced that the same person is assigned for the same time, but still rotate the assigned person.

Well, this would be a completely new assignment, but just by having a practical look on the example _"Clean Shower/Clean Toilet"_: Why not simplify that and just have one chore "Clean Shower + Clean Toilet"? Would be practically no real difference I guess...

&nbsp;
> I think maybe I'm after assigning a parent chore and chores inherit the assignment until all the chores in there are completed to rotate to the next person.

Sounds even more complex for a IMHO simply problem, technically of course everything can be done.

**Comment by LastElf** [comment]
If there's different schedules of every week vs every month where only some of the steps need to be done and the schedule can rotate based on the longest interval. So shower once a month and while it's that month then _person_ is in charge of the other linked chores if they're more often.

I'm breaking the individual tasks down into smaller chunks like this to deal with tasks being overwhelming and making it this way is easier to mentally process, and to keep track of. So sub-chores is probably more the route I'm thinking saying this out loud. The "clean bathroom" chore could be weekly but only certain sub-chores show every 2/4 instances and it needs all sub-chores need to be completed to finish the parent chore which has the assignment attached to it.

**Comment by berrnd** [comment]
Whatever, I don't really get how overly complicating tracking-things really helps in reality, unless your household is a business - but that I understand things in a practical view doesn't matter that much.

So the outcome of this here is either that a new assigment type like "Use current assignment from other chore" is needed or the aformentioned parent/child chore approach.

The former one (new assigment type) is most probably technically a easy thing, the later one (parent/child chores) is most likely a lot more to do (and I doubt I would personally work on it at some time, but of course everyone can do it).

It makes only sense to track one topic per request, so if either of that is really needed and you don't think it's already somehow covered by the referenced other requests here, feel free to open separate requests for them with a at best short generic description of what is wanted (while the parent/child chore approach would need a couple of more thoughts how everything is expected to behave at the end).
