### ISSUE TITLE
Bug: recipes sort by calories namend sort: due score

### ISSUE THREAD

**Issue by Saturo78** [grocy/grocy#2096]
When sorting the recipes by calories the sort button is named sort: due score.

**Comment by berrnd** [comment]
On [/recipes](https://demo-prerelease.grocy.info/recipes) there is no column "calories", so where exactly is it possible to sort by that?

![grafik](https://user-images.githubusercontent.com/2161815/210760034-9930e698-414c-4217-8066-e729b7a601cd.png)

**Comment by Saturo78** [comment]
My fault again.
