### ISSUE TITLE
Bug: When adding new Item in HomeAssistant version

### ISSUE THREAD

**Issue by phoniclynx** [grocy/grocy#2101]
When adding a new item from a Purchase menu, I select:
Purchase -> Create or Assign Item box comes up -> I choose Add New Product or Add New Product prefill Barcode: 

It takes me to the create new product page. I fill in all the details on that screen and press "Save & Continue" and it presents me with a "Page Not Found" error and redirects me to the main page.

It doesn't add the product to the inventory or in stock but I can go in and add it manually. I expect it to go back to the Product Page as it does in the demo-prerelease version.

As far ask I know it is up to date, it reports version 3.3.2.

This seems to be an issue with the home assistant version of grocy, if I use grocy outside of HomeAssistant (ie go directly to it's port and don't use the side bar in Home Assistant) it seems to work as expected.

**Comment by berrnd** [comment]
> This seems to be an issue with the home assistant version of grocy, if I use grocy outside of HomeAssistant (ie go directly to it's port and don't use the side bar in Home Assistant) it seems to work as expected.

So clearly nothing to be tracked here, since not a problem of grocy.
