### ISSUE TITLE
Feauture Request: Total number of stock

### ISSUE THREAD

**Issue by Kelpermoon** [grocy/grocy#2103]
I was using grocy as I normally do and I realized I found it really annoying that the total number of items in stock wasn't displayed. It looks like there is just enough room for another box stating the number of total stock. I am frankly, a really inexperienced programmer and would really appreciate a total count, both in the stock overview and the master data screen would be enormously helpful as sometimes I have issues where items say they are added but they are not and a counter would help remedy this by allowing me to see the change in real time more or less. I have figured out whats causing this false positive and it is not the app's fault. Thanks in advanced!

**Comment by berrnd** [comment]
Please describe a little bit more detailed where something is not displayed and/or where you want to have something additionally - sorry, I don't get it.

&nbsp;
The total number of everything currently in stock is displayed on the top of [/stockoverview](https://demo-prerelease.grocy.info/stockoverview):
![grafik](https://user-images.githubusercontent.com/2161815/211264119-1493dfb9-6dd9-4950-a30a-5174e2fd19fb.png)

&nbsp;
For each and every row/product on [/stockoverview](https://demo-prerelease.grocy.info/stockoverview) and of course for every stock entry on [/stockentries](https://demo-prerelease.grocy.info/stockentries) the amounts are also displayed:
![grafik](https://user-images.githubusercontent.com/2161815/211264235-c470f622-bf2e-4e44-86df-d776ecc3f226.png)
![grafik](https://user-images.githubusercontent.com/2161815/211264288-94f83d13-563a-4d3d-af0f-41a95152f966.png)

&nbsp;
The same is the case for the productcard (displayed e.g. on [/consume](https://demo-prerelease.grocy.info/consume) and many more places):
![grafik](https://user-images.githubusercontent.com/2161815/211264387-21d9275f-dcb1-4d11-b9c1-6cec91af00a2.png)

**Comment by berrnd** [comment]
Closing, can be reopened when the necessary feedback about what here is wanted exactly is provided - I guess this doesn't refer to the grocy web frontend.
