### ISSUE TITLE
Objects API OFFSET has no effect without also providing LIMIT

### ISSUE THREAD

**Issue by CSTDev** [grocy/grocy#2105]
When calling the objects API with an offset you still get all the objects back.
e.g.: https://demo-prerelease.grocy.info/api/objects/stock_log returns 79 objects (today)
doing https://demo-prerelease.grocy.info/api/objects/stock_log?offset=78 still returns all 79 objects and not just the one

Interestingly if you add a limit it does work as expected.

To work around you can use the query parameter:  https://demo-prerelease.grocy.info/api/objects/stock_log?query[]=id>78

**Comment by berrnd** [comment]
All those query filter parameters are directly used as the corresponding SQL statement, `OFFSET` without `LIMIT` is not possible ([doc ref](https://sqlite.org/lang_select.html#the_limit_clause)).

I've optimized that providing `offset` without also providing `limit` now implicitly uses `-1` for `limit` - means it works now like you've expected it.
