### ISSUE TITLE
Bug: Price is set to 0, if not passed in API call stock/add

### ISSUE THREAD

**Issue by Forceu** [grocy/grocy#2106]
If adding a product via API call `api/stock/products/ID/add` without including the parameter `price`, the price of the entry is set to 0, which reduces the average price if previous entries had a price.
It would be probably a good idea to ignore entries with a price of 0 for the calculation of the average or the graph in the overview. Otherwise the average price or last price could be set if the parameter was not submitted.

Also it seems that the API schema in the documentation is out of date, as it does not include a `price` parameter.

To reproduce:

1. Create product
2. Add amount through the webinterface with a price
3. Add amount through API without a price

**Comment by berrnd** [comment]
> It would be probably a good idea to ignore entries with a price of 0 for the calculation of the average or the graph in the overview. 

I've fixed that (also for the product's last price and for `0` and `null` prices).

&nbsp;
> Also it seems that the API schema in the documentation is out of date, as it does not include a `price` parameter.

Can't reproduce that:

https://demo-prerelease.grocy.info/api#/Stock/post_stock_products__productId__add

![grafik](https://user-images.githubusercontent.com/2161815/212319296-c0f3a814-cc6d-4b52-84d3-338e46c965b9.png)

**Comment by Forceu** [comment]
Thank you for the quick fix, really appreciated! And you are right, apparently I missed that in the schema.
