### ISSUE TITLE
[Question]/objects/products api call

### ISSUE THREAD

**Issue by TheFuzz4** [grocy/grocy#211]
If I understand correctly the POST method of this call can be used to add items to the system?  I know you have a plugin for doing the external DB lookup but I'm just writing it into a script that I'm working on that will first check if the UPC exists in the system and then if not do the external lookup, gather the information from the external source and then add it back to Grocy.  

I think I'm correct in my assumption with this.  

I'm also looking to load it with just the bare minimum here {
            "name": name,
            "description": description,
            "barcode": upc,
            "location_id": 6
        }

I'm setting the location to a dummy one so that we will go back through after things are added and then update them accordingly.  The end goal here is of course once the initial load of the inventory is complete then this will be a moot point :). Thank you for this awesome app.

**Comment by TheFuzz4** [comment]
Going to close this out as I now know everything that is needed to add a missing item to the system. 

The full json for anyone wondering looks like this

{
            "name": name,
            "description":description,
            "barcode":upc,
            "location_id":6,
            "qu_id_purchase":0,
            "qu_id_stock":0,
            "qu_factor_purchase_to_stock":0
        }

You can update the values to your discretion but for me it was easier to just leave them blank or unset and then update them after the fact.

**Comment by berrnd** [comment]
Great that you found it out yourself, just in case:

The Swagger UI on [/api](https://demo-en.grocy.info/api) shows also the schema/fields right next to the (missing) example:

![grafik](https://user-images.githubusercontent.com/2161815/56636929-8ecee100-666a-11e9-95ac-11ac4e9ae03e.png)
