### ISSUE TITLE
Feature Request:  Text Highlighting

### ISSUE THREAD

**Issue by bloeki1** [grocy/grocy#2110]
Hi Bernd,

ist es möglich, dass man ein Highlighting des Textes aktiviert über den man gerade fährt? Zum Beispiel bei Stammdaten -> Produkte Sinnvoll. Ich trage gerade Produktgruppen nach. Durch das Highlighting wäre es einfacher zu sehen bei welchem Artikel man gerade ist.

**Comment by berrnd** [comment]
Hier wird für gewöhnlich Englisch gesprochen, damit auch jeder mitlesen kann:

Consider using [custom CSS/JS](https://github.com/grocy/grocy#adding-your-own-css-or-js-without-to-have-to-modify-the-application-itself) to customize everything to your personal likings:

Example snippet (for `data/custom_js.html`) to enable a "hover effect" for each and every table throughout grocy:
```html
<script>
$(".table").addClass("table-hover");
</script>
```

https://user-images.githubusercontent.com/2161815/212975519-96282da8-2b5c-49eb-93b9-661fc5e41529.mp4
