### ISSUE TITLE
Feature Request: Check in/check out for inventary

### ISSUE THREAD

**Issue by RoBra81** [grocy/grocy#2113]
Hello,

in our office we have different tools which can be used by everybody. They are actually in a cabinet and everybody who takes one of the tools or brings it back has to fill a list. So I thought about using Grocy for managing the tools. But the only way I found to use it was the transfer function and create a location for every user. I think that would work but the user experience would be no so good. It would be better if the user signs in with his account, selects function check in or check out, scans the barcode at the tool (qr code would be great) and tool will be checked in or out. If a tool is checked out it should be still in list but with user who borrowed it. Maybe internal different location can be used.

Would be great if you can implement this.

Thanks in advance
Ronny

**Comment by berrnd** [comment]
grocy is, and will always be, supposed and optimized for needs at home - any business use case is out of scope of this project.

**Comment by RoBra81** [comment]
In my opinion it's not only a business usecase: for example if my children want to share their Nintendo Switch Games with their friends it would be very usefull to have them in an inventary and check them out and "connect" them to the friend. At the moment I do not always know which friend has which game.

**Comment by berrnd** [comment]
grocy's stock feature is about managing food, nothing else.

**Comment by RoBra81** [comment]
Okay, sorry for asking

**Comment by BurtMC** [comment]
For me, this function would also be helpful. I often lend my tools to friends and like to lose track of who has what and what is at home.

**Comment by berrnd** [comment]
Maybe I was not clear enough above, so once again:

grocy's stock feature is about managing food and other household supplies.

grocy can't be and will never be the tool to manage business use cases or the world - a project needs a defined scope.

If the above mentioned way of creating locations per people / friends work for you, why not use it.

The better place in grocy to track non-food stuff is [/equipment](https://demo-prerelease.grocy.info/equipment).
Another simple way would be to simply add a Userfield there to track who you lend the corresponding thing, if you want to track that in grocy.

And if none of these two example ways of doing that inside grocy work for you, then the conclusion is most likely to do that outside of grocy.
