### ISSUE TITLE
Feature Request: Implement group messages/unacknowledged messages to use APRS services

### ISSUE THREAD

**Issue by fkaup** [grocy/grocy#2114]
Implementing the option for messages to not ask for acknowledgment (i.e. append {nnnn to each message) allows to use APRS group messages or services like group messages, ping, call sign look-up, or (self-)spotting (basic services defined on [aprs-is.net](http://aprs-is.net/APRSServices.aspx), [SOTA2APRS](https://www.sotaspots.co.uk/Aprs2Sota_Info.php), or [APSPOT](https://apspot.radio/)).

These services are partially not configured to send proper ACKs but instead return useful information in a separate message. The current APRSdroid implementation repeats each such message 6 times, needlessly increasing network load.

**Comment by berrnd** [comment]
Please elaborate a bit more what this is about and how this is related to which part of grocy and please keep the basics in mind: grocy is a (PHP) web application.

**Comment by berrnd** [comment]
I guess you hit the wrong issue tracker - closing this unless more information, what this should be, is provided.

**Comment by fkaup** [comment]
sorry, my mistake. should have gone here https://github.com/ge0rg/aprsdroid
