### ISSUE TITLE
Bug: mealplan internalShadowRecipe is null

### ISSUE THREAD

**Issue by fabiencharrasse** [grocy/grocy#2120]
![image](https://user-images.githubusercontent.com/86050782/216076653-e97b8a44-e103-47fd-b48c-936c78ea1be1.png)

![image](https://user-images.githubusercontent.com/86050782/216077662-f67bdd39-fb64-4f72-a00a-04cdff34e036.png)

After mass deleting ~200 recipes (successfully) through the REST API, I can no longer use the menu planning page because of the JS error in the screenshot. How can I do to unblock the situation? Thanks !

**Comment by berrnd** [comment]
The meal plan is technically based on internal recipes, which are created by triggers when adding/updating meal plan entries.

So a "dummy update" over all entries like `UPDATE meal_plan SET day = day` will most likely fix that.

I would probably just restore my backup in such a case.

This is however not a bug, you deleted stuff you shouldn't delete (for whatever reason) - grocy follows the [GIGO](https://en.wikipedia.org/wiki/Garbage_in,_garbage_out) principal and what happend is just that.

**Comment by fabiencharrasse** [comment]
`you deleted stuff you shouldn't delete (for whatever reason)`

Thanks for the solution. On the other hand, I don't think that "deleting recipes through the REST API" is something I shouldn't have done. If deleting recipes through the API breaks the operation of the meal plan page, then it is a bug. Or maybe I misunderstood something?

**Comment by berrnd** [comment]
The only question would be why you deleted those recipes you even haven't created yourself - just check what you do / delete and this won't be a problem in the future.

grocy is a (very) open system which allows you to do just like anything. And that includes that putting bullshit in (here deleting data) will get you bullshit out (here a broken meal plan page). If that general principal is not what you expect of such a software, maybe grocy is not the right one.

**Comment by berrnd** [comment]
> I guess it's the "internal recipe" you mentioned in your previous message. I assumed that I would only have my recipes with /objects/recipes. Was my mistake there?

Nowhere it's mentioned that this endpoint only returns "your" recipes (internal recipes are also recipes, but just not user-facing and user-created ones) and you obviously deleted those internal recipes which shouldn't be deleted - that's the (user side) problem and nothing to be "fixed" in the sense of the just mentioned general principal grocy is built on. Feel free to improve the documentation.

All the ["Generic entity interactions" API endpoints](https://demo-prerelease.grocy.info/api#/Generic%20entity%20interactions) are basically a kind of low level interface to the corresponding database tables. That's what I just meant by "grocy is a (very) open system". grocy's API (especially those mentioned endpoints) doesn't protect you from fucking up the entire database in any way.

**Comment by fabiencharrasse** [comment]
`Nowhere it's mentioned that this endpoint only returns "your" recipes (internal recipes are also recipes, but just not user-facing and user-created ones) and you obviously deleted those internal recipes which shouldn't be deleted`

I didn't intentionally delete something that I didn't know existed before opening this github topic (internal recipe). The point of improvement is perhaps to specify more clearly the existence of these internal recipes.
