### ISSUE TITLE
Feature Request: Print labels when cooking a recipe

### ISSUE THREAD

**Issue by marcineqpol** [grocy/grocy#2123]
It would be nice to have an option when I click "Consume all ingredients needed by this recipe" in the recipe view to have the labels printed (after proper preparation of the "produced" item by marking the printed labels and checking "Auto reprint label"). The number of labels may depend on the marking of the number of labels according to the product produced (single or in accordance with the number of portions).

I think it's a useful option when I cook for a few days and store the finished dish in the fridge.

**Comment by berrnd** [comment]
Notes to clarify this a bit more:

The product option "Auto reprint stock entry label" is part of a not yet released new feature (ref #2092)

This was about reprinting - so printing an existing, now updated, label again - means this option is not related to adding stock items (regardless of if by a purchase transaction or by consuming a "produces product"-recipe).

"Produces product" is using the exact same function (server side, [code ref](https://github.com/grocy/grocy/blob/efc7b999bb1ded27448a1c4ce64327c9d9bc53dc/services/RecipesService.php#L108)). However, it's curently enforcing to not print stock entry labels there - I guess you're refering to that detail.
