### ISSUE TITLE
Feature Request: Recipies and Plans Variants for a Household

### ISSUE THREAD

**Issue by tomdavidson** [grocy/grocy#2128]
Hello, many households, including mine, have at least one member with different dietary needs.  Recipes with the option for a variant could enable all kinds of powerful features needed for a heterogeneous household. For example:

- If Person A is diabetes the Recipe variant could remove a baked potato and add more broccoli.
- When there are numeric aggregates for user filed, Person A can track their sugars  and salaries separate from Person B based on the assigned variation.
- If Person C  is working an bulking up, the need to keep a targeted ratio of carbs and protein - would be different than everyone else in the household.
- When household members are assigned to the meal variations, the shopping list and analytics will be more accurate than if the variation is being done by the user outside of Grocy.

Few somewhat similar discussions:

- https://github.com/grocy/grocy/issues/1171
- https://www.reddit.com/r/grocy/comments/104xh7w/how_to_deal_with_diet/

**Comment by berrnd** [comment]
grocy is, and will ever be, a tool to manage your household, not your health or anything related to that.

However, a lot of stuff is possible by utilizing Userfields and such - also related regarding that: #413

**Comment by tomdavidson** [comment]
OK. 

This wasn't a feature request to manage health. It was about making the recipe and meal planning more reflective of reality.

**Comment by berrnd** [comment]
> It was about making the recipe and meal planning more reflective of reality.

Which is already covered in #1171, just without (that much) health aspects.

My aim for grocy is not to create a tool to manage everything and the world (it's not Excel) and a defined scope is required to not loose control of that.
