### ISSUE TITLE
Bug: Unit conversion price bug

### ISSUE THREAD

**Issue by Tagirijus** [grocy/grocy#2131]
# Issue

When I set up a product with different unit types for purchase or consume, using the _Inventory_ or _Purchase_ action for adding the product to the stock seem to ignore the price. When changed afterwardsa through the journal-editing, the price per unit gets calculated totally wrong (like the factor is wrongly used or so).

# Steps to reproduce

1. Add a new product (e.g. "Rice") which has _Kilogram_ as the unit type for _purchase_ _Gram_ for _consume_.
2. Use _Inventory_ or _Purchase_ to add the product to stock. During this action set a price per unit (in that case per kg).
3. Add maybe 1 kg for 4,87$.

# Test

I used your testing environment /persistent demo and added _Rice_ as a product already and tried to use the above mentioned steps:

https://test-7xazppn5ink76hdzfr36y7.demo-prerelease.grocy.info/products

By the way: if I add 1000 Grams per _Inventory_ the price gets x1000. When adding the product via _Purchase_, the price gets divided by 1000 in the recent release and gets totally ignored in the preview release, I guess.

Let me know if you need anything else!

**Comment by berrnd** [comment]
Not a bug and a duplicate-question of #1986 and #1270 - please check existing requests first before opening new ones.

Please read through #1986 and #1270 for the exact same example, I won't repeat the whole story here - the short version:
- The product's QU stock is the base for any amount and any value stored anywhere (here Grams)
- So 4.87 per kg / 1000 = 0.00487 per g
- This will be rounded based on the "Decimal places allowed for prices (input)" setting (default 2, same on your demo instance)
- So: ROUND(0.00487, 2) = 0

If you want to track such little prices, set the "Decimal places allowed for prices (input)" to an appropriate high value.

I did that on your demo instance, purchased another 1 kg Rice for 4.87 - and it just works.

**Comment by berrnd** [comment]
To complete this:

> By the way: if I add 1000 Grams per _Inventory_ the price gets x1000. When adding the product via _Purchase_, the price gets divided by 1000 in the recent release and gets totally ignored in the preview release, I guess.

I guess not:

On /purchase it was the rounding problem just mentioned above

On /inventory the price entered there is related to unit used. So when you use Grams, you need to enter the price per Gram. When using Kilogram, it's just the same as on /purchase and the conversion hint even transparently shows that:

![grafik](https://user-images.githubusercontent.com/2161815/217656767-5d5afb71-7e39-44df-b3e3-84108afdd961.png)

Please also keep in mind:

The preview version / current master branch is the current development state, stuff can be and sometimes is broken there and that's just expected. When using that as your "production version", please also note that database migrations and maybe more need to be handled manually.

**Comment by Tagirijus** [comment]
Hey berrnd. First of all: Thanks for your reply!


> Not a bug and a duplicate-question of https://github.com/grocy/grocy/issues/1986 and https://github.com/grocy/grocy/issues/1270 - please check existing requests first before opening new ones.

I do so! Yet even after reading the linked issues carefully I would never have even guessed that this could be 100% related to my issue here, since ...


> If you want to track such little prices (...)

... I actually do not want to track such little prices.



I somehow fear that there could be a more fundamental issue regarding the understanding of the principle you described and other users like me might understand. The _Decimal places allowed for prices (input)_ implies that the user would input these decimal places manually. When using your last mentioned example and add in kg on the other hand, it's the _backend_, which calculates in the set up decimal places - but the user inputs only two decimal places ("4,87"). And I guess this might be the "concept-misunderstanding", which lead to similar opened issues?

Let me explain in a more practical way, why I faced this issue after all: I want to keep my _rice_ amount in _gram_ in the stock. Yet when buying a new package it's often times a 1kg pack for this product with the price of e.g. 4,87$. So I **thought** that this is the use case for setting a _purchase unit_ versus the _stock unit_ and that the system would handle the rest automatically. I mean: it can do so, **if** the decimal places are set up correctly, as I know now. It's just me trying to understand what might have gone wrong here and maybe with other users understandings as well.

**Comment by Tagirijus** [comment]
Oh and: I tested it with the recent stable release **and** the production demo on your server! It's just that often times dev ask _"Did you test it with the latest dev-release?"_, why I only mentioned this.

**Comment by berrnd** [comment]
> Yet even after reading the linked issues carefully I would never have even guessed that this could be 100% related to my issue here

Well wow, #1270 mentions also exactly a "Rice" example, #1986 takes the "Sugar" example from the demo, which is just the same 1 kg / 1000 g example.

&nbsp;
> I mean: it can do so, if the decimal places are set up correctly, as I know now. It's just me trying to understand what might have gone wrong here and maybe with other users understandings as well.

So the conclusion is simply, as mentioned multiple times now for this topic: It just works when setting up the config options correctly / how you want it. So [GIGO](https://en.wikipedia.org/wiki/Garbage_in,_garbage_out), the base principal grocy is built on.

&nbsp;
> ... I actually do not want to track such little prices.

You want when you track Rice in Grams which per unit (Gram!) costs naturally pretty little.

&nbsp;
> I wonder how you would e.g. handle the product Flour in your demo instance. This also has the unit gram. If you buy 1000g of it, wouldn't it be mandatory to enable more than two decimal places so that you could add a price for it after all?

Of course that would be needed, as also just pointed out here now multiple times. And it's simply the same example as yours, just the product is not Rice but Flour. It's just kind of random demo data after all.

&nbsp;
> it's the backend, which calculates in the set up decimal places

It's acually not ([code ref](https://github.com/grocy/grocy/blob/91700e7dae4b35c32c2483ce0837a714df87a398/public/viewjs/purchase.js#L49)), but doesn't matter - the config option is taken into account.

**Comment by Tagirijus** [comment]
Please read my following comment solely as feedback. My intention is just to help, since I imagine that such user experience feedback might be helpful to a dev ... just maybe! In the end you are totally free to just ignore it after all. It's your project and seriously: I do not want you to change anything really. (=

<br>
<br>

> #1270 mentions also exactly a "Rice"

This issue also wrote something about _"£0.001/g"_ and never anything about _kg <> g_ conversion.


>  #1986 takes the "Sugar"

This issue als wrote _"If it is below 0.005"_ which immediately was "unimportant" to me and my understanding, since I was looking for _kg <> g_ conversion and at the "top end of my thinking" I just wanted to give kg a price. Also:


> You want when you track Rice in Grams

... intuitively I do not actually. I want to have a kg price and just want the **amount** be tracked in g in the stock. This does not mean that I _practically_ want to keep track of how much a gram costs. Technically you are right and I understand your point. I just want to describe how my (and maybe other) thinking flows might be (which probably led to such issues).


> multiple times now

I for sure understood the principle now. Still I just wanted to point out **why me and others** might have come up with this _issue_: simple misunderstanding and (in my eyes) **unintuitive** ui. It is totally okay, if it stays this way and you probably have just legit points. Yes, prices are calculated with two decimal places only in most consumer-situations anyway! It is still unintuitive **to me** that there **exists unit conversion** after all.

With this **I do not want to convince you to change something** or so! I really just wanted to try to explain and give some kind of feedback, why me (and maybe others) might have come to wrong conclusions when using your system.


> It's just kind of random demo data after all.

It just feels odd to me, when such a demo does not allow to track the price of such an example item (unless you change something in the settings).

<br>
<br>

Again: Please read it solely as some feedback (with good intention - I really do not sound offensive or so!). Either it might help you in any way or you are free to just ignore this whole feedback. It's your project after all. (;

<br>
<br>

> It's acually not (code ref), but doesn't matter

I as a (non professional dev) call things _backend_, if they are "behind the UI" or done in a way the user cannot see ... probably a wrong usage of this term then, hehe.

Thanks again for taking time commenting here still!

**Comment by berrnd** [comment]
We can continue this endlessly, but everything is said and everything works - so, as you said, I will ignore and and that here, since there is nothing to add more.

&nbsp;
> It is still unintuitive to me that there exists unit conversion after all.

You want to use different units for a product and wonder that conversion needs to happen, sorry, but again wow - kind of complex systems / processes requires some complexity in thinking on the user side, not only for grocy.

The frontend has conversion hints at many places to always transparently show what happens. Again your initial rice example with only two decimal places for price inputs configured:

![grafik](https://user-images.githubusercontent.com/2161815/217750451-85eba276-7722-4162-9422-c6048d1eee25.png)

So the user / you also ignored that at first, when this "problem" happens.

**Comment by Tagirijus** [comment]
Actually I did not ignore it. I was thinking that it might be a decimal issue after all! While thinking that in the "backend" the system would **still calculate it correctly**, though.

**Comment by Tagirijus** [comment]
Another quick though: maybe you simply could rename _"Decimal places allowed for prices (input)"_ to something like _"Decimal places for prices for internal calculations and user input"_ or so. I call this (intuitively) a UX problem.
