### ISSUE TITLE
Feature Request: Feature flag for amount tracking

### ISSUE THREAD

**Issue by mwestenthanner** [grocy/grocy#2132]
I have tried out Grocy multiple times in the past and still try to find a good workflow. My problem is that tracking stock with amounts is too time-consuming for me to integrate it in a busy household and I assume this might also be a problem for other users. Therefore, I suggest making amount tracking optional. If there's already a way, feel free to explain me how and close this ticket, I've been tinkering with it for a few days now and haven't found anything.

**Current situation**: To track stock, I have to fill in the amount field.

**Preferred situation**: I can set a flag that allows me to track only whether a product is in stock, no matter how much. This ideally also extends to recipes: I can see that the ingredient is in stock/on my shopping list, but don't have to juggle amounts.

I did try to emulate a boolean by setting all pre-selected amounts to e.g. 999 but that leads to multiple problems: 
- If I, by accident, add it twice, I have 1.998 in stock and have no way of noticing it right away.
- The 999 shows up in every text which is confusing to other household members. 
- When saving a recipe, I need to specify the amount of 999 manually because there's no default value.

Suggestion: A way to implement this would be to save a set amount (e.g. 999, just like the "Never expires" date) and implement a check so the amount doesn't surpass this set number. Then, remove the amount from the UI texts. For recipe creation, it would maybe be feasible just to skip the amount and use the variable amount field instead.

If there's anything I can do to help developing this, no problem. I'm not a PHP expert, but I have worked with it and I could at least supply translations/text where needed.

**Comment by berrnd** [comment]
Sorry, but no.

grocy's stock feature is of course entirely based on tracking amounts, making this optional would kind of require to rewrite the base (unless using dummy values everywhere, which is of course maybe and already possible - ref [custom JS/CSS](https://github.com/grocy/grocy#adding-your-own-css-or-js-without-to-have-to-modify-the-application-itself)).

&nbsp;
> My problem is that tracking stock with amounts is too time-consuming for me to integrate it in a busy household

Sounds for me personally that everything in your houshold just works pretty well without grocy - just like in the vast majority of all households around the world I guess.
