### ISSUE TITLE
Bug: When filtering for location in stock overview, stock amount always shows total, instead of filtered by location

### ISSUE THREAD

**Issue by thfrei** [grocy/grocy#2133]
Behavior:
- I have two locations in grocy setup.
- I have the same product in different locations.
- Often I want to see, how much of this product is at which location.
- Now when I filter Stock overview by location, it always shows me total amount. This is very confusing.
- What is additionally confusing, if I select a location, where there is none, then the product is NOT shown.

Expected behavior:
- See Amount at given location, not total amount.

Example:
- All Locations, amount 5 (correct)
  - ![image](https://user-images.githubusercontent.com/7283497/217840276-1067cc17-b9ca-40b4-b2a9-04af52233e96.png)
- Location 2 selected (HPZ) shows also 5, even though at that location it is only 3
  - ![image](https://user-images.githubusercontent.com/7283497/217840447-779b4b06-1924-4d5e-a55e-1b79ac269e38.png)
  - ![image](https://user-images.githubusercontent.com/7283497/217840607-44667bee-e3a8-46be-9e09-2cd0839f10a1.png)

Demo:
I also made a demo instance to reproduce the issue:
- https://test-fim3q6rwgkirk8mi1oj1sa.demo-prerelease.grocy.info/stockoverview
- Product in question: Yogurt
- Location Fridge, and "Prepper Fridge in Basement" :-)
- Video:
  - ![grocy inventory by location](https://user-images.githubusercontent.com/7283497/217842716-0ed041b2-4632-4655-98e9-5d0e405ee1b2.gif)

Previous issues:
- I only found the inventory reconcile feature. https://github.com/grocy/grocy/issues/1988

If you have any more questions, please let me know.

Thank you for your time! 🙏

**Comment by thfrei** [comment]
PS: I added another location for the demo purpose.

**Comment by thfrei** [comment]
PPS: I think, when consuming it should also use the product at the location in question.

**Comment by berrnd** [comment]
#1988 is completely unrelated, it's more #682.

Duplicate-question of #1531, #1259, https://www.reddit.com/r/grocy/comments/g44dm2 and https://www.reddit.com/r/grocy/comments/10mkuk7 (and probably more).

The story repeated in short words again here:
- [/stockentries](https://demo-prerelease.grocy.info/stockentries) shows each individual stock entry at each location.
- [/stockoverview](https://demo-prerelease.grocy.info/stockoverview) is the "high level overview" of the total amount in stock per product.

&nbsp;
> PPS: I think, when consuming it should also use the product at the location in question.
Please keep it to one topic per request.

[/consume](https://demo-prerelease.grocy.info/consume) validates the amount entered related to the selected location. Means if you have 5 at location A and 5 at location B it's not possible to consume 8 from location A.

**Comment by berrnd** [comment]
> What is additionally confusing, if I select a location, where there is none, then the product is NOT shown.

I don't get that point:
When you select a product group where the product doesn't match, it's also not shown.
When you search for "xyz" a product named "Lipton Ice Tea" is also not shown.
When a product currently is not in stock, it's also not shown, since the page is a stock overview, not a "product overview" (which is more [/products](https://demo-prerelease.grocy.info/products)).

**Comment by thfrei** [comment]
Thank you very much for your time and elaborate reply. I appreciate it!

**Comment by thfrei** [comment]
I see that it has already been requested, and discussed several times. Wonder how I missed it 🤷‍♂️ I'll make a suggestion PR for #682.

**Comment by jtitley** [comment]
> The story repeated in short words again here:
> 
> * [/stockentries](https://demo-prerelease.grocy.info/stockentries) shows each individual stock entry at each location.
> * [/stockoverview](https://demo-prerelease.grocy.info/stockoverview) is the "high level overview" of the total amount in stock per product.

Is there documentation on this? I thought the same way and couldn't figure out why the "filters don't work". I stumbled here and your explanation explained where to find stock level's at a particular location.

**Comment by berrnd** [comment]
> Is there documentation on this?

There is no documentation on anything (beside [README](https://github.com/grocy/grocy#readme) and [Changelog](https://grocy.info/changelog)).
