### ISSUE TITLE
Feature Request: No expiration date on product level

### ISSUE THREAD

**Issue by ktuulos** [grocy/grocy#2136]
There are some products, like certain fuels, which have no expiration date. Currently the "does not expire" has to be marked, when purchasing some product. It would be practical to be able to mark this already when defining the product.

**Comment by berrnd** [comment]
> It would be practical to be able to mark this already when defining the product.

The "Default due days" option set to `-1` makes that possible, also explained in the help tooltip:

![grafik](https://user-images.githubusercontent.com/2161815/219970712-cfbd68ec-0997-4193-9bf5-fa93c05fe28d.png)

**Comment by Beulu** [comment]
Hello,

I've tried this but expiration date doesn't change in stock list. It keeps expiration date set on creation and does not change to "Never"
