### ISSUE TITLE
Feature Request: notes (not attached to recipes...)

### ISSUE THREAD

**Issue by devkral** [grocy/grocy#2140]
It would be nice to have a notes tab to write down ideas.

I didn't find such a feature, is something like this built in and I missed it?
Is there an addon for this functionality?

**Comment by berrnd** [comment]
You can add arbitrary lists with any field you want by utilizing Userentities and Userfields.

Reference: #242 and #176.

Related requests: #2027, #1985

Demo examples:

https://demo-prerelease.grocy.info/userobjects/exampleuserentity

https://test-wtk3k5ezbwqt2ddxn5idea.demo-prerelease.grocy.info/userobjects/assets
