### ISSUE TITLE
Feature Request: ferdium recipe

### ISSUE THREAD

**Issue by devkral** [grocy/grocy#2141]
It would be nice to have an ferdium recipe for grocy.
Currently this is possible via the custom website recipe with urls opened in ferdium 

Note: as grocy is not a single page application, urls must be opened in ferdium

**Comment by devkral** [comment]
for info:
https://github.com/ferdium/ferdium-app

it is a tool to manage social media websites and co outside of the browser

**Comment by berrnd** [comment]
Similar to #406.

In any case, that's not a specific Feature Request for grocy, so closing this.

**Comment by devkral** [comment]
It was meant as a hint for a ferdium dev (or someone interested in), so he can add a recipe.

Can you reopen the issue even it is not a defect of grocy

**Comment by devkral** [comment]
I would propose the label: help-wanted

**Comment by berrnd** [comment]
> Can you reopen the issue even it is not a defect of grocy

No. This is the tracker for Bugs and Feature Requests _for grocy_ and this is is neither of that.
