### ISSUE TITLE
Feature Request: Shopping List - Assign Shops where to buy to every item

### ISSUE THREAD

**Issue by superpower10** [grocy/grocy#2145]
At moment I am using pon shopping list. It has the most features of every shopping list if seen.

E.g. you can assign the shops for each item where is available:
![1E73615A-67C2-403F-AD32-658A8C8C2DE1](https://user-images.githubusercontent.com/20533966/220314112-987f6a9e-4126-44aa-af59-ab628dd0fcf0.png)

And it gets sorted and put together by GPS (you set GPS for each store).

So if you I‘m at Lidl it looks like this:
![63EFF020-5A7A-4CCC-8556-316655FD008E](https://user-images.githubusercontent.com/20533966/220314486-aa83221d-d2ed-4f9a-abdf-259c5dce91b5.png)

If I am at Rewe both items appear unter Rewe.

So I would like to able to set store to each item and sorted by store when I‘m shopping.

**Comment by berrnd** [comment]
This is not the repository of any of the community contributed mobile apps.

**Comment by superpower10** [comment]
I know it‘s not. It‘s pon shopping list. It was just an example how it could look and what the advantages are.

**Comment by berrnd** [comment]
Oh, one year later - hi again.

Something like that would still be already possible in Grocy when you utilize Userfields accordingly. And beyond that, #1719 and #1357 are related existing Feature Requests on that topic.

See you in February 2025!
