### ISSUE TITLE
Feature Request: Shopping List - Properties for each item

### ISSUE THREAD

**Issue by superpower10** [grocy/grocy#2146]
It would like to have a properties for each item.

E.g. I would like to add Strawberry or Chocolate to item yogurt. And be able to add both to list. 

That way the amount of items needed are necessary.

It would look like this:
![AC757BF4-6DD0-48D6-BDE0-E914A94A1639](https://user-images.githubusercontent.com/20533966/220316921-dae71264-5028-4b0b-bf91-b26ba8ce226c.jpeg)

**Comment by berrnd** [comment]
This is not the repository of any of the community contributed mobile apps.
