### ISSUE TITLE
Bug: save button, in chore form doesn't work

### ISSUE THREAD

**Issue by felipemfa** [grocy/grocy#2148]
Version 3.3.2 (Homeassistant Addon)
When I try add a new task and click the "save" button, nothing happens. Monitoring in the chrome console, displays the error:
![image](https://user-images.githubusercontent.com/2481536/220622188-dda10f2c-7889-4a18-9b72-25ac81656cd1.png)

**Comment by berrnd** [comment]
Please provide a reproducible example as mentioned on the issue template - [persistent/private demo instances](https://www.reddit.com/r/grocy/comments/jwnk9b) are there for that.

I really can't guess all the details, you haven't mentioned anything about how the related chore is configured at all.

**Comment by felipemfa** [comment]
@berrnd thanks, in the demo instance the error does not happen, I opened new inssue on github of the addon (homeassistant)

**Comment by felipemfa** [comment]
@berrnd thanks, in the demo instance the error does not happen, I opened new inssue on github of the addon (homeassistant)
