### ISSUE TITLE
Feature Request: Barcode Scanner for shopping list

### ISSUE THREAD

**Issue by superpower10** [grocy/grocy#2149]
Use a barcode scanner every time a product is added to cart and therefore mark it as shopped.

**Comment by berrnd** [comment]
Would be cool if you can eloborate a little what you have and where exactly.

Is about that button and you want it not to click, but instead scan a barcode which then "clicks" that for the corresponding product on the list: (?)

![grafik](https://user-images.githubusercontent.com/2161815/221215291-e6e245ba-4106-4d90-b95e-945a564521a0.png)

If so, is that really faster (clicking one button) vs clicking another button to open the barcode scanner interface + scan a barcode? I kind of doubt it...

**Comment by berrnd** [comment]
Closing this unless feedback about what and where this should be exactly is provided.
