### ISSUE TITLE
Purchase page improvements

### ISSUE THREAD

**Issue by Tommie84** [grocy/grocy#215]
First of all, what a nice project. wanted to make this for years but was short in programming skills and time.
This project is exactly a clone for what i had in mind, and even a bit better. So now im sure i will never start creating that app haha.

my request --> autofill 'never expires' and purchase quantity in purchased screen.
why? --> we dont use price and expiry date.
why2? --> The WAF is non-stretchable and using a wall mounted tablet is on the edge. Making the clicking proces too long is over the edge :(

use case step description:
1. open purchase page
2. fill in product or barcode (autocomplete works nice).
3. hit 'ok'
* instead of asking for exp.date and quantity they will be autofilled with 'never expires' and '1'.
both can be autofilled on forehand also (just like location is preFilled).

Again, Thanks very much for the effort and time to make this wonderfull app!

**Comment by berrnd** [comment]
The best before date can already be prefilled - there is an option "Default best before days" per product.

I had the amount field prefilled with 1 in an early version, but it happened to myself often that I just hitted ENTER too early and booked a wrong purchase...

But I will add an option to prefill it with 1 optionally...
