### ISSUE TITLE
Feature Request: equipment multiple files

### ISSUE THREAD

**Issue by lodesmets** [grocy/grocy#2157]
It would be nice to be able to add multiple files to equipment.
Sometimes you want to store, receipt, manual, quick start, ... without creating different equipments / type of document

**Comment by lodesmets** [comment]
Nevermind, this can also be done with userfields

**Comment by berrnd** [comment]
> Nevermind, this can also be done with userfields

Exactly - a duplicate of #1290 - please check existing requests before opening new ones.

&nbsp;
Quoting myself:

> You can already add any field to any entity/object by using Userfields, see #683 and #176.
>
> Rendering Userfields of type "File" for equipment as tabs is already tracked in #978.
>
> Cross-referencing #978 here - it's now possible to add multiple files / PDFs to each equipment by using Userfields, [changelog v3.3.0 excerpt](https://grocy.info/changelog#v3.3.0):
>
> > - It's now possible to add multiple files (PDFs / manuals) to each equipment
> >    - Define as many Userfields for the entity `equipment` and use the type `File`
> >    - => Each of those File-Userfields will be shown as a separate tab on the equipment page
