### ISSUE TITLE
Feature Request: Import image from URL

### ISSUE THREAD

**Issue by TheFuzz4** [grocy/grocy#216]
Some external UPC providers provide a link to an image.  i.e. buycott is it possible to have something in the API that while the item is being added we can provide the image url and have the system pull that URL back and import the image?  I know during the product creation there is an option for a file name but in an external script there is no way for me to upload the image via the API.  Thanks.  BTW you forced me to learn python haha

**Comment by berrnd** [comment]
Sure, would be possible - but I think the field `picture_file_name` in the `Product` entity would be not the right place...

The `picture_file_name` is just the file name, the file itself need to be uploaded via a PUT request to `​/files​/{group}​/{fileName}` where `group` is `productpictures`...

**Comment by berrnd** [comment]
I'm going to close this for now, we have a file API, "importing" files by posting URLs would maybe cause/open other problems and can be done by the consumer of the API...
