### ISSUE TITLE
Categorize recipes

### ISSUE THREAD

**Issue by theQuikest** [grocy/grocy#2162]
Hi there, 
Very new user to Grocy, and thank you for all the work that has been done! 

Maybe it is something I'm just not seeing but is already there, but I would rally like to categorize my recipes, i.e. Chinese, Italian.  I just started a week or so ago and have 31 recipes do far. Not even close to the recipes I would like to enter. And already I'm scrolling through an "endless" list searching for that 'one recipe'. 

Sorry  in advance if this is a double request. Pretty new to GitHub too🤣🙈

**Comment by berrnd** [comment]
Question-duplicate of #324, #1126 and #1930 - please check existing requests before opening new ones.

That's already possible by utilizing Userfields, see https://github.com/grocy/grocy/issues/324#issuecomment-513479539.
