### ISSUE TITLE
Feature Request: weekly returnable Mealplan 

### ISSUE THREAD

**Issue by James-Bond00** [grocy/grocy#2163]
Is it possible to integrate a feature that the meal from this day ( or maybe the recipe) could automatically be copied for the same day in X weeks?
We have a meal plan with 90 different Meals in 15 weeks. After week 15 it starts from the beginning.
 It would be great, so could we use the recipe system in the meal plan from grocy

**Comment by berrnd** [comment]
Already covered by the following other Feature Requests - please check existing requests before opening new ones.

=> #310

=> #553

=> #1028
