### ISSUE TITLE
Bug: database error after migration

### ISSUE THREAD

**Issue by movvamrocks** [grocy/grocy#2166]
Migrated grocy to a new docker host. Old grocy v 2.7.1 and new one is the latest available.
Copied the /config folder from old container to a volume on new container host. volume has all data and config. 
I'm getting this database error. Appears as if the users table is missing.  Where can i check this table. 

Error source
/app/www/vendor/morris/lessql/src/LessQL/Database.php:108
Error message
SQLSTATE[HY000]: General error: 1 no such table: users

**Comment by berrnd** [comment]
Definitely not a bug and you posted that already there on the r/grocy subreddit some hours ago and I already answered there - of course I gladly do that once again here:

The error message leads to that simply database migrations did not run. So double check that this happened ([README ref](https://github.com/grocy/grocy#database-migrations), click the logo on he left upper edge).

If you copied around stuff manually, potentially a lot of other things could have gone wrong - I would personally have a look at the permissions of all files and folders and all the rest, but I don't have any experience with Docker at all.

Beside that (as [mentioned in README](https://github.com/grocy/grocy#questions--help--bug-reports--feature-requests)), this here is the tracker for reproducible Bugs and Feature Requests, not the place for getting help on individual setup problems.
