### ISSUE TITLE
API Issue

### ISSUE THREAD

**Issue by rourke750** [grocy/grocy#217]
When creating a new product using a Post request with endpoint /objects/product there isn't a way to specify some of the attributes such as location.

**Comment by berrnd** [comment]
What have you tried?

Everything below `/objects/{entity}` is just a exposed mapping of the corresponding database table row and there is also the schema reference integrated in Swagger UI:

![56636929-8ecee100-666a-11e9-95ac-11ac4e9ae03e](https://user-images.githubusercontent.com/2161815/56830467-b1c5e480-6866-11e9-8451-f3cfdf883e83.png)

So a POST request to `/objects/products` with this content successfully creates a product while assuming "testapiproduct2" does not already exist:
```
{
	"name": "testapiproduct2",
	"location_id": 2,
	"qu_id_purchase": 2,
	"qu_id_stock": 2,
	"qu_factor_purchase_to_stock": 1
}
```

**Comment by rourke750** [comment]
So I have been doing it that way but looking back I'm not sure what I was struggling with as it is right there.  Anyways thanks for the quick response!

**Comment by rourke750** [comment]
Oh looking again, how would I specify the product group from api.

**Comment by berrnd** [comment]
No problem.

The same way, expanding the example above:
```
{
	"name": "testapiproduct2",
	"location_id": 2,
	"qu_id_purchase": 2,
	"qu_id_stock": 2,
	"qu_factor_purchase_to_stock": 1,
	"product_group_id": 1
}
```

The API specification ([grocy.openapi.json](https://github.com/grocy/grocy/blob/master/grocy.openapi.json)) is incomplete for the `Product` schema, I*ve created issue #218 to track this...
