### ISSUE TITLE
Error after update grocy 2.6.2 ---> 3.3.2

### ISSUE THREAD

**Issue by chrismrq17** [grocy/grocy#2170]
Hello,

I have an error after updating grocy 2.6.2 with this roadmap: [https://github.com/grocy/grocy/issues/715](url) . 
The old version work right.

This is the error source:
```
/usr/local/www/grocy/services/DatabaseService.php:37
```

Error message:
```
SQLSTATE[HY000]: General error: 1 no such column: stock_due_soon_days
```

Stack trace:
```
#0 /usr/local/www/grocy/services/DatabaseService.php(37): PDO->exec()
#1 /usr/local/www/grocy/services/DatabaseMigrationService.php(71): Grocy\Services\DatabaseService->ExecuteDbStatement()
#2 /usr/local/www/grocy/services/DatabaseMigrationService.php(35): Grocy\Services\DatabaseMigrationService->ExecuteSqlMigrationWhenNeeded()
#3 /usr/local/www/grocy/controllers/SystemController.php(27): Grocy\Services\DatabaseMigrationService->MigrateDatabase()
#4 /usr/local/www/grocy/vendor/slim/slim/Slim/Handlers/Strategies/RequestResponse.php(38): Grocy\Controllers\SystemController->Root()
#5 /usr/local/www/grocy/vendor/slim/slim/Slim/Routing/Route.php(358): Slim\Handlers\Strategies\RequestResponse->__invoke()
#6 /usr/local/www/grocy/vendor/slim/slim/Slim/MiddlewareDispatcher.php(65): Slim\Routing\Route->handle()
#7 /usr/local/www/grocy/vendor/slim/slim/Slim/MiddlewareDispatcher.php(65): Slim\MiddlewareDispatcher->handle()
#8 /usr/local/www/grocy/vendor/slim/slim/Slim/Routing/Route.php(315): Slim\MiddlewareDispatcher->handle()
#9 /usr/local/www/grocy/vendor/slim/slim/Slim/Routing/RouteRunner.php(68): Slim\Routing\Route->run()
#10 /usr/local/www/grocy/middleware/LocaleMiddleware.php(16): Slim\Routing\RouteRunner->handle()
#11 /usr/local/www/grocy/vendor/slim/slim/Slim/MiddlewareDispatcher.php(269): Grocy\Middleware\LocaleMiddleware->__invoke()
#12 /usr/local/www/grocy/middleware/AuthMiddleware.php(31): Psr\Http\Server\RequestHandlerInterface@anonymous->handle()
#13 /usr/local/www/grocy/vendor/slim/slim/Slim/MiddlewareDispatcher.php(269): Grocy\Middleware\AuthMiddleware->__invoke()
#14 /usr/local/www/grocy/vendor/slim/slim/Slim/Middleware/RoutingMiddleware.php(45): Psr\Http\Server\RequestHandlerInterface@anonymous->handle()
#15 /usr/local/www/grocy/vendor/slim/slim/Slim/MiddlewareDispatcher.php(121): Slim\Middleware\RoutingMiddleware->process()
#16 /usr/local/www/grocy/vendor/slim/slim/Slim/Middleware/ErrorMiddleware.php(76): Psr\Http\Server\RequestHandlerInterface@anonymous->handle()
#17 /usr/local/www/grocy/vendor/slim/slim/Slim/MiddlewareDispatcher.php(121): Slim\Middleware\ErrorMiddleware->process()
#18 /usr/local/www/grocy/middleware/CorsMiddleware.php(30): Psr\Http\Server\RequestHandlerInterface@anonymous->handle()
#19 /usr/local/www/grocy/vendor/slim/slim/Slim/MiddlewareDispatcher.php(269): Grocy\Middleware\CorsMiddleware->__invoke()
#20 /usr/local/www/grocy/vendor/slim/slim/Slim/MiddlewareDispatcher.php(65): Psr\Http\Server\RequestHandlerInterface@anonymous->handle()
#21 /usr/local/www/grocy/vendor/slim/slim/Slim/App.php(199): Slim\MiddlewareDispatcher->handle()
#22 /usr/local/www/grocy/vendor/slim/slim/Slim/App.php(183): Slim\App->handle()
#23 /usr/local/www/grocy/app.php(106): Slim\App->run()
#24 /usr/local/www/grocy/public/index.php(45): require_once('/usr/local/www/...')
#25 {main}
```

System info:
```
{
    "grocy_version": {
        "Version": "3.3.2",
        "ReleaseDate": "2022-11-12"
    },
    "php_version": "8.1.16",
    "sqlite_version": "3.41.0",
    "os": "FreeBSD 13.1-RELEASE-p2 FreeBSD 13.1-RELEASE-p2 n245412-484f039b1d0 TRUENAS amd64",
    "client": "Mozilla\/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit\/537.36 (KHTML, like Gecko) Chrome\/111.0.0.0 Safari\/537.36"
}
```

Thanks for your help.
Regards

**Comment by berrnd** [comment]
Please note what's [mentioned on README](https://github.com/grocy/grocy#questions--help--bug-reports--feature-requests) and on the issue template - this here is the tracker for Feature Request and reproducible Bugs, not individual setup problems - this is obviously not a bug.

Triple check that database migrations did run after the update, README ref: https://github.com/grocy/grocy#database-migrations

&nbsp;
> `"php_version": "8.1.16"`

Since v3.1.0 only PHP 8.0 is supported, mentioned [on README](https://github.com/grocy/grocy/tree/v3.3.2#how-to-install) and [the changelog.](https://grocy.info/changelog#v3.1.0)

**Comment by berrnd** [comment]
> `SQLSTATE[HY000]: General error: 1 no such column: stock_due_soon_days`

Even more weird: There was never a column on any database table named `stock_due_soon_day`: https://github.com/grocy/grocy/search?q=stock_due_soon_day&type=code

**Comment by berrnd** [comment]
I've spent more time digging into this for you:

> `"sqlite_version": "3.41.0"`

SQLite [3.41.0 changelog](https://www.sqlite.org/releaselog/3_41_0.html) excerpt:
_6. Changes to the [CLI](https://www.sqlite.org/cli.html):_:
_[...]_
_f. The [double-quoted string misfeature](https://www.sqlite.org/quirks.html#dblquote) is now disabled by default for CLI builds._

What's used in a PHP-FPM environment is commonly not a "CLI build" (so still not a bug at any chance), but it would not be the first time that FreeBSD does strange things - so best guess: Replace the file `migrations/0115.sql` by [that one](https://raw.githubusercontent.com/grocy/grocy/3d01854fa118383aa15e19de1cb764ed0a3878f1/migrations/0115.sql).

**Comment by chrismrq17** [comment]
> Veuillez noter ce qui est [mentionné sur README](https://github.com/grocy/grocy#questions--help--bug-reports--feature-requests) et sur le modèle de problème - ceci est le suivi des demandes de fonctionnalités et des bogues reproductibles, pas des problèmes de configuration individuels - ce n'est évidemment pas un bogue.
> 
> Vérifiez trois fois que les migrations de base de données ont été exécutées après la mise à jour, README ref : https://github.com/grocy/grocy#database-migrations
> 
>  
> 
> > `"php_version": "8.1.16"`
> 
> Depuis la v3.1.0, seul PHP 8.0 est supporté, mentionné [dans le README](https://github.com/grocy/grocy/tree/v3.3.2#how-to-install) et [le changelog.](https://grocy.info/changelog#v3.1.0)

Bonjour,
Merci pour votre retour et votre réactivité. 
J'ai bien compris que ce n'est pas un bug, et je vous prie de bien vouloir m'excuser pour mes débuts sur github et grocy.
Je serai vigilant à l'avenir.
Effectivement, le readme indique bien la version PHP 8.0, Cela m'a échappé. 
Je n'avais pas trouvé le changelog. je vous remercie de m'avoir fourni le lien.
En lisant ce dernier, j'ai pris connaissance de l'excellent travail que vous effectuez. Bravo !

J'effectue les modifications nécessaires.
Un grand merci à vous.

**Comment by berrnd** [comment]
Please use English here, so that everyone can understand easily what you maybe have to add on that additionally.

**Comment by chrismrq17** [comment]
Hello,

Thank you so much for your help. It's work fine !!!
Have a good day,

Bests regards.
