### ISSUE TITLE
Bug: Plan from migrating away from dockerhub?

### ISSUE THREAD

**Issue by hydrargyrum** [grocy/grocy#2172]
Grocy's docker image is currently hosted on dockerhub, which has released a [new policy that might endanger your hosting there](https://blog.alexellis.io/docker-is-deleting-open-source-images/) ([see also](https://www.docker.com/blog/we-apologize-we-did-a-terrible-job-announcing-the-end-of-docker-free-teams/)). Do you have any plans for migrating hosting elsewhere?

**Comment by berrnd** [comment]
This is not the repository of any of the community contributed Docker images.

**Comment by hydrargyrum** [comment]
Created https://github.com/grocy/grocy-docker/issues/209
