### ISSUE TITLE
Feature Request: SPARQL / federated queries to define items in inventory?

### ISSUE THREAD

**Issue by photocyte** [grocy/grocy#2173]
Hi there,

I've looked into a `grocy` a few times, but I'm not a current user! What I'm looking to do is have laboratory inventory management via a web/mobile/desktop app, but define/ingest the characteristics of the individuals in the inventory via Wikidata, using individuals like this:
https://www.wikidata.org/wiki/Q117161609

I _think_ `grocy` could be shoe-horned into being used to track items in a laboratory environment rather than a home environment, but my interest would be to "build the schema in the open" and define the inventoried items in Wikidata, rather than defining them via a Grocy GUI or Grocy internal format.

Does this type of SPARQL support within `grocy` sound plausible?

**Comment by berrnd** [comment]
grocy is, and will always be, supposed and optimized for needs at home - any business use case is out of scope of this project.

**Comment by photocyte** [comment]
Got it! Technically it's a non-profit use case rather than a business use case ;)

**Comment by berrnd** [comment]
And a non-profit laboratory environment, even it it also has a fridge, is still not a home environment. A project needs goals and can't fit each and everyone and I can't imagine that there is no better software on this planet for laboratory needs.

**Comment by photocyte** [comment]
There is indeed quite a lot of software around laboratory inventory management, for example https://www.benchling.com/ . However it is usually priced (~$4k / seat / year) outside the realm of academics (non-profits), and therefore is only typically used by the for-profit scientific endeavors i.e. pharma. 

I've not found any inventory management software that can be federated i.e. uses RDF & SPARQL queries of external endpoints. I think that is a summary of what I'm looking for, although maybe it's the wrong solution. Will keep looking! 

But, could such a feature be reasonably implemented in the context of home ERP with `grocy`?  I'm also making wikidata items for consumer things I used at home (but not groceries per-se)
https://www.wikidata.org/wiki/Q117199766

**Comment by berrnd** [comment]
> But, could such a feature be reasonably implemented in the context of home ERP with grocy?

You've only mentioned laboratory and non-groceries use cases here, so by that: No.
