### ISSUE TITLE
Feature Request: Chained / Linked SKUs/Products

### ISSUE THREAD

**Issue by thystra** [grocy/grocy#2175]
Please implement chained or linked SKUs.  

For example, if I buy a variety pack of sodas, it may contain three different items, each with their own bar code.  I would like to be able to setup an item that when I purchase it (e.g. a case of soda, or cat food variety pack), it adds the defined items instead of the 'case' - e.g. 12 lime soda, 6 orange, 6 lemon or 3 tuna, 3 chicken, 3 beef flavor cat food.  The price per item is averaged from the total master SKU.

**Comment by berrnd** [comment]
Duplicate of #1421 - please check existing requests before opening new ones.
