### ISSUE TITLE
Bug: Creating products on mobile app does not properly reflect factors compared to website

### ISSUE THREAD

**Issue by thystra** [grocy/grocy#2176]
When creating a item on the mobile app, it does not property apply the multiplier (or ask for one).  for example, creating an item as a "pack" that represents "3 pounds", on the website I can adjust the factor.  On the app, I can only have 1 pack = 1 pound until I go back and edit the item on the website.

**Comment by berrnd** [comment]
This is not the repository of any of the community contributed mobile apps / integrations.
