### ISSUE TITLE
Feature Request: Toggleswitch Food / non-Food product

### ISSUE THREAD

**Issue by FelixM01** [grocy/grocy#2179]
what is your opinion on the addition of a food/no-food toggle in the product master data dialogue?

Background:
My thought was to inventory other consumables using Grocy. 
Examples: Toilet paper, washing up liquid, cleaning products, toothbrushes, etc.

It would be useful to be able to deactivate the food specific content directly when creating the item. 
In my mind, this would deactivate/remove the following fields:
-type of due date
-Standard due dates
-should not be frozen
-Energy

In addition, the wording "Deactivate inventory check for this ingredient" should be reconsidered, as these products are not ingredient but items.

Maybe someone else has an idea for aditionally needed fields

Greets
Felix

**Comment by berrnd** [comment]
My opinion on this is / TLDR:
Toilet paper needs no different handling - I, and I guess kind everyone else using grocy, already tracks that just like a normal product in grocy. The "Never overdue" due date [shorthand](https://github.com/grocy/grocy#input-shorthands-for-date-fields) was kind of invented for exactly that.

About the "food/no-food toggle": You can add any field you want to any entity (= products, chores, etc.) you want by utilizing Userfields (ref #176).

Going on with the toilet paper example:

&nbsp;
> In my mind, this would deactivate/remove the following fields:
> type of due date

Doesn't matter at all for products which are always never overdue.

&nbsp;
> Standard due dates

Setting this to `-1` will always prefill "never overdue" (as also mentioned on the help tooltip for that product option). That's exactly what you want for toilet paper and it's the same at the end as removing the field from a handling / input perspective.

&nbsp;
> should not be frozen

Don't set it for those products or not, does also not really matter.

&nbsp;
> Energy

Leave it at `0` or not, also doesn't matter.

&nbsp;
> In addition, the wording "Deactivate inventory check for this ingredient" should be reconsidered, as these products are not ingredient but items.

Don't set (or set it, once again: doesn't matter) and don't use it in recipes. Some others may use recipes to have an easy option to consume multiple products at once. And of course that can make practically also sense for non-food products / toilet paper. grocy is an open system not enforcing the way I or you think to use it is the best one.

&nbsp;
Have you practically tried tracking toilet paper or toothbrushes that way and really encountered practical problems on that?

&nbsp;
The better place for general usage qustions is the [r/grocy subreddit](https://www.reddit.com/r/grocy) as [mentioned in README](https://github.com/grocy/grocy#questions--help--bug-reports--feature-requests).
