### ISSUE TITLE
Bug: Database backup from Home Assistant to Grocy Linux instance

### ISSUE THREAD

**Issue by martin9511** [grocy/grocy#2183]
I installed the Grocy plugin in Home Assistant, there I backed up the database and wanted to install it in my new Grocy installation web server Apache (Ubuntu).

So far everything has worked in the web interface, but the Grocy app no longer always works, when I want to log in the app says no valid Grocy instance.

Where do I have to start, so that I can install the database of Home Assistant in another Grocy instance.

**Comment by berrnd** [comment]
And how is this meant to be a bug?

This is the tracker for reproducible Bugs and Feature Requests for grocy, not the place for general setup help and also not the repository of any of the community contributed apps / integrations, please notice what's mentioned on the issue template and in README: https://github.com/grocy/grocy#questions--help--bug-reports--feature-requests
