### ISSUE TITLE
The "product overview" is not viewable if the product isn't listed in the "stock overview" page

### ISSUE THREAD

**Issue by m4v** [grocy/grocy#2185]
Product overview has useful information but I haven't found a way to see it if the product isn't in the stock overview page, like if the product is out of stock.

How to reproduce:
1. In the demo page, go to the stock overview. 
2. Pick a product that has no minimum stock amount, for example cheese. 
3. Consume all cheese :mouse: 
4. Now there's no way to see the product overview of cheese until you buy more.

Possible solutions:
1.  Add "include out of stock" option for view all products in the stock overview page, or
2. Allow viewing the "product overview" from the master product data page or edit product page.

**Comment by berrnd** [comment]
It's a *stock* overview, not a product overview - [master data /products](https://demo-prerelease.grocy.info/products) lists all products.

**Comment by berrnd** [comment]
> Now there's no way to see the product overview of cheese until you buy more.

That's not really correct - any stock transaction page (so for currently out of stock products mainly /purchase and /inventory) also displays that after selecting a product. And also the shopping list.

**Comment by berrnd** [comment]
> Allow viewing the "product overview" from the master product data page or edit product page.

That's now done.

&nbsp;
Changelog excerpt:
> - When clicking the product name on the products list (master data) page, the product card will now be displayed (like on the stock overview page)

https://user-images.githubusercontent.com/2161815/231852980-5a51f201-6519-4a3f-829c-f2ca2cfb80b3.mp4
