### ISSUE TITLE
"Add as barcode to existing product" on purchase page broken.

### ISSUE THREAD

**Issue by clegett** [grocy/grocy#219]
Clicking the "Add as barcode to existing product" button from the purchase page or pressing `B` results in a 404.
It tries to access `myurl.com/grocy/grocy/purchase?addbarcodetoselection=12345` it should access `myurl.com/grocy/purchase?addbarcodetoselection=12345`. All other functions appear to function correctly.

**Comment by berrnd** [comment]
Seems to be a problem only when running grocy in a subdirectory, here:

https://github.com/grocy/grocy/blob/6442665f6c1aee3e3751bc0df573ef5e3873d89a/public/viewjs/components/productpicker.js#L172

Instead of the whole URL path of course only the configured `BASE_URL` should be used...

Works without problems on the [demo](https://demo-en.grocy.info/purchase).

**Comment by clegett** [comment]
I forgot to mention I'm on v2.3.0. 

Is there a simple fix to this? JS isn't one of my strong suits.

**Comment by berrnd** [comment]
I fixed it just now in https://github.com/grocy/grocy/commit/b6b8c76d3aa80fe0b691b253d166ac14796b415a, will be part of the next release.

When you want to have it now, replace the two changed files in your grocy directory - I also attached them as a ZIP while keeping the directory structure.

[grocy_patch_issue219.zip](https://github.com/grocy/grocy/files/3123905/grocy_patch_issue219.zip)

**Comment by lukebo** [comment]
I just installed your patch on an instance where the webserver directly points to the public folder. The Base-URL is / but i need to set Setting('DISABLE_URL_REWRITING', true); to function properly.

My grocy instance points to http://grocy.xxxxxx.xxxxxxxx/index.php/index.php/purchase?addbarcodetoselection=243423423424234

When i remove one index.php, it works...

**Comment by berrnd** [comment]
I fixed it again, find attached the updated patch.

[grocy_patch_issue219-2.zip](https://github.com/grocy/grocy/files/3139661/grocy_patch_issue219-2.zip)

**Comment by lukebo** [comment]
Yes, that works (for me). Thank you very much. Good work!
