### ISSUE TITLE
Bug: set the price 1.52€ for 160grams but it says 160grams = 1.60€

### ISSUE THREAD

**Issue by languagemaniac** [grocy/grocy#2197]
Hi, I inputed a price of 1.52€ total price for a 160grams product but when I purchase it it says

160grams = 1.60€ 

It's adding 0.08€ to the price, I think it's a bug.

It's not much of a difference but it's not the price I setted.

**Comment by berrnd** [comment]
You haven't provided any details, so I once again do some guesswork and gladly take the time to provide just another example:

Short summary once again: grocy stores any price related to the product's QU stock. In regards to the decimal places used, your [stock settings](https://demo-prerelease.grocy.info/stocksettings#group-stock_decimal_places_prices_input) come into account.

Persistent/private demo instance: https://test-s0w9erl5i1f3iw8hws5zda.demo-prerelease.grocy.info

Product: Flour
Product stock QU: Gram
Default purchase QU: Pack (160 Grams are 1 Pack)

Example with Stock setting "Decimal places allowed for prices (input)" = 2 (Default):
Purchase of a Pack for 1.52 = 1.52 / 160 = 0.0095 = 0.01 rounded per Gram (← that's stored)
Pack price based on 0.01 per Gram = 0.01 * 160 = 1.60 per Pack
=> What you (probably) got, mathematically correct.

Example with Stock setting "Decimal places allowed for prices (input)" = 8:
Purchase of a Pack for 1.52 = 1.52 / 160 = 0.0095 per Gram (← that's stored)
Pack price based on 0.0095 per Gram = 0.0084 * 160 = 1.52 per Pack
=> Works as you (probably) expected it, still mathematically correct.

![grafik](https://user-images.githubusercontent.com/2161815/234111135-03163e07-a019-499f-ad2a-27cb94fdde1a.png)

&nbsp;
> I think it's a bug.

Conclusion: Definitely not a bug, simply set your stock setting "Decimal places allowed for prices (input)" reasonable high to make tracking little prices work.

Would also be super cool if you search just a little for related reports beforehand, you would (hopefully) have found one of just today and more:
https://github.com/grocy/grocy/issues/2196#issuecomment-1520086738
#1986
#1270

**Comment by languagemaniac** [comment]
> You haven't provided any details, so I once again do some guesswork and gladly take the time to provide just another example:
> 
> Short summary once again: grocy stores any price related to the product's QU stock. In regards to the decimal places used, your [stock settings](https://demo-prerelease.grocy.info/stocksettings#group-stock_decimal_places_prices_input) comes into account.
> 
> Persistent/private demo instance: https://test-s0w9erl5i1f3iw8hws5zda.demo-prerelease.grocy.info
> 
> Product: Flour
> Product stock QU: Gram
> Default purchase QU: Pack (160 Grams are 1 Pack)
> 
> Example with Stock setting "Decimal places allowed for prices (input)" = 2 (Default):
> Purchase of a Pack for 1.52 = 1.52 / 160 = 0.0095 = 0.01 rounded per Gram (← that's stored)
> Pack price based on 0.01 per Gram = 0.01 * 160 = 1.60 per Pack
> => What you (probably) got, mathematically correct.
> 
> Example with Stock setting "Decimal places allowed for prices (input)" = 4:
> Purchase of a Pack for 1.52 = 1.52 / 160 = 0.0095 per Gram (← that's stored)
> Pack price based on 0.0095 per Gram = 0.0095 * 160 = 1.52 per Pack
> => Works as you (probably) expected it, still mathematically correct.
> 
> ![grafik](https://user-images.githubusercontent.com/2161815/234111135-03163e07-a019-499f-ad2a-27cb94fdde1a.png)
> 
> &nbsp;
> > I think it's a bug.
> 
> Conclusion: Definitely not a bug, simply set your stock setting "Decimal places allowed for prices (input)" reasonable high to make tracking little prices work.
> 
> Would also be super cool if you search just a little for related reports beforehand, you would (hopefully) have found one of just today and more:
> https://github.com/grocy/grocy/issues/2196#issuecomment-1520086738
> #1986
> #1270

Thanks, sorry I usually check before reporting but I am a bit sleepy and I didn't think right before posting.

Thank you for taking the time to provide such a detailed explanation. Just installed grocy some days ago and still learning how it all works.
