### ISSUE TITLE
Bug: Unable to generate a rest client using openapi cli

### ISSUE THREAD

**Issue by mikedolx** [grocy/grocy#2198]
Hi,

i have tried to generate a rest client for dotnet using the [openapi cli](https://github.com/OpenAPITools/openapi-generator-cli). So far it worked quite well with other REST-API's but sadly not with Grocy.
I ran the tool using the following command prompt:
```shell
./openapi-generator-cli generate -g csharp-netcore --library restsharp -o ~/ws/connectors/dotnetgrocy -i https://raw.githubusercontent.com/grocy/grocy/master/grocy.openapi.json
```

As you can see, i am using the openapi.json from this repository. After running the prompt i get the following error:

```java
Exception in thread "main" org.openapitools.codegen.SpecValidationException: There were issues with the specification. The option can be disabled via validateSpec (Maven/Gradle) or --skip-validate-spec (CLI).
 | Error count: 7, Warning count: 11
Errors: 
	-attribute paths.'/objects/{entity}'(get).parameters.[entity].schemas.#/components/schemas/ExposedEntity_NotIncludingNotListable is missing
	-attribute paths.'/objects/{entity}/{objectId}'(delete).parameters.[entity].schemas.#/components/schemas/ExposedEntity_NotIncludingNotDeletable is missing
	-attribute paths.'/userfields/{entity}/{objectId}'(put).parameters.[entity].schemas.#/components/schemas/ExposedEntity_IncludingUserEntities_NotIncludingNotEditable is missing
	-attribute paths.'/userfields/{entity}/{objectId}'(get).parameters.[entity].schemas.#/components/schemas/ExposedEntity_IncludingUserEntities is missing
	-attribute paths.'/objects/{entity}/{objectId}'(put).parameters.[entity].schemas.#/components/schemas/ExposedEntity_NotIncludingNotEditable is missing
	-attribute paths.'/objects/{entity}'(post).parameters.[entity].schemas.#/components/schemas/ExposedEntity_NotIncludingNotEditable is missing
	-attribute paths.'/objects/{entity}/{objectId}'(get).parameters.[entity].schemas.#/components/schemas/ExposedEntity_NotIncludingNotListable is missing
Warnings: 
	-attribute paths.'/objects/{entity}'(get).parameters.[entity].schemas.#/components/schemas/ExposedEntity_NotIncludingNotListable is missing
	-attribute paths.'/objects/{entity}/{objectId}'(delete).parameters.[entity].schemas.#/components/schemas/ExposedEntity_NotIncludingNotDeletable is missing
	-attribute paths.'/userfields/{entity}/{objectId}'(put).parameters.[entity].schemas.#/components/schemas/ExposedEntity_IncludingUserEntities_NotIncludingNotEditable is missing
	-attribute paths.'/userfields/{entity}/{objectId}'(get).parameters.[entity].schemas.#/components/schemas/ExposedEntity_IncludingUserEntities is missing
	-attribute paths.'/objects/{entity}/{objectId}'(put).parameters.[entity].schemas.#/components/schemas/ExposedEntity_NotIncludingNotEditable is missing
	-attribute paths.'/objects/{entity}'(post).parameters.[entity].schemas.#/components/schemas/ExposedEntity_NotIncludingNotEditable is missing
	-attribute paths.'/objects/{entity}/{objectId}'(get).parameters.[entity].schemas.#/components/schemas/ExposedEntity_NotIncludingNotListable is missing

	at org.openapitools.codegen.config.CodegenConfigurator.toContext(CodegenConfigurator.java:620)
	at org.openapitools.codegen.config.CodegenConfigurator.toClientOptInput(CodegenConfigurator.java:647)
	at org.openapitools.codegen.cmd.Generate.execute(Generate.java:479)
	at org.openapitools.codegen.cmd.OpenApiGeneratorCommand.run(OpenApiGeneratorCommand.java:32)
	at org.openapitools.codegen.OpenAPIGenerator.main(OpenAPIGenerator.java:66)
```

I found [this issue](https://github.com/grocy/grocy/issues/1457), but somehow couldn't adopt the workaround for my solution.

Any idea what could be wrong?

Thanks and BR;
Michael

**Comment by berrnd** [comment]
This is really not the place to get support for any other tools like `openapi-generator-cl`.

[`grocy.openapi.json`](https://github.com/grocy/grocy/blob/master/grocy.openapi.json) is there to feed [/api](https://demo-prerelease.grocy.info/api) and not really something else.

And as mentioned in your referenced other thread, this file is not taken as-is, contains placeholders and is served "resolved" at the API endpoint [`openapi/specification`](https://demo-prerelease.grocy.info/api/openapi/specification).

&nbsp;
> Any idea what could be wrong?

Not knowing the mentioned tool, so guessing - as just pointed out and also pretty clearly mentioned on [the other thread](https://github.com/grocy/grocy/issues/1457#issuecomment-824899190):
[`grocy.openapi.json`](https://github.com/grocy/grocy/blob/master/grocy.openapi.json) doesn't contain the schema `ExposedEntity_NotIncludingNotListable` and all others mentioned in the "Errors" section of the provided output above, [`openapi/specification`](https://demo-prerelease.grocy.info/api/openapi/specification) does - maybe try using that.

**Comment by mikedolx** [comment]
Hi @berrnd ,

thanks for your reply. I tried using the `/api/openapi/specification` endpoint, and got some code generated by the tool!! Thank for the hint!
