### ISSUE TITLE
Feature Request: display product pictures in Product list and Inventory list

### ISSUE THREAD

**Issue by cniry** [grocy/grocy#2199]
It would be nice to see product pictures in Product list and Inventory list.

**Comment by berrnd** [comment]
Already possible - check the top right corner table options to show/hide columns:

![grafik](https://user-images.githubusercontent.com/2161815/234903265-e71b4820-5c63-4ca1-85ea-a477ceaa2348.png)

![grafik](https://user-images.githubusercontent.com/2161815/234903390-04a17373-901d-46f2-a50f-c35860162ad4.png)

**Comment by cniry** [comment]
Wow, thank you very much :)
