### ISSUE TITLE
Feature Request: Execute chore as

### ISSUE THREAD

**Issue by Zulgrib** [grocy/grocy#2203]
Hi,

It would be useful to allow admin account to execute chore as another users.
For example, you see someone doing a chore but this person forgot to mark the chore as achieved, the system will still point to this user as the next one to do the chore due to that and marking as done the next day would make the next due too late.

**Comment by berrnd** [comment]
That's already possible (since ever) on [/choretracking](https://demo-prerelease.grocy.info/choretracking) - mind the `Done by` option.
