### ISSUE TITLE
Feature Request: Dynamic Meal Plan start date

### ISSUE THREAD

**Issue by sinisterpuppy** [grocy/grocy#2205]
Hello,

(I've had a look and haven't seen this posted before)

Loving Grocy, the only thing that's really frustrating me is I'd love the meal plan to have "today" as the far left day.

At the moment you're set on the 7 days per the config

If you're start day Monday and today is Sunday you have to keep scrolling forward the week to see what's planned.

Many thanks

**Comment by berrnd** [comment]
Changelog excerpt for this:

> - The `config.php` setting `MEAL_PLAN_FIRST_DAY_OF_WEEK` can now be set to `-1` to dynamically start the meal plan week on _today_
