### ISSUE TITLE
Feature Request: Table for another currencies

### ISSUE THREAD

**Issue by albarreto** [grocy/grocy#2209]
The system only works with US Dollar (US$).
It will be interesting customize currencies like Euro, brazillian real (R$)

**Comment by berrnd** [comment]
> The system only works with US Dollar (US$).

That's not correct, don't know how you came to that conclusion.

There is a `config.php` option for that:

https://github.com/grocy/grocy/blob/8bdb74a8e084232c87db5e9b312f220e576b06cf/config-dist.php#L39-L43

That's also a duplicate-question of #1449, #486, #465 and many other threads on the [r/grocy subreddit](https://www.reddit.com/r/grocy) - which is also the better place for general help and questions as [mentioned in README](https://github.com/grocy/grocy#questions--help--bug-reports--feature-requests).

**Comment by Likqez** [comment]
Would be great to add the currency support into the UI, since e.g. hass.io Users cant change that config easily.

**Comment by berrnd** [comment]
> hass.io Users cant change that config easily.

Off-topic here and more a problem of the HA Add-On then.

I don't use HA at all but the add-on exposes multiple `config.php` options, including `CURRENCY`, maybe check that and better ask on their forum, where I guess more people with clue about all that are around.

https://github.com/hassio-addons/addon-grocy/blob/d126ea53a80027eaa8f39f3414d2f39eac7e2e63/grocy/DOCS.md?plain=1#L40
