### ISSUE TITLE
Feature proposal: Printable barcode stickers

### ISSUE THREAD

**Issue by lukebo** [grocy/grocy#221]
Hi Berrnd,
first of all, thankyou for this really great tool, which i use to keep track of everything inside our freezers.
Most of the contents are "non grocerystore-goods", frozen from our own garden, selfmade stuff and so on. Consequently, there is no barcode on them, just (at least sometimes) a handwritten note.
I would thus like to propose to implement a feature (e.g. within the product registration process) where one can define a certain (random) code and a best before date. Then, on can print all that on some sticker (e.g. with a labelprinter). Useful information on the sticker would be... ID-barcode, Name, Best before date and maybe the freezing date.
Keep up the good work!

**Comment by berrnd** [comment]
Great idea, will be added... :)

**Comment by lukebo** [comment]
Maybe this feature could also be benefitial for all the batteries (and maybe even the kitchen devices).

**Comment by berrnd** [comment]
Sure, let's call this "grocycode", a unique ID for products/batteries/chores/equipment/(users) - everything which is selected by a dropdown can have a grocycode and then can be scanned as an alternative to be typed/selected from the dropdown (just like for products as of now).

Just not sure about printing with a label printer - just thinking of a page which displays all codes to be printed or an optional CSV export for now...

Would then also be possible to not only generate barcodes, but also those fancy QRCodes with an embedded logo like that: :D

![grafik](https://user-images.githubusercontent.com/2161815/56914614-d1eae300-6ab4-11e9-90f4-3cb598492e79.png)

**Comment by shady2k** [comment]
When are you planning to add this feature?

**Comment by berrnd** [comment]
I plan nothing about when to add what... ;D

If there are news about this, you will find it here.

**Comment by shady2k** [comment]
Ok, thanks

**Comment by mistressofjellyfish** [comment]
Hey berrnd,

I would like to spend some time implementing this!

However, I am not the biggest fan of QR codes, especially not when embedding logos. This requires the labels to be huge; and my use-case would be to have a simple cheap-ish (~60€) thermo label printer next to the fridge, which ideally should print a code, and some basic info onto a stick-on-label which I can throw on my tupperware.

Barcode readers that can read 2D codes like QR Codes can also read DataMatrix, which doesn't really care about alignment and uses less space. 2D readers are about 45€ used on ebay or about 90ish € new (according to geizhals). Or they can be read with a smartphone camera as is with 1D barcodes.

So my proposed implementation looks like this:

- devise a format to be encoded – something simple like `grocy:stockentry:<id>` would probably suffice.
- have a page that displays the label for one given stockentry.
- have a page to quick-consume the stockentry by scanning its associated code.
- have the ability to configure a webhook to make a label printer print the code.

So in the end, you're free to print however you'd like. Because of the millions of label formats and printers, I guess the most simple (for now) implementation (for me) would be an ugly python script that talks to the printer.

Any input on this would be great, I'll start working on this as soon as my hardware arrives.

**Comment by berrnd** [comment]
Sounds great, feel free to start anything you like about that, everything is much appreciated. :)

The idea about the QR-Code + logo was just a rough thought, maybe something else works practically better or at the end some library for creating the codes is used which can handle different formats and we can provide all (or some) to be used...

This was not specifically about stock entries (that IMHO already works pretty good with "Scan mode" and when using the "Default consume rule"), but would be of course also a great start...

**Comment by mistressofjellyfish** [comment]
> This was not specifically about stock entries (that IMHO already works pretty good with "Scan mode" and when using the "Default consume rule"), but would be of course also a great start...

Yes. As a first step, I'll just get the printing working so it works with the scan mode on the consume page. We can worry about the rest later.

As for which codes to use - Datamatrix can be tiny; tiny enough to stick them to AAA batteries. I'll happily build it in a way that other codes can be implemented by someone else without too much hassle.

Re: grocycode (aka what gets encoded into the code), I came up with the following simple spec.

1. Each grocycode begins with the hardcoded Identifier `grcy`
2. Each part of the grocycode is separated by a single double colon `:`
3. The Basic structure of a grocycode is `grcy:<Identifer>:<Id>[:<ident specific further information>]`
4. Identifers must match the regular expression `[a-z]+` (i.e. must only contain lowercase ascii letters, minimum length 1)
  a. Known Identifiers: `p`- Product, `b` - Battery, `c` - Chore

Implementation wise, I'd just make [the existing barcode tester](https://github.com/grocy/grocy/blob/master/services/StockService.php#L640) grocycode-aware so it can handle product-grocycodes (and worry about everything else later). The rest should be done by the existing consume page already.

I don't have any good idea where to integrate the label printing though. On a per-product base, this is easily done on the stock page (triple dots menu). However, to include best-before dates, a stockentry needs to be selected. For now, I'll probably include it in the dots menu of the stock entry overview, but this getting there feels cumbersome to me (4 clicks).

**Comment by berrnd** [comment]
About the code-spec: Sounds good, don't know if we need so much abbreviations, one letter for the entity will at least become difficult for Userobjects.

If you want to attach a barcode really to every stock entry/item, then there is probably no better place than the stock entries page (or a separate page to faster print multiple ones, or print it at the corresponding events, so on purchase & inventory).

**Comment by mistressofjellyfish** [comment]
Well, bigger identifiers need more space in the barcode. For example, a product grocycode could look like this:

![barcode (2)](https://user-images.githubusercontent.com/7026857/120933034-9e013380-c6f8-11eb-8d46-5fd8896b11f9.gif)

This is 32 by 32 pixels, and could probably be read if printed to 5 by 5 mm – even if I would probably start at an area size about 10x10mm and size down from there where needed.

> If you want to attach a barcode really to every stock entry/item, then there is probably no better place than the stock entries page (or a separate page to faster print multiple ones, or print it at the corresponding events, so on purchase & inventory).
In the future, yes, absolutely! Still I think the UI could use some improvement on the stock overview page, but that is totally out of scope here.

**Comment by budda85** [comment]
Is it possible to export the Codes and discription from like 10 product? So that i can print it with an ink-jet printer on an HERMA label like this: https://www.herma.de/buero-zuhause/produkt/haushalts-tiefkuehletiketten-12906/
