### ISSUE TITLE
Feature Request: open_basedir

### ISSUE THREAD

**Issue by mokkin** [grocy/grocy#2216]
In newer PHP environments open_basedir is enabled by default as a security layer:
https://www.php.net/manual/de/ini.core.php#ini.open-basedir

If not available some (shared) hosters are blocking the usage of grocy in the default setting:
```
Warning: file_exists(): open_basedir restriction in effect. File(/var/www/vhosts/hosting123456.abcde.netcup.net/httpdocs/grocy.example.de/public/../embedded.txt) is not within the allowed path(s): (/var/www/vhosts/hosting123456.abcde.netcup.net/httpdocs/grocy.example.de/public/:/tmp/:/var/lib/php/sessions:/var/www/vhosts/hosting123456.abcde.netcup.net/tmp) in /var/www/vhosts/hosting123456.abcde.netcup.net/httpdocs/grocy.example.de/public/index.php on line 5

Warning: require_once(): open_basedir restriction in effect. File(/var/www/vhosts/hosting123456.abcde.netcup.net/httpdocs/grocy.example.de/helpers/PrerequisiteChecker.php) is not within the allowed path(s): (/var/www/vhosts/hosting123456.abcde.netcup.net/httpdocs/grocy.example.de/public/:/tmp/:/var/lib/php/sessions:/var/www/vhosts/hosting123456.abcde.netcup.net/tmp) in /var/www/vhosts/hosting123456.abcde.netcup.net/httpdocs/grocy.example.de/public/index.php on line 34

Warning: require_once(/var/www/vhosts/hosting123456.abcde.netcup.net/httpdocs/grocy.example.de/helpers/PrerequisiteChecker.php): Failed to open stream: Operation not permitted in /var/www/vhosts/hosting123456.abcde.netcup.net/httpdocs/grocy.example.de/public/index.php on line 34

Fatal error: Uncaught Error: Failed opening required '/var/www/vhosts/hosting123456.abcde.netcup.net/httpdocs/grocy.example.de/public/../helpers/PrerequisiteChecker.php' (include_path='.:/usr/local/php81/share/php81') in /var/www/vhosts/hosting123456.abcde.netcup.net/httpdocs/grocy.example.de/public/index.php:34 Stack trace: #0 {main} thrown in /var/www/vhosts/hosting123456.abcde.netcup.net/httpdocs/grocy.example.de/public/index.php on line 34
``` 

It would be cool if grocy could support this.

**Comment by berrnd** [comment]
And what exactly should grocy do about this?
Both mentioned are part of / placed in your grocy application directory, like each and every other file...

From life experience shared web hosting is always the hardest pain you can have due to (sometimes bullshity) restrictions, outdated runtime environments and everything else - avoiding that reduces headaches a lot.

**Comment by berrnd** [comment]
Or maybe it's just about a configuration thing on your, resp. the webhoster's, side:

https://forum.netcup.de/webhosting-und-webdevelopment/php-mysql/p169494-wordpress-php-open-basedir-fehler/#post169494

**Comment by mokkin** [comment]
Thanks for the hint and yes, that's possible and I already have a working grocy instance.
But I thought it could be a good security feature to have this working by default.

**Comment by berrnd** [comment]
When you explain what the big security issue here is and what exactly needs to be fixed, then I will do something about and this can reopened.

Just again: Each in every file which is loaded anywhere is of course part of your grocy application directory, grocy doesn't load any files outside of it. (!)

Nothing special to workaround Netcup peculiarities, or of any other shared webhoster, will be every implemented.

**Comment by berrnd** [comment]
> outdated runtime environments

Off-topic here, but yeah: #1939
