### ISSUE TITLE
Feature Request: localized shared iCal 

### ISSUE THREAD

**Issue by albarreto** [grocy/grocy#2217]
My Grocy is in brazillian portuguese (updated .po files on docker container). 
I shared my Grocy Calendar in my Google Agenda, but it isn't localized to my language.

PS: I searched about this issue. Nothing found ;-)

**Comment by berrnd** [comment]
Everything is localized based on the user language - can be easily verified by using the demo instance: https://pt-br.demo-prerelease.grocy.info/api/calendar/ical

So can only be a configuration issue and that's not tracked here.
