### ISSUE TITLE
Feature Request: Date format in combobox

### ISSUE THREAD

**Issue by albarreto** [grocy/grocy#2220]
In the Consumption section, the combo related to the checkbox 'Use a specific stock item' shows 'Amount: <number>; Due on <date>; Bought on <date>', where <date> is in YYYY-MM-DD format.

It would be important to allow customization of the date format to the region standard (MM/DD/YYYY or DD/MM/YYYY)

**Comment by berrnd** [comment]
Duplicate of #1348.
