### ISSUE TITLE
Feature Request: Parent product grid icon

### ISSUE THREAD

**Issue by albarreto** [grocy/grocy#2221]
It is sometimes confusing to differentiate parent products and their children in the grid.
A simple icon in the table would be interesting to differentiate items that have children.

**Comment by berrnd** [comment]
Optimizing parent/child display is already tracked in #449.

That here is (once again) very minor and also just personal taste how to display details - use [custom JS/CSS](https://github.com/grocy/grocy#adding-your-own-css-or-js-without-to-have-to-modify-the-application-itself) to customize everything to your very own very end.
