### ISSUE TITLE
Feature Request: Separate unit for product card (Last/average price + price history chart)

### ISSUE THREAD

**Issue by zunami** [grocy/grocy#2225]
_**Edit by @berrnd:**_
_This is about being able to have a separate unit (product option) where the productcard prices are then related to (currently that's the product's "Default quantity unit purchase", ref #1743)._

----

i tried to reproduce my problem. only of course it shows me the german units. i hope it is understandable when i explain it.
_Packung = Pack
Kilogramm = Kilogram_

It's about the "product overview" (see screenshot).
_Example: Tomatoes_
you can buy tomatoes 250 gram 400 gram 500 gram.
now the price information regarding package price is of course not very helpful. That is why my suggestion with the unit price. But if you change the view to the "Quantity unit" (kg) can of course improve.
- Last price kg
- Average price kg
- Price history kg

The price histroy would then be much more meaningful on the graph if it was on kg. Then one could compare the market price better.

**My settings for the test article:**
Quantity unit stock: kg kilogram
Default quantity unit purchase: pack
QU conversions: you can see in the screenshot

I hope I was able to explain it well enough.

![Product overview](https://github.com/grocy/grocy/assets/4697822/ba6a9e4f-c652-4ebe-b4e7-887eecbdb884)
![QU conversions](https://github.com/grocy/grocy/assets/4697822/8900c210-d302-4ccb-bdb3-bfe7ad58099a)
![Stock entries](https://github.com/grocy/grocy/assets/4697822/55dd9fb4-20e6-4b1c-9c3f-f57c0cf9cf97)

**Comment by zunami** [comment]
ok, there seems to be a conceptual problem that we are talking past.

I assume that _"Quantity unit stock"_ is the main unit.
**BUT**
Default "quantity unit purchase" is supposed to be used for calculation BUT in the info it says _"This is the default quantity unit used when adding this product to the shopping list"_.
What now shopping list unit or price calculation unit?

Do you understand now why I never get there?

![for shopping list](https://github.com/grocy/grocy/assets/4697822/6d49f3ff-4bf4-45e3-b20f-f552ad1e1854)

**Comment by berrnd** [comment]
Keine Ahnung ob die Sprache das Problem ist, deswegen halt mal auf Deutsch:

> What now shopping list unit or price calculation unit?

Ich hab doch 3 Mal hier bzw. in deinen anderen off-topic Kommentaren in #1859 erwähnt, dass "QU stock" das Ding ist, wo sich alle Mengen und Preise darauf beziehen. Alles überall wird auf Basis von dieser Einheit gespeichert. Eingabe/Ausgabe in allen anderen Einheiten wird auf Basis der Faktoren realisiert, nur fürs Frontend, das Backend interessiert das nicht.

&nbsp;
> Do you understand now why I never get there?

Nö, denn, auch nicht zum ersten Mal hier: Auf der oben verlinkten privaten Demoinstanz + im Screenvideo gezeigt - exakt dein Beispiel, ist es doch absolut möglich jede konfigurierte Einheit überall zu verwenden + kg im Chart und allen Angaben auf der Productcard zu haben, wenn man eben "Default quantity unit stock" auf kg setzt.

Hast das gemacht? Gehts nicht? Kann nicht sein, mach doch einfach ein nachvollziehbares Beispiel auf einer privaten Demo Instanz. Dafür sind die da und dann redet man auch weniger aneinander vorbei, wenn man ein praktisches Beispiel zur Hand hat. 

Oder hättest gerne eine weitere separate Einheit "Default quantity unit for Chart/Productcard" wo dann explizit diese genannten Stellen sich darauf beziehen? Könnte man natürlich machen, ändert praktisch nicht wirklich was und Produktoptionen haben wir definitiv noch nicht genug.

**Comment by zunami** [comment]
Ich glaube auch wir reden aneinander vorbei und es schaukelt sich hoch.

Also mir ist klar was du mir mit dem Video und dem Demozeigen möchtest . Ich habe alles mit deinen werten genau durchgearbeitet nur von den Stammdaten / Produkte werden die falschen Einheiten abgerufen.

Mir geht es um die Produktübersicht und ich möchte aussagekräftige "unit price" (Grundpreis).

Produktübersicht Werte beziehen sich auf
Stock amount **⇨** Quantity unit stock
Last Price **⇨** Default quantity unit purchase
Average price **⇨** Default quantity unit purchase
Price history **⇨** Default quantity unit purchase 

ABER laut deiner Beschreibung ist _" Default quantity unit purchase "_ und laut Info _"This is the default quantity unit used when adding this product to the shopping list"_
Eine Standardeinheit zum Hinzufügen zur Einkaufsliste finde ich auch richtig! Nur dieses Feld auch zu verwenden, um als Statistikeinheiten ist falsch. Denn das kann natürlich zur Einkaufsliste und zur Statistik / History einfach nicht passen. z. B. Tomaten -> Einkaufsliste Packungen, aber in der Statistik / History ist Packung natürlich hinderlich.
Somit JA ich wäre dafür für eine separate Einheitauswahl "Default quantity unit for Chart/Productcard" oder ich hätte es benannt in "unit price" = Grundpreis

**Comment by berrnd** [comment]
> nur von den Stammdaten / Produkte werden die falschen Einheiten abgerufen

Wenns nicht die "Default quantity unit purchase" ist, wärs ein Fehler - kann ich mir nicht vorstellen. Wenns die falschen Werte sind, könnens nur falsche Umrechnungsfaktoren sein, da kann ich nix für, Bullshit in = Bullshit out. Kann aber immer noch nix genaues sagen, weil ein praktisch nachvollziehbares Beispiel (private Demoinstanzen sind immer noch genau dafür da) hast immer noch nicht gebracht.

&nbsp;
> geht es um die Produktübersicht und ich möchte aussagekräftige "unit price" (Grundpreis).

Wirklich one last time: Kannst schon jetzt haben, wenn endlich mal die "Default quantity unit purchase" auf kg setzt (für dieses Beispiel).

Und weiter one last time, weil ich habe immer noch den Eindruck du hast es nicht einmal ausprobiert und/oder verstehst es tatsächlich nicht: Es ist eine DEFAULT Einheit, NICHT die ONLY Einheit und es ist weiterhin möglich, jede Einheit (mit direkter oder indirekter Beziehung zum Produkt) ÜBERALL zu verwenden.

&nbsp;
> Nur dieses Feld auch zu verwenden, um als Statistikeinheiten ist falsch.

Falsch liegt im Auge des Betrachters und ist quasi persönlicher Geschmack und du bist der erste, der das so sieht. Im Gegenteil, das genau so zu machen haben sich mehrere gewünscht (ref #1743) und deswegen wurde es so gemacht.

&nbsp;
> ich wäre dafür für eine separate Einheitauswahl "Default quantity unit for Chart/Productcard"

Cool, das in den Titel dieses Requests und es wäre von vornherein klar gewesen. Aber so gehts natürlich auch und macht mehr Spaß. Wir tracken genau das also nun hier (und ich überlege noch ob das grocy allgemein braucht und baue das dann oder auch nicht, irgendwann) und schließen den Rest hiermit hier ab, weil bringt offensichtlich nix.

**Comment by berrnd** [comment]
Changelog excerpt for this:

- _New product option "Quantity unit for prices"_
  - _Prices are now shown related to this quantity unit (instead of per "Default quantity unit purchase") on the product card, price history chart, stock overiew and stock entries page_
  - _Defaults to the product's "Default quantity unit purchase" (so no changed behavior when not configured)_
