### ISSUE TITLE
Feature Request: Translate to pt-br

### ISSUE THREAD

**Issue by felipemfa** [grocy/grocy#223]
Do you have plans for Portuguese (BR) translation? If not, is it possible to help you?

**Comment by berrnd** [comment]
Sorry, I cannot do it beside using machine translation which probably will not result in any good...

But as stated in [README](https://github.com/grocy/grocy#localization), localizations are managed on Transifex, so it's fairly easy to do the translations.

`pt_BR` was already started by someone and is currently 38 % complete, I include (and provide a demo for) localizations which are at least 90 % complete.

So feel free to complete the translations:
=> https://www.transifex.com/grocy/grocy/language/pt_BR/
