### ISSUE TITLE
Feature Request: Treatment of return pledge

### ISSUE THREAD

**Issue by strausmann** [grocy/grocy#2249]
At the purchase and consumption it should be possible to manage the treatment of return of deposit. How much deposit has a product, possibly also a quantity of units has an additional deposit.

Example drinks in deposit bottles and a box.

The deposit in turn must be stored somewhere, so you need a storage location for it again.

Return of deposit when making a purchase.

**Comment by berrnd** [comment]
Duplicate of #1356 - please check existing requests before opening new ones.

**Comment by strausmann** [comment]
Oh sorry, I had been looking for pledge. I didn't get anything displayed for that.
