### ISSUE TITLE
[Suggestion] Price, Quantity and product creation

### ISSUE THREAD

**Issue by SupremeSports** [grocy/grocy#225]
Two problems here

1a- It would be great to be able to set the item price and quantity while creating a new product
1b- It would be great to set a purchase date. Right now I'm transferring my inventory from my excel, I'll lose all my purchase dates :(

2- It would be great if we could set product price to more specific values (0.0993$) as when we purchase in bulk, it often gets to 4 or 5 decimals.

Thank you

this is my first day into Grocy, trying to use this to replace my Excel spreadsheet :P

**Comment by berrnd** [comment]
So I think the currently intended way to transfer an existing inventory list would be to use [inventory](https://demo-en.grocy.info/inventory).

1a
That's possible when booking a purchase, so sure, this field should also be on the inventory page

1b
That's possible when you add your stock through inventory, please don't mix up product master data (when you create a product) with the stock data - best before dates only "live" in stock...

2
Ok, would be no issue to just increase the decimal places. But we would then node some "dynamic rounding" as it would be ugly to show prices with 4 decimal places where normally the last two would just show zeros...

**So TODO for this issue:**
- Add price field on the inventory page
- Increase price fields decimal places to 4 while adding some "dynamic rounding" (only show the third and fourth decimal place of a price when it's not zero) for all places where prices are displayed
