### ISSUE TITLE
Feature Request: change in product no. count (in title on stock overview)

### ISSUE THREAD

**Issue by ARWebmaster** [grocy/grocy#2250]
Currently, all products are counted from master data -> products are counted and shown in the title.

But when an item is a parent product, 'never show on overview' is selected, and it's own stock is disabled, either count the parent product as a product or count all child products as seperate products.

Example:

- Parent: Chocolate (Never show on oveview selected, no own stock, accumalate sub products)
- Child 1: white chocolate
- Child 2: Dark chocolate
- Child 3 Chocolate with hazelnut

Currently this is shown in the title of the stock overview as: "Stock overview 4 Products, € 0,00 total value"

This situation it should read either 
- "Stock overview 1 Product, € 0,00 total value"  - refering/counting only the parent product
or
- "Stock overview 3 Products, € 0,00 total value"  - refering/counting all child products

as it either is 1 product 'Chocolate' or 3 products '1 x White chocolate', '1 x Dark chocolate', and '1 x Chocolate with hazelnut'.

It's maybe just sementics, but I find it confusing. My preference has the first option '1 product', but this maybe be different for others or even per product (for instance 'Tomato paste of three brands' is all tomato paste (this is what my preference is actually based on), but with chocolate you might want the second option as you might use one type for different things. Therefor a select option 'count parent'/'count children' might be an extra enhancement.

This also might be related to #449

**Comment by berrnd** [comment]
Your first example makes sense (= excluding products with "Never show on stock overview" set <= this will be changed), the other not.

&nbsp;
> This also might be related to https://github.com/grocy/grocy/issues/449

Rather completely unrelated, this here is about /stockoverview total product counting, #449 is about to have a collapsible row list of parent/child products.
