### ISSUE TITLE
Bug: trading/transactiontimezone goes to GMT while docker environment said Asia/Shanghai 

### ISSUE THREAD

**Issue by xiaoyuesansui** [grocy/grocy#2253]
hello 

as the subj mentioned ,time can be perfectly listed on the top of  web page while all transaction time are goes GMT

**Comment by berrnd** [comment]
None of the community contributed Docker images are maintained here, so don't get the purpose of reporting this as a Bug here.

Doing a little search beforehand would also be cool. It's mentioned in #214, all the referenced other threads there and also multiple threads on the [r/grocy subreddit](https://www.reddit.com/r/grocy) that, to make time related stuff in Grocy work now (and most likely forever), it's required that you're client, server (OS level) and PHP (php.ini) timezone settings need to match (which is practically just the normal case in any self hosted environment, unless you really live in multiple timezones). So simply triple check that.
