### ISSUE TITLE
Feature Request: Shuffle Recipes for Meal Plan

### ISSUE THREAD

**Issue by cranky-coder** [grocy/grocy#2257]
I love the meal plan and recipes.  I was thinking that it would be interesting to shuffle the recipes.  

Simple Example:  Breakfast, Lunch, Dinner
You configure the various sections for Meal Planning.  (Breakfast, Lunch, Dinner) 
On the meals you can add which "sections" this meal fits.  My family likes to do an egg scramble bowl for dinner some times.  So that recipe could be tagged with both "breakfast" and "dinner" or whatever. 

When you sit down to do your meal planning for the week.  You could have a button on the "meal plan" page that just says shuffle.  

It will then pick random recipe for each day in each section.  Then you can go through and adjust, but it gives a baseline for the meal planning for the week.

**Comment by berrnd** [comment]
Already covered by the following other Feature Requests - please check existing requests before opening new ones.

=> #310
=> #553
=> #1028

(And #1894)
