### ISSUE TITLE
Feature Request: API endpoint for recipes_pos_resolved

### ISSUE THREAD

**Issue by dominiczedler** [grocy/grocy#2258]
Hey Bernd, is it possible to open the `recipes_pos_resolved` table for use via API (read-only of course)?

As I have seen in existing SQL migrations, the check for presence of ingredient amount in stock is quite complex. Using the currently existing endpoints would mean a lot of error-prone work in third-party apps, although it would actually be faster via this table (like `quantity_unit_conversions_resolved` which is also great in your upcoming version). Do you think this is a good idea or not?

Thanks for your work!

**Comment by berrnd** [comment]
Sure, there's nothing wrong with that.

Can also be done with all other "helper views", most of the logic is done there. So far I only exposed them via the API when I needed them myself for the frontend I guess...
