### ISSUE TITLE
Night mode colors

### ISSUE THREAD

**Issue by SupremeSports** [grocy/grocy#226]
Night mode colors are not good. The text is unreadable
![Untitled](https://user-images.githubusercontent.com/13887820/57006553-8c064b80-6b96-11e9-8f59-703d352b18df.jpg)

**Comment by berrnd** [comment]
The night mode theme was originally done by @BlizzWave, everything is in a [single CSS file](https://github.com/grocy/grocy/blob/master/public/css/grocy_night_mode.css).

Feel free to tweak it to fit better.

**Comment by SupremeSports** [comment]
Cool, thanks :)

**Comment by BlizzWave** [comment]
Yes, this has been on my todo list for a while. Night mode was just something that I created (together with @berrnd) to not make the kitchen glow up at night.
Will tune this so it's better to read. 
There's also places where night mode needs to be updated for because of all the enhancements.

**Comment by SupremeSports** [comment]
Would be great to have it in settings and we could adjust the colors as we want

**Comment by berrnd** [comment]
Feel free to propose a way how this would be possible, there are n colors defined for n100 selectors which most of them are not from "us", but from used components, mainly [Bootstrap](https://getbootstrap.com/)...

That what stylesheets are made for, you could even a[dd your own rules without having to modify the included files](https://github.com/grocy/grocy#adding-your-own-css-or-js-without-to-have-to-modify-the-application-itself)...

**Comment by berrnd** [comment]
Done via #272 by @BlizzWave.
