### ISSUE TITLE
Feature Request: Get last chore execution id

### ISSUE THREAD

**Issue by malorezzanzo64** [grocy/grocy#2260]
I'd like to have the option to get the last chore execution id in order to undo the last chore via API

**Comment by berrnd** [comment]
The frontend uses the API for everything and that's possible there, so it's already possible via the API and to find out how stuff works, the easiest thing is to have a practical look (your favorite Browsers's developer tools) what the frontend does on the corresponding action.

Tracking a chore execution is done via the endpoint [`/chores/{choreId}/execute`](https://demo-prerelease.grocy.info/api#/Chores/post_chores__choreId__execute). It returns a `chore_log`-entity object, throw it's `id` into the endpoint [`/chores/executions/{executionId}/undo`](https://demo-prerelease.grocy.info/api#/Chores/post_chores_executions__executionId__undo) to undo that execution.

Use the endpoint [`/objects/chores_log`](https://demo-prerelease.grocy.info/api#/Generic%20entity%20interactions/get_objects__entity_) to get each and every execution. It returns a list of `chore_log`-entity objects, throw any `id` of a not yet undone execution into the endpoint [`/chores/executions/{executionId}/undo`](https://demo-prerelease.grocy.info/api#/Chores/post_chores_executions__executionId__undo) to undo that execution.
