### ISSUE TITLE
Feature Request: 

### ISSUE THREAD

**Issue by albarreto** [grocy/grocy#2267]
Apply Sort Number also to product groups.
This ordering would be used in the Shopping List.
Thus, it will no longer be necessary to put numbers in the group title

![Captura de tela de 2023-07-05 16-41-08](https://github.com/grocy/grocy/assets/6339761/9fdb6c19-d74c-417b-b768-f5067f00b11d)
![Captura de tela de 2023-07-05 16-41-19](https://github.com/grocy/grocy/assets/6339761/0b23c692-aebc-4590-b2ea-fb652cc78be6)
![Captura de tela de 2023-07-05 16-45-01](https://github.com/grocy/grocy/assets/6339761/cc3912a8-1af0-421f-a042-b9efaa6a7995)

**Comment by berrnd** [comment]
Nobody forces you to put numbers in any titles, it's just one example use case for product groups.

Any table can be sorted by any column since ever.

That's not possible for the meal (it's not a table), that's why that a "Sort number" was introduced for meal plan sections.

**Comment by berrnd** [comment]
Please use proper titles and don't start another shitshow like we had in May, thanks.

**Comment by berrnd** [comment]
> sort the product groups according to their location in supermarkets.

I also see. You haven't checked, once again, existing requests before opening new ones: That's a duplicate of #1719.

And you can already get that (partly, not as a different configuration per store) by simply using number prefixes as the demo showcases. Simple, effective, used for years without problems.
