### ISSUE TITLE
Feature Request: New Task/Chore button on Calendar

### ISSUE THREAD

**Issue by albarreto** [grocy/grocy#2268]
In Calendar, add shortcut button for New Task and New Chore.
Another suggestion is to have the same way of inserting a new task or chore by clicking on the day number, where this new task/chore would already be pre-filled with it, similar Meal Plan

![Captura de tela de 2023-07-05 16-50-34](https://github.com/grocy/grocy/assets/6339761/0be8ee40-854e-4466-a610-76e3da5aa959)

**Comment by berrnd** [comment]
Similar to #824, this won't be added for consistency reasons.

[/calendar](https://demo.grocy.info/calendar) is the central (read only) hub to show anything throughout Grocy on a calendar view, not limited to chores and tasks.
