### ISSUE TITLE
Stock quantity to zero are removed from the list

### ISSUE THREAD

**Issue by SupremeSports** [grocy/grocy#227]
Maybe there's a reason for it, but I can't understand. 

I would like to be able to verify my stock overview and still view those with zero remaining

Thanks

**Comment by berrnd** [comment]
The [stock overview page](https://demo-en.grocy.info/stockoverview) shows only products which are currently in stock and those which are not currently in stock, but have minimum stock amount defined (with blue background).

When you just want to see all products, that's what the [master data/products page](https://demo-en.grocy.info/products) is listing...

**Comment by SupremeSports** [comment]
Ok, thanks :)
