### ISSUE TITLE
Bug: Grocy seems to be fully translated into Estonian but it is not available in the UI

### ISSUE THREAD

**Issue by aylamz** [grocy/grocy#2270]
Grocy seems to be fully translated into Estonian on Transifex but it is not available in UI: User Settings > Language

**Comment by berrnd** [comment]
[README excerpt](https://github.com/grocy/grocy#localization):
_Also any translation which once reached a completion level of 70 % ([strings resource](https://www.transifex.com/grocy/grocy/strings/)) will be included in releases._

Transifex timeline excerpt:
![grafik](https://github.com/grocy/grocy/assets/2161815/0d129d0d-4695-4e11-a6c1-a31f96076dfb)

So the translation was completed ~ on 2023-07-02, the [current release v3.3.2](https://grocy.info/changelog#v3.3.2) was released on 2022-11-12 - so unless time traveling is finally invented, it's not a real surprise that a translation just finished can't be part of a release from the past.

No worries, the Estonia localization will be included in the next release, just like it happened for any contributed translation in the last 6 years Grocy. Thanks for translating Grocy, but I can't follow how you came to the conclusion that this is a bug.

**Comment by aylamz** [comment]
I somehow missed this. Still pretty new to Transifex and I find the UI a bit confusing compared to Weblate.
I didn't translate this, but isn't it supposed to be on https://demo-prerelease.grocy.info/ if it was completed 5 days ago? I don't see it there either.

**Comment by aylamz** [comment]
Ah, didn't know this was manual. The README makes it sound like it is automated.

> The [pre-release demo](https://demo-prerelease.grocy.info/) is available for any translation which is at least 70 % complete and will pull the translations from Transifex 10 minutes past every hour, so you can have a kind of instant preview of your contributed translations

**Comment by berrnd** [comment]
The pre-release demo for Estonian is now available: https://et.demo-prerelease.grocy.info
