### ISSUE TITLE
Feature Request: 

### ISSUE THREAD

**Issue by Alethio36** [grocy/grocy#2271]
First of thank you for a amazing app. We are integrating it into our lives at home.

Something that would be nice is "soft adding" something into the system.

For example, I would like to add ice cream on the shopping list, but we havnt bought ice cream since using the app. Since I don't have product info from the store, I'd like to add "ice cream" to the list, and when my spouse does the shopping, when it's bought, there's either a straightforward way to then fill in the details, or maybe some checkbox or gui element to convey the item is unfilled in. 

Currently we are just adding a # at the end of the items title to convey the info.

Let me know if i can make my request more clear or if there is anything I can do to help you.

THANK YOU AGAIN FOR BEING AWESOME

**Comment by berrnd** [comment]
When entering something unknown in each and every product input field, there is a popup for inplace-adding products:

![grafik](https://github.com/grocy/grocy/assets/2161815/b383191a-200e-45b3-9647-a9533e3471c9)

The better place for general usage/help questions is the [r/grocy subreddit](https://www.reddit.com/r/grocy) as [mentioned in README](https://github.com/grocy/grocy#questions--help--bug-reports--feature-requests).

**Comment by berrnd** [comment]
Additionally, a shopping list item doesn't need a product - it's perfectly valid to only fill in the "note"-field for maybe not yet added "real" products:

![grafik](https://github.com/grocy/grocy/assets/2161815/b442ac77-366f-4a16-a3c5-34e52a9c4c75)

**Comment by Alethio36** [comment]
That's absolutely perfect. I can't believe I missed that.
