### ISSUE TITLE
Feature Request: Scraping prices from internet and  create best shopping list with shop recommendation

### ISSUE THREAD

**Issue by bertrandgodefroy** [grocy/grocy#2277]
Get prices for products from shops by using the EAN code.
Specify the refreshment interval.
Recommend the best shop (best price)

Opensource webscrappers could be used such as scrapy.
The shop list should have an URL FIELD.

**Comment by berrnd** [comment]
Duplicate of #1653 for the price comparison part, any "scraping stuff" for specific sites / sources will never be part of Grocy and are subject to external tools / integrations.
