### ISSUE TITLE
Hide Stock Overview / Purchase / Consume / Inventory

### ISSUE THREAD

**Issue by CountParadox** [grocy/grocy#228]
Hi, 

I have several grocy instances, one of them I hope to use just for equipment / manual tracking.

I have set the flags as so:

```

Setting('FEATURE_FLAG_SHOPPINGLIST', false);
Setting('FEATURE_FLAG_RECIPES', false);
Setting('FEATURE_FLAG_CHORES', false);
Setting('FEATURE_FLAG_TASKS', false);
Setting('FEATURE_FLAG_BATTERIES', false);
Setting('FEATURE_FLAG_EQUIPMENT', true);
Setting('FEATURE_FLAG_CALENDAR', false);
```

However the Stock Overview, Purchase, Consume and Inventory tabs are still present. and it goes to stock overview by default.

Is it currently not possible to disable this part of grocy and have the equipment page as the default?

Thank you

**Comment by berrnd** [comment]
No, everyhting related to stock management is the default feature set which currently cannot be disabled with feature flags. You could however use [custom JS/CSS](https://github.com/grocy/grocy#adding-your-own-css-or-js-without-to-have-to-modify-the-application-itself) to just hide the menu entries.

Stock was the original feature part grocy was born with, so sure this can also be added to be disabled in the same way...
