### ISSUE TITLE
Bug: vastly increased load after update to 4.0.0

### ISSUE THREAD

**Issue by gen-angry** [grocy/grocy#2282]
After updating using update.php and loading the index page for the database changes, the site takes about 3-4 times as much RAM and pages load much slower (about 4-5 seconds per change). CPU usage spikes to 100% of the container and adds about 200MB RAM usage per page load. All pages do eventually load fine.

Previously with 3.3.2, the container ran fine and speedy, never going over 150MB total even during page changes.

Steps that I did.
- Have working 3.3.2 instance in a container.
- Set container resources to 8GB RAM + 4 VCPU temporarily for the upgrade.
- apt-get update && apt-get upgrade
- chmod +x update.sh and ran it.
- compare config.php with config-dist.php, add and set new fields.
- navigate to root of the site to trigger database update, wait for site to fully refresh.
- browse around. each page change adds 200MB RAM and CPU usage spikes to full during the page load. After about 4-5 seconds, page loads. After about 10 seconds, the container 'settles back down' a bit but over time, the RAM usage keeps creeping upwards.

Host is an i5-6500, 64GB RAM, 1TB SSD, running proxmox VE 8.0.3. 
Container is ubuntu 22.04, PHP Version 8.1.2-1ubuntu2.13, SQLite Version 3.37.2, Apache/2.4.52.
Resources currently set to 4 VCPU + 8GB RAM (would eventually like to set it back down to 1VPU + 512MB RAM)

I've tried the upgrade process 3x in case it was something weird but it has happened every time. I'm not sure which logs I can attach, will check back for that. For now, I have the container reverted back to 3.3.2 via backup but have saved a copy of my last attempt so I can grab logs, test things, etc.

Thank you for reading this and have a great day! :)

**Comment by berrnd** [comment]
You most likely have a lot QU conversions and/or products. (?) A lot has changed about how QU conversions are handled technically to support unlimited hierarchy / transitive conversions.

Can simply be checked how fast / performant a `SELECT * FROM quantity_unit_conversions_resolved` is. When having many conversions and/or products defined, this is not so fast (and resource-intensive) when using anything older than SQLite 3.39.4 (that's also why the [changelog](https://grocy.info/changelog#v4.0.0) and [README](https://github.com/grocy/grocy#platform-support) explicitly mentions that). So I recommend triple checking that.

Beside that, it can't be a general problem (this here is the place for _reproducible_ bugs). Proof: The demo instances handled thousands of v4.0.0 page loads just fine and there was no need to throw additional gigabytes of RAMs and CPUs at them.

**Comment by berrnd** [comment]
References #2081.

**Comment by gen-angry** [comment]
Thank you for commenting, that gave me a starting point for what to check. 

Apparently, ubuntu LTS version of sqlite3 is several versions behind so manually updating that helped (I just went to 23.04 as this is the only site in this container) but it was still a bit slow and spiking usage like before.

What fixed it entirely was deleting all the QUs and replacing them. I only had about 10 QUs and around 200 various products (most using a single piece QU) so it didn't take long. It's back to speedy again and only maintaining around 150-170MB usage. Maybe I had something set wrong with them initially, who knows. But it's fixed and actually faster than the previous install.

Thanks again!
