### ISSUE TITLE
Bug: 4.0.0 - DB migration fails for (crap-data) QU conversions

### ISSUE THREAD

**Issue by xyrolaith** [grocy/grocy#2285]
After upgrading to v4.0.0 the database migration is stuck on migration 207.
Unfortunately the constraint error message isn't very clear. What does the 19 refer to? There is no ID 19 in quantity_unit_conversions.

Error source:
```
/usr/share/webapps/grocy/services/DatabaseService.php:32
```

Error message:
```
SQLSTATE[23000]: Integrity constraint violation: 19 QU conversion already exists
```

Stack trace:
```
#0 /usr/share/webapps/grocy/services/DatabaseService.php(32): PDO->exec()
#1 /usr/share/webapps/grocy/services/DatabaseMigrationService.php(69): Grocy\Services\DatabaseService->ExecuteDbStatement()
#2 /usr/share/webapps/grocy/services/DatabaseMigrationService.php(35): Grocy\Services\DatabaseMigrationService->ExecuteSqlMigrationWhenNeeded()
#3 /usr/share/webapps/grocy/controllers/SystemController.php(30): Grocy\Services\DatabaseMigrationService->MigrateDatabase()
#4 /usr/share/webapps/grocy/packages/slim/slim/Slim/Handlers/Strategies/RequestResponse.php(38): Grocy\Controllers\SystemController->Root()
#5 /usr/share/webapps/grocy/packages/slim/slim/Slim/Routing/Route.php(358): Slim\Handlers\Strategies\RequestResponse->__invoke()
#6 /usr/share/webapps/grocy/packages/slim/slim/Slim/MiddlewareDispatcher.php(65): Slim\Routing\Route->handle()
#7 /usr/share/webapps/grocy/packages/slim/slim/Slim/MiddlewareDispatcher.php(65): Slim\MiddlewareDispatcher->handle()
#8 /usr/share/webapps/grocy/packages/slim/slim/Slim/Routing/Route.php(315): Slim\MiddlewareDispatcher->handle()
#9 /usr/share/webapps/grocy/packages/slim/slim/Slim/Routing/RouteRunner.php(68): Slim\Routing\Route->run()
#10 /usr/share/webapps/grocy/middleware/LocaleMiddleware.php(16): Slim\Routing\RouteRunner->handle()
#11 /usr/share/webapps/grocy/packages/slim/slim/Slim/MiddlewareDispatcher.php(269): Grocy\Middleware\LocaleMiddleware->__invoke()
#12 /usr/share/webapps/grocy/middleware/AuthMiddleware.php(32): Psr\Http\Server\RequestHandlerInterface@anonymous->handle()
#13 /usr/share/webapps/grocy/packages/slim/slim/Slim/MiddlewareDispatcher.php(269): Grocy\Middleware\AuthMiddleware->__invoke()
#14 /usr/share/webapps/grocy/packages/slim/slim/Slim/Middleware/RoutingMiddleware.php(45): Psr\Http\Server\RequestHandlerInterface@anonymous->handle()
#15 /usr/share/webapps/grocy/packages/slim/slim/Slim/MiddlewareDispatcher.php(121): Slim\Middleware\RoutingMiddleware->process()
#16 /usr/share/webapps/grocy/packages/slim/slim/Slim/Middleware/ErrorMiddleware.php(76): Psr\Http\Server\RequestHandlerInterface@anonymous->handle()
#17 /usr/share/webapps/grocy/packages/slim/slim/Slim/MiddlewareDispatcher.php(121): Slim\Middleware\ErrorMiddleware->process()
#18 /usr/share/webapps/grocy/middleware/CorsMiddleware.php(27): Psr\Http\Server\RequestHandlerInterface@anonymous->handle()
#19 /usr/share/webapps/grocy/packages/slim/slim/Slim/MiddlewareDispatcher.php(269): Grocy\Middleware\CorsMiddleware->__invoke()
#20 /usr/share/webapps/grocy/packages/slim/slim/Slim/MiddlewareDispatcher.php(65): Psr\Http\Server\RequestHandlerInterface@anonymous->handle()
#21 /usr/share/webapps/grocy/packages/slim/slim/Slim/App.php(199): Slim\MiddlewareDispatcher->handle()
#22 /usr/share/webapps/grocy/packages/slim/slim/Slim/App.php(183): Slim\App->handle()
#23 /usr/share/webapps/grocy/app.php(109): Slim\App->run()
#24 /usr/share/webapps/grocy/public/index.php(45): require_once('...')
#25 {main}
```

System info:
```
{
    "grocy_version": {
        "Version": "4.0.0",
        "ReleaseDate": "2023-07-29"
    },
    "php_version": "8.1.21",
    "sqlite_version": "3.42.0",
    "os": "Linux 6.4.7-arch1-1 #1 SMP PREEMPT_DYNAMIC Thu, 27 Jul 2023 22:02:18 +0000 x86_64",
    "client": "Mozilla\/5.0 (Windows NT 10.0; Win64; x64; rv:109.0) Gecko\/20100101 Firefox\/115.0"
}
```

**Comment by berrnd** [comment]
Then you most likely have conflicting conversions (I guess product specific ones). Grocy is generally based on [GIGO](https://en.wikipedia.org/wiki/Garbage_in,_garbage_out), so you need to find and fix those invalid entry/entries.

&nbsp;
> What does the 19 refer to? 

Any "Factor purchase to stock quantity unit" is migrated to product specific QU conversions, since that field was dropped - so that ID refers to a new row in the table (not existing when the migration fails, since a rollback happens).

The common (bullshit) case where a "Factor purchase to stock quantity unit" exists, while also a same product specific QU conversion exists is already handled by the migration ([code ref](https://github.com/grocy/grocy/blob/57ccb8645ea0a191137c7fab10c94ea083259655/migrations/0207.sql#L43-L44)), so right now I can't imagine what other crap you might could have.

**Comment by berrnd** [comment]
Feel free to recreated a reproducible example on v3.3.2, then upload that database file here (or send me your actual database by mail or something if that's ok for you) and I will have a look and find a workaround for another crap-data example.

**Comment by berrnd** [comment]
> `and p.qu_factor_purchase_to_stock != 1.0`

Btw: A "factor 1.0 conversion" must exist when "Quantity unit stock" <> "Default quantity unit purchase" (that's also created automatically when initially defining such a product).

**Comment by berrnd** [comment]
> 4.0.0 also slowed down everything even further.

Noted that myself on my personal instance (which is even older, > 20K stock transactions which is slowly getting a lot of data to process for quickly / on the fly calculating the average shelf life of a product, the last price, etc.) yesterday, tracked in #2283.

The [optimized view in migration 221](https://github.com/grocy/grocy/blob/fd7e24b7d1ae6598e69e8138260339907203b2d5/migrations/0221.sql) and[ the new indices added in migration 222](https://github.com/grocy/grocy/blob/ca740e8cee3b473f06229e869d85ecaa4ab45dad/migrations/0222.sql) made it (for me on that instance) now slightly faster than before. However, there is of course still and most likely forever room for improvements related to more data, e.g. a `SELECT * FROM uihelper_stock_current_overview` (which prepares all the data needed for /stockoverview) currently consumes about 900 ms execution time on that same instance, which is of course not fast as light. Maybe caching those expensive calculations somehow will be a good thing.

When you don't need / want history, (manually) deleting the journals will speed things up the most.
