### ISSUE TITLE
Bug: I can't get back my permissions, even as Admin

### ISSUE THREAD

**Issue by edalcin** [grocy/grocy#2290]
I changed the admin/admin login and password to my login and password.

After a few days using this wonderful tool, I decided to change my permissions and turn off some of the features I'm not using:

* Chores
* Batteries
* Tasks
* Calendar

I noticed that they still on the menu. Then I decided to turn on again and I got this message:

"Permission missing:ADMIN"

Is it possible to recover the ADMIN role? But I didn't change it anywhere.

(I'm sorry, but I don't know how to use reddit.... Please, help!)

**Comment by berrnd** [comment]
This is the place for reproducible bugs and feature requests, this is neither of that. And in any case I can't help without having something reproducible. And also in any case, Grocy doesn't change stuff on it's own, there is no magic involved.

&nbsp;
> I decided to change my permissions and turn off some of the features I'm not using

That's not possible without removing the ADMIN (= "All permissions" checkbox at the top of the list). If you're the only user on your instance, you've successfully locked you out. There is even a safety confirmation question in the case of removing the last ADMIN permission user, ignoring that does what it says.

![grafik](https://github.com/grocy/grocy/assets/2161815/cb77f535-180a-4d9d-ab58-8ce5fe7012b8)

Feature flags are there to disable stuff you don't need/want ([mentioned in README](https://github.com/grocy/grocy#disable-certain-features), [mentioned above the corresponding `config.php` setting](https://github.com/grocy/grocy/blob/d006436d49e3f6fc99982efe30c8a1c4884d89a8/config-dist.php#L127-L129)).

&nbsp;
Edit the database manually, restart completely, restore your backup - or something like that. And please use the places appropriate to your request as [mentioned in README](https://github.com/grocy/grocy#questions--help--bug-reports--feature-requests) in the future, thanks.

**Comment by edalcin** [comment]
Thanks. I just created another account and use this account (admin as default) to give me back my permissions. More simple...

Cheers
