### ISSUE TITLE
Bug: Wrong price stats if stock entry is edited.

### ISSUE THREAD

**Issue by alkuzman** [grocy/grocy#2292]
### When it happens?
While purchasing we might not select the correct QU and enter 500Kg or 0.5g by mistake. But after a while, we will spot the mistake because we have both the wrong stock and the wrong price (now we can spot the mistakes right away thanks to the Stock reports. Thanks for the great effort).

Then we edit the stock entry with the correct amount and price.

### What is the issue?
The stock and the value are correct, however, the price stats (last price, average price, price history, and the stock reports) are all wrong. Please refer to the [private demo](https://test-wxnn6o6uxc82yedshuo1w.demo-prerelease.grocy.info/stockoverview) for the product **Cookies**.

![image](https://github.com/grocy/grocy/assets/7229627/5ed39566-0c95-460e-9f6c-ec4bfb1b0fad)

### Complications
I had a look at the database and the code around this issue. I know it might be computationally expensive to look for the last viable state of a stock entry (before any consumption). But I was thinking maybe only edits right after purchase or inventory change should apply.

**Comment by berrnd** [comment]
> But I was thinking maybe only edits right after purchase or inventory change should apply.

So this would practically mean a fix for this should work if the edit transaction was done "right after" (whatever time span that technically refers to) and not when done later? No, that's really not the way to go.

**Comment by alkuzman** [comment]
> So this would practically mean a fix for this should work if the edit transaction was done "right after" (whatever time span that technically refers to) and not when done later? No, that's really not the way to go.

I meant, right after (not related to time, but) before any new stock entries are created/consumed as a result of partial consumption (30 out of 200gr) or partial transfers to new locations. If new entries are created it is hard to know which stock entry to change because the amount won't be correct. 

For example, in your commit where you select the latest change of a given stock entry, the amount could be wrong since the entry was edited after some amount was already consumed.

![image](https://github.com/grocy/grocy/assets/7229627/3d8c8506-3b1c-4e8e-994c-469a643c6587)

Here the `stock_edited_entries.stock_log_id_of_newest_edited_entry` would take that the correct amount was 1.72 instead of 2.2 Because 0.44 was consumed before the last edit.

I am suggesting that either we have to limit until which transaction the history will be processed or take the consumed or moved amounts into account too.

**Comment by berrnd** [comment]
A price "goes into stock" via a `purchase` (or `inventory` or `self-production`) transaction and it might get corrected via a `stock-edit-new` transaction, not on `consume`. Means consume transactions are not relevant for calculating the last price, average price and so on.

Simply provide a practical reproducible scenario when you still think something is wrong.

**Comment by alkuzman** [comment]
I know the price is not changed by consumption in any way. However, the amount is. If you see in the picture the latest code will select the stock_log entry with id **3180** which is the last entry in the picture.

The amount here is **1.72** which is not what was bought in the beginning **2.2**. If suppose you have another entry with price **4** and amount **2.2**, the average price should be `(2.2×3.06 + 2.2×4) ÷ (2.2 + 2.2) = 3.53`. However, it will be `(1.7×3.06 + 2.2×4) ÷ (1.7 + 2.2) = 3.59`. This clearly results in wrong average price.

I hope this clears things up. Please let me know, I will create a private demo with an example if this is not clear. I thought it might be clearer this way.

**Comment by berrnd** [comment]
> Just wanted to point out that the average price does not take only prices into account but also amouts

Of course it does (as naturally required), but not amounts of **consume** (!) transactions which I've tried to point out multiple times here now.

**Comment by alkuzman** [comment]
Hey, I was just trying to reproduce the issue on a private demo but after the last commit, the price stats are not shown at all. 
https://test-iofjqjbsyhai6n3xismcl.demo-prerelease.grocy.info/stockoverview

**Comment by berrnd** [comment]
> after the last commit, the price stats are not shown at all

Regressions happen, thanks for testing, is fixed (and was a problem when there were no single edited stock entries at all).

**Comment by alkuzman** [comment]
Hey,  thank you for your prompt answer and update. 

[On this demo](https://test-a2ax11gc3iez8mfeiscm9f.demo-prerelease.grocy.info/stockoverview) I managed to reproduce the issue I was talking about.

Cookies:
- 12 Packs (4.65 eur per Pack) *older*
- 12 Pack (6 eur per Pack) *newer*

1. Consumed 11 Packs of the *(older* entry ($4.65 per Pack)
2. Changed the price of that entry to ($4.5 per Pack)

I would expect the **average_price = (12 * $4.5 + 12 * $6) / (12 + 12) = $5.25**.
But instead, it is **$5.88**. That would be true if you count the older entry as 1 pack instead of 12.

Note: when I say _older_ I mean with a most recent due date.

**Comment by berrnd** [comment]
Is now also fixed in ee4a082c7430b6de0e612c4120706e072cb7c0bd.

**Comment by alkuzman** [comment]
Hey, thanks for the update. I am sorry I was not available to test right away.

[Newest demo](https://test-ky8owks51jh5w9bprc5i.demo-prerelease.grocy.info)

### Stock Report not updated (**Cookies**)
I believe the Stock Report is not updated with the change. It says I have spent $55.00 on cookies when it should say $120

_Note: by mistake, I consumed the last pack and then I did undo the transaction. Which probably created a new stock entry whose price is now $7. But before consumption, it was $6 so the average price is ok to be 5$._  

### Amount updates are now completely ignored. (**Cheese**)
As I looked in the query I suspected that amount updates are completely ignored and I decided to test.

1. Bought 0.5 Slices (suppose it was a mistake) of Cheese ($2.56 per Slice)
2. Fixed to 0.5 Packs and $2.56 per Pack

The price is updated but the amount update is ignored since the SQL is looking in the origin entry for the amount. The average is $4.42 instead of 4.27. It is like that because it counts 0.05 Packs instead of 0.5 Packs which is the updated value.

### My take
I am sorry I might be going out on a limb here but, I believe this issue cannot be really fixed without an additional column in the sotck_log that holds the source amount, which can be changed only by edit action (not impacted by consumption or other transactions). This way you can return to the previous solution of looking only at the last edited transaction of a given stock entry.

I propose this solution because all the other values in the log are impacted only by the edit action except for amounts.

**Comment by berrnd** [comment]
> I believe this issue cannot be really fixed without an additional column in the sotck_log

Storing the same data twice is always bad so feel free to change it that way for you. In any case this will be not be the solution for this project.

This request is already cluttered as hell completely ignoring the easily trackable "one topic per request" approach, so let's further track all that here.

**Comment by alkuzman** [comment]
I agree that having two columns for the same field in 2 different states can be hell for consistency. That was my best solution for now. I will try to find better one :)

**Comment by berrnd** [comment]
> making a complicated query that will have to take all transactions into account

Calculating a products average price or the average shelf life or getting the price history also already takes essentially all transactions of the corresponding product into account. It takes milliseconds for thousands of rows/transactions and the `products_average_price` query is rather simple so far. Having a performance fear before trying something is also always the wrong approach, performance can always be fixed later (the [best example from yesterday](https://github.com/grocy/grocy/commit/1d7f7b2992a1772b0fb0fe500eb95098a794c771) affecting everything related to stock in Grocy).

**Comment by alkuzman** [comment]
Then taking the last edit and subtracting all the consume transactions (which will result in addition since they have a negative amount) that were executed before (this transaction) should give the right amount. I could write SQL but I am not sure whether there are other types of transactions or my query will break other features since I started looking into the code like 2 days ago.

**Comment by berrnd** [comment]
> Then taking the last edit and subtracting all the consume transactions

Did it now like that ([querying the correct amount in `stock_edited_entries`](https://github.com/grocy/grocy/blob/393a3121866b241068e6492491eda2329429c995/migrations/0230.sql#L10) and using that then in the views [`products_average_price`](https://github.com/grocy/grocy/blob/393a3121866b241068e6492491eda2329429c995/migrations/0230.sql#L32) and [`products_price_history`](https://github.com/grocy/grocy/blob/393a3121866b241068e6492491eda2329429c995/migrations/0230.sql#L61)). Stock reports are also fixed by that, they use the price history.

But the total value spent on Cookies on the above linked demo is different than you expect it (I think it's correct) - probably the state there is no longer the same as of the time you posted this here - the first purchase was edited 2 times to 7 per Pack at the end, so `(4*12)+(7*12)=132`.

**Comment by alkuzman** [comment]
I did some tests and also I looked into the queries. It seems to work great now. Thanks :)
