### ISSUE TITLE
Unclear on how to confirm if migrations are up to date

### ISSUE THREAD

**Issue by TurnrDev** [grocy/grocy#2293]
It's unclear how to check if migrations are up to date.I asked [here](https://github.com/grocy/grocy/issues/2284#issuecomment-1666452754), but got [told](https://github.com/grocy/grocy/issues/2284#issuecomment-1666455807) to check the readme. However, the readme just states:

> Database schema migration is automatically done when visiting the root (`/`) route (click on the logo in the left upper edge).
> 
> _Please note: Database migrations are supposed to work between releases, not between every commit. If you want to run the current `master` branch (which is the development version), you need to handle that (and maybe more) yourself._

Is there a command one can run to ensure migrations have been run, or is visiting the root route the only way to run them? When I visit the root route, I get a redirect to `stockoverview` and consequently a 499 or 502. I've tried in a fresh container to no avail. Please don't lock this issue, it's really annoying as it just stifles the communities ability to resolve issues.

**Comment by berrnd** [comment]
> is visiting the root route the only way to run them

Yes, they are automated on that route. Of course you're free to check the database manually, but technically that's not needed at all.

Again: Docker image issues are nothing to be reported as a bug here, please stop abusing the issue tracker here (once again: [README ref](https://github.com/grocy/grocy#questions--help--bug-reports--feature-requests)).

**Comment by berrnd** [comment]
See also https://www.reddit.com/r/grocy/comments/15enu9o/comment/juvmuv8/?context=3 when it's still about the linuxserver/grocy Docker image.
