### ISSUE TITLE
Feature Request: provide alternative for Shopping List Last Price (Unit)

### ISSUE THREAD

**Issue by alkuzman** [grocy/grocy#2294]
I am opening this issue as a discussion point for improvement of the Shopping List Last Price (Unit).

### My issue
We store most of our products in grams and milliliters. This property shows the price in Stock QU which is almost always < 0.02 Eur rounded to two decimals. I know it is possible to increase the number of decimals presented but this makes the presentation not very nice and our brain is used to processing prices with 2 decimal places. This renders this property useless for us.

![image](https://github.com/grocy/grocy/assets/7229627/e62a9a2f-9dbd-4ac5-947d-3ca64ace237f)

### My suggestion
Change the QU to Price QU to make prices everywhere consistently shown. This is useful since I set this QU to whatever markets show their prices (mostly in Kg, L, and Piece). Another option is to use the QU selected in the shopping list entry. Maybe provide both or make it configurable in the Shopping List config in Settings.

Personally, I don't see a use case where Stock QU would be useful, only in cases where both Price QU and Stock QU are the same. Correct me if I am wrong.

**Comment by berrnd** [comment]
So essentially the in #2248 (invalidly) reported Bug now as Feature Request.

**Comment by alkuzman** [comment]
Yes
