### ISSUE TITLE
Improvement: Unnecessary or wrong calculation in `uihelper_shopping_list` view

### ISSUE THREAD

**Issue by dominiczedler** [grocy/grocy#2298]
Hello Bernd,

in one of your latest commits ([this](https://github.com/grocy/grocy/commit/7ef744a9959cbf00f4bebe41dd3cee47cce392d7))  there is a change for the `uihelper_shopping_list` view. But I think the change in the second line doesn't make sense, if you have in mind that the first `/` term and the second `*` term cancel each other out.

`plp.price * (sl.amount / IFNULL(quc.factor, 1.0)) * IFNULL(quc.factor, 1.0) AS last_price_total,`

Maybe there is something wrong or this is just an unnecessary calculation. So hopefully can be fixed quickly (sorry that I don't offer a pull request, just have no idea what would be right in this line).

Thanks for your work on the project.

**Comment by berrnd** [comment]
Right, the last part `* IFNULL(quc.factor, 1.0)` is of course completely unnecessary - most likely a copy & paste problem on my side + test data where this made no real difference. Thanks for the heads up.

The general change was about that the prices displayed on the shopping list should be related to the there selected QU, so adding taking the corresponding conversion factor into account in the view.
