### ISSUE TITLE
Decimal Places

### ISSUE THREAD

**Issue by teamtmedia** [grocy/grocy#230]
It is lovely to see accuracy but now I'm debating buying a scale that runs to 11 decimals places (what is 1/100000000000th of a gram called anyway) and some subatomic tweezers ;)

Any chance to opt for rounding :)

**Comment by berrnd** [comment]
Where do you see that? There should be rounding everywhere where decimal values are displayed - the requests are more for the other way (like #225)...

**Comment by teamtmedia** [comment]
It's the scaling and costings I asked for.  Typical me.  Great idea that actually causes problems ;)

![](https://screenshotscdn.firefoxusercontent.com/images/d124bceb-6b7e-4362-87b8-55ebee621fef.png)

**Comment by teamtmedia** [comment]
Actually you can probably ignore this.  The reason it is doing this is that I have set up my servings by weight (so I can use grams rather than servings).  Being that I have set the recipe to a weight for bulk (i.e. 2440) and this was, as you can see, for a very small amount the calculations are going to be screwy.

Put this WAY down your list.....unless it bugs you :)  Thank you for the great code :)

**Comment by berrnd** [comment]
Hm, that's what I meant - thought that "everywhere" rounding is applied for displaying decimal values...

So should not bother and would look better to just display currency values always with 2 decimal places and quantity unit values with max. 3 decimal places (only not zero decimal places - "dynamic rounding").
Or would this be a problem for you?

**Comment by teamtmedia** [comment]
2 and 3 is perfect.  Makes total sense in all situations I can think of.  Thank you
