### ISSUE TITLE
Bug: update to 4.0.1 breaks previous 4.0.0 installation

### ISSUE THREAD

**Issue by ulu** [grocy/grocy#2302]
- I updated a working 3.x to 4.0.0 and after the new version came out I updated to v4.0.1
- all I get is now a barcode instead of stockoverview (see attached picture error1.png)
- the html code is nearly empty and contains only:
`<body><img src="https://<url>/grocy/public/index.php/stockoverview" alt="https://<url>/grocy/public/index.php/stockoverview"></body>
`
where <url> is the url to my server, which I do not want to made public.

I tried a second approach: remove all except folder "data" from 4.0.0 installation and extract all content from 4.0. to the folder --> which means this is an update. Now I got a complete different behavior (translated with deepl.com):

Error: Redirection error
The requested website redirects the request in such a way that it can never be completed.
    This problem can sometimes occur when cookies are disabled or refused.

URL is now: http://<url>/grocy/public/index.php/login

<img width="704" alt="error1" src="https://github.com/grocy/grocy/assets/809609/eadcfeaa-baf7-4c80-a543-6aab516400f5">
<img width="635" alt="error2" src="https://github.com/grocy/grocy/assets/809609/a6db90cc-e45e-4cc0-a3e0-3e629be8eaff">

**Comment by berrnd** [comment]
You simply forgot to empty out the `data/viewache` directory, that's also mentioned in README: https://github.com/grocy/grocy#how-to-update

Searching a little bit beforehand would have brought up [that](https://www.reddit.com/r/grocy/comments/15kkmup) where the same was already mentioned.

**Comment by Zulgrib** [comment]
The update script (update.sh) take care of that part very well.

**Comment by ulu** [comment]
> The update script (update.sh) take care of that part very well.

If I had a remote shell I would use this script but I have only a webhosting space.

Regarding [that](https://github.com/grocy/grocy#how-to-update) topic on project page: Maybe a h1 instead of h2 would make the topic more "visible".
