### ISSUE TITLE
Feature Request: meal plan with choice 

### ISSUE THREAD

**Issue by roman0815** [grocy/grocy#2304]
moin Berrnd,
can you add a choice to the menu?  So, that users can say whether they want to eat or not?

**Comment by berrnd** [comment]
Please be so kind and elaborate a little more about what you want to have exactly (and also have a look at #1171, which is potentially related).

**Comment by roman0815** [comment]
I look at #1171, this is nearly what i'm looking for. 
I will use this for a fire department, i would like to send out a meal plan and get an answer from the others who would like to eat on which day.

**Comment by berrnd** [comment]
As just said by mail (which is the wrong way, please note what's [mentioned in README](https://github.com/grocy/grocy#questions--help--bug-reports--feature-requests) for the future).

Any business use case (includes non-profit or voluntary "businesses" too, anything which is not a home) is out of scope of this project.

I doubt that there is not already far better software which can handle what you need, guess you're not the first one organizing the supply chain for a canteen on this planet...
