### ISSUE TITLE
Bug: Alphabetical chore assignment gets stuck on last user alphabetically

### ISSUE THREAD

**Issue by ethw** [grocy/grocy#2305]
Alphabetical chore assignment is not rolling over to the first user alphabetically when the final user alphabetically clicks "track next chore schedule".

I reproduced this on a demo instance here: https://test-ekdub6vcjctqrpnsp2uvnp.demo-prerelease.grocy.info/choresoverview

Repro steps:
* Have two users, example 'admin' and 'user2'
* Create a chore with alphabetical assignment
* In "Assign to" select both users
* Save chore changes
* Go to chore overview
* Click "Track next chore schedule" multiple times and notice that it gets stuck on 'user2' and does not roll over to 'admin'

**Comment by berrnd** [comment]
> Click "Track next chore schedule"

When using that button on [/choresoverview](https://test-ekdub6vcjctqrpnsp2uvnp.demo-prerelease.grocy.info/choresoverview), the tracking is done in the context of the currently logged in user. Which is always `admin` for the demo instances. So for this example, the next one is always `user2` there.

When really tracking this chore as `user2` it works properly. Can also be reproduced on the demo, on [/choretracking](https://test-ekdub6vcjctqrpnsp2uvnp.demo-prerelease.grocy.info/choretracking) it's possible to track any chore for any time for any user.

**Comment by ethw** [comment]
Good to know thank you. I guess this behaviour must have changed because my old use case was me constantly flipping through a rotating list of assignees using the alphabetical option. I've adjusted how I use it so that the intended user is now selecting "track next chore". Thanks!

**Comment by berrnd** [comment]
> I guess this behaviour must have changed

No, that button on [/choresoverview](https://demo-prerelease.grocy.info/choresoverview) used the currently logged in user as "Done by" since ever. Every change is always tracked and explained on [the changelog](https://grocy.info/changelog).
