### ISSUE TITLE
Feature Request: Group Spendings Stock Report by Store

### ISSUE THREAD

**Issue by TurnrDev** [grocy/grocy#2308]
The report feature at [/stockreports/spendings](https://en.demo.grocy.info/stockreports/spendings) is great! I love it. Is it possible to get the ability to group by store? 

I may look into this myself, but I may not. Also, I'm not massively fussed by this, just a nice idea. So please, do not feel obligated or rushed to add this if it's any amount of effort.

**Comment by TurnrDev** [comment]
That was fast! I appreciate that! Do you accept donations for the effort you put in?

**Comment by berrnd** [comment]
Everything for that is stated on https://grocy.info/#say-thanks (in short: my work on this project is driven by time and desire, not money).

And as also noted there in the paragraph above:
> _When you miss something, feel free to open a feature request on GitHub - maybe it will be added within hours, because your ideas are my motivation._

Some time ago this used to be the case more often than currently (for different reasons), but here and there it's still true - so you're welcome.
