### ISSUE TITLE
Bug: Quick consume button changes value after clicking

### ISSUE THREAD

**Issue by Janovlk** [grocy/grocy#2309]
Hello,

when I set the Quick Consume amount for the button of the same name to a value less then 1 (useful for me in some products), after clicking on it, the value of the quick consume button changes.

I created the included example using pre-release version 3a2929c0.

![Grocy-bugreport-ConsumeButton](https://github.com/grocy/grocy/assets/140972046/be85eb42-9cba-42d0-940c-9f817f836d2a)

**Comment by berrnd** [comment]
It's just a display glitch, clicking the button again still consumes the desired amount even if 0 is displayed.

**Comment by berrnd** [comment]
It's a general problem about "display number parsing" ([code ref](https://github.com/grocy/grocy/blob/3a2929c016a0ace37f19343f8ba605d77c4a71b9/public/js/grocy.js#L586-L623)), so it only affects someone not using a `.` (dot) as the decimal separator (which is Browser locale dependent).
