### ISSUE TITLE
Filter recipes by stock availability

### ISSUE THREAD

**Issue by fawqsir** [grocy/grocy#231]
Would be great to add categories for recipes. Perhaps have an option (check box) to only show recipes that are available based on the inventory available.

**Comment by berrnd** [comment]
That's two things:

Filter by stock availability:
Will add this, just like "Filter by status" on most of the other pages.

Categories:
Any custom fields are now possible through "Userfields", not yet part of a release, see #176 or try it out on the [pre-release demo](https://demo-prerelease.grocy.info) if you want.
