### ISSUE TITLE
Feature Request: Flip chore execution function

### ISSUE THREAD

**Issue by lagerea** [grocy/grocy#2311]
Since 4.0 the chore execution of clicking/pressing the green button in the web view or the chore column(mobile) defaults to chore execution at the scheduled time, and the more options (kebab) menu top option is to track chore execution now. 

From a UX standpoint this functionality should be swapped as the only time a chore should be tracked at the time of scheduled that isn't the present is when it was not tracked but was executed, e.g. I cleaned the dishes, but I forgot to execute the chore tracking until the next day. This is the exception to intended or expected behavior which would be to execute/clear the chore in the present or for it to be completed late, resetting the time required for it to be completed again.

**Comment by berrnd** [comment]
As you already said, this was just flipped for v4.0.0. What should be done from an "UX standpoint" and what is "intended or expected" as always depends on personal preference, not on law. There were a lot requests to change it to like it is now, so sounds more the exception is how you expect it (or as you were used to before v4.0.0, adapting to changes is maybe sometimes the harder part), which is of course ok.

However, this won't be changed back and forth for every release from now one, how it's now makes definitely sense - the green button tracks the corresponding chore keeping the desired schedule.

If that doesn't fit your use case, consider using [custom JS](https://github.com/grocy/grocy#adding-your-own-css-or-js-without-to-have-to-modify-the-application-itself) to change it to behave like however you prefer it.

Here is a snippet (for `data/custom_js.html`) to swap the button / menu item functionality:
```html
<script>
if (Grocy.View == "choresoverview")
{
	$(".track-chore-button").addClass("now");
	$(".dropdown .track-chore-button").removeClass("now");
}
</script>
```

**Comment by maniackcrudelis** [comment]
A simple option would be way easier for everyone to adjust the behavior of this button instead of breaking the previous behavior...
I was myself wondering why my chores were suddenly acting so weird !

**Comment by berrnd** [comment]
Follow-up: #2424 was created to track adding some configuration options to make possible what was mentioned here.

**Comment by berrnd** [comment]
There is now this new settings (chores settings / top right corner settings menu) to swap the "Track next chore schedule" / "Track chore execution now" buttons/menu items on the chores overview page:

![grafik](https://github.com/user-attachments/assets/b8e2846d-c0f5-4f14-9bd1-d709014e8aec)
