### ISSUE TITLE
Bug: 1 bottle Milk 930ml shows up in stock as 1860 bottles after purchasing 2 bottles

### ISSUE THREAD

**Issue by EntityinArray** [grocy/grocy#2314]
I have a milk product that has QU conversion 1 bottle = 930 ml.
Upon purchasing 1 bottle of milk, it shows up as 930 bottles in stock.
Purchasing 2 bottles shows up as 1860 bottles in stock.

I recorded a video that demonstrates the issue: 
[grocy_bug.webm](https://github.com/grocy/grocy/assets/18554021/dee693ca-c169-4968-b6cc-c9ab8d1b0778)

Server: grocy 4.0.1 in docker on Arch Linux
Client: grocy on Android 12 from app store

Important note: this bug only occurs in android client, web interface works perfectly

**Comment by berrnd** [comment]
> Important note: this bug only occurs in android client, web interface works perfectly

None of the community contributed apps/tools/integrations are maintained here.
