### ISSUE TITLE
Servererror after downgrade to 3.2.2 

### ISSUE THREAD

**Issue by Saturo78** [grocy/grocy#2315]
Since my host doesn´t provide the right version of sqlite i made a downgrade to 3.2.2.

Now the following error message is prompted after the login:

`xxx
```
/home/xxx/html/Grocy/vendor/morris/lessql/src/LessQL/Database.php:108
```

Error message:
```
SQLSTATE[HY000]: General error: 1 circular reference: closure (View: /home/xxx
```
/home/xxx/html/Grocy/vendor/morris/lessql/src/LessQL/Database.php:108
```

Error message:
```
SQLSTATE[HY000]: General error: 1 circular reference: closure (View: /home/xxx/html/Grocy/views/stockoverview.blade.php)
```

Stack trace:
```
#0 /home/xxx/html/Grocy/vendor/illuminate/view/Engines/PhpEngine.php(60): Illuminate\View\Engines\CompilerEngine->handleViewException(Object(PDOException), 1)
#1 /home/xxx/html/Grocy/vendor/illuminate/view/Engines/CompilerEngine.php(61): Illuminate\View\Engines\PhpEngine->evaluatePath('/home/xxx...', Array)
#2 /home/xxx/html/Grocy/vendor/illuminate/view/View.php(139): Illuminate\View\Engines\CompilerEngine->get('/home/xxx...', Array)
#3 /home/xxx/html/Grocy/vendor/illuminate/view/View.php(122): Illuminate\View\View->getContents()
#4 /home/xxx/html/Grocy/vendor/illuminate/view/View.php(91): Illuminate\View\View->renderContents()
#5 /home/xxx/html/Grocy/vendor/berrnd/slim-blade-view/src/Blade.php(173): Illuminate\View\View->render()
#6 /home/xxx/html/Grocy/vendor/berrnd/slim-blade-view/src/Blade.php(65): Slim\Views\Blade->fetch('stockoverview', Array)
#7 /home/xxx/html/Grocy/controllers/BaseController.php(180): Slim\Views\Blade->render(Object(Slim\Http\Response), 'stockoverview', Array)
#8 /home/xxx/html/Grocy/controllers/BaseController.php(203): Grocy\Controllers\BaseController->render(Object(Slim\Http\Response), 'stockoverview', Array)
#9 /home/xxx/html/Grocy/controllers/StockController.php(119): Grocy\Controllers\BaseController->renderPage(Object(Slim\Http\Response), 'stockoverview', Array)
#10 /home/xxx/html/Grocy/vendor/slim/slim/Slim/Handlers/Strategies/RequestResponse.php(38): Grocy\Controllers\StockController->Overview(Object(Slim\Http\ServerRequest), Object(Slim\Http\Response), Array)
#11 /home/xxx/html/Grocy/vendor/slim/slim/Slim/Routing/Route.php(358): Slim\Handlers\Strategies\RequestResponse->__invoke(Array, Object(Slim\Http\ServerRequest), Object(Slim\Http\Response), Array)
#12 /home/xxx/html/Grocy/vendor/slim/slim/Slim/MiddlewareDispatcher.php(65): Slim\Routing\Route->handle(Object(Slim\Http\ServerRequest))
#13 /home/xxx/html/Grocy/vendor/slim/slim/Slim/MiddlewareDispatcher.php(65): Slim\MiddlewareDispatcher->handle(Object(Slim\Http\ServerRequest))
#14 /home/xxx/html/Grocy/vendor/slim/slim/Slim/Routing/Route.php(315): Slim\MiddlewareDispatcher->handle(Object(Slim\Http\ServerRequest))
#15 /home/xxx/html/Grocy/vendor/slim/slim/Slim/Routing/RouteRunner.php(68): Slim\Routing\Route->run(Object(Slim\Http\ServerRequest))
#16 /home/xxx/html/Grocy/middleware/LocaleMiddleware.php(16): Slim\Routing\RouteRunner->handle(Object(Slim\Http\ServerRequest))
#17 /home/xxx/html/Grocy/vendor/slim/slim/Slim/MiddlewareDispatcher.php(269): Grocy\Middleware\LocaleMiddleware->__invoke(Object(Slim\Http\ServerRequest), Object(Slim\Routing\RouteRunner))
#18 /home/xxx/html/Grocy/middleware/AuthMiddleware.php(76): Psr\Http\Server\RequestHandlerInterface@anonymous->handle(Object(Slim\Http\ServerRequest))
#19 /home/xxx/html/Grocy/vendor/slim/slim/Slim/MiddlewareDispatcher.php(269): Grocy\Middleware\AuthMiddleware->__invoke(Object(Slim\Http\ServerRequest), Object(Psr\Http\Server\RequestHandlerInterface@anonymous))
#20 /home/xxx/html/Grocy/vendor/slim/slim/Slim/Middleware/RoutingMiddleware.php(45): Psr\Http\Server\RequestHandlerInterface@anonymous->handle(Object(Slim\Http\ServerRequest))
#21 /home/xxx/html/Grocy/vendor/slim/slim/Slim/MiddlewareDispatcher.php(121): Slim\Middleware\RoutingMiddleware->process(Object(Slim\Http\ServerRequest), Object(Psr\Http\Server\RequestHandlerInterface@anonymous))
#22 /home/xxx/html/Grocy/vendor/slim/slim/Slim/Middleware/ErrorMiddleware.php(76): Psr\Http\Server\RequestHandlerInterface@anonymous->handle(Object(Slim\Http\ServerRequest))
#23 /home/xxx/html/Grocy/vendor/slim/slim/Slim/MiddlewareDispatcher.php(121): Slim\Middleware\ErrorMiddleware->process(Object(Slim\Http\ServerRequest), Object(Psr\Http\Server\RequestHandlerInterface@anonymous))
#24 /home/xxx/html/Grocy/middleware/CorsMiddleware.php(30): Psr\Http\Server\RequestHandlerInterface@anonymous->handle(Object(Slim\Http\ServerRequest))
#25 /home/xxx/html/Grocy/vendor/slim/slim/Slim/MiddlewareDispatcher.php(269): Grocy\Middleware\CorsMiddleware->__invoke(Object(Slim\Http\ServerRequest), Object(Psr\Http\Server\RequestHandlerInterface@anonymous))
#26 /home/xxx/html/Grocy/vendor/slim/slim/Slim/MiddlewareDispatcher.php(65): Psr\Http\Server\RequestHandlerInterface@anonymous->handle(Object(Slim\Http\ServerRequest))
#27 /home/xxx/html/Grocy/vendor/slim/slim/Slim/App.php(199): Slim\MiddlewareDispatcher->handle(Object(Slim\Http\ServerRequest))
#28 /home/xxx/html/Grocy/vendor/slim/slim/Slim/App.php(183): Slim\App->handle(Object(Slim\Http\ServerRequest))
#29 /home/xxx/html/Grocy/app.php(106): Slim\App->run()
#30 /home/xxx/html/Grocy/public/index.php(45): require_once('/home/xxx...')
#31 {main}
```

System info:
```
{
    "grocy_version": {
        "Version": "3.3.2",
        "ReleaseDate": "2022-11-12"
    },
    "php_version": "8.0.28",
    "sqlite_version": "3.27.2",
    "os": "Linux 4.19.0-23-amd64 #1 SMP Debian 4.19.269-1 (2022-12-20) x86_64",
    "client": "Mozilla\/5.0 (Windows NT 10.0; Win64; x64; rv:109.0) Gecko\/20100101 Firefox\/116.0"
}
```
			/html/Grocy/views/stockoverview.blade.php)
```

Stack trace:
```
#0 /home/xxx/html/Grocy/vendor/illuminate/view/Engines/PhpEngine.php(60): Illuminate\View\Engines\CompilerEngine->handleViewException(Object(PDOException), 1)
#1 /home/xxx/html/Grocy/vendor/illuminate/view/Engines/CompilerEngine.php(61): Illuminate\View\Engines\PhpEngine->evaluatePath('/home/xxx...', Array)
#2 /home/xxx/html/Grocy/vendor/illuminate/view/View.php(139): Illuminate\View\Engines\CompilerEngine->get('/home/xxx...', Array)
#3 /home/xxx/html/Grocy/vendor/illuminate/view/View.php(122): Illuminate\View\View->getContents()
#4 /home/xxx/html/Grocy/vendor/illuminate/view/View.php(91): Illuminate\View\View->renderContents()
#5 /home/xxx/html/Grocy/vendor/berrnd/slim-blade-view/src/Blade.php(173): Illuminate\View\View->render()
#6 /home/xxx/html/Grocy/vendor/berrnd/slim-blade-view/src/Blade.php(65): Slim\Views\Blade->fetch('stockoverview', Array)
#7 /home/xxx/html/Grocy/controllers/BaseController.php(180): Slim\Views\Blade->render(Object(Slim\Http\Response), 'stockoverview', Array)
#8 /home/xxx/html/Grocy/controllers/BaseController.php(203): Grocy\Controllers\BaseController->render(Object(Slim\Http\Response), 'stockoverview', Array)
#9 /home/xxx/html/Grocy/controllers/StockController.php(119): Grocy\Controllers\BaseController->renderPage(Object(Slim\Http\Response), 'stockoverview', Array)
#10 /home/xxx/html/Grocy/vendor/slim/slim/Slim/Handlers/Strategies/RequestResponse.php(38): Grocy\Controllers\StockController->Overview(Object(Slim\Http\ServerRequest), Object(Slim\Http\Response), Array)
#11 /home/xxx/html/Grocy/vendor/slim/slim/Slim/Routing/Route.php(358): Slim\Handlers\Strategies\RequestResponse->__invoke(Array, Object(Slim\Http\ServerRequest), Object(Slim\Http\Response), Array)
#12 /home/xxx/html/Grocy/vendor/slim/slim/Slim/MiddlewareDispatcher.php(65): Slim\Routing\Route->handle(Object(Slim\Http\ServerRequest))
#13 /home/xxx/html/Grocy/vendor/slim/slim/Slim/MiddlewareDispatcher.php(65): Slim\MiddlewareDispatcher->handle(Object(Slim\Http\ServerRequest))
#14 /home/xxx/html/Grocy/vendor/slim/slim/Slim/Routing/Route.php(315): Slim\MiddlewareDispatcher->handle(Object(Slim\Http\ServerRequest))
#15 /home/xxx/html/Grocy/vendor/slim/slim/Slim/Routing/RouteRunner.php(68): Slim\Routing\Route->run(Object(Slim\Http\ServerRequest))
#16 /home/xxx/html/Grocy/middleware/LocaleMiddleware.php(16): Slim\Routing\RouteRunner->handle(Object(Slim\Http\ServerRequest))
#17 /home/xxx/html/Grocy/vendor/slim/slim/Slim/MiddlewareDispatcher.php(269): Grocy\Middleware\LocaleMiddleware->__invoke(Object(Slim\Http\ServerRequest), Object(Slim\Routing\RouteRunner))
#18 /home/xxx/html/Grocy/middleware/AuthMiddleware.php(76): Psr\Http\Server\RequestHandlerInterface@anonymous->handle(Object(Slim\Http\ServerRequest))
#19 /home/xxx/html/Grocy/vendor/slim/slim/Slim/MiddlewareDispatcher.php(269): Grocy\Middleware\AuthMiddleware->__invoke(Object(Slim\Http\ServerRequest), Object(Psr\Http\Server\RequestHandlerInterface@anonymous))
#20 /home/xxx/html/Grocy/vendor/slim/slim/Slim/Middleware/RoutingMiddleware.php(45): Psr\Http\Server\RequestHandlerInterface@anonymous->handle(Object(Slim\Http\ServerRequest))
#21 /home/xxx/html/Grocy/vendor/slim/slim/Slim/MiddlewareDispatcher.php(121): Slim\Middleware\RoutingMiddleware->process(Object(Slim\Http\ServerRequest), Object(Psr\Http\Server\RequestHandlerInterface@anonymous))
#22 /home/xxx/html/Grocy/vendor/slim/slim/Slim/Middleware/ErrorMiddleware.php(76): Psr\Http\Server\RequestHandlerInterface@anonymous->handle(Object(Slim\Http\ServerRequest))
#23 /home/xxx/html/Grocy/vendor/slim/slim/Slim/MiddlewareDispatcher.php(121): Slim\Middleware\ErrorMiddleware->process(Object(Slim\Http\ServerRequest), Object(Psr\Http\Server\RequestHandlerInterface@anonymous))
#24 /home/xxx/html/Grocy/middleware/CorsMiddleware.php(30): Psr\Http\Server\RequestHandlerInterface@anonymous->handle(Object(Slim\Http\ServerRequest))
#25 /home/xxx/html/Grocy/vendor/slim/slim/Slim/MiddlewareDispatcher.php(269): Grocy\Middleware\CorsMiddleware->__invoke(Object(Slim\Http\ServerRequest), Object(Psr\Http\Server\RequestHandlerInterface@anonymous))
#26 /home/xxx/html/Grocy/vendor/slim/slim/Slim/MiddlewareDispatcher.php(65): Psr\Http\Server\RequestHandlerInterface@anonymous->handle(Object(Slim\Http\ServerRequest))
#27 /home/xxx/html/Grocy/vendor/slim/slim/Slim/App.php(199): Slim\MiddlewareDispatcher->handle(Object(Slim\Http\ServerRequest))
#28 /home/xxx/html/Grocy/vendor/slim/slim/Slim/App.php(183): Slim\App->handle(Object(Slim\Http\ServerRequest))
#29 /home/xxx/html/Grocy/app.php(106): Slim\App->run()
#30 /home/xxx/html/Grocy/public/index.php(45): require_once('/home/xxx...')
#31 {main}
```

System info:
```
{
    "grocy_version": {
        "Version": "3.3.2",
        "ReleaseDate": "2022-11-12"
    },
    "php_version": "8.0.28",
    "sqlite_version": "3.27.2",
    "os": "Linux 4.19.0-23-amd64 #1 SMP Debian 4.19.269-1 (2022-12-20) x86_64",
    "client": "Mozilla\/5.0 (Windows NT 10.0; Win64; x64; rv:109.0) Gecko\/20100101 Firefox\/116.0"
}
```
			`
			`

**Comment by berrnd** [comment]
Downgrades are not supported, restore your backup.
