### ISSUE TITLE
404 when creating a new product from the Purchase menu

### ISSUE THREAD

**Issue by lukebo** [grocy/grocy#232]
Sorry, me again....
On the Demo-Server it works fine, but I get a 404, when creating a new product from the purchase workflow on my instance. Here is how:
1) Go to Purchase
2) Scan some unknown barcode
3) Hit A
4) Enter some Product Details and store. 
The URL http://xxxxxxx.xx/purchase?createdproduct=test is loded but runs into 404. However, the product was stored in the database. One needs to rescan the code and then assign it to a known product.

http://grocy.fritz.box/index.php/purchase?createdproduct=test works on the other hand.

I am running the current release with your second patch on issue #219. My apache requires ('DISABLE_URL_REWRITING', true) and the server points to the public folder.

Thanks for this awesome piece of software.

**Comment by berrnd** [comment]
Of course again a problem with relative URL handling and disabled URL rewriting...

Should be also fixed now.

I attached the patch from #219 combined with the fixes from https://github.com/grocy/grocy/commit/78a230c5d543dd54c060439696a0de291dfee8c3 backported to v2.3.0.

[grocy_patch_issue219-2-w232.zip](https://github.com/grocy/grocy/files/3143135/grocy_patch_issue219-2-w232.zip)
