### ISSUE TITLE
Feature Request: add an option to set `admin` account to "super" admin

### ISSUE THREAD

**Issue by Trainax** [grocy/grocy#2320]
Hello everyone, I'm a fairly new Grocy user. I would like to suggest adding an option to set the default `admin` account to "super" admin so that it cannot be modified by anyone else even if they have admin privileges. This could be useful in a company where there is a system administrator who uses the `admin` account to manage the system and there is, for example, also a boss with an admin account which he uses to create / delete / edit employee accounts.

**Example (purely theoretical)**

Suppose the application is being used to monitor the food stocks in a small internal company canteen. The users are:

| Username | First name | Last name | Role |
| :--- | :--- |  :--- | :--- |
| admin |  |  | System administrator |
| boss |  |  | Head of the company |
| employee1 |  |  | Chef |
| employee2 |  |  | Pantry supervisor |

In this use case I would like for the boss not to be able to modify / delete the `admin` account so that no matter what there is always an admin for the system while still being able to edit / create / delete employee accounts as needed.

What do you think? Thank you very much

**Comment by berrnd** [comment]
Grocy is a software to help managing your fridge and home, any business use case is out of scope of this project.

**Comment by Trainax** [comment]
>any business use case is out of scope of this project

I see, thank you. I was just giving a purely theoretical example that came to my mind (I didn't realize it was out of scope).

---

I would then like to put this feature request in more broad terms. I would simply like to ask if there could be a way to protect the `admin` account from accidental deletion / modification so that if the system admin (using an account with admin privileges which is separate from the standard `admin` account) somehow locks himself out there will always be the default `admin` account which can be used to restore admin privileges. This feature would be opt-in and I think could be implemented with a checkbox inside the `admin` profile management page where it could be specified if other admins can modify the account or not.

Thank you again and sorry if I'm missing something again, it is not my intention to be bothersome

**Comment by berrnd** [comment]
Again: The use case is your home. If you can't trust your family members for whatever reasons on the topic mentioned here, I guess Grocy is just not what you need.

And of course there [are technical ways to restore access](https://github.com/grocy/grocy/issues/608#issuecomment-599121975) if you've managed to lock you out. But just don't do that, less stressful and the like...

And if you just started using Grocy in your home (not in your canteen), please simply just try how everything practically goes in your daily life. Grocy is about solving / helping with practical problems, not about the theoretical ones nobody has at the end.

There is already a safety check which prevents deleting the last "admin user account". There is another safety prompt when you try to remove the last "admin permission". What else is practically needed?

And furthermore practically speaking: When you're the boss at home and everyone else should just being able to use Grocy, why is there even a need that anyone else has the "admin permission"?

**Comment by Trainax** [comment]
>And if you just started using Grocy in your home (not in your canteen), please simply just try how everything practically goes in your daily life. Grocy is about solving / helping with practical problems, not about the theoretical ones nobody has at the end.

I've been using Grocy in my home for about 1½ months and I'm studying how to incorporate it even more in my routine to make pantry management in various locations within my home more efficient.

My configuration is:

- Grocy hosted using Docker on my home server
- Grocy web interface used to manage things and have a general overview of the various quantities of food in the pantry
- Grocy Android app to scan / consume products and to check info on the go

>There is already a safety check which prevents deleting the last "admin user account". There is another safety prompt when you try to remove the last "admin permission". What else is practically needed?

I would like for the `admin` account to be:
- not removable
- not modifiable by anyone else with an admin account but the `admin` account itself
- (optionally) locked in its permissions: there should not be an option to remove the admin rights from the `admin` account (the "permissions" tab should not be modifiable)

so that there's always an admin account to be used. I understand these could be some pretty serious limitations for some users, so I suggest for everything to be opt-in only via config file / checkbox in the web UI.

>When you're the boss at home and everyone else should just being able to use Grocy, why is there even a need that anyone else has the "admin permission"?

I will explain the real-life situation which prompted this feature request to begin with.

About a week ago a friend came to my house and saw me using Grocy to check if I had another box of rice in the pantry downstairs. I explained to him what Grocy is and he said he is interested and would like to try it himself. Since he already has a Linux mini PC in the attic to manage CCTV cameras I tought I could try to set up a Docker instance in his home to make him try using Grocy with his phone (he is a Mac-only user so [Grocy Desktop](https://github.com/grocy/grocy-desktop) is not an option).

My idea was to set a Docker instance up, create another admin account for him and show him how to use the web interface and the phone app. My idea was to give him an admin account so that he could create accounts for his wife / sons, create and delete accounts for guests if they want to try it, reset passwords if needed (since there isn't an automated password recovery procedure that I'm aware of) and manage everything in his instance if he desires without the need of calling me.

**The "problem"**

He likes doing experiments with whatever he comes into his hands, and I'm afraid he might lock himself out ignoring all the warnings and everything else and so I would have to remote in to copy the ZIP you have mentioned yesterday to restore admin access, while if I was sure he couldn't delete / modify the `admin` account even if he wanted to I'm sure I could always simply log into the `admin` account using the web interface and restore admin permissions to his account, do what is necessary or what I'm asked to do (which I personally think it's simpler than the `admin` account recovery procedure you have illustrated yesterday since I have to do everything remotely). Considering he has done something similar in the past (with another app) and I was then called to solve it I would like to put some measures into place to ensure that I would be able to recover everything as simply as possible if he manages to lock himself out again.

I understand this is a personal problem, but I'm sure the `admin` account protection functionality could be applied for many more use cases.

A solution could simply be not to give anyone an account with admin privileges and to create myself all the accounts for his family, but that would mean having to connect each time someone loses / wants to change his / her password or if he wants to create / delete an account for one of his guests and that would not be desireable for me personally...

Yesterday I used the *small internal company canteen* example simply because in my mind it was easier to explain than all of this.

Thank you again for your patience, your time and your reply

**Comment by berrnd** [comment]
Whatever, I already made the decision that this will not be build, since, as you said, it's a very personal problem.

Creating backups and restoring them when doing "expirements" is just another more than simple option to prevent disasters.

But this is Open Source, feel free to build that feature yourself if you think it's the one Grocy needs most.
