### ISSUE TITLE
Feature Request: Make quick open use the quantity unit of stock

### ISSUE THREAD

**Issue by luisneto** [grocy/grocy#2329]
Version 4.0.0 introduced the 'Default quantity unit consume' and the 'Quick consume amount' button of each product has been changed to be displayed using quantity unit, which is very useful.

However, the 'Quick open' button values are now also being displayed using this quantity unit. 
In my opinion, this should not have changed - it should be expressed using the quantity unit of stock, because:

- The act of opening a product relates to the unit used for its stock, rather than its consumption. 
- Having it expressed using the 'Default quantity unit consume' is confusing. 
- The 'Stock entries', 'Stock journal' and 'Stock journal summary' correctly use the quantity unit of stock to indicate the quantity that has been opened, so the 'Quick open' button in the 'Product Overview' is not being consistent with this.

To give an example: it is very useful to use packs/cans/tins/etc as the quantity unit of stock, and consume in grams. When I open something, I am opening the container, rather than opening 'X grams'.

**Comment by berrnd** [comment]
I'm not going to change everything back and forth with every release from now on. What fits best is dependent on your personal use case and not law.

What's the big problem of simply setting the "Default quantity unit consume" to the desired one? It's a default, it's not forbidden or prevented to consume by any other product related unit. "Quick consuming" in Packs and consuming in Grams is practically possible.

&nbsp;
> The 'Stock entries', 'Stock journal' and 'Stock journal summary' correctly use the quantity unit of stock to indicate the quantity that has been opened, so the 'Quick open' button in the 'Product Overview' is not being consistent with this.

The opened amount is related to the there used/displayed unit, nothing is inconsistent.

**Comment by luisneto** [comment]
@berrnd, none of what I wrote was about changing anything related to the units of consumption. 
What I wrote is about the quick open button.

**Comment by berrnd** [comment]
> What I wrote is about the quick open button.

Sure, I'm able to read and got that - sounds like you haven't read my answer. I'm used to repeat myself over and over again here lately, so no problem:

I'm not going to change everything back and forth with every release from now on. What fits best is dependent on your personal use case and not law.

What's the big problem of simply setting the "Default quantity unit consume" to the desired one? It's a default, it's not forbidden or prevented to consume by any other product related unit. "Quick consuming" in Packs and consuming in Grams is practically possible.

&nbsp;
> The 'Stock entries', 'Stock journal' and 'Stock journal summary' correctly use the quantity unit of stock to indicate the quantity that has been opened, so the 'Quick open' button in the 'Product Overview' is not being consistent with this.

The opened amount is related to the there used/displayed unit, nothing is inconsistent.

**Comment by luisneto** [comment]
> sounds like you haven't read my answer.

I read your answer, and what you wrote there is precisely the interpretation I make from your response: it sounds like you didn't properly read my suggestion/request.

You are answering as if I am requesting changes to the units of consumption.
Where did I write that?!

> What's the big problem of simply setting the "Default quantity unit consume" to the desired one?
It is the desired one! 

> It's a default, it's not forbidden or prevented to consume by any other product related unit. "Quick consuming" in Packs and consuming in Grams is practically possible.

I didn't write anything about changing the consumption!

**Comment by berrnd** [comment]
Not the first we don't understand each other here, but whatever - all have been said, nothing will be changed back (and forth again and again).

**Comment by berrnd** [comment]
> To give an example: it is very useful to use packs/cans/tins/etc as the quantity unit of stock, and consume in grams. When I open something, I am opening the container, rather than opening 'X grams'.

To conclude that once again taking this practical example: That's already (and not only since v4.0.0) possible when the product has a relation to Grams and Packs. Opening and consuming is possible by every product related unit. Default's are just used as defaults at the corresponding places.

And just also once again: A default doesn't mean it's not possible to use any other (product related) unit, it's just a default.

**Comment by berrnd** [comment]
Follow-up: I created #2427 to describe ideas for this topic using a more generic approach, feel free to add further ideas there if you think there is still something missing, not already covered by what's described there.
