### ISSUE TITLE
Function proposal: Pharmaceuticals

### ISSUE THREAD

**Issue by lukebo** [grocy/grocy#233]
Hi,
i got a function proposal:

What about ERPing pharmaceuticals. Never use them and if needed, they are expired. On could also archive the leaflets. I think most of that is already there for food. Maybe it would basically reduce to implementing some kind of metacategory: Food, Pharmaceuticals, Pets, Plants, whatever, each with its own menu on the left.

Best regards

**Comment by berrnd** [comment]
I personally already do this, and just use normal products in an own product group - is that not enough?

**Comment by BlizzWave** [comment]
I also do the same as you Bernd

**Comment by lukebo** [comment]
I do it currently the same way. I was thinking about introducing pharmaceuticals as separate category, because one could possibly make use of alternative data(fields), e.g. agent. store information about recommendations by some physician, store the leaflets, and so on. Of course, one could also store this information in the currently available fields. Just thinking.....

**Comment by berrnd** [comment]
It's now possible to add any custom field to existing objects (products/chores/recipes/...), not yet released, see #176 or try it on the [pre-release demo](https://demo-prerelease.grocy.info).

So this not includes creating complete own objects, you would still need to use products. If you have an idea how custom objects could work (from UI side is enough), similar to the new Userfields, feel free to open a new issue.

**Comment by berrnd** [comment]
I thought about a generic way to add custom objects based on the new Userfields feature, and I think it could work. Will be tracked in #242, feel free to add further ideas there.

**Comment by berrnd** [comment]
Just wanted to let you know here that I just finished implementing custom objects/lists. :)

See https://github.com/grocy/grocy/issues/242#issuecomment-532706949.

So you can start _ERPing pharmaceuticals, pets, plants, whatever_... :D
