### ISSUE TITLE
Bug: Can't consume any more product since the latest update 4.0.3

### ISSUE THREAD

**Issue by dotnjet** [grocy/grocy#2330]
I just updated to 4.0.3 and now I can't consume any products. It does not work on the iPhone App, as well as via the web app. It might relate to quantity units.

**Comment by berrnd** [comment]
I can't help without having a reproducible example or at least concrete error messages (as also mentioned on the issue template).

It works generally, so most likely a problem specific problem relate to your setup / data / whatever.
