### ISSUE TITLE
Prices for recipes are not correct

### ISSUE THREAD

**Issue by Tuxibaby** [grocy/grocy#2331]
Hallo,

I liked that the reception is not stimulating the final price and the price of the individual products. The sum is much high. The quantities are stored in the products.
an example.:
Sausage-pasta pan € 541.16
Ingredients
- 100 g Rhönland macaroni stock is sufficient for € 229.00
- 1 piece of pepper € 0.52
 - 70 g corn stock is sufficient for € 84.00
 - 10 g onions stock is sufficient for € 11.90
 - 90 g Viennese sausages stock is sufficient for € 215.10
 - 5 g new tomato paste stock is sufficient for € 0.02
- 1 g rose-paprika stock is sufficient for € 0.03
 - 10 g parsley stock is sufficient to € 0.52
- 1 g curry stock is sufficient for € 0.04 0
- 5 ml Bornsenf stock is sufficient for € 0.02
 There is an error there?

**Comment by berrnd** [comment]
Jetzt also doch Englisch? Cool, aber warum brauchts einen Doppelpost, was soll das bringen, außer das es mich nervt?

_Double post of https://www.reddit.com/r/grocy/comments/1690byo_

I'm unable to look behind screenshots or simple descriptions, [private demo instances](https://www.reddit.com/r/grocy/comments/jwnk9b) are there to reproduce complex scenarios - provide a reproducible example if you want to have that looked into, as also mentioned on the issue template.

The rest has been already said on the above linked double post: The math is correct, most likely you simply have fucked up your purchase prices of the good Wieners and Macaronis (Grocy is generally based around [GIGO](https://en.wikipedia.org/wiki/Garbage_in,_garbage_out), so Scheiße rein = Scheiße raus - it's impossible to magically guess that Wieners don't cost ~220 EUR per 100 Grams).
