### ISSUE TITLE
Add barcode as a column to master data / products page

### ISSUE THREAD

**Issue by lukebo** [grocy/grocy#234]
Hi,
i got another function proposal:

 On a long perspective, could it be interestning to have some statistics? How many is consumed of what? Which products do spoil on a regular basis? Spent money and so on.

By the way, it would be cool, if one could search in the inventory list not only by name but also with barcodes.

Keep up the awesome work!

**Comment by berrnd** [comment]
Statistics and everyhting related is tracked in #64 and #65. Feel free to add your ideas there.

Of course we can add the barcode column to the products list of master data, then it would be searchable by the normal serach field above the table. I will change the issue title to track this here.

(Or you could also just use any of the purchase/inventory/consume pages if you quickly want to check/lookup a barcode...)
