### ISSUE TITLE
Bug: iOS App suddenly cannot connect to server due to "API error detected"

### ISSUE THREAD

**Issue by kennethpiu** [grocy/grocy#2345]
App suddenly became cannot connect to server.
Web portal is still workable.
![IMG_2C466CF96250-1](https://github.com/grocy/grocy/assets/36800815/51ab4aa2-f0ad-40d7-9bf8-003f3a015610)

try domain.com/api
returns below:
{"error_message":"Not found.","error_details":{"stack_trace":"#0 \/app\/www\/vendor\/slim\/slim\/Slim\/Middleware\/RoutingMiddleware.php(44): Slim\\Middleware\\RoutingMiddleware->performRouting()\n#1 \/app\/www\/vendor\/slim\/slim\/Slim\/MiddlewareDispatcher.php(121): Slim\\Middleware\\RoutingMiddleware->process()\n#2 \/app\/www\/vendor\/slim\/slim\/Slim\/Middleware\/ErrorMiddleware.php(76): Psr\\Http\\Server\\RequestHandlerInterface@anonymous->handle()\n#3 \/app\/www\/vendor\/slim\/slim\/Slim\/MiddlewareDispatcher.php(121): Slim\\Middleware\\ErrorMiddleware->process()\n#4 \/app\/www\/middleware\/CorsMiddleware.php(30): Psr\\Http\\Server\\RequestHandlerInterface@anonymous->handle()\n#5 \/app\/www\/vendor\/slim\/slim\/Slim\/MiddlewareDispatcher.php(269): Grocy\\Middleware\\CorsMiddleware->__invoke()\n#6 \/app\/www\/vendor\/slim\/slim\/Slim\/MiddlewareDispatcher.php(65): Psr\\Http\\Server\\RequestHandlerInterface@anonymous->handle()\n#7 \/app\/www\/vendor\/slim\/slim\/Slim\/App.php(199): Slim\\MiddlewareDispatcher->handle()\n#8 \/app\/www\/vendor\/slim\/slim\/Slim\/App.php(183): Slim\\App->handle()\n#9 \/app\/www\/app.php(106): Slim\\App->run()\n#10 \/app\/www\/public\/index.php(45): require_once('...')\n#11 {main}","file":"\/app\/www\/vendor\/slim\/slim\/Slim\/Middleware\/RoutingMiddleware.php","line":76}}

**Comment by berrnd** [comment]
None of the community contributed apps/tools/integrations are maintained here.

&nbsp;
> try domain.com/api
> returns below:
> {"error_message":"Not found."

Sounds like a configuration problem, or you did an upgrade recently and ignored [README which mentions to empty the `data/viewcache` directory](https://github.com/grocy/grocy#how-to-update). Not doing that can lead to invalid routes.
