### ISSUE TITLE
Various Product Types

### ISSUE THREAD

**Issue by pixbalance** [grocy/grocy#2351]
I like the "consume and purchase" principle and would also like to use it for other stuff like electronic components. So far I could not use the items in custom entities for "use and purchase".

Is it possible to add various product types by just duplicating the current one for food and hide the inputs the product type does not need? It would also be good to change the mandatory fields.

**Comment by berrnd** [comment]
Grocy's stock management features are about you're fridge - you're simply looking for another tool and not only one was proposed [there](https://www.reddit.com/r/grocy/comments/16ubb92) just a couple of days ago.

I also use my personal Grocy instance to not only track food and (and a lot of others based on reported user stories) it's no problem to simply do so. Just ignore the due date (and set "Default due days" for the product accordingly) and the rest.

&nbsp;
> hide the inputs the product type does not need

You can customize everything to your very end without having to maintain a fork by utilizing [custom JS](https://github.com/grocy/grocy#adding-your-own-css-or-js-without-to-have-to-modify-the-application-itself).
