### ISSUE TITLE
Feature Request: Option to change date format in settings

### ISSUE THREAD

**Issue by inson1** [grocy/grocy#2356]
Right now its yyyy-mm-dd. It would be great to have option to write my own. Or just select one format from selectbox.

**Comment by berrnd** [comment]
Duplicate of #1348 (and #2220, and #2226) - please check existing requests before opening new ones.

This is a general design decision and won't be changed and that's also noted in README: https://github.com/grocy/grocy#input-shorthands-for-date-fields

**Comment by inson1** [comment]
@berrnd sorry for the duplicate
