### ISSUE TITLE
Feature Request: Add Equipment to a Task/Chore

### ISSUE THREAD

**Issue by Ray22113** [grocy/grocy#2365]
We are using this software to manage our boat while we circumnavigate.

We have all of our (extensive) equipment listed and their associated manuals added to the equipment list.  We assign chores or tasks such as "Adjust main engine valve clearance" or "service anchor windlass".  

It would be a great convenience if in the chore or task, we can assign equipment to that chore or task.  That would allow easy and quick access to the manuals of the equipment being addressed in the chore or task.

**Comment by berrnd** [comment]
Duplicate of #1558 - please check existing requests before opening new ones.
