### ISSUE TITLE
Bug: bad mobile rendering for equipment manuals

### ISSUE THREAD

**Issue by Ray22113** [grocy/grocy#2366]
PDF files uploaded as equipment manuals don’t render in iOS safari. 
![IMG_2236](https://github.com/grocy/grocy/assets/36516191/9a1c694e-8c90-412d-ad40-cfc88b92db1d)

**Comment by berrnd** [comment]
Please provide a reproducible example ([persistent demo instances](https://www.reddit.com/r/grocy/comments/jwnk9b) are there for that, as mentioned on the issue template).

Beside that, only Chrome/Edge and Firefox are supported and therefore will receive fixes/optimizations/workarounds, when required, from my side (as [mentioned in README](https://github.com/grocy/grocy#platform-support)).
