### ISSUE TITLE
Feature Request: Calendar: Different colors for due products, chores, etc.

### ISSUE THREAD

**Issue by maxata62** [grocy/grocy#2368]
Hi,

It is possible to have different color in calendar ?

By types (Products, task, chores, meal plan, etc..) or maybe by "a magic userfield" like calendar_color.

Maybe it's possible with a custom css but I don't know how to do it.
I'm new to grocy but I don't think this silk function is available today.

Best Regards,
Max.

**Comment by berrnd** [comment]
Of course that's technically possible (either by implementing the corresponding options or by custom CSS) and no, it's not possible today, otherwise it would be possible (lol).

**Comment by maxata62** [comment]
Hi, you can see here an example to do that in CalendarService.php : 

![image](https://github.com/grocy/grocy/assets/149700479/b6b59785-1df7-44a5-8f01-ee41bcbd96c2)

sources : 
https://fullcalendar.io/docs/eventColor
https://fullcalendar.io/docs/event-colors-demo
![image](https://github.com/grocy/grocy/assets/149700479/40eb02bd-3fbf-47e8-91ad-5802007c7d2c)

Regards,
Max.

**Comment by berrnd** [comment]
Your provided links doesn't reference the version of FullCalendar Grocy uses - but no worries, I've built all that stuff here so there is a tiny little chance I'll manage also getting that to work, once I start working on it - or anyone else, if you think the needed magic needs to be right there, why not simply start implementing it right away.

**Comment by maxata62** [comment]
> Your provided links doesn't reference the version of FullCalendar Grocy uses - but no worries, I've built all that stuff here so there is a tiny little chance I'll manage also getting that to work, once I start working on it - or anyone else, if you think the needed magic needs to be right there, why not simply start implementing it right away.

Hi, of course FullCalendar version is different, i just wanted to find the "best" technical solution to add this feature simply.

I have tried to apply this change in my grocy platform, and this seems to work.
![image](https://github.com/grocy/grocy/assets/149700479/537f7699-cbb6-49c8-b501-ab04186e70a1)

I'm not a professionaly programmer and i don't want destroy your work with my bad programming skills.
Also i don't want to impose a new fonctionality that you wouldn't want to add in grocy.

Personally I think it's a good feature because it improves the readability of the calendar.

In my way, i will add this feature in my grocy plateform.
If you want, I will share my custom code with you if you want to take inspiration from it to add this function natively in the future

**Comment by berrnd** [comment]
Do whatever you want and don't get me wrong, but inspiration on such a simple thing is not needed - looking and understanding what you've thought probably takes more time than simply implementing it (even this conversion took probably longer than that, lol).

And of course it's not a bad feature to add, that's why I haven't closed this Feature Request = it was accepted. But it's definitely also not the most important one, hence I'm not going to work on it next, when I once came book to work on Grocy at all.

**Comment by berrnd** [comment]
Changelog excerpt for this:

- _The different event types (due products, chores, tasks and so on) can now have different colors_
  - => _New button "Configure colors" on the calendar page to configure these colors (top right corner)_

**Comment by maxata62** [comment]
Hi Berrnd,

Thank you for this new feature. I'm sorry but there was no need to add it so quickly. As you say, there are other more important things to do first :)

Also, I have another improvement idea for this function.

As you see below in my very bad and static code, for tasks and chores, each user has a personal color. A default color exist for task no assigned or user without personal color : 
![image](https://github.com/grocy/grocy/assets/149700479/00289a58-f445-4105-a8ed-fe1e518fea02)

**Comment by berrnd** [comment]
Please keep it to one topic per request, everything else is untrackable.

What you mentioned last is already tracked in #990.

**Comment by maxata62** [comment]
i'm sorry, I don't know everything about github and how it works. my account is 2 days old ;)
