### ISSUE TITLE
Bug: Quantity Unit Only shows 1 choice after Upgrade

### ISSUE THREAD

**Issue by tebriel** [grocy/grocy#2369]
## Install information

I just upgraded from 3.3.2 to 4.0.3 (replacing all files except the data directory), I visited the `/` path to ensure any database migrations were run (how do I verify this for debugging?)

## Problem

Existing products have only one Unit type in all dropdowns

<details>
<summary>Example Screenshot</summary>

![Image](https://github.com/grocy/grocy/assets/821688/c0dd3785-cb04-465d-8882-853942b7018c)

</details>

New products created show all items even after saving and re-entering to edit.

<details>
<summary>Example Screenshot</summary>

![Image](https://github.com/grocy/grocy/assets/821688/aa2ecad0-31ff-469d-bc12-3dc585d048b1)

</details>

Because of this I cannot update old products that have the wrong unit type on them.

## Extra

What more information can I provide? Is there any kind of debug output I can provide?

Thanks for looking!

**Comment by tebriel** [comment]
The last entry in the `migrations` table is:

`234|2023-11-03 15:52:44`

**Comment by tebriel** [comment]
I've attempted to edit an item, save it, then attempt to change the unit again hoping this might refresh some connections, but the list is still limited only to the current unit.

**Comment by berrnd** [comment]
That's not a a bug, not a surprise, no connections need to be refreshed (whatever that should be), no more information and of course no "debug output" is needed to explain what's going on:

Every amount and price in Grocy is stored related to the product's quantity unit stock. So when you want to change that e.g. from "Pack" to "Piece", Grocy needs to know how much Pieces a Pack contains - it's impossible to magically guess that. All quantity units, where a direct or indirect relation to the product's QU stock exists, are shown / possible to be used for the product after it was once created.

So simply tell Grocy that, by either creating a global or product specific corresponding conversion, and it this will resolve on it's own like it's already christmas.

In any other case, please provide a reproducible example ([persistent demo instances ](https://www.reddit.com/r/grocy/comments/jwnk9b)are there for that) as mentioned on the issue template - sorry, but I'm unable to look behind screenshots guessing all the required details.

**Comment by tebriel** [comment]
Further debugging (I don't know php but trying to be helpful). It looks like maybe the cache table isn't populated like we'd want? https://github.com/grocy/grocy/blob/fdf5559c25f7020221f59c8c1c89daf243b38790/controllers/StockController.php#L195 is a very different query from what I'd expect.

This led me to an idea for a workaround (that works).
Create a conversion from the current type (`Carton` for example) to the desired type (`Bottle` for exmaple): 1 `Carton` == 1 `Bottle`. Save, now I can swap the types and delete the conversion.

**Comment by tebriel** [comment]
> In any other case, please provide a reproducible example ([persistent demo instances ](https://www.reddit.com/r/grocy/comments/jwnk9b)are there for that) as mentioned on the issue template - sorry, but I'm unable to look behind screenshots guessing all the required details.

Couldn't figure out what was going on to produce an example. Your explanation gives me the understanding though, the reason was I have stock of this item, so changing the type without having a conversion set up means that grocy wouldn't know the units of the changed stock item.

Since there isn't stock of the "new" item, it's freely changeable to any type until it gets stock.

Thanks for your quick response.
