### ISSUE TITLE
Feature Request: Import Recipies by URL

### ISSUE THREAD

**Issue by LennardPlay** [grocy/grocy#2370]
I really like all the advanced management inside Grocy, but I think recipe creation is a bit tedious, so I would love a recipe importer.
Currently, I am using Samsung Foods as a recipe manager, and honestly I love it. It's so great to just paste the URL to a recipe or YouTube Video into the software and automatically get the ingredients, picture and name of the recipe. 

The open source project www.recipesage.com already has a recipe importer so maybe it's possible to reuse some of the code.

**Comment by berrnd** [comment]
Please be so kind and do a little search beforehand - duplicate of #210 (and #1909, and #1156, and #1798, and #1909, and #286) - maybe have a look at [recipe-buddy](https://github.com/georgegebbett/recipe-buddy).
