### ISSUE TITLE
Bug: ReverseProxyAuthMiddleware can login but interaction with the page broken

### ISSUE THREAD

**Issue by RagingCub** [grocy/grocy#2372]
When using ReverseProxyAuthMiddleware, the page logins as expected, but all calls from within the page result in error codes 500 with the following content:
```json
{
  "error_message": "ReverseProxyAuthMiddleware: REMOTE_USER env variable is invalid",
  "error_details": {
    "stack_trace": "#0 \/app\/www\/middleware\/AuthMiddleware.php(53): Grocy\\Middleware\\ReverseProxyAuthMiddleware->authenticate()\n#1 \/app\/www\/packages\/slim\/slim\/Slim\/MiddlewareDispatcher.php(269): Grocy\\Middleware\\AuthMiddleware->__invoke()\n#2 \/app\/www\/packages\/slim\/slim\/Slim\/Middleware\/RoutingMiddleware.php(45): Psr\\Http\\Server\\RequestHandlerInterface@anonymous->handle()\n#3 \/app\/www\/packages\/slim\/slim\/Slim\/MiddlewareDispatcher.php(121): Slim\\Middleware\\RoutingMiddleware->process()\n#4 \/app\/www\/packages\/slim\/slim\/Slim\/Middleware\/ErrorMiddleware.php(76): Psr\\Http\\Server\\RequestHandlerInterface@anonymous->handle()\n#5 \/app\/www\/packages\/slim\/slim\/Slim\/MiddlewareDispatcher.php(121): Slim\\Middleware\\ErrorMiddleware->process()\n#6 \/app\/www\/middleware\/CorsMiddleware.php(27): Psr\\Http\\Server\\RequestHandlerInterface@anonymous->handle()\n#7 \/app\/www\/packages\/slim\/slim\/Slim\/MiddlewareDispatcher.php(269): Grocy\\Middleware\\CorsMiddleware->__invoke()\n#8 \/app\/www\/packages\/slim\/slim\/Slim\/MiddlewareDispatcher.php(65): Psr\\Http\\Server\\RequestHandlerInterface@anonymous->handle()\n#9 \/app\/www\/packages\/slim\/slim\/Slim\/App.php(199): Slim\\MiddlewareDispatcher->handle()\n#10 \/app\/www\/packages\/slim\/slim\/Slim\/App.php(183): Slim\\App->handle()\n#11 \/app\/www\/app.php(112): Slim\\App->run()\n#12 \/app\/www\/public\/index.php(45): require_once('...')\n#13 {main}",
    "file": "\/app\/www\/middleware\/ReverseProxyAuthMiddleware.php",
    "line": 37
  }
}
```

**Comment by berrnd** [comment]
Your reverse proxy needs to pass the `REMOTE_USER` header / server environment variable with every (successfully authenticated) request, not only for the "first login request" itself.

Code ref where this error message originates from:

https://github.com/grocy/grocy/blob/dc05476d09e40f6e4007e39cf31ac6f66c24eb30/middleware/ReverseProxyAuthMiddleware.php#L33-L38

So this clearly indicates that `REMOTE_USER` header / variable was empty - please triple check and rectify that and it will work.

**Comment by RagingCub** [comment]
Unfortunately, nothing seemed to be the issue in nginx, I switched back to using the default authentication :(

**Comment by berrnd** [comment]
The above mentioned code ref is pretty clear about what happened, and it works for more than a lot others - all that just not leads to a general problem / Bug. Otherwise provide a full reproducible example (so the full nginx config or whatever is needed to get that) and I will dig into it, as always.
