### ISSUE TITLE
Bug: Error when saving an equipment PDF instruction manual

### ISSUE THREAD

**Issue by iikkamerilainen** [grocy/grocy#2377]
Hi, I'm running the Grocy Home Assistant add-on so don't know if the bug is with Grocy or the add-on, but when selecting a PDF instruction manual for an equipment and saving, I get an "error while saving" notification which opens the following error details popup:

```
Error details
"\r\n\r\n\r\n

413 Request Entity Too Large
\r\n
nginx
\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n"

```
The PDF isn't very large, it's 3386KB. When trying to view the equipment's instruction manual after this, it shows:

`{"error_message":"File not found","error_details":{"stack_trace":"#0 \/var\/www\/grocy\/packages\/slim\/slim\/Slim\/Handlers\/Strategies\/RequestResponse.php(38): Grocy\\Controllers\\FilesApiController->ServeFile()\n#1 \/var\/www\/grocy\/packages\/slim\/slim\/Slim\/Routing\/Route.php(358): Slim\\Handlers\\Strategies\\RequestResponse->__invoke()\n#2 \/var\/www\/grocy\/packages\/slim\/slim\/Slim\/MiddlewareDispatcher.php(65): Slim\\Routing\\Route->handle()\n#3 \/var\/www\/grocy\/middleware\/JsonMiddleware.php(13): Slim\\MiddlewareDispatcher->handle()\n#4 \/var\/www\/grocy\/packages\/slim\/slim\/Slim\/MiddlewareDispatcher.php(168): Grocy\\Middleware\\JsonMiddleware->__invoke()\n#5 \/var\/www\/grocy\/packages\/slim\/slim\/Slim\/MiddlewareDispatcher.php(65): Psr\\Http\\Server\\RequestHandlerInterface@anonymous->handle()\n#6 \/var\/www\/grocy\/packages\/slim\/slim\/Slim\/Routing\/Route.php(315): Slim\\MiddlewareDispatcher->handle()\n#7 \/var\/www\/grocy\/packages\/slim\/slim\/Slim\/Routing\/RouteRunner.php(68): Slim\\Routing\\Route->run()\n#8 \/var\/www\/grocy\/middleware\/LocaleMiddleware.php(16): Slim\\Routing\\RouteRunner->handle()\n#9 \/var\/www\/grocy\/packages\/slim\/slim\/Slim\/MiddlewareDispatcher.php(269): Grocy\\Middleware\\LocaleMiddleware->__invoke()\n#10 \/var\/www\/grocy\/middleware\/AuthMiddleware.php(77): Psr\\Http\\Server\\RequestHandlerInterface@anonymous->handle()\n#11 \/var\/www\/grocy\/packages\/slim\/slim\/Slim\/MiddlewareDispatcher.php(269): Grocy\\Middleware\\AuthMiddleware->__invoke()\n#12 \/var\/www\/grocy\/packages\/slim\/slim\/Slim\/Middleware\/RoutingMiddleware.php(45): Psr\\Http\\Server\\RequestHandlerInterface@anonymous->handle()\n#13 \/var\/www\/grocy\/packages\/slim\/slim\/Slim\/MiddlewareDispatcher.php(121): Slim\\Middleware\\RoutingMiddleware->process()\n#14 \/var\/www\/grocy\/packages\/slim\/slim\/Slim\/Middleware\/ErrorMiddleware.php(76): Psr\\Http\\Server\\RequestHandlerInterface@anonymous->handle()\n#15 \/var\/www\/grocy\/packages\/slim\/slim\/Slim\/MiddlewareDispatcher.php(121): Slim\\Middleware\\ErrorMiddleware->process()\n#16 \/var\/www\/grocy\/middleware\/CorsMiddleware.php(27): Psr\\Http\\Server\\RequestHandlerInterface@anonymous->handle()\n#17 \/var\/www\/grocy\/packages\/slim\/slim\/Slim\/MiddlewareDispatcher.php(269): Grocy\\Middleware\\CorsMiddleware->__invoke()\n#18 \/var\/www\/grocy\/packages\/slim\/slim\/Slim\/MiddlewareDispatcher.php(65): Psr\\Http\\Server\\RequestHandlerInterface@anonymous->handle()\n#19 \/var\/www\/grocy\/packages\/slim\/slim\/Slim\/App.php(199): Slim\\MiddlewareDispatcher->handle()\n#20 \/var\/www\/grocy\/packages\/slim\/slim\/Slim\/App.php(183): Slim\\App->handle()\n#21 \/var\/www\/grocy\/app.php(112): Slim\\App->run()\n#22 \/var\/www\/grocy\/public\/index.php(45): require_once('...')\n#23 {main}","file":"\/var\/www\/grocy\/controllers\/FilesApiController.php","line":67}}
`

**Comment by iikkamerilainen** [comment]
When I remove some of the PDF pages to make the file smaller, it works, so looks like a size limit issue. PDFs can get pretty large.

**Comment by berrnd** [comment]
Grocy doesn't not limit anything in any way, but your webserver / PHP runtime maybe does, based on its configuration - so have a look there.

Has also been reported for the Home Assistant integration (none of the community contributed apps / integrations / etc.) are maintained here: https://github.com/hassio-addons/addon-grocy/issues/9

Or here: https://github.com/grocy/grocy/issues/1258

Or there: https://www.reddit.com/r/grocy/comments/13aj4p2

Seems like your search is broken as hell (again).

**Comment by iikkamerilainen** [comment]
Wow, rude. Maybe a less janky error message would help direct your users to the right forum.

**Comment by berrnd** [comment]
> Maybe a less janky error message would help direct your users to the right forum.

That error message is from your used webserver named NGINX, so feel free to report that there. And you're welcome. And bye.
