### ISSUE TITLE
Bug: [Hassio] Create product from Inventory screen takes you to a 404 page

### ISSUE THREAD

**Issue by igorsantos07** [grocy/grocy#2379]
# Problem/Motivation
When you create a product from the Inventory screen, it continues into a 404 page.
I _think_ this happens somewhere else as well, but I can't remember right now the other screen.

## Expected behavior
I tested this in the live Grocy demo and it takes you back to the Inventory page, as expected. I'm not sure if the problem is because in HA it runs on a subpath.

## Actual behavior
It looks like a root path problem; the redirect in my instance goes to `http://hass.local:8123/api/hassio_ingress/tBExf64mMbmSzXstfKLypj9J46CeBeoT1HMJZ-DIgX4//api/hassio_ingress/tBExf64mMbmSzXstfKLypj9J46CeBeoT1HMJZ-DIgX4/inventory?flow=InplaceNewProductWithName&&product-name=teste%202` (note the repeated `/api/hassio_ingress`)

## Steps to reproduce
1. go to Inventory
2. write a non-existing product on the first field
3. press enter
4. a popup shows up; select "add as new product"
5. fill in any required fields on the "new product" screen
6. press "save & continue"
7. get sent to a 404 page

## Proposed changes
Although this only happens on the HA add-on, I guess it's a problem of redirecting to a relative path?

**Comment by berrnd** [comment]
> I tested this in the live Grocy demo and it takes you back to the Inventory page, as expected.

Then it can be of course not a bug and is more a configuration issue related to URLs.

The mentioned add-on (which is not maintained here, like every community contributed app / tool / integration) even does [some special patches](https://github.com/hassio-addons/addon-grocy/blob/main/grocy/rootfs/patches/fix_braindamage.patch) in that area, for whatever reason.

**Comment by igorsantos07** [comment]
Lol right, "of course", "whatever reason" :+1:

**Comment by berrnd** [comment]
Yes, very lol. Then simply provide a reproducible example, using no external integrations, and I dig into, as always and since years and for free.

That's also mentioned on the issue template, we talked about reading just in another thread here, lol again.

**Comment by igorsantos07** [comment]
lol now you got me, I skimmed through it but indeed skipped the last topic, since I had already tried to reproduce it in the public demo. It might be more helpful if you make these checkboxes instead.

You may notice I used another template, because I started reporting it to the add-on and, while writing, realized it could be a relative path issue. I guess it is not, indeed, because for whatever reason, people that used Grocy had to patch it for it to work in another environment and didn't patch it properly.
