### ISSUE TITLE
Enhancement: Render task/battery/product instead of `1 product`

### ISSUE THREAD

**Issue by ASMfreaK** [grocy/grocy#238]
I *think*, it would be nice to have the only product/task/battery show name, not `1 product/task/battery`. 
Somthing like `Task "write good issues" is overdue` instead of `1 task is overdue`.

**Comment by berrnd** [comment]
Would maybe just make the yellow/red bars on the top of the overview pages to wide - also depends on the screen size, but currently they are most of the time in a single line on "normal" screens...

**Comment by berrnd** [comment]
I decided to not add this, as it would make the bars on top of the overview pages really to big...

![grafik](https://user-images.githubusercontent.com/2161815/65165734-a787cb00-da3f-11e9-85ce-7655359d093c.png)
