### ISSUE TITLE
Make Product Group Text Bold When Printing Shopping List

### ISSUE THREAD

**Issue by horiveira** [grocy/grocy#2386]
It's useful to have the product group option when printing shopping lists, but would it be possible to make the text of the product groups bold?  It would make it easier to look at a shopping list and be able to quickly discern the different groups; right now, the product groups look just like any other product on the list and it's easy to miss. 

I'm not familiar enough with programming/coding/scripting, but I imagine that this would require a change in Lines 499-504 in [public/viewjs/shoppinglist.js](https://github.com/grocy/grocy/blob/master/public/viewjs/shoppinglist.js#L499-L504)
```
                if (!$("#print-group-by-product-group").prop("checked"))
                {
                    shoppingListPrintShadowTable.rowGroup().enable(false);
                    shoppingListPrintShadowTable.order.fixed({});
                    shoppingListPrintShadowTable.draw();
                {
```

**Comment by berrnd** [comment]
Such trivial design remarks are up to ones individual very personal taste + dependent on how you use / organize your stuff in Grocy and therefore [custom JS/CSS](https://github.com/grocy/grocy#adding-your-own-css-or-js-without-to-have-to-modify-the-application-itself) was added a long time ago.

Here is a snippet (for `data/custom_css.html`) to turn that into reality right now:
```html
<style>
#shopping-list-print-shadow-table .dtrg-group {
	font-weight: bold;
}
</style>
```

**Comment by horiveira** [comment]
Okay, I see - thank you. I'll adjust the custom CSS.
