### ISSUE TITLE
Feature Request: Export shopping list items (api) for online grocery order

### ISSUE THREAD

**Issue by pimboli** [grocy/grocy#2394]
Hi,

I am new to grocy project and I like the project a lot. Unfortunately one main feature for me is missing which I would like to add.

I would love to have an api endpoint which lists as json or xml all products (icl. barcode) of all products which are currently in my shopping card.

This call I could use then and write a small script which ads all the products via EAN/Barcode to my online supermarket online order.

Or does someone of you guys know a better or existing way to realise this?

Chers.

**Comment by berrnd** [comment]
Grocy has an API and the web frontend uses that, so each and everything you can see and do there, is already possible via that mentioned API. A very easy approach to find out how stuff works is to simply do the corresponding action on the web UI while also having a look at you Browser's developer tools to inspect the magic behind.

&nbsp;
> I would love to have an api endpoint which lists as json or xml all products (icl. barcode) of all products which are currently in my shopping card.

Products: [GET `/objects/products`](https://demo-prerelease.grocy.info/api#/Generic%20entity%20interactions/get_objects__entity_)
Example: https://demo-prerelease.grocy.info/api/objects/products

Product barcodes: [GET `/objects/product_barcodes`](https://demo-prerelease.grocy.info/api#/Generic%20entity%20interactions/get_objects__entity_)
Example: https://demo-prerelease.grocy.info/api/objects/product_barcodes

Shopping lists: [GET `/objects/shopping_lists`](https://demo-prerelease.grocy.info/api#/Generic%20entity%20interactions/get_objects__entity_)
Example: https://demo-prerelease.grocy.info/api/objects/shopping_lists


Shopping list items: [GET `/objects/shopping_list`](https://demo-prerelease.grocy.info/api#/Generic%20entity%20interactions/get_objects__entity_)
Example: https://demo-prerelease.grocy.info/api/objects/shopping_list
