### ISSUE TITLE
Bug: Tooltip issues on desktops with touchscreens

### ISSUE THREAD

**Issue by adamaze** [grocy/grocy#2395]
This may not really be a "bug", but I thought it was worth something bringing up.

when using a touchscreen device that has a mouse (laptop with a touchscreen, or a tablet style PC) you dont really have a "hover", as you may mainly be using touch. In Grocy, when you "touch" something like "Track next chore schedule", it gets "clicked", but it also leaves the mouse cursor right over the button, which leaves the tooltip up indefinitely (as you might expect when you move the mouse over the same button and simply leave it there) I have also seen issues where the button gets clicked, but the tooltip blinks in and out of existence rapidly.
I have tested this on firefox on windows 11, and on firefox on linux with the same results on the official grocy demo page. i couldn't recreate on android/ios, as im not sure i know how to connect a mouse to a phone :)

**Comment by berrnd** [comment]
> This may not really be a "bug", but I thought it was worth something bringing up.

Not a bug, but reported as a bug - cool.

&nbsp;
Tooltips are mainly handled by the third party component [Bootstrap](https://getbootstrap.com/docs/4.6/components/tooltips/) and were already optimized a lot (ref e.g. [your own report](https://github.com/grocy/grocy/issues/2206)).

&nbsp;
> (laptop with a touchscreen, or a tablet style PC) you dont really have a "hover", as you may mainly be using touch
> but it also leaves the mouse cursor right over the button
> windows 11

Just another crazy Windows handling. If it would be a real touch event, then it would like this (the same as on your phone, as you already noticed):

https://github.com/grocy/grocy/assets/2161815/a087f0f1-fa67-4303-870b-13eca8b4ac94

I will invest no further time to workaround more special device / use case issues, feel free to use [custom JS](https://github.com/grocy/grocy#adding-your-own-css-or-js-without-to-have-to-modify-the-application-itself) to do that on your own.
