### ISSUE TITLE
Bug: Quick consume buttons not consuming the right amount

### ISSUE THREAD

**Issue by alkuzman** [grocy/grocy#2397]
### Stock entries page
- `Consume this stock entry as spoiled` consumes 1 unit instead of the whole entry.
- The `Quick open button` opens the right amount but the message says 1 unit opened (Just a presentation issue).

Both issues are easily reproducible on the public demo instance.

**Comment by berrnd** [comment]
Once again two topics in one request, loving it...

**Comment by alkuzman** [comment]
> Once again two topics in one request, loving it...

Won't happen again.
