### ISSUE TITLE
Product userfields configurable per product group

### ISSUE THREAD

**Issue by berrnd** [grocy/grocy#240]
References https://github.com/grocy/grocy/issues/176#issuecomment-489382158 by @ytilis.

> Also, an additional question which might require its own ticket:
Would it be possible to optionally associate userfields with a particular Product Groups? This would allow more granular data for certain types of products.

> A hypothetical example would be types of Tea (Black, Green, Herbal, Oolong, etc) or Coffee (Dark Roast, Light Roast, Decaf) so you can better track a more detailed breakdown of your products. These are obviously inapplicable to other types of products, so would benefit from only displaying when you select a particular product group.

**Comment by berrnd** [comment]
When displaying products anywhere in a table, the fields/columns need to be the same across all displayed products - everything else doesn't really make sense. So this practically and technically doesn't really fit.

**Comment by paulbusse** [comment]
@berrnd Let me put in a proposal.

- keep the userfield definition as is
- in product group, you can set list a set of userfields that are applicable to the group
- when you filter on product group you add these fields to the table

In this case, all fields/columns are the same across all displayed products, depending on the product group.
My use case is my wine cellar in which I would have
- type : white, red...
- grapes 
- year
And the rest is already there. With the proposal above, I can have an overview of my wine cellar by selecting product group 'Wine'

**Comment by berrnd** [comment]
> when you filter on product group you add these fields to the table

So when changing a table filter (on [/products](https://demo-prerelease.grocy.info/products)) the displayed table columns should change? Sorry, IMHO a really bad idea and if I ever start working on this (based on reality, sounds like that's not so much the case) I would never implement it like so (and I also mentioned that in the previous comment above).
