### ISSUE TITLE
Feature Request: Unify models of /stock and /stock/products/{product_id}

### ISSUE THREAD

**Issue by alkuzman** [grocy/grocy#2400]
It would be nice if the item model for the `/stock` API call would be the same as `/stock/products/{productId}`. I just believe that the model on `/stock/products/{productId}` is quite good and complete for most things that anyone will ever need. Also, having fewer models would be better for maintainability. I guess this would spimplify the stock overview page code since it will depend only on the `/stock` API call

**Comment by berrnd** [comment]
> the model on `/stock/products/{productId}` is quite good and complete for most things that anyone will ever need

First of all, the biggest customer of Grocy's API is Grocy's web frontend - so what "anyone will ever need" is based for a big part on that (and you tend to speak quite often on behalf of all Grocy users, I doubt what personally fits you or me fits the world and shouldn't therefore introduce breaking changes only for that sake).

Next, if you like `/stock/products/{productId}` endpoint more and it serves "most things YOU will ever need", simply use that and the other one not. Both endpoints serve different purposed, also performance wise based on the data calculated / provided (per product).

&nbsp;
> I guess this would spimplify the stock overview page code since it will depend only on the `/stock` API call

Funfact: That's already the case, regarding what happens client side (the API is never used server side).
