### ISSUE TITLE
Feature Request:  Group recipes into categories and/or keywords

### ISSUE THREAD

**Issue by brianwanderson** [grocy/grocy#2408]
Hi,

I would like to see some way to group recipes into categories and/or keywords.  For example, I might have categories of "Sides", "Main", and "Desserts",  This would make it easier quickly find recipes when making a weekly meal plan.

Thanks for all the hard work.  

Brian

**Comment by berrnd** [comment]
Already possible by utilizing Userfields.

Please be so kind and do a little search beforehand - exactly this has already been asked in #1930, #1936, #1968, #2162, #2194, #324 and #1126.
