### ISSUE TITLE
Feature Request: Custom headers for server

### ISSUE THREAD

**Issue by fherreror** [grocy/grocy#2409]
I use Cloudflared for connecting to Home Assistant from the outside. I have the instance protected by Zero Trust (you have to authenticate in Coudflare prior to access the tunnel to the local machine).
So, I have a problem because I cannot use Grocy, as before reaching the server, it is stopped by the authentication page.

This can be solved in two ways:
1. Enabling mtls authentication, which is what I use with the home assistant mobile app.
2. Enabling a field in "server configuration" in grocy app, so we can one or more custom headers, as in cloudflare ypu can use an API token to authenticate.

Any of these two options would be awesome. I think that maybe the second one is easier, as it only needs to set the new field in configuration and send a header with the field information in every request, in case it has data in it.

**Comment by berrnd** [comment]
Remember that Grocy is technically a simple PHP application - so each and everything related to what you mentioned is handled by your web server of choice, simply tweak its configuration accordingly to whatever you want to have.

<details><summary>Off topic:</summary>
I personally would go the simple route and simply expose your instance directly, maybe behind a VPN - I always fail to understand what one hopes that Cloudflare can do better or more secure (at least more than often that makes stuff slower, but maybe not everyone likes stuff fast af, like I do).
</details>

**Comment by fherreror** [comment]
I am not asking a new feature for the grocy pho, but for the android app.
I am not asking to solve a cloudflare problem, but asiint to add a new feature to grocy mobile app, which is send a custom header.
It is not difficult and it is related to the app.
 If you don't want to implement it, ok, but please don't tell us is a cloudflare problem.

What I expect from cloudflare is not exposing my instance directly to the internet. I have more faith in Google or cloudflare as an authentication provider than in the security of a PHP application made by one person not professionally. Anyway, I think that two security layers are better than one.

**Comment by berrnd** [comment]
> I am not asking a new feature for the grocy pho, but for the android app.

None of the community contributed mobile apps are maintained here - this is Grocy aka "the server", nothing else.

&nbsp;
> It is not difficult

Then why not simply start implementing it yourself right tonight?

&nbsp;
> don't tell us is a cloudflare problem

I haven't told "us", only you and even not that - maybe just read again what I just wrote.

&nbsp;
> PHP application made by one person not professionally

I highly recommend not using Grocy then, since it's insecure and full of bugs - your network will be in big danger, nothing can prevent that. Big sorry for being so unprofessionally and publishing Grocy to the world, even forcing you to use it (sounds like that was the case, sorry again).
