### ISSUE TITLE
Bug: File upload broken for files containing multiple spaces in the file name

### ISSUE THREAD

**Issue by desrod** [grocy/grocy#2415]
Brand-new install of Grocy on 2 different hosts following the instructions. Immediately created a product and uploaded a small screenshot of the product from the manufacturer's website. When I click `Save & Return to Products`, the button grays out indicating its busy, but it never returns to the product's list, never finishes uploading. 

I can reload the product listing for that product, and now there's a broken image icon where there should be an image. 

Clicking the trash can to delete that image and clicking `Save` does the same thing, and never deletes the orphaned image upload fragment, so now the product is effectively a corrupt record.  

![Screenshot 2023-12-29 at 10 11 06 PM](https://github.com/grocy/grocy/assets/5942125/c6221256-cd70-47f8-ae33-2ef29be18a85)

Is this a bit of unfinished work, or should image uploads work with the current 'latest' version of the Docker container image?

**Comment by desrod** [comment]
Updating my previous bug entry: It is a valid bug, but I can work around it by renaming the image before uploading to ensure it does not contain any spaces. For example `screenshot 2023-12-19.png` will not work, but `screenshot-2023-12-29.png` does work fine. A minor annoyance, but one I can live with for now.

**Comment by berrnd** [comment]
> It is a valid bug

No, it's definitely not - please don't ignore the issue template and try to reproduce issues on the [official demo instances](https://demo.grocy.info) beforehand - it works there (= it can't be a bug), of course also a file named `screenshot-2023-12-29.png`

https://test-asoqpjgogww3u8anueg5ap.demo-prerelease.grocy.info/product/1

![grafik](https://github.com/grocy/grocy/assets/2161815/37d1c57b-f5bb-4108-870e-1da8fd567f97)

&nbsp;
> Is this a bit of unfinished work, or should image uploads work with the current 'latest' version of the Docker container image?

What a question, of course image upload should work. But none of the community contributed apps/tools/integrations (including any Docker image out there) are maintained here. In fact, the problem about uploading files (which is clearly a web server configuration thing) doesn't come up the first, maybe search for it a bit or post this at the appropriate place where the corresponding image is maintained.

**Comment by desrod** [comment]
I've just confirmed the same issue with the same screenshot that contained a space in its filename in the demo instance you linked above. It behaves the same way as it did on my own self-hosted instance of the same version. You can see that here: 

https://demo.grocy.info/product/34

**Comment by berrnd** [comment]
A really reproducible example (like simply providing the file in question) would be cool, but of course I take the time and figure out everything by the sole screenshots provided, since that's much easier.
