### ISSUE TITLE
User defined objects

### ISSUE THREAD

**Issue by berrnd** [grocy/grocy#242]
References #233.

Add custom objects, with these fields:
- Name
- Caption
- Description
- Show in sidebar menu
- Sidebar menu caption

Userfields can then be attached to custom objects.

Also references #176.

**Comment by ASMfreaK** [comment]
What's the status of this feature?  I really want to see this released

**Comment by berrnd** [comment]
Sorry, no schedules from my side ([see also here](https://github.com/grocy/grocy/issues/146#issuecomment-489454192)) ... if I start something, you see it here by referenced commits or comments...

Maybe there will be some progress from my side at [the end of next month](https://github.com/grocy/grocy/issues/323#issuecomment-523158321)...

**Comment by berrnd** [comment]
This is now done. :)

Feel free to play around with it a little bit on the pre-release demo:

Example custom object (list): https://demo-prerelease.grocy.info/userobjects/exampleuserentity

Configure custom entities: https://demo-prerelease.grocy.info/userentities

**Comment by jose1711** [comment]
Also it would be nice if user defined entities have access to locations objects. Defining a custom list-type field is an option but not if you want to avoid duplicate data.

**Comment by berrnd** [comment]
> Also it would be nice if user defined entities have access to locations objects. Defining a custom list-type field is an option but not if you want to avoid duplicate data.

That's already tracked in #335.
