### ISSUE TITLE
Possibility to merge products

### ISSUE THREAD

**Issue by berrnd** [grocy/grocy#243]
It should be possible to merge two (or more) products. E. g. you've created two different products "Chocolate (Milk)" and "Chocolate (Dark)" in the past but from now on you want to only have one product "Chocolate".

**Comment by ASMfreaK** [comment]
Will this be some kind of a proxy product?
Consider I have these products:
* `Producer1 Milk, 1 Liter` with unit `Carton` of quantity 1,
* `Producer1 Milk, 2 Liter` with unit `Carton` of quantity 2,
* `Producer2 Milk, 0.93 Liter` with unit `Bottle` of quantity 5,
* `Producer3 Milk, 1.5 Liter` with unit `Bottle` of quantity 2

With this feature will it be possible to have 1 product `Milk` with `Liter` as unit and combined quantity of  12.65 Liters?

**Comment by berrnd** [comment]
No, maybe you mean more like what #196 or #204 is about.

For this I just thought about that I have created two different products in th past, but which are the same, so merging product A with B means I want to keep A and all references of B will be replaced by A (so that B is deleted at the end).
