### ISSUE TITLE
Bug: 

### ISSUE THREAD

**Issue by gaertner-services** [grocy/grocy#2430]
Hallo,

ich habe Grocy Version 4.0.3 im Linuxserver Docker installiert.
Anschließend habe ich 19 Benutzerfelder für die Entität producs eingerichtet.
Auf der Produkte Seite werden die Benutzerfelder angezeigt und der Inhalt wird gespeichert und ist dann in der Übersichtsseitentabelle Produkte auch zu sehen.
Wenn ich das Produkt wieder öffne werden die Benutzerfelder wieder angezeigt. Allerdings sind nur die ersten 9 Benutzerfelder mit Ihnhalt gefüllt. Die restlichen Felder werden ohne Ihnhalt angezeit obwohl ihr Inhalt auf der Übersichtsseite zu sehen war.
Wenn ich jetzt nichts weiter ändere sondern nur speichere werden die leer angezeiten Felder auch leer in die Datenbank gespeichert und der vorher vorhandene Ihnhalt gelöscht.

Danke

**Comment by berrnd** [comment]
- Wir sprechen hier Englisch
- Ich kann nicht hellsehen und nur Probleme beheben für die ein nachvollziehbares Beispiel geliefert wird - [persistent Demo Instances](https://www.reddit.com/r/grocy/comments/jwnk9b) können genau dafür genutzt werden
- Das alles steht auch auf dem Issue Template
- Keiner der Community contributed Docker Images / Apps / Tools / Integrationen werden hier maintained

**Comment by berrnd** [comment]
Ich habe entsprechende Zeit investiert und ein Beispiel auf einer privaten Demo Instanz nachgebaut:

https://test-znwjthhhpxude78n733if.demo-prerelease.grocy.info/userfields?entity=products

https://test-znwjthhhpxude78n733if.demo-prerelease.grocy.info/product/29

Dort werden die Inhalte der 19 Felder angezeigt, können bearbeitet werden und werden entsprechend gespeichert.

Liefere also ein entspechend nachvollziehbares Beispiel, wenn willst das ich irgendwas behebe oder mir anschaue.

**Comment by berrnd** [comment]
Weil ich einfach mal vermute, dass genauso wenig vorab gesucht hast:

Schau auch #2339 an - bereits behoben, noch nicht Teil von einem Release.
