### ISSUE TITLE
Bug: Unable to open Grocy on iPhone app

### ISSUE THREAD

**Issue by smittyuk** [grocy/grocy#2435]
Hi,

I created a new Grocy instance on Docker and copied over a previous grocy.db file and it is all working fine in the web browser however I cannot get it it load properly on the iPhone app. I am getting an error:

Jan 10, 2024 at 10:53:19 PM: Data request failed for products. Message: decodingError(error: Grocy_Mobile.APIError.decodingError(error: Swift.DecodingError.typeMismatch(Swift.String, Swift.DecodingError.Context(codingPath: [_JSONKey(stringValue: "Index 377", intValue: 377), CodingKeys(stringValue: "default_best_before_days", intValue: nil)], debugDescription: "Expected to decode String but found number instead.", underlyingError: nil))))
Jan 10, 2024 at 10:53:20 PM: Data request failed for products. Message: decodingError(error: Grocy_Mobile.APIError.decodingError(error: Swift.DecodingError.typeMismatch(Swift.String, Swift.DecodingError.Context(codingPath: [_JSONKey(stringValue: "Index 377", intValue: 377), CodingKeys(stringValue: "default_best_before_days", intValue: nil)], debugDescription: "Expected to decode String but found number instead.", underlyingError: nil))))

I've had a look at the database but could not see a product under index 377 so maybe I'm interpretting the database and or error message incorrectly.

Any thoughts on how best to resolve this please?

Thanks

**Comment by berrnd** [comment]
> Grocy instance on Docker
> cannot get it it load properly on the iPhone app

None of the community contributed apps / tools / integrations / Docker images are maintained here.

&nbsp;
> Any thoughts on how best to resolve this please?

Sure, searching [at the appropriate place](https://github.com/supergeorg/Grocy-SwiftUI/issues?q=is%3Aissue+%22Expected+to+decode+String+but+found+number+instead%22) is the first step I would try.
