### ISSUE TITLE
Bug: Same category split into several in recipe ingredients list

### ISSUE THREAD

**Issue by sebastianjagr** [grocy/grocy#2436]
Hi there,

I starter creating recipes for Grocy and noticed that when I turn on splitting ingredients by categories for recipes, not all of them are grouped. You can see in the screenshot that for example spices in the red rectangles are split into 2 groups.

<img width="1080" alt="Screenshot 2024-01-11 at 10 18 49 (2)" src="https://github.com/grocy/grocy/assets/145137781/edecc6b9-e9fc-4cc4-a4db-e78819733383">

**Comment by berrnd** [comment]
Then please be so kind and recreate a reproducible example on a [persistent demo instance](https://www.reddit.com/r/grocy/comments/jwnk9b) (that's also mentioned on the issue template, please don't ignore that) - I still can't look behind screenshots, just as mentioned in another thread.

Maybe it's as simple as there is a space or another invisible character in the "Group" of some ingredients.

**Comment by sebastianjagr** [comment]
> Maybe it's as simple as there is a space or another invisible character in the "Group" of some ingredients.

Can't be as there is only one group of each in the master data.

Anyway, I will try to recreate it.
