### ISSUE TITLE
Purchase partial quantity

### ISSUE THREAD

**Issue by dillwishlist** [grocy/grocy#244]
Hello,

I'm really excited by this project, I'm trying to get all my grocery usage to go through it.  I have a question though.

Is it possible to put in a quantity with a decimal?  For instance, if I buy 2.86 lb of Bananas, I get a red "The amount cannot be lower than 1".

Thanks,

**Comment by berrnd** [comment]
Partial/Decimal amounts can be used everywhere when you enable the product option "Allow partial units in stock".

**Comment by bwp85** [comment]
I am having this same issue. Say 1kg of loose beans is $19.95 and i only purchase 0.25 of a kilogram or 250 grams. As the price is calculated based on fractions of a kilogram, how would i best represent this in the product setup. Ticking partial does nothing when it comes to purchasing.

**Comment by berrnd** [comment]
If you have enabled "Allow partial units in stock" on the product and your purchase quantity is "kg", you can track 0.25 kg on purchase and you need to provide the price per 1 kg (as the hint "in <CURRENCY> per purchase quantity unit" next to the input field implies.

What does not work regarding that?

**Comment by bwp85** [comment]
I have enabled "Allow partial units in stock". When adding the purchase, I enter everything but when i press ok it looks like it processes but then doesn't clear the inputs.
![image](https://user-images.githubusercontent.com/14260486/63231344-9e97b400-c25d-11e9-93d3-46ea404ed70e.png)

**Comment by berrnd** [comment]
Then there must be an error, normally there should be a red popup in the top right corner, but when it's a JavaScript problem or something maybe that doesn't even show up...

Could you check the browser console for errors? Or maybe reproduce this on the [pre-release demo](https://demo-prerelease.grocy.info)?

**Comment by jeauxlb** [comment]
Hi, I can confirm I am having this issue on the Inventory page of both the pre-release and stable versions at grocy.info. The information either stays on the page and doesn't process, or changes the value from e.g. 0.7 or 0.0.

I have verified this on Mac OS X 10.14.6 using both Safari 13.0.3 and Chrome 78.0.3904.108

**Comment by berrnd** [comment]
Thank you, I can reproduce it for the inventory page - moved it to a separate issue #459.
