### ISSUE TITLE
Feature Request: Add and purchase product at once

### ISSUE THREAD

**Issue by pendraggon87** [grocy/grocy#2444]
When scanning a new product, it brings up the new product screen where I can set defaults, and then I have to re-scan the same item to add it to my inventory.

**Comment by berrnd** [comment]
Are you talking about Grocy or another software (just like most likely in #2443)?

You scan a (unknown) barcode, choose the `Add as new product and prefill barcode` workflow, create the product and are immediately taken back to [/purchase](https://demo-prerelease.grocy.info/purchase) where the just created is prefilled accordingly.

I even created a screen video showcasing that just for you:

https://github.com/grocy/grocy/assets/2161815/844b401b-73ad-4d12-95e8-473e32b89068
