### ISSUE TITLE
Bug: api/system/db-changed-time returns wrong time

### ISSUE THREAD

**Issue by xmnovotny** [grocy/grocy#2446]
Api system/db-changed-time returns time of the last API call/grocywebpage refresh instead of the last DB change (repeated call of db-changed-time return always different time).

On the demo / pre-release it works as described. Could it be something with the config / installation?

Grocy is running on the RPi4, using nginx server and haproxy.
Config:
[config.json](https://github.com/grocy/grocy/files/13956360/response_1705444282901.json)
System info
[systemInfo.json](https://github.com/grocy/grocy/files/13956364/response_1705444389475.json)

**Comment by berrnd** [comment]
This endpoint simply returns the `mtime` of the `grocy.db` file, nothing more or less ([code ref](https://github.com/grocy/grocy/blob/4659f51551fdeafd5b3e474c95ea5d51d8081f52/services/DatabaseService.php#L61)).

Changes to the database can naturally occur at a lot of places, only updates to sessions are explicitly excluded ([code ref](https://github.com/grocy/grocy/blob/4659f51551fdeafd5b3e474c95ea5d51d8081f52/services/SessionService.php#L57-L63)).

Works as defined, so not a Bug.

This endpoint was maybe more useful when Grocy was younger and is that not so much today. Feel free to discuss a specific use case where this is a problem, most of the time other approaches are there to get to the same destination - but please don't report such things as a Bug ([README ref](https://github.com/grocy/grocy#questions--help--bug-reports--feature-requests)).
