### ISSUE TITLE
Shopping list output options

### ISSUE THREAD

**Issue by teamtmedia** [grocy/grocy#245]
Firstly, as always, "Thank you" for sharing such a great project.

Just using the shopping list and realise that there are no options for outputting.  Now I realise that holding a device is a decent possibility but even that could do with an enhancement.  So my thoughts are:

1) Add a notes section to the shopping list page where we can add extra bits and bobs that are off the system (cleaning products, etc).  This would be useful for people using the app or option 2

2) Add a print button that produces a clear shopping list

3) (Potentially) Add a button that can send a calendar appointment (.ical) to an email address (handy for sharing the list with 3rd parties)

Keep on trucking, loving the work.

**Comment by berrnd** [comment]
For 1.:
You can add items without a product, just fill in the notes field of the shopping list item...

**Comment by hauweg** [comment]
For 2: 
would love to have a print button!! <3

For 1: yes, that would be great! bernd your suggestion is a working workaround, but not a really nice one :)

**Comment by berrnd** [comment]
For 1:
Is it a that big difference if the textbox is inside a shopping list item or on the list page directly? Of course we can also add a textfield there...

**Comment by hauweg** [comment]
1. it does not habe the posibility to ad a product group.
2. i am using the note field now, to mark what is ordered allreay and when.
3. in order to have a nice layout and by that a good overview, every item oth shoping list, should have the same layout

**Comment by JoschaMiddendorf** [comment]
It would also be great to have the ability to subscribe to a shopping list as iCal Reminders list. In that way shopping lists could be viewed end checked by iOS reminders App.

**Comment by berrnd** [comment]
Shopping lists now have an notes section/field and can also be printed. :)

See the pre-release demo (next release will be dropped on the coming Sunday): https://demo-prerelease.grocy.info/shoppinglist

But I'm unsure about the .ical export. Should that be just an appointment for today and the shopping list as the body/text? Do you have an example for such a file?
