### ISSUE TITLE
Feature Request: 

### ISSUE THREAD

**Issue by meizu007** [grocy/grocy#2451]
I am using the Grocy API in python.
I coded a Flask web application and I use grocy API to consume recipes.
All is well, but what if I have to consume, say like, 10 recipes ?
The API method consumes only one.
Currently I encapsulated the API call in a for loop that is calling my url 10 times.
This obviously works, but I would like to know if there is the possibility to get the job done with only one url request, passing the amount to consume (10) once, say via post/get/json.
This is because I strongly suspect that making that many http request is a bottleneck for my code and responsiveness of my app.

Pardon me, I am not a professional programmer.
Grocy is so awesome!!
Thank you!

**Comment by berrnd** [comment]
This is neither a Feature Request nor a reproducible Bug, so according to [README](https://github.com/grocy/grocy#questions--help--bug-reports--feature-requests) this here is the wrong place, but anyway:

&nbsp;
>  This is because I strongly suspect that making that many http request is a bottleneck for my code and responsiveness of my app.

The web frontend does more than a handful of API requests for kind of every page load, it takes milliseconds and API calls are not something Grocy charges anything for, so I don't understand that problem at all.

&nbsp;
> All is well, but what if I have to consume, say like, 10 recipes ?

10 different recipes of course mean 10 different calls to [`/recipes/{recipeId}/consume`](https://demo-prerelease.grocy.info/api#/Recipes/post_recipes__recipeId__consume). One recipe with 10 "Desired servings" is only one call to the same endpoint, you just need to set the recipe's `desired_servings` accordingly before - just like the web frontend does it which uses the same API for everything, e.g. simply do that there while also having a look via your favorite Browsers's developer tools to find out how all the magic works.
