### ISSUE TITLE
Bug: API inconsistency for userfield images versus other images

### ISSUE THREAD

**Issue by RealFoxie** [grocy/grocy#2452]
When adding a picture to a product, the endpoint to fetch this image is:
`baseURL/api/files/productpictures/[btoa(product.picture_file_name)]`, with `[btoa(product.picture_file_name)]` the `picture_file_name` property of a product, encoded in base64.

However, when adding a userfield that is an image, to fetch this the url is:
`baseURL/files/userfiles/[product.userfields.image]/?force_serve_as=picture`. Here `/api` is not needed (even though it follows the api spec, except that it doesn't use the api endpoint) *and* the stored property is already base64 encoded.

It would be better that this works exactly the same way, but it is also not clear that there is this difference.

**Comment by berrnd** [comment]
First of all, a Bug is something that doesn't work, not something that you personally would like to have differently for whatever reason.

Next, I'm happy to answer any questions, also for that there's no need to report things you'd like to know as a Bug ([README ref](https://github.com/grocy/grocy#questions--help--bug-reports--feature-requests)).

First let's keep in mind that product pictures and Userfields are just two different things, it's nowhere stated that everything (unrelated) works the same in any manner.

&nbsp;

> When adding a picture to a product, the endpoint to fetch this image is:
`baseURL/api/files/productpictures/[btoa(product.picture_file_name)]`, with `[btoa(product.picture_file_name)]` the `picture_file_name` property of a product, encoded in base64.

Where that's stated? Picture (and file) Userfield values contain `btoa(<real/stored file name>)_btoa(original file name)` (mind two parts separated by an underscore). So taking the _first_ part and serving it via `baseURL/api/files/userfiles/<base64 first part>` works just fine and exactly like product pictures can be served via the API.

**Comment by RealFoxie** [comment]
I called it a bug because for me the api endpoint didn't work as it should have. But like you said, the problem comes from not knowing what the userfield property actually contains (apperently not the filename, but some concatenation of BASE64 strings :) )

On https://demo.grocy.info/api, under `/files/{group}/{filename}` it says 
```
The file group
Available values : equipmentmanuals, recipepictures, productpictures, userfiles, userpictures
```
Note 'userfiles' being among the values that you can use. It doesn't state it works the same, but it is a logical conclusion to make here.
And filename
```
The file name (including extension)
BASE64 encoded
```

This was the only place I could find information about this and it doesn't really specify having to do something different for userfiles.

So depending on the point of view, this can be seen more as an issue with incomplete documentation than it being a bug. 

Where could I have gotten this information or where would it fit? Is it an idea to update the api spec to contain this specific exception of how files work for userfiles? It does go against the way the other files work, so I wouldn't say it's really obvious.

**Comment by berrnd** [comment]
> Where could I have gotten this information or where would it fit?

By simply asking (the more appropriate place according to [README](https://github.com/grocy/grocy#questions--help--bug-reports--feature-requests) would be the [r/grocy subrreddit](https://www.reddit.com/r/grocy/) by the way), I happily answered any little thing which came up since about 7 years Grocy. I'm just allergic to having things one doesn't understand at a first sight (which is of course ok) reported as a Bug.

&nbsp;
> Is it an idea to update the api spec to contain this specific exception

Feel free to do it. For me writing documentation is most of the time not that much fun (and since this is a hobby project I mostly do the fun part only), so I'm not going to change or improve anything on that.
