### ISSUE TITLE
Config: Disable authentication

### ISSUE THREAD

**Issue by lbischof** [grocy/grocy#246]
I would like to disable authentication, without enabling embedded mode. I use basic auth and therefore don't need it.

**Comment by berrnd** [comment]
Sounds reasonable, but would imply that there is only 1 user. On some places user context is needed and for this a grocy user needs to be known...

If you want to have it now, use the attached patched `SessionAuthMiddleware.php` (in folder `/middleware`).

[grocy_patch_issue246.zip](https://github.com/grocy/grocy/files/3169136/grocy_patch_issue246.zip)

**Comment by lbischof** [comment]
Where is the user context needed? Other than for logging purposes?

**Comment by berrnd** [comment]
Currently only for tracking chore executions. Not a big/important thing, but something will fail if the constant `GROCY_USER_ID` is not set or invalid...

**Comment by lbischof** [comment]
Maybe only allow the feature if there is one configured user or always use `GROCY_USER_ID=1`? As far as I can see the user is also only used for logging purposes (I haven't used the chores component yet).

**Comment by berrnd** [comment]
> Maybe only allow the feature if there is one configured user or always use `GROCY_USER_ID=1`?

Yes, will only be a small change, that's how it's already done for demo and embedded mode...

**Comment by berrnd** [comment]
There is now a `config.php` options for this:

https://github.com/grocy/grocy/blob/09b23847b54dddf4070c5d584405d552cc0644a1/config-dist.php#L44-L46
