### ISSUE TITLE
Feature Request: Installer for normal web hosting

### ISSUE THREAD

**Issue by alex01at** [grocy/grocy#2463]
Why is wordpress so successful? Cause the install is extreme easy.
I try to install grocy now over 4hr and don't get it work.
So I request a simple to use step by step install routine. (for all kind of normal hosting provider) 
Maybe you find the time for it.

thanks

**Comment by berrnd** [comment]
I won't provide that - there are more than many tutorials out there and there is the [r/grocy subreddit](https://www.reddit.com/r/grocy) to (most of the time) get help for anything.

The comparison with Wordpress lacks the fact that I'm not aiming to reach each and everyone on this planet. This here is just a hobby and it's more than ok that something doesn't fit for each and everyone's very personal way of wanting things to run (all those not so familiar with web server stuff normally go the Docker way).
