### ISSUE TITLE
Feature Request: Automatic Number Format Recognition

### ISSUE THREAD

**Issue by saya6k** [grocy/grocy#2466]
I'm building my Grocy instance and having process to migrate from Apple Notes to Grocy.

When purchasing online receipt, copying and pasting prices from receipt often leads to errors due to number formats like '10,000'. Many websites and receipts use commas for digit grouping, which isn't always recognized correctly.

ISO 80000-1, the current standard for numbers and units, suggests that '10000000' or '10 000 000' are appropriate formats, promoting spaces for grouping digits without commas. This standard acknowledges the widespread practice of digit grouping for readability.

Adapting systems to automatically recognize commas (',') or spaces (' ') in numbers would be practical. This change would facilitate accurate data entry and comply with international numeric representation standards, ensuring consistency and reducing manual corrections.

#610 looks similar but it's quite different.

**Comment by berrnd** [comment]
Each and every date input and date output/display is using the locale format defined by your Browser, so that one which you should be most familiar with, unless you haven't configured your Browser accordingly. This won't be changed, since this makes the most sense.
