### ISSUE TITLE
Feature Request: Shopping list dropdown on /shoppinglist: Show the number of items per shopping list

### ISSUE THREAD

**Issue by wingmanx** [grocy/grocy#2467]
Hi.

Nice work with Grocy.
My wife uses "Our Groceries", but we are planning to move to another app. My phone is DeGoogled and some apps require Google, and also I'm changing everything to open source.

However, couldn't convince her to change because:
When selecting shopping lists, if there are 10 shopping lists and items in only three shopping lists, we have to open each shop list to find the items and it becomes unpractical. We use shopping lists to group the items to buy in each store.
As in "our groceries", it would be more practical if when selecting the shopping list, it had a counter with the number of items in each shopping list, 

Thanks!

&nbsp;
<details>
<summary>Edit by @berrnd: Request template violation - off-topic part minimized / will be ignored and not tracked here</summary>
Also
To add items, it could be more simple, just write the name of the product and click "add", it could be some default menu and f we wanted more options, we could in the item add, select "advanced options" for these other options, for example.
</details>

**Comment by berrnd** [comment]
Multiple topics per request are untrackable and that's also mentioned on the issue template, so the second part won't be tracked here.
