### ISSUE TITLE
Deprecation of Mutation Events - DOMSubtreeModified

### ISSUE THREAD

**Issue by Teddynet** [grocy/grocy#2469]
Hi, I ran Grocy on docker application and when I opened it on Chrome (v. 121.0.6167.161) it warned me about an imminent deprecation of mutation events like "DOMSubtreeModified" used on this line

https://github.com/grocy/grocy/blob/40d1a9c3d0ecadf4678af772c232368e8c41d8c4/public/js/grocy.js#L626

I read the overview on Chrome Platform and seems the mutation events will be removed in the future  (https://chromestatus.com/feature/5083947249172480)
They suggest to change with **MutationObserver**

![image](https://github.com/grocy/grocy/assets/5700311/162441b8-daef-4fd4-9e0e-8e77ae074aa7)

I apreciated your work, congrats

**Comment by berrnd** [comment]
If you don't have that much clue what this practically means, I would recommend simply not having a look at your Browsers developer console - that's nothing to be afraid of.

And it's even nothing in Grocy's scope, feel free to report that to people maintaining jQuery, if you really think they don't know that already.

Please only report practically relevant problems or Feature Requests here in the future, thanks.

**Comment by Teddynet** [comment]
I'm so sorry if you've had a bad day (or a long unsuccessfull debugging nigth) and you like to pour out your frustration on the others. It was only a suggestion but, surely, you don't need it. Have a good life !
