### ISSUE TITLE
Feature Request (very minor): Meal plan item button order consistency

### ISSUE THREAD

**Issue by mattl1598** [grocy/grocy#2471]
Buttons for edit/delete/consume etc aren't in a consistent order between the notes, recipes, and items.

Don't want to accidently delete items when trying to edit them or consume them when trying to add to a shopping list, especially if doing lots of items at once.

**Screenshot on my instance**
![image](https://github.com/grocy/grocy/assets/37371392/7f60bc28-a72a-42cd-b796-dfbee3b7322a)

**Screenshot on pre-release demo**
![image](https://github.com/grocy/grocy/assets/37371392/a92df278-e098-4c19-8d3b-d11b566dd182)

**Reproduction steps**
* Add Item to Meal Plan
* Add Recipe to Meal Plan
* Observe mismatched button orders.

**Comment by berrnd** [comment]
Of course this (minor UI glitch) can be changed/improved, but that's nowhere a bug in any way.
