### ISSUE TITLE
Re-enable PHP 8.1 support

### ISSUE THREAD

**Issue by trallen** [grocy/grocy#2473]
I  see in commit https://github.com/grocy/grocy/commit/ee01f4197954228171fdca5db3215ef0b50109fb that Grocy stopped supporting PHP 8.1, and currently returns "Unable to run Grocy: PHP 8.2.0 is required, however you are running 8.1.2-1ubuntu2.14" when running Ubuntu's 22.04 LTS.

The PHP website at https://www.php.net/supported-versions.php lists 8.1 as no longer having active support, but it is supposed to have security support until November 2024.

The current Ubuntu LTS only supports PHP 8.1 (and 7.3).

Would it be possible to re-enable support for PHP 8.1 until November 2024, to give Ubuntu administrators time to upgrade to PHP 8.2 or 8.3?

Thank you!

**Comment by berrnd** [comment]
That's not only stated in a random commit, but of course also on the release notes / changelog: https://grocy.info/changelog#v4.1.0

If you want to use outdated runtime dependencies, it's just natural to also stay with outdated Grocy versions.

I always don't understand what's so hard simply running a quite up to date PHP release (let's remember that it's more than a year that PHP 8.2 was officially born). And yes, such a thing is also possible on Ubuntu LTS.
