### ISSUE TITLE
Feature Request: Coupons / Rainchecks / Gift Cards

### ISSUE THREAD

**Issue by isleshocky77** [grocy/grocy#248]
It would be great to be able to track Coupons, Rainchecks, and Gift Cards.

I would imagine the first two would generally be tied to a specific product you normally buy while the last one might just be tied to a store you shop at.

The big thing is that all most likely expire at some point and it's nice to know you have them and when they expire.

**Comment by berrnd** [comment]
Currently you could use Equipment for this and a custom [Userfield](https://github.com/grocy/grocy/issues/176) for the expire date.

#242 covers to be able create custom objects based on Userfields, which then also show up optionally as an own menu entry on the sidebar - I think that will fit for this then...

**Comment by berrnd** [comment]
Custom objects / lists are now implemented, so I think this can be achived with that - see https://github.com/grocy/grocy/issues/242#issuecomment-532706949.
