### ISSUE TITLE
Feature Request: Transfer a specific stock entry from its current location instead of product's default location

### ISSUE THREAD

**Issue by y0umu** [grocy/grocy#2481]
Hi developer, I found the [Grocycodes](https://github.com/grocy/grocy/issues/2448#issuecomment-1902550736) really useful. But when I scan a grocycode in the Transfer module, the "from location" is always being automaically filled with the product's default location, rather than the current location of the stock entry. This is seen in both the pre-release online-demo and my self-hosted 4.1.0 deployment.

Is it possible to make the transfer "from location" filled with the real location of the grocycode you scan?

**Comment by berrnd** [comment]
> Is it possible to make the transfer "from location" filled with the real location of the grocycode you scan?

Hi user, of course it's technically possible, this is software.
