### ISSUE TITLE
Feature Request: Unidirectional unit conversions/abstract units

### ISSUE THREAD

**Issue by Migsi** [grocy/grocy#2482]
I want to apologize straight away if this request is explained poorly/too complicated, the whole thing is not 100% thought through yet and might require some polishing, to say the least.

After using grocy for almost two years, we found that having the information about how many packages/cans/bottles/... of an item are in stock is often more important to us, than knowing how many kg or liters of it there are. With the current unit conversion system, we mostly use kg and liters for default unit of purchase and unit of price, which gives us easy comparability of prices while shopping. The other default units are set to a specific package size (e.g. "1l bottle") to represent the most commonly size purchased. But: most commonly purchased is not always purchased, so there are instances when we have e.g. a "0,5l bottle" of something of which the default is "1l bottle". This makes it necessary to select the right unit when consuming without scanning, which in our case unfortunately happens often, resulting in weird/inaccurate data (seeing [this request](https://github.com/grocy/grocy/issues/2448), would scanning even solve this?). Also, we often simply want to consume the oldest/least fresh stock of a product, not caring about the actual package size, thus "aksing" Grocy first, which stock to use.
I came up with this idea:
If items had the ability to define "one way"/"abstract" conversions to generic units, those could be used when consuming, simply pointing to the oldest available/closest to best before stock of the given product. Thus, if we had e.g. "1l bottle" of Coke and "0,5l bottle" of Coke, we could consume "bottle" of Coke and it would consume whatever stock was the least fresh. To ensure consistency with the real world, the feedback message confirming "opened/consumed x of y" could show the actual unit of the opened/consumed item, to give the user a hint on which actual item to pick from the pantry. Also, coming back to my initial statement, this generic unit could be used on the overview page. Going on with the Coke example, we'd have 2 "bottles" of Coke instead of "1,5l".

This idea could be expanded to shopping lists as well, as we often do not care about the size of something we buy (e.g. Nutella, we take whatever size the shop offers), so the list could be generic about the amount as well. But as that poses it's own set of problems (e.g. what to do when there is a minimum quantity/automated additions to the list?), I'd open a dedicated request for that if this ever gets implemented.

Thanks for the awesome work and best regards

**Comment by berrnd** [comment]
This is not a Feature Request, more a general question about how to organize your stuff in Grocy - this is not the right place for that / not the community forum ([README ref](https://github.com/grocy/grocy?tab=readme-ov-file#questions--help--bug-reports--feature-requests)).

Each and every product related unit can already be used everywhere.

Grocy (or myself) also doesn't have the aim to fit each and every specific / personal use case on this planet, sometimes other tools just fit better - just saying.

**Comment by Migsi** [comment]
> This is not a Feature Request, more a general question about how to organize your stuff in Grocy - this is not the right place for that / not the community forum ([README ref](https://github.com/grocy/grocy?tab=readme-ov-file#questions--help--bug-reports--feature-requests)).
>
One could surely question this being the proper approach to organzie stuff, but that wasn't the point of this issue. I thought it could help to provide some context around this, helping my explanations. Might have overdone that part, nonetheless, requesting one way conversions which are not existing yet, sounds a whole lot like a feature request to me.
> 
> Each and every product related unit can already be used everywhere.
>
I never questioned that, I just had the idea of introducing a new type of unit and allow to make optional use of that.
>
> Grocy (or myself) also doesn't have the aim to fit each and every specific / personal use case on this planet, sometimes other tools just fit better - just saying.
>
I fully understand this being your project and thus it being your choice on what direction to head on. It confuses me though, if you suggest other tools might fit better, even though I just wrote about being a happy user since ~2 years. The only issue I have with Grocy is this detail, which _could_ be improved. The obvious thing to me in this case is to post a feature request, which I admittedly didn't expect to get just thrown away and be pointed elsewhere for no obvious reason.

**Comment by berrnd** [comment]
No worries, I've read your request in its entirety and I roughly understand how Grocy works, what's possible and what not. All what you want is already possible, it's just a matter of organizing stuff inside Grocy. I won't invest the (much) time needed to explain all that, if you don't want to simply try different approaches on your own (sometimes thinking outside the box is needed, even more when using the same approach for years), then I can't help and the suggestion for another tool is just another way to go in general.

In any case, still the wrong place for discussing that, will lock this due to that.

Partly this here is most likely even covered by #1421 (explained there in much lees words - reading just the facts about what's wanted saves so much time than reading the whole life story).
