### ISSUE TITLE
Feature Request: Allow filenames with non-ASCII characters

### ISSUE THREAD

**Issue by wonderfulShrineMaidenOfParadise** [grocy/grocy#2484]
## How to reproduce

1. Save a file as `ビール.jpg`
2. Edit master data, product `Beer`, and upload the file `ビール.jpg` as the picture
3. Save
4. See the error

**Comment by berrnd** [comment]
Something that currently works as defined can't be a bug, even that you expect non-ASCII filenames should be possible to be used.

This is the code part you need to extend if you want that - feel free to start working on that right away:

https://github.com/grocy/grocy/blob/e01e0f3abe85945f8fac3ee2117dcbeb4a4e90aa/helpers/extensions.php#L224-L323

**Comment by berrnd** [comment]
> I will take a shot at adjusting the code.

Thanks, but it failed miserably: https://github.com/grocy/grocy/pull/2569#pullrequestreview-2246138099
