### ISSUE TITLE
Purchase > products with apostrophe don't trigger "create or assign product" modal

### ISSUE THREAD

**Issue by hannahswain** [grocy/grocy#249]
Correct behavior where tab triggers "create or assign" product modal if product doesn't exist:

![Create or assign](https://cld.wthms.co/aK9Lw8+)
Full size: https://cld.wthms.co/aK9Lw8

When working with an apostrophe:

![No create or assign modal](https://cld.wthms.co/sxDPvD+)
Full size: https://cld.wthms.co/sxDPvD

You can continue to fill in the other fields, but the `ok` button at the bottom won't do anything.  

The workaround is to create the products via Manage Master data

**Comment by berrnd** [comment]
Just released [v2.4.1](https://github.com/grocy/grocy/releases/tag/v2.4.1) to address this...

**Comment by hannahswain** [comment]
Awesome, thank you!

**Comment by berrnd** [comment]
I was sure I tested this and it worked before releasing v2.4.1, seems not to be the case anymore today, however (references https://github.com/grocy/grocy/issues/264#issuecomment-495249507).

So will be tracked again in #264.
