### ISSUE TITLE
Feature Request: opengtindb

### ISSUE THREAD

**Issue by ThorstenUm** [grocy/grocy#2493]
Hello, how can I use the BaseBarcodeLookupPlugin plugin to automatically select opengtindb products?
Where in the DemoBarcodeLookupPlugin.php do I have to enter that the public database should be queried? And where is the “product picker” in the app?

If I enter 4008400221120 in the API link, then “milk chocolate” should actually appear. Instead “LookedUpProduct_EMaYT” appears there

**Comment by berrnd** [comment]
Have you had a look [at README](https://github.com/grocy/grocy/tree/v4.1.0?tab=readme-ov-file#barcode-lookup-via-external-services) by any chance?

Everything is mentioned there and as the name implies, it's of course only a rough implementation demo of how such a plugin could work. You have to implement everything needed yourself, I won't help with that.

&nbsp;
> If I enter 4008400221120 in the API link, then “milk chocolate” should actually appear.

That's exactly what [`DemoBarcodeLookupPlugin.php`](https://github.com/grocy/grocy/blob/v4.1.0/data/plugins/DemoBarcodeLookupPlugin.php) is supposed to do, it generates random product names for demo purposes only. Expecting that this magically implements a whole service connection by randomly putting a "API link" somewhere is interesting.
