### ISSUE TITLE
Bug: Scanmode is not able to fill all fields sometimes. Next time, it works with the same barcode.

### ISSUE THREAD

**Issue by chris-h14** [grocy/grocy#2496]
> EDIT by @berrnd:
> Continuation of #2495
---
Hi, first of all: Thank you for this great application!!

Tut mir leid, dass mein erster github-Eintrag mangelhaft war. Ich gelobe Besserung.

Ich habe den unten beschriebenen Fehler im Testsystem reproduziert:
https://test-1xzuvv6185hy2qu450lxaa.demo-prerelease.grocy.info/stockoverview

Hier habe ich das Problem gefilmt:
https://www.dropbox.com/scl/fi/yahgo15rjag9x95htw5pf/IMG_3818.MOV?rlkey=bk8ax3hkzeh33tlm7qpzyd6zg&dl=0

Ich hoffe so alles getan zu haben um das Problem nachzuvollziehen.
Herzlichen Dank!

english:
If I scan using a barcode scanner lots of items as consume, the app says sometimes: "Scanmode is activated, but not all necessery fields could't filled out automatically". But all fields are filled out correct and you only have to press enter and then it works. 

german:
Wenn ich mehrere/viele Produkte mit einem externen Barcodescanner scanne um diese zu verbrauchen oder einzukaufen, funktioniert es eine Zeit lang. Irgendwann kommt aber bei jedem Scan die Fehlermeldung, dass obwohl der Scanmodus eingeschaltet ist, nicht alle erforderlichen Felder ausgefüllt werden konnten. Was aber nicht stimmt, denn er füllt alle Felder automatisch aus. Aber man muss manuell auf enter (auf der Tastatur) oder ok am Display drücken, dass er es übernimmt.

**Comment by berrnd** [comment]
Noch kurz erwähnen, welches Produkt man benutzt / scannt und so weiter wäre noch geiler - aber gar kein Problem, ich hab Freizeit ohne Ende und liebe Rätsel - zieh mir das dann aus dem Video oder dem Bestandsjournal der Demoinstanz oder woher auch immer. Ist ja mein Job und warum einfach, wenns auch mühsam geht.

Fehler sauber melden scheint selbst auf Deutsch so schwer zu sein, dass es kaum einer hinbekommt, wahnsinn.

**Comment by chris-h14** [comment]
Hallo Bernd, leider sind nicht alle die dein tolles Programm benutzen Informatiker oder haben Erfahrung mit professionellem bug reporting. Trotzdem wollte ich auf die Problematik aufmerksam machen.

Ich versuche dir alle Informationen zu beschaffen, die du brauchst.
Dass der Scanner oder die Barcodes Relevanz haben hatte ich nicht gedacht. Schließlich wird der Code ja korrekt erkannt und alle Felder richtig ausgefüllt. Nur der letzte Schritt, das ok bzw. enter drücken wird manchmal nicht ausgeführt.

In dem Video habe ich einen QR-Code gescannt, der mit dieser Zeichenkette codiert ist "1_VANILLE" (ohne die Anführungszeichen). Es passiert aber willkürlich bei allen QR-Codes oder EAN-Codes. Da ist kein Muster zu erkennen.

Der verwendete Scanner ist ein "Tera Pro 3 in 1"
https://www.amazon.de/dp/B08SB7GP77/ref=pe_27091401_487027711_TE_SCE_dp_i1

**Comment by berrnd** [comment]
> Erfahrung mit professionellem bug reporting

Ich lache hart.

Wenn man ein Problem mit irgendwas hat, dann schreibt man einfach jedes Detail möglichst genau auf. Alles ist relevant, immer. Das ist mit Software nicht anders, wie wenn ein Problem mit deiner Heizung hast. Nur bei Software scheint das immer ein Riesenproblem zu sein, da bekommt man oft nur minimale Brocken hingeworfen, ich verstehs nicht. Was müssen Softwareentwickler für geile Typen sein, wenn nur die Problembeschreibungen "professionell" aufschreiben können. Man oh man. Jedem immer jedes einzelne Detail aus der Nase ziehen zu müssen ist nervig, kostet absolut unnötig Zeit (die ich hier mal wieder for free und in einem Übermaß das seines gleichen sucht zur Verfügung stelle) und geht mir einfach nur auf den Sack.

Ich schaus mir vielleicht an, irgendwann, oder auch nicht.

**Comment by berrnd** [comment]
I've invested about 45 minutes into this funny puzzle just now, trying to extract all the not mentioned information out of the video and the provided demo instance.

&nbsp;
> In dem Video habe ich einen QR-Code gescannt, der mit dieser Zeichenkette codiert ist "1_VANILLE"

That's simply not right or at least not complete. Based on the video you scanned the "2_VANILLE" barcode on the last try. Based on the demo instance's stock journal you even used more different ones too. What's the point about describing such stuff incomplete or wrong / what do you guess that should help with?

&nbsp;
Based on the few information provided I can't help. It works, tried it more than 100 times just now for this example and I use exactly that in may daily personal workflow too, nowhere with this issue.

You can easily get that when scanning a barcode on consume with an amount set > the current stock amount of the corresponding product. Maybe it was simply that, but that's by far not a bug, but just correct.
