### ISSUE TITLE
Feature Request: less mandatory fields for products

### ISSUE THREAD

**Issue by thatso** [grocy/grocy#2504]
I understand the concept of Grocy, however, it would be nice if less product attributes were mandatory fields.
I really don't need specific storage locations or minimum amounts to buy per item.
Of course there are tons of "dumb" shopping list type apps I could use instead, but I believe it would greatly benefit Grocy's user base if building a master database was easier to start with without all these mandatory fields.

**Comment by berrnd** [comment]
> minimum amounts to buy per item.

That's not a mandatory field.

&nbsp;
> I really don't need specific storage locations

Then disable location tracking ([`config.php` ref](https://github.com/grocy/grocy/blob/6602c76005bfdb436681d976e130407650719a4a/config-dist.php#L143)).

&nbsp;
No single field anywhere is marked as mandatory when there is no technical reason behind it. And for products these are only the 4 unit fields + the default location (which can be disabled by a feature flag as just mentioned if you don't need locations at all). This won't be changed.

The better place for general usage questions is the [r/grocy subreddit](https://www.reddit.com/r/grocy) as [mentioned in README](https://github.com/grocy/grocy?tab=readme-ov-file#questions--help--bug-reports--feature-requests).
