### ISSUE TITLE
Can't use external search API plugin

### ISSUE THREAD

**Issue by Gerben321** [grocy/grocy#2505]
I've been trying to use the `DemoBarcodeLookupPlugin`. I've set the setting (like told in the plugin), restarted my docker image, and then I search for a product. When I search for it in the API it works fine and it's returning data from the plugin. However, in the frontend it doesn't seem to do it? This is what I see when I search for something:

![image](https://github.com/grocy/grocy/assets/24865452/2109b294-445f-4341-86ae-7c0a0b33b9ea)

I don't see the plugin option that I would expect. That should show here, right? I am not that familiar with Grocy yet.

**Comment by berrnd** [comment]
> I don't see the plugin option that I would expect. 

And where exactly does this expectation come from?

Nothing of that is part of the latest release v4.2.0, maybe in a future release there will be something on that.

Check the README of the corresponding release: https://github.com/grocy/grocy/tree/v4.2.0?tab=readme-ov-file#barcode-lookup-via-external-services

Check the preview changelog (each and everything what's mentioned there is not part of the current release and that's not a surprise at all): https://grocy.info/changelog#preview

**Comment by berrnd** [comment]
> I am not that familiar with Grocy yet.

Please don't report each and everything which is not super crystal clear at a first sight to you as a Bug here, I'm allergic to that and will react accordingly.

The [r/grocy subreddi](https://www.reddit.com/r/grocy)t is the place for general usage questions as [mentioned in README](https://github.com/grocy/grocy?tab=readme-ov-file#questions--help--bug-reports--feature-requests).

**Comment by Gerben321** [comment]
Okay calm down 😂

**Comment by berrnd** [comment]
> for the bug there.

Nothing what you described is a bug, please at least read what I answer.

&nbsp;
> When I search for it in the API it works fine and it's returning data from the plugin.

Great, not a bug.

&nbsp;
> However, in the frontend it doesn't seem to do it?
> I don't see the plugin option that I would expect.

Because that's not part of the current release. I've just pointed that out, simply read it again if you've missed it. Also not a bug.

&nbsp;
We're done here.
