### ISSUE TITLE
Feature Request: Generate images of generic products via AI, or search them online

### ISSUE THREAD

**Issue by vnmabus** [grocy/grocy#2509]
Product images are quite useful to visually find the products of interests inside Grocy. However, when configuring Grocy for the first time, adding images to the products takes a lot of time (either taking a good photo or searching for an appropriate image in the web, download it, rename and add it to Grocy).

Most products are, however, generic products such as milk, eggs or apples, for which is not really important to have a photo of a particular brand or format. Thus, it would be very useful if we could generate a matching photo given the title and description, just with a single click. I think today that is easy to do that calling external generative AI services, and thus I propose that as an useful feature that allows for an easier configuration of products in Grocy.

Alternatively, an option to easily search an online photo online and select it could also be useful.

**Comment by berrnd** [comment]
> I think today that is easy to do that calling external generative AI services

If you think that's easy, why not simply start right away? Grocy [has an API](https://demo-prerelease.grocy.info/api) covering everything needed, so simply create that (as an external tool / add-on) and feed your generated picture into Grocy via that API.

I doubt that this would be useful or even faster than simply taking a picture yourself (if that's even needed, as you also already pointed out - if that milk doesn't look like the milk I tend to use here, what's the point or what's the big point of having a milk picture anyway). So sounds like fancy stuff not really practically relevant, Grocy is here to primarily help with getting things done.

&nbsp;
> Alternatively, an option to easily search an online photo online and select it could also be useful.

The common barcode lookup functionality (ref. [pre-release README](https://github.com/grocy/grocy?tab=readme-ov-file#barcode-lookup-via-external-services) or [Barcode Buddy](https://github.com/Forceu/barcodebuddy)) is the general way to go for importing product data.
