### ISSUE TITLE
Add spoiled button to stock overview

### ISSUE THREAD

**Issue by hannahswain** [grocy/grocy#251]
When products have passed their expiry date, they should be either consumed (if you dare :)) or marked as spoiled. It would be great to have a "spoiled" action button on the stock overview to make that faster:

![Spoiled items](https://cld.wthms.co/kXH8tl+)
Full size: https://cld.wthms.co/kXH8tl

The button would have the same behavior as consume 1/all, but would include the spoiled option. Instead of a button, options in the dropdown menu would also be great.

I'm finding that I tend to just mark products as consumed because I can't be bothered to go to Consume, find the product, and then mark it as consumed along with the spoiled checkbox. It would be great to be able to know what's actually spoiling, though.

**Comment by berrnd** [comment]
Added this now as an option in the drop down menu: :)

![grafik](https://user-images.githubusercontent.com/2161815/60758677-40e73980-a01a-11e9-9c7e-8469a0bc639f.png)

**Comment by hannahswain** [comment]
Thank you! :)
