### ISSUE TITLE
Typo: "product specifc QU conversions"

### ISSUE THREAD

**Issue by danielrosehill** [grocy/grocy#2510]
Deployment:

Grocy add-on to Home Assistant OS.

Screen: Edit product.

There's autopopulated text that reads "Product specifc QU conversions".

"specifc" should be spelled "specific"

![grocytypo](https://github.com/grocy/grocy/assets/40233203/fcbb3c09-7202-4df9-8c21-8bbe866ec4f3)

**Comment by berrnd** [comment]
Fixed a couple of months ago in c9bc10820dddc6534d7a8d29c4f90a2eaef95f2b, not reproducible since [v4.1.0](https://grocy.info/changelog#v4.1.0) - please always try to reproduce problems on the [pre-release demo](https://demo-prerelease.grocy.info/) first (as also mentioned on issue template).
