### ISSUE TITLE
Bug: FontAwesome icons showing rectangle box with X

### ISSUE THREAD

**Issue by Chaprnks** [grocy/grocy#2512]
FontAwesome doesn't seem to work on my self-hosted (both chrome & firefox), but also with the main demo instance.

Chrome:
![chrome](https://github.com/grocy/grocy/assets/6340970/abde34b6-e7ae-4cf6-bdd1-4040cdf5bf0a)

Firefox:
![firefox](https://github.com/grocy/grocy/assets/6340970/43e5d387-cc5d-4298-abce-7fdd3aa80c40)

**Comment by berrnd** [comment]
Then triple check what's going on with your Browsers / network / computer / whatever. This reproducibly definitely works.

https://github.com/grocy/grocy/assets/2161815/0bff3356-d564-4a50-8ae8-b1aaabe230a7

**Comment by Chaprnks** [comment]
I just realized what it is! I'd like to post a reply in-case anyone else encounters this issue, can troubleshoot this option before reporting.

Check all extensions (incl. userscripts & userstyles), especially ones that modify the layout or look of a website. For me, it was the Stylus (stylish fork). One of the userstyles was coded sloppy & applied the custom font globally, not just to a designated webpage.

![WzLL9dv](https://github.com/grocy/grocy/assets/6340970/01aaf14b-dda3-4671-b145-8c355ec67d6d)

**Comment by berrnd** [comment]
> Check all extensions
> can troubleshoot this option before reporting

The most obvious thing to do when strange web things are going on is to test stuff without any Browser extensions enabled. This is not related to specifically Grocy. Obviously this doesn't came to your mind, even using multiple Browsers, before opening this request and wasting my time? Wow.
