### ISSUE TITLE
Feature Request: Assign multiple categories to one task

### ISSUE THREAD

**Issue by genderneutralnoun** [grocy/grocy#2513]
Title, essentially. Some things fit in more than one category, you know?

I know making a very short feature request like this is generally frowned upon, but I honestly can't think of anything else to say haha. I feel like the reasons someone would need such a feature would be self-evident.

Alternatively, if the way categories are coded would make implementation difficult, perhaps there should be a "tags" system in addition? They'd be useful for chores too I think.

**Comment by berrnd** [comment]
> Alternatively, if the way categories are coded would make implementation difficult, perhaps there should be a "tags" system in addition?

Of course, if a "tags system" sounds far more easy to implement for your, you're invited to start working on this right tonight.

&nbsp;
You can essentially have this yesterday by utilizing Userfields.

**Comment by berrnd** [comment]
>  You can essentially have this yesterday by utilizing Userfields.

Closed in favor of simply utilizing Userfields (type `Select list (multiple items can be selected)`) for that.
