### ISSUE TITLE
Bug: Unable to save chores when chores_assignment: false

### ISSUE THREAD

**Issue by Telain** [grocy/grocy#2514]
Using the Home Assistant addon, though not sure if that's relevant.
Set chores_assignment: false, and receive an error when trying to save a new chore. I'm able to save it (after providing an assignment), when chores_assignment: true.

Uncaught TypeError: $(...).val(...).join is not a function
    at HTMLButtonElement.<anonymous> (choreform.js?v=4.0.3:20:62)
    at HTMLButtonElement.dispatch (jquery.min.js?v=4.0.3:2:40035)
    at v.handle (jquery.min.js?v=4.0.3:2:38006)

Unable to reproduce on demo, as I cannot find if it's possible to disable chores assignment on the demo.

**Comment by berrnd** [comment]
Not reproducible, it's perfectly possible to create new chores after setting [`FEATURE_FLAG_CHORES_ASSIGNMENTS`](https://github.com/grocy/grocy/blob/af1f2aef961179f7f8d9f6d072727d3d057da239/config-dist.php#L150) to `false`.

&nbsp;
> Using the Home Assistant addon, though not sure if that's relevant.

Of course that's relevant. Just like it's the golden rule to debug any web related stuff in a Browser without any add-ons installed, it's the golden rule for Grocy to try to reproduce stuff first in an not-special environment first.
