### ISSUE TITLE
Bug: Barcode Not Functioning

### ISSUE THREAD

**Issue by Mwalton4uk** [grocy/grocy#2515]
If I make a few products on Grocy and print the Grocy Barcode, the Grocy iPhone App doesn't seem to be able to use them.

The quick scan feature does nothing, almost like it can't detect the Barcode and if I go to purchase and try to select a product via barcode, it will scan and output `grcy:p:8` but doesn't select anything or filter to the item.

For context, I am using an iPhone 12 Pro Max with app version 2.10.4 and my Grocy instant is ingress into Home Assistant and version 4.0.3 (HA addon version is 0.21.0).

**Comment by berrnd** [comment]
> the Grocy iPhone App doesn't seem to be able to use them
> Grocy instant is ingress into Home Assistant

None of the community contributed apps/tools/integrations/whatever are maintained here.
