### ISSUE TITLE
Feature Request: Edit dates that get used in calculations

### ISSUE THREAD

**Issue by GwynHannay** [grocy/grocy#2519]
Tried searching to see if it was mentioned but didn't find anything - apologies if it's already discussed somewhere.

My use case is specific to opening items, however I imagine it would be applicable to other areas as well. Where I have products with a value entered for "Default due days after opened", this causes an issue if I didn't mark something as opened on the specific date that I opened it and I can't see a way to set the date that something was _actually_ opened (or consumed).

This makes the due date useless for me and means I have to set another method of tracking when I opened something and need to chuck it out.

Can we have a field on various pages like consume and transfer to set the date for the action to have occurred?

**Comment by berrnd** [comment]
Each and every stock entry, with all the information it holds, can be edited on [/stockentries](https://demo-prerelease.grocy.info/stockentries).

The [r/grocy subreddit](https://www.reddit.com/r/grocy) is the better for general usage/help questions [according to README](https://github.com/grocy/grocy?tab=readme-ov-file#questions--help--bug-reports--feature-requests).

**Comment by GwynHannay** [comment]
Right, I can see that I can change the due date manually, which would involve me manually doing the calculation for each item that I opened based on the correct opened date and the number of days it should then be due... but that's a lot of manual work prone to human error - errors that I make a lot, hence my preference to do this in something like grocy.

The better option would be to be able to specify the correct opened date as I'm entering the entry and have the system calculate for me, rather than me marking it as opened, going to edit the stock entry, then trying to do the calculation myself to enter the correct due date.

**Comment by berrnd** [comment]
> but that's a lot of manual work prone to human error

And remembering days or weeks later when you opened stock entry xy exactly is prone to less human error? I kind of doubt that. When you don't care about tracking stuff in Grocy right when doing it in reality, or at least at the same day, it sounds for me rather you don't care / don't need something like Grocy at all.

**Comment by GwynHannay** [comment]
... Right. Good talk, bud.
