### ISSUE TITLE
Add Support For Unchecking A Completed Task

### ISSUE THREAD

**Issue by frakman1** [grocy/grocy#252]
If I accidentally check a task (press the check button to its left), there is no way to uncheck it. Even if I select "show done tasks" and then edit that task, there is no way to revert it to the uncompleted state.

See screenshot below:

![image](https://user-images.githubusercontent.com/5826484/57797703-05ff0e80-7719-11e9-86c6-5e9cb09a78ad.png)

The green checkmark is un-clickable now. I should be able to click on the checkmark  to toggle its completion status.

**Comment by berrnd** [comment]
This is now done, for a completed task there is now an undo button shown instead of the complete button:

![grafik](https://user-images.githubusercontent.com/2161815/60759971-99740200-a02d-11e9-8372-db655544b476.png)
