### ISSUE TITLE
Feature Request:  Need ability to Assign Chores

### ISSUE THREAD

**Issue by eknee** [grocy/grocy#253]
I would love to use the Chores component of Grocy with my kids but currently there is no way in the UI to assign a chore to one of my kids.  Ideally there would be a Chore UI that allows the following:

- ability to view Chores assigned to a user (can come from a user field on the chore itself)
- ability to mark a chore as completed from with the same view Chore UI 

How I've tried to accomplish this to date:

Extended the Chore table and created the following:
User field:  Assigned
List value:  Child 1 | Child 2 | Child 3 | Child 4
Display as columns in table

Created multiple chores
Chore:  Clear Kitchen Table (Child X)
Repeats:  Dynamic - every 4 days
Assigned:  Child X

The problem I keep running into is the UI to mark a chore complete is separate from the Calendar view.  Also, the list box shows the entire chore list so if Child 1 completes their chore they have to hunt through a massive list of chores just to find their name.  Having separate users accounts for each child wouldn't work because I want them all in one account otherwise I'll have to manage the constant logging in/out of which is prone to issues.

**Comment by berrnd** [comment]
Thanks for the input, also already thought about this...

Maybe would also be useful that all childs can be assigned to the same chore, + an option about to whom the next scheduled execution should be assigned to like:
- Random
- "One after another (alphabetical)"
- ...

**Comment by eknee** [comment]
Yes agreed.  This would solve the issue with assignment for sure.

There also needs to be a UI that allows each child to mark when they complete the assigned chore.  Today the Chore tracking is treated more like an Admin function where I pick a chore from a list and then enter it.  Ideally something like this is what I imagine.  

![chore_tracking](https://user-images.githubusercontent.com/6667779/57873867-ee855b80-77d4-11e9-8be3-573d68c36040.png)

**Comment by TheXenocide** [comment]
I'm just getting started and haven't put much time into the chore side yet, but chore assignment rotations and a convenient way for users to see chores assigned to themselves (maybe with due dates) sound like very helpful features.

**Comment by JoschaMiddendorf** [comment]
that would be so Great.

**Comment by oncleben31** [comment]
Love to see this. I come to Grocy for the chore management in our family.

**Comment by berrnd** [comment]
This is now done. :)

On the chore edit page different "assignment types" can be selected...
![grafik](https://user-images.githubusercontent.com/2161815/65037230-7d55e080-d94d-11e9-8dae-dccac3ff903b.png)

...and also multiple users can be assigned:
![grafik](https://user-images.githubusercontent.com/2161815/65037277-99598200-d94d-11e9-855e-14ef62fced31.png)

Then based on the assignment type, after each execution the next assignment is calculated - and displayed on the chores overview page incl. the ability to filter for "my" chores (dark gray button or "Filter by status"):
![grafik](https://user-images.githubusercontent.com/2161815/65037381-db82c380-d94d-11e9-85ea-ed1f0e10abf6.png)

If you have further ideas on this, please let me know or just open separate issues for them - and feel free to play around with it on the pre-relase demo: https://demo-prerelease.grocy.info/choresoverview
