### ISSUE TITLE
Bug: composer tries to install an old version of slim/http and slim/rs7

### ISSUE THREAD

**Issue by platyple** [grocy/grocy#2530]
Hey there!
this may be a bug with Composer and not Grocy, but when deploying Grocy on an old raspi i noticed that Composer fails when pulling the dependencies
```JSON
"slim/psr7": "^1.0",
"slim/http": "^1.0",
```
Composer pulls 1.0.0 for both, which are incompatible with php8, and then fails.

After some digging, changing composer.json to 
```JSON
"slim/psr7": "^1",
"slim/http": "^1",
```
pulls the correct version, don't ask me why.

Reading the Composer documentation `^1.0` _should_ behave as is intended here so unless something changed or i'm misinterpreting what little there is this could be a bug in Composer, so feel free to close this.

Thanks :)

**Comment by berrnd** [comment]
> this may be a bug with Composer and not Grocy

More than clearly that's the case, hence reporting here is pretty much only wasting (my) time (thanks).

&nbsp;
Composer doc ref: https://getcomposer.org/doc/articles/versions.md#caret-version-range-

So everything is correct, don't know what you get, I would first make absolutely sure to not use and outdated af composer version.

Also performance on Raspberry Pis, especially old ones, will be slow as hell and I don't get why you don't simply use the release ZIP which already contains all dependencies (using the desired and correct version of each one).
