### ISSUE TITLE
Feature Request: Consume ingredients for a recipe based on number of servings

### ISSUE THREAD

**Issue by BaccanoMob** [grocy/grocy#2536]
Most of the recipes are for 1 person so having consume in the recipe menu screen is a real help. 

While it is okay for daily use, having a option to consume based on number of servings that day would be really handy. For example, if I have to cook for 4-5 people for an occasion, manually consuming by clicking it 4-5 times or calculating the exact amount for ingredients used (can be confusing if there are sub recipes and you update the inventory a bit late) would be an annoying process.

I would like it if there is an additional button similar to the one in stock. Maybe instead of `ALL` it should be `#` or `+` or `++` to denote you can consume multiple servings at once.

![image](https://github.com/grocy/grocy/assets/82655889/3a03eed1-5b31-44dc-833e-5ee548a288ad)

**Comment by berrnd** [comment]
Well, you define a recipe and then consume each ingredient manually one by one on [/stockoverview](https://demo-prerelease.grocy.info/stockoverview) - why that?

This button per recipe on [/recipes](https://demo-prerelease.grocy.info/recipes) exactly consumes the amount based on the "Desired servings" selected.

![grafik](https://github.com/grocy/grocy/assets/2161815/80410df9-bc03-416c-8556-222703e13db6)

So this is already possible.
