### ISSUE TITLE
Bug: "This page does not exist" rewrite loop after installation (Debian 12/nginx/PHP 8.x)

### ISSUE THREAD

**Issue by YoSiJo** [grocy/grocy#2539]
# Installation

```bash
apt install \
  nginx \
  certbot python3-certbot-nginx \
  php php-fpm php-sqlite3 php-gd php-intl php-mbstring \
  unzip sudo wget

mkdir /var/www/grocy &&
cd /var/www/grocy

wget https://releases.grocy.info/latest &&
unzip latest &&
chown --recursive www-data: .

sudo --user=www-data cp config-dist.php data/config.php
```

Then: `vim data/config.php`

```php
Setting('BASE_PATH', '');
…
Setting('BASE_URL', '/');
…
```

Now edit the default nginx config and only replace the `server_name` for the ACME Chalange: `vim /etc/nginx/sites-enabled/default`

```nginx
…
    server_name grocy.example.com;
…
```

Run `certbot` and get a Cert with config changes for nginx.
Alter this we reedit the nginx default config for grocy:  `vim /etc/nginx/sites-enabled/default`

```nginx
server {
    server_name grocy.example.com;

    listen [::]:443 ssl ipv6only=on; # managed by Certbot
    ssl_certificate /etc/letsencrypt/live/grocy.example.com/fullchain.pem; # managed by Certbot
    ssl_certificate_key /etc/letsencrypt/live/grocy.example.com/privkey.pem; # managed by Certbot
    include /etc/letsencrypt/options-ssl-nginx.conf; # managed by Certbot
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem; # managed by Certbot

    root /var/www/grocy/public;

    location / {
        try_files $uri /index.php$is_args$query_string;

        location ~* \.(php|inc)$ {
            include fastcgi.conf;

            fastcgi_pass unix:/run/php/php-fpm.sock;
            fastcgi_index index.php;
            fastcgi_intercept_errors on;
            fastcgi_buffer_size 16k;
            fastcgi_buffers 4 16k;
        }
    }
}
server {
    if ($host = grocy.example.com) {
        return 301 https://$host$request_uri;
    } # managed by Certbot

    listen [::]:80 default_server;

    server_name grocy.example.com;
    return 404; # managed by Certbot
}
```

`nginx -t && nginx -s reload`

When you now open the Site https://grocy.example.com you see the message `This page does not exist` and after 5 Sec, you are rewrite to https://grocy.example.com and again and again…

# Context

Of course I can see the connection to the issue [#1404](https://github.com/grocy/grocy/issues/1404) and therefore know that I should go to the [SubReddit](https://www.reddit.com/r/grocy/); But I openly admit that I am not willing to create an account on Reddit and there is also a discussion function on Github.

In addition, I have already tested many variants of the VHost Config and also tested several variations of `BASE_PATH` and `BASE_URL`; however, the error pattern has never changed.
Therefore I think it is also possible that there is a problem with the IPv6 only stack.
However, I could not find a logging function or anything like that in the configuration, so I don't know how I could debug this further.

**Comment by berrnd** [comment]
This is clearly a configuration issue and not a reproducible Grocy Bug, but this here is the tracker for such reproducible Bugs and Feature Requests and not your personal setup problems ([README ref](https://github.com/grocy/grocy?tab=readme-ov-file#questions--help--bug-reports--feature-requests)).

I also use a NGINX / PHP-FPM stack for Grocy and all of it's demo instances, serving daily more page views any private instance will see per year or so and it works more than fine - also leads to this can't be a bug in Grocy itself. Why not simply compare your stuff with the [reference config I've published](https://www.reddit.com/r/grocy/comments/15lm1he) for everyone some time ago.

&nbsp;
> Of course I can see the connection to the issue https://github.com/grocy/grocy/issues/1404 and therefore know that I should go to the [SubReddit](https://www.reddit.com/r/grocy/)

I openly admit that I find it frustrating that you're deliberately abusing this issue tracker and essentially wasting my time on a public holiday day by that, thank you.

**Comment by YoSiJo** [comment]
I'm sorry to disturb your day off, but I feel the same way and thought I'd invest some time in the FOSS project to help.

Out of sheer desperation I did `sudo --user=www-data bash update.sh` and surprisingly it works now, although I had only checked the reference data again and here again many thanks for this. I could not find any relevant changes and had already searched and found many of these configs.
In the end I only did `sudo --user=www-data bash update.sh` and the config that had been valid since several reboots was unchanged. So it seems as if parts of the config only came into effect when `sudo --user=www-data bash update.sh` was done.

I am therefore sorry to have disturbed you and ask for your understanding that there are moral and ethical problems in using Reddit and therefore, as much as I would like to, I can not help the community here as desired.

**Comment by berrnd** [comment]
> So it seems as if parts of the config only came into effect when `sudo --user=www-data bash update.sh` was done.

Simply have a look at the executed script (guess it's [that](https://github.com/grocy/grocy/blob/master/update.sh)) and notice that this script doesn't do anything to your webserver configuration, it even doesn't know if you use NGINX, PHP-FPM or whatever else on this planet is available to run PHP web applications. So this comment doesn't really help any community (I'm pretty sure the vast majority of that community even doesn't have this particular problem) or explains whatever is (was) going on your side and the fact you have personal problems with Reddit (and not GitHub in the same way, lol) is just more than irrelevant here, please focus on the technical / content-related points for future requests, thanks.

I guess you simply forgot to unpack the release ZIP completely before and `update.sh` has "fixed" that. Or you have caching involved and forgot to restart PHP-FPM or something like that.
