### ISSUE TITLE
Bug: Impossible to add or edit a location

### ISSUE THREAD

**Issue by Kevisin** [grocy/grocy#2544]
When I click on Add in the Location page, or when I try to edit the only location I have left, I get a popup with php code inside. Please see bellow the code shown and the screenshot

![Capture d'écran 2024-06-11 143333](https://github.com/grocy/grocy/assets/172393546/6b245c0e-8482-409e-a568-9b8c11c61c75)

> @extends('layout.default') @if($mode == 'edit') @section('title', $__t('Edit location')) @else @section('title', $__t('Create location')) @endif @section('content')
@yield('title')
@if($mode == 'edit') @endif
{{ $__t('Name') }} 
@if($mode == 'edit'){{ $location->name }}@endif
{{ $__t('A name is required') }}
active == 1) checked @endif class="form-check-input custom-control-input" type="checkbox" id="active" name="active" value="1"> {{ $__t('Active') }}
{{ $__t('Description') }} 
@if($mode == 'edit'){{ $location->description }}@endif
@if(GROCY_FEATURE_FLAG_STOCK_PRODUCT_FREEZING)
is_freezer == 1) checked @endif class="form-check-input custom-control-input" type="checkbox" id="is_freezer" name="is_freezer" value="1"> {{ $__t('Is freezer') }}  
@else @endif @include('components.userfieldsform', array( 'userfields' => $userfields, 'entity' => 'locations' )) {{ $__t('Save') }}
@stop

I succeeded to add a location yesterday but this is not working anymore. Is it because I deleted the default location created with the installation ?

**Comment by Kevisin** [comment]
![Capture d'écran 2024-06-11 143333](https://github.com/grocy/grocy/assets/172393546/6c26b240-d4fb-44d3-9f1e-93ec1f2be0e2)

**Comment by berrnd** [comment]
> I succeeded to add a location yesterday but this is not working anymore.

I haven't changed anything about your web server between yesterday and now and neither anything about Grocy since months.

&nbsp;
> Is it because I deleted the default location created with the installation ?

More than most likely not. When you see PHP code client side, your web server is clearly doing something wrong. This is clearly a web server configuration issue, so nothing to fix here.

**Comment by Kevisin** [comment]
Thank you for your help.

**Comment by berrnd** [comment]
> Is it because I deleted the default location created with the installation ?

Just to add: This is easily self-provable by e.g. simply spinning up a [private demo instance](https://www.reddit.com/r/grocy/comments/jwnk9b) - did that for you there: https://test-kpyhhfzwe8cz5opw6xhypl.demo-prerelease.grocy.info

On that demo instance I've deleted all locations, even though some were currently in use / had stock. This makes absolutely no sense and of course breaks stuff logically (e.g. the stock overview page doesn't show anything from invalid / deleted locations), but of course doesn't lead to seeing PHP code as plain text client side.
