### ISSUE TITLE
Can't delete meal plan from calendar

### ISSUE THREAD

**Issue by philhawthorne** [grocy/grocy#255]
When clicking the delete button on the calendar, a Javascript error occurs and the meal is not deleted from the calendar.

```
SyntaxError: JSON.parse: unexpected character at line 1 column 1 of the JSON data mealplan.js:101:27
    <anonymous> http://XXX.XXX.XXX.X:9283/viewjs/mealplan.js?v=2.4.1:101
    jQuery 2
        dispatch
        handle
```

**Comment by matejdro** [comment]
Checking `mealplan.js`:

In line 103 it attempts to get data from the parent about the calendar entry:
`var mealPlanEntry = JSON.parse($(this).parent().parent().attr("data-meal-plan-entry"))`;

However, for me it appears that meal data is 3 levels up from button, not 2, so adding another `.parent()` call seems to fix it.

**Comment by matejdro** [comment]
I'm pretty bad at javascript, but shouldn't there be a better way to do this? maybe finding a parent with ID? That way layout changes won't break buttons.

**Comment by berrnd** [comment]
> I'm pretty bad at javascript, but shouldn't there be a better way to do this? maybe finding a parent with ID? That way layout changes won't break buttons.

Sure, for me grocy is just a hobby project where I focus on the end result, so probably not the best showcase when it comes to coding style in general...

**Comment by matejdro** [comment]
I agree with you, my hobby project are usually too pretty crappy code style wise. I was just throwing out a suggestion to reduce maintenance overhead.

**Comment by philhawthorne** [comment]
Thanks @berrnd and @matejdro 

If it helps, there is the `parents()` function which could be used

```js
var mealPlanEntry = JSON.parse($(this).parents(".fc-h-event:first").attr("data-meal-plan-entry"));
```

This would grab the first parent item with the class `fc-h-event`. The current solution `closest()` could go to a child element if it is closer. But, I don't think this matters too much.

Cheers for the great work again

**Comment by berrnd** [comment]
Thanks for the suggestion - just changed it like you proposed... :)
