### ISSUE TITLE
Feature Request: Copy grocycode to clipboard

### ISSUE THREAD

**Issue by wfjsw** [grocy/grocy#2551]
I am still trying to figure out what is the best printing solution for me. Currently my QL-800 is connected to my laptop and it is quite uncomfortable trying to set up a webhook on that, especially as it is on Windows and it moves around a lot. The open stock entry label does not help much as its styling makes it unable to print straight out on a 2.4" x 1.1" label.

![image](https://github.com/grocy/grocy/assets/2220320/ffa563fa-aed5-422a-a4ed-9776edd383e4)
(the barcode is not readable at all)

So currently I am manually transfering the grocycode to P-Touch Editor:

![image](https://github.com/grocy/grocy/assets/2220320/edd6d964-1d4b-4606-bdd5-c9fec239147f)

But I find out it is hard to actually **get the barcode content** from site. I need to point my barcode scanner to the screen to read it, and it sometimes becomes unreadable because of the size and the background.

So I think it might be helpful to have an option to copy these content on the site.

**Comment by berrnd** [comment]
Grocycodes are meant to be printed and scanned, not manually entered or anything like that. Label printing in Grocy is based on Webhooks and everything styling and the rest is up to your Webhook Receiver ([doc ref](https://github.com/grocy/grocy/blob/v4.2.0/docs/grocycode.md)).

What you've described is simply a problem about your personal way of how you print stuff.
Fix that and everything will work as it's supposed to work.

Reality check: Manually copy & pasting a Grocycode into another software, fiddle around with it there and manually printing that is really more time saving than simply manually searching/selecting the corresponding stock entry? I doubt it.

**Comment by wfjsw** [comment]
It feels weird having the server actively connecting to my computer, but ymmv. It would be far better if printing straight from the browser works, but it does not, yet.

> Reality check: Manually copy & pasting a Grocycode into another software, fiddle around with it there and manually printing that is really more time saving than simply manually searching/selecting the corresponding stock entry? I doubt it.

It is. Most of the time I don't need to resort to a computer while checking out stuffs with barcode, using a scanner connected directly to the server. On the other hand, searching and selecting requires either mobile phone or computer access.

**Comment by berrnd** [comment]
> It would be far better if printing straight from the browser works

It works, you named the stock entry Grocycode preview above, but it's not optimized for any page / label size on that planet so far - already tracked in #1623.

&nbsp;
> It feels weird having the server actively connecting to my computer

Well, if network connections from your own (hosted, meant to be trusted) services are giving you a weird feeling, maybe shutting down everything immediately is the only solution for that...
