### ISSUE TITLE
Bug: Recipes: Shopping list icon disappears when FEATURE_FLAG_STOCK is set to false

### ISSUE THREAD

**Issue by StevenBay** [grocy/grocy#2552]
Reproduction:
Set a picture for a recipe

Issue:
The icons `Consume all ingredients needed by this recipe` and `Put missing products on shopping list` disappear.

Temporary fix:
Delete picture of recipe

Example:
Without recipe picture:
![2024-07-13_105500-Rezepte _ Grocy - Vivaldi](https://github.com/user-attachments/assets/9396f1da-158e-4ff7-bdec-525f0db22721)

With recipe picture:
![2024-07-13_105550-Rezepte _ Grocy - Vivaldi](https://github.com/user-attachments/assets/a9262716-9ae4-4cec-8388-5e477b777aab)

**Comment by berrnd** [comment]
Please be so kind and provide a 100 % reproducible example, not just a random example from your private instance I'm unable to look into - [persistent demo instances](https://www.reddit.com/r/grocy/comments/jwnk9b) are made for exactly that (and that's also mentioned on the issue template).

Here's a demo instance / a recipe with a picture: https://test-sehy1bwp3nyfqewhkhs.demo-prerelease.grocy.info/recipes?recipe=3

All buttons are visible on standard 1080p screen size:

![grafik](https://github.com/user-attachments/assets/7ac0b340-a55c-4c6a-8cee-109f0a41a0ea)

All buttons are visible on a random smaller screen size (best guess based on your screenshot, you also haven't mentioned that):

![grafik](https://github.com/user-attachments/assets/0780bc83-c246-4938-ae56-394e03975cc0)

**Comment by StevenBay** [comment]
Thanks for the information about the demo instances. I forgot they existed.
I checked my settings and found out that if you set the feature flag `Setting('FEATURE_FLAG_STOCK', false);` in the `config.php` the mentioned icons disappear.
I understand that `Consume all ingredients needed by this recipe` disappears but `Put missing products on shopping list` should still be there.
Since this looks to me like a setting you can only set in the `config.php` I can't recreate it in the demo instance.

**Comment by berrnd** [comment]
> I checked my settings and found out that if you set the feature flag `Setting('FEATURE_FLAG_STOCK', false);` in the `config.php` the mentioned icons disappear.
> I understand that `Consume all ingredients needed by this recipe` disappears but `Put missing products on shopping list` should still be there.

Thanks for providing the relevant information to have this reproducible. Turns out to be completely unrelated to having a recipe picture or not - lol.
