### ISSUE TITLE
Bug: Unable to choose alternate QU in Purchase screen while Tare Weight is enabled

### ISSUE THREAD

**Issue by wfjsw** [grocy/grocy#2553]
I have a product that has its default QU set to `lb`, and enabled tare weight that is `0.03 lb`.

When Tare Weight is enabled, it is unable to choose another QU (`oz`) on the Purchase screen:

![image](https://github.com/user-attachments/assets/c3d2eb16-705b-4faa-b0e4-485c0fcb88c3)

But it is possible to do this on the Inventory screen, and the tare weight calculation is correct:

![image](https://github.com/user-attachments/assets/c3b6d892-2791-4f4d-a6d7-af6d7bb9adde)

which seems inconsistent. Is this an expected behavior?

**Comment by berrnd** [comment]
> Is this an expected behavior?

Yes. Tare weight handling currently doesn't handle unit conversion, so it's enforced to use the same unit (the product's QU stock) everywhere.

Please use the [r/grocy subreddit](https://www.reddit.com/r/grocy) for general usage questions ([README ref](https://github.com/grocy/grocy?tab=readme-ov-file#questions--help--bug-reports--feature-requests)) and don't report each and everything which is maybe not crystal clear at a first sight as a Bug here, thanks.

**Comment by wfjsw** [comment]
The only reason why I asked here is that it does look like a bug and I have intention to fix this with PR: the inventory page perfectly handle the tare weight even with unit conversion.

**Comment by berrnd** [comment]
It's never only UI, you obviously also have to take care about the math going on behind the scenes everywhere something with amounts is done.

Limitations are known, Grocy doesn't pamper the user in the sense that every possible input-bullshit is prevented at any place.

So feel free to extend that tare weight handling can work with any unit (remember that the number of the product option "Tare weight" is currently related the the product's QU stock, as accordingly outlined on the web frontend), but please do end to end tests with especially edge cases and so on before submitting a PR. Was tried in #2550 lately, reviewing not completely thought through and tested "quick fixes" are annoying to review, sorry for being honest.

&nbsp;
>  the inventory page perfectly handle the tare weight even with unit conversion.

How did you come to this conclusion? Default demo data, product "Flour" (QU stock = Gram, Tare weight = 500), it doesn't work when e.g. trying to use Kilograms on /inventory:

![grafik](https://github.com/user-attachments/assets/66cd034b-756b-41f3-88fc-0ee4e9ad7c90)

That's what I'm saying about testing stuff thoroughly, or even just a little bit at all...

**Comment by wfjsw** [comment]
It seems to be an validation error rather than math error. I didn't exhibits this because my tare weight is pretty small (0.03).

Otherwise, the calculation shown on your screenshot looks correct, or we have some disagreement on some assumptions:

1. The `Stock amount` recorded by Grocy (on the right side) is the net weight without the tare weight: 2000g (net)
2. The new weight inputted is the total weight including the tare weight: 2500g (net) + 500g (tare)
3. Grocy intends to add 500g (net) to the stock

**Comment by berrnd** [comment]
When looking only at the screenshot: Yes, it's only a validation problem (for this example).

When looking behind the scenens: There's more around.

As said, the current definition is that for tare weight only QU stock is considered, the rest maybe works, maybe not, nothing is done about it so far, every place needs a review and most likely adjustments - also as said.

&nbsp;
> what's wrong with https://github.com/grocy/grocy/pull/2550 tomorrow.

E.g. [this](https://github.com/grocy/grocy/pull/2550#discussion_r1667399430) beside the rest. He/she/it pretty much blindly applied the current selected conversion factor to just like any amount number in [consume.js](https://github.com/grocy/grocy/blob/master/public/viewjs/consume.js). Copy/pasting without thinking or testing, can't say how much I love this.
