### ISSUE TITLE
Feature Request: Per-product default shopping list override

### ISSUE THREAD

**Issue by carsonbird** [grocy/grocy#2557]
Right now, you can specify a default shopping list which items below the min stock amount are automatically added to. It would be great to also have a per-product override, or specified list to be added to instead of the default.

**Comment by berrnd** [comment]
Related to #1357, probably shopping lists per store fit reality better than per product.

**Comment by carsonbird** [comment]
Oh, like "if the product defaults to store X, put it on a shopping list connected to Store X?" Yeah, I agree.

**Comment by berrnd** [comment]
> like "if the product defaults to store X, put it on a shopping list connected to Store X?"

Yes, that's what #1357 is about.
