### ISSUE TITLE
Feature request: start of week for meal plan

### ISSUE THREAD

**Issue by lbischof** [grocy/grocy#256]
I would love to be able to set the start of the week for the meal planning calendar. I plan and buy groceries on saturday morning. Thank you for this great app!

**Comment by berrnd** [comment]
It currently uses the locale default...

I attached a patch of [`mealplan.js`](https://github.com/grocy/grocy/blob/master/public/viewjs/mealplan.js) if you want to have this now ([option `firstDay` of FullCalendar](https://fullcalendar.io/docs/v3/firstDay)).

[grocy_patch_issue256.zip](https://github.com/grocy/grocy/files/3201942/grocy_patch_issue256.zip)

**Comment by lbischof** [comment]
Wow, you reply fast (and even with a patch). Take your time. This is a nice to have feature and not a top priority.

**Comment by berrnd** [comment]
There is now a new `config.php` option for this:

https://github.com/grocy/grocy/blob/914dde4609a122362d3d594ad3b5d7d0215b01ac/config-dist.php#L24-L27
