### ISSUE TITLE
Feature Request: Picnic.app integration

### ISSUE THREAD

**Issue by PhilippRenner** [grocy/grocy#2563]
Hi, 
I would like to have an integration from picnic-app, (https://picnic.app/) so when I order something there, that after I completed the order-process, my ordered items gets automatically importet into grocy, so I dont have to add everything manual into "my warehouse"

**Comment by berrnd** [comment]
An integration for a specific app/tool/service/whatever will never be included in Grocy - if, then always using a generic approach.

Have you maybe even tried a little tiny search beforehand by any chance?
- => https://github.com/larsverp/picnic-grocy-scripts
- => https://github.com/koenieee/Grocy-Picnic
