### ISSUE TITLE
Feature Request: Mark shopping list item as "ordered"

### ISSUE THREAD

**Issue by hauweg** [grocy/grocy#257]
tolles programm, danke!! <3

wir bestellen fast alles online. es wäre schön, wenn man auf dem einkaufszettel angeben könnte, dass etwas bestellt wurde. 

die artikel könnten dann z.b. ausgegraut dargestellt sein. 

momentan muss ich mir analog notieren, was ich bestellt habe :)

**Comment by berrnd** [comment]
Ich lösche die erledigten Einträge dann einfach, aber man kann ja einen Erledigt-Haken wie bei Aufgaben hinzufügen...

Und weil wir hier ja eigtl. Englisch reden:

**TODO for this issue:**
Adding a button like "Mark as completed" per shopping list item, if clicked, the item should be displayed greyed out (just like a completed task).

**Comment by hauweg** [comment]
thank you for the quick reply! <3

if i delete it, it can happen that it is not delivered or is stuck in another department. i wouldn't notice that then.
with the hook and the gray it would be more redundant :)

**Comment by Jeltel** [comment]
This is exactly what I was looking for.
When I throw the item in my shopping cart (the physical one), I want to mark the item somehow. And your suggestion @berrnd will work.

**Comment by hauweg** [comment]
im doing it this way now:

when working in the shoping list, i edit the list entry and ad "ordered" to the note field. this is than also shown in the shoping list overview.

for me its good like that :)

**Comment by berrnd** [comment]
I added it like suggested above: :)

![2019-07-06_17-58-16](https://user-images.githubusercontent.com/2161815/60758515-e2b95700-a017-11e9-8629-f404edfc5dcb.gif)

**Comment by hauweg** [comment]
:heart:
