### ISSUE TITLE
Bug: Filter by "Product Group" in Master Data, includes other Product Groups that contains the same name.

### ISSUE THREAD

**Issue by jonaskp** [grocy/grocy#2570]
**Description:**
When having multiple product Groups, where part of the name is contained in the other, filtering in Master Data is "broken".
ie:
Group #1: "Beverages" (for milk, juice, etc.)
Group #2: "Beverages | Energydrinks"

I have it setup like this (with more groups) for some groups, because I want to split items more granulary, but still "group them together" (by having the pre-fix "Beverages").

If I go to Master Data->Products and filter by Group "Beverages", the filter also includes products with group "Beverages | Energydrinks".
So it looks like (on the surface, I have no idea how it works technically) that the filtering in "Master Data / Products" does a sort of search with "contains".

If I go to Stock Overview, and do the same filtering, it only includes the actual Group.
So "Beverages" only includes "Milk", and "Beverages | Energydrinks" only contains "Red Bull".

I have recreated it in a private demo instance (By the way, AWESOME "feature" which really makes it easy to troubleshoot and report bugs!):
https://test-yelbdb3ogbovdnij9716w.demo-prerelease.grocy.info

This is not a major thing, and I can easily live with it.
However, since the behavior is not consistent (accross Master Data and Stock overview), I am unsure if this could be causing other issues.
I did wonder if this meant that the spendings report didnt work correctly with grouping spendings, but since the filtering works as intended on "Stock Overview" I assume the Spending report does as well (and as far as I can see at a glance on my own Grocy, it does seem that the spending is grouped correctly, with now duplicating).

**
![Stock, beverages](https://github.com/user-attachments/assets/a1134f35-3f08-44f6-8fb8-60dae8f4330d)
![Master Data](https://github.com/user-attachments/assets/a5347cb7-e536-41f5-8b00-dc2e024f7887)
![Stock, beverages energydrinks](https://github.com/user-attachments/assets/a76ddfc7-0efd-4681-bc37-1d476696d0ee)**

**Comment by berrnd** [comment]
> So it looks like (on the surface, I have no idea how it works technically) that the filtering in "Master Data / Products" does a sort of search with "contains".

It does, here's the magic behind:

https://github.com/grocy/grocy/blob/c21090f5220bd5bc449d2f329f06bd454634860f/public/viewjs/products.js#L25-L34

&nbsp;

> If I go to Stock Overview, and do the same filtering, it only includes the actual Group.

Shedding some light into how that works too:

https://github.com/grocy/grocy/blob/c21090f5220bd5bc449d2f329f06bd454634860f/public/viewjs/stockoverview.js#L54-L67

&nbsp;

> I did wonder if this meant that the spendings report didnt work correctly with grouping spendings, but since the filtering works as intended on "Stock Overview" I assume the Spending report does as well

Can't follow the assumption. Filtering a table on the frontend is JavaScript stuff only, populating data is "backend stuff", so technically something completely different - another code ref for that:

https://github.com/grocy/grocy/blob/c21090f5220bd5bc449d2f329f06bd454634860f/controllers/StockReportsController.php#L61-L77
