### ISSUE TITLE
Feature Request: Enable "Table Options" for Custom User Entities

### ISSUE THREAD

**Issue by RyothJT** [grocy/grocy#2573]
Custom user entities currently lack the "Table Options" functionality, which is represented by the eye icon. This makes organizing user entities more difficult than other tables.

This issue can be observed in the following example:

https://demo.grocy.info/userobjects/exampleuserentity

In contrast to the default tables like "Recipes" or "Equipment," where the "Table Options" icon is present on the left side of the field, custom user entities do not have this option.

Please add the "Table Options" functionality to custom user entities.

**Comment by berrnd** [comment]
Well, what are you missing exactly?

Table options is about viewing/hiding columns. User Entities are entirely based on Userfields, and each Userfield has an option if it should be visible in tables or not:

![grafik](https://github.com/user-attachments/assets/aa818921-c793-42e6-8ecc-21c0edc314ba)

Column reordering and the rest is possible too, just like for any table throughout Grocy's web frontend.

**Comment by RyothJT** [comment]
Sorry I wasn't more specific. I'm specifically missing the "Group By" feature in the table options that can be accessed by clicking the "Eye" which typically appears in the top right of all tables in Grocy. However, this "Eye" is not present in userentity tables.

I'm using Grocy to organize more than just groceries and having the grouping feature present in the other tables for userentities would be appreciated.

![image](https://github.com/user-attachments/assets/5b74ac1b-d9f7-47b8-bc77-cc9172bcc4b2)

![image](https://github.com/user-attachments/assets/33ed9bee-cdf6-45d7-bb75-8a5de0d1449a)

And an example of the grouping feature in the stock overview, which can't be done at this point with userentities.

![image](https://github.com/user-attachments/assets/99ff77fd-e90b-4650-8197-85ae36f2bd9f)
