### ISSUE TITLE
Feature Request: Round amount picker's `max` by "Decimal places allowed for amounts"

### ISSUE THREAD

**Issue by stefan-muc** [grocy/grocy#2578]
I guess this screenshot says most of it:
![image](https://github.com/user-attachments/assets/bf6b3e35-cbb2-4c7d-8425-ebd60b3b480b)

I have products that have "strange" package sizes. So I have the stock amount in kilogramms, and for convenience I have product specific unit conversions. For this product, one pack is converted to 0.154 kilogramm.
For purchasing one pack this works - 0.154 kilogramms are added.
But when I want to consume 1 pack (which get's correctly converted to 0.154 kilogramms), I am not allowed. I have to change it to consume 0.154 kilogramms instead, that works.

Grocy Version 4.2.0 (but already present in at least 4.0.3)
PHP Version 8.3.8-nmm1
SQLite Version 3.37.2

**Comment by berrnd** [comment]
> I guess this screenshot says most of it:

Of course I can read the screenshot and figure everything out by hand, investing time to put it into a reproducible and debuggable scenario manually. Providing such a reproducible example on a [persistent demo instance](https://www.reddit.com/r/grocy/comments/jwnk9b) (mentioned on the issue template) would be so much nicer and saves time on my side, but wie man den Wald hineinruft und so dann halt...

Classical rounding problem, so not a bug, only solvable by something like what #389 (let the world know if you have a simpler idea) - check that and all the referenced other duplicates you've missed by not searching beforehand in case you're interested about the Why.

**Comment by berrnd** [comment]
Since I made this mistake, of course I've immediately invested half an hour for you.

First by providing an interactive screenshot: https://test-t7vjrs60glidask84j0xj.demo-prerelease.grocy.info

Then thought about how to maybe improve this specific use case without doing the whole fraction thing. An enhancement (not a bug, please simply ask if you're unsure how stuff is supposed to work in the future if your unsure, not everything not working how you personally expected it is always a bug) will be ready in minutes.

**Comment by berrnd** [comment]
And improving (nothing broken here, so nothing to fix) things would be so much more fun if people wouldn't basically throw a screenshot in only and declare each and everything as the next big bug before simply asking how stuff is supposed to work. My desire on this project gets lower and lower to be honest, often don't understand myself why I put endless time / effort into everything here. I also leave it at that for today.
