### ISSUE TITLE
Feature Request: Debian packaging

### ISSUE THREAD

**Issue by armfem** [grocy/grocy#2579]
Hi !

Really loved the application, very useful.

Since I am not that good at development and trying to learn packaging in Debian, I say to myself, why not try it with Grocy !

I will keep this issue up to date with my advances (unless you think it is not the place and/or time).

The objective is to provide a .deb file that can be easily installed in Debian 12 (and maybe 11).

**Comment by berrnd** [comment]
Feel more than free to do that, but please as a separate project - nothing related to that will be integrated into Grocy / this project directly.

Thanks anyways.
