### ISSUE TITLE
Feature Request: Userfield type "Link" / Product Userfields on shopping list

### ISSUE THREAD

**Issue by hauweg** [grocy/grocy#258]
It would be so great to be able to ad a link to to each product.

i would like to link the product page of the shop where i am ordering it.

on the shopping list it would need a button that opens that link in a new tab.

**Comment by berrnd** [comment]
Checkout the Userfields feature (see #176) - adding a field to products is possible, however it will not render as a clickable link and will not show up on the shopping list table.

So let's split this issue up into these enhancements:
- Add a new Userfield type "Link"
- Render product Userfields on the shopping list table

**Comment by berrnd** [comment]
Both is now done. :)

> - New Userfield type "Link" - a single-line-textbox where the content will be rendered as a clickable link

> - Product Userfields are now also renderd on the shopping list (for items which have a product referenced)
