### ISSUE TITLE
Bug: Removing userfields breaks stockoverview page

### ISSUE THREAD

**Issue by MarioZG** [grocy/grocy#2590]
Add Userfield to 'product' table with option to display (type text - single line, but i dont think it matters here)

remove all added field. Important - bug happens when ALL userfields are removed

Stock overview is empty, and error is logged to console.

Running version 4.2 in docker container - info on screenshot below.

![image](https://github.com/user-attachments/assets/40e3a1ba-3885-4a14-ad03-e72dc007a097)

![image](https://github.com/user-attachments/assets/8456c126-8637-4e3f-a5dd-622f4a232c9f)

![image](https://github.com/user-attachments/assets/23222aa5-b709-4865-a2b8-98e584b799eb)

**Comment by berrnd** [comment]
Simply reset the table layout (top left corner eye icon, reset button at the bottom of the dialog) and this bug will resolve itself immediately like magic.
