### ISSUE TITLE
Bug: slow performance adding to meal plan

### ISSUE THREAD

**Issue by drkp** [grocy/grocy#2591]
I have noticed recently that adding an entry to the meal plan is slow once there are already a few items on the weekly plan. Once there are maybe 10 items in the week, the insert query takes so long that it times out. 

After some investigation, it seems like the bottleneck is the prevent_infinite_nested_recipes trigger when re-generating the nesting entries for the day and week recipes.

Table sizes for context:
- recipes: 234 (84 normal)
- meal_plan: 131
- recipes_nestings: 3864
- recipes_nestings_resolved: 4253

Computing recipes_nestings_resolved takes about 0.9 seconds on this system/DB and it has to be called repeatedly.

Idea: can we skip the infinite nested recipes check when adding to a day/week/shadow recipe, since I don't think anything else could include one of them as a nested recipe?

**Comment by berrnd** [comment]
You haven't provided any details or a reproducible example. My glass sphere is out of order, so I can't say anything useful - do you if I'd have opened such an issue in one of your projects?

Table size is pretty much irrelevant. Most likely you use an outdated SQLite version or a machine slow as hell or haven't cleaned up redundant QU conversions as mentioned in the [v4.0.0 changelog](https://grocy.info/changelog#v4.0.0), at least to was the "problem" on anything performance in the last decade.

If you want to have more of my time on this, please be so kind and provide everything needed that I'm able to do that.

&nbsp;
> it seems like the bottleneck is the prevent_infinite_nested_recipes trigger

How did you came to that conclusion?

**Comment by berrnd** [comment]
> Once there are maybe 10 items in the week, the insert query takes so long that it times out.

Here's a persistent demo instance where the current week contains 20 items and adding a new one takes as long as when that week would be empty: https://test-8tixp9mnnp9lnnf0tt0zog.demo-prerelease.grocy.info/mealplan

**Comment by drkp** [comment]
Okay. I have a better idea of what is going on here now.

This problem is being caused by the sqlite optimizer selecting a very bad query plan for this query. The plan space for some of the queries is large here given the complexity of some of the views. Unfortunately that makes it hard to reproduce because it depends on both the data and the specific version of sqlite. Upgrading to the latest version (3.46.1) solves this problem but introduces other performance problems, especially making `uihelper_stock_current_overview` take >60s. I haven't yet confirmed what about my dataset is causing the problem compared to your demo instance - _possibly_ number of products (917 in my case) or the presence of many products with parent products. Not sure yet.

The specific problem that was causing this was that something caused the sqlite optimizer to choose to materialize the CTE in`recipes_nestings_resolved`, preventing predicate pushdown and forcing the full nesting graph to be resolved every time, instead of the single recipe being queried.

The issue I am seeing with `uihelper_stock_current_overview` in 3.46.1 is caused by the optimizer selecting an absurd join order.

I will send a PR with a couple simple optimizer hints that prevent this misbehavior.

**Comment by drkp** [comment]
and, for the record, my tests are running on a machine with a Xeon 8176 CPU so it shouldn't be a hardware issue! Nor does it have any redundant QU conversions.

**Comment by berrnd** [comment]
> But somewhere between there and 3.46.1 there appears to be a performance regression so you may encounter these later!
> I will send a PR with a couple simple optimizer hints that prevent this misbehavior.

Grocy is used by thousands of people and there will be complains when requiring bleeding edge SQLite releases, also if it's just about performance. I'd like to life on the edge, since more up to date stuff makes so much more fun just like always, but the golden rule to fulfill all the needs out there was to only require runtime stuff about 2 years old and that will stay like this - pleae keep that in mind and please do through testing before submitting anything (wasted a lot of time related to such things over the last few years).

&nbsp;
> a Xeon 8176 CPU

Well, that's more than 7 years old and from my daily practical experience / compared to up to date stuff slow as hell on many tasks.
