### ISSUE TITLE
Feature Request: Exclude self-produced product prices from spending reports

### ISSUE THREAD

**Issue by danielr18** [grocy/grocy#2595]
_Originally reported at: https://www.reddit.com/r/grocy/comments/1gbtrb8/should_products_created_from_recipes_affect_the/_

Currently, when a self produced product is created from a recipe, it affects the spending report as if it were a purchased item. This can lead to inaccurate spending reports.

### Proposed solution
Exclude self-produced product prices (those created from recipes) from spending reports.

**Comment by berrnd** [comment]
Done by #2596 / 5b48004449dd02ba22eec86ce42e7bc5f24e80bf.
