### ISSUE TITLE
Feature Request: Add Camera function

### ISSUE THREAD

**Issue by ScooterisT5** [grocy/grocy#2597]
- please add camera function to create a product picture quick and easy

**Comment by berrnd** [comment]
Please explain a little more detailed what you're missing where exactly.

Guessing you're referring to using Grocy's web frontend on a mobile Browser:

Any major mobile Browser on this planet already prompts to select a file or to open your default camera app, which directly puts the taken new picture into the corresponding file input (e.g. on the product edit page) to upload that just taken image. Of course that all depends on your used mobile Browser and OS. Works on current Android + current Chrome or Firefox, I don't care about anything else.
