### ISSUE TITLE
Feature Request: Meal plan without fixed dates

### ISSUE THREAD

**Issue by stephanritscher** [grocy/grocy#2600]
I would like to have the option to plan meals without deciding on the day.

Basically, roughly once a week I plan my grocery. I consider which meals I want to have over the next days (but not when), write up my grocery list based on the recipies (in Grocy, of course), and go shopping. Then, usually on a meal to meal basis, I decide what to cook based on my mood, available time and the ingredients I bought (Sometimes I also plan the meals a few days in advance). In this step, I need a "meal list" which helps me remembering to which recipies the grocery items I bought belong.

I roughly imagine my workflow as follows:

1. Select a recipie from the database. Grocy puts the ingredients on the shopping list and the recipie on the meal plan (without date).
2. Repeat 1. until enough recipies are on the meal plan for the period until the next grocery.
3. Fine tune grocery list by manually adding or removing items.
4. Go shopping, tick off shopped items.
5. Optional: Create meal plan by assigning meals on the "meal list" to specific dates (removing the date should be available too). Meals without date could be shown in the bottom (or a separate column), assignment of dates could be done with drag&drop.
6. Tick off meals which have been prepared. They are removed from the meal list. Optionally one could manage multipliers (e.g. if 2 portions have been prepared but ingredients for 4 portions have been shopped).

In the meal plan, separate views for showing only meals with fixed dates, showing only meals without fixed dates, and showing meals with and without fixed dates would make the feature flexible and avoid disturbing people not using it. In the same sense, in step 1 one should have options to put either only ingredients of a recipie on the shopping list, or only put a recipie on the meal list, or both.

**Comment by berrnd** [comment]
Grocy's meal plan is all about dates, essentially it's a calendar with appointments (= the meals or other items).

Each project/software needs a defined scope and can't help with every individual problem on this planet (unless we call this Excel, which is so far not the case).

So thanks for the suggestion, but that won't be added/changed.

**Comment by berrnd** [comment]
Grocy has the ability to add custom JS/CSS ([README ref](https://github.com/grocy/grocy?tab=readme-ov-file#adding-your-own-css-or-js-without-to-have-to-modify-the-application-itself)). So a rough idea to make what you want possible without reinventing anything:

- Force the meal plan to use the day view and always use a specific date
- Plan all meals you want then on that same day
- Hide all the stuff which is then most likely irrelevant (e.g. week costs in the header)

**Comment by berrnd** [comment]
> Grocy has the ability to add custom JS/CSS ([README ref](https://github.com/grocy/grocy?tab=readme-ov-file#adding-your-own-css-or-js-without-to-have-to-modify-the-application-itself)). So a rough idea [...]

Expanding my idea by something for the reality of today, here's a snippet (for `data/custom_js.html`) which brings that to life:

```html
<script>
if (Grocy.View == "mealplan")
{
	// Force the meal plan to always display 2000-01-01 as single day view
	if (GetUriParam("start") != "2000-01-01" || GetUriParam("days") != "0")
	{
		location.href = U("/mealplan?start=2000-01-01&days=0")
	}

	// Hide not required UI stuff
	document.head.appendChild(document.createElement("style")).innerHTML = " \
	.fc-day-header > span, \
	.fc-header-toolbar h2, \
	.fc-header-toolbar .fc-center, \
	.fc-header-toolbar .fc-right, \
	.datetimepicker-wrapper, \
	.copy-day-button, \
	thead h5 { \
		display: none !important; \
	} \
";
}
</script>
```

Will look like that:

https://github.com/user-attachments/assets/8d7f3141-7a11-4394-aa39-2a34bd580544

**Comment by stephanritscher** [comment]
Wow, that looks promising. Thanks a lot! I'll be on vacation now but definitely will look into it afterwards.

**Comment by stephanritscher** [comment]
I finally found the time to play around a bit myself. The js/css injection is awesome!!! I had to spice up my css knowledge a bit, but I was able to hide additional fields I don't use (e.g. price, calories). Nice work ❤ .

**Comment by berrnd** [comment]
> fields I don't use (e.g. price

There are also Feature Flags for most things ([README ref](https://github.com/grocy/grocy?tab=readme-ov-file#disable-certain-features), [config ref](https://github.com/grocy/grocy/blob/2b994fd2eecd187c31cb440d536d0fdf61c36d62/config-dist.php#L143)).

However, hiding kind of everything probably ends up having more or less a simple notes app - then why not simply use a notes app without all the hidden overhead.

**Comment by stephanritscher** [comment]
Thanks for pointing to feature flags, might be simpler 😁 .

I previously used a notes app and enjoy recipies and their connection with meal plan and grocery list, plus not having to type out everything on a mobile device. Though I'm still experimenting and might use more of the functionality in the future...
