### ISSUE TITLE
Feature Request: Any possibility to show picture of groceries on recipes in left ahead of name

### ISSUE THREAD

**Issue by oxedgar** [grocy/grocy#2604]
To make the recipe easier to read and more fun, displaying the thumbnail of the product photo is a good idea I think. What do you think?

**Comment by berrnd** [comment]
Everything visual is at the end subject to personal preference and a tool used by thousands of people naturally can't fit each and everyone's very personal taste.

There is a [option for custom CSS/JS](https://github.com/grocy/grocy?tab=readme-ov-file#adding-your-own-css-or-js-without-to-have-to-modify-the-application-itself) to fulfill exactly that.

I don't get what you mean exactly, maybe illustrate this a little more and when I have the time and desire to do so I maybe even provide you a custom CSS snippet to get that right now.

**Comment by berrnd** [comment]
So what do you think of exactly?

I took the time and created an example for you:

Current view:

![grafik](https://github.com/user-attachments/assets/f6783d3a-4ac0-46a4-bff9-e9aa0cdd6919)

Example somehow fiddling in the product pictures:

![grafik](https://github.com/user-attachments/assets/8c3bf524-ba37-434b-8049-ad05ada16a41)

Do you really think this makes the recipe view more clear and concise and more fun? For me not so much to be honest...

**Comment by oxedgar** [comment]
Im interested to do this. Have you any exemple of custom css or js to do that?

**Comment by berrnd** [comment]
> Have you any exemple of custom css or js to do that?

I have fiddled with that half a year ago and won't do that now again, so no.
