### ISSUE TITLE
Bug: Deleted item reappear on shopping list

### ISSUE THREAD

**Issue by UltiFix** [grocy/grocy#2608]
**Bug Description:** After deleting an item from the shopping list, if you mark another item as "done" the deleted item reappears

**How to reproduce:** delete an item from shopping list, then mark a different item as done. Notice the deleted item re-appears. This is how I show issue on demo server. In my use case I would add items below minimum stock to list, drive to store, then while in store delete items i maybe set incorrect minimum qty. etc. Then I mark other item as done and the deleted item(s) re-appear.

Here is video of the issue being reproduced on a private demo server: https://youtu.be/__GDumi6yAs

Demo Private server link: https://test-8oh81msub2q621wbhrp55j.demo.grocy.info/shoppinglist?list=1
Demo private server information: `Version 4.2.0
Released on 2024-03-15 8 months ago
PHP Version 8.3.12
SQLite Version 3.40.1
OS Linux 6.8.12-2-pve #1 SMP PREEMPT_DYNAMIC PMX 6.8.12-2 (2024-09-05T10:03Z) x86_64
Client Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:132.0) Gecko/20100101 Firefox/132.0 `

I found this bug on my setup version: ` Version 4.2.0
Released on 2024-03-15 8 months ago
PHP Version 8.3.10
SQLite Version 3.37.2
OS Linux 6.5.0-1025-gcp #27~22.04.1-Ubuntu SMP Tue Jul 16 23:03:39 UTC 2024 x86_64
Client Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:132.0) Gecko/20100101 Firefox/132.0 `

I checked on pre-release demo server. Issue persists.

**Comment by berrnd** [comment]
Just a visual / frontend glitch. The corresponding shopping list item is not really "restored" (reloading the page confirms that).
