### ISSUE TITLE
[Feature request]Plural forms, testing field

### ISSUE THREAD

**Issue by ASMfreaK** [grocy/grocy#261]
A continuation of #161 
If it is possible, it would be nice to have on `Add unit` page to have a `Test plurals field`, which could be enabled on N_plurals > 2. It is useful to test that the values entered in plurals box are correct.
The current way to test this is to save the unit and go on some page (like add product) and set up a conversion of units.

**Comment by berrnd** [comment]
That's now possible - via a button on the quantity unit edit page:

![2019-09-18_20-23-58](https://user-images.githubusercontent.com/2161815/65175091-749b0280-da52-11e9-88a7-bf089c56075b.gif)
