### ISSUE TITLE
Feature Request: Ranking / 

### ISSUE THREAD

**Issue by marzlberger** [grocy/grocy#2612]
Hello,

we buy a lot and sometime like you have sometime forgotten how the food has tasted at the end.
Can we integrate some kind of star, note or like/dislike button/field?
That would be awesome.

**Comment by berrnd** [comment]
Of course, Userfields are a way to add any field you want to any entity (= products, chores, a shopping list item, everything) you want, so simply utilize them.

Please use the the [r/grocy subreddit](https://www.reddit.com/r/grocy) for general usage questions as [mentioned in README](https://github.com/grocy/grocy?tab=readme-ov-file#questions--help--bug-reports--feature-requests).
