### ISSUE TITLE
Feature Request: Ability to Add Multiple Manuals to Equipment

### ISSUE THREAD

**Issue by CyberRad** [grocy/grocy#262]
Some of the items that I would like to add to the equipment portion of this product have multiple manuals. Repair and Owners manuals for example.

**Comment by chadmccune** [comment]
This would also be nice for keeping receipts and proofs of purchase

**Comment by berrnd** [comment]
This is now basically possible, there is new Userfield type "File" which can be used to attach any file, will be rendered as a link in tables - see #977.

Based on that, I created a follow-up issue to improve that even more for Equipment - I think a tab per file would be handy here - see #978.

**Comment by berrnd** [comment]
Cross-referencing #978 here - it's now possible to add multiple files / PDFs to each equipment by using Userfields, changelog excerpt:

> - It's now possible to add multiple files (PDFs / manuals) to each equipment
>    - Define as many Userfields for the entity `equipment` and use the type `File`
>    - => Each of those File-Userfields will be shown as a separate tab on the equipment page
