### ISSUE TITLE
Bug: Pictures are not displayed in the shopping list

### ISSUE THREAD

**Issue by oxigen-dev** [grocy/grocy#2627]
Hi,

The pictures are not displayed in the shopping list (v4.3.0 docker, but it was the same in the previous version), at least for me. In the Stock overview it gets displayed fine. @berrnd  can you please check whether it is working for you? Thanks!

![image](https://github.com/user-attachments/assets/e94333dd-5f17-4dc5-aea4-8051417b6ca1)

**Comment by berrnd** [comment]
> @berrnd can you please check whether it is working for you?

Why can't you be so kind and do that yourself using the official demo instance and instead require my time for that? And what does "The pictures" even refer to exactly? The only kind of pictures the shopping list has is barcodes, so verifying that:

=> https://test-jsj12owfmnx77ko7wdkv.demo-prerelease.grocy.info/shoppinglist

![grafik](https://github.com/user-attachments/assets/e8e1cb46-3388-49d1-b092-a053aa7ee79f)

Concludes to: Works there, so can only be a configuration problem, so nothing to track here (and please avoid reporting such stuff as big bugs in the future).

&nbsp;
> v4.3.0 docker

None of the community contributed apps/tools/integrations are maintained here.
