### ISSUE TITLE
Feature Request: User Rights Assignment

### ISSUE THREAD

**Issue by CyberRad** [grocy/grocy#263]
I believe there is a need to restrict what to allow users to do within this product. For example a child could only have access to remove stock and view their chores list.

**Comment by berrnd** [comment]
Great idea, also relates to #207.

So first we would need to define which roles/groups with which permissions would be needed. Would be great if you could make a proposal.

**Comment by CyberRad** [comment]
I would think the ability to make your own roles/groups would be beneficial. I assume each implementation (household) would want to define what they are comfortable with instead of using out of the box groups. For example I might be comfortable with my child adding items to the shopping list but others may not.

**Comment by berrnd** [comment]
Sure, I didn't mean the roles, more the "actions", or call it "permissions".

So from your example:
- View own chores
- Remove stock

These need to be defined because they need to be implemented in the destination (page) - of course you then define a own named role/group "Childs" and assign those actions/permissions to it...

**Comment by CyberRad** [comment]
Oh I see... let me brainstorm and I will get back with you.

**Comment by CyberRad** [comment]
Here is my crack at it. I am sure it is missing some functionality.

View:
Stock Overview
Shopping List
Recipes
Chores
Tasks
Batteries
Equipment
Calendar
Meal Plan

Function:
Add/Remove inventory items (Purchase/Consume/Chore/Battery)
Chore tracking/check off chore (user specific #253)
Battery tracking
Add/Remove equipment

Edit:
Any inventory item
Meal plan
Recipes
Equipment

**Comment by Wordna1** [comment]
The ability to add notes to the Meal Plan should be separate from everything else such that a given user could only have permission to mark their chores/tasks as complete, consume recipes assigned to them and add notes to the Meal Plan (eg. "I think the provided recipe should be changed in such and such manner..." or "Too many chicken-based meals have been scheduled for this day", etc)

**Comment by klausmcm** [comment]
I'd like to add that the ability to change passwords for other users should be restricted - either to admin or have the ability to create user accounts with admin privileges.

**Comment by Germs2004** [comment]
This is a great idea!  Children should not have access to "delete chores" :)

**Comment by berrnd** [comment]
This is now done, see #960.

Excerpt from the changelog:
> ## New feature: Permissions
> - Users can now have permissions, can be configured per user on the "Manage users" page (lock icon)
> - Default permissions for new users can be set via a new `config.php` setting `DEFAULT_PERMISSIONS` (defaults to `ADMIN`, so no changed behavior when not configured)
> - All currently existing users will get all permissions (`ADMIN`) during the update/migration
> - (Thanks @fipwmaqzufheoxq92ebc)

The currently added permissions will be refined and better grouped/ordered (#971).
