### ISSUE TITLE
Bug: Add Shopping List Item With Single Quote Prompts for Create or Assign Product

### ISSUE THREAD

**Issue by CyberRad** [grocy/grocy#264]
When adding a possessive named product (Maier's Premium Italian Steak Rolls) to the shopping list I am prompted to "Create or assign product" even thought the item is displayed in the drop down.

**Comment by berrnd** [comment]
We had that some days ago in #249.

Thought I fixed (and tested it), but seems not work anymore today - no one has changed anything since then ... so Murphy's law...

**Comment by CyberRad** [comment]
This looks like the opposite bug to me. It always triggers now.
