### ISSUE TITLE
Bug: Refresh moves navigation loosing field information

### ISSUE THREAD

**Issue by CyberRad** [grocy/grocy#265]
I was not able to find this listed previously but there seems to be an issue on the Meal Plan and Edit/Add Recipe in 2.4.1. When I am typing out a recipe the page periodically refreshes which causes the data in the input fields to reset. If I had saved data it reverts to it and if I am adding new data it wipes it.

I noticed similar behavior on the Meal plan screen where I am in a certain week and the page refreshes back to the current week.

**Comment by berrnd** [comment]
Hm, I could only imagine that "Auto reload on external changes" causes this, - configured in the top right corner:

![grafik](https://user-images.githubusercontent.com/2161815/58263141-c6b96900-7d7b-11e9-84b0-d36c7f779119.png)

Could you please try if that's the case by disabling this option for now if you have enabled it?

Maybe the trigger that something has changed is not the best - it's the database file modification timestamp, the database however could also be changed by a non-user interaction (e. g. on every request the "last used time" of the session/API key is updated).

But this should not be a problem when using grocy, as defined in [`grocy_dbchangedhandling.js`](https://github.com/grocy/grocy/blob/master/public/js/grocy_dbchangedhandling.js) the page reload should only occur if there was no user input for > 50 seconds and if there is no unsaved form data...

**Comment by CyberRad** [comment]
That appears to stop the refresh and in turn the reported behavior. I wonder if in this case there is a way to cache input or honor the refresh on only certain menus. For example on the Stock overview and not any of the user input areas. Although areas like the shopping list and the meal plan are going to be challenging to provide up to date data without the potential to move the navigation. I suppose you could also turn it off for those as well and update the information on a refresh initiated by a user's action.
I am not up to speed on a lot of the newer web techs but I assume other products have the same challenge and have solutions for this. We just need to find one that works within the framework of the product.

**Comment by CyberRad** [comment]
> But this should not be a problem when using grocy, as defined in grocy_dbchangedhandling.js the page reload should only occur if there was no user input for > 50 seconds and if there is no unsaved form data...

Maybe there is a bug there with detecting unsaved data/input.

**Comment by berrnd** [comment]
Seems so, the CSS class `is-dirty` is applied to the `<form>` when there was a change on any input field, which is then checked if there are any forms with unsaved data on the page - seems not to trigger when just selecting an entry from the dropdown by mouse, only when the input was typed - so this can be fixed...
