### ISSUE TITLE
[Feature Request] Calories / Summarize (numeric) Userfields per recipe

### ISSUE THREAD

**Issue by kontakt** [grocy/grocy#268]
It would be very handy to have a way to add calories to the food items, and then use that number to calculate the total cal for a recipe.

**Comment by berrnd** [comment]
To add the field to products you can do this by creating a Userfield, see #176.

But that will not summarize per recipe, let's see how we can add this in a generic way as an extension for Userfields...

**Comment by berrnd** [comment]
I decided to add this as an built-in field for products, will then be summarized per recipe based on the selected serving amount and shown in the header of the recipe (next to the costs).

=> https://demo-prerelease.grocy.info/recipes

**Comment by kontakt** [comment]
Awesome!
