### ISSUE TITLE
Barcode field not saved on product unless tab to save 

### ISSUE THREAD

**Issue by hannahswain** [grocy/grocy#269]
Tested on Grocy `2.4.1` on mobile and desktop. This had been working for me, and originally thought it was user error - testing shows issues in multiple scenarios.

Update: turns out that you need to enter the barcode and then hit tab, at which point the barcode is saved. If you don't tab, but use the mouse/cursor to jump straight to another field, the barcode value is never saved.

![Annotation 2019-05-27 184550](https://user-images.githubusercontent.com/17844465/58431907-38f9b880-80b0-11e9-9519-d9b06292b00f.png)

I'm not sure if there's a way to make this clearer, or if this was purely user confusion. 

Tested by editing the product: 

1. Edit product
2. Add a barcode (or use 123 for quick testing)
3. Save the product
4. Edit the product and note that the barcode field is empty

Tested on purchase > link existing workflow:

1. Enter purchase product
2. Enter barcode
3. Select existing product
4. Fill in other relevant details and save product purchase
5. Check the product's settings and note that the barcode field is empty

Tested on purchase > add new product workflow:

1. Enter purchase product
2. Enter barcode
3. Choose to add a new product
4. Fill in new product details and submit > return to purchase form
5. Search for new product by barcode > nothing is found
5. Check the product's settings and note that the barcode field is empty

**Comment by berrnd** [comment]
> Update: turns out that you need to enter the barcode and then hit tab, at which point the barcode is saved. If you don't tab, but use the mouse/cursor to jump straight to another field, the barcode value is never saved.

Yes, that's the case. So let's improve this that the barcode is also saved when just leaving the textbox.

But also on other places where you scan products (like the purchase/consume page) it would not jump to the next field automatically, but maybe your Barcode Scanner could be configured to send a `TAB` after each scan (see the short note: https://github.com/grocy/grocy#barcode-readers).

**Comment by hannahswain** [comment]
Lovely, thank you!
