### ISSUE TITLE
Feature Request: 

### ISSUE THREAD

**Issue by sterckxkevin** [grocy/grocy#270]
Hi,
could there be a possibility to:
Add a option to add the store were the produce has been bought.
Add a option per store to print or mail the grocery list?
Add a option that works with barcode scanner? (eg scan a product and let the system ask if you bought it or used it or something in that trend ;) )

Thank you in advance and thank you for this wonderfull software!

**Comment by berrnd** [comment]
>  Add a option to add the store were the produce has been bought.

You could add a Userfield (see #176) to products to maintain the store per product, however, this will not show up on the shopping list (rendering product Userfields there is part of #258).

> Add a option per store to print or mail the grocery list?

Adding the ability to print the shopping list is tracked in #245.

> Add a option that works with barcode scanner? (eg scan a product and let the system ask if you bought it or used it or something in that trend ;) )

So you mean page where you scan a product, then a popup "Bought" or "Used" and then a redirect to the "normal" Purchase/Consume page? Could be added of course, but I don't see the advantage at first sight...

**Comment by berrnd** [comment]
Closing this for now, feel free to reopen it when you have further ideas for the last point above.

**Comment by JoschaMiddendorf** [comment]
> Add a option that works with barcode scanner? (eg scan a product and let the system ask if you bought it or used it or something in that trend ;) )

> So you mean page where you scan a product, then a popup "Bought" or "Used" and then a redirect to the "normal" Purchase/Consume page? Could be added of course, but I don't see the advantage at first sight...

I actually like that idea. I would just scan an empty box of an item before throwing it away, to remove it from stock when its empty. That wold be so convenient.

**Comment by berrnd** [comment]
Is already possible on the normal `/consume` page...
