### ISSUE TITLE
Feature Request: Product pictures in stock overview table

### ISSUE THREAD

**Issue by eddieste79** [grocy/grocy#273]
Good morning,
First of all, I wanted to congratulate you on the beautiful GROCY project.
Later I wanted to ask you if it was possible to insert the product preview in the Stock overview grid.
thank you
Good day.

![grocy](https://user-images.githubusercontent.com/51377887/58897044-b304ef80-86f7-11e9-97ca-e8cd6110fb6c.jpg)

**Comment by berrnd** [comment]
Thank you. :)

How should it look like at the end? Displaying the product picture on each row is not an option I think - too much white space then...

Or the picture at the left or right side and always display the one of current selected row? Then it would be not that much different than the current approach with the popup...

**Comment by eddieste79** [comment]
I thought of an image for each line, perhaps creating an extra column.
In my opinion it is simpler to have the images available to search for a specific product during the scrool phase.
Possibly raise the height of the lines a bit (better if it can be set according to your needs) in order to have an adequate display.
In case of missed image insert a default one.
thank you


![grocy](https://user-images.githubusercontent.com/51377887/58899192-97e8ae80-86fc-11e9-8c73-0aa399072259.jpg)

**Comment by berrnd** [comment]
Ok, thanks for the mockup - let's add this and also a config option somewhere to change which fields/columns should be displayed...

**Comment by eddieste79** [comment]
Thanks for your time.

**Comment by eddieste79** [comment]
Hello, are there any news about the implementation of the image column? thanks

**Comment by berrnd** [comment]
https://github.com/grocy/grocy#roadmap

**Comment by eddieste79** [comment]
> https://github.com/grocy/grocy#roadmap

thank you for the annoying punctuation and availability. Good bye

**Comment by berrnd** [comment]
Sorry that I (and others) have invested countless hours into grocy and provided everything to you for free. If there is a way I can compensate you for that, let me know how.

Open Source thrives from contributions. If you can't contribute, that's no problem - often feedback/feature request comments are motivation enough to speed things up. Perfect examples for that are a lot other feature requests here.

Comments like yours are the exact opposite of that, I'm more than happy that the majority of grocy users (but not limited to grocy itself) are not like you.

Have never declined a feature request so far for grocy, but I feel I need to honor you (you're the first  - congratulations!):
**This will be closed as wontfix, unless requested/wanted by anyone else.**

**Comment by eddieste79** [comment]
I thank everyone and all the time that anyone has invested in the project. my comment was only related to the dry answer with a single link in response to a question that I thought was not so unpleasant. The irony and completeness of the answer obviously makes it clear that in addition to being offended, for who knows what reason, you have bad feelings at heart. obviously I am not here to ask for anything because I rightly don't have to do it and therefore good job and goodbye

**Comment by berrnd** [comment]
I'm just tired of answering question which could be anwered by yourself by just reading publicly available information. Asking for when something is ready is annoying - this here is an issue *tracker*, so made for tracking progress. Also both mentioned things are not limited to grocy. It's just about wasting (your and my) time...
