### ISSUE TITLE
Downscale/Resize images and use the smaller ones where appropriate

### ISSUE THREAD

**Issue by eddieste79** [grocy/grocy#275]
it is possible to implement a sort of product image resizing when attaching the image. I noticed that, using the mobile phone to take pictures of the products, the file is uploaded to my raspberry in maximum resolution. consequently, given that my small server does not have great performance in writing and reading files, the result is a certain slowness in loading the image of the product.

I tried resizing the images directly from the grocy directory and noticed a big performance improvement.

Thank you

![grocy_picture](https://user-images.githubusercontent.com/51377887/58913360-4fd98400-871c-11e9-8190-45b80e644821.JPG)

**Comment by berrnd** [comment]
This is now done. :)

All images will be downscaled (and saved in the same directory) to the appropriate size when first serving them. So the first request of a picture might take longer, but all subsequent request should be much faster...
