### ISSUE TITLE
Feature Request: calendar start of day / en_GB localization missing

### ISSUE THREAD

**Issue by karkaaa** [grocy/grocy#276]
Hello,

I use docker and i want set start of week Monday. Is that possible?
![image](https://user-images.githubusercontent.com/34538939/58934410-13854280-8773-11e9-9acb-4a8945957410.png)

p.s. and set time format to 24h in header.
![image](https://user-images.githubusercontent.com/34538939/58934371-f2bced00-8772-11e9-9359-b1aa4149c102.png)

Thanks.

**Comment by berrnd** [comment]
Start of week is determined by the used FullCalendar locale - so is part of the grocy localization - see for the same question #208.

The time format in the header is also locale specific, see for example the [German demo](https://demo-de.grocy.info) where the default format is 24h.

If you want to customize it completely, it's defined here:
https://github.com/grocy/grocy/blob/167e57ef3f41b4fdb5cbacf4a1959d7c277fd965/public/js/grocy_clock.js#L8-L9

**Comment by karkaaa** [comment]
I drop the folder in the attached ZIP into `/localization` and set the appropriate` /data/config.php `setting `(Setting('CULTURE', 'en_GB');)`

And get this error:

`2019/06/05 10:14:45 [error] 287#287: *8 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught InvalidArgumentException: '/app/grocy/services/../localization/en_GB/chore_types.po' is not a valid file in /app/grocy/vendor/gettext/gettext/src/Extractors/Extractor.php:37
Stack trace:
#0 /app/grocy/vendor/gettext/gettext/src/Extractors/Extractor.php(16): Gettext\Extractors\Extractor::getFiles('/app/grocy/serv...')
#1 [internal function]: Gettext\Extractors\Extractor::fromFile('/app/grocy/serv...', Object(Gettext\Translations), Array)
#2 /app/grocy/vendor/gettext/gettext/src/Translations.php(174): call_user_func('Gettext\\Extract...', '/app/grocy/serv...', Object(Gettext\Translations), Array)
#3 [internal function]: Gettext\Translations->__call('addFromPoFile', Array)
#4 /app/grocy/vendor/gettext/gettext/src/Translations.php(153): call_user_func_array(Array, Array)
#5 /app/grocy/services/LocalizationService.php(48): Gettext\Translations::__callStatic('fromPoFile', Array)
#6 /app/grocy/services/LocalizationService.php(18): Grocy\Services\LocalizationService->LoadLo" while reading response header from upstream, client: 192.168.1.2, server: _, request: "GET / HTTP/1.1", upstream: "fastcgi://127.0.0.1:9000", host: "192.168.1.1:9283"
`

**Comment by berrnd** [comment]
The localization file format changed since then, so here a new ZIP with the `en_GB` localization:

[en_GB.zip](https://github.com/grocy/grocy/files/3255996/en_GB.zip)

And against what I said there, the `en_GB` localization is not part of the last release - let's track this in this issue...
