### ISSUE TITLE
UserSettings is just `br`

### ISSUE THREAD

**Issue by matejdro** [grocy/grocy#277]
Not sure what exactly is going on, but `UserSettings` on my setup is just set to `<br />`:

![image](https://user-images.githubusercontent.com/507922/59145311-47b26a80-89e2-11e9-81df-d2e61fe7d5a8.png)

Since this is not valid javascript (no quotes or any other kind of synax around it), it spews errors into console and likely breaks some stuff

Any idea what could cause this? This is on on Grocy 2.4.1

**Comment by berrnd** [comment]
Where does the "Undefined variable: userSettings in..." reference point to, [line 56 in default.blade.php](https://github.com/grocy/grocy/blob/4912dd56d11da02ab02c9526b76b23a3cb6077c4/views/layout/default.blade.php#L56)?

The mentioned variable is populated [here](https://github.com/grocy/grocy/blob/4912dd56d11da02ab02c9526b76b23a3cb6077c4/controllers/BaseController.php#L72) from the function [there](https://github.com/grocy/grocy/blob/4912dd56d11da02ab02c9526b76b23a3cb6077c4/services/UsersService.php#L53-L64).

Maybe related to #278 - probably `GROCY_USER_ID` is not set properly...

**Comment by berrnd** [comment]
After reading #278 - does this then not happen when you login without "Stay logged in" set?

**Comment by matejdro** [comment]
This happens before logging in (on the login screen). 

Ah I did not even notice that there are multiple line after br. Here is full text:

```
<br />
<b>Notice</b>:  Undefined variable: userSettings in <b>/home/web/grocy/data/viewcache/2f85c60b4e961dbfb69610d644870b639d5c581c.php</b> on line <b>56</b><br />
null;
```

That line in the view cache says:

```
Grocy.UserSettings = <?php echo json_encode($userSettings); ?>;
```

**Comment by berrnd** [comment]
Thanks - I could reproduce this and also fixed it directly, see the small change in https://github.com/grocy/grocy/commit/91116ee7688f4740b5f43fc294b11bd2d2de5e6b if you want to have it now.

(Will work on all other `bug`/`ui-bug` issues today or tomorrow and will push a new patch release then.)
