### ISSUE TITLE
Stay logged in not working on 32-bit PHP

### ISSUE THREAD

**Issue by matejdro** [grocy/grocy#278]
For me "Stay logged in" button on Grocy 2.4.1 causes login to fail.

I can login with the same account just fine without checking the box, but when checking the box and typing in exact same username and password, login page just refreshes as if I entered wrong password.

Issue could be related to #277 .

Any idea what troubleshooting steps to do next?

**Comment by berrnd** [comment]
Hm, maybe there are any errors/warnings in any PHP log?

(The credentials are checked by [that](https://github.com/grocy/grocy/blob/4912dd56d11da02ab02c9526b76b23a3cb6077c4/controllers/LoginController.php#L21-L53) function.)

**Comment by matejdro** [comment]
I've done some digging and I found that issue appears to be PHP date handling.

From what I see in SessionService's code, you take current date and just add 999 years to it. However, at least on my machine, this causes rollover in PHP and produces date `1919-12-18 08:07:01`, which is obviously expired so I'm immediately logged out.

After some googling, it appears that this is caused by 32-bit PHP, which is apparently susceptible to [Year 2038 bug](https://en.wikipedia.org/wiki/Year_2038_problem). I'm currently hosting on Raspberry PI, which runs 32-bit OS (and I don't see a reason other than this to wipe and reinstall 64-bit one).

Maybe a workaround would be to replace 999 year add with absolute `PHP_INT_MAX` date? That way it would set maximum absolute date on a given platform.

**Comment by berrnd** [comment]
Oh, many thanks for your time finding that, will be of course fixed.
