### ISSUE TITLE
Feature request  : consume product on chores

### ISSUE THREAD

**Issue by BlueBlueBlob** [grocy/grocy#279]
Hi !
It will be nice if a chore can consume a product automatically.
An exemple : I need to clean my wash machine with a specific product every month.

Sorry for my English. And good job, I love this project :)

**Comment by berrnd** [comment]
This is now done. :)

New option per chore:

![grafik](https://user-images.githubusercontent.com/2161815/65129486-a7fe7280-d9fb-11e9-98f0-060b7793d4cd.png)
