### ISSUE TITLE
Storage

### ISSUE THREAD

**Issue by Shanghaiman** [grocy/grocy#280]
We all need to storage our winter cloth in summer and summer clothes in winter but what happens when we need to find which cloth is in which box.
Or we place boxes with some items at a storage unit and the kids need something for us to find, how can we know in which box?
Can u add a 'box' feature that we can place items pictures inside, then it will create a code to that box that we could write on the box or.even print a qr code to stick on the box.
When we need an item we can look thru the pictures and find in which box it is.

**Comment by berrnd** [comment]
Let's do it in a generic way and split it up:

- Make it possible to add own objects/entities - already tracked in #242
- Make it possible to add a barcode to "everything" - already tracked in #221
- New userfield type "picture" - will be tracked in #282

**Comment by berrnd** [comment]
Just to let you know here: Custom entities/objects/list are now ready - see https://github.com/grocy/grocy/issues/242#issuecomment-532706949.
