### ISSUE TITLE
New Userfield type "picture"

### ISSUE THREAD

**Issue by berrnd** [grocy/grocy#282]
References #280.

**Comment by utrost** [comment]
Hello berrnd,
are there currently any plans to implement this new userfield of type "picture"?

**Comment by berrnd** [comment]
Sorry, no schedules from my side - grocy is only my hobby, one I like, but not the only one, and because of that, there are no release dates, it's done when it's done, maybe tomorrow, maybe tomorrow next year, everyone is invited to contribute, I appreciate all ideas and contributions.

**Comment by berrnd** [comment]
Was done by #977,
