### ISSUE TITLE
Consume products from inventory when adding recipes to meal planner

### ISSUE THREAD

**Issue by andyshutak** [grocy/grocy#283]
When i create a recipe there is the option to consume products used in the recipe immediately (deduct from inventory), however there is no way (that i know of) to deduct in advance when adding the recipe to the meal planner for future consumption. 

Could there be a way to allocate stock in advance for recipes used in the week ahead, using the meal planner feature. 
Thanks - love it so far!

**Comment by berrnd** [comment]
Sure, so will add a "Consume"-button per recipe and in the header to consume all recipes for a whole week at once (only enabled when there is enough in stock, like on the recipes pages).

**Comment by berrnd** [comment]
This is now added, like described above - a button per recipe and also one per week.
