### ISSUE TITLE
Switch products between shopping lists

### ISSUE THREAD

**Issue by hannahswain** [grocy/grocy#284]
It would be lovely to be able to realize that you added a product to the wrong list and the move it to the correct one.  When editing the product, possibly add a dropdown for the shopping list?

![Product shopping list](https://cld.wthms.co/hrqmVS+)
Full size: https://cld.wthms.co/hrqmVS

**Comment by berrnd** [comment]
Added it as you suggested - a dropdown on the shopping list item edit page. :)

![grafik](https://user-images.githubusercontent.com/2161815/60758136-0b3f5200-a014-11e9-982f-6a40033eda05.png)
