### ISSUE TITLE
Feature Request: 

### ISSUE THREAD

**Issue by Mstrrlm** [grocy/grocy#285]
New to using GitHub but a grocery receipt scanner that adds everything plus price and quantity to inventory and where you bought items from with an itemized and dollar list from stores and possible cross reference others for better price. Also coupon integration would be nice Thanks

**Comment by berrnd** [comment]
Please split things up a little bit to keep the overview and maybe check other open issues first - from what I understood what you mean:

- Importing recipes from any source is tracked in #210 and #158
- "Linking" products is tracked in #196
- You can use Userfields (see #176) to add a "Store" field to products, however, it will not show up on the purchase page to - feel free to add this as an separate idea if you need this
- "Coupon integration" is tracked in #248, as mentioned there, maybe Userobejcts would also work for that (not yet done, see #242)

Closing this here for now, feel free to open separate issues per topic if something is not covered above.
