### ISSUE TITLE
Feature Request 

### ISSUE THREAD

**Issue by Mstrrlm** [grocy/grocy#286]
Adding ability to select ingredients and search local and internet recipes that match your ingredients selected. Also maybe a recipe category such breakfast, lunch, Dinner, snack, dessert check box them it searches local and internet for recipes for your selection and that you have all the ingredients in inventory

**Comment by berrnd** [comment]
As already mentioned in #285:

- Duplicate of #210 and #158
- Add categories to recipes by using Userfields (see #176)
