### ISSUE TITLE
HTML or Markdown for product description

### ISSUE THREAD

**Issue by hannahswain** [grocy/grocy#288]
It would be great if the product description was Markdown or HTML, mostly because links aren't clickable:

![clickable links](https://cld.wthms.co/NIn714+)
Full size: https://cld.wthms.co/NIn714

This is very much a nice-to-have and isn't a high priority for me.

**Comment by berrnd** [comment]
I switched to use also the "wysiwygeditor" here (like for recipes). :)

**Comment by hannahswain** [comment]
That works, too - thank you!
