### ISSUE TITLE
require_once

### ISSUE THREAD

**Issue by Spankythemusical** [grocy/grocy#291]
I know this will be something incredibly simple that I have overlooked.  I have uninstalled/reinstalled Grocy and Apache2 numerous times, but always reach the same conclusion.  Everything installs fine, no errors.  But when I go to the URL, this is what I see:

```
<?php

require_once __DIR__ . '/../app.php';
```

I don't have much hair left to pull out, so I'm seeking any assistance available for this issue.

**Comment by Joshfindit** [comment]
Related to https://github.com/grocy/grocy/issues/202 ?

**Comment by berrnd** [comment]
Seems more like your webserver doesn't send the file through the PHP interpreter, but just outputs it as plain text...

So maybe check if PHP is installed and Apache2 is configured accordingly?

**Comment by Spankythemusical** [comment]
php -v shows:
```
PHP 7.2.19-0ubuntu0.19.04.1 (cli) (built: Jun  4 2019 14:44:42) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.2.0, Copyright (c) 1998-2018 Zend Technologies
    with Zend OPcache v7.2.19-0ubuntu0.19.04.1, Copyright (c) 1999-2018, by Zend Technologies
```
sqlite3 --version shows:
`3.27.2 2019-02-25 16:06:06 bd49a8271d6*************************************************`

Some googling advised to run `sudo a2enmod php7.2` but doing that results in `HTTP Error 500`

"Maybe try putting a .php file with that content in the directory"  Which directory are you referring to here?  Currently everything resides in `/var/www/html/` with `index.php` in the `data` folder.

As I have virtually zero experience with webservers, I really am at a loss.  Thank you for your asisstance so far.

**Comment by berrnd** [comment]
I meant the webserver root directory, so probably by default `/var/www/html`. If you have unpacked grocy there, this would also be a problem, because the web-root-directory needs to be the `/public` subfolder of the grocy release ZIP.

Also check that the `/data` directory is writable by the webserver/PHP process, and maybe check #121.

If you search for something easy to host grocy, maybe [grocy-docker](https://github.com/grocy/grocy-docker/) fits better...

**Comment by Spankythemusical** [comment]
Ok, I think I'm getting closer.  I did a complete uninstall/reinstall of Ubuntu so that I could start from scratch.
`/etc/apache2/sites-available/grocy.conf` shows:
```
<VirtualHost *:80>
  DocumentRoot /var/www/html/public
  ErrorLog ${APACHE_LOG_DIR}/error.log
  CustomLog ${APACHE_LOG_DIR}/access.log vhost_combined
</VirtualHost>
```
The zip file was unpacked in `/var/www/html` and `cp /var/www/html/config-dist.php /var/www/html/data/config.php` was performed.

I read through other issues to see if I could find a solution.  Now, if I go to `http://<IP_ADDR>/index.php/stockoverview` I am greeted with a `404 Not Found`, with `The requested URL /login was not found on this server` being the description.  

I'm not giving up on this.

**Comment by Spankythemusical** [comment]
Even though you cannot see it, I am getting odd looks while I do my happy dance!  After 3 days and endless Google searches, it all came down to one option.

[https://stackoverflow.com/questions/18853066/404-not-found-the-requested-url-was-not-found-on-this-server](url)

This entry:

**In Ubuntu I did not found httpd.conf, It may not exit longer now. Edit in apache2.conf file working for me.**

```
cd /etc/apache2
sudo gedit apache2.conf
```
**Here in apache2.conf change**

```
<Directory /var/www/>
     Options Indexes FollowSymLinks
     AllowOverride None
     Require all granted
</Directory>
```
**to**

**<Directory /var/www/>
        Options Indexes FollowSymLinks
        AllowOverride All
        Require all granted
</Directory>**

**Comment by berrnd** [comment]
Great that you got it working. :)

I changed the title here, so maybe others will find this better if they have a similar problem in the future...
