### ISSUE TITLE
Lists are unpopulated on iOS 9

### ISSUE THREAD

**Issue by thies226j** [grocy/grocy#292]
Hi there,
I am trying to set up an old iPad 2nd Gen as an always on-kitchen display.
Sadly the UI isn't showing any entrys in any list(shopping, users, recipes and so on). On every other device the app is working fine.

**Comment by berrnd** [comment]
If you can check the JavaScript console output, I could maybe check if it's possible to fix it - I personally don't really care about supporting old browsers ... maybe you can just use Firefox or Chrome there?

**Comment by thies226j** [comment]
How can I do that?
Using a different Browser sadly isnt an Option as Apple requieres all Browsers to use the default rendering Engine.

**Comment by berrnd** [comment]
> Using a different Browser sadly isnt an Option as Apple requieres all Browsers to use the default rendering Engine.

Ah ok, didn't know that ... and sorry, can also not help with it ... I don't have and never used any iOS device...

**Comment by berrnd** [comment]
Closing this for now, feel free to reopen it if you found a way to reproduce this in an desktop browser which uses the same rendering engine version or if you found out which JavaScript part breaks it...

**Comment by MokkaSchnalle** [comment]
Is this also the case in iOS 10?
I just picked up an iPad 4 to use it as a kitchen display.
