### ISSUE TITLE
Double URL Redirection

### ISSUE THREAD

**Issue by JoschaMiddendorf** [grocy/grocy#293]
When adding a Barcode to a product via the workflow, it is redirecting me to 

https://subdomain.domain.de/https://subdomain.domain.de/purchase?addbarcodetoselection=%245000112546415

is that maybe a configuration mistake, PHP or NGINX?
I would be glad for any hints.

**Comment by berrnd** [comment]
Cannot reproduce this on the current demo...

Maybe double check your `BASE_URL` config setting.
[Here](https://github.com/grocy/grocy/issues/206#issuecomment-480944739) is a full example nginx/PHP-FPM config for reference, [here](https://github.com/grocy/grocy-docker/issues/15#issuecomment-486579894) another one - the config behind the [en demo instance](https://demo-en.grocy.info).

Maybe that helps...

**Comment by JoschaMiddendorf** [comment]
Thank you.
I had my BASE_URL set to "/" that allowed the error to occur. Now I have it set to 'https://grocy.domain.de/' 
I thought that isn't necessary when running directly under the root of a (sub)domain but now it works.
If you want to investigate in that behavior on my setup, fell free to ask for additional information.
