### ISSUE TITLE
Redirection to Page Not found when feature deactivated

### ISSUE THREAD

**Issue by JoschaMiddendorf** [grocy/grocy#294]
When clicking the Grocy logo, or when entering just the bare URL, I'm getting redirected to the equipment section as a sort of Start page. This is problematic because I actually deactivated that feature, and therefor getting a Page Not found error. Can the Start page be changed in any way? Any activated feature would be great, selectable would even be better.

**Comment by berrnd** [comment]
Seems to be not handled correctly in [`GetEntryPageRelative`](https://github.com/grocy/grocy/blob/4c2cf4944df3c90425ebeb674214eca1c1e70c4b/controllers/SystemController.php#L42_L60).

Adding the ability to set a custom homepage is already done by @nielstholenaar in #290, but not merged yet...

**Comment by JoschaMiddendorf** [comment]
Thank you for the feedback. Can I correct that in any way?

**Comment by berrnd** [comment]
Sure, will be corrected altogether by #290 I think...
