### ISSUE TITLE
Cost of recipe misleading when spices included

### ISSUE THREAD

**Issue by JoschaMiddendorf** [grocy/grocy#295]
I have recipes with some spices included.
"Only check if a single unit is in stock" is checked, because not much of them will be consumed for the recipes. And in that way the whole unit of the spice won't be removed from stock by the recipe. I don't want to track all my spices by weight. 
Can an Ingredient be excluded from the price calculation?

A way to accomplish the following behavior would be great:

1. Have a Product in the Ingredients of a Recipe
2. Not reduce stock by that
3. Only Check if at least one unit is in stock
4. Replace the shown amount by a sting like "a bit of" or "a pinch of" (I accomplished that by using an empty Quantity unit and adding the string to the Variable amount. See picture below.)
5. Excluding the Product from Price calculation or even better account for it just by a select able factor of something like 0,01

![Bildschirmfoto 2019-07-03 um 01 22 34](https://user-images.githubusercontent.com/19818109/60553328-1ef86900-9d33-11e9-83af-1cd195567374.png)

**Comment by berrnd** [comment]
Great idea, let's add a field per recipe ingredient "Price factor" which defaults to `1`.

**Comment by JoschaMiddendorf** [comment]
That’s perfect.

**Comment by JoschaMiddendorf** [comment]
I think while tinkering with my first recipes I compromised the database. Is there any way to rebuild it without loosing recipes products and Stock?

**Comment by berrnd** [comment]
Hm, ok - just tried it: When a recipe is deleted which is included as a nested recpie in another one, it will still be displayed there without a name - but it can be removed from the "parent" recipe...

You could edit the database manually by using for example https://sqlitebrowser.org/.
There are only 3 tables involved:
- `recipes` is the "head" table
- `recipes_pos` is the table which holds the ingredients
- `recipes_nestings` is the table which holds nested recipes

(Recipes with a negative id are not shown in the UI, those are internal recipes used for meal planning.)

**Comment by JoschaMiddendorf** [comment]
I'll take a look at the database. 
Do I undertrand you right? recipes_nestings should be empty when there are no nested recipes and no planed meals?

**Comment by berrnd** [comment]
> recipes_nestings should be empty when there are no nested recipes and no planed meals?

Yes, that's right.

**Comment by JoschaMiddendorf** [comment]
I got the nested recipes' thing fixed.

But one more issue:
![Bildschirmfoto 2019-07-03 um 01 22 34](https://user-images.githubusercontent.com/19818109/60608004-a808b200-9dbe-11e9-83c8-02178c382df0.png)
Shouldn't the cost of the week equal the sum of all recipes?

**Comment by berrnd** [comment]
There is currently also a problem about "start of week" localization, related to #256.
(The frontend "start of week" is currently browser locale specific, what the backend uses is up to PHP or SQLite for the database queries - and SQLite uses the operating system setting, AFAIK).

Do you maybe have another recipe on 2019-06-30 and that's the missing part of the sum?

**Comment by JoschaMiddendorf** [comment]
I actually have only this single recipe in the Mealplan.

**Comment by JoschaMiddendorf** [comment]
My week and Day recipe in the Database doesnt have negative IDs by the way.

**Comment by berrnd** [comment]
Hm, if you can reproduce this on the demo, maybe then I can look into it further (if so please use the [pre-release demo](https://demo-prerelease.grocy.info), the other demos are reset every night).

And sorry, I remembered it wrong - internal recipes don't have a negative id but are [distinguished by the `type` column](https://github.com/grocy/grocy/blob/8504eb9b386228d69bb78822901ab10279935c58/controllers/RecipesController.php#L146).
(And can also be shown on the recipes page when passing [`include-internal` as a query parameter](https://demo-en.grocy.info/recipes?include-internal).)

**Comment by JoschaMiddendorf** [comment]
Difficult. I did many things to my installation. Can I maybe just send you my database, or show it to you in a Teamviewer Session? The behaviour is very weired.

**Comment by berrnd** [comment]
Sure, if it's ok for you, just send me the database and I will look into it. -> bernd@berrnd.de

**Comment by JoschaMiddendorf** [comment]
I found it. When having a Recipe for 4 servings and then adding 4 Servings to the Mealplan, the Mealplan doesn't break it down to one serving first, but calculates ingredients of 4*4=16 Servings.
Ading 1 serving to the Mealplan Calculates ingredients for 4 Servings. 
Sent you the database.

**Comment by berrnd** [comment]
Thanks, I can reproduce this now.

Also noticed that the internal recipes are not deleted when deleting a meal plan entry, resulting in that the week sum is wrong.

-> 
->

**Comment by berrnd** [comment]
So the base issues above are resolved, open for this issue as an enhancement:

**TODO**
> add a field per recipe ingredient "Price factor" which defaults to `1`.
