### ISSUE TITLE
Hide 2999-12-31 in stockoverview

### ISSUE THREAD

**Issue by JoschaMiddendorf** [grocy/grocy#296]
It would be great to have the date 2999-12-31 hidden in stockoverview.

**Comment by berrnd** [comment]
Sounds reasonable, or maybe show "Never" instead...

(Such things could also be customized individually by using [custom JS/CSS](https://github.com/grocy/grocy#adding-your-own-css-or-js-without-to-have-to-modify-the-application-itself)...)

**Comment by JoschaMiddendorf** [comment]
Sounds great. 

I hope you don’t feel annoyed by all my improvement  ideas. 
I really love your project. Great idea and excellent implementation.

**Comment by berrnd** [comment]
Absolutely ok, all ideas are very welcome... :)

**Comment by JoschaMiddendorf** [comment]
Great!

**Comment by JoschaMiddendorf** [comment]
Could you also remove the information `in 981 Jahren`
`Nie in 981 Jahren` seems a bit wired.

**Comment by JoschaMiddendorf** [comment]
After removing an Item from stock via the button, `2999-12-31 in 981 Jahren` shows up again.

**Comment by berrnd** [comment]
Thanks - fixed both things again, you can test in on the [pre-release demo](https://demo-prerelease.grocy.info/) if you want...
