### ISSUE TITLE
Wrong week-sum after deleting a meal plan entry

### ISSUE THREAD

**Issue by berrnd** [grocy/grocy#298]
When a week plan entry is removed, the corresponding internal day/week recipe is not removed/updated.

References https://github.com/grocy/grocy/issues/295#issuecomment-508224484.

**Comment by JoschaMiddendorf** [comment]
Week and day recipe still doesn't get deleted/updated after removing recipes from meal-plan.

**Comment by berrnd** [comment]
Maybe you have not visited the the root (`/`) route at first, but directly any page?

This was about database schema migrations and they are [executed only when](https://github.com/grocy/grocy#database-migrations) "visiting" `/`...
