### ISSUE TITLE
Wrong Timestamp in Stock Journal

### ISSUE THREAD

**Issue by JoschaMiddendorf** [grocy/grocy#301]
When taking an item from stock, regardless if that's done in stock overview or consume, the stored timestamp in journal is wrong (2h earlier).

**Comment by berrnd** [comment]
It uses the local server time - maybe check the configured timezone in your `php.ini`...

(Would assume your server uses the UTC timezone, as MESZ is UTC +2 ...)

**Comment by JoschaMiddendorf** [comment]
I'm using the linuxserver/grocy Docker container which the correct timezone is passed to. 
Thu Jul  4 11:15:15 CEST 2019 is the current date inside the container. 
php-local.ini has "date.timezone = Europe/Berlin" in it which is also correct.
Where can I find php.ini?

**Comment by berrnd** [comment]
Normally the `php.ini` can be found in `/etc/php/7.2/fpm` (when using PHP-FPM 7.2 on Linux/Debian), but I don't know how it works in Docker containers...

Stock journal shows the `row_created_timestamp` of the `stock_log` row, which is filled by SQLite, SQLite uses the operating system timezone, AFAIK this cannot be configured anywhere...

Maybe the better approach is to store everything in UTC, and only convert it to local time when displaying it - but would be a bigger change, currently everywhere I assume all timestamps are in local time (and therefore PHP/SQLite/Browser timezones need to be the same)...

References #214.

**Comment by JoschaMiddendorf** [comment]
I found the php.ini. Therein date.timezone is empty, but that should be replaced by the value from php-local.ini.

**Comment by JoschaMiddendorf** [comment]
Docker works similar to a VM in that case. It has its own system timezone.

**Comment by JoschaMiddendorf** [comment]
That looks wired I added an item and immediately after that canceled the addition. The screenshot of the journal speaks for its own.
![Bildschirmfoto 2019-07-05 um 02 52 24](https://user-images.githubusercontent.com/19818109/60691500-5d775a80-9ed0-11e9-8e91-7a679696d3e6.png)

**Comment by JoschaMiddendorf** [comment]
It looks like `undone_timestamp` is working fine `row_created_timestamp` does not. Could you just change the DatabaseStructure for `row_created_timestamp` to solve that?

![Bildschirmfoto 2019-07-05 um 03 15 00](https://user-images.githubusercontent.com/19818109/60691917-53a32680-9ed3-11e9-9bcc-b2841b19e5fc.png)

**Comment by berrnd** [comment]
What I said above
> currently everywhere I assume all timestamps are in local time (and therefore PHP/SQLite/Browser timezones need to be the same)...

`row_created_timestamp` is populated by SQLite itself (default column value), SQLite uses the operating system local time - so I assume the timezone of your machine is not "Europe/Berlin"...

I know that storing everything in UTC or including the timezone part would be the better approach, but currently it's like it is...

**Comment by JoschaMiddendorf** [comment]
I tested that again in the command line, directly with SQLite.
The timezone of my machine is "Europe/Berlin"!

> root@62c7edcf84cf:/# echo $TZ
Europe/Berlin

>root@62c7edcf84cf:/# php -i | grep timezone
Default timezone => Europe/Berlin
date.timezone => Europe/Berlin => Europe/Berlin

>root@62c7edcf84cf:/# date
Sat Jul  6 01:01:34 CEST 2019

>root@62c7edcf84cf:/# /usr/bin/sqlite3
SQLite version 3.28.0 2019-04-16 19:49:53
Enter ".help" for usage hints.
Connected to a transient in-memory database.
Use ".open FILENAME" to reopen on a persistent database.
sqlite> CREATE TABLE IF NOT EXISTS datetime_text(d1 text, d2 text);
sqlite> INSERT INTO datetime_text(d1, d2) VALUES ( datetime('now'), datetime('now', 'localtime'));
sqlite> SELECT d1, typeof(d1), d2, typeof(d2) FROM datetime_text;
2019-07-05 23:02:03|text|2019-07-06 01:02:03|text

Isn't that exactly what Grocy is doing?

**Comment by berrnd** [comment]
Yes, `datetime('now', 'localtime')` is what's the default value for the `row_created_timestamp` columns...

I can't say why that's wrong...
PHP is not using the `sqlite3` executable, but its own PDO SQLite extension - maybe that's a difference...
However, it works on my machines and I have not cared about anything else that the PHP and machine timezone setting...

**Comment by berrnd** [comment]
Closing this for now, I will change everything to use UTC in the database and only convert to local time for displaying purposes, this will be tracked in #214.
