### ISSUE TITLE
Chores: weekly chore remains overdue

### ISSUE THREAD

**Issue by isabellaalstrom** [grocy/grocy#304]
I created two chores today to be made weekly on sundays. I then proceeded to track execution of one of those tasks a while later, but they remained to show as overdue.
Let me know if you need more information. I run Grocy through the Hass.io add-on.

![image](https://user-images.githubusercontent.com/22006797/60770769-f1b70c80-a0de-11e9-9b0e-7921365fcc5a.png)

**Comment by berrnd** [comment]
Thanks, I could reproduce it - is already fixed and a new version will be ready in a couple of minutes... :)

**Comment by isabellaalstrom** [comment]
Amazing, thanks!
