### ISSUE TITLE
LDAP authentication

### ISSUE THREAD

**Issue by histal89** [grocy/grocy#305]
Would be nice to authenticate with ldap users.

**Comment by berrnd** [comment]
Already requested in #207, but I let this open as it is specific about LDAP...

**Comment by berrnd** [comment]
This is now done. 🙂
(Have tested it with a Microsoft Windows Domain / Active Directory.)

Changelog excerpt:
> ### New feature: External authentication support
> - New `config.php` setting `AUTH_CLASS` to change the used authentication provider
> - Via LDAP
>   - New `config.php` settings `LDAP_DOMAIN`, `LDAP_ADDRESS` and `LDAP_BASE_DN`
>   - If you set `AUTH_CLASS` to `Grocy\Middleware\LdapAuthMiddleware`, users will be authenticated against your directory (and will also be created (in grocy), if not already present)
