### ISSUE TITLE
Feature Request: Shopping List API

### ISSUE THREAD

**Issue by oli-f** [grocy/grocy#311]
Hey,

it would be very handy to be able to access the shopping list via an API endpoint. While it it possible to add missing products and clear the shopping list, there is currently no API endpoint for retrieving the shopping list.

Best regards,
oli-f

**Comment by berrnd** [comment]
That's already there, for all objects ... see the [Generic entity interactions section on `/api`](https://demo-en.grocy.info/api#/Generic%20entity%20interactions).

Example GET to retrieve all lists:
https://demo-en.grocy.info/api/objects/shopping_lists

And to get the actual items:
https://demo-en.grocy.info/api/objects/shopping_list
