### ISSUE TITLE
Feature Request: Chore Schedule Biweekly

### ISSUE THREAD

**Issue by isabellaalstrom** [grocy/grocy#312]
As title says, would be nice to be able to have period type biweekly. Am using dynamic 14 days as workaround right now, but that doesn't work well with everything.

**Comment by JoschaMiddendorf** [comment]
@bernd You could come by that by a nice generic approach. 
Aust ad a period field to the weekly monthly or daily schedule, to make intervals like every 1 or 2 or 5 weeks on a Monday or every 3 months on the 1st possible.

**Comment by berrnd** [comment]
> Just ad a period selection field to the weekly and monthly schedule, to make intervals like every 1 or 2 or 5 weeks on a Monday or every 3 months on the 1st possible.

Thanks for the suggestion, will do that. :)

**Comment by berrnd** [comment]
This is now done, a new option "period interval" per chore, possible for the daily, weekly and monthly period type, defaults to 1.

![grafik](https://user-images.githubusercontent.com/2161815/66196173-5ced8c00-e698-11e9-9add-33ebc1b67800.png)
