### ISSUE TITLE
Feature Request: access userfield value thru API

### ISSUE THREAD

**Issue by oncleben31** [grocy/grocy#316]
We can add userfield to many objects, but the value set in the UI is not exposed in the API.

Having access thru API could improve the number of usages with API.

**Comment by berrnd** [comment]
That's already possible, see the `/usefields` routes in the ["Generic entity interaction" section on `/api`](https://demo-prerelease.grocy.info/api#/Generic%20entity%20interactions).

Example `GET` to get the userfields of product with id `10`:
https://demo-prerelease.grocy.info/api/userfields/products/10

Execute a `PUT` request to the same route with the same body to edit the userfields of the product...
