### ISSUE TITLE
Feature Request: Move from Storage A to Storage B

### ISSUE THREAD

**Issue by hauweg** [grocy/grocy#319]
Hello, since I'm using the program more and more, I managed to mirror almost all our processes in grocy. That's fantastic!

But one of the features missing is: booking items from one storage to another.

Since we have several storages, it would be great, to move items from one storage to another. in the stock i would love to see the total number, but also split into the several storages. 

Also i would love to filter the stock by storage.

Also in the inventory i need than to assign the number of items to a specific storage. 

Is there already an existing feature, that I am just not realizing? Or a goof workaround for it?

**Comment by berrnd** [comment]
Duplicate of #191 

> Also i would love to filter the stock by storage.

Already possible on the stock overview page, see the filters above the table.
