### ISSUE TITLE
Product overview > context menu > add to shopping list

### ISSUE THREAD

**Issue by hannahswain** [grocy/grocy#321]
It would be awesome if we could have the option to add a product directly to the shopping list:

![Context](https://cld.wthms.co/n2z8ar+)
Full size: https://cld.wthms.co/n2z8ar

This would save remembering that you'd like another of product X and then going to the shopping list and manually adding it. This is for when a product isn't enough of a staple that it has a minimum stock amount set.

**Comment by berrnd** [comment]
I merged this into https://github.com/grocy/grocy/issues/327#issuecomment-516907088.

**Comment by berrnd** [comment]
This is now possible - see https://github.com/grocy/grocy/issues/327#issuecomment-533517797.
