### ISSUE TITLE
Product overview context menu > options for which options are shown?

### ISSUE THREAD

**Issue by hannahswain** [grocy/grocy#322]
Given that there have been a few different requests for options to be added to this dropdown/context menu, it might be nice to have an options menu to choose which options are available. For example, not everyone uses the shopping list, so the dropdown menu option to add a product to the shopping list (e.g. #321 ) isn't useful for all. 

This is more of an idea/suggestion than an actual wish - it's nice to be able to track these things. :)

**Comment by berrnd** [comment]
Closing this - those context menu items are partly shown/hidden by [`FEATURE_FLAG`s](https://github.com/grocy/grocy#disable-certain-features), like any other UI element.

Each element can individually be hidden by using [custom JS](https://github.com/grocy/grocy#adding-your-own-css-or-js-without-to-have-to-modify-the-application-itself) and there is also `FEATURE_FLAG_SHOPPINGLIST` to disable/hide everything related to that.
