### ISSUE TITLE
Table contents not visible with culture set to "nl"

### ISSUE THREAD

**Issue by syphernl** [grocy/grocy#323]
I'm unable to view my Grocy data (users, API keys, locations etc). They are stored in the database just fine, but for some reason they never show up in the frontend. Recipes for instance show up just fine.

Turns out, when I changed the `CULTURE` back to `en` (set it to `nl` as I'm Dutch) it works again. 

I'm running the latest version (2.4.4)

**Comment by berrnd** [comment]
I was able to reproduce it and fixed it - the localization string `datatables_localization` of the file `component_translations.po` was wrong, needs to be a JSON string ([source](https://datatables.net/plug-ins/i18n/Dutch)).

If you want to have it fixed now, drop [this file](https://raw.githubusercontent.com/grocy/grocy/master/localization/nl/component_translations.po) into `localizations/nl`.

**Comment by syphernl** [comment]
Thanks for the quick fix @berrnd! I can confirm it works now with the `nl` locale :)

**Comment by syphernl** [comment]
@berrnd After updating to the latest version this problem appears to have resurfaced.

**Comment by berrnd** [comment]
If you overwrote the manual changed file `localizations/nl/component_translations.po` then yes - there was no release since I fixed this in https://github.com/grocy/grocy/commit/3dbce7547fb2b0c9b5acbed1926d98b5f61d10b0...

https://github.com/grocy/grocy/compare/v2.4.4...master

**Comment by syphernl** [comment]
Ah darn, I assumed the `update.sh` would pull in the latest master (saw some fixes / changed I wanted) :)

**Comment by tjorim** [comment]
@berrnd Planning on a new release soon? Maybe just a bugfix release because this is pretty annoying (and there's no easy way to fix in the Hass.io add-on).

**Comment by berrnd** [comment]
Is there no option to replace the mentioned file above?

I will have more time to work on grocy at the end of september, so thought about the next release around that time then...

**Comment by tjorim** [comment]
We try not to let users fiddle with the Docker containers themselves.
However I implemented a temporary fix that should do the trick for now.
