### ISSUE TITLE
Feature Request: Recipe categories/labels

### ISSUE THREAD

**Issue by syphernl** [grocy/grocy#324]
It would be nice if recipes could be put in categories (e.g. breakfast/lunch/dinner/snack) which makes it easier to search for a particular recipe.

Something like labels should also work. Recipes should be able to be in multiple categories (e.g. dinner + lowcarb, dinner + vegetarian, lunch + dinner)

**Comment by berrnd** [comment]
This is generally already possible by using Userfields, see #176 and I created an example for recipe categories on the [pre-release demo](https://demo-prerelease.grocy.info/recipes).

However, we don't have a Userfield type where multiple predefined values can be then assigned to the recipe in this case - I created issue #325 to track adding such a Userfield type.

**Comment by syphernl** [comment]
Ah clear! Thanks.

**Comment by berrnd** [comment]
A new Userfield type "Select list" is now available, see #325.

> - New userfield type "Select list" for a list of predefined values where a single or also multiple values can then be selected on the entity object
