### ISSUE TITLE
Feature request: Improve stock overview product actions

### ISSUE THREAD

**Issue by Jayphen** [grocy/grocy#327]
From the dashboard it is possible to consume 1 unit quickly, which could be very handy:

![image](https://user-images.githubusercontent.com/329184/61590593-fdfd9800-abbb-11e9-9ca2-4494e6a14144.png)

But for the case where the item is measured in grams/mls (e.g. flour here), consuming 1g/1ml is rarely what is desired. It would be nice to be able to set a default consumption amount, or to be able to vary the amount from the dashboard.

**Comment by kingo55** [comment]
I can see the value of providing default amounts for some products. But when I think of default usage amounts in grocy, I think of recipes. E.g. Making pancakes - 500ml of milk, 150g of flour, 75g of oats - hit "Consume ingredients for recipe" and all the defaults are used for that recipe. And when I bake bread I consume different amounts of ingredients.

I feel there has to be a more elegant way to represent product actions on this page to accommodate users' needs. The stock overview page is like the grocy homepage, but actions are relatively limited here. 

Bit of a bigger problem, but I think we need to improve product-specific navigation on this page. Maybe that's a default consumption amount, or a configurable consumption amount, or maybe other things - like shopping list additions, purchases or filter for recipes including this item?

**Comment by Jayphen** [comment]
Yes, it would also be nice to have default 'configurations' that could trigger a specified amount. But I feel that is a step beyond what I have suggested here.

**Comment by berrnd** [comment]
> I feel there has to be a more elegant way to represent product actions on this page to accommodate users' needs. The stock overview page is like the grocy homepage, but actions are relatively limited here.

I totally agree, so let's rename this issue and collect all related improvements on this here:
- Make "Consume 1" configurable per product (default amount per product)
  - Maybe multiple amounts per product?
- Add "Add product to shopping list" (merging #321 into this)
  - Maybe ask for the amount in a popup?
- For the same default amount(s) as above for consuming, add "Purchase x"
- Add "Filter for recipes including this product" which jumps to the recipes page filtered for recipes which contain the selected product

**Comment by kingo55** [comment]
Sorry for hijacking your issue @Jayphen ... I still see the value in a default consumption amount.

As for the actions bar, the lazy way would be to overload it like so:

![Screenshot_20190801_183707](https://user-images.githubusercontent.com/2361388/62278459-781b0000-b48b-11e9-8810-64c3416cc19f.png)

We'd go from the current state of actions:

 - Consume 1
 - Consume All
 - Mark open 1
 - Hamburger menu:
    - Show product journal
    - Edit product
    - Show product overview

To the following actions:

 - Purchase
    - Add to shopping list
    - Purchase item
 - Consume
    - Default amount (or 1 unit)
    - All stock
    - Open default amount (or 1 unit)
 - Recipes for product
 - Edit product

Doing so, would demote both "Product journal" and an explicit "Product overview" link from the actions bar. It also makes consumption actions less convenient. There has to be other ways to make actions more accessible from the stock overview page. E.g.:

 - Mouse-over on the row reveals more options
 - Add more options to product overview

What do others think?

**Comment by berrnd** [comment]
I've changed now the context/more menu on the stock overview page like that:

![grafik](https://user-images.githubusercontent.com/2161815/65323045-a8883c00-dba8-11e9-8b7e-65e04a47034f.png)

The menu entries then open the purchase/consume/etc. pages in a popup/dialog prefilled with the current product.

Hope this fits for what you thought about here, feel free to open new issues if you have further ideas on this.

Can be tested on pre-release demo (next release planned for this Sunday): https://demo-prerelease.grocy.info

**Comment by hannahswain** [comment]
What a cool solution! :D
