### ISSUE TITLE
Feature Request: url parameter API key

### ISSUE THREAD

**Issue by taylorcoffelt** [grocy/grocy#329]
If the API key was available to be provided via the URL as a GET parameter (e.g. ?GROCY-API-KEY=XXXXX) instead of just the headers, then a service such as IFTTT could be used to set up a kind of integration with Google Assistant ("Hey Google, Mark 1 packet of instant potatoes used")

IFTTT specifically does not allow custom headers in their webhooks.

**Comment by berrnd** [comment]
I've added this now - as you propsed it: Same query parameter name as the header, so for example:

https://demo-prerelease.grocy.info/api/objects/products?GROCY-API-KEY=xyzxyzxyzxyzxyzxyzxyzxyz

If the header and the query parameter is supplied at the same time, the header takes precedence.
