### ISSUE TITLE
API Stock by barcode

### ISSUE THREAD

**Issue by Phoara** [grocy/grocy#330]
I'm trying to add products (do a purchase) via the Shortcut App in iOS. However, I've got two problems with the API so far:

1) How do I communicate the API-Key with Grocy via the URL?

2) Is there a way to add stock not via product ID but by barcode (POST)?

**Comment by berrnd** [comment]
Just browse the [integrated Swagger UI instance on /api](https://demo-en.grocy.info/api) - there are interactive examples for all endpoints...

1. You need to provide the API key via a custom HTTP header `GROCY-API-KEY`.

2. No. Internal objects are always referenced by the internal ids everywhere, but [there is an endpoint to lookup products by barcode](https://demo-en.grocy.info/api#/Stock/get_stock_products_by_barcode__barcode_).

**Comment by JoschaMiddendorf** [comment]
Very interesting. Would you mind sharing your iOS shortcuts approach?

**Comment by Phoara** [comment]
@berrnd: 
1. Via the GET-command, right? 
2. When I add something in "purchase", I have the option to enter a barcode or a product name. That's the easiest way to add a good. I would like to do the same via the Shortcuts app. I don't think it's very practical to have to look up all the product IDs for all the goods in my bags, right? What you are recommending is a work-around of letting the app scan the barcode, look of the matching ID, copy and insert it to add the product to the stock!?

What I basically need to achieve is visiting /purchase via the API (otherwise Shortcuts will ask for the login credentials all the time) and fill in the input fields by

1. scanning and inserting the barcode
2. asking for the best-before-date  -> type or voice input via Siri
3. asking for the quantity -> type or voice input via Siri

with POST and the input fields "product_id", "best_before_date" and "amount". Is there no way to mimic this input with the automatic transfer of barcode to product_id?

@JoschaMiddendorf:

I'm no expert (obviously) and I haven't come very far. If I can manage to make it work, I will share it of course.

**Comment by berrnd** [comment]
> What you are recommending is a work-around of letting the app scan the barcode, look of the matching ID, copy and insert it to add the product to the stock!?

I would not call this a workaround - most of the time APIs work like this, I would say - and that's basically also how the grocy UI does that job as the API is heavily used by grocy itself...

But feel to suggest/implement any API endpoint you need in separate issues.

**Comment by berrnd** [comment]
@Phoara 
Providing the API key via a query parameter is now possible, see #329.

Closing this here for now, feel free to reopen it or create a separate issue if you need anything else.
