### ISSUE TITLE
Feature request: API add stocks via barcode

### ISSUE THREAD

**Issue by Phoara** [grocy/grocy#331]
POST /stock/products/by-barcode/{barcode}/add -> Adds the given amount of the given product to stock.

I would like to ask for an implementation of adding stock via barcode, internally handling the conversion of barcode -> product_id to make it easier to implement adding stock in apps/iOS Shortcuts.

**Comment by berrnd** [comment]
This is now done - to make it (more) complete, I also added the corresponding endpoint to remove a product from stock by its barcode. :)

> - New endpoint `/stock/products/by-barcode/{barcode}/add` to add a product to stock by its barcode
>  - New endpoint `/stock/products/by-barcode/{barcode}/consume` to remove a product to stock by its barcode

See the API doc of the pre-release demo: https://demo-prerelease.grocy.info/api

**Comment by berrnd** [comment]
Of course `/stock/products/by-barcode/{barcode}/inventory` and `/stock/products/by-barcode/{barcode}/open` were also missing - which are now added as well... :)
