### ISSUE TITLE
Multiple locations/expiration dates

### ISSUE THREAD

**Issue by Spankythemusical** [grocy/grocy#332]
Is there a way to enter items with multiple locations or expiration dates?  Say I have 3 bottles of Brand X hot sauce, all with different expiration dates.  2 are in the pantry, and 1 is in the fridge.  Right now I can only see where I can enter either 3 bottles with the same date and same location or 1 bottle with the correct info and the other bottles aren't entered.  Or am I missing something quite simplistic?

**Comment by berrnd** [comment]
For multiple expiration dates: You can assign a best before date for each purchase, so if you have the same product with 3 different dates, you need to do this by posting it 3 times. But on the stock overview page and on the product card you only see the most next expiration date. It's already tracked in https://github.com/grocy/grocy/issues/191#issuecomment-473299770 that there should be a way to see all stock entries per product.

For multiple locations: Also already tracked in https://github.com/grocy/grocy/issues/191#issuecomment-473299770.

**Comment by Spankythemusical** [comment]
Thank you for clarifying the expiration date issue.  I was doing the inventory and that scenario occurred.  I was not aware that the items with the longest expiration date were still entered into the database.  I did see #191, however I created my issue as my question was concerning the same product in multiple locations simultaneously.  Thank you for your quick response on this.

**Comment by berrnd** [comment]
You're welcome. :)

So I close this for now, please follow #191 when you want to be notified when this is ready.
