### ISSUE TITLE
Config option to remove week of the year

### ISSUE THREAD

**Issue by SunX99** [grocy/grocy#333]
Apologies if this is already in here.
Request if the config.php and settingoverrides function could include removal of the week of the year from the calendar view so columns shown starts with chosen start day (ex. Sunday). Both in the Calendar function and the mini calendar shown in other modules.

**Comment by berrnd** [comment]
This is now done. :)

> - Added a new `config.php` setting `CALENDAR_SHOW_WEEK_OF_YEAR` to configure if calendars should show week numbers (defaults to `true`)
