### ISSUE TITLE
Feature Request:  OpenHAB binding or WebView

### ISSUE THREAD

**Issue by bwosborne2** [grocy/grocy#336]
A binding or WebView for OpenHAB would be very useful to users.

**Comment by berrnd** [comment]
Maybe better request this in the OpenHAB Community?

**Comment by gersilex** [comment]
Posted a [tutorial in the openHAB Community](https://community.openhab.org/t/shopping-grocery-list-ideas/79111/7?u=gersilex) in the [relevant thread](https://community.openhab.org/t/shopping-grocery-list-ideas/79111?u=gersilex)
