### ISSUE TITLE
Search method from API

### ISSUE THREAD

**Issue by gmandres** [grocy/grocy#337]
I cannot find a search method in the API.  It would be nice to be able to search an entity by entity name.  So if I wanted to search product by product name it would return a list of products that matched.

**Comment by berrnd** [comment]
There is now a [new API endpoint](https://demo-prerelease.grocy.info/api#/Generic%20entity%20interactions/get_objects__entity__search__searchString_) for this.

Example request to get all products where the name contains "gu":
https://demo-prerelease.grocy.info/api/objects/products/search/gu
