### ISSUE TITLE
Feature Request: Printable Inventory / Reports

### ISSUE THREAD

**Issue by SummittDweller** [grocy/grocy#341]
Great tool here, but not everyone in my household will use it.  8^(  So, what I really need is the ability to print an inventory report paginated "by location".  That way, on a weekly or monthly basis, I can print an inventory sheet for a location and hang it there for others to use when removing items.  For example, I print an inventory for the "fridge", pin it to the fridge along with a pencil, then when my wife or kids remove or "consume" an item they can cross it off the sheet or decrement the quantity.  That way I can pull the sheets each week (or month) with some hope of updating Grocy to maintain reasonable accuracy.  The alternative is to have an iPad at each location (not going to happen) and expect the family to use them regularly (definitely not happening).

**Comment by BlizzWave** [comment]
I second this. I do a inventory check every month, but I drag my laptop around and do necessary adjustment in the stock in Grocy.

**Comment by skevas** [comment]
Same here. That would be a great feature.

**Comment by SummittDweller** [comment]
Just FYI... last evening I managed to get a local `grocy` stack running with [Docksal](https://docksal.io).  Since I am a developer with quite a bit of PHP experience, MAYBE I can work something like this into the code and share it in a PR?

**Comment by berrnd** [comment]
Sure, any contributions are very welcome. :)

...but I'm already fiddling together a first draft about this ... will show you in a couple of minutes ... feel free to improve it then... :)

**Comment by SummittDweller** [comment]
Absolutely, I'd love to kick the tires and take it for a spin.  Thanks.

**Comment by berrnd** [comment]
So here is a first draft about this: https://demo-prerelease.grocy.info/locationcontentsheet

Per location a table with the current amounts and a third column to fill in what was used ... should print a new page per location ... but does not work on Firefox here currently ... found not out why right now...

Feel free to improve it. :)

**Comment by BlizzWave** [comment]
Cool!

My improvement thoughts, though minor.

- Grocy logo on first page or all
- The third column needs a name "Actual Amount"

**Comment by skevas** [comment]
* Print works in Firefox 67.0.4 for Linux. 
* Third column name might be "Consumed Amount" -> consumers can use the column as tally sheet

**Comment by SummittDweller** [comment]
Nice!  I would stick with "Amount" or "Actual Amount" though.  "Consumed Amount" suggests they will be incrementing the value, and I think that's counter-intuitive?  It also doesn't tell me if the item needs re-stocking.  Other thing I would advocate is the date printed at the top of each page. 

In my experience the "Print" button in Firefox (my browser of choice) just prints one page, it's not "by location".  Chrome worked PERFECTLY though.

**Comment by SummittDweller** [comment]
My bad...  "Consumed Amount" does make sense as an **additional** column, and I like the tally marks idea too!

**Comment by SummittDweller** [comment]
I see you're using `page-break-after` in the media CSS to force the page breaks, and that should work in Firefox, but doesn't appear to.  I see a note attached to that code indicating it has been replaced with `break-after`.  Maybe give that a go and see if it helps?  I've got to run for a volunteer gig at the moment, but might take a shot at this later when I return home.

**Comment by SummittDweller** [comment]
OK, after some trial and error I have a grocy-docker version of `master` now up and running.  What I could really use is an export of your pre-release `/data` or database so that I can quickly build an identical set of items to test with.

**Comment by SummittDweller** [comment]
Confirmed that `break-after` doesn't behave any better in Firefox.  

So, what about providing one `Print` button for each `location`?  I'm going to have quite a few locations and probably won't want to print them all each time.  Couple this with ability to print a single <div>, maybe like mentioned in https://stackoverflow.com/a/28447739?

**Comment by berrnd** [comment]
When you create a empty file `data/demo.txt` it will populate all the demo data (and also disable authentication) like [mentioned in README](https://github.com/grocy/grocy#demo-mode)...

**Comment by berrnd** [comment]
I've finished this:

- grocy logo & timestamp of printing on top of each page
- All locations can be printed or also each single one separately
- Linked by a new button in the header of the stock overview page
- Larger third column to fill in the consumed amount / other notes

=> https://demo-prerelease.grocy.info/locationcontentsheet

If you have further ideas on this, just drop them here. :)

`page-break-after` problem/workaround was about this:
https://github.com/grocy/grocy/blob/7004cf4400d51bc222d50ae9d73008520a20d2d3/views/locationcontentsheet.blade.php#L18-L25
