### ISSUE TITLE
Feature request: hyperlink URLs to manuals

### ISSUE THREAD

**Issue by toretorden** [grocy/grocy#342]
Hi,

First off - thanks for making grocy!

To the point. Before grocy, I already had a system for keeping tabs on manuals. Me and my wife share folders on our google drive and, among other things, store manuals for our equip there. I would prefer to keep it that way in the future and to not have to upload those files to grocy.

Hence, I suggest that EQUIPMENT should have a URL link field where I could input URL links to manuals that I keep on drive. As an approximate solution, I have created a userfield for this purpose, but the URL is only shown in plain text and not as a hyperlink.

Hence, my feature request is to either build this into EQUIPMENT as default (preferred) or to make it possible to create a userfield which recognizes URLs and turns them into hyperlinks.

Cheers!

**Comment by berrnd** [comment]
To have a Userfield type "Link" is already tracked in #258.

But I leave this open, maybe it's also a good idea to be able to have "external" manuals for Equipment...

**Comment by toretorden** [comment]
Thank you and sorry for duplicating, in part, an already open issue. 

To have this feature better integrated into equipment would be _much_ preferable as showing my userfield with google drive URLs as a column seriously clutters up my equipment page.

**Comment by berrnd** [comment]
There is now a Userfield type which renders as a clickable link - see #258.

I think I don't implement "external manuals" for now, as it would depend on the server if they could be rendered embedded (like upload PDFs as of now) and also when you need them maybe they're then gone ... or other problems...
