### ISSUE TITLE
Feature request: allow multiple purchase units

### ISSUE THREAD

**Issue by tjorim** [grocy/grocy#345]
For example cans of Coke zero: we can purchase them in packs of 15, packs of 6 or just per can.
Right now I need to put the purchase unit to 1 can and multiply it myself depending on which package size I bought (or even worse, set purchase unit to 15 and calculate the 'partial units').
A dropdown to choose which unit would come in very handy.

**Comment by berrnd** [comment]
I think this is already requested in #177 - so closing this as duplicate for now.
