### ISSUE TITLE
Feature Request: API managing Shopping List

### ISSUE THREAD

**Issue by JulienSambre** [grocy/grocy#348]
Hi!

First of all, thanks for this great piece of software : i was asking myself if it would fits my needs and it fits quiet perfectly!

I am working on an integration with a self-hosted AI, Kalliope. For that, I would need to work with shopping list and i don't find in the API (https://demo-en.grocy.info/api#/) something to manage shopping list (get all shopping lists with their products, add or delete a shopping list or a product of a shopping list, etc.).

Am I missing something or is it possible in some way? I found for example the list of shopping list objects from "/objects/{entity}" but don't see how to get products in the shopping list. I think that it would nice to add these possibilities, like you started to do under "/stock/shoppinglist"

**Comment by berrnd** [comment]
Great that grocy works for you, looking forward to the AI integration... :)

As you already found out for shopping lists, "direct" access for all objects is possible via the `/objects/{entity}` routes.

So to get all shopping list items:
`GET https://demo-en.grocy.info/api/objects/shopping_list`

(Maybe the naming of the entity/database table is a bit odd - not long ago there were no multiple shopping lists, that's why...)

**Comment by JulienSambre** [comment]
I and my girlfriend are very curious to use the AI for stock management, asking for a meal to prepare, etc. And use the Grocy GUI on smartphone when shopping :).

Would it be possible to querry the API in order to simulate what the API could nicely do like with products? Like to list what product is in a shopping list, add or remove a product from the shopping list. I suppose it is possible via the API, but didnt't found how to manage it.

**Comment by berrnd** [comment]
It's currently not possible with one single API request...

https://demo-en.grocy.info/api/objects/shopping_list returns all shopping list items from all shopping lists.

Match the `shopping_list_id`s of the items against https://demo-en.grocy.info/api/objects/shopping_lists to get the shopping list names.

Match the `product_id`s of the items against https://demo-en.grocy.info/api/objects/products to get the products.

Or use https://demo-en.grocy.info/api/stock/products/1 (`/stock/products/{productId}`) to get more information about a single product (like the next expiring date, currrent stock amount, and so on).

Execute a `DELETE` request against `/objects/shopping_list/{objectId}` to delete a single shopping list item.

Hope this helps to get started... :)

**Comment by JulienSambre** [comment]
I think it will work. Thank you very much for the very quick answers ;).
