### ISSUE TITLE
Recipe display shows both amount and variable amount

### ISSUE THREAD

**Issue by cyberlink1** [grocy/grocy#350]
This is a white rice recipe used to test the system. When I enter the recipe I used both the amount in lb (for inventory) and the Variable Amount for the recipe (cups) 

![save-recipe](https://user-images.githubusercontent.com/12261936/64077626-cb08f280-cc97-11e9-8dd6-90f17c88f249.png)

The recipe displays "2 cups lbs" in the amount

![rice-recipe](https://user-images.githubusercontent.com/12261936/64077625-c80e0200-cc97-11e9-8331-6c988557a742.png)

**Comment by berrnd** [comment]
This is intentional. It's only about a different amount, not about a different quantity unit (as also the hint there implies), most of the time something like "1 - 2".

Was introduced by #181.

**Comment by cyberlink1** [comment]
1) Not sure what "hint" you are talking about. I dont get a popup hint explaining it on the site itself.

2) Then it needs to be clarified.
     Maybe something like "2 cups of rice, 25 lb in inventory. <check>"

**Comment by BlizzWave** [comment]
The hint he's talking about is this. 

> Variable amount  When this is not empty, it will be shown instead of the amount entered above while the amount there will still be used for stock fulfillment checking

Please have a look at issue #181

**Comment by cyberlink1** [comment]
> The hint he's talking about is this.
> 
> > Variable amount  When this is not empty, it will be shown instead of the amount entered above while the amount there will still be used for stock fulfillment checking
> 
> Please have a look at issue #181

The Variable amount is confusing. This is not a conversion meaning the inventory amount is in lbs but Im using cups? From reading the thread it is just for recipes that have an approximation of the amount like bread where it could be 2-2.5 lb of flour where stock is in lbs. Not for changing the measurement from .80 lb of rice to 2 cups of rice?

**Comment by BlizzWave** [comment]
> The Variable amount is confusing. This is not a conversion meaning the inventory amount is in lbs but Im using cups? From reading the thread it is just for recipes that have an approximation of the amount like bread where it could be 2-2.5 lb of flour where stock is in lbs. Not for changing the measurement from .80 lb of rice to 2 cups of rice?

Yes, thats correct.
