### ISSUE TITLE
Allow decimal numbers for "Factor purchase to stock quantity unit" when "Allow partial units in stock" is enabled

### ISSUE THREAD

**Issue by cyberlink1** [grocy/grocy#351]
I know my math can be bad sometimes but I am sure that 2.5 is more than 2. lol

![factor-off](https://user-images.githubusercontent.com/12261936/64078338-28ed0880-cc9f-11e9-8793-a3a1976c5987.png)

**Comment by berrnd** [comment]
Currently this can only be an integral number.
But I agree that when "Allow partial units in stock" is enabled, it should also be possible to use a decimal number here.

...and it uses browser form data validation capabilities, so also checks the format - but yes, the validation error message could be more precise then...

**Comment by berrnd** [comment]
This is now done.

...and the validation message looks like that:

![grafik](https://user-images.githubusercontent.com/2161815/65066926-a6926300-d985-11e9-802a-2cdded45e50e.png)
