### ISSUE TITLE
Feature Request: Running low with open products

### ISSUE THREAD

**Issue by BlizzWave** [grocy/grocy#353]
I have a lot of things that has min. stock amount of 1 and I often use the "mark as open" on products.
But this will not flag the product as low in the stock and it will not show up in the shopping list.
My point is to never run out of products when I need them. 

Maybe a extra button in the shopping list page with "Add opened products that are on minimum stock"

**Comment by berrnd** [comment]
Sounds logic to me - to be honest, I personally don't track opened products myself...

So I changed the default behavior, opened products now count by default against the the minimum stock amount. The old behavior can be restored by a new `config.php` setting:

>  New `config.php` setting `FEATURE_SETTING_STOCK_COUNT_OPENED_PRODUCTS_AGAINST_MINIMUM_STOCK_AMOUNT` to configure if opened products should be considered for minimum stock amounts (defaults to `true`, so opened products will now be considered missing by default - please change this setting if you want the old behaviour)
