### ISSUE TITLE
Mealplan fails to load when recipe is deleted

### ISSUE THREAD

**Issue by Jeltel** [grocy/grocy#361]
Relating to another bug I wanted to remove a recipe, so I could add it again.
It was, however,  added to the mealplan. After deleting the item, the week where the recipe was added to the mealplan failed to load. Also other weeks didn't load anymore.

I've fixed this via the API and added a recipe with the same id again (long live the API!), so I could continue with the meal plan and shopping list.

**So to reproduce:**

- Add a recipe to the meal plan
- Delete the recipe
- Reload the meal plan in the week where the recipe was previously edit
- See that it fails to load.

**Steps to repair via the API**

- Add a new recipe with the same ID as the deleted recipe in the API.

**Comment by berrnd** [comment]
Thanks for finding that. :)

I fixed it in two ways:
- A non-existant recipe does not break meal plan loading anymore
- When a recipe is deleted, it is automatically removed from the meal plan (all weeks)
