### ISSUE TITLE
Barcode recognition is hit or miss

### ISSUE THREAD

**Issue by pglaz** [grocy/grocy#362]
Hello! I've discovered grocy only recently but love it already. I've noticed you're about to release an update where device camera can be used as a barcode scanner. That's awesome!

I gave it a try using the publicly available pre-release version on iPhone Xs with iOS 13.0 installed on Safari but it seems that the barcode recognition is hit or miss, with miss happening more often. Sometimes I don't even move my camera in any way and if I hit the scan button, it gives me a different result.

I guess it might be due to the engine you're using but I've noticed that sometimes it gives me two rectangles, as if it's trying to scan two barcodes in a single image at once. Maybe disabling this would improve scanning accuracy?

I'm attaching [a video](https://youtu.be/fKEu1Yd3_48) of my scanning attempts and the still picture of the barcode I was trying to scan. Am I right that the expected result here is that the text box displays the same number that I see under the barcode?

Thanks!

![IMG_7517](https://user-images.githubusercontent.com/4352382/65375485-cd061600-dc85-11e9-9d32-4e633a8e670c.jpg)

**Comment by berrnd** [comment]
Thanks for trying that! :)

I'm completely not doing the barcode recognition myself, it's entierely made possible by [QuaggaJS ](https://serratus.github.io/quaggaJS) and I'm more or less using just the default configuration...

In my few tests it worked pretty well, but I will do some tests with the barcode you provided later.

I think normally the number printed below the barcode is the same as the content of the barcode...

**Comment by berrnd** [comment]
I've added a fun little barcode scanner testing page:
https://demo-prerelease.grocy.info/barcodescannertesting?barcode=5905784315546

...and can reproduce it: https://www.youtube.com/watch?v=q4qq68Mprbo

Will try what I can improve therefore...

**Comment by berrnd** [comment]
I fiddled around a little bit ... and looks good in my test: :)
https://www.youtube.com/watch?v=dEyIuxGTZzw

Scanning is now may be a little bit slower (depends generally on the camera, illumination, angle, etc.), but the accuracy of the recognized barcodes should be better...

Would you mind testing it again on the pre-release demo?
=> https://demo-prerelease.grocy.info/barcodescannertesting?barcode=5905784315546

**Comment by pglaz** [comment]
Hi! Thank you for the quick update! It definitely works better now. 😃

**Comment by SeaLife** [comment]
Hey!

I'm using a new Samsung Galaxy Note 10+ with a wide angle camera. For some reason the Chrome and the default installed browser uses the '0.5x' camera mode to scan in browser. This does not work as this mode does not support autofocus and stuff like this.

A old sony xperia is doing a better job there, as there is no 0.5x camera mode.

I've found this issue (probably related) on the library used for Barcode scanning but this must be fixed on grocy's code (options missing?!)
https://github.com/serratus/quaggaJS/issues/380

Regards
SeaLife

**Comment by berrnd** [comment]
Everything about the camera barcode scanner, starting with `Quagga.init`, is in [`/public/viewjs/components/barcodescanner.js`](https://github.com/grocy/grocy/blob/master/public/viewjs/components/barcodescanner.js) - maybe you can play around a little bit with the options there?

If it's about `facingMode`, we already use `environment` for that option...

If you found a working solution, I'm happy to add it (or submit a pull request)... :)
