### ISSUE TITLE
Bug: Purchase: Barcode-to-Product resolution breaks default best-before entry

### ISSUE THREAD

**Issue by gersilex** [grocy/grocy#363]
On the `/purchase` route, when I enter a barcode that is assigned to a product that has a default best-before date, the best-before date gets autofilled but remains invalid even though the content is correct.

This only happens when using the barcode and works fine when using the product name directly. I assume the best-before date validation happens before the barcode-to-product resolving.

Expected behaviour: The auto-filled best-before field is validated when using a barcode, too.

The bug is present in both the v2.4.4 and the 51e015410170cf411b98c9249c890c3435d27966 (master as of today) ref and can be reproduced in the online demos.

Reproduction:
---
In either demo-en or demo-prerelease:

![image](https://user-images.githubusercontent.com/2018039/65379887-3448b800-dcd0-11e9-857b-ebb3ae5d9004.png)
1. Assign a barcode to a product
2. Assign a default best before days value to the product

---
![image](https://user-images.githubusercontent.com/2018039/65379901-6ce89180-dcd0-11e9-870c-f5757db70256.png)
Go to `/purchase` and enter the barcode, then press TAB

---
![image](https://user-images.githubusercontent.com/2018039/65379918-af11d300-dcd0-11e9-85c6-83f758ca1432.png)
The product is resolved and the best-before will be filled accordingly
1. Enter Amount
2. Enter Price

Submit/OK button is disabled because of the validation error in the red box.

To workaround: Make a dummy change in the input, then leave/blur it.

**Comment by berrnd** [comment]
Thanks for testing! :)

**Comment by gersilex** [comment]
Confirmed fixed. Wow, that was fast. Thank you!
