### ISSUE TITLE
Feature Request: Prefer barcode 'exact' matches over 'contains' matches

### ISSUE THREAD

**Issue by gersilex** [grocy/grocy#366]
As a User I'd like to have my products chosen by a exact match of a barcode, if exists, so that I use my own barcode sheets with very short barcodes.

I created supermarket-like sheets with products of barcodes that typically have no barcodes on themselves (like fruit or paper towels). These have very short Code 128 barcodes (like $1, $2, $10, and so on).

Now when I enter `$1` into the product field, it matches `$10` even though there is an exact match `$1`.

Is it possible to have exact matches match first, maybe by reversing the sort order or do a separate EQUALS search first?

![image](https://user-images.githubusercontent.com/2018039/65394340-d6c67100-dd8c-11e9-8c80-e4a82c1a3380.png)

**Comment by berrnd** [comment]
Sure, it should be an exact match for barcodes.
I thought initially barcodes are distinct enough that this should be no problem...

All barcodes are comma separated in one field of the product, this is put in a data attribute of the `<select> -> <option>` element, looks like that for example:
```
<option data-additional-searchdata="$1,$10" value="15">Tomato</option>
```

Then here the contains search over the `data-additional-searchdata` attribute happens to resolve the input to a product:
https://github.com/grocy/grocy/blob/66571f662fbdbc117c66067337da8afd3cc169ec/public/viewjs/components/productpicker.js#L137

Maybe it's enough to add commas to the input before doing the contains search to make it match only when the complete input is found as a barcode - will try that...

**Comment by berrnd** [comment]
> Maybe it's enough to add commas to the input before doing the contains search to make it match only when the complete input is found as a barcode

I changed it like that and it worked in my tests.

Feel free to test it on the pre-release demo: https://demo-prerelease.grocy.info

**Comment by gersilex** [comment]
Confirmed working in your Demo instance and in my production setup. Incredible, thank you!
