### ISSUE TITLE
Feature request: Meal Plan included in Calender

### ISSUE THREAD

**Issue by kriddles** [grocy/grocy#368]
Can the meal plan be included in the calendar as an option so that the meals flow alongside with the calender ical syncs?

**Comment by berrnd** [comment]
Sure would be doable, but how should the "appointment item" look like?

One full-day-event per day and planned recipe with text "Meal plan: Pizza"?

**Comment by kriddles** [comment]
With the current setup, I would suggest keeping it simple with one full day event 

- Title: "Meal Plan"
- Description: 
"{Meal Name}: {link to full screen recipe}
 {Meal Name}: {link to full screen recipe}
 etc." 

Ideas for future features on Meal Plans concerning calendar -
1.   Build out the date times - breakfast, lunch, dinner which would then correlate to events for each of those.

2. Add a feature to Recipes called "Meal Prep" with a text field. When adding a recipe to the meal plan, if there is meal prep for the recipe then either offer the option or just create a chore for the meal prep for the previous day. My main purpose would be pulling frozen meat from the freezer to the fridge to thaw out. 
To make it an even fancier feature, the meal prep could include a recipe such as a sauce or noodles that could be prepared the day beforehand.

**Comment by berrnd** [comment]
Cool ideas! :)

I've moved them to separate issues (#370 and #371) to keep the overview, this here will be about adding meal plan entries as full day events to the calendar like you suggested:

> With the current setup, I would suggest keeping it simple with one full day event 
>
> - Title: "Meal Plan"
> - Description: 
> "{Meal Name}: {link to full screen recipe}
> {Meal Name}: {link to full screen recipe}
> etc."
