### ISSUE TITLE
Feature request: Meal plan day splitting (breakfast/lunch/dinner)

### ISSUE THREAD

**Issue by berrnd** [grocy/grocy#370]
Ideas for future features on Meal Plans concerning calendar -
1.   Build out the date times - breakfast, lunch, dinner which would then correlate to events for each of those.

_Originally posted by @kriddles in https://github.com/grocy/grocy/issues/368#issuecomment-534123418_

**Comment by deliantwo** [comment]
Sorry for missing this already open issue.
My additional comment: i will find useful not to force the splitting in "breakfast, lunch, dinner" only but, maybe, a custom set and not a fixed one: I may want to add a "snack" meal on Tuesday because I want to do a cake that day but not the day after.

**Comment by berrnd** [comment]
That's now done, looks like that: :)

> ### New feature: Meal plan sections
> - Split the meal plan into sections like Breakfast/Lunch/Dinner
>   - => New button "Configure sections" on the meal plan page to configure the sections (top right corner)
>   - => Each meal plan entry can be assigned to a section

![2021-07-15_17-59-49](https://user-images.githubusercontent.com/2161815/125819569-66b6b850-a9bf-4f9a-8508-e772a911a2f5.png)

=> https://demo-prerelease.grocy.info/mealplan
