### ISSUE TITLE
Meal Plan Mobile Responsive Switch to Agenda View

### ISSUE THREAD

**Issue by kriddles** [grocy/grocy#372]
> I noticed that the grid for mobile for the Meal Plan is not very responsive and the buttons are not all visible. - using google chrome pixel 3

Hm, seems to be not responsive at all...

That's basically just the same as the calendar, forced to view only weeks - the component used is [FullCalendar](https://fullcalendar.io/)...

_Originally posted by @berrnd in https://github.com/grocy/grocy/pull/369#issuecomment-534240712_

Research
https://stackoverflow.com/questions/52751335/full-calendar-mobile-view

**Comment by berrnd** [comment]
Thanks, but `agendaDay` would then only show a single day, I think for the meal plan it would be good to see the whole week always ... maybe somehow the current view could just be made horizontally scrollable...
