### ISSUE TITLE
Tie a Recipe to a Product ("Self produced products")

### ISSUE THREAD

**Issue by kriddles** [grocy/grocy#374]
Just an idea, not fully thought out... 

Can consuming a recipe also be able to increase a product qty tied to the recipe?

For example, if you make your own ranch sauce or gyro meat for use in other recipes.

The product then could also be checked if used as a nested recipe.

**Comment by berrnd** [comment]
Sorry, maybe don't understand that...

So when your recipe needs 2 eggs and you use the "consume this recipe" button, the recipe ingredient amount should be increased (to 4) on that action?

**Comment by blubbel42** [comment]
I Think its more like:
My recipe uses 3 carrots, 5 potatos and 1 kohlrabi, so they are consumed from stock.
It produces 6 portions of vegetable-soup. These will be frozen and added to stock.
so the amount of individual vegetables ist decreased but the amount of soup-portions is increased.
works the like for bread etc., there are even recipes for shampoos..
Especially useful for homemade stuff.

**Comment by berrnd** [comment]
Ah, ok, got it now, great idea!

So kind of "self produced products"...

**Comment by kriddles** [comment]
Thanks!

Yes, I would then use that self produced product which is tied to a recipe in another recipe as an ingredient instead of a nested recipe. That way I can make a 'batch' of whatever the product is to be used across multiple recipes in a week.

A useful part would be making it a clickable link that opens the recipe full screen for that product in the recipe screen.
Or if in the new Meal Plan Recipe Modal, switch to that Product recipe

**Comment by berrnd** [comment]
And just thinking: Even the price of the self produced product should be possible to track automatically, as we already have the price what 1 serving costs based on the product purchase prices...

**Comment by berrnd** [comment]
This has now landed, done by #501.
