### ISSUE TITLE
General error: 1 duplicate column name: parent_product_id

### ISSUE THREAD

**Issue by syphernl** [grocy/grocy#377]
After updating to the latest version of Grocy using `update.sh` I am now getting a `Slim Application Error` stating:

```
Details
Type: PDOException
Code: HY000
Message: SQLSTATE[HY000]: General error: 1 duplicate column name: parent_product_id
File: /srv/http/grocy/hosts/grocy.local/services/DatabaseService.php
Line: 55
```

**Comment by berrnd** [comment]
Cannot reproduce this...

On which page do you get the error?
Could only be the `/stockoverview` or `/product/{productId}` page I think...
Also when an error happens, the full stacktrace should normally be printed, any database statement runs through line 55 of `DatabaseService.php`...

The mentioned column was added in [migration 81](https://github.com/grocy/grocy/blob/master/migrations/0081.sql) to the `products` table.

Anyway, if there are no other errors, this should not hurt anyway, as then maybe the migration runned twice, cannot really think of how this can happen...

Of course `update.sh` is intended to only work between releases, not if you have updated manually something inbetween...

**Comment by syphernl** [comment]
It happens on `/`. 

Here is the trace for that page:
```

#0 /srv/http/grocy/hosts/grocy.local/services/DatabaseService.php(55): PDO->exec('ALTER TABLE pro...')
#1 /srv/http/grocy/hosts/grocy.local/services/DatabaseMigrationService.php(47): Grocy\Services\DatabaseService->ExecuteDbStatement('ALTER TABLE pro...')
#2 /srv/http/grocy/hosts/grocy.local/services/DatabaseMigrationService.php(23): Grocy\Services\DatabaseMigrationService->ExecuteSqlMigrationWhenNeeded(81, 'ALTER TABLE pro...')
#3 /srv/http/grocy/hosts/grocy.local/controllers/SystemController.php(23): Grocy\Services\DatabaseMigrationService->MigrateDatabase()
#4 [internal function]: Grocy\Controllers\SystemController->Root(Object(Slim\Http\Request), Object(Slim\Http\Response), Array)
#5 /srv/http/grocy/hosts/grocy.local/vendor/slim/slim/Slim/Handlers/Strategies/RequestResponse.php(40): call_user_func(Array, Object(Slim\Http\Request), Object(Slim\Http\Response), Array)
#6 /srv/http/grocy/hosts/grocy.local/vendor/slim/slim/Slim/Route.php(281): Slim\Handlers\Strategies\RequestResponse->__invoke(Array, Object(Slim\Http\Request), Object(Slim\Http\Response), Array)
#7 /srv/http/grocy/hosts/grocy.local/middleware/SessionAuthMiddleware.php(26): Slim\Route->__invoke(Object(Slim\Http\Request), Object(Slim\Http\Response))
#8 [internal function]: Grocy\Middleware\SessionAuthMiddleware->__invoke(Object(Slim\Http\Request), Object(Slim\Http\Response), Object(Slim\Route))
#9 /srv/http/grocy/hosts/grocy.local/vendor/slim/slim/Slim/DeferredCallable.php(57): call_user_func_array(Object(Grocy\Middleware\SessionAuthMiddleware), Array)
#10 [internal function]: Slim\DeferredCallable->__invoke(Object(Slim\Http\Request), Object(Slim\Http\Response), Object(Slim\Route))
#11 /srv/http/grocy/hosts/grocy.local/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(70): call_user_func(Object(Slim\DeferredCallable), Object(Slim\Http\Request), Object(Slim\Http\Response), Object(Slim\Route))
#12 /srv/http/grocy/hosts/grocy.local/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(117): Slim\Route->Slim\{closure}(Object(Slim\Http\Request), Object(Slim\Http\Response))
#13 /srv/http/grocy/hosts/grocy.local/vendor/slim/slim/Slim/Route.php(268): Slim\Route->callMiddlewareStack(Object(Slim\Http\Request), Object(Slim\Http\Response))
#14 /srv/http/grocy/hosts/grocy.local/vendor/slim/slim/Slim/App.php(503): Slim\Route->run(Object(Slim\Http\Request), Object(Slim\Http\Response))
#15 /srv/http/grocy/hosts/grocy.local/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(117): Slim\App->__invoke(Object(Slim\Http\Request), Object(Slim\Http\Response))
#16 /srv/http/grocy/hosts/grocy.local/vendor/slim/slim/Slim/App.php(392): Slim\App->callMiddlewareStack(Object(Slim\Http\Request), Object(Slim\Http\Response))
#17 /srv/http/grocy/hosts/grocy.local/vendor/slim/slim/Slim/App.php(297): Slim\App->process(Object(Slim\Http\Request), Object(Slim\Http\Response))
#18 /srv/http/grocy/hosts/grocy.local/app.php(80): Slim\App->run()
#19 /srv/http/grocy/hosts/grocy.local/public/index.php(3): require_once('/srv/http/grocy...')
#20 {main}
```

On `/stockoverview` it is throwing an exception too but this time because of `Message: SQLSTATE[HY000]: General error: 1 no such table: stock_missing_products_including_opened`

**Comment by berrnd** [comment]
That's what I thought of, migration 81, the `ALTER TABLE` for adding the `parent_product_id` column...

_/srv/http/grocy/hosts/grocy.local/services/DatabaseMigrationService.php(23): Grocy\Services\DatabaseMigrationService->ExecuteSqlMigrationWhenNeeded(**81, 'ALTER TABLE pro...'**)_

So your `products` table already has that column, though the migration did not run - that's the problem and I cannot explain how that happened...
All subsequent migrations then don't run either if there is an error, that's the reason for the next error...

So to fix that for your installation, I would remove that `ALTER TABLE` statement from migration 81: Replace the attached file in `/srv/http/grocy/hosts/grocy.local/migrations` (please mind the filename `0081.sql`, `.sql` files cannot be uploaded here obviously...). Or execute the containing statements manually with for example [SQLiteDatabaseBrowser](https://sqlitebrowser.org/).

[0081.sql.txt](https://github.com/grocy/grocy/files/3648194/0081.sql.txt)

**Comment by syphernl** [comment]
Thanks @berrnd that seemed to have fixed it 😄

**Comment by berrnd** [comment]
Great to hear! :)
