### ISSUE TITLE
iCal calendar export data does not include time zone

### ISSUE THREAD

**Issue by zmanplex** [grocy/grocy#379]
I have linked my grocy calendar to google calendar via the api, and it seems that there is no time zone defined in the ical data. I have ensured that my timezone is correct within the app and on my system. The time zone data is just not there and defaults to GMT. This is causing my grocy calendar in the app to look correct, but my google calendar to have incorrect times. Could time zone be added to the ical data to cause it to appear at the correct time in other applications?

**Comment by berrnd** [comment]
Sure, the server timezone can be added, will do that.

Timezone handling in general is currently not done, it is expected that the server and client timezone is the same (see #214).

**Comment by berrnd** [comment]
Is now done, would be great if you could give this a quick test via the pre-release demo: https://demo-prerelease.grocy.info/calendar

(The time zone of the demo server is `Europe/Berlin`.)

**Comment by zmanplex** [comment]
Looks great! The time zone on events when imported to google calendar matches Berlin local time. Thanks for addressing this!
