### ISSUE TITLE
Recipe ingredient list seems to be pulling the converted quantity for purchase, but still displaying the stock label

### ISSUE THREAD

**Issue by DeeeeLAN** [grocy/grocy#382]
I only notice it on items with a ratio other than 1, but the list is displaying a wrongly converted value.

Here for example, I entered 1 teaspoon of white wine vinegar:

![Screen Shot 2019-09-24 at 10 58 07 PM](https://user-images.githubusercontent.com/12877032/65573349-76b40400-df1f-11e9-80c3-9c06a78f3c17.png)

Here is the conversion fields under the product listing:

![Screen Shot 2019-09-24 at 11 04 04 PM](https://user-images.githubusercontent.com/12877032/65573403-9e0ad100-df1f-11e9-9a4d-a29d26a5f90a.png)

Thanks!

**Comment by berrnd** [comment]
Thanks for testing! :)

Can reproduce it...

**Comment by DeeeeLAN** [comment]
Thanks! Definitely frustrating that we purchase by weight but consume by volume. It means a lot of product conversions that I can't use generally, like this one.

**Comment by DeeeeLAN** [comment]
I went to fix my quantities after implementing this change, but now I am unable to select a unit in the recipe product editor:

![image](https://user-images.githubusercontent.com/12877032/65638755-a6085680-df9b-11e9-9b1d-7ac85cfe1b2a.png)

**Comment by DeeeeLAN** [comment]
Disregard, I missed a closing parentheses. :)
