### ISSUE TITLE
Minimum stock amounts should take sub-products amount into account

### ISSUE THREAD

**Issue by berrnd** [grocy/grocy#384]
_Originally posted by @blubbel42 in https://github.com/grocy/grocy/issues/297#issuecomment-535049537_

(Maybe this should be an optional thing per product.)

**Comment by berrnd** [comment]
That's now done, a new option per product:

![grafik](https://user-images.githubusercontent.com/2161815/65672703-c1319f80-e049-11e9-81fe-45dd05e95ef9.png)

Would be great if you could play little bit with it on the pre-release demo: https://demo-prerelease.grocy.info

//CC @blubbel42

**Comment by blubbel42** [comment]
I played around with this. at the moment it doesn't work as I thought it should.
I thought of:

Enough Items: 
- ParentProduct, min.Stock 3,  Sum 5, No Shopping requiered
-- SubProduct1, min.Stock 0, InStock 2, No Shopping requiered
-- SubProduct2, minStock 0, InStock 2, No Shopping requiered
-- SubProduct3, minStock 0, InStock 1, No Shopping requiered

Not Enough Items:
- ParentProduct, min.Stock 3,  Sum 2,  Shopping requiered 1 Item
-- SubProduct1, min.Stock 0, InStock 0, No Shopping requiered
-- SubProduct2, minStock 0, InStock 1, No Shopping requiered
-- SubProduct3, minStock 0, InStock 1, No Shopping requiered

A special case would be I need 3 Items of this type, and at least one of these should be a specific one:
- ParentProduct, min.Stock 3,  Sum 3, No Shopping requiered
-- SubProduct1, min.Stock 0, InStock 2, No Shopping requiered
-- SubProduct2, minStock 1, InStock 0, Shopping requiered 1 Item
-- SubProduct3, minStock 0, InStock 1, No Shopping requiered

For testing I used the Chocolate group on the demo-server, with the box for accumulate amounts checked at the ParentProduct Chocolate, not on the other ones
At the moment it seems to work like this:
Enough Items:
- ParentProduct, min.Stock 2, InStock 0,  Sum 2, Shopping required 2 Items
-- SubProduct1, minStock 0, InStock 1, No Shopping requiered
-- SubProduct2, minStock 0, InStock 1, No Shopping requiered

Not enough Items:
- ParentProduct, min.Stock 2, InStock 0,  Sum 1, Shopping required 2 Items
-- SubProduct1, minStock 0, InStock 0, No Shopping requiered
-- SubProduct2, minStock 0, InStock 1, No Shopping requiered
Special Case:
- ParentProduct, min.Stock 2, InStock 0,  Sum 1, Shopping required 3 Items
-- SubProduct1, minStock 1, InStock 0, No Shopping requiered
-- SubProduct2, minStock 0, InStock 1, No Shopping requiered

So the Sum i should shop tends to be to big for what I thought it should be, I can't really explain better than with these examples, 
Hope this helps a bit, please come back to me with questions any time, as i can't work with code this is the only way i can help at the moment.

Blubbel

**Comment by berrnd** [comment]
Thank you a lot for testing this through, much appreciated! :)
Those things tend to be the most complicated ones, as there are so much details to consider, but that's also the fun part... :D

> Enough Items:
> - ParentProduct, min.Stock 2, InStock 0, Sum 2, Shopping required 2 Items
> -- SubProduct1, minStock 0, InStock 1, No Shopping requiered
> -- SubProduct2, minStock 0, InStock 1, No Shopping requiered

This example is fixed, the problem was that I not took the aggregated amount into acccount on ParentProduct level...

> Not enough Items:
> - ParentProduct, min.Stock 2, InStock 0, Sum 1, Shopping required 2 Items
> -- SubProduct1, minStock 0, InStock 0, No Shopping requiered
> -- SubProduct2, minStock 0, InStock 1, No Shopping requiered

This is implicitly fixed by the example before -> results now in "shopping required for 1 item of ParentProduct" (what you expected above).

> Special Case:
> - ParentProduct, min.Stock 2, InStock 0, Sum 1, Shopping required 3 Items
> -- SubProduct1, minStock 1, InStock 0, No Shopping requiered
> -- SubProduct2, minStock 0, InStock 1, No Shopping requiered

This now results in "shopping required for 2 items of ParentProduct", because the "minStock SUM" is 3 minus "InStock SUM" of 1.

This is what I meant with the hint next to the checkbox "_If enabled, the min. stock amount of sub products will be accumulated into this product, means **the sub product will never be "missing"**, only this product_"

This checkbox is the indicator if everything should be accumulated on the parent product level or not.

What you expected seems to be a mixture, if I understand it right, the "InStock" amount should be aggregated on parent product level, but not the "minStock" amount. (?)

I don't know if this makes it not overly complicated...

```
Just as a note to myself:
The expected result for the "special case" is possible when taking
in the last block "Sub products where the amount SHOULD NOT be cumulated into the parent product"
of the view "stock_missing_products" the aggregated amount into account ->
"SUM(sub_p.min_stock_amount) - IFNULL(SUM(s.amount_aggregated), 0) AS amount_missing".
```

The pre-release demo is updated again, if you want to play around again: https://demo-prerelease.grocy.info

I noticed two other things:
- On any consume/open/etc. of a sub product on the stock overview page, also the parent product (row) should be refreshed -> will be tracked in #394
- Maybe it would be good to have some kind of "persistent" demo instances where scenarios could be saved/shared (currently the stable demos are recreated every 24 hours, the pre-release demo past 10 minutes every hour)

**Comment by blubbel42** [comment]
Thank you very very much. The first two cases are working fine now.

regarding the third case: yes, thats the reason i called it a special case. It's something i wouldn't need (why should i buy something i wouln't need anyway?) and I think if one product is so important it needs to be there in exactly that version (some people may be/know picky eaters) then the issue can be solved by making this an individual product. without grouping.  So it would be considered seperately.

I really came to thinking about this because a frind of mine has an autistic son who will just eat this one special version of whatever.

**Comment by berrnd** [comment]
Thanks for testing again. :)

Then I think we'll leave it as it is now for the next release, works like the hint/label of the checkbox describes it. I plan to drop a new patch release on Saturday or Sunday.

**Comment by IlonkaPingel** [comment]
Hey there,

I ran into a problem with the feature. I did the following

- add product A intended to be used as a parent product, unit in Gram, minimum amount 1000
- add product A.1 with parent product A, unit in Piece, QU conversion 1 Piece = 120 g
- add product A.2 with parent product A, unit in Piece, QU conversion 1 Piece = 110 g
- add product A.3 with parent product A, unit in Piece, QU conversion 1 Piece = 300 g
- add 3 instances of product A.1 -> sum in product A is 360 g = fine
- add 3 instances of product A.2 -> sum in product A is 660 g = **not fine**, should be 690 g
- add 2 instances of product A.3 -> sum in product A is 2,400 g = **totally not fine**, should be 1290 g

I tried to remove all products from above and redo the process, but it keeps happening. Renaming for example product A does not change anything either.

What is happening with the sum calculation here? This seems to be a bug.
Can you reproduce and maybe fix it, please?
