### ISSUE TITLE
Allow substitutions in a recipe

### ISSUE THREAD

**Issue by DeeeeLAN** [grocy/grocy#385]
I want to be able to add alternate ingredients to an ingredient in a recipe, so that when I click "consume all ingredients in this recipe", it by default consumes all primary ingredients, then if there isn't enough of a primary ingredient, it consumes a secondary ingredient (perhaps they can be sorted as well, to indicate priority of consumption).

For example, I had a recipe tonight that called for 1 Persian cucumber, but I chose to use 0.5 of an English cucumber instead. And if I was out of both, then a normal cucumber could be used as another alternative. But because I didn't have any Persian cucumbers, I was unable to click the "consume all ingredients" button.

**Comment by berrnd** [comment]
Similiar to #187, but different regarding what should happen on "Consume this recipe".

Spontaneously I have no real idea how to do this best UI wise on the recipe edit page...

Another idea:
If you have a parent product "Cucumber" where all other variants are sub-products and use only "Cucumber" in the recipe, the fulfillment checking should be good, as suggested in #187.

Then maybe we could list all sub products of a parent product in the ingredient list of a recipe (maybe expand it by clicking on it).

When consuming a recipe, there could be then a popup like when using "Put missing products on the shopping list" where you can exchange parent to sub-products.

What do you think?

**Comment by DeeeeLAN** [comment]
I am thinking it could be similar to the unit conversion interface, where you could add substitutions generally like "1 English cucumber = 2 Persian cucumbers", then just have a dropdown where you can select it. 

Then maybe just have a warning in the recipe list "This ingredient is out of stock, [x] will be substituted instead."

I think your suggestions should work as well.

**Comment by Sanfam** [comment]
What if there were an intermediate step between when a recipe added to the list, and the recipe is consumed, where the user has the option of making alterations to it? This would essentially treat the recipe as a template from which the meal is based and allow for an opportunity to confirm ingredients and offer a point at which they could alter them.

**Comment by berrnd** [comment]
_UI suggestion for this originally posted here: https://www.reddit.com/r/grocy/comments/g3w44r/allow_for_substitutions/fo59z6f/_

> more Product dropdown-menus inside each Ingredient card

**Comment by berrnd** [comment]
Merged into / replaced by #2078 and #2079, which should cover this use case.
