### ISSUE TITLE
Feature Request: Work out price per unit quantity on purchace

### ISSUE THREAD

**Issue by Akeboshiwind** [grocy/grocy#390]
I think a simpler flow to the purchase panel would be:

1. Add Product name & best before
2. Add Amount purchased
3. Add Price paid in total for all purchased
4. Carry on as normal

It should be easy to work out how much an individual product costs using the amount and the total paid.

I appreciate that some people might prefer the current solution of adding in the price of a single unit so maybe an option could be added in the config to use one or the other if this is added?

**Comment by berrnd** [comment]
So the only change would be that the price is for the whole purchased amount instead of for 1 unit as currently.

Can be changed, of course - on the receipts I have there are usually both values printed on...

**Comment by berrnd** [comment]
That's now possible - an option below the price field on the purchase page:

![grafik](https://user-images.githubusercontent.com/2161815/65767335-ded83500-e12d-11e9-9701-eadc41e37068.png)

Defaults to "Unit price".

=> https://demo-prerelease.grocy.info/purchase

**Comment by Akeboshiwind** [comment]
Amazing, thank you!
