### ISSUE TITLE
Ability to hide out of stock items on overview

### ISSUE THREAD

**Issue by lwis** [grocy/grocy#393]
I typically have lots of items that are out of stock that we may not purchase for a while, but when we do purchase it's good to track the dates, it would be good to hide these products from the overview.

**Comment by berrnd** [comment]
Only products with a min. stock amount defined are visible on the stock overview page, when not in stock (blue lines).

Is currently wrong, as you noticed in #392.

Or do you mean an option to hide those blue lines / products with a min. stock amount defined?

**Comment by lwis** [comment]
@berrnd ah, gotcha - makes sense. The way it works is fine 👍 thanks.
