### ISSUE TITLE
feature request: Make customEntity List  printable

### ISSUE THREAD

**Issue by blubbel42** [grocy/grocy#396]
Hello,
The custom entities are a great feature, what I would love is making it printable like the inventory-list. in this case sorted by whatever customField I define. Then i could print out a list of my RubberDuckies, give it to my friends and be sure not to get a third one of a special kind.

yes i can do this via Browser, but the design of the printable list is so much better for paper.

Also nice in terms of keeping track of inedible objects: adding a location (may be same pool as for products? but then there would be RubberDuckies in my FoodInventory I think..) as a custom field.

Blubbel

**Comment by berrnd** [comment]
> adding a location (may be same pool as for products?

Means you want to reference an existing object, this is already tracked in #335.

**Comment by berrnd** [comment]
I've optimized the custom objects list page that it can be printed properly (search field etc. is hidden when printing the page), hope this helps for what you thought of.

=> https://demo-prerelease.grocy.info/userobjects/exampleuserentity
