### ISSUE TITLE
QU conversions - Product overrides are displayed on every product

### ISSUE THREAD

**Issue by Aphris-Karu** [grocy/grocy#400]
The new QU conversions when adding a product apply to all products. 

This is a problem because the number of cups in 1lb of rice is not the same as the number of cups in 1lb of flour.

**Comment by berrnd** [comment]
You can QU conversions on the QU directly - then it applies to all products which uses this QU.

And you can add the conversion to a product (product edit page, [example](https://en.demo.grocy.info/product/10)), then it only applies to that product. I cannot reproduce that such a conversion applies to any other product than the one on which it is defined... (?)

**Comment by Aphris-Karu** [comment]
My QU Conversion added to the product rice shows up under both rice and flour.

**Comment by berrnd** [comment]
Ok, seems to be just a display error on the product edit page, for the demo example of course the conversion should be only visible for "Cheese".

When you check that example when adding the ingredients to a recipe, it works correctly, only "Cheese" will have the Slice QU available.
