### ISSUE TITLE
Feature Request: shift+arrows to adjust best before date by months and years

### ISSUE THREAD

**Issue by Sohalt** [grocy/grocy#405]
It would be helpful to have shift+up/down adjust the best before date by a month and shift+left/right by a year.

**Comment by berrnd** [comment]
That's slightly different already possible:
https://github.com/grocy/grocy#input-shorthands-for-date-fields

So you want be able to customize what the arrow keys do on date fields?

**Comment by Sohalt** [comment]
I would like to have the possibility to not only adjust by day or week intervals, but also month and year intervals (pressing shift and the corresponding arrow key).
The desired behavior for me would be:
down -> increment by 1 day
right -> increment by 1 week
shift+down -> increment by 1 month
shift+right -> inrcement by 1 year

**Comment by berrnd** [comment]
Ah, sorry, I missed that your request is for "arrow keys **+ shift modifier**" - that's totally fine, thanks for the idea, will add that... :)
