### ISSUE TITLE
Seasonal/yearly chore frequency.

### ISSUE THREAD

**Issue by CryoByte33** [grocy/grocy#407]
First of all I wanted to say that the latest release fixed every concern I had about using products with quantity conversion! 

I decided to attempt to swap over from a calendar based chore system to using grocy, the one issue I'm having is that there's no functionality to create seasonal/yearly chores. As it currently stands, I'd need to make a calendar reminder in my personal calendar telling me to do the chore in grocy, which eliminates the point.

I think the easiest way to do this would be to add a selection for yearly recurrence and allow for a number, just like the monthly option now.

I think that allowing this numerical entry would allow for much greater flexibility for long term scheduling for home maintenance!

Bonus request: Allow the box to accept a comma delimited list so you can specify certain days throughout the year. That way you can just specify `60,150,240,330` to schedule a task for each of the 4 seasons (at least in New York).

**Comment by CryoByte33** [comment]
Just as a note on this, I'm aware I can use a 90 day "Dynamic Regular" frequency, but this doesn't guarantee a stable "due date" since it'd slide the whole schedule back if I did the task a day late. In addition, that would create a constantly sliding schedule where the due date would eventually end up moving forward or backward out of a season for example.

**Comment by berrnd** [comment]
Great that QU conversions now work for you! :)

Chore scheduling should be more flexbile when https://github.com/grocy/grocy/issues/312#issuecomment-510765428 is done and I think that should also fit your request, but I'll leave this also open...

**Comment by CryoByte33** [comment]
Oh, yup, that looks perfect!

**Comment by berrnd** [comment]
#312 is now done, see https://github.com/grocy/grocy/issues/312#issuecomment-538319876.

Additionally I also added a yearly period type, but that should be the same as a monthly schedule with the new "period interval" set to 12.
