### ISSUE TITLE
Feature Request: Store attribute for products and shopping list

### ISSUE THREAD

**Issue by mdallaire** [grocy/grocy#408]
I think it would be great if we could define one or several stores where a product is usually bought and generate shopping lists filtered by stores.

For example: If I stop by the grocery store coming back from work I would be able to have a shopping list with only the items I usually buy there (no hardware store related items or items I buy online). Some options to display all/low/empty stocks for the items tagged with this store would also be nice.

Being able to tag several stores for an item and maybe have a primary one would let us define a preferred store for sourcing but also show the item in other store lists if low or out of stock. I may be able to buy some headache medication at the grocery store if I am in a rush or out of stock but I can probably buy better quality/cheaper at the drug store.

**Comment by berrnd** [comment]
You can create a Userfield to attach one or more stores to a product, these Userfields are also rendered on the shopping list. No "filter by store" dropdown will be rendered on the shopping list for the Userfield (could also be added as a general thing for Userfields maybe), but the normal search field will work and is maybe already enough.

I created an example on the English demo:
https://en.demo.grocy.info/shoppinglist
https://en.demo.grocy.info/userfield/3
https://en.demo.grocy.info/product/2
