### ISSUE TITLE
Order of products in grocery list

### ISSUE THREAD

**Issue by Suitcasechild** [grocy/grocy#409]
Hi, 

I think it will be e very good feature to have a possiblity to edit the sequence /order of entrys in grocery list. i think every one has his prefered foodmarket. So you have most of this cases one way through the market.  In my case are vegetables at first, milk butter at second, bread, bakery on third.. etc.. 
So i want to have on my list that things correct sorted when i walk through the market and don´t have to search or went chaotically through the mart. They don´t have sorted their products  accorded to alphabet.

**Comment by berrnd** [comment]
First: You can sort every table by every column by just clicking the column header.

Second: For exactly what you mean, order products how they are ordered in the supermarket, product groups were introduced. Products get grouped together (and ordered) by them on the shopping list. See the demo shopping list: https://en.demo.grocy.info/shoppinglist

![grafik](https://user-images.githubusercontent.com/2161815/66265478-82ed6a80-e817-11e9-9ed8-4ccbe2bfa7d3.png)

**Comment by Suitcasechild** [comment]
thanks for that fast reply. i dont  understood the sense of  product groups until your explanation.  this is really better than a sorting of grocery list.
