### ISSUE TITLE
Feature Request: Show unit/total price on the shopping list (configurable)

### ISSUE THREAD

**Issue by Suitcasechild** [grocy/grocy#410]
Hi Bernd, An other question:
Is it possible to to show the unitprice and the total price on shopping list, based on the last price of last purchase?

**Comment by berrnd** [comment]
No, not in the table - only Userfields can be configured to be shown in tables, for built-in fields there are currently no options to show them in tables.

I changed the title here accordingly.
I think this should be optional.
