### ISSUE TITLE
Feature Request: Close "Create new product" page when GET parameter was submitted

### ISSUE THREAD

**Issue by Forceu** [grocy/grocy#419]
It would be great if there was a GET parameter to have the window close itself after a new product was created. With Barcode Buddy it is possible to create a new product from the UI and once the tab is closed, Barcode Buddy looks up the new product.

If the window closed itself after creating the new product, this would make it a lot user-friendlier. Unfortunately I am not really familiar with blade PHP, otherwise I would have made a PR.

This is a very simple change: If eg. the parameter $_GET["closeAfterCreation"] is set and the new product is created, simply calling `window.close();` with JS would close the window. This works, as the new tab was already opened with Barcode Buddy, therefore it can also be closed with this command (it would probably not work if it was a tab that the user opened).

Thank you! :)

**Comment by berrnd** [comment]
Let's close this when #420 is merged... :)
