### ISSUE TITLE
Feature Request: Calendar overview 

### ISSUE THREAD

**Issue by BlizzWave** [grocy/grocy#42]
A calendar overview where you could see upcoming habits, product best before dates, battery charge schedules.

**Comment by berrnd** [comment]
Added a first version of this now using [FullCalendar](https://github.com/fullcalendar/fullcalendar).

It currently provides a month and week view and contains:
- Upcoming product expirations
- Upcoming due tasks
- Upcoming due chores
- Upcoming due battery charge cycles

Can be tested on the [pre-release demo](https://demo-prerelease.grocy.info/calendar).
