### ISSUE TITLE
Option to freeze products

### ISSUE THREAD

**Issue by berrnd** [grocy/grocy#426]
Analogue to "Default best before days after opened" - option per product, then an action from the stock overview product conetext menu.

**Comment by kriddles** [comment]
My pull request set's the best buy date dependent on if a location is a freezer.

I suppose if not using the locations feature then the frozen would need to apply to a stock item instead.

**Comment by berrnd** [comment]
Thank you, but I think it's more common, at least for me, like this:
- I think (most) frozen products also expire at some time, at least they also have a best before date
- If I buy an already frozen product, I directly put it in the freezer on purchase (or better the product already has the freezer as its default location) and set the best before date and so on just as for all other products
- If I buy a product and freeze it later, it probably is good longer than the initial best before date on purchase (e. g. meat)
  - But when I thaw it, the best before date is not again the original one (which is probably already in the past), but again some x days starting at that time (so an option like "Default best before date after defrosting would maybe be needed as well)

So I think your idea to mark an location as a freezer is good.
But the  "Default best before days after freezing" and  "Default best before days after defrosting" I think are different per product, and therefore a product option.
Also to apply that when transfering products from/to a freezer location is a good idea, I think.
(So a context menu option "Freeze this product" would be just a shortcut to a transfer action internally.)

**Comment by kriddles** [comment]
Sounds good, I'll leave the merge open for now so the branch is available to work off of. Maybe I can take a look at it again but don't wait on me for it.
