### ISSUE TITLE
Feature Request: Keep screen on while displaying recipe

### ISSUE THREAD

**Issue by yarons** [grocy/grocy#427]
One of the most annoying things while cooking is having to unlock the screen with dirty hands, is there an option to keep the screen on (if it's not currently happening)?

**Comment by berrnd** [comment]
There is currently no option for this - and grocy is only a webpage/-app, the Browser has access to your device, not grocy directly.

I don't think there is an official API for this, but maybe https://github.com/richtr/NoSleep.js looks promising which tries to solve this by playing an invisible video in the background...

There are also Browser extensions to solve this...

**Comment by Forceu** [comment]
I am using NoSleep.js, however I am using [this PR](https://github.com/richtr/NoSleep.js/pull/65) which reduces the CPU load

**Comment by berrnd** [comment]
Great, so let's add this as an option in the display menu (where also Night mode and so can be configured) as an option `Keep screen on` alongside with an option `Only while displaying a fullscreen-card` to only enable it when for example a recipe is displayed in "expanded mode"...

**Comment by berrnd** [comment]
This is now done using NoSleep.js.

Two new options in the display menu:

![firefox_2020-01-05_10-03-23](https://user-images.githubusercontent.com/2161815/71777629-d43a0100-2fa2-11ea-89ba-5756a95b6e21.png)
