### ISSUE TITLE
Select start of week for mealplan

### ISSUE THREAD

**Issue by Jeltel** [grocy/grocy#429]
We always do the weekly shopping on saturday. But the mealplan starts on monday. Therefore we have to switch back and forth between two weeks and cannot use the add to shopping list in one go.

Is it possible to select a start day for the week just for the mealplan?

**Comment by berrnd** [comment]
No, there is currently only the setting [`CALENDAR_FIRST_DAY_OF_WEEK`](https://github.com/grocy/grocy/blob/da2c8d48ac741b53c63f210032d5c115aae52866/config-dist.php#L28) to define the first day of the week which is then used for all calendar views, the date picker, etc.

Of course a separate option just for the meal can be added...

**Comment by berrnd** [comment]
Or maybe just a question for a date range when using the button "Put missing products on the shopping list" which defaults to the current week...

**Comment by Jeltel** [comment]
the latter would lead us to have to do more actions. So the first one (a separate option) is preferred.

**Comment by berrnd** [comment]
There is now a new `config.php` setting `MEAL_PLAN_FIRST_DAY_OF_WEEK` to override that only for the meal plan view.
