### ISSUE TITLE
Feature Request: Allow Inventory Items to be split between Locations

### ISSUE THREAD

**Issue by Sanfam** [grocy/grocy#432]
Much as you would find in a proper warehouse ERP, it'd be awesome to be able to split a single Inventory Item's stock across multiple locations (ex. 4 Units in Refrigerator, 12 Units in Overflow Refrigerator, 20 Units in Freezer).  

Similarly, users should be able to move inventory between existing locations (Potentially related to #191) or transfer it to new (unoccupied) locations entirely (ex. move 3 Units from Freezer to Refrigerator)

**Comment by berrnd** [comment]
You can already set a different location on purchase.

Moving existing stock items between locations is already tracked in #191 and is also already worked on in #421.
