### ISSUE TITLE
Feature Request: Allow user to "Increase/Decrease Inventory By Qty" instead of setting Absolute Stock Level

### ISSUE THREAD

**Issue by Sanfam** [grocy/grocy#433]
When making inventory adjustments in Grocy, users appear to be restricted to setting absolute inventory values. 
![image](https://user-images.githubusercontent.com/3504427/67736922-c59dff00-f9df-11e9-9cac-d98785293fb5.png)

In many cases, it would be more convenient potentially safer to adjust by the count added or removed to Inventory rather than adjusting the absolute count/total on-hand. For example, when adding 5 Boxes of Pasta to my stock of 12, I would enter `5` while the present system would have me enter `17`.  When consuming 3 Boxes, I would enter `-3` instead of `9`. 

The current system includes context hints communicating this:
![image](https://user-images.githubusercontent.com/3504427/67737238-ca16e780-f9e0-11e9-8618-69841b27a0ba.png)

Ideally, this would be configured through a config setting, or have both available in the input form.

**Comment by berrnd** [comment]
Ok, can be added - but you could also just use the purchase/consume pages when you want to enter the amount added/removed...

**Comment by gersilex** [comment]
@Sanfam How would that differ from using the `purchase` or `consume` page? Or what is driving your desire to have that feature in the inventory? I'm genuinely interested from a user experience point of view.

**Comment by Sanfam** [comment]
@gersilex , to summarize, this issue was created relatively shortly after I adopted Grocy and began to more clearly understand various functions for managing inventory beyond setting absolute stock levels.  To be honest, I agree; The `purchase` and `consume` functions make more sense and enforce good use practices. And finally, I believe I more concisely identified what bothered me here in #434, so I'm for closing this.
