### ISSUE TITLE
Pre-populate "New Amount" with current Inventory level

### ISSUE THREAD

**Issue by Sanfam** [grocy/grocy#434]
When making an adjustment to an inventory item, the "New Level" field is unpopulated. This requires the user to read the form to determine current count and enter an appropriate value. The field should be pre-populated with the current count.

![image](https://user-images.githubusercontent.com/3504427/67737311-0cd8bf80-f9e1-11e9-83df-ba999ecb69cc.png)

**Comment by berrnd** [comment]
The current count would also invalidate the form, because it is checked that the new amount cannot be the same as the current amount (as the validation message says).

If you count your products and the result is that you have 5 in grocy and in reality, you don't have to do anything.

So I don't see why initially populating that field with the current stock value of the item would make any difference...

**Comment by Sanfam** [comment]
@berrnd , though obviously based in opinions, I feel this issue relates to usability considerations and not how validation should operate. It is expected for form validation to fail if form were pre-loading the current stock value ("Nothing's changed, nothing to submit"). 

- With the field empty, the user **must** input the value via the keyboard versus using the up/down arrows to adjust the current value.  This forces a keyboard or input selector to load in on mobile devices or switching inputs between mouse, keyboard, and back.
- There are cases where large quantities of an item are inventoried, making counts unnecessarily time consuming (ex. hundreds or thousands of small items)
- Forces a cognitive load on the user where none is necessary ("I want to add 13 to 934" vs tapping the UI and seeing immediate count confirmation via validation)

**Comment by berrnd** [comment]
Ok, then let's populate it with current stock amount, like you proposed - for me it makes no real difference...

Or maybe also make this configurable...

**Comment by gersilex** [comment]
I agree that functionality-wise it makes absolutely no sense. But from a usability perspective, seeing *what* the current stock is in the field where you will enter the new stock amount makes much sense and feels more natural than having to look it up in the product details pane.

Not really a useful comment of mine; just want to show that I also think this would be a good addition to the inventory function :)
