### ISSUE TITLE
Incrementing Inventory Price with Arrow Buttons alters price with wrong precision

### ISSUE THREAD

**Issue by Sanfam** [grocy/grocy#435]
Attempting to adjust a price, for example `21.37`, by using the form's clickable arrows increases/decreases the value by `0.0001`.  For example:

Initial State:
![image](https://user-images.githubusercontent.com/3504427/67737881-16632700-f9e3-11e9-89d6-b6e09cf4b5c1.png)

After 3 taps of the Up Arrow:
![image](https://user-images.githubusercontent.com/3504427/67737891-24b14300-f9e3-11e9-9d44-3c919030e1b9.png)

**Comment by berrnd** [comment]
This was fixed by #421.
