### ISSUE TITLE
Nicer error for barcode scanner

### ISSUE THREAD

**Issue by OmgImAlexis** [grocy/grocy#437]
Currently this error is thrown on the barcode scanner page. It'd be nice to see a better description with maybe a link to how this is fixed?

```
"getUserMedia is not defined"
```

**Comment by berrnd** [comment]
The info is in [README](https://github.com/grocy/grocy#barcode-readers--camera-scanning) and in the changelog were this was introduced, of course we can show a link in the error...

But there can only be two problems: Your Browser does not support the Media Streams API or you don't use a secure (https) connection (the later can also be worked around, like [in that example](https://github.com/grocy/grocy-desktop/blob/4393d87f50335ffa65940bdea1f20d83050ed229/grocy-desktop/FrmMain.cs#L32) by commandline arguments for Chrome I used in [grocy-desktop](https://github.com/grocy/grocy-desktop))...
