### ISSUE TITLE
Feature Request: Change default chores sort

### ISSUE THREAD

**Issue by pglaz** [grocy/grocy#439]
Hello!

It appears that currently the default chore sort is:

- ones I don't have to worry about in a while on top,
- ones that are due soon or overdue on bottom.

Personally, I'd prefer if it was the other way around -- I want to see tasks that are due soon or overdue on top. Is this setting already available perhaps?

**Comment by berrnd** [comment]
All tables can be sorted by any column (click on the header) on the desired sorting is saved in `localStorage` (so per Browser)...

**Comment by pglaz** [comment]
Ah, I knew I can sort by any column but I didn't know it was being saved. On my end it's not but I'll assume that it's due to my browser configuration as it's not standard.

Thank you!
