### ISSUE TITLE
Bug: Tables search: Only search in visible columns/content

### ISSUE THREAD

**Issue by BlizzWave** [grocy/grocy#440]
There is a weird issue regarding searching for something that starts with "eg" if you are using other language than English.

![ui-bug](https://user-images.githubusercontent.com/6298655/68544383-ea707a00-03c2-11ea-8a31-7894f0b74ddb.gif)

**Comment by berrnd** [comment]
We use the [native DataTables search function](https://datatables.net/reference/api/search()), and seems that this searches in everything of the row - the first option in the context-/more menu is "Legg til i handlelisten" in Norwegian, which contains "egg" and therefore all rows are matching...

I'll try to fix it that it only searches in visible columns.

**Comment by BlizzWave** [comment]
Ahh, that makes sense. This would probably also be a issue in other languages
