### ISSUE TITLE
Feature Request: Add attachments to equipment.

### ISSUE THREAD

**Issue by CorneliousJD** [grocy/grocy#441]
I know we already have the ability to attach user manuals (which is fantastic) but sometimes equipment has other related documents. 

For one, I'd like to keep the following.
Sales receipt 
Warranty/extended warranty info
repair person contact info/receipts/service history, etc.

Thanks for the consideration!

**Comment by CorneliousJD** [comment]
To add some additional context to an easy implementation, two good options I think would be.

1. Just allowing an attachment in notes, right now it's only photo or videos, but you can't add/link other PDFs or anything like that. 

2. Add a tab for attachments, so have user manual / notes / attachments and then you can just upload whatever file (within reason) and give it a friendly name maybe?

**Comment by berrnd** [comment]
More or less the same as #262.

**Comment by HydrelioxGitHub** [comment]
If this feature is implemented, it could be very useful for my needs. Especially for warranty files. I hope it will be integrated.

**Comment by HydrelioxGitHub** [comment]
Any news on this enhancement ?

**Comment by berrnd** [comment]
https://github.com/grocy/grocy#roadmap

**Comment by berrnd** [comment]
This is now basically possible, there is new Userfield type "File" which can be used to attach any file, will be rendered as a link in tables - see #977.

Based on that, I created a follow-up issue to improve that even more for Equipment - I think a tab per file would be handy here - see #978.

**Comment by berrnd** [comment]
Cross-referencing #978 here - it's now possible to add multiple files / PDFs to each equipment by using Userfields, changelog excerpt:

> - It's now possible to add multiple files (PDFs / manuals) to each equipment
>    - Define as many Userfields for the entity `equipment` and use the type `File`
>    - => Each of those File-Userfields will be shown as a separate tab on the equipment page
