### ISSUE TITLE
Feature Request: Userfields for stock entries (+ possibility to add them on purchase)

### ISSUE THREAD

**Issue by cwoomi** [grocy/grocy#443]
Is it possible to add a userfield similar to "best before" to save the batch number for each product? I plan on using grocy to manage stuff, which requires me to also save the batch number of specific items in case of a recall of certain batches.

**Comment by berrnd** [comment]
It's currently only possible to attach a Userfield to a product itself, so you can only assign a single batch number to a product. I assume you want to track that number on each purchase - that's currently not possible.

I change the title of this issue to track extending Userfields about that.

**Comment by cwoomi** [comment]
Sorry to bother you, but any update about the chances of this being added? =) great work btw =)

**Comment by berrnd** [comment]
Sorry, no - if there is progress, you'll find it here...

**Comment by aeramos** [comment]
Is there any progress on this or any ideas for a workaround? It would be really nice to have this.

**Comment by berrnd** [comment]
> Is there any progress on this

[README mentions](https://github.com/grocy/grocy#roadmap) that any progress is always tracked in the corresponding issue/request, so here. This is still open, so not yet done. Simply subscribe to this request if you want to get notified about updates.
