### ISSUE TITLE
Consume recipe: Consume child products when parent product is out of stock

### ISSUE THREAD

**Issue by schildgenb** [grocy/grocy#446]
When I am trying to click consume recipe I keep getting the message not all ingredients of recipe are in stock, nothing removed even though the recipe is stating everything is in stock. Has anyone else ran into this issue? I have also looked and everything is in stock.

**Comment by berrnd** [comment]
I can reproduce this with parent/child products on the demo:
Recipe "Chocolate sauce" has the ingredient "Chocolate", which is not in stock, but any of the child products "Dark Chocolate" or "Milk Chocolate" are in stock, so the amount of any child product should be consumed.

Is your problem reproducible in that way?

**Comment by schildgenb** [comment]
I never thought of that but yes I believe that is my problem is I have the parent on there which is not on stock but the child is. I looked at the recipes and that is the common factor.

**Comment by berrnd** [comment]
Thanks for the feedback, so this is clearly a bug - when consuming a recipe and the ingredient is a parent product which is not in stock, but any child product, any of those child products should be consumed.

(Maybe this should also apply for "normal consume".)

I changed the title of this issue to track this here.
