### ISSUE TITLE
Have a way to specify shop places / Price tracking per store

### ISSUE THREAD

**Issue by immae** [grocy/grocy#447]
I’m not sure it is feasible with the current state of the code (with "user entities"), but it would be nice to be able to specify a list of (location, price) for a product, so that we can for instance compare prices between two shopping places (or see the evolution of price separately per shop), or prepare a shopping list specific to a given place, etc.

**Comment by berrnd** [comment]
Userfields are attached to a product, it's currently not possible to track them on purchase/consume/etc.

Similar to #443, but I also leave that open as it is about price tracking per purchase location.

**Comment by berrnd** [comment]
_Originally posted by @aaruni96 in https://github.com/grocy/grocy/issues/490#issue-548462452_

> It'd be really nice if while making a purchase, we can record what shop/supermarket the thing was purchased at, and the price tracker tracked prices per store.

> So, if I sometimes purchase product from store A, and sometimes from store B, I want to see two graphs in the price tracker : one for store A and one for store B

**Comment by Belafestim** [comment]
i see this in the pre-release and am really pumped, can we additional fields address and phone numbers
