### ISSUE TITLE
[Idea] Database seed with some basic recipe ingredients

### ISSUE THREAD

**Issue by LukaszSolo** [grocy/grocy#451]
Hi,

I've searched through issues and haven't seen one, sorry if my search skill was not great.

I just started using grocy and realized I need to to a lot of initial manual work. I was thinking maybe adding option during installation of importing some basic, common, non-barcoded items to the database would be helpful?

E.g I was adding banana as an recipe ingredient, then I was googling how many calories bananas have. I will repeat it with apple, carrot, califlower etc.

I was thinking maybe having them in db already would be nice. If someone is using a specific type of fruits/veggies/spices, they can add them later, while for me defaults would be enough.

I know it's only initial set up of adding it all, but if I'm going to add 50 elements (salt, pepper, sugar, apple, banana, pear, carrot, etc etc) and it takes me 1 hour and the same is done by another thousand of people ;) think how much time we could save globally :)

**Comment by berrnd** [comment]
Somehow relates to #445, #158, #210.

A product also needs at least a location and a quantity unit stock/purchase.
All of them are individual, maybe someones want to track Pepper in grams, I for example prefer to only track packs.
And everyhting of that needs to be localized.
If I need to adjust all properties, don't know if it's so much time saving to not also give the product a name manually...

I added the "workflows" (enter something unknown in the product picker) to maintain product data and add new ones on the fly, during purchase and so on. Personally I also only add generic products to grocy, not products per brand or flavor or something. So most of the time I buy things I've not bought before, I only need to attach that barcode to an existing product (also a workflow). After two and a half year of grocy and tracking everything, I maybe add a new product once a month or so...

So "the import topic" comes up quite often, maybe I (or someone else) will fiddle something together at some time, but at the end I think there is no way around that if you want to have it your way, you need to define the products how you want it. The more details you want to get out ([analysis stuff](https://github.com/grocy/grocy/issues/64) will hopefully arrive soon), the more details need to be put in - that's the same for all (ERP) systems...

**Comment by LukaszSolo** [comment]
Thanks for the detailed response. I was thinking about it a little more - maybe me (and the users I was thinking about) are not the target of the app in the end? I'm someone who wanted to use grocy as a self-hosted app where I can track the recipes and ingredients for them, the rest of the system is a nice bonus. Thus the recipe func is the focus and a starting point of my interaction with the app.

In general, I feel the initial set up is bit daunting (sorry :) ) Taking your pepper example, I think that it's easier/faster to delete/edit the defaults later. Setting up the initial options requires a lot to understand from the beginning.

I hope I'm not sounding too negative, I like grocy and idea behind it (and I'm adding stuff every day, bit by bit)

**Comment by vorkuta** [comment]
@berrnd To take a slightly different approach to this, how does the following sound.

If an enhancement can be made that allows for the export / import of products (excl. userfields) then could this allow the community to create a crowdsourced 'seed' that new users can then use? The only challenge I see is for the units etc., but provided the defaults are used for this it shouldn't be problematic?

This extract could then be edited rapidly outside of grocy and imported on a new install. optional of course. I would certainly find this useful for rapid editing of my master product list in another program, for example.

**Comment by berrnd** [comment]
Sure, should be possible, but I think already part of / tracked in #129...

**Comment by berrnd** [comment]
Closed in favor of #129.

No products (like anything else) will ever be shipped by default. When having a generic import/export way some "default lists" could be easily shared. All that is also already possible today by using [the API](https://demo.grocy.info/api).
