### ISSUE TITLE
Function and filter checkmark in shopping list?

### ISSUE THREAD

**Issue by ministryofsillywalks** [grocy/grocy#452]
I'm trying to figure out what the checkmark in the shopping list does apart from crossing out the item on the list?
![grafik](https://user-images.githubusercontent.com/10544895/70134947-51fbab80-1689-11ea-8a24-583dec3c3b9a.png)
As far as I can tell it has no other function right?
It would be great to filter out the checked items from the shopping list, as especially on a long list it would be nice to have the list decreasing until nothing is left making it a lot easier to see what still needs to be purchased.
After shopping the filter could then be taken out again to then add all the items to stock in one swoop.
![grafik](https://user-images.githubusercontent.com/10544895/70135000-735c9780-1689-11ea-8f8e-ee29bc4e2065.png)
Maybe add an option here to filter out the checked items?
Keep up the great work!

**Comment by berrnd** [comment]
>  As far as I can tell it has no other function right?

Correct.

> Maybe add an option here to filter out the checked items?

Will do that.
