### ISSUE TITLE
Translations not complete

### ISSUE THREAD

**Issue by llewy** [grocy/grocy#454]
Is there a reason why the dutch (nl_NL) translation isn't completely migrated from Transifex to Github?

![image](https://user-images.githubusercontent.com/525767/70182678-9c5e4600-16e4-11ea-8691-6f3902e89c9d.png)

![image](https://user-images.githubusercontent.com/525767/70182755-c31c7c80-16e4-11ea-8851-20e845f48da1.png)

![image](https://user-images.githubusercontent.com/525767/70182837-ecd5a380-16e4-11ea-9598-dd12bc161e80.png)

**Comment by berrnd** [comment]
I pull all languages which are at least 90 % complete on every release, seems that this was not yet translated 2 months ago when the last release was published.

It's included now / in the next release, see the pre-release demo, which always runs the current master branch and the current translations from Transifex: https://nl.demo-prerelease.grocy.info
