### ISSUE TITLE
default Conversions linking?

### ISSUE THREAD

**Issue by ddecaro** [grocy/grocy#455]
If I have a quantity unit of quart and gallon and define the Default conversions that 1 gallon is the same as 4 Quarts. Should I see that 1 quart is the same as 0.25 Gallons?

have a quantity of Gallon with the factor of 4 for quarts
![image](https://user-images.githubusercontent.com/10151083/70206191-ed216f00-16e3-11ea-857a-3b76d0fa6255.png)

The relationship created in Gallon is not displaying when pulling up quart
![image](https://user-images.githubusercontent.com/10151083/70206308-543f2380-16e4-11ea-9f57-c310b28a5517.png)

Should I create the relationship in Quarts?

**Comment by berrnd** [comment]
The opposite conversion is currently not created automatically, but that's already tracked in #388, so I'm closing this.
