### ISSUE TITLE
Enter shopping with tare and shopping/stock unit conversion

### ISSUE THREAD

**Issue by schattenkrieger** [grocy/grocy#457]
just got grocy installed and entered the first few articles, created my first shopping list and went shopping.
when i came back i wanted to enter my shopping, but could not get it right.

I created for example Sugar with buying as pack and have 1 pack converted to 1000g in the inventory, additionally i activated tare handling and have tare wight set to 9 grams.
My shoppinglist contains 1 Pack of sugar.
when i try to enter it grocy asks for the number of packs but wont accept any number below 10 (apperantly the 9 GRAMS get substracted from the # of Packs)
whatever number i enter is multiplied by 1000 and gets the tare substracted and the result is added as grams to the inventory
for example if i enter 10 packs purchased, i get 9.991 grams of sugar added to the inventory. if i enter any number below 10  grocy complains that the number of packs purchased need to be more then 1
either i am getting someting wrong here, or the tare should be substracted from the amount in stock not the number of units bought

**Comment by berrnd** [comment]
> either i am getting someting wrong here, or the tare should be substracted from the amount in stock not the number of units bought

Sure, you're right - seems to be a form validation bug...
