### ISSUE TITLE
Feature request : db-changed-time return the change

### ISSUE THREAD

**Issue by BlueBlueBlob** [grocy/grocy#461]
Hi,

It could be interesting for refresh through API to have the change or at least the type/table (product, chores, etc..) to know what to refresh :)

Kind regards

**Comment by berrnd** [comment]
That would also require that we track the `row_updated_timestamp` analogue to the `row_created_timestamp` for at least all master data entities (should be no problem)...

**Comment by BlueBlueBlob** [comment]
Should be a good idea. 
Sorry, my lack of sql can not help you or I will make a pull request.
But thx to take care 👍

**Comment by berrnd** [comment]
Similar to #587, this will not be added - see https://github.com/grocy/grocy/issues/587#issuecomment-1364308722.
