### ISSUE TITLE
[request] general collection manager

### ISSUE THREAD

**Issue by charlessteiner** [grocy/grocy#463]
Something like GCstar. Manage everything from books, to DVDs, to shoes and sweaters. 

Item is assigned a category, title, description, location and photo. 
Filter by category and location

List all books (category)

Or list contents of storage container (location)

Or list all books in storage 

mabye tags, too. donate recycle lent_out

**Comment by berrnd** [comment]
This is already possible with Userfields and Userentities.
See #176 and #242.

Maybe the filtering of custom lists by Userfields could be improved, general search works across all fields.
