### ISSUE TITLE
Fearure request: Different currencies

### ISSUE THREAD

**Issue by tedstriker** [grocy/grocy#465]
It would be nice, if the used currency would be configurable. Also the way it is usually displayed is different. 
e.g 
- USD 1.00 or $1.00 for US
- 1,00 Eur or 1,00 € for many European countries

**Comment by jackwilsdon** [comment]
[You can already specify currency on an application level](https://github.com/grocy/grocy/blob/0be1994c029b2dbe9204765dcf5a4d7d804cd5ee/config-dist.php#L33-L37) - are you suggesting adding support for per-item currencies?

**Comment by tedstriker** [comment]
Thanks for your quick reply. I wasn't aware of that configuration as I'm using docker and I thought the only available configuration option would be `culture`
Thanks for clarification.
