### ISSUE TITLE
Feature request: REST API should include user fields

### ISSUE THREAD

**Issue by tedstriker** [grocy/grocy#466]
It would be great tohave  the REST API return user-defined fields as well as the default ones.
I added fields like `manufacturer`, `brand` and `pointofsale` to the products entity, but when testing it via swagger pages `DOMAIN/api#/Generic%20entity%20interactions/get_objects__entity_` those fields are not returned.

**Comment by berrnd** [comment]
There are the API routes `GET/PUT /userfields/{entity}/{objectId}` to retrieve and set userfields.

I think it would not be a good idea to mix and include them in the standard schemas returned by the API (duplicate field names, inconsistent default object entities, ...).

**Comment by tedstriker** [comment]
I got your point. So there have to be two API calls to fetch the complete information.
