### ISSUE TITLE
Feature request: Add fields for nutritional information 

### ISSUE THREAD

**Issue by J-HB** [grocy/grocy#467]
It would be great to be able to add nutritional info to ingredients and to get an overview of your planned intake for a meal and the day. Maybe even with some daily goals.

**Comment by berrnd** [comment]
You can add all missing fields to products using Userfields, see #176.

However, Userfields will not yet get summarized at recipe/meal plan level, but that's already tracked in #413.

The built-in product field for calories gets accumulated at recipe level. Or do you mean that specifically that field should also be summarized for meal plans per day and week?

**Comment by berrnd** [comment]
Feel free to reopen this, if you have specific ideas beyond #413.

**Comment by berrnd** [comment]
>  is it possible to get the userfields to appear in the journal?

Since you explicitly requested my spare time to answer that: No.
