### ISSUE TITLE
Feature Request : Add fields in equipment

### ISSUE THREAD

**Issue by HydrelioxGitHub** [grocy/grocy#468]
This is related with another issue #441 . Equipments could have enhancement fields like handle in which room the equipment is used/stored, date of buy/installation, . I don't if it's better to try to implemented fields one by one or if it's better to do all at once ...

**Comment by berrnd** [comment]
Adding these fields should already be possible by using Userfields, see #176.

#441 is about adding multiple attachments, this is currently not possible with Userfields, primitive fields are possible...
