### ISSUE TITLE
Feature request: Light bulb managment

### ISSUE THREAD

**Issue by dadosch** [grocy/grocy#472]
The new types of light bulbs (mostly LED) often break after a very short amount of time, way less than what was promised they would last.

A bulb has a make ("Marke"), product name, installdate, a faildate, a lamp in which it is installed in, a promised lifespan/amount of switches, a wattage, a socket type (GU10/ E14) etc.

A new category in grocy (I know, I can create user objects) would be useful as then statistics could be generated which bulb from which make lasted longer, etc.

**Comment by berrnd** [comment]
Thanks for the idea.

Maybe using products for that could also work, having more detailed statistics for stock is already tracked in #64.

**Comment by berrnd** [comment]
> A new category in grocy (I know, I can create user objects) would be useful as then statistics could be generated which bulb from which make lasted longer, etc.

Since we can't add every specific thing / use case built-in, Userfields / Userobjects are there for that. If you miss something related to that, feel free to open separate requests for maybe enhancing that in a generic way.
