### ISSUE TITLE
Feature request: Free input field for mealplan

### ISSUE THREAD

**Issue by Jeltel** [grocy/grocy#477]
When we go out (to family or a restaurant) the meal for a certain doesn't need to be filled in. But it is handy to show something there, so that it is clear we do not need to think of something to eat that day.
Just like the note field when adding an item to the shopping list. When you only fill in the note, that gets added to the shopping list.

**Comment by kriddles** [comment]
Hi Jeltel, could you create a recipe called "Eating Out" for now to use?

To expand this as a feature, maybe there could be another selection for Eating Out which could then provide an optional picker list of restaurants to select from which could be either added to the locations table with a new field tagging it or a separate object.

Or even better, an integration with Yelp? It looks like there is an open yelp REST api.

**Comment by Jeltel** [comment]
@kriddles That is an option. But more complicated than I need.

In your solution you indeed cover the restaurants, but for family I need to make a list for every option. And I just want to fill in where I'm going to eat.  Just as a placeholder, so that I know I don't have to think of something that day and don't have to do any shopping.

For now I have a 'pizza' meal without any ingredients. But for the other things now, when I have the mealplan open, I would have to go back to the recipes. Create a 'recipe' like Eating at my Mom, go back to mealplan and select the recipe there. 
I would just want to fill in the title 'eating at my mom' one time and go on with the other days. Also with all empty recipe, the recipe section becomes cluttered.

**Comment by berrnd** [comment]
That's now possible: New option in the dropdown of the add button per day:

![grafik](https://user-images.githubusercontent.com/2161815/73019209-6fe0c380-3e23-11ea-9655-2a87c455c36e.png)

Maybe have a short test on the pre-release demo if this would work for you: https://demo-prerelease.grocy.info/mealplan
