### ISSUE TITLE
Items with different Best before dates in Inventory

### ISSUE THREAD

**Issue by dadosch** [grocy/grocy#478]
Currently, it seems not possible to add the same item multiple times with different Best before dates in inventory, but instead it deletes the ones added before.

**Comment by berrnd** [comment]
When using [/inventory](https://endemo.grocy.info/inventory), you put it the amount which you currently have at home of that product So if you do this multiple times with the same amount (which is not possible by the way through the UI), there is no change in stock at the end.

![grafik](https://user-images.githubusercontent.com/2161815/71309942-383ec000-240e-11ea-863b-4aa618564b57.png)


To add something [/purchase](https://en.demo.grocy.info/purchase) is the way to go.

Is that maybe the problem?

**Comment by dadosch** [comment]
Purchase works fine, but how do I know when I use inventory with product with which MHD is still available? There might be different ones too.

**Comment by berrnd** [comment]
Maybe I don't understand the problem...

I use purchase when I want to add something, so most of the time after I went shopping. The amount entered there is always added.

I use consume when I want to remove something, so when it was used. The amount entered there is always removed.

Inventory I use when I want to correct the grocy stock, so when grocy and the reality are not the same. Based on the amount entered there something is maybe added or removed from stock.

If you maybe mean how the check all the single stock entries for a product (with maybe different best before dates), this is currently only possible/visibile when using consume with the option "Use a specific stock item". #421 added the possibility to show and edit all single stock entries (not yet part of a release).

**Comment by dadosch** [comment]
OK, Ich versuche es mal auf Deutsch:

Im "Inventur" Fenster ist es möglich, ein MHD einzutragen. Wenn man mehrmals die Inventur für das gleiche Produkt mit unterschiedlichem MHD durchführt, wird das erstere gelöscht.

Entweder sollte man dann bei Inventur gar kein MHD angeben können, oder ein einzelnes Produkt sollte eindeutig durch sein MHD sein und dadurch nicht überschrieben werden bei der Inventur (wie man dann allerdings die Differenz zwischen Inventur und Bestand ausgleicht, keine Ahnung?).

**Comment by berrnd** [comment]
Das habe ich soweit schon verstanden, bzw. eben nicht - hier mal als kurzes Screenvideo:
[2019-12-21_17-21-41.mp4.zip](https://github.com/grocy/grocy/files/3991575/2019-12-21_17-21-41.mp4.zip)

- Neues Produkt
- Inventur mit "Neue Menge = 1" und MHD 2019-12-12
- => 1 ist jetzt im Bestand
- Nochmal Inventur mit "Neue Menge = 2" und MHD 2019-12-13
- => 2 sind jetzt im Bestand
- => Mit den beiden angegebenen MHDs, zu prüfen im aktuellen Release eben nur z. B. durch das Dropdown auf der Verbrauch-Seite

Nehme ich beim zweiten Mal dasselbe MHD, ändert das nix, es wird trotzdem 1 hinzugefügt. (Überschrieben werden kann überhaupt eh nix, da intern nur "Purchase" oder "Consume" läuft anhand von ob was dazu kommt, oder nicht. MHD ist von daher auch nur erforderlich, wenn Neue Menge > Bestandsmenge.)

> wie man dann allerdings die Differenz zwischen Inventur und Bestand ausgleicht, keine Ahnung?

Was soll es denn da für eine Differenz geben? Ich mach die Inventur um genau die Differenz zwischen grocy-Bestand und Real-Bestand auszugleichen. Von der Terminologie her nix anderes wie die Inventur im Einzelhandel...

**Comment by dadosch** [comment]
Ahhh, jetztedle, vielen Dank. Ich dachte, die "neue Menge" bezöge sich auf das Produkt, das durch das MHD identifiziert wird. 

Also

[
Inventur mit 
1 x product  2019-12-12
und dann
1 x product 2020-01-01
]


Vielleicht könnte man das deutlicher machen, indem man sagt "Neue gesamte Menge für dieses Produkt" oder die Felder, die nur für hinzugefügte Produkte gelten, zB leicht gelb hinterlegen oder so.

**Comment by berrnd** [comment]
Auf der Inventur-Seite steht jeweils über MHD/Preis/Standort "Dies gilt für hinzugefügte Produkte"...

Vorhandene Bestandseinträge zu bearbeiten ist ab dem nächsten Relase dann auch möglich. Das wäre ja dann die bessere Variante für den Fall, wenn man beim Hinzufügen halt das falsche MHD erfasst hat.

Siehe pre-release Demo: https://demo-prerelease.grocy.info/stockdetail?product=15
(Ist aktuell dort über die Kontextmenüeinträge möglich.)

Aber super, dass sich das dann soweit geklärt hat - dass sich was überschreibt wäre ja sehr blöd gewesen... :D
