### ISSUE TITLE
add purchases via API

### ISSUE THREAD

**Issue by peterPython92** [grocy/grocy#483]
Maybe I don't understand the logic behind the products/entity tables, but is it correct that you cannot add purchases via API ?

I think most people are buying groceries online and would just want to import from the receipt / order confirmation (parsed to JSON of course), rather than manually scanning / typing.

Thanks :-)

**Comment by berrnd** [comment]
Sure you can, the UI also does nearly everything by using the API.

The `products` table holds the products master data, but not the current stock, that's in the `stock` table, which is not directly exposed via the `/objects` endpoints.

Example:
Get a `product_id`, mabye by searching for a product:
`GET` https://demo.grocy.info/api/objects/products/search/Cheese

Use the `/stock/products/{productId}/add` endpoint to add something to stock:
`POST` https://demo.grocy.info/api/stock/products/10/add
```
{
  "amount": 1,
  "best_before_date": "2020-01-19",
  "transaction_type": "purchase",
  "price": "1.99"
}
```
