### ISSUE TITLE
Feature request : add demo mode as env variable

### ISSUE THREAD

**Issue by BlueBlueBlob** [grocy/grocy#484]
Hi :)
Best wishes 2020

I'm trying to run Grocy in demo mode in docker on Travis for testing purpose.

Can you expose it as environment variable and not only a file in data ? Plz :)

Best regards

**Comment by berrnd** [comment]
Makes sense to handle this as a "normal" setting, don't know why I did this via checking the existence of a file...

So demo mode is now enabled when `MODE` is set to `dev`, `demo` or `prerelease`. All settings can also be set via environment variables (`GROCY_MODE`).

**Comment by BlueBlueBlob** [comment]
Thx a lot ! 😻
