### ISSUE TITLE
Question : can we grab the pre-release version ?

### ISSUE THREAD

**Issue by BlueBlueBlob** [grocy/grocy#485]
Hello again.

I think it's more a GitHub question but I did some research, I'm not sure.

I don't speak about source code ;)
But the zip file you are using for https://demo-prerelease.grocy.info/

Can I download it without you have to do anything ?

Kind regards

**Comment by Niko9911** [comment]
There isn't "readyToGo" sources for preview, however you can clone the master and then run composer & npm in the root of this project to build sources.

**Comment by BlueBlueBlob** [comment]
Thx for information. I will wait next release :)
And thx again to take care about our questions/issues :)

**Comment by berrnd** [comment]
> There isn't "readyToGo" sources for preview, however you can clone the master and then run composer & npm in the root of this project to build sources.

Yes, that's the case (thanks!) - I update the-prerelease demo automatically with this script:
```sh
git reset --hard
git pull
yarn install
composer install
tx pull --all --minimum-perc=80 --force
```

But please don't use it for "production", I only care that database migrations work between releases, not between every commit.

**Comment by BlueBlueBlob** [comment]
Thx for commands to run.
It's for dev purpose, I will not complain about :)

And thx all to answer and help 👍
