### ISSUE TITLE
Little stock API refinements

### ISSUE THREAD

**Issue by jglauche** [grocy/grocy#488]
For a my interface I am writing I need some kind of way to update the stock database directly. My motivation is to update the best_before_date of items without having to remove the item from stock and entering it again.

For my application I hacked it into the api:

```
diff --git a/grocy.openapi.json b/grocy.openapi.json
index eb6a246..199247b 100644
--- a/grocy.openapi.json
+++ b/grocy.openapi.json
@@ -2858,7 +2858,8 @@
                                        "userfields",
                                        "userentities",
                                        "userobjects",
-                                       "meal_plan"
+                                       "meal_plan",
+                                       "stock"
                                ]
                        },
                        "ExposedEntitiesPreventListing": {
```

This is probably not the best solution as this does not touch the stock_log table.

**Comment by jglauche** [comment]
.. I should have checked master branch, this was already merged into.

**Comment by berrnd** [comment]
This was all introduced by the huge amount of changes of #421 (not yet released).

But I think exposing the `stock` table directly was not intentional, and is also not necessary (and maybe dangerous) - there is the new endpoint `PUT /stock` to update stock entries, which then handles journal updates for every change.

We should check/undo that, maybe also renaming to new endpoint to something like `PUT /stock/{entryId}` would be better. I'll reopen this to track that here.

//CC @kriddles

**Comment by jglauche** [comment]
Sounds reasonable. Maybe related, there's an inconsistency with the stock api: When querying 
/stock/products/{productId}/entries
, you get an array with Stock items that have an "id" element. However, the PUT /stock/ api in master requires you to submit "stock_row_id"

**Comment by kriddles** [comment]
Ok I'll take a look at removing the stock access and updating the endpoints.

**Comment by kriddles** [comment]
> Sounds reasonable. Maybe related, there's an inconsistency with the stock api: When querying
> /stock/products/{productId}/entries
> , you get an array with Stock items that have an "id" element. However, the PUT /stock/ api in master requires you to submit "stock_row_id"

I updated the "stock_row_id" to be named "id" for the put requirement

**Comment by berrnd** [comment]
Done by #493.
