### ISSUE TITLE
Buying product in shopping list does not remove it from shopping list

### ISSUE THREAD

**Issue by BlueBlueBlob** [grocy/grocy#497]
Hi :)

Not sure if it's a bug. But when I buy a product from shopping list, it remains in shopping list.

Is it the regular behavior ? Btw I do it trough web UI, not API.

Kind regards

**Comment by berrnd** [comment]
I get's only automatically removed when you add from the shopping list by using that button:

![firefox_2020-01-17_18-16-48](https://user-images.githubusercontent.com/2161815/72631984-a2874980-3955-11ea-9b16-bca749115f28.png)

If you want to have it removed always (somehow configurable), feel free to reopen this.

**Comment by BlueBlueBlob** [comment]
> It get's only automatically removed when you add it from the shopping list by using that button:
> 
> ![firefox_2020-01-17_18-16-48](https://user-images.githubusercontent.com/2161815/72631984-a2874980-3955-11ea-9b16-bca749115f28.png)
> 
> If you want to have it removed always (somehow configurable), feel free to reopen this.

It is what I do, but the pop-up window doesn't close itself after buying.

Certainly my browser or my system taking too long.

I will open an issue if it seems to not be on my side/config.

Thanks again :)
