### ISSUE TITLE
Feature Request: Meal planning summary

### ISSUE THREAD

**Issue by DellanX** [grocy/grocy#502]
Meal plan is awesome; however, I still feel like I'm doing some manual work.

It'd be nice to see some summary info, such as total cost and total calories per planned day.

For my use case, I'm adding recipes to the meal plan until it reaches my target calories for the day.
Seeing the per serving cost is pretty awesome, but it leaves me wondering what the total cost is.

**Comment by berrnd** [comment]
Did that now, in the header of the day column:

![grafik](https://user-images.githubusercontent.com/2161815/72845617-4e56cf00-3c9f-11ea-851a-284e3185c579.png)
