### ISSUE TITLE
Feature Request: Statistics on how much food goes to waste

### ISSUE THREAD

**Issue by teitrand** [grocy/grocy#504]
I'd love to se some statistics on how much food goes to waste, and some functions to help reducing waste. Maybe get grocy to propose meals from the list of soon expiring food.

**Comment by berrnd** [comment]
Statistics about everything are also my personal wish since ever... :)

I added this to #64.

**Comment by berrnd** [comment]
And just to note it here: The "Spoil rate" is already there on the productcard (% per product that was spoiled).
