### ISSUE TITLE
Feature Request: make it easier to add recipies. Recipies sharing/database

### ISSUE THREAD

**Issue by teitrand** [grocy/grocy#505]
It is a pain in the butt to add recipies. Maybe a integration with a recipie service or a common database of recipies/products would make it simpler? If all recipies were stored to a database that were common to users you could make proposals to help reduce food waste, tip-of-the-day, share recipies and such..

**Comment by berrnd** [comment]
Please search existing issues first, there is #210, #451, #445 and #158 about this or related points. And there is also mentioned why this is maybe technically not so easy. But as always: Working ideas or solutions are very welcome.
