### ISSUE TITLE
api_keys cannot be listed, but is shown in the dropdown of possible entities on the Swagger UI

### ISSUE THREAD

**Issue by rsxaeon** [grocy/grocy#510]
A call to api/objects/api_keys returns:
`{
  "error_message": "Entity does not exist or is not exposed"
}`

**Comment by berrnd** [comment]
What the error message says - (listing of) `api_keys` (and `users`) is not exposed for security reasons.

For users there are specific endpoints in the ´/users` group.

What would you need for `api_keys` to do via the API?

**Comment by rsxaeon** [comment]
Apologies, I was just starting to examine the application to integrate it with a front end I have that integrates with several platforms and was under the assumption that certain portions would have more ownership based input (e.g. api calls to mark a task complete would need to include an api key specific to the user that completed the task) but I see now that I can simply use a single key for all users.  Is there a reason it is listed in the documentation if it is disabled?

**Comment by berrnd** [comment]
Ok, no problem. :)

The OpenAPI-Definition (grocy.openapi.json) is also partly used to validate requests, so this is not intentional, `api_keys` is listed because all other "generic entity interactions" are allowed, only listing if forbidden - I'll try to improve it...
