### ISSUE TITLE
debounce search input

### ISSUE THREAD

**Issue by vrih** [grocy/grocy#515]
Every character input to the search box causes a complete search of the table. This is particularly problematic when deleting characters from the search box as each render will be longer after a character deletion.

The input in the search box should be debounced to sensibly minimise the number of times the full data table is processed.

**Comment by vrih** [comment]
Apologies. Have seen that you've already implemented this but haven't put into a release yet. Any chance of doing a release sometime soon because this is fairly important on mobile performance for me.

**Comment by berrnd** [comment]
No problem, also didn't remember that this is already done... :)

We try to finish and test the latest bigger changes currently and have planned to drop the next release next friday or saturday.
