### ISSUE TITLE
Product sort and save recipe

### ISSUE THREAD

**Issue by kriddles** [grocy/grocy#520]
I noticed that on the Recipe Edit page the product dropdown is not sorted by name. In the recipe controller products is ordered by name. Is the list coming from somewhere else?

Also, it does look like a save recipe is needed when adding an ingredient. I updated a recipe serving amount and added an ingredient. This forced a reload which cleared the serving amount I had entered.

**Comment by berrnd** [comment]
> I noticed that on the Recipe Edit page the product dropdown is not sorted by name. In the recipe controller products is ordered by name. Is the list coming from somewhere else?

No, no different source - but I cannot see this on the demo... (?)
You mean that page: ?
https://demo-prerelease.grocy.info/recipe/5/pos/14?embedded&product=2

> Also, it does look like a save recipe is needed when adding an ingredient. I updated a recipe serving amount and added an ingredient. This forced a reload which cleared the serving amount I had entered.

Yes, so we should make sure to save the recipe before any reload by `recipeform.js`...

**Comment by kriddles** [comment]
This page for the produces product dropdown
https://demo-prerelease.grocy.info/recipe/5

**Comment by kriddles** [comment]
This page for the produces product dropdown
https://demo-prerelease.grocy.info/recipe/5

**Comment by berrnd** [comment]
Ok, both should be now fixed by the two commits referenced above.
