### ISSUE TITLE
Slovak translation > 90 % finished but missing in demo

### ISSUE THREAD

**Issue by jose1711** [grocy/grocy#524]
https://demo-prerelease.grocy.info/stockoverview does not list Slovak as a language despite Slovak translation more than 90 % complete (https://www.transifex.com/grocy/grocy/language/sk_SK/).

**Comment by berrnd** [comment]
Yes, was just adding it as I noticed that it's almost ready, thanks for translating grocy! :)

Pre-release demo is now available: https://sk.demo-prerelease.grocy.info/

**Comment by berrnd** [comment]
Sure - will be done when the next release is ready, so on friday or saturday.
