### ISSUE TITLE
Unit pricing avg 

### ISSUE THREAD

**Issue by kriddles** [grocy/grocy#529]
Based on this article and reddit
https://twocents.lifehacker.com/keep-a-list-of-benchmark-prices-for-regular-groceries-1841326895/amp

https://www.reddit.com/r/povertyfinance/comments/ev70qe/keep_a_list_on_you_with_benchmark_pricing_for/

There could be something interesting to see either average unit cost along with the most recent price in the shopping cart.

**Comment by berrnd** [comment]
Haven't read the links, but we already have the price history chart in the productcard...

**Comment by kriddles** [comment]
> Haven't read the links, but we already have the price history chart in the productcard...

That's true, but in shopping cart mobile view the only way to see the product card is by clicking edit on the product correct?
Perhaps adding the last price as a column could be useful just to see if the purchase price is a good deal. If the price is drastically higher then maybe need to go to another store or buy the none name brand item.

**Comment by berrnd** [comment]
Yes, good idea - or a general to configure which columns to show where, maybe DataTables has a way to do this (client side)...

**Comment by gersilex** [comment]
If I understood the article correctly it recommends comparing the per-unit pricing - that is `Price per 100 grams` or `Price per Liter`. This could actually come in handy and could be computed using the conversion and purchase/stock conversion ratios. 

Sometimes you don't purchase in the same unit like the unit pricing displays (A bottle of olive oil might have different sizes, but it's always compared by a unit of Liters), so we might also need to somehow mark what the correct unit pricing unit is.

**Comment by MattiasDreger** [comment]
I would love to have price per gram (or other unit) listed or shown on the history graph! For example if one bag of chips is $5 and another is $6, it means nothing to me unless I can compare by weight even though I'm purchasing 1 bag of either - and consuming them 1 bag at a time.

**Comment by berrnd** [comment]
The unit and total price is now shown on the shopping list (new column, hidden by default, ref #1058).

That price is also related to the quantity unit selected for the shopping list item (any product related unit can now be used anywhere, ref #1015).
