### ISSUE TITLE
Recipe variable amount display denotation

### ISSUE THREAD

**Issue by kriddles** [grocy/grocy#530]
The variable amount is not updated based on changing the serving size of a recipe so in the future I may forget that it's a variable amount.

When using the variable amount to override an ingredient value, it would be useful in the ingredient list to denote that this is a variable amount override to help me remember.

**Comment by berrnd** [comment]
Is now rendered like that:

![grafik](https://user-images.githubusercontent.com/2161815/73611580-73263d00-45e3-11ea-9f1c-ffe7b810e937.png)
