### ISSUE TITLE
Option to hide the calendar on the shopping list

### ISSUE THREAD

**Issue by kriddles** [grocy/grocy#531]
Just a question on what you use the calendar for on the shopping list?

It doesn't provide any functionality does it?

**Comment by berrnd** [comment]
Self-quote from [here](https://www.reddit.com/r/grocy/comments/erig41/new_user_multiple_questions/):

> It does nothing, I personally just find it handy to have it there ... it's most about fresh products ... to quickly check in which week the best before date is ... nobody complaint about to hide that since grocy 1.0... :D

Maybe we should add an option to hide it...

**Comment by kriddles** [comment]
Ah, someday I'll join reddit...

Yes, I think a hide would be nice just because it takes up a lot of real estate

**Comment by berrnd** [comment]
Ok, I changed the title of this issue to track this here.
