### ISSUE TITLE
Bug: (v2.6.0) Consuming fails with FEATURE_FLAG_STOCK_LOCATION_TRACKING set to false

### ISSUE THREAD

**Issue by gersilex** [grocy/grocy#532]
When the Setting `FEATURE_FLAG_STOCK_LOCATION_TRACKING` is set to `false`, the consume, inventory, purchase and probably more endpoints use `1` from a hidden field for the `location_id`.

`/consume` fails with a `400 Bad Request` `Location does not exist`

It fails even if a location is present for the stock item, so this problem comes from the FEATURE flag. It was introduced with the latest release v2.6.0.

I have attached a Network-Tab Dump from the Chrome DevTools. Please let me know if this is a good way of sharing issues and related data.

[grocy.zip](https://github.com/grocy/grocy/files/4140069/grocy.zip)

**Comment by gersilex** [comment]
It looks like the `/consume` endpoint actually checks the `location_id` while the requests just send `1` as ID and do not expect it to be checked. A possible solution might be to disable the checks when POSTing to `/consume`, too.

**Comment by berrnd** [comment]
> I have attached a Network-Tab Dump from the Chrome DevTools. Please let me know if this is a good way of sharing issues and related data.

For me a short description how to reproduce the problem is enough, but many thanks! :)
