### ISSUE TITLE
Enhancement: Recipe Ingredients: Choose "single unit in stock checkbox" before "amount" and "quantity unit"

### ISSUE THREAD

**Issue by gersilex** [grocy/grocy#533]
Please have a look at this:
![image](https://user-images.githubusercontent.com/2018039/73581129-8a9ce300-4488-11ea-8962-cfef5d4a1c99.png)
I track my Toast as "Packs" instead of counting individual slices. When creating recipes and adding ingredients to it, my typical workflow is to 

1. Choose the product
2. Press TAB repeatedly to skip to `2` and check the checkbox
3. Press SHIFT+TAB repeatedly to go to `3` and enter the amount
4. Press TAB and choose a friendly quantity unit
5. Press TAB repeatedly and continue with the other fields

As you can see, there is a twist and I would like to suggest swapping `2` and `3` by effectively moving it `light green` to the position above `amount` and `quantity unit` `dark green`.

What do you think? Is this an improvement or am I super weird by not tracking slices? :grin:

**Comment by berrnd** [comment]
Makes sense, haven't had that problem so far, as `FEATURE_FLAG_RECIPES` is set to `false` in my personal grocy instance (yes, shame on me)... :D
