### ISSUE TITLE
Is Freezer Error

### ISSUE THREAD

**Issue by schildgenb** [grocy/grocy#534]
When I go to update a location or add a new one that is a freezer I get the below Error:
"{\"error_message\":\"SQLSTATE[HY000]: General error: 1 no such column: is_freezer\"}"

**Comment by berrnd** [comment]
After you have updated, you have to visit the root route (`/`, click the grocy icon in the left upper edge) - only on that route database migrations are executed, as [mentioned in README](https://github.com/grocy/grocy#database-migrations). And of course this only works when you update between release, maybe not when you directly use/used the master branch at any time.
