### ISSUE TITLE
UI-Bug: Recipe Ingredients: "Only check if a single unit is in stock" breaks quantity conversions

### ISSUE THREAD

**Issue by gersilex** [grocy/grocy#535]
Hi. This is really hard to describe. I select the `Only check if a single unit is in stock` checkbox and choose any fitting quantity unit and the quantity and save.

If I re-open the ingredient popover and if (and only if) the quantity unit I chose has no conversion to the product's main quantity unit, jquery-ui fails the conversion with `The specified value "NaN" is not a valid number. The value must match to the following regular expression: -?(\d+|\d+\.\d+|\.\d+)([eE][-+]?\d+)?` and the quantity field stays empty. Also the quantity units are wrong as the dropdown only display the quantities with known conversions.

I've compiled a short recording of the issue: https://youtu.be/kSPJZjXCIFU (sorry, too big for a GIF even without colors and 5 fps)

As soon as I disable and enable the checkbox, all of the options are available again.

**Comment by berrnd** [comment]
Thanks, will try to reproduce it (we also finally need #395 to share such more "complex" scenarios easier)...

**Comment by berrnd** [comment]
I think the commented out part at the end of `recipeposform.js` was the only problem...

Maybe you can have a short test again on the pre-release demo.

**Comment by gersilex** [comment]
The quantity is correct now, but the quantity unit is always the first unit in the dropdown. I also can't find it in the `GET /api/stock/products/19`

![GIF 01 02 2020 20-28-02](https://user-images.githubusercontent.com/2018039/73597922-d3f53d00-4531-11ea-88d9-b55150c72ece.gif)

**Comment by berrnd** [comment]
Thanks for testing, should now also work.
