### ISSUE TITLE
New Recipe Creation with db change event?

### ISSUE THREAD

**Issue by kriddles** [grocy/grocy#536]
I'm not clear what happened but I think I left Grocy open on the create new recipe screen and stepped away from the computer. I think the db change refresh occurred and it created a new recipe with a new row_created_timestamp?

I cleaned them up in the db, but I couldn't imagine going through and deleting each one.

![image](https://user-images.githubusercontent.com/54413450/73595603-45a49b00-44e0-11ea-9701-031f148fa873.png)

**Comment by berrnd** [comment]
Good find - the `/recipe/new` page creates a new recipe on load (mainly because for adding ingredients a `recipe_id` is already needed), so reloading that page will creating a new recipe on each reload...
