### ISSUE TITLE
Bug: Shopping List: "Shopping list to stock workflow" doesn't respect FEATURE_FLAG_STOCK_BEST_BEFORE_DATE_TRACKING

### ISSUE THREAD

**Issue by gersilex** [grocy/grocy#537]
I am not sure if this is the source of the problem, but it seems that the workflow does neither work nor flow if a product without a default best-before duration gets added. I have `FEATURE_FLAG_STOCK_BEST_BEFORE_DATE_TRACKING` set to `false` and was really wondering why the workflow just stops at some items. Didn't find anything interesting in `purchase.js`. 

It seems to consistently happen to products with a `default_best_before_date` of `0`. As the feature is disabled, I have no input field to enter the date, but clicking OK manually works.

In the following example, the first product "Halloumi" is the only product with a  `default_best_before_date` of `0`:

![GIF 01 02 2020 20-12-42](https://user-images.githubusercontent.com/2018039/73598380-e96d6580-4537-11ea-839e-6d5558dde604.gif)

Sorry for the German language of my local installation. I'm not able to set feature flags on the demo instance, obviously. The console don't show any relevant errors and the API calls look right.

**Comment by berrnd** [comment]
Thanks for noticing that, the main problem was only that the workflow was triggered in the wrong if block in `purchase.js`...
