### ISSUE TITLE
User documentation missing

### ISSUE THREAD

**Issue by jose1711** [grocy/grocy#538]
Currently all the documentation is developer/admin-oriented. To me it does not have to be super-detailed but for instance .. a few words about battery management would be nice. Like.. how to find out the proper length of charge cycle for NiMH or how to avoid alkaline batteries leaking. Or describe a difference between task and chore.

**Comment by gersilex** [comment]
We are aware of that and are tracking user documentation in #365

I already wanted to start it but had too much personal stuff going on in the last few months.

**Comment by jose1711** [comment]
#365 is said to be an installation guide, this idea behind this issue is a guide for less technical users that do not install nor configure `grocy`.

**Comment by berrnd** [comment]
Let's track this topic in #365, I will change the title to include general user documentation.
