### ISSUE TITLE
Possible typo in hint

### ISSUE THREAD

**Issue by jose1711** [grocy/grocy#542]
Should not this say "1 week"?

https://github.com/grocy/grocy/blob/ba6bfa6a2c77ac1673996efc847c9877937efc7c/public/viewjs/choreform.js#L147

**Comment by berrnd** [comment]
Depends on how you understand it... :)

It's scheduled 1 day after the last execution, but if that weekday is not in list of selected weekdays, it will be on the next selected weekday. If you select all weekdays, then it would be scheduled daily.
