### ISSUE TITLE
Add recipe via api

### ISSUE THREAD

**Issue by OmgImAlexis** [grocy/grocy#544]
I've looked in the swagger docs and I couldn't find any way of adding a recipe. Did I miss something or is this not a feature yet?

**Comment by berrnd** [comment]
It's possible via the "Generic entity interactions" routes, example:

`POST https://demo.grocy.info/api/objects/recipes`
```json
{
  "name": "New recipe xy",
  "description": "asfsfsfsf"
}
````

Response:
```json
{
  "created_object_id": "8"
}
````

Adding an ingredient:
`POST https://demo.grocy.info/api/objects/recipes_pos`
```json
{
  "recipe_id": 8,
  "product_id": 2,
  "amount": 2
}
````
