### ISSUE TITLE
View Recipes on Mobile with large recipe list

### ISSUE THREAD

**Issue by kriddles** [grocy/grocy#547]
If I have a long list of recipes and viewing them on my phone, when I select a recipe then I have to scroll way to the bottom of the recipe list to see the recipe card.

What ideas could be done to help this?
1. Can you set it to if on mobile it opens up the recipe card to full screen when selected?
2. Should the Recipe Card be at the top of the recipe list on mobile?
3. Could the recipe list be hidden with a button?

I lean toward 1. if possible.

**Comment by berrnd** [comment]
1 should be possible, or maybe just scroll to the recipe card after selecting a recipe (always, so would do nothing on desktops when the card is already in view).

Like it's done for the active menu item:
https://github.com/grocy/grocy/blob/06fe308f3179f4afc3abb85261fd0bc4060d02d0/public/js/grocy.js#L279-L282
