### ISSUE TITLE
[HASSIO] curl post to update the stock

### ISSUE THREAD

**Issue by yorchtf** [grocy/grocy#559]
I can not register in grocy api:

I have tried the next queries:

1. Query: 
``` 
curl -X POST \
-H "Authorization: Bearer TOKEN-KEY-HASSIO" \
-H "Content-Type: application/json" \
-H "accept: application/json" \
-u <user_grocy>:<passwd_grocy> \
-d "{\"amount\":3,\"transaction_type\":\"consume\",\"spoiled\":false}" \
"https://<endpoint_hassio>:8123/api/hassio_ingress/rAxPRtNqbnVNLiTXxV1_pSTM6YeCUTU7ZE9FDXYodIc/api/stock/products/4/consume"
```

**Return**: 401: Unauthorized

2. Query: 
```
curl -X POST \
-H "Authorization: Bearer TOKEN-KEY-HASSIO" \
-H "Content-Type: application/json" \
-H "accept: application/json" \
-H "GROCY-API-KEY: TOKEN-KEY-GROCY" \
-d "{\"amount\":3,\"transaction_type\":\"consume\",\"spoiled\":false}" \
"https://<endpoint_hassio>:8123/api/hassio_ingress/rAxPRtNqbnVNLiTXxV1_pSTM6YeCUTU7ZE9FDXYodIc/api/stock/products/4/consume"
```

**Return:** 401: Unauthorized

Could you help me?

**Comment by berrnd** [comment]
I think this must be an error before the request is reaching grocy, as long as the header `GROCY-API-KEY` contains a valid API key and reaches grocy. But sorry, I don't use and therefore anything about the Home Assistant integration...

To check if it's an error on grocy side, please always try to reproduce it on the official demo instance.

So probably https://github.com/hassio-addons/addon-grocy or https://community.home-assistant.io/t/community-hass-io-add-on-grocy/112422 is the better place to get help about that...
