### ISSUE TITLE
Sub Recipes Weekly Meal Plan Quantities Wrong for Consume and Add to Shopping Cart

### ISSUE THREAD

**Issue by kriddles** [grocy/grocy#562]
I've not detailed this out further other than I noticed the nested recipes positions may be computing the incorrect quantity values I think due to the recipes_nestings_resolved.

**Comment by berrnd** [comment]
I played a little bit with that topic and found no problems...

Only noticed the known thing the the client/server locale needs to be the same, otherwise maybe which days a week recipe includes are not the same.

Feel free to reopen this if you find a reproducible problem.

**Comment by kriddles** [comment]
Thanks for checking it out, I'll see if I can reproduce what I saw.
