### ISSUE TITLE
Meal plan JavaScript error? invalid currency code in NumberFormat()

### ISSUE THREAD

**Issue by hannahswain** [grocy/grocy#563]
When trying to add a meal, product, or note to the meal plan, nothing happens. On checking the console, there's a JavaScript error: `RangeError: invalid currency code in Numberformat(): $`

![firefox_yYQxCMEu9p](https://user-images.githubusercontent.com/17844465/74365738-f52a1900-4dce-11ea-837d-c7dae1961471.png)

I've tested this a few times in the past and seen the same behavior, but was hoping it was fixed in recent versions. When testing today, I was able to initially add one recipe. However, after testing further in Brave (Chrome-based) and in Firefox, I could not add an item and saw the same console error. 

Interestingly, the same recipe is showing up even when changing the date:

![RKcCgeT5cW](https://user-images.githubusercontent.com/17844465/74365921-4df9b180-4dcf-11ea-9a10-19b2dc8b7695.gif)

What could be going wrong here?

**Comment by berrnd** [comment]
I can reproduce this when the setting `CURRENCY` is set to `$`:
https://github.com/grocy/grocy/blob/5dd78aa19a1f79d916f1ef9f6bb57cce6f998caa/config-dist.php#L34-L38

As noted in the comment there, this should be the ISO4217 currency code, as the JS function `toLocaleString` expects that...

https://developer.mozilla.org/de/docs/Web/JavaScript/Reference/Global_Objects/Number/toLocaleString#Parameter

https://en.wikipedia.org/wiki/ISO_4217#Active_codes

**Comment by hannahswain** [comment]
Thank you for tracking this down!

It looks like I have an outdated config file, as this is the description:

```
# To keep it simple: grocy does not handle any currency conversions,
# this here is used to format all money values,
# so can be anything (e. g. "USD" OR "$", doesn't matter...)
```

Updating from Setting('CURRENCY', '$'); to Setting('CURRENCY', 'SEK'); solved the problem. 

Updating the config file also helped, given that it's a docker installation.
