### ISSUE TITLE
Lock parent product for purchases

### ISSUE THREAD

**Issue by hannahswain** [grocy/grocy#564]
I would like to be able to disable parent products so that they can't be purchased. 

Example:

* Salami (parent product)
* Percy's salami
* Magnifico
* Percy's Milano salami

I can purchase the parent salami product, which takes away the detail of the child product. For example, if I buy both magnifico and milano salami, I'd like to make sure both are registered and that nothing ends up under the generic salami product.

In the product purchase dialog, would it be possible to either grey out parent products so they aren't selectable, or hide them all together? And even better, to have this option per parent product, i.e. `allow purchases`?

**Comment by hannahswain** [comment]
This might cause trouble on the shopping list. When you have "Salami (parent product)" as the shopping list item, click on "add to stock", the product name is prefilled. There would need to be a UI check to alert if a product isn't available or can't be selected.

**Comment by Saturo78** [comment]
In this case after click on "add to stock" the product Name could be empty. So you can see that you have to pick a child product.

**Comment by Saturo78** [comment]
I also think a parent product should not have a "Factor purchase to stock quantity unit". This option should only be set on child products.

**Comment by berrnd** [comment]
There is now the following new product option for that:

![grafik](https://user-images.githubusercontent.com/2161815/161307549-d8e4557c-c13b-48a9-816b-4aa5c6b7dfe7.png)
