### ISSUE TITLE
flexible table design under stock, stock entries and location content sheet 

### ISSUE THREAD

**Issue by Wit4r7** [grocy/grocy#569]
Hello, 

I would appreciate it very much if you had the possibility to adjust the displayed information in the table. 

When you create a new product, you have the possibility to add some additional information (energy (kcal), product group, etc.) 

The information will not be displayed anywhere after that. 

I am interested in how much total energy the stored food has? I Use Grocy for planning camping holidays or trekking tours. Therefore such a function would be great. 

Alternatively, it would also be sufficient to display the information on the "Print location sheet". 

best regards
wit4r7

**Comment by jokerjoe** [comment]
Would greatly appreciate this, the main reason I want to use Grocy is to accurately assess how many days of food I have for my family during this crisis.

**Comment by berrnd** [comment]
Hiding columns is now possible, additionally the calories and product group fields have been added to the stock overview page (hidden by default), see #1058.

If you have requests to add more built-in fields on some other tables, feel free to just open separate issues.
