### ISSUE TITLE
Option to duplicate product

### ISSUE THREAD

**Issue by hannahswain** [grocy/grocy#571]
Add an option in the `Manage master data > Products` view to duplicate an existing product. 

In terms of UI, a duplicate/copy button next to the edit and delete buttons would be great:

![Screen Shot 2020-02-17 at 12 45 42](https://user-images.githubusercontent.com/17844465/74651155-80b2f980-5183-11ea-85e6-ee5fe0dbc917.png)

In terms of behaviour:

1. Click the copy/duplicate button
2. All settings (including name, parent product, image, etc) are copied over to the new product template. 
3. User can edit the settings and then save to create the new product.

Use case: I usually buy 500g of butter but realize we haven't been eating it all before it expires. I'd like to buy 250g instead - it's nearly the same product except for different barcodes and a slightly different title. 

Somewhat related to #567.

**Comment by fduchatelet** [comment]
Hi, I just discovered Grocy and I find it great.

But creating the initial list of products is just a PIA. Cloning/Duplicate product would be very helpful.
