### ISSUE TITLE
Meal plan > copy to date

### ISSUE THREAD

**Issue by hannahswain** [grocy/grocy#573]
In the meal plan > day drop down, add an option "copy to date". 

![Screen Shot 2020-02-17 at 13 22 44](https://user-images.githubusercontent.com/17844465/74653523-9e369200-5188-11ea-978e-cda8d864ea2a.png)

There would need to be an option to choose the day/date (maybe a calendar picker?). All information on the meal plan would be copied to the selected date, appending it to whatever information is already on that date.

Use case: I made a meal plan, but we had pizza that night instead. That food still needs to be eaten and it would be easier to copy over the day that's already set up rather than manually recreate the day.

**Comment by berrnd** [comment]
This took quite long ... but now there is an option to copy a day to another one: :)

![grafik](https://user-images.githubusercontent.com/2161815/125344316-6de02c80-e357-11eb-899d-623a9b0e049f.png)

**Comment by hannahswain** [comment]
Lovely, thank you!
