### ISSUE TITLE
Feature request: API to delete all data

### ISSUE THREAD

**Issue by smhgit** [grocy/grocy#576]
One API calll that can delete and reset grocy data.

**Comment by kriddles** [comment]
Do you mean to reset the database completely or do you have specific data you want to manage?

While there is no current api call, you can just delete or rename the database found in your /data folder. A new one would then be built by either clicking the "Grocy" icon or starting at the Grocy login screen.

**Comment by smhgit** [comment]
@kriddles reset the database.

Do you mean grocy.db? if so than for me it is ok, although I think API will still be a nice addon.

**Comment by kriddles** [comment]
> @kriddles reset the database.
> 
> Do you mean grocy.db? if so than for me it is ok, although I think API will still be a nice addon.

Yes, just rename grocy.db if you want to keep it as a backup

**Comment by shadow7412** [comment]
Presumably, as part of this call you'd also lose user information and API keys - so you'd only be able to call it once...

I can't see how this would be helpful - maybe you could elaborate on your use case?

**Comment by smhgit** [comment]
@shadow7412 I agree that maybe there is no strong use case here. As I am currently in development stage of my env., I am doing changes to the data I am putting in Grocy and it easier for me in some cases to delete all.

As long as I can delete the db and get the same result, I can assume you can close this feature request.

**Comment by berrnd** [comment]
I also think that deleting the database file is enough, that's also how the demo instances are reset multiple times per day...
