### ISSUE TITLE
Feature request (API): search object by other fields

### ISSUE THREAD

**Issue by smhgit** [grocy/grocy#577]
Currently search support only name. Will be helpful if it will support other (any) fields.

Use case: I want to get all items in shopping list which belongs to specific shopping list id.

**Comment by berrnd** [comment]
That's now possible, excerpt from the changelog:

> - The output of the following endpoints can now be filtered (by any field), ordered and paginated (thanks @fipwmaqzufheoxq92ebc)
>   - `/objects/{entity}/search`
>   - `/stock/products/{productId}/entries`
>   - `/stock/products/{productId}/locations`
>   - `/recipes/fulfillment`
>   - `/users`
>   - `/tasks`
>   - `/chores`
>   - `/batteries`
>   - There are 4 new (optional) query parameters to use that
>     - `order` The field to order by
>     - `limit` The maximum number of objects to return
>     - `offset` The number of objects to skip
>     - `query[]` An array of conditions, each of them is a string in the form of `<field><condition><value>`, where
>       - `<field>` is a field name
>       - `<condition>` is a comparison operator, one of
>         - `=` equal
>         - `~` LIKE
>         - `<` less
>         - `>` greater
>         - `>=` greater or equal
>         - `<=` less or equal
>       - `<value>` is the value to search for
