### ISSUE TITLE
Feature request: hide / remove the compact / normal mode button

### ISSUE THREAD

**Issue by smhgit** [grocy/grocy#578]
I am doing some integration of grocy to home assistant. In addition to HA UI (lovelace) I would like also the ability to see shopping list via the grocy interface (using iframe panel).
The compact view is a good step towards this target (see image) although it is still not perfect:

1. Can the normal view button be moved to another place (not on top)
2. Remove calendar
3. Items list to fill the full width of the screen

![image](https://user-images.githubusercontent.com/10852598/75116726-e3206400-5673-11ea-9b25-b1bdf189d7db.png)

**Comment by berrnd** [comment]
2. and 3. is already done, but not yet released - see the [pre-release demo](https://demo-prerelease.grocy.info/shoppinglist#compact).

For 1:
Maybe use [custom JS/CSS](https://github.com/grocy/grocy#adding-your-own-css-or-js-without-to-have-to-modify-the-application-itself) to maybe completely hide it for your case. (?)

**Comment by smhgit** [comment]
Using CSS might be an option although I am not expert in that and probably so others.

I suggest to consider adding toggle option for compact mode in the settings.

**Comment by berrnd** [comment]
What would be best for your use case -  remove the button and always use compact mode, move it to the bottom of the page, ... (?)

**Comment by smhgit** [comment]
The goal is that the UI will fit nice in mobile device. So, basically, compact mode should be the mode when the UI is viewed from mobile. If there is an automatic mode to detect it, better. IN that case, I don;t want to see the compact mode, even in the bottom.
If auto detection is not possible, than global option is ok for me, and last but not preferred  option is to have it in the bottom.

**Comment by berrnd** [comment]
It already switches automatically to compact mode on loading the page when the screen width is < 768 px...

I'll think about it, without any possibilty to leave compact mode it would be not possible to navigate to any other page...

**Comment by smhgit** [comment]
For my use case, I only want to see the list. Is it possible maybe to define a URL which will be in compact mode?

**Comment by berrnd** [comment]
Already possible and visible (the URL get's updated when switching from/to compact view: https://demo-prerelease.grocy.info/shoppinglist#compact

**Comment by smhgit** [comment]
But I assume I still see the button. BTW, I also see that there is notes bar in the bottom.  This is something I would also want to hide ... (only for mobile devices)

![image](https://user-images.githubusercontent.com/10852598/75371598-b9fc0f80-58cf-11ea-8536-59192429de2b.png)

**Comment by berrnd** [comment]
Closing this for now.

Really individual customizations can be done via using custom CSS/JS: https://github.com/grocy/grocy#adding-your-own-css-or-js-without-to-have-to-modify-the-application-itself

For help on this, please use the subbredit: https://www.reddit.com/r/grocy/
