### ISSUE TITLE
Recipes page reloads when extending row

### ISSUE THREAD

**Issue by Mikhail5555** [grocy/grocy#589]
## Expected Behavior

The Recipes DataTable hides extra fields if they don't fit in the width (Almost always the case on mobile devices). When pressing the expand button this row gets shown.

## Actual Behavior

When clicked on the blue plus, indeed the row is expanded with the new info, but the page is also instantly reloaded.

## Steps to Reproduce the Problem

1. Add a custom field to recipes (Like URL) and enter a long url
2. Open the https://demo.grocy.info/recipes and resize the browser until he URL colomn is hidden and a blue Plus appears.
3. Try to click the blue plus without the page reloading (To click the url) (This doesn't seem to be the problem when clicking the first entry, only second and above)

## Proposed solutions

  1.  Add a check to [recipes.js](https://github.com/grocy/grocy/blob/master/public/viewjs/recipes.js#L206) to only change pages when a recipe is selected which IS NOT the current one.
```
recipesTables.on('select', function(e, dt, type, indexes)
{
	if (type === 'row')
	{
		var selectedRecipeId = $(recipesTables.row(indexes[0]).node()).data("recipe-id");
		var currentRecipeId = location.search.split('recipe=')[1];
		if (selectedRecipeId.toString() !== currentRecipeId) {
			window.location.href = U('/recipes?recipe=' + selectedRecipeId.toString());
		}
	}
});
```
  1.  Change the blue plus to not trigger the 'select' event.
 
## Specifications

  - Version: 2.6.0 and pre-release
  - Platform: Whatever the demo server runs on
  - Subsystem: Whatever the demo server runs on

**Comment by berrnd** [comment]
Thanks - I just added it as proposed by you above.
