### ISSUE TITLE
2.6.1 can not generate all demo data

### ISSUE THREAD

**Issue by BlueBlueBlob** [grocy/grocy#598]
Hi.

(Demo mode)
Migration works when I install 2.6.0 then update to 2.6.1
But a fresh install from 2.6.1gives me a php error : 
```
[php7:error] [pid 1625] [client ::1:58770] PHP Fatal error:  Maximum execution time of 30 seconds exceeded in /var/www/html/vendor/morris/lessql/src/LessQL/Result.php on line 324
```
Result: 7 products in stock...

Do you need more logs/infos ?

Best regards

**Comment by berrnd** [comment]
"Maximum execution time of 30 seconds exceeded" says all, I think: Increase your `max_execution_time` (php.ini)

(For me it still works, but of course depends on how fast the machine is - all demo data is populated in one request...)

**Comment by BlueBlueBlob** [comment]
Thx ! Raspberry Pi 0W... ;)
