### ISSUE TITLE
Feature request: Add friendly_name to product

### ISSUE THREAD

**Issue by smhgit** [grocy/grocy#599]
Add the ability to define friendly name to the product. In my used case, the product name is not in english, but I would like also to have the english name at the same time. I know it can be added via user field, but user field is more complicated and less friendly.

**Comment by berrnd** [comment]
What's the real difference between an userfield and a built-in one?

**Comment by smhgit** [comment]
Unless I am missing something, userfield requires extra REST API calls. If userfields can be added to the product response, than it is fine, otherwise, the extra calls make it more "complicated" to handle.

**Comment by berrnd** [comment]
> If userfields can be added to the product response

Ok, no problem with that, maybe fits better into a separate issue.

But I still don't get the real use case for an "internal" and a "visible" product, why not just name it how you would like it to be displayed?

**Comment by smhgit** [comment]
@berrnd 

In the mobile app, i show the name in Hebrew, but if I want to announce it with Alexa / Google Home, Hebrew is still not supported, so I use English. This is my use case.

Another use case can be the following: In mobile app you can show more information than what you want to announce with voice assistant, so you might want to have two names, this is why I call it friendly. Actually, the friendly comes from home assistant terms ...

**Comment by smhgit** [comment]
> Ok, no problem with that, maybe fits better into a separate issue.

Will you open new issue?

**Comment by berrnd** [comment]
Ok, I created #601.
