### ISSUE TITLE
UI-Bug: Text missing in Transifex

### ISSUE THREAD

**Issue by BlizzWave** [grocy/grocy#602]
There is some text that cannot be translated in Transifex. 
This is found in German and Norwegian and these are 100% translated.
Please have a look at the screencap below:

![ui-bug](https://user-images.githubusercontent.com/6298655/76410028-8c16d080-638f-11ea-9833-34ef1ae9fa97.gif)

**Comment by berrnd** [comment]
This was fixed by #657.
