### ISSUE TITLE
Feature request: Collapse product groups in the shopping list

### ISSUE THREAD

**Issue by lyz-code** [grocy/grocy#604]
I'd like to be able to collapse the different product groups in the shopping list, so when all items in one have been added to the cart, I can browse more quickly through the remaining items.

P.D: Super cool the 2.6.1 upgrade, everything is much faster, thanks!

**Comment by kriddles** [comment]
This might be a good reference to make collapsing work with datatables.
https://stackoverflow.com/questions/46414643/jquery-datatables-rowgroup-collapse-expand

**Comment by kriddles** [comment]
> This might be a good reference to make collapsing work with datatables.
> https://stackoverflow.com/questions/46414643/jquery-datatables-rowgroup-collapse-expand

I've tried to make this work but so far have been unsuccessful.

**Comment by berrnd** [comment]
Thanks for the link @kriddles, I've fiddled around a little bit in https://github.com/grocy/grocy/commit/6f4769a7b312ce2420ba02f776cca3b235d61a3b and it seems to work...
