### ISSUE TITLE
Feature request: Select children product on recipe consumption

### ISSUE THREAD

**Issue by lyz-code** [grocy/grocy#605]
When creating recipes that use parent products as ingredients, it would be cool to be able to select which of the different children products to consume.

Probably related to https://github.com/grocy/grocy/issues/548

**Comment by berrnd** [comment]
And releated to #385.

**Comment by organismen** [comment]
Exactly what I was looking for!

It make sense to me after you click "Consume all products" that in the confirm modal that appears a list of all products to consume would appear with the ability to pick sub products to consume instead of parent product.

**Comment by berrnd** [comment]
Duplicate of / merge into #548.

**Comment by lyz-code** [comment]
Thanks @berrnd for the feature and for maintaining `grocy` :)

**Comment by berrnd** [comment]
Just if you got it wrong, "merged into" doesn't mean this is done, it will be further tracked in #548, which is about the same.
