### ISSUE TITLE
hosting with sub/relative URL

### ISSUE THREAD

**Issue by klausmcm** [grocy/grocy#607]
Hello, I'm already hosting a few services on a single physical machine and making them available through sub URLs (ex. https://docs.gitlab.com/ee/install/relative_url.html).

I have studied the documentation at https://grocy.info/links but couldn't find straightforward instructions for such a setup.

My public facing webserver is nginx.

**Can grocy be configured to make available at a sub URL?**
ex. `https://server.org/grocy`

**Comment by berrnd** [comment]
See those two options in the `config.php` file:

https://github.com/grocy/grocy/blob/eb3c0f93970df0c19b8bbb1a55a933c50305e6b2/config-dist.php#L40-L50

However, I prefer and would recommend to use a subdomain, it's less complicated not only for grocy...

**Comment by klausmcm** [comment]
Danke Bernd.

Hosting is relatively new to me so I hope I can bother you with a few more follow-up questions. Can you please clarify subdomains? Would that setup for example then look like

* `gitlab.server.org`
* `grocy.server.org`

instead of

* `server.org/gitlab`
* `server.org/grocy`

?

I'm using letsencrypt through certbot to enable https and used `server.org` when running the setup. Would the same registration work for the subdomains?

I looked at your configuration here https://github.com/grocy/grocy-docker/issues/15#issuecomment-486579894 and #399 but I don't think you have configured subdomains there. I'd love some tips. I'm hosting on Debian 10 by the way.

**Comment by berrnd** [comment]
> Would that setup for example then look like...

Yes.

> Would the same registration work for the subdomains?

Only if you use a wildcard certificate (`*.server.org`), otherwise just create separate certificates for each subdomain.

The nginx configuration in https://github.com/grocy/grocy-docker/issues/15#issuecomment-486579894 mentions the hostname `demo-en.grocy.info`, so `demo-en` is a subdomain of `grocy.info`.

**Comment by klausmcm** [comment]
Merci, I will review the info and give this a try. The subdomain you mentioned makes sense. I overlooked that.

**Comment by klausmcm** [comment]
@berrnd Thank you for the subdomain tip. I moved everything over from relative URLs. I also managed to get grocy working using your configuration from https://github.com/grocy/grocy-docker/issues/15#issuecomment-486579894 as a template. Thank you for your work and effort and I look forward to giving your project a try.
