### ISSUE TITLE
How to reset admin password ?

### ISSUE THREAD

**Issue by RichardDern** [grocy/grocy#608]
For some reasons I lost my admin password, and so, access to Grocy.

How can I reset it ?

**Comment by berrnd** [comment]
Put the file `9999.php` from the attached ZIP into the `migrations` folder and visit the root route (`/`) to apply migrations - the password of the user `admin` is then reset to `admin`.

(And maybe start using a password manager...)

[grocy_reset_admin_password_migration.zip](https://github.com/grocy/grocy/files/4333215/grocy_reset_admin_password_migration.zip)

**Comment by RichardDern** [comment]
I do use a password manager. But I'm using grocy through the HomeAssistant plugin and for that specific reason, my password manager didn't remind grocy's password when I changed it.

I wanted to access the ical calendar through my calendar client and it asked me for credentials (the full API URL wasn't enough for it), so I thought I got the wrong password. I changed it in the admin, disconnected and thought the password manager would remind it. There, I can't log in again.

I just didn't want to go into details as nothing of this is relevant to my question.

That said, "Ease password reset procedure" should be added to your features requests.

**Comment by RichardDern** [comment]
Line 5 of 9999.php file should read:

```$db = $this->DatabaseService->GetDbConnection();```

instead of:

```$db = $this->getDatabaseService()->GetDbConnection();```

Otherwise it throws an undefined method exception.

**Comment by RichardDern** [comment]
Actually, both throws an exception:

```
Slim Application Error
The application could not run because of the following error:

Details

Type: Error
Message: Call to undefined method Grocy\Services\DatabaseMigrationService::getDatabaseService()
File: /var/www/grocy/migrations/9999.php
Line: 5
Trace

#0 /var/www/grocy/services/DatabaseMigrationService.php(57): include()
#1 /var/www/grocy/services/DatabaseMigrationService.php(38): Grocy\Services\DatabaseMigrationService->ExecutePhpMigrationWhenNeeded(9999, '/var/www/grocy/...')
#2 /var/www/grocy/controllers/SystemController.php(23): Grocy\Services\DatabaseMigrationService->MigrateDatabase()
#3 [internal function]: Grocy\Controllers\SystemController->Root(Object(Slim\Http\Request), Object(Slim\Http\Response), Array)
#4 /var/www/grocy/vendor/slim/slim/Slim/Handlers/Strategies/RequestResponse.php(40): call_user_func(Array, Object(Slim\Http\Request), Object(Slim\Http\Response), Array)
#5 /var/www/grocy/vendor/slim/slim/Slim/Route.php(281): Slim\Handlers\Strategies\RequestResponse->__invoke(Array, Object(Slim\Http\Request), Object(Slim\Http\Response), Array)
#6 /var/www/grocy/middleware/SessionAuthMiddleware.php(26): Slim\Route->__invoke(Object(Slim\Http\Request), Object(Slim\Http\Response))
#7 [internal function]: Grocy\Middleware\SessionAuthMiddleware->__invoke(Object(Slim\Http\Request), Object(Slim\Http\Response), Object(Slim\Route))
#8 /var/www/grocy/vendor/slim/slim/Slim/DeferredCallable.php(57): call_user_func_array(Object(Grocy\Middleware\SessionAuthMiddleware), Array)
#9 [internal function]: Slim\DeferredCallable->__invoke(Object(Slim\Http\Request), Object(Slim\Http\Response), Object(Slim\Route))
#10 /var/www/grocy/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(70): call_user_func(Object(Slim\DeferredCallable), Object(Slim\Http\Request), Object(Slim\Http\Response), Object(Slim\Route))
#11 /var/www/grocy/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(117): Slim\Route->Slim\{closure}(Object(Slim\Http\Request), Object(Slim\Http\Response))
#12 /var/www/grocy/vendor/slim/slim/Slim/Route.php(268): Slim\Route->callMiddlewareStack(Object(Slim\Http\Request), Object(Slim\Http\Response))
#13 /var/www/grocy/vendor/slim/slim/Slim/App.php(503): Slim\Route->run(Object(Slim\Http\Request), Object(Slim\Http\Response))
#14 /var/www/grocy/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(117): Slim\App->__invoke(Object(Slim\Http\Request), Object(Slim\Http\Response))
#15 /var/www/grocy/vendor/slim/slim/Slim/App.php(392): Slim\App->callMiddlewareStack(Object(Slim\Http\Request), Object(Slim\Http\Response))
#16 /var/www/grocy/vendor/slim/slim/Slim/App.php(297): Slim\App->process(Object(Slim\Http\Request), Object(Slim\Http\Response))
#17 /var/www/grocy/app.php(72): Slim\App->run()
#18 /var/www/grocy/public/index.php(3): require_once('/var/www/grocy/...')
#19 {main}
```

**Comment by berrnd** [comment]
> "Ease password reset procedure" should be added to your features requests.

That would require something like sending a password reset link by mail - grocy doesn't send mails or something at the moment ... and at the end maybe sending such a link is the problem...

I think it's enough for now that this is document here by using a migration file.

**Comment by gabriel-lucas** [comment]
Hi,

I have a similar situation, should I open a new issue?

I set up grocy using docker. I have two containers.

5b9d8e65d952        grocy/nginx:v2.7.1-3                  
2a362c5d3fb7        grocy/grocy:v2.7.1-3                                        

I might have changed the name of the admin user 

I can save the file file @berrnd posted (https://github.com/grocy/grocy/files/4333215/grocy_reset_admin_password_migration.zip) and unzip it into the /var/www/migrations/9999.php

I open the browser and visit the /  of my server and then try to enter with credentials admin/admin  but it doesn´t work, then I modify the 9999.php file to fit the changed the user name but it doesn´t work either.

Can you give a hint?

Thanks a lot.

**Comment by berrnd** [comment]
Great (and easier) suggestion, thanks! :)

There is also the setting `DISABLE_AUTH` which fits better, when you change `GROCY_MODE` to `demo` also some demo data will be populated...

**Comment by beta-j** [comment]
> Hi,
> 
> I found a better way of doing it.
> 
> Just change the GROCY_MODE in the data/config.php file. Change the value from "production" to "demo" and then change the password.
> 
> Thanks a lot for the great project. I´m enjoying quite a lot 👍

hey can you tell me in which directory to find the data/config.php file please?

**Comment by berrnd** [comment]
> hey can you tell me in which directory to find the data/config.php file please?

?
You answered that yourself: `<grocy>/data/config.php`, the exact path to the "main grocy directory" on your installation nobody else can guess...

**Comment by beta-j** [comment]
> > hey can you tell me in which directory to find the data/config.php file please?
> 
> ?
> You answered that yourself: `<grocy>/data/config.php`, the exact path to the "main grocy directory" on your installation/system nobody else can guess...

Yeah - I figured as much.  I'm running Grocy as an addon for Home Assistant and I'm really having a hard time looking for the Grocy directory.  I can't even install 'locate' on the machine so I'm having to go through directories one by one.

**Comment by mohe2015** [comment]
> Yeah - I figured as much. I'm running Grocy as an addon for Home Assistant and I'm really having a hard time looking for the Grocy directory. I can't even install 'locate' on the machine so I'm having to go through directories one by one.

There also exists `find` which is probably installed.

**Comment by beta-j** [comment]
> > Yeah - I figured as much. I'm running Grocy as an addon for Home Assistant and I'm really having a hard time looking for the Grocy directory. I can't even install 'locate' on the machine so I'm having to go through directories one by one.
> 
> There also exists `find` or `ls -R` combined with `grep` which is probably installed.

Thanks for the pointers but I've already tried using "find" and "grep" and searching for *config.php* and *grocy*.  I even logged in with WinSCP and tried using the built in search tool but I keep coming up empty.

Could it be something to do with the docker environment that HA uses? Is grocy inside some kind of container maybe? (Sorry total n00b especially when it comes to docker)

**Comment by mohe2015** [comment]
@beta-j if you're using https://github.com/hassio-addons/addon-grocy/ that seems unsupported https://github.com/hassio-addons/addon-grocy/issues/66. Should be in /var/www/grocy though - but possibly inside of the container and not in a volume or however this works. You should definitely ask there though.

**Comment by beta-j** [comment]
> @beta-j if you're using https://github.com/hassio-addons/addon-grocy/ that seems unsupported [hassio-addons/addon-grocy#66](https://github.com/hassio-addons/addon-grocy/issues/66). Should be in /var/www/grocy/data though - but possibly inside of the container and not in a volume or however this works. You should definitely ask there though.

Thanks for the pointer.  
There is no /var/www folder on my HA machine (or - as you said - it's in some kind of docker container that I don't know how to get to).  I tried adding the "GROCY_MODE" and "DISABLE_AUTH" in the configuration section of the addon in the HA GUI - but no luck.  

I honestly can't understand how I got locked out of Grocy, I used to use it regularly and I have all my recipes stored in there.

If anyone has any ideas on how I can try to regain access do let me know please!  Thanks!

**Comment by mohe2015** [comment]
I think you should really ask the addon developer.

**Comment by highaltidude** [comment]
Frenck the maintainer is usually helpful. Otherwise Portainer should expose the location.

**Comment by pbanj** [comment]
> 
> 
> Put the file `9999.php` from the attached ZIP into the `migrations` folder and visit the root route (`/`) to apply migrations - the password of the user `admin` is then reset to `admin`.
> 
> (And maybe start using a password manager...)
> 
> [grocy_reset_admin_password_migration.zip](https://github.com/grocy/grocy/files/4333215/grocy_reset_admin_password_migration.zip)

where is the migration folder found? i dont seem to have it

**Comment by berrnd** [comment]
> where is the migration folder found? i dont seem to have it

On the same level as the `public` directory and all the others (simply check the the [GitHub repo](https://github.com/grocy/grocy/#files) here or the [release ZIP](https://releases.grocy.info/latest) content), if you don't have it, I highly doubt grocy runs at all.

**Comment by pbanj** [comment]
> 
> 
> > where is the migration folder found? i dont seem to have it
> 
> On the same level as the `public` directory and all the others (simply check the the [GitHub repo](https://github.com/grocy/grocy/#files) here or the [release ZIP](https://releases.grocy.info/latest) content), if you don't have it, I highly doubt grocy runs at all.

ok so it's the docker versions fault. time to go digging and find it lol

**Comment by rbh00723** [comment]
> > > where is the migration folder found? i dont seem to have it
> > 
> > 
> > On the same level as the `public` directory and all the others (simply check the the [GitHub repo](https://github.com/grocy/grocy/#files) here or the [release ZIP](https://releases.grocy.info/latest) content), if you don't have it, I highly doubt grocy runs at all.
> 
> ok so it's the docker versions fault. time to go digging and find it lol
> 
> got it, thank you, not sure how my password changed from what i had saved in bitwarden, but it's fixed now.

Okay So I'm in the same boat you were in...I'm running grocy in a docker container on my unraid server...I can't seem to locate a migration folder in my file structure. Any advice on where to find it or how to use the 9999 file provided ?

**Comment by pbanj** [comment]
> > > > where is the migration folder found? i dont seem to have it
> > > 
> > > 
> > > On the same level as the `public` directory and all the others (simply check the the [GitHub repo](https://github.com/grocy/grocy/#files) here or the [release ZIP](https://releases.grocy.info/latest) content), if you don't have it, I highly doubt grocy runs at all.
> > 
> > 
> > ok so it's the docker versions fault. time to go digging and find it lol
> > got it, thank you, not sure how my password changed from what i had saved in bitwarden, but it's fixed now.
> 
> Okay So I'm in the same boat you were in...I'm running grocy in a docker container on my unraid server...I can't seem to locate a migration folder in my file structure. Any advice on where to find it or how to use the 9999 file provided ?

i use portainer so i just use that to find where it was saving the container to and went there

**Comment by jfwerner** [comment]
So in case anyone is using the linuxserver grocy image (or idk maybe it changed to this for all grocy versions), the config/php file in grocy/data now has a `Setting('DISABLE_AUTH', false);` line which you can set to true. Not sure how to reset the password from here though...

**Comment by berrnd** [comment]
> Not sure how to reset the password from here though...

By just using the [`/users`](https://demo.grocy.info/users) page as normal. The menu "Manage users" is hidden (due to not really needed when not using authentication), but the page is still accessible.

&nbsp;
> the config/php file in grocy/data now has a `Setting('DISABLE_AUTH', false);` line

Just wanted to clarify "now": This setting exists since [v2.4.3](https://grocy.info/changelog#v2.4.3), so since almost 3 years.

**Comment by jsternadel** [comment]
@rbh00723 and anyone else using Grocy on unRAID:

The migrations directory is not exposed by the default template.  You will need to add your own Path to expose it.  

1. Edit the Grocy docker configuration
2.  Click the "+ Add another Path, Port, Variable, Label or Device"  option at the bottom of the edit screen
3.  For Config Type choose "Path"
4. Container path = `/app/grocy/migrations`
5. Host Path is wherever grocy app data is located:  I used `/mnt/user/appdata/grocy/migrations`
6. Access Mode = read/write
7. Save that configuration and you should have a new directory called migrations parallel to the data directory wherever your grocy appdata is located
8. Copy the 9999.php file to /migrations

Once that is all done follow @berrnd original instructions to reset your admin password.  Once I set my password I renamed 9999.php to 9999.php.old so it wouldn't run again but I had it just in case I needed it.

**Comment by Man-in-Black** [comment]
I moved my Grocy instance from HomeAssistant to Docker today and had the same problem.
Unfortunately, the 9999.php script didn't work for me, my approach was different:
1. Open SQLite database with a SQLite Explorer (DB Browser for SQLite on Windows)
2. Open the "users" table
3. Overwrite password hash with desired hash
4. Copy the database to the server
After that, the login worked for me without any problems.

**Comment by Charliopoulos** [comment]
So.... how do I reset the password now? I am using version 4.4.1 and when editing the users, there is no set password or similar.
is there a way to do it from the cli or somehting?

**Comment by berrnd** [comment]
@Charliopoulos At least 3 different ways have been mentioned here. Where have you been stuck exactly?

> Put the file `9999.php` from the attached ZIP into the `migrations` folder and visit the root route (`/`) to apply migrations - the password of the user `admin` is then reset to `admin`.
> 
> [grocy_reset_admin_password_migration.zip](https://github.com/grocy/grocy/files/4333215/grocy_reset_admin_password_migration.zip)

&nbsp;

> I am using version 4.4.1 and when editing the users, there is no set password or similar.

And what does that refer to exactly? On the edit user page there are two text boxes to change a password of a user - example: https://demo-prerelease.grocy.info/user/1?changepw=true

**Comment by Charliopoulos** [comment]
The 1st way: Honestly, I did not want to go through the hussle of messing with the docker configs to access the migration folder and I was hoping there was a CLI command to kind of reset the password from the terminal or maybe show it in the log files... 

And for the 2nd: If I change the DISABLE_AUTH flag to true, then also the reset pw box dissappears in the user setting  menu:
Is it a bug or a feature? :)

DISABLE_AUTH=false
![Image](https://github.com/user-attachments/assets/866af37f-632b-4e52-b939-1e7d5df81261)
DISABLE_AUTH=true
![Image](https://github.com/user-attachments/assets/b19469aa-f9d4-4db4-8985-33bcbb68cafb)

In the end I got lucky and found the password in another browser.

**Comment by berrnd** [comment]
> If I change the DISABLE_AUTH flag to true, then also the reset pw box dissappears in the user setting menu
> Is it a bug or a feature? :)

`DISABLE_AUTH` disables authentication. Disabled authentication means you neither need a username nor a password - don't get the question, of course it makes sense to not show related UI elements then.

The only problem is the forgotten password and I personally don't get why this is so often a problem, we use passwords or real keys multiple times a day in our lives. Grocy or any software can't be blamed for that. At the worst case, restore your backup and if you don't have one: Kein Backup, kein Mitleid.

**Comment by Armag3ddon** [comment]
For anyone who - like me - repeatedly finds themselves on this page because after changing the admin password, grocy claims again and again that the password is wrong:
grocy only accepts passwords with a maximum length of 16 characters. If you entered something longer, grocy will change the password and not tell you anything but it silently dropped the characters after the 16th.

**Comment by ITDZ12** [comment]
Hello, I can´t login anymore. My Grocy is running in Portainer. I try to change it from production to demo but this gives a server error.  Where/how can I use the DISABLE-AUTH in then config.php?

**Comment by berrnd** [comment]
> Where/how can I use the DISABLE-AUTH in then config.php?

The file is in the directory `data/config.php` and it's simply this line:

https://github.com/grocy/grocy/blob/303eec06b3be2e916aca8e8f38605fc7d191ecca/config-dist.php#L84-L86

If this file is maybe somewhere else in your specific environment is something you have to figure out or better ask at the corresponding place wherever a "Portainer image" (or how that's called) is maintained.

It's still crazy that so many people have trouble remembering (properly managing) their passwords. Do you guys constantly forget your front door keys when leaving home, too?
