### ISSUE TITLE
Bug: currency mismatch

### ISSUE THREAD

**Issue by fnordson** [grocy/grocy#609]
There is a weird currency mismatch on my installation.
I have grocy running in German (de).
When on "purchase" I can enter comma separated values and they're taken and displayed properly as comma separated value.
When I edit the cost through "stockentries" it only accepts values separated by dots/points. It'll still be displayed as comma separated value on the list in the end though.

**Comment by fnordson** [comment]
Edit: nevermind. Had the wrong config file and it was set to USD...

**Comment by berrnd** [comment]
Ok, but I created #610 for this - prefilling number inputs does not respect the browser locale number format.
