### ISSUE TITLE
Feature request: Make "quick consume" buttons in stock view configurable per product

### ISSUE THREAD

**Issue by sgofferj** [grocy/grocy#613]
At the moment, the "quick consume" buttons in the stock overview always consume 1 stock unit of the product. It would be quite useful to make this configurable per product so one could - as an example - set it to consume 0.1 pack of dogfood when feeding the dogs.

**Comment by fsironman** [comment]
I'm trying grocy out and came across this too especially when using the grocy app.

A use case where I imagine this being helpful would be the following:

Coffee is configured to the bought in packs and 1 pack equals 500 grams

Everytime you press on the quick consume it will take 1 gram
Which is not really helpful at all.

If there was an option to set it to lets say 10 grams (=1 cup),  then whenever you put a spoon of coffee in the filter you only have to press it once or maybe twice, when doing 2 cups.
