### ISSUE TITLE
Parent product accumulation wrong when QU conversion is involved

### ISSUE THREAD

**Issue by klausmcm** [grocy/grocy#615]
I might be using this wrong but I created a general product for honey (**honey**) and then created a specific honey product (**beemaid honey**) and made **honey** its parent

This is what I have configured for **honey**

![image](https://user-images.githubusercontent.com/14914359/76719565-5c512b00-66f7-11ea-9765-3961c1125eaf.png)

and this for **beemaid honey** (purchased **2 kg**)

![image](https://user-images.githubusercontent.com/14914359/76719535-47749780-66f7-11ea-80aa-eee3ed509ca1.png)

I also have the unit conversions configured correctly

1 kg = 1000 g

![image](https://user-images.githubusercontent.com/14914359/76719619-8276cb00-66f7-11ea-9fea-79aa84444f86.png)

1 g = 0.001 kg

![image](https://user-images.githubusercontent.com/14914359/76719648-96bac800-66f7-11ea-9211-7296acd787aa.png)

The issue I encounter is that the aggregate for **honey** shows **2 g** whereas I expected **2 kg**

![image](https://user-images.githubusercontent.com/14914359/76719449-0f6d5480-66f7-11ea-94c2-1035578b9481.png)

Is this a user or program error?

**Comment by berrnd** [comment]
Can reproduce this, seems that quantity unit conversion get not applied when doing the parent product accumulation...

**Comment by klausmcm** [comment]
My current workaround is to make the *Quantity unit stock* of the children the same unit as that of the parent.

**Comment by towo** [comment]
I'll bump on this even if slightly different, but probably the same inheritance problem:

1. Top level 'butter' entry, in grams/grams. (Alternatively: package/grams, same result.)
2. Store-specific 'butter' entry, 1 package purchase ≘ 1 package stock, 1 package ≘ 250 grams conversion.

(Logic being that I'm trying to figure packages in storage, opened packages, and using parts of a package.)

**Comment by piotrekoo** [comment]
I've been just working on the `stock_current` view to include QU conversion. Good to see it coming in the next version 👍 
Thanks a lot for your work!

**Comment by klausmcm** [comment]
Thank you! I look forward to trying the next release with this fix.
