### ISSUE TITLE
"Allow partial units in stock" sometimes ignored

### ISSUE THREAD

**Issue by sgofferj** [grocy/grocy#616]
Version: 2.6.1
Platform: Docker on Ubuntu Linux
Container: linuxserver/docker-grocy

Despite "Allow partial units in stock" being enabled for all my products, I ran into a few places where it doesn't work:
Stock entries - three dot menu in product row -> consume (gives error)
Stock entries - edit button in product row -> edit stock entry (accepts e.g. 0.5 but sets stock amount to zero which leads to some DB inconsistencies)

![Screenshot_20200316_100613](https://user-images.githubusercontent.com/3258466/76735684-1d11f100-676e-11ea-84be-0ad09c9b93fe.png)

**Comment by berrnd** [comment]
>  Stock entries - three dot menu in product row -> consume (gives error)

Can't reproduce this (the other one I can)...

**Comment by sgofferj** [comment]
Just to be sure, I mean "Stock entries" = Stock overview -> Stock entries (button with 3 disks on top of the page)
