### ISSUE TITLE
Feature Request: Go-bag content

### ISSUE THREAD

**Issue by fotodille** [grocy/grocy#618]
It would be nice to have the possibility to tag products as part of a go-bag/emergency kit.
Some of the content in a go-bag is of a never expiring kind while some need to be on "circulation" to not get too old when the emergency comes.
I think a number of needed items (for the whole family) to indicate "go-bag content" would suffice. Any "normal" minimum amount could either be included in that or not - I can't really see which is best.
A list to print with amount and places for all items would be a really nice to have.
Ordinary reminders on expiring dates and stock amount would probably be enough.

**Comment by kriddles** [comment]
You could create a new Location called "Go-Bag" then see the contents on the location content sheet. Specific stock best buy dates are available to be set by location including transferings to and from locations so that they could be rotated.

What specific feature would that not provide?

**Comment by fotodille** [comment]
I'll have to try this out, but as far as I've understood every item can only be in one place (duh) but what I would like is to have things in different places to make up "the complete go-bag". For instance some things will be in the actual go-bag (like matches, torches, some warm clothes and some cash). Other things I would have in my "dry-store" (rice packages with perhaps 2 years expiration date) and others in the more frequently used cupboards (bars with 6 months expiration period).
My hope is of course to never have to use a go-bag (I actually don't have one :) ) so I think some of the content need to be in the normal rotation of things to be decently fresh when the time comes.

A thought that occurs to me as I write this is that a recipe would probably solve this. (I haven't used any, but can I get a printout with locations for the ingredients?)

**Comment by berrnd** [comment]
> every item can only be in one place

No, every product has a default location, but you can set a different location on purchase or transfer products between any location.

**Comment by fotodille** [comment]
Yes, but can one thing (a specific protein bar) be in two places at the same time? Both in "Cupboard" and "Go-bag"?
I want to know what I should pack in my bag and where it is. 
Maybe I'm just complicating the whole thing =)

**Comment by kriddles** [comment]
Ah, I think I misunderstood your desire.
To me a GoBag contains all the items in it so that if you need it... you just grab it and go. In this case, locations work well and can keep your items separated and identifiable.

It sounds like you want to just tag and product as something you want for your GoBag when you have to pack it? It seems counter intuitive to have to then pack your GoBag to have to Go?
But if you want to, just explore adding a UserField option to products so that you can tag them as GoBag.

**Comment by berrnd** [comment]
> Yes, but can one thing (a specific protein bar) be in two places at the same time?

Yes.

**Comment by fotodille** [comment]
> To me a GoBag contains all the items in it so that if you need it... you just grab it and go. In this case, locations work well and can keep your items separated and identifiable.
Yes, I know, it's really the same for me, therefore I also called it Emergency kit, but not very clear ...
 
> But if you want to, just explore adding a UserField option to products so that you can tag them as GoBag.
I'll try this to see what I can do. Or a recipe. Anyway I think this can be solved without any modification to grocy.
Thank you both for putting up with me on this =)
