### ISSUE TITLE
Install on Ionos webspace

### ISSUE THREAD

**Issue by witzker** [grocy/grocy#619]
Hi
I'm new with this
can you PLS give me instructions on how to install this on my Ionos web space.

I created a domain and pointed it to a directory under root
I uploaded the files directly to this folder to this folder
![image](https://user-images.githubusercontent.com/4120266/76766104-c6211180-6797-11ea-8ad0-1925a39fee6b.png)
set PHP 7.3 for this folder
copied config-dist.php to data/config.php,
write rules:

![image](https://user-images.githubusercontent.com/4120266/76774900-db506d00-67a4-11ea-91af-bb91027cc455.png)

![image](https://user-images.githubusercontent.com/4120266/76774977-fae79580-67a4-11ea-9603-b52b0ae0904d.png)
![image](https://user-images.githubusercontent.com/4120266/76775016-089d1b00-67a5-11ea-8500-4cb6d8a1e7b5.png)

When I call the url nothing happens (no login screen)

what's next 

I can create a database My SQL in control center?

Hope for help to get this running

**Comment by dricetea** [comment]
Hi
first of all point your domain as discribed in the install guide to the public folder of grocy.
Make sure you have apache as a web server (I had no success with Nginx but with Apache 2.4)
A database is not needed since it uses SQLite... 
Set the write permissions of the data folder correctly and try again.
Good luck

**Comment by witzker** [comment]
THX for taking care.

I check once again and will try to comment here.

I created a subdomain grocy.domain.de and pointed it to a folder grocy.domain in the root directory of my server.

I downloaded
![image](https://user-images.githubusercontent.com/4120266/76785396-a862a500-67b5-11ea-839c-9b5c6fcf1d0b.png)


![image](https://user-images.githubusercontent.com/4120266/76785267-6f2a3500-67b5-11ea-831c-0f33e1e89b90.png)
unzipped it and uploaded the the unzipped files 
on the server it lis like this
![image](https://user-images.githubusercontent.com/4120266/76785740-3c347100-67b6-11ea-9bb4-27d0ad99bfa4.png)

NOT the directory to the folder grocy.domain.de
![image](https://user-images.githubusercontent.com/4120266/76785601-098a7880-67b6-11ea-8a76-c8f8125de061.png)

Write permission on that folder grocy.domain.de  is
![image](https://user-images.githubusercontent.com/4120266/76784935-d85d7880-67b4-11ea-90fc-5f7d2acbbfad.png)
data folder 

![image](https://user-images.githubusercontent.com/4120266/76785933-9e8d7180-67b6-11ea-8936-b022ea6d23b4.png)
set PHP 7.3 for this folder
copied config-dist.php to data/config.php

**Comment by dricetea** [comment]
Please point to the folder /public/ of Grocy 
<img width="261" alt="grafik" src="https://user-images.githubusercontent.com/41590050/76786725-fa0c2f00-67b7-11ea-85e2-0e0f0fe57848.png">

**Comment by berrnd** [comment]
And maybe don't download or clone the GitHub repository. First the master branch is not the latest stable/released version, second dependencies (composer/yarn) are not included, everyhting is mentionend in the [README](https://github.com/grocy/grocy#how-to-install), latest release ZIP (with dependencies): https://releases.grocy.info/latest

**Comment by witzker** [comment]
Great THX I'll try the other files from download link

**Comment by witzker** [comment]
I installed as described
copied config-dist.php to data/ folder and renamed it to config.php

now:
Internal Server Error
The server encountered an internal error or misconfiguration and was unable to complete your request.

Please contact the server administrator at to inform them of the time this error occurred, and the actions you performed just before this error.

More information about this error may be available in the server error log.

Additionally, a 500 Internal Server Error error was encountered while trying to use an ErrorDocument to handle the request.

PLS Help

**Comment by witzker** [comment]
Now I put the path in:

# When running grocy in a subdirectory, this should be set to the relative path, otherwise empty
# Example:
#  Webserver root directory = /var/www
#  grocy directory = /var/www/grocy
#  => BASE_PATH = /grocy
Setting('BASE_PATH', 'grocy.domin.de');

I got
404 Not Found
The application could not run because of the following error:

Details
Type: Slim\Exception\HttpNotFoundException
Code: 404
Message: Not found.
File: /homepages/46/d314935202/htdocs/grocy.domain.de/vendor/slim/slim/Slim/Middleware/RoutingMiddleware.php
Line: 93

do I have to put in someting else

# The base url of your installation,
# should be just "/" when running directly under the root of a (sub)domain
# or for example "https://example.com/grocy" when using a subdirectory
Setting('BASE_URL', '/');

**Comment by berrnd** [comment]
> Setting('BASE_PATH', 'grocy.domin.de');

This cannot be correct, this always is a local path, in a shared hosting environment, of course you have no control over it - guessed from the error messages above, probably: `/homepages/46/d314935202/htdocs/grocy.domain.de`

**Comment by witzker** [comment]
THX
you meen instead of
Setting('BASE_PATH', 'grocy.domin.de');
/homepages/46/d314935202/htdocs/grocy.domain.de

**Comment by berrnd** [comment]
`BASE_PATH` needs to be the relative path, starting at the webservers root directory (see the example in `config-dist.php`), but I cannot say what the webserver root directory is in you shared hosting account...

**Comment by berrnd** [comment]
But if `grocy.domain.de` really points to the `public` directory as mentioned above and the webserver really handles this as a own website with it's own root directory, then `BASE_PATH` should be just empty (but again, just guessing, I would never use shared hosting environments)...

**Comment by witzker** [comment]
When:
Setting('BASE_PATH', '');
Internal Server Error
The server encountered an internal error or misconfiguration and was unable to complete your request.

Please contact the server administrator at to inform them of the time this error occurred, and the actions you performed just before this error.

More information about this error may be available in the server error log.

Additionally, a 500 Internal Server Error error was encountered while trying to use an ErrorDocument to handle the request.

When
Setting('BASE_PATH', '/');

404 Not Found
The application could not run because of the following error:
Details
Type: Slim\Exception\HttpNotFoundException
Code: 404
Message: Not found.
File: /homepages/46/d314935202/htdocs/grocy.domain.de/vendor/slim/slim/Slim/Middleware/RoutingMiddleware.php
Line: 93
Trace
#0 /homepages/46/d314935202/htdocs/grocy.domain.de/vendor/slim/slim/Slim/Middleware/RoutingMiddleware.php(59): Slim\Middleware\RoutingMiddleware->performRouting(Object(Slim\Http\ServerRequest))
#1 /homepages/46/d314935202/htdocs/grocy.domain.de/vendor/slim/slim/Slim/MiddlewareDispatcher.php(140): Slim\Middleware\RoutingMiddleware->process(Object(Slim\Http\ServerRequest), Object(Slim\Routing\RouteRunner))
#2 /homepages/46/d314935202/htdocs/grocy.domain.de/vendor/slim/slim/Slim/Middleware/ErrorMiddleware.php(98): class@anonymous->handle(Object(Slim\Http\ServerRequest))
#3 /homepages/46/d314935202/htdocs/grocy.domain.de/vendor/slim/slim/Slim/MiddlewareDispatcher.php(140): Slim\Middleware\ErrorMiddleware->process(Object(Slim\Http\ServerRequest), Object(class@anonymous))
#4 /homepages/46/d314935202/htdocs/grocy.domain.de/vendor/slim/slim/Slim/MiddlewareDispatcher.php(81): class@anonymous->handle(Object(Slim\Http\ServerRequest))
#5 /homepages/46/d314935202/htdocs/grocy.domain.de/vendor/slim/slim/Slim/App.php(211): Slim\MiddlewareDispatcher->handle(Object(Slim\Http\ServerRequest))
#6 /homepages/46/d314935202/htdocs/grocy.domain.de/vendor/slim/slim/Slim/App.php(195): Slim\App->handle(Object(Slim\Http\ServerRequest))
#7 /homepages/46/d314935202/htdocs/grocy.domain.de/app.php(81): Slim\App->run()
#8 /homepages/46/d314935202/htdocs/grocy.domain.de/public/index.php(3): require_once('/homepages/46/d...')
#9 {main}
Go Back

PLS HELP

**Comment by berrnd** [comment]
All information needed is in the README, or on the comments about the `config.php` settings, or in the changelog - sorry, I'm out - the problem here is that informatino about the webserver configuration is (maybe) needed to setup everything correctly...

**Comment by witzker** [comment]
web server configuration needed

I Also have ssh connection but I don't know the commands

**Comment by dricetea** [comment]
I'm still not sure if your configuration points to the right folder.

- So please create a new file in Notepad and add the following:

```
<html>
<header><title>This is title</title></header>
<body>
Hello world
</body>
</html>
```
and save this file as **index.html** 

- Then upload it into your **/public/** folder of your Grosy installation.

When you open Grosy now -> no error page will show up -> instead a **Hello World** should be shown...

- If this works, check again your file permission (write) of the /data/ folder

- Next step would be to check if you have all needed extensions in PHP activ... to do this read the instructions on [PHP Info anzeigen](https://www.internetwerk.de/support/webhosting/php-info-datei-erstellen-und-konfiguration-anzeigen/)

**Comment by witzker** [comment]
THX
Hello World works
now  file permission (write) of the /data/ folder

![image](https://user-images.githubusercontent.com/4120266/76830525-b0f2c400-6825-11ea-8ee5-a1b5c8d12162.png)

![image](https://user-images.githubusercontent.com/4120266/76830495-9fa9b780-6825-11ea-819a-1051c1c922fd.png)

How should the rights be?

**Comment by witzker** [comment]
PHP info attached
WOW!
[PHP 7.3.15 - phpinfo().pdf](https://github.com/grocy/grocy/files/4341988/PHP.7.3.15.-.phpinfo.pdf)

Hope for further help
THX

**Comment by dricetea** [comment]
pdo_sqlite, sqlite3 are enabled... 
write permission should work too
Please remove the index.html from your /public/ folder 8-)
check & poste again the logs of your web server

**Comment by witzker** [comment]
Removed the index.html from /public/ folder

No error but also nothing else ( no loginscreen) white page

**Comment by dricetea** [comment]
Make sure you follow all the instructions... you had problems to point to the public folder and I asked to create a HTML file and you created a PHP file... 
-> so please **do not** remove the index.php because this is a script of Grocy...
Try again to see if you have access to the log files of your webserver...
No output is always caused by an error...

**Comment by witzker** [comment]
THX OK sorry!

**Comment by berrnd** [comment]
My really last try to invest time for this, maybe better use any Docker image or [grocy-desktop](https://github.com/grocy/grocy-desktop) if your unable to to figure this out yourself...

https://www.ionos.de/hilfe/hosting/php-fuer-web-projekt-verwenden/absoluten-pfad-document-root-mittels-php-skript-ermitteln/

This needs to be set for `BASE_PATH`, so probably `/kunden/homepages/46/d314935202/htdocs/grocy.domain.de` - BUT PLEASE double check that yourself.

**Comment by witzker** [comment]
THX
tried to set path as described
with and without /public

Still, the same Error:

404 Not Found
The application could not run because of the following error:
Details
Type: Slim\Exception\HttpNotFoundException
Code: 404
Message: Not found.
File: /homepages/46/d314935202/htdocs/grocy.domain.de/vendor/slim/slim/Slim/Middleware/RoutingMiddleware.php
Line: 93

Hope that someone knows how to solve this stupid Path problem.

**Comment by dricetea** [comment]
Did you set the `BASE_PATH` in the `config.php` at about line 45 to:

`Setting('BASE_PATH', '/kunden/homepages/46/d314935202/htdocs/grocy.zenewa.de/public');`

as seen in your php-info...

**Comment by witzker** [comment]
THX for taking care
i checked the pat to the dada folder in Ionos and set in toock a new config-dist.php from downloaded package put in:
`# When running grocy in a subdirectory, this should be set to the relative path, otherwise empty
# Example:
#  Webserver root directory = /var/www
#  grocy directory = /var/www/grocy
#  => BASE_PATH = /grocy
Setting('BASE_PATH', '/kunden/homepages/46/d314935202/htdocs/grocy.zenewa.de/public');

# The base url of your installation,
# should be just "/" when running directly under the root of a (sub)domain
# or for example "https://example.com/grocy" when using a subdirectory
Setting('BASE_URL', '/');`

loaded it to data folder and renamed it to config.php
cleaned browser cash in Edge, firefox, chrome

Type: Slim\Exception\HttpNotFoundException
Code: 404
Message: Not found.
File: /homepages/46/d314935202/htdocs/grocy.zenewa.de/vendor/slim/slim/Slim/Middleware/RoutingMiddleware.php
Line: 93

**Comment by witzker** [comment]
@dricetea 
If you have time. And would be so kind to help me I could give you access to my PC via TeamViewer or similar and call you.
What do you Think?

**Comment by berrnd** [comment]
`BASE_PATH` is of course always without the `public` directory...

More ideas:
- Enable error logging and check what gets logged there
  https://www.ionos.de/hilfe/hosting/problemloesungen-fuer-php/error-logs-aktivieren/
- Disable URL rewriting (`config.php` option `DISABLE_URL_REWRITING`), the URL would then be for example `https://domain.com/grocysubdir/public/index.php/stockoverview`
- Use a subdomain (which you already did according to the last screenshot above)
  https://www.ionos.de/hilfe/domains/website-mit-subdomains-strukturieren/website-inhalte-mit-subdomains-gliedern/
  https://www.ionos.de/hilfe/domains/domain-verwenden/

**Comment by witzker** [comment]
THX
will try will take time

**Comment by dricetea** [comment]
As discussed before -> you problem is the base path...
Error 404 means path of the request in the script is wong... File not found...
When you look on your error message you can see the error!
<img width="739" alt="grafik" src="https://user-images.githubusercontent.com/41590050/77027544-d3581f00-6996-11ea-98f5-c517f277db75.png">
The folder grocy is missing...
The correct path would be `/kunden/homepages/46/d314935202/htdocs/grocy.zenewa.de/grocy/vendor/slim/slim/Slim/MiddlewareDispatcher.php`
so mabe try to play arround with your BasePath...
Try like
`Setting('BASE_PATH', '/kunden/homepages/46/d314935202/htdocs/grocy.zenewa.de/grocy/');`
and check the error message to see what changed... till you have the right Base_path...

Good luck and sorry I can not support you online!

**Comment by witzker** [comment]
THX
Nothing chanced

**Comment by dricetea** [comment]
Last idea…

create a php file like **test.php**

put this code into it

```
<?php
  echo $_SERVER["DOCUMENT_ROOT"]
?> 
```

save it and place it in your `grocy/publi/` **folder**

run it like `http://grocy.zenewa.de/test.php` and paste the result here…

**Comment by witzker** [comment]
![image](https://user-images.githubusercontent.com/4120266/77059685-9e1ff100-69d7-11ea-87a2-50ddc7cf61c2.png)

**Comment by witzker** [comment]
@dricetea 
 How can I send You Private message?

**Comment by dricetea** [comment]
Did you try this in config.php?

`Setting('BASE_PATH', '/kunden/homepages/46/d314935202/htdocs/grocy.zenewa.de/');`

if it still fails - try this:
`Setting('DISABLE_URL_REWRITING', false);`
or 
`Setting('DISABLE_URL_REWRITING', true);`

**Comment by witzker** [comment]
still same

@dricetea
How can I send You Private message?

**Comment by witzker** [comment]
@dricetea 

I made a mistake by posting my domain!!
I have now corrected my posts to **grocy.domain.de**

I would like to ask you to do a search on the thread and set it also to **grocy.domain.de**
in your posts please

Many THX

**Comment by berrnd** [comment]
I've finally made some own test. It works. Maybe someone can verify this, see #694.

**Comment by witzker** [comment]
I tried but not with comands!
and got this:
`Fatal error: require_once(): Failed opening required '/homepages/46/d314935202/htdocs/grocy/data/config.php' (include_path='.:/usr/lib/php7.3') in /homepages/46/d314935202/htdocs/grocy/app.php on line 28`

**Comment by berrnd** [comment]
Simple question: Does `/homepages/46/d314935202/htdocs/grocy/data/config.php` exist and has proper permissions set?

**Comment by witzker** [comment]
Try to find:
![image](https://user-images.githubusercontent.com/4120266/78421220-3bc12480-7656-11ea-8da9-0a97301aac66.png)

**Comment by berrnd** [comment]
How should I see from the screenshot if the file `config.php` in the subdirectory `data` of your grocy directory exists? Should be a copy + configured as needed of `config-dist.php`. It's really hard to help you that way... :/

**Comment by berrnd** [comment]
Based on my example, your settings should most probably look like this (without URL rewriting enabled):
```
Setting('BASE_PATH', '/grocy/public/index.php');
Setting('BASE_URL', 'http://<YOURHOST>/grocy/public');
Setting('DISABLE_URL_REWRITING', true);
```

**Comment by witzker** [comment]
THX
Its very hard for me to check everything in Ionos controlcenter and filezilla.
If you like you can come to my pc via teamviever if you are so kind to help me and pove yourself.
Im doin to much mistakes

**Comment by berrnd** [comment]
Then I can just recommend to use other options ([grocy-desktop](https://github.com/grocy/grocy-desktop), [Docker1](https://github.com/grocy/grocy-docker), [Docker2](https://docs.linuxserver.io/images/docker-grocy)), I would to do it that way, if I don't really understand what I'm doing...

**Comment by berrnd** [comment]
The general problem about subdirectory installations is now resolved (in fact there was never an issue, it was just unclear how to configure everything properly).

See for Apache: https://github.com/grocy/grocy/issues/694#issue-592850273

See for nginx: https://github.com/grocy/grocy/issues/694#issuecomment-609079721

For specific setups / shared hosting environments / etc., please better ask this on [the subbredit](https://www.reddit.com/r/grocy/) if there are still problems.

**Comment by lovespreader** [comment]
@witzker I've just installed Grocy on my IONOS shared hosting with the same issues you experienced.

Here's my configuration, hoping it will solve your problems and enrich the docs for other IONOS clients out there.

I have followed this process:
- Copy the PHP files from the latest release into a `/grocy` directory.
- Create a subdomain that points to the `/grocy/public` directory from the IONOS admin panel.
- Ensure the permissions of my `/grocy/data/` directory.
- Rename `config-dist.php` to `config.php` and moved it to the `/grocy/data/` dir.
- Tweak the `config.php` as detailed below.
- Change the `/grocy/public/.htaccess` file as detailed below (that's the key!).

**/grocy/data/config.php**
```php
Setting('BASE_PATH', '');
Setting('BASE_URL', '/');
Setting('DISABLE_URL_REWRITING', false);
```

**/grocy/public/.htaccess**
```apache
RewriteEngine On
RewriteBase / # <- That's was causing issues
RewriteCond %{REQUEST_FILENAME} !-f
RewriteCond %{REQUEST_FILENAME} !-d
RewriteRule ^ index.php [QSA,L]
```

Access your subdomain from your favorite web browser and that should be good!

Hope it will work for you!

**Comment by witzker** [comment]
Many THX for your Post & taking care

I quickly followed your discription but still
![image](https://user-images.githubusercontent.com/4120266/113596478-a8407c00-963a-11eb-9e97-55f1ea454fc1.png)

The permission in Ionos for folders is 705
![image](https://user-images.githubusercontent.com/4120266/113596684-f5bce900-963a-11eb-9e23-caad3d79bc35.png)
 and  604 for These:
![image](https://user-images.githubusercontent.com/4120266/113596756-0f5e3080-963b-11eb-899f-86e515d38dee.png)

Is this OK?

**Comment by lovespreader** [comment]
I have exactly the same permissions on my folders, so AFAIK it's ok.

In your subdomain settings, did you configure the target to be the `/grocy/public` folder as seen below? (sorry it's in French).

<img width="494" alt="Capture d’écran 2021-04-05 à 21 13 25" src="https://user-images.githubusercontent.com/50042985/113615319-0037ac80-9654-11eb-8739-1ea80e7129a1.png">

Also, did you add the `RewriteBase /` attribute to the `/grocy/public/.htaccess`.

**Comment by witzker** [comment]
THX for taking care
Yes seems all like you have!?
![image](https://user-images.githubusercontent.com/4120266/113730519-434b5b80-96f8-11eb-9d87-5dd950993e55.png)

![image](https://user-images.githubusercontent.com/4120266/113730731-6d9d1900-96f8-11eb-9513-8c22e9153e8a.png)

I uploaded the all files from extracted
![image](https://user-images.githubusercontent.com/4120266/113730891-93c2b900-96f8-11eb-9828-ea3c17ca9baf.png)
to
![image](https://user-images.githubusercontent.com/4120266/113731240-e8feca80-96f8-11eb-9f3c-7694ca94af52.png)

So fare seems like you have
BUT I noticed the following in FileZilla !
![image](https://user-images.githubusercontent.com/4120266/113731811-5ad71400-96f9-11eb-955c-88e9c85aefe4.png)

![image](https://user-images.githubusercontent.com/4120266/113731915-717d6b00-96f9-11eb-8cb1-cd0180f0827a.png)
 Fehlgeschlagene Ubertagungen 26 ( failure in transmission) !!

I also uploaded with WinSCP but I don't know if the transmission was ok there?
I will google how to verify the upload.

What do you think?

**Comment by lovespreader** [comment]
It seems like you have all the same settings that I have. I don't think that the FTP failures are causing your current issues as the files that were not transferred are not the ones that are "blocking" you (it will be important to transfer them though, but not now).

Can you share your data/config.php file?

**Comment by witzker** [comment]
THX  for taking care
here is the data/config.php file:
```
<?php

// Settings can also be overwritten in two ways
//
// First priority
// A .txt file with the same name as the setting in /data/settingoverrides
// the content of the file is used as the setting value
//
// Second priority
// An environment variable with the same name as the setting and prefix "GROCY_"
// so for example "GROCY_BASE_URL"
//
// Third priority
// The settings defined here below

// Either "production", "dev", "demo" or "prerelease"
// When not "production", authentication will be disabled and
// demo data will be populated during database migrations
Setting('MODE', 'production');

// Either "en" or "de" or the directory name of
// one of the other available localization folders in the "/localization" directory
Setting('DEFAULT_LOCALE', 'en');

// This is used to define the first day of a week for calendar views in the frontend,
// leave empty to use the locale default
// Needs to be a number where Sunday = 0, Monday = 1 and so forth
Setting('CALENDAR_FIRST_DAY_OF_WEEK', '');

// If calendars should show week numbers
Setting('CALENDAR_SHOW_WEEK_OF_YEAR', true);

// To keep it simple: grocy does not handle any currency conversions,
// this here is used to format all money values,
// so doesn't really matter, but should be the
// ISO 4217 code of the currency ("USD", "EUR", "GBP", etc.)
Setting('CURRENCY', 'USD');

// When running grocy in a subdirectory, this should be set to the relative path, otherwise empty
// It needs to be set to the part (of the URL) after the document root,
// if URL rewriting is disabled, including index.php
// Example with URL Rewriting support:
//  Root URL = https://example.com/grocy
//  => BASE_PATH = /grocy
// Example without URL Rewriting support:
//  Root URL = https://example.com/grocy/public/index.php/
//  => BASE_PATH = /grocy/public/index.php
Setting('BASE_PATH', '');

// The base URL of your installation,
// should be just "/" when running directly under the root of a (sub)domain
// or for example "https://example.com/grocy" when using a subdirectory
Setting('BASE_URL', '/');

// The plugin to use for external barcode lookups,
// must be the filename without .php extension and must be located in /data/plugins,
// see /data/plugins/DemoBarcodeLookupPlugin.php for an example implementation
Setting('STOCK_BARCODE_LOOKUP_PLUGIN', 'DemoBarcodeLookupPlugin');

// If, however, your webserver does not support URL rewriting, set this to true
Setting('DISABLE_URL_REWRITING', false);

// Specify an custom homepage if desired - by default the homepage will be set to the stock overview page,
// this needs to be one of the following values:
// stock, shoppinglist, recipes, chores, tasks, batteries, equipment, calendar, mealplan
Setting('ENTRY_PAGE', 'stock');

// Set this to true if you want to disable authentication / the login screen,
// places where user context is needed will then use the default (first existing) user
Setting('DISABLE_AUTH', false);

// Either "Grocy\Middleware\DefaultAuthMiddleware", "Grocy\Middleware\ReverseProxyAuthMiddleware"
// or any class that implements Grocy\Middleware\AuthMiddleware
Setting('AUTH_CLASS', 'Grocy\Middleware\DefaultAuthMiddleware');

// When using ReverseProxyAuthMiddleware,
// the name of the HTTP header which your reverse proxy uses to pass the username (on successful authentication)
Setting('REVERSE_PROXY_AUTH_HEADER', 'REMOTE_USER');

// When using LdapAuthMiddleware
Setting('LDAP_DOMAIN', ''); // Example value "local"
Setting('LDAP_ADDRESS', ''); // Example value "ldap://vm-dc2019.local.berrnd.net"
Setting('LDAP_BASE_DN', ''); // Example value "OU=OU_Users,DC=local,DC=berrnd,DC=net"

// Set this to true if you want to disable the ability to scan a barcode via the device camera (Browser API)
Setting('DISABLE_BROWSER_BARCODE_CAMERA_SCANNING', false);

// Set this if you want to have a different start day for the weekly meal plan view,
// leave empty to use CALENDAR_FIRST_DAY_OF_WEEK (see above)
// Needs to be a number where Sunday = 0, Monday = 1 and so forth
Setting('MEAL_PLAN_FIRST_DAY_OF_WEEK', '');

// Default permissions for new users
// the array needs to contain the technical/constant names
// see the file controllers/Users/User.php for possible values
Setting('DEFAULT_PERMISSIONS', ['ADMIN']);

// Default user settings
// These settings can be changed per user, here the defaults
// are defined which are used when the user has not changed the setting so far

// Night mode related
DefaultUserSetting('night_mode_enabled', false); // If night mode is enabled always
DefaultUserSetting('auto_night_mode_enabled', false); // If night mode is enabled automatically when inside a given time range (see the two settings below)
DefaultUserSetting('auto_night_mode_time_range_from', '20:00'); // Format HH:mm
DefaultUserSetting('auto_night_mode_time_range_to', '07:00'); // Format HH:mm
DefaultUserSetting('auto_night_mode_time_range_goes_over_midnight', true); // If the time range above goes over midnight
DefaultUserSetting('currently_inside_night_mode_range', false); // If we're currently inside of night mode time range (this is not user configurable, but stored as a user setting because it's evaluated client side to be able to use the client time instead of the maybe different server time)

// Keep screen on settings
DefaultUserSetting('keep_screen_on', false); // Keep the screen always on
DefaultUserSetting('keep_screen_on_when_fullscreen_card', false); // Keep the screen on when a "fullscreen-card" is displayed

// Stock settings
DefaultUserSetting('product_presets_location_id', -1); // Default location id for new products (-1 means no location is preset)
DefaultUserSetting('product_presets_product_group_id', -1); // Default product group id for new products (-1 means no product group is preset)
DefaultUserSetting('product_presets_qu_id', -1); // Default quantity unit id for new products (-1 means no quantity unit is preset)
DefaultUserSetting('stock_decimal_places_amounts', 4); // Default decimal places allowed for amounts
DefaultUserSetting('stock_decimal_places_prices', 2); // Default decimal places allowed for prices
DefaultUserSetting('stock_due_soon_days', 5);
DefaultUserSetting('stock_default_purchase_amount', 0);
DefaultUserSetting('stock_default_consume_amount', 1);
DefaultUserSetting('stock_default_consume_amount_use_quick_consume_amount', false);
DefaultUserSetting('scan_mode_consume_enabled', false);
DefaultUserSetting('scan_mode_purchase_enabled', false);
DefaultUserSetting('show_icon_on_stock_overview_page_when_product_is_on_shopping_list', true);
DefaultUserSetting('show_purchased_date_on_purchase', false); // Wheter the purchased date should be editable on purchase (defaults to today otherwise)
DefaultUserSetting('show_warning_on_purchase_when_due_date_is_earlier_than_next', true); // Show a warning on purchase when the due date of the purchased product is earlier than the next due date in stock

// Shopping list settings
DefaultUserSetting('shopping_list_to_stock_workflow_auto_submit_when_prefilled', false); // Automatically do the booking using the last price and the amount of the shopping list item, if the product has "Default due days" set
DefaultUserSetting('shopping_list_show_calendar', false);

// Recipe settings
DefaultUserSetting('recipe_ingredients_group_by_product_group', false); // Group recipe ingredients by their product group

// Chores settings
DefaultUserSetting('chores_due_soon_days', 5);

// Batteries settings
DefaultUserSetting('batteries_due_soon_days', 5);

// Tasks settings
DefaultUserSetting('tasks_due_soon_days', 5);

// If the page should be automatically reloaded when there was
// an external change
DefaultUserSetting('auto_reload_on_db_change', true);

// Show a clock in the header next to the logo or not
DefaultUserSetting('show_clock_in_header', false);

// Component configuration for Quagga2 - read https://github.com/ericblade/quagga2#configobject for details
// Below is a generic good configuration,
// for an iPhone 7 Plus, halfsample = true, patchsize = small, frequency = 5 yields very good results
DefaultUserSetting('quagga2_numofworkers', 4);
DefaultUserSetting('quagga2_halfsample', false);
DefaultUserSetting('quagga2_patchsize', 'medium');
DefaultUserSetting('quagga2_frequency', 10);
DefaultUserSetting('quagga2_debug', true);

// Feature flags
// grocy was initially about "stock management for your household", many other things
// came and still come by, because they are useful - here you can disable the parts
// which you don't need to have a less cluttered UI
// (set the setting to "false" to disable the corresponding part, which should be self explanatory)
Setting('FEATURE_FLAG_STOCK', true);
Setting('FEATURE_FLAG_SHOPPINGLIST', true);
Setting('FEATURE_FLAG_RECIPES', true);
Setting('FEATURE_FLAG_CHORES', true);
Setting('FEATURE_FLAG_TASKS', true);
Setting('FEATURE_FLAG_BATTERIES', true);
Setting('FEATURE_FLAG_EQUIPMENT', true);
Setting('FEATURE_FLAG_CALENDAR', true);

// Sub feature flags
Setting('FEATURE_FLAG_STOCK_PRICE_TRACKING', true);
Setting('FEATURE_FLAG_STOCK_LOCATION_TRACKING', true);
Setting('FEATURE_FLAG_STOCK_BEST_BEFORE_DATE_TRACKING', true);
Setting('FEATURE_FLAG_STOCK_PRODUCT_OPENED_TRACKING', true);
Setting('FEATURE_FLAG_STOCK_PRODUCT_FREEZING', true);
Setting('FEATURE_FLAG_STOCK_BEST_BEFORE_DATE_FIELD_NUMBER_PAD', true); // Activate the number pad in due date fields on (supported) mobile browsers
Setting('FEATURE_FLAG_SHOPPINGLIST_MULTIPLE_LISTS', true);
Setting('FEATURE_FLAG_CHORES_ASSIGNMENTS', true);

// Feature settings
Setting('FEATURE_SETTING_STOCK_COUNT_OPENED_PRODUCTS_AGAINST_MINIMUM_STOCK_AMOUNT', true); // When set to true, opened items will be counted as missing for calculating if a product is below its minimum stock amount
Setting('FEATURE_FLAG_AUTO_TORCH_ON_WITH_CAMERA', true); // Enables the torch automaticaly (if the device has one)


```
