### ISSUE TITLE
Feature request : add a parameter in UI to disable force compact view in shopping list

### ISSUE THREAD

**Issue by BlueBlueBlob** [grocy/grocy#620]
Hi,

I know it was a request but can you an option to disable it. I prefer the usual mobile view and compact view removes some features.

Great regards :)

**Comment by berrnd** [comment]
Is already possible: Settings icon top right corner -> Shopping list settings ->

![grafik](https://user-images.githubusercontent.com/2161815/76789207-a94b0500-67bc-11ea-97d0-0ba825782ac7.png)
