### ISSUE TITLE
UI Bug: Consume button wrong tooltip on Stock Entries page

### ISSUE THREAD

**Issue by dricetea** [grocy/grocy#621]
While on the Stock Overview page the button to consume 1 of the products works fine, on the Stock Entries page the consume button shows that cklicking will consume 1 product -> but after clicking all the certain products are consumed instead of one...

**Comment by berrnd** [comment]
It's supposed to consume the whole stock entry, so the tooltip description is wrong. Maybe also the button should be better red to match the "consume all"-button on the stock overview page.
