### ISSUE TITLE
Installation not working

### ISSUE THREAD

**Issue by matematrix** [grocy/grocy#623]
I have freshly installed Grocy 2.6.1 after completely wiping v2.6.0. After copying all files to the webserver, I received this error (grp is the root file for Grocy):

404 Not Found
The application could not run because of the following error:

Details
Type: Slim\Exception\HttpNotFoundException
Code: 404
Message: Not found.
File: /grp/vendor/slim/slim/Slim/Middleware/RoutingMiddleware.php
Line: 93
Trace
#0 /grp/vendor/slim/slim/Slim/Middleware/RoutingMiddleware.php(59): Slim\Middleware\RoutingMiddleware->performRouting(Object(Slim\Http\ServerRequest))
#1 /grp/vendor/slim/slim/Slim/MiddlewareDispatcher.php(140): Slim\Middleware\RoutingMiddleware->process(Object(Slim\Http\ServerRequest), Object(Slim\Routing\RouteRunner))
#2 /grp/vendor/slim/slim/Slim/Middleware/ErrorMiddleware.php(98): class@anonymous->handle(Object(Slim\Http\ServerRequest))
#3 /grp/vendor/slim/slim/Slim/MiddlewareDispatcher.php(140): Slim\Middleware\ErrorMiddleware->process(Object(Slim\Http\ServerRequest), Object(class@anonymous))
#4 /grp/vendor/slim/slim/Slim/MiddlewareDispatcher.php(81): class@anonymous->handle(Object(Slim\Http\ServerRequest))
#5 /grp/vendor/slim/slim/Slim/App.php(211): Slim\MiddlewareDispatcher->handle(Object(Slim\Http\ServerRequest))
#6 /grp/vendor/slim/slim/Slim/App.php(195): Slim\App->handle(Object(Slim\Http\ServerRequest))
#7 /grp/app.php(81): Slim\App->run()
#8 grp/public/index.php(3): require_once('/homepages/46/d...')
#9 {main}
Go Back

If there is any other information required, I would be happy to provide it. Thanks!

**Comment by berrnd** [comment]
Probably you run grocy in a subdirectory, means not the webservers root, so double check this new `config.php` setting (as also mentioned in the changelog of v2.6.1):
https://github.com/grocy/grocy/blob/eb3c0f93970df0c19b8bbb1a55a933c50305e6b2/config-dist.php#L40-L45

And just guessed by the error messages above, you probably use a shared hosting environment, so related to #619.

**Comment by witzker** [comment]
Hi same here https://github.com/grocy/grocy/issues/619. As mentioned
are you on Ionos too?
Maybe there is a problem with write rights

**Comment by matematrix** [comment]
Yes, it indeed is IONOS, but with version 2.6.0, there was absolutely no issue, everything was running wonderfully. Then, I used the update.sh and this ran without errors. But afterwards, there was this issue.
As a fix, I tried to wipe everyting and upload the new 2.6.1 again, but still the same error. I will try v.2.6.0 again.

**Comment by berrnd** [comment]
There was a change about "base path handling" in v2.6.1 (see the "Important notice" in the changelog header), I think in most shared hosting environments, your account is some subfolder of the webservers root directory.

The change was not intended by me, but caused by an upgrade of [Slim Framework](http://www.slimframework.com/) (which grocy uses) from v3 to v4.

See #568 or the discussion in https://github.com/grocy/grocy/commit/d4fa1a64c2f3021e400cb1b1506f291e20b57bf3 or the referenced links there.

**Comment by matematrix** [comment]
Okay, I understand. Sadly I have already tested the subfolder (due to the shared hosting environment) and other options there, without any success. Thanks for your help & the links though.

**Comment by witzker** [comment]
As I under stud it is an Issue that occurred in Update 2.6.0 to 2.6.1.
So there is hope that it will be solved soon.

If I can  do some testing? Let me know.
THX for taking care

**Comment by berrnd** [comment]
Just again: It's not really a problem of grocy, more a "problem" of the different base path handling of Slim 4 - so any documention / posts about that would be (probably) already valid for grocy.

I never use subfolders for any application, it's not only easier for grocy that way...

**Comment by witzker** [comment]
Is this helpful?
https://github.com/slimphp/Slim/issues/2512
My knowledge is to low!

**Comment by emk2203** [comment]
Can confirm that the new config.php option doesn't work for me. I get the same error message as @matematrix when trying to set up a new system. I also used a subdirectory.

**Comment by apleschu** [comment]
I have the same problem. Following the install instructions to the T and getting an error that is nowhere described being redirected to some other product is very frustrating. 

I *AM* running grocy in the root of a virtual name based server

**Comment by emk2203** [comment]
@apleschu I got it to work now ***without*** using a subdirectory, just using webroot. The rest of the instructions are unchanged. I am updating the instructions soon.

**Comment by witzker** [comment]
Great
Will there also be a solution to work in root/subdirectory on Ionos

**Comment by emk2203** [comment]
I am using php 7.4 and nothing more than outlined in #201.

I would love to see a solution for root/subdir, but it has to come from someone else. I wasn't able to make it work so far.

**Comment by AlphaJack** [comment]
> I am using php 7.4 and nothing more than outlined in #201.
> 
> I would love to see a solution for root/subdir, but it has to come from someone else. I wasn't able to make it work so far.

You mean having https://example.com/grocy/ working?

**Comment by emk2203** [comment]
No, just seeing <webroot>/grocy working, instead of <webroot> only.

At the moment, only `/var/www/html` works. Not `/var/www/html/grocy` as before.

**Comment by witzker** [comment]
As already asked:
pls tell me what php 7.3 modules have to be installed?

**Comment by berrnd** [comment]
>  pls tell me what php 7.3 modules have to be installed?

If missing modules are the problem, you would get a blank page / 500 internal server error, so that's not the problem here - but here are all listed:

https://github.com/grocy/grocy/blob/375865d80e54f71ee355bb3bd8f00d04a11cd6f3/helpers/PrerequisiteChecker.php#L5

**Comment by irl** [comment]
> No, just seeing /grocy working, instead of / only. Referring to webmaster root here in the config file.
> 
> At the moment, only `/var/www/html` works. Not `/var/www/html/grocy` as before.

Aaah, I had tried in /var/www which didn't work, and /var/www/grocy, which also didn't work. Is there some assumption about how paths work built in to the PHP framework? I'm running on Debian right now but I'd really like to run this on OpenBSD where the web server runs in a chroot, and the path would be like /sites/grocy not in /var/www at all.

**Comment by witzker** [comment]
Hey
@ you would get a blank page / 500 internal server error, so that's not the problem here

I exactly have this

And sorry I do not understand where to get the names of the moduls from your post
What exactly are the names of modules pls.

**Comment by berrnd** [comment]
@witzker if you use Windows client-side, I highly recommend to just [grocy-desktop](https://github.com/grocy/grocy-desktop).

`array('fileinfo', 'pdo_sqlite', 'gd')` means of course
- fileinfo
- pdo_sqlite
- gd

if a bullet list is better to read for you...

Maybe you will also find "gd2" instead of "gd" in your list...
But I would just check the error logs if that's the problem...

**Comment by witzker** [comment]
@berrnd 
THX
I try to setup on synology virtual host.

**Comment by zebfross** [comment]
I was able to partially fix the 404 error by setting my base path to "/index.php":
`Setting('BASE_PATH', '/index.php');`
My folder structure and my root directory is /Apache24/htdocs/public/.  I think it would also work if it was in a subdirectory, but it would have to be something like "/subdirectory/public/index.php".

**Comment by irl** [comment]
> I was able to partially fix the 404 error by setting my base path to "/index.php":
> `Setting('BASE_PATH', '/index.php');`
> My folder structure and my root directory is /Apache24/htdocs/public/. I think it would also work if it was in a subdirectory, but it would have to be something like "/subdirectory/public/index.php".
> 
> My "localhost/index.php" is still broken, but "localhost/index.php/stockoverview" works.

This works for me on OpenBSD with httpd(8) in a chroot! (with the limitation that you have to go to /index.php/stockoverview yourself, it won't redirect. I hadn't considered that I have turned off URL rewriting.

Possible fix: Perhaps it's possible to add some redirect to the base path if index.php is hit but base path isn't in the path?

**Comment by DocViper** [comment]
Ich hab das gleiche Problem und beisse mir hier die Zähne dran aus. Installation unter Debian unter einen vhost. Mir wird in den ganzen Antworten und Links woanders hin einfach nicht klar, was muss jetzt wo rein geschrieben werden, damit es funktioniert? Und mein Englisch ist zu schlecht.

404 Not Found
The application could not run because of the following error:

Details
Type: Slim\Exception\HttpNotFoundException
Code: 404
Message: Not found.
File: /var/www/vhosts/XXXdomainXXX.de/httpdocs/grocy/vendor/slim/slim/Slim/Middleware/RoutingMiddleware.php
Line: 93
Trace
#0 /var/www/vhosts/XXXdomainXXX.de/httpdocs/grocy/vendor/slim/slim/Slim/Middleware/RoutingMiddleware.php(59): Slim\Middleware\RoutingMiddleware->performRouting(Object(Slim\Http\ServerRequest))
#1 /var/www/vhosts/XXXdomainXXX.de/httpdocs/grocy/vendor/slim/slim/Slim/MiddlewareDispatcher.php(140): Slim\Middleware\RoutingMiddleware->process(Object(Slim\Http\ServerRequest), Object(Slim\Routing\RouteRunner))
#2 /var/www/vhosts/XXXdomainXXX.de/httpdocs/grocy/vendor/slim/slim/Slim/Middleware/ErrorMiddleware.php(98): class@anonymous->handle(Object(Slim\Http\ServerRequest))
#3 /var/www/vhosts/XXXdomainXXX.de/httpdocs/grocy/vendor/slim/slim/Slim/MiddlewareDispatcher.php(140): Slim\Middleware\ErrorMiddleware->process(Object(Slim\Http\ServerRequest), Object(class@anonymous))
#4 /var/www/vhosts/XXXdomainXXX.de/httpdocs/grocy/vendor/slim/slim/Slim/MiddlewareDispatcher.php(81): class@anonymous->handle(Object(Slim\Http\ServerRequest))
#5 /var/www/vhosts/XXXdomainXXX.de/httpdocs/grocy/vendor/slim/slim/Slim/App.php(211): Slim\MiddlewareDispatcher->handle(Object(Slim\Http\ServerRequest))
#6 /var/www/vhosts/XXXdomainXXX.de/httpdocs/grocy/vendor/slim/slim/Slim/App.php(195): Slim\App->handle(Object(Slim\Http\ServerRequest))
#7 /var/www/vhosts/XXXdomainXXX.de/httpdocs/grocy/app.php(81): Slim\App->run()
#8 /var/www/vhosts/XXXdomainXXX.de/httpdocs/grocy/public/index.php(3): require_once('/var/www/vhosts...')
#9 {main}
Go Back

![config_php_und_Installation_not_working_·_Issue__623_·_grocy_grocy](https://user-images.githubusercontent.com/542795/77795512-ebeac800-706d-11ea-954b-237e570a3d79.jpg)

**Comment by emk2203** [comment]
@DocViper So wie es aussieht, muss man `grocy` vorerst direkt unter Webroot installieren. Wenn bei dir webroot `/var/www/vhosts/<deinpfad.de>` ist, **musst** du grocy auch da installieren, ohne Unterverzeichnis. Der `BASE_PATH` muss `/` sein.

**Comment by DocViper** [comment]
Danke für deine Bemühungen @emk2203 . Ich hab nun alle Varianten durch und geb's auf. 
Auf Webservern mit Plesk lässt sich das einfach nicht betreiben. 
![404_Not_Found](https://user-images.githubusercontent.com/542795/77831590-64b25880-7130-11ea-9970-ea3279c8e930.jpg)
![Code-Editor__zwillunke_de___data___config_php_-_Plesk_Onyx_17_8_11](https://user-images.githubusercontent.com/542795/77831636-b1962f00-7130-11ea-8f9e-61abf4d77435.jpg)

Gibt es eigentlich noch irgendwo die Vorgänger-Version, die das Problem noch nicht hatte?

**Comment by TaciteOFF** [comment]
I'm having the same issue with ATSPACE.com free web hosting.

`Details

Type: Slim\Exception\HttpNotFoundException
Code: 404
Message: Not found.
File: /srv/disk18/3376730/www/mydomain.atspace.eu/vendor/slim/slim/Slim/Middleware/RoutingMiddleware.php
Line: 93
`

I did set

`Setting('BASE_PATH', '/srv/disk18/3376730/www/mydomain.atspace.eu');`

**Comment by jmoseley** [comment]
I ran into this problem as well (running on a raspberry pi with pi-hole installed as well, using lighttpd). I was not able to resolve the issue with many combinations of BASE_URL and various directories in the `/var/www`.

I fixed it by downgrading to to 2.6.0 and it works without issue. This makes me think there is a bug in the usage of `BASE_URL` or how its being passed to Slim, but I don't know enough about any of that to comment.

**Comment by HattoriHanzuo** [comment]
How can i make a downgrade to 2.6.0 ? O.o

**Comment by jmoseley** [comment]
When following. the install instructions, there is a step that says to download and unzip the code, a command like this:

```
$ wget https://releases.grocy.info/latest
$ unzip latest -d /var/www/html && rm latest
```

To install 2.6.0, you can modify the command to download and unzip the older version instead:

```
$ wget https://releases.grocy.info/v?2.6.0
$ unzip v?2.6.0 -d ./grocy && rm v?2.6.0
```

**Comment by berrnd** [comment]
I've finally made some own test. It works. Maybe someone can verify this, see #694.

**Comment by berrnd** [comment]
The general problem about subdirectory installations is now resolved (in fact there was never an issue, it was just unclear how to configure everything properly).

See for Apache: https://github.com/grocy/grocy/issues/694#issue-592850273

See for nginx: https://github.com/grocy/grocy/issues/694#issuecomment-609079721

For specific setups / shared hosting environments / etc., please better ask this on [the subbredit](https://www.reddit.com/r/grocy/) if there are still problems.

**Comment by jmoseley** [comment]
Thanks for the update. I managed to get this to work with just the right rewriting rules. Here is more info in case it helps anyone:

I access grocy at `http://grocy.lan`.

My grocy installation is at `/var/www/grocy`.

Here is my lighttpd config. Shouldn't be too hard to translate it to Apache or nginx.

```
$HTTP["host"] =~ "grocy.lan" {
        url.rewrite-repeat = (
          "^/$"  => "/index.php"
        )
        url.rewrite-if-not-file = (
           "/(.*)\.^((?!php))$" => "/$1.$2",
           "/(.*)$" => "/index.php?/$1"
        )

        server.document-root        = "/var/www/grocy/public"
        server.error-handler-404 = ""
        index-file.names            = ( "index.php", "index.html", "index.lighttpd.html" )
}
```

and my `config.php` settings:

```
Setting('BASE_PATH', '');
Setting('BASE_URL', '/');
Setting('DISABLE_URL_REWRITING', false);
```

**Comment by Schlaefer** [comment]
For reference Raspberry Pi with lighttpd on DietPi having grocy 2.7.1 installed in a subdirectory  `/var/www/html/grocy`:
```
# In /etc/lighttpd.conf add mod_rewrite
server.modules = (
   ...,
   "mod_rewrite",
)

# Add /etc/lighttpd/conf-enabled/20-grocy.conf
url.rewrite-if-not-file = (
"^/grocy/public/(.*)" => "/grocy/public/index.php"
)

# in /var/www/html/grocy/data/config.php
Setting('BASE_PATH', '/grocy/public');
Setting('BASE_URL', 'http://<your server|IP>/grocy/public');
```

Grocy available at `http://<your server|IP>/grocy/public/`

**Comment by heinrich-ulbricht** [comment]
Got it running on a RasPi with Raspian Stretch, Apache 2.4 and URL rewriting enabled.
Server root is `/var/www`, grocy has been extracted to sub-directory `/var/www/grocy`.

Apache site:
```
ServerName grocy.my-domain.de
DocumentRoot /var/www/grocy/public/

<Directory "/var/www/grocy/">
    AllowOverride All
</Directory>
```

Grocy `config.php`:
```
Setting('BASE_PATH', '');
Setting('BASE_URL', 'https://grocy.my-domain.de');
```

Note the empty `BASE_PATH`. It did not work with `'/'`.

No manual rewrite rules needed to be configured.

**Comment by TryCatchCrash** [comment]
> For reference Raspberry Pi with lighttpd on DietPi having grocy 2.7.1 installed (alongside Pi-hole) in a subdirectory `/var/www/html/grocy`:
> 
> ```
> # In /etc/lighttpd.conf add mod_rewrite 
> server.modules = (
>    …,
>    "mod_rewrite",
> )
> 
> # and having this document root:
> server.document-root        = "/var/www/html"
> 
> # Add /etc/lighttpd/conf-enabled/20-grocy.conf
> url.rewrite-if-not-file = (
> "^/grocy/public/(.*)" => "/grocy/public/index.php"
> )
> 
> # in /var/www/html/grocy/data/config.php
> Setting('BASE_PATH', '/grocy/public');
> Setting('BASE_URL', 'http://<your server|IP>/grocy/public');
> ```
> 
> Grocy available at `http://<your server|IP>/grocy/public/`

Just if someone has the same problem as I did.
I've tried with that config on and it worked, but /api access with the key as the url parameter did not work.

by looking around on https://www.slimframework.com/docs/v3/start/web-servers.html i've configured the server as advised there and now it works along with the /api path.

my config looks like:

`$HTTP["host"] == "grocy.domain.com" {
  url.rewrite-if-not-file = ("(.*)" => "/index.php/$0")
  server.document-root = "/var/www/grocy.domain.com/html/public"
}
`
