### ISSUE TITLE
Set Language in Grocy to German

### ISSUE THREAD

**Issue by witzker** [grocy/grocy#624]
Sorry but I really do not fin a hint how to get Grocy in German

On demo version there is a dropdown but not in my installation on server. 
Pls give me instructions 
THX

**Comment by klausmcm** [comment]
https://github.com/grocy/grocy#localization

![image](https://user-images.githubusercontent.com/14914359/76808594-78130a80-67a5-11ea-8ddb-43ef29ecc0f3.png)

**Comment by witzker** [comment]
Great THX
