### ISSUE TITLE
Purchase: QU conversion hint wrong (no decimal places)

### ISSUE THREAD

**Issue by klausmcm** [grocy/grocy#625]
I'm observing issues related to partial quantities. Test setup is as follows (on v2.6.1)

Product is **coke (small bottle)**. Setup is as follows

![image](https://user-images.githubusercontent.com/14914359/76885250-2a95ac80-683c-11ea-99f2-2f10d01302b8.png)

When *purchasing* this item, the UI informs me **Bottle (will be multiplied a factor of 0 to get L)** - the factor I expected and configured is **0.5**

![image](https://user-images.githubusercontent.com/14914359/76887085-f4a5f780-683e-11ea-8b3e-a5ce208b84ce.png)

**Comment by berrnd** [comment]
Is only a display problem, in your example 0.5 L will be added to stock.

**Comment by klausmcm** [comment]
Yes, I forgot to mention that. Correct amount is still added.
