### ISSUE TITLE
Feature Request: Use username from reverse proxy

### ISSUE THREAD

**Issue by CRTified** [grocy/grocy#627]
Hello,

I want to use grocy behind a reverse nginx proxy, similar to other services that I use. For my other services, I also use the nginx PAM module for authentication to keep the password management for all services in one place.

It would be great if grocy would be able to use the username supplied in a request header.
This request seems related to #246 , but instead of using the first user in the database, it would probably need to create users if they do not exist.

**Comment by berrnd** [comment]
This is now done by #921 

Excerpt from the changelog:
> ### New feature: Reverse proxy authenticaton support
> - New `config.php` settings `AUTH_CLASS` and `REVERSE_PROXY_AUTH_HEADER`
> - If you set `AUTH_CLASS` to `Grocy\Middleware\ReverseProxyAuthMiddleware` and your reverse proxy sends a username in the HTTP header `REMOTE_USER` (header name can be changed by the setting `REVERSE_PROXY_AUTH_HEADER`), the user is automatically authenticated (and will also be created, if not already present)
> - (Thanks @fipwmaqzufheoxq92ebc for the initial work on this)
