### ISSUE TITLE
Product names disappear in stock overview on small devices

### ISSUE THREAD

**Issue by Mik-** [grocy/grocy#629]
If you open the stock overview on small devices, the product names were not shown.
This takes effect in the German translation in your demo, probably because of longer one-word product names.

I expected to never hide the product name column, but to move the action buttons to the vertical ellipsis menu. Alternativly, the product name can be shortend (with an ellipsis) or the column spread out of the right screen border.

Beside that, the button to toggle the details (+ sign) is hardly to touch on small device.

I attached two screenshots to show, what I mean.

German
![stock_overview_de](https://user-images.githubusercontent.com/5106436/77060260-97de4480-69d8-11ea-9c04-1056e22c34a0.png)

English
![stock_overview_en](https://user-images.githubusercontent.com/5106436/77060380-c825e300-69d8-11ea-9c3f-f8315e05d615.png)

Kind regards
Mik

**Comment by berrnd** [comment]
Answered in https://github.com/grocy/grocy/issues/205#issuecomment-480502674.

I'll try to check if there's an option for DataTables to not collapase a specific column - would then use this for the "main column" in each table.
