### ISSUE TITLE
product location

### ISSUE THREAD

**Issue by Meowulf-storage** [grocy/grocy#630]
This program is great, but i have 1 question:
When filter products by location it show full stock, not stock in curren location. For example - i have 2 cans of  beans in my kitchen cabinet & 5 in my pantry. But whatever location i choose, it always show 7. So i can not find out, how many cans stocked in  location.
Does it suppose work like this, or this is bug? Or its me do something wrong?

**Comment by berrnd** [comment]
The stock overview page always shows the whole amount of the specific product.

Use the [Location Content Sheet](https://demo-prerelease.grocy.info/locationcontentsheet) or the [Stock Entries page](https://demo-prerelease.grocy.info/stockentries?product=3) to show details.
