### ISSUE TITLE
Hide Inventory

### ISSUE THREAD

**Issue by witzker** [grocy/grocy#631]
Is it not possible to hide Inventory and everything that deals with tare weight handling
could You Implement It PLS

Setting('FEATURE_FLAG_STOCK', true);
Setting('FEATURE_FLAG_SHOPPINGLIST', true); 
Setting('FEATURE_FLAG_RECIPES', true);
Setting('FEATURE_FLAG_CHORES', false); 
Setting('FEATURE_FLAG_TASKS', false); 
Setting('FEATURE_FLAG_BATTERIES', false); 
Setting('FEATURE_FLAG_EQUIPMENT', true); 
Setting('FEATURE_FLAG_CALENDAR', true);

**Comment by berrnd** [comment]
Inventory is part of stock handling, if you hide it, you have no option to correct wrong stock entries. So I think it's ok to combine it under `FEATURE_FLAG_STOCK`.

Tare weight handling: When you don't enable it for any product, where do you get bothered about that?

If you want to hide the Inventory menu entry, use [custom CSS](https://github.com/grocy/grocy#adding-your-own-css-or-js-without-to-have-to-modify-the-application-itself):

Create the file `data/custom_css.html` and put that into it:
```
<style>
.nav-item[data-nav-for-page="inventory"] {
	display: none !important;
}
</style>
```
