### ISSUE TITLE
Customize width of tables in Recipes

### ISSUE THREAD

**Issue by witzker** [grocy/grocy#632]
Hi
where can I set the width of the tables
![image](https://user-images.githubusercontent.com/4120266/77210977-a759ac80-6b02-11ea-9360-bff6daf218da.png)

Would like to have the left one wider
and get rid oft the column
![image](https://user-images.githubusercontent.com/4120266/77211122-32d33d80-6b03-11ea-953e-a6db3bb50a4d.png)

PS: Is this the right place for such questions?

**Comment by berrnd** [comment]
Also possible of course with [custom CSS](https://github.com/grocy/grocy#adding-your-own-css-or-js-without-to-have-to-modify-the-application-itself)...

If you remove the right column / recipe card, you have no way to display, edit or delete a recipe - I don't really understand some of your "customization" requests, maybe think through it completely before... ;D

**Comment by berrnd** [comment]
Sorry, have read your request wrong - you only mean to make the "Desired servings" columns wider...

So yes, use custom CSS, but I have no time to figure out all needed CSS...

**Comment by witzker** [comment]
THX
I'm not clever enough to check this CSS

Hope someone can help
