### ISSUE TITLE
Head navbar overlaps page headline on small screens (iPhone SE)

### ISSUE THREAD

**Issue by lucasverra** [grocy/grocy#635]
![ADBF4E0D-DED0-43B2-B504-6D219947DAAF](https://user-images.githubusercontent.com/11323803/77230900-e71ea380-6b97-11ea-92f3-9f84a4fb3b65.png)

**Comment by berrnd** [comment]
Would be very kind to specifiy what's incorrect, but you probably mean the overlapping head navbar.

Of course your screen is too small, and of course this could be improved - but please don't take the demo as a reference for UI bug reporting in general - for this example the "Demo" label is added which removes space that's normally available. And maybe just hide the clock and it would already work for you.

**Comment by lucasverra** [comment]
That is exactly what i was going for. 
OK for demo string to be removed on a “regulal” deploy

**Comment by berrnd** [comment]
I decided to not change anything about this. When the clock is shown, the navbar only gets second line below a width of 322px, that should also be enough for an iPhone SE. The clock fits perfectly on that side, when there is no "Demo" string.
