### ISSUE TITLE
Auth via curl

### ISSUE THREAD

**Issue by JmzTaylor** [grocy/grocy#642]
I was wondering what the POST URL and params would be to authenticate via curl if thats even possible.  I'm not overly familiar with JS.

**Comment by berrnd** [comment]
Everything is described on the [`/api`](https://demo.grocy.info/api) page and you also can play around and generate CURL requests there...

> Authentication is done via API keys (header GROCY-API-KEY or same named query parameter), which you can manage [here](https://demo.grocy.info/manageapikeys).
> Additionally requests from within the frontend are also valid (via session cookie).

Example:
`curl -X GET "https://demo.grocy.info/api/objects/products" -H  "accept: application/json" -H  "GROCY-API-KEY: whateveryourapikeyis"`
