### ISSUE TITLE
Feature Request: Magento/WooCommerce integration

### ISSUE THREAD

**Issue by dimitrismv** [grocy/grocy#643]
Would be a nice advanced feature to be able to purchase / increase stock not by manual entry of individual items but rather by picking items from a Magento/WooCommerce datafeed (assuming the eshop provides such a link e.g. in xml or json format). The datafeed import functionality already exists in WooCommerce extension WP All Import (I'm mentioning it as a guide for reference). Once the order arrives the stock can go up across all products in it.

Leaving it here as an idea if anyone want to work on it

**Comment by berrnd** [comment]
Something like that is up to an separate external tool (using [the API](https://demo.grocy.info/api)).
