### ISSUE TITLE
UI-Bug: Create Chore > Assign to > Clicking on Users does not select them (Chrome/Safari)

### ISSUE THREAD

**Issue by dshafik** [grocy/grocy#645]
When creating a Chore, clicking Assign to a user, and then clicking one or more users from the list does not select them.

Select All and Deselect All buttons work, which means a _workaround_ is to search for the individual and when only those you want are visible Select or Deselect All.

Both (latest) Safari and Chrome

**Comment by berrnd** [comment]
Whatever this is, can't reproduce it on Firefox...

**Comment by berrnd** [comment]
Can't reproduce this on Chrome 80:

![grafik](https://user-images.githubusercontent.com/2161815/79098812-0a85da00-7d63-11ea-9777-041b0579a0c8.png)

If there is a reproducible way, feel free to reopen this.
