### ISSUE TITLE
Track shipments and auto detect  deliveries?

### ISSUE THREAD

**Issue by hlopez058** [grocy/grocy#647]
Could I track package shipments made through amazon or usps? Also maybe even tap into delivery services like shipt to know what the items are and I won’t have to rescan them into the app.

**Comment by berrnd** [comment]
1. Add a Userfield to the shopping list where you put in the tracking link
2. Use the normal shopping-list-to-stock-button to add it to stock

![grafik](https://user-images.githubusercontent.com/2161815/77316110-10ab0c80-6d09-11ea-9c2e-95b30e873e96.png)

For more integration, please describe more detailed what you want and how you expect it to work.
