### ISSUE TITLE
NginX /location/ works but without img, css and js

### ISSUE THREAD

**Issue by AlphaJack** [grocy/grocy#648]
I'm trying to selfhost grocy under the subdirectory [/grocy/](), I can move between [/grocy/stockoverview]() and [/grocy/calendar]() etc., but it won't load any css, image or script.  

I've installed it from the [AUR](https://aur.archlinux.org/packages/grocy/), here is my configuration:
`/etc/webapps/grocy/config.php`
```php
Setting('MODE', 'demo');
Setting('BASE_PATH', '/grocy');
Setting('BASE_URL', '/grocy');
```
`/etc/nginx/nginx.conf`
```nginx
[...]
http {
    server  {
        listen 443 ssl http2 default_server;
        [...]
        location /grocy/ {
            proxy_pass http://127.0.0.1:5555;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
            proxy_buffering off;
           proxy_request_buffering off;
        }
        [...]
    }
    server  {
        listen 127.0.0.1:5555;
        root /usr/share/webapps/grocy/public/;
        index index.php;
        location /  {
            try_files $uri /index.php$is_args$query_string;
            add_header X-Content-Type-Options "" always;
        }
        location ~* \.(php|inc)$    {
            include fastcgi.conf;
            fastcgi_pass 127.0.0.1:9000;
            fastcgi_index index.php;
            fastcgi_buffer_size 16k;
            fastcgi_buffers 4 16k;
        }
    } 
}
```
`/etc/systemd/system/php-fpm.service`
```ini
[...]
ReadWritePaths=/usr/share/webapps/grocy/data/
[...]
```
---

URLs are generated like this:
```html
<link rel="icon" type="image/png" sizes="16x16" href="/grocy/img/appicons/favicon-16x16.png?v=2.6.1">
<link rel="manifest" href="/grocy/img/appicons/site.webmanifest?v=2.6.1">

[..]
<li class="nav-item nav-item-sidebar" data-toggle="tooltip" data-placement="right" title="Stock overview" data-nav-for-page="stockoverview">
    <a class="nav-link discrete-link" href="/grocy/stockoverview">
        <i class="fas fa-box"></i><span class="nav-link-text">Stock overview</span>
    </a>
</li>
```
If I try to open [/grocy/img/appicons/favicon-16x16.png?v=2.6.1]() I get:
```
Type: Slim\Exception\HttpNotFoundException
Code: 404
Message: Not found.
File: /usr/share/webapps/grocy/vendor/slim/slim/Slim/Middleware/RoutingMiddleware.php
Line: 93
```

If I try to change 'BASE_URL' to "/grocy/public/", where the static assets seems to be located, I get the above error anyway, and I also get that error with the previously working URLs like  [/grocy/calendar]().  

This is what I see under [/grocy/calendar]()
![calendar](https://user-images.githubusercontent.com/19962243/77331222-558a6f80-6d18-11ea-840d-12b9350f8876.png)

---
**EDIT** I get the same results with
`nginx.conf`
```nginx
[...]
        location /grocy/ {
            proxy_pass http://127.0.0.1:5555/grocy/;
[...]
        location /grocy/  {
            try_files $uri /index.php$is_args$query_string;
[...]
```

**Comment by berrnd** [comment]
The example above `Setting('BASE_URL', '/');` states that this needs to be the full URL, please check that.

**Comment by AlphaJack** [comment]
> 
> 
> The example above `Setting('BASE_URL', '/');` states that this needs to be the full URL, please check that.

If I set 'BASE_URL' to "/", and go to [/grocy/]() (with or without trailing slash)
- I get a 302 (found) from [/grocy]() 
- I get redirected to [/stockoverview]()
- I see my website 404 page, because that resource doesn't exist

If I go directly to [/grocy/stockoverview]() instead,
- the page loads exactly like the [/grocy/calendar]() one I took a screenshot of
- the URLs are now generated with the full domain without the [/grocy/]() location, like 
```html
<link rel="icon" type="image/png" sizes="16x16" href="https://example.com/img/appicons/favicon-16x16.png?v=2.6.1=>
```
- they return my website 404 page

**Comment by berrnd** [comment]
Again, based on the example in the comment in `config-dist.php`:
`BASE_URL` should be `https://example.com/grocy`.

**Comment by AlphaJack** [comment]
I've already tried it, but unfortunately that's not the issue.  
I finally found a way to make it work: remove the `BASE_PATH` and add a trailing slash in the `proxy_pass` directive.
These are the changes I made to my original configuration in the first post, if someone else can test this subdirectory configuration I think it may be an useful addition to the community installation guides.  

`/etc/webapps/grocy/config.php`
```php
Setting('BASE_PATH', '');        # left it empty, resources will be loaded from 127.0.0.1:5555/
Setting('BASE_URL', '/grocy');   # needed to generate URLs that match the NginX location below
```
`/etc/nginx/nginx.conf`
```nginx
[...]
        location /grocy/ {       # location of the public 0.0.0.0:443 server
            proxy_pass http://127.0.0.1:5555/; #added the trailing slash here
[...]
        location /  {            # location of the internal 127.0.0.1:5555 server
            try_files $uri /index.php$is_args$query_string;
[...]
```

**Comment by berrnd** [comment]
Thanks for the feedback.
