### ISSUE TITLE
CentOS 7/8 not loading

### ISSUE THREAD

**Issue by andrewm659** [grocy/grocy#650]
I am trying to get this working on CentOS 7/8 and seem to be running into some difficulty.  SELinux is enforcing mode.  The firewall is opened to allow the ports through.  I have gone through and allowed the folders access to system_u:object_r:httpd_sys_rw_content_t:s0.  However it doesn't load when I refresh the site.  I thought maybe index.php not having a execute permission might be the issue but it is not.  Nginx logging is set to debugging but i'm not seeing ANY errors in the nginx logs.  I haven't checked for php-fpm logs.  I am using php73 from remi repo.  I can provide more information such as config files and what not.  But I think I have it setup correctly.

**Comment by berrnd** [comment]
>  I haven't checked for php-fpm logs

If any, the useful information would be there.

Check that all required php extions (pdo_sqlite, fileinfo, gd) are installed. grocy is not different than any other PHP application.

Maybe also better ask this on the [subbredit](https://www.reddit.com/r/grocy/), I think you would potentially reach more who could help there....

**Comment by andrewm659** [comment]
So I didn't do a FULL due-diligence on this prior to posting something.  But I did miss some booleans in SELinux.  All of these are now allowing traffic to pass through.

httpd_can_network_connect=1 httpd_can_network_connect_db=1 httpd_can_network_relay=1

But it still isn't working.  I will check the other logs like you suggested.

**Comment by JamesHarrison** [comment]
Make sure your php-fpm user (not usually the nginx user) is able to write to the data folder. You only need httpd_user_rw_content_t on the data folder.

**Comment by andrewm659** [comment]
So I have the SELinux context correct.  However I'm not sure what to do for the php-fpm user.

**Comment by JamesHarrison** [comment]
`chown nginx:php-fpm -R data`?

Also, for reference, if you get this bit working you're going to hit an issue on CentOS 7 where grocy has a need for SQLite >3.8.3 to support recursive CTEs, and CentOS 7 has only 3.7.7. So you'll end up doing Docker anyway. CentOS 8 should work, I think.

**Comment by andrewm659** [comment]
```
# chown nginx:php-fpm -R data
chown: invalid group: ‘nginx:php-fpm’

```

**Comment by berrnd** [comment]
Closing this here for now, please use the [subbredit](https://www.reddit.com/r/grocy/) if any more help is needed on this.
