### ISSUE TITLE
Tables: accent insensitive search

### ISSUE THREAD

**Issue by berrnd** [grocy/grocy#654]
> I've found [a plugin](https://datatables.net/plug-ins/filtering/type-based/accent-neutralise#Version-control).

_Originally posted by @luismanson in https://github.com/grocy/grocy/issues/651#issuecomment-603256209_

**Comment by berrnd** [comment]
This is now done, //CC @luismanson.

**Comment by albarreto** [comment]
I also can't search strings with accents.
A solution would be to create a function that replaces that letters and the search compare "func(input) = func(db field)"?

**Comment by berrnd** [comment]
> I also can't search strings with accents.

This was exactly about that. Already implemented (since this here is closed) as of [v2.7.0](https://grocy.info/changelog#v2.7.0).

Provide a reproducible (!) example if you think you've found an issue and don't (!) spam old threads.
