### ISSUE TITLE
Feature Request: Button to clear search field/bar

### ISSUE THREAD

**Issue by BlizzWave** [grocy/grocy#656]
Would it be possible to implement a "X" or similar to clear the search field/ bar? 
Picture underneath as an example:

![feature](https://user-images.githubusercontent.com/6298655/77436172-753a9a00-6de3-11ea-911a-09f5fdc67820.JPG)

**Comment by berrnd** [comment]
Sure, like we already have it for example with the up/down buttons on number inputs.

https://getbootstrap.com/docs/4.1/components/input-group/#button-addons

**Comment by BlizzWave** [comment]
Yeah, that would be perfect.

Bigger up and down buttons was my request from the early days of grocy #44. Haha

> Sure, like we already have it for example with the up/down buttons on number inputs.
> 
> https://getbootstrap.com/docs/4.1/components/input-group/#button-addons

**Comment by renarena** [comment]
+1 for this.
I am more for a little x inside the search field

**Comment by berrnd** [comment]
There is now a "Clear filter" button on all pages with filters.
