### ISSUE TITLE
UI bug: Stock overview -> 3 dots menu

### ISSUE THREAD

**Issue by notDavid** [grocy/grocy#659]
Hi there, this is what i see on my iPhone X, is this a bug or... some configuration/installation issue? I'm running https://github.com/linuxserver/docker-grocy version 2.6.1

Also, if in Safari you tap `share > Add to Home screen` and start the app from the home screen (instead of opening the url in Safari), the screen size is a little different and the problem seems even worse.

![IMG_6529](https://user-images.githubusercontent.com/1530401/77562389-db90ec80-6eb7-11ea-9c1b-5ed17009bbe9.png)

![IMG_6530](https://user-images.githubusercontent.com/1530401/77562726-4e01cc80-6eb8-11ea-9603-ac5b376619a5.png)

**Comment by berrnd** [comment]
#633 improved the ellipsis menu for small devices (not yet released), maybe check the [pre-release demo](demo-prerelease.grocy.info/) to verify if that helps.

Another issue about Safari when using "Add to home screen" has been reported here: https://www.reddit.com/r/grocy/comments/fmk6ni/barcode_scanner_fails_on_ios_when_grocy_is/

Maybe a problem, maybe a limitation of Safari. Contributions to improve this while not breaking other browsers are welcome, I personally don't use any iOS device...

**Comment by notDavid** [comment]
@berrnd the pre-release demo seems to work better indeed. Thanks :)
