### ISSUE TITLE
404 Not Found - Slim\Exception\HttpNotFoundException

### ISSUE THREAD

**Issue by Hotfirenet** [grocy/grocy#661]
Hello,
I am making a plugin for the Jeedom home automation system. I'm looking to install grocy from the plugin.
Grocy can be found in the 3rdparty directory. Installed from https://releases.grocy.info/latest.

I want have this url:

> http://myinstancesmarthome/grocy

<img width="1264" alt="image" src="https://user-images.githubusercontent.com/2387292/77579964-7bac3d00-6edb-11ea-835d-60c6c53b0e5c.png">

here is the apache configuration:

```
<VirtualHost *:80>
        ServerAdmin webmaster@localhost
        DocumentRoot /var/www/html
        ErrorLog /var/www/html/log/http.error

	Alias /grocy /var/www/html/plugins/grocy/3rdparty/grocy/public

	<Directory /var/www/html/plugins/grocy/3rdparty/grocy/public>
		Options Indexes FollowSymLinks MultiViews
		AllowOverride All
		Order allow,deny
		allow from all
	</Directory>

       ProxyPass /grocy/ http://localhost/plugins/grocy/3rdparty/grocy/public/
       ProxyPassReverse /grocy/ http://localhost/plugins/grocy/3rdparty/grocy/public/
</VirtualHost>
```

If i check the documentroot with php since index file, i have:
`/var/www/html`

my data/config.php

```
Setting('BASE_PATH', '/var/www/html/plugins/grocy/3rdparty/grocy/');

Setting('BASE_URL', '/grocy');

Setting('DISABLE_URL_REWRITING', true);
```

Have you got any idea ?

Thanks

**Comment by berrnd** [comment]
Please check the latest issues about subdirectory problems here and on reddit, has been discuess lately a lot...

#623

#619

**Comment by Hotfirenet** [comment]
> Please check the latest issues about subdirectory problems here and on reddit, has been discuess lately a lot...
> 
> #623
> 
> #619

I already read these topics, but they did not give me an answer :(
I think my problem is different because I use apache in proxy pass mode

Thans @berrnd

**Comment by berrnd** [comment]
I think the [subbredit](https://www.reddit.com/r/grocy/) is the better place to ask for setup problems and most probably your reach more who could help there...

**Comment by berrnd** [comment]
I've finally made some own test. It works. Maybe someone can verify this, see #694.

**Comment by berrnd** [comment]
The general problem about subdirectory installations is now resolved (in fact there was never an issue, it was just unclear how to configure everything properly).

See for Apache: https://github.com/grocy/grocy/issues/694#issue-592850273

See for nginx: https://github.com/grocy/grocy/issues/694#issuecomment-609079721

For specific setups / shared hosting environments / etc., please better ask this on [the subbredit](https://www.reddit.com/r/grocy/) if there are still problems.
