### ISSUE TITLE
Feature Request: Barcode lookups, nutrition information and planning, existing recipe databases, online shopping integration, documentation, chat and API.

### ISSUE THREAD

**Issue by aindilis** [grocy/grocy#663]
Hi,

I have been working on a similar program for some time now ( https://github.com/aindilis/free-life-planner ), but grocy is definitely ahead of mine in a great many important areas.  Therefore, I'm going to share all the feature requests that I can think of that I've been trying to do with my software, in the hopes that they are of use here to you and your user base.

I like many others have trouble understanding how grocy works because of the lack of documentation.  I would like to find or create a chat room on like slack and/or discord and/or IRC where people can discuss.  I am close to volunteering to write the documentation for grocy but I don't know how to use the system yet and so there is a chicken and egg problem.  One thing that would help would be hover-over explanations of fields.

I didn't see anything about serving size / number of servings per individual product.  I know the nutritionix API includes serving size information for a great many products.

https://www.nutritionix.com/
https://api.nutritionix.com/v1_1/item?upc=$barcode&appId=$appid&appKey=$appkey

This outputs JSON.  I believe there is a cost, but a free tier.

I use a metric PDDL planner (OPTIC_CLP):
https://nms.kcl.ac.uk/planning/software/optic.html

to select ingredients that meet nutrition profiles:
https://frdcsa.org/~andrewdo/WebWiki/MealPlannerUpdate.html

There is also 

https://www.upcindex.com/
https://www.upcindex.com/$barcode

For product information, including pictures.  Again a proprietary service I believe.

Another feature would be MealMaster or RecipeML import.  There are several sites that have large databases of recipes (> 600K recipes).

Someone said there there was a 50GB dump of RecipeML recipes floating around on r/DataHoarder but I could not find it.

Here are some others:

http://thehoseys.org/buster/recipes.html
http://www.ffts.com/recipes/
http://dsquirrel.tripod.com/recipeml/indexrecipes2.html
http://lizquilty.com/uploads/recipes/

I have written an importer and could export to whatever format you need.

One thing I am working on is normalizing everything to match barcodes to products to ingredients in recipes, in order to generate meal plans based on what you have in inventory

Another thing I wasn't quite sure of was is whether you can have non-food items in your inventory, for instance, cat litter.  I am interested in that use case, to keep stock of and reorder different products like that.

A useful feature would be tracking of online orders and QFX/OFX/etc support to sync between your bank accounts and purchases, along with tracking of shipment arrival date.  In the time of Coronavirus it would be nice to have the ability to track packages in quarantine.

If there isn't one already, an external API to access your system from other systems would be useful.

Okay that's it for now.  I will post more ideas as I can recall them.

**Comment by berrnd** [comment]
Thanks for your input, but please split this up in separate issues per topic or add your ideas to existing ones - it's absolutely chaotic and untrackable to have this all in one ticket. So just some comments here:

> I like many others have trouble understanding how grocy works because of the lack of documentation.

Feel free to to contribute this. I have no time for that beside that documention is not my favorite thing to do, existing issue = #365.

Issues about import stuff:
#451, #445, #210, #158

> Another thing I wasn't quite sure of was is whether you can have non-food items in your inventory,

Why not? Products can have a best before date of "never"...

> If there isn't one already, an external API to access your system from other systems would be useful.

Sure there is an API, for everything, it's also used for (nearly) everything the UI does: https://demo.grocy.info/api
