### ISSUE TITLE
Putting grocy in subdomain results in "error while saving"

### ISSUE THREAD

**Issue by t3pfaffe** [grocy/grocy#664]
When accessing grocy to the direct IP of the docker server nothing is wrong. However, when accessing it behind a subdomain (like "grocy.websiste.com") every reload results in `"error while saving, probably this item already exists"` an expansion on this error just shows "` \n\r\n\r\n 405 Not Allowed \r\n nginx/1.16.1 \r\n\r\n\r\n"`

**Comment by berrnd** [comment]
Is this [grocy-docker](https://github.com/grocy/grocy-docker) related? Then please report it there.

`405 Not Allowed` just means than anything blocks an API request, the API uses `GET`, `POST`, `PUT` and `DELETE` requests.

**Comment by therealklanni** [comment]
I have the same issue, but only on the website (I have https://grocy.website.com), but does **not** happen in the Android app (works fine).

**Comment by berrnd** [comment]
Then please check the browser console what API get used, maybe the URL is wrong (based on the `config.php` setting `BASE_URL`) or if the request (method) gets blocked, then it would be something about your webserver...

**Comment by t3pfaffe** [comment]
The issue in my case was resolved with removing Nginx rules that restricted the range of http methods available. I believe I was blocking anything not GET HEAD or POST. I had to remove this restriction to alleviate the error.
