### ISSUE TITLE
Feature Request: Inventory location

### ISSUE THREAD

**Issue by Stoicmaverick** [grocy/grocy#670]
Part of the reason I checked it out was that I want to do stock location and lookup of all my small electrical complainants. Is there a way to (or could there be?) to have a dedicated panel or tab where I can start to type, say: "10k resistors" and it will pop up with inventory count, draw one from stock, and list the drawer or compartment number I have them stored in (for instance Drawer 2, Compartment C-9)? I suppose I COULD do it from the general stock search screen, and add all the drawer numbers as separate locations, but it would be nice if they were separate tabs, so that "Potentiometer" and "Pomegranate Juice" weren't right next to each other.

**Comment by berrnd** [comment]
If I understand it right, everyhting should be possible from the normal stock overview page. You can search there and consume/remove products.

If you mean nested locations, that's already tracked in #481.
As a workaround, maybe simply create separate locations for each drawer/compartment ("Drawer 2, Compartment C-9", Drawer 2, Compartment C-10", ...).

**Comment by berrnd** [comment]
> so that "Potentiometer" and "Pomegranate Juice" weren't right next to each other.

Because of that, maybe it would be really better to use separate instances of grocy - or #644.

**Comment by berrnd** [comment]
Because it came up again in #680, I created #682 to track to add the "tabs per location" idea for the stock overview page.
