### ISSUE TITLE
Feature Request: Barcode-Buddy like scan queuing

### ISSUE THREAD

**Issue by Stoicmaverick** [grocy/grocy#671]
The most useful thing about Barcode Buddy to me is actually the queuing functionality that's inherent to its design. When adding bulk items to the database, for instance after grocery shopping, It's convenient to be able to scan like 30 things without looking at the screen, and then manually enter all the details all at once. Could something like that be added natively? The two projects are so complementary, it seems they could be merged completely to greatly increase the "Wife-Acceptance-Factor" variable.

**Comment by berrnd** [comment]
If Barcode Buddy would be fully integrated, it would not be any different I would say - so I really don't see the point. I will never implement exactly the same what Barcode Buddy does, of course I'm open to integrate it in any way "natively".

But I'm also more than happy as it is now, a AddOn / helper application for grocy, thanks @Forceu for all the work on it.

I personally use grocy without Barcode Buddy and it works great, I have a cheap barcode laser scanner attached to a always on PC running grocy in my kitchen, most of the time the consume page is open with "Scan mode" on - so I just take the scanner, scan something => product removed incl. audio feedback, so I even don't need to look at the screen. But I see the points of Barcode Buddy (queuing like you mentioned and the Open Food Facts integration to lookup unknown barcodes). So I'm happy that it exists and helps a lot of grocy users.

**Comment by Uatschitchun** [comment]
@berrnd 
> incl. audio feedback

How's that done, if I may ask?

**Comment by berrnd** [comment]
> How's that done, if I may ask?

This is Open Source, why not just have a look yourself?

Example of the consume page:
The "success sound" is played after successfully submitting the form here:
https://github.com/grocy/grocy/blob/c483c345981be5c49353c50cea6befffe3d66e2e/public/viewjs/consume.js#L43-L47

Everything regarding audio is wrapped into the `UISound` component and is technically nothing more than playing a sound file:
https://github.com/grocy/grocy/blob/c483c345981be5c49353c50cea6befffe3d66e2e/public/js/grocy_uisound.js#L1-L26

**Comment by Uatschitchun** [comment]
> > How's that done, if I may ask?
> 
> This is Open Source, why not just have a look yourself?

Sorry, wasn't meant technical. Haven't used barcode scanning and thought having sounds needs some extra "tricks"
