### ISSUE TITLE
Stock entries page broken if there are product userfields defined

### ISSUE THREAD

**Issue by berrnd** [grocy/grocy#677]
_(Originally reported [here](https://www.reddit.com/r/grocy/comments/fmv6ee/stock_entries_page_blank/).)_

If there are product userfields with "Show as columns in tables", the stock entries page is broken / shows nothing (JS error).

Workaround to fix this immediately is to disable “Show as column in tables” for the userfield.

**Comment by keriati** [comment]
adding in the file **views/stockentries.blade.php** after line 152 the lines

    @include('components.userfields_tbody', array(
        'userfields' => $userfields,
        'userfieldValues' => FindAllObjectsInArrayByPropertyValue($userfieldValues, 'object_id', $stockEntry->product_id)
    ))

should make the feature work as intended. Only tested it with checkbox type user fields.
