### ISSUE TITLE
Allow fractional kcal for store units

### ISSUE THREAD

**Issue by towo** [grocy/grocy#678]
Cheers, I'm trying to input e.g. noodles with 350kcal/100g, but I'm using an easier to manage 1 pack ⇒ 500g purchase to storage unit conversion, and thus would need to enter the kcals for 1g, e.g. 3.5 kcal.

**Comment by berrnd** [comment]
That's already possible since https://github.com/grocy/grocy/commit/6f035fd64db6d540697c901bfc9debba48b56329 which is included in v2.6.0 and v.2.6.1.

Where/how does it not work?

**Comment by towo** [comment]
Entirely correct, I recently rolled back an update to 2.6.1 due to #568 also affecting me; it works with 2.6.0, though. Thanks!
