### ISSUE TITLE
Add a Notes Field to a recipe

### ISSUE THREAD

**Issue by midniteslice** [grocy/grocy#679]
Really digging Grocy, and appreciate the time that ya'll put into it. 
Would it be possible to add a Notes field to the recipes? I know there is a notes field for individual ingredients but not for the recipe itself. 
I have more than a few that have notes added and this would be helpful. 
Thank You!!!!
--Brian

**Comment by berrnd** [comment]
Is the general big "prepartion" field not enough for everything the recipe needs?

![grafik](https://user-images.githubusercontent.com/2161815/77947129-bb9c6700-72c3-11ea-84da-2621af9d24fa.png)

**Comment by midniteslice** [comment]
You know, and I'll be quite honest, I never thought of that. 
I apologize for the time waster.... :-/
Thank you berrnd.

**Comment by berrnd** [comment]
No problem, you're welcome. :)
