### ISSUE TITLE
Feature Request: location of 

### ISSUE THREAD

**Issue by dricetea** [grocy/grocy#680]
Hi, 
I put my whole pantry in grocy and fail at the simplest tasks... I have stored a product in 3 different places with different best before dates (BBD). Now when I want to take the item with the next BBD, I have to leave the Stock Overview and go to the Stock Entries list to see where the appropriate product is located. I also have to go back to the Stock Overview to remove one product. Or is there a easier way to do that?
It would be great if the Stock Overview would also list the storage location with the next expiring product... As already reported, in my opinion this BBD information is missing on the Location Content Sheets... It would also be helpful if the whole application could be more customized. For example, Stock Entries cannot be selected as a menu item, and the reports cannot be customized (without further efforts). 
I hope for improvement - or can this be accelerated with a donation?
Regards
Dr. Ice Tea

**Comment by berrnd** [comment]
There is the stock [overview page](https://en.demo.grocy.info/stockoverview):
One line per product, regardless in how many locations the product currently has stock.

There is the stock stock [entries page](https://en.demo.grocy.info/stockentries):
_(Button at the top of the stock overview page or shortcut from the "more menu" per product line.)_
Displays the "raw" stock entries, so basically how you put them into grocy via purchase/inventory, not grouped in any way, so separate lines per separate locations of the same product.

There is the [consume page](https://en.demo.grocy.info/consume):
You can select/scan a product there, selecte a location, or also a specific stock entry.

I personally only use and would go for the consume page to remove products from stock.

Somewhere was also the idea to (optionally) split up the stock overview in tabs per location. Maybe that's a good idea and would fit what you think of. (?)

> As already reported, in my opinion this BBD information is missing on the Location Content 

Yes, thanks, it's still there in #622.

> It would also be helpful if the whole application could be more customized

I think what you mentioned is maybe beyond what's simply possible with options. Of course it would be possible to customize everything by extensively using [custom CSS/JS](https://github.com/grocy/grocy#adding-your-own-css-or-js-without-to-have-to-modify-the-application-itself) and/or just modify the PHP/JS files directly (maybe a problem or at least things you would need to check on every update). I'm still open for ideas for general improvements, as always.

>  I hope for improvement - or can this be accelerated with a donation?

I will work on (nearly) every idea recorded in the issues here at some point in time. Or anyone else. grocy is still only my hobby. I prefer contributions in the form of help in code/translation/documentation or whatever you could help with. Financial donations will not speed up anything. I don't plan anyhting, that not fits a hobby in my opinion - and always say "It's ready when it's done, maybe tomorrow, maybe tomorrow next year" (and yes, we had both timespans for requested features already).

**Comment by dricetea** [comment]
Thanks a lot for all the explanations. I totaly missed the function Consume... yeah! this is a much easier approach...
Tabs would also be a good approach - making the thing more clearly arranged. 
I took already a deeper look into the printout and I have given up...
I appreciate your work and look forward to the next updates!

**Comment by berrnd** [comment]
Then let's catch up the "tab per location" idea, I created #682 to track this.
