### ISSUE TITLE
CORS Misconfiguration

### ISSUE THREAD

**Issue by arjes** [grocy/grocy#681]
Hello,

I am working with some of the Grocy API's and am running into CORS issues. I see from this line https://github.com/grocy/grocy/blob/master/routes.php#L252 that you are adding some middleware to handle the request, but OPTIONS requests are all failing.

Making a request to `OPTIONS http://localhost/api/objects/locations` results in a response of `Allowed methods: GET, POST`.

I got this error or a similar one using the LinuxServer and the grocy provided docker images

**Comment by arjes** [comment]
For more context, when making this request from the browser via JS AJAX I'm getting a response of:

```
HTTP/1.1 200 OK
Allow: GET, POST
Content-Encoding: gzip
Content-Type: text/html;charset=UTF-8
Date: Mon, 30 Mar 2020 22:38:30 GMT
Server: nginx/1.16.1
X-Powered-By: PHP/7.3.15
Content-Length: 814
```

which lacks the required CORS headers

**Comment by arjes** [comment]
Another follow up, this issues looks similar: https://github.com/tuupola/cors-middleware/issues/46

I can however verify that PHP is reached since I get this response:
```json
{
    "message": "405 Method Not Allowed",
    "exception": [
        {
            "type": "Slim\\Exception\\HttpMethodNotAllowedException",
            "code": 405,
            "message": "Method not allowed. Must be one of: GET, POST",
            "file": "/app/grocy/vendor/slim/slim/Slim/Middleware/RoutingMiddleware.php",
            "line": 96
        }
    ]
}
```

With this request:

```
curl --location --request OPTIONS 'http://localhost/api/objects/locations' \
--header 'Accept: application/json' \
--header 'Access-Control-Request-Headers: content-type' \
--header 'Access-Control-Request-Method: POST' \
--header 'Origin: http://fghhjghjg.com'
```

This request was made to be as close as possible to the request made by the browser

**Comment by berrnd** [comment]
I will try to reproduce the problem about the failing `OPTIONS` request later.

But sure that we need to add the other possible request methods to https://github.com/grocy/grocy/blob/8e8252573215b76b1632100de86a83e66f7afeeb/routes.php#L254 (we originally only had `GET` and `POST` routes for the API) - thanks for finding that.

**Comment by bmalinconico** [comment]
Let me know if i can be of any help. It has been a decade since I've used php, so I solved it on my local install by letting nginx respond tonthe requests.

**Comment by berrnd** [comment]
I can reproduce it, but haven't found a solution yet - seems that something has changed with Slim 4 here (Slim Framework was upgraded from v3 to v4 with the grocy v2.6.1 release).

**Comment by mrdarrengriffin** [comment]
Just to pitch in on this. I am having the same issue using Javascript via Angular.

**Comment by berrnd** [comment]
I've reimplemented this now by a own Middleware, mostly based on http://www.slimframework.com/docs/v4/cookbook/enable-cors.html.

The example request
```
curl -v --location --request OPTIONS 'https://demo-prerelease.grocy.info/api/objects/locations' \
--header 'Accept: application/json' \
--header 'Access-Control-Request-Headers: content-type' \
--header 'Access-Control-Request-Method: POST' \
--header 'Origin: http://fghhjghjg.com'
```

now returns
```
< HTTP/2 200
< server: nginx
...
< access-control-allow-origin: http://fghhjghjg.com
< access-control-allow-methods: GET,POST,OPTIONS
< access-control-allow-headers: Content-Type,GROCY-API-KEY
...
```

I think this is ok...

**Comment by arjes** [comment]
I just sent an options request to `https://demo-prerelease.grocy.info/api/objects/locations`  It looks like `Access-Control-Allow-Origin` is being sent back as blank.

**Comment by berrnd** [comment]
It currently sends back the request header `Origin` for `Access-Control-Allow-Origin`, here:
https://github.com/grocy/grocy/blob/7fb76df33a6c27a647469b66246cea5296872e4b/middleware/CorsMiddleware.php#L20-L24

Don't know if this is common / how it should be done, however, will change it to return `*`...

**Comment by arjes** [comment]
You can just send `*` back, sending origin back is only required if you want to limit the allowed domains

**Comment by berrnd** [comment]
So I just changed the headers and status code to return exact the values provided by @GerardRibas above, it's already live on the pre-release demo, `curl` example:

```
curl -v --location --request OPTIONS 'https://demo-prerelease.grocy.info/api/objects/locations'
```

Returns:
```
...
< HTTP/2 204
< server: nginx
< date: Tue, 21 Apr 2020 19:16:48 GMT
< access-control-allow-origin: *
< access-control-allow-methods: GET, POST, PUT, DELETE, OPTIONS
< access-control-allow-headers: *
...
```

But the provided stackblitz.com example above still fails, I don't know what's still wrong...

**Comment by arjes** [comment]
The stackblitz error is occurring due to the Same-origin policy, a policy which limits frame behavior. Its likely protection for StackBlitz from being used maliciously.

You can open a console and run:

```
let y = new XMLHttpRequest();
y.open('GET', 'https://demo-prerelease.grocy.info/api/objects/locations')
y.setRequestHeader("Content-Type", "application/json")
y.setRequestHeader("GROCY-API-KEY", "1")
y.send()
```
and see the options request and get request succeed.

**Comment by berrnd** [comment]
This should now be finally fixed, the `Access-Control-Allow-Origin` apparently needs also be included in content responses, not only for the `OPTIONS` request...

Both provided examples above (test via browser console & StackBlitz) work now.

If you want to have it now, replace [`middleware/CorsMiddleware.php`](https://raw.githubusercontent.com/grocy/grocy/master/middleware/CorsMiddleware.php) and [`middleware/JsonMiddleware.php`](https://raw.githubusercontent.com/grocy/grocy/master/middleware/JsonMiddleware.php).

**Comment by winterscar** [comment]
Hey @berrnd, I just read through this thread, and despite me being on v2.7.1, the changes in those files weren't present for me. However, that may be a config issue on my part, or something to do with the fact that I'm using the ls.io docker container. 

_anyway_, I changed the files as you suggested, but I was still getting `cors` errors. The reason was because I was not authenticating (just to test the cors stuff), and the ApiAuthMiddleware doesn't serve `cors` tokens on failure.

So if you fail to auth (because you didn't provide/provided an invalid token, instead of getting an auth error, you'll get a `cors` one!

**Comment by berrnd** [comment]
Thank you, I created #861 to track that there.

**Comment by margani** [comment]
I am using the Windows desktop application:

```
Version 4.0.3
Released on 2023-09-02 4 months ago
PHP Version 8.2.9
SQLite Version 3.39.2
OS Windows NT 10.0 build 22631 (Windows 11) AMD64
Client Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/116.0.0.0 Safari/537.36
```

When I am sending the following request via Insomnia:

```
PUT http://192.168.0.11:4010/api/objects/products

{
  "id": 26,
  "name": "Lemon",
  "active": 1,
  "location_id": 4,
  "qu_id_purchase": 3,
  "qu_id_stock": 3
}
```

The response is `405 Method Not Allowed`:

```
{
  "error_message": "Method not allowed. Must be one of: GET, POST, OPTIONS",
  "error_details": {
    "stack_trace": "#0 C:\\Users\\<USER>\\AppData\\Roaming\\grocy-desktop\\runtime-dependencies\\2.7.0\\grocy\\packages\\slim\\slim\\Slim\\Middleware\\RoutingMiddleware.php(44): Slim\\Middleware\\RoutingMiddleware->performRouting()\n#1 C:\\Users\\<USER>\\AppData\\Roaming\\grocy-desktop\\runtime-dependencies\\2.7.0\\grocy\\packages\\slim\\slim\\Slim\\MiddlewareDispatcher.php(121): Slim\\Middleware\\RoutingMiddleware->process()\n#2 C:\\Users\\<USER>\\AppData\\Roaming\\grocy-desktop\\runtime-dependencies\\2.7.0\\grocy\\packages\\slim\\slim\\Slim\\Middleware\\ErrorMiddleware.php(76): Psr\\Http\\Server\\RequestHandlerInterface@anonymous->handle()\n#3 C:\\Users\\<USER>\\AppData\\Roaming\\grocy-desktop\\runtime-dependencies\\2.7.0\\grocy\\packages\\slim\\slim\\Slim\\MiddlewareDispatcher.php(121): Slim\\Middleware\\ErrorMiddleware->process()\n#4 C:\\Users\\<USER>\\AppData\\Roaming\\grocy-desktop\\runtime-dependencies\\2.7.0\\grocy\\middleware\\CorsMiddleware.php(27): Psr\\Http\\Server\\RequestHandlerInterface@anonymous->handle()\n#5 C:\\Users\\<USER>\\AppData\\Roaming\\grocy-desktop\\runtime-dependencies\\2.7.0\\grocy\\packages\\slim\\slim\\Slim\\MiddlewareDispatcher.php(269): Grocy\\Middleware\\CorsMiddleware->__invoke()\n#6 C:\\Users\\<USER>\\AppData\\Roaming\\grocy-desktop\\runtime-dependencies\\2.7.0\\grocy\\packages\\slim\\slim\\Slim\\MiddlewareDispatcher.php(65): Psr\\Http\\Server\\RequestHandlerInterface@anonymous->handle()\n#7 C:\\Users\\<USER>\\AppData\\Roaming\\grocy-desktop\\runtime-dependencies\\2.7.0\\grocy\\packages\\slim\\slim\\Slim\\App.php(199): Slim\\MiddlewareDispatcher->handle()\n#8 C:\\Users\\<USER>\\AppData\\Roaming\\grocy-desktop\\runtime-dependencies\\2.7.0\\grocy\\packages\\slim\\slim\\Slim\\App.php(183): Slim\\App->handle()\n#9 C:\\Users\\<USER>\\AppData\\Roaming\\grocy-desktop\\runtime-dependencies\\2.7.0\\grocy\\app.php(112): Slim\\App->run()\n#10 C:\\Users\\<USER>\\AppData\\Roaming\\grocy-desktop\\runtime-dependencies\\2.7.0\\grocy\\public\\index.php(45): require_once('...')\n#11 {main}",
    "file": "C:\\Users\\<USER>\\AppData\\Roaming\\grocy-desktop\\runtime-dependencies\\2.7.0\\grocy\\packages\\slim\\slim\\Slim\\Middleware\\RoutingMiddleware.php",
    "line": 79
  }
}
```

I can see [here](https://github.com/grocy/grocy/blob/99f448dd6476dda1ea71037c8af1daa5254c64af/middleware/CorsMiddleware.php#L31) that all methods are allowed. Am I missing something?

**Comment by berrnd** [comment]
> I am using the Windows desktop application

Please don't spam random threads, Grocy Desktop isn't even maintained here (ref. [grocy/grocy-desktop](https://github.com/grocy/grocy-desktop)).

Furthermore, this isn't related to CORS at all (what you're referring to with "all methods are allowed" is simply a HTTP header, what you get is a server error - two completely different and unrelated things). Also furthermore, Grocy Desktop is meant to be an alternative way to run Grocy, if you want to run it just like a normal desktop application - this excludes API usage by definition.

Lastly: Simply have another and deeper look at [/api](https://demo-prerelease.grocy.info/api#/Generic%20entity%20interactions/put_objects__entity___objectId_), choose the correct endpoint and be surprised that everything will work, even with Grocy Desktop - your example, but done right:

```
PUT http://192.168.0.11:4010/api/objects/products/26

{
  "name": "Lemon",
  "active": 1,
  "location_id": 4,
  "qu_id_purchase": 3,
  "qu_id_stock": 3
}
```
