### ISSUE TITLE
Errors in purchase with disabled FEATURE_FLAG_STOCK_PRICE_TRACKING

### ISSUE THREAD

**Issue by Mik-** [grocy/grocy#685]
I'm on current [master](https://github.com/grocy/grocy/commit/746203b82d4fbb046165ad6454622252e901b584).

I don't use stock price taking.
```php
Setting('FEATURE_FLAG_STOCK_PRICE_TRACKING', false);
```
If I try to account a purchase, after choosing the product, I get this error in the console:
```
Uncaught TypeError: Cannot read property 'SetId' of undefined
    at purchase.js?v=2.6.1:150
    at XMLHttpRequest.xhr.onreadystatechange (grocy.js?v=2.6.1:17)
```
(References [this line](https://github.com/grocy/grocy/blob/746203b82d4fbb046165ad6454622252e901b584/public/viewjs/purchase.js#L150)).

After filling in the form and hitting *OK*, this error appears:
```
purchase.js?v=2.6.1:32 Uncaught TypeError: Cannot read property 'GetValue' of undefined
    at purchase.js?v=2.6.1:32
    at XMLHttpRequest.xhr.onreadystatechange (grocy.js?v=2.6.1:17)
```

The OK button becomes pale and nothing else happens.

**Comment by berrnd** [comment]
Thanks, there was a new "price tracking per store" feature introduced a couple of days.

References #658 and #447.
