### ISSUE TITLE
Chore assignment not part of API?

### ISSUE THREAD

**Issue by zigurana** [grocy/grocy#693]
When using Grocy in Home-Assistant (under HASSIO), we rely heavily on the API to disclose information from Grocy on HA cards, notifications, etc.

Looking at the API demo (https://demo.grocy.info/api#/Chores/get_chores__choreId_), it looks like the chore assignment is currently not included (although the last person to execute the chore is).

Is this correct? I'd like to contribute, but will need some pointers to get started. Are there test-cases I could take a look at?

**Comment by berrnd** [comment]
[/api/chores](https://demo.grocy.info/api/chores) returns all chores including `next_estimated_execution_time` and `next_execution_assigned_to_user_id` (so basically what the [chores overview page](https://demo.grocy.info/choresoverview) shows).

The assignment is based on the "assignment type" configured for the specific chore, `POST /chores/executions/calculate-next-assignments` can be used to re-evaluate the next assignments for all chores.

If you want to edit the chore object itself, see the ["Generic entity interactions"-routes](https://demo.grocy.info/api#/Generic%20entity%20interactions).

Maybe that helps...

**Comment by zigurana** [comment]
Hey, thanks for the reply! 
It seems that `next_execution_assigned_to_user_id` is not used by either the custom component, or the UI-card. This is likely due to the added complexity when matching user_ids to readable user names. I will enquire further with those maintainers downstream.
