### ISSUE TITLE
Potential security issue / Content is rendered for 302 redirects

### ISSUE THREAD

**Issue by berrnd** [grocy/grocy#696]
Originally reported by @jayaddison in https://github.com/grocy/grocy-docker/issues/69#issuecomment-608518045.

When not authenticated, a redirect to `/login` is done (302 redirect/response). But the originally requested page is rendered and returned in the repsonse body (this repsonse body for a 302 redirect seems to be not shown in browsers, including their developer tools - just as a side note).

**Comment by berrnd** [comment]
@jayaddison: So should be already fixed by https://github.com/grocy/grocy/commit/2778d2ad5697ef293faffecd5365055a76a5be23 (also did some tests).

If you've found more, please comment here - otherwise I plan to release this in about 2 hours (only including this change compared to v.2.6.1, nothing else).

**Comment by jayaddison** [comment]
@berrnd Thanks for the swift fix.  Hold up - I have a slight improvement on this change.

**Comment by berrnd** [comment]
Turns out that his was only a problem since the upgrade of Slim Framework to v4. So only grocy v2.6.1 is affected.

The published release of v2.6.1 was replaced and contains this fix.
