### ISSUE TITLE
Expire severity

### ISSUE THREAD

**Issue by jglauche** [grocy/grocy#699]
I have tons of things at home that are past expire date, but they're still good. Most of them will be good for a long period of time (say, ketchup in the fridge, tea, rice, etc). 

Now on the other hand, I have things that expire but where this is more critical, say I open a package of milk or have meat in the fridge. On my installation, I currently have 31 'expired' products (of which 25 I don't care about if they expire), but the GUI is not useful for me to give me an overview what's both expired and critical at the same time, once they are past the best-before date. 

Is it a viable request to have like a 'best before date is important' checkbox for products? Does anyone have a good system for this short of changing the best-before dates of items that just slowly expire?

**Comment by msoups** [comment]
If the best before date isn't important why not set the "best before" to never expires or set the best before date to an estimated future date rather than rely on packaging?

**Comment by jglauche** [comment]
> If the best before date isn't important why not set the "best before" to never expires or set the best before date to an estimated future date rather than rely on packaging?

Basically I want to use the stock_log grocy makes productively at some point. It saves purchase date, best before date, use date and if it spoiled or not at that point .

Say to order things in bulk, to evaluate a purchase, I want to know: 
- How long does it last for me
- How long until they say it spoils (their best before date)
- How long is it safe to keep it until it spoils

It'll take a while before I get useful information from this of my grocy instance but it is already saving the information I need, considering I feed it with good data.

Maybe a field that sets a user estimated best before date will be good and buttons "this will be good for another [day], [week], [month], [year]" reachable from the stock overview.

**Comment by berrnd** [comment]
We have now the differentiation between expiry and best before dates, see https://github.com/grocy/grocy/issues/851#issuecomment-727619271.

Currently it's only used for different highlighting on the stock overview page.

What specific things about this topic should be added further?

**Comment by berrnd** [comment]
I'll close this for now, feel free to reopen it if something specific to this comes up.

Analysis things (more detailed spoil rate and stuff) will be tracked in #64.
