### ISSUE TITLE
update.sh has CRLF line endings and can't be executed in linux shell

### ISSUE THREAD

**Issue by keriati** [grocy/grocy#705]
When executing update.sh in a linux (bash) terminal, we get an error message:
    
    ./update.sh
    bash: ./update.sh: /bin/bash^M: bad interpreter: No such file or directory 

**Issue:**
The update.sh file has CRLF line endings.

**Solution:**
Change the line endings to from CR LF to LF.

**How to reproduce:**
Run update.sh in a linux (bash) terminal

**System Tested on:**

    Distributor ID: Ubuntu
    Description: Ubuntu 18.04.4 LTS

**Comment by berrnd** [comment]
Was already reported and fixed in #412, but seems that it's here again...
