### ISSUE TITLE
releases.grocy.info issue ?

### ISSUE THREAD

**Issue by Loxeno** [grocy/grocy#707]
Hi,

Is that normal that https://releases.grocy.info/v?2.6.2 gives content from this repo, but https://releases.grocy.info/latest gives the complete app ? 

I mean, with composer and yarn folders already in ?

By advance, thank you.

**Comment by berrnd** [comment]
https://releases.grocy.info/v?2.6.2 and https://releases.grocy.info/latest (currently) return the exact same ZIP file, the same ZIP is found (always) in the release assets (https://github.com/grocy/grocy/releases).

And yes, composer/yarn dependiencies are included there.

**Comment by Loxeno** [comment]
Not sure, I had some troubles installing the app until I found that I don't had the vendor folder via a PHP error.

**Comment by Loxeno** [comment]
I have re-test it and you're right, I don't understand why I had this error and assume wrongly.

Sorry for the inconvenience :s

**Comment by jayaddison** [comment]
@berrnd What do you think about archiving this issue in the `grocy/grocy` repo?  I don't think it related to anything regarding docker.

**Comment by jayaddison** [comment]
> @berrnd What do you think about archiving this issue in the `grocy/grocy` repo?

Thanks for applying the move :)
