### ISSUE TITLE
Show if already on shoping list

### ISSUE THREAD

**Issue by witzker** [grocy/grocy#708]
Hi
When looking through the items that has to be shopped (Bestand) it would be great to see if the product is already in a shopping list

![image](https://user-images.githubusercontent.com/4120266/78830588-7de8be00-79e8-11ea-9200-e050bdb3f459.png)

So if someone else already has put it in the list.

How can I get this?

**Comment by berrnd** [comment]
There is now a little icon next to the amount if the product is already on the shopping list (optionally, can be disabled in the stock settings / top right corner settings menu).

![grafik](https://user-images.githubusercontent.com/2161815/79139938-772ac400-7db7-11ea-822f-7a492250ee7d.png)
