### ISSUE TITLE
Feature Request: Night mode 

### ISSUE THREAD

**Issue by BlizzWave** [grocy/grocy#71]
Would it be possible to fade the look of grocy to a darker view at night?

Since I am running my kitchen tablet 24/7 it lights up the kitchen at night even with brightness at a minimum.

**Comment by BlizzWave** [comment]
This could most likely be done with css I assume?

**Comment by berrnd** [comment]
Yes, you can already add your own CSS by adding a file `data/custom_css.html` - the base template used is, beside Bootstrap, https://github.com/BlackrockDigital/startbootstrap-sb-admin.

**Comment by BlizzWave** [comment]
Yes, but that would change the look of grocy all the time? I would just like it to automatically change to "night mode" at a given time.

**Comment by berrnd** [comment]
Then some JavaScript would be needed to change it by time (`data/custom_js.html`)...

**Comment by BlizzWave** [comment]
Haha, thats beyond what I can figure out.

**Comment by berrnd** [comment]
If you put something together for the CSS part, I could do the JS part...

**Comment by BlizzWave** [comment]
That I can do!
Can you please add into the readme that the custom_css.html need to look like this:
Helpful to novices like me. haha
```
<style type="text/css">
custom css here
</style>
```

**Comment by berrnd** [comment]
Ok, will add some notices - the idea was to just have one file which content is added just before `</head>` and one just before `</body>`, that's why I changed the file extension some time ago to `.html` - you could add anything there, not just CSS/JS...

**Comment by BlizzWave** [comment]
I understand that now.

**Comment by BlizzWave** [comment]
Some progress. Remeber its not really going to be used like this. This is just at night when nobody is using it.

![night mode](https://user-images.githubusercontent.com/6298655/46224508-d997ad00-c356-11e8-8b12-501276243942.JPG)

**Comment by berrnd** [comment]
Cool! :)

Here an example JS with some comments how you can switch it automatically by a time range.

(Just saw that there is also an early API in [Firefox](https://developer.mozilla.org/en-US/docs/Web/API/DeviceLightEvent) and [Chrome](https://developer.mozilla.org/en-US/docs/Web/API/AmbientLightSensor) which can be used to do this by ambient light level (if the device has a sensor, most mobile device do)...)

#### data/custom_css.html
```css
<style id="nightmodestyle">

	.content-wrapper {
		background-color: darkgray;
	}
	
	/* ... */

</style>
```

#### data/custom_js.html
```js
<script>

	// Night mode time range
	const NIGHT_MODE_TIME_START = "20:00"; // Format HH:mm
	const NIGHT_MODE_TIME_END = "07:00"; // Format HH:mm


	window.GrocyNightModeStyleElementRemoved = false;
	function CheckNightMode()
	{
		// Create Moment.js objects for time range
		var start = moment(NIGHT_MODE_TIME_START, "HH:mm");
		var end = moment(NIGHT_MODE_TIME_END, "HH:mm");
		var now = moment();

		// When start time is later than end time,
		// the time range is going over midnight,
		// so the end time must be tomorrow
		if (start.isAfter(end))
		{
			end.add(1, "day");
		}

		if (now.isSameOrAfter(start) && now.isSameOrBefore(end)) // We're INSIDE of night mode time range
		{
			// Just reload the page to have the nightmode style element again
			// when it was removed before
			if (window.GrocyNightModeStyleElementRemoved)
			{
				window.location.reload();
			}
		}
		else // We're OUTSIDE of night mode time range
		{
			// Remove the night mode style element
			// if it was not removed before
			if (!window.GrocyNightModeStyleElementRemoved)
			{
				$("#nightmodestyle").remove();
				window.GrocyNightModeStyleElementRemoved = true;
			}
		}
	}

	// Run the function above on page load ...
	CheckNightMode();

	// ... and once every minute
	setInterval(CheckNightMode, 60000);

</script>
```

**Comment by BlizzWave** [comment]
Freaking sweet!! Will test later

**Comment by berrnd** [comment]
Hm, yes - that's always the tricky part ... tested it before midnight and there it worked ... when "start is later than end" it will set the end time to the next day - so it did:

```
Start 2018-09-29 20:00
End   2018-09-29 07:00
Start > End = End on next day => End 2018-09-30 07:00
```

Don't know how to deal with it spontaneously ... maybe simply two ranges for today and tomorrow...

**Comment by BlizzWave** [comment]
Theres also another issue with this. If you change pages it will first load the custom css (nightmode) and then regular grocy. This is also shown when grocy auto refreshes. 

I assume this happens because the custom_css loads before the JS?

**Comment by berrnd** [comment]
Yes, the nightmode CSS is always applied, then removed when outside night mode time range...

Would be of course better to have it as a own stylesheet (somewhere) and then load it by JS only when INSIDE night mode time range...

**Comment by BlizzWave** [comment]
Yes, thats why I initially asked for night mode and if we (I mean you. haha) should implement it to be a feature you could activate in grocy. 
I have the the custom css that I would share of course.

**Comment by berrnd** [comment]
Would be great when you could share it - I will find a propper way to include it - currently the only way is the time range way I think as the ambient light sensor API is too experimental currently (and not even enabled by default in Chrome/Firefox stable channel) - so need just to find a way how and where to configure this - currently the only place for settings is `config.php` which is not so user friendly - maybe it's time to give all "user space" settings a own settings page...

**Comment by BlizzWave** [comment]
I'm all for a simple setting page.

**Comment by BlizzWave** [comment]
Here's the night mode css.
We don't actually have anywhere to place it yet, so I'll leave that up to you. 
When you find a place we can to proper PR for it.

```
<style type="text/css">

body {
	color: #c1c1c1;
}

.table-info, .table-info>td, .table-info>th {
    background-color: #07373f;
}

.btn-info {
        color:#c1c1c1;
        background-color:#07373f;
        border-color:#07373f;
}

.btn-warning {
	color:#c1c1c1;
	background-color:#473604;
	border-color:#473604;
}

.btn-danger {
        color:#c1c1c1;
        background-color:#471116;
        border-color:#471116;
}

.btn-success {
        color:#c1c1c1;
        background-color:#0d3a18;
        border-color:#0d3a18;
}

.form-control {
	color: #495057;
	background-color: #333131;
  	border: 1px solid #ced4da;
}

.content-wrapper {
	background: #333131;
}

table.dataTable tr.group td {
	font-weight: bold;
	background-color: #333131;
}

.table-danger, .table-danger>td, .table-danger>th {
	background-color: #471116;
}

.table-warning, .table-warning>td, .table-warning>th {
	background-color: #473604;
}

.bg-warning {
	background-color: #473604!important;
}

.bg-info {
	background-color: #07373f!important;
}

.bg-danger {
	background-color: #471116!important;
}

.form-control:focus {
	color: #495057;
	background-color: #333131;
	border-color: #80bdff;
}

.dropdown-item:focus, .dropdown-item:hover {
	color: #16181b;
	background-color: #333131;
}

.dropdown-item {
   	color: #7c7b6f;
	background-color: #333131;
}

.list-group-item {
	background-color: #333131;
}

.modal-content {
	background-color: #1a1919;
	border: 1px solid rgba(186, 189, 189, 0.66);
}

.modal-footer {
	border-top: 1px solid #6f7173;
}

.container-fluid {
	background-color: #333131;
}

a.discrete-link:hover {
	color: #16354f !important;
	text-decoration: none !important;
	background-color: #333131;
}

a.discrete-link:focus {
	color: #3a0b0f !important;
	background-color: #333131;
}

.card {
	border: 2px solid;
	border-color: #383838;
	background-color: #333131;
}

.card-header {
	background-color: #333131;
}

/* Navigation style customizations */
#mainNav {
	background-color: #333131 !important;
	border-bottom: 2px solid !important;
	border-color: #383838 !important;
}

.navbar-sidenav,
.sidenav-second-level {
	background-color: #333131 !important;
	border-right: 2px solid !important;
	border-color: #383838 !important;
}

.navbar-nav .dropdown-menu {
	background-color: #333131 !important;
}

.navbar-nav .dropdown-divider {
	border-color: #383838 !important;
	background-color: #333131;
}

.sidenav-toggler {
	background-color: #383838 !important;
	border-right: 2px solid !important;
	border-color: #383838 !important;
}

.navbar-sidenav > li:hover,
.sidenav-second-level > li:hover,
.navbar-nav .dropdown-item:hover {
	box-shadow: inset 5px 0 0 #112a3f !important;
	background-color: #383838 !important;
}

.navbar-sidenav > li > a:focus,
.sidenav-second-level > li > a:focus,
.navbar-nav .dropdown-item:focus {
	box-shadow: inset 5px 0 0 #350a0f !important;
	background-color: #383838 !important;
}

.active-page {
	box-shadow: inset 5px 0 0 #350a0f !important;
	background-color: #383838 !important;
}

.toast-success {
	background-color: #092810;
}

.toast-error {
	background-color: #471015;
}

.typeahead .active {
	background-color: #333131;
}


</style>

```

**Comment by berrnd** [comment]
When I had a second look, I think all the other options currently in `config.php` are nothing a "user" should change, so maybe too early for a dedicated user options page...

Anyway, I did quick test implementation, see [pre-release demo](https://demo-prerelease.grocy.info):
- Placed your styles in a new stylesheet in [public/css/grocy_night_mode.css](https://github.com/berrnd/grocy/blob/cda3dde120dc857c1708ea7bc1a2600ae8760940/public/css/grocy_night_mode.css)
- Prefixed all of your rules with class `.night-mode`
- => So the stylesheet can always be included, to change to night mode it is only needed to apply `.night-mode` to `<body>`
- => A checkbox in the user menu to switch en-/disable night mode (currently remembered in local storage of the browser)

So open points regarding this are:
- [ ] Remember the setting server side (per user)
- [ ] Apply the `.night-mode` class to `<body>` already on server side when night mode is enabled (to prevent flickering)
- [ ] Add an option to automatically enable it between a time range

**Comment by BlizzWave** [comment]
Something weird is going on with the color of all the letters. Its defined in the "body" section in the css, but does not seem like its enforcing it. 
Load issue between pages are still there (temporarily switches from night mode to normal if night mode enabled)

**Comment by berrnd** [comment]
> Something weird is going on with the color of all the letters.

Ok, that was my fault I think ... CSS ... still not so my thing... :D

> Load issue between pages are still there

Yes, that's for the open point _Apply the `.night-mode` class to `<body>` already on server side when night mode is enabled (to prevent flickering)_

> What about language?
> Currency symbol?
> Also how often grocy should refresh and/or possibilty of disabling it.

The refresh thing - ok, but is language and currency really a per user setting? I would say that's per installation/household...

**Comment by BlizzWave** [comment]
> The refresh thing - ok, but is language and currency really a per user setting? I would say that's per installation/household...

You make a good point there sir. 

One thing about the refresh. I was adding a recipe just now. But I was interrupted by something. And since the refresh fired I lost everything I added (had not pressed save yet)

**Comment by berrnd** [comment]
I think I have it... :)

Maybe you can play around a little bit with it in the [pre-release demo](https://demo-prerelease.grocy.info) (the settings are behind the new dropdown next to the user dropdown)...

**Comment by BlizzWave** [comment]
Am I doing something wrong here?

![grocy_issue6](https://user-images.githubusercontent.com/6298655/46260058-9e75b500-c4e1-11e8-9866-eeca1d43daf3.gif)

**Comment by berrnd** [comment]
There was something wrong with the default values ... this example looks better now to me...

**Comment by berrnd** [comment]
Just off-topic:
Just noticed in your screenshot that we obviously have the same taste regarding some applications... :D

![firefox_2018-09-30_19-34-20](https://user-images.githubusercontent.com/2161815/46260599-5c03a680-c4e8-11e8-8736-d04c16e1639c.png)

**Comment by BlizzWave** [comment]
> There was something wrong with the default values ... this example looks better now to me...

You have cracked it! Seems okay now.


> Just off-topic:
Just noticed in your screenshot that we obviously have the same taste regarding some applications... :D

HAHA! Yes, Syncthing, NetSpeedMonitor, KeePass and f.lux.
The extra scary part is that I wondered if I would get a comments on the screenshot. 

I am a big fan of self host applications, hence KeePass, Syncthing and of course Grocy. 
f.lux I found because I got very used to RedShift on Linux.

**Comment by BlizzWave** [comment]
On topic again
Noticed theres a footer in the prerelease thats not styled correctly. 

Please add this to the night_mode CSS

```
footer.sticky-footer {
    background-color: #333131;
}
```

**Comment by berrnd** [comment]
Cool! And thanks again for the night mode style! :)

The footer is just added via `data/custom_js.html` for the demo ... so no need to include that I think...

**Comment by BlizzWave** [comment]
> Something weird is going on with the color of all the letters. Its defined in the "body" section in the css, but does not seem like its enforcing it.
> Load issue between pages are still there (temporarily switches from night mode to normal if night mode enabled)

The load issue is back again.

**Comment by berrnd** [comment]
Hm, cannot reproduce this on the pre-release demo and Firefox...

![2019-06-05_19-06-34](https://user-images.githubusercontent.com/2161815/58975424-30e2fc80-87c5-11e9-8d43-d123d5ccad6b.gif)

**Comment by BlizzWave** [comment]
![issue_nightmode](https://user-images.githubusercontent.com/6298655/58976009-b74c0e00-87c6-11e9-9c49-f7b6b4debc7c.gif)

Night mode is enabled, but not in active hours.

**Comment by berrnd** [comment]
Ok, but seems not be an issue when you just not set "Enable night mode"...

(So maybe we could just force this to be disabled when "Auto enable in time range" is set...)

**Comment by BlizzWave** [comment]
> (So maybe we could just force this to be disabled when "Auto enable in time range" is set...)

Yes, that would work.

**Comment by berrnd** [comment]
> How about adding automatic for the login screen? Blinding light, woof.

Currently if night mode is on or not is based on user settings, before logging in no user context is available and therefore no user settings.

However, to reduce that woof and to not start another great discussion about everything and the live with us, my only option was to implement that right away in 15ab198af0d2859d93f4863b98794a2b4f6f1da2. The login page now uses night mode if that's the system preferred color scheme.
