### ISSUE TITLE
Thread Count as setting

### ISSUE THREAD

**Issue by Belafestim** [grocy/grocy#713]
Good Day, i noticed that the thread count for the Barcode Scanner is adjustable in viewjs/components/barcodescanners.js but this is overwritten when running update.sh

Can you make it possible that the resolution and thread count can be adjustable in /data/ or possibly in the UI

FYI - i noticed a drastic improvement in barcode scans when i increased the thread count

**Comment by berrnd** [comment]
There is now a new `config.php` user setting for this and I also changed the default to `4`.

https://github.com/grocy/grocy/blob/f36d9c46ed0e8dde656f31898a24b90b83292bef/config-dist.php#L129

Additionally, I switched to Quagga2, see #579.

Maybe give it a short try on the [pre-release demo](https://demo-prerelease.grocy.info) if this improved something.

**Comment by Belafestim** [comment]
Im having some issues with the barcode scanner with the new update. it was working in pre-release a couple days ago though.

**Comment by berrnd** [comment]
Then please report the specific problems / reproducible bugs in a separate issue.

**Comment by berrnd** [comment]
Just to note that here: Using [QuaggaJS](https://github.com/serratus/quaggaJS) (master branch) again instead of [Quagga2](https://github.com/ericblade/quagga2) because of #749.
