### ISSUE TITLE
Need explaination on how stock, mealplan and shopping list are working

### ISSUE THREAD

**Issue by Loxeno** [grocy/grocy#717]
Hi, 

First of all, thank you for this software.

I don't understand if I'm correctly using Grocy or if it miss a "stock reservation" system based on mealplan.
Maybe I miss something or maybe these features are not implemented yet.

Multiple scenarios.

1.  
- Stock of product A = 0
- Quantity of product A in the shopping list = 0
- Quantity of product A in recipe 1 = 1
- Quantity of product A in recipe 2 = 2

Both of recipes is configured without "Do not check against the shopping list when adding missing items to it"

These two recipes is planned on the mealplan.

Adding Recipe 1 will add one unit : quantities on the shopping list = needed amount - stock - shopping list => 1 - 0 - 0 = 1
Adding Recipe 2 will add one unit => 2 - 0 - 1 = 1
Final stock = 1 + 1  = 2

I can consume Recipe 1 OR Recipe 2.
=> I expect to consume both, Recipe 2 should not take the unit on the shopping list in account nor the unit in stock, so use case n°2.

2.
- Stock of product A = 0
- Quantity of product A in the shopping list = 0
- Quantity of product A in recipe 1 = 1
- Quantity of product A in recipe 2 = 2

Both of recipes is configured with "Do not check against the shopping list when adding missing items to it"

These two recipes is planned on the mealplan.

Adding Recipe 1 will add one unit : quantities on the shopping list = needed amount - stock => 1 - 0 = 1
Adding Recipe 2 will add two unit : 2 - 0 = 2
Final stock = 1 + 2 = 3

I can consume Recipe 1 AND Recipe 2.
=> Ok, it works. Recipe 2 does not take in account what is on the shopping list. But there were no stock, so use case n°3.

3. Same as 2, but with a stock entry
- Stock of product A = 1
- Quantity of product A in the shopping list = 0
- Quantity of product A in recipe 1 = 1
- Quantity of product A in recipe 2 = 2

Both of recipes is configured with "Do not check against the shopping list when adding missing items to it"

These two recipes is planned on the mealplan.

Adding Recipe 1 will do nothing : quantities on the shopping list = needed amount - stock => 1 - 1 = 0
Adding Recipe 2 will add two unit : 2 - 1 = 1
Final stock : 1 + 1 = 2

I can consume Recipe 1 OR Recipe 2.
=> Not okay... You virtually take two unit of the product in account.

So what I think is that mealplan does not make a reservation on the stock, and adding a product on a shopping list is not based on the stock and the reservation.

I expect Grocy to make my shopping list based on my current stock and my mealplan.
I am missing something ?

Precision : my product is configured as follows :
- Purchase unit : pack
- Stock unit : piece
- Factor : 0.167 (1 pack is 6 pieces)

By the way, is there a way to change to inverse the of how quantity unit conversion works ?
In my case, it would be easier to configure 1 pack of 6 pieces instead of 1 pieces is 0.167 of a pack (eggs, in my case).

By advance, thank you.

**Comment by berrnd** [comment]
- The checks against the stock is done per recipe, not for multiple recipe at once
- The meal plan is internally a (nested) recipe per day and week, so the checks if everything for the whole week is in stock consider all planned recipes
- There are buttons to put everything missing for a recipe on the shopping list, which does that, no other cross-checks happen
- There is a button to put everyhting bellow the minimum stock amount, defined per product, on the shopping, also no other cross-checks (for planned recipes) happen

> By the way, is there a way to change to inverse the of how quantity unit conversion works ?
No, but maybe related to #388.

**Comment by Loxeno** [comment]
Hi @berrnd , thank you for your answers.

> The check against the stock is done per recipe, not for multiple recipes at once
You mean on the recipe menu ?

> The meal plan is internally a (nested) recipe per day and week, so the checks if everything for the whole week is in stock consider all planned recipes.
Okay, I understand what I was doing wrong : on the mealplan, I click on the "put the missing products" for a specific recipie, I was not using the global button.
And I guess I didn't look well, when adding two recipes sharing the same product, I have two lines for that product on the shopping list.

> No, but maybe related to #388.
Will wait to see if it fit my needs.

So I guess I have the correct behaviors now :)

I still have a strange warning when consuming a recipe from the mealplan.
I have every single product on the stock, when I click on this recipe button for consume it, I have warning telling me that there is missing product so there will be no consummation, but it actualy consume the products.
Not a problem because I have the product and all the products is consumed.

Again, thank you, this software is necessary by the current time if you don't want to be surprised with missing supplies on stores.

Best regards.

**Comment by berrnd** [comment]
> > The check against the stock is done per recipe, not for multiple recipes at once

> You mean on the recipe menu ?

Yes.

> And I guess I didn't look well, when adding two recipes sharing the same product, I have two lines for that product on the shopping list.

There should be already request here to combine the lines when the product is already on the shopping list, but haven't found it right now...

> I have every single product on the stock, when I click on this recipe button for consume it, I have warning telling me that there is missing product so there will be no consummation, but it actualy consume the products.

If this is reproducible (use the demo for example), I will have a look at it.

**Comment by Loxeno** [comment]
Okay, I was able to reproduce it, and this is not a bug (or maybe the warning isn't clear enough).

If you have a recipe containing a product with "Disable stock fulfillment checking for this ingredient" checked, if you don't have a stock, you are able to consume the recipe but you get the warning.

Maybe the warning should tell that a product is configured that way and should list what products isn't in stock ?

**Comment by berrnd** [comment]
This should be clearer when #548 is done.
