### ISSUE TITLE
Add API endpoint for all config.php and user settings

### ISSUE THREAD

**Issue by MrJohnZoidberg** [grocy/grocy#718]
Is there a way to get the currency (EUR, USD, ...) from the server with the API?

**Comment by berrnd** [comment]
No, currently not - so let's add a generic one to get all `config.php` and user settings.

**Comment by berrnd** [comment]
There is now the new endpoint [`/user/settings`](https://demo-prerelease.grocy.info/api/user/settings) to get all user settings of the currently logged in user and [`/system/config`](https://demo-prerelease.grocy.info/api/system/config) to get all config settings (key/value pairs).
