### ISSUE TITLE
Feature Request: Show out-of-stock in API

### ISSUE THREAD

**Issue by noxhirsch** [grocy/grocy#720]
Hi,
I couldn't find any way to get the list of out-of-stock items, but checking for every product item if it is in the stock-list or not.
It would be great if `GET /stock` could return the out of stock items with amount zero or if there would be something like `GET /stock/out` or something similar.

Or is there any more elegant solution with which I haven't come up with so far?
Thank you!

**Comment by berrnd** [comment]
Only products which have a minimum stock amount set and the current stock amount is below that value are considered missing (highlighted in blue on the stock overview page).

And that's already part of the [`/stock/volatile`](https://demo-prerelease.grocy.info/api/stock/volatile) endpoint.
