### ISSUE TITLE
Product page: Add camera scanning button for barcodes field

### ISSUE THREAD

**Issue by kkakkong** [grocy/grocy#723]
location : Master Data > Products > add> Create product> Parent Product, Barcode 
The two positions seem to have changed.

Version pre-release-4f8ef28
Version 2.6.2

![2020-04-12 (1)](https://user-images.githubusercontent.com/62811794/79062872-cc43d880-7cd8-11ea-9e24-e0afccb01968.png)

![2020-04-12 (2)](https://user-images.githubusercontent.com/62811794/79062979-a0752280-7cd9-11ea-8bbd-9b65cfe0e5ac.png)

**Comment by berrnd** [comment]
Sorry, I don't understand what you mean.

The "Parent products" features is there since v2.5.0...

**Comment by kkakkong** [comment]
> Sorry, I don't understand what you mean.
> 
> The "Parent products" feature is there since v2.5.0...

Cheese, milk, snacks, etc. are the choices for the parent product.

The barcode topic below does not have a barcode scanning feature.

**Comment by berrnd** [comment]
Ok, but that's not new, was never there, so not a bug - and I'll change the title to make this clear.

**Comment by berrnd** [comment]
> Isn't it strange that the parent product has a barcode scanner?

It's the same product picker input as on all pages, and I don't see what's wrong that you can pick a product by scanning its barcode - the same way as on all other places..

**Comment by kkakkong** [comment]
How do I enter the "barcode" item after the "Description"?

Cheese, milk, snacks, etc. are the choices for the parent product.

I don't think the parent product is a "barcode" input.

**Comment by berrnd** [comment]
> How do I enter the "barcode" item after the "Description"?

Currently by typing or using for example a USB laser barcode scanner (which works 1000 % better, anyway).

> I don't think the parent product is a "barcode" input.

Again, it's the same input as on all pages. Your example barcode from the screenshot above did not get recognized because it's not attached to any product on the demo instance. So what do you expect?

**Comment by kkakkong** [comment]
I am registering an unregistered barcode product.
I want to register by "barcode" with a mobile camera.
I hope the barcode form also has a "barcode scanning function".
Thank you

**Comment by berrnd** [comment]
>  I hope the barcode form also has a "barcode scanning function".

That's what will be tracked in this issue (add that camera scanning button to the barcode field on the product edit page).

The simplest way, in my opinion, or how I do it:
Directly during purchase, scan an unknown barcode, select "Add as new product and prefill barcode" (or just use the shortcut key `A`), enter all other needed product infos, continue the purchase.

![grafik](https://user-images.githubusercontent.com/2161815/79064602-8ff98380-7caa-11ea-88c4-d23549d95dfa.png)

**Comment by kkakkong** [comment]
Now I understand.
You are telling me to use the automatic input function when adding a new barcode if it is not registered when scanning the barcode.
