### ISSUE TITLE
UI Bug: wrong limits for amount with tare weight handling enabled

### ISSUE THREAD

**Issue by MrJohnZoidberg** [grocy/grocy#727]
The input field "amount" of the menu entry "consume" has wrong limits for possible values.

**Example:**
Flour has tare weight handling on and its tare weight is 500g.
1. The flour container and hence the flour stock is empty
2. You buy 700g of flour (your container now weights 1200g) and add it to the Grocy stock
3. You consume 300g of flour, so the container weights 900g now. You go to the menu entry "consume" for flour and enter the weight of the container, but the warning says: "The amount must be between 1 and 700" - it doesn't take the value 900.

**Actual behaviour:**
So the warning says that you only can consume that amount which is in stock, but these limits are wrong with enabled tare weight handling because then the weight of the container is missing.

**Expected behaviour:**
The limits should be 500 (the tare weight: container without flour) and 1200 (the tare weight + what is in stock). The description above the field is not wrong: "Tare weight handling enabled - please weigh the whole container".

The API does not have this bug.

**Comment by berrnd** [comment]
Seems that his was a problem since #421.
