### ISSUE TITLE
[API bug] "open" request answer doesn't contain transaction id

### ISSUE THREAD

**Issue by MrJohnZoidberg** [grocy/grocy#732]
When you open a product from strock overview you can undo the transaction with the button in the green notification. But this doesn't work because the transaction id from the answer of the "open" requests is "null". Hence, the request "api/stock/transactions/null/undo" fails with a 400 error.

Is it intended that open doesn't have a transaction id or is this a bug?

**Comment by berrnd** [comment]
> Is it intended that open doesn't have a transaction id or is this a bug?

No, is of course a bug - thanks for finding that. :)
