### ISSUE TITLE
Shopping List Printing Template

### ISSUE THREAD

**Issue by hmronline** [grocy/grocy#740]
Hi, first of all, thank you for developing this!

The print button provides an export of the shopping list that look nice, however the font size was pretty small making it difficult to read at the supermarket.

Please find below some suggestions to make it more compact (in order to carry a smaller sheet of paper at the supermarket) and more readable (avoid blank spaces and increase font size):

Item/Product quantity should be placed on the first column instead of second column as it is right now.
Quantity text is shorter so it would fit better on the left, and column size should not be fixed to avoid wasting blank space between columns.
I think it also reads better: 2 pieces of product X

It would be great to have a few additional options in the configuration menu:
 * Font size: at least small, medium, large
 * Layout: 1 column (as it is right now), 2 columns (to save some space and make it fit in one page)
 * Include Headers (yes/no), or at least make it smaller.

Hope this helps to improve that feature.

Thanks in advance!
Hernán.-

**Comment by CRTified** [comment]
It would also be helpful to include the product group headers in the print view.

The 2-Column option can be achieved by using the printer option "Print 2 pages on 1". The font size is fine (at least for me, YMMV).

**Comment by lousando** [comment]
![image](https://user-images.githubusercontent.com/1214300/79630787-36a9ae00-8109-11ea-9286-5bf8e1d1c8a1.png)

Currently working on this enhancement :)
I will add options for headers (yes/no) next.
Re-ordering of columns might take a bit longer, but I'll make a PR before that sub-feature and possibly and that in a future revision.

**Comment by bfayers** [comment]
I would like to see the product groups included on the printed list in the same way they are included on the web view list.

**Comment by hosios** [comment]
I would also urge these options for printing. I know Grocy is suposed to be used with the app, and it is handy, but our times with COVID-19 changed that. We now opt for delivery, and then you have to have a printed list (or a pdf for that matter). 
So, pelase make these options as soon as possible. 

Thank you vor a great product

**Comment by edenhaus** [comment]
I found https://www.reportbro.com which is generating from a template a pdf. Also it supports a template designer so the user can easy adopt and configure the required layout for it.
Before starting to implement there are a few questions to solve:
- The pdf is generating in the backend, which is written in python. @berrnd  Would you accepted a PR which is forwarding a pdf request to a python application? The first idea in my mind was a python rest server, which is only listening on localhost and so only the php backend can call it. If you have a better idea, then feel free to write it 😊
- Opensource can use it for free but we have to check the license. I will do that when the first one is answered.

**Comment by edenhaus** [comment]
> Sounds like a little bit too much overhead for a customizable printed shopping list in my opinion...
> (So if, then please better as an add-on, like [Barcode Buddy](https://github.com/Forceu/barcodebuddy).)

I know but it will move the design/layout of the pdf to the user. I will probably create the addon, maybe already during Christmas, we will see...

> Options for which columns/headers should be printed, font size and that stuff is nothing IMHO can't be solved by some JS magic and has also already been started in #754, it's just not ready...

For sure. I have tried to use the extension buttons of DataTable for that, but the extension is unfortunately very limited and I don't want to invent the wheel again :smile: Maybe some goes on with #754

**Comment by berrnd** [comment]
There are now these options before printing the shopping list:

![grafik](https://user-images.githubusercontent.com/2161815/102701306-09903b00-4256-11eb-8e63-e0a6027b3836.png)

Default options (screenshot above) produces the same output as before, but including product groups grouping.

"Show header" and "Group by product group" checkboxes should be self explanatory.
Layout type "List" produces a simple list instead of a table like mentioned above.

Hope this helps, if someone has further ideas/needs - feel free to comment or open separate requests.

Can be tested on the pre-release demo: https://demo-prerelease.grocy.info/shoppinglist
