### ISSUE TITLE
Unable to access the Quantity Units page in Home Assistant

### ISSUE THREAD

**Issue by SupremeSports** [grocy/grocy#741]
When trying to add new Quantity Units, it gives error below. I was able to do so in previous versions (2 or 3 versions back). but I don't add quantity units very often, so just realized I was no able to access it.

I'm using Grocy 0.7.1 for Home Assistant

`Slim Application Error
The application could not run because of the following error:

Details
Type: ErrorException
Message: Function name must be a string (View: /var/www/grocy/views/quantityunits.blade.php)
File: /data/grocy/viewcache/721c9aab32a4fc7dbf818ced13d44d71576eac71.php
Line: 1
Trace
#0 /var/www/grocy/vendor/illuminate/view/Engines/PhpEngine.php(47): Illuminate\View\Engines\CompilerEngine->handleViewException(Object(Symfony\Component\Debug\Exception\FatalThrowableError), 2)
#1 /var/www/grocy/vendor/illuminate/view/Engines/CompilerEngine.php(59): Illuminate\View\Engines\PhpEngine->evaluatePath('/var/www/grocy/...', Array)
#2 /var/www/grocy/vendor/illuminate/view/View.php(142): Illuminate\View\Engines\CompilerEngine->get('/var/www/grocy/...', Array)
#3 /var/www/grocy/vendor/illuminate/view/View.php(125): Illuminate\View\View->getContents()
#4 /var/www/grocy/vendor/illuminate/view/View.php(90): Illuminate\View\View->renderContents()
#5 /var/www/grocy/vendor/rubellum/slim-blade-view/src/Blade.php(173): Illuminate\View\View->render()
#6 /var/www/grocy/vendor/rubellum/slim-blade-view/src/Blade.php(65): Slim\Views\Blade->fetch('quantityunits', Array)
#7 /var/www/grocy/controllers/StockController.php(167): Slim\Views\Blade->render(Object(Slim\Http\Response), 'quantityunits', Array)
#8 [internal function]: Grocy\Controllers\StockController->QuantityUnitsList(Object(Slim\Http\Request), Object(Slim\Http\Response), Array)
#9 /var/www/grocy/vendor/slim/slim/Slim/Handlers/Strategies/RequestResponse.php(40): call_user_func(Array, Object(Slim\Http\Request), Object(Slim\Http\Response), Array)
#10 /var/www/grocy/vendor/slim/slim/Slim/Route.php(281): Slim\Handlers\Strategies\RequestResponse->__invoke(Array, Object(Slim\Http\Request), Object(Slim\Http\Response), Array)
#11 /var/www/grocy/middleware/SessionAuthMiddleware.php(57): Slim\Route->__invoke(Object(Slim\Http\Request), Object(Slim\Http\Response))
#12 [internal function]: Grocy\Middleware\SessionAuthMiddleware->__invoke(Object(Slim\Http\Request), Object(Slim\Http\Response), Object(Slim\Route))
#13 /var/www/grocy/vendor/slim/slim/Slim/DeferredCallable.php(57): call_user_func_array(Object(Grocy\Middleware\SessionAuthMiddleware), Array)
#14 [internal function]: Slim\DeferredCallable->__invoke(Object(Slim\Http\Request), Object(Slim\Http\Response), Object(Slim\Route))
#15 /var/www/grocy/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(70): call_user_func(Object(Slim\DeferredCallable), Object(Slim\Http\Request), Object(Slim\Http\Response), Object(Slim\Route))
#16 /var/www/grocy/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(117): Slim\Route->Slim\{closure}(Object(Slim\Http\Request), Object(Slim\Http\Response))
#17 /var/www/grocy/vendor/slim/slim/Slim/Route.php(268): Slim\Route->callMiddlewareStack(Object(Slim\Http\Request), Object(Slim\Http\Response))
#18 /var/www/grocy/vendor/slim/slim/Slim/App.php(503): Slim\Route->run(Object(Slim\Http\Request), Object(Slim\Http\Response))
#19 /var/www/grocy/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(117): Slim\App->__invoke(Object(Slim\Http\Request), Object(Slim\Http\Response))
#20 /var/www/grocy/vendor/slim/slim/Slim/App.php(392): Slim\App->callMiddlewareStack(Object(Slim\Http\Request), Object(Slim\Http\Response))
#21 /var/www/grocy/vendor/slim/slim/Slim/App.php(297): Slim\App->process(Object(Slim\Http\Request), Object(Slim\Http\Response))
#22 /var/www/grocy/app.php(72): Slim\App->run()
#23 /var/www/grocy/public/index.php(3): require_once('/var/www/grocy/...')
#24 {main}
Previous exception
Type: Symfony\Component\Debug\Exception\FatalThrowableError
Message: Function name must be a string
File: /data/grocy/viewcache/721c9aab32a4fc7dbf818ced13d44d71576eac71.php
Line: 1
Trace
#0 /var/www/grocy/vendor/illuminate/view/Engines/PhpEngine.php(43): include()
#1 /var/www/grocy/vendor/illuminate/view/Engines/CompilerEngine.php(59): Illuminate\View\Engines\PhpEngine->evaluatePath('/var/www/grocy/...', Array)
#2 /var/www/grocy/vendor/illuminate/view/View.php(142): Illuminate\View\Engines\CompilerEngine->get('/var/www/grocy/...', Array)
#3 /var/www/grocy/vendor/illuminate/view/View.php(125): Illuminate\View\View->getContents()
#4 /var/www/grocy/vendor/illuminate/view/View.php(90): Illuminate\View\View->renderContents()
#5 /var/www/grocy/vendor/rubellum/slim-blade-view/src/Blade.php(173): Illuminate\View\View->render()
#6 /var/www/grocy/vendor/rubellum/slim-blade-view/src/Blade.php(65): Slim\Views\Blade->fetch('quantityunits', Array)
#7 /var/www/grocy/controllers/StockController.php(167): Slim\Views\Blade->render(Object(Slim\Http\Response), 'quantityunits', Array)
#8 [internal function]: Grocy\Controllers\StockController->QuantityUnitsList(Object(Slim\Http\Request), Object(Slim\Http\Response), Array)
#9 /var/www/grocy/vendor/slim/slim/Slim/Handlers/Strategies/RequestResponse.php(40): call_user_func(Array, Object(Slim\Http\Request), Object(Slim\Http\Response), Array)
#10 /var/www/grocy/vendor/slim/slim/Slim/Route.php(281): Slim\Handlers\Strategies\RequestResponse->__invoke(Array, Object(Slim\Http\Request), Object(Slim\Http\Response), Array)
#11 /var/www/grocy/middleware/SessionAuthMiddleware.php(57): Slim\Route->__invoke(Object(Slim\Http\Request), Object(Slim\Http\Response))
#12 [internal function]: Grocy\Middleware\SessionAuthMiddleware->__invoke(Object(Slim\Http\Request), Object(Slim\Http\Response), Object(Slim\Route))
#13 /var/www/grocy/vendor/slim/slim/Slim/DeferredCallable.php(57): call_user_func_array(Object(Grocy\Middleware\SessionAuthMiddleware), Array)
#14 [internal function]: Slim\DeferredCallable->__invoke(Object(Slim\Http\Request), Object(Slim\Http\Response), Object(Slim\Route))
#15 /var/www/grocy/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(70): call_user_func(Object(Slim\DeferredCallable), Object(Slim\Http\Request), Object(Slim\Http\Response), Object(Slim\Route))
#16 /var/www/grocy/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(117): Slim\Route->Slim\{closure}(Object(Slim\Http\Request), Object(Slim\Http\Response))
#17 /var/www/grocy/vendor/slim/slim/Slim/Route.php(268): Slim\Route->callMiddlewareStack(Object(Slim\Http\Request), Object(Slim\Http\Response))
#18 /var/www/grocy/vendor/slim/slim/Slim/App.php(503): Slim\Route->run(Object(Slim\Http\Request), Object(Slim\Http\Response))
#19 /var/www/grocy/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(117): Slim\App->__invoke(Object(Slim\Http\Request), Object(Slim\Http\Response))
#20 /var/www/grocy/vendor/slim/slim/Slim/App.php(392): Slim\App->callMiddlewareStack(Object(Slim\Http\Request), Object(Slim\Http\Response))
#21 /var/www/grocy/vendor/slim/slim/Slim/App.php(297): Slim\App->process(Object(Slim\Http\Request), Object(Slim\Http\Response))
#22 /var/www/grocy/app.php(72): Slim\App->run()
#23 /var/www/grocy/public/index.php(3): require_once('/var/www/grocy/...')
#24 {main}`

**Comment by berrnd** [comment]
Not reproducible with the latest [stable](https://demo.grocy.info) and [preview version](https://demo-prerelease.grocy.info) - please always try to reproduce problems on the demo instances first.

So maybe was a problem in an older version, I think the Home Assistant addon still uses grocy v2.6.0.

**Comment by SupremeSports** [comment]
Ok, so after looking a little bit further, I realized that chores, tasks, and many more stuff were giving similar errors. So it looks something got corrupted

So I found a way to fix this:

- In Home Assistant, insure you have a backup (snapshot)
- Take a copy of the config in the add-on
- Uninstall Grocy add-on
- Reinstall Grocy (fresh install will remove every settings)
- Set the Config you copied above
- Find the location on your storage (SSD or HDD) where grocy is installed by searching for grocy.db
- Open your backup file (*.tar), Extract the file grocy.db and folder storage
- Paste it into the grocy location
- Restart Grocy
- Everything should be back even your logins
