### ISSUE TITLE
Update 2.7.0 -> unable to access "Manage master data" menu

### ISSUE THREAD

**Issue by bbreton09** [grocy/grocy#743]
![image](https://user-images.githubusercontent.com/10090794/79484024-5eb6e580-8013-11ea-84d8-b22e2009ff30.png)

Unable to extend the "Manage master data" menu since the update to 2.7.0.
Tested on Firefox and Chrome.
The cache has been emptied.

Same problem with https://en.demo.grocy.info/stockoverview

**Comment by redinsight** [comment]
I am having the same issue.

**Comment by berrnd** [comment]
Thanks a lot for noticing this so fast! :)

I've re-published the v2.7.0 release just now.

Underlying problem: twbs/bootstrap#30553

**Comment by bbreton09** [comment]
All it's ok !
You're welcome and thanks for the quick correction.
