### ISSUE TITLE
Feature: Configure sound on/off

### ISSUE THREAD

**Issue by jmoseley** [grocy/grocy#746]
It would be great to be able to configure whether sounds are played or not.

**Comment by berrnd** [comment]
The only place where sound is played is no the purchase/consume page when "Scan mode" is on. The intention of "Scan mode" was to scan products without the real need to look at the screen, therefore provide audio feedback.

So you want to use "Scan mode" without audio feedback?
An option would also be to just disable audio permissions for the grocy website in your browser...

**Comment by jmoseley** [comment]
I've found that the sound plays whenever I use the purchase form. I guess the default is "Scan mode"? It has just caught me by surprise and I'd like to not have to deactivate scan mode every time I use the purchase menu.

**Comment by berrnd** [comment]
It stays disabled, as it is saved as a user setting. So just disable it and it should be fine. And it also not only play sounds, it also auto-submits the form, excerpt from the changelog:

> ### New feature: Scan mode
> - Just scan one product after another, no manual input required and audio feedback is provided
> - New switch-button on the purchase and consume page
> - When enabled
>   - The amount will always be filled with `1` after changing/scanning a product
>   - If all fields could be automatically populated (means for purchase the product has a default best before date set), the transaction is automatically submitted
>     - If not, a warning is displayed and you can fill in the missing information
>   - Audio feedback is provided after scanning and on success/error of the transaction
> - => Quick video demo: https://www.youtube.com/watch?v=83dm9iD718k
