### ISSUE TITLE
I suggest that the translation application rate be lowered.

### ISSUE THREAD

**Issue by kkakkong** [grocy/grocy#747]
I suggest that the translation application rate be lowered.

Each language has many meanings that can be translated.

It's hard to translate because I don't know how the sentences shown in transifex actually work.

.

**Comment by berrnd** [comment]
So you probably mean to lower the ["80 % rule](https://github.com/grocy/grocy#localization)" for the [pre-release demo](https://demo-prerelease.grocy.info)?

I would have no problem with that (but new languages get currently not added manually, so I need to first notice that a translation reched the defined completion level).

But I don't think it's useful to include far-incomplete translations in releases (is also the same for translations which had a completion level of 80 % some time ago, but now are stale - they're currently still included...).

**Comment by kkakkong** [comment]
Yes, please lower the threshold for the demo test. thank you

**Comment by berrnd** [comment]
Then let's leave this open until it's done... :)

**Comment by kkakkong** [comment]
sorry. I'm not used to using the GitHub.

**Comment by berrnd** [comment]
Adding the Korean translation will be tracked in #903, I think we'll the "80% rule" for now.
