### ISSUE TITLE
Barcode scanner stopped working after update to 2.7

### ISSUE THREAD

**Issue by fnordson** [grocy/grocy#749]
So up to yesterday when I updated to 2.7.0 as described on front-page: 

- copy all files but /data
- deleted data/viewcache
- add new lines to config: (Setting('FEATURE_FLAG_AUTO_TORCH_ON_WITH_CAMERA', true) and DefaultUserSetting('quagga2_numofworkers', 4);

...barcode scanner was working swiftly and perfectly. 

Now when I tried to scan today I got those errors: 

![error_01](https://user-images.githubusercontent.com/5624605/79591459-d4d15000-80d8-11ea-9d47-0cf0e487d5c4.jpg)

Blue says: _camera access is only possible if your browser allows it_ (it does because the camera is being called afterwards and I can see the output) _and if your access comes through a secure connection_ (as you can see on top, it does. I also didn't change anything there). 

Red says: _Error initializing barcode-scan-components. Click to show technical details._ 
Those look like this: 

![error_02](https://user-images.githubusercontent.com/5624605/79591979-9a1be780-80d9-11ea-8f92-3690a182675c.jpg)

If I click the barcode button again, the error msg won't appear again, the scanner window will properly show camera output but it won't look for the barcode. Nothing is happening. 

What I tried: 

- I updated the DemoBarcodeLookupPlugin.php in the /data/plugins as it was newer but only now after I already
- I commented out the: Setting('FEATURE_FLAG_AUTO_TORCH_ON_WITH_CAMERA', true); in config which only triggered the error msg again
- I tried a different device which didn't help

Help please.

**Comment by DanBenHa** [comment]
Similar issue here. Updated to 2.7 and can't use the barcode scanner anymore. It still shows the camera live picture but it's just not doing any scanning. Tried different devices and also the official demo. None works

**Comment by berrnd** [comment]
I can reproduce it.

Just for clarification:
> I updated the DemoBarcodeLookupPlugin.php in the /data/plugins as it was newer but only now after I already

This file has nothing to do with the camera scanning thing, it's all about the used library [Quagga2](https://github.com/ericblade/quagga2) in this [JS component](https://github.com/grocy/grocy/blob/master/public/viewjs/components/barcodescanner.js)...

**Comment by berrnd** [comment]
New release is ready: https://github.com/grocy/grocy/releases/tag/v2.7.1

**Comment by fnordson** [comment]
> 
> 
> New release is ready: https://github.com/grocy/grocy/releases/tag/v2.7.1

Thank you @berrnd for the fix fix!

**Comment by ericblade** [comment]
My apologies for my library breaking your usage :)  I'm going through some major restructuring to bring Quagga up to date, and the test suite I inherited has a fair number of holes in it's surface area, so it's been a bit prickly at times.  I hope I can fix this problem this weekend, and get you a version that will work correctly with the app :)

**Comment by fnordson** [comment]
Oh man no need to apologize at all!
I'm sure I can speak for all when I say we really appreciate your work here. 
I love the tool and I'm always happy if I can help out finding bugs :)

**Comment by ericblade** [comment]
hey @berrnd I found where the error in Quagga2 came in, fixed it, and added tests, so hopefully it won't totally break again.  If you pick up 0.0.21 it should be a drop-in replacement for the original, again.  

There are some pretty big changes in the queue, but that's going to be a major version upgrade, although I still don't expect the public interface to change much -- although there might be some change to the canvas interface, i'm not real sure yet.  We may add capabilities to have multiple instances running in a page, now that I've fixed parallel decoding.

**Comment by berrnd** [comment]
> also, sorry that took an extra week to figure out, i didn't get much time to sit and debug last week

Still no need to apologize! Thanks for your work! :)

Will try it, but probably not this weekend - created #799 to track this.

**Comment by fnordson** [comment]
@berrnd it's kinda embarrassing but I'm having an issue again with the barcode scanner as a result of a backup restore. 
I write this here since I had the backup made after the 2.7 update. 

What I did now was updating the backed up 2.7 version to 2.7.1. 
The camera popup does come up, flash lights up, but no scanning happens and I'm kinda lost as there is no error msg this time. 

I checked the files and they seem to have been updated properly so there is nothing there to look for. Do you have any idea how do debug this?

**Comment by berrnd** [comment]
> Do you have any idea how do debug this?

This is only JavaScript, so please check the browser console for errors. If it's the same error as above, please double check that you use the right version WITHOUT Quagga2, but WITH QuaggaJS (there should be a folder `public/node_modules/quagga`).

**Comment by fnordson** [comment]
I have this folder. 
Is there anything in regards to the configuration that I have to set there? 
Is it somehow related to the "Component configuration" setting? Should I comment it out? 

I can't access the console on my Fennec at the moment. I'll have to try to install another browser but I'm not really good at this and the browser on my PC seems to refuse working with it alltogether as it doesn't have a camera.

**Comment by berrnd** [comment]
It's most probably something about that the browser does not support something QuaggaJS needs, so checking for errors there is the only thing I would say...

Nothing needs to be configured, the new setting was for Quagga2, but we reverted to QuaggaJS in v2.7.1...

**Comment by ericblade** [comment]
fennec? what browser/device?

**Comment by fnordson** [comment]
@berrnd I tried Chrome too. Same effect: 

![signal-attachment-2020-05-24-185537](https://user-images.githubusercontent.com/5624605/82759893-6034b400-9df0-11ea-8b61-c31563262895.png)

Camera was there, but no scanning occurred. 

@ericblade Fennec is a Firefox fork for Android on a Pixel2 but I tried with a MotoG with the same effect. 

Is there something that might have been messed up within the config files? 
My barcode related settings are:

Setting('STOCK_BARCODE_LOOKUP_PLUGIN', 'DemoBarcodeLookupPlugin');
Setting('DISABLE_BROWSER_BARCODE_CAMERA_SCANNING', false);
DefaultUserSetting('quagga2_numofworkers', 4);
Setting('FEATURE_FLAG_AUTO_TORCH_ON_WITH_CAMERA', true);

**Comment by berrnd** [comment]
Sorry but I think I cannot really help without any error messages. Maybe try to reproduce this with the QuaggaJS demos if that's a general QuaggaJS problem...

And just for clarification:
- The setting `STOCK_BARCODE_LOOKUP_PLUGIN` has nothing to do with the "browser camera scanning" implementation at all
- `quagga2_numofworkers` is currently not used since we downgraded to QuaggaJS again
- `DISABLE_BROWSER_BARCODE_CAMERA_SCANNING` just hides all "camera buttons" if enabled
- `FEATURE_FLAG_AUTO_TORCH_ON_WITH_CAMERA` is also not QuaggaJS releated, it just enables the flash light if the device has one using the official MediaDevices API

**Comment by ericblade** [comment]
What kind of a barcode is that fnordson?  Doesn't look like a UPC, I'm not sure what quagga readers grocy is configured to use by default, I'd assume UPC/EAN, as those are the most common product barcode types that I know of, but I'm over in the US so I have no idea what is used everywhere else :|

**Comment by fnordson** [comment]
OK I have something. 
I just went to my laptop and there is an quagga.min.js error in the console: 

`asm.js type error: Disabled by debugger `

There is also one for "purchase"  

Invalid URI. Media ressource loading failed (translated by me)

**Comment by fnordson** [comment]
@ericblade here is the full thing: 

![signal-attachment-2020-05-24-200059](https://user-images.githubusercontent.com/5624605/82761228-709d5c80-9df9-11ea-9876-4b2fb2fa51dd.jpg)

and it did work before as those are our favourite bag of flips and I had is scanned before. 
I also tried different other products I scanned before just to be sure.

**Comment by fnordson** [comment]
Adding to this: 

I disabled ublock origin and got another error. 
This time in red for barcodescanner.js:183:4

`TypeError: drawingCtx is undefined`

**Comment by ericblade** [comment]
That sounds like you're using the version of grocy that wasn't working because i broke quagga2 on accident :(   (on the bright side, i've implemented much better testing on quagga2, but it's going to take me some time to build testing to ensure the live camera mode doesn't get broken by anything.. so i try to be real careful and manually test changes that might affect that)

I am interested to see if there's a problem with firefox and the ASM.js code inside quagga, so i've noted a bug on my repo for that.

**Comment by fnordson** [comment]
Mh ok. I thought it was reverted with that 2.7.1 update.  
Anything I can do besides waiting now?

**Comment by fnordson** [comment]
FYI: I was tired waiting and entering data by hand so I've set it up again, copied config&data files over from the last installation and the scanner works now.
