### ISSUE TITLE
Best before is set to the day it was buyed when best before disabled -> API problem

### ISSUE THREAD

**Issue by noxhirsch** [grocy/grocy#752]
Hi,
when `FEATURE_FLAG_STOCK_BEST_BEFORE_DATE_TRACKING` is set to false, it seems like grocy automatically sets the best before date to the day the item was bought.
This creates a problem with the API request `/stock/volatile` (to get the out of stock items) which now always outputs the whole stock because now everything is always expired.
It's not a big problem, because I can ignore that data, but it's just useless traffic ;)

**Comment by berrnd** [comment]
Thanks for finding, of course it's better to set the default best before date "never expires" (aka `2999-12-31`), when best before tracking is disabled, I think.

But in general disabled feature flags currently only hide some UI things, maybe we should consider them also for the API, but then API responses maybe get inconsistent based on disabled flags, so maybe not a good idea...

**Comment by noxhirsch** [comment]
But wouldn't it make more sense in general to set the default best before date no "never expires" regardless of the feature flag? (at least for me that seems way more usefull than "already expired")
Also if best before tracking is enabled the best before input is a requiered field, so is there even any case where the default best before date matters?

**Comment by berrnd** [comment]
It just matters to track when something expires. So if you want track expiration dates, I think than you have to add that on purchase, that's why it is required then. There is also the product option "Default best before days" where the best before date on purchase get prefilled with, when set, can also be `-1` the prefill with "never expires"...

**Comment by noxhirsch** [comment]
That's what I mean: If you set the hard coded default best before date to "never expire" instead of "today", it only comes into play when best before tracking is disabled. The people with tracking enabled should never see this hard coded default, because they must enter a date - they can't let the input field empty.
So from my understanding the hard coded best before date is only relevant for people with disabled tracking. If it's set to "never expire" it doesn't change anything for people with tracking and solves the problem for people without tracking - even without changing anything of the behavior of the feature flags or API.

**Comment by berrnd** [comment]
> So from my understanding the hard coded best before date is only relevant for people with disabled tracking. If it's set to "never expire" it doesn't change anything for people with tracking and solves the problem for people without tracking - even without changing anything of the behavior of the feature flags or API.

Sure, that's how I understood it - only set it by default _always_ to "never expires" when `FEATURE_FLAG_STOCK_BEST_BEFORE_DATE_TRACKING` is disabled...

**Comment by noxhirsch** [comment]
Ich versuche es mal auf Deutsch (sorry für mein schlechtes Englisch).
Das ist leider nicht ganz so wie ich es meinte. Ich meinte es so:
Das im Programmcode festgeschriebene MHD scheint ja "heute" zu sein (also vermutlich `best before default days = 0`). Soomit, wenn ich im Produkt kein Default angegeben habe oder nichts beim Einkauf in das MHD-Feld schreibe, setzt Grocy automatisch für den Einkauf das MHD auf heute.
Von meinem Verständnis her sollte das aber nie passieren, wenn jemand `FEATURE_FLAG_STOCK_BEST_BEFORE_DATE_TRACKING` aktiviert hat. Der User muss dann ja immer ein MHD angeben - entweder durch ein vorausgefülltes MHD Eingabefeld mit den "default best before days" des Produktes oder durch eine ansonsten zwingende manuelle Eingabe.
Wenn man jetzt das im Programmcode festgeschriebene `best before default days` auf -1 ändert, dann sollte das eine Person mit aktiviertem `FEATURE_FLAG_STOCK_BEST_BEFORE_DATE_TRACKING` nie merken, weil sie ja zwangsweise selbst was eingeben muss (was ja bei aktiviertem Tracking auch Sinn macht).
Wenn das Feature Flag aber deaktiviert ist, werden jetzt automatisch alle Produkte auf "never expire" gesetzt, was hier wiederum da sinnvoll ist.
Das Feature Flag müsste also meinem Verständnis nach (sorry, wenn ich mich hier irre und mit dadurch unnötigen Erläuterungen deine Zeit stehle) gar nichts an den "default best before days" ändern (die könnten somit immer bei -1 bleiben), weil diese nur für Nicht-MHD-Tracker zum Tragen kommen.
Letztendlich wäre die IMHO einzig nötige (und wahrscheinlich recht unkomplizierte) Änderung am Code das interne "best before default days". Eine Änderung am Verhalten des Feature Flags oder gar der API erscheint mir da deutlich aufwändiger.

**Comment by berrnd** [comment]
Alles gut - es wird funktionieren. :)
Die einzige Änderung wird sein, bei deaktiviertem `FEATURE_FLAG_STOCK_BEST_BEFORE_DATE_TRACKING` immer "never expires" zu setzen.

Nochmal allgemein:
Wenn das Flag aktiviert ist (Standard), gibt es kein Standard-MHD. Es muss immer gesetzt werden. Es wird nur vorgeschlagen anhand von "Default best before days" des Produkts, mehr passiert nicht.

Wenn das Flag deaktiviert ist, passiert mit "Default best before days" gar nichts, das MHD-Eingabefeld ist in der Oberfläche ausgeblendet, trotzdem aber intern erforderlich, deswegen das setzen "irgendeines" Datums, weil ja prinzipiell egal (derzeit _Heute_, zukünftig _Never expires_).

An der API werde ich hierzu nix ändern.

**Comment by noxhirsch** [comment]
Okay, ich verstehe :)
Vielen Dank!

**Comment by berrnd** [comment]
Fixed by #767.
