### ISSUE TITLE
Recipes userfield UI bug

### ISSUE THREAD

**Issue by lyz-code** [grocy/grocy#755]
Sometimes the userfields are not shown in the recipes columns even though they are marked to be shown.

I've been able to reproduce it in demo.grocy.info creating the following userfields:

* name: test, caption: test1, type: Select list (multiple items can be selected).
* name: test2, caption: test2, type: Select list (multiple items can be selected).
* name: test3, caption: A very loooooooooooooooooooooooooooooong caption, type: Select list (multiple items can be selected).

The third userfield is never shown in the recipes.

Thanks

**Comment by berrnd** [comment]
No:

![grafik](https://user-images.githubusercontent.com/2161815/79637139-1ca9b300-817d-11ea-97b3-e799a940fb79.png)

Depends on the screen size, if it's to small, table columns get collapsed and can be expanded with the blue plus-symbol on the left (default behaviour of [DataTables](https://datatables.net/) which is used for all tables in grocy).

![grafik](https://user-images.githubusercontent.com/2161815/79637193-845ffe00-817d-11ea-8256-cd56203f49f7.png)
