### ISSUE TITLE
Enhancement Feature: Remember store location

### ISSUE THREAD

**Issue by lyz-code** [grocy/grocy#756]
When "purchasing" items on the "Purchase" or "Shopping List" pages, it would be nice that the `store` field was automatically filled up either from the last purchased item (as it's probable that consecutive items are being bought in the same store) or from the last location the item was bought from.

Thanks

**Comment by lyz-code** [comment]
Even if the default store location exists in the product definition, using the first explained approximation would be useful, for example, if I set the default store to a supermarket brand, but one day I go to another, I'd have to change the store for all the purchased products. 

Maybe `store` can be a shopping list editable attribute, so all products on that list have that store by default.

**Comment by berrnd** [comment]
It's already remembered/prefilled for purchasing, works exactly like described on the changelog, cannot reproduce a problem, excerpt:

> ### New feature: Price history per store
> ...
> Track on purchase/inventory in which store you bought the product **_(gets prefilled by the last store you purchased the product, or the default store of the product if you never bought it)_**
> ...
