### ISSUE TITLE
Enhancement Feature: Show store in the shopping list columns

### ISSUE THREAD

**Issue by lyz-code** [grocy/grocy#757]
It would be awesome that we could have the option of a new column in the shopping list page that showed the stores the product has been bought on in the past.

Therefore if you are going to the Fruit store you can filter only the items that can be bought there.

Thanks

**Comment by berrnd** [comment]
Related to #612.

**Comment by berrnd** [comment]
The products Default store is now available as new (hidden by default) column on the shopping list.

See https://github.com/grocy/grocy/issues/957#issuecomment-748583749.
