### ISSUE TITLE
Minimum stock amount fills wrong buying amount.

### ISSUE THREAD

**Issue by lyz-code** [grocy/grocy#758]
When adding products that are below the minimum stock amount, if the product has a minimum stock amount smaller than 1 purchase unit, a whole unit is added to the shopping list instead of the proportional fraction.

For example, I like to use "pieces" as storage unit for my fruit, and my fruit store uses Kg and $/Kg in their tickets. So I've created an average transformation from Kg to pieces, imagine 3 oranges each Kg.

In the product details I've set `Kg` as `Quantity unit purchase`, and `Piece` as `Storage unit purchase` with a `Factor purchase to stock quantity unit` of `3`. I've also set the equivalence in the Units conversion.

If the `Minimum stock` is 2, and I have none, when adding products that are below the minimum stock amount, instead of adding 0.66, it adds 1.

Thanks

**Comment by berrnd** [comment]
Can reproduce it.

But should only generate decimal amounts on the shopping list when "Allow partial units in stock" is enabled (product option).

**Comment by berrnd** [comment]
> But should only generate decimal amounts on the shopping list when "Allow partial units in stock" is enabled (product option).

Wrong idea: In that example the stock amount would not be a partial amount. So I think just allowing in gernal decimal amounts on the shopping list for "Add products that are below defined min. stock amount" should be ok...
