### ISSUE TITLE
Feature Enhancement: Make amount decimals configurable

### ISSUE THREAD

**Issue by lyz-code** [grocy/grocy#759]
Right now only 2 decimals are allowed in the purchase units. If you could rise it to 3 it will be nice.

My Fruit shop uses Kg as purchase unit, with a precision of 3 decimals, I know that I have two options:

* Use grams instead of Kg, but then I'd have to convert both the quantity and the $/Kg for each product (with an non descriptive $/g).
* Round the Kg to the second decimal, this is what I'm doing with neglegible precision loss.

The request is not to have a better stock precision, but to make the introduction of purchased items even easier, so less thinking.

Thanks

**Comment by berrnd** [comment]
Maybe we should finally add an option for how much decimals should be used, or even remove the restriction completely. Don't know if it would better fit per product, per quantity unit, or as a global option.

For me personally decimal amounts does not make much sense / it's easier to just avoid them. Maybe I don't need/track everything in that much detail. However, the only real solution for handling fractions would be something like #389, partly tried in #527.

**Comment by berrnd** [comment]
That's now done.

There are two new stock settings (top right corner settings menu) to configure decimals for amounts and prices, that's then used for all inputs and also displaying numbers everywhere accordingly.

https://github.com/grocy/grocy/blob/2b4d8a7cc56b7df1c42d5c814f1d81fff7d978d1/config-dist.php#L114-L115

**Comment by lyz-code** [comment]
Thanks!! :)
