### ISSUE TITLE
UI Enhancement: Swap purchase Best Before and Amount position

### ISSUE THREAD

**Issue by lyz-code** [grocy/grocy#760]
When `purchasing` a new product, the Best before is usually automatically generated, while the Amount is not.

So I need to hit TAB twice, if they were swapped, I'd only have to hit it once.

It's a small improvement but still.

Thanks!

**Comment by berrnd** [comment]
Makes sense. The inventory page has it unintentionally already ordered that way...

**Comment by berrnd** [comment]
Fixed by #767.
