### ISSUE TITLE
Consume recipe ingedients not working for product with tare weight handling

### ISSUE THREAD

**Issue by markusappel** [grocy/grocy#761]
Example:
* Product "Flour" has tare weight handling with 500g empty container, 1000g are in stock.
* Recipe XX has 600g Flour as ingredient.
* => "Consume all ingredients needed by that recipe" will not reduce stock to 400g (as expected), but instead to 100g.

It seems the Consume operation is executed in that case with the amount of ingredient (600g), but handles it as if container+stock weight was entered and calculates 600g-500g=100g new stock amount.

**Comment by berrnd** [comment]
I've split the second part into #762. Let's track here the bug about recipe consumption.
