### ISSUE TITLE
DB error after upgrading to 2.7.1

### ISSUE THREAD

**Issue by hmronline** [grocy/grocy#765]
After upgrading from 2.6.1 to 2.7.1, using linuxserver docker image, I've got the following error when trying to edit an existing product:

Type: ErrorException
Code: 0
Message: SQLSTATE[HY000]: General error: 1 no such table: shopping_locations (View: /app/grocy/views/components/shoppinglocationpicker.blade.php) (View: /app/grocy/views/components/shoppinglocationpicker.blade.php)
File: /app/grocy/vendor/morris/lessql/src/LessQL/Database.php
Line: 108

Please let me know if further info is required.

Thank you in advance!
Hernán.-

**Comment by berrnd** [comment]
Have you at least once visited the root route after upgrading?

See https://github.com/grocy/grocy#database-migrations.

**Comment by hmronline** [comment]
It seems I didn't. I can confirm it's working properly.

Thank for you quick response!

Best regards,
Hernán.-
