### ISSUE TITLE
Disallow product opening for tare weight handling enabled products (makes no sense)

### ISSUE THREAD

**Issue by MrJohnZoidberg** [grocy/grocy#770]
Currently, clicking the "open" button in the consume window ignores tare weight handling.

The example with flour: It has 2000g in stock. If I enter 500g as amount and open it, I expect the stock being empty because of the tare weight calculation. But instead the amount is 500g less than before.

I wonder if it makes sense to have the "open" action with products with tare weight handling enabled.
When I have a container with flour, I always consume some of the flour, but not open it. So in my opinion the "open" button should be grayed out. What do you think, Bernd?

**Comment by berrnd** [comment]
> I wonder if it makes sense to have the "open" action with products with tare weight handling enabled.
When I have a container with flour, I always consume some of the flour, but not open it. So in my opinion the "open" button should be grayed out

If I remember correctly, it was initally thought like that - "opening" should not be possible for products with tare weight handling enabled. But haven't found that in #132, the "product open"-feature was implement long before in #86.

There is no check in [`StockService->OpenProduct()`](https://github.com/grocy/grocy/blob/f4b70e9ae347c0bf2b2e81b920253c69a35bbe6d/services/StockService.php#L727-L828) so let's add that there:
- The API request should fail if the product has enabled tare weight handling
- On the frontend the corresponding buttons (stock overview, stock entries, consume) should be greyed out
