### ISSUE TITLE
Camera will not open/not an option for any devices on new installation (2.7.1)

### ISSUE THREAD

**Issue by themcv** [grocy/grocy#771]
Hello,

Very excited to try grocy!

We were getting ready to put it to use, but realized that the camera will not open on any devices (Android/Chrome), (Chrome+Firefox/Windows). I get nothing from the drop down list (no permissions windows on both mobile and Windows)

I found a thread reporting a camera bug and upgraded to 2.7.1 as suggested, but no change it would seem.

I can grab any logs that are needed. :)

**Comment by themcv** [comment]
Nevermind- I missed that it needs to be HTTPS. Sorry about that!

**Comment by themcv** [comment]
Is there a guide on enabling HTTPS for nginx?

**Comment by berrnd** [comment]
Please use the subreddit for general installation help.

But for that specific question: No, I don't think there is any "[nginx](https://nginx.org/en/docs/http/configuring_https_servers.html) [how](https://www.techrepublic.com/article/how-to-enable-ssl-on-nginx/) [to](https://www.linode.com/docs/web-servers/nginx/enable-tls-on-nginx-for-https-connections/) [https](https://www.nginx.com/blog/using-free-ssltls-certificates-from-lets-encrypt-with-nginx/)" tutorial on that internet... ;D
