### ISSUE TITLE
Feature Request: Lock phone input when placed in a pocket

### ISSUE THREAD

**Issue by kses** [grocy/grocy#773]
Would it be possible to have the phone web ui work similar to how the phone behaves when you speak. Lock input but not the phone when close to the face, but for Grocy the face would be a pocket.

I used a no longer maintained shopping list app called shopi that implemented that feature and it was great! You take up your phone from your pocket, pick what you need from the shelf, picks the phone up again, check the box, read next line, put it back in the pocket. Fast and no fiddling with lock/unlock, and still no uninteded inputs.

**Comment by vorkuta** [comment]
As this is working through a web browser I don't think this will be possible. If you are able to find a web browser that has this functionality to 'lock' then I think it will serve your need.

**Comment by berrnd** [comment]
As already pointed out by @vorkuta, grocy is just a website and therefore can nothing do beyond what's provided by the browser. And I don't think there is an standardized API for that. Feel free to add an example how that could be posible, if I'm wrong.
