### ISSUE TITLE
Feature Request: Change the order / time of meal plan entries

### ISSUE THREAD

**Issue by vorkuta** [grocy/grocy#775]
Allow the user to enter an order value, or time for meal plan entries This functionality would be possible both at point of creation as well as editing.

**Comment by TheFlyrain** [comment]
Maybe it is possible to order the entries like cards? I'm using Trello right now and wish to have this functionality. Drag & Drop and maybe visual tags. Eventually give an option to generate automatically a entry with leftovers to the next day. (Only plan leftovers, don't calculate or use to generate shopping list) Like my example: 
![image](https://user-images.githubusercontent.com/8540529/80300526-d87e6a00-879d-11ea-8edc-f106b1e05084.png)

**Comment by vorkuta** [comment]
From a UX standpoint this works for me. It may be easier to start with a manual entry of 'start time' or order, then build drag functionality after.

**Comment by kriddles** [comment]
#370 For meal plan day splitting

> Maybe it is possible to order the entries like cards? I'm using Trello right now and wish to have this functionality. Drag & Drop and maybe visual tags. Eventually give an option to generate automatically a entry with leftovers to the next day. (Only plan leftovers, don't calculate or use to generate shopping list) Like my example:
> ![image](https://user-images.githubusercontent.com/8540529/80300526-d87e6a00-879d-11ea-8edc-f106b1e05084.png)
> 
> Sometimes it is necessary to rearrange the planned meals.

I like the drag & drop and could see some uses for tags.

Recipes can also create products which is great for some recipes that create lots of servings. The created product can then be used as leftovers or a meal that does not generate shopping list since the meal plan can add and consume products as well.

**Comment by CWempe** [comment]
I second the idea of moving meals via drag and drop.
And being able to move/reorder meals in general.

I would also add a feature requst to duplicate meals.
Maybe combine this with drag and drop: Hold Ctrl key to copy instead of move a meal to another time slot.

**Comment by charlessteiner** [comment]
It would be nice

Maybe up and down arrows to rearrange if drag and drop is a little too development intensive.

**Comment by berrnd** [comment]
I made this now basically possible by just adding the day to the edit dialog of any meal plan entry - hope that fits:

![grafik](https://user-images.githubusercontent.com/2161815/161434343-2ceb686c-326e-43c7-ae10-3a7d9cec9293.png)

**Comment by renarena** [comment]
Nice!
Maybe add Arrows to the mealplan recipe buttons to quick move to the next/previous day?
