### ISSUE TITLE
Feature Request: API: Meal plan query / stock fulfillment check endpoints

### ISSUE THREAD

**Issue by zsarnett** [grocy/grocy#777]
Adding Meal Plan to the API would be a great help to HA users and I am sure others.

I would love the ability to pull down the next 7 days, today, x days of the meal plan.

Maybe x entries

The API would only really need to return the name of the meal plan, and the date associated. Potentially adding in a boolean if there is enough in stock?

With Home assistant. We could then pull this down into the Main UI and create a sensor from it. Displaying what is the meal plan for the day :)

**Comment by berrnd** [comment]
That's already possible. There are no specific meal plan endpoints, but basic operations for all entities are possible through the "Generic entity interactions" endpoints.

Examples:

Add a recipe to the meal plan of 2020-04-20:
```
curl -X POST "https://demo.grocy.info/api/objects/meal_plan" -H  "accept: application/json" -H  "Content-Type: application/json" -d "{\"recipe_id\":\"2\",\"recipe_servings\":\"1\",\"day\":\"2020-04-20\",\"type\":\"recipe\"}"
```

Get the whole meal plan:
```
curl -X GET "https://demo.grocy.info/api/objects/meal_plan" -H  "accept: application/json"
```

Generic filtering is currently not possible, but already tracked in #577.

Meal plans are internally just (nested) recipes per day and week (so a recipe which just contains all added recipes as "Included recipes" / products added to the meal plan directly as ingredients).

So currently only possible for example like that:
- Get all recipes through [`GET /objects/recipes`](https://demo-prerelease.grocy.info/api/objects/recipes)
  - Recipes with type `mealplan-day` have the date as the recipe name
  - Recipess with type `mealplan-week` have a name in the format `<year>-<calendar week>`
- Use the existing `/recipes/{recipeId}/fulfillment` or `/recipes/fulfillment` to check if the day/week meal plan has enough stock

Probably some specific meal plan endpoints would make this easier, so let's add them. If you have some concrete ideas, just note them here. :)

**Comment by zsarnett** [comment]
Oh nice that is very helpful to know. Thank you!

For the Meal Plan Endpoints, my ideas are:

GET `/meal-plan` - Limit 50-100?

Response - All Meal Plan entries including the recipe name

Example response

```json
[
  {
    "meal_plan_id": "1",
    "day": "2020-04-12",
    "type": "recipe",
    "recipe_id": "2",
    "recipe_servings": "4",
    "recipe_name": "Pizza",
    "recipe_need_fulfilled": "0",
    "recipe_need_fulfilled_with_shopping_list": "0",
    "recipe_missing_products_count": "2",
    "recipe_costs": "17.74",
    "note": null,
    "product_id": null,
    "product_amount": "0.0",
    "product_qu_id": null,
    "row_created_timestamp": "2020-04-13 16:28:01"
  }
]
```

------------

Get `meal-plan/today` - Gets meal plan entries for today

Same response as above

------------

Post `meal-plan/add` - Adds meal plan entry for certain day

Params - Day, RecipeID (optional), ProductID (optional), note (optional)

Object above that is the added entry

**Comment by berrnd** [comment]
Generic filtering, ordering and pagination is now possible, see https://github.com/grocy/grocy/issues/577#issuecomment-685048875.
