### ISSUE TITLE
Location & product group filter in overview also shows partial matches

### ISSUE THREAD

**Issue by markusappel** [grocy/grocy#778]
I'd except the filter to show only products of the selected category (exact match), but filtering e.g. for the location "Free" also shows all products in location "Freezer":
![Screenshot_20200420_225430](https://user-images.githubusercontent.com/13602252/79799071-2ccab980-835a-11ea-9c7b-79b46a020710.png)

(Stumbled on this in German with "Schrank" and "Kühlschrank")

**Comment by kriddles** [comment]
For exact search, try using quotes such as "free "

Datatables is used for this interface
https://datatables.net/reference/api/search()

**Comment by berrnd** [comment]
Yes, it currently does a contains search - should be of course an exact search...
