### ISSUE TITLE
Recipe Costs with only_check_single_unit_in_stock logic

### ISSUE THREAD

**Issue by kriddles** [grocy/grocy#780]
The only_check_single_unit_in_stock logic will currently prevent consuming a product along with allowing the recipe to be consumed.
The recipe costs defaults to provide an amount of 1 for this product which adds 1 cost to the total recipe costs. Should this instead default to 0 so that no cost is added to the recipe costs?

**Comment by berrnd** [comment]
Maybe just setting the price factor of the ingredient to 0 if that is checked (+ show this somehow on the UI to avoid confusion) would be an option...

**Comment by kriddles** [comment]
Yes, that would work setting the price factor to zero and maybe then change the hint of the price factor along with disabling it? 
Also, It might also be useful to add this up in Ingredient list grid so you don't have to edit the ingredients to see that only_check_single_unit_in_stock is being used.

**Comment by berrnd** [comment]
**TODO for this:**

Just use the original amount for cost calculation also when "Only check if any amount is in stock" is checked, there is no need to use `1` instead and the help-tooltip also doesn't imply that.
