### ISSUE TITLE
Default store in Product not displayed

### ISSUE THREAD

**Issue by crazyelectron-io** [grocy/grocy#783]
Grocy version 2.7.1.

The default store is not retained when editing, saving and reopening the product details page.

Steps to reproduce:
1. Create a new product or edit an existing product.
2. Make sure to select a default store.
3. Save the product.
4. Reopen the product details -> there is no default store filled in.

**Comment by berrnd** [comment]
Thanks for reporting.

But it seems to be saved, just get not displayed when editing a product...

**Comment by crazyelectron-io** [comment]
Indeed. I should have been more precise...
