### ISSUE TITLE
Changing qu_factor_purchase_to_stock affects historical prices and current recipe costs

### ISSUE THREAD

**Issue by kriddles** [grocy/grocy#785]
Low priority since this may rarely occur...
but since price is saved in the stock and stock log table based on the point in time factor qu_factor_purchase_to_stock, if this factor is changed then the current and historical prices will be wrong.

Consider a method to adjust the prices by the factor difference in order to try to keep historical information?

**Comment by kriddles** [comment]
What are your thoughts for saving the qu_factor_purchase_to_stock used on purchase into the stock_log and stock table? 

- It would then maintain historical information at purchase time and allow changing the qu_factor_purchase_to_stock for a product
- Cost information is available at the current stock level without having to look at the product
- On purchase, we could allow changing the qu_factor_purchase_to_stock to stock a different size product #204
- #204 could be further managed by a new table of (product_id, barcode, qu_factor_purchase_to_stock) so that a barcode could be assigned to a qu_factor_purchase_to_stock. On purchase this could fill the qu_factor_purchase_to_stock amount. The last price for the purchase could then filter on the qu_factor_purchase_to_stock in the stock_log table. The product form would need to be updated to populate this table for the barcodes

**Comment by berrnd** [comment]
`qu_factor_purchase_to_stock` alone without the QUs doesn't say much more...

For #204: The question there is about "barcode+amount shortcuts", but I think this should also work without barcodes - something like generating "virtual products" for each pack size, or something like that...

Automatically keeping everything correct while allowing to change everything will be a lot of work...
