### ISSUE TITLE
Feature Request: Purchase/Scan buttons in botton of minimized shopping list screen

### ISSUE THREAD

**Issue by kses** [grocy/grocy#786]
I am not at "full scale" deployment yet, take my suggestion with a grain of salt. When I have tested and tested the shopping list feature in store, I have been missing 1 or 2 "shortcuts".

1:
A purchase button below notes, that jumps straight to the purchase screen and when you press "OK" you get back to the shopping list.

2:
The next level would be 2 buttons where the first is purchase and the second is scan, and it jumps directly to purchase scan with camera mode and use the standard options you have for purchase (scan mode yes/no, defaults etc).

**Comment by berrnd** [comment]
Adding products directly from the shopping list is essentially already possible by using that button (which opens basically the /purchase page while prefilling all relevant fields):

![grafik](https://user-images.githubusercontent.com/2161815/150696077-20468201-a719-4e0b-895b-129b4fb79587.png)

For the other idea about a shortcut to the purchase page on the shopping list page:
I would suggest simply having to tabs open and switching between them (sometimes personally do it like that when directly adding things while waiting at the checkout) - or utilize [custom JS](https://github.com/grocy/grocy#adding-your-own-css-or-js-without-to-have-to-modify-the-application-itself) if you really find an additional button useful.

**Comment by liffez** [comment]
Do you have an example of how to add a botton to the list using custom js.
could be a "add to shoppinglist" on the stockoverview.
i have looked on a lot of your snippets, but have never been able to figure that out

**Comment by liffez** [comment]
Hi Berrnd
Thank you so much. 
This was exactly what i was looking for (i also like the movie)
The custom_js.html is a very powerful tool. My JS programming skills are apperently not so good - but this helped me alot.
br
//Leif
