### ISSUE TITLE
Recipe gallery images do not retain aspect when window width exceeds 1920px

### ISSUE THREAD

**Issue by vorkuta** [grocy/grocy#787]
Recipe gallery image lose their original aspect ratio when window width exceeds 1920px, they are stretched. No vertical stretching from what I can see. The images seen in the recipe window itself (right hand side) do not appear to be affected.

![Correct aspect](https://user-images.githubusercontent.com/6390017/79988595-be474200-84a6-11ea-998c-bec1454b8af6.PNG)

![Stretched aspect](https://user-images.githubusercontent.com/6390017/79988605-c0a99c00-84a6-11ea-8150-4665bb05ef82.PNG)

**Comment by zsarnett** [comment]
Working on a PR that I can include a fix for this
