### ISSUE TITLE
Slim Application Error 'product does not exist' opening Meal plan page

### ISSUE THREAD

**Issue by crazyelectron-io** [grocy/grocy#789]
Since today I get an error page instead of the meal plan for this week.
The error comes from this exception being thrown in `StockService.php`:

```php
public function GetProductDetails(int $productId)
{
	if (!$this->ProductExists($productId))
	{
		throw new \Exception('Product does not exist');
	}
  [...]
}
```
I noticed this function is called by the `MealPlan` function (in `RecipesController.php`):
```php
$productDetails = null;
if ($mealPlanEntry['product_id'] !== null)
{
	$productDetails = $this->getStockService()->GetProductDetails($mealPlanEntry['product_id']);
}
  [...]
```
So, it looks like somethings is not right with the database content. 
By adding the `$productId` variable to the exception message I could see that it is productId 91. Since I have no clue of the database structure, I can use some pointers how to find where the issue is...

UPDATE: Using the `sqlite3` command I could determine that `id` 91 is indeed not available in the `products` table. But I'm unsure how to fix that; adding a dummy entry manually? How should that look like?

**Comment by berrnd** [comment]
Related to #565. Deleting products or Locations/Quantity units/etc. is currently not handled and will cause problems.

> But I'm unsure how to fix that; adding a dummy entry manually? How should that look like?

Create a new dummy product, change the id of that new product to 91...

**Comment by crazyelectron-io** [comment]
> Related to #565. Deleting products or Locations/Quantity units/etc. is currently not handled

I missed that one.

> Create a new dummy product, change the id of that new product to 91...

OK, I should have thought of that myself. 😏
Thanks for the quick reply!

**Comment by crazyelectron-io** [comment]
Adding a dummy product and changing the id to the missing one fixed it.

**Comment by berrnd** [comment]
> Adding a dummy product and changing the id to the missing one fixed it.

Great. :)

Let's leave this open to track the fix for the meal plan page, and maybe finally a general solution for that problem...

**Comment by berrnd** [comment]
#565 is now done, so products can be disabled instead of being deleted, this should prevent this to happen again.
