### ISSUE TITLE
Feature request (UI): Markdown link format for link attributes in userfields

### ISSUE THREAD

**Issue by vorkuta** [grocy/grocy#790]
Links currently display as a hyperlink with the text being the full url.

I think the UI could be improved here by allowing the user to specify the link title, in a similar way to markdown.

`[title](url)`

This will improve UI for links displayed in columns.

**Comment by berrnd** [comment]
Is now done, but not with "markdown style", instead a new Userfield type "Link (with title)" which is then rendered as two separate fields (I think this is more intuitive in general) - looks like that:

![grafik](https://user-images.githubusercontent.com/2161815/102802086-74f11e80-43b6-11eb-84b4-3183a3d77d32.png)
