### ISSUE TITLE
Clicking '+' next to recipe name causes page refresh

### ISSUE THREAD

**Issue by vorkuta** [grocy/grocy#791]
**Expected behaviour**

Would expect that clicking on the '+' icon for any recipe would expand the recipe to show some of the metadata.

![Unexpanded](https://user-images.githubusercontent.com/6390017/80084807-45e88b80-854f-11ea-9fa3-d0bd675a348c.PNG)

![Expanded](https://user-images.githubusercontent.com/6390017/80084814-497c1280-854f-11ea-99c6-24ddabe02c08.PNG)

**Witnessed behaviour**

The recipes page is being refreshed when the user clicks on a '+' for any row other than the currently selected row. This is not a major issue, but expect the fix is reasonably easy and would improve UX.

**Expected root case**

I think that the '+' is a child of a div that has an action / link associated with it that is used to select that recipe, resulting in a page refresh. If the '+' can have it's own column, or be separated from this div, then I think the issue will be fixed.

If any of this isn't clear I can try to do a recording and make a .gif

**Comment by berrnd** [comment]
Was already reported and fixed in #589, but seems to be a problem again, however...

**Comment by vorkuta** [comment]
Bug encountered using Chrome for Windows `Version 81.0.4044.113 (Official Build) (64-bit)`
