### ISSUE TITLE
[UI bug] Focus on product when consuming a different product

### ISSUE THREAD

**Issue by lyz-code** [grocy/grocy#792]
When introducing several products with the `Scan mode ON`, the focus goes to `Amount` instead of remaining in `Product`.

So if we have Milk and Cheese, when I load the Consume page, I have the focus in Product, introduce Milk, it get's consumed and the focus remains in Parent, so I can write Cheese without problems, but when Cheese gets consumed the focus goes to Amount, so if I want to introduce a new product I have to click on Product to be able to write the next one

**Comment by lyz-code** [comment]
And with `Scan off` after consuming a product, the focus doesn't go back to `Product`

**Comment by berrnd** [comment]
Can't reproduce this with "Scan mode off":

![2020-04-23_14-07-22](https://user-images.githubusercontent.com/2161815/80097631-e2208b80-856b-11ea-9c64-f98ad92f78a0.gif)

"Scan mode on" is intended to be used only with a barcode scanner, each scan consumes 1 product, no other manual inputs, excerpt from the changelog of v2.6.0 where this was introduced:

> ### New feature: Scan mode
> - Just scan one product after another, no manual input required and audio feedback is provided
> - New switch-button on the purchase and consume page
> - When enabled
>   - The amount will always be filled with `1` after changing/scanning a product
>   - If all fields could be automatically populated (means for purchase the product has a default best before date set), the transaction is automatically submitted
>     - If not, a warning is displayed and you can fill in the missing information
>   - Audio feedback is provided after scanning and on success/error of the transaction
> - => Quick video demo: https://www.youtube.com/watch?v=83dm9iD718k

And also that works just like described...

**Comment by lyz-code** [comment]
It seems to be a problem with my Firefox configuration, if I disable the plugins or use Chromium, both cases work as expected.
