### ISSUE TITLE
Unable to enter more than 999 quantity in recipes

### ISSUE THREAD

**Issue by crazyelectron-io** [grocy/grocy#794]
When entering an ingredient for a recipe, any amount over 999 is reverted to 1.
For example, I have a product 'beaf' which is bought and used by a quantity 'grams', when entering 1000 or more in the amount field it always reverts to 1.

**Comment by berrnd** [comment]
Strange, whatever that is...

The field has the max value set to `999999`, but however when for example entering `123456`, `123.456` is send in the recipe ingredient API update request, so clearly a frontend / JS problem...

**Comment by crazyelectron-io** [comment]
When checking the database, the field for this ingredient contains the value '1,000', with a comma as decimal point. Looks like language related formatting gets in the way. My Windows system is configured for Dutch number formatting.
Needs some more investigation...

**Comment by Wordna1** [comment]
I am running into the same issue
