### ISSUE TITLE
Install on IIS

### ISSUE THREAD

**Issue by slug1121** [grocy/grocy#797]
Trying to get grocy working on IIS, have require modules (from all documentation I've seen), and getting the following errors... Seems to be an issue in Slim.

#0 C:\inetpub\wwwroot\grocy\vendor\slim\slim\Slim\Middleware\RoutingMiddleware.php(59): Slim\Middleware\RoutingMiddleware->performRouting(Object(Slim\Http\ServerRequest))
#1 C:\inetpub\wwwroot\grocy\vendor\slim\slim\Slim\MiddlewareDispatcher.php(140): Slim\Middleware\RoutingMiddleware->process(Object(Slim\Http\ServerRequest), Object(Slim\Routing\RouteRunner))
#2 C:\inetpub\wwwroot\grocy\vendor\slim\slim\Slim\Middleware\ErrorMiddleware.php(107): class@anonymous->handle(Object(Slim\Http\ServerRequest))
#3 C:\inetpub\wwwroot\grocy\vendor\slim\slim\Slim\MiddlewareDispatcher.php(140): Slim\Middleware\ErrorMiddleware->process(Object(Slim\Http\ServerRequest), Object(class@anonymous))
#4 C:\inetpub\wwwroot\grocy\vendor\slim\slim\Slim\MiddlewareDispatcher.php(81): class@anonymous->handle(Object(Slim\Http\ServerRequest))
#5 C:\inetpub\wwwroot\grocy\vendor\slim\slim\Slim\App.php(215): Slim\MiddlewareDispatcher->handle(Object(Slim\Http\ServerRequest))
#6 C:\inetpub\wwwroot\grocy\vendor\slim\slim\Slim\App.php(199): Slim\App->handle(Object(Slim\Http\ServerRequest))
#7 C:\inetpub\wwwroot\grocy\app.php(68): Slim\App->run()
#8 C:\inetpub\wwwroot\grocy\public\index.php(27): require_once('C:\\inetpub\\wwwr...')

**Comment by berrnd** [comment]
Please use the [subreddit](https://www.reddit.com/r/grocy/) for help, as [stated in README](https://github.com/grocy/grocy#questions--help--bug-reporting--feature-requests).

And maybe include your `config.php`, if you install grocy in a subdirectory, and the complete error message (check also the webserver / PHP logs) - the stacktrace alone is useless...

There are also a lot of links pointing to install guides on https://grocy.info/links.

**Comment by slug1121** [comment]
Thank you berrnd! I've replied to another string in the subreddit, another user having the same issue...
https://www.reddit.com/r/grocy/comments/g50gx9/hosting_on_iis/

**Comment by berrnd** [comment]
When it's the there mentioned "404 HttpNotFoundException" problem, triple check the `BASE_PATH` setting, also mentioned more than a a lot of times in the links of https://grocy.info/links.

https://github.com/grocy/grocy/issues/694#issue-592850273 says:
> ## Conclusion
> Basically, `BASE_PATH` needs to be set to the part (of the URL) after the document root, if URL rewriting is disabled, including `index.php`.

So according to that, when you don't have URL rewriting enabled and access grocy via `https://grocy.mydomain.com/public/index.php/stockoverview`, `BASE_PATH` needs to be `/public/index.php`...
