### ISSUE TITLE
Upgrade to Quagga2 (again)

### ISSUE THREAD

**Issue by berrnd** [grocy/grocy#799]
References https://github.com/grocy/grocy/issues/749#issuecomment-619499413.

**Comment by ericblade** [comment]
If you find any problems, or need any assistance, give me a yell, thanks :)

**Comment by ericblade** [comment]
just dropping a line to let you know that it's up to 1.0.1 now, it should work just the same, but there's been a big amount of internal changes and a slight difference that impacts how people using it with Image and File inputs rather than LiveStream inputs might see it working.

it should still just drop in and replace the old quagga

**Comment by TheBird956** [comment]
What would be the testing requirements for this? I might do the upgrade and see what happens. I have a few issues that I want to know if the updates fixes (camera not focusing right and not scanning, returning the wrong code)

**Comment by ericblade** [comment]
Most of what I've done with Q2 so far has been code modernization, maintenance, updating dependencies, things of that nature, so just replacing the original with the fork probably won't affect much of that.   As far as focus and accuracy goes, there are some things that can be done in the user code (ie, grocy) -- there are various ways to implement error rejection, as well as having camera selection (i'm not familiar with grocy's feature set, so i'm not sure if either are a thing it does already).  Although I've discovered that some phones just plain don't support auto-focus in the browser/webview camera capture, i've also discovered that many phones have different logical or physical cameras that produce very different results.   (ie, my LG G6 has two rear cameras, one is a wide-angle, which is useless for scanning barcodes becuase it fisheyes the image... and it's also the one that the browser selects by default)
