### ISSUE TITLE
Edit Recipe Add Ingredient Not Refreshing Table

### ISSUE THREAD

**Issue by kriddles** [grocy/grocy#803]
I am getting used to the UI Updates which look great! @zsarnett #795 

I noticed when adding ingredients or recipes that the recipe table for those additions are not updated after saving the new item. Can you take a look?

**Comment by kriddles** [comment]
I also tried adding some pictures but they do not seem to work for me.
Failed to load resource: the server responded with a status of 400 (Bad Request) in the console log

**Comment by zsarnett** [comment]
Hmm yea I will take a look

**Comment by organismen** [comment]
I have the same Issue, installed Grocy via home assistant:

Version 2.6.0
Utgiven 2020-01-31 för 3 månader sedan

PHP Version 7.3.14
SQLite Version 3.30.1

**Comment by kriddles** [comment]
> I have the same Issue, installed Grocy via home assistant:
> 
> Version 2.6.0
> Utgiven 2020-01-31 för 3 månader sedan
> 
> PHP Version 7.3.14
> SQLite Version 3.30.1

Thank you, but the current release is 2.7.1 which you will see quite a few feature improvements since 2.6.0. I would recommend upgrading your install.

I should have been clear that this issue is in the Master branch which has not yet been released. It is not an issue in 2.7.1 current release.

**Comment by zsarnett** [comment]
I will be getting to this eventually, hopefully this week.

**Comment by organismen** [comment]
Thanks for heads up @kriddles, I'm new to Grocy since last week and as mentioned I installed directly via home assistant so there is probably som lag between versions. I will definitely install the latest release.

**Comment by organismen** [comment]
I can confirm that the problem still exists in 2.7.1. See GIF.

![rec](https://user-images.githubusercontent.com/3727297/83516940-51c55700-a4d8-11ea-9ba8-bfb9377b0ae4.gif)

I need to close the modal and refresh page manually to see the newly added ingredient.

Please note that I'm using Grocy via home assistant addon install.

**Comment by zagl** [comment]
I had the same problem. Using a complete URL including http(s):// as BASE_URL instead of only the path /grocy/public in config.php fixed it.

Before in config.php:
Setting('BASE_URL', '/grocy/public')
After:
Setting('BASE_URL', 'http://[domain]/grocy/public')

The BASE_URL is used in Javascript code which requires a complete URL at some place (It's the targetOrigin parameter of postMessage(), which has to be a complete URL).
