### ISSUE TITLE
"The amount cannot be lower than 1" error when adding a decimal place to values greater than one

### ISSUE THREAD

**Issue by vorkuta** [grocy/grocy#809]
Encountered when adding ingredients to a recipe.

I was using custom units (1 tsp = 5ml, and the reverse)

I tried entering 1.5 tsp, but got the following error

`The amount cannot be lower than 1`

**Comment by berrnd** [comment]
Maybe the form validation hint is not the best, but partial amounts are generally only possible when the product option "Allow partial units in stock" is enabled - is that set for the product?

**Comment by vorkuta** [comment]
@berrnd this has resolved this issue for me. When I get around to writing up some documentation I will make a note of this.
