### ISSUE TITLE
Tare weight in relation to stock and purchase units?

### ISSUE THREAD

**Issue by crazyelectron-io** [grocy/grocy#810]
I don't understand the handling of tare weight. It is supposed to deal with taking the package weight into account but you can only specify the weight for stock units.

It is stated that:

> This is useful e.g. for flour in jars - on purchase/consume/inventory you always weigh the whole jar, the amount to be posted is then automatically calculated based on what is in stock and the tare weight defined below

And below that you have to specify the tare weight for the _stock quantity unit_.

_An example_

I buy herbs with 25g net weight and 75g gross weight (the tare weight is 50g in this example).
I 'consume' the herbs per teaspoon, so the purchase quantity unit is _bottle_ and the stock qu is _tea spoon_ (with a 1:10 ratio for example, so 2.5g per teaspoon).
Because I have to specify the tare weight per _stock qu_ (teaspoon in this example), I don't really get it. Isn't the tare weight (the packaging) applicable to the _purchase qu_ instead of the stock qu, or am I totally missing the concept here?

**Comment by berrnd** [comment]
If you want to consume teaspoons, I think you don't need tare weight handling. I don't know if it's working correctly with a different purchase/stock QU.

It was created for the example of flour: Purchase and stock QU = Gram. You buy/use whatever amount, you don't need to care, you always just weigh the whole container (also assumes you only have 1) and the difference will be automatically added/removed to/from stock...

**Comment by crazyelectron-io** [comment]
Thanks for clarifying.

> If you want to consume teaspoons, I think you don't need tare weight handling. I don't know if it's working correctly with a different purchase/stock QU.

I assumed it could help me with stock check scenario, like get the gross weight and know how many stock qu was left/used... ;o)

**Comment by berrnd** [comment]
Closing this for now.

Feel free to reopen it, if something needs further clarification.
