### ISSUE TITLE
Chores: Adding Duty Roaster 

### ISSUE THREAD

**Issue by AjayShanker98** [grocy/grocy#812]
Is it possible to add a function to circulate the duty randomly and evenly like a duty roaster?

**Comment by berrnd** [comment]
Depends on what you/mean what by that exactly... (?)

There is an assignment type "Random" and "Who least did first":

![grafik](https://user-images.githubusercontent.com/2161815/80867955-92db0900-8c97-11ea-92fb-f35d51f6941d.png)

If you mean to have a plan, like for example a week-view, where you can assign users to days, that's currently not possible. That would also need to be different for each period type...

**Comment by berrnd** [comment]
So does it work for what you wanted with the current possibilities?

Otherwise feel free to leave this open, all suggestions are welcome (!) - maybe just more info about what you want to have would be needed... :)
