### ISSUE TITLE
Feature Request: 

### ISSUE THREAD

**Issue by ji76** [grocy/grocy#813]
Bonjour, comment l'utiliser sous ios? iphone ou iPad ? 
Merci 
Hello, how to use it on ios? iphone or iPad? 
Thanks

**Comment by berrnd** [comment]
It's just a web app / website. So of course you need a (web)server to run it on, client side only a webbrowser. But please use the [subreddit](https://www.reddit.com/r/grocy/) for questions/help as [stated in README](https://github.com/grocy/grocy#questions--help--bug-reporting--feature-requests), thanks
