### ISSUE TITLE
Request: Allow assigning chores to a specific person

### ISSUE THREAD

**Issue by Germs2004** [grocy/grocy#815]
We can currently assign chores randomly, alphabetically, or "who least did first".  But the most important option is missing: the ability to assign a specific person permanently.  For example, we always want "Dad" to "mow the grass" and we always want "Johnny" to "clean Johnny's bedroom."

Please add an option called "Specified" or "Permanent" or something like that,  and allow us to select a single person to assign the chore to.  When the chore is completed, that person will remain assigned to the chore for when it's due again.

**Comment by berrnd** [comment]
Sorry for coming back on this so late - but that's already possible by using either "In alphabetical order" or "Random" as the assignment type and just assign only one person.
