### ISSUE TITLE
Request: Allow scheduling annual chores on same day every year

### ISSUE THREAD

**Issue by Germs2004** [grocy/grocy#817]
Currently, when we add an "annual" chore, the help text on the page says "_This means the next execution of this chore is scheduled 1 year after the last execution_".  So if I schedule a chore for Jan 1, 2019, but actually execute the chore on Feb 8, 2019, then the help text looks like Grocy will schedule the follow chore for Feb 8, 2020.

This request is to add a checkbox called "always repeat on this specified schedule."  When this checkbox is checked, then this chore will be scheduled for Jan 1, 2019, and Jan 1, 2020, and Jan 1, 2021.  Even if the chores are executed late, the followup chores should still be scheduled for the same date as originally scheduled.

**Comment by berrnd** [comment]
Sorry being late here. You're right, makes totally sense - and the `Yearly` period type is also just the same as using `Daily` and a period interval of 365 days.

So the `Yearly` period type now does exactly what you thought of, schedules the chore on the same day each year (based on the new start date, ref #1612).

All existing `Yearly` chores will be automatically migrated to `Daily` on the upgrade to the next release.

![grafik](https://user-images.githubusercontent.com/2161815/153249034-bf42cd4f-c469-4eeb-95a0-a55487c68818.png)
