### ISSUE TITLE
Request: Activity Reports

### ISSUE THREAD

**Issue by Germs2004** [grocy/grocy#818]
Please consider adding reports that show overviews of activities in Grocy.

For example, a parent may want to see a quick report that shows all chores performed by all users.  It might look like:

All Chores Executed in the past 30 days:
5/4/2020 - change smoke detector batteries - Dad
5/2/2020 - clean bedroom - John
5/1/2020 - take out the trash - John
5/1/2020 - wash the car - Sally
4/22/2020 - bathe the dog - John
etc

and

All Food Consumed in the past 30 days:
5/4/2020 - 1 banana
5/2/2020 - 1 gallon milk
5/1/2020 - 3 eggs
5/1/2020 - 6 potatoes
4/22/2020 - 1 box of Lucky Charms cereal
etc

and

All Food Expired in the past 30 days:
5/4/2020 - 1 pack of cheese
5/2/2020 - 6 pieces of yogurt
etc

**Comment by berrnd** [comment]
I merged this into / added this to #65.
