### ISSUE TITLE
Request: Allow typing new Location on "Create Product" page

### ISSUE THREAD

**Issue by Germs2004** [grocy/grocy#819]
On the Create Product page, there is a dropdown called "Default location".  Please change that to a typeable control so we can either select an existing location from the dropdown list OR type in a new location that will be added to Grocy's list of locations.

This is more convenient than stopping, going to the Locations page to add the location, and then coming back to refresh this Create Product page to be able to select the new Location.

Thank you!

**Comment by Uatschitchun** [comment]
How often do new locations appear!?

**Comment by berrnd** [comment]
Merged into / the same as #1607.
