### ISSUE TITLE
Request: Option to hide Battery features

### ISSUE THREAD

**Issue by Germs2004** [grocy/grocy#821]
Many users never use the battery charging features, so this request is to add an option to hide those features from Grocy.  If I check the box to "Hide Battery features in Grocy," then these things will be hidden:
"Batteries overview" link
"Battery tracking" link
Manage master data > "Batteries" link
"batteries" from the Entity dropdown

This will help keep the interface cleaner.  You may also consider adding options to hide the other built-in features too.

**Comment by berrnd** [comment]
That's already possible, not only for batteries, see the "features flags" in `config.php` (`FEATURE_FLAG_BATTERIES` to hide everything related to batteries):

https://github.com/grocy/grocy/blob/1e07a2dc2e1bb34ad1f5cf5c3a591278128e2320/config-dist.php#L133-L156

**Comment by Germs2004** [comment]
Great, I wasn't aware of that config file before.  Having the settings configurable from the web UI would be convenient but I'm sure you have a reason to keep them separate.  Thank you

**Comment by berrnd** [comment]
> Having the settings configurable from the web UI would be convenient

Sure, would be better - the only reason is that the config file was there before any of the UI config pages ... and some settings (like `BASE_PATH` need to be loaded before any UI rendering happens)...
