### ISSUE TITLE
Request: Make the Night Mode settings global for all users of that device

### ISSUE THREAD

**Issue by Germs2004** [grocy/grocy#822]
Please make Grocy apply "night mode" settings to all users of that device, so if one user changes the Night Mode settings of a device, that should apply to everyone who uses that device.  Grocy would need to be able to detect devices uniquely, which could be done by IP address, cookies, or some other browser-accessible attribute.

For example, there may be a touchscreen computer in the kitchen that everyone shares.  If one person customizes that device's night mode settings, that should apply to all users of that computer.  And some users may access the same instance of Grocy from their smart phones, so those devices may have different settings than the kitchen computer.

This request would help a tech-savvy user to make Grocy easier to use by all the less tech-savvy users.

**Comment by berrnd** [comment]
Merging this into #1334 which was just done - just set the preferred system setting for the corresponding device.
