### ISSUE TITLE
Request: Add an "Add Chore" button to "Chores overview" page

### ISSUE THREAD

**Issue by Germs2004** [grocy/grocy#824]
The "Tasks" page has an "Add" button but the "Chores overview" page does not.  Please add an "Add" button to the "Chores overview" page to make it faster for users to add a new chore.

The current workflow requires 3 clicks and 3 page loads: click "Manage master data", then click "Chores", then click "Add".  The new workflow would just have 1 click with 1 page load, assuming you're already on the "Chores overview" page.

**Comment by berrnd** [comment]
> The "Tasks" page has an "Add" button but the "Chores overview" page does not

Because tasks are thought to be "done once things", chores more something that needs to be done regularly. Once set up, I don't think you'll add new chores daily, but of course such a button would not hurt...

**Comment by berrnd** [comment]
To keep it consistent, let's don't add this.

Chores are meant to be for things that happen regularly, use tasks for one-time things.
