### ISSUE TITLE
Product ownership / roommate setup

### ISSUE THREAD

**Issue by duncanam** [grocy/grocy#827]
While considering this for a roommate setup, some groceries would be shared but some are not. If my roommate and I both like to eat apples, it would be useful to track who is eating what. Perhaps there is a better way to denote shared vs. non-shared resources though.

**Comment by sinni800** [comment]
I just had the same thought. I think a roommate setup could include new attributes on ingress of new items that denote "ownership" of things to one (multiple?) people and whether or not it's a shared thing or not.

**Comment by berrnd** [comment]
With #989 it's now possible to track who added/used a product, visible currently on the stock journal page.

I'll reopen this, as this is more about "product ownership" (roommate setup), I think there is more todo to make this really useful for that use case...

**Comment by berrnd** [comment]
Merged into #418.
