### ISSUE TITLE
Display a QRCode for API Keys & API URL

### ISSUE THREAD

**Issue by berrnd** [grocy/grocy#829]
For clients which use the API, it's required to somewhere type in the grocy API URL & an API Key, which is maybe somehow tedious...

So let's display a QRCode per API Key on the `/manageapikeys` page which contain the API URL and the Key (so use a separator, something like `https://grocy.tld/api|xxyAPIKEYxxy` which could then be scanned by the client (app).

//CC @arjes

**Comment by Forceu** [comment]
I did this for barcode buddy with [this JS library](https://github.com/kazuhikoarase/qrcode-generator), maybe you can reuse some code. 

https://github.com/Forceu/barcodebuddy/blob/master/menu/apimanagement.php
https://github.com/Forceu/barcodebuddy/blob/master/incl/js/scripts.js

**Comment by arjes** [comment]
Sounds like a great usability improvement. I'll follow it and implement once its in dev.

**Comment by berrnd** [comment]
This is now done by #986, excerpt from the changelog:

> ### API improvements/fixes
> - For better integration (apps), it's now possible to show a QR-Code for API keys (thanks @fipwmaqzufheoxq92ebc)
>   - New QR-Code button on the "Manage API keys"-page (top right corner settings menu), the QR-Codes contains `<API-Url>|<API-Key>`
>   - And on the calendar page when using the button "Share/Integrate calendar (iCal)", there the QR-Codes contains the Share-URL (which is displayed in the textbox above)

Also /CC @patzly
