### ISSUE TITLE
Feature Request: Move stock to fridge after opening if indicated by the product ("transfer workflow")

### ISSUE THREAD

**Issue by CrushaKRool** [grocy/grocy#830]
Some products can generally be kept at room temperature in your pantry, but then require to be moved to a refrigerated location after opening them. This is usually written on the product description near the hint about the expiration date.

It could be helpful to automate this process in Grocy:
1. Make it possible to mark locations as "is refrigerated" (similar to "is freezer").
2. Make it possible to mark products as "needs to be refrigerated after opening".
3. When marking a stock entry of such a product as opened, automatically transfer it to the refrigerated location. If multiple locations are marked as "is refrigerated", display a dialog to manually pick a destination.

**Comment by berrnd** [comment]
This is now done in combination with #1365 (new product option "Default consume location") - changelog excerpt:

> - New product option "Move on open" (defaults to disabled)
>    - When enabled, on marking the product as opened, the corresponding amount will be moved to the products default consume location
