### ISSUE TITLE
Tab completion for new product from purchase screen causes failure

### ISSUE THREAD

**Issue by cjramseyer** [grocy/grocy#831]
grocy install on Home Assistant v0.109.4
When on the purchases tab, and entering a new product/barcode to create a new product, the new product screen is shown, then when save is clicked, an error is caused.

The error states: "Page Not Found"

There is also a link to View the homepage, which opens the home assistant overview in the same iframe that grocy was opened in.  Products have to be added to the master list, then quantity add through purchases.  Very cumbersome and time consuming

**Comment by berrnd** [comment]
Most probably something about `BASE_URL` must be wrong, but I don't know how this is handled in Home Assistant. As [mentioned in README](https://github.com/grocy/grocy#questions--help--bug-reporting--feature-requests), please use the [subreddit](https://www.reddit.com/r/grocy/) for general help or for this maybe even better the [Home Assistant AddOn repo](https://github.com/hassio-addons/addon-grocy) or [their forum](https://community.home-assistant.io/t/home-assistant-community-add-on-grocy/112422)...

If you can reproduce this on the current demo, feel free to reopen this issue - I found no problem about what you described...
