### ISSUE TITLE
Embeds don’t scroll on iOS 

### ISSUE THREAD

**Issue by thoppa** [grocy/grocy#833]
Embeds don’t scroll on iOS devices- at least not on my iPad or iPhone. For example, the instruction manuals display only the first page.  I cannot scroll past the first page of any pdf

**Comment by berrnd** [comment]
I will not be really able to reproduce this, as I don't use any iOS device - so any help would be much appreciated to fix this...

**Comment by thoppa** [comment]
I’m not very skilled in this, but I have been messing with custom css to resolve.  I think there’s a solution there, but it may be beyond my skills. Hopefully someone else with iOS devices and greater skills will try

**Comment by thoppa** [comment]
It seems PDF embeds and mobile browsers are a common issue. Most solutions involve third-party helper apps that, to me, are inconsistent with the self-hosting. 

As a work-around, can a suggest placing a link to the file somewhere on the page?  Perhaps near the full screen toggle?  Directly linking to the file, rather than an embed works, and that appears to be the easiest way to work around the mobile browser limitation.

**Comment by berrnd** [comment]
> As a work-around, can a suggest placing a link to the file somewhere on the page? Perhaps near the full screen toggle?

Sure, should be possible, thanks for the suggestion.
