### ISSUE TITLE
FEATURE_SETTING_STOCK_COUNT_OPENED_PRODUCTS_AGAINST_MINIMUM_STOCK_AMOUNT has no effect

### ISSUE THREAD

**Issue by berrnd** [grocy/grocy#834]
_Originally post here: https://www.reddit.com/r/grocy/comments/gcxjbe/how_to_use_opened/fpsjoqu/_

> Add Product, Name = "ketchup", Minimum stock amount = 1
> Purchase 1 bottle of ketchup
> In Stock Overview, mark ketchup as opened

=> Should be considered missing at that point when `FEATURE_SETTING_STOCK_COUNT_OPENED_PRODUCTS_AGAINST_MINIMUM_STOCK_AMOUNT` is set to false, otherwise not.

**Comment by teddybeermaniac** [comment]
Hi,
I encountered the bug myself and after some research I think I found a source of the issue, testing my fix right now, will submit a PR shortly. :smile:

**Comment by teddybeermaniac** [comment]
I made the PR - #855.
