### ISSUE TITLE
Can't purchase 1 unit with tare weight enabled

### ISSUE THREAD

**Issue by winterscar** [grocy/grocy#836]
I have added a 750ml bottle of olive oil to grocy. 
Purchase Unit = bottle
Stock unit = g
To keep track, I would like to use the tare system. So, I input tare weight = 427g.

However, when I try purchase said olive oil, I get the following issue:
![image](https://user-images.githubusercontent.com/11340175/81397818-f8a81480-911f-11ea-8326-936704e30de1.png)

I'm not sure what I'm miss-understanding here? 

Thanks! (Love grocy btw)

**Comment by berrnd** [comment]
See this comment: https://github.com/grocy/grocy/issues/810#issuecomment-621635515

It currently does not really work when having different purchase/stock QUs...

**Comment by winterscar** [comment]
Ok, so if I change the purchase QU to 'g', it should work?

Any idea what's happening under the hood? I'm happy to try have a look into this, but I don't understand where the strange constraint is coming from?

**Comment by berrnd** [comment]
> Ok, so if I change the purchase QU to 'g', it should work?

Yes. See the product "Flour" on the demo as an example: https://demo.grocy.info

> Any idea what's happening under the hood? I'm happy to try have a look into this, but I don't understand where the strange constraint is coming from?

Frontend - the container weight is always based on the stock QU:
https://github.com/grocy/grocy/blob/98f214e9f14d5197f85aaefd38de856bff5da208/public/viewjs/purchase.js#L194-L201

Backend - here also the tare weight is based fixed on the stock QU:
https://github.com/grocy/grocy/blob/98f214e9f14d5197f85aaefd38de856bff5da208/services/StockService.php#L220-L239

**Comment by berrnd** [comment]
Closing this for now.

Feel free to reopen it if any problems/questions on this are still open - tare weight currently only works correctly when the stock/purchase QU is the same.
