### ISSUE TITLE
Unable to assign a chore to a person

### ISSUE THREAD

**Issue by redinsight** [grocy/grocy#837]
Running grocy 2.7.1 and am unable to assign a person to a chore via the dropdown. I have tried on the demo site and was not able to there either.

![image](https://user-images.githubusercontent.com/1321428/81450591-fc4b9380-913f-11ea-9c07-7d92b0a60ea1.png)

Thanks!

**Comment by berrnd** [comment]
Can't reproduce this...

![2020-05-09_08-25-44](https://user-images.githubusercontent.com/2161815/81466047-c0abda80-91ce-11ea-9b7e-585b5a10c3c8.gif)

What browser are you using? Maybe try to check the browser console for errors...

**Comment by redinsight** [comment]
Yep you are correct!

Thanks for your time.

**Comment by kses** [comment]
I have this issue on Safari and Chrome on iOS och Safari and Chrome on macOS . I can only select users with Firefox. Otherwise clicking the greyed out Assign to selector does not do anything.

Adding a gif but a bit unlclear, I click the grey bar and nothing happens.

![chore-error](https://user-images.githubusercontent.com/17168512/82713866-ca344880-9c8c-11ea-8bfc-e504d3695399.gif)

**Comment by berrnd** [comment]
If someone could check the browser console for errors it would maybe help to fix this...

This component is used for the picker: https://github.com/snapappointments/bootstrap-select

Here are the official examples (which then should have the same problem on Safari): https://developer.snapappointments.com/bootstrap-select/examples/

**Comment by kses** [comment]
If I check the javascript consol in safari it shows nothing at all. I also found out that it is intermittent. If I reload the webpage a few times, it sometimes work and sometimes not. It looks slightly different when it does not work from when it work.

The linked examples all worked.

**Comment by kses** [comment]
For some reason I can not recreate the problem on my own Grocy instance, only the demo instance

**Comment by RossMcMillan92** [comment]
I just ran across this too. Assigning chores was originally working great for my user "Ross" and the default "admin". 

It broke for me after doing the following:

1. Remove the admin user
2. Add new user "Person"

I went back to add more chores and it was suddenly broken. Hopefully this narrows the issue down somewhat.

**Comment by RossMcMillan92** [comment]
Seems that bootstrap is just being flakey. I've always got a "disabled" className on the bootstrap-select `button` element. If I remove that manually in the devtools then it works fine.
