### ISSUE TITLE
Reload needed after added barcode to existing product 

### ISSUE THREAD

**Issue by noxhirsch** [grocy/grocy#839]
When scanning a new barcode and adding it to an existing product, Grocy doesn't use that new information if the same item is scanned directly after. Instead it asks again, what to do with the new barcode. If I reload, everything is fine.

**Comment by berrnd** [comment]
Maybe you expect something different how it's thought to work...

1. Scan a unknown barcde
2. Select "Add as barcode to existing product" in the popup
3. => The hint `xyzNEWBARCODE will be added to the list of barcodes for the selected product on submit` is displayed below and the the hint `Barcode lookup is disabled` is displayed above the product picker
4. => You select manually a product, which is used to do the transaction and at the same time the before scanned barcoded is added to the product

So when is a page reload needed?

**Comment by noxhirsch** [comment]
Sorry, now I see that one part wasn't clearly written: I meant, when I want to scan the same item multiple times, because I bought 5 pieces. After I scanned the first item, added it manually to an existing product, I usually would scan the item again 4 times. But if I don't reload the page, Grocy doesn't recognize the barcode of the second item and asks again.
It seems like the new barcode is added to the product on server side, while the barcode to product conversion is done on client side with a "local cache" of the product/barcode table. So the client doesn't know the new barcode until the site gets reloaded.
I hope that clears it up :)

**Comment by berrnd** [comment]
Ok, thanks, got it - yes, that's because the product picker only get's initialized on page load...

So reloading the page after a "Add as barcode to existing product"-workflow would be a workaround, but doing that without reloading the page would be of course nicer...
