### ISSUE TITLE
Store the medical supplies in a specific section

### ISSUE THREAD

**Issue by skylarkbe** [grocy/grocy#841]
As a user, I would like to track the status of all my medical supplies, so that I am informed when I need to buy new ones or take a visit to the doctor to get a prescription.

- Store the name of the medical supply
- Store the expiration date
- Store the _is medical prescription required_
- Possibility to keep multiple medical supplies boxes (for instance, one in the house and one in the car)
- Possibility to store the box as a whole, as a number of tabs, and as pills

This would be a nice and easy improvement imho ; as most of the requirements already exists for the food.

**Comment by berrnd** [comment]
Was already requested before, this should already be possible by using Userfields and/or Userobjects.
See #176 and #242.

Or just by separate locations (I personally do it like that) und us the default stock functionality...

So still unsure if this should be implemented specific for medical things...

**Comment by skylarkbe** [comment]
Thanks for the insight.
I'm a very new user so I'm not yet familiar with all the concepts ; but I'll definitively give it a try !
