### ISSUE TITLE
Chores and shopping list items expand when pressing item actions on iOS

### ISSUE THREAD

**Issue by hype-armor** [grocy/grocy#842]
When pressing the button to journal a chore or pressing the check button on an item in the shopping list, the item expands to show details. I think the details should only show when you press the area to the right of the item's buttons. This seems to only be reproducible on iOS.

**Comment by berrnd** [comment]
I will be unable to reproduce this, as I don't use any iOS device, so any help would be appreciated...

Just strange that iOS/Safari behaves different than Chrome/Firefox for so much detail-things, seems to be new IE lol...

**Comment by berrnd** [comment]
Tables are now horizontally scrollable instead of hiding columns with those "+" icons on small screens, so this should not be a problem anymore.
