### ISSUE TITLE
API keys are not displayed on mobile in portrait mode

### ISSUE THREAD

**Issue by Forceu** [grocy/grocy#843]
When opening the API management page on a Samsung Galaxy S7, the API keys are not displayed when in portrait mode

![2020-05-11 08 40 30](https://user-images.githubusercontent.com/1593467/81551585-60f63080-9382-11ea-8c20-0d4598c35480.jpg)

**Comment by berrnd** [comment]
Could be improved, we had that with other tables too - but they are there, just behind the blue little plus symbol (default DataTables behaviour)...

**Comment by andrelam** [comment]
The same happens on an iPhone.

**Comment by KTibow** [comment]
I think this has been fixed; on an S7, this doesn't happen for me.

**Comment by berrnd** [comment]
This is outdated, all tables are horizontally scrollable since v3.0.0 / #1115.
