### ISSUE TITLE
Frozen does not accept -1 as never expire

### ISSUE THREAD

**Issue by kses** [grocy/grocy#846]
When trying ro use never expire, -1, as default after frozen best before date, the date is instead unchanged.

(Part 2 maybe a feature not a bug: When adding a product to a freezer via the purchase function, it uses the default best before date instead of the frozen best before date which I feel would make more sense.)

<img width="437" alt="e2" src="https://user-images.githubusercontent.com/17168512/81568863-ab85a600-939e-11ea-91aa-87dd6e46de88.png">
<img width="426" alt="e3" src="https://user-images.githubusercontent.com/17168512/81568876-afb1c380-939e-11ea-81aa-069283e37d38.png">

**Comment by berrnd** [comment]
This is not a Docker issue, so I've transfered this to the right repo...

> When trying ro use never expire, -1, as default after frozen best before date, the date is instead unchanged.

Can be added, was just not supposed that `-1` should mean "Never expires" here...

> (Part 2 maybe a feature not a bug: When adding a product to a freezer via the purchase function, it uses the default best before date instead of the frozen best before date which I feel would make more sense.)

This is intentional. On purchase ONLY the default best before date is considered, as the "freezer feature" is explicitly thought to be used when you freeze something yourself ... maybe an option could be added if that date should be considered on purchase when the destination location is a freezer...

**Comment by kses** [comment]
> This is not a Docker issue, so I've transfered this to the right repo...
> 

Sorry, too many tabs open i guess.
Grocy is a fantastic tool. Thank you for working on it and creating it.

> > When trying ro use never expire, -1, as default after frozen best before date, the date is instead unchanged.
> 
> Can be added, was just not supposed that `-1` should mean "Never expires" here...
> 
> > (Part 2 maybe a feature not a bug: When adding a product to a freezer via the purchase function, it uses the default best before date instead of the frozen best before date which I feel would make more sense.)
> 
> This is intentional. On purchase ONLY the default best before date is considered, as the "freezer feature" is explicitly thought to be used when you freeze something yourself ... maybe an option could be added if that date should be considered on purchase when the destination location is a freezer...

What I did, was that with products that is frozen in the store is that they have -1 as default best before and frozen in the name, such as frozen mango. Worked as intended. (They have nothing added to the freezer part of the settings.)
But I might buy a steak (fresh) when the price is good, and put it straight into the freezer, but next time I buy a steak I might put it in the fridge with the intention of using it soon.

For me the optimal thing (and what feels natural) when purchasing to the freezer would be, if nothing is entered in the freezer part, grocy use the default best before, but if something is entered in freezer part of the product config, that would be used instead.
