### ISSUE TITLE
API calls to /stock/products/ are slow

### ISSUE THREAD

**Issue by Forceu** [grocy/grocy#848]
I recently noticed that API calls to `/stock/products/` are rather slow. First I thought it might be because the routing is not cached, but adding 

```
$routeCollector = $app->getRouteCollector();
$routeCollector->setCacheFile(GROCY_DATAPATH . '/routecache');
```

to `app.php` did not increase the performance significantly, therefore the problem is probably somewhere else. My current database has 246 products, 261 stock entries and around 3000 stock logs. Deleting the stock logs did not increase the performance. On average a `/stock/products/` API call takes around 650ms, while a call like `/stock/shoppinglist/remove-product` takes only around 100ms.

Unfortunately I did not find any causes for the problem, do you have any idea how to improve the speed?

**Comment by kriddles** [comment]
I assume you mean pulling an individual product detail with the api?
'/stock/products/{productId}' which calls '\Grocy\Controllers\StockApiController:ProductDetails

ProductDetails pulls from quite a few tables to build the product details information including a few calls to the stock_log table using different parameters which could probably be optimized. It is probably the heaviest api call.

If you're looking for dedicated product information then making a call to the product table would be the fastest. /objects/products/{id}

This recent commit looked to improve performance
1a5f3ce92628e81310d17f4ec1d6ad65282d0ea3

The other recent commits just add more information to product details such as the new feature shopping locations.

**Comment by Forceu** [comment]
```
2020-05-14 17:27:46: Executing API call: objects/products
2020-05-14 17:27:46: Executing took 221ms
2020-05-14 17:27:46: Executing API call: stock/products/255/open
2020-05-14 17:27:46: Executing took 196ms
2020-05-14 17:27:46: Executing API call: system/info
2020-05-14 17:27:47: Executing took 167ms
2020-05-14 17:27:47: Executing API call: stock/products/255
2020-05-14 17:27:47: Executing took 764ms
2020-05-14 17:27:47: Executing API call: stock/products/255/add
2020-05-14 17:27:48: Executing took 873ms
2020-05-14 17:27:48: Executing API call: stock/shoppinglist/remove-product
2020-05-14 17:27:48: Executing took 184ms
2020-05-14 17:27:48: Executing API call: stock/shoppinglist/remove-product
2020-05-14 17:27:49: Executing took 179ms
2020-05-14 17:27:49: Executing API call: stock/shoppinglist/add-product
2020-05-14 17:27:49: Executing took 188ms
2020-05-14 17:27:49: Executing API call: stock/products/255/consume
2020-05-14 17:27:50: Executing took 744ms
2020-05-14 17:27:50: Executing API call: stock/products/by-barcode/TEST
2020-05-14 17:27:50: Executing took 945ms
2020-05-14 17:27:51: Executing API call: stock/products/255/locations
2020-05-14 17:27:51: Executing took 199ms
```

You are right, it is exclusively ProductDetails (I think  `by-barcode`, `add` and `consume` load the product details as well).

The  `/objects/products/{id}` suggestion would be a good idea, especially as for my use the add and consume calls are non-blocking for my application. I am already using 2.7.1, so I assume the commit you linked would already be included?

**Comment by kriddles** [comment]
> The `/objects/products/{id}` suggestion would be a good idea, especially as for my use the add and consume calls are non-blocking for my application. I am already using 2.7.1, so I assume the commit you linked would already be included?
Yes

> /edit: Unfortunately `/objects/products/{id}` does not provide the stock. Maybe the stock calculation could be the problem here? As in that all stock amounts for all products are calculated every time this is called?
Sql views are to provide stock which rolls up lots of information so that could be part of it.

What specific information are you looking for? We can always create an endpoint to try to optimize the request.
/stock/products/{id}/entries could be used and you could just sum up the amounts?

**Comment by Forceu** [comment]
To be fair, it would be probably better to have it in a single API call, therefore it would be probably a good idea to try to optimize the existing one. (Also I assume this would speed up grocy's UI?).

I had a look at `StockService.php`, in which `GetProductDetails` has 11 calls `getDatabase()` - I assume these are all single queries? Maybe it is possible to reduce the number of DB calls there?

**Comment by kriddles** [comment]
> I had a look at `StockService.php`, in which `GetProductDetails` has 11 calls to `getDatabase()` - I assume these are all single queries? Maybe it is possible to reduce the number of DB calls there?

Yes, and my current branches I'm working on add a few more calls and also already consolidate some calls.
There could definitely be more consolidation and there's just a lot going on there which could be split out into more manageable methods.

**Comment by kriddles** [comment]
Some of these should be tracked most likely in a new product_statistics table which would prevent a lot of these calls.
When consume -> update stats table to prevent having to look so much at the stock_log table
Same for when purchase -> update stats, etc.

**Comment by Forceu** [comment]
So I just ran some tests, and the DB calls itself in that function are not the problem, it seems to be `function GetCurrentStock` in `StockService` which takes 500-700ms. I will have a further look into it.

**Comment by Forceu** [comment]
It would be possible to replace the `$sql = 'SELECT * FROM stock_current';` from `GetCurrentStock` with a function below: This one takes less than 10ms compared to 500ms, as only the stock for the product is considered. The code still needs some work before I issue a PR however.

```
function GetCurrentStockSingleProduct(int $productId) {
    
    $childProducts          = $this->getDatabaseService()->ExecuteDbQuery("SELECT id FROM products WHERE parent_product_id=$productId")->fetchAll();
    $amount                 = $this->getDatabaseService()->ExecuteDbQuery("SELECT IFNULL(SUM(amount),0) as amount FROM stock WHERE product_id=$productId")->fetchColumn();
    $amountAggregated       = $this->getDatabaseService()->ExecuteDbQuery("SELECT IFNULL(SUM(amount),0) FROM stock WHERE product_id=$productId" . self::addChildProductIds($childProducts))->fetchColumn();
    $bestBeforeDate         = $this->getDatabaseService()->ExecuteDbQuery("SELECT MIN(best_before_date) FROM stock WHERE product_id=$productId" . self::addChildProductIds($childProducts))->fetchColumn();
    $amountOpened           = $this->getDatabaseService()->ExecuteDbQuery("SELECT IFNULL(SUM(amount),0) FROM stock WHERE open=1 AND product_id=$productId")->fetchColumn();
    $amountOpenedAggregated = $this->getDatabaseService()->ExecuteDbQuery("SELECT IFNULL(SUM(amount),0) FROM stock WHERE open=1 AND (product_id=$productId" . self::addChildProductIds($childProducts) . ")")->fetchColumn();
    $isAggregatedAmount     = "0";
      return array(
        "amount" => $amount,
        "amount_aggregated" => $amountAggregated,
        "best_before_date" => $bestBeforeDate,
        "amount_opened" => $amountOpened,
        "amount_opened_aggregated" => $amountOpenedAggregated,
        "is_aggregated_amount" => $isAggregatedAmount
    );
}
```



@berrnd: I understand that using SQL views makes migrating a lot easier and introduces less bugs, would you rather stick to SQL views or is code like this accepted? Also I noted that in the statement to create the `stock_current` view, `qucr.factor` is only considered for child products, is that intentional?

**Comment by berrnd** [comment]
> @berrnd: I understand that using SQL views makes migrating a lot easier and introduces less bugs, would you rather stick to SQL views or is code like this accepted? Also I noted that in the statement to create the stock_current view, qucr.factor is only considered for child products, is that intentional?

Anything which improves things is ok, I don't have a hard-coded preference - just had the idea at first to put all/most of the logic into SQL (views/triggers/etc.), but not everything is possible by that approach...

The current version of the `stock_current` view is [this](https://github.com/grocy/grocy/blob/98f214e9f14d5197f85aaefd38de856bff5da208/migrations/0100.sql). I think that's ok. Only when "rolling up" child product amounts into parent products QU conversions need to be considered, if the child/parent products not have the same QU, otherwise (second SELECT of the UNION) that's not needed...

**Comment by berrnd** [comment]
The `/stock/products/*` endpoints should now be noticeable faster (done by @fipwmaqzufheoxq92ebc in #927).
