### ISSUE TITLE
help with install

### ISSUE THREAD

**Issue by amanalar** [grocy/grocy#850]
Hello I saw this git mentioned on a sub I frequent and thought I'd give it a try. I'm having issues getting this to run in Ubuntu wit nginx.

I am using latest release:
wget https://github.com/grocy/grocy/releases/download/v2.7.1/grocy_2.7.1.zip

I put that into /var/www/grocy

The error I am getting is

404 Not Found
The application could not run because of the following error:

Details
Type: Slim\Exception\HttpNotFoundException
Code: 404
Message: Not found.
File: /var/www/grocy/vendor/slim/slim/Slim/Middleware/RoutingMiddleware.php
Line: 93
Trace
#0 /var/www/grocy/vendor/slim/slim/Slim/Middleware/RoutingMiddleware.php(59): Slim\Middleware\RoutingMiddleware->performRouting(Object(Slim\Http\ServerRequest))
#1 /var/www/grocy/vendor/slim/slim/Slim/MiddlewareDispatcher.php(140): Slim\Middleware\RoutingMiddleware->process(Object(Slim\Http\ServerRequest), Object(Slim\Routing\RouteRunner))
#2 /var/www/grocy/vendor/slim/slim/Slim/Middleware/ErrorMiddleware.php(107): class@anonymous->handle(Object(Slim\Http\ServerRequest))
#3 /var/www/grocy/vendor/slim/slim/Slim/MiddlewareDispatcher.php(140): Slim\Middleware\ErrorMiddleware->process(Object(Slim\Http\ServerRequest), Object(class@anonymous))
#4 /var/www/grocy/vendor/slim/slim/Slim/MiddlewareDispatcher.php(81): class@anonymous->handle(Object(Slim\Http\ServerRequest))
#5 /var/www/grocy/vendor/slim/slim/Slim/App.php(215): Slim\MiddlewareDispatcher->handle(Object(Slim\Http\ServerRequest))
#6 /var/www/grocy/vendor/slim/slim/Slim/App.php(199): Slim\App->handle(Object(Slim\Http\ServerRequest))
#7 /var/www/grocy/app.php(68): Slim\App->run()
#8 /var/www/grocy/public/index.php(27): require_once('/var/www/grocy/...')
#9 {main}

this is what my server block looks like:

server  {
        listen          80;
        listen          [::]:80;
        server_name     grocy.example.com;
        root /var/www/grocy/public;
        index index.php;
        try_files $uri /index.php$is_args$query_string;
        access_log /var/log/nginx/grocy_access.log;
        error_log /var/log/nginx/grocy_error.log info;

        location = /robots.txt {
                add_header  Content-Type  text/plain;
                return 200 "User-agent: *\nDisallow: /\n";
        }
                location ~ \.php$ {
                try_files $uri = 404; 
                fastcgi_pass unix:/var/run/php/php7.2-fpm.sock;
                fastcgi_index index.php;
                include /etc/nginx/fastcgi.conf;
        }
}

**Comment by berrnd** [comment]
Please see [this](https://github.com/grocy/grocy/issues/694#issuecomment-609079721) and use the [subbredit](https://www.reddit.com/r/grocy/) for general help as [mentioned in README](https://github.com/grocy/grocy#questions--help--bug-reporting--feature-requests), thanks.
