### ISSUE TITLE
Expiry Vs Best Before

### ISSUE THREAD

**Issue by Wordna1** [grocy/grocy#851]
Does Grocy currently distinguish between Best Before and Expiry dates?  If not, this is a feature request as there is a significant difference between "Best Before" and Expiry.

**Comment by kriddles** [comment]
There is no distinction at the moment so this would be a new feature.

**Comment by kriddles** [comment]
I would assume that you would choose to either have an expiry date or a best before date set at the product or use the  config to have have neither dates.

**Comment by berrnd** [comment]
Kind of related to #699.

**Comment by Wordna1** [comment]
>Kind of related to #699.

Yes, it is related in the sense that Expiry Dates are definitely more severe/important than Best Before Dates since the latter refers to freshness.  However, both come directly off the label and therefore aren't as subjective as #699 

> I would assume that you would choose to either have an expiry date or a best before date set at the product or use the config to have have neither dates.

I'm not 100% sure, but I believe food has EITHER an Expiry date OR a Best Before date OR neither.  So the user should be able to select at the product level which is intended.

**Comment by jglauche** [comment]
> I'm not 100% sure, but I believe food has EITHER an Expiry date OR a Best Before date OR neither. So the user should be able to select at the product level which is intended.

by law (here in Germany), it either has a "use by" or "best before" date, there's no neither. 

"use by" is primarily used in food that will go bad quickly (like raw meat, unpasteurized milk) and is likely to become a health hazard when consumed afterwards.

a passed "best before" date does not suggest that the food has gone bad and some foods (say mustard) will have to have a "best before" date on their package but they will never ever go bad. 

I'd be in favor that we both be able to track the type of label and the severity of how long things last.

**Comment by duracell** [comment]
There is a "neither" in the EU, the "[EU-Lebensmittelinformationsverordnung (LMIV)](https://eur-lex.europa.eu/LexUriServ/LexUriServ.do?uri=OJ:L:2011:304:0018:0063:de:PDF)" is the regulation of food, you can see it on page 57, point "d)"

But it sounds good to give the ability to track both!

**Comment by adec** [comment]
I’d definitely find this enhancement valuable - particularly if products past their “best before” date were highlighted in a different colour other than Red.  Perhaps grey?

**Comment by berrnd** [comment]
There is now a product option to distinguish between best before dates and expiration dates.

No new functionality for now, except different highlighting on the stock overview page.
Let's discuss more functionality changes for this in #699.

I focused more on wording changes here, which is also imported, I think.

Let me know if you have any further suggestions, excerpt from the changelog: 🙂

> - Changes about best before dates: It's now possible to distinguish between best before dates and expiration dates:
>   - New product option "Due date type" (defaults to "Best before date")
>   - Wording changes:
>     - All current places where "Best before date" was used now use "Due date"
>     - Products with `Due date type = Best before date` (so all existing products) are "due" or "overdue" (they don't "expire" or are "expired")
>     - Products with `Due date type = Expiration date` (new option) can "expire" or are "expired"
>   - Color changes:
>     - Prducts which are due soon or expire soon are (still) highlighted in yellow
>     - Products which are overdue are highlighted in grey (there is is also a new filter button on the stock overview page for them)
>     - Products which are expired (new option) are highlighted in red

**Comment by berrnd** [comment]
Can also be played around with on the pre-release demo: https://demo-prerelease.grocy.info

Demo product with `Due date type = Expiration date` is `Minced meat".
