### ISSUE TITLE
ReturnTo Element incorrect when using "Add as new Product"

### ISSUE THREAD

**Issue by dmintz7** [grocy/grocy#852]
When adding a new product from the Inventory, Shopping List, etc screen a popup appears giving options on how to enter the new item. When selecting "Add as new Product", the returnto element in the URL contains the domain of the website instead of the subdirectory

For example instead of https://grocy.example.com/product/new?prefillname=Eggs&returnto=%2Fshoppinglistitem%2Fnew the url is https://grocy.example.com/product/new?prefillname=Eggs&returnto=%2Fhttps%3A%2Fgrocy.example.com%2Fshoppinglistitem%2Fnew

This causes a 404 Not Found error after submitting the new product

**Comment by kriddles** [comment]
What are some of the settings in your config.php? mainly base_path and base_url?
perhaps those need to be updated?

**Comment by dmintz7** [comment]
Setting('BASE_PATH', '');
Setting('BASE_URL', '');

Should they have a single slash?

**Comment by dmintz7** [comment]
Single slash on Base URL fixed it. Must have removed inadvertently
