### ISSUE TITLE
Quantity of an ingredient in the recipe is displayed as 0

### ISSUE THREAD

**Issue by amo42** [grocy/grocy#853]
Hi, I'm new to grocy and think I'm not understanding the logic for units and products, here's my use case:

Deutsch:
Ich habe ein Produkt „Mehl“ mit den Einheiten, „g" and „kg“. 1kg entspricht 1000g und 1g entspricht 0,001kg. 
In einem Rezept möchte ich nun 240g „Mehl“ benutzen. Wenn ich das eintrage und speichere, wird es aber immer wieder mit 0g angezeigt. Wenn ich dagegen 1kg wähle, dann wird auch 1kg angezeigt.

English:
I have a product "flour" with units of "g" and "kg". 1kg equals 1000g and 1g equals 0.001kg. 
In a recipe, I want to use 240g "flour". But when I enter and save this, it is always shown with 0g. On the other hand, if I choose 1kg, 1kg is also displayed.

![image](https://user-images.githubusercontent.com/12328155/82017524-9f8e3280-9683-11ea-8c68-3d76538f7b98.png)

![image](https://user-images.githubusercontent.com/12328155/82017548-b03ea880-9683-11ea-91fa-17cabb8a35e1.png)

Thanks in advance
Andreas

**Comment by berrnd** [comment]
Two ideas:
- Check if "Allow partial units in stock" (product option) is enabled for Mehl
- Decimal separators need to be browser locale specific - so maybe check if comma/dot is correct based on the browser language

**Comment by Tricade** [comment]
You need to make it like this. 
![grafik](https://user-images.githubusercontent.com/6281655/82157996-36760d00-9885-11ea-8cd4-79b1347b3773.png)

If you make it like this, it wont work correctly.
![grafik](https://user-images.githubusercontent.com/6281655/82158009-4c83cd80-9885-11ea-907a-84b827d2d317.png)

German: Bin auch durch mein Mehl drauf gekommen. :-)

**Comment by Tricade** [comment]
Causal Bug ->

![grafik](https://user-images.githubusercontent.com/6281655/82158066-ae443780-9885-11ea-851c-210911c86c89.png)

The costs dont show up correctly

**Comment by Tricade** [comment]
After a short test can i confirm that upper posted bug.
i tested it with "Leitungswasser" xD
![grafik](https://user-images.githubusercontent.com/6281655/82158191-9de08c80-9886-11ea-926a-3dc1474b6d1f.png)

**Comment by amo42** [comment]
Hi @berrnd ,

I've set partial to true and tried the german 0,xx as well as the dot-notation with 0.xx.

Mehl is set up this way:

<img width="632" alt="Produkt_bearbeiten___grocy" src="https://user-images.githubusercontent.com/12328155/82158317-59092580-9887-11ea-86c1-72c5d60561c5.png">

**Comment by Tricade** [comment]
![grafik](https://user-images.githubusercontent.com/6281655/82158486-830f1780-9888-11ea-8db6-2669ad970ea7.png)
@amo42 Your mehlt result
![grafik](https://user-images.githubusercontent.com/6281655/82158496-928e6080-9888-11ea-944b-b884f6f01434.png)
with this factors
![grafik](https://user-images.githubusercontent.com/6281655/82158504-a043e600-9888-11ea-9e37-0f40e1560610.png)
in that

**Comment by Tricade** [comment]
@amo42 Are you using a raspi installation too? Maybe it happens just in that case.

**Comment by amo42** [comment]
@Tricade no, it is running on a Standard Webserver 

@berrnd now ist Works. I had to set the factor within the product as recommended by @Tricade

![image](https://user-images.githubusercontent.com/12328155/82184131-6524cf80-98e7-11ea-84c9-eb57e259920b.jpeg)

Is this the the expected behavior? In yes, we can close this issue. Even if this is not very handy.

Best
Andreas

**Comment by Tricade** [comment]
@amo42 Did it calculate the costs correctly for you? With this config the costs for a reciep isnt calculated correctly for me.

**Comment by amo42** [comment]
![image](https://user-images.githubusercontent.com/12328155/82190150-e2087700-98f0-11ea-8715-614ecb201ccd.jpeg)

@Tricade   Since only the flour does cost something, this works now as well

**Comment by Tricade** [comment]
@amo42 Change it to 5 Portionen ;-)

**Comment by amo42** [comment]
@Tricade  for me, everything works even with 5 servings (or any other number)

![image](https://user-images.githubusercontent.com/12328155/82406953-3b46e680-9a68-11ea-95d6-580d337dabc8.png)
