### ISSUE TITLE
Update to 2.7.1 error at Einkauf

### ISSUE THREAD

**Issue by witzker** [grocy/grocy#854]
Hi
I updated to 2.7.1
when I click on 
![image](https://user-images.githubusercontent.com/4120266/82076570-56b79780-96de-11ea-9698-2dcc42a8b4cc.png)

This appears:

![image](https://user-images.githubusercontent.com/4120266/82076711-86ff3600-96de-11ea-8a9b-dcf0c9b3c168.png)

Pls Help To Solve

also, problem with inventory
![image](https://user-images.githubusercontent.com/4120266/82076874-be6de280-96de-11ea-9db6-9fe43c814784.png)

**Comment by witzker** [comment]
Stated new everythin OK so far
POST can be deleted

**Comment by berrnd** [comment]
Database migrations run when visiting the root route, also [mentionend in README](https://github.com/grocy/grocy#database-migrations)...
