### ISSUE TITLE
Editing ingredient resets QU and can cause issues with amounts

### ISSUE THREAD

**Issue by vorkuta** [grocy/grocy#858]
When editing ingredients of recipes I have been running into issues with QUs.

Example: I have an ingredient that is stored in ml, and has a QU to tablespoons. A tablespoon is 15ml.

I add the ingredient as 3 x tbsp.

When I edit the ingredient, the values have changed to 

**Amount:** 2.999992

**Wuantit unit:** ml

The ingredients list looks fine before editing, it only shows up when editing.

**Comment by berrnd** [comment]
So the factor is `6.6666666...`, that's the problem...

Is already tracked in #389, to make this possible we would need to handle "real fractions" or somehow workaround that problem by reasonable roundings at some point...
