### ISSUE TITLE
How to help with documentation?

### ISSUE THREAD

**Issue by kses** [grocy/grocy#859]
I want to help where I can on this great project! But I am not a software developer.
What is the best way to help with documentation?

Should I make pull request on the readme file? Or send a pdf somewhere? Or something else?

**Comment by berrnd** [comment]
> I want to help where I can on this great project!

That would be awesome! :)

Someone already started some things:
https://github.com/grocy/docs
https://www.reddit.com/r/grocy/comments/g43ras/startup_guide/

So feel free to contribute there or start something new if that doesn't fit - but I think a separate repo would be best in general...

**Comment by kses** [comment]
https://github.com/grocy/docs
I did not know that one existed. I will try to extend it. I feel reddit is great when you know the basics but can be a bit confusing and all over the place when getting started.

**Comment by kses** [comment]
I think I have managed to do PR to the docs project. If not I will find some more git/github tutorials...

**Comment by berrnd** [comment]
Thanks a lot! :)

As I cannot maintain the docs in general, is it ok for you that I just give you write permissions for the grocy/docs repo? Feel free to add then anything you find useful / helps others.

**Comment by kses** [comment]
Sure, new to github but I will figure it out.

**Comment by berrnd** [comment]
Great, you should see a invitation here: https://github.com/grocy/docs/invitations

**Comment by golD-Line** [comment]
@berrnd perhaps add the link so people can help with docs to the grocy.info/#say-thanks webpage.

And I want to say thanks :) This software includes a lot of great features
