### ISSUE TITLE
Feature Request: Product opened

### ISSUE THREAD

**Issue by BlizzWave** [grocy/grocy#86]
Would it be possible to have a way of showing that a product have been opened?
For example you are making something that requires flour, but only 200 grams of it and your quantity unit is 1000 grams.
You would not press consume in grocy, because you have not used the whole thing.

**Comment by berrnd** [comment]
Great idea (best to be done in combination with #62)...

**Comment by Forceu** [comment]
Yes, it would be great to have that. Also it would be good to have an option to change the Best Before date once it is opened with an option to enter it in the master product overview.

Eg. when adding a new product add the standard expiry date when unopened and the standard expiry date once it is opened from that day on.

**Comment by berrnd** [comment]
I implemented this now like the following:

- A product can be marked as opened from the consume page (new button next to the OK button) or from the stock overview page (new button right to the consume all button)
- On the product edit page there can be "Default best before days after opened" defined - this replaces the best before date when marking a product as opened (when > 0)
- On the consume page it is now also possible to pick a specific stock item (#62) - in the dropdown it is mentioned if a stock item is opened or not
- Like all stock bookings, "opening a product" can be undone on the stock journal page

Let the know if this works for you or if you have any other suggestions on this - can be tested on [the pre-release demo](https://demo-prerelease.grocy.info) (will prepare a new release tomorrow).

**Comment by BlizzWave** [comment]
Your implimentation is spot on! Need to do some more testing. Testing in general actually, been away for work for a month. 
A lot of cool progress in that month thanks to ideas from other people. And your "Life runs on code" mentality :-)

Do you have a rough time when you are going to release tomorrow?
Reason I ask is that I have some translating and fine tuning of the norwegian language to do.

**Comment by berrnd** [comment]
Thanks a lot - also for the translation all the time! :)
(As far I can see on Transifex only the new translations are missing for Norwegian - will also update the source files in a moment - this needs also to be automated soon.)

Just wanted to push a new release tomorrow because it has been 3 weeks since the last one - will have a couple of hours to work on grocy tommorrow - so maybe it's better to do some general fine tuning and postpone the release to next week...

**Comment by BlizzWave** [comment]
Decisions decisions. Hehe.
I would love a release tomorrow, but on the other hand my latest translation is actually totally wrong. 
I translated directly without actually looking for where the wording would appear. Some looks plain stupid. Haha

**Comment by berrnd** [comment]
:D, so I think we postpone the release to next weekend, there are also enough open enhancements or smaller UI things or the automation things I could work on tomorrow...

**Comment by BlizzWave** [comment]
Yeah, I think you are right. Also I might find issues with the "Open product" feature.
