### ISSUE TITLE
Seeing belowminstockamount xxUNDONExx in shopping list after adding items that are below stock level

### ISSUE THREAD

**Issue by Jeltel** [grocy/grocy#862]
Just doing our weekly shopping planning. Adding ingredients for recipes, checking stock level and then pressing the mighty 'add items that are below stock level button'

And then this happens:
![Screenshot_20200519-202011](https://user-images.githubusercontent.com/1732436/82363506-36554900-9a0e-11ea-9103-3764666fd662.jpg)

The headers now contain belowminstockamount xxUNDONExx which do not go away after a refresh or relogin.
Unhandy since shopping tomorrow is going to be a bit complicated.

What's going on?

**Comment by Jeltel** [comment]
Only on my user. Other users sees the correct headers

**Comment by berrnd** [comment]
Maybe just a browser problem (column ordering and so on is saved in local storage), mabye try to delete all browser caches or try a different browser to check if that's the problem...

**Comment by Forceu** [comment]
I have had that once as well, only happened on my phone however. It was gone after I updated Grocy, so I thought it had been fixed with the new version.

**Comment by berrnd** [comment]
There are hidden columns which contain the in the screenshot above visible contents (used for "Filter by status"). I was not able to reproduce this so far on small screens...

**Comment by Jeltel** [comment]
It's gone again yes. Weird. When I see it again I'll try to remember exactly what I've done.

**Comment by berrnd** [comment]
Closing this for now.

If this is reproducible, feel free to reopen it.
