### ISSUE TITLE
How to setup development environment?

### ISSUE THREAD

**Issue by TheBird956** [grocy/grocy#863]
Hi!

I am trying to set up a dev environment, but I can't seem to get it right. I am running on Windows 10.

I first try going the docker route but I quickly got to permission errors (need to assign www-data owner on all files, can't mount aw volume because of that and `chown` is taking a very long time, don't want to troubleshoot docker on windows)

I used Xampp as a fallback but whatever I do I am stuck with this 404 error:
```
404 Not Found
The application could not run because of the following error:

Details
Type: Slim\Exception\HttpNotFoundException
Code: 404
Message: Not found.
File: E:\xampp\htdocs\grocy\vendor\slim\slim\Slim\Middleware\RoutingMiddleware.php
Line: 93
Trace
#0 E:\xampp\htdocs\grocy\vendor\slim\slim\Slim\Middleware\RoutingMiddleware.php(59): Slim\Middleware\RoutingMiddleware->performRouting(Object(Slim\Http\ServerRequest))
#1 E:\xampp\htdocs\grocy\vendor\slim\slim\Slim\MiddlewareDispatcher.php(140): Slim\Middleware\RoutingMiddleware->process(Object(Slim\Http\ServerRequest), Object(Slim\Routing\RouteRunner))
#2 E:\xampp\htdocs\grocy\vendor\slim\slim\Slim\Middleware\ErrorMiddleware.php(107): class@anonymous->handle(Object(Slim\Http\ServerRequest))
#3 E:\xampp\htdocs\grocy\vendor\slim\slim\Slim\MiddlewareDispatcher.php(140): Slim\Middleware\ErrorMiddleware->process(Object(Slim\Http\ServerRequest), Object(class@anonymous))
#4 E:\xampp\htdocs\grocy\vendor\slim\slim\Slim\MiddlewareDispatcher.php(81): class@anonymous->handle(Object(Slim\Http\ServerRequest))
#5 E:\xampp\htdocs\grocy\vendor\slim\slim\Slim\App.php(215): Slim\MiddlewareDispatcher->handle(Object(Slim\Http\ServerRequest))
#6 E:\xampp\htdocs\grocy\vendor\slim\slim\Slim\App.php(199): Slim\App->handle(Object(Slim\Http\ServerRequest))
#7 E:\xampp\htdocs\grocy\app.php(68): Slim\App->run()
#8 E:\xampp\htdocs\grocy\public\index.php(27): require_once('E:\\xampp\\htdocs...')
#9 {main}
```

I made sure that config.php was copied in `data/` and ran `composer install` and `npm install` but I don't know where to go from here.

**Comment by berrnd** [comment]
That depends on personal preference, so many solutions/IDEs out there, some might prefer to just use a plain text editor...

I personally also use Windows and just use Visual Studio Code with some plugins.

See #811 or here something more I described in a mail some time ago:
> So for grocy development I use [Visual Studio Code](https://code.visualstudio.com/) (most notably helpful extensions would be [“GitHub Pull Requests”](https://marketplace.visualstudio.com/items?itemName=GitHub.vscode-pull-request-github), [“Laravel Blade Snippets”](https://marketplace.visualstudio.com/items?itemName=onecentlin.laravel-blade), [“OpenAPI (Swagger) Editor”](https://marketplace.visualstudio.com/items?itemName=42Crunch.vscode-openapi), [“PHP Debug”](https://marketplace.visualstudio.com/items?itemName=felixfbecker.php-debug), [“PHP IntellliSense”](https://marketplace.visualstudio.com/items?itemName=felixfbecker.php-intellisense) and [“PHP Server”](https://marketplace.visualstudio.com/items?itemName=brapifra.phpserver)).

> So I just open the checked out grocy folder in VSCode and can start a PHP server right from there, all changes are “live” immediately.
> For better/more Git access/commits/etc. I also use, beside the in VSCode integrated things, [TortoiseGit](https://tortoisegit.org/).
> And also using a separate Browser ([Firefox Developer Edition](https://www.mozilla.org/en-US/firefox/developer/)), but just because I want to have the development things separated.

**Comment by TheBird956** [comment]
I tried the setup described but I still get the same error in my browser. I also have this on the PHP server output:
```
[Sat May 23 00:51:10 2020] [404] /index.php/stockoverview - No such file or directory 
[Fri May 22 18:51:10 2020] [::1]:60077 [404]: GET /index.php/stockoverview
```

**Comment by berrnd** [comment]
Maybe you have not set the `/public` directory as the root directory?

I use the in PHP integrated development web server, the [VSCode PHP Server Plugin](https://marketplace.visualstudio.com/items?itemName=brapifra.phpserver) starts that server with the proper root directory set because of the setting referenced in [`.vscode/settings.json`](https://github.com/grocy/grocy/blob/master/.vscode/settings.json)...

**Comment by TheBird956** [comment]
Yeah I noticed that setting when cloning and did not play with it. Changing it to the default breaks it more so I know it works.

I tried installing PHP differently (using windows IIS instead of Xampp) but it did not change anything.

What is your OS? How did you install PHP and which version? Do I need some specific PHP extensions?

**Comment by berrnd** [comment]
> What is your OS? How did you install PHP and which version? Do I need some specific PHP extensions?

I only use Windows on clients/workstations and always the latest PHP release, so currently 7.4 ([that one](https://windows.php.net/downloads/releases/php-7.4.6-nts-Win32-vc15-x64.zip), just unpacked the ZIP in a directory in my `PATH`). The required PHP extensions are mentioned here (and checked by grocy):
https://github.com/grocy/grocy/blob/98f214e9f14d5197f85aaefd38de856bff5da208/helpers/PrerequisiteChecker.php#L5

**Comment by TheBird956** [comment]
I replicated the setup as you mentioned, and I am still getting a 404 error.
I managed to get it in a docker container running the php:7.3-apache image and I also have the same error

```
404 Not Found
The application could not run because of the following error:

Details
Type: Slim\Exception\HttpNotFoundException
Code: 404
Message: Not found.
File: /var/www/html/vendor/slim/slim/Slim/Middleware/RoutingMiddleware.php
Line: 93
Trace
#0 /var/www/html/vendor/slim/slim/Slim/Middleware/RoutingMiddleware.php(59): Slim\Middleware\RoutingMiddleware->performRouting(Object(Slim\Http\ServerRequest))
#1 /var/www/html/vendor/slim/slim/Slim/MiddlewareDispatcher.php(140): Slim\Middleware\RoutingMiddleware->process(Object(Slim\Http\ServerRequest), Object(Slim\Routing\RouteRunner))
#2 /var/www/html/vendor/slim/slim/Slim/Middleware/ErrorMiddleware.php(107): class@anonymous->handle(Object(Slim\Http\ServerRequest))
#3 /var/www/html/vendor/slim/slim/Slim/MiddlewareDispatcher.php(140): Slim\Middleware\ErrorMiddleware->process(Object(Slim\Http\ServerRequest), Object(class@anonymous))
#4 /var/www/html/vendor/slim/slim/Slim/MiddlewareDispatcher.php(81): class@anonymous->handle(Object(Slim\Http\ServerRequest))
#5 /var/www/html/vendor/slim/slim/Slim/App.php(215): Slim\MiddlewareDispatcher->handle(Object(Slim\Http\ServerRequest))
#6 /var/www/html/vendor/slim/slim/Slim/App.php(199): Slim\App->handle(Object(Slim\Http\ServerRequest))
#7 /var/www/html/app.php(68): Slim\App->run()
#8 /var/www/html/public/index.php(27): require_once('/var/www/html/a...')
#9 {main}
```

**Comment by TheBird956** [comment]
Here's the Dockerfile if you want to take a look

https://github.com/TheBird956/grocy/blob/docker-dev/Dockerfile.dev

**Comment by berrnd** [comment]
Closing this for now, see https://github.com/grocy/grocy/pull/904#issuecomment-675562451.
