### ISSUE TITLE
Problem with Meal Plan View

### ISSUE THREAD

**Issue by Miker26** [grocy/grocy#864]
I deleted a product in the database. When I went to the meal plan view I got the error below instead. I can restore an earlier backup but this will lose a lot of stored information. Can anyone suggest an alternative cure please?
Slim Application Error
The application could not run because of the following error:

Details
Type: Exception
Code: 0
Message: Product does not exist
File: C:\Users\User\.grocy-desktop\grocy\services\StockService.php
Line: 105
Trace
#0 C:\Users\User\.grocy-desktop\grocy\controllers\RecipesController.php(161): Grocy\Services\StockService->GetProductDetails(45)
#1 C:\Users\User\.grocy-desktop\grocy\vendor\slim\slim\Slim\Handlers\Strategies\RequestResponse.php(43): Grocy\Controllers\RecipesController->MealPlan(Object(Slim\Http\ServerRequest), Object(Slim\Http\Response), Array)
#2 C:\Users\User\.grocy-desktop\grocy\vendor\slim\slim\Slim\Routing\Route.php(381): Slim\Handlers\Strategies\RequestResponse->__invoke(Array, Object(Slim\Http\ServerRequest), Object(Slim\Http\Response), Array)
#3 C:\Users\User\.grocy-desktop\grocy\vendor\slim\slim\Slim\MiddlewareDispatcher.php(81): Slim\Routing\Route->handle(Object(Slim\Http\ServerRequest))
#4 C:\Users\User\.grocy-desktop\grocy\middleware\SessionAuthMiddleware.php(43): Slim\MiddlewareDispatcher->handle(Object(Slim\Http\ServerRequest))
#5 C:\Users\User\.grocy-desktop\grocy\vendor\slim\slim\Slim\MiddlewareDispatcher.php(283): Grocy\Middleware\SessionAuthMiddleware->__invoke(Object(Slim\Http\ServerRequest), Object(Slim\MiddlewareDispatcher))
#6 C:\Users\User\.grocy-desktop\grocy\vendor\slim\slim\Slim\MiddlewareDispatcher.php(81): class@anonymous->handle(Object(Slim\Http\ServerRequest))
#7 C:\Users\User\.grocy-desktop\grocy\vendor\slim\slim\Slim\Routing\Route.php(341): Slim\MiddlewareDispatcher->handle(Object(Slim\Http\ServerRequest))
#8 C:\Users\User\.grocy-desktop\grocy\vendor\slim\slim\Slim\Routing\RouteRunner.php(84): Slim\Routing\Route->run(Object(Slim\Http\ServerRequest))
#9 C:\Users\User\.grocy-desktop\grocy\vendor\slim\slim\Slim\Middleware\RoutingMiddleware.php(60): Slim\Routing\RouteRunner->handle(Object(Slim\Http\ServerRequest))
#10 C:\Users\User\.grocy-desktop\grocy\vendor\slim\slim\Slim\MiddlewareDispatcher.php(140): Slim\Middleware\RoutingMiddleware->process(Object(Slim\Http\ServerRequest), Object(Slim\Routing\RouteRunner))
#11 C:\Users\User\.grocy-desktop\grocy\vendor\slim\slim\Slim\Middleware\ErrorMiddleware.php(107): class@anonymous->handle(Object(Slim\Http\ServerRequest))
#12 C:\Users\User\.grocy-desktop\grocy\vendor\slim\slim\Slim\MiddlewareDispatcher.php(140): Slim\Middleware\ErrorMiddleware->process(Object(Slim\Http\ServerRequest), Object(class@anonymous))
#13 C:\Users\User\.grocy-desktop\grocy\vendor\slim\slim\Slim\MiddlewareDispatcher.php(81): class@anonymous->handle(Object(Slim\Http\ServerRequest))
#14 C:\Users\User\.grocy-desktop\grocy\vendor\slim\slim\Slim\App.php(215): Slim\MiddlewareDispatcher->handle(Object(Slim\Http\ServerRequest))
#15 C:\Users\User\.grocy-desktop\grocy\vendor\slim\slim\Slim\App.php(199): Slim\App->handle(Object(Slim\Http\ServerRequest))
#16 C:\Users\User\.grocy-desktop\grocy\app.php(68): Slim\App->run()
#17 C:\Users\User\.grocy-desktop\grocy\public\index.php(27): require_once('C:\\Users\\User\\....')
#18 {main}
Go Back

**Comment by berrnd** [comment]
See https://www.reddit.com/r/grocy/comments/fsfl1y/gf_accidentally_deleted_parent_product/.

Manually recreating the missing product (id) is the only way to fix that currently...

**Comment by berrnd** [comment]
Closing this for now.

#565 is implemented now to archive products instead of deleting them, so this should not happen again.
