### ISSUE TITLE
Provide as a Yunohost-App

### ISSUE THREAD

**Issue by nr458h** [grocy/grocy#865]
Hi all,

self-hosting is a great thing. If you are able to manage all the settings etc.

There is a project called [Yunohost](yunohost.org). It provides a self-hosting OS for people who aren't able to configure all the open source apps out there.

Probably you want to provide your app this way too?

Greetings

**Comment by berrnd** [comment]
Maybe it would be better to request that in their community (personally don't use any "selfhosting server")...

**Comment by nr458h** [comment]
Thanks for the quick reply.
I already did ;) just wanted to spread the idea - that it would fit your project.

If there is no interest on your side I would close this issue.

Thanks anyway and nice project!

**Comment by berrnd** [comment]
So is there now a Yunohost app for grocy?

Otherwise we better leave this open unless someone starts working on such an app...

**Comment by nr458h** [comment]
It seems to me there is no interest - thats why I closed that issue.

But of course - if someone picks it up  that would be great.

Here is the link on the Yunohost forum
https://forum.yunohost.org/t/grocy-erp-beyond-your-fridge/11543

**Comment by hferee** [comment]
> It seems to me there is no interest 
I'm interested, but LDAP (#305) is required first.

**Comment by berrnd** [comment]
LDAP auth should no be doable (see https://github.com/grocy/grocy/issues/207#issuecomment-676565611), so let's add it for the next version... 🙂

**Comment by berrnd** [comment]
LDAP auth support is now done, see https://github.com/grocy/grocy/issues/305#issuecomment-713097864.

**Comment by nr458h** [comment]
Thanks to @ericgaspar there is now a repository - if someone wants to support this little side-project

https://github.com/YunoHost-Apps/grocy_ynh

**Comment by berrnd** [comment]
Thanks! :)

Will add a link on the website, will be tracked in grocy/grocy-website#23
