### ISSUE TITLE
[Feature Request] Support the X-Forwarded-Host header when building the Base URL

### ISSUE THREAD

**Issue by nemec** [grocy/grocy#867]
I see that grocy [reflects back the Host header](https://github.com/grocy/grocy/blob/master/helpers/UrlManager.php#L40) when generating URLs for sub-resources, which is helpful when putting grocy behind a reverse proxy. However, some reverse proxies use a different header to show where the request originated, called [X-Forwarded-Host](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/X-Forwarded-Host). Can grocy be modified to prefer this header in UrlManager, if available, and fall back to using Host otherwise?

**Comment by berrnd** [comment]
Sure, should be possible...

But just setting the full/proper `BASE_URL` is not an option?
https://github.com/grocy/grocy/blob/98f214e9f14d5197f85aaefd38de856bff5da208/config-dist.php#L47-L50

**Comment by tboby** [comment]
Not OP, but can confirm, with a caddy reverse proxy configured as:
```
https://grocy.home:443 {
    reverse_proxy /* grocy:80
    tls internal
}
```
using
`Setting('BASE_URL', 'https://grocy.home/');`
was what I needed.

**Comment by nemec** [comment]
Ah, I didn't realize, thanks! I was looking at a new reverse proxy program and it took me a while to figure out why my configuration (with `Setting('BASE_URL', '/');`) worked in nginx but not in the new one. Turns out nginx set the Host header while the other set X-Forwarded-Host.

**Comment by zaped212** [comment]
Just thought I would leave this here as it is relevant, and might help others.

Here is the reverse proxy configuration that I have settup using nginx
replace ##PUBLIC_HOSTNAME##, and ##INTERNAL_IP_AND_PORT## as appropriate for your settup.
Note this is a HTTPS only configuration.

`server {
        server_name ##PUBLIC_HOSTNAME##;
        location / {
                proxy_pass http://##INTERNAL_IP_AND_PORT##/;
                proxy_redirect default;

                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                proxy_set_header Host $http_host;
                proxy_set_header X-Forwarded-Proto $scheme;
                proxy_redirect off;

                sub_filter_types *;
                sub_filter 'http://##INTERNAL_IP_AND_PORT##' 'https://##PUBLIC_HOSTNAME##';
                sub_filter '##INTERNAL_IP_AND_PORT##' '##PUBLIC_HOSTNAME##';
                sub_filter_once off;
        }
    listen [::]:443 ssl;
    listen 443 ssl;
    include /etc/nginx/options-ssl-nginx.conf; <-- I use a base file to configure my TLS settings.
}
`

**Comment by Uatschitchun** [comment]
Could be closed, couldn't it?

**Comment by Uatschitchun** [comment]
Would be nice if those reverse proxy configurations could be added to https://github.com/grocy/docs to keep and collect them for users to find and use?

**Comment by berrnd** [comment]
Closing this for now, I think setting `BASE_URL` accordingly should be always possible (you could even do it dynamically by reading headers since `config.php` is just a PHP file...).
