### ISSUE TITLE
Cannot connect to the server with Android app

### ISSUE THREAD

**Issue by Gsyltc** [grocy/grocy#868]
Hi, 

I cannot connect to my personnal server (with docker in a swarm cluster).
I get an error message : "An error Occured" while login

Web site is reachable over internet and LAN.
I can connect to my server with a browser

API Key are created and valid.

I currently not running server with a TLS encryption.

Demo server is reachable with the app.
Android version : 10

Thanks

**Comment by Gsyltc** [comment]
Move this issue to grocy-android

**Comment by berrnd** [comment]
I don't know what "grocy-android" should be, probably you mean [PantryParty](https://github.com/PantryParty/pantry_party).

But this is most probably not a bug, so please use the [subreddit](https://www.reddit.com/r/grocy/) for help questions as [stated in README](https://github.com/grocy/grocy#questions--help--bug-reporting--feature-requests), thanks.

> I currently not running server with a TLS encryption.

If you use iOS, that's the problem, as mentioned not only [here](https://www.reddit.com/r/grocy/comments/gdevir/introducing_pantryparty_a_mobile_app_for_your/)...
