### ISSUE TITLE
Sorting by alphabetical order does not consider accented letters

### ISSUE THREAD

**Issue by Kitsunechan** [grocy/grocy#872]
### Issue details
Whether in "Recipes" or in "Stock overview", products with a name whose first letter is an accent are always last in the lists.

### Environment
- grocy version that exhibits the issue: Release grocy 2.7.1
- php version: 7.3.11
- SQLite Version : 3.10.2
- type of hosting (shared or dedicated): dedicated

### Screens
![Screenshot_2020-05-28 Recipes grocy](https://user-images.githubusercontent.com/25407678/83106167-4cbd6d80-a0bc-11ea-95de-7d8eea78051c.png)
![Screenshot_2020-05-28 Stock overview grocy](https://user-images.githubusercontent.com/25407678/83106249-6c549600-a0bc-11ea-9316-b4e856df9f58.png)

**Comment by berrnd** [comment]
Similar to #654.
