### ISSUE TITLE
Can't access grocy; permission denied in app.php

### ISSUE THREAD

**Issue by e-edgren** [grocy/grocy#877]
Hi.

I downloaded [the ZIP file](https://releases.grocy.info/latest), extracted the content to `/var/www/html/grocy`, copied `/config-dist.php` to `/data/config.php`, changed the settings in `/data/config.php` such as `CULTURE`, `CALENDAR_FIRST_DAY_OF_WEEK` and `CURRENCY` to my needs, saved the file and ran `sudo chown -R www-data:www-data /var/www/html/grocy/data/` in the terminal.

After that, I went to `localhost/grocy`. I only see the `Index of /grocy` page and if I click on `app.php`, I get the following warning and error:

```
Warning: require_once(/var/www/html/grocy/vendor/autoload.php): failed to open stream: Permission denied in /var/www/html/grocy/app.php on line 12

Fatal error: require_once(): Failed opening required '/var/www/html/grocy/vendor/autoload.php' (include_path='.:/usr/share/php') in /var/www/html/grocy/app.php on line 12
```

I have so many questions!

- Should I do something more?
- Where's the (needed?) `index.php` file?
- How can I access the website?
- Why do I get permission denied for `autoload.php` and how can I fix this?

**Comment by berrnd** [comment]
I would assume this must be something about your webserver and/or PHP configuration. Normally also a `index.php` file is the default index file, so also that seems to be different in your setup...

But please use the [subreddit](https://www.reddit.com/r/grocy/) for such help questions as [mentioned in README](https://github.com/grocy/grocy#questions--help--bug-reporting--feature-requests), I'm sure there are more other gorcy users which can help better, thanks.
