### ISSUE TITLE
Wrong summation value shown for parent product

### ISSUE THREAD

**Issue by dibyadip-das** [grocy/grocy#878]
I have setup Milk as a parent product and the quantity is set as seen below:

![image](https://user-images.githubusercontent.com/47345141/83395769-840f7f80-a418-11ea-8887-ce6203e413e1.png)
Also, I have set the following **Accumulate sub products min. stock amount** option.

**"Amul Tazza 500ml"** is a product setup as a child product of Milk . Also to mention that this product will be expiring today.
![image](https://user-images.githubusercontent.com/47345141/83395990-db155480-a418-11ea-8105-3e960435e0a7.png)
Since, this milk pack with a capacity of 500ml, I have set the following QU Conversion for this product:
![image](https://user-images.githubusercontent.com/47345141/83396190-3b0bfb00-a419-11ea-89cb-a8c77b83bde5.png)

Till this point there is no issue in the Stock overview for 1 milk pack being in stock, I could see 0.5l in as summation of Milk parent. The issue starts when I add another product **"Amul Taaza Homogenised Milk 1L"** that expires after 5 months from now and I have 4 items in stock. The following are the settings I have kept.
![image](https://user-images.githubusercontent.com/47345141/83396556-cc7b6d00-a419-11ea-84b1-c94bbc485763.png)
![image](https://user-images.githubusercontent.com/47345141/83396591-d7360200-a419-11ea-8ee1-66d7ae180bc0.png)

Now in stock overview, I could see 2.5l of milk will be expiring today whereas it should be 0.5l of milk.
![image](https://user-images.githubusercontent.com/47345141/83396683-fb91de80-a419-11ea-9080-90d64f65d777.png)

PS: I even tried setting the Quantity unit stock "Amul Tazza 500ml" as litre but was having the same result.

**Comment by dibyadip-das** [comment]
I could simulate the same in https://demo.grocy.info/ too:
![image](https://user-images.githubusercontent.com/47345141/83398684-73add380-a41d-11ea-8cb1-20f36dc3e479.png)

**Comment by berrnd** [comment]
"Accumulate sub products min. stock amount" has nothing todo with what get summarized on the stock overview page, it's only about what is considered for the minimum stock amount (as the hint next to the option on the product edit page implies).

Currently the amount gets summarized for parent products and as for all other products, always the most recent best before date is shown on the stock overview page.

If you want to use partial stock amounts, then you also have to enable the product option "Allow partial units in stock" (for the parent product and all child products), otherwise only integral amounts are used/posted during purchase for the product - if that's changed, your example provided on the demo works.

**Comment by dibyadip-das** [comment]
Thanks @berrnd but I am still facing the same problem even after enabling the "**Allow partial units in stock"** for all the 3 products:

I have now added 2 pack of  **Test Product 500 ml**. Thus, it should be **1** litre for 2 packs.
![image](https://user-images.githubusercontent.com/47345141/83432392-6e20af80-a456-11ea-97f1-156398d4b603.png)

On the other hand, I have 2 litre of  **Test Product 1L**. Thus, it should be **2** litre in total.
![image](https://user-images.githubusercontent.com/47345141/83432893-d1aadd00-a456-11ea-99ce-7bd7f69787a2.png)

Still the count in Stock shows **2.5 litre** instead of **3 litre**
![image](https://user-images.githubusercontent.com/47345141/83433062-dec7cc00-a456-11ea-8489-488c33a9c1e9.png)

**Comment by berrnd** [comment]
Ok, seems to be reproducible - so the difference between the two child products is only the different stock QU.

Needs more investigation, here is a snapshot of the current demo database that we not always have to recreate the example:
[grocy.db.zip](https://github.com/grocy/grocy/files/4712572/grocy.db.zip)

**Comment by dibyadip-das** [comment]
Thanks @berrnd for understanding the problem 👍

**Comment by Phyioa** [comment]
Hey there,

I ran into a similar problem with the feature. I did the following

- add product A intended to be used as a parent product, unit in Gram, minimum amount 1000
- add product A.1 with parent product A, unit in Piece, QU conversion 1 Piece = 120 g
- add product A.2 with parent product A, unit in Piece, QU conversion 1 Piece = 110 g
- add product A.3 with parent product A, unit in Piece, QU conversion 1 Piece = 300 g
- add 3 instances of product A.1 -> sum in product A is 360 g = fine
- add 3 instances of product A.2 -> sum in product A is 660 g = **not fine**, should be 690 g
- add 2 instances of product A.3 -> sum in product A is 2,400 g = **totally not fine**, should be 1290 g

I tried to remove all products from above and redo the process, but it keeps happening. Renaming for example product A does not change anything either.

What is happening with the sum calculation here? This seems to be a bug.
Can you reproduce and maybe fix it, please?
