### ISSUE TITLE
[Feature Request] Make adding the product optional or recipe optional

### ISSUE THREAD

**Issue by reslip1** [grocy/grocy#883]
I started trying out grocy and I'm running into some issues in that it takes a long time to add some one of items. I'd prefer to put all items into a single list for all of my shopping. For example, I may need to buy 2 bolts to assemble something or purchase a gift for a friend. It'd like to add these to a shopping list, but it doesn't necessarily go into something. 

The same is true of recipes. I don't know a recipe for everything I cook and sometimes I just want to keep track of meals.. or keep track of that I'm dining out on this day or that.

**Comment by berrnd** [comment]
Sorry, I maybe don't get the problem...

You can add products to shopping lists in many different ways, manually, from the stock overview page, automatically by miniumum stock amounts...

And of course you can also add as many recipes as you want and put everything missing for a whole recipe onto the shopping list with one click or each missing ingredient separately...

General usage questions may fit better on the [subreddit](https://www.reddit.com/r/grocy/) as also [mentioned in README](https://github.com/grocy/grocy#questions--help--bug-reporting--feature-requests), so closing this here for now.
