### ISSUE TITLE
Feature Request: API call to create new Products

### ISSUE THREAD

**Issue by TheFlyrain** [grocy/grocy#885]
It would be nice to add products over the API. I want to use an external program to gather all data for the entry and send it to grocy over API. Am I blind and this is already possible?

**Comment by berrnd** [comment]
It's possible via the ["Generic entity interactions" routes](https://demo.grocy.info/api#/Generic%20entity%20interactions), example:

`POST https://demo.grocy.info/api/objects/products`
```json
{
  "name": "New product xy",
  "description": "asfsfsfsf",
  "location_id": 1,
  "qu_id_purchase": 1,
  "qu_id_stock": 1,
  "qu_factor_purchase_to_stock": 1
}
````

Response:
```json
{
  "created_object_id": "31"
}
````

The UI also uses the API for (mostly) everything, so to find out how it's done IMHO a good way is to just look at that via the browser developer tools...

**Comment by TheFlyrain** [comment]
Oh, sorry. I totally not seen this. Thanks alot!
