### ISSUE TITLE
change to other key for starting a workflow

### ISSUE THREAD

**Issue by wilda17** [grocy/grocy#889]
my barcode scanner either adds a "TAB" or a "ENTER" as suffix to the scanned data.
In Barcodebuddy a "ENTER" is used. In grocy a "TAB" is needed to start the purchase workflow for example. 

Would it be possible to make this adjustable?

**Comment by kses** [comment]
If this would be possible to add it would be awesome! My experience is that cheap no name scanners use new line between scans. I tried the solutions suggested in this thread in custom js file without luck. https://stackoverflow.com/questions/1009808/enter-key-press-behaves-like-a-tab-in-javascript?answertab=votes#tab-top

**Comment by berrnd** [comment]
Is now done in https://github.com/grocy/grocy/commit/5f920e2cc6c612b0df8aae7f494cc82035ce8522, `ENTER` now just behaves the same as `TAB`.

**Comment by kses** [comment]
Great! Thank you! Tried the pre release demo with my scanner. Worked great!
