### ISSUE TITLE
Android App crashes while starting barcode scanner (with v.1.4.0)

### ISSUE THREAD

**Issue by triagony** [grocy/grocy#893]
Yesterday (14.6.2020), when I tested the android app for the first time, everything worked ootb. 

Today, when I start the barcode scanner within the app, the scanner pops up for a sec but finally the whole app crashes (closes) without any hint what's wrong. As I don't know, where the logfile is stored (debug enabled), I don't know either where to get more information what this behaviour is caused by. 

I just saw, that there was an update of the app on June 14th. Perhaps it has anything to do with that update? Reinstall didn't work. 

Am I the only one? 

Thanks in advance,

Triagony.

**Comment by berrnd** [comment]
This is the repository of the main grocy (web) application.

I think you either mean https://github.com/PantryParty/pantry_party or https://github.com/patzly/grocy-android.

Maybe it's better to report that there...
