### ISSUE TITLE
Feature Request: add ability to tag recipes

### ISSUE THREAD

**Issue by jcy79ihc** [grocy/grocy#896]
ability to tag recipes. eg: dinner, pasta, sweet, savory, etc.

**Comment by berrnd** [comment]
It's already possible to add any field: Userfields (see #176).

**Comment by jcy79ihc** [comment]
Thank you for commenting. I have been having a little bit of trouble finding documentation on this software, but I got the user fields figured out. I am enjoying using this to organize my wife's recipes.
