### ISSUE TITLE
"Auto-reload on external changes" doesnt work as expected 

### ISSUE THREAD

**Issue by Dinth** [grocy/grocy#898]
Ive got a large database with several hundreds of products and for past couple of months i've been experiencing serious problems with adding new products to stock - every time i've saved a change, i needed to wait literally a couple of minutes until Grocy becomes responsive again and i could start entering the next product. 
I just found out that disabling "Auto-reload on external changes" actually fixes the issue and i can start adding the next product few seconds after saving the previous one. I understand that Grocy may not know if the change was actually external and does its thing on every change, but in this circumstances maybe "Auto-reload on external changes" option should be renamed to something less confusing?

**Comment by berrnd** [comment]
"Auto-reload on external changes" currently works by just checking the modified time of the database file once every minute.
If that locally saved date is different and if there is unsaved form data and the idle time is > 50 seconds, the page will be reloaded.

Code reference: https://github.com/grocy/grocy/blob/master/public/js/grocy_dbchangedhandling.js

Maybe this has nothing todo with that and is just a problem with loading large tables (which is currently not handled in the best possible way as the whole HTML markup for the whole table is generated server side...)?

**Comment by Dinth** [comment]
How can i troubleshoot it? 
If im opening two tabs with Grocy, adding products in one of them, while the second one is just sitting in the background, with "Auto-reload on external changes" enabled, i can see that every time im saving a change and Grocy freezes for 2 minutes, the other tab also gets reloaded and has a spinning "reload" icon for whole duration of freeze.

**Comment by berrnd** [comment]
If you disable auto reloading, the JavaScript part referenced above does (should do) nothing - so if it's only happening when enabled, strange - have no idea what this could be at the moment...

When it's only when you have a second tab open and that one is currently reloading, maybe that's the thing - depends not only on server power but also webserver/PHP configuration, maybe the (longer running) reload request of the second tab blocks further requests (of the first tab)...

**Comment by Dinth** [comment]
>When it's only when you have a second tab open and that one is currently reloading, maybe that's the thing - depends not only on server power but also on webserver/PHP configuration, maybe the (longer running) reload request of the second tab blocks further requests (of the first tab)...
The thing is that it doesnt only happen when a second tab is open, i just wanted to use a second tab to check if Grocy is accessible in a different session when the first one freezes.

**Comment by berrnd** [comment]
> When it's only when you have a second tab open and that one is currently reloading, maybe that's the thing - depends not only on server power but also on webserver/PHP configuration, maybe the (longer running) reload request of the second tab blocks further requests (of the first tab)...

Have you checked? It maybe depends on how much concurrent requests (PHP child processes) your webserver can handle.

Feel free to reopen this if you have more/specific details available.
