### ISSUE TITLE
Feature Request: Consume child products when parent product is out of stock (not just in recipes)

### ISSUE THREAD

**Issue by ChloeBJohnston** [grocy/grocy#899]
It would be super useful if you could 'consume' a parent product and have that item deducted from quantity of the child product when the parent product quantity is 0.  For example, I have a parent product 'butter' with child products for an Aldi 1 lb box of butter (4 sticks) and another child product for Costco 4 lb package of butter (16 sticks).  If I'm consuming 1 stick of butter (parent product) in a cookie recipe, then the number of sticks of butter in the child product decreases accordingly.  But if I attempt to 'consume' 1 stick of butter (the parent product) outside of the recipe (like I put it on my counter to soften for daily use - not like I'm shoving a stick of butter directly in my mouth) I get the 'This product is not in stock' alert.  

I found [this closed issue](https://github.com/grocy/grocy/issues/446) which seems to address the problem, but I think maybe it was only resolved for products consumed within a recipe and not products consumed in the general 'Consume' function.

Or maybe I'm misunderstanding some parent / child option someplace?

Either way, thanks so much for this amazing project!  I've been having a lot of fun tinkering with our kitchen inventory and imagining workflows to make our cooking lives easier.

**Comment by slyticoon** [comment]
I agree with Chloe. If there was an option to group all child products into the inventory of a parent product, that would be great! Also, the parent product, with its stock at 0, does not show up when I select a storage location, even when its child products exist in that location.

**Comment by zaped212** [comment]
I have to agree.

I am working on setting up my environment so I have a whole bunch of generic products ( soy sauce ) for example that my recipies will consume from, but for shopping I will be making  specific items that then have the generic product as its parent.

It already shows the sum of the child inventory on the products, but being able to consume from it would be nice as well.

for the most part, I dont care if I have 3 cans of 8oz pasta sauce and 1 can of 30oz pasta sauce. my parent just sees 54oz pasta sauce

**Comment by berrnd** [comment]
This is now done - nothing new UI-wise, it just uses any sub product if the parent product is not in stock (consume page and stock overview) while also handling unit conversions (if product specific conversions are used, those need to be defined on the child product).

**Comment by ChloeBJohnston** [comment]
Berrnd, you are a rockstar!
