### ISSUE TITLE
Feature Request: Scroll bar for Navigation section

### ISSUE THREAD

**Issue by akteeter** [grocy/grocy#90]
Can you add a scroll bar to the navigation section when using a non-mobile web browser.
I need to change zoom settings to 75% or update address bar to get to manage master data section.

**Comment by berrnd** [comment]
The scrollbar overlapped all the time, that's why it was removed some time ago...

Although there is no scrollbar, the section should be scrollable by mousewhell/touch-swipe, or not?

**Comment by BlizzWave** [comment]
Its not scrollable on my tablet. I never got around to send in a bug.

**Comment by ateeter** [comment]
On my laptop which has a touch screen it is not scrollable and I'm not able to touch&swipe.

**Comment by berrnd** [comment]
For me https://github.com/berrnd/grocy/commit/366152c049b5e5c3ef407649e3f2d5b6263ae984 did now the trick, if someone wants to verify this on the [pre-release demo](https://demo-prerelease.grocy.info), then this can be closed...

**Comment by BlizzWave** [comment]
Works here

**Comment by berrnd** [comment]
Thanks for testing! :)

**Comment by berrnd** [comment]
Reopened for https://github.com/grocy/grocy/issues/15#issuecomment-440450599

**Comment by berrnd** [comment]
Closed in https://github.com/grocy/grocy/issues/15#issuecomment-440801492.
