### ISSUE TITLE
I would like to request a ko-kr language recommendation.

### ISSUE THREAD

**Issue by kkakkong** [grocy/grocy#903]
I would like to request a ko-kr language recommendation.

thank you

**Comment by berrnd** [comment]
As [noted in README](https://github.com/grocy/grocy#localization), localizations are managed via Transifex - you can add any language there and start translating.

=> https://www.transifex.com/grocy/grocy

**Comment by kkakkong** [comment]
Korean (Korea) (ko_KR) 0 strings to translate 735 strings to review    ready for use

The translation has been completed.
A month has passed and is not being reflected.

**Comment by berrnd** [comment]
Sorry, I normally only check new translations for new releases - but will have a look in the next days and provide a pre-release demo for it.

Thanks for translating grocy! :)

**Comment by kkakkong** [comment]
https://github.com/grocy/grocy/tree/master/localization
https://demo.grocy.info/
Ko-kr does not exist.
Did I miss anything?

**Comment by berrnd** [comment]
As said above, I will have a look and add it to the pre-release demo - nothing happens automatically and nobody else had done it yet...

**Comment by berrnd** [comment]
A pre-release demo for Korean is now available: https://ko.demo-prerelease.grocy.info

Will be of course included in the next release, thanks again for translating grocy! :)
