### ISSUE TITLE
Changing store of an entry does not reflect on the price history

### ISSUE THREAD

**Issue by Alwaysin** [grocy/grocy#913]
What I did:

- added a purchase without a store, because I didn't create it before
- created the store
- edited the purchase to reflect the store I bought it from

Then, on the details, the price history is still showing "unknown store".
Is is the same when you choose a specific store and change it later: it will display the first store that had been assigned and not update at all.

**Comment by berrnd** [comment]
Technically because the price history is based on entries in the `stock_log` table and the /stockentries page only edits rows of the `stock` table - so we should of course also update the corresponding log entries on editing...
