### ISSUE TITLE
No brand field on a product

### ISSUE THREAD

**Issue by Alwaysin** [grocy/grocy#914]
Is it normal that I can't find a brand field on a product?
I'm adding it in parentheses at the end but I think this is not optimal :/

If you have tips on how you manage the brands, for example if you buy the same product from different brands, tell me please!

**Comment by Melvidor** [comment]
I didnt get your Question for first time as I am using grocy for kitchen stuff (for now). But in my bathroom I have several shampoos with different brands... so I would composite it to Product name "SHAMPOO L'Oreal" "Shampoo H&D"

+1 for Brand field

**Comment by berrnd** [comment]
You can add any field by using Userfields, see #176.

Parent/child products is also used by others for this (generic "Shampoo" product as parent, child product for each brand).

I personally don't have brand specific products because I try to keep it simple where I don't need the details...

**Comment by Melvidor** [comment]
Berrnd: thanks, maybe its time for wiki.grocy. :-)
