### ISSUE TITLE
Wrong conversions (g to kg)

### ISSUE THREAD

**Issue by drewowen** [grocy/grocy#915]
I have a conversion set on the unit "g" stating that 1g=0.001kg. However, when I try to use the conversion in a recipe to convert from g to kg, it lists the kg quantity as 1 000 000 times smaller than I input it. I change the unit to kg and input the value 1, it shows the statement below the quantity input field "this is equal 1000g in stock" accurately, but once I press save, the number reverts to 0.001kg (due to rounding). When I input 100000kg, it displays 0.1kg.

**Comment by berrnd** [comment]
Related to #794, most probably also already fixed once #876 will be merged.
