### ISSUE TITLE
Umlauts in equipment pdf filename

### ISSUE THREAD

**Issue by Kurisutian** [grocy/grocy#916]
Hi,

I just added some data to grocy and found the following: When entering equipment and adding the pdf manual to it, grocy does not allow any Umlauts in the pdf filename. The site will become empty and reloading it results in starting over to enter something as it empties all fields. Tested with 'ä', 'ö' and 'ü' in the filenames... perhaps it will also do that with 'ß' or other non latin letters. I think it should accept all utf8 symbols as it seems to rename the file different internally anyway.

**Comment by berrnd** [comment]
Hm, cannot reproduce this ... just added a file named "täst.pdf" to the equipment "täst" on the (English) release demo without problems: https://en.demo.grocy.info/equipment

Maybe you can check the browser console what is going on exactly.

**Comment by berrnd** [comment]
Just to add: The file names are Base64 encoded when using the API to save/get them, so special characters shouldn't be a problem...

https://github.com/grocy/grocy/blob/98f214e9f14d5197f85aaefd38de856bff5da208/public/viewjs/equipment.js#L35

https://github.com/grocy/grocy/blob/98f214e9f14d5197f85aaefd38de856bff5da208/controllers/FilesApiController.php#L42-L49

https://github.com/grocy/grocy/blob/573b6ece895735ab1a5ba58bc367252f255bd9d7/helpers/extensions.php#L211-L219

**Comment by Kurisutian** [comment]
Checked it with a file called "Geräteübersicht.pdf" and still doesn't work: Error code: RESULT_CODE_KILLED_BAD_MESSAGE
It does not show anything in the console as it kills the tab pretty much before that.

**Comment by berrnd** [comment]
Ok, seems to be a browser error.
Do you use any Add Ons which maybe filter some things?

Also tried it with the latest Firefox and Chrome and a file named "Geräteübersicht.pdf" without issues...

Unrelated to Chrome and Firefox, but I found this: brave/brave-browser#9878

**Comment by Kurisutian** [comment]
Seems to be exactly what causes it. I checked with 2 browsers on Linux (Chromium and Falkon), both show the same issue, but checked with Firefox now after you mentioned that and it works in there. Thanks for the update on this and letting me know it works on the Grocy end. I'll close this issue as it's not a Grocy one. Sorry about that.

**Comment by berrnd** [comment]
Absolutely no problem! :)
