### ISSUE TITLE
AI vision

### ISSUE THREAD

**Issue by 5kull** [grocy/grocy#917]
It would be cool to use the [ML kit](https://developers.google.com/ml-kit/vision/object-detection) somehow, to recognize vegetables, fruits and other stuff and their quantity.

**Comment by Uatschitchun** [comment]
Who's not able to tell a cucumber from a banana?

**Comment by Uatschitchun** [comment]
Maybe https://github.com/Forceu/barcodebuddy is a good place to integrate something like this as it queries OpenFoodFacts, etc. already?

**Comment by berrnd** [comment]
This is more something for native companion apps or other external add-ons.
