### ISSUE TITLE
Feature Request : Add decimal in meal plan servings 

### ISSUE THREAD

**Issue by Desaydrone** [grocy/grocy#918]
Can we imagine having this feature?

To explain this feature, I'm on a ketosis diet, so I have to calculate, not by serving but by gram, so to simplify the use of grocy. I enter one serving in the recipe and when I add this recipe to the meal plan I would like to be able to multiply by a decimal number so that the resulting basket will be good.

Hope i'm clear enough

**Comment by berrnd** [comment]
Decimal handling for number inputs in general has been completely reworked. So that's now possible.
