### ISSUE TITLE
Reverse Proxy + Cloudflare

### ISSUE THREAD

**Issue by Dinth** [grocy/grocy#926]
I had Grocy running behind reverse proxy for a while and without a problem. Recently i have enabled Cloudflare DDOS protecting on that subdomain and suddenly grocy stopped working - Im getting "Too many redirections" errors when i try to open it.

**Comment by berrnd** [comment]
I would say this has nothing to do with grocy itself and is more a general webserver problem or something.

Please use the [subreddit](https://www.reddit.com/r/grocy/) for such questions as [mentioned in README](https://github.com/grocy/grocy#questions--help--bug-reporting--feature-requests), thanks.
