### ISSUE TITLE
Chore rotation alphabetic not looping

### ISSUE THREAD

**Issue by jlo88** [grocy/grocy#930]
I notice that with some chores I make that the alphabetic rotation does not work. For example with this one: 

![image](https://user-images.githubusercontent.com/10574850/88485685-fe233700-cf77-11ea-95b0-1f527ed2a167.png)

I try to rotate the chore by pressing the exectud buttong. When a chore reached Mirjam, I cannot get it back to Jan. I tried accessing grocy from both accounts..

**Comment by berrnd** [comment]
Can reproduce this on the current demo, so seems to be broken currently somewhere.

Code ref:
https://github.com/grocy/grocy/blob/98f214e9f14d5197f85aaefd38de856bff5da208/services/ChoresService.php#L166-L193
