### ISSUE TITLE
Decimal places in Recips not needed? (UI bug for big numbers)

### ISSUE THREAD

**Issue by pawido** [grocy/grocy#932]
Hi Community,

as i see in most cases, that amount of calories in recips is mostly broken because of the zwo decimal places, it's worth a second to think over, they're needed or not. A 10th of an calories is burned in a second, so i think it makes no sense, to show decimal places and also the gui is not broken. It happen on Desktop and on mobile, too. Scaling the web-browser view down helps, but than fonts are smaller, too - making it difficult to read..
![calories_decimal](https://user-images.githubusercontent.com/68723143/88512994-bfc56080-cfe7-11ea-886f-9dc34b33646a.jpg)

**Comment by berrnd** [comment]
Using decimal places or not is a controversy topic, however, if that get's changed, I guess there will be immediately a request to change that back again...

Of course the UI could be improved to not a new line if the number is too big.

**Comment by berrnd** [comment]
This already fits better by the new general UI updates introduced in #795.

**Comment by winterscar** [comment]
I too would appreciate some way of limiting the precision of the calories value
<img width="450" alt="image" src="https://user-images.githubusercontent.com/11340175/156020966-3d81f7ce-6d7d-4fd6-8941-849b453e5043.png">
Anything less than a single calorie is meaningless (to me).

**Comment by berrnd** [comment]
> I too would appreciate some way of limiting the precision of the calories value
> <img width="450" alt="image" src="https://user-images.githubusercontent.com/11340175/156020966-3d81f7ce-6d7d-4fd6-8941-849b453e5043.png">
> Anything less than a single calorie is meaningless (to me). 

That's off-topic here, since this was about the UI part / how big/wide numbers are on the recipe page only.

Also mentioning unrelated things in an 1.5 year old request is untrackable, so moved to #1802.
