### ISSUE TITLE
Kubernetes Resources

### ISSUE THREAD

**Issue by johnhamelink** [grocy/grocy#935]
Hi there,

I've implemented Grocy on my kubernetes cluster, I thought I'd share: https://git.sr.ht/~johnhamelink/k8s-grocy

Thanks :smile:

**Comment by berrnd** [comment]
Cool. :)

Maybe useful for some others, so maybe share it on the [subreddit](https://www.reddit.com/r/grocy/), I think that's the place where more grocy would see it.
And I created grocy/grocy-website#16 to track to add that to grocy.info as well.
