### ISSUE TITLE
Some Ingredient/Product Names Disappearing from Recipes

### ISSUE THREAD

**Issue by Wordna1** [grocy/grocy#937]
I haven't identified a pattern yet, but occasionally a recipe that was previously correct suddenly has one or more ingredients listed with only a measurement (ie. No ingredient/product name)

**Comment by berrnd** [comment]
Maybe when you delete the product?
(Ref #565)

**Comment by berrnd** [comment]
#565 is now done, so deleted products should not be a problem again.
