### ISSUE TITLE
Parent product accumulation wrong when QU conversion is involved part 2

### ISSUE THREAD

**Issue by chrishas35** [grocy/grocy#938]
Related to #615, I found what I believe is a bug in the SQL view that is causing a single child QU factor to be applied to all stock rows instead of each row's respective QU factor being applied and then summing.

I found this line to be problematic:
https://github.com/grocy/grocy/blob/152d3b70058db94716f7f326eba5b4ff3a1b2af4/migrations/0100.sql#L7

changing to:
```sql
SUM(s.amount * IFNULL(qucr.factor, 1)) AS amount_aggregated, 
```
causes each stock row to be multiplied by the QU factor and then summing the products.

I'm new to grocy, but this does seem to solve my issue which I detailed out on reddit. https://www.reddit.com/r/grocy/comments/i1fxsd/how_to_properly_setting_up_child_products_with/

**Comment by chrishas35** [comment]
Quickly looking at the amount_opened_aggregated calculation, it too likely needs a correction, but I haven't played with that enough yet to get a proper test case built out.

**Comment by berrnd** [comment]
Haven't tried to reproduce this yet, but I think you're right - the multiplication has to be inside the summarization to take the factor per row/product - thanks for finding that! :)

**Comment by berrnd** [comment]
This was fixed in https://github.com/grocy/grocy/commit/4db373b27291091f603284356f45351486cfcf66 (references #878)
