### ISSUE TITLE
Inconsistent computation of $BasePath in Grocy\Helpers\UrlManager

### ISSUE THREAD

**Issue by fgrsnau** [grocy/grocy#944]
I observed that the value of `Grocy.BaseUrl` is different when Grocy is running in the web root or in a subdirectory.

This is leads to a wrong computation of the `&returnto=` value in the product card edit buttion and hence later to an invalid redirect when Grocy runs in a subdirectory.

**Grocy in web root:**
```
[config.php] Setting('BASE_PATH', '');
[config.php] Setting('BASE_URL', '/');
[JS] Grocy.BaseUrl === 'https://grocy.example'
```

**Grocy in subdirectory:**
```
[config.php] Setting('BASE_PATH', '/subdir');
[config.php] Setting('BASE_URL', '/subdir/');
[JS] Grocy.BaseUrl === '/subdir'
```

**Problem caused:**
This is problematic because `Grocy.CurrentRelativeUrl` is computed like [this](https://github.com/grocy/grocy/blob/f6852e82b278d4fd8836346c2603f2852f760540/views/layout/default.blade.php#L53): `Grocy.CurrentUrlRelative = "/" + window.location.href.split('?')[0].replace(Grocy.BaseUrl, "");`

The `.replace` obviously only works if the base url starts with `https://` and the full hostname due to the usage of `window.location.href`.

If you run grocy in a subdirectory you get redirect urls like `https://grocy.example/subdir/product/14?returnto=/http://grocy.examplepurchase` which obviously breaks.

**The root cause:**
The `U` function uses [`constructUrl`](https://github.com/grocy/grocy/blob/f6852e82b278d4fd8836346c2603f2852f760540/helpers/UrlManager.php#L21) of the `UrlManager`. However the `$BasePath` is only set to the full `https://hostname` URL if the `BASE_PATH` constant is set to '/'. In any other case it is set to something that the frontend is unable to handle correctly.

I do not now why the special handling was introduced. I replaced the constructor by a simple `$this->BasePath = $this->GetBaseUrl() . $basePath;` and it works for all cases (grocy in web root and in subdirectory). I did not find any other downstream users of the `UrlManager`, so I think the change does not break other behaviour.

**Comment by berrnd** [comment]
Thanks for finding and immediately fixing that! :)

> I do not now why the special handling was introduced.

I also can't remember, a lot URL handling related things changed when we [upgraded Slim Framework to v4](https://github.com/grocy/grocy/issues/561), maybe that was necessary before, however...

**Comment by berrnd** [comment]
I had another test on this (after merging your pull request, sorry for the confusion :D) - and found out why it was done like this:

`BASE_URL` should be a full URL or just `/`, according to the comment in `config-dist.php`:
https://github.com/grocy/grocy/blob/68dcd02d00c406e8597910ba00a988b45c8182dd/config-dist.php#L47_L50

It does not work with your example `/subdir/`, but that's ok according on how it's defined and documented in the config file comment - so I think we should not change to not break this...
