### ISSUE TITLE
Grocy slowdown on Hassio vm

### ISSUE THREAD

**Issue by Vader266** [grocy/grocy#946]
Grocy, while initially very nippy, has ground to almost a halt, rendering it near-unusable.

When accessing the Meal Plan or Recipes, Grocy hangs for up 30 seconds to load the page. This hang is duplicated if I open a new recipe.

I'm not entirely sure how to reproduce this, but it has developed over time. Hopping around the other tabs (Stock overview, Chore etc) is initially slow as well but speeds up on later access.

Could this be an issue of increasing archive access time for the records and/or the images we have on-file? The meal plan in particular is heavily used so it could be an inefficient storage structure. Has anyone else experienced similar issues?

**Comment by highaltidude** [comment]
I had performance issues running this under Hassio. I ended up just spinning up a webserver to run it. I'd post on the add-on git page to see if Frenck can help. 

https://github.com/hassio-addons/addon-grocy

**Comment by Vader266** [comment]
I actually got referred here by Frenck! Interesting that you had trouble with Hassio too. Is there a trivial way of transferring to a webserver if I wanted to go that route?

**Comment by berrnd** [comment]
#695 is about performance enhancements for recipes / meal plan.
There is room for improvement, currently all ever planned meals are for example loaded on accessing the meal plan page.

If it's more slower when using the Home Assistant integration than on a "normal" webserver, it would be interesting what the differences are (have personally no experience with HA).

So let's close this and continue in #695 for the general performance improvements.
