### ISSUE TITLE
Include vendor folder in the source code

### ISSUE THREAD

**Issue by tetragir** [grocy/grocy#950]
Hello,
I'm porting grocy to FreeBSD and not including the vendor folder in the source code currently blocks it. Other projects, like kanboard do include the vendor folder. Would it be possible to also include it for grocy?
Thank you!

**Comment by berrnd** [comment]
If you mean to include managed dependencies (Composer for PHP dependencies, the mentioned `vendor` folder and Yarn for frontend dependencies, the `public/node_modules` folder) - of course not, because why we should version control them?

You can pull the dependencies yourself or just use the release ZIP where everything is included as mentioned in README.

**Comment by tetragir** [comment]
Hallo Bernd,
thank you for the reply. I'm still not absolutely sure how porting php applications work, so far I've looked at a couple and it seems that they sometimes include the external modules in the vendor folders in GitHub (like kanboard, webtrees, bareos-webgui).
If it's not feasible/possible/makes sense, I will try to find another way to build it (or download the pre-built file even).

**Comment by berrnd** [comment]
It makes no sense to include them, nobody says that checking out a (GitHub) repository provides a fully working application - a fully working application is what releases are for.

If you want to use the repo directly, also make sure to use the `release` branch, which always points to the latest released version.

And beside of having the tools installed (Composer & Yarn) it's nothing more than `yarn install` and `composer install`, if downloading the release ZIP is too difficult ;D...

And I personally don't use FreeBSD anywhere, but I think there are also webservers like nginx and of course PHP, so setting grocy up can't really be much different than on other unix OS (someone wrote about FreeNas FreeBSD [here](https://github.com/grocy/grocy/issues/715#issue-597535439), linked [there](https://grocy.info/links))...
