### ISSUE TITLE
multi tenant?

### ISSUE THREAD

**Issue by fredhampton** [grocy/grocy#951]
Is it possible to have a multi tenant option for grocy ?
A single instance of  grocy with multiple users having their own grocy ?

Thanks

**Comment by berrnd** [comment]
Currently you would need to have multiple directories.

But that was already added by @fgrsnau in #939 (not yet merged, but will be of course included in the next release).

**Comment by fredhampton** [comment]
@berrnd Thanks so much !!!!   Is there a date range for the next release ?

**Comment by berrnd** [comment]
No, but see: https://www.reddit.com/r/grocy/comments/hxeg31/when_can_we_expect_an_update/fz6apyt/
