### ISSUE TITLE
Add Greek translation

### ISSUE THREAD

**Issue by apo-mak** [grocy/grocy#952]
Hi i can see from other issues here that you manually pull and update the translations from transifex.
I thought  that this was automated because of this message:

> The pre-release demo is available for any translation which is at least 80 % complete and will pull the translations from Transifex 10 minutes past every hour, so you can have a kind of instant preview of your contributed translations. Thank you!

I just finish the Greek translation and i will really love to be included in the next release but it will be helpful to first see where each text is shown  in the app :P .
Can you pull it so it can work here ? https://demo-prerelease.grocy.info/stockoverview  ( and i will update any problem i see in the next 3 days)

BTW : i also made a request on transifex for Greek on the "grocy-desktop" because i do not see it as an option to translate.

**Comment by berrnd** [comment]
Thanks for translating grocy! :)

Adding new languages is not automated, of course I at least check them before releasing a new version, and normally also faster, but currently [my work on grocy is a bit paused](https://www.reddit.com/r/grocy/comments/hxeg31/when_can_we_expect_an_update/fz6apyt/) - so let's leave this open, I will close it once the greek translation was added.

**Comment by berrnd** [comment]
A pre-release demo for Greek is now available: https://el.demo-prerelease.grocy.info

Will be of course included in the next release, thanks again for translating grocy! :)
