### ISSUE TITLE
Product Consumption Classification Record

### ISSUE THREAD

**Issue by kkakkong** [grocy/grocy#953]
There are two functions of product consumption in stock. 

consumption of spoiled  products and normal products

However, both are marked "consume" in Stock Journal and cannot be distinguished.

![2020-08-18 (2)](https://user-images.githubusercontent.com/62811794/90433892-8922c780-e107-11ea-963d-4950d6fe2f59.png)

**Comment by berrnd** [comment]
If spoiled or not is already tracked in the database, so it's just about that information is missing on the stock journal page.

**Comment by kkakkong** [comment]
I request you to check the function.  
Both the stable and preview versions of the demo site are the same symptoms.
Like you said.
Database records may be wrong when consuming unhealthy products.
Or it could be misstatement in the the stock journal page.

**Comment by berrnd** [comment]
I meant the information is already tracked, we need to add that it's also shown on the stock journal page, which is currently not there, in any version - that's why I left this open...
