### ISSUE TITLE
API does not return period_interval for chores

### ISSUE THREAD

**Issue by michaelblight** [grocy/grocy#955]
If you set up a chore that repeats every, say, 3 weeks using the period interval, it would be good if this value was returned by `/objects/chores`.

You can get the period interval from `/objects/chores/{objectId}`, but it means you have to iterate all to get a tabular result showing "every 3 weeks" etc.

**Comment by berrnd** [comment]
Cannot reproduce this, see the demo chore with id `6` for example, `period_interval` (`1` in that example) is included in both, the complete chores list (https://demo.grocy.info/api/objects/chores) and in the in the single object endpoint (https://demo.grocy.info/api/objects/chores/6)... (?)

**Comment by michaelblight** [comment]
My bad - sorry. It was me filtering out the property further down in the processing. Closed.

**Comment by berrnd** [comment]
Ok, no problem. :)
