### ISSUE TITLE
Filter/sort/split shopping list by default store

### ISSUE THREAD

**Issue by bramvrensen** [grocy/grocy#957]
I usually have a favorite store where I get most of my groceries (default store), when a product is not available or is not a part of the default stores' assortment I will go to another store. I always sort my shopping list (currently in google keep) based on the store, therefor it would be really helpful if I could sort, or even better split the shopping list per store (as setup in the default store).

Thanks for the awesome work! I have grocy integrated in Home Assistant and I am slowly getting to convince my wife to start using it!

**Comment by max0x0** [comment]
Thanks for your work !
I need this feature too !

**Comment by berrnd** [comment]
The products Default store is now available as new (hidden by default) column on the shopping list.

You can also group by that column, so hope that helps for this.

See the new table options - https://github.com/grocy/grocy/pull/1189#issuecomment-746611318.
