### ISSUE TITLE
Manual pages should not autorefresh.

### ISSUE THREAD

**Issue by shadow7412** [grocy/grocy#958]
When viewing a manual on the equipment page (sometimes quite large ones), the page will occasionally refresh.

This has two undesired effects;
1. Losing my page
2. Selecting the first item in the list (as opposed to the one I have open).

When viewing the equipment page (particularly when the PDF is open) can we look into either suppressing the auto-refresh option, or updating the page in such a way that doesn't reload the PDF viewer?

**Comment by berrnd** [comment]
When "Auto reload on external changes" is on, the page reloads when idling for 50 seconds and when there is a change, currently maybe also to often, see #898.

I think it's ok that we disable this on the equipment page.

**Comment by berrnd** [comment]
This is now added, another note:

The page also does not automatically reload when you use the "fullscreen button" to expand the manual PDF or notes section (also works the same on the recipes page).

![grafik](https://user-images.githubusercontent.com/2161815/96014747-05573400-0e47-11eb-9d13-08cc97a7ec98.png)

**Comment by berrnd** [comment]
I've reverted that change because that's unecessary.

We already have the general handling that when a "fullscreen card" is displayed, the page will never get automatically reloaded. So please just use that.
