### ISSUE TITLE
Multi-Bar Code comments Suggestions

### ISSUE THREAD

**Issue by kkakkong** [grocy/grocy#962]
product -> Barcodes 

If multiple bar codes are registered, additional comments are suggested to distinguish them.

**Comment by berrnd** [comment]
How barcodes are entered has changed since the last release, see the pre-release demo: https://demo-prerelease.grocy.info/product/10

So you want to have a comment field in the new "Add Barcode"-dialog?

**Comment by kkakkong** [comment]
yes.
We need an comments filed that can recognize the barcode normally and check if it is the product you want.
It is not known even if it is incorrectly recognized as another product registered above the surface of the barcode.
Thank you for the improvement.

**Comment by Festeazy** [comment]
It would also be so cool if there was a drop down with all the barcodes/specific_product_name to pic from
