### ISSUE TITLE
Disabling stock turns off products

### ISSUE THREAD

**Issue by isabellaalstrom** [grocy/grocy#966]
I understand this is by default, but I don't use the stock to keep track of my stock at all, but I do use products together with recipes, meal plan and shopping list. What I would like is for the products sections of "Manage master data" to be visible even if I don't have Stock enabled. I also would like to disregard stock at all when I use the meal plan and shopping list, since I don't use it.

**Comment by berrnd** [comment]
That should now work like you expected it. 🙂

Changelog excerpt:
> - Optimized what's hidden when `GROCY_FEATURE_FLAG_STOCK` is disabled
>   - Products, quantity units and product groups are possible to use now
>   - Means you can use for example the shopping list, recipes and the meal plan with products while the "stock handling part" is hidden
