### ISSUE TITLE
Uncertainty regarding some localization strings

### ISSUE THREAD

**Issue by yarons** [grocy/grocy#980]
https://github.com/grocy/grocy/blob/d4c5da21731396ab70866600b2c6e9b9496cf7ce/services/DemoDataGeneratorService.php#L172

https://github.com/grocy/grocy/blob/d4c5da21731396ab70866600b2c6e9b9496cf7ce/services/UserfieldsService.php#L27

I really don't understand why do these strings appear as translatable and why there are no instructions how to translate them?
If I understand correctly these are database columns, I don't think it's a good idea to translate these, what happens if I switch langauges? The database will fail?

There are also ISO 639-1 locales for translation, I don't think it should be translated at all, it can cause a major headache when switching a language (And Hebrew does not appear on that list).

**Comment by berrnd** [comment]
I already answered on Transifex.

Userfield types are the names in the dropdown on the Userfields page, not database columns: https://demo.grocy.info/userfield/new

Locales have notes attached to each string, example: cz = Czech, so translate Czech.

> why there are no instructions how to translate them?

Feel free to add those instructions, all contributions are welcome, thanks for translating grocy! :)

**Comment by yarons** [comment]
OK, so is it accep

> Userfield types are the names in the dropdown on the Userfields page, not database columns: https://demo.grocy.info/userfield/new

I see, so is it fine to just translate these to simple names without the underscores?

Thanks for the locale comments, I've completed their translation to Hebrew already.

**Comment by berrnd** [comment]
> I see, so is it fine to just translate these to simple names without the underscores?

Just like it's done for English...

**Comment by yarons** [comment]
Hmmmm that doesn't look right, the text is replaced with the ID in Transifex so I can see the small letters with underscore altough I should actually see the English strings, this is where the confusion is comming from.
