### ISSUE TITLE
API to get recipe details including ingredients

### ISSUE THREAD

**Issue by nervetattoo** [grocy/grocy#983]
Thanks for building Grocy. I'm in the process of working on meal plan integrations with Home Assistant and have been unable to find a way to fetch recipe details over the API.
Is there a reason why this is omitted or just that no one built it yet?
I expected to be able to get the ingredient list in order to display it elsewhere. As its more complex than the current recipe endpoint I guess a `/api/recipes/1/ingredients` would be a safe way to add it?

**Comment by berrnd** [comment]
See the ["Generic entity interactions" endpoints](https://demo.grocy.info/api#/Generic%20entity%20interactions) to get any "base objects".

To get all recipe ingredients use [`GET /objects/recipes_pos`](https://demo.grocy.info/api/objects/recipes_pos), you manually have them to match them to recipes by `recipe_id` (get all recipes by [`GET /objects/recipes`](https://demo.grocy.info/api/objects/recipes).

Once #577 is done, the filtering will be directly possible.
