### ISSUE TITLE
Stock entries page: Tare weight handling products: Consume button consumes wrong amount

### ISSUE THREAD

**Issue by klausmcm** [grocy/grocy#988]
**Observed Behavior**

In the below screenshot, I clicked on the button **Mark this stock entry as open** for the entry from **Kroger**. The amount is **1000 g**.

![image](https://user-images.githubusercontent.com/14914359/92075061-7d244000-ed6c-11ea-8957-4049b38b9add.png)

After clicking the button, the amount is set to **1 g**.

![image](https://user-images.githubusercontent.com/14914359/92075156-b52b8300-ed6c-11ea-8654-7fa81d5e966c.png)

**Expected Behavior**

Amount should stay at **1000 g**.

Tried on **pre-release-836bcc8** (https://demo-prerelease.grocy.info/).

**Comment by berrnd** [comment]
Because of that product has "Enable tare weight handling" set, so seems to be a problem with such products...

**Comment by klausmcm** [comment]
I unchecked the *Enable tare weight handling* for the same flour product and went through the same steps again for the other remaining entry. The amount is still set to **1 g** after pressing the button.

![image](https://user-images.githubusercontent.com/14914359/92082246-1fe2bb80-ed79-11ea-9554-5c297d29a5c3.png)

**Comment by berrnd** [comment]
Sorry, I missed that it's about the **open button**, not the consume button...

So consume with tare weight handling does not work, as mentioned above.

Opening works, it's just not displayed immediately:
It opens also 1 g for that example, so the 1000 g entry get split - visible after you reload the page (and makes absolutely no sense for the example of flour, but works so far...).

**Comment by klausmcm** [comment]
You're right. I didn't refresh the page. I think this makes sense when the amount is *1 container*. Opening a product where the amount is a multiple of something (ex. 1 g) has the side effect that the opened 1 g is shown to have the same price as the remaining 999 g.
