### ISSUE TITLE
Use date of manufacturing instead of date of purchase to calculate expiry/best before dates.

### ISSUE THREAD

**Issue by RoguedBear** [grocy/grocy#992]
As from what I've used this app, when adding new products to inventory (purchasing products), the best before or the expiry date is calculated based on the date of purchase. 
For non-packaged food that makes sense, but If there could be a way which asks for the product's date of manufacturing and then calculate the expiry date based on the default expiry days value set in the product's master data, instead of the date of purchasing/adding the product to the inventory.

(PS: if some of my wordings seem like _that stuff_ does not belong to Grocy webapp, that's because I mainly use the grocy android app while filling out inventory and adding products.)

**Comment by berrnd** [comment]
Just out of interest: Which are practical examples of products where there is no expiration / best before date mentioned, but a manufacturing/production date?

**Comment by RoguedBear** [comment]
I looked at my issue description, and this issue is obsolete now since due date feature is already there.
I believe the issue was meant to be opened on the grocy-android app's repository but I may have mistaken for the feature not being here.

I will close the issue, and my apologies for any inconveniences caused.

---
> Just out of interest: Which are practical examples of products where there is no expiration / best before date mentioned, but a manufacturing/production date?

All products do have expiry / best before date mentioned along with manufacturing date printed,  I have encountered a few products where they simply state the manufacturing date in print but state the best before in the packaging as "best before `X` months/days from the date of manufacturing" and leave it up to the consumer to figure out the exact date.
I don't remember the exact products that do this but remember being annoyed at this mild inconvenience many times

**Comment by Z-ack-L** [comment]
@berrnd Almost all products in China are labeled with production date and shelf life, no expiration date. grocy's default date method turns grocy into an oral math training app in China...
It would be nice to add an option to enter the production instead date expiration date when entering the product.

PS: Not sure if I should open a new issue in grocy project or grocy-android(and IOS) project.

> Just out of interest: Which are practical examples of products where there is no expiration / best before date mentioned, but a manufacturing/production date?

**Comment by berrnd** [comment]
> Almost all products in China are labeled with production date and shelf life, no expiration date

Then this part of Grocy doesn't fit for China and that's ok, in any case nothing will be changed for that.
