### ISSUE TITLE
"Secret" query param does not work but "GROCY-API-KEY" does

### ISSUE THREAD

**Issue by moverperfect** [grocy/grocy#993]
When you click on the integrate button from the calendar it gives you a ical link with the "secret" query param. When I tried using this in incognito mode (so that I had no cookies) it gives a 401. But when I switch the query param name to "GROCY-API-KEY" it works. I think this might have originated from the auth reshuffle at d60d981fd12ceffdc91a469e6f37586590ede61c

**Comment by berrnd** [comment]
Thanks for testing! :)
