### ISSUE TITLE
users_dto does not concat display_name properly

### ISSUE THREAD

**Issue by moverperfect** [grocy/grocy#994]
**Steps to reproduce on the pre release server:**
1. Change the First name and last name of demo user 4 to "Test"
2. Manage Master data
3. Edit any chore
4. Assign to
5. See that Demo User 4 shows as "0" instead of "Test Test"

**Cause of the error**
The Users_dto view does not concat correctly, "||" should be used instead of "+" see the following sqlfiddle http://sqlfiddle.com/#!5/60b4de/1

**Recommended Change 1:**
`CREATE VIEW users_dto AS SELECT id, username, first_name, last_name, row_created_timestamp, (CASE WHEN IFNULL(first_name, '') = '' AND IFNULL(last_name, '') != '' THEN last_name WHEN IFNULL(last_name, '') = '' AND IFNULL(first_name, '') != '' THEN first_name WHEN IFNULL(last_name, '') != '' AND IFNULL(first_name, '') != '' THEN first_name + ' ' + last_name ELSE username END ) AS display_name FROM users`
to
`CREATE VIEW users_dto AS SELECT id, username, first_name, last_name, row_created_timestamp, (CASE WHEN IFNULL(first_name, '') = '' AND IFNULL(last_name, '') != '' THEN last_name WHEN IFNULL(last_name, '') = '' AND IFNULL(first_name, '') != '' THEN first_name WHEN IFNULL(last_name, '') != '' AND IFNULL(first_name, '') != '' THEN first_name || ' ' || last_name ELSE username END ) AS display_name FROM users`

**Recommended Change 2:**
Change the DemoDataGeneratorService.php so that the users test different scenarios
Set Demo User 2 first name
Set Demo User 3 last name
Set Demo User 4 first name and last name

**Comment by berrnd** [comment]
Thanks, I just added this in https://github.com/grocy/grocy/commit/3f1135713aef53eaca5897643c757f661bb413e5.
