### ISSUE TITLE
XSS and HTML Injection on Create Shopping List & shopping list item notes (Rendered upon deleting it)

### ISSUE THREAD

**Issue by mufaddalmasala** [grocy/grocy#996]
_**Edit by @berrnd:**_

**Just to note that here:**
**I don't consider this critical for grocy, this cannot be done unauthenticated, grocy is not an application you (should) host publicly (means without authentication) on the internet.**

-----------------

**Vulnerability Name:** Stored Cross Site Scripting & HTML Injection

**Vulnerability Description:**  grocy household management solution v2.7.1, allows stored XSS and HTML Injection, via Create Shopping List module, that is rendered upon deletiing that Shopping List. 
Cross Site Scripting (also referred to as XSS) is a vulnerability that allows an attacker to send malicious code (usually in the form of Javascript) to the web application. Because a browser cannot know if the script should be trusted or not, it will execute the script in the user context allowing the attacker to access any cookies or session tokens retained by the browser.
HTML injection occurs when a user is able to control an input point and is able to inject arbitrary HTML code into a vulnerable web page. Consequences can be disclosure of a user's session cookies that could be used to impersonate the victim, or, more generally, it can allow the attacker to modify the page content seen by the victims.

**Vulnerable URL:** http://127.0.0.1/shoppinglist/new

**Payload:** 
```
1. <marquee onstart=alert(document.cookie)> 
2. <h1>HTML Injection</h1>
```

**Steps to Reproduce:**
1. Login to the application
2. Go to 'Shooping List' module
3. Click on 'New Shopping List' module
4. Enter the payload: <marquee onstart=alert(document.cookie)> in 'Name' input field.
5. Click Save
6. Click 'Delete Shopping List'

**Request:**
POST /api/objects/shopping_lists HTTP/1.1
Host: 127.0.0.1
User-Agent: Mozilla/5.0 (X11; Linux x86_64; rv:68.0) Gecko/20100101 Firefox/68.0
Accept: */*
Accept-Language: en-US,en;q=0.5
Accept-Encoding: gzip, deflate
Referer: http://127.0.0.1/shoppinglist/new
Content-type: application/json
Content-Length: 38
Connection: close
Cookie: grocy_session=GhIjKZyST7Qkx18Q97u9MaPM1LsMtBmcJ6I59gxTO3Ks4WJXUd
{"name":"<marquee onstart=alert(1)> "}

**Comment by berrnd** [comment]
Merged #991 into this.

**Comment by fipwmaqzufheoxq92ebc** [comment]
I can reproduce this also on: users, batteries, chores, equipment, locations, quantity units, shopping locations, tasks, taskcategories, product groups, recipes

(For all: add an item named `<marquee onstart=alert(document.cookie)> `, save and try to delete it)

**Comment by fipwmaqzufheoxq92ebc** [comment]
via API or JS-Console:
`Grocy.Api.Put('objects/shopping_lists/1', {"description":" <marquee onstart=alert(document.cookie)> "})`
and then open the shopping list
or
`Grocy.Api.Put('objects/recipes/2', {"description":" <marquee onstart=alert(document.cookie)> "})`
and then open the recipe (in recipes list or in recipe form)

Create a userfield, e.g. for products, use USERFIELD_TYPE_PRESET_CHECKLIST ( = "Select list (multiple items can be selected)"), add `<marquee onstart=alert(document.cookie)>` as value, choose "Show in tables", and then edit any product, check the field, and open the stockoverview

**Comment by berrnd** [comment]
I fixed some parts of the mentioned places, see the referenced commits above. Maybe filtering the input before saving it (so mostly in the "Generic entity interactions" API routes") would be better...

Just to note that also here:
I don't consider this too critical for grocy, this cannot be done unauthenticated, grocy is not a application you (should) host publicly (means without authentication) on the internet.

**Comment by berrnd** [comment]
I think this should now be resolved, I've added fiiltering of the whole request body for all API routes in https://github.com/grocy/grocy/commit/c11001467b4dca3ab02143fdbee65f65836c3882.

Feel free to play around with it on the [pre-release demo](https://demo-prerelease.grocy.info) and let me know here if you find any other/leftover places where this is still possible.

**Comment by kriddles** [comment]
> I think this should now be resolved, I've added fiiltering of the whole request body for all API routes in [c110014](https://github.com/grocy/grocy/commit/c11001467b4dca3ab02143fdbee65f65836c3882).
> 
> Feel free to play around with it on the [pre-release demo](https://demo-prerelease.grocy.info) and let me know here if you find any other/leftover places where this is still possible.

Not sure if it's related but on the pre-release demo I cannot edit stock entries anymore.

**Comment by berrnd** [comment]
> Not sure if it's related but on the pre-release demo I cannot edit stock entries anymore.

Maybe, I added to use [htmlpurifier](https://github.com/ezyang/htmlpurifier) to just filter all request body properties ([code ref](https://github.com/grocy/grocy/blob/56d79d7db88f3a939f7124298fd0ee6ec4804af1/controllers/BaseApiController.php#L121-L135)), so maybe this breaks/removes something which is not "bad HTML"...

Moved this to #1055.
