### ISSUE TITLE
Dark Mode text hard to read

### ISSUE THREAD

**Issue by yarons** [grocy/grocy#999]
<img width="1186" alt="Screen Shot 2020-09-12 at 15 15 32" src="https://user-images.githubusercontent.com/406826/92995301-f8bf8300-f50a-11ea-956c-0dd3ccbe3a55.png">

I think making the text a little brighter will ease on the eye.

**Comment by berrnd** [comment]
All night-mode related styling is done in [grocy_night_mode.css](https://github.com/grocy/grocy/blob/master/public/css/grocy_night_mode.css), feel free to tweak it.
